docs/content/tutorial/saving-your-data.mdx, examples/docs_snippets/docs_snippets/tutorial/saving/add_db_io_manager.py
Uses the new Pythonic DuckDB io manager in our tutorial.
=> [docs] Update use of resources in new tutorial

docs/content/concepts/configuration/configured.mdx, docs/content/guides/dagster/using-environment-variables-and-secrets.mdx, examples/docs_snippets/docs_snippets/guides/dagster/using_environment_variables_and_secrets/repository.py, examples/docs_snippets/docs_snippets/guides/dagster/using_environment_variables_and_secrets/repository_v2.py
Updates the "env vars and secrets" page
=> [docs][pythonic config] Update env vars and secrets docs

CHANGES.md
https://github.com/dagster-io/dagster/blob/yuhan/04-18-1.3.0_changelog/CHANGES.md
=> 1.3.0 changelog

docs/content/_navigation.json, docs/content/guides/dagster/migrating-to-pythonic-resources-and-config.mdx, docs/content/guides/general.mdx, examples/docs_snippets/docs_snippets/guides/dagster/migrating_to_python_resources_and_config/migrating_config.py, examples/docs_snippets/docs_snippets/guides/dagster/migrating_to_python_resources_and_config/migrating_resources.py, examples/docs_snippets/docs_snippets_tests/guides_tests/migrating_to_python_resources_and_config_tests/test_migrating_config.py, examples/docs_snippets/docs_snippets_tests/guides_tests/migrating_to_python_resources_and_config_tests/test_migrating_resources.py
This is a migration guide for moving from legacy resources and config to Pythonic resources and config.
Read
=> Migration guide for Pythonic Resources and Config

docs/next/.versioned_content/_versioned_navigation.json
step 4 in https://github.com/dagster-io/dagster/pull/13786
preview
=> backfill 1.3.0 sidenav

js_modules/dagit/packages/core/src/assets/Stale.tsx
=> [dagit] Switch stale cause asset references to a monospace font

docs/sphinx/sections/api/apidocs/libraries/dagster-duckdb.rst, python_modules/libraries/dagster-duckdb/dagster_duckdb/__init__.py, python_modules/libraries/dagster-duckdb/dagster_duckdb/resource.py, python_modules/libraries/dagster-duckdb/dagster_duckdb_tests/test_resource.py, python_modules/libraries/dagster-duckdb/tox.ini
Adds a duckdb resource
new tests
=> [dagster-duckdb] duckdb resource

docs/content/guides/dagster/software-defined-assets.mdx, examples/assets_pandas_pyspark/README.md, examples/assets_pandas_pyspark/assets_pandas_pyspark/__init__.py, examples/assets_pandas_pyspark/assets_pandas_pyspark/local_filesystem_io_manager.py, examples/assets_pandas_pyspark/assets_pandas_pyspark/local_spark_filesystem_io_manager.py
converts custom io managers to pythonic config (there isn't any configuration though, so it's just changing the parent class)
ran locally
=> [assets_pandas_pyspark] Upgrade to pythonic config

python_modules/dagster-test/dagster_test/toys/auto_materializing/repo_1.py, python_modules/dagster-test/dagster_test/toys/auto_materializing/repo_2.py, python_modules/dagster-test/dagster_test/toys/repo.py
Some basic examples to play with
=> Add AutoMaterializePolicies to toys

python_modules/dagster-test/dagster_test/toys/data_versions.py
=> fix data_versions toy

js_modules/dagit/packages/core/src/graphql/schema.graphql, js_modules/dagit/packages/core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster-graphql/dagster_graphql/schema/auto_materialize_policy.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py, python_modules/dagster/dagster/_core/definitions/auto_materialize_policy.py, python_modules/dagster/dagster_tests/definitions_tests/test_auto_materialize_policy.py
Initial backend for https://github.com/dagster-io/dagster/issues/13446
=> Add auto materialize policy to gql

python_modules/dagster/dagster/_core/telemetry.py, python_modules/dagster/dagster_tests/cli_tests/command_tests/test_telemetry.py
Closes https://github.com/dagster-io/dagster/issues/13756
=> Add auto materialize policy to telemetry

python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_decorators.py
=> [AutoMaterializePolicy] Add ability to specify an AutoMaterializePolicy for graph-backed assets

python_modules/libraries/dagster-postgres/dagster_postgres/event_log/event_log.py
Our base sql event log implementation inserts dynamic partitions by first finding existing ones and then inserting only new ones.
Generally, this is fine. But if you try to create a lot of dynamic partitions in a single call and a lot of the dynamic partitions already exist, there's a lot of overhead in pulling such a large list into memory.
SQLAlchemy doesn't have a generalized abstraction for insert if not exist but it does have dialect specific ones for certain dbs. This overloads `add_dynamic_partitions` for Postgres to push the behavior down to the db layer.
=> Push dynamic partition insert down to Postgres

js_modules/dagit/packages/core/src/hooks/usePortalSlot.tsx, js_modules/dagit/packages/core/src/runs/RunCreatedByCell.tsx, js_modules/dagit/packages/core/src/runs/RunsFilterInputNew.tsx, js_modules/dagit/packages/core/src/runs/RunsRootNew.tsx, js_modules/dagit/packages/core/src/ui/Filters/FilterDropdown.tsx, js_modules/dagit/packages/core/src/ui/Filters/__tests__/useStaticSetFilter.test.tsx, js_modules/dagit/packages/core/src/ui/Filters/__tests__/useSuggestionFilter.test.tsx, js_modules/dagit/packages/core/src/ui/Filters/__tests__/useTimeRangeFilter.test.tsx, js_modules/dagit/packages/core/src/ui/Filters/useFilter.tsx, js_modules/dagit/packages/core/src/ui/Filters/useSuggestionFilter.tsx
As titled, this clears the search bar whenever an entry is selected.
Jest
=> [Suggestion Filter] Reset search bar entry when selecting an entry

js_modules/dagit/packages/core/src/runs/RunTable.tsx, js_modules/dagit/packages/core/src/runs/RunTableNew.tsx, js_modules/dagit/packages/core/src/schedules/ScheduleRoot.tsx, js_modules/dagit/packages/core/src/sensors/SensorPreviousRuns.tsx
=> Hide "created by" column in Schedule/Sensor Runs Table

python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py, python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
Helps with https://github.com/dagster-io/dagster/issues/10912
=> add get_step_failure_events to RunFailureSensorContext

python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py
=> Change CheckErrors for partition keys to DagsterInvariantViolationErrors

docs/content/_navigation.json, docs/content/dagster-cloud/managing-deployments/code-locations.mdx, docs/content/dagster-cloud/managing-deployments/dagster-cloud-yaml.mdx
=> New PR for dagster_cloud.yaml

python_modules/dagster/dagster/_grpc/server.py, python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_grpc_server_registry.py
Summary:
Without this, if there's an exception constructing the object, there will be another exception in __del__ when it tries to access an attribute that does not exist
Buildkite
=> Initialize variables used in __del__ right away in GrpcServerProcess

python_modules/dagster/dagster/_core/definitions/schedule_definition.py, python_modules/dagster/dagster/_core/definitions/sensor_definition.py
https://github.com/dagster-io/dagster/issues/3794#issuecomment-1515714783
updates docstr, adds public decorator
=> Mark resources in schedule, sensor context as public

js_modules/dagit/packages/core/src/launchpad/LaunchpadHooksContext.tsx, js_modules/dagit/packages/core/src/runs/RunCreatedByCell.tsx, js_modules/dagit/packages/core/src/runs/RunTableNew.tsx, js_modules/dagit/packages/core/src/runs/RunsFilterInputNew.tsx, js_modules/dagit/packages/core/src/runs/RunsRootNew.tsx, js_modules/dagit/packages/core/src/runs/UserDisplay.tsx
1. Move countdown to the right
2. Move filters to the left
3. Smaller User icon in filters/row
=> Runs page filter tweaks

python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
to make debugging tests easier
eyes
=> add error to validate_tick assert

docs/content/_navigation.json, docs/content/guides.mdx, docs/content/guides/best-practices.mdx, docs/content/guides/experimental-features.mdx, docs/content/guides/general.mdx, docs/next/content_templates/file-reference-template.mdx
This PR re-organizes the content in the Guides category, updating relevant category pages and the sidenav. No redirects.
Builds on work in #12823
👀, local
=> [docs] - Update Guides category structure

python_modules/dagster-test/dagster_test/toys/partitioned_assets/__init__.py, python_modules/dagster-test/dagster_test/toys/partitioned_assets/dynamic_asset_partitions.py, python_modules/dagster-test/dagster_test/toys/partitioned_assets/partitioned_run_request_sensors.py, python_modules/dagster-test/dagster_test/toys/repo.py, python_modules/dagster-test/dagster_test_tests/toys_tests/partitioned_assets_tests/test_dynamic_asset_partitions.py, python_modules/dagster-test/dagster_test_tests/toys_tests/partitioned_assets_tests/test_sensors.py
Also tries to clean up the toys a bit, separating assets and sensors out into different files
=> Add sensors w/ partitioned run requests to toys 

docs/content/tutorial/next-steps.mdx
=> in tutorial "Next Steps" section, take out topics already covered by the tutorial

python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py, python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
Fixes the failure in this build: https://buildkite.com/dagster/dagster/builds/57290#0187be37-cff0-439a-8778-8ac9f212e979/230-444
```
pytest ./python_modules/dagster/dagster_tests/daemon_sensor_tests/test_run_status_sensors.py::test_run_failure_sensor
```
=> fix test_run_failure_sensor

js_modules/dagit/packages/core/src/graphql/schema.graphql, js_modules/dagit/packages/core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/schema/instigation.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/snapshots/snap_test_sensors.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py
Exposes dynamic partition requests via graphql when testing sensors
pytest
=> [1/2] Expose dynamic partition requests via GQL for DryRunInstigationTick

docs/content/dagster-cloud/managing-deployments/dagster-cloud-yaml.mdx, docs/content/guides/dagster/branch_deployments.mdx, examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/branch_deployments/clone_prod.yaml, examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/branch_deployments/drop_db_clone.yaml
was tested in a one of by shalabh
=> [docs] fix branch deployment location_name value

examples/assets_smoke_test/setup.py, examples/project_fully_featured/setup.py, python_modules/libraries/dagster-dbt/setup.py
=> [dagster-dbt] relax pin

python_modules/dagster/dagster/_config/pythonic_config/__init__.py, python_modules/libraries/dagster-dbt/dagster_dbt/asset_defs.py, python_modules/libraries/dagster-dbt/dagster_dbt/cloud/ops.py, python_modules/libraries/dagster-dbt/dagster_dbt/ops.py
Migrates `dagster-dbt` to use Pythonic config for ops. Stacks on #13816 which handles resources.
existing unit tests
=> [pythonic config][2/2] Update dbt ops to use Pythonic config

docs/content/integrations/dbt-cloud.mdx, docs/content/integrations/dbt/reference.mdx, docs/content/integrations/dbt/using-dbt-with-dagster/part-three.mdx, docs/content/integrations/dbt/using-dbt-with-dagster/part-two.mdx, examples/docs_snippets/docs_snippets/integrations/dbt/dbt.py, examples/docs_snippets/docs_snippets/integrations/dbt/dbt_cloud.py, examples/docs_snippets/docs_snippets_tests/integrations_tests/test_dbt.py, examples/project_fully_featured/project_fully_featured/resources/__init__.py, examples/tutorial_dbt_dagster/tutorial_finished/tutorial_dbt_dagster/__init__.py
Updates the DBT guides to use the new DBT resource classes
=> [docs] Update dbt integration docs to use migrated resources

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py, python_modules/libraries/dagster-ge/dagster_ge_tests/snapshots/snap_test_basic_integ.py, python_modules/libraries/dagster-ge/setup.py
summary:
- update snapshots
- remove py311 testing (ge does not claim to have py311 support)
=> fix dagster-ge tests

js_modules/dagit/packages/core/src/runs/RunTableNew.tsx
=> [Runs Table] Add a "Re-execution" tag to runs that are re-executed

js_modules/dagit/packages/core/src/runs/RunsFilterInputNew.tsx
=> [Runs Filtering] Show long filter tags on hover

js_modules/dagit/packages/core/src/assets/AssetView.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/AssetAutomaterializePolicyPage.tsx
=> [Auto-materialize Policy page] Add initial page design with mock data

python_modules/libraries/dagster-gcp/dagster_gcp/gcs/__init__.py, python_modules/libraries/dagster-gcp/dagster_gcp/gcs/gcs_fake_resource.py, python_modules/libraries/dagster-gcp/dagster_gcp/gcs/io_manager.py, python_modules/libraries/dagster-gcp/dagster_gcp/gcs/resources.py, python_modules/libraries/dagster-gcp/dagster_gcp_tests/gcs_tests/test_io_manager.py, python_modules/libraries/dagster-gcp/dagster_gcp_tests/gcs_tests/test_resources.py
Updates GCS Resource and IO Manager to use pydantic config
=> [dagster-gcp] Convert GCS to pythonic config and resources

python_modules/libraries/dagster-ge/dagster_ge_tests/great_expectations/expectations/.ge_store_backend_id, python_modules/libraries/dagster-ge/dagster_ge_tests/snapshots/snap_test_basic_integ.py, python_modules/libraries/dagster-ge/setup.py, python_modules/libraries/dagstermill/setup.py
=> Pin ipython<8.13 for python 3.8

python_modules/libraries/dagster-databricks/dagster_databricks/__init__.py, python_modules/libraries/dagster-databricks/dagster_databricks/ops.py, python_modules/libraries/dagster-databricks/dagster_databricks/resources.py, python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_ops.py
Updates the Databricks client resource and ops to use Pythonic config and resources.
Does not update the step launcher yet - not sure the proper way to handle this case. Leaving this open for discussion.
Updated unit tests.
=> [pythonic resources] Update dagster-databricks

python_modules/dagster/dagster/_daemon/sensor.py, python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
The dynamic partitions instance methods are idempotent:
- Calling `add_dynamic_partitions` will ignore partitions that already exist
- Calling `delete_dynamic_partition` for a partition that does not exist is a no-op
Prior to this PR, we called `add_dynamic_partitions` and `delete_dynamic_partition` for whichever dynamic partitions requests we received and generated log messages for those changes.
This PR updates the daemon to skip partitions that we do not need to write, which occurs when:
- A partition in `AddDynamicPartitionsRequest` already exists
- A partition in `DeleteDynamicPartitionsRequest` does not exist
We also now log the skipped partitions.
=> [dynamic partitions requests in tick 1/3] Update logging to handle existent partitions

docs/content/concepts/partitions-schedules-sensors/backfills.mdx, examples/docs_snippets/docs_snippets/concepts/partitions_schedules_sensors/backfills/single_run_backfill_asset.py, examples/docs_snippets/docs_snippets/concepts/partitions_schedules_sensors/backfills/single_run_backfill_io_manager.py, examples/docs_snippets/docs_snippets_tests/concepts_tests/partitions_schedules_sensors_tests/backfills_tests/test_single_run_backfill_asset.py, examples/docs_snippets/docs_snippets_tests/concepts_tests/partitions_schedules_sensors_tests/backfills_tests/test_single_run_backfill_io_manager.py
=> docs for single-run range backfills

python_modules/libraries/dagster-mlflow/dagster_mlflow/resources.py
=> remove use of solids in mlflow api docs

docs/content/concepts/ops-jobs-graphs/op-events.mdx
=> in asset materializations section of op events page, mention sdas

python_modules/libraries/dagster-dbt/dagster_dbt_tests/conftest.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_defs.py
https://github.com/dagster-io/dagster/issues/14057
=> fix flaky dbt test

CHANGES.md
https://github.com/dagster-io/dagster/blob/yuhan/05-03-1.3.3_changelog/CHANGES.md
=> 1.3.3 changelog

python_modules/libraries/dagster-azure/dagster_azure/adls2/__init__.py, python_modules/libraries/dagster-azure/dagster_azure/adls2/fake_adls2_resource.py, python_modules/libraries/dagster-azure/dagster_azure/adls2/io_manager.py, python_modules/libraries/dagster-azure/dagster_azure/adls2/resources.py, python_modules/libraries/dagster-azure/dagster_azure/adls2/utils.py, python_modules/libraries/dagster-azure/dagster_azure/blob/utils.py, python_modules/libraries/dagster-azure/dagster_azure_tests/adls2_tests/test_adls2_file_manager.py, python_modules/libraries/dagster-azure/dagster_azure_tests/adls2_tests/test_io_manager.py
Migrates the `dagster-azure` IO manager & resources over to Pythonic resource format.
New unit tests + existing tests.
=> [dagster-azure] Migrate resources, IO manager

docs/content/integrations/bigquery/reference.mdx, docs/content/integrations/bigquery/using-bigquery-with-dagster.mdx, docs/content/integrations/snowflake/reference.mdx, docs/content/integrations/snowflake/using-snowflake-with-dagster.mdx, examples/docs_snippets/docs_snippets/integrations/bigquery/full_example.py, examples/docs_snippets/docs_snippets/integrations/bigquery/load_downstream.py, examples/docs_snippets/docs_snippets/integrations/snowflake/full_example.py, examples/docs_snippets/docs_snippets/integrations/snowflake/load_downstream.py, examples/docs_snippets/docs_snippets/integrations/snowflake/private_key_auth_file.py
when writing the duckdb tutorial i noticed a bunch of places where the snowflake and bigquery tutorials/references had gotten out of date. This fixes them
=> [docs] fix inconsistencies in snowflake and bigquery guides

integration_tests/test_suites/backcompat-test-suite/dagit_service/pins.txt
https://github.com/dagster-io/dagster/pull/14089 but to get our backcompat tests passing.
=> Pin urllib3 for backcompat tests

python_modules/dagster/dagster/_core/definitions/asset_in.py, python_modules/dagster/dagster/_core/definitions/asset_out.py, python_modules/dagster/dagster/_core/definitions/asset_selection.py, python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/events.py, python_modules/dagster/dagster/_core/definitions/source_asset.py, python_modules/dagster/dagster/_core/execution/context/input.py, python_modules/dagster/dagster/_core/execution/context/output.py, python_modules/dagster/dagster/_core/execution/execute_in_process_result.py, python_modules/dagster/dagster/_core/storage/asset_value_loader.py, python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/asset_reconciliation_scenario.py, python_modules/dagster/dagster_tests/storage_tests/branching_io_manager_tests/utils.py
=> coerceable -> coercible

docs/content/integrations/dbt-cloud.mdx, examples/docs_snippets/docs_snippets/integrations/dbt/dbt_cloud.py, examples/docs_snippets/docs_snippets_tests/integrations_tests/test_dbt.py
Fixing incorrect code example in dbt cloud docs
Read and added test
=> EnvVar --> EnvVar.int in dbt code example

python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster/_core/storage/event_log/base.py, python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py, python_modules/dagster/dagster/_core/storage/legacy_storage.py, python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
Test Plan: To support getting the last N events for a given run.
Test Plan: BK
=> Add ascending arg to get_records_for_run

python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
Closes https://github.com/dagster-io/dagster/issues/13843
=> Fix failed partition counts with in progress overlap

js_modules/dagit/packages/core/src/app/Flags.tsx, js_modules/dagit/packages/core/src/app/getVisibleFeatureFlagRows.tsx, js_modules/dagit/packages/core/src/graph/SVGViewport.tsx
Feedback has been very positive about the new "scroll / scroll wheel to pan" behavior on the DAG viz and we're going to switch it on this week for everyone.
The new behavior is:
Trackpad:
- Scroll to pan
- Command-scroll to zoom
Mouse:
- Mouse wheel to scroll vertically
- Shift mouse wheel to scroll horizontally
- Command-wheel to zoom
I ran dagit after making these changes to verify I'd deleted the correct branch of the if/else 🤔
=> [ui] Remove feature flag, default to “scroll to pan” on DAG viz

python_modules/dagster/dagster/_core/definitions/run_request.py, python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
Reported by a user: https://dagster.slack.com/archives/C01U954MEER/p1683218607008819
If you have a multipartitioned asset with a dynamic partitions dimension, yielding a sensor result with a dynamic partitions request along with a partitioned run request for a multipartitions key with that new dynamic partition for the dynamic dimension, this currently fails. 
This is because we currently validate the set of dynamic partition keys after requests only when the partitions definition is a dynamic partitions definition. This PR extends this logic to apply to multipartitions definitions too.
=> Fix yielding run request in sensor result for multipartitioned asset w/ dynamic dimension

js_modules/dagit/packages/core/src/pipelines/GraphNotices.tsx
Resolves #14160.
Load an empty job, view it in UI.
=> [ui] Clean up old "pipeline" copy

python_modules/dagster-graphql/dagster_graphql/schema/instigation.py
Error from datadog: https://app.datadoghq.com/apm/trace/316573255363055180?spanID=1393001358924365529&spanViewType=errors
The likely cause of this error is that the user code version is older than the dagster cloud version, so the returned sensor execution data object doesn't contain a dynamic partitions requests field. Subsequently we need to add a check in graphQL to handle this field being `None`.
=> Fix sensor dry run dynamic partitions requests error

js_modules/dagit/packages/app/src/index.tsx
=> Revert back to React 17 (legacy mode)

python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
This is a follow up of https://github.com/dagster-io/dagster/pull/14155
=> update docs for TimeWindowPartitionsDefinition

js_modules/dagit/packages/core/src/gantt/GanttChart.tsx
Reimplement Gantt chart animation to use `requestAnimationFrame`. Hopefully this helps resolve some of the weird animation loop issues we currently see.
Kick off some runs, verify that the Gantt chart animates smoothly. Use the React profiler to ensure that it's not too expensive to use rAF for this.
I should check this on some heavy jobs with lots of concurrent steps, and I could use some help hammering away at this to make sure everything works as expected even in edge cases.
=> [ui] Reimplement Gantt animation loop

js_modules/dagit/packages/core/src/workers/dagre_layout.worker.ts
This is a small regression from https://github.com/dagster-io/dagster/commit/770b73b98b6d107b7d9f287f99e905b64b5d43ba#diff-fbe12ed550f699366fbfc8dde7f98e1edc596ca64652ea4b73c954d4ae291aaeL18
=> [ui] Fix reference to window in webworker

docs/content/dagster-cloud/managing-deployments/dagster-cloud-yaml.mdx
Fixing error in dagster_cloud.yaml guide
=> Fixing python_executable with executable path

.github/CODEOWNERS
I only want to be the master of docs, not the master of all. Trying to correct this 😭
Forked this repo into my personal account and tested it there - it seemed to work! 🤞
=> Deactivate the trap card

.buildkite/dagster-buildkite/dagster_buildkite/pipelines/dagster_oss_main.py
I'm working on producing a lot more signal from our oss-internal-compatibility Buildkite builds because it's come to my attention that it has a painfully low success rate.
I suspect most issues are just because of a lack of hardening around how Buildkite finds the right combination of OSS and internal code to test.
One category of frequent failures I noticed is on external PRs. Our internal build doesn't know how to find the remote origin for the contributor's PR. Consequently, the build always fails with something along the lines of:
```
warning: Could not find remote branch pull/14200/head to clone.
```
https://buildkite.com/dagster/oss-internal-compatibility/builds/27811
For now, let's just not run these builds at all for external contributions.
=> Don't trigger compatbility build from external PRs

docs/content/dagster-cloud/deployment/agents/amazon-ecs/configuration-reference.mdx
Brings docs in line with this change https://github.com/dagster-io/internal/pull/2614
👁️
=> ecs agent can support multiple deployments

CHANGES.md
=> 1.3.4 Changelog

js_modules/dagit/packages/core/src/runs/RunListTabs.new.tsx
As titled, instead of showing DONE we want to show FAILED
=> [Runs Page] Change "Done" tab to "Failed"

python_modules/dagster/dagster/_cli/api.py, python_modules/dagster/dagster/_grpc/server.py, python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_persistent.py
Summary:
This has not been used for a very long time.
Test Plan: BK
=> Remove ipc-output-file from dagster api grpc

python_modules/dagster/dagster/_core/definitions/time_window_partition_mapping.py
Would have made: https://dagster.slack.com/archives/C01U954MEER/p1683820517410289 easier to debug
=> more informative error message when cron schedule does not match in TimeWindowPartitionMapping

js_modules/dagit/packages/core/src/overview/OverviewAssetsRoot.tsx
=> [Assets Overview] Fix counting in progress materializing assets

python_modules/dagster/dagster/_cli/api.py, python_modules/dagster/dagster/_grpc/server.py, python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_ping.py
Summary:
This paves the way for a separate proxy server entry point that still uses the DagsterGrpcServer entrypoint but with a different implementer of the api interface. No functionality changes yet.
=> Move DagsterApiServer to an input variable to DagsterGrpcServer instead of constructed within it

js_modules/dagit/packages/core/src/asset-graph/AssetNode.tsx, js_modules/dagit/packages/core/src/overview/OverviewAssetsRoot.tsx
=> Show number of missing/failed/materialized partitions in asset overview page dialog

js_modules/dagit/packages/app/package.json, js_modules/dagit/packages/core/package.json, js_modules/dagit/packages/core/src/nav/__tests__/LeftNavRepositorySection.test.tsx, js_modules/dagit/packages/core/src/nav/__tests__/useRepositoryLocationReload.test.tsx, js_modules/dagit/packages/ui/package.json, js_modules/dagit/packages/ui/src/components/__tests__/actWarnings.test.tsx, js_modules/dagit/yarn.lock
Update testing-library dependencies to try to eliminate some of the `act` warnings that have appeared in the last week or two.
ts, lint, jest
=> [ui] Update testing-library/dom

python_modules/dagster/dagster/_core/storage/schedules/schema.py, python_modules/dagster/dagster/_core/storage/schedules/sql_schedule_storage.py
Missed adding this, got caught it a cloud test
Also rename the python object for the table
=> Wipe asset_daemon_asset_evaluations table

python_modules/dagster/dagster/_core/definitions/asset_reconciliation_sensor.py, python_modules/dagster/dagster/_utils/test/schedule_storage.py
=> Revert "Revert "Change AutoMaterializeAssetEvaluation to store serialized subsets (#14295)""

python_modules/libraries/dagster-snowflake/dagster_snowflake/resources.py
fixes an error in the SnowflakeResource docstring
=> [docs] fix snowflake resource docstring

docs/content/_navigation.json, docs/content/integrations.mdx, docs/content/integrations/duckdb.mdx, docs/content/integrations/duckdb/reference.mdx, docs/content/integrations/duckdb/using-duckdb-with-dagster.mdx, docs/sphinx/sections/api/apidocs/libraries/dagster-duckdb-pandas.rst, docs/sphinx/sections/api/apidocs/libraries/dagster-duckdb-polars.rst, docs/sphinx/sections/api/apidocs/libraries/dagster-duckdb-pyspark.rst, docs/sphinx/sections/api/apidocs/libraries/dagster-duckdb.rst, examples/docs_snippets/docs_snippets/integrations/duckdb/basic_example.py, examples/docs_snippets/docs_snippets/integrations/duckdb/configuration.py, examples/docs_snippets/docs_snippets/integrations/duckdb/downstream_columns.py, examples/docs_snippets/docs_snippets/integrations/duckdb/full_example.py, examples/docs_snippets/docs_snippets/integrations/duckdb/load_downstream.py, examples/docs_snippets/docs_snippets/integrations/duckdb/multi_partition.py, examples/docs_snippets/docs_snippets/integrations/duckdb/multiple_dataframe_types.py, examples/docs_snippets/docs_snippets/integrations/duckdb/multiple_io_managers.py, examples/docs_snippets/docs_snippets/integrations/duckdb/polars_configuration.py, examples/docs_snippets/docs_snippets/integrations/duckdb/pyspark_configuration.py, examples/docs_snippets/docs_snippets/integrations/duckdb/pyspark_with_spark_resource.py, examples/docs_snippets/docs_snippets/integrations/duckdb/pyspark_with_spark_session.py, examples/docs_snippets/docs_snippets/integrations/duckdb/resource.py, examples/docs_snippets/docs_snippets/integrations/duckdb/schema.py, examples/docs_snippets/docs_snippets/integrations/duckdb/source_asset.py, examples/docs_snippets/docs_snippets/integrations/duckdb/static_partition.py, examples/docs_snippets/docs_snippets/integrations/duckdb/time_partition.py
Adds tutorial and guide for duckdb 
resolves #14036
=> [docs] duckdb guide and reference

CHANGES.md
=> docs: add 1.3.5 changelog

python_modules/dagster-graphql/dagster_graphql/schema/auto_materialize_asset_evaluations.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_auto_materialize_asset_evaluations.py, python_modules/dagster/dagster/_core/definitions/asset_reconciliation_sensor.py, python_modules/dagster/dagster/_utils/test/schedule_storage.py
=> Refactor AutoMaterializeAssetEvaluation conditions type

js_modules/dagit/packages/core/src/app/__tests__/AppTopNav.test.tsx, js_modules/dagit/packages/core/src/app/__tests__/CustomConfirmationProvider.test.tsx, js_modules/dagit/packages/core/src/app/__tests__/analytics.test.tsx, js_modules/dagit/packages/core/src/assets/__tests__/AssetPartitions.test.tsx, js_modules/dagit/packages/core/src/assets/__tests__/AssetView.test.tsx, js_modules/dagit/packages/core/src/assets/__tests__/LaunchAssetExecutionButton.test.tsx, js_modules/dagit/packages/core/src/hooks/__tests__/useQueryPersistedState.test.tsx, js_modules/dagit/packages/core/src/instance/__tests__/BackfillTable.test.tsx, js_modules/dagit/packages/core/src/instance/__tests__/DaemonList.test.tsx, js_modules/dagit/packages/core/src/instance/backfill/__tests__/BackfillPage.test.tsx, js_modules/dagit/packages/core/src/nav/__tests__/LeftNavRepositorySection.test.tsx, js_modules/dagit/packages/core/src/nav/__tests__/VersionNumber.test.tsx, js_modules/dagit/packages/core/src/partitions/__tests__/CreatePartitionDialog.test.tsx, js_modules/dagit/packages/core/src/pipelines/__tests__/PipelineRoot.test.tsx, js_modules/dagit/packages/core/src/runs/__tests__/AssetKeyTagCollection.test.tsx, js_modules/dagit/packages/core/src/runs/__tests__/RunActionsMenu.test.tsx, js_modules/dagit/packages/core/src/runs/__tests__/RunFilterInput.test.tsx, js_modules/dagit/packages/core/src/ticks/__tests__/DryRunRequestTable.test.tsx, js_modules/dagit/packages/core/src/ticks/__tests__/EvaluateScheduleDialog.test.tsx, js_modules/dagit/packages/core/src/ticks/__tests__/SensorDryRunDialog.test.tsx, js_modules/dagit/packages/core/src/ui/Filters/__tests__/FilterDropdown.test.tsx, js_modules/dagit/packages/core/src/ui/Filters/__tests__/useSuggestionFilter.test.tsx, js_modules/dagit/packages/core/src/ui/Filters/__tests__/useTimeRangeFilter.test.tsx, js_modules/dagit/packages/core/src/ui/__tests__/useRepoExpansionState.test.tsx
Clean up some tests in `packages/core`, especially with regard to `act`, events, and awaits.
Buildkite
=> [ui] Clean up some tests

python_modules/libraries/dagster-k8s/dagster_k8s/client.py, python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_client.py
Summary:
Retrying and getting a 409 after getting a 500 after creating a k8s job indicates that the job was actually created after all - so allow it through.
Test Plan: BK
=> Keep going if you get a 409 Conflict after retrying creating a k8s job

docs/content/concepts/partitions-schedules-sensors/sensors.mdx, examples/docs_snippets/docs_snippets/concepts/partitions_schedules_sensors/sensors/sensors.py
Found a stray `config_schema` in the docs
=> [docs] Update sensor page to use Config

examples/tutorial_dbt_dagster/tutorial_finished/tutorial_dbt_dagster/__init__.py
Very brief IO manager update to use new Pythonic IO manager
=> [examples][pythonic resources] Update tutorial_dbt_dagster

examples/deploy_docker/from_source/repo.py, examples/deploy_docker/repo.py, examples/project_fully_featured/project_fully_featured_tests/test_core.py, python_modules/libraries/dagster-pandas/dagster_pandas/examples/__init__.py, python_modules/libraries/dagstermill/dagstermill/examples/repository.py
Small updates to a bunch of examples to use the Pythonic version of the filesystem IO manager
=> [examples][pythonic_resources] Update various examples relying on fs_io_manager

js_modules/dagit/packages/app/src/index.tsx
Concurrent mode Is causing all sorts of issues atm
=> Revert back to React 17 legacy mode.

python_modules/dagster-test/dagster_test/toys/asset_sensors.py, python_modules/dagster-test/dagster_test_tests/toys_tests/test_asset_sensors.py
Fixed an issue with the multi asset sensor last week, hoping to dogfood this in cloud for this week's release
=> Add partitioned multi asset sensor toy

examples/assets_dbt_python/assets_dbt_python/__init__.py
Small update to use Pythonic resources
=> [examples][pythonic resources] Update assets-dbt-python

examples/assets_modern_data_stack/assets_modern_data_stack/__init__.py, examples/assets_modern_data_stack/assets_modern_data_stack/db_io_manager.py
Updates the I/O manager definition and resources to use Pythonic resources
=> [examples][pythonic resources] Update assets_modern_data_stack

helm/dagster/values.yaml
Summary:
This is in the schema but forgot to add it to the comments in the values.yaml
Test Plan: Inspect
=> Add comment to helm chart explaining numSubmitWorkers

python_modules/dagster-graphql/dagster_graphql/schema/auto_materialize_asset_evaluations.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_auto_materialize_asset_evaluations.py, python_modules/dagster/dagster/_core/definitions/asset_reconciliation_sensor.py, python_modules/dagster/dagster/_core/definitions/partition.py, python_modules/dagster/dagster/_utils/test/schedule_storage.py, python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/test_asset_reconciliation_sensor.py, python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/test_auto_materialize_asset_evaluation.py
https://elementl-workspace.slack.com/archives/C04UD72HHQX/p1684867150840489
=> Add SerializedPartitionsSubset namedtuple and use it for AutoMaterializeAssetEvaluations

python_modules/dagster-graphql/dagster_graphql/client/client.py, python_modules/dagster-graphql/dagster_graphql_tests/client_tests/test_submit_pipeline_execution.py
=> Allow RunConfig class to be passed into graphql client

python_modules/dagster/dagster/_daemon/asset_daemon.py
Now that we disabled in the release branch, re-enable in master
=> Revert "Don't log evaluations in asset daemon (#14430)"

python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py
=> docs(fivetran): fix api string argument

js_modules/dagit/packages/core/src/graphql/schema.graphql, js_modules/dagit/packages/core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/schema/auto_materialize_policy.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
=> Add maxMaterializationsPerMinute to gql auto materialize policy

examples/experimental/tutorial_dbt_dagster_v2/README.md, examples/experimental/tutorial_dbt_dagster_v2/setup.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/__init__.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/__init__.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/build.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/customize_asset_keys.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/partitions.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/runtime_metadata.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/seed_run_test.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/separate_asset_defs.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/use_artifacts.py
=> refactor(dbt-assets): use DbtManifest.read

js_modules/dagit/packages/core/src/assets/__tests__/AssetView.test.tsx
This is causing my build to fail on https://github.com/dagster-io/dagster/pull/14478
=> Disable eslint rule for skipped tests

python_modules/dagster/dagster/_core/definitions/asset_graph.py, python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/multi_dimensional_partitions.py, python_modules/dagster/dagster/_core/definitions/partitioned_schedule.py, python_modules/dagster/dagster/_core/definitions/time_window_partitions.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_decorators.py, python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py, python_modules/dagster/dagster_tests/core_tests/test_op_invocation.py, python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/exotic_partition_mapping_scenarios.py, python_modules/dagster/dagster_tests/definitions_tests/test_multi_partitions.py
Resolves https://github.com/dagster-io/dagster/issues/13248
**Test Plan**
- Tested locally by launching runs and backfills
- BK tests for asset backfills, asset reconciliation, unit tests
=> Enable multipartitioned assets to contain self dependencies

js_modules/dagit/packages/core/src/instance/backfill/BackfillPage.tsx
New status just dropped
Storybook
=> [Backfill Page] Support "canceling" status

python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py
Azure builds failing
azure pipelines
=> skip windows tests for sqlite conn path

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_runs.py
=> Delete test with no assert

js_modules/dagit/packages/core/src/app/time/TimezoneSelect.tsx
Older versions of Chrome don't support `Intl.supportedValuesOf`, which leads to an error on `TimezoneSelect`.
Fall back to only supporting the browser's local timezone and UTC in this case.
Throw an error from the try block, verify that the timezone select shows UTC and Automatic (CDT) and behaves properly when I choose one.
Sanity check that current behavior (with all timezones listed) is unchanged when the error is not thrown.
=> [ui] Handle Intl.supportedValuesOf error

docs/content/integrations/great-expectations.mdx, examples/with_great_expectations/with_great_expectations/__init__.py, examples/with_great_expectations/with_great_expectations/ge_demo.py, examples/with_great_expectations/with_great_expectations_tests/test_ge_example.py
`dagster dev` loads and run is green
=> [pythonic resources] update example with_great_expectations

examples/quickstart_aws/README.md, examples/quickstart_aws/quickstart_aws/__init__.py, examples/quickstart_aws/quickstart_aws/assets/hackernews.py
=> [pythonic resources] update example quickstart_aws

js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/AssetAutomaterializePolicyPage.tsx
This tooltip isn't being used atm.
=> Remove unused tooltip on auto-materialize policy page

js_modules/dagit/packages/core/src/nav/__fixtures__/LeftNavRepositorySection.fixtures.tsx, js_modules/dagit/packages/core/src/nav/__tests__/LeftNavRepositorySection.test.tsx
Cleaning up another notoriously flaky test, `LeftNavRepositorySection.test`.
ts, lint, jest
=> [ui] Clean up LeftNavRepositorySection.test

python_modules/dagster/dagster/_core/utils.py, python_modules/dagster/dagster/_daemon/run_coordinator/queued_run_coordinator_daemon.py, python_modules/dagster/dagster/_daemon/sensor.py, python_modules/dagster/dagster/_scheduler/scheduler.py, python_modules/dagster/dagster_tests/core_tests/test_utils.py
Add and use a ThreadPoolExecutor class that inherits the main threads contextvars at submission time. 
added test
=> [daemons] InheritContextThreadPoolExecutor

js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/AssetAutomaterializePolicyPage.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/__fixtures__/AutoMaterializePolicyPage.fixtures.ts, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/__stories__/AutoMaterializePolicyPage.stories.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/__tests__/getEvaluationsWithSkips.test.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/types/AssetAutomaterializePolicyPage.types.ts, js_modules/dagit/packages/core/src/assets/__fixtures__/AutoMaterializePolicyPage.fixtures.ts, python_modules/dagster-test/dagster_test/toys/auto_materializing/repo_1.py
As titled
Storybook + local testing + jest test
=> [Auto-materialize Policy page] Group skips

js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/AssetAutomaterializePolicyPage.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/__fixtures__/AutoMaterializePolicyPage.fixtures.ts, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/__stories__/AutoMaterializePolicyPage.stories.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/__tests__/getEvaluationsWithSkips.test.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/types/AssetAutomaterializePolicyPage.types.ts, js_modules/dagit/packages/core/src/graphql/schema.graphql, js_modules/dagit/packages/core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/implementation/fetch_auto_materialize_asset_evaluations.py, python_modules/dagster-graphql/dagster_graphql/schema/auto_materialize_asset_evaluations.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_auto_materialize_asset_evaluations.py, python_modules/dagster-test/dagster_test/toys/auto_materializing/repo_1.py, python_modules/dagster/dagster/_core/definitions/asset_reconciliation_sensor.py, python_modules/dagster/dagster/_daemon/asset_daemon.py, python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/test_asset_daemon_cursor.py
So we know how many evals have passed since the latest for a given asset
=> Current asset daemon evaluation id gql

python_modules/dagster/dagster/_core/workspace/context.py
Summary:
Fixes an issue where a background thread tried to send events to all state subscribes while a state subscriber was being added or removed.
Test Plan:
- start a grpc server and dagit, have a script that is reloading the gRPC Server every 5 seconds
- refresh the dagit page while the server is reloading
Before: Can induce this error:
```
│ Exception in thread grpc-server-watch:                                                                             ││ Traceback (most recent call last):                                                                                 │
│   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner                                      ││     self.run() …
```
=> Add a lock around the list of state subscribers in dagit

js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/AssetAutomaterializePolicyPage.tsx
=> Change text to Required to meet this asset's freshness policy

js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/AssetAutomaterializePolicyPage.tsx
=> Make skip conditions yellow

python_modules/libraries/dagster-dbt/dagster_dbt/__init__.py
As the title.
See warning when importing in local.
=> feat(dbt): deprecate dbt-rpc integration

js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/AssetAutomaterializePolicyPage.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/__tests__/getEvaluationsWithEmptyAdded.test.tsx
https://github.com/dagster-io/dagster/assets/22018973/1f5e7e1b-fe1a-4d84-94e1-277cd9448679
=> Make empty asset evaluation rows selectable

python_modules/dagster/dagster/_core/instance/config.py, python_modules/dagster/dagster/_daemon/monitoring/concurrency.py, python_modules/dagster/dagster_tests/daemon_tests/test_concurrency_daemon.py
=> rename setting to be more terse

python_modules/libraries/dagster-wandb/setup.py
`0.15.4` moved a file... pinning until we can fix.
BK
=> add pin for wandb

js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/AssetAutomaterializePolicyPage.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/__tests__/getEvaluationsWithEmptyAdded.test.tsx
Copy of https://github.com/dagster-io/dagster/pull/14653/, since that one got merged in to the stack and borked commits
=> Evaluations UI make empty evaluations selectable

docs/content/integrations/spark.mdx, examples/with_pyspark/with_pyspark/definitions.py, examples/with_pyspark/with_pyspark_tests/test_basic_pyspark.py, examples/with_pyspark_emr/with_pyspark_emr/definitions.py, examples/with_pyspark_emr/with_pyspark_emr_tests/test_emr_pyspark.py
=> move spark integration page to focus on assets

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
=> Remove unused method

python_modules/dagster/dagster/_core/definitions/decorators/sensor_decorator.py
Simply wires up existing functionality to the public API.
`python -m pytest python_modules/dagster/dagster_tests`
=> feat: support resources in asset and multi_asset sensors

python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/integration/test_managed_elements.py
https://buildkite.com/dagster/dagster/builds/60054#01889bbb-45c7-4503-900e-88d838598b16
I assume there's something happening in another container here that we need to wait for? @benpankow can you take a look when you get a chance?
=> Mark airbyte tests as flaky

python_modules/dagster/setup.py
alembic 1.11.1 patched some breaking changes: https://alembic.sqlalchemy.org/en/latest/changelog.html#change-1.11.1
https://github.com/dagster-io/dagster/issues/14708
BK
=> unpin alembic

python_modules/dagster/dagster/__init__.py, python_modules/dagster/dagster/_core/execution/context/compute.py
Went with a type alias to move things forward on discussing what to name it. Open to moving to more refined subclass in this PR or stacked one. 
Planning to stack call site updates.
eyes
=> add context type for @asset

docs/content/concepts/io-management/io-managers.mdx, docs/content/guides/dagster/migrating-to-pythonic-resources-and-config.mdx, docs/content/integrations/databricks.mdx, examples/docs_snippets/docs_snippets/concepts/io_management/loading_multiple_upstream_partitions.py, examples/docs_snippets/docs_snippets/guides/dagster/migrating_to_python_resources_and_config/migrating_config.py, examples/docs_snippets/docs_snippets/guides/dagster/migrating_to_python_resources_and_config/migrating_resources.py, examples/docs_snippets/docs_snippets/integrations/databricks/databricks.py, examples/quickstart_aws/quickstart_aws/assets/hackernews.py, examples/quickstart_etl/quickstart_etl/assets/hackernews.py, examples/quickstart_gcp/quickstart_gcp/assets/hackernews.py, examples/quickstart_snowflake/quickstart_snowflake/assets/hackernews.py, examples/with_wandb/with_wandb/assets/advanced_example.py, examples/with_wandb/with_wandb/assets/custom_serialization_example.py, examples/with_wandb/with_wandb/assets/model_registry_example.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py, python_modules/dagster/dagster/__init__.py, python_modules/dagster/dagster/_config/pythonic_config/attach_other_object_to_context.py, python_modules/dagster/dagster/_core/execution/context/compute.py, python_modules/dagster/dagster_tests/core_tests/resource_tests/pythonic_resources/test_general_pythonic_resources.py, python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py, python_modules/dagster/dagster_tests/execution_tests/test_data_versions.py, python_modules/dagster/dagster_tests/execution_tests/test_execute_job.py, python_modules/dagster/dagster_tests/storage_tests/test_upath_io_manager.py
used regex search `@asset[\w\W]*?context: OpExecutionContext` to find callsites 
bk
=> update callsites to use @asset context type

examples/quickstart_aws/quickstart_aws/assets/hackernews.py
=> [example] fix quickstart_aws post resource migration

js_modules/dagit/packages/core/src/app/CustomConfirmationProvider.tsx, js_modules/dagit/packages/core/src/runs/RunsFilterInput.tsx
Some changes got lost in https://github.com/dagster-io/dagster/pull/14633. This pr brings em back
=> [Runs] fix filtering by created date

js_modules/dagit/packages/core/src/assets/AssetView.tsx
=> Auto materialize policy -> history

python_modules/libraries/dagster-dbt/dagster_dbt/cli/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/cli/test_resources_v2.py
=> feat(dbt): add execution duration as default metadata on model materialization

python_modules/dagster-graphql/tox.ini
Summary:
These tests are timing out, add measurement to surface the slowest ones.
Test Plan: GK
=> Add top 10 slowest tests to graphql output

docs/content/dagster-cloud/getting-started.mdx
We're releasing a new CI/CD workflow for hybrid deployments. This updates to the relevant docs.
=> Update cloud docs for the new hybrid cicd workflow

python_modules/dagster/dagster/_core/execution/context/compute.py
=> rm SourceAssetObserveContext

CHANGES.md
=> Fix stray hashtag on 1.3.10 release

examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/__init__.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/build.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/customize_asset_keys.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/customize_description.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/partitions.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/runtime_metadata.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/seed_run_test.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/separate_asset_defs.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/use_artifacts.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/constants.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/jobs/yield_materializations.py
Show an example of using `DbtCli` if you are still using ops and jobs.
local
=> docs(dbt): add example to yield materializations in a job

examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/jobs/yield_materializations.py, python_modules/libraries/dagster-dbt/dagster_dbt/cli/resources_v2.py
Separating this out so that the initial example that's referenced in the RFC is working without needing to upgrade versions.
local
=> feat(dbt): add `get_asset_key_by_output_name`

python_modules/dagster-test/dagster_test/toys/auto_materializing/repo_1.py
=> Remove duplicate asset in toys

docs/sphinx/sections/api/apidocs/execution.rst, python_modules/dagster/dagster/_core/execution/context/compute.py, python_modules/dagster/dagster/_core/execution/context/system.py, python_modules/dagster/dagster/_core/execution/plan/compute.py, python_modules/dagster/dagster/_core/execution/plan/execute_step.py
Refine `AssetExecutionContext` to extend `OpExecutionContext` and set-up methods to be moved 
existing tests
=> make AssetExecutionContext subclass of OpExecutionContext

python_modules/libraries/dagster-dbt/dagster_dbt/cli/resources_v2.py
=> feat(dbt): represent project directory and target path as `pathlib.Path`

python_modules/libraries/dagster-airflow/setup.py
=> [dagster-airflow] pin airflow < 2.6.2

python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster/_core/storage/event_log/base.py, python_modules/dagster/dagster/_core/storage/legacy_storage.py, python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
=> Temporarily remove `get_latest_storage_id_by_partition`

python_modules/dagster-test/dagster_test/toys/auto_materializing/repo_1.py, python_modules/dagster-test/dagster_test/toys/auto_materializing/repo_2.py
=> add patitioned auto materialize assets to toys

python_modules/dagster-test/dagster_test/toys/auto_materializing/repo_1.py, python_modules/dagster-test/dagster_test/toys/auto_materializing/repo_2.py
=> toy assets actually use partitions def

docs/content/getting-started/telemetry.mdx
=> in telemetry docs, include an example telemetry blob

python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster/_core/storage/event_log/base.py, python_modules/dagster/dagster/_core/storage/legacy_storage.py, python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
This reverts commit 6a248398175b4774fdffc770e4b55f73234a5bf2.
=> Re-add get_latest_storage_id_by_partition

js_modules/dagit/packages/core/src/ui/Filters/FilterDropdown.tsx
press f key with modifiers, see filter dropdown not open
=> [Filters] Ignore modifiers when pressing "F" key

CHANGES.md
=> Update CHANGES.md spacing

python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
The test case was failing in cloud, because it was taking longer to terminate so the prior partition key was still in progress. Could wait for termination, but the tests cases where very similar so I condensed them.
=> Revert "Revert "Fix negative materialized count (#14901)""

python_modules/dagster/dagster/_cli/project.py, python_modules/dagster/dagster_tests/cli_tests/test_project_commands.py
One less decision for new users to make
=> make --name argument optional when scaffolding example

python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/asset_reconciliation_scenario.py
The current time does not always change in these scenarios, so use random instead.
=> Fix observable_source_asset_def for tests

python_modules/libraries/dagster-airbyte/dagster_airbyte/asset_defs.py, python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py
=> remove experimental marker from airbyte and fivetran apis

docs/sphinx/sections/api/apidocs/libraries/dagster-dbt.rst
=> tweak dbt docs link in dagster-dbt api docs

python_modules/dagster/dagster/_core/scheduler/instigation.py, python_modules/dagster/dagster/_scheduler/scheduler.py, python_modules/dagster/dagster_tests/scheduler_tests/conftest.py, python_modules/dagster/dagster_tests/scheduler_tests/simple_repo_one.py, python_modules/dagster/dagster_tests/scheduler_tests/simple_repo_two.py, python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py
https://github.com/dagster-io/dagster/issues/13597
BK
=> handle cron schedule changes

helm/dagster/schema/schema_tests/test_instance.py, helm/dagster/templates/helpers/instance/_compute-log-manager.tpl
Report that the verify flag was never being set to False
BK
=> fix helm bug for s3 compute log manager verify

js_modules/dagit/packages/core/src/pipelines/PipelineRunsRoot.tsx, js_modules/dagit/packages/core/src/runs/RunTable.tsx, js_modules/dagit/packages/core/src/runs/RunsFilterInput.tsx, js_modules/dagit/packages/core/src/runs/RunsRoot.tsx
Add created date filtering token types to the enabled filters + fix alignment on the active filter tags
before:
after:
=> [Job runs page] Fix alignment on filters + enable created date filtering

python_modules/dagster/dagster/_core/definitions/asset_reconciliation_sensor.py
Alternative fix for: https://github.com/dagster-io/dagster/pull/14962
This is a bandaid patch.
=> Avoid slow partition mapping when unnecessary

examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/runtime_metadata.py, python_modules/libraries/dagster-dbt/dagster_dbt/cli/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/cli/test_resources_v2.py
Make this consistent with `raw_manifest`.
existing bk
=> refactor(dbt): rename underlying dbt json log as `raw_event`

docs/content/guides/limiting-concurrency-in-data-pipelines.mdx, examples/docs_snippets/docs_snippets/concepts/ops_jobs_graphs/job_execution.py, python_modules/dagster/dagster/_cli/instance.py
Have something to point users towards in terms of limiting global op concurrency.
BK, inspection
=> concurrency docs

CHANGES.md
=> 1.3.12 Changelog

docs/content/tutorial/setup.mdx
Current tutorial scaffolding command is wrong, this fixes it.
Ran command.
=> Fix: my-tutorial-project -> tutorial-project

docs/content/integrations.mdx
Making a PR under here to circumnavigate the whole forking, git heads, and vercel deploy stuff.
@danielgafni 
https://github.com/dagster-io/dagster/pull/14981/files
=> Adding dagster-polars to the docs

js_modules/dagit/packages/core/src/ui/Filters/__tests__/useTimeRangeFilter.test.tsx
We removed this prop in https://github.com/dagster-io/dagster/pull/15011
jest
=> Update TimeRangeFilter test

python_modules/dagster-graphql/dagster_graphql_tests/graphql/graphql_context_test_suite.py, python_modules/dagster/dagster/_core/storage/event_log/sqlite/sqlite_event_log.py
We sometimes see flakes in these tests presumably because of a race condition on setup:
https://buildkite.com/dagster/dagster/builds/60833
=> Suppress flaky fixture cleanup

examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/__init__.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/build.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/customize_asset_keys.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/customize_description.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/dependencies.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/partitions.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/runtime_metadata.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/seed_run_test.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/separate_asset_defs.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/use_artifacts.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/jobs/yield_materializations.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/schedules/define_schedules.py, python_modules/libraries/dagster-dbt/dagster_dbt/__init__.py, python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt/cli/__init__.py, python_modules/libraries/dagster-dbt/dagster_dbt/cli/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/cli/test_resources_v2.py
As the title. Refactor examples and docstrings to import from API's from the top level as well.
existing bk
=> feat(dbt): export experimental API's at the top level

python_modules/libraries/dagster-dbt/dagster_dbt/cli/resources_v2.py
=> docs(dbt): add docstrings and examples for experimental API

js_modules/dagit/packages/ui/src/components/Text.tsx
Not modifying any existing styles, but adding styles that are missing based on this figma:
https://www.figma.com/file/AhZwBSolIwuvHwg5gIRELn/Dagster-UI-Component-Library?node-id=6%3A120&mode=dev
👀
=> [Text] Update text styles based off figma

docs/content/deployment/run-coordinator.mdx
=> [docs] - Fix link in Run Coordinators doc

js_modules/dagit/packages/ui/src/components/Icon.tsx, js_modules/dagit/packages/ui/src/icon-svgs/bar-chart.svg
Add bar chart icon for Cloud.
Buildkite
=> [ui] Add bar chart icon

python_modules/libraries/dagster-dbt/dagster_dbt/cli/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/cli/test_resources_v2.py
The user should have control on what to do when a dbt command fails. By default, we should expose the failure to the user. Then, the user can either handle it by:
- suppressing the failure, and setting `raise_on_failure=False`, or
- catching the failure and handling the exception.
Before, the failure was not raised, which caused the underlying execution in Dagster to not display as failure.
pytest
=> feat(dbt): raise exception by default when dbt command is not successful

docs/content/concepts/ops-jobs-graphs/op-events.mdx, examples/docs_snippets/docs_snippets/concepts/ops_jobs_graphs/op_events.py, examples/docs_snippets/docs_snippets_tests/concepts_tests/ops_jobs_graphs_tests/test_op_events.py
=> clarify how Failures relate to Exceptions, and remove redundant code snippet

python_modules/dagster/dagster/_core/definitions/asset_reconciliation_sensor.py, python_modules/dagster/dagster/_core/definitions/auto_materialize_condition.py, python_modules/dagster/dagster/_utils/caching_instance_queryer.py, python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/auto_materialize_policy_scenarios.py, python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/test_asset_daemon.py
Tell people which assets we're waiting on!
I had a terrible time trying to think of a good name for the function that returns the things that we're waiting on, very open to suggestions.
TODO: more in-depth tests
=> [AutoMaterialize] Add asset keys to ParentOutdatedAutoMaterializeCondition

python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_defs.py
I caused this failure in a recently-merged PR
=> fix dbt test_runtime_metadata_fn

js_modules/dagit/packages/core/src/assets/AssetPartitions.tsx, js_modules/dagit/packages/core/src/assets/__tests__/AssetPartitions.test.tsx
Address https://github.com/dagster-io/dagster/issues/15019
jest + tested locally
Note: screenshot says "created" but I changed it to "creation"
Also changed "sorting" to "sort"
=> [Partitions] Allow sorting alphabetically

python_modules/dagster/dagster/_core/definitions/graph_definition.py
Adds docstrings for public GraphDefinition methods
To enable https://github.com/dagster-io/dagster/pull/15078
=> Docstrings for GraphDefinition

python_modules/dagster/dagster/_core/definitions/job_definition.py
To help through https://github.com/dagster-io/dagster/pull/15078
=> Add docstrings for public job methods

examples/with_wandb/with_wandb/assets/model_registry_example.py, examples/with_wandb/with_wandb/ops/partitioned_job.py
Closes #15065
Note that in two cases I just removed the `config_schema` instead of updating since it wasn't actually being used.
=> Update dagster-wandb to use Pythonic config

js_modules/dagit/packages/core/src/graphql/schema.graphql, js_modules/dagit/packages/core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/schema/auto_materialize_asset_evaluations.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_auto_materialize_asset_evaluations.py
Add field to gql for which assets we're waiting on
=> ParentOutdatedAutoMaterializeCondition gql

python_modules/dagster/dagster/_core/definitions/run_request.py
Fixes #15080 
Triggered a RunRequest from sensor
=> Update run_request.py tags validation

docs/content/integrations/dbt/reference.mdx, examples/docs_snippets/docs_snippets/integrations/dbt/dbt.py
=> remove with_resources from dbt reference

js_modules/dagit/packages/ui/src/components/Icon.tsx, js_modules/dagit/packages/ui/src/icon-svgs/dot.svg
=> [ez] Add dot icon

python_modules/dagster/dagster/_core/storage/tags.py
I couldn't find any references to this
=> remove unused preset tag

docs/content/tutorial/setup.mdx
=> Fix intro docs

python_modules/dagster/dagster/_core/definitions/assets.py
This makes the error a little easier to debug.
=> in error message for self-dependency, include asset key

python_modules/dagster/dagster/_core/definitions/dependency.py, python_modules/dagster/dagster/_core/definitions/executor_definition.py, python_modules/dagster/dagster/_core/definitions/logger_definition.py, python_modules/dagster/dagster/_core/definitions/version_strategy.py, python_modules/dagster/dagster/_core/execution/context/compute.py, python_modules/dagster/dagster/_core/execution/context/hook.py, python_modules/dagster/dagster/_core/execution/execute_in_process_result.py, python_modules/libraries/dagstermill/dagstermill/context.py
Docstrings for "Misc" category from #15078.
=> [docstrings] Misc

python_modules/dagster/dagster/_core/types/dagster_type.py
Docstrings for "Dagster Types" category from #15078.
=> [docstrings] Dagster Types

python_modules/dagster/dagster/_core/definitions/metadata/__init__.py
Docstrings for "Metadata" category from #15078.
=> [docstrings] Metadata

pyproject.toml, python_modules/automation/automation_tests/telemetry/test_resource_telemetry.py, python_modules/dagster/dagster/_core/definitions/asset_layer.py, python_modules/dagster/dagster/_core/definitions/external_asset_graph.py, python_modules/dagster/dagster/_core/execution/retries.py, python_modules/dagster/dagster/_core/executor/step_delegating/step_delegating_executor.py, python_modules/dagster/dagster/_core/storage/cloud_storage_compute_log_manager.py, python_modules/dagster/dagster_tests/definitions_tests/test_sensor_invocation.py, python_modules/libraries/dagstermill/dagstermill/factory.py
Enable subset of new ruff PERF rule class:
- [unnecessary-list-cast](https://beta.ruff.rs/docs/rules/unnecessary-list-cast/)
- [incorrect-dict-iterator](https://beta.ruff.rs/docs/rules/incorrect-dict-iterator/)
ruff
=> [ruff] Enable PERF rules

.buildkite/dagster-buildkite/dagster_buildkite/python_packages.py, pyright/alt-1/requirements-pinned.txt, pyright/master/requirements-pinned.txt, python_modules/dagster/dagster/_config/config_type.py, python_modules/dagster/dagster/_core/definitions/graph_definition.py, python_modules/dagster/dagster/_core/definitions/partition.py, python_modules/dagster/dagster/_core/definitions/scoped_resources_builder.py, python_modules/dagster/dagster/_core/scheduler/instigation.py, python_modules/dagster/dagster/_core/storage/event_log/sqlite/sqlite_event_log.py, python_modules/dagster/dagster/_core/storage/fs_io_manager.py, python_modules/dagster/dagster/_daemon/cli/__init__.py, python_modules/dagster/dagster/_grpc/server.py, python_modules/dagster/dagster/_serdes/ipc.py, python_modules/dagster/dagster/_serdes/serdes.py, python_modules/dagster/dagster_tests/core_tests/resource_tests/pythonic_resources/test_general_pythonic_resources.py, python_modules/dagster/dagster_tests/core_tests/resource_tests/test_resource_parameters.py, python_modules/dagster/setup.py, python_modules/libraries/dagster-dbt/dagster_dbt/ops.py, python_modules/libraries/dagster-snowflake-pandas/dagster_snowflake_pandas_tests/test_snowflake_pandas_type_handler.py, python_modules/libraries/dagster-snowflake-pyspark/dagster_snowflake_pyspark_tests/test_snowflake_pyspark_type_handler.py, python_modules/libraries/dagster-wandb/dagster_wandb/io_manager.py
Internal companion PR: https://github.com/dagster-io/internal/pull/6120
Bump pyright version and pins. This required changing some type signatures to handle newly detected errors, as well as adding/removing some type-ignores.
pyright
=> [pyright] Update from 1.1.298 -> 1.1.316

python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/test_asset_reconciliation_sensor_perf.py
=> Bump limit on perf regression test

docs/sphinx/sections/api/apidocs/libraries/dagster-shell.rst, python_modules/libraries/dagster-shell/dagster_shell/ops.py
some small improvements to the dagster-shell api docs that should hopefully help users understand how to use the various ops in different circumstances
ran docs site locally
=> [docs] improve dagster-shell api docs

python_modules/libraries/dagster-snowflake/dagster_snowflake/snowflake_io_manager.py
fixes a small naming typo in the snowflake api docs example
=> [docs] fix typo in snowflake api docs

js_modules/dagit/packages/core/src/launchpad/LaunchpadSession.tsx
Addresses #14580 
https://www.loom.com/share/92a25229e40d4af191114f3e9f124284
=> Preserve run config on partition selection

js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/Conditions.tsx
Context: https://elementl-workspace.slack.com/archives/C04UD72HHQX/p1689007961856609
=> Remove color from evaluations ui center

python_modules/dagster/dagster/_core/definitions/assets.py
Modifies the implementations of the `subset_for`, `with_attributes`, and `with_resources` methods of `AssetsDefinition` to rely on a new `get_attributes_dict` method.
This will allow subclasses of `AssetsDefinition` (i.e. `DbtAssetsDefinition`) to override this method to provide additional attributes, instead of having these subclasses override `subset_for`, `with_attributes`, and `with_resources`.
This reduces the number of locations that we need to enumerate all the attributes of `AssetsDefinition`.
=> refactor: AssetsDefinition.get_attributes_dict

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py, python_modules/dagster/dagster/_core/execution/context/output.py, python_modules/dagster/dagster_tests/storage_tests/test_io_manager_asset_metadata.py
Addresses https://github.com/dagster-io/dagster/issues/10243 and https://github.com/dagster-io/dagster/issues/14916
=> make asset metadata available in cases where it was missing

pyright/alt-1/requirements-pinned.txt, pyright/master/requirements-pinned.txt
As the title.
This was autogenerated from `make rebuild_pyright_pins`
=> chore: update pinned deps for pyright

python_modules/dagit/dagit_tests/test_cli.py, python_modules/dagster-webserver/dagster_webserver/cli.py
doh
Ran `dagit -f ...`, observed log messages (previously missing).
=> [bugfix] dagit logger

python_modules/dagster/dagster/_core/test_utils.py, python_modules/dagster/dagster/_daemon/sensor.py, python_modules/dagster/dagster/_scheduler/scheduler.py, python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py, python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py
added tests for sensors and schedules that failed before these changes
=> [instigators] refresh request_context during submissions

python_modules/dagster/dagster/_core/definitions/events.py, python_modules/dagster/dagster/_core/execution/context/input.py, python_modules/dagster/dagster/_core/execution/context/output.py
to contribute API docs to https://github.com/dagster-io/dagster/pull/15078
=> [docs] api docs for missing public methods on input context, output context, and dynamic output

python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/op_definition.py
https://github.com/dagster-io/dagster/pull/15078
=> [docs] API docs for AssetsDefinition and OpDefinition

examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/customize_asset_keys.py, examples/experimental/tutorial_dbt_dagster_v2/tutorial_dbt_dagster_v2/assets/customize_description.py, python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt/asset_defs.py, python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py, python_modules/libraries/dagster-dbt/dagster_dbt/dbt_assets_definition.py, python_modules/libraries/dagster-dbt/dagster_dbt/dbt_manifest_asset_selection.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_defs.py
=> [dagster-dbt] rename translator methods 

python_modules/libraries/dagster-dbt/dagster_dbt/asset_defs.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_defs.py
=> accept Path in load_assets_from_dbt_manifest

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py
This is a regression from inferring the dbt manifest from the `AssetsDefinition`. In cases where we are not in an `AssetsDefinition` context, `context.assets_def` raises an exception when the property is `None`.
Suppress that behavior. This way, `DbtCli` can continue being invoked in `op`'s.
pytest
=> fix(dbt): allow `DbtCli` to be invoked in ops

python_modules/dagster/dagster/_config/config_type.py, python_modules/dagster/dagster/_config/field.py, python_modules/dagster/dagster/_config/field_utils.py, python_modules/dagster/dagster/_core/definitions/resource_definition.py, python_modules/dagster/dagster/_core/execution/context/init.py
Adds docstrings to various public resources / config functions
=> [docstrings] Resources & config

python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_environment_schema.ambr
Fixes test failure introduced in #15323, I guess Graphite let me merge despite the test failing 😔
=> [fix] update launchpad snapshot test

docs/content/tutorial/setup.mdx
DuckDB is not an in-memory database, but an in-process database.
=> Fix description of DuckDB

.buildkite/dagster-buildkite/dagster_buildkite/steps/docs.py
=> Fix docs comment

docs/content/deployment/guides/kubernetes/deploying-with-helm-advanced.mdx, docs/content/deployment/guides/kubernetes/deploying-with-helm.mdx, examples/deploy_k8s/example_project/example_repo/repo.py, examples/deploy_k8s/tests/test_project.py
Per https://github.com/dagster-io/dagster/issues/15249, we have these 3 example jobs when you install the Helm chart, and 2 of them don't work out of the box. Help that a bit by explaining them in the ui and the docs.
=> Document k8s example jobs

python_modules/libraries/dagster-dbt/dagster_dbt/dbt_assets_definition.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_dependencies.py
=> remove get_asset_key_for_dbt_unique_id

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/conftest.py, python_modules/libraries/dagster-dbt/pytest.ini, python_modules/libraries/dagster-dbt/tox.ini
As the title. This should speed up tests.
bk
=> test(dbt): separate legacy resource tests into tox factor

docs/content/concepts/assets/asset-auto-execution.mdx
=> fix sentence in auto-observe docs

docs/content/deployment/guides/kubernetes/deploying-with-helm-advanced.mdx, docs/content/deployment/guides/kubernetes/deploying-with-helm.mdx, examples/deploy_k8s/example_project/example_repo/repo.py, examples/deploy_k8s/tests/test_project.py
=> Revert "Revert "Document k8s example jobs (#15255)""

docs/sphinx/sections/api/apidocs/libraries/dagster-dbt.rst, python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py
=> api docs for DagsterDbtTranslator and dbt_assets

python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt/asset_defs.py, python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py, python_modules/libraries/dagster-dbt/dagster_dbt/cloud/asset_defs.py, python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_defs.py
=> add get_group_name to DagsterDbtTranslator

docs/content/guides/limiting-concurrency-in-data-pipelines.mdx
Misleading non-support statement
BK - will examine preview
=> reword global op concurrency notice

python_modules/dagster/dagster/_core/events/__init__.py, python_modules/dagster/dagster/_core/events/log.py, python_modules/dagster/dagster/_core/storage/dagster_run.py
https://github.com/dagster-io/dagster/pull/15078
=> [docs] Docstrings for public methods/properties (runs & events)

python_modules/libraries/dagster-dbt/dagster_dbt/__init__.py, python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt/dbt_manifest_asset_selection.py
=> take the experimental decorator off dbt_assets and DbtManifestAssetSelection

docs/sphinx/sections/api/apidocs/libraries/dagster-dbt.rst
=> in dbt apidoc, move resources above ops

python_modules/dagster/dagster/_core/instance/__init__.py
Allows forward-compat with custom dagster instances
=> Add a kwargs arg to DagsterInstance

CHANGES.md
Add changes since 1.3.14. 
Will add major changes section + migration guide in a follow up PR.
=> 1.4.0 Changelog

python_modules/dagster/dagster/_core/definitions/asset_reconciliation_sensor.py, python_modules/dagster/dagster/_core/definitions/auto_materialize_condition.py, python_modules/dagster/dagster/_utils/caching_instance_queryer.py, python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/auto_materialize_policy_scenarios.py, python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/basic_scenarios.py
Surface which parent materialized, causing the eager materialize condition
=> Add ParentMaterialized details

CHANGES.md
=> docs: add dbt entries to 1.4.0 changelog

js_modules/dagit/packages/core/src/graphql/schema.graphql, js_modules/dagit/packages/core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/schema/auto_materialize_asset_evaluations.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_auto_materialize_asset_evaluations.py, python_modules/dagster/dagster/_core/definitions/asset_reconciliation_sensor.py, python_modules/dagster/dagster/_core/definitions/auto_materialize_condition.py, python_modules/dagster/dagster/_utils/caching_instance_queryer.py, python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/auto_materialize_policy_scenarios.py, python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/basic_scenarios.py
Surface which parent materialized.
cc @hellendag - would you be able to throw together another modal for this?
=> ParentMaterialized details gql

CHANGES.md
=> major changes for 1.4.0

CHANGES.md, MIGRATION.md
As the title.
- https://github.com/dagster-io/dagster/blob/rl/migration-1.4.0/MIGRATION.md
- https://github.com/dagster-io/dagster/blob/rl/migration-1.4.0/CHANGES.md
=> docs: add migration guide for 1.4.0

js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/AutomaterializeMiddlePanelWithPartitions.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/AutomaterializeRequestedPartitionsLink.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/Conditions.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/WaitingOnPartitionAssetKeysLink.tsx
=> Add colored tags on partition links

js_modules/dagit/packages/core/src/assets/AssetView.tsx
Resolves #15410
The link in the `HistoricalViewAlert` on `AssetView` is really for navigation, not for in-place query param updates. Instead of using query persisted state, just build a link to the appropriate `time` value.
Navigate from a run to a historical view of an asset. Verify that when I click the link in the alert, I navigate via normal link behavior, and that I can navigate back with the back button, as expected.
=> [ui] Use a regular RR link for historical alert on AssetView

CHANGES.md
=> docs: add 1.4.1 changelog

docs/content/concepts/assets/software-defined-assets.mdx, examples/docs_snippets/docs_snippets/concepts/assets/asset_w_context.py
missed this earlier
make mdx-format
=> [docs] update Asset Context section

docs/content/getting-started/releases.mdx
=> [docs] fix python version heading

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py
Fix a regression from https://github.com/dagster-io/dagster/pull/15344.
add pytest
=> fix(dbt): correctly determine if `DbtCliResource` is in a subselection context

CHANGES.md
=> docs: add 1.4.2 changelog

js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/WaitingOnPartitionAssetKeysLink.tsx
=> missing parenthesis

python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py
Fix forward https://github.com/dagster-io/dagster/pull/15466.
pytest
=> fix(dbt): make test deterministic

docs/sphinx/sections/api/apidocs/libraries/dagster-dbt.rst, python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py
As the title.
```bash
make apidoc-build
```
=> docs(dbt): add public decorators to new `dagster-dbt` API

docs/content/integrations/dbt/reference.mdx, docs/content/integrations/dbt/using-dbt-with-dagster/load-dbt-models.mdx, docs/content/integrations/dbt/using-dbt-with-dagster/upstream-assets.mdx, examples/docs_snippets/docs_snippets/integrations/dbt/dbt.py, examples/tutorial_dbt_dagster/tutorial_finished/tutorial_dbt_dagster/__init__.py
=> docs(dbt): `DbtCli` -> `DbtCliResource`

python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt/asset_defs.py
=> api doc for dagster_dbt_translator argument on dbt_assets

python_modules/dagster/dagster/_daemon/sensor.py
Resolve perf issues stemming from run tag multi-search.
BK
=> break up batched run-key tag search into separate queries

docs/content/concepts/code-locations.mdx
Inspired by this user question: https://dagster.slack.com/archives/C01U954MEER/p1690201858374139
=> link to workspace page from code locations page

docs/content/guides/dagster/branch_deployments.mdx, examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/branch_deployments/repository_v1.py, examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/branch_deployments/repository_v2.py
=> [docs] fix branch deploy resource mismatch

python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py
Deprecate the following:
- `dagster_auto_materialize_policy`
- `dagster_freshness_policy`
N/A
=> feat(dbt): deprecate old style dbt project configuration for Dagster

python_modules/dagster/dagster/_core/definitions/partition_mapping.py, python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_asset_partition_mappings.py
Still need to fix up the test but this is the basic vibe
=> add downstream partitions for partitions method

js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/AssetKeysDialog.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/AutomaterializeMiddlePanelNoPartitions.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/AutomaterializeMiddlePanelWithPartitions.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/Conditions.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/GetEvaluationsQuery.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/ParentUpdatedLink.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/ParentUpdatedPartitionLink.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/VirtualizedAssetListForDialog.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/VirtualizedAssetPartitionListForDialog.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/WaitingOnAssetKeysLink.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/WaitingOnPartitionAssetKeysLink.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/assetDetailUtils.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/assetFilters.tsx, js_modules/dagit/packages/core/src/assets/AutoMaterializePolicyPage/types/GetEvaluationsQuery.types.ts, python_modules/dagster-test/dagster_test/toys/auto_materializing/repo_1.py
Add a details modal for which parent was updated
unpartitioned
partitioned
=> Parent updated ui

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py
As the title.
See logs when running `DAGSTER_DBT_PARSE_PROJECT_ON_LOAD=1 dagster dev`
=> feat(dbt): write stdout logs when calling `.wait()`

python_modules/libraries/dagster-dbt/setup.py
=> chore(dbt): require `typer>=0.9.0`

python_modules/libraries/dagster-dbt/dagster_dbt_tests/cli/test_app.py
Error message changed in https://buildkite.com/dagster/dagster/builds/62668, so continue going down the env var rabbithole.
bk
=> fix(dbt): continue disabling threading affinity for OpenBlas

python_modules/dagster-test/dagster_test/toys/asset_reconciliation/eager_reconciliation.py, python_modules/dagster-test/dagster_test/toys/asset_sensors.py
=> Move final toys to AMP

docs/content/deployment/dagster-instance.mdx
=> Small typo in dagster instance docs

.github/workflows/build-storybook-core.yml, .github/workflows/build-storybook-ui.yml
branch-stable vercel previews for storybook PRs
Inspection
=> add branch previews to storybook vercel pushes

CHANGES.md
As the title.
https://github.com/dagster-io/dagster/blob/rl/changes-release-1.4.3/CHANGES.md
=> docs: add 1.4.3 changelog

docs/content/concepts/partitions-schedules-sensors/sensors.mdx, examples/docs_snippets/docs_snippets/concepts/partitions_schedules_sensors/sensors/sensor_alert.py
=> fix slack sensor code snippet

.github/workflows/build-docs.yml, .github/workflows/build-storybook-core.yml, .github/workflows/build-storybook-ui.yml
Saw failed docs build, due to invalid preview subdomain
[docs preview](https://github.com/dagster-io/dagster/actions/runs/5732391451/job/15535237848)
=> make sure subdomains are sanitized to alphanumeric, hypen

.github/workflows/build-docs.yml, .github/workflows/build-storybook-core.yml, .github/workflows/build-storybook-ui.yml, docs/content/dagster-cloud/deployment/agents/customizing-configuration.mdx
For Cloud users to configure streaming compute logs
BK
=> add docs section about configuring agent for streaming compute logs

CHANGES.md, MIGRATION.md
* document known helm upgrade breaking change 
* document isloated_agents rename
* clean up migration guide
* let autoforamtter run 
vscode markdown preview
=> changelog / migration guide updates

python_modules/dagster/dagster/_annotations.py, python_modules/dagster/dagster/_utils/backcompat.py
Fixes minor recent warning formatting regression.
=> Fix experimental warning formatting

docs/next/util/redirectUrls.json
missed a couple redirects when i did the non_argument_deps -> deps docs changes
tested that the redirects work in the vercel preview
=> [docs] add redirects for some removed non_argument_deps links

.github/ISSUE_TEMPLATE/config.yml, docs/content/getting-started.mdx, python_modules/dagster/README.md, python_modules/dagster/setup.py
- Use vanity URL
- Add link to documentation
- Use correct tagline
read
=> docs: use `@dagsterio` for YouTube channel

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py, python_modules/libraries/dagster-dbt/setup.py, python_modules/libraries/dagster-dbt/tox.ini
Resolves https://github.com/dagster-io/dagster/issues/15662.
bk
=> feat(dbt): support `dbt-core==1.6.*`

.github/workflows/build-storybook-ui.yml
Update paths to `ui-components` instead of old `ui`.
=> Fix storybook paths

.github/workflows/build-storybook-core.yml, .github/workflows/build-storybook-ui.yml
Removing "dagit" from lexicon
docs previews
=> remove "dagit" from docs preview urls

.github/workflows/build-storybook-ui.yml
for consistency, disambiguation, want to rename ui => components to match the file structure
inspection
=> rename ui-storybook => components-storybook

python_modules/dagster/dagster/_core/definitions/multi_dimensional_partitions.py
Cap the maximum size that this can grow more excessively
=> Reduce lru_cache maxsize from 5 to 1 on MultiPartitionsDefinition

python_modules/dagster/dagster/_core/definitions/data_time.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenarios/auto_materialize_policy_scenarios.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenarios/freshness_policy_scenarios.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_asset_daemon.py
Added test failed before, passes now.
=> fix bug with calculating failed data time

docs/content/integrations/dbt/reference.mdx, examples/docs_snippets/docs_snippets/integrations/dbt/dbt.py
Resolves https://github.com/dagster-io/dagster/issues/15650.
read
=> docs(dbt): clarify `get_metadata` example function

docs/content/integrations/dbt/using-dbt-with-dagster.mdx, docs/content/integrations/dbt/using-dbt-with-dagster/load-dbt-models.mdx
As the title. We already talk about installing dependencies in the prequisites of the tutorial start.
read
=> docs(dbt): remove unnecessary installation step in dbt tutorial

docs/content/integrations/dbt/using-dbt-with-dagster/upstream-assets.mdx
=> docs(dbt): fix test

docs/content/integrations/airbyte-cloud.mdx, docs/content/integrations/airbyte.mdx, examples/docs_snippets/docs_snippets/integrations/airbyte/airbyte.py
Add an example using `deps` to the airbyte docs
=> [docs] add an example using deps in airbyte docs

python_modules/dagster/dagster/_core/storage/tags.py
=> Add dagster/isolation to user editable tags

js_modules/dagster-ui/packages/ui-core/src/runs/RunStats.tsx
Fixes: https://github.com/dagster-io/dagster/issues/15291
Not all expectations are successful, so fix this wording.
=> "expectations passed" -> "expectations evaluated"

docs/tox.ini
seems like this new release doesn't work for us
bk
=> [docs] pin sphinxcontrib-serializinghtml

docs/content/concepts/assets/asset-auto-execution.mdx
=> fix typo in auto-materialize docs

python_modules/dagster/dagster/_grpc/impl.py, python_modules/dagster/dagster_tests/api_tests/test_api_launch_run.py
clean-up from validating that we communicate these exceptions correctly
udpated test
=> update definition time failure message

js_modules/dagster-ui/packages/ui-core/src/graph/ParentOpNode.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/LogsToolbar.tsx
These 2 issues:
Checking CSH with shadow dagit
=> Fix issues with nulls

js_modules/dagster-ui/packages/ui-components/.storybook/main.js, js_modules/dagster-ui/packages/ui-core/src/app/analytics.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/RunTable.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/RunTag.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/RunTags.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/RunsRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/__fixtures__/RunsRoot.fixtures.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/__stories__/RunsRoot.stories.tsx
Solves #15535 
Storybook:
https://www.loom.com/share/5c56c98d1b6240d197b8c0d0c1a3bfcc
=> [Runs table] Allow pinning/unpinning tags

.github/workflows/build-docs.yml, .github/workflows/build-storybook-core.yml, .github/workflows/build-storybook-ui.yml
Got vercel alias failure for some branch names
```
$ echo 'yuhan/_docs-no-version_version_dropdown_' | sed 's/[^a-zA-Z0-9-]/-/g' | sed 's/^-*//' | sed 's/-*$//' 
yuhan--docs-no-version-version-dropdown
```
=> strip leading/trailing dashes from vercel subdomain

docs/next/components/Sidebar.tsx
Resolves #15746.
When expanding and collapsing sections in the Docs sidebar, don't navigate away. This way, users can browse the sidebar structure without losing their place.
This is implemented by using a `button` for expand/collapse, positioned absolutely in a container that also contains the link itself. The button's click event is stop-propagated, preventing any `NextLink` wrapper component from performing the navigation.
View Docs site, expand and collapse sections, verify that I am not taken away from my current page.
Verify that the sidebar styles, colors, etc. all look correct, including on hover. Find an external link element, verify that its icon renders correctly.
=> [docs] Don't navigate on sidebar expand/collapse

python_modules/libraries/dagster-k8s/dagster_k8s/job.py, python_modules/libraries/dagster-k8s/dagster_k8s/launcher.py
some clean-up while in the area
bk
=> [k8s] update typing for job.py

docs/sphinx/sections/api/apidocs/assets.rst
=> [docs] add @graph_multi_asset

js_modules/dagster-ui/packages/ui-core/src/runs/RunTable.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/RunTags.tsx
This PR hides system tags by default and keeps user tags shown by default.
storybook
=> [Runs table] Hide system tags by default

python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py, python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster/_daemon/asset_daemon.py, python_modules/dagster/dagster/_utils/caching_instance_queryer.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/base_scenario.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenarios/version_scenarios.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_asset_daemon_fast.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_asset_daemon_perf.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_auto_observe.py
=> [auto-materialize] Add flag to optionally enable data versions to be used in calculation

python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenarios/version_scenarios.py
=> Patch missing imports

docs/content/_navigation.json
The short name is a little underspecified, and we use the full name elsewhere in links to this guide.
=> update nav item for validating data guide

python_modules/libraries/dagster-k8s/dagster_k8s/executor.py, python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_executor.py
Summary:
If users want to set some configuration to every step pod when using the k8s executor, their only recourse is the clunky solution of creating an op factory and using it on every one of the ops. A more natural place is to put this as config on the executor. Do that.
Will do docs on top of this in a separate PR.
Test Plan: BK
=> Allow setting config at the executor level that applies to all steps launched by the k8s_job_executor

docs/content/concepts/partitions-schedules-sensors/partitions.mdx
=> docs(partitions): add an API reference to `context.partition_key`

docs/content/concepts/assets/asset-auto-execution.mdx
We included a bunch of performance improvements to address these issues and haven't been hearing these complaints.
=> remove warning about large numbers of partitioned assets from auto-materialize docs

python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py, python_modules/dagster/dagster/_core/definitions/asset_graph.py, python_modules/dagster/dagster/_utils/caching_instance_queryer.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenarios/observable_source_asset_scenarios.py
=> [auto-materialize] fix missing observable source case

CHANGES.md
=> 1.4.6 Changelog

python_modules/dagster/dagster/__init__.py, python_modules/dagster/dagster/_core/definitions/partition.py, python_modules/dagster/dagster_tests/core_tests/partition_tests/test_partitioned_job.py
=> :star: add partitioned_config decorator

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py
Resolves https://github.com/dagster-io/dagster/issues/15258. If events can no longer be written to the Dagster framework when the job/op process terminates, then the subprocess executing dbt commands should also terminate.
If the controlling process
pytest
=> feat(dbt): terminate `dbt` subprocess on exit

python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt/dbt_manifest.py, python_modules/libraries/dagster-dbt/dagster_dbt/dbt_manifest_asset_selection.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_selection.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_decorator.py
Resolves https://github.com/dagster-io/dagster/issues/15689.
pytest
=> feat(dbt): allow `manifest` to accept `Union[dict, str, Path]`

python_modules/dagster-test/Dockerfile, python_modules/dagster-test/dagster_test/test_project/build.sh, python_modules/dagster/dagster/_core/external_execution/resource.py, python_modules/dagster/dagster/_core/external_execution/task.py, python_modules/libraries/dagster-docker/dagster_docker/external_resource.py, python_modules/libraries/dagster-docker/dagster_docker_tests/test_external_asset.py, python_modules/libraries/dagster-docker/tox.ini
extend dagster-external to docker 
added test
=> dagster-external docker asset

CHANGES.md
=> 1.4.7 changelog

examples/project_fully_featured/project_fully_featured/resources/__init__.py
I spaced that project fully featured will pull from latest when users download it, so we need to keep this as the old name until next week's release
=> [quick] [example] project fully featured use ConfigurablePickledObjectS3IOManager

python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_persistent_db/test_persistent_airflow_2_db.py
=> update airflow tests for 2.7

CHANGES.md
This PR adds a few changelog entries for 1.4.5 since I was OOO last week when the changelog was assembled.
=> [ui] Updates to the changelog for UI work in 1.4.5

js_modules/dagster-ui/packages/ui-core/src/ui/Filters/useStaticSetFilter.tsx
=> [Filters] Don't try to pluralize the filter name

python_modules/libraries/dagster-dbt/dagster_dbt/cli/app.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_metadata/profiles.yml
dbt's `profiles.yml` can contain a `config` key: https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml
This fixes a failure where the dbt scaffolding CLI fails when attempting to
read a `profiles.yml` file with a config key.
Here's an example exception that was reported:
```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/SW/.pyenv/versions/3.9.2/lib/python3.9/site-packages/dagster_dbt/cli/app.py:189 in        │
│ project_scaffold_command                                                                         │
│                                                                                                  │
│   186 │                                                                                          │
│ …
```
=> [dagster-dbt] Fix dbt scaffolding failure when config key defined in profiles.yml

python_modules/libraries/CONTRIBUTING.md
This adds early instructions on contributing Dagster library integrations.
=> Add Dagster Library Integration contribution guide

docs/content/deployment/guides/docker.mdx, examples/deploy_docker/Dockerfile_dagster, examples/deploy_docker/Dockerfile_user_code, examples/deploy_docker/from_source/Dockerfile_dagster, examples/deploy_docker/from_source/Dockerfile_user_code, examples/deploy_ecs/Dockerfile, examples/deploy_ecs/from_source/Dockerfile, examples/docs_snippets/docs_snippets/deploying/docker/Dockerfile, examples/docs_snippets/docs_snippets/deploying/docker/Dockerfile_user_code
Thess got missed when we dropped 3.7 support
bk
=> update example Dockerfile to use 3.10-slim

docs/content/integrations/dbt/reference.mdx
=> docs(dbt): fix formatting

docs/content/integrations/dbt/reference.mdx
=> docs(dbt): fix formatting again

python_modules/dagster/dagster/_core/external_execution/task.py
Changes file output mode to tail the file rather than reading all at once at the end. This is a stepping stone to eliminating IO modes and standardizing on file I/O.
=> [externals] tail file output rather than reading all at once

.buildkite/dagster-buildkite/dagster_buildkite/steps/dagster.py, python_modules/automation/automation_tests/telemetry/test_resource_telemetry.py, python_modules/automation/automation_tests/test_repo.py
dir scanning based tests were not ready for this file to be here, handle it
bk
=> update tests for python_modules/libraries/CONTRIBUTING.md

python_modules/dagster/dagster/_core/definitions/asset_check_result.py, python_modules/dagster/dagster/_core/definitions/asset_check_spec.py, python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py, python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_decorator_with_check_specs.py
=> check_specs argument on @multi_asset

examples/experimental/assets_yaml_dsl/assets_yaml_dsl/__init__.py, examples/experimental/assets_yaml_dsl/assets_yaml_dsl/assets_dsl.py, examples/experimental/assets_yaml_dsl/assets_yaml_dsl/sql_script.py, examples/experimental/assets_yaml_dsl/assets_yaml_dsl_tests/test_assets_dsl.py, examples/experimental/assets_yaml_dsl/setup.py, examples/experimental/assets_yaml_dsl/tox.ini
First usage of dagster externals in the DSL to log metadata
Manually tested in dagit
=> Make the asset DSL invoke an external script using dagster externals

python_modules/dagster/dagster/_core/execution/asset_backfill.py, python_modules/dagster/dagster/_daemon/backfill.py, python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py
https://elementl-workspace.slack.com/archives/C05MDAH8QM6/p1692105811624019
=> don't fail backfill due to DagsterAssetBackfillDataLoadError

examples/experimental/assets_yaml_dsl/assets_yaml_dsl/__init__.py, examples/experimental/assets_yaml_dsl/assets_yaml_dsl/assets_dsl.py, examples/experimental/assets_yaml_dsl/assets_yaml_dsl_tests/test_assets_dsl.py
=> fix-up SubprocessExecutionResource import

docs/content/concepts/webserver/graphql-client.mdx, examples/docs_snippets/docs_snippets/concepts/webserver/graphql/client_example.py
Making sure content from https://github.com/dagster-io/dagster/discussions/7772 is in the published docs
preview
=> add section in graphql client docs for dagster cloud

python_modules/dagster/dagster/_core/definitions/step_launcher.py, python_modules/libraries/dagster-databricks/dagster_databricks/databricks.py, python_modules/libraries/dagster-databricks/dagster_databricks/databricks_pyspark_step_launcher.py, python_modules/libraries/dagster-databricks/dagster_databricks/databricks_step_main.py
Type annotations for dagster-databricks `StepLauncher` and some other code.
=> [dagster-databricks] type annotations

js_modules/dagster-ui/packages/ui-core/src/graph/OpTags.tsx
https://elementl-workspace.slack.com/archives/C03CCE471E0/p1692823429064439
👀 
Will deploy to dogfood to confirm the fix
=> Check that known isn't undefined before trying to use `in` operator

python_modules/dagster/dagster/_core/definitions/asset_layer.py, python_modules/dagster/dagster/_core/definitions/assets_job.py, python_modules/dagster/dagster/_core/definitions/job_definition.py, python_modules/dagster/dagster/_core/execution/context/system.py
This is a refactor with no behavior changes. Its goal is to reduce lines of code and make AssetLayer easier to understand.
=> make AssetLayer a NamedTuple

docs/next/pages/[...page].tsx
Statically render breadcrumbs on Sphinx-based docs pages by providing the path to the layout component.
This will allow these documents to be crawled as "API Reference" docs instead of the generic "Dagster Docs" fallback, as with https://github.com/dagster-io/dagster/pull/15916.
View API Docs pages, verify that the breadcrumb nav is present in the retrieved document.
=> [docs] Include breadcrumbs for sphinx docs

js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/AutomaterializeLeftPanel.tsx, python_modules/dagster/dagster/_daemon/asset_daemon.py
=> bump amp evaluation retention to 1 month

python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py, python_modules/dagster/dagster/_core/definitions/auto_materialize_policy.py, python_modules/dagster/dagster/_core/definitions/auto_materialize_rule.py, python_modules/dagster/dagster/_utils/caching_instance_queryer.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenarios/auto_materialize_policy_scenarios.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_auto_materialize_policy.py
Obsoletes: https://github.com/dagster-io/dagster/pull/15919
The framework shifted a fair bit from the original PR, and I decided to rewrite this one to better align with the target API
=> [auto-materialize] Add a skip_on_parent_missing rule

CHANGES.md
=> changelog 1.4.8

.github/workflows/build-docs.yml
=> [easy] fix build-docs.yml identation

.github/workflows/build-docs.yml
https://github.com/dagster-io/dagster/pull/16075 didn't fix the problem 😢
=> [easy] fix build-docs.yml take 2

python_modules/dagster/dagster/_core/storage/alembic/versions/041_add_asset_check_executions_table.py, python_modules/dagster/dagster/_core/storage/event_log/schema.py
Pulled out from the combo diff https://github.com/dagster-io/dagster/pull/15851/files#diff-c77874c9582ea257b39111b61e2221285e700ba04e950db2d9b4b008c6560aab and addressed comments
=> asset_check_executions schema

python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_ping.py
wait() calls with no timeout can block indefinitely so timeout and kill 
bk
=> improve process cleanup in test_ping.py

js_modules/dagster-ui/packages/app-oss/src/pages/_app.tsx
blames to: https://github.com/dagster-io/dagster/pull/15842
👀
=> Fix document title in OSS

python_modules/dagster/dagster/_core/definitions/asset_layer.py
=> fix asset layer error

python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py
=> wipe asset check

docs/content/integrations/duckdb/using-duckdb-with-dagster.mdx
Some small updates to the DuckDB tutorial based off comments on the BigQuery tutorial https://github.com/dagster-io/dagster/pull/15799
=> [docs] small updates to duckdb tutorial

python_modules/dagster-test/dagster_test/toys/asset_checks.py, python_modules/dagster-test/dagster_test/toys/repo.py
=> Add asset check toy

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/implementation/fetch_asset_checks.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_checks.py, python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_checks.py
=> asset check executions gql

python_modules/libraries/dagster-aws/dagster_aws/s3/io_manager.py
I reopen this because I messed up in another branch
This PR addresses an issue in `PickleObjectS3IOManager` where missing partitions weren't handled consistently due to differing error types even provide `allow_missing_partitions` . The problem arises from `UPathIOManager` using `FileNotFoundError` while S3 io_manager return `botocore.exception.ClientError` with error code `NoSuchKey` when it can't get object.
The goal is to ensure uniformity in error handling. This PR modifies `PickleObjectS3IOManager.load_from_path` to raise FileNotFoundError for missing partitions, aligning it with `UPathIOManager` and improving error clarity.
=> Fix `S3IOManager` failed to handle missing partitions input

docs/content/integrations/dbt/reference.mdx, docs/content/integrations/dbt/using-dbt-with-dagster/load-dbt-models.mdx
=> docs(dbt): add reference for `dagster-dbt project scaffold`

python_modules/libraries/dagster-docker/dagster_docker_tests/test_external_asset.py
shouldn't run on oss BK pipeline
eyes
=> mark docker externals test as integration

examples/experimental/assets_yaml_dsl/assets_yaml_dsl/domain_specific_dsl/stocks_dsl.py
Use AssetSpec in the stocks dsl to dogfood.
Note: This PR definitively makes me want to support multi-key assetsdefinitions in`deps`.
BK. Viewed in dagster dev
=> Use AssetSpec in DSL example

docs/content/concepts/assets/software-defined-assets.mdx
I was working on a blog post for asset checks and came across this.  I think I wrote the original version, but I think this replacement might be more friendly without losing clarity.
=> update description for software-defined assets to be less jargony

docs/content/dagster-cloud/account/managing-users/managing-user-roles-permissions.mdx
=> Add audit logs to permissions docs

CHANGES.md
=> changelog 1.4.9 and 1.4.10

python_modules/dagster/dagster/_core/definitions/schedule_definition.py, python_modules/dagster/dagster_tests/definitions_tests/test_schedule_invocation.py
Summary:
A straight port of https://github.com/dagster-io/dagster/pull/14717/files to schedules as well.
Resolves https://github.com/dagster-io/dagster/issues/14333.
Test Plan: New test case, code in https://github.com/dagster-io/dagster/issues/14333 now loads
=> Fix issue when recreating schedules with resource reqs

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
Per https://www.notion.so/Asset-Checks-MVP-Todo-list-1705e087daad446b956cb63f7ed6de90?d=53504980061c4583967e560d9ea9336d&pvs=4#b68419fd9fcf4edab4897476a5a444cb
=> hasAssetChecks gql

python_modules/dagster-test/dagster_test/toys/asset_checks.py, python_modules/dagster-test/dagster_test/toys/repo.py
=> Add in-op and severe checks to toys

js_modules/dagster-ui/packages/ui-core/src/assets/AssetTabs.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/__fixtures__/AssetViewDefinition.fixtures.ts, js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/buildAssetTabs.test.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/AssetChecks.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/VirtualizedAssetCheckTable.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetView.types.ts
Add an interval refresh + improve the status logic
locally
=> [Asset checks] Add polling logic

js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/AssetCheckDetailModal.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/__fixtures__/AssetChecks.fixtures.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/__stories__/AssetChecks.stories.tsx
Increase modal width, add some more padding and remove the link to the docs for now.
storybook:
=> [AssetChecks] Increase modal widths + remove docs url for now

python_modules/dagster/dagster_tests/cli_tests/command_tests/test_execute_command.py
add test for external contrib #16124
ran test
=> test for cli --op-selection

js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/AssetCheckDetailModal.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/types/AssetCheckDetailModal.types.ts
Pass severity in so that the status tag is red or yellow.
=> [Asset checks] pass severity to status tag component in details modal

.github/workflows/build-dagster-university.yml
so it's easier to test. when we're ready to roll out, we'll re-think how we want to deploy: https://www.notion.so/dagster/Determine-how-we-release-dagster-university-micro-site-fcad33a0d8e643dca27f873ad1e67613
=> [dagster u] switch to use master as prod branch for now

js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/AssetCheckDetailModal.tsx
=> [Asset Checks] Add target materialization column

python_modules/dagster-test/dagster_test/toys/asset_checks.py
This probably shouldn't be possible, tracking https://www.notion.so/dagster/Asset-Checks-MVP-Todo-list-1705e087daad446b956cb63f7ed6de90?pvs=4#5ca85c951c3a4e00a03d8a1fc081f801
=> Fix asset key in toys

.buildkite/dagster-buildkite/dagster_buildkite/pipelines/dagster_oss_main.py
This suite is high volume but low signal. Just turn it off except for:
- merges to master/release branches
- commits that specifically have [INTERNAL_BRANCH=<branch>] in them
=> Disable most OSS compatibility builds

js_modules/dagster-ui/Makefile, js_modules/dagster-ui/packages/ui-components/package.json, js_modules/dagster-ui/packages/ui-core/package.json, js_modules/dagster-ui/packages/ui-core/src/ui/Filters/__tests__/FilterDropdown.test.tsx, js_modules/dagster-ui/tox.ini, js_modules/dagster-ui/yarn.lock
Bump `@testing-library/jest-dom` in lieu of https://github.com/dagster-io/dagster/pull/16194.
BK
=> [ui] Bump @testing-library/jest-dom

js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/AssetChecksBanner.tsx
=> [asset checks] fix banner copy

docs/content/dagster-cloud/account/managing-users/managing-teams.mdx, docs/content/dagster-cloud/account/managing-users/managing-user-roles-permissions.mdx, docs/content/dagster-cloud/managing-deployments/environment-variables-and-secrets.mdx, docs/content/guides/dagster/migrating-to-pythonic-resources-and-config.mdx, docs/next/components/Header.tsx
This PR fixes a few broken links in some of our non-API docs. This is part one of a two-part effort to clean up our links.
All of these links are inside React components, which we don't seem to test upon build. We should address this.
👀 , local
=> [docs] - Fix broken links

python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py
Summary:
These don't show up in the daemon by default, but are useful for debugging and rough profiling of what's going on in a tick. I could imagine them being sent in by users to help troubleshooting rule issues as well.
Test Plan:
Run a sample tick locally, see output like this:
https://gist.github.com/gibsondan/4e938c43675c3b626225652f12e1c963
=> More debug-level per-rule log lines

python_modules/dagster-test/dagster_test/toys/asset_checks.py
Add an example that can be used for control flow
=> Add severe check to toys

python_modules/dagster/dagster/_core/definitions/asset_sensor_definition.py, python_modules/dagster/dagster/_core/definitions/decorators/sensor_decorator.py
=> clarify behavior of asset sensors in docstring

docs/content/dagster-cloud/account/managing-users/managing-teams.mdx
This PR fixes a typo in the Cloud team docs.
👀
=> [docs] - Fix typo in Cloud team docs

python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py
Makes it easier to override the image used in a subclass.
Existing buildkite tests.
=> Extract overridable method EcsRunLauncher._get_image_for_run

docs/sphinx/sections/api/apidocs/partitions.rst, python_modules/dagster/dagster/__init__.py, python_modules/dagster/dagster/_core/definitions/backfill_policy.py
=> add BackfillPolicy to the public API

CHANGES.md
=> fix asset changes changelog link

python_modules/dagster/dagster/_utils/caching_instance_queryer.py
Summary:
For assets with tons of partitions, it is not uncommon to end up in a situation where you have a single asset partition being passed in, that is then compared to a dictionary with a ton of partition keys. The old logic here was iterating through the giant dictionary and comparing each element with the passed in partition key. Doing the reverse when possible makes the function much faster in this case (the original logic was only ~20-30ms per call, but the fact that we were then doing it once for each partition in certain cases made it basically O(n^2) in the number of partitions).
Test Plan: Working on an asset perf scenario
Manually, a single asset rule that was previously taking ~20 minutes now takes ~30 seconds
=> Optimize the 'quick check' in get_asset_partitions_updated_after_cursor when there are a large number of partitions for a given key

python_modules/dagster-externals/dagster_externals/_context.py, python_modules/dagster-externals/dagster_externals/_protocol.py, python_modules/dagster-externals/setup.py
This gets us to 0 runtime deps and required only trivial changes.
=> [externals] Remove typing-extensions dependency

python_modules/dagster/dagster/_core/definitions/data_version.py
Summary:
_get_current_data_version can be expensive, and we don't need it for partitioned assets.
Test Plan:
BK
Load a deployment that was experiencing slowdown in _get_data_version on their asset catalog, no longer
=> Short-circuit in _get_stale_causes for partitioned assets

js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/AssetChecksBanner.tsx
Now that we have a dedicated discussion for the MVP https://github.com/dagster-io/dagster/discussions/16266
=> update asset checks banner

python_modules/dagster-test/dagster_test/toys/asset_checks.py
=> add check on partitioned asset to toys

python_modules/dagster/dagster/_core/execution/plan/compute.py
=> Stop logging step did not fire outputs for checks

python_modules/dagster/dagster/_core/definitions/data_version.py, python_modules/dagster/dagster_tests/execution_tests/test_data_versions.py
Self-partitioned assets can cause a recursion error during stale status resolution if there are too many partitions. This is because resolution of the Nth partition will recurse back to the 1st partition, since this is within its ancestor tree.
This PR adds a threshold number of dependencies beyond which no staleness status will attempt to be derived for self-partitioned assets. This follows the existing approach of opting out of staleness calculation for partitions with large numbers of "horizontal" dependencies.
See: https://elementl-workspace.slack.com/archives/C03D094F23G/p1693573479147479
New unit test.
=> Introduce limit for stale resolution for self-partitioned assets

python_modules/libraries/dagster-dbt/dagster_dbt/include/setup.py.jinja
=> fix(dbt): add new lines when templating adapters in `setup.py`

CHANGES.md
=> 1.4.12 changelog

helm/dagster/Chart.yaml, helm/dagster/charts/dagster-user-deployments/Chart.yaml
=> refactor(helm): rename maintainer to Dagster Labs

python_modules/libraries/dagster-dbt/dagster_dbt/asset_defs.py, python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py, python_modules/libraries/dagster-dbt/dagster_dbt/cloud/asset_defs.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_defs.py
Resolves https://github.com/dagster-io/dagster/issues/16350.
pytest
=> fix(dbt): use dbt translator for freshness and auto-materialize policies

python_modules/dagster/dagster/_daemon/asset_daemon.py
Summary:
This won't catch all idempotency issues, but moves a lot more work that can fail part-way through (validating job names and asset keys, calling out to user code to generate execution plans, etc.) up front, so that the only operations that could run into run-related idempotency issues is the act of creating the run and submitting it to the queue (both of which only touch the dagster DB).
Test Plan: Existing test suite
=> Simpler idempotency fix for asset daemon

python_modules/dagster/dagster/_core/executor/step_delegating/step_delegating_executor.py
Noticed we were still using offset pagination here instead of better cursor based. This change should increase DB effeciency. 
existing tests
=> [step delegating executor] avoid offset events pagination

examples/docs_snippets/docs_snippets/integrations/dbt/dbt.py
=> refactor(dbt): remove unused docs snippets

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py
By closing the subprocess streams properly, we can remove unclosed file warnings when using `dagster-dbt`:
```
sys:1: ResourceWarning: unclosed file <_io.BufferedReader name=16>
Running with dbt=1.6.1
Registered adapter: duckdb=1.6.0
Unable to do partial parsing because saved manifest not found. Starting full parse.
Performance info: /Users/rexledesma/Dropbox/Mac (3)/Downloads/projects/jaffle_shop/target/1d5e876/perf_info.json
sys:1: ResourceWarning: unclosed file <_io.BufferedReader name=3>
```
Now we show:
```
Running with dbt=1.6.1
Registered adapter: duckdb=1.6.0
Unable to do partial parsing because saved manifest not found. Starting full parse.
Performance info: /Users/rexledesma/Dropbox/Mac (3)/Downloads/projects/jaffle_shop/target/1d5e876/perf_info.json
```
local
=> fix(dbt): close dbt subprocess stream after emitting logs

docs/content/deployment/run-monitoring.mdx, examples/docs_snippets/docs_snippets/deploying/dagster_instance/dagster.yaml
I just found a sneaky little typo i wanted to help fix :)
=> Fix typo: execpt -> except

js_modules/dagster-ui/packages/ui-core/src/asset-graph/useLiveDataForAssetKeys.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/useLiveDataForAssetKeysBatcher.tsx
As titled. 
Originally tested in shadow-dagit but this time I tested in OSS and found that 10 is a better batch size
=> [Asset Overview] Update batch size to 10 + fix batching logic

python_modules/dagster-test/dagster_test/toys/asset_checks.py, python_modules/dagster/dagster/_core/definitions/asset_check_result.py, python_modules/dagster/dagster/_core/definitions/asset_layer.py, python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py, python_modules/dagster/dagster/_core/definitions/job_definition.py, python_modules/dagster/dagster/_core/execution/plan/compute.py, python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_decorator_with_check_specs.py
Support passing check specs in to `@graph_asset`s.
Added a test case and toys example with the asset promotion flow
=> asset checks on @graph_asset

docs/content/integrations/dbt.mdx, examples/docs_snippets/docs_snippets/integrations/dbt/potemkin_dag_for_cover_image.py, python_modules/libraries/dagster-dbt/dagster_dbt/core/resources.py
=> refactor(dbt): migrate tutorial cover image to use `@dbt_assets`

python_modules/libraries/dagster-census/dagster_census/resources.py
Fixes bug in issue https://github.com/dagster-io/dagster/issues/16428
I've added a `SYNC_RUN_STATUSES` set and RaiseValue check because, without it, if Census changes its API responses again, then Census sync runs proceed in an unexpected way without users knowing that something has changed and is effectively broken. I'm happy to get feedback on this change.
I've run these changes in a forked `dagster-census` integration in our prod environment.
=> [fix][dagster-census] poll_sync_run new 'queued' status

js_modules/dagster-ui/packages/ui-core/src/asset-graph/useLiveDataForAssetKeysBatcher.tsx
=> Add missing dep to react callback

python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt/cloud/asset_defs.py, python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt/include/scaffold/assets.py.jinja
Resolves https://github.com/dagster-io/dagster/issues/16214.
existing bk
=> refactor(dbt): use `AssetExecutionContext`

CHANGES.md
Summary:
I've pointed a couple of folks at this fix but the symptoms are slightly incorrect - updating them to reference the RecursionError.
=> Update changelog for recursionerror issue

docs/next/components/mdx/MDXComponents.tsx, docs/next/styles/globals.css, docs/next/tailwind.config.js, docs/sphinx/_ext/dagster-sphinx/dagster_sphinx/docstring_flags.py
Use "Experimental" and "Legacy" tag style from elsewhere in Docs within Sphinx-generated API docs.
Build docs, view site. Verify that tags appear.
=> [docs] Spruce up experimental/legacy tags in Sphinx-generated docs

python_modules/dagster-test/dagster_test/toys/asset_checks.py
=> Add assets with lots of checks to toys

python_modules/dagster-graphql/setup.py, python_modules/libraries/dagster-docker/setup.py
Summary:
requests now supports this version - the dust seems to have settled by now as per comment on https://github.com/dagster-io/dagster/pull/14089
Test Plan: BK
=> Remove urllib<2 pin in dagster-graphql and dagster-docker

python_modules/dagster/dagster/_daemon/asset_daemon.py
Summary:
This change makes it so that when the AssetDaemon materializations N partitions for a single asset in N runs, it does 2 user code calls instead of 2*n user code calls. Mirrors similar logic in the backfill daemon added in https://github.com/dagster-io/dagster/pull/13086.
Test Plan: Locally run an AMP graph of an asset with N partitions with max_materializations_per_minute set to N - add a log line whenever a user code line is called. See 2 calls instead of 2*n.
=> Cache identical user code calls in the asset daemon

python_modules/dagster-test/dagster_test/toys/asset_checks.py
=> Graph asset with multiple checks in toys

js_modules/dagster-ui/packages/ui-components/src/components/Icon.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/Run.tsx
=> [Run logs] default back to events tab again

.buildkite/dagster-buildkite/setup.py
Removed this earlier today and BK did not complain. Now it seems to be complaining again, so adding it back.
BK
=> Add back urllib3 pin

docs/sphinx/sections/api/apidocs/assets.rst, python_modules/dagster/dagster/__init__.py
its marked as @experimental already
bk
=> top level export for MaterializeResult

js_modules/dagster-ui/packages/ui-core/src/asset-graph/useLiveDataForAssetKeysBatcher.tsx
Floats are imprecise... who would have thought.
Was able to repro original issue locally
=> Fix overview asset page spam

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/schema/asset_checks.py, python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_checks.py
To populate the 'target' column of the runs page
=> Add assetCheckSelection to GrapheneRun

js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/AssetCheckStatusTag.tsx
Thought I tested this, must not have
=> Fix asset check run link

python_modules/dagster/dagster/_core/definitions/asset_layer.py, python_modules/dagster/dagster/_core/definitions/run_config.py
=> fix hash_asset_checks typo

docs/content/integrations/dbt/reference.mdx, docs/content/integrations/dbt/using-dbt-with-dagster/downstream-assets.mdx, docs/content/integrations/dbt/using-dbt-with-dagster/load-dbt-models.mdx, docs/content/integrations/dbt/using-dbt-with-dagster/upstream-assets.mdx, examples/docs_snippets/docs_snippets/integrations/dbt/dbt.py, examples/docs_snippets/docs_snippets/integrations/dbt/tutorial/downstream_assets/assets.py, examples/docs_snippets/docs_snippets/integrations/dbt/tutorial/load_dbt_models/assets.py, examples/docs_snippets/docs_snippets/integrations/dbt/tutorial/upstream_assets/assets.py
https://github.com/dagster-io/dagster/pull/16455 but for docs.
pytest
=> docs(dbt): use `AssetExecutionContext`

docs/content/concepts/assets/asset-auto-execution.mdx, examples/docs_snippets/docs_snippets/concepts/assets/auto_materialize_after_all_parents.py, examples/docs_snippets/docs_snippets/concepts/assets/auto_materialize_max_materializations_per_minute.py, examples/docs_snippets/docs_snippets/concepts/assets/auto_materialize_with_missing_parents.py, python_modules/dagster/dagster/_core/definitions/auto_materialize_rule.py
Goals here:
1. Refresh this page, correcting some inaccuracies (e.g. it said that only the last partition of time-partitioned assets would be materialized, which isn't true)
2. Explain the new AutoMaterializeRule system
3. Separate out discussion of freshness-based scheduling from the core content
=> [auto-materialize][docs] Refresh AutoMaterialize docs

python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py
Summary:
Making this a class allows the class to be overridden in a different context with different instance and workspace fixtures.
Test Plan: BK
=> Split the core test_scheduler_run tests into a class

python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py, python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py
adds an instance method for reporting runless asset events
added test
=> instance.report_runless_asset_event

scripts/run-pyright.py
=> [pyright] check=False subprocess output

js_modules/dagster-ui/packages/app-oss/package.json, js_modules/dagster-ui/packages/eslint-config/package.json, js_modules/dagster-ui/packages/ui-components/package.json, js_modules/dagster-ui/packages/ui-core/package.json, js_modules/dagster-ui/yarn.lock
Bump TS version to match VSCode in OSS.
Buildkite
=> [ui] Upgrade TS to 5.2.2

js_modules/dagster-ui/packages/ui-core/src/app/Flags.tsx, js_modules/dagster-ui/packages/ui-core/src/app/getVisibleFeatureFlagRows.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx
Add feature flag for the DAG sidebar
tested enabling/disabling the sidebar locally
=> [7/n][Asset Graph Sidebar] Feature flag it

js_modules/dagster-ui/packages/ui-core/src/app/Flags.tsx, js_modules/dagster-ui/packages/ui-core/src/app/getVisibleFeatureFlagRows.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorerSidebar.tsx
Add the folder view + make the sidebar collapsible
=> [6/n][Asset Graph Sidebar] Add folder view + Make sidebar collapsible

js_modules/dagster-ui/packages/ui-core/src/app/Flags.tsx, js_modules/dagster-ui/packages/ui-core/src/app/getVisibleFeatureFlagRows.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorerSidebar.tsx
=> [5/n][Asset Graph Sidebar] Hook up materialization to asset nodes in sidebar

docs/content/concepts/code-locations.mdx
This PR makes some minor changes to the Code Locations documentation.
👀 , local
=> [docs] [essentials] - Code Locations

docs/next/pages/_document.js
Adding an additional tracker to the docs site.
Asking Erin to test as I can't run the docs locally
=> Adding the tag to the docs site

CHANGES.md
=> 1.4.15 Changelog

python_modules/dagster-test/dagster_test/toys/asset_checks.py
=> Add a checks only job to toys

docs/content/guides/limiting-concurrency-in-data-pipelines.mdx
=> fix global ops concurrency link in docs

js_modules/dagster-ui/packages/app-oss/package.json, js_modules/dagster-ui/packages/ui-core/package.json, js_modules/dagster-ui/yarn.lock
Resolves https://github.com/dagster-io/dagster/security/dependabot/324.
Buildkite
=> [ui] Bump graphql dep

python_modules/dagster/dagster/_core/definitions/asset_check_evaluation.py, python_modules/dagster/dagster/_core/events/__init__.py
Convenience methods for asset check event data
=> Check convenience methods

docs/content/concepts/partitions-schedules-sensors/backfills.mdx, examples/docs_snippets/docs_snippets/concepts/partitions_schedules_sensors/backfills/single_run_backfill_asset.py, python_modules/dagster/dagster/_core/definitions/backfill_policy.py
Depends on https://github.com/dagster-io/dagster/pull/16709
=> add backfill policies to concept docs

python_modules/dagster-ext/dagster_ext/__init__.py, python_modules/dagster/dagster/_core/ext/utils.py
Add `dagster_ext_version` field to all ext messages.
New tests.
=> [ext] add protocol version to all messages

python_modules/dagster/dagster/_core/execution/context/hook.py
This currently results in a recursion error
=> Fix hook prop

python_modules/dagster/dagster/_core/definitions/asset_check_evaluation.py, python_modules/dagster/dagster/_core/events/__init__.py, python_modules/dagster/dagster/_core/instance/__init__.py
=> Add step key to check planned event

python_modules/dagster/dagster/_core/host_representation/external_data.py
pretty sure this would be bad so assert against it 
existing test coverage
=> add defensive check for multiple ExternalAssetNodes for same key

examples/assets_modern_data_stack/assets_modern_data_stack/__init__.py, examples/assets_modern_data_stack/assets_modern_data_stack/utils/constants.py
=> fix(dbt): use `DbtCliResource` instead of `DbtCliClientResource`

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py
If the user has already specified `DBT_TARGET_PATH`, then use it as the parent directory when creating artifact files using `DbtCliResource`.
If `DBT_TARGET_PATH` is a relative path, then continue create artifacts as a subdirectory of the dbt project directory. Otherwise, `DBT_TARGET_PATH` is an absolute path, and artifacts should be created as subdirectories of that.
pytest
=> feat(dbt): create unique target path in existing `DBT_TARGET_PATH`

python_modules/dagster/dagster/_core/telemetry.py, python_modules/dagster/dagster_tests/cli_tests/command_tests/test_telemetry.py
start with num_asset_checks. Maybe we add `num_assets_with_checks` next?
=> asset check telemetry

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py
=> [dagster-dbt] fix type annotation for compat with new context API

python_modules/dagster-graphql/dagster_graphql/implementation/utils.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_checks.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_checks.py, python_modules/dagster/dagster/_api/snapshot_execution_plan.py, python_modules/dagster/dagster/_api/snapshot_job.py, python_modules/dagster/dagster/_core/definitions/asset_check_evaluation.py, python_modules/dagster/dagster/_core/definitions/asset_check_spec.py, python_modules/dagster/dagster/_core/definitions/asset_checks.py, python_modules/dagster/dagster/_core/definitions/asset_graph.py, python_modules/dagster/dagster/_core/definitions/asset_layer.py, python_modules/dagster/dagster/_core/definitions/asset_selection.py, python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py, python_modules/dagster/dagster/_core/definitions/job_base.py, python_modules/dagster/dagster/_core/definitions/job_definition.py, python_modules/dagster/dagster/_core/definitions/reconstruct.py, python_modules/dagster/dagster/_core/definitions/repository_definition/repository_definition.py, python_modules/dagster/dagster/_core/definitions/selector.py, python_modules/dagster/dagster/_core/execution/plan/compute.py, python_modules/dagster/dagster/_core/execution/plan/execute_step.py, python_modules/dagster/dagster/_core/execution/plan/outputs.py, python_modules/dagster/dagster/_core/host_representation/external.py, python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster/_core/selector/subset_selector.py, python_modules/dagster/dagster/_core/snap/job_snapshot.py, python_modules/dagster/dagster/_core/storage/dagster_run.py, python_modules/dagster/dagster/_grpc/impl.py, python_modules/dagster/dagster/_grpc/types.py, python_modules/dagster/dagster_tests/core_tests/snap_tests/__snapshots__/test_execution_plan.ambr, python_modules/dagster/dagster_tests/definitions_tests/test_asset_check_selection.py
Context https://github.com/dagster-io/dagster/pull/16672#discussion_r1334574671
=> rename AssetCheckHandle -> AssetCheckKey

.buildkite/dagster-buildkite/dagster_buildkite/pipelines/dagster_oss_main.py
Adds an `OSS_COMPAT_SLIM` mode (set with an environment variable) to the internal compat BK pipeline. OSS pushes by default trigger an internal pipeline run with this `OSS_COMPAT_SLIM` set. Currently `OSS_COMPAT_SLIM` will only run pyright internal, but we might add other steps to it in the future.
This is a nice intermediate state between the status quo (no internal compat build at all) and previous excessive state (running entire internal pipeline for every OSS build).
This PR sets `OSS_COMPAT_SLIM` (needed because we are also setting `INTERNAL_BRANCH`).
=> Add OSS_COMPAT_SLIM mode for BK internal runs, on by default for feature branches

MIGRATION.md
=> migration guide entry for single-run backfills change

docs/content/concepts/configuration/config-schema.mdx
This PR updates the Run config docs to be in line with the Essentials v1 project.
👀 , local
=> [docs] [essentials] - Run config

python_modules/dagster/dagster/_core/pipes/client.py, python_modules/dagster/dagster/_core/pipes/context.py, python_modules/dagster/dagster/_core/pipes/subprocess.py, python_modules/libraries/dagster-databricks/dagster_databricks/pipes.py, python_modules/libraries/dagster-docker/dagster_docker/pipes.py, python_modules/libraries/dagster-k8s/dagster_k8s/pipes.py
See title. Those two renames. 
BK
=> ExtMessageHandler -> PipesMessageHandler; ExtResult --> PipesResult

python_modules/libraries/dagster-docker/dagster_docker/pipes.py, python_modules/libraries/dagster-docker/dagster_docker_tests/test_ext.py
=> ExtDocker --> PipesDockerClient

integration_tests/test_suites/k8s-test-suite/tests/test_external_asset.py, python_modules/libraries/dagster-k8s/dagster_k8s/pipes.py
=> ExtK8sPod --> PipesK8sClient

python_modules/libraries/dagster-databricks/dagster_databricks/__init__.py, python_modules/libraries/dagster-databricks/dagster_databricks/pipes.py, python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_external_asset.py
=> ExtDatabricks --> PipesDatabrickClient

python_modules/dagster-pipes/dagster_pipes/__init__.py, python_modules/dagster/dagster/_core/pipes/utils.py, python_modules/dagster/dagster_tests/execution_tests/pipes_tests/test_subprocess.py, python_modules/libraries/dagster-databricks/dagster_databricks/__init__.py, python_modules/libraries/dagster-databricks/dagster_databricks/pipes.py, python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_external_asset.py, python_modules/libraries/dagster-docker/dagster_docker/pipes.py, python_modules/libraries/dagster-k8s/dagster_k8s/pipes.py
Decision in this PR is to name this family of classes a "PipesMessageWriter" rather than "PipeableMessageWriter"
BK
=> ExtMessageWriter --> PipesMessageWriter

python_modules/dagster/dagster/_core/host_representation/external_data.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py, python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py, python_modules/dagster/dagster_tests/core_tests/host_representation_tests/test_external_data.py
Current name would really have you believe it returns an ExternalAssetGraph
=> Rename external_asset_graph_from_defs -> external_asset_nodes_from_defs

python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py, python_modules/dagster-pipes/dagster_pipes/__init__.py, python_modules/dagster-test/dagster_test/toys/asset_checks.py, python_modules/dagster/dagster/_core/definitions/asset_check_result.py, python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py, python_modules/dagster/dagster/_core/pipes/context.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py, python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_check_decorator.py, python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_decorator_with_check_specs.py, python_modules/dagster/dagster_tests/definitions_tests/test_asset_check_selection.py, python_modules/dagster/dagster_tests/definitions_tests/test_blocking_asset_checks.py, python_modules/dagster/dagster_tests/execution_tests/pipes_tests/test_subprocess.py, python_modules/dagster/dagster_tests/execution_tests/test_require_typed_event_stream.py, python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_checks.py
https://dagsterlabs.slack.com/archives/C05KFG9TETB/p1695670075179949
=> AssetCheckResult success -> passed

examples/docs_snippets/docs_snippets/concepts/assets/asset_checks/asset_with_check.py, examples/docs_snippets/docs_snippets/concepts/assets/asset_checks/metadata.py, examples/docs_snippets/docs_snippets/concepts/assets/asset_checks/orders_check.py, examples/docs_snippets/docs_snippets/concepts/assets/asset_checks/severity.py, python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_decorator_with_check_specs.py
=> success -> passed stragglers

docs/content/concepts/assets/asset-checks.mdx, examples/docs_snippets/docs_snippets/concepts/assets/asset_checks/severity.py
=> checks docs success -> passed

js_modules/dagster-ui/packages/ui-core/src/app/Flags.tsx, js_modules/dagster-ui/packages/ui-core/src/app/getVisibleFeatureFlagRows.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx, js_modules/dagster-ui/packages/ui-core/src/graph/asyncGraphLayout.ts, js_modules/dagster-ui/packages/ui-core/src/pipelines/PipelinePathUtils.tsx
Adding a kill switch in case something goes wrong with the cache
Tested this locally, flip the switch on and we use the old path again
=> [Asset-graph] Add feature flag to disable cache 

python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py
Clean up the test suite with a pytest fixture for internal and external asset graphs
=> parameterize asset graph tests

python_modules/dagster/dagster/_core/pipes/utils.py
spotted a missing rename during dogfooding
=> [easy] fix docstring import for open_pipes_session

python_modules/dagster-pipes/dagster_pipes/__init__.py, python_modules/libraries/dagster-docker/dagster_docker/pipes.py, python_modules/libraries/dagster-k8s/dagster_k8s/pipes.py
=> [pipes] fix a few typos

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, js_modules/dagster-ui/packages/ui-core/src/overview/OverviewResourcesRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/overview/types/OverviewResourcesRoot.types.ts, js_modules/dagster-ui/packages/ui-core/src/resources/WorkspaceResourcesRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/resources/types/WorkspaceResourcesRoot.types.ts, js_modules/dagster-ui/packages/ui-core/src/search/types/useGlobalSearch.types.ts, js_modules/dagster-ui/packages/ui-core/src/search/useGlobalSearch.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/types/WorkspaceContext.types.ts, python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster-graphql/dagster_graphql/schema/external.py, python_modules/dagster-graphql/dagster_graphql/schema/resources.py
Introduces an id field to external resource and asset group objects
=> [gql] add id to resource, asset group gql objects

js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/AssetAutomaterializePolicyPage.tsx
I also checked the other tabs with my browser viewport really short and verified they all work
=> [ui] Scrolling fix for the auto-materialize policy page

js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetLiveDataProvider.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-data/__tests__/AssetLiveDataProvider.test.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/Node.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/Sidebar.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/util.ts, js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/util.tsx
Show status dots in the sidebar
https://www.loom.com/share/3dc890c004d24421939eb4532b797d5f
=> [Asset graph] Show status dot in sidebar

MIGRATION.md
=> 1.5.0 Migration guide

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_checks.py
=> feat(dbt): add `invocation_id` to emitted events as metadata

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/implementation/fetch_ticks.py, python_modules/dagster-graphql/dagster_graphql/schema/instigation.py, python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_auto_materialize_asset_evaluations.py
Summary:
New top-level field that queries the list of AMP ticks, similar query pattern to the sensor ticks query
=> Graphql fields for AMP ticks

python_modules/dagster/dagster/_core/definitions/auto_materialize_rule.py, python_modules/dagster/dagster/_utils/caching_instance_queryer.py
Was browsing this code, and made some changes along the way to address confusions I encountered.
=> clarity improvements for skip_on_parent_outdated rule

CHANGES.md
https://github.com/dagster-io/dagster/blob/09-29-1.5.0_changelog/CHANGES.md
=> 1.5.0 changelog

python_modules/libraries/dagster-databricks/README.md
=> [pipes] update databricks README

python_modules/dagster-pipes/dagster_pipes/__init__.py, python_modules/dagster/dagster/_core/pipes/client.py, python_modules/dagster/dagster/_core/pipes/context.py, python_modules/dagster/dagster/_core/pipes/subprocess.py, python_modules/dagster/dagster/_core/pipes/utils.py
Add docstrings to `dagster-pipes` exports/public methods.
Existing test suite (docstrings added to published API docs upstack).
=> [pipes] dagster_pipes docstrings

python_modules/dagster-pipes/dagster_pipes/__init__.py
- Add validation of user-passed metadata type
- Add validation that value is JSON-serializable for `encode_env_var`
=> [pipes] add a few validations

python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py
=> Test asset graph subsets on external asset graph

CHANGES.md
Add a note about dagster insights to the Cloud section of the changelog
=> Add note about dagster insights to cloud section in the changelog

js_modules/dagster-ui/packages/ui-core/src/assets/LaunchAssetChoosePartitionsDialog.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/LaunchAssetExecutionButton.test.tsx
This blocks Cloud users whose user code versions are pinned < 1.5.0 to not use backfill policy and not launch asset backfills as single runs.
We should gate this UI by adding an OSS hook and then checking user code dagster versions in Cloud.
This reverts commit 73123b5b99ed11eeca84e126da3789a0c324b95e.
BK
=> Revert "[ui] Remove ability to launch an asset backfill as a single run (#16737)

CHANGES.md
=> 1.5.0 changelog fix

docs/content/integrations/dbt/reference.mdx, examples/docs_snippets/docs_snippets/integrations/dbt/dbt.py
=> docs(dbt): add reference to enable asset checks

CHANGES.md
=> 1.5.0 changelog docs link fix

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_asset_checks.py, python_modules/dagster/dagster/_core/definitions/asset_checks.py, python_modules/dagster/dagster/_core/host_representation/external_data.py, python_modules/dagster/dagster/_core/storage/event_log/base.py, python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py, python_modules/dagster/dagster/_core/storage/legacy_storage.py, python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py, python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_check_decorator.py, python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_decorator_with_check_specs.py, python_modules/dagster/dagster_tests/definitions_tests/test_materialize_result.py, python_modules/dagster/dagster_tests/execution_tests/pipes_tests/test_subprocess.py, python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
Rename and take an AssetCheckKey
=> refactor get_asset_check_executions

python_modules/dagster/dagster_tests/definitions_tests/test_materialize_result.py
=> fixed missed get_asset_check_execution_history callsite

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/schema/solids.py
saw an error from someone hitting these, remove them from the schema 
bk
=> [graphql] remove solidDefinition from input & output def

js_modules/dagster-ui/packages/ui-core/src/app/Util.tsx
Hashing the key
Loaded the asset graph and saw it working
=> [Asset graph] Hash the key used for layout cache

docs/content/concepts/assets/asset-checks.mdx, examples/docs_snippets/docs_snippets/concepts/assets/asset_checks/jobs.py
=> asset check jobs docs

CHANGES.md
https://github.com/dagster-io/dagster/blob/10-03-1.5.1_changelog/CHANGES.md
=> 1.5.1 changelog

js_modules/dagster-ui/packages/ui-core/src/ui/GraphQueryInput.tsx
=> [Asset-graph] Update copy inside the ops query info dialog

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/implementation/fetch_auto_materialize_asset_evaluations.py, python_modules/dagster-graphql/dagster_graphql/schema/auto_materialize_asset_evaluations.py, python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_auto_materialize_asset_evaluations.py, python_modules/dagster/dagster/_core/scheduler/instigation.py, python_modules/dagster/dagster/_core/storage/schedules/sql_schedule_storage.py
Summary:
Expose a new field that takes in an evaluation ID and returns all the evaluation records for that ID.
Test Plan: BK
=> Graphql call for querying evaluations by evaluation ID

docs/dagster-university/package.json, docs/dagster-university/yarn.lock, docs/next/components/mdx/MDXComponents.tsx, docs/next/package.json, docs/next/yarn.lock, js_modules/dagster-ui/packages/app-oss/package.json, js_modules/dagster-ui/yarn.lock
A number of dependabot alerts came up. Fix them by upgrading Nextjs and otherwise cleaning up dependencies.
Also fixed a lint error in dagster-university.
`yarn why zod` in all three projects, verify that none remain.
`yarn why postcss` in all three projects, verify that all of them are now up to date to the required version.
TS, lint.
=> [ui] Dependabot fixes for zod, postcss

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_checks.py, python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
tests for https://github.com/dagster-io/internal/pull/7115
=> test check cursoring

js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/AssetCheckStatusTag.tsx
Per https://github.com/dagster-io/dagster/discussions/16730#discussioncomment-7086234
=> checks warning -> failed

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_asset_checks.py
=> remove commented out block

docs/content/integrations/bigquery/using-bigquery-with-dagster.mdx
=> [docs] update bigquery guide to use pyobject

docs/content/dagster-cloud/managing-deployments/setting-up-alerts.mdx
As the title. Also changes run/job based language to be asset-centric.
=> Add docs for asset-based alerting

python_modules/dagster/dagster/_core/definitions/asset_check_spec.py
=> fix typo in asset check spec docstring

docs/content/integrations/dbt/reference.mdx
=> update dbt reference to use new recommended partition API

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_asset_checks.py
We shouldn't raise this error unless a code location for an included check is < 1.5
=> fix checks 1.5 error for other code locations

docs/content/guides/dagster-pipes/customizing-dagster-pipes-protocols.mdx, docs/content/guides/dagster-pipes/integrating-databricks-with-dagster-pipes.mdx, docs/content/guides/dagster-pipes/integrating-docker-with-dagster-pipes.mdx, docs/content/guides/dagster-pipes/integrating-kubernetes-with-dagster-pipes.mdx, docs/content/guides/dagster-pipes/integrating-subprocess-with-dagster-pipes.mdx, docs/content/guides/dagster-pipes/understanding-dagster-pipes.mdx
This PR adds placeholder pages for the Dagster Pipes documentation.
👀
=> [docs] [pipes] - Add placeholder pages

python_modules/libraries/dagster-dbt/dagster_dbt/cloud/cli.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud/test_cli.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud/utils.py
Resolves https://github.com/dagster-io/dagster/issues/17056.
pytest
=> feat(dbt-cloud): allow configuration of dbt cloud host in the `dagster-dbt-cloud` CLI

examples/project_dagster_university_start/.devcontainer/Dockerfile, examples/project_dagster_university_start/.devcontainer/devcontainer.json
This adds a devcontainer for Dagster University, allowing for a consistent development environment for the course.
=> Add Dagster University DevContainer

docs/content/concepts/webserver/graphql-client.mdx, python_modules/dagster-graphql/dagster_graphql/client/client.py
Unexperimentalizing graphql client, which has been around for 2+ years
BK
=> remove experimental tag for python client

python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_check_decorator.py
When working on a PR related to source assets, I found myself wanting to be sure that this was the case.
=> test that IO manager not invoked with @asset_check

python_modules/dagster-pipes/dagster_pipes/__init__.py
We updated the var but not the value.
Can we even do this now that we're past 1.5.0 ?
If we are not aleady past the point of no return we better do this now. 
bk
=> [pipes] IS_DAGSTER_PIPED_PROCESS -> IS_DAGSTER_PIPES_PROCESS

docs/content/guides/dagster-pipes/modifying-existing-code-to-work-with-dagster-pipes.mdx
this page was missing in https://github.com/dagster-io/dagster/pull/17057
this should fix the test for https://github.com/dagster-io/dagster/pull/17048
=> [docs][pipes] - Add empty modifying page

js_modules/dagster-ui/packages/ui-components/src/components/BaseTag.tsx, js_modules/dagster-ui/packages/ui-core/src/ticks/DryRunRequestTable.tsx
As titled fixing this bug
Also fixed the tooltip not showing up on tags
note that the second tag in the image is being hovered
=> Fix tags in test schedule modal overflowing table

CHANGES.md
=> 1.5.2 changelog

CHANGES.md
=> Update CHANGES.md for 1.5.2

python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_decorator.py
=> enable setting backfill_policy on @dbt_assets

python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_all_snapshot_ids.ambr, python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_solids.ambr
fixes tests broken in https://github.com/dagster-io/dagster/pull/17105
=> [external assets] fixup snapshot refresh

docs/content/dagster-cloud/insights.mdx, docs/content/dagster-cloud/insights/integrating-external-metrics.mdx, docs/content/dagster-cloud/insights/integrating-snowflake-and-dbt.mdx
This builds on #17119. It adds a note about an Enterprise only feature to relevant guides and formats/edits some of the concept page copy.
👀
=> [docs] [insights] - Update/format insights changes

examples/experimental/external_assets/airflow_example.py, examples/experimental/external_assets/external_assets/pipes/__init__.py, examples/experimental/external_assets/pipes/join_iot.py
adds an example of using partition's with pipes and how an equivalent solution would look like in airflow
=> [demo][pipes] add partitions to iot asset + airflow k8s example code

python_modules/dagster-webserver/dagster_webserver/external_assets.py, python_modules/dagster-webserver/dagster_webserver/webserver.py, python_modules/dagster-webserver/dagster_webserver_tests/webserver/test_app.py, python_modules/dagster-webserver/dagster_webserver_tests/webserver/test_asset_events.py
to better group these for coming other endpoints
bk
=> [external assets] move api endpoint code & tests

js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadHooksContext.tsx, js_modules/dagster-ui/packages/ui-core/src/ui/Filters/useStaticSetFilter.tsx
Updating the type here for cloud
👀
=> Update StaticSetFilterSorter type

python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_decorator.py
This enables using dbt_assets with op-level concurrency limits.
=> add op_tags argument to @dbt_assets

docs/content/deployment/guides/kubernetes/customizing-your-deployment.mdx
=> Docs to explain merge_behavior: DEEP in k8s configuration

docs/content/dagster-cloud/deployment/agents/running-multiple-agents.mdx
multiple agents have been supported for ~2 years, seems stable.
BK
=> remove experimental tag for running multiple agents

docs/content/integrations/dbt/reference.mdx, examples/docs_snippets/docs_snippets/integrations/dbt/dbt.py
As the title. Don't need this anymore after https://github.com/dagster-io/dagster/pull/16217.
N/A
=> docs(dbt): remove empty manifest reference

python_modules/dagster/dagster/_core/definitions/op_definition.py, python_modules/dagster/dagster/_core/execution/plan/compute_generator.py, python_modules/dagster/dagster_tests/definitions_tests/test_materialize_result.py
update expectations around return typing to handle `MaterializeResult`
updated tests
=> handle MaterializeResult output typing with checks

python_modules/dagster-pipes/dagster_pipes/__init__.py, python_modules/dagster/dagster_tests/execution_tests/pipes_tests/test_subprocess.py, python_modules/libraries/dagster-aws/dagster_aws/pipes.py
Add an S3 context injector/loader. I thought we already had this (we have DBFS) but now IIRC we didn't add it in the past because we thought the env var one would be sufficient, but it turns out people like these blob store injectors.
New unit test.
=> [pipes] add s3 context injector

python_modules/dagster/dagster/_core/execution/plan/instance_concurrency_context.py, python_modules/dagster/dagster_tests/core_tests/execution_tests/test_instance_concurrency_context.py
Instead of checking every second, we can check every 10 seconds (backing off exponentially), to grab concurrency slots.  Will relieve any db pressure just from checking contentious rows.  Shouldn't affect starvation, since we still have priority checks.
BK
=> add default support for backing off of checking concurrency claims

CHANGES.md
=> Changelog 1.5.3

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_decorators.py
follow up to https://github.com/dagster-io/dagster/pull/15384, adds config to the multi asset variant decorator.
updated tests
=> add config to @graph_multi_asset

python_modules/dagster-webserver/dagster_webserver/external_assets.py, python_modules/dagster-webserver/dagster_webserver/webserver.py, python_modules/dagster-webserver/dagster_webserver_tests/webserver/test_asset_events.py
adds a rest endpoint for reporting runless asset check evaluations
added test
=> [external assets] report_asset_check endpoint

js_modules/dagster-ui/packages/ui-core/src/app/QueryRefresh.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/auto-materialization/AssetDaemonTicksQuery.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/auto-materialization/AutomaterializationRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/auto-materialization/types/AssetDaemonTicksQuery.types.ts
=> Limit AMP ticks query to 15

examples/experimental/external_assets/external_assets/pipes/__init__.py, python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_check_decorator.py, python_modules/dagster/dagster_tests/definitions_tests/test_blocking_asset_checks.py, python_modules/dagster/dagster_tests/execution_tests/pipes_tests/test_in_process_client.py
Updates all uses of `@asset_check` with a `context` to have a type annotated `context`
=> Update asset_check uses to have type annotated context 

examples/project_dagster_university_start/.devcontainer/devcontainer.json
Adds a label when using devcontainers, thanks to @davidgasquez!
=> [examples] Adds port attributes to Dagster University VS Code DevConatiners

python_modules/dagster/dagster/_core/definitions/op_definition.py, python_modules/dagster/dagster_tests/definitions_tests/test_materialize_result.py
further bypass of type annotation resultion, this time with tuples of materialize results 
added tests
=> handle output typing tuple MaterializeResult with checks

docs/content/concepts/assets/graph-backed-assets.mdx, examples/docs_snippets/docs_snippets/concepts/assets/graph_backed_asset.py
Updates an example that never got updated to pythonic resources
=> [quick][docs] update example to use pythonic resources

docs/sphinx/sections/api/apidocs/external-assets.rst, python_modules/dagster-webserver/dagster_webserver/external_assets.py, python_modules/dagster-webserver/dagster_webserver_tests/webserver/test_asset_events.py
add api docs content for `report_asset_check` and define how `passed` is handled as a query parameter  (json bool)
added test
=> [rest api] report_asset_check docs and tweaks

CHANGES.md
=> 1.5.4 changelog

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/resources.py, python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/test_assets.py
=> Remove unused import and fix linting error

docs/content/dagster-cloud/deployment/agents/running-multiple-agents.mdx
Summary:
Missed a spot when doing the update looks like.
Test Plan: eyes
=> update multiple agents docs to reference isolatedAgents instead of agentReplicas

helm/dagster/schema/schema_tests/test_dagit.py, helm/dagster/schema/schema_tests/test_dagster_daemon.py
=> fix helm configmap test

.buildkite/dagster-buildkite/dagster_buildkite/steps/helm.py
Changes like https://buildkite.com/dagster/dagster/builds/69392 should get these tests
=> run helm schema tests on helm changes

docs/content/getting-started.mdx
This PR adds a link to Dagster University to the docs landing page.
👀
=> [docs] - Add DU to landing page

python_modules/dagster/dagster/_core/definitions/load_assets_from_modules.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_assets_from_modules.py
=> bugfix: respect source_key_prefix

azure-pipelines.yml
Fixes tox factors to include the pydantic 1, pydantic 2 suites
=> Fix tox factors for windows

python_modules/dagster/dagster/_utils/caching_instance_queryer.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_assets_from_modules.py
Two nits that my local ruff complains on. ~~not sure what's different vs bk~~
=> ruff format on master

python_modules/dagster/dagster/_config/pythonic_config/type_check_utils.py, python_modules/dagster/dagster/_core/definitions/load_asset_checks_from_modules.py, python_modules/dagster/dagster_tests/definitions_tests/asset_check_tests/test_load_from_modules.py
=> load_asset_checks_from_current_module

js_modules/dagster-ui/packages/ui-core/src/assets/CalculateChangedAndMissingDialog.tsx
Fixes the middle truncate behavior
=> Add overflow hidden to middletruncate wrapper

docs/content/concepts/webserver/graphql-client.mdx, docs/content/dagster-cloud/account/authentication/okta/scim-provisioning.mdx, docs/content/dagster-cloud/account/managing-user-agent-tokens.mdx, docs/content/dagster-cloud/account/managing-users.mdx, docs/content/dagster-cloud/account/managing-users/managing-teams.mdx, docs/content/dagster-cloud/account/managing-users/managing-user-roles-permissions.mdx, docs/content/dagster-cloud/insights/exporting-insights-metrics.mdx, docs/content/dagster-cloud/managing-deployments/managing-deployments.mdx, docs/next/components/mdx/includes/dagster-cloud/GenerateAgentToken.mdx, examples/docs_snippets/docs_snippets/concepts/webserver/graphql/client_example.py
This PR renames the **Cloud Settings** page to the **Organization Settings** page.
👀
=> [docs] [cloud] - Cloud Settings > Organization Settings

python_modules/dagster/dagster/_core/definitions/load_asset_checks_from_modules.py, python_modules/dagster/dagster/_core/definitions/load_assets_from_modules.py, python_modules/dagster/dagster_tests/definitions_tests/asset_check_tests/checks_module/checks_submodule/__init__.py, python_modules/dagster/dagster_tests/definitions_tests/asset_check_tests/test_load_from_modules.py
load_asset_checks_from_package_module and load_asset_checks_from_package_name
=> load_asset_checks_from_package_*

CHANGES.md
=> Changelog for 1.5.5

js_modules/dagster-ui/packages/ui-core/src/instance/CodeLocationsPage.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/flattenCodeLocationRows.tsx
Move flattening/filtering code locations into a hook to be reused in Cloud.
Buildkite. Verify that the flattened and filtered lists work correctly in code location list.
=> [ui] Use a utility to supply flattening/filtering on code locations

python_modules/dagster/dagster/_core/telemetry.py, python_modules/dagster/dagster_tests/cli_tests/command_tests/test_telemetry.py
=> num_assets_with_checks telemetry

python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py
User reporting error while deleting run.
Inspection, BK
=> ensurethat unmigrated instances can delete runs

python_modules/libraries/dagster-mysql/dagster_mysql_tests/test_event_log.py
Turn the build green while we track down the cause in https://dagsterlabs.slack.com/archives/C03EQ628RS7/p1698681598868299
=> skip mysql test_materialization_tag_on_wipe

docs/content/_navigation.json, docs/content/getting-started/getting-help.mdx
The aim is to link to this page from the #dagster-support Slack channel
=> add Getting Help page to docs community section

python_modules/dagster/dagster_tests/scheduler_tests/test_cron_string_iterator.py
Summary:
We have some evidence that croniter doesn't always behave the same way depending on what start timestamp you pass in. To ensure that our existing workarounds for bad croniter upstream behavior don't break, augment our tests to check a range of timestamps between one tick and the next and verify that it awlays advances (luckily, it does).
Test Plan: BK
=> Ensure that existing croniter workaround tests cover all timestamps between the previous tick and the next tick

python_modules/dagster/dagster/_core/storage/db_io_manager.py, python_modules/dagster/dagster_tests/storage_tests/test_db_io_manager.py, python_modules/libraries/dagster-duckdb/dagster_duckdb/io_manager.py, python_modules/libraries/dagster-gcp/dagster_gcp/bigquery/io_manager.py, python_modules/libraries/dagster-snowflake/dagster_snowflake/snowflake_io_manager.py
#17389
Added additional assertions to `test_asset_schema_defaults` successful
``` bash
pytest -s python_modules/dagster/dagster_tests/storage_tests/test_db_io_manager.py -k test_asset_schema_defaults
```
=> 17389 schema metadata

python_modules/libraries/dagster-dbt/dagster_dbt/asset_defs.py, python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_checks.py
Resolves https://github.com/dagster-io/dagster/issues/17292.
pytest
=> fix(dbt): yield `AssetMaterialization` when invoking `DbtCliResource` in ops

js_modules/dagster-ui/packages/ui-core/src/runs/RunsFilterInput.tsx
https://dagsterlabs.slack.com/archives/C03CCE471E0/p1696886835362699
locally:
=> [Runs filters] Dont allow multiple selections for launched by filter

js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetLiveDataProvider.tsx
As titled
Loaded dagit, killed the server, started it again
=> [AssetLiveDataProvider] Fix passing poll rate in case of an error

python_modules/dagster/dagster/_core/pipes/context.py, python_modules/dagster/dagster/_core/pipes/utils.py
Establish a pattern with message reader threads to report exceptions to the handler. 
manually tested with the s3 message reader and not having aws auth. Previously it would fail silently but now reports as:
will add test coverage if we like this approach
=> [pipes] add report_component_exception

CHANGES.md
=> 1.5.6 Changelog

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_checks.py
Replaced by AssetNode.assetChecksOrError
=> Remove AssetNode.assetChecks resolver

python_modules/dagster-graphql/dagster_graphql/implementation/asset_checks_loader.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_checks.py
=> typo and rename

docs/content/concepts/assets/asset-checks.mdx, docs/sphinx/sections/api/apidocs/asset-checks.rst, examples/docs_snippets/docs_snippets/concepts/assets/asset_checks/factory.py, python_modules/dagster/dagster/__init__.py
=> export AssetChecksDefinition

python_modules/dagster/dagster/_utils/schedules.py, python_modules/dagster/dagster_tests/scheduler_tests/test_cron_string_iterator.py, python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_timezones.py
This is actually easier than daily schedules and has correctness (and possibly performance) implications, so we should just do it.
Test Plan: BK
=> Expand croniter divesting to hourly schedules

python_modules/dagster/dagster/_utils/schedules.py, python_modules/dagster/dagster_tests/scheduler_tests/test_cron_string_iterator.py
Same strategy as https://github.com/dagster-io/dagster/pull/17499, but for monthly schedules too.
BK
=> expand croniterless support to monthly schedules

python_modules/dagster/dagster/_utils/schedules.py
Now that we have a custom get_prev implementation for daily/hourly/weekly/monthly schedules, we can run a version of cron_string_iterator that never touches croniter, and relegate it just for fancier cronstrings.
It's probably not a huge lift to expand our support for these additional cronstrings (*/15, 8,11,12 etc.) and maybe we can eventually remove croniter entirely or remove non-UTC support for the very small number of schedules that use it?
=> Fully croniter-free cron_string_iterator for daily/weekly/monthly/schedules

python_modules/dagster/dagster/_utils/schedules.py
Summary:
These two methods were still duplicating lots of code. Use an "ascending" argument instead while sharing the core loop.
=> Fully merge reverse_cron_string_iterator into cron_string_iterator

js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadSession.tsx, python_modules/dagster-test/dagster_test/toys/partition_config.py, python_modules/dagster-test/dagster_test/toys/repo.py
Fixes https://github.com/dagster-io/dagster/issues/17522
created a job in the toys repository to test this
=> Fix merging partition config into existing launchpad config

python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py, python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
[INTERNAL_BRANCH=prha/assign_pending_steps]
Getting into a situation now where an assigned step that is removed before claiming a slot is roadblocking all other pending steps
BK
=> reassign freed pending steps, instead of freed slots

js_modules/dagster-ui/yarn.lock
Resolves https://github.com/dagster-io/dagster/security/dependabot/350.
BK
=> [ui] Update browserify-sign for dependabot

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/asset_defs.py, python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/resources.py, python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/test.csv, python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/test_assets.py, python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/test_resource.py
Fixes an issue where the incorrect type was set for the `updated_at` parameter.
Fixes #17348 
Added a test
=> [dagster-embedded-elt] Fix Updated At parameter's incorrect type

python_modules/dagster/README.md
=> remove star ask from top of README

python_modules/dagster/README.md
=> clarify supported python versions in README

python_modules/dagster/dagster/_utils/schedules.py
Summary:
Ensure that schedules like */15 and */30 aren't adversely affected by the correctness improvements in https://github.com/dagster-io/dagster/pull/17710
Test Plan:
Existing BK covers examples that match the new logic (e.g. */15 * * * *)
=> Support multiple minutes in hourly schedules

js_modules/dagster-ui/packages/ui-core/src/runs/RunsFilterInput.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/RunsRoot.tsx
Addresses https://github.com/dagster-io/dagster/issues/17060
Locally
=> [Runs Table] Allow filtering by partition

python_modules/dagster/dagster/_core/definitions/auto_materialize_rule.py
=> small code clarity updates in auto_materialize_rule.py

python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/perf/test_asset_daemon_perf.py
Looks like this was running a little too close to the limit.
=> [auto-materialize][perf] bump limit

python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster/_daemon/sensor.py, python_modules/dagster/dagster/_scheduler/scheduler.py
Summary:
For easier overridability
Test Plan: BK
=> Move scheduler/sensor settings to a field on the instance

docs/content/concepts/assets/asset-checks.mdx
=> checks scaling limit in docs

js_modules/dagster-ui/packages/ui-core/src/app/getVisibleFeatureFlagRows.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGroupNode.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNode.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/CollapsedGroupNode.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/ExpandedGroupNode.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/Utils.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/assetKeyTokensInRange.ts, js_modules/dagster-ui/packages/ui-core/src/asset-graph/layout.ts, js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/Node.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/Sidebar.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeLineageGraph.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetsGroupsGlobalGraphRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/graph/OpGraph.tsx, js_modules/dagster-ui/packages/ui-core/src/graph/SVGViewport.tsx, js_modules/dagster-ui/packages/ui-core/src/graph/asyncGraphLayout.ts, js_modules/dagster-ui/packages/ui-core/src/graph/common.ts
https://www.loom.com/share/051e525e97f242448dd08ecc5a2ef5a5?sid=e37d5247-beea-42ae-9179-cb7e466a30fb
=> [ui] Collapsing groups on the global asset graph

examples/quickstart_aws/quickstart_aws/assets/hackernews.py, examples/quickstart_aws/setup.py
updating quickstart_aws to match 1.5
=> updating quickstart_aws to match 1.5

examples/quickstart_etl/quickstart_etl/assets/hackernews.py, examples/quickstart_etl/setup.py
=> Updating quickstart_etl to match 1.5

examples/README.md, examples/assets_modern_data_stack/README.md, examples/assets_pandas_pyspark/README.md, examples/assets_pandas_type_metadata/README.md, examples/project_analytics/README.md, examples/project_fully_featured/README.md, examples/tutorial_notebook_assets/README.md, examples/with_great_expectations/README.md, examples/with_pyspark/README.md, examples/with_pyspark_emr/README.md
To start off the example update progress, added a README to the examples directory and marked some specific examples as `UNMAINTAINED` as we'll keep them, but not ensure updating them.
=> [examples] Adding docs about example states

python_modules/dagster/dagster/_core/instance/__init__.py
Motivated by: https://github.com/dagster-io/dagster/discussions/17847
=> make DagsterInstance.report_runless_asset_event public

js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillPage.tsx
Fix for issue described here: https://dagsterlabs.slack.com/archives/C03CA4TVCAW/p1699554612573519
I tested this by creating an asset backfill that includes non-partitioned assets and more than one partition key range.
=> [ui] Fix the link from backfill to asset details for un-partitioned assets

docs/content/concepts/assets/asset-auto-execution.mdx, examples/docs_snippets/docs_snippets/concepts/assets/auto_materialize_on_cron.py
=> [auto-materialize] Add docs for the MaterializeOnCronRule

python_modules/dagster/dagster/_core/definitions/events.py
=> remove commented-out from_coercible_to_asset_dep

python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_checks.py
less confusing than testing two things in one case
=> separate dbt checks test cases

docs/content/guides/dagster/branch_deployments.mdx, examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/branch_deployments/clone_and_drop_db.py, examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/branch_deployments/repository_v2.py
I user had some questions about the branch deployment guide, and I noticed it uses some out of date APIs for pythonic resources. This updates it
=> [docs] update pythonic resources in branch deployment guide

python_modules/libraries/dagster-airbyte/dagster_airbyte/asset_defs.py, python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py
Addresses #17842.
Updates the load-from-instance logic for Fivetran & Airbyte to bind a not-fully-initialized copy of the resource instead of the fully initialized copy which has already processed EnvVars. This prevents env var values from showing up in the launchpad.
Sanity checked locally.
=> [dagster-fivetran][dagster-airbyte] Properly handle EnvVar when loading ETL assets from instance

python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_checks.py
improve the existing test coverage with asserts on the materializations and check evaluations
=> test dbt check selection results

python_modules/dagster/dagster/_core/definitions/events.py
=> fix typos in Output docstring

python_modules/libraries/dagster-snowflake/setup.py
3.5.0 includes drastic changes which seem to break things (at least tests)
bk
=> pin snowflake-connector-python

CHANGES.md
changelog for cherry-pick release today
=> [changelog] 1.5.8 cherry-pick release changelog

python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
=> fix typo in TimeWindowPartitionsDefinition docstring

python_modules/dagster/dagster/_core/storage/dagster_run.py, python_modules/dagster/dagster_tests/storage_tests/test_dagster_run.py, python_modules/dagster/dagster_tests/storage_tests/test_job_run.py
Am I missing somewhere this is used? Somewhere in user space? If not, any reason to keep it?
=> Remove RunsFilter serialization?

python_modules/libraries/dagster-msteams/dagster_msteams/hooks.py, python_modules/libraries/dagster-msteams/dagster_msteams_tests/test_hooks.py
addresses https://github.com/dagster-io/dagster/issues/17896
this PR handles resource api differently according the resource type. cuirous if there's a more elegant way
unit
=> fix msteams hook for pythonic resource

docs/content/deployment/dagster-instance.mdx
the scheme has changed from this
eyes
=> [docs] correct old compute logs layout reference

python_modules/dagster/dagster/_core/execution/plan/execute_plan.py, python_modules/dagster/dagster_tests/execution_tests/test_retries.py
feature request, hoist the Failure `metadata` when retries are exceeded or disabled
added test
=> hoist Failure metadata on retry failures

python_modules/libraries/dagster-deltalake/dagster_deltalake/handler.py
=> [fix] fix pyright err

CHANGES.md
changelog
eyes https://github.com/dagster-io/dagster/blob/e8256bca5ddb7d0bdcc60db924a5567c7e9b0d6e/CHANGES.md
=> 1.5.9 changelog

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py, python_modules/dagster/dagster/_core/definitions/decorators/source_asset_decorator.py, python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_source_asset_decorator.py
Inspired by this question: https://github.com/dagster-io/dagster/discussions/17648
=> key argument on observable_source_asset decorator

python_modules/libraries/dagster-managed-elements/dagster_managed_elements/types.py
i skipped running the build because it was so simple, got owned 
make ruff
=> fix ruff from oss commit

python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_evaluation.py
=> add type to RuleEvaluationResults

js_modules/dagster-ui/packages/ui-core/src/app/Flags.tsx, js_modules/dagster-ui/packages/ui-core/src/app/getVisibleFeatureFlagRows.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/layout.ts, js_modules/dagster-ui/packages/ui-core/src/graph/asyncGraphLayout.ts, js_modules/dagster-ui/packages/ui-core/src/graph/layout.ts
=> Remove longest path asset graph layout

python_modules/dagster/dagster/_core/definitions/time_window_partition_mapping.py, python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_time_window_partition_mapping.py
Summary:
This plus the additional hourly DST fixes lets the new test case pass without issue.
Test Plan: BK
=> Fix datetime comparisons during partition mapping

python_modules/dagster/setup.py
unused, the yamllint bk stuff installs it on its own
=> remove yamllint test dep

python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_time_window_partition_mapping.py
Summary:
Race condition between two PRs landing - bring up to date with the latest API.
Test Plan: BK
=> Fix broken time window partition mapping test

.buildkite/dagster-buildkite/dagster_buildkite/steps/dagster.py, .buildkite/dagster-buildkite/dagster_buildkite/utils.py
=> add prettier to bk

python_modules/dagster/dagster/_core/definitions/schedule_definition.py, python_modules/dagster/dagster_tests/definitions_tests/test_schedule_invocation.py
resolves https://github.com/dagster-io/dagster/issues/18070
added test
=> fix schedule context logger

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/resources.py, python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/test_assets.py
Resolves an issue when non-unicode output is emitted from Sling's stdout process. 
Closes #17966. 
Unit-tests
=> [dagster-embedded-elt] Support non-unicode standard out

js_modules/dagster-ui/packages/ui-core/src/instigation/TickHistory.tsx
We should be refreshing the data in this table
👀 
locally
=> Refresh sensor table data

python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py, python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/test_launching.py
useful for debugging what exactly caused the stop 
exiting test coverage
=> [ecs] include container exit code in failure message

docs/content/dagster-cloud/insights/integrating-snowflake-and-dbt.mdx, docs/content/dagster-cloud/insights/integrating-snowflake.mdx
Fix small typo in insights docs
=> [docs] fix typo in insights docs

python_modules/dagster-test/dagster_test/toys/sensors.py, python_modules/dagster-test/dagster_test_tests/test_toys.py
This thing doesn't currently work - this makes it work.
=> Fix math_sensor

js_modules/dagster-ui/packages/ui-components/src/palettes/LegacyPalette.tsx, js_modules/dagster-ui/packages/ui-components/src/theme/theme.tsx
Add a legacy theme to keep the colors mostly unchanged while working on the new palettes.
=> Add legacy palette

python_modules/dagster/dagster/_core/definitions/auto_materialize_rule.py
Summary:
Believe the comment here reflects the original plan for the filter but not the plan that ended up shipping.
Test Plan: Eyes
=> Update comment on AutoMaterializeAssetPartitionsFilter

docs/content/integrations/bigquery/reference.mdx, docs/content/integrations/duckdb/reference.mdx, docs/content/integrations/snowflake/reference.mdx, examples/docs_snippets/docs_snippets/integrations/bigquery/reference/dataset.py, examples/docs_snippets/docs_snippets/integrations/duckdb/reference/schema.py, examples/docs_snippets/docs_snippets/integrations/snowflake/schema.py, python_modules/dagster/dagster/_core/storage/db_io_manager.py, python_modules/dagster/dagster_tests/storage_tests/test_db_io_manager.py, python_modules/libraries/dagster-duckdb-pandas/dagster_duckdb_pandas/duckdb_pandas_type_handler.py, python_modules/libraries/dagster-duckdb-polars/dagster_duckdb_polars/duckdb_polars_type_handler.py, python_modules/libraries/dagster-duckdb-pyspark/dagster_duckdb_pyspark/duckdb_pyspark_type_handler.py, python_modules/libraries/dagster-duckdb/dagster_duckdb/io_manager.py, python_modules/libraries/dagster-gcp-pandas/dagster_gcp_pandas/bigquery/bigquery_pandas_type_handler.py, python_modules/libraries/dagster-gcp-pyspark/dagster_gcp_pyspark/bigquery/bigquery_pyspark_type_handler.py, python_modules/libraries/dagster-gcp/dagster_gcp/bigquery/io_manager.py, python_modules/libraries/dagster-snowflake-pandas/dagster_snowflake_pandas/snowflake_pandas_type_handler.py, python_modules/libraries/dagster-snowflake-pyspark/dagster_snowflake_pyspark/snowflake_pyspark_type_handler.py, python_modules/libraries/dagster-snowflake/dagster_snowflake/snowflake_io_manager.py
See https://github.com/dagster-io/dagster/pull/17904 for a description of the schema changes being made. This PR updates the docs for all of the DB IO managers to reflect the changes to how the schema is determined
=> [docs] update DB IO manager docs to reflect schema changes

python_modules/dagster/dagster_tests/asset_defs_tests/test_unresolved_asset_job.py
Improving a test from a community contribution.
=> improve test for op_retry_policy on define_asset_job

python_modules/dagster-graphql/dagster_graphql/schema/instigation.py, python_modules/dagster/dagster/_api/snapshot_sensor.py, python_modules/dagster/dagster/_cli/sensor.py, python_modules/dagster/dagster/_core/definitions/multi_asset_sensor_definition.py, python_modules/dagster/dagster/_core/definitions/sensor_definition.py, python_modules/dagster/dagster/_core/host_representation/code_location.py, python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster/_core/scheduler/instigation.py, python_modules/dagster/dagster/_daemon/sensor.py, python_modules/dagster/dagster/_grpc/impl.py, python_modules/dagster/dagster/_grpc/server.py, python_modules/dagster/dagster/_grpc/types.py, python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_sensor.py, python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py, python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_persistent.py
=> Revert sensor flag for sensor start timestamp

docs/content/concepts/partitions-schedules-sensors/backfills.mdx
=> in docs, explain that backfill policies are ignored by asset jobs

python_modules/dagster/dagster_tests/daemon_tests/test_queued_run_coordinator_daemon.py
So we can run this same test suite in different contexts.
=> Extract QueuedRunCoordinatorDaemonTests

python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py
Have not investigated fully why this is hitting the slow path, but this alternative is fine (just one query) and much safer.
=> [auto-materialize] fix perf regression

docs/content/concepts/partitions-schedules-sensors/sensors.mdx
See: https://dagsterlabs.slack.com/archives/C05S2A2QNMR/p1701283607573729
User was confused that resetting cursor wasn't having desired effect. Was simultaneously using run keys, as shown in example. This PR adds a point of clarification.
=> [docs] sensor doc clarification

python_modules/dagster/dagster/_core/definitions/auto_materialize_rule.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/updated_scenarios/cron_scenarios.py
Reported here: https://github.com/dagster-io/dagster/discussions/18271#discussioncomment-7690603
=> fix MaterializeOnCron rule for dynamic partitions

python_modules/dagster/dagster/_core/storage/db_io_manager.py
origin https://github.com/dagster-io/hooli-data-eng-pipelines/pull/53#issuecomment-1836611816
=> [db io manager] dont add Query metadata for None outputs

python_modules/dagster/dagster/_core/decorator_utils.py, python_modules/dagster/dagster_tests/definitions_tests/test_sensor_invocation.py
resolves https://github.com/dagster-io/dagster/issues/18040
update our util `get_type_hints` to support objects with `__call__` similar to how it special cases partial functions 
added test related to reported issue
=> [sensor] restore ability to use callable object

python_modules/dagster/dagster/_core/execution/plan/execute_step.py
Refactors `_store_output` so that outputs that do not require the I/O manager are immediately handled. Before we created a no op generator that would be used in the rest of the function, but would result in no real action occurring. This change makes it more obvious which sections of the function are run when the I/O manager is or is not used
Added benefit of making https://github.com/dagster-io/dagster/pull/17451 a smaller PR
=> refactor _store_output so that outputs that do not invoke the I/O manager are immediately handled

docs/content/integrations/airflow.mdx
This PR fixes a broken link on the Airflow page that was reported in #18464
Clicking
=> [docs] - Fix link in Airflow concept reference table

python_modules/dagster/dagster/_core/storage/partition_status_cache.py, python_modules/dagster/dagster_tests/storage_tests/test_partition_status_cache.py
Getting timeouts while fetching the run status for a large number of asset partition statuses.
BK
Also ran shadow-dagit, ensured that we didn't get query timeouts.
=> batch run fetches in partition status cache

python_modules/dagster/dagster/_core/definitions/decorators/sensor_decorator.py, python_modules/dagster/dagster/_core/definitions/sensor_definition.py, python_modules/dagster/dagster_tests/core_tests/definitions_tests/decorators_tests/test_sensor_decorator.py, python_modules/dagster/dagster_tests/definitions_tests/test_sensor.py
=> allow CoercibleToAssetSelection in sensor asset_selection arg

python_modules/dagster/dagster/_core/definitions/asset_automation_evaluator.py
=> [ruff] fmt

python_modules/dagster/dagster/_grpc/client.py
=> refactor(grpc): add types to grpc client

python_modules/dagster/dagster/_grpc/server.py
=> refactor(grpc): add types to grpc server

python_modules/libraries/dagster-k8s/dagster_k8s/models.py
Some type annotations that will hopefully fix some non-deterministic pyright behavior: https://dagsterlabs.slack.com/archives/C03EQ628RS7/p1701980572449609
pyright
=> Type annotations for dagster_k8s

python_modules/libraries/dagster-twilio/dagster_twilio_tests/test_resources.py
Looks like twilio changed their api https://buildkite.com/dagster/dagster-dagster/builds/71988#018c4a4b-8a2f-4ed3-b84f-49d1c8c35c1d/625-1182
=> update twilio error string

python_modules/dagster/dagster/_grpc/client.py, python_modules/libraries/dagster-k8s/dagster_k8s/models.py
Fix some pyright errors
pyright
=> Fix pyright errors

CHANGES.md
changelog for 1.5.12 cherry-pick release
=> 1.5.12 changelog

python_modules/dagster/dagster/_core/execution/context/input.py
=> fix type docstring on partition key range for build_input_context

docs/content/guides/dagster-pipes.mdx
=> [pipes] updated guide language

integration_tests/test_suites/k8s-test-suite/tests/test_integration.py
=> fix oss contrib test

python_modules/dagster/dagster/_core/execution/asset_backfill.py, python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py
=> remove unused asset_graph argument
