.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
python_modules/libraries/dagster-mysql/tox.ini
python_modules/libraries/dagster-postgres/dagster_postgres/event_log/event_log.py
python_modules/libraries/dagster-postgres/dagster_postgres/run_storage/run_storage.py
python_modules/libraries/dagster-postgres/dagster_postgres/schedule_storage/schedule_storage.py
python_modules/libraries/dagster-postgres/dagster_postgres/utils.py
python_modules/libraries/dagster-postgres/tox.ini

This reverts commit f0b0e33eb99dce7c046f6a8051fdc4fa7556b694.
Getting complicated with how this interacts with Cloud connections
BK

Revert "Make all postgres connection CMs transactional (#18584)"

---

CHANGES.md

add changelog for 1.5.13

---

python_modules/dagster/dagster/_core/execution/context/compute.py

Pretty sure the status of limitations has passed on this one. This will stop it from showing up in autocomplete.

remove context.file_manager

---

python_modules/libraries/dagster-databricks/dagster_databricks/pipes.py

Changes the default behavior to forward termination/cancelation to the Databricks run. Adds a flag on the client to toggle this behavior (based on feedback from conversing with user).
While I was adding the toggle it made sense to me to move the hard coded poll interval to client instance option as well. 
addresses https://github.com/dagster-io/dagster/issues/18570 for databricks client 
run `pytest python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_pipes.py::test_pipes_client`
ctrl+c
observe the databricks job run was cancelled

[pipes] databricks termination forwarding

---

integration_tests/test_suites/backcompat-test-suite/webserver_service/pins.txt

Summary:
This will break webserver and user code loading on older versions before the pin was added.
Test Plan: BK

add pendulum pin to pins.txt

---

python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py

This PR changes run status sensors in the following ways:
1. Changes storage reads to always read from the index shard.
2. Change new cursors to only store the globally unique event id, rather than the run-sharded cursor with the run update timestamp.
We've been writing run status change events to the index shard in sqlite since https://github.com/dagster-io/dagster/pull/16814 (`1.5.1`).  For Sqlite users upgrading from `dagster<=1.5.1` to this current version, run status sensors may miss runs in their first tick post-upgrade for runs that are persisted using pre-`1.5.1` code.
This is a second attempt, (after https://github.com/dagster-io/dagster/pull/16849).
BK

switch run status sensors to read from index shard

---

examples/project_dagster_university_start/setup.py

Also updating the starter project

Dagster University - updating starter project version

---

python_modules/dagster/dagster/_core/definitions/asset_selection.py

fix SubtractAssetSelection namedtuple superclass

---

python_modules/dagster/dagster/_core/definitions/job_definition.py

fix long docstring lines in job_definition.py

---

python_modules/dagster/dagster/_daemon/sensor.py

It is a large function, and I have a change planned that would make it even larger.

refactor _evaluate_sensor

---

docs/content/concepts/assets/asset-checks.mdx
examples/docs_snippets/docs_snippets/concepts/assets/asset_checks/factory.py
examples/docs_snippets/docs_snippets_tests/concepts_tests/assets_tests/test_asset_checks.py

Fix an issue that @jrstats caught with the factory example: https://github.com/dagster-io/dagster/discussions/15880#discussioncomment-7917192

fix checks factory example

---

docs/content/concepts/assets/asset-checks.mdx
examples/docs_snippets/docs_snippets/concepts/assets/asset_checks/factory.py

missed in https://github.com/dagster-io/dagster/pull/18867#discussion_r1434409441

docs example fmt

---

docs/content/concepts/assets/asset-checks.mdx

Since some cloud users hadn't found this

link to alerting from checks docs

---

python_modules/dagster/dagster/_grpc/proxy_server.py

When the proxy server calls through timeout arg to the client, it does so without providing a timeout arg. This means that the default grpc timeout gets used for the get_response call. This PR changes to intercept the timeout param from the sensor request args, and pass it through to the get_response call.
I think the existing test where we decrease the timeout can be used for also expanding it to test this behavior.

Respect sensor timeout arg from proxy server

---

js_modules/dagster-ui/packages/ui-core/.storybook/main.js
js_modules/dagster-ui/packages/ui-core/.storybook/preview.js
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/PolicyEvaluationCondition.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/PolicyEvaluationTable.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/__stories__/PolicyEvaluationCondition.stories.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/__stories__/PolicyEvaluationTable.stories.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/flattenEvaluations.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/types.tsx

Create components and Storybook examples for new AMP policy conditions.
https://github.com/dagster-io/dagster/assets/2823852/562024b9-d7de-48ac-b967-515a6247afd4
Storybook, see video. Hover on rows, verify highlighting behavior.

[ui] Initial components for AMP policy condition tables

---

python_modules/dagster/dagster/_utils/container.py
python_modules/dagster/dagster_tests/utils_tests/test_container_utils.py

Adds methods to retrieve containerized memory and cpu. I tested these methods on kubernetes and ecs containers that are running live agents, and the same methodology works for both.
Added an additional test that ensures that when metrics are not retrievable, we handle it gracefully.

[RFC] utils to retrieve mem/cpu usage from containerized environment

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx
js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadAllowedRoot.tsx

Create a trace for AssetCatalogRoot and the AssetView so that we can track their E2E performance
console.log'd the trace and checked it happened at the right time

Instrument asset catalog root

---

python_modules/dagster-test/dagster_test/toys/sensors.py

test(instigator-tick-logs): add toy that emits tick logs

---

python_modules/dagster/dagster/_core/definitions/asset_selection.py

fix KeyPrefixesAssetSelection namedtuple superclass

---

python_modules/dagster/dagster/_core/host_representation/code_location.py
python_modules/dagster/dagster/_core/host_representation/grpc_server_registry.py
python_modules/dagster/dagster/_core/storage/cloud_storage_compute_log_manager.py
python_modules/dagster/dagster/_grpc/proxy_server.py
python_modules/dagster/dagster/_grpc/server.py
python_modules/dagster/dagster/_grpc/server_watcher.py
python_modules/dagster/dagster/_utils/__init__.py
python_modules/libraries/dagster-aws/dagster_aws_tests/emr_tests/test_emr.py
python_modules/libraries/dagster-celery/dagster_celery_tests/test_priority.py
python_modules/libraries/dagster-celery/dagster_celery_tests/test_queues.py

This pattern was bothering me, so refactor it. No need to mutate the thread properties after creating it.
bk, https://docs.python.org/3/library/threading.html#threading.Thread

refactor: set thread daemon property at initialization

---

integration_tests/test_suites/daemon-test-suite/test_dagster_daemon_health.py

Cleanup a test initialization of sensor daemon.

Fix sensor daemon test

---

python_modules/dagster/dagster/_core/definitions/asset_check_spec.py

Oversight from removing the blocking behavior

fix AssetCheckSeverity api doc

---

docs/Makefile
docs/content/guides/dagster-pipes/subprocess/reference.mdx
examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/subprocess/custom_messages/dagster_code.py
examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/subprocess/custom_messages/external_code.py
examples/docs_snippets/docs_snippets_tests/guides_tests/dagster_pipes_tests/test_subprocess.py

add a section to the subprocess reference demonstrating the custom messages capability

[pipes] document custom messages

---

python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/base_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenarios/blocking_check_scenarios.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenarios/scenarios.py

So we can change a test when we fix this

Add test for current AMP + checks behavior

---

docs/content/guides/dagster/how-assets-relate-to-ops-and-graphs.mdx

While reading the documentation I noticed, that there was a word missing.
n.a.

docs: add missing word

---

python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py

Recommit of #18616.  
This got bumped so the breaking change gets grouped with `1.6` instead of `1.5.14`.
BK

Recommit "switch run status sensors to read from index shard"

---

docs/content/guides/limiting-concurrency-in-data-pipelines.mdx
examples/docs_snippets/docs_snippets/deploying/concurrency_limits/dagster.yaml

Documents a new feature to set default concurrency limits.
BK, Inspection

add docs section about setting concurrency default values

---

integration_tests/python_modules/dagster-k8s-test-infra/dagster_k8s_test_infra/helm.py

Summary:
Looks like k8s 29 had a breaking change to this type. Test-only issue.
Test Plan: BK

Fix k8s tests

---

js_modules/dagster-ui/packages/ui-core/src/assets/auto-materialization/AutomaterializationRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/instigation/LiveTickTimeline2.tsx
js_modules/dagster-ui/packages/ui-core/src/instigation/TickHistory.tsx
js_modules/dagster-ui/packages/ui-core/src/instigation/util.ts
js_modules/dagster-ui/packages/ui-core/src/sensors/SensorPageAutomaterialize.tsx
js_modules/dagster-ui/packages/ui-core/src/ticks/TickStatusTag.tsx

https://dagsterlabs.slack.com/archives/C03CCE471E0/p1704316508760969
Shadow dagit:

Update logic to detect stale ticks stuck in started state

---

js_modules/dagster-ui/packages/ui-core/src/runs/__tests__/RunActionButtons.test.tsx

Clean up another TestProvider.
yarn jest

[ui] Clean up RunActionButtons.test

---

docs/next/package.json
docs/next/yarn.lock

Resolves https://github.com/dagster-io/dagster/security/dependabot/386.
yarn why follow-redirects

[docs] Fix dependabot alert on follow-redirects

---

python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_daemon_scenario.py

Summary:
And that's why you always rebase before landing.
Test Plan: BK

Fix merge conflict with asset daemon sensor tests and cursor storage changes

---

js_modules/dagster-ui/packages/ui-core/src/assets/auto-materialization/AutomaterializationRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/sensors/SensorPageAutomaterialize.tsx

I removed this gating in response to feedback on my PR but realize now the feedback was wrong (the PR was open for a few days so my brain became foggy on the exact details). 
load the AMP page

Add back index !== 0 and !tick.endTimestamp gating

---

python_modules/dagster/dagster/_core/definitions/asset_dep.py
python_modules/dagster/dagster/_core/definitions/asset_spec.py
python_modules/dagster/dagster/_core/definitions/result.py

remove experimental marker from AssetSpec, MaterializeResult, AssetDep

---

python_modules/dagster/dagster/_core/definitions/data_version.py

In `DataProvenance` objects the `input_data_versions` and `input_storage_ids` should always have the same set of keys. Code is written based on this assumption. However, we've observed one instance where that wasn't the case, resulting in an error. It's as yet unclear how this happened.
This PR changes our key check in `input_data_versions` (implicitly used to check both dicts) to instead explicitly check both dicts. The corrupted state where a key is present in only one of these dicts is handled the same as if the key is present in neither, that is, as if the key is a new dependency not used in the prior materialization.
Attempted to replicate error in client deployment that was triggering reports, but could not. But I think this should prevent it in any case.

Fix data version bug with corrupted state

---

js_modules/dagster-ui/packages/ui-core/src/graph/SVGViewport.tsx

This PR fixes #[18651](https://github.com/dagster-io/dagster/issues/18651). There was a forgotten todo in this code and it was still trying to use ReactDOM.render.
It's not possible to ReactDOM.render anymore, and even upgrading to the new root.render doesn't work because we now use ApolloClient + some other contexts within the DAG (for the context menus). The asset DAG can't be rendered into a freestanding React root.
This changes the implementation so that it re-renders the actual DAG, clones the DOM nodes and exports that. 
Exported graphs and viewed the SVGs. Also verified the DOM is restored + intact after exporting, and exporting over and over again works and generates the same SVG.

[ui] Fix SVG export option on the DAG

---

CHANGES.md

Inspected the rendered version

Major changes section of changelog for 1.6

---

MIGRATION.md

Inspected the rendered version

migration guide entries for 1.6

---

CHANGES.md
docs/content/dagster-cloud/deployment/agents/running-multiple-agents.mdx

Add enterprise notice to agent queues page

---

python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

Was doing some refactoring and the methods in the tests got missed since they were untyped so I decided it was time to do this
Most of the non type hint changes are just doing more `assert`s to handle `Optional` values now that this code is examined by the type checker. 
bk type checks and tests pass

type EventLogStorage tests

---

python_modules/dagster/dagster/_core/utils.py

This adds a new class, `FuturesAwareThreadPool`, to explicitly track threadpool utilization metrics. This is useful because there are places where `InheritContextThreadpoolExecutor` is not appropriate, but we still want to be able to retrieve containerized metrics. This gives us a centralized implementation to use.

Split out threadpool properties from context aware threadpool

---

js_modules/dagster-ui/packages/ui-components/src/index.ts

This will be useful for defining themable values in Cloud.
Buildkite

[ui] Expose the Dagster theme value in ui-components

---

js_modules/dagster-ui/packages/ui-core/src/instigation/LiveTickTimeline2.tsx

[LiveTickTimeline] Fix off by 1 error

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/Sidebar.tsx

Locally open asset graph in a code location with more than 1 group.

[Asset graph] Open code location if only one available

---

CHANGES.md

Release 1.6.1 changelog

---

.buildkite/dagster-buildkite/dagster_buildkite/python_version.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/dagster_ui.py

shfit to align with hosted services python version
bk

[buildkite] bump default python version to 3.11

---

python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py

These log lines are quite helpful for debugging, and are not particularly high-volume

[auto-materialize] make logs more verbose

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetGroupRoot.tsx

broken in https://github.com/dagster-io/dagster/pull/19083
Fixes https://github.com/dagster-io/dagster/issues/19292
Loaded the page after removing

Remove unused "SensorSwitchFragment"

---

js_modules/dagster-ui/packages/ui-core/src/instigation/TickDetailsDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/instigation/TickHistory.tsx
js_modules/dagster-ui/packages/ui-core/src/instigation/util.ts
python_modules/dagster-test/dagster_test/toys/partitioned_assets/partitioned_run_request_sensors.py

Addresses https://github.com/dagster-io/dagster/issues/17663
Test plan:
Updated a toy in the toy repo to make multiple requests

[Sensors] Fix count of number of partitions added/deleted

---

docs/next/styles/globals.css
docs/next/tailwind.config.js

This reverts commit 450420897a02689ebcaf9e8978aa45a6a554ad3e.

Revert "[docs] Reduce base font size and line height (#18917)"

---

js_modules/dagster-ui/packages/ui-components/.storybook/preview.js
js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/AssetCheckDetailModal.tsx

I overlooked an incorrect import in `ui-components` Storybook preview.
Run storybook, verify that it loads.

[ui] Fix bad import in storybook

---

examples/with_airflow/setup.py
python_modules/libraries/dagster-airflow/setup.py

Add pin on flask-session for dagster-airflow

---

python_modules/dagster/dagster/_core/definitions/asset_automation_evaluator.py

We want to make this ConditionEvaluation class serializable, and in order to do so, we'll want to serialize snapshots of our conditions rather than the objects themselves.
This brings up an interesting question: the ConditionEvaluation class has information that we want to call up from previous ticks, and it has a recursive structure. On the next tick, we need to be able to locate which part of the recursive structure we should explore next (this is the `for_child` call). However, there are three issues:
1. A given condition can have multiple identical sub-expressions, i.e. `(A & (B | C) & (B | C))` is technically valid, so we can't use a pure equality test to detect which sub-expression to go to next
2. If each node in the condition evaluation tree needs to have a snapshot class which …

[amp-refactor][2/n] Create snapshot class for condition objects

---

python_modules/dagster/dagster/_core/definitions/asset_condition.py
python_modules/dagster/dagster/_core/definitions/asset_condition_evaluation_context.py
python_modules/dagster/dagster/_core/definitions/auto_materialize_rule.py
python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_evaluation.py
python_modules/dagster/dagster/_core/definitions/freshness_based_auto_materialize.py

Return the new AssetConditionEvaluationResult object from the existing AutoMaterializeRules

[amp-refactor][12/n] Return AssetConditionEvaluationResult from AutoMaterializeRule

---

python_modules/dagster/dagster/_core/definitions/asset_check_spec.py
python_modules/dagster/dagster_tests/definitions_tests/test_asset_check_spec.py

https://github.com/dagster-io/dagster/pull/19319/files#r1460110077

verify no duplicate dependencies on AssetCheckSpec

---

python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

Companion PR to https://github.com/dagster-io/internal/pull/8014, which fixes an ursula event log storage bug.
BK

add run status filter change test

---

js_modules/dagster-ui/packages/ui-components/src/components/Icon.tsx
js_modules/dagster-ui/packages/ui-components/src/icon-svgs/send.svg

Add the "send" Material icon.
Buildkite

[ui] Add "send" icon

---

js_modules/dagster-ui/packages/ui-core/src/app/analytics.tsx

Export the `usePageContext` hook for use in Cloud.
Verify that it can be imported and used successfully.

[ui] Export usePageContext

---

python_modules/dagster-graphql/dagster_graphql/test/utils.py

refactor: allow schema to be specified on `execute_dagster_graphql`

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_scheduler.py

refactor: introduce `TestScheduleMutations` class

---

js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadSession.tsx
js_modules/dagster-ui/packages/ui-core/src/launchpad/TagEditor.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunTags.tsx
python_modules/dagster-test/dagster_test/toys/simple_config.py
python_modules/dagster/dagster_tests/cli_tests/workspace_tests/hello_world_file_in_directory/hello_world_repository.py

Adding the ability to copy the default tag to make it easier to override.

Add copy action to tags in launchpad session

---

python_modules/dagster/dagster/_core/definitions/auto_materialize_rule.py

Fix issue if asset goes from partition <> unpartitioned

---

python_modules/dagster/dagster/_core/definitions/asset_subset.py

2nd partitions hotfix for discord

---

python_modules/dagster/dagster/_core/definitions/auto_materialize_rule.py

Fix parens

---

python_modules/dagster-webserver/setup.py

https://github.com/encode/starlette/discussions/2436
`0.36.1` fixed it
resolves https://github.com/dagster-io/dagster/issues/19356
bk

[dagster webserver] pin away bad starlette version

---

python_modules/dagster/dagster/_core/definitions/assets_job.py
python_modules/dagster/dagster/_core/definitions/partition_mapping.py
python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py

Fix partitioned asset mapped to all partitions of upstream asset

---

CHANGES.md

1.6.2 changelog

---

python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

[INTERNAL_BRANCH=prha/last_planned_nonnull]
Not all assets will have associated planned events
this PR

test the last planned materialiazation storage method

---

examples/docs_snippets/setup.py
python_modules/libraries/dagster-aws/setup.py

Moto 5 introduces some public API changes that I noticed were failing tests. I'm conservatively placing a pin for today but I'll get everything fixed forward this week.
https://github.com/dagster-io/internal/pull/8060

Pin moto<5.0

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py

When running multiple dbt commands in a single computation body, it's a bit hard to disambiguate which command actually failed unless you look deeper into the stack trace.
Instead, just hoist it into the exception message. And when running `raise_on_error=False`, log when a command has finished.
local

feat(dbt): log the `dbt` command on completion and exception

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py

The third attempt at interrupting the dbt subprocess on exit.
Instead of relying on `atexit` (https://github.com/dagster-io/dagster/pull/15897) or overriding signal handlers, just catch the execution interrupt exception like `dagster-pipes` (https://github.com/dagster-io/dagster/pull/18685) and terminate the subprocess when that's handled.
pytest, local
https://github.com/dagster-io/dagster/assets/16431325/05d1e002-430b-49b3-a81e-c08743e3ed63

feat(dbt): forward termination to `dbt` subprocess on exit

---

docs/content/community/contributing.mdx
docs/content/getting-started/hello-dagster.mdx
docs/dagster-university/pages/dagster-essentials/lesson-2/requirements-and-installation.md
docs/next/components/mdx/includes/dagster/DagsterVersion.mdx
docs/next/markdoc/partials/DagsterVersion.md

This PR adds a max supported version of Python to the docs and DaggyU. Noted in #17933
👀

[docs] - Add max Python version to docs and DU

---

CHANGES.md

1.6.3 CHANGELOG

---

python_modules/dagster/dagster/_core/definitions/asset_check_spec.py
python_modules/dagster/dagster/_core/definitions/assets_job.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py
python_modules/dagster/dagster/_core/execution/plan/execute_step.py
python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_check_decorator.py
python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_decorator_with_check_specs.py

Reintroduce a modified version of blocking from https://github.com/dagster-io/dagster/pull/16016
Relevant docs:
- https://github.com/dagster-io/internal/discussions/7719
- https://www.notion.so/dagster/Blocking-asset-check-naming-fa08474ba33242e89637bed2119d9d78

blocking toggle on asset checks

---

python_modules/dagster/dagster/_core/definitions/asset_check_spec.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py

missed in https://github.com/dagster-io/dagster/pull/19299/files/048d607149b4560b24780f216635881953f7c2df#diff-7f199b7ebaf574f28657456f17ecb41d6b6d5dc9e71ccb9253101ba2fc21d86b

blocking check docstring change

---

docs/dagster-university/pages/dagster-essentials/lesson-7/jobs-schedules-dagster-ui.md

Minor improvement in dagster-university. 
Docs only

docs: Corrected lesson where sensors are covered

---

docs/sphinx/sections/api/apidocs/assets.rst
python_modules/dagster/dagster/_core/definitions/decorators/source_asset_decorator.py

fix observable source asset docstring

---

python_modules/dagster/dagster/_core/definitions/partitioned_schedule.py
python_modules/dagster/dagster/_core/definitions/unresolved_asset_job_definition.py
python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py

Allow creating a schedule from a statically parititoned asset job

---

python_modules/dagster/dagster/_daemon/sensor.py

On our journey of adding threads to the sensor daemon we encountered problems when the same sensor was being evaluated concurrently. 
Our initial understanding of this problem led to adding a global lock across sensors to prevent certain portions of book keeping from running concurrently. 
#8720 7/6/2022 - add global lock to prevent thread contention 
Later, it became clear that other problems manifest from allowing this type of concurrency so we prevented it.
#9812 9/28/2022 - enforces one active future / thread per sensor
This means the global lock is no longer useful and actively causes contention problems in high throughput situations, so remove it.
#8720 added tests that continue to pass

[sensors] remove state lock

---

python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_daemon_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/base_scenario.py

same logic as https://github.com/dagster-io/dagster/pull/19543
existing suite

[asset daemon] remove state lock

---

python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_asset_daemon.py

Summary:
When you move from the old AMP model to the new sensor based model, we need to figure out whether each of those sensors should be running and what their cursors should be. On the first iteration of the asset daemon, initialize the running state of each sensor based on AMP was running before, and initialize the cursor value by subsetting the existing cursor for each sensor's asset keys. This migration will only run once the first time you run AMP after migrating.

Initialize automation policy sensor state the first time the asset daemon runs after enabling the feature

---

js_modules/dagster-ui/packages/ui-core/src/overview/OverviewSensorsRoot.tsx

follow up to https://github.com/dagster-io/dagster/pull/19561
missed a spot because I forgot to rebase before merging.
buildkite

initialState -> state

---

python_modules/libraries/dagster-k8s/dagster_k8s/pipes.py
python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_pipes.py

This PR adds a way for users to be able to read to the pipes session context from containers 
other than the first container in the pod spec allowing sidecars to read extra information from Dagster. This PR also allows to make it possible to write messages to a file if needed,
but we default to writing to `/dev/null` to keep `open_dagster_pipes` functional without 
any extra need from the user.
The user can specify a custom message writer by specifying it like below:
```python
from dagster_pipes import encode_env_var
env = [
{
"name": "DAGSTER_PIPES_MESSAGES",
"value": encode_env_var({"path": "/custom/path"}),
},
],
```
I have added unit test coverage to the necessary places and whilst doing it I have split
the tests to provide better feedback to the developer debugging the failures. I …

feat(dagster-k8s): inject dagster session env vars to all containers

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/AssetSidebarNode.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/Sidebar.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/util.tsx

As the title:
Fixes issue https://github.com/dagster-io/dagster/issues/18932
Tested locally, confirming each button in the popover functioned as intended.

[ui] Add context menu popover in sidebar for asset groups

---

python_modules/libraries/dagster-dbt/dagster_dbt/cli/app.py
python_modules/libraries/dagster-dbt/dagster_dbt/cloud/asset_defs.py
python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py
python_modules/libraries/dagster-dbt/dagster_dbt/utils.py

Didn't see this for https://github.com/dagster-io/dagster/pull/19476. Remove it.
bk

refactor(dbt): remove more `dbt-core==1.4.*` backcompat

---

python_modules/dagster/dagster/_core/storage/migration/bigint_migration.py
python_modules/libraries/dagster-mysql/dagster_mysql_tests/compat_tests/test_back_compat.py

Altering the type for autoincrementing ids wipes out the autoincrement in mysql.  This grabs the schema from the table definition and makes sure the id is marked as autoincrementing.
Fixes https://github.com/dagster-io/dagster/issues/19510
BK

fix bigint migration for mysql

---

python_modules/dagster/dagster/_daemon/backfill.py

Summary:
This paves the way to add an additional callsite to this function.

factor out the function that the backfill daemon calls into a separate function

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_sensors.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_selections.py
python_modules/dagster-graphql/dagster_graphql/schema/external.py
python_modules/dagster-graphql/dagster_graphql/schema/sensors.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py

Summary:
In addition to the human readable strings, would allow us to give you a way to click through to a dialog or something with the specific list of assets being targeted by a sensor.
Test Plan: BK

add list of asset keys to GrapheneAssetSelection

---

python_modules/dagster/dagster/_core/definitions/asset_selection.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection.py

`__str__` implementations for `AndAssetSelection`, `OrAssetSelection`, and `SubtractAssetSelection`

strings for asset selection operators

---

python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_schedules.py

Resolves https://github.com/dagster-io/dagster/issues/17512.
pytest

feat(dbt): add `default_status` argument to `build_schedule_from_dbt_selection`

---

js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/AssetAutomaterializePolicyPage.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/AutomaterializeLeftPanel.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/AutomaterializeMiddlePanel.tsx

1. Show the partition if there's only 1 requested
2. Reset selected partition when you change evaluations
shadow-dagit with dogfood-test-1

Policy evaluations follow ups

---

docs/content/dagster-cloud/managing-deployments/branch-deployments.mdx

This PR removes the backfill limitation from the Branch Deployment docs.
👀

[docs] - Remove backfill limitation from Branch Deployment docs

---

js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedSensorRow.tsx

As titled
Locally loaded the overview sensor page and confirmed issues are fixed

Sensors - Update icon for automation policy sensor + make column bigger

---

docs/content/concepts/partitions-schedules-sensors/sensors.mdx
examples/docs_snippets/docs_snippets/concepts/partitions_schedules_sensors/sensors/sensors.py
python_modules/dagster-test/dagster_test/toys/run_status_sensors.py
python_modules/dagster/dagster/_utils/alert.py
python_modules/libraries/dagster-msteams/dagster_msteams/sensors.py
python_modules/libraries/dagster-slack/dagster_slack/sensors.py

monitor_all_repositories -> monitor_all_code_locations in email, teams, slack
and updates docs

more renames in integrations + docs 2/2

---

CHANGES.md

CHANGES for 1.6.4

---

CHANGES.md

amend 1.6.4 CHANGES.md to mention dynamic partitions bugfix

---

docs/content/integrations/airflow.mdx

This PR adds some more detail about what's possible with `dagster-airflow` to the integration's page in the docs.

[docs] - Update Airflow integration page intro

---

js_modules/dagster-ui/packages/ui-core/src/schedules/ScheduleDetails.tsx

Make the spacing of `ScheduleResetButton` and its toggle be the same as `SensorResetButton`'s spacing.
local

fix(declarative-instigator-status): add spacing to schedule reset button

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py

When parsing dbt debugging events, we can get even more metadata about the computation. We can yield this back to the framework at no cost to the user.
local, pytest

feat(dbt): add adapter response metadata to Dagster events by default

---

docs/content/getting-started/hello-dagster.mdx

This PR fixes some unhappy JSX in the Hello, Dagster! page.
local

[docs] - Fix JSX issue in Hello Dagster

---

python_modules/dagster/dagster/_core/definitions/decorators/source_asset_decorator.py

fix observable_source_asset api doc typo

---

python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py

this method is now frowned upon in Python 3.12 but it is actually what we want here to satisfy postgres as per the comment (verified that including the timezone does indeed produce incorrect results) - make the same calculation in a different way that does not raise a warning
BK

utcfromtimestamp => fromtimestamp in sql storage

---

CHANGES.md

I missed adding this to the notion, I'll pick it on to the release branch

Add missing changelog entry

---

python_modules/dagster-graphql/dagster_graphql/schema/auto_materialize_asset_evaluations.py

Make this have a consistent order

[auto-materialize] Sort metadata sent to the UI

---

docs/content/dagster-cloud/managing-deployments/setting-up-alerts.mdx

Add 5 min to agent alert docs

---

python_modules/dagster/dagster/_core/definitions/run_request.py

clarify RunRequest asset_selection arg api doc

---

python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_checks.py

In the spirit of https://github.com/dagster-io/dagster/pull/19752, reduce the usage of `mocker` when testing `dagster-dbt`. We should aim to go through the current machinery that the user is expected to use, and test against that.
Refactor `test_asset_checks.py` with those principles in mind. Instead of asserting against events emited by a standalone `DbtCliResource`, assert in the body of the asset definition when `DbtCliResource` is invoked.
pytest

test(dbt): remove unnecessary uses of `mocker`

---

docs/content/integrations/dbt/reference.mdx

Rework https://github.com/dagster-io/dagster/pull/19551 by using https://github.com/dagster-io/dagster/pull/19623 as the mechanism for collecting dbt metadata. 
read, try it local

feat(dbt): add reference for collecting columns metadata using the `dagster` dbt package

---

python_modules/dagster-graphql/dagster_graphql/schema/backfill.py

Summary:
Before, if you tried to create a GrapheneAssetBackfillData with a set of rootTargetedPartitions for assets that no longer existed, it would raise an error, even if you did not fetch the rootTargetedPartitions field. Now, we only fetch fields when they are needed.
Test Plan: BK
Make a manual graphql query on an asset backfill that was previously erroring out on rootTargetedPartitions - it no longer raises an error unless you specifically query for that field

Delay computations of fields in GrapheneAssetBackfillData until they are asked for

---

python_modules/dagster/dagster/__init__.py

As title.
from dagster import AutoMaterializeSensorDefinition

Make AutoMaterializeSensorDefinition public (but experimental)

---

python_modules/dagster/dagster/_core/definitions/source_asset.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_observe.py

allow observable source asset observations with no data version

---

python_modules/dagster/dagster/_core/definitions/auto_materialize_policy.py
python_modules/dagster/dagster/_core/definitions/auto_materialize_rule.py

This is a precursor for more complex changes in which we incrementally move the implementation logic out of the AutoMaterializeRule class and into AssetCondition objects.

[AssetCondition] Add to_asset_condition method on AutoMaterializeRule

---

docs/dagster-university/pages/dagster-essentials/lesson-2/requirements-and-installation.md

This PR updates the Python and Dagster versions in the Requirements portion of Dagster Essentials.

[daggy-u] [essentials] - Update Python and Dagster versions 

---

docs/dagster-university/pages/dagster-essentials/lesson-9/creating-an-asset-triggered-by-a-sensor.md

Deleted empty code block
Docs only

[docs] Deleted empty code block

---

python_modules/automation/automation_tests/telemetry/test_resource_telemetry.py
python_modules/automation/automation_tests/test_repo.py
python_modules/automation/tox.ini
python_modules/libraries/dagster-polars/dagster_polars/__init__.py

Community PR adding dagster-polars was merged but did not add it to `DagsterLibraryRegistry`, causing a failure on BK.

Register dagster-polars in DagsterLibraryRegistry

---

python_modules/dagster/dagster_tests/general_tests/parent_asset_graph_differ_tests/asset_graph_scenarios/basic_asset_graph/branch_deployment_change_inputs.py
python_modules/dagster/dagster_tests/general_tests/parent_asset_graph_differ_tests/asset_graph_scenarios/basic_asset_graph/branch_deployment_new_asset_connected.py
python_modules/dagster/dagster_tests/general_tests/parent_asset_graph_differ_tests/asset_graph_scenarios/code_versions_asset_graph/branch_deployment_multiple_changes.py
python_modules/dagster/dagster_tests/general_tests/parent_asset_graph_differ_tests/asset_graph_scenarios/code_versions_asset_graph/branch_deployment_update_code_version.py
python_modules/dagster/dagster_tests/general_tests/parent_asset_graph_differ_tests/asset_graph_scenarios/code_versions_asset_graph/parent_asset_graph.py
python_modules/dagster/dagster_tests/general_tests/parent_asset_graph_differ_tests/asset_graph_scenarios/huge_asset_graph/branch_deployment_restructure_graph.py
python_modules/dagster/dagster_tests/general_tests/parent_asset_graph_differ_tests/asset_graph_scenarios/huge_asset_graph/parent_asset_graph.py
python_modules/dagster/dagster_tests/general_tests/parent_asset_graph_differ_tests/test_parent_asset_graph_diff.py

Adds more tests of the Differ in https://github.com/dagster-io/dagster/pull/19681
Will probably merge this branch into https://github.com/dagster-io/dagster/pull/19681 rather than separately into master, but seemed easier to review the tests separately

[graph diffing] Larger test suite - FOU-22

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNode.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNodeStatusContent.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/__fixtures__/AssetNode.fixtures.ts
js_modules/dagster-ui/packages/ui-core/src/asset-graph/__stories__/AssetNode.stories.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/layout.ts

Add over due status to source assets in asset graph

---

python_modules/dagster/dagster/_core/definitions/metadata/__init__.py

add example to apidoc for TableMetadataValue

---

js_modules/dagster-ui/yarn.lock

Resolves https://github.com/dagster-io/dagster/security/dependabot/425.
yarn why ip

[ui] Resolve dependabot alert on ip package

---

.buildkite/dagster-buildkite/dagster_buildkite/step_builder.py

[buildkite] bump plugin versions

---

CHANGES.md

docs: add changelog for `1.6.6`

---

python_modules/dagster-test/dagster_test/toys/asset_checks.py

Add context.selected_asset_check_keys example to toys

---

docs/sphinx/sections/api/apidocs/assets.rst

apidoc for multi_observable_source_asset

---

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/__init__.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/asset_defs.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/resources.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/staging_test.csv
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/test_assets.py

This reverts #18270 in preparation for adding the new asset decorator approach. I had initially created this revert after the implementation but it made the diff very hard to parse, moving it before the merge makes it a little easier to review the incoming Sling changes.
bk

[embedded-elt] Revert #18270 Sling Replication changes.

---

docs/content/integrations/airbyte-cloud.mdx
examples/docs_snippets/docs_snippets/integrations/airbyte/airbyte.py

[docs] - Remove brackets from assets in Airbyte Cloud guide

---

docs/content/dagster-cloud/account/managing-user-agent-tokens.mdx

Documenting the agent token permissions dialog for Dagster Cloud.
buildkite

Document agent token permissions

---

python_modules/dagster/dagster/_check/__init__.py
python_modules/dagster/dagster/_core/definitions/instigation_logger.py
python_modules/dagster/dagster/_core/events/log.py
python_modules/dagster/dagster/_core/execution/context_creation_job.py
python_modules/dagster/dagster/_core/log_manager.py
python_modules/dagster/dagster/_utils/log.py

Add some type annotations to old logging code and do a few renames to new terminology in local vars, comments.

[logging] Logging annotations and local variable renames

---

js_modules/dagster-ui/packages/ui-core/src/ui/Filters/useTimeRangeFilter.tsx

Fix for build broken by https://github.com/dagster-io/dagster/pull/20033
Discussion: https://dagsterlabs.slack.com/archives/C03CCE471E0/p1708968961678069

[ui] Fix internal build, make activeFilterTerm optional

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/external.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py

Summary:
Creates a replacement for the old "autoMaterializeTicks" field once auto-materialize is beings sourced from sensors.
Test Plan: BK

Add a sensorType filter to the sensors resolver

---

.buildkite/dagster-buildkite/dagster_buildkite/step_builder.py

we use unique tags, no need to always pull 
bk

[buildkite] turn off always-pull

---

docs/sphinx/Makefile

This is especially important when, like me, you are often making mistakes in Sphinx but need to scroll through hundreds of lines to find the problem.
Output with -q
```
sphinx-build -j auto -q -b json -d _build/doctrees  -W --keep-going . _build/json
/Users/pedram/projects/dagster/docs/sphinx/_ext/dagster-sphinx/dagster_sphinx/configurable.py:141: ExperimentalWarning: Function `build_bigquery_io_manager` is experimental. It may break in future versions, even between dot releases. To mute warnings for experimental functionality, invoke warnings.filterwarnings("ignore", category=dagster.ExperimentalWarning) or use one of the other methods described at https://docs.python.org/3/library/warnings.html#describing-warning-filters.
obj = self.object([]) …
```

[docs] Makes Sphinx quiet so it only shows warnings/errors when running with `make api-doc-build`.

---

docs/content/dagster-cloud/deployment/agents/running-multiple-agents.mdx

Summary:
With agent queues in the mix, this line is misleading.
Test Plan: View docs page

Remove line in logs about agents of multiple types

---

js_modules/dagster-ui/packages/ui-core/src/search/SearchDialog.tsx

Add data attributes to the trigger element and the input element for Search

[Search] Add data attributes for cypress

---

python_modules/dagster/dagster/_config/pythonic_config/io_manager.py
python_modules/dagster/dagster_tests/storage_tests/test_io_managers_pythonic_config.py

Resolves: https://github.com/dagster-io/dagster/issues/20053

[config] Pass i/o config schemas through constructor

---

python_modules/libraries/dagster-gcp/dagster_gcp/bigquery/resources.py

Somehow imported the wrong Sequence and Mapping. this fixes.

Fix imports for bigquery resources

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py

This query powers the checks tab. It's filtered down with a single asset key. However, `resolve_assetNodeOrError` calls `get_asset_nodes_by_asset_key`, which returns all (!) the GrapheneAssetNodes, then filters them down.
A consequence is that the AssetChecksLoader gets setup to batch fetching checks for all assets, and that query times out https://dagsterlabs.slack.com/archives/C03F3HVV60G/p1708984388605829. If we filter down before we create the AssetChecksLoader, then we only fetch checks for the one asset, and only create the one GrapheneAssetNode.
**Test plan**: page loads in shadow script when it didn't before
```gql
query AssetChecksQuery($assetKey: AssetKeyInput!) {
assetNodeOrError(assetKey: $assetKey) {
... on AssetNode {
id
assetChecksOrError {
... on …
```

Filter down asset nodes in get_asset_nodes_by_asset_key

---

python_modules/dagster/dagster/_core/definitions/data_time.py

Refactor introduced check on incorrect asset key.
BK

[external-assets] Fix check for unpartitioned data time

---

python_modules/automation/tox.ini

Add dagster-openai to automation tox

---

docs/dagster-university/pages/dagster-dbt.md
docs/dagster-university/pages/dagster-dbt/lesson-2/1-requirements.md
docs/dagster-university/pages/dagster-dbt/lesson-2/2-set-up-the-dagster-project.md
docs/dagster-university/pages/dagster-dbt/lesson-3/5-loading-dbt-models-into-dagster-as-assets.md
docs/dagster-university/pages/dagster-dbt/lesson-3/7-viewing-dbt-models-in-the-dagster-ui.md
docs/dagster-university/pages/dagster-dbt/lesson-3/knowledge-check.md
docs/dagster-university/pages/dagster-dbt/lesson-4/2-speeding-up-the-development-cycle.md
docs/dagster-university/pages/dagster-dbt/lesson-5/2-connecting-dbt-models-to-dagster-assets.md
docs/dagster-university/pages/dagster-dbt/lesson-5/3-creating-assets-that-depend-on-dbt-models.md
docs/dagster-university/pages/dagster-dbt/lesson-5/coding-practice-grouping-models.md
docs/dagster-university/pages/dagster-dbt/lesson-7/1-overview.md
docs/dagster-university/pages/dagster-dbt/lesson-7/4-creating-the-manifest-during-deployment.md

Addressing the things that are checked off in the Linear ticket: https://linear.app/dagster-labs/issue/DEV-147/227-post-dogfooding-action-items
Also snuck in some renames bc I felt Lesson 7 was too directed toward Dagster Cloud when it can be applied to OSS deployments, too.

[du-dbt] updating-post-2-27-dogfooding

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/CollapsedGroupNode.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/Sidebar.tsx

As titled, only 2 lines were added, the rest is prettier

[Asset graph ui] Sort code locations and groups alphabetically

---

integration_tests/test_suites/daemon-test-suite/auto_run_reexecution_tests/test_auto_run_reexecution.py
python_modules/dagster/dagster/_daemon/auto_run_reexecution/auto_run_reexecution.py

Summary: step => asset or op
Test Plan: BK

Update copy on run retry skip message

---

python_modules/dagster/dagster/_core/definitions/partition.py

Bug fix for https://github.com/dagster-io/dagster/issues/20134
Verified minimal reproducible example passes.

🐛 Fix missing property definition

---

pyright/alt-1/requirements-pinned.txt
pyright/master/requirements-pinned.txt

a pin we picked up got yanked
bk

update pyright pins

---

docs/content/dagster-cloud/account/managing-user-agent-tokens.mdx
docs/content/dagster-cloud/account/managing-users/managing-user-roles-permissions.mdx

- Viewers can create their own user tokens
- Only org admins can edit others user tokens

Update managing user token perms docs

---

CHANGES.md

Changelog for 1.6.7

---

azure-pipelines.yml

I broke this with my tox changes
* install uv
* target 3.10 instead
* delete weird 2.7 artifact 
azure

fix windows build

---

CHANGES.md

prettier changes.md

---

CHANGES.md

Fix CHANGES.md using 'make prettier'

---

js_modules/dagster-ui/packages/ui-core/src/search/createSearchWorker.tsx
js_modules/dagster-ui/packages/ui-core/src/search/useGlobalSearch.tsx

Fixes an issue where if you type a query before data is available then you will see "no results" even after the data is available.
https://github.com/dagster-io/dagster/assets/2286579/1aefcb0b-9059-4ead-b95a-fe5d685dfbbd

[Search] Make search when data is available

---

CHANGES.md

1.6.8 changelog

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql/schema/external.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
python_modules/dagster-graphql/dagster_graphql/schema/solids.py

Reverts dagster-io/dagster#20146 which reverted https://github.com/dagster-io/dagster/pull/19814. 
Adds the AssetGraphDiffer to GQL

[graph differ] [re-introduce] Add AssetGraphDiffer to GQL 

---

python_modules/dagster/dagster/_core/definitions/data_time.py
python_modules/dagster/dagster/_utils/caching_instance_queryer.py

[auto-materialize] fix external asset + amp

---

python_modules/dagster/dagster/_core/definitions/auto_materialize_rule.py

[auto-materialize] Take the more accurate path when no previous max storage id

---

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py

use asset specs in docstring for multi_asset

---

js_modules/dagster-ui/packages/ui-core/src/search/useIndexedDBCachedQuery.tsx

Fixes an error that is logged to the console

Check if cache has entry before getting it

---

docs/content/getting-started/what-why-dagster.mdx

This PR updates some copy in the docs to more generally describe DU as a whole, instead of only the Essentials course.
👀

[daggy-u] [dbt] - Update DU copy in docs (DEV-68)

---

docs/content/integrations/embedded-elt.mdx

docs: correct spelling of Database in embedded-elt.mdx

---

python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_deps_error_informative.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection_error_informative.py

what ruffian introduced this error

[fix] a ruff error

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py
python_modules/dagster/dagster/_utils/__init__.py
python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py
python_modules/dagster/dagster_tests/storage_tests/test_partition_status_cache.py

to avoid lock contending in increment when nothing is watching the count
bk

default traced_counter to None

---

docs/next/components/PagePagination.tsx
docs/next/components/mdx/MDXComponents.tsx
docs/next/pages/changelog.tsx
docs/next/pages/migration.tsx

clean up unused code, bad formatting
no errors in `yarn build`

docs infra: make build happy

---

docs/next/pages/_document.js

resolves DS-112
visual changes can be configured in portal. see internal thread: https://dagsterlabs.slack.com/archives/C03B54GFTBJ/p1709658190415639
https://03-05-docs-ai-widget.dagster.dagster-docs.io/getting-started

docs ai widget

---

js_modules/dagster-ui/packages/ui-core/src/runs/RunsRoot.tsx

[Runs] use filter for queued/in progress terminate all

---

python_modules/dagster/dagster/_generate/download.py

Separating #20163 into two PRs: one for adding to the scaffold, and another for rewording DU to use the scaffold. Keeping th rewording as a draft unitl we're ready for it

[du-dbt] adding starter project to quickstart templates

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py

Fix pandas build

---

python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py

We've unexperimentalized `AssetSpec` and `AssetDep`, so remove this.
Also, this was suppressing the intentional messages we wanted to display for `DagsterDbtTranslator.get_partition_mapping` and `+meta.dagster.has_self_dependency` (oops). 
bk

refactor(dbt): remove `disable_dagster_warnings` from `@dbt_assets`

---

python_modules/dagster/dagster/_scheduler/scheduler.py

Summary:
added a new type here that can be returned
Test Plan: make quick_pyright

fix scheduler pyright

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetSidebarActivitySummary.tsx

Link to asset check from asset graph sidebar

---

js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializeSensorFlag.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/DaemonList.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/__tests__/DaemonList.test.tsx

Disable Asset daemon global toggle if using AMP sensors.

---

python_modules/dagster/dagster/_core/utils.py

compacting on every submit is expensive for large throughput threadpools, so use a scheme to avoid doing it as often 
existing tests

[FuturesAwareThreadPoolExecutor] avoid compact on every submit

---

python_modules/dagster/dagster/_core/definitions/decorators/repository_decorator.py
python_modules/dagster/dagster/_core/definitions/repository_definition/repository_definition.py

[type hints] RepositoryDefinition

---

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/resources.py

Adds missing docs for Sling's replication

[embedded-elt] Add additional docs to resources

---

python_modules/dagster-graphql/dagster_graphql/schema/tags.py

This does not appear to be used anywhere

Remove GrapheneAssetTag

---

python_modules/dagster/dagster/_core/execution/submit_asset_runs.py
python_modules/dagster/dagster/_core/remote_representation/code_location.py

This changes addresses a very subtle issue with functionality addressed in https://github.com/dagster-io/dagster/pull/19091. That PR addresses the situation where, in the middle of a backfill, the targeted job is changed to no longer include the targeted asset. It solves this problem by examining the execution plan returned by `get_external_job` to see if it actually targets the requested asset-- if it does not, then the asset graph refreshes.
This approach was failing against changes to job subsetting introduced upstack because trying to subset a job with an asset that is not targeted by that job now throws an InvalidSubsetError instead of returning a "null" execution plan. This was also true before, but would never happen for base asset jobs because all other assets were included as …

[external-assets] Make backfill retry handle InvalidSubsetError

---

python_modules/libraries/dagster-aws/dagster_aws_tests/s3_tests/test_s3_sensor.py
python_modules/libraries/dagster-gcp/dagster_gcp/gcs/sensor.py
python_modules/libraries/dagster-gcp/dagster_gcp_tests/gcs_tests/test_sensor.py

- Completion of this feature initiated by https://github.com/dagster-io/dagster/pull/13764

Added get_gcs_keys helper function

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx
js_modules/dagster-ui/packages/ui-core/src/ui/Filters/useAssetOwnerFilter.tsx

As the title.
Used in https://github.com/dagster-io/dagster/pull/20372

[ui] Enable filtering asset table by owner

---

docs/next/pages/_document.js

make Ask AI fab more prominent in the UI

---

js_modules/dagster-ui/packages/ui-core/src/app/getVisibleFeatureFlagRows.tsx
js_modules/dagster-ui/packages/ui-core/src/ui/SideNavItem.tsx

Some Settings side nav item tweaks for use in Cloud.
View Settings in Cloud, verify that the right-hand icon appears for one of my items.

[ui] Settings updates for Cloud

---

python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py
python_modules/libraries/dagster-aws/dagster_aws/ecs/tasks.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/test_launching.py

Summary:
Allows you to configure that your launched runs can, for example, be sshed into.
Test Plan: BK

Add "linux_parameters" to EcsRunLauncher

---

docs/dagster-university/pages/dagster-dbt/lesson-2/3-set-up-the-dbt-project.md

https://dagster.slack.com/archives/C060X0EB7K4/p1710079583644689

[du][du-dbt] fixing bad file extensions

---

integration_tests/test_suites/daemon-test-suite/test_dagster_daemon_health.py
python_modules/dagster/dagster/_daemon/controller.py

Exceptions refreshing the workspace cause the daemon controller to crash, taking the rest of the daemon threads with it. This adds exception handling that allows the controller to continue operation until a tolerance for workspace freshness is hit, then it falls over.
test

Add workspace tolerance to daemon controller

---

CHANGES.md

[docs] - Correct version for libraries in changelog

---

python_modules/dagster-graphql/dagster_graphql/implementation/asset_checks_loader.py
python_modules/dagster-graphql/dagster_graphql/implementation/execution/backfill.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/mutation.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
python_modules/dagster/dagster/_core/execution/asset_backfill.py
python_modules/dagster/dagster/_core/execution/backfill.py
python_modules/dagster/dagster/_core/execution/submit_asset_runs.py
python_modules/dagster/dagster/_core/workspace/workspace.py
python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster/_scheduler/stale.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_external_asset_graph.py
python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/base_scenario.py

same logic as https://github.com/dagster-io/dagster/pull/20468

move RemoteAssetGraph.from_workspace to cached property on IWorkspace

---

python_modules/dagster/dagster/_core/instance/__init__.py

Summary:
After https://github.com/dagster-io/dagster/pull/20335/files, there are edge cases where the parent snapshot ID returned in code might not match up with the parent job snapshot ID stored in the database or in memory for the full job. Rather than invarianting and failing the launched job, warn.
Test Plan:
- Run a grpc server locally, start dagit
- Add a new asset to the job, restart the gRPC server (may need to disable the watcher on dagit that automatically reloads the code location)
- Launch a subsetted job
Before: invariant stops job from launching
Now: warning, job launches just fine

Change parent snapshot ID invariant to a warning

---

CHANGES.md

1.6.10 changelog

---

CHANGES.md

1.6.11 hotfix changelog

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/types/AssetGraphJobSidebar.types.ts
js_modules/dagster-ui/packages/ui-core/src/asset-graph/types/SidebarAssetInfo.types.ts
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/types/GetEvaluationsQuery.types.ts
js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/types/AssetCheckDetailModal.types.ts
js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/types/AssetChecks.types.ts
js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/types/VirtualizedAssetCheckTable.types.ts
js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetMetadata.types.ts
js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetNodeDefinition.types.ts
js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetPartitionDetail.types.ts
js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetView.types.ts
js_modules/dagster-ui/packages/ui-core/src/assets/types/useLatestPartitionEvents.types.ts
js_modules/dagster-ui/packages/ui-core/src/assets/types/useRecentAssetEvents.types.ts
js_modules/dagster-ui/packages/ui-core/src/dagstertype/types/DagsterType.types.ts
js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
js_modules/dagster-ui/packages/ui-core/src/metadata/MetadataEntry.tsx
js_modules/dagster-ui/packages/ui-core/src/metadata/types/MetadataEntry.types.ts
js_modules/dagster-ui/packages/ui-core/src/pipelines/types/GraphExplorer.types.ts
js_modules/dagster-ui/packages/ui-core/src/pipelines/types/PipelineExplorerRoot.types.ts
js_modules/dagster-ui/packages/ui-core/src/pipelines/types/SidebarContainerOverview.types.ts
js_modules/dagster-ui/packages/ui-core/src/runs/types/LogsProvider.types.ts
js_modules/dagster-ui/packages/ui-core/src/runs/types/LogsRow.types.ts
js_modules/dagster-ui/packages/ui-core/src/runs/types/LogsScrollingTable.types.ts
js_modules/dagster-ui/packages/ui-core/src/runs/types/RunFragments.types.ts
js_modules/dagster-ui/packages/ui-core/src/runs/types/RunMetadataProvider.types.ts
js_modules/dagster-ui/packages/ui-core/src/typeexplorer/types/TypeExplorer.types.ts
js_modules/dagster-ui/packages/ui-core/src/typeexplorer/types/TypeExplorerContainer.types.ts
python_modules/dagster-graphql/dagster_graphql/schema/metadata.py

display timestamp metadata values as timestamps

---

docs/sphinx/sections/api/apidocs/assets.rst

Add AutoMaterializeSensorDefinition to api docs

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeOverview.tsx

Resolves https://github.com/dagster-io/dagster/issues/20247.
If the definition level column schema is supplied with descriptions, render its descriptions along the materialization level column schema.
Materialize a set of dbt assets with definition and materialization column schema metadata. See both rendered together.

feat(asset-overview): merge definition and materialization level column descriptions

---

docs/content/getting-started/getting-help.mdx

In addition to #ask-ai in Slack, our LLM is available within docs pages as a chat window now
👀

[docs] note that Ask AI is available within docs pages

---

python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py

These tests are annoying to maintain because they involve manually constructed objects. Also, their functionality is already tested when we materialize dbt assets. Remove them.
bk

test(dbt): remove tests against manually constructed dbt events

---

python_modules/dagster/dagster/_core/definitions/asset_selection.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection.py

- Adds `AssetSelection.tag` (public, experimental), which accepts a key and a value
- Adds `AssetSelection.tag_string` (internal for now), which accepts a string interprets it as a key-value pair
- Adds support in the asset CLI for `--select tag:foo=fooval`
added tests

Support tags in asset selections

---

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/asset_decorator.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/replication_configs/base_with_meta_config/replication.yaml
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/test_asset_decorator.py

- Resolves https://github.com/dagster-io/dagster/issues/20483#issue-2186874893
- Follow-up to https://github.com/dagster-io/dagster/pull/20534; adds unit test to ensure full translator coverage

[embedded-elt][sling] e2e test coverage Sling translator calls in AssetSpec

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetsOverview.tsx

Adds two changes:
- Ensures that on scroll all of the page content is displayed. Previously in certain situations the page was cut off.
- Displays user's first name instead of full name.

[ui] Asset catalog small design fixes

---

js_modules/dagster-ui/packages/ui-core/src/assets/LaunchAssetObservationButton.tsx

make observation button assertion more accurate

---

docs/content/integrations/dbt/reference.mdx
examples/docs_snippets/docs_snippets/integrations/dbt/dbt.py
python_modules/dagster/dagster/__init__.py
python_modules/dagster/dagster/_core/definitions/asset_selection.py
python_modules/dagster/dagster/_core/storage/tags.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection.py
python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py
python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_meta_config/models/schema.yml

Pull in dbt tags onto asset definitions

---

python_modules/dagster/dagster/_core/definitions/asset_graph.py

Eliminate multiple iterations over assets defs in AssetGraph.from_assets. This greatly speeds up AssetGraph construction for large asset graphs.
Timed `AssetGraph.from_assets` for the below set of defs. Time went from ~6.5s on my machine to <1ms.
```
from dagster import multi_asset, Definitions, AssetCheckSpec, AssetSpec, AssetKey
import random
import string
alphabet = string.ascii_lowercase
def asset_key():
return AssetKey("".join(random.choice(alphabet) for _ in range(10)))
asset_keys = [asset_key() for _ in range(5000)]
def asset_check_spec():
name = "".join(random.choice(alphabet) for _ in range(10))
return AssetCheckSpec(name= name, asset=random.choice(asset_keys))
asset_check_specs = [asset_check_spec() for _ in range(5000)]
@multi_asset(specs=[AssetSpec(k) for k in asset_keys], …
```

[external-assets] Eliminate redundant iteration over assets_defs in AssetGraph construction

---

docs/sphinx/sections/api/apidocs/asset-checks.rst
python_modules/dagster/dagster/__init__.py
python_modules/dagster/dagster/_core/definitions/asset_checks.py
python_modules/dagster/dagster/_core/definitions/asset_selection.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_check_decorator.py

multi_asset_check decorator

---

docs/content/concepts/assets/software-defined-assets.mdx
examples/docs_snippets/docs_snippets/concepts/assets/multi_component_asset_key.py

Reported here: https://github.com/dagster-io/dagster/discussions/20554#discussioncomment-8847366

fix multi-component asset keys docs snippet

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/dbt_packages/test_columns_metadata.py

Apply https://github.com/dagster-io/dagster/pull/20477 on https://github.com/dagster-io/dagster/pull/20407 to see how the API feels.
pytest

feat(dbt): use `TableMetadataEntries` to emit column lineage

---

python_modules/dagster/dagster/_core/definitions/asset_check_spec.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py
python_modules/dagster/dagster/_core/definitions/freshness_checks/non_partitioned.py
python_modules/dagster/dagster/_core/definitions/freshness_checks/time_window_partitioned.py
python_modules/dagster/dagster/_core/definitions/freshness_checks/utils.py
python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_check_decorator.py
python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_non_partitioned.py
python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_time_window_partitioned.py

Add metadata field to checkspec and asset check decorator
only added tests for the decorator case

Check spec metadata

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/dbt_packages/test_columns_metadata.py

Reverts dagster-io/dagster#20569
Unblocks https://github.com/dagster-io/dagster/pull/20613

Revert "feat(dbt): use `TableMetadataEntries` to emit column lineage"

---

js_modules/dagster-ui/packages/ui-core/src/search/AssetSearch.tsx

Improves handling to escape from search. Exit by:
- Hitting esc
- Clicking anywhere outside of the search box/results
https://github.com/dagster-io/dagster/assets/29110579/fc300a82-818f-4c09-8863-8d6d216aab6c

[ui] Click outside / hit esc to hide search

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetsOverview.tsx

Refactor the links into buttons.
https://github.com/dagster-io/dagster/assets/2798333/4c93b3d9-c43f-47f2-a31a-f991282ec730
Loaded up the UI

Refactor links to buttons

---

docs/sphinx/sections/api/apidocs/asset-checks.rst
python_modules/dagster/dagster/__init__.py
python_modules/dagster/dagster/_core/definitions/freshness_checks/non_partitioned.py

Top level export + api docs addition for freshness check builders

Expose freshness builders publicly

---

python_modules/dagster/dagster/_core/definitions/freshness_checks/non_partitioned.py
python_modules/dagster/dagster/_core/definitions/freshness_checks/time_window_partitioned.py

experimentalize freshness checks APIs

Experimentalize freshness check apis

---

python_modules/dagster/dagster/_core/definitions/utils.py

Raise correct error for invalid tag value

---

CHANGES.md

1.6.12 changelog

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeDefinition.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetTableFragment.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetTableFragment.types.ts
js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetsCatalogTable.types.ts
js_modules/dagster-ui/packages/ui-core/src/ui/Filters/useAssetTagFilter.tsx
js_modules/dagster-ui/packages/ui-core/src/ui/Filters/useStaticSetFilter.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/types/VirtualizedRepoAssetTable.types.ts
js_modules/dagster-ui/packages/ui-core/src/workspace/types/WorkspaceAssetsRoot.types.ts
python_modules/dagster-test/dagster_test/toys/big_honkin_asset_graph.py

[Assets] Allow filtering by tag

---

docs/content/concepts/assets/software-defined-assets.mdx

Compliments #20590 to fix #20554
👀

[docs] remove reference to segmented string for multi-component asset key_prefix

---

python_modules/dagster/dagster/_core/definitions/assets_job.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets_job.py

#20509 broke job construction for the case where there is an assets def with a dependency on only a subset of the asset keys of a parent multi-asset. Remarkably, we had no test coverage for this case.
This PR fixes this by permitting inclusion of the whole upstream multi-asset if it is unsubsettable.
Added new unit test.

Fix upstream partial dependency multi-asset case

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_checks.py

handle unexpected relationship tests

---

js_modules/dagster-ui/packages/ui-core/src/search/useGlobalSearch.tsx

Make links to the asset table with filters exportable.

Export links to asset table filters

---

docs/content/integrations/dbt/reference.mdx

Fixes broken formatting introduced by #20549
local

[docs] - Fix dbt reference

---

js_modules/dagster-ui/packages/ui-core/src/search/BuildAssetSearchResults.tsx
js_modules/dagster-ui/packages/ui-core/src/search/SearchResults.tsx
js_modules/dagster-ui/packages/ui-core/src/search/types.ts
js_modules/dagster-ui/packages/ui-core/src/search/types/useGlobalSearch.types.ts
js_modules/dagster-ui/packages/ui-core/src/search/useGlobalSearch.tsx
js_modules/dagster-ui/packages/ui-core/src/ui/Filters/useAssetTagFilter.tsx
js_modules/dagster-ui/packages/ui-core/src/ui/tagAsString.ts

As the title.
Bumps the search query version as we're now fetching new fields.
Internal PR: https://github.com/dagster-io/internal/pull/8869

[ui] Enable building search results for tags

---

docs/content/guides/dagster-pipes/aws-lambda.mdx
examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/lambda/dagster_code.py
examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/lambda/lambda_function.py

move bare code block to referencing real python files.
fix the code snippet in [1] ([see details in slack](https://dagsterlabs.slack.com/archives/C05M31J51J6/p1711139990552689?thread_ts=1711138351.981709&cid=C05M31J51J6))
also mention and navigate in case readers are interested in how pipes work with our dev to prod testing story
preview

docs: update code snippet in lambda pipes

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py

refactor(dbt): remove unused adapter metadata helper function

---

js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/AssetChecks.tsx

support multi-line descriptions for asset check results

---

docs/next/pages/_document.js

This should hopefully fix the ugly font issue for people without Open Sans". 
Before
After

[docs] Use normal font-feature-settings for AskAI bot

---

examples/project_fully_featured/project_fully_featured/assets/__init__.py
python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/legacy/test_asset_defs.py

Resolves https://github.com/dagster-io/dagster/issues/20670.
Note that this is a breaking change, so wait until 1.7 to land this.
pytest

refactor(dbt)!: remove `@classmethod` from `DagsterDbtTranslator` methods

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py

These messages are a bit incomprehensible if there's a lot going on, so add some more spacing.
eyes

feat(dbt): add spacing to exception messages

---

python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py

Looks like an accidental commit from #20424. Remove it.
N/A

refactor(dbt): remove unused code

---

.buildkite/dagster-buildkite/dagster_buildkite/pipelines/dagster_oss_main.py

IMO if you pass NO_SKIP, we should run the full compatibility pipeline.
Test plan: this diff should run the full compatibility pipeline

Run the full internal-oss pipeline on NO_SKIP

---

examples/project_du_dbt_starter/dagster_university/jobs/__init__.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
python_modules/dagster-test/dagster_test/toys/user_computed_data_versions/__init__.py
python_modules/dagster/dagster/_core/definitions/asset_job.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection_error_informative.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_unresolved_asset_job.py
python_modules/dagster/dagster_tests/core_tests/host_representation_tests/test_external_sensor_data.py
python_modules/dagster/dagster_tests/core_tests/test_data_time.py
python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenarios/auto_materialize_policy_scenarios.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenarios/freshness_policy_scenarios.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_asset_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_asset_daemon_fast.py
python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_decorator_with_check_specs.py
python_modules/dagster/dagster_tests/definitions_tests/test_automation_policy_sensor_definition.py
python_modules/dagster/dagster_tests/definitions_tests/test_freshness_policy_sensor.py
python_modules/dagster/dagster_tests/definitions_tests/test_sensor_invocation.py
python_modules/dagster/dagster_tests/general_tests/test_pending_repository.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/dbt_packages/test_columns_metadata.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_checks.py

```
codemod -d . --extensions py 'AssetSelection.keys' 'AssetSelection.assets'
```

AssetSelection.keys -> AssetSelection.assets in tests and examples

---

docs/content/_navigation.json
docs/content/concepts.mdx
docs/content/concepts/assets/asset-checks.mdx
docs/content/concepts/assets/asset-checks/define-execute-asset-checks.mdx
docs/sphinx/sections/api/apidocs/asset-checks.rst

following https://github.com/dagster-io/dagster/pull/20708

Remove experimental from checks docs

---

helm/dagster/charts/dagster-user-deployments/templates/helpers/_helpers.tpl

I mistakenly believed BK to have run on this public PR and landed it. I need to edit it to allow the value to not be present.
`git revert -n`

Reverting the breaking PR

---

python_modules/dagster/dagster/_core/definitions/metadata/__init__.py
python_modules/dagster/dagster/_core/definitions/metadata/table.py
python_modules/dagster/dagster_tests/definitions_tests/metadata_tests/test_table_metadata_entries.py
python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py

refactor(metadata): sort and de-duplicate `deps_by_column`

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx

As the title. Used in https://github.com/dagster-io/internal/pull/8974

Export useAllAssets hook

---

js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadSetupFromRunRoot.tsx

When re-executing a run with an op selection, the Launchpad incorrectly discards the op selection. This appears to be because we aren't setting a `solidSelectionQuery` value for the session, which leads to the op selection state being `*`.
Repair this by setting `solidSelectionQuery` based on the `solidSelection` value returned by `ConfigForRunQuery`.
I also moved the session creation step into `onCompleted`, because it appears that we can inadvertently kick off an infinite effect loop by saving the session. The storage data returned by the save can re-run the effect, the save occurs within the effect, and so on. Instead, we will now just save the session when the query completes with a `Run` object.
Run `hammer` job with only `chase_giver` selected. View the create run, then open that …

[ui] Fix runs launched from op selection runs

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetFeatureContext.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/AssetChecks.tsx

remove unused imports

---

python_modules/dagster/dagster/_core/definitions/asset_job.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_job.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_unresolved_asset_job.py

You can hit this error with check_specs, so add them to the log

add checks to subset error msg

---

js_modules/dagster-ui/packages/app-oss/src/InjectedComponents.tsx
js_modules/dagster-ui/packages/ui-core/src/app/BaseFallthroughRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/app/ContentRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/app/FallthroughRoot.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/app/FallthroughRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/app/InjectedComponentContext.tsx

part 2 of https://github.com/dagster-io/dagster/pull/20767
Shadow-dagit catalog mode

[2/2] FallthroughRoot injected component

---

python_modules/libraries/dagster-polars/setup.py

https://dagsterlabs.slack.com/archives/C03EQ628RS7/p1711648459441669
Latest version is breaking tests. Could land this to get the build green unless the fix is easy

pin polars <0.20.17

---

python_modules/dagster/dagster/_core/definitions/metadata/table.py
python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py

We should let column lineage stabilize for at least a minor release.
N/A

feat(metadata): mark column lineage as experimental

---

js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/useAssetTabs.test.tsx

Fixes errors in bk: https://buildkite.com/dagster/dagster-dagster/builds/79663#018e866a-c732-4c4a-9daf-247c83d99ab7
bk

fix(asset-overview): remove assertion for plots tab

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetSidebarActivitySummary.tsx

Title says it all. Also, this goes more in line with how we display this information in the asset details page.
eyes

feat(sidebar): remove references to runs

---

js_modules/dagster-ui/packages/ui-core/src/assets/ChangedReasons.tsx

We decided we liked "changed" better than "modified" this updates the UI for that

[ui] update modified to changed in ui

---

CHANGES.md

docs: add `1.6.14` changelog

---

python_modules/dagster/dagster/_core/definitions/metadata/table.py
python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/conftest.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/dbt_packages/test_columns_metadata.py
python_modules/libraries/dagster-dbt/pytest.ini

A follow up to https://github.com/dagster-io/dagster/pull/20697. Pass this down to more places.
Simulate other SQL dialects against the jaffle shop queries. Fix any errors.

fix(dbt): use dialect in sqlglot parsing

---

python_modules/dagster/dagster_tests/core_tests/run_coordinator_tests/test_queued_run_coordinator.py
python_modules/dagster/dagster_tests/daemon_tests/test_queued_run_coordinator_daemon.py
python_modules/dagster/dagster_tests/storage_tests/test_event_log.py
python_modules/dagster/dagster_tests/storage_tests/test_io_manager.py
python_modules/dagster/dagster_tests/storage_tests/test_polling_event_watcher.py
python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
python_modules/dagster/dagster_tests/storage_tests/utils/run_storage.py
python_modules/libraries/dagster-mysql/dagster_mysql_tests/test_event_log.py
python_modules/libraries/dagster-postgres/dagster_postgres_tests/test_event_log.py

Changes daemon tests to use UUID run ids
BK

change daemon tests to use UUID run ids

---

examples/docs_snippets/docs_snippets/concepts/webserver/graphql/client_example.py
python_modules/dagster-graphql/dagster_graphql_tests/client_tests/test_submit_pipeline_execution.py
python_modules/dagster-graphql/dagster_graphql_tests/client_tests/test_terminate_run.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_checks.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_execute_pipeline.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_instance.py
python_modules/dagster/dagster_tests/cli_tests/command_tests/test_launch_command.py
python_modules/dagster/dagster_tests/cli_tests/test_api_commands.py
python_modules/dagster/dagster_tests/core_tests/graph_tests/test_graph.py
python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py
python_modules/dagster/dagster_tests/core_tests/run_coordinator_tests/test_default_run_coordinator.py
python_modules/dagster/dagster_tests/core_tests/run_coordinator_tests/test_queued_run_coordinator.py
python_modules/dagster/dagster_tests/daemon_tests/test_queued_run_coordinator_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenario_state.py
python_modules/dagster/dagster_tests/launcher_tests/test_default_run_launcher.py
python_modules/dagster/dagster_tests/launcher_tests/test_persistent_grpc_run_launcher.py
python_modules/dagster/dagster_tests/logging_tests/test_stdout.py
python_modules/dagster/dagster_tests/storage_tests/test_event_log.py
python_modules/dagster/dagster_tests/storage_tests/test_io_manager.py
python_modules/dagster/dagster_tests/storage_tests/test_polling_event_watcher.py
python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
python_modules/dagster/dagster_tests/storage_tests/utils/run_storage.py
python_modules/libraries/dagster-mysql/dagster_mysql_tests/test_event_log.py
python_modules/libraries/dagster-postgres/dagster_postgres_tests/test_event_log.py
python_modules/libraries/dagster-wandb/dagster_wandb/io_manager.py
python_modules/libraries/dagster-wandb/dagster_wandb_tests/test_io_manager.py

Changes miscellaneous tests to use UUID run ids
BK

convert misc tests to use uuid run_ids

---

docs/content/concepts/assets/asset-checks.mdx
docs/content/concepts/assets/asset-checks/define-execute-asset-checks.mdx
examples/docs_snippets/docs_snippets/concepts/assets/asset_checks/blocking.py
examples/docs_snippets/docs_snippets_tests/concepts_tests/assets_tests/test_asset_checks.py

Document `@asset_check(blocking=True)`

[docs] - Blocking asset checks (DOC-163)

---

python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

Didn't catch these because it bypasses the check call on the instance
BK

storage tests uuid missing patch

---

python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_check_selection.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_checks.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/legacy/test_asset_defs.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/legacy/utils.py

Default dbt asset checks on

---

pyright/master/requirements-pinned.txt
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/dlt/asset_decorator.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/dlt/constants.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/dlt/resource.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/dlt_tests/test_dlt.py

Fixes issue mentioned by @hello-world-bfree in base-PR review: https://github.com/dagster-io/dagster/pull/20759#discussion_r1542258917
By explicitly retrieving dlt source resource from metadata.
```
pytest
```

[dagster-embedded-elt][dlt] fix subset selection

---

.buildkite/dagster-buildkite/dagster_buildkite/python_packages.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/dlt/asset_decorator.py

(fix) remove unnecessary pyright ignores

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py
python_modules/libraries/dagster-dbt/dagster_dbt/utils.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py

Enables the extraction of some of the adapter profile information for reuse.
BK

reconstruct dbt adapter in DbtCLIInvocation

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/filterAssetDefinition.test.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/useAssetDefinitionFilterState.tsx

1. Add back compute kind tag filtering
2. Fix some bugs + add tests
jest

Repair asset filtering logic

---

python_modules/dagster/dagster/_core/definitions/asset_graph.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py

Fix the execution set logic for asset checks, and test it on `@multi_asset_check`s

@multi_asset_check execution set

---

js_modules/dagster-ui/packages/ui-core/src/search/BuildAssetSearchResults.tsx
js_modules/dagster-ui/packages/ui-core/src/ui/usePersistedExpansionState.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedRepoAssetTable.tsx

Generalizes storing row toggle state in local storage for use in https://github.com/dagster-io/internal/pull/9048

[ui] Generalize persisting clickable row state

---

docs/content/deployment/guides/kubernetes/customizing-your-deployment.mdx

Summary:
Documenting that we are changing the default from SHALLOW to DEEP and fleshing out the examples.

Docs for k8s precedence changes

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNodeMenu.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/CollapsedGroupNode.tsx

These materialize buttons should be gated by the featureContext `canSeeMaterializeAction`
👀

Gate more materialize buttons by featureContext

---

docs/content/concepts/assets/asset-auto-execution.mdx
docs/content/dagster-cloud/managing-deployments/deployment-settings-reference.mdx
examples/docs_snippets/docs_snippets/concepts/assets/auto_materialize_sensor.py
examples/docs_snippets/docs_snippets_tests/concepts_tests/assets_tests/test_auto_materialize.py

Auto-materialize sensor docs

---

python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_meta_config/dbt_project.yml
python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_meta_config/models/staging/schema.yml
python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_meta_config/seeds/schema.yml

Just add a test to make sure this is working.
pytest

test(dbt): assert correct owners when using dbt config inheritance

---

docs/dagster-university/pages/dagster-dbt.md
docs/dagster-university/pages/dagster-dbt/lesson-1/0-about-this-course.md
docs/dagster-university/pages/dagster-dbt/lesson-2/1-requirements.md
docs/dagster-university/pages/dagster-dbt/lesson-7/4-creating-the-manifest-during-deployment.md

Added pre-requisite experience section and support information for users in Dagster-DBT documentation lessons.
Added pre-requisite experience section for dbt, Dagster, and Python & SQL knowledge. Also included a support section with Slack community information.
Verify that the pre-requisite experience section is displayed correctly on the documentation lessons.
To provide users with the necessary background needed to successfully complete the course and to offer assistance through the community Slack channel.
---

[du-dbt] adding pre-reqs and detail to the deployment step (DEV-220)

---

python_modules/libraries/dagster-snowflake/dagster_snowflake/resources.py
python_modules/libraries/dagster-snowflake/dagster_snowflake_tests/test_resources.py

Return the correct case from fetch_last_updated_times
Changed test to ensure that table case is same going in as out.

Return the correct case from tables

---

docs/content/dagster-cloud/deployment/serverless.mdx
docs/content/dagster-cloud/getting-started.mdx
docs/content/dagster-cloud/managing-deployments/branch-deployments/using-branch-deployments-with-github.mdx

This PR updates mentions of `deploy.yml` & `branch-deployments.yml` in the docs to `dagster-cloud-deploy.yml`.
eyes

[docs] - Update deploy.yml & branch-deployments.yml to dagster-cloud-deploy.yml

---

docs/content/_navigation.json

[easy] customzing => customizing

---

docs/content/dagster-cloud/getting-started.mdx

This PR fixes some wonky Markdown formatting in the Cloud GS guide.
👀

[docs] - Fix link formatting in Cloud GS guide

---

js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/filterAssetDefinition.test.tsx

ChangeReason.INPUTS -> ChangeReason.DEPENDENCIES pt 2

---

docs/next/pages/_document.js

Set this on a parent element since i'm not sure the web component takes style as a prop.
doitinproduction

Set font-feature-settings for co-pillot AI widget

---

docs/content/integrations/dbt/reference.mdx
examples/docs_snippets/docs_snippets/integrations/dbt/dbt.py

update dbt checks docs

---

examples/tutorial/README.md

be explicit that this project is supposed to be empty

---

docs/dagster-university/pages/dagster-dbt/lesson-7/5-preparing-for-a-successful-run.md

[dagster-university] Refining environment variable descriptions for dbt DU

---

docs/dagster-university/pages/dagster-dbt/lesson-2/1-requirements.md
docs/dagster-university/pages/dagster-dbt/lesson-2/2-set-up-the-dagster-project.md
examples/project_du_dbt_starter/README.md
examples/project_du_dbt_starter/setup.py

[du-dbt] adding starter project to quickstart templates (DEV-168)

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNode.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/CalculateUnsyncedDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/Stale.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedAssetRow.tsx

As titled. Motivated by [this thread](https://github.com/dagster-io/dagster/pull/21065)
Locally viewed the asset graph and it still rendered correctly. Also storybook

Remove isAssetStaleFiltered in favor of being consistent and always showing "all"

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/asset_checks.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_all_snapshot_ids.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_checks.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py

surface the blocking toggle so we can display it in the UI

blocking checks gql

---

docs/content/community/contributing.mdx

[Contributing](https://docs.dagster.io/community/contributing) 6 days ago there was [update of](https://github.com/dagster-io/dagster/commit/9a85245c18254e20b4c14d0820c04fcebfdb7079) ipython to 8.23.0 which [requires](https://github.com/ipython/ipython/blob/main/pyproject.toml#L23) mentioned python version.
installed env from zero

fix: update contributing documentation

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/__fixtures__/AssetNode.fixtures.ts
js_modules/dagster-ui/packages/ui-core/src/assets/ChangedReasons.tsx
js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster/dagster/_core/definitions/asset_graph_differ.py
python_modules/dagster/dagster_tests/general_tests/asset_graph_differ_tests/asset_graph_scenarios/tags_asset_graph/base_asset_graph.py
python_modules/dagster/dagster_tests/general_tests/asset_graph_differ_tests/asset_graph_scenarios/tags_asset_graph/branch_deployment_change_tags.py
python_modules/dagster/dagster_tests/general_tests/asset_graph_differ_tests/test_asset_graph_differ.py

Change Tracking can detect changes in the tags on an asset
new unit test, ran shadow dagit against our deployment and saw tag changes detected

[graph diffing] add tag change reason

---

docs/content/concepts/io-management/io-managers.mdx

This PR addresses the broken link referenced in #21074 
eyes, local

[docs] - Fix link in I/O managers page

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py
python_modules/libraries/dagster-dbt/dagster_dbt/dbt_project.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py

updated existing test to test project based target setting also

[DbtProject] add target

---

python_modules/dagster/dagster/_core/definitions/asset_graph.py

nit refactor execution_set_asset_and_check_keys

---

docs/content/_navigation.json
docs/content/dagster-cloud.mdx
docs/content/dagster-cloud/managing-deployments.mdx
docs/content/dagster-cloud/managing-deployments/alerts.mdx

Add pagerduty docs to navigation

---

python_modules/dagster-webserver/dagster_webserver/webserver.py

Recreates https://github.com/dagster-io/dagster/pull/19046 but with `make ruff` run

Added mime-types for UI files

---

docs/sphinx/sections/api/apidocs/asset-checks.rst

schema change check api doc

---

python_modules/dagster/dagster/_core/definitions/asset_check_result.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/op_invocation.py
python_modules/dagster/dagster/_core/execution/plan/compute_generator.py
python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_check_decorator.py
python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_decorator_with_check_specs.py

Instead of re deriving asset check output names, fetch them off of the assets def

replace AssetCheckResult get_spec_python_identifier

---

js_modules/dagster-ui/packages/ui-core/src/app/Flags.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorerFilters.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/__stories__/AssetNode.stories.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/ChangedReasons.tsx

To be merged for launch event no sooner.
👀

Remove branch deployment asset graph diffing flag

---

CHANGES.md

👀  https://github.com/dagster-io/dagster/blob/04-11-changelog_1.7.1/CHANGES.md

changelog 1.7.1

---

js_modules/dagster-ui/packages/ui-core/src/live-data-provider/util.ts

Add url parameter for controlling batch size

---

js_modules/dagster-ui/packages/ui-core/src/assets/buildConsolidatedColumnSchema.tsx

fix(asset-overview): use lowercase columns when merging definition and materialization column schema

---

js_modules/dagster-ui/packages/ui-core/src/ui/Filters/useAssetTagFilter.tsx

Resolves https://github.com/dagster-io/dagster/issues/21082
Now:

[ui] Sort tag filters by key and value

---

python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py

docs(dbt): add example to access dbt event stream

---

docs/sphinx/sections/api/apidocs/assets.rst
docs/sphinx/sections/api/apidocs/ops.rst

docs: move `AssetKey` from `ops.rst` to `assets.rst`

---

python_modules/dagster/README.md

As requested by staff, updating the README temporarily to mention Dagster+.

updating readme for dagster plus event

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
python_modules/dagster-graphql/dagster_graphql/implementation/loader.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py

Summary:
This class is useful for many more things than just loading the last materialization.
Test Plan: BK

Rename BatchMaterializationLoader to BatchAssetRecordsLoader

---

python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/dlt/asset_decorator.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/asset_decorator.py

Noticed that this could be simplified when reading the `embedded_elt` implementation!

refactor: remove unnecessary `inner` function from `@XXX_assets`

---

docs/content/dagster-plus/insights.mdx
docs/content/dagster-plus/insights/asset-metadata.mdx
docs/content/dagster-plus/insights/exporting-insights-metrics.mdx
docs/content/dagster-plus/insights/integrating-bigquery-and-dbt.mdx
docs/content/dagster-plus/insights/integrating-bigquery.mdx
docs/content/dagster-plus/insights/integrating-external-metrics.mdx
docs/content/dagster-plus/insights/integrating-snowflake-and-dbt.mdx
docs/content/dagster-plus/insights/integrating-snowflake.mdx

This PR removes the `experimental` label from the Insights docs. 🎉 
👀

[docs] - Remove experimental label from Insights (DOC-204)

---

python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

Missed a spot in https://github.com/dagster-io/dagster/pull/20928

Use uuid run_id in test

---

python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

Would have caught gaps in the AssetRecordsFilter implementation in Cloud.
BK

more comprehensive tests for the event log storage fetch_X APIs

---

CHANGES.md
docs/content/concepts/assets/asset-observations.mdx
docs/content/dagster-plus/deployment/serverless.mdx
docs/content/integrations/airflow/from-airflow-to-dagster.mdx
docs/content/integrations/deltalake/using-deltalake-with-dagster.mdx
python_modules/dagster-pipes/dagster_pipes/__init__.py
python_modules/dagster/dagster/_core/definitions/asset_condition/asset_condition.py
python_modules/dagster/dagster/_core/definitions/asset_graph_differ.py
python_modules/dagster/dagster/_core/definitions/dependency.py
python_modules/dagster/dagster/_core/definitions/reconstruct.py
python_modules/dagster/dagster/_core/definitions/schema_change_checks.py
python_modules/dagster/dagster/_core/execution/plan/external_step.py
python_modules/dagster/dagster/_core/storage/dagster_run.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/managed/generated/sources.py
python_modules/libraries/dagster-aws/dagster_aws/emr/pyspark_step_launcher.py
python_modules/libraries/dagster-deltalake/dagster_deltalake/io_manager.py
python_modules/libraries/dagster-k8s/dagster_k8s/ops/k8s_job_op.py
python_modules/libraries/dagster-wandb/dagster_wandb/launch/configs.py

the the purge

---

docs/content/concepts/assets/asset-checks/define-execute-asset-checks.mdx
docs/content/concepts/testing.mdx
examples/docs_snippets/docs_snippets/concepts/assets/asset_checks/test_asset_check.py

This PR adds a section for testing asset checks to the Testing documentation.
👀

[docs] - Add testing for asset checks

---

python_modules/dagster/dagster/_core/storage/partition_status_cache.py
python_modules/dagster/dagster_tests/storage_tests/test_partition_status_cache.py

Summary:
If a run that planned to materialize an asset is deleted partway through, it currently stays marked as "in progress", since it is not returned in the query that checks for finished runs. Instead, remove runs that no longer exist from both the "in-progress" list and the "failed" list.

Correctly handle deleted runs when determining in progress runs for the asset status partition cache

---

docs/next/components/Header.tsx

Need to update these header buttons. 
next dev locally

Change docs header copy

---

python_modules/dagster/dagster/_core/definitions/metadata/__init__.py

use DagsterModel as superclass for NamespacedMetadataSet

---

docs/content/concepts/io-management/unconnected-inputs.mdx

This PR updates the Unconnected inputs page to include a link to the **When to use I/O managers** section of the I/O manager concept page. It also does some minor formatting and copy clean up.
local

[docs] [i/o] - Unconnected inputs (DOC-130)

---

js_modules/dagster-ui/packages/ui-core/src/app/QueryRefresh.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx
js_modules/dagster-ui/packages/ui-core/src/live-data-provider/LiveDataThread.tsx
js_modules/dagster-ui/packages/ui-core/src/live-data-provider/LiveDataThreadManager.tsx
js_modules/dagster-ui/packages/ui-core/src/overview/OverviewAssetsRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/overview/OverviewTabs.tsx
js_modules/dagster-ui/packages/ui-core/src/overview/OverviewTimelineRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/performance.tsx

As titled, adding manual instrumentation
locally loaded the page and waited for everything to load.

Add manual instrumentation for overview assets root

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py

allow custom subclasses
added test

[DbtCliResource] pass through kwargs

---

docs/content/concepts/assets/asset-checks/checking-for-data-freshness.mdx

Fix incorrect import in freshness docs

Fix freshness docs typo

---

docs/content/concepts/assets/external-assets.mdx
docs/content/concepts/webserver/graphql-client.mdx
docs/content/dagster-plus/account/authentication/okta/saml-sso.mdx
docs/content/dagster-plus/account/authentication/setting-up-azure-ad-saml-sso.mdx
docs/content/dagster-plus/account/authentication/setting-up-google-workspace-saml-sso.mdx
docs/content/dagster-plus/account/authentication/setting-up-onelogin-saml-sso.mdx
docs/content/dagster-plus/account/authentication/setting-up-pingone-saml-sso.mdx
docs/content/dagster-plus/getting-started.mdx
docs/content/dagster-plus/insights/exporting-insights-metrics.mdx
docs/content/dagster-plus/managing-deployments/branch-deployments.mdx
docs/content/dagster-plus/managing-deployments/branch-deployments/using-branch-deployments-with-gitlab.mdx
docs/content/dagster-plus/managing-deployments/dagster-plus-cli.mdx
docs/content/integrations/dbt.mdx
docs/sphinx/sections/api/apidocs/external-assets.rst
examples/docs_snippets/docs_snippets/concepts/webserver/graphql/client_example.py

Our documentation was updated to do SAML against dagster.plus, but that is no longer the case.
doc preview

Remove the erroneous URI

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py

[DbtCliResource] get_state_args

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/tox.py

https://dagsterlabs.slack.com/archives/C03EQ628RS7/p1713382127516139

pin uv to 0.1.32

---

python_modules/dagster/dagster/_core/definitions/asset_condition/asset_condition.py
python_modules/dagster/dagster/_model/__init__.py

Discussed here: https://dagsterlabs.slack.com/archives/C0549KFJJH1/p1713372802301219

ignore cached properties on DagsterModel

---

python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py
python_modules/dagster/dagster_tests/storage_tests/utils/run_storage.py

Summary:
Verify that in addition to passing the filter, the resulting migrated run has the expected tag.
Test Plan: BK

Fix updating tags in run body when migrating to a new repository

---

CHANGES.md

1.7.2 changelog

---

python_modules/dagster/dagster/_core/definitions/asset_checks.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_decorators.py

add tags argument to graph_asset decorator

---

python_modules/dagster/dagster/_core/definitions/metadata/__init__.py

Followup to https://github.com/dagster-io/dagster/pull/20625. My bad for missing this the first time around.

remove NamespacedMetadataEntries from docstring

---

docs/content/dagster-plus/insights/integrating-bigquery-and-dbt.mdx
docs/content/dagster-plus/insights/integrating-bigquery.mdx

We want to add a note about how the BQ cost metric is calculated.
Inspection

bigquery cost note

---

docs/content/guides/limiting-concurrency-in-data-pipelines.mdx
examples/docs_snippets/docs_snippets/deploying/concurrency_limits/dagster.yaml

Realized I never wrote up a docs section about the run throttling features released in early March.
BK

add concurrency docs section on the concurrency run throttling

---

js_modules/dagster-ui/packages/app-oss/package.json
js_modules/dagster-ui/packages/app-oss/src/App.tsx
js_modules/dagster-ui/packages/app-oss/src/NUX/CommunityNux.tsx
js_modules/dagster-ui/packages/ui-core/package.json
js_modules/dagster-ui/packages/ui-core/src/app/AppError.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetEdges.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/backfill/__tests__/BackfillPage.test.tsx
js_modules/dagster-ui/packages/ui-core/src/testing/mocking.ts
js_modules/dagster-ui/yarn.lock

Revert https://github.com/dagster-io/dagster/pull/21292

---

js_modules/dagster-ui/packages/ui-core/src/app/getVisibleFeatureFlagRows.tsx

By request from @braunjj.
View user settings dialog.

[ui] Rename nav/settings flag

---

docs/next/package.json
docs/next/yarn.lock
js_modules/dagster-ui/packages/app-oss/package.json
js_modules/dagster-ui/packages/eslint-config/package.json
js_modules/dagster-ui/packages/ui-components/package.json
js_modules/dagster-ui/packages/ui-core/package.json
js_modules/dagster-ui/yarn.lock

Bump TS to 5.4.5 to match vscode.
Buildkite

[ui] Upgrade TS to 5.4.5

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/asset_selections.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py

Summary:
Will allow us to display a clearer error message when there is an invalid asset selection in a sensor.
Test Plan: BK

Add an "assetsOrError" field to GrapheneAssetSelection

---

docs/content/guides/dagster/ml-pipeline.mdx
examples/docs_snippets/docs_snippets/guides/dagster/ml_pipelines/ml_pipeline.py

Remove duplicated line from documentation.

Remove duplicate line

---

docs/content/concepts/assets/asset-checks/checking-for-data-freshness.mdx

freshness guide touch-ups

---

js_modules/dagster-ui/packages/ui-components/package.json
js_modules/dagster-ui/yarn.lock

Use updated eslint-config in ui-components.
Run lint, verify that there are no warnings.

[ui] Update ui-components lint config dep

---

python_modules/dagster/dagster/_utils/__init__.py
python_modules/dagster/dagster_tests/utils_tests/test_file_lock.py
python_modules/dagster/setup.py

add a utility function to coordinate updating artifacts between concurrent processes
added tests

[util] run_with_concurrent_update_guard

---

python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster/_daemon/daemon.py
python_modules/dagster/dagster/_daemon/sensor.py
python_modules/dagster/dagster/_scheduler/scheduler.py

Summary:
This ensures that we can process errors even if they make it all the way up to the top-level core loop.
Fixes a related issue where the sensor daemon and interval daemon were ignoring their interval if an exception was raised in the iteration (unlike other IntervalDaemons).
Test Plan: BK

Add DaemonErrorCapture to top-level core_loop exception handler

---

python_modules/dagster/dagster/_utils/caching_instance_queryer.py

limit max updated size

---

js_modules/dagster-ui/packages/ui-core/src/overview/OverviewAssetsRoot.tsx

[ui] Display a deprecation banner on Overview > Activity > Assets [OSS only]

---

python_modules/dagster/dagster/_scheduler/scheduler.py

Summary:
Added a typo by mistake, spelling is hard

[easy] Fix SchedulerDaemon typo

---

python_modules/dagster/dagster/_core/definitions/metadata/__init__.py
python_modules/dagster/dagster_tests/definitions_tests/metadata_tests/test_table_metadata_set.py

avoid warnings for accessing __fields__ in pydantic 2

---

python_modules/dagster/dagster/_core/definitions/asset_checks.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_decorators.py

Closes https://github.com/dagster-io/dagster/issues/21356. Follows example https://github.com/dagster-io/dagster/pull/21272
Added unit test

Enable "owners" parameter for graph assets

---

docs/content/concepts/assets/asset-checks/checking-for-data-freshness.mdx

Incorrect APIs referenced here, just fixing.

Fix incorrect APIs in docs

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
python_modules/dagster/tox.ini

run DagsterModel tests in buildkite

---

python_modules/dagster/dagster/_model/pydantic_compat_layer.py
python_modules/dagster/dagster/_serdes/serdes.py
python_modules/dagster/dagster_tests/general_tests/test_serdes.py
python_modules/dagster/dagster_tests/model_tests/test_dagster_model_serdes.py

Were getting warnings and divergent behavior.

smooth over pydantic 2 and pydantic 1 in alias serializing

---

integration_tests/test_suites/daemon-test-suite/test_dagster_daemon_health.py
python_modules/dagster/dagster/_daemon/daemon.py

Summary:
I think https://github.com/dagster-io/dagster/pull/21384 caught all the places that we were actually sending an exception up into core_loop - but if we do again, make it wait a few seconds instead of potentially spamming errors in a tight loop.
Test Plan: Add an exception to a core_loop call, run dagster dev locally, see errors spaced apart

Add a recovery interval when a daemon raises an exception in its core_loop function

---

python_modules/dagster/dagster/_model/pydantic_compat_layer.py

correct mistake in pydantic compat layer

---

python_modules/dagster/dagster/_core/definitions/asset_job.py

fix error typo in asset_job.py

---

python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

We want stricter enforcement to save disk storing run ids.
BK

make run id uuid in asset check tests

---

python_modules/dagster/dagster/_core/definitions/metadata/__init__.py
python_modules/dagster/dagster_tests/core_tests/test_metadata.py
python_modules/dagster/dagster_tests/execution_tests/test_metadata.py

This reverts commit 4f5139af8bb111c4e565b98b5bfc05d7f942a2a9.
Causing an error in dagstermill logging

Revert "MetadataValue subclasses to DagsterModel (#21324)"

---

docs/dagster-university/pages/dagster-dbt.md
docs/dagster-university/pages/dagster-dbt/lesson-1/4-project-preview.md
docs/dagster-university/pages/dagster-dbt/lesson-7/1-overview.md
docs/dagster-university/pages/dagster-dbt/lesson-7/2-pushing-the-project-to-github.md
docs/dagster-university/pages/dagster-dbt/lesson-7/3-setting-up-dagster-cloud.md
docs/dagster-university/pages/dagster-dbt/lesson-7/4-creating-the-manifest-during-deployment.md
docs/dagster-university/pages/dagster-dbt/lesson-7/5-preparing-for-a-successful-run.md

This PR renames `Dagster Cloud` to `Dagster+` in the Dagster University content.
👀

[daggy-u] [dbt] - Rename to Dagster+

---

examples/with_openai/setup.py
examples/with_openai/with_openai/assets.py
examples/with_openai/with_openai/utils.py

This PR updates and add doc sources in the `with_openai` example so that we can showcase a more complete example in the blog post.
This PR also fixes the summaries of the sources provided to the model. Long story short, passing a list of summaries caused the model to always answer "I don't know", although it was working just fine before. Passing a string created by joining the summaries fixed the problem.
dagster dev
BK

Update sources in with_openai

---

python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

We're trying to get rid of unconstrained calls to `get_event_records` in favor of narrower-calls to the durable `fetch_X` storage methods.
Specifically, for planned materializations which do not have persistent storage in Cloud, we want to restrict calls to the `get_latest_planned_materialization_info` storage API.
BK

get rid of calls to get_event_records for planned materializations

---

python_modules/dagster/dagster/_core/execution/context/system.py

This is going to be a stack that batches and consolidates the logic to fetch upstream records. We are going to be building up a "preamble" to ExecutionStepContext construction that frontloads fetching. This is a first of series of PRs that does refactors to make that tractable. This just pushes down `is_sda_step` logic to a new standlone function `is_step_in_asset_graph_layer` that can be invoked before ExecutionStepContext is constructed
BK

Push down logic in is_sda_step into standalone function

---

examples/with_openai/setup.py
examples/with_openai/with_openai/assets.py
examples/with_openai/with_openai/utils.py

Reverts https://github.com/dagster-io/dagster/pull/21405
Appears to have broken this pyright-related test https://buildkite.com/dagster/dagster-dagster/builds/81462#018f2a9c-eced-4b36-815e-64128eb6729d
BK. Specifically `dagster-dbt dbt15-core 3.11`
[Before](https://buildkite.com/dagster/dagster-dagster/builds/81462#018f2a9c-edc3-4050-9932-8974578742b9)
[After](https://buildkite.com/dagster/dagster-dagster/builds/81526#018f2c5e-c215-4058-9c49-5d9b116ce06f)

Revert "Update sources in with_openai (#21405)"

---

examples/with_openai/setup.py
examples/with_openai/with_openai/assets.py
examples/with_openai/with_openai/utils.py
pyright/master/requirements-pinned.txt

This PR adds back the code reverted in https://github.com/dagster-io/dagster/pull/21506, but fixes the dependency conflict that caused the build to fail [here](https://buildkite.com/dagster/dagster-dagster/builds/81462#018f2a9c-eced-4b36-815e-64128eb6729d).
Same as https://github.com/dagster-io/dagster/pull/21405 but with the fix 
local `make rebuild_pyright_pins` to make sure it's not failing
BK

Update sources in with_openai with fix

---

docs/content/concepts/logging/custom-loggers.mdx
examples/docs_snippets/docs_snippets/concepts/logging/custom_logger.py

on loggers concept page, avoid JSON-serializing DagsterEvents in example

---

python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
python_modules/dagster/dagster_tests/daemon_sensor_tests/test_run_status_sensors.py

Summary:
Right now run status sensors process 5 events per tick, no matter what. In cases where you're following one job of many, this can mean that the vast majority of ticks do nothing while you churn through events from other jobs that you are not even subscribed to.
This PR proposes the following changes centered around improving throughput for that use case:
- Make the number of runs that you fetch configurable, and higher than 5 by default.
- Actually process up to 5 of those runs (that value is also configurable, separately)
- Update the cursor to be the last un-matching run after some run that you did process (or the whole fetched list if none were processed).
- If you happen to return more than 5 (maybe all the recent failures are from this job) then this will result in …

Better throughput in run status sensors

---

python_modules/dagster/dagster/_serdes/serdes.py

now that we have Pydantic models in use we can see that this method is not cheap so is worth memoizing
bk

[serdes] @cached_property all ObjectSerializer.constructor_param_names

---

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py

List -> Sequence in owners param annotation

---

python_modules/dagster/dagster/_core/definitions/assets.py

reduce boilerplate in AssetsDefinition._from_node

---

python_modules/dagster/dagster/_core/definitions/metadata/table.py

mark TableColumnDep experimental

---

python_modules/dagster/dagster/_serdes/serdes.py

Some additional performance tweaks from profiling `AssetDaemonCursor` payloads that are using `DagsterModel`
before & after 
the dark purple chunks in the left are pydantic import machinery frames

[serdes] pydantic model perf

---

python_modules/dagster/dagster/_core/definitions/events.py
python_modules/dagster/dagster_tests/definitions_tests/test_events.py

allow dagster/reporting_user in asset event tags

---

python_modules/dagster/dagster/_core/definitions/asset_condition/asset_condition.py
python_modules/dagster/dagster/_core/definitions/auto_materialize_rule.py
python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_impls.py

Continues work from the PR below, just banishing more traces of the AssetConditionEvaluationContext

[DS][2/n] Update signature of AutoMaterializeRule

---

python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py
python_modules/dagster/dagster/_core/definitions/auto_materialize_rule.py
python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_impls.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/asset_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/dep_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_context.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/slice_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/updated_since_cron_condition.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/asset_condition_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_dep_condition.py

Simple rename of SchedulingConditionEvaluationContext -> SchedulingContext

[DS][12/n] Rename SchedulingContext object

---

python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/legacy_context.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_context.py
python_modules/dagster/dagster/_core/definitions/freshness_based_auto_materialize.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/asset_condition_scenario.py

As title. The previous name was confusing as it implies that this is more "core" than it really is

[DS][16/n] Rename AssetConditionEvaluationContext to LegacyRuleEvaluationContext

---

python_modules/dagster-graphql/dagster_graphql/schema/asset_condition_evaluations.py
python_modules/dagster-graphql/dagster_graphql/schema/auto_materialize_asset_evaluations.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_condition_evaluations.py
python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py
python_modules/dagster/dagster/_core/definitions/asset_daemon_cursor.py
python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_evaluation.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/legacy/asset_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/legacy/legacy_context.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_context.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/serialized_objects.py
python_modules/dagster/dagster/_core/definitions/freshness_based_auto_materialize.py
python_modules/dagster/dagster/_core/scheduler/instigation.py
python_modules/dagster/dagster/_core/storage/legacy_storage.py
python_modules/dagster/dagster/_core/storage/schedules/base.py
python_modules/dagster/dagster/_core/storage/schedules/sql_schedule_storage.py
python_modules/dagster/dagster/_utils/test/schedule_storage.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/asset_condition_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_asset_condition.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_auto_materialize_asset_evaluation.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/updated_scenarios/asset_daemon_scenario.py
python_modules/libraries/dagster-mysql/dagster_mysql/schedule_storage/schedule_storage.py
python_modules/libraries/dagster-postgres/dagster_postgres/schedule_storage/schedule_storage.py

[DS][18/n] Move serialized objects into separate file

---

python_modules/dagster/dagster/_core/definitions/auto_materialize_rule.py
python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_impls.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/legacy/asset_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/legacy/rule_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/slice_conditions.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/updated_since_cron_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operators/boolean_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operators/dep_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/serialized_objects.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/asset_condition_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_dep_condition.py

[DS][21/n] Rename AssetConditionResult to SchedulingResult

---

python_modules/dagster/dagster/_daemon/daemon.py

Summary:
Lets you write daemons that don't all do the same work at the same time.
Test Plan: Corresponding PR that uses this in a new daemon

Add a jitter_seconds argument to IntervalDaemon

---

python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_check_decorator.py
python_modules/dagster/dagster_tests/definitions_tests/test_default_io_manager.py

sanity checking some theories while investigating a checks/io manager issue

add more checks io manager tests

---

docs/next/util/redirectUrls.json

- Verify redirect in deployed docs
- https://dagster-docs-5po774d82-elementl.vercel.app/dagster-cloud/deployment/agents/kubernetes

[docs] redirect dagster-cloud /dagster-plus/deployment/agents/kubernetes

---

docs/content/concepts/assets/asset-checks/checking-for-data-freshness.mdx
examples/docs_snippets/docs_snippets/concepts/assets/asset_checks/materializable_freshness_complete.py
examples/docs_snippets/docs_snippets/concepts/assets/asset_checks/materializable_freshness_in_pieces.py
examples/docs_snippets/docs_snippets/concepts/assets/asset_checks/source_data_freshness_complete.py
examples/docs_snippets/docs_snippets/concepts/assets/asset_checks/source_data_freshness_in_pieces.py
python_modules/dagster-test/dagster_test/toys/freshness_checks.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/last_update.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/time_partition.py
python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_last_update_freshness.py
python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_sensor.py
python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_time_partition_freshness.py

For consistency with build_column_schema_change_checks

refactor build freshness checks to return list

---

docs/content/integrations/dbt/reference.mdx
examples/docs_snippets/docs_snippets/integrations/dbt/dbt.py
python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py

remove lingering references to __dagster_no_value in docs

---

python_modules/dagster/README.md

removing d plus callout from readme

---

python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_condition.py

Forgot to add this into the original set of changes

[DS] Mark SchedulingCondition experimental

---

docs/content/concepts/dagster-pipes/subprocess.mdx

PyObject link for PipesSubprocessClient

---

python_modules/dagster/tox.ini

Going to edit this file so sorting it to provide some organization.
I am splitting up the dagster_tests into more subsuites to improve parallelism. Cleaning some stuff up along the way.
BK

Sort dagster/tox.ini

---

python_modules/dagster-graphql/dagster_graphql/implementation/events.py

fix circular import error

---

python_modules/dagster/dagster/_core/definitions/resource_annotation.py

Refactor _is_resource_annotation to use seven.is_subclass

---

python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py

`Definitions` itself now has functionality that removes the need for the `resolve_pending_repo_if_required` test helper

remove unnecessary definitions test helper

---

python_modules/dagster/dagster/_core/definitions/metadata/__init__.py
python_modules/dagster/dagster/_core/definitions/unresolved_asset_job_definition.py

remove unnecessary type quotes from metadata and unresolved asset job

---

CHANGES.md

1.7.5 changelog

---

python_modules/dagster/dagster/_core/definitions/metadata/metadata_value.py

TableColumnLineageMetadataValue.column_lineage

---

python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

In https://github.com/dagster-io/dagster/pull/21674, we restricted which asset tags we actually persist to the `asset_event_tags` table.  This PR formally adds a test checking that the unnecessary tags are filtered out.
BK

add asset tag filtering logic test

---

python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

Reverts dagster-io/dagster#21761
To unbreak the build

Revert "add asset tag filtering logic test"

---

python_modules/dagster/dagster/_core/definitions/time_window_partitions.py

The check in this method if the timezone name is the same on the datetime as what was passed in was incorrect. It was always false. It's hard to write correctly though honestly. There isn't a method on tzinfo or datetime that exposes the full timezone name that was used to create the `tzinfo`. 
Ideally, strftime shouldn't really be taking a datetime and a tz. Callers should just convert the datetime to the tz before calling the method. Instead of doing that larger refactor, I'm slipping in an optimization: Many of the methods on TimeWindowPartitionDef call this strftime method with timestamps that were generated by the cron iterator. All datetimes from that iterator are already using `self.timezone` for the `tzinfo`. 
bk

Fix the strftime tz argument and make optional

---

examples/project_dagster_university_start/setup.py
examples/project_du_dbt_starter/dagster_university/__init__.py
examples/project_du_dbt_starter/dagster_university/assets/metrics.py
examples/project_du_dbt_starter/dagster_university/assets/requests.py
examples/project_du_dbt_starter/dagster_university/assets/trips.py
examples/project_du_dbt_starter/dagster_university/partitions/__init__.py
examples/project_du_dbt_starter/dagster_university/schedules/__init__.py
examples/project_du_dbt_starter/dagster_university/sensors/__init__.py
examples/project_du_dbt_starter/setup.py

[du] updating dbt+du starter kit

---

js_modules/dagster-ui/packages/ui-core/src/nav/__tests__/LeftNavRepositorySection.test.tsx

As titled, fixing this flaky test. We need to wrap renders / userEvent.click with act to make it pass

Fix flaky test

---

python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/slice_conditions.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/updated_since_cron_condition.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_asset_condition.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_dep_condition.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_in_progress_condition.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_latest_time_window_condition.py

Noticed that some bits of the code still reference AssetCondition instead of SchedulingCondition

[DS][34/n] Remove some AssetCondition references

---

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/__init__.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/__init__.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/slice_conditions.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_condition.py
python_modules/dagster/dagster/_utils/caching_instance_queryer.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_failed_condition.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenario_state.py

As title -- this is basically exactly what you'd expect.

[DS][38/n] Create FailedSchedulingCondition

---

python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py

Add new startup transient reason

---

python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py

Tweak new transient error

---

helm/dagster/charts/dagster-user-deployments/templates/helpers/_helpers.tpl
helm/dagster/charts/dagster-user-deployments/values.schema.json
helm/dagster/schema/schema/charts/dagster_user_deployments/subschema/user_deployments.py
helm/dagster/schema/schema_tests/test_user_deployments.py
helm/dagster/values.schema.json

Same as #20691 but properly using default to allow setting the namespace.
bk

Allow setting namespace

---

python_modules/dagster/dagster/_seven/compat/datetime.py

Summary:
This breaks in certain zoneinfo environs

Unbreak using utc as a schedule timezone

---

CHANGES.md

1.7.6 changelog

---

python_modules/dagster/dagster/_core/definitions/asset_condition_evaluator.py
python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py
python_modules/dagster/dagster/_core/definitions/asset_daemon_cursor.py

Extract asset condition evaluation into its own class rather than in `AssetDaemonContext`
BK

extract AssetConditionEvaluator

---

js_modules/dagster-ui/packages/ui-core/src/nav/__tests__/LeftNavRepositorySection.test.tsx

Skip flaky test

---

python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_condition_evaluator.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_user_space_ds_api.py

As title. Rename AssetConditionEvaluator --> SchedulingConditionEvaluator.
Also moved the filed into the declarative_scheduling subfolder.
BK

AssetConditionEvaluator --> SchedulingConditionEvaluator

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/inputs.py
python_modules/dagster/dagster_tests/storage_tests/utils/run_storage.py

[graphql] add updatedBefore and createdAfter

---

python_modules/dagster/dagster/_core/definitions/assets.py

The constructor for `AssetsDefinition` is a huge method that's difficult to navigate. This change moves some of the sections that validate inputs into contained helper functions.

[spec-ify-assets-def] factor heavy AssetsDefinition validation into helpers

---

python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

We need a hook so that we can override the mock implementation for nested storages.
BK

need to create test overrides stub in event log test

---

CHANGES.md

Amend changelog to include analytics change

---

.github/workflows/build-docs.yml

Make updating the changelog also rebuild the docs site

---

.github/workflows/build-docs.yml

Make changing docs workflow file and changelog trigger build on push

---

python_modules/dagster/dagster/_core/definitions/asset_daemon_cursor.py

[auto-materialize] Avoid losing cursor values for assets that are not evaluated on a tick.

---

.pre-commit-config.yaml
pyproject.toml
python_modules/dagster/setup.py

for whatever reason ruff in vscode is crashing for me constantly so i am updating in the hopes of fixing that 
make ruff

update ruff 0.4.4

---

python_modules/dagster/dagster/_utils/alert.py

In some corporate contexts, it is important to have the ability to authenticate in the smtp server with a user that is not the sender email. This PR adds this functionality to Dagster's built-in email on failure sensor, keeping the default behavior of smtp_user == email_from.
make pyright
make ruff

Allow custom smtp user for email alerts

---

python_modules/libraries/dagster-polars/setup.py

This started breaking builds this morning.

Add pin for `polars`

---

python_modules/dagster/dagster/_core/storage/event_log/schema.py

accompanies https://github.com/dagster-io/internal/pull/8755

Add comment on checks unique index

---

python_modules/libraries/dagster-polars/dagster_polars/io_managers/delta.py
python_modules/libraries/dagster-polars/dagster_polars_tests/test_polars_delta.py

- Update references to use new `dagster/row_count` metadata entry
- `pytest`

[dagster-polars] fix usage of dagster/row_count metadata

---

python_modules/dagster/dagster_tests/definitions_tests/test_op_definition.py

fix pipe union test

---

python_modules/libraries/dagster-polars/setup.py

[dagster-polars] bump pin

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx

the recursive approach would degrade on certain large graph stuctures, so instead use an iterative approach to calculating depth 
existing tests in `js_modules/dagster-ui/packages/ui-core/src/asset-graph/__tests__/useAssetGraphData.test.tsx`
also validated against a large production asset graph

[ui] iterative calculateGraphDistances

---

js_modules/dagster-ui/packages/ui-core/src/nav/__tests__/LeftNavRepositorySection.test.tsx

Disable flaky jest test

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_checks.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py

Add Execution Duration metadata for dbt tests

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_checks.py

Follow up https://github.com/dagster-io/dagster/pull/22008 with passing through the count of failed rows. Going to start an discussion about metadata key names.

Add num_failures metadata for dbt tests

---

python_modules/automation/automation/docker/images/dagster-celery-k8s-editable/Dockerfile
python_modules/automation/automation/docker/images/dagster-celery-k8s/Dockerfile
python_modules/automation/automation/docker/images/dagster-k8s-editable/Dockerfile
python_modules/automation/automation/docker/images/dagster-k8s/Dockerfile
python_modules/automation/automation/docker/images/user-code-example/Dockerfile
python_modules/dagster-test/Dockerfile

https://github.com/astral-sh/uv/releases/tag/0.2.0
bk images build

updated dockerfile for uv 2.0

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py
python_modules/libraries/dagster-dbt/dagster_dbt/core/utils.py

In order to use the DuckDB dbt adapter for postprocessing tasks like querying row count, we needed to ensure the db filepath resolved properly. Often, this filepath was relative to the dbt project directory, requiring us to use `os.pushd` so that accesses would happen with the dbt project dir as working directory. 
Unfortunately, this working dir was occasionally getting overridden in between opening the `pushd` context and actually executing queries. I'm not sure what exactly was responsible for adjusting the working directory, but the status quo is pretty fragile.
Under the hood, this PR resorts to updating duckdb db paths in the dbt adapter to be absolute paths. This makes the test run much more reliably locally, and means we no longer need to set the working directory.
Also cleans up …

[dagster-dbt] force duckdb adapter to use abs path, fixing flaky test

---

js_modules/dagster-ui/packages/ui-core/src/app/HelpMenu.tsx

https://linear.app/dagster-labs/issue/FE-375/upgrade-in-app-share-feedback-form-to-become-create-a-support-ticket

Update help menu "Share feedback" -> "Create a support ticket"

---

docs/dagster-university/pages/dagster-essentials/lesson-9/updating-the-definitions-object.md

This PR removes some extra asterisks (likely leftover formatting) from Lesson 9 of DU Essentials.

[daggy-u] - Remove asterisks from code snippet

---

docs/content/dagster-plus/managing-deployments/alerts/email.mdx
docs/content/dagster-plus/managing-deployments/alerts/managing-alerts-cli.mdx
docs/content/dagster-plus/managing-deployments/alerts/microsoft-teams.mdx
docs/content/dagster-plus/managing-deployments/alerts/pagerduty.mdx
docs/content/dagster-plus/managing-deployments/alerts/slack.mdx
examples/docs_snippets/docs_snippets/dagster_cloud/alerts/cli_commands.yaml

[docs] Remove incorrect dagster-plus CLI command

---

CHANGES.md

release-1.7.7 CHANGELOG

---

js_modules/dagster-ui/packages/ui-core/src/app/Permissions.tsx
js_modules/dagster-ui/packages/ui-core/src/app/types/Permissions.types.ts
js_modules/dagster-ui/packages/ui-core/src/nav/__fixtures__/ReloadRepositoryLocationButton.fixtures.tsx

avoid loading the workspace to resolve permissions

[ui] move permissions fetch to locationStatusesOrError

---

python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/scheduled_since_condition.py
python_modules/dagster/dagster/_core/definitions/metadata/metadata_value.py
python_modules/dagster/dagster_tests/definitions_tests/metadata_tests/test_namespaced_metadata_set.py
python_modules/libraries/dagster-duckdb-pandas/dagster_duckdb_pandas_tests/test_type_handler.py
python_modules/libraries/dagster-gcp-pandas/dagster_gcp_pandas_tests/bigquery/test_type_handler.py
python_modules/libraries/dagster-snowflake-pandas/dagster_snowflake_pandas_tests/test_snowflake_pandas_type_handler.py

MetadataValue back to NamedTuple

---

python_modules/dagster/dagster/_core/storage/partition_status_cache.py

Summary:
Don't enumerate every key in the subset unless required.
Test Plan: BK + speedscope shows that we are no longer spending undue time calling get_partition_keys when the cache is already up to date

use subsets more effectively when calculating partition status cache

---

python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py

while attempting to reproduce https://github.com/dagster-io/dagster/issues/20325 while watching `pg_stat_activity`
`from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname='concurrency_slots'`
appeared more than I expected. We shouldn't need to re-query this so just cache it.
monitoring `pg_stat_activity` in `psql` while running ~10 runs of 
```
import time
from dagster import (
DynamicOut,
DynamicOutput,
graph_asset,
op,
)
@op(out=DynamicOut())
def create_range(context):
for i in range(100):
yield DynamicOutput(mapping_key=str(i), value=str(i))
@op(
tags={"dagster/concurrency_key": "serial"},
)
def sleep(context, value):
time.sleep(2)
return
@graph_asset(
group_name="test",
)
def break_dagster():
return create_range().map(sleep) …
```

[global concurrency] cache if supported

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
js_modules/dagster-ui/packages/ui-core/src/instigation/TickDetailsDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/instigation/types/TickDetailsDialog.types.ts
js_modules/dagster-ui/packages/ui-core/src/ticks/TickLogDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/ticks/types/TickLogDialog.types.ts
python_modules/dagster-graphql/dagster_graphql/schema/instigation.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py

fix(instigator-tick-logs): allow `tickId` to be `BigInt`

---

python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py

This builds off of the work in https://github.com/dagster-io/dagster/pull/22014, and implements __and__ and __or__ in a similar style.

[TWP][1/n] Efficient __and__ and __or__ operators for TimeWindowPartitionsSubsets

---

python_modules/dagster/dagster/_core/definitions/partition.py
python_modules/dagster/dagster/_core/definitions/time_window_partitions.py

As title -- this lets us skip a bit of tedious checking inside this class.

[TWP][3/n] Delegate non-time-window operations to superclass

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_condition_evaluations.py
python_modules/dagster-graphql/dagster_graphql/schema/backfill.py
python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/definitions/asset_graph_subset.py
python_modules/dagster/dagster/_core/definitions/asset_subset.py
python_modules/dagster/dagster/_core/definitions/data_time.py
python_modules/dagster/dagster/_core/definitions/partition.py
python_modules/dagster/dagster/_core/definitions/time_window_partition_mapping.py
python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_time_window_partition_mapping.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_subset.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_partitions_subset.py
python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py
python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

[TWP] Revert removal of PartitionKeysTimeWindowPartitionSubset

---

python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_decorators.py

stop ignoring AssetOut.code_version for graph assets

---

CHANGES.md

changelog for 1.7.8

---

python_modules/dagster/dagster/_core/definitions/asset_check_factories/utils.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_last_update_freshness.py
python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_time_partition_freshness.py

consolidate generating unique ids from asset and check keys

---

js_modules/dagster-ui/packages/ui-core/src/runs/RunTimeline.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/useRunsForTimeline.tsx
js_modules/dagster-ui/packages/ui-core/src/search/useGlobalSearch.tsx

I added this clowny O(n^2) deduping cuz it looked cool. We likely don't need the deduping anymore but for now just going to make it O(n) instead
app proxy, load run timeline

[RunTimeline] Change deduping logic to be O(n)

---

python_modules/dagster/dagster/_core/definitions/asset_graph.py

in AssetNode, access attrs via specs

---

python_modules/dagster/dagster/_core/definitions/asset_out.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py

use AssetSpec.dagster_internal_init in more places

---

python_modules/libraries/dagster-deltalake/dagster_deltalake/__init__.py
python_modules/libraries/dagster-deltalake/dagster_deltalake/handler.py

Closes [[dagster-deltalake] GcsConfig ImportError and TypeError for partitioned assets #22053](https://github.com/dagster-io/dagster/issues/22053)
`python -m pytest python_modules/libraries/dagster-deltalake/dagster_deltalake_tests`

[dagster-deltalake] Fix GcsConfig() ImportError and TypeError for partitioned assets

---

python_modules/libraries/dagster-polars/setup.py

https://github.com/dagster-io/dagster/pull/22002#issuecomment-2140855089

[dagster-polars] unpin polars

---

python_modules/dagster/dagster/_core/definitions/asset_spec.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/utils.py
python_modules/dagster/dagster_tests/definitions_tests/test_asset_spec.py

validate asset owners when constructing AssetSpec

---

python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/asset_condition_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_asset_condition.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_dep_condition.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_eager_condition.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_failed_condition.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_in_progress_condition.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_latest_time_window_condition.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_legacy_missing_condition.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_missing_condition.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_on_cron_condition.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_parent_newer_condition.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_scheduled_since_condition.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_updated_since_cron_condition.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_will_be_requested_condition.py

[DS][43/n] Rename AssetConditionScenarioState

---

python_modules/dagster/dagster/_core/definitions/declarative_scheduling/__init__.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/__init__.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/slice_conditions.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_context.py

[DS][47/n] Create CronTickPassedCondition

---

python_modules/dagster/dagster/_core/definitions/time_window_partition_mapping.py
python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_time_window_partition_mapping.py

As title -- I noticed that this caused an error upwards in the stack. There's no reason we can't map from an AllPartitionsSubset, we just need to convert it into a more explicit form first.

[DS][48/n] Allow AllPartitionsSubsets in TimeWindowPartitionMapping

---

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/definitions/asset_subset.py
python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_evaluation.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/legacy/legacy_context.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/parent_newer_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/slice_conditions.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operators/boolean_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operators/dep_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operators/newly_true_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operators/since_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_condition_evaluator.py
python_modules/dagster/dagster/_core/definitions/declarative_scheduling/serialized_objects.py
python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/asset_condition_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_result_value_hash.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_perf.py

The main thing here is just switching from the slower DagsterModel class to the very-fast NamedTuple class for some hot-path objects. Also contains a few minor simple tweaks here and there that I tossed in while py-spying.

[DS][59/n] Switch from DagsterModel to NamedTuple, misc. simple improvements

---

python_modules/dagster/dagster/_core/definitions/events.py
python_modules/dagster/dagster/_core/execution/plan/execute_step.py
python_modules/dagster/dagster_tests/definitions_tests/test_materialize_result.py

don't invoke IO manager when MaterializeResult is returned

---

python_modules/libraries/dagster-databricks/dagster_databricks/blueprints.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_blueprints.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_pipes.py

Databricks task blueprint

---

python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/assets_definition_factory.py

There's a bunch of logic to build `keys_by_input_name` and `keys_by_output_name`. This moves that all into the factory code
BK

Factor out keys_by_input_name and keys_by_output_name into the factory area

---

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/assets_definition_factory.py

There's a bunch of logic to create the appropriate partition mappings dictionary. Extracts that into the factory.
BK

Extract logic to create partition_mapping into the factory

---

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py

We have this logic that handles computing the resource keys to pass to underlying the op strewn about the creation pathways. We consolidate it into a function here.
BK

Extract compute_required_resource_keys

---

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py

The previously deleted lines were included as part of a botch merge conflict, and there was a naming collision. 
Fixes master that was broken blaming to https://github.com/dagster-io/dagster/pull/22228
BK

Fix master by redeleting code that causes incorrect behavior because of naming collision.

---

python_modules/dagster/dagster/_check/__init__.py
python_modules/dagster/dagster_tests/general_tests/check_tests/test_check.py

Adds a utility funtion to check for programatiically building calls based on a type signatures. 
added tests

[check] call builder

---

docs/content/tutorial/next-steps.mdx

Hopefully helps with feature discoverability.

Add asset checks + alerts to next steps section of tutorial.

---

python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster/_core/storage/tags.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_decorators.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/ops.py
python_modules/libraries/dagster-census/dagster_census/ops.py
python_modules/libraries/dagster-databricks/dagster_databricks/ops.py
python_modules/libraries/dagster-dbt/dagster_dbt/asset_defs.py
python_modules/libraries/dagster-dbt/dagster_dbt/cloud/ops.py
python_modules/libraries/dagster-dbt/dagster_dbt/ops.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/legacy/utils.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/ops.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_asset_defs.py
python_modules/libraries/dagster-gcp/dagster_gcp/bigquery/ops.py
python_modules/libraries/dagster-ge/dagster_ge/factory.py
python_modules/libraries/dagster-snowflake/dagster_snowflake/ops.py
python_modules/libraries/dagster-spark/dagster_spark/ops.py
python_modules/libraries/dagstermill/dagstermill/asset_factory.py
python_modules/libraries/dagstermill/dagstermill/factory.py
python_modules/libraries/dagstermill/dagstermill_tests/test_ops.py

We currently hardcode `"kind"` everywhere in tags for the compute kind. This PR factors out  a constant.

Make COMPUTE_KIND_TAG a constant

---

docs/content/getting-started/what-why-dagster.mdx

This is one of the first pages users see when coming to dagster; feels important to reference data quality here.

Add data quality tooling to the "what and why" of dagster

---

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py

We have this class `_Asset` that is really quite pointless. We should eliminate it. First step here to extract all logic from it to either before it or after it.
BK

Make _Asset have no logic in prep for its elimination

---

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py

This eliminates a bunch of necessary assignments and reduces an indent level by making `_Asset` a plain named tuple and its `__call__` function a normal function
BK

Eliminate layer of callables by making _Asset a non-callable NamedTuple

---

python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

event log storage test coverage.
BK

add test for desc get_records_for_run

---

python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py

For some reason this test is failing in BK but passing locally. Skipping until we figure out what's going on.
BK

Skip PartitionsDefinition test to fix BK

---

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/asset_decorator.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/dagster_sling_translator.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/sling_tests/test_asset_decorator.py

Add the ability to provide custom asset tags as part of the `DagsterSlingTranslator`.
Add a unit test.

[dagster-embedded-elt] Add custom tags to DagsterSlingTranslator

---

docs/content/concepts/assets/software-defined-assets.mdx

fix typo on assets def concepts page

---

examples/experimental/dagster-blueprints/dagster_blueprints/shell_command_blueprint.py
examples/experimental/dagster-blueprints/dagster_blueprints_tests/test_shell_command_blueprint.py

accept commands with spaces in ShellCommandBlueprint

---

python_modules/dagster/dagster/_core/definitions/asset_checks.py
python_modules/dagster/dagster/_core/definitions/asset_graph.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/resolved_asset_deps.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_defs_source_metadata.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/base_scenario.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/test_asset_defs.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/test_load_from_instance.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_code_references.py

The aim is to eventually remove these properties entirely. This removes a chunk of them, which gets us closer to that goal.

remove some usages of AssetsDefinition.attr_by_key props

---

python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py

Use `compute_required_resource_keys` in `asset_multi_check` code path
BK

Use compute required resources help in multi_asset

---

python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/decorator_assets_definition_builder.py

Rename build_asset_ins to build_named_ins
BK

Renamed build_asset_ins to build_named_ins

---

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/decorator_assets_definition_builder.py

Rename build_asset_outs to build_named_outs
BK

Rename build_asset_outs to build_named_outs

---

js_modules/dagster-ui/packages/ui-core/src/code-links/CodeLink.tsx

[ui] Fix the storybook build

---

python_modules/dagster/dagster/_core/definitions/unresolved_asset_job_definition.py

Improves the error message when multiple backfill policies are present in the constituent assets of an asset job by explicitly listing assets by backfill policy.

Improve error message for multiple backfill policies in an asset job

---

docs/content/dagster-plus/managing-deployments/alerts.mdx

As the title. Also documents the default policy functionality.

Add docs for budget and long-running run alerts

---

python_modules/dagster/dagster/_core/definitions/assets.py

The main things are:
- When specs are passed, rely on the set of specs, instead of keys_by_output_name, for the set of asset keys
- Only validate `partition_mappings` and `asset_deps` in the branch where they're allowed
This makes PRs like this one more more clear: https://github.com/dagster-io/dagster/pull/22165.

rearrange AssetsDefinition constructor for clarity

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_scheduler.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster_tests/daemon_tests/test_backfill_failure_recovery.py
python_modules/dagster/dagster_tests/daemon_tests/test_concurrency_daemon.py
python_modules/dagster/dagster_tests/daemon_tests/test_monitoring_daemon.py
python_modules/dagster/dagster_tests/daemon_tests/test_queued_run_coordinator_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/asset_condition_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/base_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenario_state.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenarios/active_run_scenarios.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenarios/auto_materialize_policy_scenarios.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenarios/auto_observe_scenarios.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenarios/observable_source_asset_scenarios.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenarios/partition_scenarios.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_asset_daemon_failure_recovery.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/updated_scenarios/asset_daemon_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/conftest.py
python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_last_update_freshness.py
python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_sensor.py
python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_time_partition_freshness.py
python_modules/dagster/dagster_tests/definitions_tests/test_partitioned_schedule.py
python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py
python_modules/dagster/dagster_tests/storage_tests/utils/run_storage.py

Mopping up the remaining usage of pendulum_freeze_time.

[3/n] Move pendulum_freeze_time into a helper function part 3: everything else

---

python_modules/dagster/dagster/_seven/__init__.py
python_modules/dagster/dagster/_seven/compat/datetime.py
python_modules/dagster/dagster_tests/core_tests/host_representation_tests/test_external_data.py
python_modules/dagster/dagster_tests/core_tests/test_op_invocation.py
python_modules/dagster/dagster_tests/definitions_tests/test_multi_partitions.py
python_modules/dagster/dagster_tests/execution_tests/misc_execution_tests/test_metadata.py
python_modules/dagster/dagster_tests/scheduler_tests/test_cron_string_iterator.py
python_modules/dagster/dagster_tests/storage_tests/test_db_io_manager.py
python_modules/libraries/dagster-aws/dagster_aws_tests/s3_tests/test_compute_log_manager.py
python_modules/libraries/dagster-azure/dagster_azure_tests/blob_tests/test_compute_log_manager.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_freshness_checks.py
python_modules/libraries/dagster-gcp/dagster_gcp_tests/gcs_tests/test_compute_log_manager.py

Mop up remaining usage of pendulum in our test suite.
BK

[7/n] remove pendulum from the rest of the tests

---

python_modules/dagster/dagster/_core/definitions/time_window_partitions.py

Summary:
By always passing in the tz and assuming that the passed in datetime was already in that timezone (which was already true) we don't need to care if the timezone can be derived from the datetime or not.
Test Plan: BK

[8/n] Remove pendulum-specific logic from dst_safe_strftime

---

python_modules/libraries/dagster-dbt/dagster_dbt/freshness_builder.py

Marks dbt freshness check builder as experimental.

Mark dbt freshness as experimental

---

python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_dbt_mixed_freshness/models/schema.yml
python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_last_update_freshness/models/schema.yml
python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_last_update_freshness_multiple_assets_defs/models/schema.yml
python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_time_partition_freshness/models/schema.yml
python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_time_partition_freshness_multiple_assets_defs/models/schema.yml

fix prettier

---

js_modules/dagster-ui/packages/ui-core/src/runs/HourlyDataCache/HourlyDataCache.tsx

Fix undefined check

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud/asset_defs.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud/test_asset_defs.py

Resolves #21593.
TLDR: Previously dagster-dbt added new --select arg to dbt Cloud command when subsetting some assets from the job. However this approach does not work since dbt 1.5.0 when multiple --select args have been supported. So dagster have to remove all selection args from cloud job command in order to run only subsetted models in dbt.
Also previously pure string operations were used to modify command, which can lead to not properly removed `--selector=xyz` args. So quasi-parser for dbt command was created to extract and remove all `--select` and `--selector` args from materialisation command.
I also slightly modified tests for subsetting by adding cases with options which should not be removed be dagster inside subsetting and cases for correct removing all `--select` flags from …

fix subsetting for dagster-dbt cloud integration

---

python_modules/dagster/dagster/_check/__init__.py
python_modules/dagster/dagster/_model/decorator.py
python_modules/dagster/dagster_tests/general_tests/test_serdes.py
python_modules/dagster/dagster_tests/model_tests/test_dagster_model.py

* support empty models
* support setting default values in the model declaration
* ensure things like [] and {} are not shared
added tests

[dagster_model] support default values

---

python_modules/dagster/dagster/_core/definitions/decorators/decorator_assets_definition_builder.py

Trivial. Just sorting the attributes on `DecoratorAssetsDefinitionBuilderArgs`
BK

Sort attributes on DecoratorAssetsDefinitionBuilderArgs

---

python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_check_decorator.py

As title. As I am testing the asset check decorator codepaths I want to understand their test suites better. I figured a nice way of doing that would be to add typehinting
BK

Type  test_asset_check_decorator.py

---

python_modules/dagster/dagster/_check/__init__.py
python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_check_decorator.py
python_modules/dagster/dagster_tests/general_tests/check_tests/test_check.py

I was surprised this did not exist, so I added it and used it.
BK

Add is_iterable and use in test_asset_check_decorator

---

python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_decorator_with_check_specs.py

Add type checks to test_asset_decorator_with_check_specs.py

---

python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/decorator_assets_definition_builder.py

Push `_Op` creation into the builder.
BK.

Use create_op_definition instead of manually creating _Op

---

python_modules/dagster/dagster/_check/__init__.py

fix build_check_call for py3.8

---

docs/content/guides/dagster/using-environment-variables-and-secrets.mdx

Resolves https://github.com/dagster-io/dagster/issues/15787
👀

[docs] add example using EnvVar.int(str) to environment variables and secrets guide

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py

Just noticed these don't show up in the docs, fix that.
eyes

[DbtCliResource] @public get_defer|state_args

---

js_modules/dagster-ui/packages/ui-core/src/runs/useRunsForTimeline.tsx

https://dagsterlabs.slack.com/archives/C070G3UNNLW/p1718238323769339?thread_ts=1718238288.884269&cid=C070G3UNNLW
before: multiple rows for adhoc materializations
after: just a single one:

Fix Run Timeline splitting out ad hoc jobs

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/tox.py

unpinning patch version in hopes we will pick up fixes for network retries 
bk

[uv] 0.2.*

---

python_modules/libraries/dagster-dbt/dagster_dbt/dbt_project.py

[dagster_model] DbtProject

---

CHANGES.md

docs: add changelog for `1.7.10`

---

docs/content/apidocs/external-assets-rest.mdx

in external check evaluation docs, mark check_name as required

---

python_modules/dagster-webserver/dagster_webserver/external_assets.py
python_modules/dagster-webserver/dagster_webserver_tests/webserver/test_asset_events.py

fix typo in error for REST asset check evaluation construction

---

docs/next/package.json
docs/next/pages/_document.js
docs/next/yarn.lock

Actually install GTM
idk, just doing what nextjs said to do:

Setup GTM correctly

---

python_modules/dagster/dagster/_core/definitions/asset_graph.py

During `AssetGraph` construction, we call `AssetsDefinition.with_attributes` on every `AssetsDefinition` to resolve relative keys, including if the map of updated keys is empty. This PR updates the logic to skip the unnecessary `AssetsDefinition` copy if the list of updated keys is empty.
Perf testing on a large asset graph that took ~40s to load before this PR, 28s after.

Optimize relative asset key resolution in AssetGraph construction

---

python_modules/dagster/dagster/_check/__init__.py
python_modules/dagster/dagster_tests/general_tests/check_tests/test_check.py

support AbstractSet in dagster_model

---

python_modules/dagster/dagster/_core/definitions/asset_layer.py

remove unused AssetLayer.asset_check_specs_for_node

---

python_modules/dagster/dagster/_core/definitions/asset_layer.py
python_modules/dagster/dagster/_core/definitions/job_definition.py
python_modules/dagster/dagster/_core/execution/context/data_version_cache.py
python_modules/dagster/dagster_tests/definitions_tests/test_external_assets.py

We can resolve deps using the underlying `AssetGraph`

remove AssetLayer.asset_deps

---

python_modules/dagster/dagster/_core/definitions/asset_layer.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/job_definition.py

We can just go straight through to the `AssetsDefinition`s.

remove AssetLayer.partition_mappings_by_asset_dep

---

python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py

Request from a user. It's available on `SensorEvaluationContext`, so no reason not to make it available here.

add `repository_def` to `RunStatusSensorContext`

---

docs/content/dagster-plus/insights.mdx

This PR adds a sentence to the Insights intro that was incorrectly removed in a previous commit.

[docs] - Add intro sentence back into Insights 

---

examples/with_airflow/with_airflow/airflow_simple_dag.py
examples/with_airflow/with_airflow/assets_repository.py
python_modules/libraries/dagster-airflow/dagster_airflow/dagster_asset_factory.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_dagster_job_factory/test_load_assets.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_dagster_job_factory/test_load_assets_airflow_2.py

in dagster-airflow, stop allowing multiple tasks per asset

---

python_modules/dagster/dagster/_core/definitions/asset_daemon_cursor.py

This is no longer accessed, and can be quite large.

[DA] Remove previous_evaluation_state from AssetDaemonCursor

---

python_modules/dagster/dagster/_core/definitions/asset_graph.py
python_modules/dagster/dagster/_core/definitions/asset_layer.py
python_modules/dagster/dagster/_core/definitions/job_definition.py
python_modules/dagster/dagster/_core/execution/context/compute.py
python_modules/dagster/dagster/_core/execution/context/output.py
python_modules/dagster/dagster/_core/execution/context/system.py
python_modules/dagster/dagster/_core/execution/plan/compute.py
python_modules/dagster/dagster/_core/execution/plan/execute_step.py
python_modules/dagster/dagster/_core/execution/plan/inputs.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/libraries/dagster-polars/dagster_polars/io_managers/delta.py

This is redundant with `AssetNode`

remove AssetOutputInfo

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/__fixtures__/AssetTables.fixtures.ts
js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/useAllAssets.test.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetsCatalogTable.types.ts
js_modules/dagster-ui/packages/ui-core/src/runs/fetchPaginatedBucketData.ts
js_modules/dagster-ui/packages/ui-core/src/search/__tests__/useIndexedDBCachedQuery.test.tsx
js_modules/dagster-ui/packages/ui-core/src/search/useIndexedDBCachedQuery.tsx

Paginate fetching asset data in batches of 100k
Existing jest tests

Paginate fetching all assets

---

docs/content/dagster-plus/deployment/agents/amazon-ecs/creating-ecs-agent-existing-vpc.mdx
docs/content/dagster-plus/deployment/agents/amazon-ecs/creating-ecs-agent-new-vpc.mdx

This PR fixes some formatting in the AWS agent guides.
eyes

[docs] - Fix formatting in AWS agent guides

---

docs/content/dagster-plus/managing-deployments/branch-deployments/change-tracking.mdx
docs/content/dagster-plus/managing-deployments/branch-deployments/using-branch-deployments.mdx

Spurred by [this support thread](https://dagsterlabs.slack.com/archives/C04P1BJH88M/p1718291730916549)
👀

[docs] Clarify how to set main/base deployment for branch deployments

---

js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext.tsx

Honestly not sure where the null is coming from but @alangenfeld noticed this error pointing to this line in datadog.
👀

Check that location entry is not null before attempting to access property.

---

python_modules/dagster/dagster/_core/definitions/asset_layer.py
python_modules/dagster/dagster/_core/definitions/job_definition.py

It does not appear to be used anywhere

remove AssetLayer.assets_defs_by_check_key

---

python_modules/dagster/dagster/_check/__init__.py
python_modules/dagster/dagster/_serdes/serdes.py
python_modules/dagster/dagster_tests/general_tests/test_serdes.py

The initial strategy for resolving `ForwardRef`s was to capture the namespaces from the scopes of
1. at definition time
2. at first callsite time
One place this approach breaks down is if serdes is that first callsite. In that scenario the callsite scope does not directly have the string name -> type mapping.
It does however have it indirectly via the whitelist map which is what this solution takes advantage of.
Here we add a "contextual" namespace to the `EvalContext` that can be set to suppy another source to fold in to the merged namespace that we use for ForwardRef resolution and `exec`. 
added test case that previously failed

[dagster_model] add contextual namespace for serdes resolution

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_partition_sets.py
python_modules/dagster-graphql/dagster_graphql/schema/partition_sets.py

`PartitionsStatusQuery` has two sibling resolvers that both need partition name so we end up calculating it twice, this makes it so we dont do that.

[graphql] memoize fetching partition_names for a PartitionSet

---

examples/experimental/dagster-blueprints/dagster_blueprints/__init__.py

export YamlBlueprintsLoader at the top level

---

examples/experimental/dagster-blueprints/dagster_blueprints/load_from_yaml.py
examples/experimental/dagster-blueprints/dagster_blueprints_tests/test_load_defs_from_yaml.py

add resources arg to YamlBlueprintsLoader.load_defs

---

examples/experimental/dagster-blueprints/examples/builtin-blueprints/builtin_blueprints/__init__.py
examples/experimental/dagster-blueprints/examples/builtin-blueprints/builtin_blueprints/definitions.py
examples/experimental/dagster-blueprints/examples/builtin-blueprints/builtin_blueprints/pipelines/customer_stats.py
examples/experimental/dagster-blueprints/examples/builtin-blueprints/builtin_blueprints/pipelines/process_customers.yaml
examples/experimental/dagster-blueprints/examples/builtin-blueprints/pyproject.toml
examples/experimental/dagster-blueprints/examples/builtin-blueprints/setup.cfg
examples/experimental/dagster-blueprints/examples/builtin-blueprints/setup.py
examples/experimental/dagster-blueprints/setup.py

add blueprints example

---

python_modules/dagster/dagster/_core/definitions/asset_layer.py
python_modules/dagster/dagster/_core/definitions/run_config.py

remove AssetLayer.assets_defs

---

js_modules/dagster-ui/packages/ui-core/src/instance/useDaemonStatus.tsx

Disable `useRefreshAtInterval` if `skip = true` 
locally with app-proxy

Disable `useRefreshAtInterval` if `skip = true` in `useDaemonStatus`

---

js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillLogsTab.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/backfill/__tests__/BackfillLogsTab.test.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/backfill/types/BackfillLogsTab.types.ts
js_modules/dagster-ui/packages/ui-core/src/live-data-provider/LiveDataRefreshButton.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/useCursorAccumulatedQuery.tsx

Follow-up from PR feedback in #22409
Expanded the existing test case to verify the "Refreshing..." label disappears, and also tested it manually in the new backfill logs UI

[ui] Switch useCursorAccumulatedQuery to a less hook-specific solution

---

python_modules/dagster/dagster/_seven/__init__.py
python_modules/dagster/dagster_tests/general_tests/seven_tests/test_seven.py

Happened to look at this file and noticed code likely to be dead.
BK

Eliminate dead code in sevev

---

docs/dagster-university/pages/dagster-essentials/lesson-4/coding-practice-trips-by-week-asset.md

[docs][daggy-u] fix typo lesson 4 part 6

---

python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_impls.py

Summary:
Since we are starting with a fixed list of run IDs, we can fetch those runs in memory and then apply the tag filter in memory, rather than asking the query planner to do a large and complex join to do that filtering for us.
Test Plan: BK

Do run tag filtering in memory in AutoMaterializeAssetPartitionsFilter

---

js_modules/dagster-ui/packages/ui-core/src/runs/RunsFilterInput.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/__tests__/RunFilterInput.test.tsx

Similar to https://github.com/dagster-io/dagster/pull/19633,

[Runs filtering] Allow free form typing partition 

---

python_modules/dagster/dagster/_core/definitions/dependency.py
python_modules/dagster/dagster_tests/core_tests/definitions_tests/test_dependency.py

This makes debugging a little easier

pretty __str__ for NodeInputHandle and NodeOutputHandle

---

js_modules/dagster-ui/packages/ui-core/src/resources/WorkspaceResourcesRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceAssetsRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceGraphsRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceHeader.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceJobsRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceSchedulesRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceSensorsRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceTabs.tsx

bumped in to this in another refactor
bk

[ui] remove unused WorkspaceTabs queryData

---

docs/content/integrations/dbt/reference.mdx

in dbt reference, "column-level lineage" -> "column-level metadata"

---

python_modules/dagster/dagster/_seven/__init__.py
python_modules/dagster/dagster_tests/storage_tests/test_fs_io_manager.py

Skips failing test on python 3.12

Skip failing test on 3.12

---

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/test_version.py

- add `test_version.py` to be aligned with other integrations
- bk

[dagster-embedded-elt] add test_version.py

---

python_modules/libraries/dagster-sdf/dagster_sdf/__init__.py

pytest python_modules/automation/automation_tests/test_repo.py

[dagster-sdf] register library

---

python_modules/dagster/dagster/_core/definitions/asset_job.py
python_modules/dagster/dagster/_core/definitions/asset_layer.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/dependency.py
python_modules/dagster/dagster/_core/definitions/graph_definition.py
python_modules/dagster/dagster/_core/definitions/job_definition.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py

make NodeOutputHandle and NodeInputHandle dagster_models

---

CHANGES.md

changelog 1.7.11

---

js_modules/dagster-ui/packages/ui-core/src/pipelines/PipelineExplorerRoot.tsx

when we load by snapshotId it causes us to not render execution buttons in some cases 
reverts the part of https://github.com/dagster-io/dagster/pull/22696 that adds the argument to allow snapshot id loads to prevent this behavior 
verified problematic state no longer occurs by navigating to an asset job and ensuring the materialize button appears

partial revert [PipelineRootExplorer] load by snapshotId when available from WorkspaceContext (take 2) #22696

---

examples/experimental/dagster-blueprints/examples/builtin-blueprints/README.md
examples/experimental/dagster-blueprints/examples/custom-blueprints/README.md

add instructions for configuring vscode to blueprint example readmes

---

python_modules/dagster/dagster/_core/definitions/source_asset.py
python_modules/dagster/dagster_tests/definitions_tests/test_observe_result.py

Makes tests inside test_observe_result.py use the `@observable_source_asset` decorator instead of a bespoke decorator defined in that test file.
Making this change revealed that the `@observable_source_asset`decorator ignored tags on the `ObserveResult`, so this fixes that.

test_observe_result->public APIs and fix ObserveResult tags

---

CHANGES.md

1.7.12 changelog

---

js_modules/dagster-ui/packages/ui-core/src/app/AppProvider.tsx

Retry graphql requests that receive status code 502,503,504
Forced a 503 error and saw that we retried the query a second time.

Add RetryLink to retry on 502/503/504 errors

---

python_modules/dagster-graphql/dagster_graphql/schema/backfill.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_backfill.py

I'm not sure if this should be `rootTargetedPartitionsOrError` with an explanation about why they can't be computed? But in the short-term, detecting the case where the partitions can no longer be computed due to being un-resolvable anymore seems better than raising an uncaught exception
New test case that was failing before

Don't raise a 500 if you try to load rootTargetedPartitions on an asset backfill with assets that no longer exist

---

docs/dagster-university/pages/dagster-essentials/lesson-6/coding-practice-refactoring-assets.md

- Fixes imports when refactoring to use resources
Closes #22765

[daggy-u] fix imports when refactoring to use resource (closes #22765)

---

python_modules/dagster/dagster/_config/errors.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/serialized_objects.py
python_modules/dagster/dagster/_core/definitions/dependency.py
python_modules/dagster/dagster/_model/__init__.py
python_modules/dagster/dagster/_record/__init__.py
python_modules/dagster/dagster/_serdes/serdes.py
python_modules/dagster/dagster_tests/general_tests/test_serdes.py
python_modules/dagster/dagster_tests/model_tests/test_dagster_model.py
python_modules/libraries/dagster-dbt/dagster_dbt/dbt_project.py

rename `@dagster_model` to `@record` to reflect its simpler nature as a value type 
bk

@dagster_model -> @record 

---

python_modules/dagster/dagster/_core/remote_representation/external.py

rename pr missed callsite added after latest rebase
bk

[record] fix callsite

---

python_modules/dagster/dagster/_core/storage/event_log/polling_event_watcher.py

Summary:
In theory this should not matter since it only kicks in once we are tailing for new events, but we've observed large heap sizes here and it can't hurt to add a limit.
Test Plan: BK, view a run with streaming events and observe new events still streaming in

Add a batch size to the polling event watcher new events run records fetch

---

python_modules/dagster-graphql/dagster_graphql/implementation/execution/backfill.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/serialized_objects.py
python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
python_modules/dagster/dagster/_core/storage/event_log/migration.py
python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py
python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py
python_modules/dagster/dagster/_core/storage/schedules/sql_schedule_storage.py
python_modules/dagster/dagster/_time/__init__.py
python_modules/dagster/dagster/_utils/__init__.py
python_modules/libraries/dagster-mysql/dagster_mysql/run_storage/run_storage.py
python_modules/libraries/dagster-postgres/dagster_postgres/run_storage/run_storage.py

Summary:
Consolidating all the datetime utils into one place.

Combine dagster._utils.utc_datetime_from_timestamp with dagster._time.datetime_from_timestamp and move utc_datetime_from_naive into dagster._time

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_schedules.py
python_modules/dagster-graphql/dagster_graphql/schema/instigation.py
python_modules/dagster-graphql/dagster_graphql/schema/schedules/__init__.py
python_modules/dagster-graphql/dagster_graphql/schema/sensors.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_scheduler.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py
python_modules/dagster/dagster/_core/remote_representation/external.py
python_modules/dagster/dagster/_core/storage/dagster_run.py

align ids between the instigator and its state
bk

[graphql] change InstigationState over to CompoundID

---

js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetNodeDefinition.types.ts
js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetNodeInstigatorTag.types.ts
js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetView.types.ts
js_modules/dagster-ui/packages/ui-core/src/nav/types/JobMetadata.types.ts
js_modules/dagster-ui/packages/ui-core/src/schedules/ScheduleMutations.tsx
js_modules/dagster-ui/packages/ui-core/src/schedules/ScheduleStateChangeDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/schedules/ScheduleSwitch.tsx
js_modules/dagster-ui/packages/ui-core/src/schedules/__fixtures__/ScheduleState.fixtures.tsx
js_modules/dagster-ui/packages/ui-core/src/schedules/types/ScheduleMutations.types.ts
js_modules/dagster-ui/packages/ui-core/src/sensors/SensorFragment.tsx
js_modules/dagster-ui/packages/ui-core/src/sensors/SensorMutations.tsx
js_modules/dagster-ui/packages/ui-core/src/sensors/SensorStateChangeDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/sensors/SensorSwitch.tsx
js_modules/dagster-ui/packages/ui-core/src/sensors/__fixtures__/SensorState.fixtures.tsx
js_modules/dagster-ui/packages/ui-core/src/sensors/types/SensorFragment.types.ts
js_modules/dagster-ui/packages/ui-core/src/sensors/types/SensorMutations.types.ts
js_modules/dagster-ui/packages/ui-core/src/sensors/types/SensorRoot.types.ts
js_modules/dagster-ui/packages/ui-core/src/sensors/types/SensorSwitch.types.ts
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceQueries.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/types/VirtualizedJobRow.types.ts
js_modules/dagster-ui/packages/ui-core/src/workspace/types/VirtualizedSensorRow.types.ts
js_modules/dagster-ui/packages/ui-core/src/workspace/types/WorkspaceQueries.types.ts
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_scheduler.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py

move from the two argument mutation to the singular compoun id argument, simplifying things 
bk

[ui] switch sensor/schedule mutations to id argument

---

python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/dbt_packages/test_columns_metadata.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_metadata/profiles.yml

Introduce nightly BigQuery test to ensure column lineage deferred fetches work as expected
https://buildkite.com/dagster/full-moon-with-face-dagster-nightly/builds/67

[dagster-dbt] Test column lineage against bigquery nightly

---

js_modules/dagster-ui/packages/ui-core/src/partitions/PartitionGraph.tsx
js_modules/dagster-ui/packages/ui-core/src/schedules/ScheduleSwitch.tsx
js_modules/dagster-ui/packages/ui-core/src/sensors/SensorSwitch.tsx

Clean up a couple of lingering lint warnings. Also tidy up a couple of ts-expect-error directives.

[ui] Clean up lint warnings, eliminate some ts errors

---

python_modules/dagster/dagster/_record/__init__.py
python_modules/dagster/dagster_tests/model_tests/test_dagster_model.py

support pickling for records since we need it in some places 
added test

[record] pickle-ability

---

integration_tests/test_suites/k8s-test-suite/conftest.py
python_modules/dagster/dagster/_config/pythonic_config/config.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/input.py
python_modules/dagster/dagster/_core/definitions/partition_mapping.py
python_modules/dagster/dagster/_core/definitions/resource_definition.py
python_modules/dagster/dagster/_core/events/__init__.py
python_modules/dagster/dagster/_core/storage/db_io_manager.py
python_modules/dagster/dagster/_model/pydantic_compat_layer.py
python_modules/dagster/setup.py
python_modules/libraries/dagster-docker/dagster_docker/ops/docker_container_op.py
python_modules/libraries/dagster-docker/dagster_docker/pipes.py
python_modules/libraries/dagster-github/dagster_github_tests/test_resources.py
python_modules/libraries/dagster-polars/dagster_polars_tests/conftest.py

Internal companion PR: https://github.com/dagster-io/internal/pull/10454
Update pyright from 1.1.356 -> 1.1.370. Add/remove a few type-ignores and fix a few minor newly detected type errors.

[pyright] 1.1.356 -> 1.1.370

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/resources.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_top_level_resources.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_top_level_resources.py

stacked for cross push safety, remove the fields no longer in use 
bk

[graphql] remove expensive jobsOpsUsing fields

---

docs/content/concepts/assets/asset-jobs.mdx

fix typo in asset-jobs.mdx

---

docs/content/concepts/assets/asset-jobs.mdx
docs/dagster-university/pages/dagster-essentials/extra-credit/definition-metadata-asset-descriptions.md

This PR fixes minor typos in docs.

Fix minor typos in docs

---

docs/content/guides/dagster/testing-assets.mdx

This PR adds info about asset checks to the **Testing assets** guide.
👀

[docs] - Add asset checks to testing assets guide (DOC-264)

---

python_modules/dagster/dagster/_core/definitions/metadata/__init__.py
python_modules/dagster/dagster/_core/definitions/metadata/source_code.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_defs_source_metadata.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_code_references.py

[code refs] rename link_to_git to link_code_references_to_git

---

python_modules/dagster/dagster/__init__.py
python_modules/dagster/dagster/_core/definitions/metadata/__init__.py

Adds top-level exports for various code reference related classes and functions.

export code reference classes at dagster package

---

python_modules/dagster/dagster/_core/execution/plan/inputs.py
python_modules/dagster/dagster/_core/execution/plan/plan.py
python_modules/dagster/dagster_tests/execution_tests/misc_execution_tests/test_input_values_from_intermediates.py

migrate some more things to `@record`
bk

[record] plan/inputs.py

---

docs/sphinx/sections/api/apidocs/libraries/dagster-looker.rst

fix(looker): render `build_looker_asset_specs` in docs

---

python_modules/dagster/dagster/_core/definitions/run_request.py

converts `RunRequest` to be a `@record`

make run request an @record

---

azure-pipelines.yml

Add launcher tests to windows azure checks

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/rule_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/code_version_changed_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/slice_conditions.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/any_downstream_conditions_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/newly_true_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/since_operator.py

DagsterModel -> `@record`
existing tests

[AutomationCondition] move to @record

---

python_modules/dagster/dagster/_core/instance/__init__.py

fix docstring return type in get_latest_materialization_event

---

python_modules/dagster/dagster/_core/executor/multiprocess.py
python_modules/dagster/dagster/_grpc/impl.py
python_modules/dagster/dagster/_utils/__init__.py

Historically we just let the daemon thread exit while waiting on the `Event`, but recently discovered that if we try to set the `Event` after the child process exited then we could hang since the `wait` call did not clean up.
Set the event and a new done event to prevent this bad state.
tested against https://github.com/dagster-io/dagster/pull/22839 which was consistently hanging without this applied

shutdown interrupt thread on exit

---

python_modules/libraries/dagster-celery/dagster_celery/launcher.py

Summary:
As title
Test Plan: BK

Fix typing error in CeleryRunLauncher on 3.8

---

examples/experimental/dagster-blueprints/dagster_blueprints/blueprint_assets_definition.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/utils.py
python_modules/dagster/dagster/_core/definitions/asset_graph_computation.py
python_modules/dagster/dagster/_core/definitions/asset_layer.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/execution/plan/execute_step.py
python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_last_update_freshness.py
python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_time_partition_freshness.py

move AssetGraphComputation to its own module

---

docs/content/dagster-plus/deployment/agents/kubernetes/configuring-running-kubernetes-agent.mdx

Summary:
The previous instructions involved setting a flag that was easy to forget if you later make more changes. Have the tutorial create a values.yaml file from the beginning, so you have somethign to add to for future deploys.
Test Plan: View page, carry out these steps in a new cluster

Reference a values.yaml file in the kubernetes startup guide

---

js_modules/dagster-ui/packages/ui-core/src/instance/flattenCodeLocationRows.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/useCodeLocationPageFilters.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/CodeLocationRowSet.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/RepositoryLocationsList.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedCodeLocationRow.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceQueries.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/types/WorkspaceQueries.types.ts

Revert "[ui] update code locations table to source from status and entries (#22799)"

---

python_modules/dagster/dagster/_record/__init__.py
python_modules/dagster/dagster_tests/general_tests/test_record.py

The updated test failed before this PR, now succeeds.

[record] Fix default inheritence

---

python_modules/dagster-test/dagster_test/test_project/test_jobs/repo.py
python_modules/dagster/dagster/_core/test_utils.py
python_modules/dagster/dagster_tests/launcher_tests/test_default_run_launcher.py

Summary:
Wait for the other op to start
Test Plan: BK

Attempt to de-flake test_job_that_fails_run_worker

---

python_modules/dagster/dagster/_check/builder.py
python_modules/dagster/dagster_tests/general_tests/test_record.py

[record] fix ImportFrom on 3.8

---

python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py

Just makes the code a little less verbose.

in test_assets, use materialize instead of constructing job

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_instigators.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_instigation.py

If we are passed both id and selector, fallback to the selector if theres nothing in the DB for the ID

[graphql] InstigationState lookup by selector fallback

---

js_modules/dagster-ui/packages/ui-core/src/app/Permissions.tsx

pull can edit workspace perms for location-specific perms

---

js_modules/dagster-ui/packages/ui-core/src/runs/LogsScrollingTable.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/Run.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/StepLogsDialog.tsx

[ui] Rename LogsScrollingTableNew to LogsScrollingTable

---

js_modules/dagster-ui/packages/ui-core/src/automation/AutomationRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/automation/AutomationsTable.tsx
js_modules/dagster-ui/packages/ui-core/src/automation/MergedAutomationRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/automation/VirtualizedAutomationRow.tsx
js_modules/dagster-ui/packages/ui-core/src/automation/VirtualizedAutomationScheduleRow.tsx
js_modules/dagster-ui/packages/ui-core/src/automation/VirtualizedAutomationSensorRow.tsx
js_modules/dagster-ui/packages/ui-core/src/sensors/makeSensorKey.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedScheduleRow.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedSensorRow.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedWorkspaceTable.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/types/VirtualizedScheduleRow.types.ts
js_modules/dagster-ui/packages/ui-core/src/workspace/types/VirtualizedSensorRow.types.ts

First step in merging automations into a single table. Combine all sensors and schedules into a bucketed virtualized table. Still quite a bit more to do here, including bulk actions, moving text into tags, and filtering.
View `/automations/merged`, verify correct bucketing, ordering, rendering, scroll loading.

[ui] Merged Automations table

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/asset_condition_evaluations.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_condition_evaluations.py

Allows us to switch the UI based on if we're looking at a legacy evaluation or not.

[DA] Add isLegacy field

---

python_modules/dagster/dagster/_utils/__init__.py

Resolves https://github.com/dagster-io/dagster/issues/21357.
existing bk

refactor: use `pathlib` for `file_relative_path`

---

python_modules/dagster/dagster/_core/storage/dagster_run.py

fix comment on DagsterRunStatus.NOT_STARTED

---

docs/content/concepts/assets/asset-checks/checking-for-data-freshness.mdx

This PR moves the example use case from the **How it works** section to the intro of the **Checking data freshness** guide.
👀

[docs] - Move use cases to intro in freshness checks guide (DOC-276)

---

docs/content/concepts/metadata-tags/tags.mdx

document storage_kind

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_decorators.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_on_cron_condition.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_result_value_hash.py

Adds some labels to simplify parsing of these policies in the UI, changes `cron` to `on_cron`.

[DA] Update static constructors

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_condition_evaluations.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_auto_materialize_asset_evaluations.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py
python_modules/dagster/dagster_tests/definitions_tests/asset_policy_sensors_tests/test_default_auto_materialize_sensors.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_backfills_requested.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_asset_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_asset_daemon_failure_recovery.py

[DA] Default auto_materialize_use_sensors to True

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/dbt_packages/test_columns_metadata.py

Keeps a cross-thread cache which stores the result of fetching relation metadata from the warehouse. This means when building column lineage we only fetch each table ~once (though simultaneous fetches of the same relation can still happen).
Sanity check on existing unit tests that number of fetches is lower than total number of calls (~ halved).

[dagster-dbt] Cache relation metadata fetches when building column metadata

---

js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext.tsx

fixes https://linear.app/dagster-labs/issue/FE-468/[bug]-deleting-a-code-location-in-dagster-causes-application-error-a.

Guard against undefined entry in WorkspaceContext

---

python_modules/dagster/dagster/_core/definitions/graph_definition.py

This confused me a couple times when I broke a test.

improve error msg in _validate_out_mappings

---

python_modules/dagster/dagster/_core/definitions/asset_job.py
python_modules/dagster/dagster/_core/definitions/job_definition.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_unresolved_asset_job.py

Get rid of a couple `# noqa`'s

op_retry_policy on JobDefinition

---

js_modules/dagster-ui/packages/ui-core/src/instance/flattenCodeLocationRows.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/useCodeLocationPageFilters.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/CodeLocationRowSet.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/RepositoryLocationsList.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedCodeLocationRow.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceQueries.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/types/WorkspaceQueries.types.ts

This should be safe to land again after https://github.com/dagster-io/internal/pull/10524

Revert "Revert "[ui] update code locations table to source from status and entries (#22799)" (#22947)"

---

python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py

Resolves https://github.com/dagster-io/internal/pull/10631#discussion_r1684684880.
internal

refactor(catalog): move selection types to graphql asset graph

---

python_modules/dagster/dagster/_core/definitions/job_definition.py
python_modules/dagster/dagster/_core/selector/subset_selector.py

use record for AssetSelectionData and OpSelectionData

---

python_modules/dagster/dagster/_serdes/serdes.py

once the downstack PR removes the only callsite we can remove this flag
bk

[serdes] remove is_pickleable

---

pyright/master/requirements-pinned.txt
pyright/master/requirements.txt

chore(sdf): add `dagster-sdf` to `pyright`

---

python_modules/dagster-test/dagster_test/fixtures/docker_compose.py

This hooks into docker-compose's functionality to optionally disable building images, even if specified by the policy
Existing integration tests heavily depend on this functionality, so if those pass then we can be confident that the new args are correct

PLA-509 add --no-build option to docker-compose up

---

python_modules/dagster/dagster/_core/execution/asset_backfill.py

Summary:
From the comment it looks like this was supposed to be CANCELED? There is already a CANCELING check above, so this code would never run.
Test Plan: BK

Fix duplicate backfill CANCELING status check

---

python_modules/dagster/dagster/_core/execution/asset_backfill.py

Summary:
This is a no-op but I found it easier to parse after consolidating the duplicated logic between the two paths.
Test Plan: BK

Simplify duplicated logic for computing failed asset parittions in asset backfill daemon

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeOverview.tsx

Hide compute details for source assets

---

examples/experimental/dagster-blueprints/dagster_blueprints/blueprint.py
examples/experimental/dagster-blueprints/dagster_blueprints/blueprint_assets_definition.py
examples/experimental/dagster-blueprints/dagster_blueprints/load_from_yaml.py
examples/experimental/dagster-blueprints/dagster_blueprints_tests/test_cli/sample_blueprint_project/blueprint_project/__init__.py
examples/experimental/dagster-blueprints/dagster_blueprints_tests/test_databricks_blueprint.py
examples/experimental/dagster-blueprints/dagster_blueprints_tests/test_load_defs_from_yaml.py
examples/experimental/dagster-blueprints/dagster_blueprints_tests/test_shell_command_blueprint.py
examples/experimental/dagster-blueprints/examples/custom-blueprints/custom_blueprints/definitions.py

Now that https://github.com/dagster-io/dagster/pull/22909 is merged, we can do this.

eliminate BlueprintDefinitions; use Definitions

---

python_modules/dagster/dagster/_core/execution/context/invocation.py

[1.8] remove _assets_def argument on build_op_context

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_cli_invocation.py
python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_event_iterator.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/dbt_packages/test_columns_metadata.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_postprocessing.py

refactor(dbt): separate out `DbtEventIterator` to `dbt_event_iterator.py`

---

python_modules/dagster/dagster/_core/definitions/asset_graph_subset.py
python_modules/dagster/dagster/_core/execution/asset_backfill.py

Does a pass over the backfill daemon logs to make them more user readable. still room for improvement but i think this makes the logs a good bit more approachable 
Logs after these changes 
https://github.com/user-attachments/assets/32d259d6-1f5a-45bf-969e-8d1a38f2d986

make backfill logs more user friendly

---

CHANGES.md

[changelog] 1.7.15

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetPageHeader.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/PolicyEvaluationTable.tsx

Noticed a couple of lint warnings unrelated to my working branch. Fix them.
Run lint.

[ui] Tidy up lint warnings

---

docs/next/.versioned_content/_versions_with_static_links.json

complete the last step of the release

Automation: versioned docs for 1.7.15

---

python_modules/dagster/dagster/_core/definitions/materialize.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_materialize.py

`SourceAsset`s can currently be passed to the `assets` argument of `materialize`. This allows metadata about an upstream asset to be made available during the execution of an asset downstream of it – e.g. to grab the upstream `PartitionsDefinition` to resolve the upstream partitions that the execution depends on.
This PR enables the same with `AssetSpec`s, given the impending deprecation of `SourceAsset`.
This PR depends on `Definitions` accepting `AssetSpec`s (https://github.com/dagster-io/dagster/pull/22961).

[1.8][external assets] accept `AssetSpec`s in `materialize`

---

python_modules/libraries/dagster-polars/setup.py

Putting a pin up while we look into breaking changes in our build.

Pin around polars 1.3.0

---

python_modules/libraries/dagster-sdf/tox.ini

As the title. Until some `pip` or `uv` stuff gets sorted out.
bk

chore(sdf): temporarily remove `uv`

---

docs/content/concepts/automation.mdx

Closes https://github.com/dagster-io/dagster/issues/23309

[docs] fix typo in automation docs

---

python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/storage/event_log/base.py
python_modules/dagster/dagster/_core/storage/event_log/in_memory.py
python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py
python_modules/dagster/dagster/_core/storage/event_log/sqlite/sqlite_event_log.py
python_modules/dagster/dagster/_core/storage/legacy_storage.py
python_modules/dagster/dagster_tests/storage_tests/test_event_log.py
python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
python_modules/libraries/dagster-postgres/dagster_postgres/event_log/event_log.py

Bubble up storage ID returned when inserting into the event log
New event storage suite test

Return storage ID when adding to the event log

---

docs/content/concepts/webserver/ui.mdx

- No longer experimental
- No longer needs a feature flag
- Cloud -> Dagster+
- Add all available filters
N/A

docs(catalog): update information about Dagster Catalog

---

python_modules/dagster/dagster/_core/definitions/run_request.py

`with_resolved_tags_and_config` accepts an `UnresolvedAssetJobDefinition`, but none of the calling paths provide it one

[single-implicit-asset-job] remove unused input type from `RunRequest` method

---

python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/test_launching.py

Summary:
Resolves https://github.com/dagster-io/dagster/issues/14939.

Add a dagster/job_name tag to ECS run launcher tasks

---

python_modules/dagster-test/dagster_test/toys/external_assets.py

remove use of external_assets_from_specs from toys

---

python_modules/automation/tox.ini
python_modules/dagster/setup.py

- Failing buildkite on master
- pyright and automation are working successfully

fix: buildkite failures on automation and pyright

---

js_modules/dagster-ui/packages/ui-core/src/runs/RunTimeline.tsx

Resolves https://github.com/dagster-io/dagster/issues/23342.
There is currently a bug in the run timeline when rendering time interval markers for users in timezones that do not use hour offsets (e.g. `Asia/Kolkata`, `Australia/Adelaide`, `America/St_Johns`).
This is caused by how we calculate the initial interval marker, which is based on a mod operation on the start time. If the user has a half-hour offset from UTC, and we're drawing markers at every hour, we end up drawing the time marker at the user's half-hour mark. We then label the marker with the hour digits only -- for instance, we render a "10:30" marker but label it as "10", thus making it appear that the timeline is shifted incorrectly.
To fix this, use the same approach for marker generation on time markers as we do for day …

[ui] Repair run timeline markers for timezones with non-hour offsets

---

docs/content/concepts/assets/asset-checks.mdx

[docs] document built-in asset checks

---

examples/docs_snippets/docs_snippets_tests/guides_tests/dagster_pipes_tests/test_databricks.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_data_versions.py
python_modules/dagster/dagster/_cli/asset.py
python_modules/dagster/dagster/_core/definitions/asset_job.py
python_modules/dagster/dagster/_core/definitions/definitions_class.py
python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
python_modules/dagster/dagster/_core/definitions/repository_definition/repository_data_builder.py
python_modules/dagster/dagster/_core/definitions/repository_definition/repository_definition.py
python_modules/dagster/dagster/_core/definitions/sensor_definition.py
python_modules/dagster/dagster/_core/execution/submit_asset_runs.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_partitioned_assets.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_source_asset_observation_job.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/base_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenario_state.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/updated_scenarios/asset_daemon_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py
python_modules/dagster/dagster_tests/definitions_tests/test_external_assets.py
python_modules/dagster/dagster_tests/storage_tests/branching_io_manager_tests/utils.py
python_modules/dagster/dagster_tests/storage_tests/test_fs_io_manager.py
python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

epilogue to the single-implicit-asset-job stack

[single-implicit-asset-job] remove `get_implicit_job_def_for_assets`

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_runs.py

Summary:
Allows efficient pagination on this field.
Test Plan: BK

Add 'limit' argument to eventConnection on run

---

python_modules/libraries/dagster-sdf/dagster_sdf/asset_decorator.py
python_modules/libraries/dagster-sdf/dagster_sdf/resource.py
python_modules/libraries/dagster-sdf/dagster_sdf/sdf_workspace.py

feat(sdf): mark `dagster-sdf` API as experimental

---

python_modules/dagster/dagster/_check/builder.py
python_modules/dagster/dagster_tests/general_tests/check_tests/test_check.py

support Literal annotations on record fields

---

python_modules/dagster/dagster/_core/remote_representation/external_data.py

make ExternalAssetNode a record

---

examples/experimental/dagster-airlift/dagster_airlift/core/def_factory.py
examples/experimental/dagster-airlift/examples/peering-with-dbt/peering_with_dbt/dagster_defs/definitions.py

Add a simple helper defs_from_factories to make defs cosntruction more ergonomic
BK

Add defs_from_factories helper to clean up code

---

js_modules/dagster-ui/yarn.lock

Resolve three open dependabot alerts on `elliptic`.
`yarn why elliptic`

[ui] Upgrade elliptic for dependabot

---

python_modules/dagster-webserver/dagster_webserver/webserver.py

Fix internal test related to the GraphiQL change. The relevant configuration is in OSS, but the test runs internally.
Point internal branch at this branch, verify that the internal build passes.

[ui] Fix internal static asset test for GraphiQL

---

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/dlt/resource.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/dlt_tests/test_asset_decorator.py

dlt's `LoadInfo` includes column information for loaded tables - this PR extracts them into Dagster column schema.
Unit test update.

[dagster-embedded-elt] generate column metadata for dlt output

---

examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_peering.py

mark flaky airlift test

---

python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_impls.py
python_modules/dagster/dagster/_core/definitions/freshness_policy.py

[DA] Update breaking versions for freshenss-based-scheduling

---

docs/dagster-university/pages/dagster-dbt/lesson-4/2-speeding-up-the-development-cycle.md

This PR adds a brief explanation of `prepare_if_dev()` to Lessson 4 of the dbt course.
👀 , docs

[daggy-u] - Add prepare_if_dev() explanation to Lesson 4

---

python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/dependency.py
python_modules/dagster/dagster/_core/definitions/graph_definition.py
python_modules/dagster/dagster/_core/definitions/hook_definition.py
python_modules/dagster/dagster/_core/definitions/hook_invocation.py
python_modules/dagster/dagster/_core/definitions/job_definition.py
python_modules/dagster/dagster/_core/definitions/op_definition.py
python_modules/dagster/dagster/_core/definitions/resource_definition.py
python_modules/dagster/dagster/_core/definitions/resource_invocation.py
python_modules/dagster/dagster/_core/definitions/resource_requirement.py
python_modules/dagster/dagster/_core/definitions/source_asset.py
python_modules/dagster/dagster/_core/execution/context/invocation.py
python_modules/dagster/dagster/_core/types/config_schema.py
python_modules/dagster/dagster/_core/types/dagster_type.py
python_modules/dagster/dagster_tests/general_tests/seven_tests/test_seven.py

* use `@record`
* remove interface that forced a bunch of weird casting and update callsites accordingly

ResourceRequirements clean-up
