dagster-io/dagster

docs/content/integrations/bigquery/reference.mdx
docs/content/integrations/bigquery/using-bigquery-with-dagster.mdx
docs/content/integrations/deltalake/reference.mdx
docs/content/integrations/deltalake/using-deltalake-with-dagster.mdx
docs/content/integrations/duckdb/reference.mdx
docs/content/integrations/duckdb/using-duckdb-with-dagster.mdx
docs/content/integrations/snowflake/reference.mdx
docs/content/integrations/snowflake/using-snowflake-with-dagster-io-managers.mdx
docs/content/integrations/snowflake/using-snowflake-with-dagster.mdx
examples/docs_snippets/docs_snippets/integrations/bigquery/reference/dataset.py
examples/docs_snippets/docs_snippets/integrations/bigquery/tutorial/io_manager/full_example.py
examples/docs_snippets/docs_snippets/integrations/bigquery/tutorial/io_manager/source_asset.py
examples/docs_snippets/docs_snippets/integrations/bigquery/tutorial/resource/full_example.py
examples/docs_snippets/docs_snippets/integrations/bigquery/tutorial/resource/source_asset.py
examples/docs_snippets/docs_snippets/integrations/deltalake/full_example.py
examples/docs_snippets/docs_snippets/integrations/deltalake/schema.py
examples/docs_snippets/docs_snippets/integrations/deltalake/source_asset.py
examples/docs_snippets/docs_snippets/integrations/duckdb/reference/schema.py
examples/docs_snippets/docs_snippets/integrations/duckdb/tutorial/io_manager/full_example.py
examples/docs_snippets/docs_snippets/integrations/duckdb/tutorial/io_manager/source_asset.py
examples/docs_snippets/docs_snippets/integrations/duckdb/tutorial/resource/full_example.py
examples/docs_snippets/docs_snippets/integrations/snowflake/io_manager_tutorial/full_example.py
examples/docs_snippets/docs_snippets/integrations/snowflake/schema.py
examples/docs_snippets/docs_snippets/integrations/snowflake/source_asset.py

`SourceAsset` is a deprecated concept, but our docs on warehouse integrations still mention them. This PR switches mentions to `AssetSpec` and "external asset".

[deprecate-source-assets] storage integration docs

---

js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationDefinitionsMain.tsx
js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationOpsView.tsx
js_modules/dagster-ui/packages/ui-core/src/code-location/__fixtures__/CodeLocationPages.fixtures.ts
js_modules/dagster-ui/packages/ui-core/src/code-location/__stories__/CodeLocationDefinitionsRoot.stories.tsx
js_modules/dagster-ui/packages/ui-core/src/ops/OpsRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/ops/types/OpsRoot.types.ts

Insert the ops explorer into the new code locations page.
Storybook example.

[ui] Code location: Ops page

---

docs/content/guides/dagster/using-environment-variables-and-secrets.mdx

Follow up from https://github.com/dagster-io/dagster/issues/23355
👀

[docs] add example using EnvVar.get_value() method

---

python_modules/dagster/dagster/_core/execution/job_backfill.py

missed removing this message from https://github.com/dagster-io/dagster/pull/23613

[quick] remove debugging log message from job backfills

---

python_modules/dagster/dagster/_api/snapshot_partition.py
python_modules/dagster/dagster/_grpc/types.py
python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_partition.py

"Partition set"s are an eliminated concept that lives on like a ghost inside our host processes and gRPC APIs. This PR is the bottom of a stack that makes a dent at removing it.
When a job has a `PartitionsDefinition`, we also automatically generate a `PartitionSetSnap` whose name is f"{job_name}_partition_set". This is a relic from a past era when jobs could have multiple partition sets. This partition set name is then referenced from host processes when they need to get partition-related information for the job:
- The set of partitions
- The tags corresponding to a particular partition
- The config corresponding to a particular partition
This is problematic for two reasons:
- The redundant and vestigial "partition set" concept is threaded through a bunch of our host process code
- When …

[single-implicit-asset-job] add `selected_asset_keys` and `job_name` to grpc partition api params

---

.pre-commit-config.yaml
examples/with_great_expectations/with_great_expectations/great_expectations/notebooks/pandas/validation_playground.ipynb
examples/with_great_expectations/with_great_expectations/great_expectations/notebooks/spark/validation_playground.ipynb
examples/with_great_expectations/with_great_expectations/great_expectations/notebooks/sql/validation_playground.ipynb
pyproject.toml
python_modules/libraries/dagster-ge/dagster_ge/examples/great_expectations/notebooks/pandas/validation_playground.ipynb
python_modules/libraries/dagster-ge/dagster_ge/examples/great_expectations/notebooks/spark/validation_playground.ipynb
python_modules/libraries/dagster-ge/dagster_ge/examples/great_expectations/notebooks/sql/validation_playground.ipynb
python_modules/libraries/dagster-ge/dagster_ge_tests/great_expectations/notebooks/pandas/validation_playground.ipynb
python_modules/libraries/dagster-ge/dagster_ge_tests/great_expectations/notebooks/spark/validation_playground.ipynb
python_modules/libraries/dagster-ge/dagster_ge_tests/great_expectations/notebooks/sql/validation_playground.ipynb
scripts/templates_create_dagster_package/__init__.py.tmpl

This PR makes `pre-commit` use the same `ruff` settings & executable as the local environment (e.g. when run via `make ruff`). 
Should we add a `buildkite` job for `pre-commit`? Currently it's not being tested in CI.
Context: https://dagsterlabs.slack.com/archives/C03A0D72A6T/p1723065934987029
`pre-commit` can be enabled and doesn't produce any changes when run
---
P.S. I had to add a few ` = None` placeholders in some of the notebooks since previously these expressions lacked any assignment and were invalid (`ruff` was failing completely on these files)

[chore] unify local and pre-commit ruff configuration

---

js_modules/dagster-ui/packages/ui-core/src/hooks/__tests__/useQueryPersistedFilterState.test.tsx

Run prettier

---

python_modules/dagster-graphql/dagster_graphql/implementation/execution/backfill.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_partition_sets.py
python_modules/dagster-graphql/dagster_graphql/schema/partition_sets.py
python_modules/dagster/dagster/_api/snapshot_partition.py
python_modules/dagster/dagster/_cli/asset.py
python_modules/dagster/dagster/_cli/job.py
python_modules/dagster/dagster/_core/definitions/job_definition.py
python_modules/dagster/dagster/_core/definitions/run_request.py
python_modules/dagster/dagster/_core/remote_representation/code_location.py
python_modules/dagster/dagster/_core/remote_representation/external.py
python_modules/dagster/dagster/_core/workspace/context.py
python_modules/dagster/dagster/_grpc/impl.py
python_modules/dagster/dagster/_grpc/server.py
python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_partition.py
python_modules/dagster/dagster_tests/api_tests/utils.py
python_modules/dagster/dagster_tests/cli_tests/command_tests/test_materialize_command.py

This builds on top of https://github.com/dagster-io/dagster/pull/23527 to do two related things:
- On the host process side, refactors `CodeLocation` methods and call sites to use job names and selected asset keys instead of partition set names.
- On the user code process side, updates the implementations of grpc APIs that fetch partition information to pass selected asset keys to the `JobDefinition`.

[single-implicit-asset-job] methods on `CodeLocation` to get job partitions, partition tags, and partition config, with asset selection

---

examples/use_case_repository/use_case_repository/guides/sling_replicate_csv_files_to_snowflake.md
examples/use_case_repository/use_case_repository/guides/sling_replicate_csv_files_to_snowflake.py

- alternative to using `COPY INTO` for copying CSV to Snowflake
- leverage embedded ELT sling
- define resource connections
- create replication config (programmatically for easier inclusion in tutorial, opposed to yaml)
- verified end-to-end execution with use of local `.env`

[usecase] replicate csv to snowflake using embedded elt sling

---

docs/dagster-university/pages/dagster-dbt/lesson-7/5-preparing-for-a-successful-run.md

This PR corrects the name of the S3 bucket environment variable in Lesson 7 to `S3_BUCKET_PREFIX`.
Matches the [`constants.py` of the accompanying project](https://github.com/dagster-io/project-dagster-university/blob/module/dagster-and-dbt/dagster_university/assets/constants.py)

[daggy-u] [dbt] - Correct S3 env var key

---

python_modules/libraries/dagster-duckdb/dagster_duckdb/io_manager.py
python_modules/libraries/dagster-duckdb/dagster_duckdb/resource.py

- Resolves **https://github.com/dagster-io/dagster/issues/23761**
Only provide `custom_user_agent` when `duckdb.__version__` is greater than. `1.0.0`, as that is when this feature was included.
- `tox`

fix(duckdb) only specify custom_user_agent for duckdb > 1.0.0

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_partition_sets.py
python_modules/dagster-graphql/dagster_graphql/implementation/utils.py
python_modules/dagster-graphql/dagster_graphql/schema/auto_materialize_asset_evaluations.py
python_modules/dagster-graphql/dagster_graphql/schema/inputs.py
python_modules/dagster-graphql/dagster_graphql/schema/partition_keys.py
python_modules/dagster-graphql/dagster_graphql/schema/partition_sets.py
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_job_partitions.py

This enables the frontend to query for partition information with respect to an asset selection within a job. This enables a world where jobs can contain assets with different `PartitionsDefinition`s.
It's used by @bengotow 's `partition-set-to-job/graphql-ui` branch.
Sits atop https://github.com/dagster-io/dagster/pull/23491.

[single-implicit-asset-job] add `partitionKeysOrError` and `partition` to `GrapheneJob`

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphExplorerFilters.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/useAssetCatalogFiltering.oss.tsx

https://linear.app/dagster-labs/issue/FE-521/[bug]-filter-to-group-action-no-longer-works-in-the-lineage-ui
The AssetGraphExplorer had an optional `assetFilterState?: AssetFilterState` that needed to be passed for this filtering to work, and it's no longer passed anywhere the component is used.  I updated this to work the same way the clickable computeKind tags work.
I verified that the asset graph sidebar and asset graph collapsed + expanded nodes "Filter to group" options all still work

[ui] Fix “filter to group” action no longer working in the asset graph

---

js_modules/dagster-ui/packages/ui-core/src/app/ExecutionSessionStorage.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/LaunchAssetChoosePartitionsDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/LaunchAssetExecutionButton.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/RunningBackfillsNotice.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/__fixtures__/LaunchAssetChoosePartitionsDialog.fixtures.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/__fixtures__/LaunchAssetExecutionButton.fixtures.ts
js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/LaunchAssetChoosePartitionsDialog.test.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/LaunchAssetExecutionButton.test.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/types/LaunchAssetExecutionButton.types.ts
js_modules/dagster-ui/packages/ui-core/src/assets/types/RunningBackfillsNotice.types.ts
js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
js_modules/dagster-ui/packages/ui-core/src/launchpad/ConfigEditorConfigPicker.tsx
js_modules/dagster-ui/packages/ui-core/src/launchpad/ConfigFetch.tsx
js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadSession.tsx
js_modules/dagster-ui/packages/ui-core/src/launchpad/types/ConfigEditorConfigPicker.types.ts
js_modules/dagster-ui/packages/ui-core/src/launchpad/types/ConfigFetch.types.ts
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_partition_sets.py
python_modules/dagster-graphql/dagster_graphql/implementation/utils.py
python_modules/dagster-graphql/dagster_graphql/schema/auto_materialize_asset_evaluations.py
python_modules/dagster-graphql/dagster_graphql/schema/inputs.py
python_modules/dagster-graphql/dagster_graphql/schema/partition_keys.py
python_modules/dagster-graphql/dagster_graphql/schema/partition_sets.py
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_job_partitions.py

Related: https://linear.app/dagster-labs/issue/FE-509/update-the-materialize-button-to-pull-jobpartitiondefinition-using-the
This PR stacks on top of #23494:
- On the backend, there is now just a single hidden asset job which contains all assets.
- This asset job has no partition_set, but given a set of asset keys, you can still retrieve the list of available partitions and config + tags for a specific partition using new resolvers on the job. (Added in @sryza's PR)
This requires some changes to expectations made on the front-end:
- We no longer check both the partition definitions AND the presence of a partition set on the job the assets have in common. If you select partitioned assets you will get the partitions dialog.
- When we launch a job targeting a single partition, OR open the …

[ui] Use single hidden asset job for all single-run asset executions

---

python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/decorators/decorator_assets_definition_builder.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_decorators.py

For purposes of migrating older `@multi_assets` without dropping custom IO manager capability, it's useful to be able to specify an IO manager to use for each asset output. Currently, an invariant will error if the special `SYSTEM_METADATA_KEY_IO_MANAGER_KEY` key is set on a materializable multi-asset.
This PR drops that requirement and threads through this IO manager expectation into the `Out`, also allowing any data type to be returned if an IO manager override is specified.
Before:
```python
@multi_asset(
outs={
"foo": AssetOut(key=AssetKey("foo_asset"), io_manager_key="foo_io_manager", dagster_type=int)
"bar": AssetOut(key=AssetKey("bar_asset"), io_manager_key="bar_io_manager", dagster_type=int)
}
)
def my_multi_asset():
...
yield Output(output_name="foo", value=5)
yield …
```

Allow attaching IO managers to specs

---

js_modules/dagster-ui/packages/ui-components/src/components/TextInput.tsx

As titled.
One thing to note is that, [according to this thread](https://www.reddit.com/r/Lastpass/comments/z1jno4/recent_update_html_to_disable_autofill/), the user may still need to enable a setting to have lastpass respect the data attribute

Make last pass ignore TextInput

---

js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationDefinitionsMain.tsx
js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationGraphsList.tsx
js_modules/dagster-ui/packages/ui-core/src/code-location/__fixtures__/CodeLocationPages.fixtures.ts
js_modules/dagster-ui/packages/ui-core/src/code-location/__stories__/CodeLocationDefinitionsRoot.stories.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceGraphsQuery.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceGraphsRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/extractGraphsForRepo.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/types/WorkspaceGraphsQuery.types.ts

Add a Graphs section to the new Code Locations definitions page.
Storybook example.

[ui] Code location: Graphs page

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx

As titled.
The cause of this was an effect fetching all assets instead of using the `groupSelector` on initial load.
loaded the list view for a group and made sure we filtered correctly.

Fix bug: "Asset Group list view shows entire catalog"

---

js_modules/dagster-ui/packages/ui-core/src/instigation/TickHistory.tsx

We want to set up a constrained set of indices to make the tick query faster.  We can do that more efficiently for common queries if we restrict the views enabled in the UI.
I think the common modes are going to be `All ticks`, `Failed`, and `Requested`. 
I don't think it's very useful to see `Started` or `Skipped` ticks in isolation.
https://github.com/user-attachments/assets/fa2df72b-ad8f-43ae-9b16-640b53bdabcd
BK

switch tick filters to contained set rather than every permutation

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_load_from_instance.py

Internal refactor to use specs instead of outs to build the Fivetran multi-asset. This should hopefully make further reworks of the integration a little bit easier, and in the meantime enables us to do things like set asset tags.

[dagster-fivetran][refactor] Use specs instead of outs when building Fivetran multi assets

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_load_from_instance.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/utils.py

Pull and thread through storage kind from the destination's `service` field in the API:
https://fivetran.com/docs/rest-api/destinations#retrievedestinationdetails
Unit test; tested locally w/ prod Fivetran.

[dagster-fivetran] Add storage kind to fivetran assets

---

.github/PULL_REQUEST_TEMPLATE.md
scripts/generate_changelog.py

As title. This adds a script to read through the commits since the previous release and create changelog entries for them. The expected workflow is for PR authors to add their changelog entries in their commit messages, i.e.:
CHANGELOG:
Added internal script to generate changelog entries.
In the case that your PR does not actually require any acknowledgement in the changelog (such as this one, as it is an internal script), you can indicate that by adding the NOCHANGELOG string anywhere in your commit message.
If neither of these strings are found, then the commit is considered "Undocumented", and manual intervention will be required. We can trial this workflow for a few weeks before adding CI hooks to enforce that you add changelog text to your commits.
To generate a new changelog, you …

[script] Add script to help generate the Changelog

---

docs/content/concepts/partitions-schedules-sensors/backfills.mdx
docs/content/guides/dagster/enriching-with-software-defined-assets.mdx
docs/content/guides/dagster/software-defined-assets.mdx
docs/content/integrations/embedded-elt/dlt.mdx
examples/assets_pandas_pyspark/assets_pandas_pyspark/assets/table_assets.py
examples/assets_pandas_pyspark/assets_pandas_pyspark_tests/test_assets.py
examples/docs_snippets/docs_snippets/concepts/partitions_schedules_sensors/backfills/single_run_backfill_io_manager.py
examples/docs_snippets/docs_snippets/guides/dagster/enriching_with_software_defined_assets/sda_io_manager.py
examples/docs_snippets/docs_snippets/guides/dagster/enriching_with_software_defined_assets/sda_nothing.py
examples/docs_snippets/docs_snippets/integrations/embedded_elt/dlt_source_assets.py

SourceAsset is a deprecated concept, but our dlt docs and some random guides still reference them. This PR switches mentions to AssetSpec and "external asset".

[deprecate-source-assets] remove SourceAsset from assorted docs

---

CHANGES.md

Add 1.8.2 changelog

---

python_modules/dagster/dagster/_core/execution/submit_asset_runs.py

Here's the situation that's broken:
- The user code is on a Dagster version where there's an implicit asset job per `PartitionsDefinition`
- The host code is on a Dagster version where there's a single implicit asset job
- The user code has assets with two different `PartitionsDefinition`s, meaning it has `__ASSET_JOB_0` and `__ASSET_JOB_1`
- DA wants to submit a run to materialize one of those `PartitionsDefinition`s
- It needs to figure out what job to submit the run for 
Prior to this PR, it expects there to be a job just named `__ASSET_JOB`, but because there isn't, this gets raised:
```python
File "/Users/sryza/dagster/python_modules/dagster/dagster/_core/execution/asset_backfill.py", line 754, in _submit_runs_and_update_backfill_in_chunks …
```

fix backfill and DA backcompat with single implicit asset jobs

---

js_modules/dagster-ui/packages/ui-core/src/instigation/TickDetailsDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/instigation/TickHistory.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/TickTagForRun.tsx

There is a bug on the sensor tick table where clicking to view a run requested for a tick can show information about an unrelated tick.
This is because sensor tick IDs can be larger than JavaScript's `Number.MAX_SAFE_INTEGER`, but they're being cast to `Number` for the GraphQL variable. JS may cast the value to a number that doesn't match the intended value, resulting in the wrong tick ID being sent in the query.
We shouldn't be trying to represent them as `number` in JS. The GraphQL input type expects it to be a BigInt, and we can just pass a string for that.
View sensor tick history with ticks that have tick IDs being cast to incorrect values. Verify that the values are now correct, and that when I click to view runs requested for the tick, the query variable and rendered output are …

[ui] Sensor history: Fix tick ID variable

---

js_modules/dagster-ui/package.json

Whenever we run cloud we call `yarn generate-resolutions` which inserts a gitignore'd `.tsconfig.json` file inside `ui-core/src`. This config file remaps all of the shared imports to their `.cloud.tsx` counterparts. Since this file is  in `.gitignore` it never gets removed which you'd want to happen if you were developing solely in OSS. To make that happen I'm making `yarn start` automatically remove the config file. Note that this doesn't affect the ability to run both OSS and Cloud at the same time.
yarn start

Remove tsconfig for cloud resolutions when running OSS

---

js_modules/dagster-ui/packages/ui-core/src/search/SearchDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/search/SearchResults.tsx

As titled
If results are loading then don't show the "No results message".
NOCHANGELOG

[Search] Don't show "No results" while search is loading

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_runs_feed.py
python_modules/dagster/dagster/_core/execution/backfill.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/storage/legacy_storage.py
python_modules/dagster/dagster/_core/storage/runs/base.py
python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py
python_modules/dagster/dagster_tests/storage_tests/utils/run_storage.py
python_modules/libraries/dagster-postgres/dagster_postgres_tests/test_run_storage.py

Adds ability to filter on create time to the BulkActions table so that we dont need to filter out results manually when serving the RunsFeed.  Does this by adding a `BulkActionsFilter` like `RunsFilter` so that if we want to add more filtering capabilities we can add them to this object rather than as new parameters on the `get_backfills` method
companion internal pr https://github.com/dagster-io/internal/pull/11031

create time filtering for bulk actions table

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_backfills.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py
python_modules/dagster-graphql/dagster_graphql/schema/inputs.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_backfill.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_runs_feed.py
python_modules/dagster/dagster/_core/execution/backfill.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/storage/legacy_storage.py
python_modules/dagster/dagster/_core/storage/runs/base.py
python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py
python_modules/dagster/dagster_tests/storage_tests/utils/run_storage.py
python_modules/libraries/dagster-postgres/dagster_postgres_tests/test_run_storage.py

pipes the bulk actions filters through to the GQL layer

BulkActions filters in GQL layer

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/inputs.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_backfill.py
python_modules/dagster/dagster/_core/execution/backfill.py
python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py
python_modules/dagster/dagster_tests/storage_tests/utils/run_storage.py

You can select multiple statuses when you filter for runs in the UI, so we should support filtering backfills for multiple statuses. Alternatively we can wait until the dagster run status for a backfill is stored in the DB and then just allow filtering for multiple statuses of dagster run statuses
companion internal pr https://github.com/dagster-io/internal/pull/11113
unit tests

filter by multiple statuses in BulkActionsFilter

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_backfills.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/storage/legacy_storage.py
python_modules/dagster/dagster/_core/storage/runs/base.py
python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py
python_modules/dagster/dagster/_daemon/backfill.py
python_modules/dagster/dagster/_utils/caching_instance_queryer.py
python_modules/dagster/dagster_tests/storage_tests/utils/run_storage.py

reorders the params to `get_backfills` so that `filters` comes before `status`. Also updates internal callsites to use the `filters` parameter. `get_backfills` is not marked public, so reordering params like this is probably ok? can choose not to go forward with this if it seems like too much of a change. 
companion internal pr https://github.com/dagster-io/internal/pull/11114

Reorder status and filters params for get_backfills

---

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/resources.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/sling_event_iterator.py

- Yielding `AssetMaterialization` for assets, as supported results have been limited in 1.8.1
- `pytest`
- Sling resource yields `MaterializeResult` for assets and `AssetMaterialization` for op

[sling] yield asset materialization / materialize result depending if asset or op

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_auto_materialize_policy_conversion.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_automation_condition.py

If users create a custom AutomationCondition, it will of course not be serializable. This updates the serialization logic to detect this case and convert the entire AutomationCondition into a format that retains the essential information but does not contain an evaluation function. This allows us to render it in the UI (if we so desire -- currently we only render historical values, not the current condition on the definition object).
Note that this serialization logic is happening in a somewhat-surprising spot, which is the AutoMaterializePolicy object. This is because we store AutomationConditions wrapped inside an AutoMaterializePolicy on the ExternalAssetNode. I'll move this logic over to ExternalAssetNode further up the stack.

[DA][2/n][user-code] Allow custom AutomationConditions to cross a serdes boundary

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/slice_conditions.py

As title, this converts AutomationContext to a dataclass, which allows fields to start with underscores. This allows us to mark certain fields as private to help slim down the number of available properties.

[DA][4/n][user-code] Convert AutomationContext to dataclass, make methods private

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_evaluator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py

We don't need to tote around two separate variable for handling legacy context -- just make it None if we don't need it.

[DA][5/n][user-code] Simplify legacy_context handling

---

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/code_version_changed_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/slice_conditions.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/any_downstream_conditions_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/newly_true_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/since_operator.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/automation_condition_scenario.py

This is commonly used throughout our built-in AutomationConditions, and likely will be commonly-used in user-defined AutomationConditions. This is significantly more ergonomic than the previous setup. Note that there is not a corresponding utility provided for getting the "full" asset slice. This is because in almost all cases where you would want to do that, you should instead just use `context.candidate_slice` to avoid returning a superset of your candidates.
Also renamed `create_empty_slice` on `AssetGraphView`, as it's inconsistent naming-wise from the other methods (in which `get_*` indicates a cheap operation).

[DA][6/n][user-code] Add `get_empty_slice` to AutomationContext

---

python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_impls.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_evaluator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/code_version_changed_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/slice_conditions.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/any_downstream_conditions_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/newly_true_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/since_operator.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/automation_condition_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_automation_condition.py
python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_dep_condition.py

This reduces the number of fields on the AutomationCondition class by taking advantage of cached properties. I also removed the somewhat confusing `create()` methods in favor of just a bog-standard `__init__` method, which routes all construction through the same entrypoint. I think this will feel more intuitive in most cases.
I plan on using a hidden-param-style pattern to futher hide "extra_state" and "asset_subsets_with_metadata", which are not needed for user-defined automation conditions.

[DA][7/n][user-code] Simplify AutomationResult

---

python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_impls.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/code_version_changed_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/newly_true_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/serialized_objects.py

Technically, the Declarative Automation cursoring system can accept and store any serializable value in its "extra_state". This is useful as a performance optimization (it is common for us to want to keep track of serialized AssetSubsets between ticks, so not needing to do a double serialization / deserialization process is pretty valuable), but this overly-broad construct is likely more confusing than anything if we expose it as a public API.
Instead, expose a simplified, string-only cursor interface on the context. This mirrors the existing sensor APIs more closely.

[DA][8/n][user-code] Add simplified string-only `cursor` property

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/slice_conditions.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/serialized_objects.py

I don't want to expose "TemporalContext" as part of the public API, so I remove references to it. Also renamed the existing fields (subjective, but I think they look a little better this way).

[DA][9/n][user-code] Rename temporal-context-related fields

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/rule_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/code_version_changed_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/slice_conditions.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/any_downstream_conditions_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/newly_true_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/since_operator.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/user_defined/test_user_defined_automation_condition.py

Previously, it was required to opt into storing a cursor, as most builtin conditions do not require a cursor and it would be wasteful to store one. However, this is unintuitive for user-defined AutomationConditions, and so for non-builtins, we will automatically opt into using cursors.

[DA][11/n][user-code] Don't require `requires_cursor` to be set

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_evaluator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/rule_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/user_defined/test_user_defined_automation_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/automation_condition_scenario.py

Two things:
1. Change it from `context.logger` to `context.log` to better align with our existing interfaces
2. Make the log you get on each context object specific to the class that's being logged from (this is just quality of life)
Before this change:
```
2024-08-14 19:05:37 -0700 - dagster.daemon.SensorDaemon - INFO - Checking for new runs for sensor: tryin_to_make_a_change
2024-08-14 19:05:37 -0700 - dagster - INFO - __repository__ - tryin_to_make_a_change - Prefetching asset records for 1 records.
2024-08-14 19:05:37 -0700 - dagster - INFO - __repository__ - tryin_to_make_a_change - Done prefetching asset records.
2024-08-14 19:05:37 -0700 - dagster - ERROR - some msg
```
After this change:
```
2024-08-14 19:05:37 -0700 - dagster.daemon.SensorDaemon - INFO - Checking for new runs for …
```

[DA][12/n][user-code] Improve log handling

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_asset_condition_evaluations.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_auto_materialize_asset_evaluations.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_condition_evaluations.py
python_modules/dagster-graphql/dagster_graphql/schema/auto_materialize_asset_evaluations.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_condition_evaluations.py
python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_evaluation.py
python_modules/dagster/dagster/_core/scheduler/instigation.py
python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster/_daemon/sensor.py
python_modules/dagster/dagster/_utils/test/schedule_storage.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_asset_daemon_failure_recovery.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/legacy_tests/test_auto_materialize_asset_evaluation.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/legacy_tests/test_auto_materialize_policy.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/asset_daemon_scenario.py

Ran into this big chunk of code while working on some other changes. It is no longer necessary and can be removed.
Put simply, we had a very old format for serializing information about AMP evaluations. When we switched formats, I created some fairly extensive / hacky backcompat logic to convert from the old format to the new format automatically in the serdes layer. Over time, this has broken down to a certain extent. For example, a change several months ago made it so that this logic would no longer work properly with partitioned assets.
This is ok, as we delete old evalaution data after 30 days, and most people have updated past this version long ago (the original backcompat changes were ~9 months ago). The net impact will be that now if someone is in this (exceedingly rare) situation, …

[DA][14/n][cleanup] Remove old backcompat logic

---

examples/experimental/dagster-airlift/dagster_airlift/core/sensor.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/conftest.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_sensor.py

Fixes the unsynced issue with the sensor. We need to sort first by timestamp, then by topological order, for the case of dependencies within the same task.
Tested by verifying the unsynced issue went away in dbt example.

[dagster-airlift] sensor fix

---

examples/experimental/dagster-airlift/dagster_airlift/core/utils.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_utils.py

Allow task/dag to be set by name, op tag, or asset tag.
Simple unit tests for the util methods.

[dagster-airlift] allow all retrieval methods of task/dag

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_job_partitions.py
python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_partition.py

While working on https://github.com/dagster-io/dagster/pull/23491 and https://github.com/dagster-io/dagster/pull/23494, I wrote a set of tests that validate that operations like `get_tags_for_partition` over GraphQL and gRPC, when an asset job includes assets with different `PartitionsDefinition`s and an asset selection is provided. However, I had to take them out due to the way the stack was sequenced.
This PR adds them back in.
NOCHANGELOG

Add tests for grpc and graphql against single implicit asset jobs

---

python_modules/dagster/dagster/_generate/download.py
python_modules/dagster/dagster_tests/cli_tests/test_project_commands.py

Fixes the broken Buildkite build. I assume we want to ignore these? If not, I'll stick them in the other list.

Ignore docs_beta_snippets examples

---

examples/experimental/dagster-airlift/dagster_airlift/core/__init__.py
examples/experimental/dagster-airlift/dagster_airlift/core/defs_builders.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_utils.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/lakehouse.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/lakehouse.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/migrate.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/observe.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/shared/dbt/models/iris_setosa.sql
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/shared/dbt/models/sources.yml
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/shared/load_iris.py

adds a simple defs builder which ingests a list of specs for a particular dag/task id, to make the observe step more straightforward.

[dagster-airlift] assets_from_task

---

docs/content/guides/integrations/approaches-to-writing-integrations.mdx

- Introduces a landing page for guides on writing integrations, currently outlined include:
* asset factory
* multi-asset decorator
* resource definitions
* pipes

[docs][guide] approaches to writing integrations

---

docs/docs-beta/.eslintrc.js
docs/docs-beta/README.md
docs/docs-beta/package.json
docs/docs-beta/yarn.lock

Modified yarn commands. Now:
- `ts` runs TypeScript
- `lint` applies prettier changes and autofixes
- `vale` checks value
- `lint-and-vale` is a combination of the two above
Run the commands, verify that they behave as expected.
NOCHANGELOG

[docs-beta] README change regarding lint:fix

---

CHANGES.md

```
TypeError: PartitionArgs.__new__() missing 1 required positional argument: 'job_name'
```
We've yanked this version of Dagster from PyPI. Affected users should downgrade to 1.8.2/0.24.2.
> NOCHANGELOG

Update changelog to reflect yank

---

examples/experimental/dagster-airlift/dagster_airlift/core/sensor.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_sensor.py
python_modules/dagster/dagster/_core/definitions/repository_definition/repository_data.py
python_modules/dagster/dagster/_core/definitions/repository_definition/repository_definition.py

Make the sensor support requesting runs for any checks which exist on assets for which it is reporting materializations.

[dagster-airlift] support checks in sensor

---

examples/experimental/dagster-airlift/dagster_airlift/core/__init__.py
examples/experimental/dagster-airlift/dagster_airlift/core/dag_defs.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_dag_defs.py

This adds `dag_defs` and `task_defs` in order to manage the airlift mapping process.
e.g.
```python
defs = dag_defs(
"dag_one",
task_defs("task_one", AssetSpec(key="asset_one")),
task_defs("task_two", AssetSpec(key="asset_two"), AssetSpec(key="asset_three")),
)
```
`task_defs` takes a list where each element can be a AssetSpec, AssetsDefinition, or Definition. It attaches task_id and dag_id as tags expected by Airlift.
This is designed such one a dag migration is complete, you can delete all references to `dag_defs` and `task_defs` and use the argument to `task_defs` to `combine_defs` without modification.
BK
NOCHANGELOG

Add dag_defs and task_defs to composably add tags to airlifted defintions

---

examples/docs_beta_snippets/README.md
examples/docs_beta_snippets/docs_beta_snippets/guides/automation/asset-sensor-custom-eval.py
examples/docs_beta_snippets/docs_beta_snippets/guides/automation/asset-sensor-with-config.py
examples/docs_beta_snippets/docs_beta_snippets/guides/automation/multi-asset-sensor.py
examples/docs_beta_snippets/docs_beta_snippets/guides/automation/schedule-with-partition.py
examples/docs_beta_snippets/docs_beta_snippets/guides/automation/simple-asset-sensor-example.py
examples/docs_beta_snippets/docs_beta_snippets/guides/automation/simple-schedule-example.py
examples/docs_beta_snippets/docs_beta_snippets/guides/automation/simple-sensor-example.py
examples/docs_beta_snippets/docs_beta_snippets/guides/data-assets/passing-data-assets/passing-data-avoid.py
examples/docs_beta_snippets/docs_beta_snippets/guides/data-assets/passing-data-assets/passing-data-explicit.py
examples/docs_beta_snippets/docs_beta_snippets/guides/data-assets/passing-data-assets/passing-data-io-manager.py
examples/docs_beta_snippets/docs_beta_snippets/guides/data-assets/passing-data-assets/passing-data-rewrite-assets.py
examples/docs_beta_snippets/docs_beta_snippets/guides/data-modeling/metadata/custom-local-references.py
examples/docs_beta_snippets/docs_beta_snippets/guides/data-modeling/metadata/definition-metadata.py
examples/docs_beta_snippets/docs_beta_snippets/guides/data-modeling/metadata/oss-references.py
examples/docs_beta_snippets/docs_beta_snippets/guides/data-modeling/metadata/owners.py
examples/docs_beta_snippets/docs_beta_snippets/guides/data-modeling/metadata/plus-references.py
examples/docs_beta_snippets/docs_beta_snippets/guides/data-modeling/metadata/python-local-references.py
examples/docs_beta_snippets/docs_beta_snippets/guides/data-modeling/metadata/runtime-metadata.py
examples/docs_beta_snippets/docs_beta_snippets/guides/data-modeling/metadata/table-column-lineage-metadata.py
examples/docs_beta_snippets/docs_beta_snippets/guides/data-modeling/metadata/table-schema-metadata.py
examples/docs_beta_snippets/docs_beta_snippets/guides/data-modeling/metadata/tags.py

Update the beta docs code snippets to use the new `import dagster as dg` code pattern. This should be the new approach to all documentation that references dagster code, as consistency is important.
Here are a few reasons why I like this approach:
0) There is prior art in many libraries of this approach, notably `pandas`, `sklearn`, `numpy`, `matplotlib`, `pytest` and many other packages that export many objects. 
1) Fewer import lines in code samples/snippets. Compare the first image which is 12 lines shorter. This makes code easier for users to understand parse.
2) Another side benefit is that type-ahead experience is improved. 
In VS Code, for example, typing `dg.sensor` and pressing Ctrl+Space provides you with all the exported Sensor-like objects 
Compare to typing `sensor` …

[docs-beta] Update to dagster as dg

---

examples/experimental/dagster-airlift/dagster_airlift/core/__init__.py
examples/experimental/dagster-airlift/dagster_airlift/core/dag_defs.py
examples/experimental/dagster-airlift/dagster_airlift/core/defs_builders.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_utils.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/complete.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/lakehouse.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/migrate.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/observe.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/definitions.py

This eliminates `combine_defs` in airlift and instead relies on vanilla `Definitions.merge` which ends up with more clarity and less code overall. We may try a different way of "sugaring" this later, but `combine_defs` was not it.
BK
NOCHANGELOG

Eliminiate combine defs

---

examples/experimental/dagster-airlift/README.md
examples/experimental/dagster-airlift/dagster_airlift/dbt/multi_asset.py
examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_dbt_multi_asset.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/complete.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/migrate.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/definitions.py

Make the name of the multi-asset node backing dbt_assets, by default "build_{project_name}". E.g. "build_jaffle_shop"
BK
NOCHANGELOG

Default name of dbt multi asset to build_{project_name}

---

examples/experimental/dagster-airlift/dagster_airlift/core/dag_defs.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_dag_defs.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/observe.py
examples/experimental/dagster-airlift/examples/simple-migration/simple_migration/dagster_defs/observe.py

Change `task_defs` to only accept a single `Definitions` argument, to mirror `dag_defs`.  This is more consistent and simplifies the implementation.
BK
NOCHANGELOG

Change task_defs to only accept Definitions

---

docs/docs-beta/src/components/CodeExample.tsx

Addresses https://linear.app/dagster-labs/issue/DOC-381/component-make-titles-optional-in-codeexamples. This turns out to be very easy, we just don't pass the title to the underlying component :)

[DOC-381] make titles optional in CodeExamples

---

examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_python_multi_assets.py

Improving the test logic here so that `noqa` and `type: ignore` are not required.
BK
NOCHANGELOG

Remove all type: ignores and noqa in airlift test

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/managed/generated/sources.py

Resolves:
```
Error: MDX compilation failed for file "/Users/colton/src/dagster/docs/docs-beta/docs/apidocs/libraries/dagster-airbyte.md"
Cause: Can't parse URL https:/ with base unspecified://
Details:
Error: Can't parse URL https:/ with base unspecified://
```
NOCHANGELOG

[docathon] remove invalid urls breaking docusaurus

---

python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py

The test change causes a graphql test to fail until the fix is applied.
Fixed a bug that caused an "Asset must be part of at least one job" error when clicking on an external asset in the asset graph UI

fix GrapheneAssetNode.resolve_configFields

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/inputs.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_backfill.py
python_modules/dagster/dagster/_core/definitions/selector.py
python_modules/dagster/dagster/_core/execution/asset_backfill.py
python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py
python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py

Motivated by a user request. This makes it possible to request multiple ranges of partitions for an asset within a single launch backfill mutation. This is already supported by the underlying backfill machinery, so it's just a matter of exposing it at the graphql layer.
The fact that `GraphenePartitionsSelector` already has a `range` parameter is a little bit unfortunate, because now we have to support both `range` and `ranges`. While this isn't technically a public API, I know that some users rely on it, so I don't want to break it in a patch release.
I am still not an expert in the way of GraphQL - is there any way to enforce at the GraphQL layer that they can't supply both `range` and `ranges`?
NOCHANGELOG

enable launch backfill graphql mutation to target multiple partition ranges per asset

---

python_modules/dagster/dagster/_core/definitions/job_definition.py

Summary:
This can take seconds on large jobs, and we call it at twice when loading a new code location when using defer_snapshots=True - once when generating the IDs for the JobRefs,and then again when loading the actual jobs.
Test Plan: BK, verify when running an agent locally that this is called only once per job when loading a new code locatoin

Cache JobDefinition.get_job_index

---

examples/docs_beta_snippets/setup.py
scripts/run-pyright.py

As title -- this makes precommit hooks work when modifying things in the docs_beta_snippets directory (which is explicitly excluded from pyright as it requires dagster-cloud). It's totally expected in some cases for there to be no environment which maps to a particular file, in the case where we are explicitly excluding that file's directory from type checking.
Note that the function I modified is only used in the quick_pyright script not the full pyright build that we run in CI, so this leniancy will not impact the overall correctness of anything, it's just a matter of avoiding local errors.
NOCHANGELOG

[DOCS-423] Fix `make quick_pyright` when editing docs

---

docs/docs-beta/docs/guides/data-modeling/metadata.md

I learned some new things during @erinkcochran87's presentation
NOCHANGELOG

[docathon] Clean up metadata docs (DOC-382)

---

python_modules/dagster/dagster/_grpc/impl.py
python_modules/dagster/dagster/_grpc/server.py
python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_persistent.py

Allows you to run code servers in a mode where exceptions are logged to the console, in addition to being logged to the caller.
New test case - run code server locally and add an exception to schedules/sensors, view code server output

Add an env var that, when enabled, logs exceptions raised during code server calls to stderr

---

python_modules/dagster/dagster/_core/storage/event_log/sqlite/consolidated_sqlite_event_log.py
python_modules/dagster/dagster/_core/storage/event_log/sqlite/sqlite_event_log.py
python_modules/dagster/dagster/_core/storage/local_compute_log_manager.py

Summary:
This was changed to a kwarg in watchdog 5.0 instead of a positional arg. Resolves https://github.com/dagster-io/dagster/issues/23957.
Test Plan:
View run logs streaming in on watchdog 5.0 and <5.0
Fixed an issue where viewing run logs with the latest 5.0 release of the watchdog package raised an exception.

Fix filesystem observer on watchdog 5.0

---

docs/docs-beta/docs/guides/data-modeling/configuring-assets.md
docs/docs-beta/src/components/CodeExample.tsx
docs/vale/styles/config/vocabularies/Dagster/accept.txt
examples/docs_beta_snippets/docs_beta_snippets/guides/data-modeling/configuring-assets/config-schema.py
examples/docs_beta_snippets/docs_beta_snippets/guides/data-modeling/configuring-assets/run_config.yaml

First pass at a short-but-sweet asset config guide.
NOCHANGELOG

[docathon] Configuring assets guide

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
examples/experimental/dagster-airlift/README.md
examples/experimental/dagster-airlift/dagster_airlift/core/dag_defs.py
examples/experimental/dagster-airlift/dagster_airlift/migration_state.py
examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_migrating_dag_correctly_marked.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_migration_state.py
examples/experimental/dagster-airlift/examples/tutorial-example/Makefile
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/airflow_dags/migration_state/rebuild_customers_list.yaml
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/conftest.py

Adapted from https://github.com/dagster-io/dagster/pull/23944
This represents the minimal set of changes necessary to get tests working and the tutorial up and running.
* Adding tutorial-examples to the overall test suite.
* Adds local airflow setup to the README.md
* Updates makefile for the local airflow setup
* Fixes migration state format
Manual spinup of tutorial-example. BK.
NOCHANGELOG

Adding makefile for tutorial

---

examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/build_dag_defs.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/csv_to_duckdb_defs.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/definitions.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/duckdb_to_csv_defs.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/unit_tests/test_build_dag_defs.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/unit_tests/test_duckdb_to_csv_defs.py

Takes advantage of new unit tests with fast feedback loops direction to create defs in isolated environment.
Without unique node names was getting this mystifying error:
```
E                       dagster._core.errors.DagsterInvalidDefinitionError: Invalid dependencies: node "_multi_asset_2" does not have output "raw_data__raw_customers". Listed as dependency for node "build_jaffle_shop input "raw_data_raw_customers"
```
This fixes that and provides convenient op names.
BK
NOCHANGELOG

Extract dags_def construction into separate file, write tests, and fix bugs

---

docs/docs-beta/docs/guides/data-modeling/configuring-assets.md

This is a quick followup to [this PR](https://github.com/dagster-io/dagster/pull/23924) on asset configuration.
I wanted to make it super clear that the point of asset config is runtime configuration, because this has been a source of confusion in the past which makes it more difficult to explain asset factories.
Also incorporated @erinkcochran87's feedback here: https://github.com/dagster-io/dagster/pull/23924#discussion_r1733105326.
NOCHANGELOG

[docs-beta] tweaks to configuring assets page

---

python_modules/dagster/dagster/_grpc/server.py
python_modules/dagster/dagster/_grpc/types.py
python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_partition.py

Having `job_name` as a required param causes problems when a pre-1.8.2 agent is used, because the agent strips the parameter off when reserializing the object.
Added unit tests. Verified that these tests pass when cherry-picking onto the 1.8.2 branch.
Fixes a bug that caused an error when loading the launchpad for a partition, when using in Dagster+ with an agent with version below 1.8.2.

make `job_name` param on `PartitionArgs` and `PartitionNames` args optional

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py
examples/experimental/dagster-airlift/dagster_airlift/core/defs_from_airflow.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_dbt_defs_migrated.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_load_dagster.py

We were not copied resources during the manual merge rountine in `build_defs_from_airflow_instance`. This fixes that a provides a minimal repro in a unit test environment. Also flagged another potential problematic miscopy and tracked in https://linear.app/dagster-labs/issue/FOU-372/investigate-suspect-code-in-construct-assets-with-task-migration-info.
Ran
```python
import os
from pathlib import Path
from dagster import AssetSpec, Definitions
from dagster_airlift.core import (
AirflowInstance,
BasicAuthBackend,
build_defs_from_airflow_instance,
dag_defs,
task_defs,
)
from dagster_airlift.dbt import dbt_defs
from dagster_dbt import DbtProject
def dbt_project_path() -> Path:
env_val = os.getenv("DBT_PROJECT_DIR")
assert env_val
return Path(env_val)
def rebuild_customer_list_defs() -> …
```

Check-in minor repo of resource issue and mark suspect code

---

js_modules/dagster-ui/packages/ui-core/src/hooks/useQueryPersistedState.tsx

Try to avoid the `history.replace` loop in `useQueryPersistedState` by bailing out if the query is unchanged.
I think we're ending up in a situation where URL querystring updates are triggering effects that lead to querystring updates, but without any actual changes to the query values. With no guard in place to ensure that we don't hammer `history.replace`, we just keep calling it. This can lead to an error when fires too much, which can kill the page.
Instead, just skip the `history.replace` call if the previous query and new query are the same. This is done with a `qs.stringify()` comparison.
View Insights, with lots of query params in the URL. Verify that when I change filters, even though the change handler fires a lot, `history.replace` only fires once.
Bug:
[ui] Prevent excessive …

[ui] Try to guard against history loop in useQueryPersistedState

---

js_modules/dagster-ui/packages/eslint-config/rules/index.js
js_modules/dagster-ui/packages/eslint-config/rules/no-apollo-client.js
js_modules/dagster-ui/packages/ui-core/src/apollo-client/index.tsx

Wrapping `useQuery` and `useLazyQuery` to automatically integrate with our performance tracking so that we can get rid of `useBlockTraceOnQueryResult`
I ran yarn lint --fix and saw it auto-fix all of the @apollo/client imports in ui-core. I will put these changes in the next PR to keep this one small.
NOCHANGELOG

[1/4] Wrap useQuery/useLazyQuery + lint rule

---

docs/content/integrations/dbt/using-dbt-with-dagster-plus/hybrid.mdx
docs/content/integrations/dbt/using-dbt-with-dagster-plus/serverless.mdx
docs/dagster-university/pages/dagster-dbt/lesson-7/4-creating-the-manifest-during-deployment.md
examples/assets_dbt_python/.github/workflows/examples/branch_deployments.yml
examples/assets_dbt_python/.github/workflows/examples/deploy.yml

Summary:
Switch to the correct command for upgrading pip.

Fix pip upgrades in dbt examples

---

examples/experimental/dagster-airlift/examples/mwaa-example/scripts/setup_mwaa.py
python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/ecs.py
python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/glue.py
python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/lambda_.py
python_modules/libraries/dagster-aws/dagster_aws/pipes/context_injectors.py
python_modules/libraries/dagster-aws/dagster_aws/pipes/message_readers.py
python_modules/libraries/dagster-aws/dagster_aws/secretsmanager/resources.py
python_modules/libraries/dagster-aws/dagster_aws/ssm/resources.py
python_modules/libraries/dagster-aws/dagster_aws_tests/pipes_tests/fake_ecs.py
python_modules/libraries/dagster-aws/dagster_aws_tests/pipes_tests/fake_glue.py
python_modules/libraries/dagster-aws/dagster_aws_tests/s3_tests/test_s3_file_manager.py
scripts/auto_ignore_pyright_errors.py

Ignore pyright errors in `dagster-aws` which popped out after the introduction of `boto3-stubs-lite`. 
I suggest we slowly remove these ignore comments and fix the code for pyright to pass over time. 
I made a script to do it automatically. 
pyright should be passing now
> NOCHANGELOG

[dagster-aws] ignore pyright errors with boto3-stubs

---

examples/experimental/dagster-airlift/dagster_airlift/test/shared_fixtures.py
examples/experimental/dagster-airlift/examples/tutorial-example/Makefile
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/conftest.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_migration_state.py

Adds an integration test which tries loading the tutorial project at each stage of migration & validates that Airflow & Dagster show the correct status.
`NOCHANGELOG`

[airlift] Add migration state tests to Airlift tutorial

---

docs/docs-beta/docs/guides/quality-testing/data-freshness-testing.md
docs/vale/styles/config/vocabularies/Dagster/accept.txt
examples/docs_beta_snippets/docs_beta_snippets/guides/data-assets/quality-testing/freshness-checks/anomaly-detection.py
examples/docs_beta_snippets/docs_beta_snippets/guides/data-assets/quality-testing/freshness-checks/external-asset-freshness-check.py
examples/docs_beta_snippets/docs_beta_snippets/guides/data-assets/quality-testing/freshness-checks/materializable-asset-freshness-check.py
examples/docs_beta_snippets/setup.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/dags.py

[docs] Data freshness guide

---

.github/workflows/build-docs.yml

Exclude `docs-beta` changes from the docs GitHub action. We don't want beta-only changes to trigger this action at all.
Stack a docs-beta change on top of this, verify that the action doesn't run.

[ui] Exclude docs-beta content from docs GH action

---

.github/workflows/build-docs-revamp.yml

FIx the build-docs-revamp GitHub action:
- Make sure we find files within `docs/docs-beta` when diffing.
- Find both `md` and `mdx` files within `docs-beta` content, for display as preview URLs.
- Enable the preview link output for the PR comment.
- Remove the explicit `alias-domains` entry, which we don't actually need and which ends up creating a weird extra useless link because of the way the vercel action applies the preview URL. (It joins all aliases together and spits them out to replace the `{{deploymentUrl}}` marker.)
Add md and mdx changes to this PR, push. Verify that the GH action behaves correctly, and produces correct links.
`NOCHANGELOG`

[docs-beta] Update docs-revamp GitHub action

---

helm/dagster/schema/schema/charts/dagster/subschema/daemon.py
helm/dagster/schema/schema_tests/test_dagster_daemon.py
helm/dagster/templates/configmap-instance.yaml
helm/dagster/values.schema.json

Summary:
Allows you to set the retry_on_asset_or_op_failure config when deploying on k8s.
Test Plan: BK
[dagster-k8s] Added support for setting `dagsterDaemon.runRetries.retryOnAssetOrOpFailure` to False in the Dagster Helm chart to [prevent op retries and run retries from simultaneously firing on the same failure.](https://docs.dagster.io/deployment/run-retries#combining-op-and-run-retries)

Add retryOnAssetOrOpFailure to helm chart

---

.github/workflows/build-docs-revamp.yml

The glob isn't finding md/mdx files properly. Not sure why, but if I just cd into the docs directory and use syntax like in the old docs action, it works.
Modify a `md` file in `docs-beta/docs`, verify that the GH action posts a comment with the preview URL.
`NOCHANGELOG`

[docs-beta] Fix preview links in docs-revamp GH action

---

examples/docs_beta_snippets/docs_beta_snippets/dagster-plus/deployment/alerts/generate_alerts_doc.py
examples/docs_beta_snippets/setup.py
examples/docs_beta_snippets/tox.ini
scripts/generate_changelog.py

We want to test docs snippets against source as much as possible, but we need to special case `dagster-cloud` since its not in the repo. To do this we move dependency management to just `tox.ini` since this module only runs in the context of testing via tox.
Additionally i updated some `path` to `pathlib` since we don't depend on it else where and it doesn't seem worth the friction to users of requiring installing something outside of `dagster` / `dagster-X` when built in `pathlib` works just fine.
NOCHANGELOG

[bk] tweak docs beta snippets tox

---

docs/content/concepts/assets/asset-selection-syntax.mdx

Just noticed this typo, figured even if these are legacy some of the copy might get moved over, so thought I'd fix

[typo] asset selection syntax upstream->downstream

---

examples/experimental/dagster-airlift/examples/tutorial-example/tox.ini
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/airflow_dags/dags.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/conftest.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_load_dagster.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_migrating_e2e.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_observing_e2e.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_peering_e2e.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/utils.py
examples/experimental/dagster-airlift/tox.ini

Adds e2e test suites which fully spin up Dagster + Airflow for each of the peer, observe, migrate steps and ensures that:
(1) run state transfers over properly once a DAG run completes
(2) migrated steps run in Dagster rather that in Airflow

[airlift] add e2e tests for peer, observe, migrate steps

---

js_modules/dagster-ui/packages/ui-core/src/runs/__tests__/useRunsForTimeline.test.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/useRunsForTimeline.tsx

While looking at this code again I realized there's an edge case due to the paginated logic. In particular it's possible that the user closes the tab before we've paginated across all runs for a specific time period. When this happens we will have partially committed data to the cache. 
Nobody reported this issue.
Added a jest test that previously failed.
NOCHANGELOG

[Run Timeline] Only commit data to cache after all data is fetched.

---

docs/docs-beta/docs/dagster-plus/deployment/environment-variables/built-in.md
docs/docs-beta/docs/dagster-plus/deployment/serverless/transition-hybrid.md

Knocking out this pretty easy one too while i do the other env var doc. I have a couple aesthetic questions about how to format some things, but i think the existing doc does a pretty good job, so i ended up re-using most of it 
Docs preview - https://dagster-docs-beta-5iiwhw9qp-elementl.vercel.app/dagster-plus/deployment/environment-variables/built-in
`NOCHANGELOG`

reference for built-in env vars

---

examples/experimental/dagster-airlift/examples/tutorial-example/README.md
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/migrate.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/migrate_with_check.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/observe.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/standalone.py

Changes a few of the stages to standardize file structure and make the observation->migration step a little easier to understand.
In particular:
- Moves defs building to `rebuild_customers_list_defs` fn in each of the observe, migrate, standalone steps
- Moves the asset definition builder fns to use user-passed Specs instead of constructing them, reducing complexity + making observe->migrate step clearer
I think this is most clear viewing observe and then. migrate stages back to back:
https://github.com/dagster-io/dagster/blob/99c96ced310195c1ff3a2ed9cd893ec8a4bdf1a5/examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/observe.py#L22-L50
https://github.com/dagster-io/dagster/blob/99c96ced310195c1ff3a2ed9cd893ec8a4bdf1a5/examples/experimental/ …

[airlift] Standardize file structure of stage snippets

---

docs/docs-beta/docs/dagster-plus/deployment/hybrid/agents/local.md
docs/docs-beta/docs/dagster-plus/deployment/serverless/transition-hybrid.md
examples/docs_beta_snippets/docs_beta_snippets/dagster-plus/deployment/hybrid/agents/local_dagster.yaml

Guide for moving from serverless to hybrid. 
Also a guide for setting up the local agent since i went through this process to test that the transitioning guide didn't have any steps to add after making the agent, but then i couldn't set up the local agent with my org in canary bc the cli command was set to work with prod only
`NOCHANGELOG`

transitioning serverless to hybrid guide

---

python_modules/libraries/dagster-celery-k8s/dagster_celery_k8s/launcher.py
python_modules/libraries/dagster-celery-k8s/dagster_celery_k8s_tests/test_executor.py
python_modules/libraries/dagster-celery-k8s/dagster_celery_k8s_tests/test_launcher.py
python_modules/libraries/dagster-k8s/dagster_k8s/launcher.py
python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_job.py
python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_launcher.py

If I explicitly set tag `dagster-k8s/config:{"container_config": {"image": "my_image:latest"}}`,
once the job starts, additional tag dagster/image with current (wrong) code location image is added.
Discussed here: https://github.com/dagster-io/dagster/discussions/24006#discussioncomment-10479249
Found all usages of `from dagster._core.storage.tags import DOCKER_IMAGE_TAG`.
Found tests that mention `user_defined` and extended them to cover case when image is explicitly set from UI as:
```
"dagster-k8s/config": {"container_config": {"image": "myregistry/myimage:mytag"}}
```
[dagster-k8s, dagster-celery-k8s] label `dagster/image` is correctly set when image is provided from user_defined_k8s_config

fix: label dagster/image is correctly set when image is provided from user_defined_k8s_config

---

js_modules/dagster-ui/packages/ui-core/src/instigation/TickHistory.tsx

Fixes the tick filter display, once selected
Selected filter, saw that the selector displayed the correct label.
NOCHANGELOG

fix tick filter display

---

python_modules/dagster/setup.py

Summary:
Since watchdog 5 broke us, add a pin to prevent watchdog 6 someday from potentially breaking us.
Test Plan: BK

Add a watchdog<6 pin

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_condition_evaluations.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_result_value_hash.py

The goal here is to make the implementations of these conditions simpler, such that it is less daunting to copy/paste/modify. Building up an "intermediate layer" of AutomationConditions which do common / important tasks (e.g. being true if a parent is updated) is an important piece of the overall puzzle. These composite conditions roughly map to "AutoMaterializeRules" in the old world. The advantage is just that these are composed of simpler parts, which can be inspected if desired, and modified at will.
The most controversial name here is probably "since_last_handled". Very open to other suggestions there.

[DA] Refactor `eager` and `on_cron`

---

docs/docs-beta/docs/dagster-plus/insights/asset-metadata.md

Refresh and port the asset metadata in insights docs page
The new doc is at https://dagster-docs-beta-kzz25pif0-elementl.vercel.app/dagster-plus/insights/asset-metadata.
TODOs:
- add insights UX images added.
- link back to the insights home doc [for examples of non-custom metrics](https://github.com/dagster-io/dagster/pull/24027#discussion_r1737166614)
NOCHANGELOG

[docathon] Asset metadata in Insights

---

examples/experimental/dagster-airlift/dagster_airlift/mwaa/auth.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_mwaa_auth.py
examples/experimental/dagster-airlift/examples/mwaa-example/mwaa_example/definitions.py

Users need more flexibility when controlling auth and session configuration. Therefore we're making `MwaaSessionAuthBackend` parameterizable with a full session object. The old `__init__` is available for convenience in the static method `for_local`.
BK
NOCHANGELOG

Allow explicit mwaa client to be passed into MwaaSessionAuthBackend

---

pyright/master/requirements-pinned.txt
pyright/master/requirements.txt
python_modules/libraries/dagster-powerbi/dagster_powerbi/__init__.py
python_modules/libraries/dagster-powerbi/dagster_powerbi/translator.py

Builds out a very barebones translator class to build specs for PowerBI assets.
The structure of this translator is slightly different than our existing ones, curious for feedback. Instead of implementing many functions to define each property of an asset, it has a single function that returns an asset spec (which calls out to other functions for each object type).
The user also supplies a translator class rather than a translator instance. The ontology in this model is:
- A translator class defines the logic for how to translate API data into asset specs.
- A user can subclass a translator class to override or customize this logic.
- An instance of a translator class represents a translation "session," provided with any global context information (`PowerBIWorkspaceData`, in this case).
- …

[2/n][dagster-powerbi] scaffold DagsterPowerBITranslator class

---

docs/docs-beta/src/styles/custom.scss

The basic issue is that there's just too much text to fit in a single line. The previous css made it so that each individual box would get squished, which was pretty ugly. This just lets the breadcrumbs wrap into a second line, which looks a bit better.
NOCHANGELOG

DOC-385 Fix odd breadcrumb rendering

---

examples/experimental/dagster-airlift/dagster_airlift/core/sensor.py

We need to make airlift work on pre 1.8 for some early design partners. This does that by not using target on sensor.
Because of bug [here](https://linear.app/dagster-labs/issue/FOU-376/make-airflow-polling-sensor-work-with-asset-selection=) we need to use `AssetsSelection.assets()` rather than "*".
BK
NOCHANGELOG

Use asset_selection instead of target in airlift polling sensor

---

docs/docs-beta/src/styles/custom.scss
docs/docs-beta/src/styles/theme-dark.scss
docs/docs-beta/src/styles/theme-globals.scss
docs/docs-beta/src/styles/theme-light.scss

Adds search styles, but does not actually add Search. Once Search is configured it'll look like this.

Docathon -- Add Search Styles

---

python_modules/libraries/dagster-powerbi/dagster_powerbi/translator.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_translator.py

Implements base `DagsterPowerBITranslator` logic to convert API response dicts into asset specs for the four major content types: dashboards, reports, semantic models (fka datasets), and data sources.
Unit test that asset specs match expected values.

[4/n][dagster-powerbi] implement base DagsterPowerBITranslator spec generation

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx
js_modules/dagster-ui/packages/ui-core/src/search/useIndexedDBCachedQuery.tsx

Only a couple call sites using this hook and they were using the performance tracking APIs directly. Lets move this into the hook so that callers don't need to think about it.
NOCHANGELOG

Make useIndexedDBCachedQuery integrate with performance tracking.

---

docs/docs-beta/docs/dagster-plus/saved-views.md
docs/docs-beta/sidebars.ts

Adds a page describing catalog views, how to manipulate them, and potential use-cases.
https://dagster-docs-beta-g3ci1gizo-elementl.vercel.app/dagster-plus/saved-views
`NOCHANGELOG`

[DOC-372] Saved views guide

---

python_modules/libraries/dagster-powerbi/dagster_powerbi/resource.py
python_modules/libraries/dagster-powerbi/dagster_powerbi/translator.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/conftest.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/pending_repo.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_asset_specs.py

In response to feedback on asset caching apis in #23341, uses cacheable assets definitions to ensure that PowerBI data is only fetched from the API once. Once we settle on more agreeable asset caching apis, we can improve the ergonomics here.
New unit test to load a repo and launch runs without re-fetching data from PowerBI APIs.

[6/n][dagster-powerbi] use asset caching logic for powerbi assets

---

examples/docs_beta_snippets/docs_beta_snippets_tests/test_all_files_load.py

Omits files that call `setuptools.setup()` in them. This is because `setup()` calls a `distutils` function that tries to parse the command line of the command that resulted in `setup` being called. In the case of this test suite, it's a `pytest` command, which is not what `distutils` expects, do it raises an error.
`NOCHANGELOG`

fix docs-beta-tests

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_instance.py
examples/experimental/dagster-airlift/dagster_airlift/core/utils.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_dag_asset_keys.py

Preprocesses DAG ids to ensure they comply with allowed Dagster chars.
unit test of DagInfo key, new integration test which previously failed
`NOCHANGELOG`

[airlift] allow DAG names with hyphens

---

docs/docs-beta/docs/dagster-plus/deployment/hybrid/architecture.md
docs/docs-beta/docs/dagster-plus/deployment/hybrid/tokens.md
docs/vale/styles/config/vocabularies/Dagster/accept.txt

Port the existing hybrid agent docs to Dagster+. Mostly a copy paste job but removed some extraneous stuff and cleaned up the formatting.
NOCHANGELOG

[docathon] Port hybrid architecture doc

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py
examples/experimental/dagster-airlift/dagster_airlift/core/utils.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_build_defs.py

Fix the name sanitization process when creating node defs.
Adds a test of a declared mapping between asset and dag with hyphenated name, and conversion.

[dagster-airlift] fix name sanitization

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_build_defs.py

When creating multiple asset definitions for the same task, we need to make sure that node names are unique and reproducible. We actually already have a mechanism for creating a unique identifier from a list of asset keys (deterministic ordering), so just use that.

[dagster-airlift] unique node names

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_build_defs.py

This is how we perform the conversion for inputs/outputs, and I think we should match that.

[dagster-airlift] conform asset key to node name conversion to match the rest of the codebase

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py
examples/experimental/dagster-airlift/dagster_airlift/core/utils.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_build_defs.py

We attempt to retrieve the task name off of the node name, and end up with a mismatch because of the added unique identifier. Instead, use a generic name that doesn't fire the convention.
Previously, assetspecs which were not mapped to tasks but passed into the builder weren't getting coerced, and this would cause errors at repo load time.
Add testing for the latter problem, and change existing tests for the former.

[dagster-airlift] fix cacheableasset bugs

---

js_modules/dagster-ui/packages/ui-core/src/app/FeatureFlags.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/app/useVisibleFeatureFlagRows.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationDefinitionsNav.tsx
js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationOverviewRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/CodeLocationNotFound.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceRoot.tsx

Behind a feature flag, plug in the new Code Location pages at `/location/:repoPath/...`.
With flag disabled, click around from `/locations` to various code locations and verify correct routing and behavior throughout, including clicking to individual jobs, schedules, etc.
With flag enabled, verify same. Verify that the new overview page is the new destination when clicking into a code location, and that the "Definitions" tab behaves correctly.
`NOCHANGELOG`
No changelog because this is flagged for now and not quite ready for people to use.

[ui] Plug in new code location pages behind a flag

---

js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillRow.tsx
python_modules/dagster-graphql/dagster_graphql/schema/backfill.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_partition_backfill.py

Could not cancel runs from a backfill - forced users to search on the runs page and cancel from there.
Added a BK test for the `cancelableRuns` field.
Sanity checked with a test run.
* Fixed a bug where in-progress runs from a backfill could not be terminated from the backfill UI.

fix backfill run termination

---

js_modules/dagster-ui/packages/ui-core/src/app/UserSettingsDialog/UserSettingsDialog.tsx

Used the setting
[ui] Added an option under user settings to clear client side indexeddb caches as an escape hatch for caching related bugs.

Add user settings for clearing indexeddb caches

---

js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceRoot.tsx

This shouldn't be imported from `shared`, vscode just auto-added it that way.
Load Plus app, verify that the error is gone.
`NOCHANGELOG`

[ui] Fix CodeLocationNotFound import path

---

js_modules/dagster-ui/packages/eslint-config/.eslintrc.js
js_modules/dagster-ui/packages/eslint-config/rules/__tests__/missing-graphql-variables-type.test.js
js_modules/dagster-ui/packages/eslint-config/rules/__tests__/no-apollo-client.js
js_modules/dagster-ui/packages/eslint-config/rules/__tests__/no-react-router-route.test.js
js_modules/dagster-ui/packages/eslint-config/rules/index.js
js_modules/dagster-ui/packages/eslint-config/rules/missing-graphql-variables-type.js
js_modules/dagster-ui/packages/eslint-config/rules/no-apollo-client.js
js_modules/dagster-ui/packages/eslint-config/rules/no-oss-imports.js
js_modules/dagster-ui/packages/eslint-config/rules/no-react-router-route.js
js_modules/dagster-ui/packages/eslint-config/util/findRelativeImportPath.js
js_modules/dagster-ui/packages/ui-core/src/apollo-client/index.tsx
js_modules/dagster-ui/packages/ui-core/src/app/__tests__/analytics.test.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/AssetPartitions.test.tsx
js_modules/dagster-ui/packages/ui-core/src/hooks/__tests__/useQueryAndLocalStoragePersistedState.test.tsx
js_modules/dagster-ui/packages/ui-core/src/hooks/__tests__/useQueryPersistedState.test.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/backfill/__stories__/BackfillPage.stories.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/backfill/__tests__/BackfillLogsTab.test.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/backfill/__tests__/BackfillPage.test.tsx

Adds a lint rule to disallow importing Route directly from react-router-dom. Instead it should be imported from our custom Route component that wraps the one from react-router-dom
jest test + ran `yarn lint --fix` which created the updated imports in this PR
NOCHANGELOG

Add lint rule to disallow importing Route from react-router-dom

---

examples/experimental/dagster-airlift/dagster_airlift/in_airflow/dagster_operator.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/gql_queries.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/mark_as_migrating.py
examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/operator_test_project/dags/migrated_dag.py

Genericizes session auth for dagster operator.
Conflicted on whether we should fully genericize the `launch_runs_for_task` method for now. I think it's fine to have a default implementation personally for now and see how needs evolve, since it can be overridden.

[dagster-airlift][rfc] genericize dagster operator

---

python_modules/dagster/dagster/_core/definitions/multi_asset_sensor_definition.py

Uses a fetch batch limit of 1000, to prevent overfetching.
The last vestige of framework calls to `get_event_records`.
BK
* Changed data fetching in the multi-asset sensor definition to be less likely to timeout queries against the asset history storage.

switch get_event_records => fetch_materializations for multi asset sensors (#22779)

---

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/dlt/asset_decorator.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/dlt/translator.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/dlt_tests/test_asset_decorator.py

Add support `AutomationCondition` in `DagsterDltTranslator`.
Inspired by the implementation in `dagster-dbt`:
https://github.com/dagster-io/dagster/blob/9b9b96842bad988e9173ab2afca8748ad3bc43aa/python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py#L432-L488
https://github.com/dagster-io/dagster/blob/9b9b96842bad988e9173ab2afca8748ad3bc43aa/python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py#L829-L831
[Added tests](https://github.com/aksestok/dagster/blob/3e8cb2eb2ebc39cbcfba48e043a5d19748345558/python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/dlt_tests/test_asset_decorator.py#L155-L190).
> [dagster-dlt] Added support for `AutomationCondition` using `DagsterDltTranslator.get_automation_condition()` (thanks, …

[dagster-embedded-elt][dlt] Support `AutomationCondition`

---

examples/experimental/dagster-airlift/Makefile
examples/experimental/dagster-airlift/scripts/mirror_tutorial.sh
examples/experimental/dagster-airlift/setup.py

Adds an additional makefile command which will run entire release process off of master and create a new branch to increment pypi version.
The release process:
- Ensure we're on master so we can get a reproducible release
- Run adhoc_pypi commands to release to pypi
- Run mirror_tutorial script to mirror tutorial to github repo
- Create a new branch called airlift-<release_num> which increments airlift version
- Push branch to remote
- go back to master
Tested this by upgrading pypi. Took a few tries to get everything working hence 0.0.21.
You can try this out by running `make adhoc_release`
Also includes https://github.com/dagster-io/dagster/pull/24187.

[dagster-airlift] 0.0.21 and revamped release process

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_cli_invocation.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resource.py
python_modules/libraries/dagster-sdf/dagster_sdf/sdf_cli_invocation.py

Summary:
This is currently set to only 2 seconds which is very tight - you could imagine cleanly terminating a running dbt process that is doing a bunch of stuff taking a lot longer. Increase the default and make it configurable via env var.
Test Plan: Terminate a running dbt job, watch it still finish
[dagster-dbt] Increased the default timeout when terminating a run that is running a `dbt` subprocess to wait 25 seconds for the subprocess to cleanly terminate. Previously, it would only wait 2 seconds.
[dagster-sdf] Increased the default timeout when terminating a run that is running an `sdf` subprocess to wait 25 seconds for the subprocess to cleanly terminate. Previously, it would only wait 2 seconds.

increase default value of DAGSTER_DBT_TERMINATION_TIMEOUT_SECONDS and make it configurable

---

js_modules/dagster-ui/packages/ui-core/src/partitions/DimensionRangeInput.tsx

As titled fixes a bug where the selection input keeps resetting. This is due to partition health data being fetched serially for many assets. As each asset comes in that constrains the available partitions to select from which changes the available values for the input. The problem is that, in the case were looking at, every asset has the same partition definition, so we end up creating a new values array which triggers the `useEffect` that resets the text input, however the values array is a new reference but otherwise it has the exact same values. To get around this issue I'm json.stringifying the values array same as we already do to the partition names array (for the same reason I suspect).
Used app-proxy to make sure the repro from …

Fix time range partition selection input resetting when partition health data updates

---

docs/content/concepts/automation/schedules/automating-assets-schedules-jobs.mdx

The documentation at https://docs.dagster.io/concepts/automation/schedules/automating-assets-schedules-jobs is incomplete with `define_asset_job` and `ScheduleDefinition` missing from the step 3 code summary.
N/A
NOCHANGELOG

[Docs] Fix automating-assets-schedules-jobs

---

python_modules/dagster/dagster/_api/snapshot_partition.py
python_modules/dagster/dagster/_core/remote_representation/code_location.py
python_modules/dagster/dagster/_core/remote_representation/external.py
python_modules/dagster/dagster/_grpc/impl.py
python_modules/dagster/dagster/_grpc/server.py
python_modules/dagster/dagster/_grpc/types.py
python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_partition.py

We discovered that backcompatibility for the single-implicit-asset-job change is actually a three-body problem, between the host processes, agent, and user code processes:
- It's now possible for a job to target asset definitions with different `PartitionsDefinitions`
- You need a `PartitionsDefinition` to resolve the run tags for a given partition
- This means that, to get the run tags corresponding to a particular partition, you need to know what assets the run is targeting
- Jobs can be assigned custom functions that determine run tags for a partition
- These custom functions mean that, at least sometimes, there needs to be a gRPC to the user code process to resolve the tags for a partitioned run
- Currently, we always gRPC to the user code process to resolve the tags for a partitioned …

avoid gRPCs when resolving partition tags for implicit asset jobs

---

python_modules/dagster-graphql/dagster_graphql/implementation/external.py
python_modules/dagster-graphql/dagster_graphql_tests/client_tests/test_shutdown_repository_location.py
python_modules/dagster/dagster/_core/execution/asset_backfill.py
python_modules/dagster/dagster/_core/test_utils.py
python_modules/dagster/dagster/_core/workspace/context.py
python_modules/dagster/dagster/_core/workspace/workspace.py
python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster/_daemon/sensor.py
python_modules/dagster/dagster/_daemon/workspace.py
python_modules/dagster/dagster/_scheduler/scheduler.py
python_modules/dagster/dagster_tests/core_tests/workspace_tests/test_request_context.py
python_modules/dagster/dagster_tests/daemon_sensor_tests/test_pythonic_resources.py
python_modules/dagster/dagster_tests/daemon_sensor_tests/test_run_status_sensors.py
python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
python_modules/dagster/dagster_tests/daemon_tests/conftest.py
python_modules/dagster/dagster_tests/scheduler_tests/conftest.py
python_modules/dagster/dagster_tests/scheduler_tests/test_pythonic_resources.py
python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py

Summary:
- Paves the way to use a WorkspaceSnapshot object with the entries in it in a way that is not extremely confusing.

[1/n] rename get_workspace_snapshot() to get_code_location_entries()

---

examples/experimental/dagster-airlift/examples/tutorial-example/README.md
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/airflow_dags/custom_proxy.py

Add a section on custom auth to the tutorial. This could be genericized for sure since there are other potential uses for a subclass of the proxy, but to keep it use-case driven.

[dagster-airlift] tutorial auth

---

python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

add a test case that fails if you forget to filter asset check executions by asset key

---

pyright/master/requirements-pinned.txt
scripts/run-pyright.py

The `uv` cache can cause subtle problems sometimes when rebuilding pyright environments. Rebuilding envs without using the cache can fix an apparently intractable problem. This PR adds `--no-cache` as an arg to `run-pyright.py`. This is intended for rare use as an escape hatch for pyright env problems-- it makes rebuilding the envs much more slow.
See this issue I posted over at `uv` for some info about why you might want to use this: https://github.com/astral-sh/uv/issues/7028
My pyright was (unresolvable imports for all dagster packages). After rebuilding my env with `--no-cache` the problem went away. The issue was that the cache seemed to be holding `pth` files for our dagster editables that did not respect `editable_mode=compat` and were incorrectly formatted for pyright.
NOCHANGELOG

Add --no-cache option to run_pyright script

---

python_modules/dagster/dagster/_core/pipes/subprocess.py

Summary:
2 seconds is pretty tight if there is any non-trivial signal handling going on in the subprocess to gracefully clean things up. This PR bumps it up to 20 seconds so that it's still below the default termination grace period on ECS and k8s.
Test Plan: BK

increase default pipes subprocess termination timeout

---

docs/content/dagster-plus/deployment/agents/amazon-ecs.mdx
docs/content/deployment/run-monitoring.mdx

Dagster+ users get confused by the instruction to enable Run Monitoring as the doc is specific to OSS.
👀
NOCHANGELOG

[docs] indicate Run Monitoring enabled by default in Dagster+

---

docs/content/concepts/automation/declarative-automation.mdx

[AutomationCondition API docs](https://docs.dagster.io/_apidocs/assets#dagster.AutomationCondition) use .on_cron()
👀
NOCHANGELOG

[docs] update mentions of ".cron()" to ".on_cron()"

---

examples/experimental/dagster-airlift/dagster_airlift/core/sensor.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/utils.py
python_modules/dagster/dagster/_core/definitions/sensor_definition.py
python_modules/dagster/dagster_tests/definitions_tests/test_sensor_invocation.py

When a sensor targets an `asset_selection` (as opposed to a job, which is always targeted when using any other targeting param, including `target`), any `RunRequest` produced by its eval function undergoes an extra step of processing, where it is turned into a `RunRequest` targeting a base asset job.
This extra processing sets `asset_selection` on the new `RunRequest` if it is not already set. Prior to this PR, the check for it already being set was ignoring an `[]` value (since this is false in booleans). This was causing the `asset_selection` on the `RunRequest` to be reset to the `asset_selection` for the entire sensor, which is incorrect. Also, checking for unexpected asset check keys (keys not part of the match the sensor asset selection subset) was not being done.
This PR:
- Changes …

[bugfix] Fix asset selection and asset check selection handling on sensor RunRequests

---

pyright/master/requirements-pinned.txt
scripts/install_dev_python_modules.py

After wiping my pyright & base virtual envs, I was unable to get pyright working, hitting [strange errors that dagster imports were not found](https://dagsterlabs.slack.com/archives/C03A0D72A6T/p1724874346772169):
```python
/Users/ben/repos/dagster/python_modules/libraries/dagster-shell/dagster_shell/__init__.py:
1:5: Import "dagster._core.libraries" could not be resolved (reportMissingImports)
```
Some Googling turned up that there are [multiple ways to install editable packages](https://github.com/astral-sh/uv/issues/3898) & the default behavior of `uv pip install` is to not install packages in compat mode, which pyright requires.
We [explicitly opt in in our pyright venv building code](https://github.com/dagster-io/dagster/blob/master/scripts/run-pyright.py#L304), but I'm wondering if …

use compat mode when uv installing editable packages in make dev_install

---

python_modules/dagster/dagster/_core/storage/db_io_manager.py
python_modules/dagster/dagster_tests/storage_tests/test_db_io_manager.py
python_modules/libraries/dagster-duckdb-pandas/dagster_duckdb_pandas_tests/test_type_handler.py
python_modules/libraries/dagster-gcp-pandas/dagster_gcp_pandas_tests/bigquery/test_type_handler.py
python_modules/libraries/dagster-snowflake-pandas/dagster_snowflake_pandas_tests/test_snowflake_pandas_type_handler.py
python_modules/libraries/dagster-snowflake-pyspark/dagster_snowflake_pyspark_tests/test_snowflake_pyspark_type_handler.py

Automatically populate `dagster/relation_identifier` metadata on assets which are emitted by a DbIOManager.
This should hopefully make it easier to pull data from Dagster into external catalogs.
Unit tests.
`dagster/relation_identifier` metadata is automatically attached to assets which are stored using an IO manager.

[io managers] Add dagster/relation_identifier metadata to IO Manager outputs

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_all_snapshot_ids.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_assets.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_solids.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
python_modules/dagster/dagster/_core/definitions/asset_graph.py
python_modules/dagster/dagster/_core/definitions/asset_spec.py
python_modules/dagster/dagster/_core/definitions/decorators/decorator_assets_definition_builder.py
python_modules/dagster/dagster/_core/definitions/utils.py
python_modules/dagster/dagster/_core/storage/tags.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py
python_modules/dagster/dagster_tests/definitions_tests/test_utils.py

Introduces a `kinds` property to `AssetSpec`, a set of strings representing compute, storage etc kinds, based on https://github.com/dagster-io/internal/discussions/10821#discussioncomment-10353301. These kinds are backed by specially constructed tags of the form `dagster/kind/python`, `dagster/kind/snowflake` which canonically have empty `""` values.
Right now, we expect these tags to be only set by internal Dagster code (e.g. integrations). A subsequent, stacked PR (#24154) introduces a top-level `kinds` parameter, which is immediately converted to this special tag format.
Unit tests.

Introduce `kinds` backed by asset spec tags

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNode.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/types/AssetNode.types.ts
js_modules/dagster-ui/packages/ui-core/src/asset-graph/types/useAssetGraphData.types.ts
js_modules/dagster-ui/packages/ui-core/src/assets/AssetTableFragment.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetNodeDefinition.types.ts
js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetTableFragment.types.ts
js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetView.types.ts
js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetsCatalogTable.types.ts
js_modules/dagster-ui/packages/ui-core/src/graph/KindTags.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedAssetRow.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/types/WorkspaceAssetsQuery.types.ts

Begin moving from compute kinds to kinds by requesting the list of kinds from GraphQL (introduced in #24154, a superset of the compute kind) and then displaying those in place of the compute kind tags in the asset graph and asset list.
`NOCHANGELOG`

[1/k][ui] Pull, display generic kinds in place of compute kind

---

examples/experimental/dagster-airlift/dagster_airlift/constants.py
examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py
examples/experimental/dagster-airlift/dagster_airlift/core/dag_defs.py
examples/experimental/dagster-airlift/dagster_airlift/core/defs_builders.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor.py
examples/experimental/dagster-airlift/dagster_airlift/core/utils.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/base_proxy_operator.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_dag_defs.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_migrating_e2e.py

Removes a core import from in_airflow. Gets rid of relative pathing along the way.

[dagster-airlift] move tags to a neutral location

---

docs/sphinx/_ext/dagster-sphinx/dagster_sphinx/__init__.py

This was a fun one. Essentially, a class __dict__ returns none when `__doc__` is called, eg. with `obj.__doc__`. Instead, you can assert that docs exist with `hasattr`. This was causing PipesContext and other classes to erroneously report no documentation.
Was getting these odd messages in Sphinx:
```
Docstring not found for object.__dict__. All public methods and properties must have docstrings.
Docstring not found for object.__enter__. All public methods and properties must have docstrings.
Docstring not found for object.__exit__. All public methods and properties must have docstrings.
Docstring not found for object._instance. All public methods and properties must have docstrings.
Docstring not found for object._write_message. All public methods and properties must have docstrings. …
```

[sphinx] fix: check_public_method_has_docstring bug with mappingproxy type

---

python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/storage/event_log/base.py
python_modules/dagster/dagster_tests/storage_tests/test_run_storage.py
python_modules/dagster/dagster_tests/storage_tests/utils/run_storage.py
python_modules/libraries/dagster-mysql/dagster_mysql_tests/test_run_storage.py
python_modules/libraries/dagster-postgres/dagster_postgres_tests/test_run_storage.py

Summary:
For storages that do the run updating in the same transaction as storing the event, this prevents handle_run_event from being called twice - once in store_event
Test Plan: BK, currently a no-op since it always returns False

Add a "handles_run_events_in_store_event" property to EventLogStorage, check it when handling new events

---

python_modules/automation/tox.ini

This PR adds the dagster-tableau dependency to the automation tox suite instead of excluding it in #24248. Fixes the build.
BK

fix: add dagster-tableau to automation tox suite dependencies

---

python_modules/dagster/dagster/_core/definitions/asset_spec.py
python_modules/dagster/dagster/_core/definitions/utils.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py
python_modules/dagster/dagster_tests/definitions_tests/test_asset_spec.py

See changelog
The `AssetSpec` constructor now raises an error if an invalid group name is provided, instead of an error being raised when constructing the `Definitions` object.

validate group name in AssetSpec

---

examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/conftest.py

This syntax is not supported in python 3.8
NOCHANGELOG

[dagster-airlift] Fix airlift test on 3.8

---

python_modules/libraries/dagster-k8s/dagster_k8s/pipes.py
python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_pipes.py

Summary:
Restrict additional characters in addition to just underscores (most notably, capital letters, but other non-alphanumeric characters as well).

Improve k8s pipes pod name sanitization

---

python_modules/libraries/dagster-powerbi/dagster_powerbi/resource.py
python_modules/libraries/dagster-powerbi/dagster_powerbi/translator.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_asset_specs.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_translator.py

[dagster-powerbi] add ability to reload semantic models

---

docs/sphinx/_ext/dagster-sphinx/dagster_sphinx/configurable.py
docs/sphinx/_ext/sphinx-mdx-builder/sphinxcontrib/mdxbuilder/writers/mdx.py
docs/sphinx/conf.py

Adds additional node types of the Sphinx MDX writer. This now runs without errors on all our existing RST files, meaning we can generate MDX from RST. 
The MDX files themselves are not ready yet, they will error if you try to load them into Docusaurus. More fixes will come to that in a future PR.
Lots of local testing and previews

[sphinx] Add additional node types to the MDX writer

---

examples/temp_pins.txt
python_modules/dagster/setup.py
python_modules/libraries/dagster-datahub/setup.py

pydantic 2.9.0 (released 2024-09-05) introduces some breaking changes causing 
| `TableMetadataSet` is not fully defined; you should define `TableColumn`, then call `TableMetadataSet.model_rebuild()`.
pinning to <2.9.0 should fix this
existing tests

pin pydantic < 2.9.0

---

python_modules/dagster/dagster/_core/definitions/metadata/metadata_set.py
python_modules/dagster/dagster/_core/definitions/metadata/table.py

Remove forward imports in a failed attempt to fix pydantic 2.9 complaints

Remove forward imports in failed attempt to fix Pydantic 2.9 error

---

docs/content/guides/migrations.mdx
docs/content/guides/migrations/observe-your-airflow-pipelines-with-dagster.mdx

This PR adds a link for the Airflow + Pipes guide to the Migration guides page.
NOCHANGELOG

[docs] - Add link to Migration guides page

---

python_modules/dagster/dagster/_serdes/serdes.py
python_modules/dagster/dagster_tests/general_tests/test_serdes.py

The added test fails before the change, and succeeds after. The basic issue is that sub-fields of invalid fields can also be invalid, so we need to recurse into the object in order to avoid errors.
NOCHANGELOG

Fix deserialization of ignored invalid fields

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py
examples/experimental/dagster-airlift/dagster_airlift/core/airflow_instance.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/base_proxy_operator.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/mark_as_migrating.py
examples/experimental/dagster-airlift/dagster_airlift/migration_state.py
examples/experimental/dagster-airlift/dagster_airlift/test/airflow_test_instance.py
examples/experimental/dagster-airlift/dagster_airlift/test/shared_fixtures.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/in_airflow_tests/test_mark_as_dagster_migrating.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_migrating_e2e.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/unit_tests/test_proxy_operators.py

Switches out the tag descriptor to instead use variables for cross-process communication. 
Tags in mwaa have a 1224 char size limit; for large dags, we likely won't be able to fit migration state.
Instead, use airflow variables, which don't have a fixed size limit, and can be queried via the rest api. 
Variables don't have _no_ size limit however, they're stored in a KV store in airflow's metadata database, and are therefore limited by the maximum row size for the database backend. I think this should be more than enough for our needs, although for large numbers of dags it's possible the bulk fetch of variables that we do at the start of caching could be very expensive.
Switched the unit testing to mock out airflow's variables, and ensure that variables are set under the correct …

[dagster-airlift][rfc] use airflow variables to communicate migration state

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py
examples/experimental/dagster-airlift/dagster_airlift/core/airflow_instance.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/base_proxy_operator.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/mark_as_migrating.py
examples/experimental/dagster-airlift/dagster_airlift/migration_state.py
examples/experimental/dagster-airlift/dagster_airlift/test/airflow_test_instance.py
examples/experimental/dagster-airlift/dagster_airlift/test/shared_fixtures.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/in_airflow_tests/test_mark_as_dagster_migrating.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_migrating_e2e.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/unit_tests/test_proxy_operators.py

After the change to make dags marked as migrating via a variable, I was missing the visual indicator that the dag has been "marked". I think making it explicit via a dag is a good step of building trust.
Added some additional unit test lines for this.
`NOCHANGELOG`
Here's what it looks like:

[dagster-airlift] tag dags as migrating

---

examples/experimental/dagster-airlift/dagster_airlift/constants.py
examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py
examples/experimental/dagster-airlift/dagster_airlift/core/dag_defs.py
examples/experimental/dagster-airlift/dagster_airlift/core/defs_builders.py
examples/experimental/dagster-airlift/dagster_airlift/core/utils.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/base_proxy_operator.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/gql_queries.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/conftest.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_build_defs.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_dag_defs.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_utils.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_migrating_e2e.py

Airflow dag/task ids can go over our 63 character limit for tags. Instead, move to checking metadata.
Updated all callsites and unit tests. Ran dbt-example successfully.
`NOCHANGELOG`

[dagster-airlift] use metadata instead of tags

---

examples/temp_pins.txt
python_modules/dagster/setup.py
python_modules/libraries/dagster-datahub/setup.py

This reverts commit 0875c0b3ca05938e7c81ffb32578ec711c0ce2eb.

Revert "pin pydantic < 2.9.0 (#24258)", replace with pydantic < 2.10.0

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/resource.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resource.py

Addresses https://github.com/dagster-io/dagster/issues/23906
Added a unit test that asserts that the cli is able to parse the project, even when `DBT_PROJECT_DIR` contains a nonexistent path.
When instantiating `DbtCliResource`, the `project_dir` argument will now override the `DBT_PROJECT_DIR` environment variable if it exists in the local environment.

feat(dbt): use `project_dir` to override the `DBT_PROJECT_DIR` environment variable

---

python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py

For some dbt data platforms the database is none. This change reduces the `relation_name` to `schema.alias` when `database.schema.alias` is not possible.
Resolves https://github.com/dagster-io/dagster/issues/23047
In my local dagster + dbt setup.
[dagster-dbt] account for no database

fix(dbt): account for no database

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_ticks.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py

Returning unfiltered tick statuses.
BK

respect tick status filters in batch loaded sensors

---

examples/assets_dbt_python/assets_dbt_python/definitions.py

- Fixed missing asset `raw_data_assets` in definitions for `assets_dbt_python` example
- `raw_data_assets` was imported in `definitions.py` but was not included in the definitions assets
- Loaded `raw_data_assets` example locally
- [examples] Fixed missing assets in `assets_dbt_python` example

Fix assets_dbt_python example definitions

---

js_modules/dagster-ui/packages/ui-core/src/runs/AssetTagCollections.tsx

On the run page, if you hover over "N assets", you see these labels:
I think "View downstream lineage" is misleading, and it should just be "View lineage"

on run page, fix misleading lineage label

---

js_modules/dagster-ui/packages/ui-core/src/overview/OverviewTimelineRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/overview/useGroupTimelineRunsBy.tsx

- Added groupBy query param in URL to help track how many people group by job vs. automation
- Linear: https://linear.app/dagster-labs/issue/FE-526/can-we-track-the-state-of-this-toggle-in-the-url-somehow
1. On local, navigated to `/overview/activity/timeline` page and ensured URL changed to add query param (?groupBy=job)
2. On local, navigated to `/overview/activity/timeline` page and changed Group by selector and ensured query param in URL changed accordingly
[ui] Added a feature that adds a query param (?groupBy=) on the Timeline Overview page based on the Group by selector

Add group by query param on timeline overview

---

js_modules/dagster-ui/packages/ui-core/src/search/BuildAssetSearchResults.tsx
js_modules/dagster-ui/packages/ui-core/src/ui/Filters/useAssetTagFilter.tsx

Filters out the set of kind tags from the list of tags that the user can filter, and the list of tags that show up in the Catalog page categories, since these are represented by separate kinds filters and section, respectively.

[3/k][ui] Hide kind tags from search results, filter list

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeOverview.tsx
js_modules/dagster-ui/packages/ui-core/src/graph/KindTags.tsx

Adds a new collapsible "system tags" section to the tags pane in the asset sidebar. This is used currently solely for kind tags, which are hidden by default.

[4/k][ui] Hide kind tags by default from asset view

---

docs/docs-beta/README.md
docs/docs-beta/docs/intro.md
docs/docs-beta/src/components/Cards.tsx
docs/docs-beta/src/components/CodeExample.tsx

fix master beta docs build:
- fixed broken link (seems an oversight intro'ed from https://github.com/dagster-io/dagster/pull/24267)
- ran `yarn lint`, `yarn build`
`yarn build` passes
- before: https://vercel.com/elementl/dagster-docs-beta/8XXsNCL1WTPyenbCKJtCH1YaxBsy?filter=errors
```
Exhaustive list of all broken links found:
- Broken link on source page path = /:
-> linking to /tutorial/quick-start
```
- after: https://vercel.com/elementl/dagster-docs-beta/ARCKGoxukSyZt1wvM1aGqJ9fsHXk is green and https://dagster-docs-beta-4qfhiknub-elementl.vercel.app/ builds
`NOCHANGELOG`

fix beta docs build

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py

Gives us kind tags on airflow assets even before migration starts (when this status is empty)

[dagster-airlift] display airflow kind on assets when no recorded migration state

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/asset_defs.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/test_asset_defs.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/test_load_from_instance.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/test_load_from_project.py

Fixes [DS-417](https://linear.app/dagster-labs/issue/DS-417/avoid-name-collisions-for-dagster-airbyte-assets)
This PR updates the Airbyte assets naming template to include the full connection ID. Previously, we were truncating the connection ID to keep only the first 5 characters in the asset name, which created name collisions for some users.
Updated tests + BK
Bug:
[dagster-airbyte] Update the Airbyte asset naming template to include the full connection ID, avoiding name collisions.

[fix] Update Airbyte assets to avoid name collisions

---

docs/sphinx/Makefile

- Install `sphinx-mdx-builder` in `make install`
- Rename `copy_mdx` to `mdx_copy`
NOCHANGELOG

[sphinx-mdx-build] install editible version locally with Makefile directive

---

docs/docs-beta/src/styles/custom.scss
docs/sphinx/_ext/sphinx-mdx-builder/sphinxcontrib/mdxbuilder/writers/mdx.py

Render inline flags coming from `dagster_sphinx` custom package.
NOCHANGELOG

[sphinx-mdx-builder] support inline flags

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/resource.py

I put the logging statement in https://github.com/dagster-io/dagster/pull/23615 in the wrong place.
N/A
NOCHANGELOG

chore(dbt): add logging if adapter is not created

---

python_modules/libraries/dagster-k8s/dagster_k8s/client.py
python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_client.py

This is meant to address https://github.com/dagster-io/dagster/issues/22453
Previously, if a pod was Evicted by the Kubelet or force deleted before initialization was finished, the `wait_for_pod` function would simply wait forever, forcing us to kill the job.
To solve this, we added a wait timeout loop specifically for the initial pod creation. As soon as the pod is "seen" for the first time by the Kubernetes API, we break out of that loop and continue to the main logic loop of waiting for pod readiness.
If at any point in that second loop the pod no longer exists, we know that it was unexpectedly deleted, and thus we need to raise an error so that the job doesn't hang indefinitely.
- Added unit tests 
- Ran successful jobs with these changes
- Killed pod on startup and confirmed that an …

[dagster-k8s] fix: Prevent job hang when Pod exits before init

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNode.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeOverview.tsx

Display an asset's kind tags in the sidebar, provided that the asset has at least one non-legacy-compute-kind tag.

[kinds] add kinds to asset sidebar

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_event_iterator.py
python_modules/libraries/dagster-dbt/dagster_dbt/core/resource.py

Summary:
Attempt to resolve https://github.com/dagster-io/dagster/issues/23952: Instead of attempting to import duckdb and logging a warning on importerror, do a bit of introspection on the relevant class and only try to import it if the class name matches.
Test Plan: could use some help with this from reviewers, I don't see any duckdb-specific tests in https://github.com/dagster-io/dagster/pull/21542

Gate duckdb-specific instance check in dagster-dbt in a way that doesn't require an import of a module that might not be present

---

js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationDefinitionsMain.tsx

Repair the `:name` param on the ops explorer in the new code location page.
View code location with ops, click on an op. Verify that it shows the details correctly.
NOCHANGELOG

[ui] Fix ops navigation in new code location defs page

---

docs/content/concepts/dagster-pipes/dagster-pipes-details-and-customization.mdx
docs/content/concepts/dagster-pipes/databricks.mdx
docs/dagster-university/pages/dagster-essentials/extra-credit/materialization-metadata.md
examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/dagster_pipes_details_and_customization/session_lifecycle_external.py

The class is "MaterializeResult" not MaterializationResult, this just fixes up some places that reference it incorrectly (noticed in the dagsterU lesson here: https://courses.dagster.io/courses/take/dagster-essentials/multimedia/48235027-materialization-metadata)

[docs] MaterializationResult should be MaterializeResult

---

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/sling_event_iterator.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/sling_tests/replication_configs/csv_to_sqlite_config/dataworks/Products.csv

Lowercases the column lineage and column schema column names for Sling for consistency and since in the UI we lowercase the names when we link them.
Unit test.

[sling] lowercase col names, deps

---

python_modules/dagster/dagster/_config/pythonic_config/resource.py
python_modules/dagster/dagster/_core/execution/context/init.py
python_modules/dagster/dagster_tests/core_tests/resource_tests/pythonic_resources/test_lifecycle_methods.py

Updates the implementation of `process_config_and_initialize`, a utility which we use to ready up configurable resources outside of the runtime context (e.g. to load assets from external tools). It now properly handles nested resources, and has a contextmanager variant to handle setup/teardown.

[resources] Ensure process_config_and_initialize handles nested resources, env vars properly

---

python_modules/libraries/dagster-azure/dagster_azure/adls2/io_manager.py

This PR adds the 'lease_duration' attribute to the ADLS2PickleIOManager 
This PR is a followup of #21150. The attribute 'lease_duration' is added to ADLS2PickleIOManager, so that it can be configured when the IO Manager is used as a dagster resource.
Successfully run dagster-azure test with 20 passed and 3 skipped.

Extend adls2 pickle io manager config

---

integration_tests/test_suites/k8s-test-suite/tests/test_utils.py
python_modules/libraries/dagster-k8s/dagster_k8s/client.py

follow-up to https://github.com/dagster-io/dagster/pull/24280 for internal integration tests that we dont run on external contributions 
tweaks an error to use the enum value instead of print the enum since the enum name in the message felt repetitive. 
bk

[dagster-k8s] test fixes

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/Sidebar.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphExplorerFilters.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/useAssetCatalogFiltering.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/graph/asyncGraphLayout.ts
js_modules/dagster-ui/packages/ui-core/src/pipelines/GraphNotices.tsx

- Export a new property `filteredAssetsLoading` from `useAssetCatalogFiltering` that is always False in OSS (client side filtering which happens synchronously so there is no "loading") and is true in cloud if catalog view filters or the elastic search filtering are loading.
- Use the property in the asset graph to display a shimmer / loading spinner.
Tested switching between catalog views, reloading the page. 
Tested with elastic search backend on and off.
https://github.com/user-attachments/assets/b11a99a7-262a-4e73-88ef-54c576a290ea
NOCHANGELOG

[1/n] Add shimmer + loading state to asset graph

---

examples/docs_beta_snippets/docs_beta_snippets/getting-started/hello-world.py
python_modules/dagster/dagster/_core/pipes/utils.py
python_modules/libraries/dagster-aws/dagster_aws/pipes/message_readers.py

Add ability to route logs to an arbitrary file instead of just `stdout` for `dagster-pipes` 
NOCHANGELOG

[dagster-pipes] allow routing logs to arbitrary files

---

docs/docs-beta/docs/guides/data-assets.md
docs/docs-beta/docs/guides/external-assets.md
examples/docs_beta_snippets/docs_beta_snippets/guides/data-assets/data-assets/asset_decorator.py
examples/docs_beta_snippets/docs_beta_snippets/guides/data-assets/data-assets/graph_asset_decorator.py

Improving examples, clarifying language.
NOCHANGELOG

[docs-beta] Update Define data assets

---

python_modules/dagster/dagster/_core/execution/context/system.py
python_modules/dagster/dagster/_core/pipes/context.py

This is a non-behavior-changing PR that refactors some methods within the internal execution context classes. This aim of this PR is to prepare for https://github.com/dagster-io/dagster/pull/23824, by centralizing the logic for getting the `PartitionsDefinition` for an execution.
Working on this made me aware of a behavioral weirdness that I think we should consider addressing in 1.9: `context.partition_keys` etc. will return a non-`None` value in steps that target no partitioned assets, if other steps in the same run do target partitioned assets.
NOCHANGELOG

refactor step context partition methods

---

docs/docs-beta/docs/guides/pipelines.md

Resolves:
```
Exhaustive list of all broken links found:
- Broken link on source page path = /guides/pipelines:
-> linking to /tutorial/installation
-> linking to /tutorial/quick-start
-> linking to /guides/dagster/define-data-assets
-> linking to /guides/dagster/create-asset-dependencies
-> linking to /guides/dagster/enrich-assets-with-metadata
-> linking to /guides/dagster/partition-assets
-> linking to /guides/dagster/represent-external-data-sources
```
NOCHANGELOG

[docs-beta] fix broken links in pipelines guide

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_instance.py
examples/experimental/dagster-airlift/dagster_airlift/core/defs_from_airflow.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor.py
examples/experimental/dagster-airlift/dagster_airlift/test/airflow_test_instance.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/conftest.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_sensor.py

- Batch requests to airflow rest API
- Move to an iteration model where we can pause iteration in the middle of processing (basically after processing step of any dag run) and restart gracefully
- Handle skipped tasks gracefully
- Stop iteration at 40 seconds to give adequate time for startup and teardown.
This nearly 10xes speed of sensor iteration, even on local where ipc cost is low. See https://gist.github.com/dpeng817/7979124e3286b1473aa57f252817b488

[dagster-airlift] sensor revamp

---

docs/docs-beta/docs/guides/partition-dependencies.md
docs/docs-beta/docs/guides/partitioning.md
docs/docs-beta/sidebars.ts
examples/docs_beta_snippets/docs_beta_snippets/guides/data-modeling/partitioning/static_partitioning.py
examples/docs_beta_snippets/docs_beta_snippets/guides/data-modeling/partitioning/time_based_partitioning.py

This PR cleans up the Partitioning guide and splits it into two pages: one for partitioning assets, one for defining dependencies.
@yuhan I know parts of this are still in the works - this PR is mostly for cleanup in the definition portion, and an RFC for the page split.
NOCHANGELOG

[doc-revamp] - Clean up partitioning guide

---

js_modules/dagster-ui/packages/ui-core/src/workspace/CodeLocationSource.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/__stories__/CodeLocationSource.stories.tsx

The CodeLocationSource button is stretching when rendered in a flex container. Wrap it in a div.
Created a storybook example to demo the different possibilities of the component.
Storybook

[ui] Fix CodeLocationSource in flex container

---

python_modules/dagster/dagster/_core/definitions/asset_spec.py
python_modules/dagster/dagster/_core/definitions/tags/__init__.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py
python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py
python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/dlt/asset_decorator.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/asset_decorator.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/dlt_tests/test_asset_decorator.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/sling_tests/test_asset_decorator.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_asset_defs.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_load_from_instance.py
python_modules/libraries/dagster-sdf/dagster_sdf/asset_decorator.py
python_modules/libraries/dagster-sdf/dagster_sdf/sdf_information_schema.py

Updates the Fivetran, dbt, sdf, and embedded-elt integrations to use `dagster/kind/xyz` tags in place of compute kind. In particular, brings back kinds for both storage & compute in the UI.
Updated unit tests.

Update integrations to use kind tags in place of storage kind

---

helm/dagster/templates/ingress.yaml

The 'PathType' field is missing from the ingress template for 'succeedingPaths' in 'dagsterWebserver' paths causing the helm deployment to fail if a 'succeedingPath'  has been declared in the input values file.
[Issue Link](https://github.com/dagster-io/dagster/issues/24420)
- Added the 'pathType' field to and re-deployed the helm chart without error.
- Confirmed that the resulting ingress resource was created successfully.

add 'pathType' field to 'dagsterWebserver' ingress

---

python_modules/dagster/dagster/_core/utils.py
python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_event_iterator.py
python_modules/libraries/dagster-dbt/dagster_dbt/core/utils.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/utils.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_asset_defs.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_load_from_instance.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/utils.py

Currently, we attach column schema information to Fivetran asset definitions [if provided by the API, but](https://fivetran.com/docs/rest-api/connectors#retrieveconnectordetails)
> The schema config includes schemas, tables, and columns. If you have not specified any schema configurations that differ from the default, the response will consist of only the top schema level. 
In other words, if a user is syncing an entire table, we don't get this information at Asset definition creation time. This is why our Fivetran assets on Hooli don't have schema info.
We can separately request this information from the API, but it requires one request per table, which adds up quickly. This PR
adds a default-on option to fetch column schema information after syncing a set of Fivetran tables, so we only …

[dagster-fivetran] Pull column schema at runtime after syncing table

---

docs/content/guides/limiting-concurrency-in-data-pipelines.mdx

Section runs quite long and a user got confused between what could be configured with the CLI vs in `dagster.yaml`. Adding subheads to differentiate. 
👀
NOCHANGELOG

[docs] Add subheads to 'Limiting op/asset concurrency across runs' section

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py
examples/experimental/dagster-airlift/dagster_airlift/core/airflow_instance.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/mark_as_migrating.py
examples/experimental/dagster-airlift/dagster_airlift/test/__init__.py
examples/experimental/dagster-airlift/dagster_airlift/test/airflow_test_instance.py
examples/experimental/dagster-airlift/dagster_airlift/test/shared_fixtures.py
examples/experimental/dagster-airlift/dagster_airlift/utils.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/conftest.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/migration_state_for_sqlite_test/dag.yaml
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_build_defs.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/in_airflow_tests/test_mark_as_dagster_migrating.py
examples/experimental/dagster-airlift/examples/dbt-example/Makefile
examples/experimental/dagster-airlift/examples/perf-harness/.airflow_home/logs/scheduler/latest
examples/experimental/dagster-airlift/examples/tutorial-example/Makefile

When sqlite is the airflow backend, expect that there will be an env var set to point dagster at the migration state folder.
How I tested this
Added unit tests for the airflow side as well as the dagster side.
`NOCHANGELOG`

[dagster-airlift] local migration state

---

js_modules/dagster-ui/packages/ui-core/src/app/Permissions.tsx
js_modules/dagster-ui/packages/ui-core/src/schedules/ScheduleResetButton.tsx
js_modules/dagster-ui/packages/ui-core/src/sensors/SensorDetails.tsx
js_modules/dagster-ui/packages/ui-core/src/sensors/SensorResetButton.tsx

Disable the cursor editing button on sensors for users who don't have permission.
Also fixed the tooltip width on the "Reset sensor status" button, because with a very long object name, the tooltip is comically wide.
View a sensor with viewer permissions, verify that the buttons are disabled and tooltip'd.

[ui] Disable sensor cursor editing based on code location permissions

---

examples/experimental/dagster-airlift/dagster_airlift/core/defs_from_airflow.py
examples/experimental/dagster-airlift/dagster_airlift/core/utils.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/base_proxy_operator.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/gql_queries.py
examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/operator_test_project/dagster_defs.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_build_defs.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_utils.py

Remove convention-based approaches for setting dag id and task ID.
`NOCHANGELOG`

[dagster-airlift] remove naming convention

---

python_modules/dagster/dagster/_core/libraries.py
python_modules/dagster/dagster_tests/core_tests/test_utils.py
python_modules/libraries/dagster-dbt/dagster_dbt/__init__.py

As the title. Since `dbt-core` isn't a Dagster library, we'll skip the version check and write it directly into the library mapping.
N/A

chore: register `dbt-core` version in `DagsterLibraryRegistry`

---

docs/content/integrations/dbt/using-dbt-with-dagster/load-dbt-models.mdx

The dbt tutorial explains `prepare_if_dev` in a couple different ways, and I think it could get the same info across with a bit less.

simplify `prepare_if_dev` explanation in dbt tutorial

---

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/resources.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/sling_event_iterator.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/sling_tests/test_fetch_metadata.py

Uses Sling's built-in `exec` CLI command to query the Sling target table to get a row count. Follows existing pattern of deferred metadata fetches, though we might want to start doing this behavior by default. Leaves that decision to a future PR.
```python
@sling_assets(replication_config=replication_config)
def my_assets(context, sling: SlingResource):
yield from sling.replicate(context=context).fetch_row_count()
```
Under the hood, invokes `sling conns exec [target conn] 'select count(*) from [target table]``, which uses Sling's underlying db adapters to query the target.
Similar to #23388, this fetch is synchronous and only happens after the sync completes, since this is when materializations are yielded. A future improvement could yield materializations as they happen and fetch the …

[dagster-embedded-elt] allow deferred fetch of row count using Sling

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
js_modules/dagster-ui/packages/ui-core/src/instance/flattenCodeLocationRows.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/CodeLocationRowSet.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/WorkspaceContext.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/WorkspaceQueries.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/__tests__/WorkspaceContext.test.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/types/WorkspaceQueries.types.ts
python_modules/dagster-graphql/dagster_graphql/implementation/external.py
python_modules/dagster-graphql/dagster_graphql/schema/external.py
python_modules/dagster/dagster/_core/remote_representation/code_location.py
python_modules/dagster/dagster/_core/workspace/context.py
python_modules/dagster/dagster/_core/workspace/workspace.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_external_asset_graph.py
python_modules/dagster/dagster_tests/core_tests/workspace_tests/test_request_context.py
python_modules/dagster/dagster_tests/general_tests/asset_graph_differ_tests/test_asset_graph_differ.py
python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py

We were using update timestamp as a proxy for version which does not work when there are multiple web servers with their own derived timestamp. Instead use an explicit "version key" based on the user code server id which should correctly be representative of potential changes in definitions. 
fixes https://github.com/dagster-io/dagster/issues/23753
* launch a code server
* 2 webservers pointed at that code server 
* nginx load balancing between those web servers 
* ensure the code locations table behaves as expected across multiple reloads as the user code server is restarted 
[dagster-webserver] fixes issue with code locations appearing in fluctuating incorrect state in deployments with multiple webserver processes

explicit version_key on code location status and entry

---

python_modules/libraries/dagster-k8s/dagster_k8s/client.py
python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_client.py

Addresses #23497. The `wait_for_pod` implementation currently erroneously assumes that the pod will be ready after one `initContainer` is ready. I added a set to track completed `initContainers` and compare the completed container count to the number of found statuses reported by the API.
Added two tests to `test_client.py` with multiple initcontainers. The second test has the second container succeed before the first. I also ran code by Oren in the linked issue, but patched my `wait_for_pod` implementation in.

[bugfix] k8s client wait_for_pod correctly handles multiple initcontainers

---

pyright/master/requirements-pinned.txt
pyright/master/requirements.txt
python_modules/libraries/dagster-tableau/dagster_tableau/__init__.py
python_modules/libraries/dagster-tableau/dagster_tableau/translator.py

Builds out a very barebones translator class to build specs for Tableau assets.
The structure of the `DagsterTableauTranslator` is based on the `DagsterPowerBITranslator` introduced in #23245.
Tests will be added in subsequent PRs.

[2/n][dagster-tableau] Scaffold DagsterTableauTranslator class

---

js_modules/dagster-ui/packages/ui-core/src/graph/OpTags.tsx
js_modules/dagster-ui/packages/ui-core/src/insights/InsightsIcon.tsx
js_modules/dagster-ui/packages/ui-core/src/search/SearchResults.tsx

Made a few changes to how the types are defined for insights icons to try to add a bit more strictness.
Counterpart to https://github.com/dagster-io/internal/pull/11507.
TS in both internal and OSS.
NOCHANGELOG

[ui] Some changes to icon types for Plus

---

docs/next/components/mdx/includes/dagster/DagsterDevTabs.mdx
python_modules/dagster/dagster/_core/workspace/load_target.py
python_modules/dagster/dagster_tests/cli_tests/workspace_tests/toml_tests/invalid_empty_modules.toml
python_modules/dagster/dagster_tests/cli_tests/workspace_tests/toml_tests/invalid_modules_dict.toml
python_modules/dagster/dagster_tests/cli_tests/workspace_tests/toml_tests/mixed_modules_and_module_name.toml
python_modules/dagster/dagster_tests/cli_tests/workspace_tests/toml_tests/multiple_modules.toml
python_modules/dagster/dagster_tests/cli_tests/workspace_tests/toml_tests/test_toml_loading.py

> Copied the same motivation that was stated back here, where it wasn't proceeded further https://github.com/dagster-io/dagster/pull/12551
It would be nice to load multiple modules using pyproject.toml so users don't have to type out all the modules they want to load using the CLI command. See issue https://github.com/dagster-io/dagster/issues/11439 and discussion https://github.com/dagster-io/dagster/discussions/11167.
I tried to add the recommendations mentioned here: https://github.com/dagster-io/dagster/pull/12551#issuecomment-1460574415
I added a new unit test in dagster_tests/cli_tests/test_toml_loading.py
-------------------------------------------------------------------------------------
* Updated documentation to include example of loading multiple modules (`DagsterDevTabs.mdx`) …

Add: Support for loading multiple modules

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py

The `name` property is now favored in the UI over `description`, and has a default value of the name of the class. This meant that in rows where we evaluated something against a specfic asset, it would render as DepConditionWrapperCondition instead of the asset name.
looked at the UI
[ui] Fixed an issue that would cause some AutomationCondition evaluations to be labeled `DepConditionWrapperCondition` instead of the key that they were evaluated against.

Update name property of DepConditionWrapperCondition

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/any_downstream_conditions_operator.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_any_downstream_conditions.py

Due to how we gate access to the legacy context object, and the fact that the "fully resolved" automation condition is not available until we execute the AnyDownstreamConditions condition (because we need access to the full asset graph), this would previously cause errors.
These errors are weird, as the method says "any downstream *conditions*", whereas the downstream causing that failure has an AutoMaterializePolicy, not a condition.
This change just ignores AMPs that are found downstream, avoiding the error
Fixed issue which could cause errors when using `AutomationCondition.any_downstream_condition()` with downstream `AutoMaterializePolicy` objects.

Ignore legacy AutoMaterializePolicies in AnyDownstreamConditions

---

python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/time_partition.py
python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_time_partition_freshness.py

Summary:
The current logic returns the last partition window that ends before the deadline, but I think what we actually want here is the most recent partition *at the time of* the deadline. The former does not correctly account for the end_offset shifting over the last partition window - the latter does. This PR makes that change.
Resolves https://github.com/dagster-io/dagster/issues/24394.
Test Plan: Adding a new test case now

Correctly account for end_offset when deciding which partition key to look for in a freshness-based asset check

---

python_modules/dagster/dagster/_core/definitions/decorators/definitions_decorator.py
python_modules/dagster/dagster/_core/definitions/definitions_loader.py
python_modules/dagster/dagster/_core/definitions/reconstruct.py
python_modules/dagster/dagster/_core/workspace/autodiscovery.py
python_modules/dagster/dagster_tests/cli_tests/command_tests/test_execute_command.py
python_modules/dagster/dagster_tests/cli_tests/workspace_tests/autodiscovery_tests/definitions_loader_no_context.py
python_modules/dagster/dagster_tests/cli_tests/workspace_tests/autodiscovery_tests/definitions_loader_with_context.py
python_modules/dagster/dagster_tests/cli_tests/workspace_tests/autodiscovery_tests/test_autodiscovery.py
python_modules/dagster/dagster_tests/definitions_tests/test_definitions_loader.py
python_modules/dagster/dagster_tests/definitions_tests/test_reconstructable.py

Base of `Definitions` lazy load stack.
Adds a `@definitions` decorator that returns a `DefinitionsLoader` object. This is a bare-bones object that wraps a `load_fn`. The `load_fn` optionally accepts a `DefinitionsLoadContext` instance and is expected to return a `Definitions` instance.
```
@definitions
def defs(context: DefinitionsLoadContext) -> Definitions:
return Definitions(
...
)
```
The loader is resolved to a `RepositoryDefinition` at the same point where all other loadable targets are, in `repository_def_from_target_def`.
This PR borrows heavily from @sryza's #23678. The main difference is that I aimed to keep it as minimal as possible:
- I create `DefinitionsLoadContext` only at the moment it is needed rather than threading it through multiple entry points.
- I have omitted the …

[lazy-defs] `@definitions` decorator and `DecoratorLoadContext`

---

python_modules/dagster/dagster/_core/definitions/decorators/repository_decorator.py
python_modules/dagster/dagster/_core/definitions/definitions_class.py
python_modules/dagster/dagster/_core/definitions/repository_definition/repository_definition.py
python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py

Adds a `metadata` field on `Definitions` to match the underlying `metadata` field on `RepositoryDefinition`. This supports upstack work on caching "code location metadata' on a `Definitions` object returned from a `DefinitionsLoader`.
NOCHANGELOG

[lazy-defs] Add `metadata` field on `Definitions`

---

python_modules/dagster/dagster/_cli/workspace/cli_target.py
python_modules/dagster/dagster/_core/definitions/definitions_loader.py
python_modules/dagster/dagster/_core/definitions/reconstruct.py
python_modules/dagster/dagster_tests/cli_tests/workspace_tests/autodiscovery_tests/test_autodiscovery.py
python_modules/dagster/dagster_tests/definitions_tests/test_definitions_loader.py

Add a `DefinitionsLoadType` to the `DefinitionLoaderContext`. I am not sure of the final ontology but decided to start it off as simple as possible, with two values: `ROOT` and `RECONSTRUCTION`. This can be accessed in a `DefinitionsLoader` to condition initial construction vs reconstruction logic.
NOCHANGELOG

[lazy-defs] Add a DefinitionsLoadType Enum

---

python_modules/dagster/dagster/_core/definitions/decorators/definitions_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/repository_decorator.py
python_modules/dagster/dagster/_core/definitions/definitions_class.py
python_modules/dagster/dagster/_core/definitions/definitions_loader.py
python_modules/dagster/dagster/_core/definitions/metadata/metadata_value.py
python_modules/dagster/dagster/_core/definitions/repository_definition/repository_definition.py
python_modules/dagster/dagster_tests/core_tests/test_metadata.py
python_modules/dagster/dagster_tests/definitions_tests/test_definitions_loader.py
python_modules/dagster/dagster_tests/general_tests/test_pending_repository.py

Add reconstruction metadata to `Definitions`, a new API for representing data underlying state-driven definitions from third-party sources. This allows potentially expensive external service calls underlying state-driven definitions to be made once in the code server, with the result reused when reconstructing `Definitions` again in child processes (run workers and step workers). Credit to @sryza for many of the ideas behind this API.
This is intended as a replacement for the existing `CacheableAssetsDefinition` API. Key differences:
- Code location metadata must be used with a `DefinitionsLoader` (`@definitions`) to work correctly
- Code location metadata can be used for metadata underlying any definition, not just assets.
- Code location metadata does not needs pseudo-definitions like …

[lazy-defs] Add new reconstruction metadata API on Definitions

---

js_modules/dagster-ui/packages/ui-core/src/instance/InstanceBackfills.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillStatusTagForPage.tsx

Updates the FE to display the `COMPLETED_SUCCESS` and `COMPLETED_FAILED` statuses in the downstream PR
Backfill run after updating the UI shows `Succeeded` status. Backfill run before the UI update is still `Completed`. Note that we changed the language to `Success` instead of `Succeeded` so this screenshot is slightly out of date

display new bulk action statuses in UI

---

python_modules/dagster/dagster/_record/__init__.py
python_modules/dagster/dagster_tests/general_tests/test_record.py

The test, as written, fails with `TypeError: <class 'dagster_tests.general_tests.test_record.test_generic.<locals>.Things'> is not a generic class`
NOCHANGELOG

[record] Make work with Generics

---

python_modules/libraries/dagster-powerbi/dagster_powerbi/__init__.py
python_modules/libraries/dagster-powerbi/dagster_powerbi/resource.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/pending_repo.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/pending_repo_two_workspaces.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_asset_specs.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_resource.py

Moves the PowerBI auth to a nested resource, which now has two options: direct API credential, or credentials for a Service Principal.

[dagster-powerbi] Add option to auth using a Service Principal

---

python_modules/dagster/dagster/_core/definitions/decorators/repository_decorator.py
python_modules/dagster/dagster/_core/definitions/definitions_class.py

Now that `Definitions` is the solidified default way of doing things, I don't think we need to spend words comparing it to a legacy API.

in Definitions docstring, remove discussion of repository

---

integration_tests/test_suites/daemon-test-suite/monitoring_daemon_tests/test_monitoring.py
python_modules/dagster-test/dagster_test/test_project/test_jobs/repo.py
python_modules/dagster/dagster/_core/execution/context/system.py
python_modules/dagster/dagster/_core/executor/base.py
python_modules/dagster/dagster/_core/executor/multiprocess.py
python_modules/dagster/dagster/_core/executor/step_delegating/step_delegating_executor.py
python_modules/dagster/dagster_tests/launcher_tests/test_default_run_launcher.py
python_modules/libraries/dagster-docker/dagster_docker/docker_executor.py
python_modules/libraries/dagster-docker/dagster_docker/docker_run_launcher.py
python_modules/libraries/dagster-docker/dagster_docker_tests/test_docker_executor.py

Instead of always failing the step when it crashes, potentially emit a run retry event instead - I did not realize that the core of processing these retry events was already happening within the executor, so getting this working is just a matter of emitting the correct event.
Resolves https://github.com/dagster-io/dagster/issues/16168.
New test cases
- `BUGFIX` Fixed an issue where an op or asset RetryPolicy was not respected after the process executing the op or asset crashed instead of raising an exception.

Respect op/asset retry policy when a step crashes or fails a health check

---

python_modules/libraries/dagster-tableau/dagster_tableau/resources.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/conftest.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_asset_specs.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_resources.py

Adds the `build_asset_specs` function on the `TableauWorkspace` resource, which users can use to fetch a list of asset specs.
Subsequent PR #24385 will cache the metadata returned from the API.
```python
workspace = TableauCloudWorkspace(
personal_access_token_name=...,
personal_access_token_value=..., 
site_name=..., 
pod_name=...,
)
specs = workspace.build_asset_specs()
defs = Definitions(assets=external_assets_from_specs(specs))
```
BK with additional unit tests.

[5/n][dagster-tableau] implement non-cached asset-building fns for dagster-tableau

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_on_missing_condition.py

Adds a new static constructor for a fairly-common situation. Users want new partitions to get filled in as soon as possible, but never want a partition to get re-materialized.
You could achieve that behavior with AutomationCondition.eager() & AutomationCondition.missing(), but that would result in a much more complex policy than necessary. This is a much cleaner (and more performant) option, and gives first-class support to a common use case
Added `AutomationCondition.on_missing()`, which materializes an asset partition as soon as all of its parent partitions are filled in.

[DA] Add `on_missing` prebuilt condition

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_on_missing_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_automation_condition.py

This adds a convenient way for users to remove operands from a top-level expression. A common use case here would be to remove the "in_latest_time_window" condition from one of the built-in expressions.
Added a new `.without()` method to `AutomationCondition.eager()`, `AutomationCondition.on_cron()`, and `AutomationCondition.on_missing()` which allows sub-conditions to be removed, e.g. `AutomationCondition.eager().without(AutomationCondition.in_latest_time_window())`.

[DA] Add `without()` method to AndAutomationCondition

---

python_modules/libraries/dagster-tableau/dagster_tableau/resources.py
python_modules/libraries/dagster-tableau/dagster_tableau/translator.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/conftest.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/pending_repo.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_asset_specs.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_resources.py

Adds cacheable assets definitions to ensure that Tableau data is only fetched from the API once.
```python
workspace = TableauCloudWorkspace(
connected_app_client_id=...,
connected_app_secret_id=...,
connected_app_secret_value=...,
username=...,
site_name=..., 
pod_name=...,
)
defs = workspace.build_defs()
```
BK with additional tests
NOCHANGELOG

[6/n][dagster-tableau] use asset caching logic for Tableau assets

---

js_modules/dagster-ui/packages/ui-components/src/components/PageHeader.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetPageHeader.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetTable.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx
js_modules/dagster-ui/packages/ui-core/src/automation/MergedAutomationRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/jobs/JobsPageContent.tsx
js_modules/dagster-ui/packages/ui-core/src/nav/PipelineNav.tsx
js_modules/dagster-ui/packages/ui-core/src/overview/OverviewPageHeader.tsx
js_modules/dagster-ui/packages/ui-core/src/overview/OverviewTabs.tsx
js_modules/dagster-ui/packages/ui-core/src/overview/OverviewTimelineRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunTableActionBar.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunsRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/schedules/ScheduleDetails.tsx
js_modules/dagster-ui/packages/ui-core/src/sensors/SensorDetails.tsx
js_modules/dagster-ui/packages/ui-core/src/settings/SettingsLayout.tsx

- makes headers a consistent height everywhere
- adds breadcrumbs to runs, automations, and jobs

Cleanup Header components on all pages

---

python_modules/dagster/dagster/_daemon/sensor.py

Summary:
Noticed this in a user report - these are sensors, not schedules
Test Plan: BK

Fix error message when a sensor is paused due to being unable to reach the code server

---

python_modules/dagster/dagster/_daemon/monitoring/run_monitoring.py

Summary:
Noticed this while testing something involving run monitoring. This feature is experimental and should only be refernced if the user has done something to enable it.
Test Plan: BK

Don't mention experimental resume run feature in every run monitoring failure message

---

js_modules/dagster-ui/packages/ui-core/src/hooks/useQueryPersistedState.tsx
js_modules/dagster-ui/packages/ui-core/src/ui/BaseFilters/useStaticSetFilter.tsx

Fix potential infinite loop caused by useLayoutEffect and isFirstRenderRef. The layout and regular effects were both gated by isFirstRenderRef, but since the effect is responsible for setting this flag, React's behavior allows useLayoutEffect to loop. This PR separates the refs for layout and regular effects to prevent the looping issue.
jest tests
NOCHANGELOG

[StaticSetFilter] Remove potential layoutEffect infinite loop

---

python_modules/dagster/dagster/_core/execution/backfill.py
python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py
python_modules/dagster/dagster_tests/storage_tests/test_run_storage.py
python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
python_modules/dagster/dagster_tests/storage_tests/utils/run_storage.py
python_modules/libraries/dagster-mysql/dagster_mysql_tests/test_run_storage.py
python_modules/libraries/dagster-postgres/dagster_postgres_tests/test_run_storage.py

add the ability to filter backfills by tags by using the run tags table as a proxy.
All runs launched by a backfill have the backfill tags added to them. We can query the run tags table for runs that match the provided tags and have a backfill tag and use those backfill ids to filter the backfill table.
We have to do an additional check of the results at the end to ensure the filter tags are present on the backfill object, and were not added to the run in another way
NOCHANGELOG

`tags` filtering for backfills

---

python_modules/libraries/dagster-looker/dagster_looker/cacheable_assets.py
python_modules/libraries/dagster-looker/dagster_looker/resource.py
python_modules/libraries/dagster-looker/dagster_looker/translator.py
python_modules/libraries/dagster-looker/dagster_looker_tests/mock_looker_data.py
python_modules/libraries/dagster-looker/dagster_looker_tests/test_cacheable_assets.py
python_modules/libraries/dagster-looker/setup.py

Implements cacheable assets for Looker. First, we represent all the explores as cacheable assets.
To populate the cache, we serialize the Looker API responses back to their JSON structured format using the Looker SDK. When retrieving from the cache, we can just deserialize them back to their corresponding classes.
In the following PRs, we will:
- Represent views as cacheable assets
- Represent dashboards as cacheable assets
- Add a custom translator for subsequent Looker structure types.
pytest with mocks, local
NOCHANGELOG

feat(looker): implement cacheable assets

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py

We should be checking this instead of the global permission when deciding whether or not to allow the "Report materialization" button. This PR handles the addition of the backend field for that.
NOCHANGELOG

Add a "hasReportRunlessAssetEventPermission' field to GrapheneAssetNode

---

python_modules/dagster/dagster/_core/definitions/cacheable_assets.py
python_modules/libraries/dagster-powerbi/dagster_powerbi/__init__.py
python_modules/libraries/dagster-powerbi/dagster_powerbi/resource.py
python_modules/libraries/dagster-powerbi/dagster_powerbi/translator.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/pending_repo.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_asset_specs.py

Add a reconstruction metadata API to the PowerBI integration.
Also make the existing PowerBI data structures serializable to eliminate an extra layer of translation to plain dict/list for serialization.
The PowerBI integration already offers state-driven asset definitions using `CacheableAssetsDefinition`. This adds an alternative `load_powerbi_defs` function as an alternative that uses code location instead of `CacheableAssetsDefinition`. It is invoked like this:
```python
@definitions
def reconstruction_metadata_defs(context: DefinitionsLoadContext) -> Definitions:
pbi_defs = load_powerbi_defs(
context,
api_token="token",
workspace_id="my_workspace",
enable_refresh_semantic_models=False,
)
return Definitions.merge(
Definitions(assets=[my_materializable_asset], …
```

[lazy-defs] Add reconstruction metadata to PowerBI integration

---

python_modules/dagster-graphql/dagster_graphql/implementation/execution/backfill.py
python_modules/dagster-graphql/dagster_graphql/schema/backfill.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_partition_backfill.py
python_modules/dagster/dagster/_core/execution/backfill.py

Adds a `job_name` property to PartitionBackfill. In addition to filtering by job name for storage implementations that store the job name, this will let us display the name of the job in the UI for job backfills rather than the name of the partition set. 
associated internal pr https://github.com/dagster-io/internal/pull/11617
NOCHANGELOG

add `job_name` property to partition backfill

---

docs/content/guides/dagster/software-defined-assets.mdx
examples/assets_pandas_pyspark/assets_pandas_pyspark/local_spark_filesystem_io_manager.py

This PR fixes a small ordering issue in the Spark/Pandas SDA guide. TL;DR is that the file in this example should be written only after data is written. Related to #14108.
eyeballs

[docs] - Fix example in Spark/Pandas SDA guide

---

docs/content/dagster-plus/deployment/serverless.mdx

The terms "allowlist" and "allowlisting" are synonymous with "whitelist" and "whitelisting". Users may be searching for one term rather than the other.
👀
NOCHANGELOG

[docs] also use 'allowlist' when referencing 'whitelist'

---

js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedRoot.tsx

As titled, previously we were hardcoding the height to 84px.
before:
after:
NOCHANGELOG

Set virtualized row height dynamically for runs feed

---

.github/workflows/build-docs-revamp.yml

mirrors https://github.com/dagster-io/dagster/blob/master/.github/workflows/build-docs.yml#L107
but on "master". we will switch to "docs-prod" when we go live (so the main site is versioned on every release)
`NOCHANGELOG`

update build-docs-revamp gh action to only publish prod on master

---

docs/content/concepts/partitions-schedules-sensors/backfills.mdx

This PR adds a note about backfill policies and their impact on launching backfills for asset jobs to the Backfill docs.
👀

[docs] - Add note about asset jobs + backfill policies to Backfill docs

---

docs/docs-beta/docs/guides/external-assets.md
docs/vale/styles/config/vocabularies/Dagster/accept.txt

- Fixes broken vale linter
* Missing `-` in front matter
* Adds unpartitioned and unserialized words to our `accept.txt`
* Sorted the `accept.txt` file
```
yarn vale
```
NOCHANGELOG

[docs-revamp] fix vale

---

python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/conftest.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/test_resource.py
python_modules/libraries/dagster-sigma/setup.py

Introduces  `build_organization_data`, which does the under-the-hood heavy lifting of building the Sigma object model.
There are two main object types we care about in Sigma's ontology:  [datasets](https://help.sigmacomputing.com/docs/datasets).
and [workbooks](https://help.sigmacomputing.com/docs/workbooks-overview).
Datasets are the Sigma equivalent of Power BI Semantic Models, they are views (optionally materializable, which we might want to handle later) which sit on top of tables or other data sources.
Workbooks consist of several pages composed of elements, each of which is a table or other visualization built from a dataset.
Sigma's APIs are a little cumbersome here - we'd like to build a relationship of dependencies from workbooks to datasets and datasets to raw source data, but …

[3/n][dagster-sigma] Build out organization parsing logic

---

python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
python_modules/libraries/dagster-sigma/dagster_sigma/translator.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/pending_repo.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/pending_repo_2.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/test_asset_specs.py

Introduces lazy-loading `build_defs` which users can use to get a set of assets for their Sigma organization:
```python
@definitions
def defs(context: DefinitionsLoadContext) -> Definitions:
sigma_org = SigmaOrganization(
cloud_type=SigmaCloudType.AWS_US,
client_id=...,
client_secret=...,
)
return sigma_org.build_defs(context)
```
This caches the expensive API fetches between loads.
New unit test which ensures assets are built and cached properly.
NOCHANGELOG

[5/n][dagster-sigma] Add lazy-loading build_defs fn

---

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/definitions/asset_subset.py
python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_impls.py
python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/legacy_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/valid_asset_subset.py
python_modules/dagster/dagster/_core/definitions/freshness_based_auto_materialize.py
python_modules/dagster/dagster/_utils/caching_instance_queryer.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_subset.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_dep_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/asset_daemon_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/automation_condition_scenario.py

The ValidAssetSubset class existed to enable us to do operations over subsets of assets that we knew to be valid. The AssetSlice class does the same thing, making ValidAssetSubset redundant and a lot of code to comprehend.
Removing this entirely would require updating all the internal auto_materialize_rule_impls, so for now this just hides the ValidAssetSubset in a legacy folder and reduces dependence on it throughout the rest of the codebase.
NOCHANGELOG

[cleanup] Quarantine ValidAssetSubset class

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_instigators.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_sensors.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py

due to modifications to the state made by `get_current_instigator_state` we can only short cut return if the persisted state entry is on or off
added test that previously failed 
[dagster-webserver] Fix an issue where the incorrect sensor/schedule state would appear when using `DefaultScheduleStatus.STOPPED` / `DefaultSensorStatus.STOPPED` after performing a reset

[graphql] fix issue with instigator state

---

python_modules/libraries/dagster-tableau/dagster_tableau/resources.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_asset_specs.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_pending_repo.py

Implements a simple materializable asset definition in `build_defs()`. 
The View assets are materialized in Dagster: 
- Fetch the most recent version
- Materialize the Dagster asset
- Add the metadata using the Tableau API response.
```python
workspace = TableauCloudWorkspace(
connected_app_client_id=...,
connected_app_secret_id=...,
connected_app_secret_value=...,
username=...,
site_name=..., 
pod_name=...,
)
defs = workspace.build_defs()
```
BK with updated tests
NOCHANGELOG

[7/n][dagster-tableau] add materializable assets for Tableau

---

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/legacy_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/valid_asset_subset.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/code_version_changed_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/slice_conditions.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/any_downstream_conditions_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/newly_true_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/since_operator.py
python_modules/dagster/dagster/_core/definitions/entity_subset.py
python_modules/dagster/dagster_tests/asset_defs_tests/asset_graph_view_tests/test_asset_slice.py
python_modules/dagster/dagster_tests/asset_defs_tests/asset_graph_view_tests/test_basic_asset_graph_view.py
python_modules/dagster/dagster_tests/asset_defs_tests/asset_graph_view_tests/test_latest_time_window.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_dep_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_automation_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/asset_daemon_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/automation_condition_scenario.py

Similar to the previous PR, but this time for AssetSlice. This lets us create and use slices of arbitrary EntityKeys. To help make this a bit simpler, I refactored the internal representation of an AssetSlice / EntitySlice to store a separate key/value so that the type system could independently understand the key type. I also removed some unused methods / code paths to aovid needing to refactor them . In particular, I removed the `time_windows` property of AssetSlice as it was unused outside of tests. We can always bring that back if we find a use for it.
NOCHANGELOG

AssetSlice -> EntitySlice

---

docs/docs-beta/docs/guides/configuring-assets.md

- Missing images were causing the Vercel deployment to fail; this replaces them with `placeholder.svg`
NOCHANGELOG

[docs-revamp] fix build by replacing missing images with placeholder.svg

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_condition_evaluations.py
python_modules/dagster/dagster/_core/definitions/asset_key.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/legacy_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/rule_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/code_version_changed_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/slice_conditions.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/any_downstream_conditions_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/newly_true_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/since_operator.py

This updates all of the AutomationCondition-adjacent objects to be generic, allowing them to operate over any type of EntityKey (if applicable). This opens the door to creating AutomationConditions that operate over AssetCheckKeys.
Note that I had to divest from `@record` due to an issue with how they handle generics: https://github.com/dagster-io/dagster/pull/23832
In its place, I went with subclassing our old friend `DagsterModel`. The reasoning here is that pydantic handles generics / hashing / inheriting fields in a better way than `@dataclass`. The main concern with this in the past was perf, but we're not actually constructing many instances of the conditions themselves, so that's not a huge concern here.
I also created a separate `BuiltinAutomationCondition` class for our built-in …

Generic AutomationContext, AutomationResult, AutomationCondition

---

js_modules/dagster-ui/packages/ui-core/src/sensors/EditCursorDialog.tsx

We're not resetting the loading state on the edit-cursor mutation on sensors, so if you edit the sensor, then open the dialog again, the save button is never re-enabled.
Fix this by using the `loading` value from the mutation itself, instead of a separate state value.
Edit a sensor cursor, save it. Verify brief loading state, success of the save mutatation, dialog closure, and toaster. Reopen dialog, verify that the button is enabled and I can save a new value.

[ui] Fix edit cursor save state

---

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py
python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster/_utils/caching_instance_queryer.py
python_modules/dagster/dagster_tests/asset_defs_tests/asset_graph_view_tests/test_basic_asset_graph_view.py

As title. This simplifies the process of constructing an AssetGraphView -- you just need to pass in an AssetGraph and a DagsterInstance.
Currently, no stale status calculation is done within the view object, but if/when we change that, we'll construct the object responsible for doing that querying within the AssetGraphView.
NOCHANGELOG

[refactor] Remove CachingStaleStatusResolver from AssetGraphView

---

python_modules/dagster/dagster/_core/loader.py
python_modules/dagster/dagster/_core/storage/dagster_run.py
python_modules/dagster/dagster/_utils/aiodataloader.py
python_modules/dagster/dagster_tests/utils_tests/test_dataloader.py

This PR adds sync support for the DataLoader pattern.
The pattern itself is a very clean way of allowing us to avoid creating separate BatchXLoader objects and threading them through a bunch of different functions. However, it's not realistic (at least in the short term) to have all callsites which require this sort of caching behavior to be async. So adding this capability allows sync code to take advantage of a shared cache without major refactors.
One explicit choice made here is that it is *not* required to call "prepare" before doing a synchronous query, which differs a bit from our existing BatchXLoader objects, which require you to add your keys beforehand, otherwise they'll error.
Personally, I think this works out a lot nicer in practice, as it avoids an entire class of runtime …

Add sync capabilities to DataLoader class

---

python_modules/dagster-graphql/dagster_graphql/implementation/asset_checks_loader.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_asset_checks.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_checks.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
python_modules/dagster/dagster/_core/storage/asset_check_execution_record.py
python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py

As title. This lets us get rid of a lot of complicated and bespoke code used for caching objects of different types.
Note that there is some weirdness that remains that requires us to eagerly prefetch data up front.
NOCHANGELOG

[refactor] Use InstanceLoadableBy for AssetCheckExecutionRecord

---

python_modules/dagster/dagster/_core/definitions/asset_graph.py
python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py

As title -- this adds a new AssetCheckNode which you can access using BaseAssetGraph.get(check_key).
While both AssetGraph and RemoteAssetGraph had information regarding the checks they contained, there was no unified interface for getting information about a specific check. More properties can be added in the future, but for now I just went with the bare minimum.
NOCHANGELOG

Add AssetCheckNode to AssetGraph classes

---

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/asset_graph_view/entity_subset.py
python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
python_modules/dagster/dagster/_utils/caching_instance_queryer.py
python_modules/dagster/dagster_tests/asset_defs_tests/asset_graph_view_tests/test_basic_asset_graph_view.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py

As title. This lets us do partition mappings to / from asset checks, meaning:
1. you can find the upstream partitions of the target asset from that asset's check
2. you can find the downstream subset of a given target check from that check's asset
At the moment, all asset checks are unpartitioned, and so these subsets will always be all or none. However, by modeling it in this way, we don't need to write any custom code to make it work this way, and can just rely on the existing partition mapping logic.
If in the future we decide that asset checks can be partitioned, then no changes will need to be made to these code paths.
NOCHANGELOG

Allow getting parent/child subsets with AssetCheckKeys

---

python_modules/dagster/dagster/_core/definitions/asset_check_spec.py
python_modules/dagster/dagster/_core/definitions/asset_graph.py
python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py
python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py

As title. This exposes a new AutomationCondition argument to the AssetCheckSpec class (and the asset_check decorator).
Currently, this AutomationCondition does not get evaluated. That will happen later up stack.
NOCHANGELOG

Allow AssetCheck to have AutomationConditions

---

docs/sphinx/sections/api/apidocs/libraries/dagster-looker.rst
python_modules/libraries/dagster-looker/dagster_looker/__init__.py
python_modules/libraries/dagster-looker/dagster_looker/lkml/asset_specs.py
python_modules/libraries/dagster-looker/dagster_looker/lkml/asset_utils.py
python_modules/libraries/dagster-looker/dagster_looker/lkml/dagster_looker_lkml_translator.py
python_modules/libraries/dagster-looker/dagster_looker_tests/lkml/test_asset_specs.py

We want to pave the way for a `DagsterLookerAPITranslator`. So start by clarifying the role of the existing `DagsterLookerTranslator` to be explicitly for `lkml`.
NOCHANGELOG

refactor(looker): rename `DagsterLookerTranslator` to `DagsterLookerLkmlTranslator`

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_evaluator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/legacy_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/slice_conditions.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/automation_condition_scenario.py

Refactors the `.create()` method on the context objects and reorganizes the code a bit more to my liking.
There's an unfortunate complication here caused by a weird thing that we do with non-subsettable multi assets, which is that if any asset decides to materialize, we materialize all of its neighbors as well.
If I could go back in time, I might not have implemented this behavior at all, but I think for now we're essentially stuck with it. Future attempts may be made to hide this nasty logic away more thoroughly.
NOCHANGELOG

[refactor] Simplify AutomationConditionEvaluator

---

python_modules/dagster/dagster/_core/asset_graph_view/entity_subset.py
python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py
python_modules/dagster/dagster/_core/definitions/asset_graph_subset.py
python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_evaluator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_tester.py
python_modules/dagster/dagster/_core/execution/asset_backfill.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_any_downstream_conditions.py

This is the next stop on the train to letting AssetChecks get automated. We need a way for the system to return a value that will cause both regular assets and checks to be executed. Iterable[EntitySubset] can do this, while AbstractSet[AssetPartitionKey] cannot.
NOCHANGELOG

[refactor] Return Iterable[EntitySubset] from evaluate() method

---

python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py
python_modules/dagster/dagster/_core/definitions/asset_daemon_cursor.py
python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_evaluator.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_any_downstream_conditions.py

As title -- this updates the return type to be Sequence[EntitySubset[EntityKey]], and updates the method for building run requests to process check keys in addition to asset keys.
Does not handle the case when this is running in "daemon mode" (i.e. checks can exist in different code locations), which is an explicit choice to avoid unnecessary complexity. The default behavior is for AutomationConditions to be evaluated against a single code location at a time, and so this is not an issue.
Tests will be done upstack.
NOCHANGELOG

AssetDaemon can produce runs targeting EntitySubset[AssetCheckKey]

---

python_modules/libraries/dagster-sigma/dagster_sigma/resource.py

Breaks out the Sigma integration logic which works around missing dataset APIs into their own methods. This will make it easier to drop in replacements if APIs are introduced, and is a bit easier to parse.
NOCHANGELOG

[dagster-sigma][refactor] Breakout dataset metadata fetches into separate methods

---

python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py
python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_evaluator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_tester.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/legacy_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/automation_condition_scenario.py

This updates the BaseAssetGraph class to produce a dependency graph of all entities (not just AssetKeys), allowing us to topologically sort the entire graph.
Note that I am using `parent_entity_keys` instead of `parent_keys`, because we use `parent_keys` / `child_keys` all over the codebase and historically this has just meant asset keys.
Worth considering renaming those to `parent_asset_keys` and `child_asset_keys`, but that felt like it was outside the scope of this PR.
NOCHANGELOG

AutomationConditionEvaluator operate over EntityKeys

---

python_modules/libraries/dagster-tableau/dagster_tableau/resources.py
python_modules/libraries/dagster-tableau/dagster_tableau/translator.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/conftest.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_asset_specs.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_pending_repo.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_translator.py

Initial implementation in previous PRs was using the PAT auth + REST API to fetch workbooks and views.
Updating the previous PRs in favor of the JWT auth + Metadata API + REST API, we were fetching workbooks and sheets as views (sheets are a subtype of views).
This PR add the necessary code to support dashboards using the JWT + Metadata + REST approach.
BK with updated tests
NOCHANGELOG

[8/n][dagster-tableau] support dashboards in dagster-tableau

---

integration_tests/test_suites/auto_materialize_perf_tests/test_asset_daemon_perf.py
python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py
python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_evaluator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_tester.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/legacy_context.py
python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/legacy_tests/test_auto_observe.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/asset_daemon_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/automation_condition_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/base_scenario.py

Makes it easier to construct an AutomationConditionEvaluator and simplifies the AssetDaemonContext object.
Previously, we were juggling a ton of parameters between these classes for essentially no reason.
NOCHANGELOG

[refactor] Slim down AssetDaemonContext

---

python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/automation_tick_evaluation_context.py
python_modules/dagster/dagster/_core/execution/asset_backfill.py
python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/legacy_tests/test_auto_observe.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/asset_daemon_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/base_scenario.py

This cleans up the AssetDaemonContext object a bit more, and renames it such that it's suitable for use in the user-code version of this feature.
NOCHANGELOG

[refactor] Cleanup AssetDaemonContext / rename to AutomationTickEvaluationContext

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_asset_condition_evaluations.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_auto_materialize_asset_evaluations.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_condition_evaluations.py
python_modules/dagster-graphql/dagster_graphql/schema/auto_materialize_asset_evaluations.py
python_modules/dagster/dagster/_core/definitions/asset_daemon_cursor.py
python_modules/dagster/dagster/_core/definitions/automation_tick_evaluation_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/serialized_objects.py
python_modules/dagster/dagster/_core/definitions/run_request.py
python_modules/dagster/dagster/_core/scheduler/instigation.py
python_modules/dagster/dagster/_core/storage/legacy_storage.py
python_modules/dagster/dagster/_core/storage/schedules/base.py
python_modules/dagster/dagster/_core/storage/schedules/sql_schedule_storage.py
python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster/_daemon/sensor.py
python_modules/dagster/dagster/_utils/test/schedule_storage.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_asset_daemon_failure_recovery.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/asset_daemon_scenario.py
python_modules/libraries/dagster-mysql/dagster_mysql/schedule_storage/schedule_storage.py
python_modules/libraries/dagster-postgres/dagster_postgres/schedule_storage/schedule_storage.py

This allows the serialized objects within the system to be generic (i.e. support either assets or asset checks).
This does not implement a method for storing AutomationConditionEvaluation objects that target AssetCheckKeys, as this will be handled in the next PR in the stack.

Generic serialized AutomationCondition objects

---

python_modules/dagster/dagster/_core/definitions/asset_key.py
python_modules/dagster/dagster/_core/scheduler/instigation.py
python_modules/dagster/dagster/_core/storage/schedules/sql_schedule_storage.py
python_modules/dagster/dagster/_utils/test/schedule_storage.py
python_modules/dagster/dagster_tests/definitions_tests/test_entity_key.py
python_modules/libraries/dagster-mysql/dagster_mysql/schedule_storage/schedule_storage.py
python_modules/libraries/dagster-postgres/dagster_postgres/schedule_storage/schedule_storage.py

This builds off the previous PR and actually lets these things be stored to / queried from the database.
Curious if people have better ideas for the serialization format. At the very least, it's under test so if something changes we'll know.
NOCHANGELOG

Allow AutomationConditionEvaluation[AssetCheckKey] to be stored in the database

---

python_modules/dagster/dagster/_core/definitions/asset_graph.py
python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/automation_tick_evaluation_context.py
python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_evaluator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/legacy_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/slice_conditions.py
python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
python_modules/dagster/dagster/_core/definitions/run_request.py
python_modules/dagster/dagster/_core/execution/submit_asset_runs.py
python_modules/dagster/dagster/_core/remote_representation/external.py
python_modules/dagster/dagster/_core/scheduler/instigation.py
python_modules/dagster/dagster/_core/workspace/workspace.py
python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py
python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/check_after_parent_updated.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/check_on_other_location.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_e2e.py

This fixes up some issues that I've been putting off downstack, in which the submit_asset_runs utility was being strict about requiring at least one asset key. There are now cases in which we want to submit asset checks with no asset keys, so this required some updates.
Added tests which demonstrate that:
a) runs can be successfully created that target both assets and checks
b) the system can launch the correct sets of runs even in "weird" cases (i.e. two checks are listening for updates from the same asset, but exist in different code locations)
NOCHANGELOG

Allow submit_asset_runs to submit runs targeting AssetCheckKeys

---

docs/docs-beta/docusaurus.config.ts
docs/docs-beta/src/styles/custom.scss

- Introduces a warning announcement bar to notify users that work is ongoing
NOCHANGELOG

[docs-revamp] introduce announcement bar

---

docs/content/concepts/partitions-schedules-sensors/sensors.mdx
examples/docs_snippets/docs_snippets/concepts/partitions_schedules_sensors/sensors/sensors.py
python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
python_modules/dagster/dagster/_utils/alert.py
python_modules/libraries/dagster-msteams/dagster_msteams/sensors.py
python_modules/libraries/dagster-slack/dagster_slack/sensors.py

Clarifies scope to a specific deployment. Previous description of applying to Dagster "instance" could be interpreted as applying to all deployments.
👀
NOCHANGELOG

[docs] Clarify that monitor_all_code_locations is scoped to a deployment

---

docs/content/_navigation.json
docs/content/dagster-plus.mdx
docs/content/dagster-plus/managing-deployments.mdx
docs/content/dagster-plus/managing-deployments/branch-deployments.mdx
docs/content/dagster-plus/managing-deployments/environment-variables-and-secrets.mdx
docs/content/dagster-plus/managing-deployments/reserved-environment-variables.mdx
docs/content/guides/dagster/branch_deployments.mdx
docs/content/guides/dagster/using-environment-variables-and-secrets.mdx

This PR moves the built-in/reserved env vars to a dedicated reference page. We've had some feedback that these were difficult to find, even in search. This makes the content visible in the sidenav; additionally, the now H1-level heading should improve search results.
eyes, local

[docs] - Move Dagster+ reserved env vars to dedicated reference

---

docs/docs-beta/docs/dagster-plus/access/rbac/users.md

Bug introduced in PR #23929. Cross-references in `users.md` miss a backslash, causing compilation to fail.
BK
NOCHANGELOG

[docs] Fix cross-reference in users.md

---

examples/use_case_repository/use_case_repository/guides/sftp_file_upload.md
examples/use_case_repository/use_case_repository/guides/sftp_file_upload.py

- example of uploading a file to an sftp server
- uses dagster-ssh resource
- Still need to setup unit test, possibly using Docker container to emulate server

[usecase] upload a file to an sftp server with dagster-ssh

---

python_modules/libraries/dagster-looker/dagster_looker/api/cacheable_assets.py
python_modules/libraries/dagster-looker/dagster_looker/api/dagster_looker_api_translator.py
python_modules/libraries/dagster-looker/dagster_looker/api/resource.py
python_modules/libraries/dagster-looker/dagster_looker_tests/api/mock_looker_data.py
python_modules/libraries/dagster-looker/dagster_looker_tests/api/test_cacheable_assets.py

Models [Looker dashboards](https://developers.looker.com/api/explorer/4.0/methods/Dashboard/all_dashboards?s=dashboard) as cacheable assets. To get a Looker dashboard's dependencies, we parse out its [dashboard filters](https://developers.looker.com/api/explorer/4.0/methods/Dashboard/dashboard?s=dashboard) for explores.
pytest, local
NOCHANGELOG

feat(looker): implement dashboards as cacheable assets

---

python_modules/dagster/dagster/_core/definitions/definitions_loader.py
python_modules/dagster/dagster_tests/definitions_tests/test_definitions_loader.py

Changes behavior of `DefinitionsLoadContext.get()` to default to an object with type `INITIALIZATION` and empty repository load data (instead of throwing an error).
New unit test.
NOCHANGELOG

[lazydefs] Default global DefinitionsLoadContext

---

python_modules/dagster/dagster_tests/storage_tests/utils/run_storage.py

fixes a test where the job_name for a backfill and it's subrun were different because the backfill and run were manually created. This was fine for OSS because filtering by job name for backfills in OSS just looks at the run, but didn't work for plus because we actually store the job name of the backfill in plus
NOCHANGELOG

[quick] align backfill and sub-run job name for job name filtering test

---

examples/experimental/dagster-airlift/dagster_airlift/core/dag_asset.py
examples/experimental/dagster-airlift/dagster_airlift/core/load_defs.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization_utils.py
examples/experimental/dagster-airlift/dagster_airlift/core/task_asset.py
examples/experimental/dagster-airlift/dagster_airlift/core/utils.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/conftest.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py

Refactor some core components of airlift for readability. This is a pretty big PR, but everything is interrelated so it's hard to break apart. Line change is a bit misleading, the actual code deletion here is more significant, but since I broke out into multiple files, there's at least 50 odd lines of imports getting added. 
- Split out the relatively massive and confusingly named defs_from_airflow.py file into more well-structured, smaller files which take on a specific vertical of functionality (dag_asset, task_asset, etc).
- Add a new serdes class `ExistingAssetKeyAirflowData`, rename `CacheableAssetSpec` to `SerializableAssetSpec` to better reflect our internal language.
- Rename all references to 'cache*' to 'serialize*', again to reflect our internal language and distance from …

[dagster-airlift] load_airflow_defs internal component refactor

---

python_modules/dagster/dagster/_core/storage/dagster_run.py

this change is motivated by some work i'm doing on the runs feed where i need to replace one of the values in the RunsFilter. However, the current `__new__` for the runs filter assigns `[]` as the value for `run_ids` if None is passed. When `copy(filters, created_before=updated_created_before)` is called, a new `RunsFilter` is constructed with `[]` passed as the value for `run_ids` which causes the `check` to fail. 
associated internal pr https://github.com/dagster-io/internal/pull/11683
existing tests
NOCHANGELOG

default the value of run_ids to None for RunsFilter

---

python_modules/libraries/dagster-looker/dagster_looker/api/cacheable_assets.py
python_modules/libraries/dagster-looker/dagster_looker/api/dagster_looker_api_translator.py
python_modules/libraries/dagster-looker/dagster_looker/api/resource.py

`LookerInstanceData` is used in the following manners:
- Used to build cacheable data
- Built from cacheable data
Consolidate these uses as methods on `LookerInstanceData`.
NOCHANGELOG

refactor(looker): consolidate `LookerInstanceData` methods

---

python_modules/libraries/dagster-looker/dagster_looker/api/cacheable_assets.py
python_modules/libraries/dagster-looker/dagster_looker/api/dagster_looker_api_translator.py
python_modules/libraries/dagster-looker/dagster_looker_tests/api/mock_looker_data.py
python_modules/libraries/dagster-looker/dagster_looker_tests/api/test_cacheable_assets.py

Slowly paves the way for modeling the materialized tables upstream of the views. First, we model the views upstream of an explore as dependencies.
pytest, local
NOCHANGELOG

feat(looker): implement views as dependencies of explores

---

python_modules/libraries/dagster-looker/dagster_looker/__init__.py
python_modules/libraries/dagster-looker/dagster_looker/api/cacheable_assets.py
python_modules/libraries/dagster-looker/dagster_looker/api/dagster_looker_api_translator.py
python_modules/libraries/dagster-looker/dagster_looker/api/resource.py
python_modules/libraries/dagster-looker/dagster_looker_tests/api/mock_looker_data.py
python_modules/libraries/dagster-looker/dagster_looker_tests/api/test_cacheable_assets.py

Uses https://cloud.google.com/looker/docs/reference/looker-api/latest/methods/DerivedTable/start_pdt_build to materialize a PDT.
Unfortunately, there's no API to fetch these PDTs in the first place, so they have to be manually specified. Here are all the APIs related to PDT's, just as a sanity check: https://cloud.google.com/looker/docs/reference/looker-api/latest/methods/DerivedTable.
pytest, local
NOCHANGELOG

feat(looker): implement pdts as assets

---

python_modules/libraries/dagster-looker/dagster_looker/api/resource.py

Reduce the time for API requests + the size of the cacheable asset by only fetching the fields from the Looker API used in the `dagster-looker` implementation.
local
NOCHANGELOG

feat(looker): only fetch a subset of fields from the Looker API

---

python_modules/dagster/dagster/_utils/interrupts.py

Fix an issue where this code could result in a spurious exception during process shutdown. Resolves https://github.com/dagster-io/dagster/issues/15100.
Writing an automated test is tricky because it only happens during proess shutdown, but the following script no longer raises an exception during __del__ in process shutdown:
```
from dagster import build_op_context
x = build_op_context(resources={"foo": "bar"})
```

Fix an issue where build_op_context could sometimes raise an exception during process shutdown

---

python_modules/dagster/dagster/_core/definitions/decorators/repository_decorator.py
python_modules/dagster/dagster/_core/definitions/repository_definition/repository_definition.py
python_modules/dagster/dagster_tests/definitions_tests/test_definitions_loader.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_asset_specs.py

Removes use of `PendingRepositoryDefinition` in the reconstruction metadata code path in favor of creating `RepositoryLoadData` directly in the `@repository` decorator.
Fixes https://linear.app/dagster-labs/issue/FOU-401/cut-pendingrepositorydefinition-out-of-the-loop-for-reconstruction
NOCHANGELOG

[lazy-defs] Cut PendingRepositoryDefinition out of reconstruction metadata code path

---

docs/docs-beta/docusaurus.config.ts

> [!CAUTION]  
> The `noIndex` parameter had to be unset for this to work. We should discuss the implications of that before merging, as I believe this would allow non-Algolia crawlers to hit the site too.
- Our Algolia crawler depends on a `sitemap.xml` file present on the deployed website
- This using the `docusaurus-sitemap` plugin to generate that file
```
yarn build. # sitemap is not available with `yarn start`
yarn serve
```
NOCHANGELOG

[docs-revamp] add sitemap.xml generation for use with Algolia

---

python_modules/dagster/dagster/_check/builder.py
python_modules/dagster/dagster/_record/__init__.py
python_modules/dagster/dagster_tests/general_tests/test_record.py

This came about from the PR stacked above this. Realized that there were some remaining issues, particularly with `copy()` and type checking paramters that were generic. Added tests for these cases and fixed them.
NOCHANGELOG

Fix edge cases of generic @records

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/sensors.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_sensors.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_instigation.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py
python_modules/dagster/dagster/_core/definitions/asset_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/decorators/sensor_decorator.py
python_modules/dagster/dagster/_core/definitions/multi_asset_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/sensor_definition.py
python_modules/dagster/dagster/_core/remote_representation/external.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster_tests/core_tests/definitions_tests/decorators_tests/test_sensor_decorator.py
python_modules/dagster/dagster_tests/definitions_tests/test_sensor_result.py

Add new `tags` parameter to `SensorDefinition` and associated classes.
The `tags` parameter represents strictly definition tags-- it is under no circumstances automatically attached to runs emitted from the sensor. This can be interpreted as matching the behavior on `ScheduleDefinition` (added upstack), where `tags` are _only_ auto-appended as run tags if a custom evaluation function is not provided (this is for backcompat reasons). We don't have to worry about this case with sensors since there are no instances without custom evaluation functions.
Note that there is one sensor type (`AutomationConditionSensor`) that already has a `run_tags` parameter. That did not interfere with this PR since it is under the `run_tags` name, but it's odd that this is the only sensor type with `run_tags` …

[definition-tags] Add `tags` param to SensorDefinition and subclasses/decorators

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/schedules/schedules.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_scheduler.py
python_modules/dagster/dagster/_core/definitions/decorators/schedule_decorator.py
python_modules/dagster/dagster/_core/definitions/schedule_definition.py
python_modules/dagster/dagster/_core/remote_representation/external.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/__snapshots__/test_active_data.ambr
python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_schedule.py
python_modules/dagster/dagster_tests/definitions_tests/test_schedule.py
python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py

Tweak the behavior of `tags` on `ScheduleDefinition` to make them act as "definition tags", as opposed to "run tags".
Downstack we add `tags` to `SensorDefinition`. This was straightforward because there was no pre-existing `tags` param. The situation is more complex for schedules-- `ScheduleDefinition` has a preexisting `tags` parameter that effectively acts as "run tags", i.e. if set it is attached to runs launched from the schedule.
However, if `tags` _and_ a custom execution function are set, then `ScheduleDefinition` errors on construction. Further, due to an apparent past mistake, if `tags` is passed to the `@schedule` decorator, then it is simply ignored in all but the case where the schedule returns a dict run config (an old and possibly not-even-supported anymore API)?
This …

[definition-tags] Add definition tags to `ScheduleDefinition`

---

python_modules/dagster/dagster/_check/builder.py
python_modules/dagster/dagster_tests/general_tests/test_record.py

Updated the `@record` check generating code to support optional, generic type annotations where the base type is also a `@record`. #24629 fixed this for non-optional generic records. Previously, this hit the unhandled case and raised an exception, e.g.
```python
@record
class Things(Generic[T]):
things: Sequence[T]
@record
class HolderOfThings(Generic[T]):
things: Optional[Things[T]]
```
New unit test which previously failed

 Allow @records to have optional, generic @records as fields

---

docs/docs-beta/docusaurus.config.ts

- `.git` folder is present on GitHub action
- `.git` folder is lost when using `vercel deploy` as is done by Vercel GitHub action
- Sitemap plugin relies on history in `.git` to add `lastmod` attribute to site entries
- I could not figure out how to include `.git` in deployment
- Future solution might be to perform the `yarn run build` on GitHub action, and deploy static files to Vercel
`yarn build`
`👀  build/sitemap.xml`
NOCHANGELOG

[docs-beta] temporarily remove `lastmod` for sitemap as `.git/` is not present on Vercel

---

docs/docs-beta/src/styles/custom.scss

- Text color was incorrectly black on dark background for announcement bar with dark theme
`yarn start`
NOCHANGELOG

[docs-beta] fix announcement bar colors for dark theme

---

docs/docs-beta/package.json
docs/docs-beta/yarn.lock

Try to use a resolution to force `path-to-regexp` to a version that resolves the dependabot alert. I can't find a breaking changes guide for v2 to v3 so I don't actually know what might break with this. Can I ask someone from docs-infra to try this and sanity check that everything works?
TBD. `yarn start` seemed to load the docs site fine.
NOCHANGELOG

[docs-beta] Set resolution for path-to-regexp

---

python_modules/dagster-webserver/dagster_webserver/graphql.py
python_modules/dagster-webserver/dagster_webserver/webserver.py

Break up the methods for graphql execution to when it is handed off to a thread and when it is handed off to an asyncio event loop.
bk

[graphql] shuffle execution methods

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_runs_feed.py
python_modules/dagster/dagster/_core/execution/backfill.py

Reverts dagster-io/dagster#24654
Adds runs feed filtering back in with method to skip filtering tests for plus since filtering won't be implemented there for a few more days
internal pr https://github.com/dagster-io/internal/pull/11719
NOCHANGELOG

Revert "Revert "support filtering in the runs feed""

---

.buildkite/dagster-buildkite/dagster_buildkite/cli.py
.buildkite/dagster-buildkite/dagster_buildkite/pipelines/prerelease_package.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
.buildkite/dagster-buildkite/dagster_buildkite/utils.py
.buildkite/dagster-buildkite/setup.py
python_modules/libraries/dagster-powerbi/setup.py
python_modules/libraries/dagster-sigma/dagster_sigma/__init__.py
python_modules/libraries/dagster-sigma/setup.py
scripts/build_and_publish.sh

Introduces a new BK pipeline which we can manually trigger to publish a package outside of the typical release process.
Right now, pulls a list of possible packages that do not have dynamic versions in `setup.py`:
The main use-case is for new integrations and experimental packages that we may want to iterate on rapidly, e.g. release more than once a week, separate from our stable package release process.
The pipeline:
1. Updates the version tag in code
2. Builds and publishes the package to pypi
3. Commits the new version tag
4. Pushes to a git tag `{package_name}/v{version}` and the selected branch on GitHub
Tested manually in BK
NOCHANGELOG

Introduce individual package publish Buildkite script

---

docs/docs-beta/README.md
docs/docs-beta/docusaurus.config.ts

- Adds Algolia search when _not_ `process.env.ENV === 'development'
- Reviewed the deployed preview
NOCHANGELOG

[docs-beta] add algolia search when deployed

---

js_modules/dagster-ui/packages/ui-core/src/assets/auto-materialization/AutomaterializationEvaluationHistoryTable.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/auto-materialization/InstanceAutomaterializationEvaluationHistoryTable.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/auto-materialization/SensorAutomaterializationEvaluationHistoryTable.tsx

This restricts the automaterialization tick filter component to the statuses that we know will be performant.
Loaded history page, used filter

update automaterialization views to use simplified tick filter

---

docs/content/dagster-plus/deployment/serverless.mdx
docs/docs-beta/docs/dagster-plus/deployment/serverless/runtime-environment.md

It should be `dagster-cloud serverless deploy-python-executable` and not `dagster-cloud deploy-python-executable`.
NOCHANGELOG

Fix `dagster-cloud serverless deploy-python-executable` references in docs

---

python_modules/dagster/dagster/_core/pipes/utils.py
python_modules/libraries/dagster-databricks/dagster_databricks/pipes.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_pipes.py

Right now Databricks Pipes create a new cluster for every invocation, because Databricks does not allow setting runtime environment variables for Pipes bootstrap params. 
This PR allows using existing clusters with Databricks Pipes. This is achieved by passing Pipes bootstrap params via Databricks [task parameters](https://docs.databricks.com/en/jobs/create-run-jobs.html#pass-parameters-to-a-databricks-job-task). These parameters are exposed to Python tasks as CLI args, so this feature requires using a `PipesCliArgsParamsLoader` in the task. Also, we do not support forwarding stdout/stderr from existing clusters (yet). 
Slack thread: https://dagsterlabs.slack.com/archives/C05M31J51J6/p1726501276959059
Resolve [FEAT-756](https://linear.app/dagster-labs/issue/FEAT-756/support-running-on-exis …

[dagster-databricks] Support existing clusters in Pipes

---

docs/content/dagster-plus/managing-deployments/deployment-settings-reference.mdx
docs/content/deployment/run-monitoring.mdx
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/instance/config.py
python_modules/dagster/dagster/_daemon/monitoring/run_monitoring.py
python_modules/dagster/dagster_tests/daemon_tests/test_monitoring_daemon.py

Allows you to set a global max across all runs in the deployment instead of tagging individual runs
BK

Expose a global 'max_runtime_seconds' field on run monitoring

---

docs/docs-beta/src/styles/custom.scss

- Fixes mobile view of announcement bar
* Removes hard-coded height limit
* Adds padding to top and bottom
* Changes color from red to yellow
**Before**
**After**
`yarn start`
NOCHANGELOG

[docs-beta] fix mobile view of announcement bar

---

examples/experimental/dagster-airlift/dagster_airlift/core/state_backed_defs_loader.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_state_backed_defs_loader.py

This class captures the common pattern of how an integration will interact with `DefinitionsLoadContext` to do state-backed loading.
Note: I am doing this in airlift only to make adding this lower stakes for now. If it proves useful, we can move it into dagster-core.
This also adds `scoped_metadata_for_reconstruction` which will be useful for test cases.
Docblock for usage:
```python
class StateBackedDefinitionsLoader(ABC, Generic[TState]):
"""A class for building state-backed definitions. In a structured way. It
handles manipulation of the DefinitionsLoadContext on the user's behalf.
The goal here is so that an unreliable backing source is fetched only
at code server load time, which defines the code location. When, for example,
a run worker is launched, the backing source is not queryed …
```

StateBackedDefinitionsLoader

---

python_modules/libraries/dagster-powerbi/dagster_powerbi/__init__.py
python_modules/libraries/dagster-powerbi/dagster_powerbi/resource.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/repos/pending_repo.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/repos/pending_repo_two_workspaces.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_asset_specs.py
python_modules/libraries/dagster-powerbi/setup.py

Now that we can obtain the definitions load context contextually, drop in replace cacheable assets with this approach. Leaves the existing deferred load method for now, but combines its impl with `build_defs`.
NOCHANGELOG

[dagster-powerbi] Use lazy loading in place of cacheable assets by default

---

python_modules/dagster/dagster/_core/definitions/asset_spec.py
python_modules/dagster/dagster/_core/definitions/source_asset.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_materialize.py

`SourceAsset` has been deprecated in favor of `AssetSpec`. Unlike `SourceAsset`, `AssetSpec` has no `io_manager_key` attribute, but an IO manager key can be provided via metadata to dictate how the asset is loaded in downstream assets.
This metadata-based IO management has up until this point not been very discoverable (you need to read the migration guide or https://docs.dagster.io/concepts/io-management/io-managers#using-io-managers-to-load-source-data to find it).
`AssetSpec` now has a `with_io_manager_key` method that returns an `AssetSpec` with the appropriate metadata entry to dictate the key for the IO manager used to load it. The deprecation warning for `SourceAsset` now references this method.

add AssetSpec.with_io_manager_key and update SourceAsset deprecation warning

---

python_modules/dagster/dagster_tests/general_tests/test_record.py

These features do not work with python 3.8/3.9. We're not currently using them anywhere, so skipping for now until we can diagnose the issue.
NOCHANGELOG

Skip failing record tests

---

docs/docs-beta/docusaurus.config.ts
docs/docs-beta/src/styles/custom.scss

- Adds a "Feedback" link to a GitHub discussion
@PedramNavid - we will need to update this to the new discussion.
`yarn start`
NOCHANGELOG

[docs-beta] add feedback link to github discussion

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
examples/experimental/dagster-airlift/dagster_airlift/core/load_defs.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py

I had encountered a bug around using serdes objects in the DefinitionsLoadContext. I ended up doing this refactor and adding a test case to understand the existing behavior. This made the replacement upstack more minimal so submitting a separate PR.
Specifically `defs_with_airflow_metadata_applied` was kind of in an unexpected spot (deep in the callstack) so moved it much closer to where the state is actually fetched.
BK
NOCHANGELOG

Refactor airlift defintions construction logic for more elegant replacement

---

docs/content/integrations/sigma.mdx
examples/docs_snippets/docs_snippets/integrations/sigma/customize-sigma-asset-defs.py
examples/docs_snippets/docs_snippets/integrations/sigma/multiple-sigma-organizations.py
examples/docs_snippets/docs_snippets/integrations/sigma/representing-sigma-assets.py
python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/pending_repo.py

Now that we can obtain the definitions load context contextually, add a default `None` input for `sigma_organization.build_defs()` so that it can be called outside the context of a definitions-building function. This simplifies the user-facing code:
```python
resource = SigmaOrganization(
base_url=SigmaBaseUrl.AWS_US,
client_id=fake_client_id,
client_secret=fake_client_secret,
)
@asset
def my_materializable_asset():
pass
defs = Definitions.merge(
Definitions(assets=[my_materializable_asset], jobs=[define_asset_job("all_asset_job")]),
resource.build_defs(),
)
```
Existing unit tests, with new approach.
NOCHANGELOG

[dagster-sigma] Extract defs loading context implicitly

---

examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_airflow_asset_mapping.py

One of the big sources of complexity in airlift right now is `compute_serialized_data` which iteratively builds up a bunch of data structures in parallel. If we want to change anything about the way this works, it is complicated and error-prone.
Instead of building up these data structures imperatively in one pass, we instead will construct data structures that use functional programming to build up "views" of the data that are easier to reason about. 
In this case we introduce `TaskSpecMappingInfo` which manages all the various data that maps task_id and dag_ids to asset keys. 
It also accepts a list of asset specs, so the operations are guaranteed to be fast, and all results are memoized with `cached_property`.
BK
NOCHANGELOG

Add functional type mapping object to control complexity in compute_serialized_data

---

examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_airflow_asset_mapping.py

Similar in spirit to the upstack #24680. This adds another functional "view" object, but this time over prefetched data from the Airflow instance.
This current PR changes no behavior w/r/t to interaction with the AirflowInstance, but it structures things in way where it will be trivial to change fetching task infos to bulk fetching.
BK
NOCHANGELOG

FetchedAirflowData

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_instance.py
examples/experimental/dagster-airlift/dagster_airlift/test/airflow_test_instance.py
examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_airflow_instance.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_test_utils.py

Add `get_task_infos` to AirlfowInstance and its associated test class
We will use this to improve performance of our definitions fetching code.
BK
NOCHANGELOG

Add get_task_infos on AirflowInstance

---

examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py

Using bulk fetching of task infos on a per-dag basis. Things are much faster now.
`sudo py-spy record --format speedscope -- python perf_harness/cli.py 1 100 1`
Before:
After:
Suspect that at a certain number of dags and task we will need to either throttle down fetching or move this process to a CI/CD step in the Airflow repo. 
`make run_perf_1_100_1`
Before:
```
Total airflow dags load time: 0.2467 seconds
Airflow defs import time: 0.2093 seconds
Mark as dagster migrating time: 0.0311 seconds
Airflow setup time: 3.2898 seconds
Airflow standup time: 5.0973 seconds
Peered defs import time: 0.2268 seconds
Observed defs import time: 9.2317 seconds
Migrate defs import time: 8.4607 seconds
peer defs initial load time: 0.0017 seconds
observe defs initial load time: 0.0068 seconds
migrate defs …
```

Use AirflowInstance.get_task_infos to improve performance.

---

python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
python_modules/libraries/dagster-sigma/dagster_sigma/translator.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/conftest.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/test_asset_specs.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/test_translator.py

Fetches and attaches owner metadata to Sigma workbooks, since it's available to us. Users can override these owners in a custom translator.

[dagster-sigma] Fetch and assign default owners to workbooks

---

python_modules/dagster/dagster/_check/builder.py
python_modules/dagster/dagster/_core/definitions/asset_graph_differ.py
python_modules/dagster/dagster_tests/general_tests/asset_graph_differ_tests/test_asset_graph_differ.py

Currently, `AssetGraphDiffer` only a list of `AssetDefinitionChangeType` that have changed between a base and branch workspace. We want to also provide the content diff of those changes.
```
pytest python_modules/dagster/dagster_tests/general_tests/asset_graph_differ_tests/test_asset_graph_differ.py
```

[PLUS-1363] Generate asset definition diff information

---

python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
python_modules/dagster/dagster/_core/utils.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py

This would cause an error if both an asset key and an asset check key existed in the same "level", as there was no way to sort a list of asset key or asset check key.
NOCHANGELOG

Fix toposorted_entity_keys sorting

---

js_modules/dagster-ui/packages/ui-core/src/automation/AutomationsTable.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/LogsScrollingTable.tsx
js_modules/dagster-ui/packages/ui-core/src/ui/VirtualizedTable.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/RepositoryLocationsList.tsx

Remove `DynamicRowContainer`, as it's not actually necessary for our dynamic row sizing in virtualized tables.
View affected list views, verify that they render and scroll correctly.
NOCHANGELOG

[ui] Clean up dynamic row sizing in virtualized tables

---

examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
examples/experimental/dagster-airlift/dagster_airlift/core/task_asset.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_airflow_asset_mapping.py

To split up the work of converting to allowing multiple tasks to map to single asset, we first refactor the internals to handle this without changing the actual metadata format. We write everything in terms of lists but asset that those lists only contain one element.
BK
NOCHANGELOG

Refactor compute.py to think in terms of multiple task handles per asset key

---

examples/experimental/dagster-airlift/dagster_airlift/constants.py
examples/experimental/dagster-airlift/dagster_airlift/core/task_asset.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_airflow_asset_mapping.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_migrating_e2e.py

Per discussion we do not use this in business logic. Additionally it might be out of date with the actual state of things depending on when you reloaded the code location relative to the airflow instance.
BK
NOCHANGELOG

Delete unused MIGRATED TAG

---

python_modules/dagster/dagster/_core/definitions/asset_graph_differ.py
python_modules/dagster/dagster_tests/general_tests/asset_graph_differ_tests/test_asset_graph_differ.py

An `AssetDefinitionDiff` serdes class already exists in internal, causing a `SerdesUsageError`. Renaming it to `AssetDefinitionDiffDetails`

Rename AssetDefinitionDiff serdes class

---

examples/experimental/dagster-airlift/dagster_airlift/constants.py
examples/experimental/dagster-airlift/dagster_airlift/core/dag_asset.py
examples/experimental/dagster-airlift/dagster_airlift/core/dag_defs.py
examples/experimental/dagster-airlift/dagster_airlift/core/defs_builders.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
examples/experimental/dagster-airlift/dagster_airlift/core/task_asset.py
examples/experimental/dagster-airlift/dagster_airlift/core/utils.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/base_proxy_operator.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/gql_queries.py
examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/operator_test_project/dagster_defs.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/conftest.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_airflow_asset_mapping.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_dag_defs.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/in_airflow_tests/test_parse_metadata.py

This changes the actual underlying metadata representation 
Note that this still preserves us the option to display additional (purely for display) metadata in the common case where there is only a single airflow task at play.
Instead of separate `task_id` and `dag_id` metadata entries, we just have a single `dagster-airlift/task_mapping` key which expects a list of dictionaries with keys task_id and dag_id. This ends up getting coerce to a JsonMetadataValue, a slight regression in our display. 
BK
Additionally ran through dbt-example (and debugged issue)
NOCHANGELOG

Change underlying metadata representation to handle multiple task mappings

---

js_modules/dagster-ui/packages/ui-core/src/app/CloudOSSContext.tsx
js_modules/dagster-ui/packages/ui-core/src/search/useAugmentSearchResults.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/search/useGlobalSearch.tsx

Injecting this via context introduces a run time circular dependency when combined with https://github.com/dagster-io/dagster/pull/24685 and https://github.com/dagster-io/internal/pull/11739.
Instead lets use our new shared component approach which will make circular dependencies harder to miss.
build and load the app with the above PRs included, observe no white screen.
NOCHANGELOG

Move useAugmentSearchResults to a shared component

---

python_modules/dagster/dagster/_core/definitions/asset_graph_differ.py

Without explicitly specifying this here, we were hitting this error on the backcompat tests:
```python
...
2024-09-25 08:51:16   File "/tmp/python_modules/dagster-graphql/dagster_graphql/implementation/execution/__init__.py", line 34, in <module>
2024-09-25 08:51:16     from dagster_graphql.implementation.fetch_assets import get_external_asset_node
2024-09-25 08:51:16   File "/tmp/python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py", line 25, in <module>
2024-09-25 08:51:16     from dagster._core.definitions.asset_graph_differ import AssetGraphDiffer
2024-09-25 08:51:16   File "/tmp/python_modules/dagster/dagster/_core/definitions/asset_graph_differ.py", line 60, in <module>
2024-09-25 08:51:16     class DictDiff(Generic[T]):
2024-09-25 08:51:16   File …
```

explicitly set kwargs_fields to fix bk

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor.py

Right now we compute all the asset check keys related to the asset keys during the definitions fetching process. The information seems to be readily computable within the sensor itself. 
Eliminating the serialization of this allows for the deletion of a significant amount of code upstack.
BK
NOCHANGELOG

Compute asset checks directly in sensor rather than relying on serialized values

---

python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py
python_modules/libraries/dagster-dbt/dagster_dbt/metadata_set.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_def_metadata.py

Without this, it's difficult to determine whether a dbt model is a view or not.
https://docs.getdbt.com/docs/build/materializations
One question that came up is whether this should instead be "dagster-dbt/**materialized**_type", given that it's configured in dbt using e.g. `+materialized: table`. However, in their docs they call it "materialization", and the past tense seems a little awkward for this use case.

add "dagster-dbt/materialization_type" to default metadata produced for dbt assets

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization/serialized_data.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py

With #24728 we no longer compute check keys associated with the asset keys in the serialization process and instead compute them on demand in the sensor.
It was actually the only piece of data we accessed in the `SerializedAssetKeyScopedAssetGraphData` which allowed for a set of cascading deletes.
Also was able to eliminate the `GenericNonScalarKeyMappingSerializer` and instead just rely on serializing key-value records (I tried tuples at first which would be even less code. Not sure what is going on there.). We can very easily convert lists to dictionaries and back, which is simpler and more obvious.
e.g.
```python
@record
@whitelist_for_serdes
@record
class SerializedAirflowDefinitionsData:
key_scoped_data_items: List[KeyScopedDataItem]
@cached_property
def key_scope_data_map(self) -> …
```

remove SerializedAssetKeyScopedAssetGraphData and SerializedAssetKeyScopedData

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/since_operator.py

This field already exists on the base BuiltinAutomationCondition class
NOCHANGELOG

Remove duplicated label attribute

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_check_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_dep_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_automation_condition.py

Avoids warning in pydantic 2, and is just better architecturally. It's kinda weird to have a class that users subclass have a built-in property.
Existing tests
NOCHANGELOG

Avoid annoying pydantic warnings

---

python_modules/dagster/dagster/_core/execution/context/output.py
python_modules/dagster/dagster_tests/execution_tests/context_tests/test_output.py

Contributes to https://github.com/dagster-io/dagster/issues/23965. 
Exposes the `AssetSpec` on the `OutputContext`, which in turn contains things like the `code_version` and `partitions_definition`.
Some thoughts:
- The asset `PartitionsDefinition` and `AssetKey` are already exposed on the `OutputContext` directly, but they are also part of the `AssetSpec`. Maybe this makes the directly exposed properties superfluous in the long run?
- The way to get to the `AssetSpec` via `step_context.job_def.asset_layer` seems like a bit of a long way around. Perhaps the `AssetSpec` should be part of the `OutputContext` constructor and be attached directly as a property?
Added a unit test to confirm that the `AssetSpec` is exposed on the `OutputContext` by checking with an io manager
`OutputContext` …

Expose AssetSpec on OutputContext

---

python_modules/dagster/dagster/_core/definitions/automation_tick_evaluation_context.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/check_not_subsettable.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_e2e.py

This is a stopgap measure. This solution would cause undesired behavior in some edge cases where users are automating asset checks separately from their associated asset (essentially, the check would double-fire in some circumstances.
NOCHANGELOG

Fix asset check selection for required asset checks

---

python_modules/dagster/dagster/_core/definitions/definitions_load_context.py
python_modules/dagster/dagster/_utils/test/definitions.py
python_modules/dagster/dagster_tests/definitions_tests/test_definitions_load_context.py

- Factors `StateBackedDefinitionsLoader` out of experimental dagster-airlift and into core.
- Move test utilities defined next to `StateBackedDefinitionsLoader` from dagster-airlift to core
NOCHANGELOG

[lazy-defs] Move StateBackedDefinitionsLoader from airlift to core

---

python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
python_modules/libraries/dagster-sigma/dagster_sigma/translator.py

Define a `SigmaOrganizationDefsLoader` class inheriting from the new `StateBackedDefinitionsLoader` and make SigmaOrganization.build_defs() use this class.
NOCHANGELOG

[lazy-defs] [dagster-sigma] Refactor dagster-sigma to use the StateBackedDefinitionsLoader

---

python_modules/libraries/dagster-k8s/dagster_k8s/models.py
python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_models.py

Speedscope results suggest that we are spending excessive amounts of time just acquiring a logging lock that we don't use here. Pass in a configuration object to prevent that from happening.
Test Plan: GK
Changelog

Don't create a new k8s configuration object every time a model is programatically created

---

python_modules/dagster/dagster/_check/builder.py
python_modules/dagster/dagster/_record/__init__.py
python_modules/dagster/dagster_tests/general_tests/check_tests/test_check.py
python_modules/dagster/dagster_tests/general_tests/test_record.py

Tidy up record inheritance fixes by enforcing different rules for `@record_custom` and `@record`, only allowing inheritance on the latter.  Doing this allows us to place the generated `__new__` on the generated class directly for regular `@record` and avoid MRO resolving to the wrong ancestral `NamedTuple`.  Additional fixes to get all tests passing on py3.8.
updated test cases
on python3.8 run 
```
pytest python_modules/dagster/dagster_tests/general_tests/check_tests/test_check.py python_modules/dagster/dagster_tests/general_tests/test_record.py --sw -vvvv
```

[record] mutex record_custom and record inheritance

---

python_modules/libraries/dagster-docker/dagster_docker/docker_run_launcher.py
python_modules/libraries/dagster-docker/dagster_docker_tests/test_launch_docker.py

Add dagster/run_Id and dagster/job_name as Docker labels in the docker run launcher

---

js_modules/dagster-ui/packages/ui-core/src/runs/RunsFilterInput.tsx

I noticed that the "created date" filter in the UI uses the `createdBefore` and `updatedAfter` filters rather than the `createdBefore` and `createdAfter` filters. I think this is because the `createdAfter` filter was not added to the GrapheneLayer until recently ([pr](https://github.com/dagster-io/dagster/pull/21945)), but want to ensure that it's not intentional that the `updatedAfter` filter is being used.

update UI Runs filter to use created_after rather than updated_after

---

python_modules/dagster-graphql/dagster_graphql/implementation/asset_checks_loader.py
python_modules/dagster-graphql/dagster_graphql/implementation/execution/__init__.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_asset_checks.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
python_modules/dagster/dagster/_core/workspace/context.py

Consolidate our handling of the global asset graph in the code base by moving the GraphQL layer over to `RemoteAssetGraph` more directly. This setup also moves grabbing specific assets to a  `get_asset_node` on workspace request context, allowing it to be overrode in other implementations. 
counting on existing coverage

[graphql] use RemoteAssetGraph

---

docs/content/dagster-plus/deployment/serverless.mdx

1. replace example project with quickstart_etl ([assets_modern_data_stack](https://github.com/dagster-io/dagster/tree/master/examples/assets_modern_data_stack) is no longer maintained).
2. clarify `dagster-cloud` dependency requirement note and move `setup.py` example snippet up into the note.
3. show `--python-version` arg in example snippet. In my testing of the serverless deploy command, not including the arg resulted in an error that was not obvious to solve. I had to search through the dagster-cloud CLI commands to find it was even possible to specify.
NOCHANGELOG

[docs] update 'Getting started with Serverless' manual deployment guide

---

python_modules/dagster/dagster/_core/executor/step_delegating/step_delegating_executor.py
python_modules/dagster/dagster/_core/storage/event_log/base.py
python_modules/dagster/dagster_tests/execution_tests/engine_tests/test_step_delegating_executor.py

Summary:
- Pull the default value to use for the executor offset from the event log storage
- Fix an issue that occurred when where the limit was less than the offset, so that it becomes safe to set the default offset higher than the default limit - in rare situations where every event globally was from the same run, the offset scheme created situations where the offset would result in going back to only events that were from that run, so the cursor wouldn't actually advance on each run! To fix that, advance it so that it will go halfway through the returned list on the next iteration when this happens, to ensure that there is always forward progress no matter what.

Set up StepDelegatingExceutor to accept a default offset to guard against out-of-order insertion issues

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/rule_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/code_version_changed_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/slice_conditions.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/any_downstream_conditions_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/check_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/newly_true_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/since_operator.py

Converts all of the built-in automation conditions to use @record instead of pydantic models.
NOCHANGELOG

Convert AutomationCondition to @record

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization/serialized_data.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py

This can be easily computed in the code location and it is memoized, so there is little benefit. Sets up further simplification of `compute.py`.
BK
NOCHANGELOG

Do not precompute topological ordering in build airflow assets

---

examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_airflow_asset_mapping.py

With the need to serialize the topological order, we can simplify our favorite `compute_serialized_data`. The downstream dependencies dictionary is immutable, `all_asset_keys` is totally eliminated, as well  computing upstream deps.
NOCHANGELOG

Delete upstream deps and simplify compute_serialized_data 

---

python_modules/dagster-graphql/dagster_graphql/schema/asset_selections.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py

Stabilize the order of keys from a resolved asset selection in `GrapheneAssetSelection`. Keys are sourced from a set, unstable order was causing indeterminacy in tests.
Existing test suite and repeated previously indeterminate test 5x locally.
NOCHANGELOG

Stabilize GQL AssetSelection key order

---

python_modules/dagster/dagster/_core/definitions/data_version.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster_tests/execution_tests/versioning_tests/test_data_versions.py

Internal companion PR: https://github.com/dagster-io/internal/pull/10427
Non-transitive sync status calculation is toggled by an org setting. This has been turned off by default for everyone for a few months now. We have had no need to revert, so this PR cleans non-transitive sync status completely out of the codebase.

Non-transitive sync status

---

python_modules/dagster/dagster/_core/definitions/definitions_class.py
python_modules/dagster/dagster/_core/definitions/metadata/metadata_value.py
python_modules/dagster/dagster_tests/core_tests/test_metadata.py
python_modules/dagster/dagster_tests/definitions_tests/test_definitions_load_context.py

Make reconstruction metadata only accept string values. Add error message about need to pre-serialize when string is not passed.
NOCHANGELOG

[lazy-defs] Restrict reconstruction metadata to string values

---

python_modules/libraries/dagster-powerbi/dagster_powerbi/resource.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_asset_specs.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_resource.py

On `PowerBIWorkspace`:
- Mark public methods with `@public`
- Make other methods private, so they won't so up in auto-complete
Also change some `Dict`s to `Mapping`s.
NOCHANGELOG

publicize and privatize PowerBIWorkspace methods

---

python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/test_failures.py

For example, task placement failures.
[dagster-aws] The ECS launcher now automatically retries transient ECS RunTask failures (like capacity placement failures).

Retry certain kinds of run task failures

---

js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedRow.tsx

The RunStatusTagWithStats can't get stats for backfills, so instead we should show the non-stats RunStatusTag for backfills. 
I'm having an issue with the size of the tag though, the RunStatusTagWithStats is the expected size, but RunStatus tag is strangely wide 
👀 
NOCHANGELOG

disable run status popover for backfills in runs feed

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/inputs.py

Adds `excludeSubruns` to  `GrapheneRunsFilter` so that the UI can power the "Show runs within backfills" checkbox
An alternate implementation would be to have a separate parameter for the `runsFeedOrError` query that determines whether we exclude subruns. I tried that [here](https://github.com/dagster-io/dagster/pull/24710) but ran into some confusing gql errors. Marco had a slight preference for implementing the UI as passing the option to the RunsFilter, so i switched to that approach. I can go back to the parameter version though if we want to be more cautious about adding this filter to more APIs
Corresponding internal PR https://github.com/dagster-io/internal/pull/11793
NOCHANGELOG

add `exclude_subruns` option to GrapheneRunsFilter

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py
python_modules/dagster-graphql/dagster_graphql/schema/inputs.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_runs_feed.py

Updates the `runsFeedOrError` query to incorporate the `exclude_subruns` filter if provided. 
NOCHANGELOG

incorporate runsfilter.exclude_subruns value when fetching runs feed

---

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/sling_event_iterator.py

Right now, we don't include the actual error message text in the warning log. We should emit it so it's easier for users to track down what went wrong.

[dagster-embedded-elt] Include entire error message when failing to fetch Sling metadata

---

docs/content/integrations/embedded-elt/dlt.mdx

This PR fixes a typo in docs on the `dlt.mdx` page.
Didn't test it.
NOCHANGELOG

Fix a typo in dlt.mdx

---

python_modules/dagster/dagster/_core/definitions/asset_graph_differ.py

Now that records and generics are fixed, revert this change as it's no longer necessary.
See if backcompat test works on bk.
NOCHANGELOG

Revert "explicitly set kwargs_fields to fix bk (#24750)"

---

python_modules/dagster/dagster/_daemon/run_coordinator/queued_run_coordinator_daemon.py
python_modules/dagster/dagster_tests/daemon_tests/test_queued_run_coordinator_daemon.py

No need to repeatedly spam the logs for each iteration of the run coordinator on blocked runs.
BK

remove log spamming on concurrency blocked runs

---

.buildkite/dagster-buildkite/dagster_buildkite/python_packages.py
.buildkite/dagster-buildkite/setup.py

python packages can be identified with either setup.py or pyproject.toml at their root
buildkite

buildkite - python packages can either have setup.py or pyproject.toml

---

js_modules/dagster-ui/packages/ui-core/src/metadata/TableSchema.tsx

Column schema tags are a little misaligned, fix them by putting them in a wrapping flexbox.
Before:
After:
Add a column schema to an asset, verify that tags render and wrap nicely.

[ui] Fix Asset column schema tags

---

examples/docs_snippets/docs_snippets_tests/deploying_tests/test_monitoring_daemon_examples.py
js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_all_snapshot_ids.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_pipeline_snapshot.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_pipeline_snapshot.py
python_modules/dagster/dagster/_core/definitions/asset_job.py
python_modules/dagster/dagster/_core/definitions/decorators/job_decorator.py
python_modules/dagster/dagster/_core/definitions/graph_definition.py
python_modules/dagster/dagster/_core/definitions/job_definition.py
python_modules/dagster/dagster/_core/definitions/unresolved_asset_job_definition.py
python_modules/dagster/dagster/_core/execution/api.py
python_modules/dagster/dagster/_core/execution/execute_in_process.py
python_modules/dagster/dagster/_core/remote_representation/external.py
python_modules/dagster/dagster/_core/snap/job_snapshot.py
python_modules/dagster/dagster/_daemon/sensor.py
python_modules/dagster/dagster/_scheduler/scheduler.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_unresolved_asset_job.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/test_job_snap.py
python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_job.py
python_modules/dagster/dagster_tests/execution_tests/execute_job_tests/test_job.py
python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py

Add `run_tags` param to `JobDefinition` and associated decorators/functions.
The purpose of this is to introduce separate "definition tag" functionality for `JobDefinition`. Currently `JobDefinition` has a `tags` param where the tags are automatically attached to all runs for the job (i.e. act as "run tags". To support separate "definition tags" and "run tags" while maintaining backcompatibility, this PR introduces the following behavior:
- if the new `run_tags` param is set, only `run_tags` will act as run tags, and `tags` will act only as definition tags
- if `run_tags` is not set, then `tags` acts as both definition and run tags
Note that if `run_tags` is set but the host process is on a version prior to release of this PR, then it will not work correctly-- the definition tags will be …

[definition-tags] Add new `run_tags` param to JobDefinition and associated constructs

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_sensors.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql/schema/sensors.py
python_modules/dagster/dagster/_core/remote_representation/__init__.py
python_modules/dagster/dagster/_core/remote_representation/external.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster/_daemon/sensor.py
python_modules/dagster/dagster_tests/core_tests/host_representation_tests/test_external_data.py

Renames:
- `ExternalTargetData` -> `TargetSnap`
- rename associated methods that reference "external targets"

[external-renames] ExternalTargetData -> TargetSnap

---

examples/tutorial_notebook_assets/setup.py
pyright/alt-1/requirements-pinned.txt
pyright/master/requirements-pinned.txt

This install the `jwt` package which conflicts with `pyjwt` and screws up our pyright env.
@jamiedemaria confirms we no longer need this anyawy.
pyright, existing test suite
NOCHANGELOG

remove papermill-origami dependency

---

python_modules/dagster/dagster/_core/definitions/metadata/table.py

This docblock uses `required = True` in `TableColumnConstraints`, but the API appears to be `nullable = False` based on the definition elsewhere in the file. This updates the doc accordingly.
I didn't, but this is a doc only change.
NOCHANGELOG

[documentation] Fix incorrect example of TableColumnConstraints

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/ExpandedGroupNode.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeLineageGraph.tsx
js_modules/dagster-ui/packages/ui-core/src/graph/SVGComponents.tsx

Fixes FE-570
I'd seen this happen a couple other times -- Safari seems to have an annoying bug where you can't "position" the first DOM node inside a foreignObject. To use things like marginTop / top / inset, etc. we have to have at least one div above the positioned one in the foreignObject.
I created a named wrapper for this case because I think I'm likely to drive-by and remove this wrap layer otherwise :-) 
Tested in Firefox, Chrome and Safari
Before:
After:

[ui] Fix asset group outlines not rendering properly in Safari

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py

This PR puts the dag downstream of the automapped tasks.
BK. Viewed in kitchen sink.
NOCHANGELOG

Put dags downstream of automapped tasks

---

js_modules/dagster-ui/packages/ui-components/src/components/TokenizingField.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunsFilterInput.tsx

Hooks up the "show runs within backfills" checkbox to the backend
View with runs in backfills hidden (default view)
View showing runs in backfills 
NOCHANGELOG

show runs within backfill checkbox

---

examples/experimental/dagster-airlift/dagster_airlift/core/sensor.py

First step of allowing a callback to the sensor. We factor out a pluggable implementation for the translation of getting a set of asset events from airflow task/dag runs.
Existing test behavior
NOCHANGELOG

[dagster-airlift] factor out pluggable impl from sensor

---

examples/experimental/dagster-airlift/dagster_airlift/constants.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_sensor.py

Separate out the notion of "effective timestamp", which is used for actual ordering purposes, from the pretty metadata we display.
With a pluggable implementation, we need a consistent way of retrieving ordering information even though users might be constructing god knows what.
Existing tests
NOCHANGELOG

[dagster-airlift] introduce effective timestamp

---

js_modules/dagster-ui/packages/ui-core/src/automation/MergedAutomationRoot.tsx

When determining whether to show a code location bucket in the Automations page, repos with 1+ schedules and zero sensors were being incorrectly ignored. The result was an empty Automations page even though there were schedules that should have appeared.
View an org with a single code location that has schedules but not sensors. Verify that the Automations page now shows them correctly.

[ui] Fix Automations page when only schedules present

---

python_modules/dagster-graphql/dagster_graphql/implementation/asset_checks_loader.py
python_modules/dagster-graphql/dagster_graphql/implementation/execution/__init__.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_asset_condition_evaluations.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
python_modules/dagster-graphql/dagster_graphql/implementation/loader.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql/schema/external.py
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
python_modules/dagster-graphql/dagster_graphql/schema/solids.py
python_modules/dagster/dagster/_core/definitions/asset_graph_differ.py
python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
python_modules/dagster/dagster/_core/remote_representation/external.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster/_core/telemetry.py
python_modules/dagster/dagster/_core/workspace/workspace.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py
python_modules/dagster/dagster_tests/cli_tests/workspace_tests/test_repository_load.py
python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py
python_modules/dagster/dagster_tests/core_tests/host_representation_tests/test_custom_repository_data.py
python_modules/dagster/dagster_tests/core_tests/host_representation_tests/test_external_data.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/base_scenario.py

Internal companion PR: https://github.com/dagster-io/internal/pull/8998
Renames:
- `ExternalAssetNode` -> `AssetNodeSnap`
- `ExternalAssetDependency` -> `AssetParentEdgeSnap`
- `ExternalAssetDependedBy` -> `AssetChildEdgeSnap`
- a bunch of private methods and local variables that were inflections of "external asset node"
Note that "parent"/"child" terminology was used for renames because it is consistent with the terminology used in `AssetGraph`.
Also:
- `external_asset_nodes_from_defs` renamed to `asset_node_snaps_from_repo`, now just takes a `RepositoryDefinition`

[external-renames] Rename ExternalAssetNode and associates

---

python_modules/dagster-graphql/dagster_graphql/implementation/asset_checks_loader.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_checks.py
python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
python_modules/dagster/dagster/_core/remote_representation/external.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster/_core/workspace/workspace.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py
python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py
python_modules/dagster/dagster_tests/core_tests/host_representation_tests/test_custom_repository_data.py

Internal companion PR: https://github.com/dagster-io/internal/pull/9020
- Rename `ExternalAssetCheck` -> `AssetCheckNodeSnap`. This matches `AssetNodeSnap`. 
- Rename various private methods and local variables that were inflections of "external asset check"

[external-renames] Rename ExternalAssetCheck -> AssetCheckNodeSnap

---

python_modules/dagster-graphql/dagster_graphql/schema/resources.py
python_modules/dagster/dagster/_core/remote_representation/external.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/test_repository_snap.py

Renames:
- `ExternalResourceData` -> `ResourceSnap`
- `ExternalResourceValue` -> `ResourceValueSnap`
- `ExternalResourceConfigEnvVar` -> `ResourceConfigEnvVarSnap`
- `external_resource_data_from_def` -> `ResourceSnap.from_def`

[external-renames] ExternalResourceData -> ResourceSnap

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/sensors.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_sensors.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_instigation.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py
python_modules/dagster/dagster/_core/definitions/asset_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/decorators/sensor_decorator.py
python_modules/dagster/dagster/_core/definitions/multi_asset_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/sensor_definition.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster_tests/core_tests/definitions_tests/decorators_tests/test_sensor_decorator.py

Add standard `metadata` to `@sensor`, `SensorDefinition`, and all sensor subclasses.
Threading metadata through the serdes layer was slightly complicated by the presence of an existing `ExternalSensorMetadata` object with a single field `asset_keys` that is already passed as `SensorSnap.metadata`. This was added three years ago before we had the standard of using a `Mapping[str, MetadataValue]` on all definitions.
I attached the standard metadata as `standard_metadata` on this object rather than placing it directly on `SensorSnap`, since `SensorSnap.metadata` was already taken.
NOCHANGELOG

Add metadata to sensors

---

js_modules/dagster-ui/packages/ui-core/src/asset-data/__tests__/AssetLiveDataProvider.test.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/Utils.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/__fixtures__/AssetNode.fixtures.ts
js_modules/dagster-ui/packages/ui-core/src/asset-graph/__tests__/Utils.test.tsx

Fixes FE-535
Currently, If you have an asset run that fails to emit a materialization event, and you fix that failure by manually reporting a materialization event, the “Failed in Run XYZ” state is still shown everywhere in Dagster’s UI. This is undesirable especially on the asset graph, but also on the asset catalog page where the failure appears under the subheading “Latest materialization”
This PR adds a new rule: The “Failed to materialize” status, banner, and asset health alert only appear if the latest materialization is older than the run’s timestamp.
This also makes the UI consistent with what it /said/ it already did — our component for displaying the failure banner was already called  `<FailedRunSinceMaterializationBanner />`. :-)
I tested this using …

[ui] Only show “materialization failed in run” if the latest materialization is older

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
examples/experimental/dagster-airlift/dagster_airlift/core/airflow_instance.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization/serialized_data.py
examples/experimental/dagster-airlift/dagster_airlift/test/airflow_test_instance.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_dag_asset_keys.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_sensor.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/dbt_tests/test_dbt_defs.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/constants.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example_tests/integration_tests/test_e2e.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink_tests/integration_tests/test_e2e_automapped.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink_tests/integration_tests/test_e2e_mapped.py
examples/experimental/dagster-airlift/examples/perf-harness/perf_harness/cli.py
examples/experimental/dagster-airlift/examples/perf-harness/perf_harness_tests/test_e2e.py
examples/experimental/dagster-airlift/examples/tutorial-example/README.md
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/peer_with_check.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_peer_with_check_e2e.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_peering_e2e.py

Previously all dag and automapped asset keys were hardcoded to "airflow_instance" which was not desirable. This diff does a few things
* Defaults to `airflow_instance.name` instead of `"airflow_instance"`.
* Changes airflow instance name to be a valid dagster name so it can be incorporated in definition names.
* Changes sensor names for airflow polling sensor to include instance name.
BK
Added unit test to load from two test instances.
NOCHANGELOG

Make instance name parameterizable

---

python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/storage/legacy_storage.py
python_modules/dagster/dagster/_core/storage/runs/base.py
python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py
python_modules/dagster/dagster_tests/storage_tests/test_run_storage.py
python_modules/dagster/dagster_tests/storage_tests/utils/run_storage.py
python_modules/libraries/dagster-mysql/dagster_mysql_tests/test_run_storage.py
python_modules/libraries/dagster-postgres/dagster_postgres_tests/test_run_storage.py

Adds `get_backfills_count` method to return the number of backfills that match a given filter
corresponding internal pr https://github.com/dagster-io/internal/pull/11795
NOCHANGELOG

add get_backfills_count

---

js_modules/dagster-ui/packages/ui-core/src/app/useVisibleFeatureFlagRows.oss.tsx

enables the Runs feed feature flag and adds a link to the github discussion i created to get feedback

enable RunsFeed feature flag

---

integration_tests/test_suites/auto_materialize_perf_tests/test_asset_daemon_perf.py
python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/automation_tick_evaluation_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_evaluator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_tester.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/slice_conditions.py
python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_result_value_hash.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/backfill_simple.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/backfill_with_runs_and_checks.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_backfills_requested.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_e2e.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/legacy_tests/test_auto_observe.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/asset_daemon_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/automation_condition_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/base_scenario.py

The previous behavior when enabling DA to emit backfills was to *always* emit a backfill regardless of it was required or not.
This updates the behavior to only emit a backfill when more than one partition is requested for a given asset at one time.
If a backfill is required, the system will group together all "touching" assets into a single backfill to ensure that execution order is respected.
This means that it is possible for the system to request multiple backfills and multiple runs on the same tick.
NOCHANGELOG

Allow DA to selectively emit backfills

---

python_modules/dagster/dagster/_core/definitions/metadata/table.py
python_modules/dagster/dagster_tests/core_tests/test_metadata.py
python_modules/dagster/dagster_tests/definitions_tests/metadata_tests/test_table_metadata_set.py

Introduces a new `tags` field to `TableColumn` which can be used to encode additional tag-style information to tabular assets' columns.
Use-cases include:
- Carrying over tags from dbt #24718
- Marking PII information
- Marking primary keys in databases or keys used in ETL syncs 
Eventually, these tags should be made searchable in Cloud.
NOCHANGELOG

[1/c] add column tag field to TableColumn

---

docs/content/integrations/deltalake/using-deltalake-with-dagster.mdx

When running this tutorial, the current asset definition errors out with a `NameError: name 'iris_dataset' is not defined`. This PR contains a quick workaround that does run. Probably this could be solved in a better way.
Reloading definitions and running `dagster dev` locally.

update iris_dataset asset definition in Delta Lake integration tutorial

---

docs/content/integrations/dbt/reference.mdx

Without the additional config the model wouldn't be idempotent, as the incremental would be append only and rerunning a date would insert those again.
When using `delete+insert`, the `unique_key` doesn't actually need to be unique (in comparison to `merge` that would fail if `unique_key` is not unique)
Docs update
N/A

Update config dbt incremental model with partitions

---

docs/dagster-university/pages/dagster-dbt/lesson-5/4-automating-dbt-models-in-dagster.md

[du] fixing imports for build_selection_from_dbt_something

---

docs/content/community/contributing.mdx
js_modules/dagster-ui/packages/ui-core/src/instance/InstanceConcurrency.tsx

- Fix a layout issue when Dagster displays warning of unsupported run coordinator.
- Update a reference to obsolete job script name in `contributing.mdx`
Before
After

fix(ui/instance): correct padding when display warning unsupported run coordinator

---

js_modules/dagster-ui/packages/ui-core/src/app/Util.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/HourlyDataCache/HourlyDataCache.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/HourlyDataCache/__tests__/HourlyDataCache.test.tsx
js_modules/dagster-ui/packages/ui-core/src/search/__tests__/useIndexedDBCachedQuery.test.tsx
js_modules/dagster-ui/packages/ui-core/src/search/useIndexedDBCachedQuery.tsx

Some users are hitting [this issue](https://issues.chromium.org/issues/369636250) so lets degrade gracefully incase we can't rely on indexeddb.
I'm banking on this line https://github.com/make-github-pseudonymous-again/idb-lru-cache/blob/main/src/mod.ts#L322 being the problematic line that throws the error since it leads to this line https://github.com/jakearchibald/idb/blob/main/src/entry.ts#L70
I forced an error and loaded the app and saw that we could still load code locations.
Also added jest tests

Wrap IndexeddbDB usage with try/catch and degrade gracefully.

---

python_modules/dagster/dagster/_core/execution/compute_logs.py

https://github.com/dagster-io/dagster/issues/23336
- I work on mac (comes with posix tail instead of gnu tail), so I [installed gnu tail](https://apple.stackexchange.com/questions/410513/in-mac-how-to-do-tail-f-pid-to-terminate-after-process-exit-like-linux) to run with `--pid` locally.
```
~ > tail --help                                                                                                                                                                  ✔  22:36:02
tail: unrecognized option `--help'
usage: tail [-F | -f | -r] [-q] [-b # | -c # | -n #] [file ...]
~ > gtail --help                                                                                                                                                               1 ✘  22:36:06
Usage: gtail [OPTION]... …
```

Add an opt-in delay after compute logs finish to ensure that the captured logs are redirected back to stdout/stderr

---

examples/experimental/dagster-airlift/dagster_airlift/core/multiple_tasks.py

Messed up and had this commit locally. This makes the docstring on `targeted_by_multiple_tasks` accurate with the latest changes.
Look
NOCHANGELOG

Fixing comment on targeted_by_multiple_tasks

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py
python_modules/dagster/dagster/_core/definitions/asset_out.py
python_modules/dagster/dagster/_core/definitions/asset_spec.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py

Introduces a `kinds` parameter to `AssetSpec`, sugar which converts immediately into the kind tags introduced in #23779. This PR properly introduces kinds as a user-facing input, so hoping to center conversation around those APIs here.
Unit tests.

Add kinds parameter to AssetSpec

---

python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/dbt_packages/test_columns_metadata.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_metadata/models/schema.yml

Surfaces dbt column tags in the new `TableColumn` tags field introduced in #24717. These will flow into table column search and UI, once built.
New unit test.
NOCHANGELOG

[dagster-dbt] populate column tags for dbt

---

.github/ISSUE_TEMPLATE/report_bug.yml

Move Dagster Version input lower down the order of inputs. Helps when previewing content in Pylon tickets for the first input to be the issue's description.
👀
NOCHANGELOG

Move Dagster Version input lower in report_bug.yml

---

python_modules/libraries/dagster-polars/dagster_polars/io_managers/base.py
python_modules/libraries/dagster-polars/dagster_polars_tests/test_upath_io_managers_lazy.py

[dagster-polars] fix loading missing LazyFrames

---

python_modules/dagster/dagster/_serdes/serdes.py

Remove bound on `T_NamedTuple` typevar used for custom serializers and add explanatory comments. Also alias `NamedTupleSerializer` to `RecordSerializer`.
NOCHANGELOG

Relax bound on NamedTupleSerializer type variable

---

examples/experimental/dagster-airlift/dagster_airlift_tests/test_version.py
examples/experimental/dagster-airlift/setup.py

As the title. We need to pin dagster to >=1.8.8 for multiple kinds and changes to lazy definitions.
Test version
NOCHANGELOG

[dagster-airlift] pin dagster on non-dev installs

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
examples/experimental/dagster-airlift/dagster_airlift/core/load_defs.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/__init__.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/builder.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/event_translation.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization/serialized_data.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py

Part of my ultimate scheme to turn AirflowDefinitionsData into a user-invokable class that can be used to vend cacheable properties off of the fully resolved Definitions object. Let's make it non-serializable, and we'll eventually move all spec mapping utilities to the serializable class, so that AirflowDefinitionsData is purely an information retrieval layer and not a transformation layer.
NOCHANGELOG

[dagster-airlift] make AirflowDefinitionsData non serializable, make loader use serializable class

---

examples/experimental/dagster-airlift/dagster_airlift/constants.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/base_proxy_operator.py
examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_dagster_operator.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink_tests/integration_tests/test_e2e_mapped.py

Add a tag `"dagster-airlift/dag-run-id"` to every launched run in Dagster that contains the _airfllow_ dag run id that sources it.
This will allow us to query for dagster runs that are associated with a specific dag run id.
Included tests. Also manually confirmed it appears in the UI
NOCHANGELOG

Add dag_id tag to base_proxy_operator.py

---

examples/experimental/dagster-airlift/dagster_airlift/in_airflow/base_proxy_operator.py

Extract graphql response handling to a common helper method in the proxy operator. While not totally robust, it will at least report the entireity of the graphql response consistently.
Manually used this to debug issues.
Injected error and saw response:
NOCHANGELOG

Better response handling in the proxy operator

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
examples/experimental/dagster-airlift/dagster_airlift/core/load_defs.py
examples/experimental/dagster-airlift/dagster_airlift/core/utils.py

Changes parameterization to retrieve serialized data from Definitions. 
Requires an additional pr for the instance name. 
A downstream will change this to only look at the asset metadata, instead of relying on the serialized metadata (except for migration state for dags/tasks, which we're waiting on the airflow conf to change)
Existing tests
NOCHANGELOG

[dagster-airlift] change AirflowDefinitionsData to operate on fully resolved definitions

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
examples/experimental/dagster-airlift/dagster_airlift/core/load_defs.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
examples/experimental/dagster-airlift/dagster_airlift/core/utils.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py

Previously, the properties on AirflowDefinitionsData which retrieved information about asset keys did so from the information gathered during the serialization compute step. In a world where the sensor can be built separately from the mapped definitions, we need to be able to handle any additional mapping steps that the user might perform.
NOCHANGELOG

[dagster-airlift][mapped-defs] asset properties on AirflowDefinitionsData use resolved defs

---

examples/experimental/dagster-airlift/dagster_airlift/k8s/__init__.py
examples/experimental/dagster-airlift/dagster_airlift/k8s/asset.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/k8s_tests/test_k8s_pod_defs.py
examples/experimental/dagster-airlift/setup.py
examples/experimental/dagster-airlift/tox.ini
python_modules/libraries/dagster-k8s/dagster_k8s/ops/k8s_job_op.py

Uses PipesK8sClient to new up a pod similar to the behavior seen in AirflowK8sPodOperator.
I opted to not have the same arguments that the K8sPodOperator has, and instead have an intensive docstring that describes how to map the airflow k8spodoperator arguments onto the k8s config API. This was a bit painstaking, but removes actual complexity from our end and foists some small modicum of complexity onto the user (and gets them to use better practice, IMO).
Manual testing covered here: https://github.com/dagster-io/dagster/pull/24675
Added a unit test for the construction.
`NOCHANGELOG`

[dagster-airlift][k8s] k8s_pod_defs

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/builder.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization/serialized_data.py

This makes our reliance on the serialized data within the sensor explicit. These callsites should both eventually be eliminated in favor of approaches which don't require the serialized data.
Existing tests
NOCHANGELOG

[dagster-airlift][mapped-defs] make explicit our reliance on the serialized data within sensor

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_instance.py
examples/experimental/dagster-airlift/dagster_airlift/test/airflow_test_instance.py

Airflow uses isoformat strings for run ids, and returned times from the rest API. Let's standardize on the isoformat utils from datetime.
NOCHANGELOG

[dagster-airlift][partitions] standardize timing formats

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_instance.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/event_translation.py
examples/experimental/dagster-airlift/dagster_airlift/test/airflow_test_instance.py
examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_airflow_instance.py

DagRun.start_date,end_date is confusingly a float (same for TaskInstance). Instead, make it a fully-fledged datetime and call `.timestamp()` when needed
Existing tests
NOCHANGELOG

[dagster-airlift][partitions] standardize on datetime properties

---

js_modules/dagster-ui/packages/ui-core/src/app/App.tsx
js_modules/dagster-ui/packages/ui-core/src/app/AppTopNav/AppTopNav.tsx
js_modules/dagster-ui/packages/ui-core/src/app/LayoutProvider.tsx
js_modules/dagster-ui/packages/ui-core/src/app/UserSettingsButton.tsx
js_modules/dagster-ui/packages/ui-core/src/nav/LeftNav.tsx

A few changes to the behavior of the new IA flag.
- Restore the left nav, and only show it by sliding over the main content, even for large screens.
- Allow immediately turning off the flag via the Alert at the top of the app.
- Restore the gear button in the top nav for users in the flag.
Load the app with the flag on and off, verify that the left nav and gear button render and behave as expected. Click to turn the flag off via the Alert, verify that it works correctly.
NOCHANGELOG

[ui] Update nav flag behavior

---

docs/docs-beta/.cursorrules
docs/docs-beta/docs/reference/workspace-yaml.md
docs/vale/styles/config/vocabularies/Dagster/accept.txt

Adds a reference doc for workspace.yaml.
I used the following as references:
https://docs.dagster.io/concepts/code-locations/workspace-files
https://github.com/dagster-io/cloud-examples/blob/main/multi-location-project/workspace.yaml 
https://github.com/dagster-io/dagster/blob/618731246cf220c0257f5d030e8c4eaf68b5d8b1/docs/content/concepts/code-locations.mdx#L121 
I read them
NOCHANGELOG

[docs-beta] Add workspace.yaml [DOC-437]

---

python_modules/libraries/dagster-gcp/dagster_gcp/gcs/file_manager.py

Ran into an issue with `GCSFileManager` not grabbing all the data from a blob. The temporary file handle has all the data, but the actual file on disk does not.
Flushing the temporary file immediately after the blob download ensures all the data is written to the temporary file.
Manually in Python REPL

flush temp_file_obj after blob download

---

js_modules/dagster-ui/packages/ui-components/src/components/Alert.tsx
js_modules/dagster-ui/packages/ui-components/src/components/ButtonLink.tsx
js_modules/dagster-ui/packages/ui-components/src/components/MetadataTable.tsx
js_modules/dagster-ui/packages/ui-core/src/app/LayoutProvider.tsx
js_modules/dagster-ui/packages/ui-core/src/app/time/TimestampFormat.tsx
js_modules/dagster-ui/packages/ui-core/src/schedules/SchedulesNextTicks.tsx
js_modules/dagster-ui/packages/ui-core/src/schedules/TimestampDisplay.tsx
js_modules/dagster-ui/packages/ui-core/src/ui/Loading.tsx

With the Blueprint upgrade, `defaultProps` warnings are spamming the app in dev. Clean these up.
TS, lint, jest
NOCHANGELOG

[ui] Eliminate defaultProps

---

js_modules/dagster-ui/packages/ui-core/src/app/App.tsx
js_modules/dagster-ui/packages/ui-core/src/app/AppTopNav/AppTopNavLinks.tsx
js_modules/dagster-ui/packages/ui-core/src/app/FeatureFlags.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/app/UserSettingsDialog/UserSettingsDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/app/__tests__/AppTopNav.test.tsx
js_modules/dagster-ui/packages/ui-core/src/app/useVisibleFeatureFlagRows.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/auto-materialization/AutomaterializationRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/overview/OverviewRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/overview/OverviewTabs.tsx
js_modules/dagster-ui/packages/ui-core/src/settings/SettingsMainPane.tsx

Enable the new navigation UI by flipping the feature flag to be a "revert to legacy nav" flag, turned off by default.
- Replace all `flagSettingsPage` with `flagLegacyNav`, flip the logic at each callsite.
- Add a `trackEvent` call to start observing feature flag change events (Plus only)
Load app. Verify that the app has the updated nav without my changing any flags. Verify behavior of new flag to revert to old nav.

[ui] Flip navigation feature flag

---

python_modules/dagster/dagster/_core/definitions/repository_definition/repository_data.py
python_modules/dagster/dagster/_core/definitions/repository_definition/repository_data_builder.py
python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py

In the course of implementing `map_asset_specs`, I noticed an oddity / gap in how we handle canonicalized asset check definitions.
During construction of `Definitions`, we canonicalize `AssetChecksDefinition` objects to `AssetsDefinition` objects. However, if these are then passed in to construct a new `Definitions` object, then they are ignored. This PR addresses that.

stop ignoring AssetsDefinitions with only checks passed to Definitions

---

js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillActionsMenu.tsx

We renamed the view button for runs, but missed it for backfills - this make the button "View" instead of "view runs" 
before 
after
NOCHANGELOG

change backfill view runs button to view

---

python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py

Was getting a warning like this
```
/Users/jamie/dev/dagster/python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py:304: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
query = query.where(RunsTable.c.run_id.notin_(db_subquery(runs_in_backfills)))
```
This removes the unnecessary conversion to a subquery, so now the error is gone
Ran the UI locally, saw that the warning was gone
NOCHANGELOG

remove unecessary conversion to subquery in run storage

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/usePartitionHealthData.tsx
js_modules/dagster-ui/packages/ui-core/src/partitions/AssetJobPartitionsView.tsx

Currently AssetJobPartitionsView ends up fetching partition information for every asset in the job. This PR updates it to only do it for partitioned assets because those are the assets that would have any partition information...
app-proxy
Saw that a job with a hundred asset keys only fetched partition information for the 6 assets that have partititons.

Skip fetching partition information for unpartitioned assets

---

js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedRow.tsx

Planned to include this in https://github.com/dagster-io/dagster/pull/24915 but it got dropped (idk). 
The mode tag is relic from when there were PipelineModes (solid, pipeline days) but some of the UI still thinks they should be around. This sets the mode to 'default' so that the UI doesn't display it as a tag
👀 
before - tags has a "view all tags" and the pop up has a mode tag
after 
NOCHANGELOG

set mode tag for runs feed entries to 'default' so that it doesn't get displayed in runs feed

---

python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py

we check if `repo` is `None` below so accidentally using that variable name causes things to break
will follow up with automated test

[graphql] avoid using outerscoped repo variable in resolve_assetNodes

---

python_modules/dagster/dagster/_core/definitions/metadata/table.py

run a script on a specific snapshot to verify snapshot id is now stable

prevent TableColumn.tags from shifting job snapshot id

---

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/asset_graph_view/entity_subset.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/__init__.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_automation_condition_tester.py

Right now, we allow users to apply an arbitrary AutomationCondition against all of its dependencies.
However, there is no way for a user to apply an arbitrary AutomationCondition against an arbitrary non-dependency.
```
pytest python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_automation_condition_tester.py::test_asset_matches
```
Add AutomationCondition.asset_matches() capability

[FOU-402] Add AutomationCondition.asset_matches() capability

---

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_evaluator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/check_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py
python_modules/dagster/dagster_tests/asset_defs_tests/asset_graph_view_tests/test_basic_asset_graph_view.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_result_value_hash.py

Now that we have `EntityMatchesCondition`, we can replace `DepConditionWrapperCondition` and `CheckConditionWrapperCondition`. Can also clean up the implementation of `compute_parent_subset` and `compute_child_subset` using the new `compute_mapped_subset`.

Remove condition wrapper conditions

---

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/resources.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/sling_tests/test_asset_decorator.py

Pull `target` from a sling replication config and use it as a destination name create a relation identifier when a sling asset is materialized.
BK with new test + tested with a test pipeline.
[dagster-embedded-elt] relation identifier metadata is now attached to sling assets.

[dagster-embedded-elt] Add relation identifier metadata to sling assets

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetEventDetail.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetPartitionDetail.tsx

As title -- keeps this view around for the overdue tag (which is hidden behind a popover).
This mostly useful to give information relevant to the now-deprecated FreshnessPolicy abstraction, and these queries can be very expensive.
NOCHANGELOG

Remove AssetMaterializationUpstreamData view from materialization views

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/asset_defs.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/types.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/test_asset_defs.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/test_load_from_instance.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/test_load_from_project.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/utils.py

Pull `configuration.database` and `configuration.schema` from Airbyte destinations when loading assets Airbyte. Works for a project and an instance.
Also, `destination_table` and `destination_schema` can now be passed to `build_airbyte_assets()` when creating assets for Airbyte Cloud. Currently, we don't fetch connection details for Airbyte Cloud, and users can only create Airbyte assets using `build_airbyte_assets()`, so destination details must be manually provided to create the relation identifier metadata in this use case.
Join this with known schema and table info to produce a full `dagster/relation_identifier`.
BK with new and updated tests + tested with an instance and a project.
[dagster-airbyte] relation identifier metadata is now attached to Airbyte assets.

[dagster-airbyte] Add relation identifier metadata to Airbyte assets

---

examples/docs_beta_snippets/docs_beta_snippets/guides/tutorials/etl_tutorial/etl_tutorial/definitions.py

The unit test that validates that our `docs_beta_snippets` example load uses the following:
```
spec = importlib.util.spec_from_file_location("module", file_path)
assert spec is not None and spec.loader is not None
module = importlib.util.module_from_spec(spec)
try:
spec.loader.exec_module(module)
except Exception as e:
pytest.fail(f"Failed to load {file_path}: {e!s}")
```
It appears that this doesn't play well with our loader functions:
```
all_assets = dg.load_assets_from_current_module()
all_asset_checks = dg.load_asset_checks_from_current_module()
```
This pull request replaces these with hard-coded asset names--though admittedly this is less elegant.
`tox -e all`
NOCHANGELOG

[docs-beta-snippets] fix broken unit test in `module_from_spec`

---

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/resources.py

The current implementation explicitly tries to access the returned value through the `"ct"` key. This has led to a `KeyError` for us.
Whether the column name alias `"ct"` is upper or lowercase depends on the backend system. While DuckDB returns lowercase, which makes the tests pass, the Snowflake connection returns `"CT"`. By instead iterating once over the `dict_values`, we do not need to use a key to access the row count.
Ran all unit tests for Sling.
Sling's `fetch_row_count()` method now works for databases returning uppercase column names.

[dagster-embedded-elt] fix `KeyError` when fetching Sling `row_count`

---

examples/experimental/dagster-airlift/dagster_airlift/constants.py
examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
examples/experimental/dagster-airlift/dagster_airlift/core/load_defs.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/builder.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/event_translation.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization/defs_construction.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization/serialized_data.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/base_proxy_operator.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_airflow_asset_mapping.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_sensor.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/in_airflow_tests/test_parse_metadata.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/airflow_dags/print_dag.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/airflow_dags/proxied_state/print_dag.yaml
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/dagster_defs/automapped_defs.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/dagster_defs/mapped_defs.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink_tests/integration_tests/test_e2e_automapped.py

This PR makes it so that automapped tasks get materialization history.
The major change here is to 
1) Add the `dagster_airlift/task_mapping` metadata entry to automapped tasks AND
2) Have the sensor fetch all task_ids rather than just the ones with explicit mappings.
The second point results in more fetching in the case where the user will _not_ do automapped tasks. However I do think that is the default and I commented inline what the workaround would be.
BK. Manually tested in kitchen sink.
Then ran an unproxied dag:
NOCHANGELOG

[dagster-airlift] Make autopeered tasks produce synthetic materializations

---

js_modules/dagster-ui/packages/ui-core/src/runs/LogsToolbar.tsx

The Blueprint upgrade broke the step selector in the Run logs toolbar. Fix it by giving it a container with some width.
It would probably make sense to try to clean up the `GlobalSuggestStyle` styles to see if they can be simplified altogether, but I'm hesitant to risk breaking other `Suggest` right this second.
View Run, switch to stdout logs. Verify that the suggest component input has width.

[ui] Fix logs toolbar step selector width

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py
python_modules/dagster-graphql/dagster_graphql/implementation/utils.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql/schema/external.py
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
python_modules/dagster-graphql/dagster_graphql/schema/solids.py
python_modules/dagster/dagster/_cli/job.py
python_modules/dagster/dagster/_core/definitions/asset_graph.py
python_modules/dagster/dagster/_core/definitions/asset_graph_differ.py
python_modules/dagster/dagster/_core/definitions/freshness_based_auto_materialize.py
python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
python_modules/dagster/dagster/_core/execution/asset_backfill.py
python_modules/dagster/dagster/_core/execution/submit_asset_runs.py
python_modules/dagster/dagster/_core/remote_representation/code_location.py
python_modules/dagster/dagster/_core/remote_representation/external.py
python_modules/dagster/dagster/_core/remote_representation/handle.py
python_modules/dagster/dagster/_core/workspace/context.py
python_modules/dagster/dagster/_core/workspace/workspace.py
python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_repository.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_external_asset_graph.py
python_modules/dagster/dagster_tests/cli_tests/command_tests/test_telemetry.py
python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py
python_modules/dagster/dagster_tests/daemon_tests/test_queued_run_coordinator_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/asset_policy_sensors_tests/test_default_auto_materialize_sensors.py
python_modules/libraries/dagster-celery-k8s/dagster_celery_k8s_tests/test_launcher.py
python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_executor.py
python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_launcher.py

In an effort to make `RemoteAssetNode` serializable, have it use a simple pointer to know which code location / repo it came from. 

[RemoteAssetNode] move from RepositoryHandle to RepositorySelector

---

examples/experimental/dagster-airlift/dagster_airlift/core/load_defs.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/__init__.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/builder.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/event_translation.py

This change removes the `get_asset_events` function and updates related imports and function calls. The `event_translation_fn` parameter is now optional in the `build_airflow_polling_sensor_defs` function. These modifications simplify the event translation process in the Dagster Airlift integration with Airflow.
To test these changes, I:
Existing tests
NOCHANGELOG

[dagster-airlift][sensor] Get rid of unused get_asset_events

---

examples/experimental/dagster-airlift/dagster_airlift/core/load_defs.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/__init__.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/builder.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/event_translation.py

Moves sorting of events to the end of the sensor's iteration loop. This provides a clearer pluggability point where we have access to all the events, but they haven't been sorted yet.
Existing tests
NOCHANGELOG

[dagster-airlift][sensor] Move sorting to end of loop

---

.buildkite/dagster-buildkite/dagster_buildkite/python_packages.py

this was an oversight on my part because I thought `git ls-files .` would include directories. I thought I had verified the resulting packages but I guess was confused because we still traverse explicit packages that are listed. This fixes like in https://app.graphite.dev/github/pr/dagster-io/internal/12014/alerts-fix-build-by-adding-logging-statement-back where we weren't running dagit tests after backend changed
```➜ CLOUD_PROD_ELEMENTL_AGENT_TOKEN=x BUILDKITE_BRANCH=test-testing BUILDKITE_MESSAGE=x BUILDKITE_DOCKER_QUEUE=blah BUILDKITE_MEDIUM_QUEUE=blah BUILDKITE_WINDOWS_QUEUE=blah python .buildkite/pipeline.py | tee /tmp/steps.yaml
From github.com:dagster-io/dagster
* branch                  master     -> FETCH_HEAD
2024-10-03 16:06:38 INFO     Changed files between origin/master …
```

fix python packages logic to account for the fact that ls-files doesn't list directories

---

examples/experimental/dagster-airlift/dagster_airlift/core/load_defs.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/builder.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/event_translation.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/conftest.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_sensor.py

Introduce a pluggability point for the sensor. Only bit that has changed from offline discussion is that I added a context argument so that users can perform their own logging.
Added a new test for pluggable implementation.
Additional testing I would like to do:
- ensure that an error in pluggable fxn doesn't advance the cursor
- ensure that we handle errors in the pluggable function well.
- ensure that we gracefully error when effective timestamp metadata is missing.
NOCHANGELOG

[dagster-airlift][sensor] make sensor implementation pluggable at top level

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_runs.py

This currently does an event log fetch, which can be slow. Instead, get the materializations and observations separately (which is faster) and get the planned asset materializations from the execution plan snapshot (which is also fast)
BK
NOCHANGELOG

More performant way of going from a run to its asset keys in graphql

---

js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedTable.tsx

When using the bulk action menu, the number of backfills being excluded was determined based on the total number of entries in the page, not on the number of selected entries
before - one run selected, but warning says 25 backfills will be ignored
after
one run selected, no warning
one backfill and one run selected, warning says 1 backfill will be ignored

[runs feed ui] display correct number of selected backfills in actions menu

---

python_modules/dagster-graphql/dagster_graphql/implementation/utils.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_permissions.py

Summary:
This ensures that if the inner resolver sets attributes or other metadata on the resolver, that it is still accessible by determined middleware.
Test Plan: BK
Changelog:
NOCHANGELOG

Add functools.wrap to graphql decorators

---

python_modules/libraries/dagster-k8s/dagster_k8s/ops/k8s_job_op.py

The current behavior of execute_k8s_job is to immediately delete a
failed Kubernetes job. This change adds a boolean parameter to control
this behavior so that users and supporting processes (such as log
ingestion tools) have time to access a failed job's pods. The new arg
defaults to True, preserving existing behavior.
I created a Kubernetes job from my local dagster web server using an image I knew would fail, and observed that the job and pod were still visible using `kubectl` when `delete_failed_k8s_job` was set to `False`.
NOCHANGELOG
- [x ] `NEW` _(added new feature or capability)_

Add execute_k8s_job arg to delete failed k8s jobs

---

python_modules/dagster/dagster/_core/pipes/client.py
python_modules/dagster/dagster/_core/pipes/context.py
python_modules/dagster/dagster/_core/pipes/utils.py

Add `on_launched` hook to `PipesMessageReader` which can be used to set `.launched_payload`. 
Seems like it's a good idea to also move `opened_payload` and `launched_payload` attribute annotations to `PipesMessageReader`?
NOCHANGELOG

[dagster-pipes] add on_launched hook to PipesMessageReader

---

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py

Adds an experimental `kinds` parameter to `@asset`, following from the pattern introduced in #24154.
```python
@asset(kinds={"python", "snowflake"}) 
def my_asset():
pass
```
Added the ability to experimentally specify multiple kinds for an asset with the `kinds` parameter.

Add kinds parameter to @asset

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_runs_feed.py

Originally we were showing/hiding subruns by setting `exclude_subruns` on `GrapheneRunsFilter`. This caused an issue with the default behavior for the filter
The existing Runs page and the Runs feed share code for how to create the filters that are applied to the page. 
On the existing runs page, we want all runs shown, but on the runs feed we want to hide runs that are part of backfills by default. Since the two pages use the same code to generate the filters that are sent to the backend, both have `show_runs_within_backfill` as None in the default case. That means the backend needs to determine what to do in this default case. For the existing runs page it's fine, because the filter is always ignored (and there's no way to set in the UI). For the runs feed, we need to convert the `None` …

update runs feed resolver to have runs within backfill exclusion as a separate param

---

js_modules/dagster-ui/packages/ui-core/client.json
js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedTabs.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunsFilterInput.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/types/RunsFeedRoot.types.ts
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_runs_feed.py

Updates the UI to use the new `includeRunsInBackfills` param when fetching the runs feed
modifies the logic for how we generate URLs for the tabbed pages to include whether we are showing the runs within backfills
NOCHANGELOG

[runs feed ui] use updated gql endpoint

---

python_modules/libraries/dagster-tableau/dagster_tableau/resources.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/conftest.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_resources.py

Add `add_data_quality_warning_to_data_source` so that users can add a data quality warning to a Tableau data source with upstream assets are failing asset checks or materialization.
BK with additional unit test
NOCHANGELOG

[dagster-tableau] Implement data quality warning endpoint for data sources

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py

silences the experimental warnings that are thrown when we use the `exclude_subruns` RunsFilter when fetching the runs feed
ran the UI, saw that no experimental warnings were printed
NOCHANGELOG

silence experimental warnings when loading the runs feed

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py
python_modules/dagster-graphql/dagster_graphql/schema/inputs.py

since we aren't using the filter to pass along whether we should show/hide the runs within backfills, we can remove it from the GQL layer.  Any users of this filter would have gotten an experimental warning when they used it, so should be fine to remove
NOCHANGELOG

remove excludeSubruns from GrapheneRunsFilter

---

python_modules/libraries/dagster-github/dagster_github/resources.py
python_modules/libraries/dagster-github/dagster_github_tests/test_resources.py

Contributes to https://github.com/dagster-io/dagster/issues/24967
Tested on my fork with the snippet below:
```python
from dagster import Definitions, asset
from dagster_github import GithubResource
@asset
def github_branch(github_resource: GithubResource):
client = github_resource.get_client()
return client.create_ref("dagster", "marijncv", "refs/heads/master", "refs/heads/test-branch")
assets=[github_branch],
resources={
"github_resource": GithubResource(
github_app_id=<your_app_id>,
github_app_private_rsa_key=<your_rsa_key>,
github_installation_id=<your_installation_id>,
)
},
)
```
& added unit test
[dagster-github] Added `create_ref` method on `GithubClient` that enables creating a new branch

[dagster-github] add create_ref method on GithubClient

---

python_modules/libraries/dagster-aws/dagster_aws/s3/sensor.py

- Uses the `paginator` utility for improved pagination in `list_objects_v2`
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/paginators.html#creating-paginators
`pytest`
NO CHANGELOG

[dagster-aws] use paginator in get_s3_keys

---

python_modules/dagster/dagster_tests/storage_tests/utils/run_storage.py

use a UUID4 for a run id instead of "sldkfjsldf"
ran the unit test

use real run uuid in unit test

---

python_modules/libraries/dagster-tableau/dagster_tableau/resources.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/conftest.py
python_modules/libraries/dagster-tableau/setup.py

Previous implementation worked well when multiple workbooks exist in a workspace, but could not be loaded in Dagster when only one workbook exists. Parsing a XML response with only one workbook would create a JSON object like
`{"workbooks": {"workbook": {"id": "my_id"}}}`
but one with many workbooks would be 
`{"workbooks": {"workbook": [{"id": "my_id_1"}, ..., {"id": "my_id_n"}]}}`
Updates the code to use `tableauserverclient.WorkbookItem` and `tableauserverclient.ViewItem` instead of XML and JSON objects - Tableau handles parsing their API response in these classes.
BK with updated tests.
NOCHANGELOG

[dagster-tableau][fix] Update workbooks and view endpoint

---

python_modules/dagster/dagster/_generate/templates/CODE_LOCATION_NAME_PLACEHOLDER/CODE_LOCATION_NAME_PLACEHOLDER/definitions.py
python_modules/dagster/dagster/_generate/templates/CODE_LOCATION_NAME_PLACEHOLDER/pyproject.toml.tmpl

In this [issue](https://github.com/dagster-io/dagster/issues/24878) Daniel Bartley demonstrates that we can make Dagster compatible with uv by updating the `pyproject.toml` template. This is an opt-in feature that gives users the benefit of being able to have uv manage virutal environments.
Assuming a user has `uv` installed, one can install and run Dagster as follows:
```bash
uvx dagster project scaffold --name dagster-quickstart
cd dagster-quickstart
uv run dagster dev
```
This also fixes a bug in the project scaffold template introduced during a refactor.
The documentation for this will be in a follow-up PR in our docs-beta repo.
Updated the template, installed Dagster as a local editable installed, and confirmed the scaffolding works.

feat: Make Dagster scaffold pyproject compatible with uv

---

python_modules/libraries/dagster-github/dagster_github/resources.py
python_modules/libraries/dagster-github/dagster_github_tests/test_resources.py

Adds a method to `GithubClient` that enables creating a pull request. Contributes to https://github.com/dagster-io/dagster/issues/24967
Unit test & running snippet below:
```python
from dagster import Definitions, asset
from dagster_github import GithubResource
@asset
def github_pull_request(github_resource: GithubResource):
client = github_resource.get_client()
return client.create_pull_request(
"dagster",
"marijncv",
"refs/heads/master",
"dagster",
"marijncv",
"refs/heads/test-branch",
"test-pull-request",
"test-content",
)
assets=[github_pull_request],
resources={
"github_resource": GithubResource(
github_app_id=<app_id>,
github_app_private_rsa_key=<rsa_key>,
github_installation_id=<installation_id>,
)
},
)
```
[dagster-github] Added create_pull_request method on …

[dagster-github] add create_pull_request method on GithubClient

---

docs/content/integrations/embedded-elt/dlt.mdx

The current docs example on customizing the dagster-dlt translator mistakenly type hints the `resource` argument of dagster-dlt translator methods as a `DagsterDltResource`, which maps to a Dagster resource, instead of type-hinting it as a `DltResource`, which maps to a dlt resource.
Not Applicable.
NOCHANGELOG

Fix type of dlt resource in dagster-dlt translator methods.

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNodeMenu.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetActionMenu.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetTable.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/LaunchAssetExecutionButton.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/__fixtures__/AssetTables.fixtures.ts
js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/AssetTables.test.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/LaunchAssetExecutionButton.test.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/useObserveAction.ts
js_modules/dagster-ui/packages/ui-core/src/assets/useReportEventsModal.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/useWipeModal.tsx

Related: https://linear.app/dagster-labs/issue/FE-517/remove-observe-sources-button-add-to-materialize-all-dropdown
Loom:
https://www.loom.com/share/2e044d1117734c2dbfff4fb4bef2a570
This PR folds the Observe Sources button into the Materialize button, which brings the Observe option to the asset catalog! I also updated the asset menus to use the same logic for building their menu items so the behavior is consistent. 
- There's pretty good test coverage of this button and it's updated + still passing
- I tested this manually with observable, materializable, external, and non-SDA assets to kick the tires :-)

[ui] Move Observe Sources into the Materialize button

---

python_modules/dagster/dagster/_core/definitions/asset_in.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_decorators.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/base_scenario.py

match `AssetOut`s typing
since we coerce to `DagsterType` in the construcotr it actually accepts any `Type`
added -> None to existing test to have type checker run on it
Corrected the AssetIn.__new__ typing for the dagster_type argument

update AssetIn dagster_type type

---

python_modules/dagster/dagster/_core/execution/api.py
python_modules/dagster/dagster_tests/execution_tests/dynamic_tests/test_dynamic_output.py

It looks like we erroneously set output_capture in this code path despite it not being used / passed forward. Remove it.
updated test
- [bugfix] execute_job / execute_run with in_process execution should no longer retains unused references to outputs, allowing them to be garbage collected

[execution] removed unused output_capture

---

python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/last_update.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/time_partition.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/utils.py
python_modules/dagster/dagster/_core/event_api.py
python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/conftest.py
python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_last_update_freshness.py

This PR makes it possible to override materialization timestamp for freshness checks.
I also discovered a bug where we weren't rendering "0 seconds" properly in the description, so I fixed that.
New test for this behavior.
NOCHANGELOG

[freshness] override materialization timestamp

---

js_modules/dagster-ui/packages/ui-core/client.json
js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedTabs.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/types/RunsFeedTabs.types.ts
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_runs_feed.py

Updates the runs feed UI to pass the value of the `show runs within backfills` checkbox to the counts query so that we display the correct number of results in the status tabs

incorporate checkbox value when querying for status counts

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_condition_evaluations.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_tester.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/legacy_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/rule_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/__init__.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/slice_conditions.py
python_modules/dagster/dagster/_core/definitions/partition.py
python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_eager_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_initial_evaluation_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_newly_true_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_on_missing_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_automation_condition_tester.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_result_value_hash.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/default_condition.py

Updates the behavior of the `newly_true()` condition to optionally change its "baseline" assumption of what was true before the first evaluation. This allows us to better fulfill the promise of "only reacting to changes which happened after the condition was added to the asset", as we do for the "deps updated" part of the condition.
In short, this provides a strong bit of protection against the "surprise backfill" issue, without having to add any new rate-limiting concepts to the system.
AutomationCondition.eager() will now only launch runs for missing partitions which become missing *after* the condition has been added to the asset. This avoids situations in which the eager policy kicks off a large amount of work when added to an asset with many missing historical static/dynamic …

Update first tick behavior of AutomationCondition.eager()

---

examples/experimental/dagster-airlift/dagster_airlift/in_airflow/base_asset_operator.py
examples/experimental/dagster-airlift/examples/dbt-example/Makefile
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example_tests/integration_tests/test_e2e.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/airflow_dags/print_dag.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/dagster_defs/mapped_defs.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/custom_operator_examples/custom_proxy.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/custom_operator_examples/plus_proxy_operator.py

Because of automapping, we need to filter out non-executable asset nodes instead of just erroring. Instead, error when no nodes available
Existing tests
NOCHANGELOG

[dagster-airlift] unbreak master

---

python_modules/dagster/dagster/_core/pipes/context.py
python_modules/dagster/dagster/_core/pipes/utils.py
python_modules/dagster/dagster_tests/execution_tests/pipes_tests/test_threaded_message_reader.py
python_modules/libraries/dagster-aws/dagster_aws/pipes/message_readers.py
python_modules/libraries/dagster-databricks/dagster_databricks/pipes.py

Sometimes we can only start readings messages (and logs) after the external process has been launched. 
This PR:
- Moves most of `PipesBlobStoreMessageReader`'s functionality into `PipesThreadedMessageReader`
- practically renames `PipesBlobStoreMessageReader` to `PipesThreadedMessageReader` with very little refactoring
- adds `can_read` method. For `PipesBlobStoreMessageReader` it defaults to `True` since it was only used with known locations until now. 
Resolve [FEAT-755](https://linear.app/dagster-labs/issue/FEAT-755/support-reading-pipes-messages-and-logs-from-locations-known-at)

[dagster-pipes] add `PipesThreadedMessageReader`

---

python_modules/dagster/dagster/_record/__init__.py
python_modules/dagster/dagster_tests/general_tests/test_record.py

Currently, `LegacyNamedTupleMixin._replace` is setup using `copy` which goes through the `@record` constructor, using the manually implemented `__new__` if present.
This actually diverges from `namedtuple._replace` which bypasses any custom `__new__` using the tuple `__new__` directly via `_make`. 
We had an issue where a callsite using `_replace` was believed to be a `namedtuple` but was actually a `@record` wtih `LegacyNamedTupleMixin` and this behavior divergence caused an issue. Validation that was expected to be skipped was run and caused an exception.
Avoid this by creating `replace` an alternative to `copy` which bypasses any custom `__new__`. This can be useful when trying to skip certain validation or if the custom `__new__` diverges from the record field set substantially and …

[record] add replace method with namedtuple._replace behavior

---

.buildkite/dagster-buildkite/dagster_buildkite/python_packages.py

not all pyproject.toml files will have dependencies, so gracefully handle that, and log a better error when python package processing fails
https://github.com/dagster-io/internal/pull/11948 failed build with https://buildkite.com/dagster/internal/builds/83302#01926879-ff03-4440-839e-4ae0be6528e6, but I can now run `make pipeline` locally and it succeeds

handle pyproject.toml that doesn't specify dependencies

---

python_modules/dagster/dagster/_core/definitions/partition.py
python_modules/dagster/dagster_tests/core_tests/partition_tests/test_partitioned_job.py

Support returning a `RunConfig` from `PartitionedConfig`. Fixes #20117.
New unit test.
`PartitionedConfig` objects can now return a `RunConfig` without causing a crash.

Support returning RunConfig from PartitionedConfig

---

python_modules/dagster/dagster/_core/definitions/asset_job.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/external_asset.py

When building an assets job, assets needed for loading only (they are immediate dependencies of target assets) are converted into unexecutable assets definitions. This replaces previous behavior where these assets were converted into source assets. The status quo is that this is implemented by converting each asset to a set of source assets, and each source asset to an unexecutable `AssetsDefinition` with one key.
Due to some hairy implementation constraints, it is also the case that unsubsettable multi-assets have _all_ their keys wrapped in this way-- even those that are not actual dependencies of the target assets.
This combination of factors can cause perf difficulties loading code locations in extreme scenarios, where:
- There are many asset jobs in the location (including asset base …

Change asset job construction to create only a single unexecutable assets def per upstream assets def

---

docs/content/dagster-plus/deployment/agents/kubernetes/configuration-reference.mdx
python_modules/libraries/dagster-celery-k8s/dagster_celery_k8s/config.py
python_modules/libraries/dagster-celery-k8s/dagster_celery_k8s_tests/test_launcher.py
python_modules/libraries/dagster-k8s/dagster_k8s/container_context.py
python_modules/libraries/dagster-k8s/dagster_k8s/executor.py
python_modules/libraries/dagster-k8s/dagster_k8s/job.py
python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_container_context.py
python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_executor.py
python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_launcher.py

Provides a hook to add additional metadata configuration (e.g. annotations) when using this class to spin up code servers. Allows us to remove the "labels" argument from K8sContainerContext since it is now redundant.
Requires some changes to the "only_allow_user_defined_k8s_config_fields" config option since there are now explicitly fields that only make sense in a code server context - so use two different paths, one of which considers the run specific config fields, and the other considers the code server fields. Similarly, make "namespace" a top-level thing that you can allowlist instead of asking people to set pod_template_spec_metadata.namespace to allow it - that didn't really make sense anyway since you set the namespace in many different places, not just no the pod.
New / modified …

Add service_metadata and deployment_metadata to UserDefinedDagsterK8sConfig

---

python_modules/dagster/dagster/_cli/api.py
python_modules/dagster/dagster/_core/execution/run_metrics_thread.py
python_modules/dagster/dagster/_core/storage/runs/base.py
python_modules/dagster/dagster_tests/core_tests/execution_tests/test_run_metrics_thread.py

- ensure that the run telemetry function is supported by the instance before starting the thread
- refactors the run metrics thread functionality to reduce code duplication.
- adjusts the default polling intervals. 
Replaces: https://github.com/dagster-io/dagster/pull/23503 - revert behavior to starting the metric collection thread only if the dagster/run_metrics tag is set.
- BK
- Manual testing (retested 2024/09/17)
NOCHANGELOG

refactor: run metric threads startup and shutdown

---

python_modules/dagster/dagster/_core/execution/run_metrics_thread.py
python_modules/dagster/dagster_tests/core_tests/execution_tests/test_run_metrics_thread.py

- Fix edge conditions discovered while working on code server metrics
- Calculate cpu usage rate instead of relying on datadog derivative calculation
- BK / new unit tests
- Manual testing (retested 2024/09/17)

feat: run metrics improvements

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_runs.py
python_modules/dagster/dagster/_core/storage/tags.py

This change introduces a new field `hasRunMetricsEnabled` to the GrapheneRun type in the GraphQL schema. It allows clients to query whether run metrics are enabled for a specific run. The implementation checks for the presence of run metric tags and their boolean values.
This enables hiding the run metrics tag to declutter the frontend of this implementation detail.
- BK w/ added test
NOCHANGELOG

feat: graphql add Run.hasRunMetricsEnabled field

---

python_modules/dagster/dagster/_cli/api.py
python_modules/dagster/dagster/_core/storage/tags.py

We intend to change the triggering mechanism for starting a run metric collection thread from a public to a hidden tag.
NOCHANGELOG

feat: future proofing the tag used to trigger run metrics collection

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py
python_modules/dagster-graphql/dagster_graphql/implementation/utils.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql/schema/external.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
python_modules/dagster-graphql/dagster_graphql/schema/solids.py
python_modules/dagster/dagster/_core/definitions/asset_graph.py
python_modules/dagster/dagster/_core/definitions/asset_graph_differ.py
python_modules/dagster/dagster/_core/definitions/freshness_based_auto_materialize.py
python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
python_modules/dagster/dagster/_core/execution/asset_backfill.py
python_modules/dagster/dagster/_core/execution/submit_asset_runs.py
python_modules/dagster/dagster/_core/remote_representation/external.py
python_modules/dagster/dagster/_core/workspace/workspace.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_external_asset_graph.py
python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py

partial revert of https://github.com/dagster-io/dagster/pull/24824
in the process of solving other issues in that PR I figured out how to make `RepositoryHandle` serializable, and it turns out that theres some information in there its best to keep available to support things like https://github.com/dagster-io/dagster/pull/25122
existing tests

[RemoteAssetNode] move back to RepositoryHandle

---

python_modules/dagster-graphql/dagster_graphql/client/client.py
python_modules/dagster/dagster/_cli/job.py
python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/composition.py
python_modules/dagster/dagster/_core/definitions/dependency.py
python_modules/dagster/dagster/_core/definitions/graph_definition.py
python_modules/dagster/dagster/_core/definitions/job_definition.py
python_modules/dagster/dagster/_core/definitions/node_definition.py
python_modules/dagster/dagster/_core/definitions/partition.py
python_modules/dagster/dagster/_core/definitions/run_request.py
python_modules/dagster/dagster/_core/definitions/schedule_definition.py
python_modules/dagster/dagster/_core/definitions/sensor_definition.py
python_modules/dagster/dagster/_core/definitions/unresolved_asset_job_definition.py
python_modules/dagster/dagster/_core/definitions/utils.py
python_modules/dagster/dagster/_core/execution/plan/step.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_daemon/sensor.py
python_modules/dagster/dagster/_scheduler/scheduler.py
python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_job.py
python_modules/libraries/dagstermill/dagstermill/asset_factory.py
python_modules/libraries/dagstermill/dagstermill/factory.py

Remove the `NormalizedTags` construct from the code. I understand the theory behind this construct (that tags need only be normalized once) but it was used inconsistently in the code and isn't a pattern we use elsewhere. The net effect was to add noise to anything one wants to do with tags.

[definition-tags] Eliminate the NormalizedTags construct

---

python_modules/dagster/dagster/_core/definitions/asset_selection.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection.py

Adds a way to drop all non-materializable assets from a selection, in case a user has downstream non-materializable, external assets within a selection they'd like to ignore
Unit test
- Added AssetSelection.materializable(), which returns only assets that are materializable in an existing selection

Add AssetSelection.materializable selection type

---

python_modules/dagster/dagster/_core/definitions/utils.py
python_modules/dagster/dagster/_core/execution/plan/step.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_daemon/sensor.py
python_modules/dagster/dagster/_scheduler/scheduler.py

Makes it so that `normalize_tags` always warns on deprecated tags.
This flag was only being used in places where (a) we don't need to normalize because tags are already normalized/will be normalized again; or (b) we can just use `disable_dagster_warnings`, which is the standard approach in the codebase to suppressing unwanted warnings.
This is part of a stack that aims to consolidate and simplify tags normalization logic.
NOCHANGELOG

[definition-tags] Remove `warn_on_deprecated_tags` flag from `normalize_tags`

---

python_modules/dagster-graphql/dagster_graphql/client/client.py
python_modules/dagster/dagster/_cli/job.py
python_modules/dagster/dagster/_core/definitions/asset_out.py
python_modules/dagster/dagster/_core/definitions/asset_spec.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/composition.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/job_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/schedule_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/source_asset_decorator.py
python_modules/dagster/dagster/_core/definitions/dependency.py
python_modules/dagster/dagster/_core/definitions/events.py
python_modules/dagster/dagster/_core/definitions/job_definition.py
python_modules/dagster/dagster/_core/definitions/node_definition.py
python_modules/dagster/dagster/_core/definitions/partition.py
python_modules/dagster/dagster/_core/definitions/run_request.py
python_modules/dagster/dagster/_core/definitions/schedule_definition.py
python_modules/dagster/dagster/_core/definitions/sensor_definition.py
python_modules/dagster/dagster/_core/definitions/source_asset.py
python_modules/dagster/dagster/_core/definitions/unresolved_asset_job_definition.py
python_modules/dagster/dagster/_core/definitions/utils.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_utils/tags.py
python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_job.py
python_modules/dagster/dagster_tests/definitions_tests/test_utils.py
python_modules/libraries/dagster-airflow/dagster_airflow/dagster_job_factory.py
python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py
python_modules/libraries/dagstermill/dagstermill/asset_factory.py
python_modules/libraries/dagstermill/dagstermill/factory.py

Move the two separate tags normalization routines to `dagster._utils.tags` and add some explanatory comments.
This is preparation for merging the two routines.
NOCHANGELOG

[definition-tags] Move tags normalization logic

---

python_modules/libraries/dagster-powerbi/dagster_powerbi/resource.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_asset_specs.py

When testing this feature locally against a live PowerBI instance, I ended up using a non-group scoped URL for my personal workspace. These URLs do not work for group-scoped objects.
Update unit test, test against live instance.

[dagster-powerbi] Fix refreshing semantic models on non-personal workspaces

---

js_modules/dagster-ui/packages/ui-core/src/search/BuildAssetSearchResults.tsx
js_modules/dagster-ui/packages/ui-core/src/search/useGlobalSearch.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/assetOwnerAsString.ts

Owners link in the catalog view is broken
Reported here: https://dagsterlabs.slack.com/archives/C06AWMPT3DF/p1728408026154439
https://linear.app/dagster-labs/issue/FE-602/investigate-bug-in-catalog-related-to-owners
Internal PR: https://github.com/dagster-io/internal/pull/12079/files
[dagster plus] Fixed a bug in the catalog UI where owners filters were not applied correctly.

Fix asset owner links on catalog page

---

python_modules/dagster/dagster/_core/definitions/asset_out.py
python_modules/dagster/dagster/_core/definitions/asset_spec.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/schedule_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/source_asset_decorator.py
python_modules/dagster/dagster/_core/definitions/events.py
python_modules/dagster/dagster/_core/definitions/partition.py
python_modules/dagster/dagster/_core/definitions/schedule_definition.py
python_modules/dagster/dagster/_core/definitions/source_asset.py
python_modules/dagster/dagster/_core/storage/tags.py
python_modules/dagster/dagster/_utils/tags.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py
python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_job.py
python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_source_asset_decorator.py
python_modules/dagster/dagster_tests/definitions_tests/test_utils.py
python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py

Currently there are two separate tags validation/normalization routines, `normalize_tags` and `validate_tags_strict`. The names do not make clear that one is intended for legacy and one for new use-cases.
This PR merges the two methods and refactors the inner logic. There is now only one method `normalize_tags` that accepts a `strict` param. Also generally cleaned up the terminology and added a solid docstring so that anyone can look at `normalize_tags` now and understand the somewhat complicated tags normalization situation.

[definition-tags] Merge normalize_tags and validate_tags_strict

---

python_modules/dagster-graphql/dagster_graphql/schema/dagster_types.py
python_modules/dagster/dagster/_cli/job.py
python_modules/dagster/dagster/_core/debug.py
python_modules/dagster/dagster/_core/definitions/job_definition.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/remote_representation/__init__.py
python_modules/dagster/dagster/_core/remote_representation/code_location.py
python_modules/dagster/dagster/_core/remote_representation/external.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster/_core/remote_representation/historical.py
python_modules/dagster/dagster/_core/remote_representation/job_index.py
python_modules/dagster/dagster/_core/remote_representation/represented.py
python_modules/dagster/dagster/_core/snap/__init__.py
python_modules/dagster/dagster/_core/snap/job_snapshot.py
python_modules/dagster/dagster/_core/storage/legacy_storage.py
python_modules/dagster/dagster/_core/storage/runs/base.py
python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py
python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_job.py
python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_repository.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/test_job_snap.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/test_legacy_mode_def_snap.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/test_repository_snap.py
python_modules/dagster/dagster_tests/definitions_tests/test_reconstructable.py
python_modules/dagster/dagster_tests/general_tests/compat_tests/test_back_compat.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_dagster_pipeline_factory/test_dependency_structure_translation.py

Internal companion PR: https://github.com/dagster-io/internal/pull/11941
- `ExternalJobData` -> `JobDataSnap`
- `JobSnapshot` -> `JobSnap`
- `ExternalJobRef` -> `JobRefSnap`
- `JobLineageSnapshot` -> `JobLineageSnap`
This rename was slightly less formulaic than the others because there was _both_ an existing `ExternalJobData` and `JobSnapshot`. `ExternalJobData` is an additional layer wrapping `JobSnapshot` and a parent `JobSnapshot`
Because of this, couldn't do the usual thing of converting `ExternalJobData` -> `JobSnap`. So opted to rename `ExternalJobData` to `JobDataSnap`.
NOCHANGELOG

[external-renames] ExternalJobData -> JobDataSnap

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_reload_repository_location.py
python_modules/dagster/dagster/_core/remote_representation/__init__.py
python_modules/dagster/dagster/_core/remote_representation/code_location.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster/_grpc/server.py
python_modules/dagster/dagster_tests/cli_tests/command_tests/test_telemetry.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/test_active_data.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/test_repository_snap.py
python_modules/dagster/dagster_tests/definitions_tests/asset_policy_sensors_tests/test_default_auto_materialize_sensors.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_automation_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/scenario_state.py

Internal companion PR: https://github.com/dagster-io/internal/pull/11942
`external_repository_data_from_def` -> `RepositorySnap.from_def`
This change follows the pattern used throughout the rest of the external rename stack.
NOCHANGELOG

[external-renames] external_repository_data_from_def -> RepositorySnap.from_def

---

examples/experimental/dagster-airlift/dagster_airlift/core/__init__.py
examples/experimental/dagster-airlift/dagster_airlift/core/top_level_dag_def_api.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_dag_defs.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/jaffle_shop.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/lakehouse.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/observe.py

Per the discussion about not pushing the `Definitions`-centric integration pattern and instead focusing more on continuity, this is how that would apply to the current airlift examples.
This means that the airlift mapping APIs need to be changed to "think" in terms of `AssetsDefinitions` and friends rather than `Definitions`.
We need new top-level APIs to do this, as the current ones return `Definitions` objects.
Sadly we can no longer bundle up the resource alongside the dbt definitions in a single composable pattern. However the dbt integration is immediately customizable per all our existing docs and examples.
The new API for mapping assets to tasks is a single function: `assets_with_task_mappings`.
Docblock:
```python
def assets_with_task_mappings(
dag_id: str, task_mappings: …
```

[dagster-airlift] Introduce asset_with_task_mapping and use the to divorce from Definitions-centric construction in airlift examples

---

js_modules/dagster-ui/packages/ui-core/client.json
js_modules/dagster-ui/packages/ui-core/src/assets/buildConsolidatedColumnSchema.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/lineage/types/useColumnLineageDataForAssets.types.ts
js_modules/dagster-ui/packages/ui-core/src/assets/lineage/useColumnLineageDataForAssets.tsx

Return tag information when building column lineage to power the lineage view.
Also updates the lineage-data-building logic. Right now, we only return lineage data (for the lineage graph view) for assets which have lineage information. This means that assets which have schema information but no lineage information won't render a description, data type etc. This change allows for these assets to still render this extra information.
NOCHANGELOG

[4/c] query column tags when building lineage

---

python_modules/dagster/dagster/_record/__init__.py
python_modules/dagster/dagster_tests/conftest.py
python_modules/dagster/dagster_tests/general_tests/test_record.py

Caught a one-off error here in the wild, so thinking its a threading race condition. Disable the check in produciton but gating it to only be done in test.
add a print line and ensure it only fires in test

[record] opt-in defensive checks

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
python_modules/dagster-graphql/dagster_graphql/implementation/loader.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql/schema/external.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
python_modules/dagster-graphql/dagster_graphql/schema/solids.py

complete the migration to backing `GrapheneAssetNode` with `RemoteAssetNode`, which allowed me to delete the entire cross dependency loader class 

[graphql] back GrapheneAssetNode with RemoteAssetNode

---

python_modules/dagster/dagster/_core/definitions/asset_key.py
python_modules/dagster/dagster/_core/definitions/asset_selection.py
python_modules/dagster/dagster_tests/definitions_tests/test_asset_check_selection.py

`AssetSelection.checks_for_assets` now accepts `AssetKey`s and string asset keys, in addition to `AssetsDefinition`s.

accept asset key coercibles in AssetSelection.checks_for_assets

---

python_modules/dagster/dagster/_utils/schedules.py
python_modules/dagster/dagster_tests/scheduler_tests/test_cron_string_iterator.py

The is_numeric check here was incorrectly assumimg that if it wasn't "*", it would be a number (and also assuming that it would still be a string even if it was numeric, which was more harmless). But you can have "L" in a cronstring to indicate the last day of the month.
BK, load UI with one of these schedules and turn it on

Fix "Last day of the month" schedules in dagster

---

docs/sphinx/sections/api/apidocs/libraries/dagster-github.rst
python_modules/libraries/dagster-github/dagster_github/resources.py

This adds docstrings to the public methods of `GithubClient` & `GithubResource`, and the classes themselves. Also updates the `.rst` file to start rendering the `GithubClient`.
Built the docs locally and inspected the result with:
```
cd docs
make apidoc-build
```

[dagster-github] add docstrings to dagster-github public methods

---

js_modules/dagster-ui/packages/ui-core/src/app/App.tsx
js_modules/dagster-ui/packages/ui-core/src/app/AppTopNav/AppTopNav.tsx
js_modules/dagster-ui/packages/ui-core/src/app/LayoutProvider.tsx
js_modules/dagster-ui/packages/ui-core/src/app/UserSettingsButton.tsx
js_modules/dagster-ui/packages/ui-core/src/nav/LeftNav.tsx

Restore the behavior of the left nav on wide viewports: when open, the nav does not slide over the main content. It can also be permanently kept open, via a localStorage value.
This is a selective revert of #24976. The "small screen" behavior (sliding nav) and "wide screen" behavior (docked nav) distinction will be restored.
View app in wide screen and narrow screen. Verify that open/close of left nav works correctly, and that in the wide screen version, the preference is preserved through reload.
Verify in both legacy nav and new nav. (This affects top navigation and other pages.)
[ui] Restore docked left nav behavior for wide viewports.

[ui] Restore wide-screen left nav docking

---

examples/experimental/dagster-airlift/dagster_airlift/constants.py
examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
examples/experimental/dagster-airlift/dagster_airlift/core/dag_asset.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/event_translation.py

Make dag mapping utilities plural. This allows us to map a single asset to multiple dags eventually.
Existing changes.
NOCHANGELOG

[dagster-airlift][dag] make dag mapping utilities plural

---

examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_airflow_asset_mapping.py

Found this while working on dag-level overrides.
Downstreams in airflow mapping data were operating on an incomplete set of asset specs (only the mapped ones). But it's in fact possible for the definitions object to have unmapped asset specs which affect the asset graph dependency structure.
Existing tests (could probably add better testing here)
NOCHANGELOG

[dagster-airlift][dag] fix downstreams in airflow mapping data

---

examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization/defs_construction.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization/serialized_data.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_airflow_asset_mapping.py

Trying to simplify implementation patterns in advance of dag-level overrides to tease out a shared implementation.
In this case, MappedAirflowTaskData was giving us information that is better inferred from the airflow mapping info. So get rid of it.
Existing tests
NOCHANGELOG

[dagster-airlift][dag] remove MappedAirflowTaskData

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/sensor_builder.py

Change remaining properties to rely on asset spec-level metadata and delete dependency on serialized data.
Existing tests
NOCHANGELOG

[dagster-airlift][dag] Remove serialized data from AirflowDefinitionsData

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
examples/experimental/dagster-airlift/setup.py

In order to support 3.8, we need to place a lower bound on boto3 (older versions don't have access to mwaa).
The version I chose is quite old, I don't anticipate this causing a problem. I guess with some resolvers it chooses a version pre-mwaa though, as that's why the tests were failing.
Tests now run on 3.8
NOCHANGELOG

[dagster-airlift] Add python 3.8 support

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetPageHeader.oss.tsx

I'm honestly not entirely sure what is happening here but while debugging I noticed that the internal React fiber nodes were being improperly reused for different instances of the breadcrumb. In one render the instance would be rendering "SEO", and in the next it was rendering "Mart". I'm assuming this is due to our recent Blueprint upgrade. Adding keys onto the breadcrumb elements fixes the issue.
https://app.usepylon.com/issues?conversationID=6713c615-56be-43b1-9559-18d76f2f5c32
Successfully Loaded an asset page that was previously flickering like crazy.
[Bugfix][ui] Fixed an issue where the breadcumb on asset pages would flicker nonstop.

[AssetPageHeader] Add keys to breadcrumb elements to fix crazy flashing

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_cli_event.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/conftest.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/dbt_packages/test_columns_metadata.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/__init__.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_dbt_dependencies/.gitignore
python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_dbt_dependencies/dbt_project.yml
python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_dbt_dependencies/models/customers_refined.sql
python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_dbt_dependencies/models/schema.yml
python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_dbt_dependencies/package-lock.yml
python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_dbt_dependencies/packages.yml
python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_dbt_dependencies/profiles.yml

Addresses #23116. Right now, when building column metadata, we attempt to read a dbt .sql source file from a path including the current dbt project name, but this incorrectly generates a path for models that are pulled in from other projects via dependencies. This PR updates the logic to pull the package name for each individual node.
New unit test with dependencies.
> [dagster-dbt] Fixed an issue where column metadata generated with `fetch_column_metadata` did not work properly for models imported through dbt dependencies

[dagster-dbt] Fix generating column metadata for models installed through dbt dependencies

---

python_modules/dagster/dagster/_core/storage/event_log/base.py
python_modules/dagster/dagster/_core/storage/sqlite_storage.py
python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

We want to turn `get_and_update_asset_status_cache_value` into a GraphQL query to improve performance for declarative automation. Thus, we need to add `get_updated_asset_status_cache_values` to `EventLogStorage` which will call `get_and_update_asset_status_cache_value`.
```pytest -vv /Users/briantu/repos/dagster/python_modules/dagster/dagster_tests/storage_tests/test_event_log.py -k test_get_updated_asset_status_cache_values```

Add get asset status cache values to EventLogStorage

---

docs/content/concepts/partitions-schedules-sensors/partitioning-assets.mdx

"A asset" -> "An asset"
I was just reading through your docs and noticed this little typo -- "A asset..." should be "An asset...".
A PR to fix it seemed easier than submitting an issue -- I hope this is okay.
N/A

[DOCS] Typo in partitioning-assets.mdx

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/SidebarAssetInfo.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeOverview.tsx
js_modules/dagster-ui/packages/ui-core/src/metadata/TableSchema.tsx

Adds definition metadata to the `TableSchemaAssetContext` so we can use definition-level column lineage.

[ui][ez] Add definition metadata to TableSchemaAssetContext

---

python_modules/dagster-graphql/dagster_graphql/implementation/external.py
python_modules/dagster-graphql/dagster_graphql/schema/instigation.py
python_modules/dagster/dagster/_cli/job.py
python_modules/dagster/dagster/_cli/sensor.py
python_modules/dagster/dagster/_core/execution/job_backfill.py
python_modules/dagster/dagster/_core/execution/submit_asset_runs.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/remote_representation/code_location.py
python_modules/dagster/dagster/_core/workspace/context.py
python_modules/dagster/dagster/_daemon/auto_run_reexecution/auto_run_reexecution.py
python_modules/dagster/dagster/_daemon/sensor.py
python_modules/dagster/dagster/_scheduler/scheduler.py
python_modules/dagster/dagster/_utils/external.py
python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_partition.py
python_modules/dagster/dagster_tests/daemon_tests/test_queued_run_coordinator_daemon.py
python_modules/dagster/dagster_tests/launcher_tests/test_default_run_launcher.py
python_modules/dagster/dagster_tests/launcher_tests/test_persistent_grpc_run_launcher.py

Internal companion PR: https://github.com/dagster-io/internal/pull/12098
Rename "external" accessor methods (e.g. `get_external_execution_plan`) on `CodeLocation` to remove `external` (so `get_execution_plan`), which is no longer accurate. The new qualifier is `remote` but this is left implicit.

[external-renames] Rename `CodeLocation.get_external*` methods

---

python_modules/dagster-graphql/dagster_graphql/implementation/execution/__init__.py
python_modules/dagster-graphql/dagster_graphql/implementation/execution/launch_execution.py
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_retry_execution.py
python_modules/dagster/dagster/_cli/api.py
python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/launcher/default_run_launcher.py
python_modules/dagster/dagster/_core/pipes/context.py
python_modules/dagster/dagster/_core/storage/dagster_run.py
python_modules/dagster/dagster/_core/storage/runs/migration.py
python_modules/dagster/dagster/_core/test_utils.py
python_modules/dagster/dagster/_daemon/auto_run_reexecution/auto_run_reexecution.py
python_modules/dagster/dagster/_daemon/run_coordinator/queued_run_coordinator_daemon.py
python_modules/dagster/dagster/_daemon/sensor.py
python_modules/dagster/dagster/_grpc/impl.py
python_modules/dagster/dagster/_scheduler/scheduler.py
python_modules/dagster/dagster/_utils/external.py
python_modules/dagster/dagster_tests/storage_tests/test_dagster_run.py
python_modules/dagster/dagster_tests/storage_tests/test_job_run.py
python_modules/dagster/dagster_tests/storage_tests/utils/run_storage.py
python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/test_launching.py
python_modules/libraries/dagster-celery-k8s/dagster_celery_k8s/executor.py
python_modules/libraries/dagster-celery-k8s/dagster_celery_k8s/launcher.py
python_modules/libraries/dagster-k8s/dagster_k8s/executor.py
python_modules/libraries/dagster-k8s/dagster_k8s/launcher.py
python_modules/libraries/dagster-k8s/dagster_k8s/ops/k8s_job_op.py

Internal companion PR: https://github.com/dagster-io/internal/pull/12106
Rename `DagsterRun.external_job_origin` -> `remote_job_origin`. This is separate from downstack PRs because it is a serdes-layer change.

[external-renames] DagsterRun.external_job_origin -> remote_job_origin

---

python_modules/dagster/dagster/_api/snapshot_job.py
python_modules/dagster/dagster/_core/remote_representation/__init__.py
python_modules/dagster/dagster/_core/remote_representation/code_location.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster/_grpc/impl.py
python_modules/dagster/dagster/_grpc/server.py
python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_job.py

Internal companion PR: https://github.com/dagster-io/internal/pull/12109
Serdes layer renames:
- `ExternalJobSubsetResult` -> `RemoteJobSubsetResult`
- `RemoteJobSubsetResult.external_job_data` -> `.job_data_snap`

[external-renames] `ExternalJobSubsetResult` -> `RemoteJobSubsetResult`

---

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/dlt/asset_decorator.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/dlt/translator.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/asset_decorator.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/dagster_sling_translator.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/dlt_tests/test_asset_decorator.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/sling_tests/test_asset_decorator.py
python_modules/libraries/dagster-powerbi/dagster_powerbi/translator.py
python_modules/libraries/dagster-sdf/dagster_sdf/sdf_information_schema.py
python_modules/libraries/dagster-sigma/dagster_sigma/translator.py

Begin using `kinds=` in internal integration implementations instead of `build_kind_tags`.
Also add translator methods for a few integrations to let users specify custom kinds.
Existing unit tests, new unit test.

[kinds] Use kinds argument in integrations, add to translators

---

js_modules/dagster-ui/packages/ui-components/src/components/TokenizingField.tsx

Want to use `onBlur` prop on `TokenizingField` to perform a side effect every time we blur instead of every time the tokens in `TokenizingField` changes
yarn lint, ts, build
NOCHANGELOG

[ui-components] add onBlur prop to TokenizingField

---

docs/next/components/mdx/includes/dagster/concepts/logging/RawComputeLogs.mdx

Addresses https://github.com/dagster-io/dagster/issues/24043
Windows / Azure users may not be able to see compute logs in the Dagster UI and encounter this warning in their terminal:
>UserWarning: WARNING: Compute log capture is disabled for the current environment. Set the environment variable PYTHONLEGACYWINDOWSSTDIO to enable.
>warnings.warn(WIN_PY36_COMPUTE_LOG_DISABLED_MSG)
👀

[docs] add note about enabling PYTHONLEGACYWINDOWSSTDIO

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/task_proxy_operator.py
examples/experimental/dagster-airlift/examples/tutorial-example/Makefile
examples/experimental/dagster-airlift/setup.py

A few things preventing 3.12 support and additional fixes.
- Different airflow requirements for 3.12 above and below, as Airflow 2.9 officially added python 3.12 support.
- When performing automagical task creation with parameter swapping (I suspect we'll need to either get rid of this or at least have an argument to disable it), the weight_rule parameter causes problems because it's attribute form is transformed into something we can't interpret in 2.9 or above. So ignore it.
- Remove airflow as a setup.py dependency from the [in-airflow] package. This is because Airflow recommends installation via a constraints file, and installations can be wonky if this is not done. Instead, expect the user to roll their own airflow and have the tests + tutorial install airflow directly.
Existing …

[dagster-airlift] Add python 3.12 support

---

examples/experimental/dagster-airlift/CHANGES.md
examples/experimental/dagster-airlift/Makefile
examples/experimental/dagster-airlift/scripts/find_airlift_commits.sh

Adds tooling to pull all [dagster-airlift] prefixed commits between the last two changelog versions, pastes it to the clipboard.
Tested the new fxnality to write the 0.0.26 entry 😄 
NOCHANGELOG (ironic)

[dagster-airlift] add changelog tooling + changelog section for 0.0.26

---

python_modules/dagster/dagster/_generate/templates/CODE_LOCATION_NAME_PLACEHOLDER/pyproject.toml.tmpl

It appears that Python 3.12 has been officially supported for months now [#17350], but the scaffold template has not been updated yet. This change increases the upper version bound in the template from <3.12 to <3.13.

Add support for Python 3.12 in scaffold template

---

examples/experimental/dagster-airlift/dagster_airlift/constants.py
examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
examples/experimental/dagster-airlift/dagster_airlift/core/dag_asset.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/event_translation.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/sensor_builder.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization/defs_construction.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization/serialized_data.py
examples/experimental/dagster-airlift/dagster_airlift/core/utils.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/conftest.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_airflow_asset_mapping.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_sensor.py

Support dag-level override behavior in the airflow builder.
This iteration explicitly duplicates some implementation pathways across dag / task enrichment.
A new test for e2e behavior with sensor.
NOCHANGELOG

[dagster-airlift] Support dag-level overrides in builder

---

pyright/alt-1/requirements-pinned.txt
pyright/master/requirements-pinned.txt
python_modules/libraries/dagster-aws/dagster_aws/pipes/__init__.py
python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/__init__.py
python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/emr.py
python_modules/libraries/dagster-aws/dagster_aws/pipes/message_readers.py
python_modules/libraries/dagster-aws/ruff.toml
python_modules/libraries/dagster-aws/setup.py

This PR adds `PipesEMRCLient` to `dagster-aws`. 
It allows running Spark workloads in ephemeral EMR (EC2 flavor) clusters. 
There is no support for submitting steps to existing EMR clusters. It turned out to be pretty hard to support properly since there is no native way to distinguish between steps submitted by our client and other workloads running in the same cluster. We can try to implement this in the future. 
Tasks:
Showcase:
[dagster-aws] new AWS EMR Dagster Pipes client (`dagster_aws.pipes.PipesEMRCLient` ) for running and monitoring AWS EMR jobs from Dagster.

[dagster-aws] add `PipesEMRClient`

---

examples/experimental/dagster-airlift/dagster_airlift/in_airflow/dag_proxy_operator.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/proxied_state.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/proxying_fn.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_proxied_state.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/airflow_dags/dag_level_proxied.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/airflow_dags/proxied_state/overridden_dag.yaml
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/dagster_defs/mapped_defs.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink_tests/integration_tests/test_e2e_mapped.py

Adds everything we need to get dag-level proxying working airflow side. Namely a new operator type and handling within `proxying_to_dagster`
Implementation here more or less matches what was in https://github.com/dagster-io/dagster/pull/25013.
Added a kitchen sink test for the behavior.
NOCHANGELOG

[dagster-airlift][dag] in-airflow dag proxying behavior

---

examples/experimental/dagster-airlift/dagster_airlift/cli.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/dag_proxy_operator.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/proxied_state.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/proxying_fn.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/scaffolding.py
examples/experimental/dagster-airlift/dagster_airlift/test/__init__.py
examples/experimental/dagster-airlift/dagster_airlift/test/test_utils.py
examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/scaffold_test_airflow_home/airflow_dags/dags.py
examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_scaffolding.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_proxied_state.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/airflow_dags/dag_level_proxied.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/airflow_dags/proxied_state/overridden_dag.yaml
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/dagster_defs/mapped_defs.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink_tests/integration_tests/test_e2e_mapped.py
examples/experimental/dagster-airlift/examples/tutorial-example/README.md
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/migrate.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/migrate_with_check.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/observe.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/standalone.py
examples/experimental/dagster-airlift/setup.py

Assets forward version of the tutorial. Also changes some of the wording
Existing tests
NOCHANGELOG

[dagster-airlift][tutorial] Assets forward tutorial

---

python_modules/libraries/dagster-aws/dagster_aws/_stubs.py
python_modules/libraries/dagster-aws/dagster_aws/s3/sensor.py
python_modules/libraries/dagster-aws/dagster_aws_tests/s3_tests/test_s3_sensor.py

- Adds `since_last_modified` parameter to `get_s3_keys` to support shortcoming of `since_key` as `since_key` can result in missing records if that key has been modified (keys are sorted by last modified date)
- `pytest`

[dagster-aws] add `since_last_modified` parameter to get_s3_keys

---

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_decorators.py

This adds the `code_version` parameter to the `graph_asset` decorator and passes it to `AssetsDefinition.from_graph()`. Also removes the `(Experimental)` qualifier in the docstring of the `asset` decorator since it is no longer marked as experimental. Closes https://github.com/dagster-io/dagster/issues/20902
Added to existing unit test
Added `code_version` parameter to the `@graph_asset` decorator

Add `code_version` parameter to `@graph_asset` decorator

---

examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/lakehouse.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/migrate.py

[dagster-airlift] Migrate complete to assets_with_task_mappings

---

python_modules/dagster/dagster/_check/functions.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster_tests/general_tests/check_tests/test_check.py

match the behavior pydantic went with here https://github.com/pydantic/pydantic/issues/5595 which I think is preferable 
updated tests

[check] dont allow str or bytes for sequence_param

---

python_modules/dagster/dagster/_core/definitions/load_asset_checks_from_modules.py
python_modules/dagster/dagster_tests/definitions_tests/asset_check_tests/test_load_from_modules.py

This makes sure that the `load_asset_checks_from_*` functions return `[AssetChecksDefinition]` by replacing the typecast with the creation of an actual `AssetChecksDefinition`.
Alternatively, this issue could be addressed by adding a specialized `with_attributes()` method to `AssetChecksDefinition` to make it return the correct type. I'd be happy to try this path as well! But it feels like this change would be sufficient and minimally impactful across the codebase.
Closes https://github.com/dagster-io/dagster/issues/22064
Added an `isinstance` check to the `load_asset_checks_from_*` tests

Recreate `AssetChecksDefinition`s after setting prefix

---

examples/experimental/dagster-airlift/dagster_airlift/constants.py
examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
examples/experimental/dagster-airlift/dagster_airlift/core/load_defs.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/event_translation.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/sensor_builder.py
examples/experimental/dagster-airlift/dagster_airlift/test/airflow_test_instance.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/conftest.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_sensor.py

Take 3 of adding time window partition handling to airlift.
Most of the implementation here has already been gone over. The only new bits are how it relates to the top-level pluggable API we decided on. It makes things a little more weird because we're transforming the asset materializations after the fact.
Same unit test battery as last time, minus the timezone test. We no longer require the same timezone as long as timestamps match up.
NOCHANGELOG

[dagster-airlift][partitions] add a default implementation with time partition handling to airlift

---

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/asset_graph_view/entity_subset.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_evaluator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_eager_condition.py

As title.
For self-dependent assets, the inference logic that determines the direction we should map partitions in does not work for self-dependent assets, as these are always upstream of themselves, meaning from_key will always be a parent of to_key, and we will always take the first branch.
This solves the issue by adding an optional direction parameter to the EntityMatches condition, and threads that through to the underlying mapping function, allowing us to determine what direction we should map our partitions in.
Fixed an issue which could cause incorrect evaluation results when using self-dependent partition mappings with `AutomationConditions` that operate over dependencies.

[bug] Fix issue with partition mapping handling in the EntityMatches condition

---

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/__init__.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_tester.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/__init__.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/slice_conditions.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_check_passed_failed_conditions.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_eager_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_failed_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_newly_updated_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_on_cron_condition.py

This updates our suite of built-in automation conditions to work natively with asset checks (previously, they only worked with assets).
This means you can do things like use the `on_cron` or `eager` conditions with checks.
This requires a unified set of statuses that apply to both assets and asset checks, as each has different ways of describing their status.
- The `AutomationCondition.eager()`, `AutomationCondition.missing()`, and `AutomationCondition.on_cron` conditions are now compatible with asset checks.

Make existing conditions work with Asset Checks

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py
python_modules/dagster-graphql/dagster_graphql/implementation/utils.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
python_modules/dagster-graphql/dagster_graphql/schema/solids.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_partition_backfill.py
python_modules/dagster/dagster/_core/definitions/asset_graph.py
python_modules/dagster/dagster/_core/definitions/freshness_based_auto_materialize.py
python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
python_modules/dagster/dagster/_core/execution/asset_backfill.py
python_modules/dagster/dagster/_core/execution/submit_asset_runs.py
python_modules/dagster/dagster/_core/remote_representation/external.py
python_modules/dagster/dagster/_core/workspace/context.py
python_modules/dagster/dagster/_core/workspace/workspace.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py
python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py

More accurately model the two flavors of `RemoteAssetGraph` that we create, a repository scoped one and a global / workspace scoped one. The global asset graph is built by combining all of the repository scoped asset graphs.

split RemoteAssetGraph in to RemoteRepository and RemoteGlobal

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/check_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py

As title. These return types were overly-specific. We have some subclasses that support additional methods, but most do not. To keep things more comprehensible for users that are seeing these types, use the least specific type possible in these cases.
NOCHANGELOG

Simplify return types of static constructors for AutomationCondition

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/code_version_changed_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/slice_conditions.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/any_downstream_conditions_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/check_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/newly_true_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/since_operator.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_any_downstream_conditions.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_result_value_hash.py

The `description` property is a holdover from the old UI flow, and is not rendered in the new UI. Therefore, having it be specified on a bunch of built in conditions was a waste. This updates the name properties to be more descriptive (containing the relevant properties), which allows them to be represented in the UI.
NOCHANGELOG

Remove description property, make names more descriptive

---

examples/experimental/dagster-airlift/dagster_airlift/in_airflow/__init__.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/proxying_fn.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/task_proxy_operator.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/airflow_dags/custom_callback.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/airflow_dags/proxied_state/affected_dag.yaml
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/airflow_dags/proxied_state/unaffected_dag.yaml
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/dagster_defs/mapped_defs.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink_tests/integration_tests/test_e2e_mapped.py
examples/experimental/dagster-airlift/examples/tutorial-example/README.md
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/custom_operator_examples/custom_proxy.py

It's highly likely that the default magic we perform to "swizzle in" the dagster operator will fail for some cases. We need to have fallbacks for edge cases and weirdness with forked versions of airflow, weird parameters, etc.
This introduces a few different pluggability points:
- Top-level callback to the `proxying_to_dagster` fxn which allows for complete control of the creation of the new operator.
- Make the default `build_dagster_task` pluggable by allowing for parameter level overrides, and the class to be instantiated to be overridden. This should account for the common cases.
Added a new kitchen sink test which invokes both layers of pluggability.
NOCHANGELOG

[dagster-airlift] Make proxy operator pluggable

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_condition_evaluations.py
python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/__init__.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/__init__.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/operands.py
python_modules/dagster/dagster/_utils/caching_instance_queryer.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_result_value_hash.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_e2e.py

As title. This converts the existing `in_progress` AutomationCondition to capture both in progress runs and in progress backfills. It keeps these as separate conditions to maximize flexibility (and also increases explainability in the UI, as you can tell if an asset is part of a backfill but not an active run, or vice-versa).
`AutomationCondition.in_progress()` now will be true if an asset partition is part of an in-progress backfill that has not yet executed it. The prior behavior, which only considered runs, is encapsulated in `AutomationCondition.execution_in_progress()`.

Create backfill_in_progress AutomationCondition

---

integration_tests/test_suites/auto_materialize_perf_tests/test_asset_daemon_perf.py
python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/automation_tick_evaluation_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_evaluator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_tester.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/backfill_simple_non_user_code.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/backfill_simple_user_code.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/backfill_with_runs_and_checks.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_e2e.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/legacy_tests/test_auto_observe.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/asset_daemon_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/automation_condition_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/base_scenario.py

This allows it to be transferred across the serdes boundary, enabling it for non-user code automation conditions
NOCHANGELOG

Store allow_backfills in the sensor metadata

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_schedules.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_sensors.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_selections.py
python_modules/dagster-graphql/dagster_graphql/schema/external.py
python_modules/dagster-graphql/dagster_graphql/schema/schedules/schedules.py
python_modules/dagster-graphql/dagster_graphql/schema/sensors.py
python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
python_modules/dagster/dagster/_core/remote_representation/external.py
python_modules/dagster/dagster/_core/workspace/context.py

To facilitate being able to resolve all required information for an asset node from just the global scope remote asset node, track which sensors and schedules target each repository scoped asset. 
existing coverage, additional coverage in https://github.com/dagster-io/internal/pull/11840

[global asset graph] precompute targeting instigators

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_schedules.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_sensors.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_selections.py
python_modules/dagster-graphql/dagster_graphql/schema/external.py
python_modules/dagster-graphql/dagster_graphql/schema/schedules/schedules.py
python_modules/dagster-graphql/dagster_graphql/schema/sensors.py
python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
python_modules/dagster/dagster/_core/remote_representation/external.py
python_modules/dagster/dagster/_core/remote_representation/handle.py
python_modules/dagster/dagster/_core/workspace/context.py
python_modules/dagster/dagster/_serdes/serdes.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py

Make the global and repository scoped `RemoteAssetNode` serializable so we can persist/cache the resolved global asset node of a workspace.
added test

serializable RemoteAssetNodes

---

python_modules/dagster/dagster/_scheduler/scheduler.py
python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py

Make more consistent the behavior of schedules removed from (and thus added back to) code locations.
This PR wipes schedule state for schedules removed from code locations.
The schedule state row contains:
1) the status of the schedule (e.g. on/off)
2) the start time of the schedule (should we try to go back and make up for missed ticks in the recent past)
This does NOT affect tick history.
BK

remove state for removed schedules

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/AutomaterializeMiddlePanelWithData.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/auto-materialization/GlobalAutomaterializationContent.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillRunsTab.tsx
js_modules/dagster-ui/packages/ui-core/src/pipelines/PipelineRunsEmptyState.tsx
js_modules/dagster-ui/packages/ui-core/src/pipelines/PipelineRunsFeedRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/pipelines/PipelineRunsRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunRowTags.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunTable.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedRow.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedTable.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedTabs.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedUtils.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/useRunsFeedEntries.tsx
js_modules/dagster-ui/packages/ui-core/src/schedules/ScheduleRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/sensors/SensorPageAutomaterialize.tsx
js_modules/dagster-ui/packages/ui-core/src/ui/IndeterminateLoadingBar.tsx

This fixes the cloud build errors caused by my previous PR importing OSS code via `shared/`, and also includes some small tweaks to the backfill / runs consolidation:
- Fix react error caused by `loading` being applied to a DOM node
- Fix loading state of new runs feed table using old page-size Spinner
- Hide backfill tags in the runs table on the backfill page
- Land on Overview tab when clicking into a backfill page
- Empty state for the `In progress` and `Queued` tab counts is `null`
Verified these manually on the impacted pages, verifying the internal build is fixed manually

[ui] Fix shared/ imports, additional tweaks for backfill / runs consolidation

---

examples/experimental/dagster-airlift/dagster_airlift/in_airflow/__init__.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/scaffolding.py

Improves the error state when airflow is not installed when using the [in-airflow] module; and only throw errors when [in-airflow] isn't installed on import error.
Created new venv without airflow and attempted to use scaffold cli.
NOCHANGELOG

[dagster-airlift] better errors when [in-airflow] is not installed, or apache-airflow is not installed

---

examples/experimental/dagster-airlift/dagster_airlift/cli.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/__init__.py
examples/experimental/dagster-airlift/setup.py

The normal `requires` of a package is not installed when installing submodules. As a result, we need to separately specify these dependencies in order to use the CLI if someone, for example, just installs [in-airflow].
I don't love needing to repeat this installation step over and over. Could be more convenient to just have a [cli] extras installation pathway.
Fixed problem I was running into with installation.
NOCHANGELOG

[dagster-airlift] Ensure cli requirements are installed

---

js_modules/dagster-ui/packages/ui-components/package.json
js_modules/dagster-ui/packages/ui-components/src/components/NewConfigEditor.tsx
js_modules/dagster-ui/packages/ui-components/src/components/RefreshableCountdown.tsx
js_modules/dagster-ui/packages/ui-components/src/components/configeditor/codemirror-yaml/mode.tsx
js_modules/dagster-ui/yarn.lock

Update lint config and TS for ui-components, which uses the external npm package as its eslint-config dependency.
TS, lint, jest. Repeat at `dagster-ui` level, verify that everything passes.

[ui] TS, lint updates for ui-components

---

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/storage/event_log/base.py

We realized that since that we already have a GraphQL query for to get asset check summary records `get_asset_check_summary_records`, we can just use that to get the `AssetCheckExecutionRecord`s we want instead of creating another query to get execution records.

Use AssetCheckSummaryRecord to compute subsets for asset checks

---

python_modules/libraries/dagster-aws/dagster_aws/s3/sensor.py
python_modules/libraries/dagster-aws/dagster_aws_tests/s3_tests/test_s3_sensor.py

- Change `since_last_modified` to be `datetime` as this is the type of `obj.get("LastModified")`
- Adds unit test for `get_objects`
```
pytest
```
- [dagster-aws] `get_objects` takes a `datetime` for the `since_last_modified` parameter to improve ergonomics

[dagster-aws] use datetime for since_last_modified; include unit test

---

python_modules/libraries/dagster-databricks/dagster_databricks/databricks_pyspark_step_launcher.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_pyspark.py

This makes sure to use the `iam.AccessControlRequest` to format the permissions request instead of the `jobs.JobAccessControlRequest` because the latter would result in skipping a permission that is only defined on clusters (and not on jobs).
Closes https://github.com/dagster-io/dagster/issues/25106
Added to the unit test to confirm that both permission request types are formatted correctly

Fix cluster permissions in databricks step launcher

---

docs/content/integrations/looker.mdx

- add related
- use `import dagster as dg`
- use PyObject references
```
```

[dagster-looker] add related; use dagster as dg; use PyObject references

---

js_modules/dagster-ui/packages/ui-core/src/apollo-client/index.tsx

In internal, we consume a couple of Apollo error utilities for an error link. Expose these via `apollo-client` exports in `ui-core` so that the internal app can appease our eslint-config.
Run TS and lint in internal.

[ui] Export Apollo error utilities

---

python_modules/libraries/dagster-looker/dagster_looker/api/resource.py

Fetching the list of dashboards and explores is quite slow right now. Implements a threadpool to do this in parallel, which cuts down the time to tens of seconds for me, locally.
Existing unit tests, tested locally.
> [dagster-looker] When fetching explores and dashboards from the Looker API, retrieve in parallel

[dagster-looker] Fetch dashboards, explores etc in parallel

---

docs/docs-beta/docs/guides/automation.md
docs/docs-beta/docs/guides/sensors.md
docs/docs-beta/sidebars.ts

- Explains how to trigger a run using the `LaunchRunMutation` with the GraphQL endpoint
Created a local Dagster instance containing:
```
@dg.job
def example_job():
print('Hello, world')
defs = dg.Definitions(
jobs=[example_job]
)
```
Launched the run using:
```
response = requests.post(
graphql_endpoint,
json={
"query": query,
"variables": {
"repositoryLocationName": "graphql-example-dagster.py",
"repositoryName": "__repository__",  # default if using `Definitions`
"jobName": "example_job",
"runConfigData": {},
},
},
)
```
The same was done for the asset materialization.
```
response = requests.post(
graphql_endpoint,
json={
"query": query,
"variables": {
"executionParams": {
"mode": "default",
"runConfigData": "{}",
"selector": {
"assetCheckSelection": [], …
```

[DOC-557] add example for triggering job with GraphQL endpoint

---

js_modules/dagster-ui/packages/ui-core/src/instance/useCodeLocationPageFilters.tsx
js_modules/dagster-ui/packages/ui-core/src/nav/useCodeLocationsStatus.tsx

Fix `useCodeLocationPageFilters` when an invalid query param is used.
- If `status` is a non-array string, discard it. (This is the bug that was reported, where perhaps the user just modified the URL manually?)
- Use a query parameter array instead of JSON encoding.
View code location list, filter on status. Verify that it works correctly and updates the URL accordingly, e.g. `?status%5B%5D=Loaded&status%5B%5D=Failed`.
Modify the parameter manually to be `?status=failed`, verify that the page loads correctly with no JS errors, and ignores the invalid parameter.
[ui] Fix an issue in the code locations page where invalid query parameters could crash the page.

[ui] Fix code location page status filters

---

python_modules/dagster/dagster/_core/definitions/asset_spec.py
python_modules/dagster/dagster_tests/definitions_tests/test_asset_spec.py

Adds two new type-hinted methods to let users replace `AssetSpec` attributes or merge new metadata, tag, owner, dep values. Shipped as standalone methods for us to use internally, at first.
These methods pass through `dagster_internal_init`, so they correctly post-process any coercible inputs (e.g. `AssetKey` to `AssetDep`).
```python
spec = AssetSpec(key="foo", owners=["original@dagsterlabs.com"])
spec_with_replaced_owner = replace_attributes(spec, owners=["replacement_owner@dagsterlabs.com"])
spec_with_additional_owner = merge_attributes(spec, owners=["additional_owner@dagsterlabs.com"])
```
`NOCHANGELOG`

[rfc] replace_attributes(spec, ...) and merge_attributes(spec, ...)

---

js_modules/dagster-ui/packages/ui-components/src/components/StyledButton.tsx
js_modules/dagster-ui/packages/ui-components/src/components/TextInput.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/SearchFilter.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetPartitions.tsx
js_modules/dagster-ui/packages/ui-core/src/ticks/EvaluateScheduleDialog.tsx

https://linear.app/dagster-labs/issue/FE-615/fix-text-wrapping-issues-in-buttons-on-ui-pages
Tested these callsites manually in OSS.

[ui] Fix misc styling / unnecessary overrides following Blueprint update

---

python_modules/dagster/dagster/_core/execution/plan/instance_concurrency_context.py
python_modules/dagster/dagster_tests/core_tests/execution_tests/test_instance_concurrency_context.py

the column is stored as a postgres Integer, so trying to set a priority that is too high will fail.
BK

Raise a clearer exception when a concurrency slot is tried to claim with a priority outside of the valid range

---

docs/dagster-university/pages/dagster-essentials/lesson-8/coding-practice-partition-taxi-trips.md

Noticed this typo in the code for Lesson 8 of Dagster Essentials which lead to the example code no longer working. This is part of the "Practice: Partition the taxi_trips asset" section of Lesson 8.
It's just a markdown typo and the code now works in my Dagster University project.

[daggy-u] Example code fix for Lesson 8 in Dagster Essentials

---

pyright/master/requirements-pinned.txt
python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/conftest.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/test_asset_specs.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/test_resource.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/utils.py
python_modules/libraries/dagster-sigma/setup.py
python_modules/libraries/dagster-sigma/tox.ini

Rewrites the internals of `dagster-sigma` to fetch from APIs using aiohttp instead of requests, letting us parallelize many fetches.
Drops the owner fetch for now, since this can also introduce delay and is not super important.
Existing unit tests, tested vs live instance.
> [dagster-sigma] The Sigma integration now fetches initial API responses in parallel, speeding up initial load.

[dagster-sigma] Use aiohttp to fetch data from Sigma APIs

---

js_modules/dagster-ui/packages/eslint-config/rules/index.js
js_modules/dagster-ui/packages/eslint-config/rules/missing-graphql-variables-type.js
js_modules/dagster-ui/packages/eslint-config/rules/missing-shared-import.js
js_modules/dagster-ui/packages/ui-core/src/ui/Filters/useDefinitionTagFilter.tsx

This PR introduces a lint rule to prevent `shared/` imports that are incompatible with the cloud build process.
In OSS, we use a [virtual path mapping](https://github.com/dagster-io/dagster/blob/22cf05f516036a780e7971ccd70e2e92ab682c3b/js_modules/dagster-ui/packages/ui-core/tsconfig.json#L5) `shared/` to `src/`, avoiding the need to run a script to generate a `tsconfig.json` for shared components. However, in the cloud environment, this mapping doesn't exist. Instead, [a script generates specific path mappings](https://github.com/dagster-io/internal/blob/089cba51954742e8e0697f080a479825cad19be5/dagster-cloud/js_modules/app-cloud/scripts/generateResolutions.ts#L38) for the cloud `tsconfig.json`. While the `shared/` imports work fine in the OSS build due to Next.js using the local …

Add lint rule to auto-fix incorrect `shared/` imports

---

python_modules/dagster/dagster/_core/definitions/asset_check_evaluation.py

When sending a request like:
```
curl --location 'localhost:3000/report_asset_check/' \
--header 'Content-Type: application/json' \
--data '{
"asset_key": "meta_subs_bucket",
"check_name": "freshness_check",
"passed": true,
"metadata": {
"dagster/row_count": 20,
"dagster/fresh_until_timestamp": 1729526344
}
}'
```
I would get an error in the asset check page like:
```
Operation name: {AssetGraphLiveQuery}
Message: Not implemented: <class 'int'> unsupported metadata entry for now
Path: ["assetNodes",0,"assetChecksOrError","checks",0,"executionForLatestMaterialization"]
Locations: [{"line":77,"column":3}]
Stack Trace:
File "/Users/pablo.recio/.pyenv/versions/3.12.2/envs/dagster/lib/python3.12/site-packages/graphql/execution/execute.py", line 530, in await_result
return_type, field_nodes, …
```

Normalizes the metadata object in asset_check_evaluation.py

---

python_modules/dagster/dagster/_annotations.py
python_modules/dagster/dagster/_utils/warnings.py

Adding new Supersession Python utils.
This is done in alignment with the new [API lifecycle](https://www.notion.so/dagster/API-Lifecycle-Refresh-f72f6e199da3409c8c5da297a109b3c8) and as requested in [this](https://github.com/dagster-io/dagster/pull/25335#discussion_r1805034325) comment by @yuhan 
The raised warning is a `FutureWarning` instead of `DeprecationWarning`.
Example screenshot in the upstack PR.
I decided not to add a superseeded_param decorator yet as it's unlikely we are going to need something like this.
Example screenshot in the upstack [PR](https://github.com/dagster-io/dagster/pull/25335).

[utils] add supersession warning and decorator

---

docs/content/about/releases.mdx
docs/markdoc-component-documentation.md
docs/next/components/markdoc/Badges.tsx
docs/next/components/mdx/MDXComponents.tsx
docs/next/markdoc/tags.js
docs/next/styles/globals.css
docs/sphinx/_ext/dagster-sphinx/dagster_sphinx/__init__.py
docs/sphinx/_ext/dagster-sphinx/dagster_sphinx/docstring_flags.py

Adding new `Supersession` helpers for docs.
This is done in alignment with the new [API lifecycle](https://www.notion.so/dagster/API-Lifecycle-Refresh-f72f6e199da3409c8c5da297a109b3c8) and as requested in [this](https://github.com/dagster-io/dagster/pull/25335#discussion_r1805034325) comment by @yuhan 
Example screenshot in the upstack [PR](https://github.com/dagster-io/dagster/pull/25335).

[docs] display supersession info

---

docs/next/styles/globals.css
docs/next/tailwind.config.js

Making deprecation badge orange since yellow will be used for supersession. This was supposed to be part of https://github.com/dagster-io/dagster/pull/25362 but I forgot to push this change

[docs] deprecated badge yellow -> orange

---

python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/pending_repo.py

Fixes an issue where we would request the client ID as part of the cached data ID, but this would not be resolved from its env var status.
Update test to ensure env vars are tested properly

[dagster-sigma] Fix client ID when using env var

---

python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/conftest.py

Properly fetch paginated responses from the Sigma APIs, which we hit for very large workspaces which might have >1000 workbooks, datasets etc.
Update test cases to paginate API response.
> [dagster-sigma] Fixed pulling incomplete data for very large workspaces

[dagster-sigma] handle paginating large workspaces

---

python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster/_daemon/sensor.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/simple_defs.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/simple_non_user_code.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/simple_user_code.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_e2e.py

As title. Previous codepaths assumed that for a given instigator, the `handled_by_asset_daemon` property would never change, which is not the case. To avoid this issue, we ignore the instigator state in these codepaths, and instead use the current value based off of the workspace snapshot.
Added test which failed before these changes, and now passes.
Fixed an issue which would cause `AutomationConditionSensorDefinitions` to not be evaluated if the `use_user_code_server` value was toggled after the initial evaluation.

Fix bug when switching from non-user-code to user-code

---

js_modules/dagster-ui/packages/ui-core/src/ui/Filters/util.ts

[Recent PR ](https://github.com/dagster-io/dagster/pull/25196/files)switched to using a Tag type which omits the __typename. There was 1 more spot that I needed to update to also do that which cloud is relying on.

Fix cloud build

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization/defs_construction.py
examples/experimental/dagster-airlift/dagster_airlift/core/utils.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py
examples/experimental/dagster-airlift/examples/dbt-example/Makefile
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/dags.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/proxied_state/rebuild_iris_models.yaml
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/proxied_state/rebuild_iris_models.yaml-e
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/jaffle_shop.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/observe.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/observe_with_check.py
js_modules/dagster-ui/packages/ui-core/src/graph/OpTags.tsx

The recent changes we made to how proxying behavior works have broken the presence of the Airflow tag on external assets. This adds an "Airlift Mapped" kind tag so that all the mapped assets get a kind tag.
Adds new assertions for kind tags.
NOCHANGELOG

[dagster-airlift] Fixes for demo

---

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
python_modules/dagster/dagster_tests/asset_defs_tests/asset_graph_view_tests/test_asset_slice.py

As title. This guards against situations in which an asset is completely removed from the graph and we try to get an EntitySubset from a SerializedEntitySubset.
NOCHANGELOG

[asset-graph-view] Make deserializing subsets safer

---

python_modules/dagster-test/dagster_test/toys/auto_materializing/large_graph.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/500_eager_assets.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_e2e.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/perf_tests/test_perf.py

As title. This sets a baseline for feeling "safe" with this many assets.
Some upgrades were needed to the test suite to make it more realistic such that we could trip the error.
Future changes will allow us to greatly increase, or entirely remove, this limit.
Confirmed that if 1000 assets were supplied, we would fail this test.

Add test demonstrating that we do not hit the RESOURCE_EXHAUSTED error above a given threshold

---

python_modules/dagster-test/dagster_test/toys/auto_materializing/large_graph.py
python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/automation_tick_evaluation_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster_tests/definitions_tests/test_automation_condition_sensor_definition.py

Building off of the previous PR, now we emit a helpful error message rather than just letting users run into the RESOURCE_EXHAUSTED error.

Add error for user code sensors with too many entities targeted

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_condition_evaluations.py
python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/__init__.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/operands.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_eager_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_result_value_hash.py

Resolves: https://github.com/dagster-io/dagster/issues/24389
To put it simply, this ensures the `any_deps_updated` condition does not "count" an update from a parent if the run that materialized that parent also planned to materialize the child.
This guards against a variety of situations where a run can be launched with the intention of updating many assets, but fail to do so for whatever reason (intentional skip, failure event). In those cases, the assumption is that the child should NOT be attempted again (even though the parent did successfully materialize).
This is a fairly niche implementation detail that users should not have to think about when crafting their own policies.
I added a parameterized test that failed before this change (for the skip and fail cases) and passes now. …

Add `executed_with_root_target` condition to handle partial runs / failures

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_runs_feed.py

updates the partition_set name in a test so that it conforms to the expected pattern https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_core/remote_representation/external_data.py#L1800
important for https://github.com/dagster-io/internal/pull/12131 since it relies on the job name of a backfill being stored correctly. it's not stored correctly if the test uses the wrong format

fix partition set name for runs feed tests

---

python_modules/dagster-test/dagster_test/test_project/test_jobs/repo.py
python_modules/libraries/dagster-docker/dagster_docker/docker_executor.py
python_modules/libraries/dagster-docker/dagster_docker/docker_run_launcher.py
python_modules/libraries/dagster-docker/dagster_docker_tests/test_launch_docker.py

container_kwargs.stop_timeout should work out of the box, but does not due to a longstanding docker-py bug. Move it into the terminate() method instead
New test case
[dagster-docker] `container_kwargs.stop_timeout` can now be set when using the `DockerRunLauncher` or `docker_executor` to configure the amount of time that Docker will wait when terminating a run for it to clean up before forcibly stopping it with a SIGKILL signal.

Fix using the stop_timeout argument in DockerRunLauncher.container_kwargs

---

python_modules/dagster/dagster/_core/definitions/asset_selection.py
python_modules/libraries/dagster-dbt/dagster_dbt/dbt_manifest_asset_selection.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_selection.py

Current implementation does a full equality check on the full manifest. Scope it down to just the "metadata" part of the manifest, which is much smaller and faster to compare.
New tests
Speed scope importing code like this and see a marked improvement:
```
dbt_job_6 = define_asset_job(
name="dbt_6",
selection=build_dbt_asset_selection(dbt_assets=[dbt_project_assets]),
)
@sensor(job=dbt_job_6)
def my_sensor():
pass
```
[dagster-dbt] Performance improvements when loading definitions using `build_dbt_asset_selection`.

Speed up equality checks for build_dbt_asset_selection asset selections

---

js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/WorkspaceContext.tsx

As titled
Used app-proxy to confirm we don't make any LocationWorkspaceQuery calls anymore if the data is up to date.
Existing jest tests still pass

WorkspaceContext - wait for indexeddb data to load before checking for stale locations

---

docs/dagster-university/pages/dagster-essentials/extra-credit/asset-metadata-as-markdown.md
docs/dagster-university/pages/dagster-essentials/extra-credit/materialization-metadata.md

One example code snippet was missing an import (`MaterializeResult`) and the other had an additional unnecessary import (`get_dagster_logger`). This would be especially confusing for newbies, because `get_dagster_logger` isn't covered anywhere in the course.
It's just a markdown typo and the code now works in my Dagster University project.

[daggy-u] Example code fixes for extra credit lesson in Dagster Essentials

---

python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/backfill_simple_non_user_code.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/backfill_simple_user_code.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/backfill_with_runs_and_checks.py

This updates the default value of this setting. To be merged in 1.9.
By default, `AutomationConditionSensorDefinitions` will now emit backfills to handle cases where more than one partition of an asset is requested on a given tick. This allows that asset's BackfillPolicy to be respected. This feature can be disabled by setting `allow_backfills` to `False`.

[1.9] Update default value of allow_backfills to True

---

python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/500_eager_assets.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/backfill_simple_user_code.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/backfill_with_runs_and_checks.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/custom_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/default_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/simple_non_user_code.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/simple_user_code.py
python_modules/dagster/dagster_tests/definitions_tests/test_automation_condition_sensor_definition.py

As title -- these should be documented and visible to users.
Open to suggestions on `use_user_code_server` as a name.
Added a new `use_user_code_server` paramter to `AutomationConditionSensorDefinition`. If set, the sensor will be evaluated in the user code server (as traditional sensors are), allowing custom `AutomationCondition` subclasses to be evaluated. To learn more, view the docs [TODO].
Added a new `default_condition` parameter to `AutomationConditionSensorDefinition`. If set, this condition will be used for any assets or asset checks within the selection that do not have an automation condition defined. Requires `use_user_code_server` to be set.

[1.9] Promote hidden params to top-level args in AutomationConditionSensorDefinition

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py

[1.9] Remove experimental warnings from AutomationCondition static constructors

---

python_modules/dagster/dagster/_core/definitions/asset_spec.py
python_modules/dagster/dagster/_core/definitions/auto_materialize_policy.py
python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_impls.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/freshness_policy.py

As title. We're bumping back one more release on these deprecations to give a full release worth of non-experimental AutomationConditions before forcing a migration.
As a note, the FreshnessPolicy object was always marked as deprecated, so it was not possible to use the freshness_policy params without getting a deprecation warning. However, I added those warnings to be extra explicit.
NOCHANGELOG

[1.9] Update deprecation warnings for automation_condition, auto_materialize_policy, and freshness_policy

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py
python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/definitions_class.py
python_modules/dagster/dagster/_core/definitions/utils.py
python_modules/dagster/dagster/_core/remote_representation/external.py
python_modules/dagster/dagster/_daemon/sensor.py
python_modules/dagster/dagster_tests/definitions_tests/asset_policy_sensors_tests/test_default_auto_materialize_sensors.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/old_code_server_simulation.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_e2e.py

This shifts us to creating the default automation condition sensor in user-code land, which has the benefit of allowing us to update default values in sync with user-code updates, rather than host process version updates (particularly in a cloud context, these may be out of sync with each other).
However, in order to retain compatibility for users on a pre-1.9 version, we need to also keep the external data version as a fallback, in case their repository definition hasn't been generated using the latest code.
To support both use cases, I factored out the logic into a helper function.
Existing tests exercise these codepaths pretty heavily in a variety of oddball situations.
NOCHANGELOG

[1.9] Create default_automation_condition_sensor in Definitions object

---

python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/decorators/source_asset_decorator.py
python_modules/dagster/dagster/_core/definitions/external_asset.py
python_modules/dagster/dagster/_core/definitions/source_asset.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_on_cron_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/hourly_observable.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_e2e.py

As title -- just needed to wire this up, the system already supported this nicely. Also took the opportunity to mark the deprecated APIs as deprecated.
The `@observable_source_asset` decorator now supports an `automation_condition` argument.

[1.9] Add automation_condition to observable_source_asset

---

python_modules/dagster-graphql/dagster_graphql/schema/instigation.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_condition_evaluations.py
python_modules/dagster/dagster/_core/scheduler/instigation.py
python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_asset_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_asset_daemon_failure_recovery.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/asset_daemon_scenario.py

When running in user-code mode, evaluation ids are always based off of the tick id. This prevents us from having to deserialize the AssetDaemonCursor server side, and just in general is an easier way of producing monotonically increasing integers across multiple values.
In general, the tick id is guaranteed to be strictly larger than the AssetDaemonCursor value, as the daemon cursor (unless manually edited) cannot increase without a new tick being created. This means that it is safe to switch from daemon-mode to user-mode, but if you switch from user-mode back to daemon-mode, you could end up with an evaluation id that was much smaller, with the end result being that new evaluation records you produce would have a lower evaluation_id than older ones, messing up the history.
This change …

[1.9] Update evaluation id logic to be in sync with tick ids

---

python_modules/dagster/dagster/_core/definitions/repository_definition/repository_data_builder.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py

In https://github.com/dagster-io/dagster/pull/22569/ we started breaking this list out by asset key so that we could add assets that were referenced by sensors and schedules. This means that if a single AssetsDefinition has 50 keys, 50 Assetsdefinitions now go into AssetGraph.from_assets, which appears to be much slower. This PR adds a deduping step so that only one of each AssetsDefinition goes into AssetGraph.from_assets.
BK, run a benchmark where a single AssetsDefinition produced 5000 asset keys and observe this codepath getting much faster again
Performance improvements when loading definitions with multi-assets with many asset keys.

Dedupe AssetDefinitions before passing them into AssetGraph.from_assets

---

docs/content/integrations/dbt/using-dbt-with-dagster/downstream-assets.mdx
examples/docs_snippets/docs_snippets/integrations/dbt/tutorial/downstream_assets/assets.py
python_modules/dagster/dagster/_core/definitions/asset_key.py
python_modules/dagster/dagster/_core/definitions/asset_selection.py
python_modules/dagster/dagster/_core/definitions/resolved_asset_deps.py
python_modules/dagster/dagster/_core/definitions/target.py
python_modules/dagster/dagster/_record/__init__.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/base_scenario.py
python_modules/libraries/dagster-dbt/dagster_dbt/dbt_manifest_asset_selection.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_selection.py
python_modules/libraries/dagster-wandb/dagster_wandb/io_manager.py

Storing `path` as a tuple and avoiding custom `__eq__` and `__hash__` functions results in a substantial performance improvement for operations like building up a large global asset graph. 
For this target large graph, function calls decreased by ~70% and execution time decreased by ~50%
Before:
```
Profiling asset graph...
353461 function calls in 0.083 seconds
Ordered by: internal time
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
119166    0.021    0.000    0.027    0.000 asset_key.py:56(__hash__)
1    0.012    0.012    0.080    0.080 remote_asset_graph.py:303(_build)
1    0.008    0.008    0.018    0.018 remote_asset_graph.py:355(<dictcomp>)
119166    0.006    0.000    0.006    0.000 {built-in method builtins.hash}
1    0.005    0.005    0.012    0.012 …
```

[1.9] AssetKey path as a tuple

---

python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_evaluator.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py

Start to making the automation condition evaluator evaluate asynchronously. This won't reduce any latency yet, but will be useful once we can actually batch database queries instead of doing `AssetRecord.blocking_get`.

Make automation condition evaluator async

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_evaluator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/any_downstream_conditions_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/check_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/newly_true_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/since_operator.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_check_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_code_version_changed_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_dep_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_eager_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_failed_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_in_progress_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_latest_time_window_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_missing_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_newly_requested_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_newly_true_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_newly_updated_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_on_cron_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_on_missing_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_since_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_updated_since_cron_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_will_be_requested_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_automation_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_result_value_hash.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/automation_condition_scenario.py

We now want to make each the `AutomationCondition.evaluate` function optionally async. This is because we still want to keep it non async if users want to make their own automation conditions. To handle this, added a wrapper async evaluate function on `AutomationContext` that checks if the evaluate function is async or not.

Make AutomationCondition evaluate optionally async

---

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/storage/partition_status_cache.py

We want to make `AssetStatusCacheValue` follow the dataloader pattern as this will help optimize DA evaluation. This PR just uses `AssetStatusCacheValue.blocking_get()`, but will switch to using `AssetStatusCacheValue.gen()` when making things async in a follow up PR.

Make AssetStatusCacheValue inherit InstanceLoadableBy

---

python_modules/dagster-graphql/dagster_graphql/schema/asset_checks.py
python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/operands.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/subset_automation_condition.py
python_modules/dagster/dagster/_core/storage/asset_check_execution_record.py

We now want to make the compute asset and asset check subset functions on `AssetGraphView` async so we can use `AssetStatusCacheValue.gen()` instead of `AssetStatusCacheValue.blocking_get()`. Same for `AssetCheckExecutionRecord`.

Make compute asset/check subset functions async

---

python_modules/dagster/dagster/_core/loader.py
python_modules/dagster/dagster/_core/storage/asset_check_execution_record.py
python_modules/dagster/dagster/_core/storage/dagster_run.py
python_modules/dagster/dagster/_core/storage/event_log/base.py
python_modules/dagster/dagster/_core/storage/partition_status_cache.py
python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
python_modules/dagster/dagster_tests/utils_tests/test_dataloader.py

This lets us use the loading_context for get_asset_status_cache_values, which saves us from needing to re-fetch the asset records in here again.
Copied from demo PR https://github.com/dagster-io/dagster/pull/25270
Perf test before/after
```
pytest python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/perf_tests/test_perf.py
```

Pass loading context through _blocking_batch_load

---

python_modules/libraries/dagster-polars/dagster_polars/__init__.py
python_modules/libraries/dagster-polars/dagster_polars/io_managers/__init__.py
python_modules/libraries/dagster-polars/dagster_polars/io_managers/base.py
python_modules/libraries/dagster-polars/dagster_polars/io_managers/delta.py
python_modules/libraries/dagster-polars/dagster_polars/io_managers/parquet.py
python_modules/libraries/dagster-polars/dagster_polars/io_managers/type_routers.py
python_modules/libraries/dagster-polars/dagster_polars/types.py
python_modules/libraries/dagster-polars/dagster_polars_tests/test_upath_io_managers.py
python_modules/libraries/dagster-polars/dagster_polars_tests/test_upath_io_managers_lazy.py

This PR: 
- :art: refactors logic around loading Optional, Dict, Eager, Lazy, and Pandera-typed DataFrames (currently blocked by #22694) with new recursive `TypeRouter` (needs a better name?) helper class. This made the base IOManager logic much cleaner while supporting all combinations of these types. Also, `TypeRouter` can potentially be used in the `BigQuery` IOManager, and in general in other non-upath IOManagers.
- :boom: [TBD] drops support for storing extra metadata in storage as it became too hard to maintain. Extra jsons can be stored in separate assets. This decision is debatable and not final. 
I think `dagster-polars` is a good playground for this `TypeRouter` system. We can test if it's powerful and versatile enough here, specially with the upcoming support for native Parquet …

[dagster-polars] refactor logic for loading various types with a new `TypeRouter` system

---

examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py
python_modules/dagster/dagster/_cli/workspace/cli_target.py
python_modules/dagster/dagster/_core/definitions/definitions_load_context.py
python_modules/dagster/dagster/_core/definitions/reconstruct.py
python_modules/dagster/dagster/_core/definitions/repository_definition/repository_definition.py
python_modules/dagster/dagster/_utils/test/definitions.py
python_modules/dagster/dagster_tests/cli_tests/workspace_tests/autodiscovery_tests/test_autodiscovery.py
python_modules/dagster/dagster_tests/definitions_tests/test_definitions_load_context.py
python_modules/dagster/dagster_tests/definitions_tests/test_reconstructable.py
python_modules/libraries/dagster-aws/dagster_aws_tests/pipes_tests/test_pipes.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_asset_specs.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/test_asset_specs.py

Currently, `StateBackedDefinitionsLoader` stashes its reconstruction data in the output `Definitions`. This means that in order for it to be persisted, that `Definitions` object must make its way to the terminal user-specified `defs`. In the case that we build APIs which emit non-Definitions objects as a result of cached computation (e.g. specs), we lose that reconstruction data.
This PR moves to a paradigm where we store this reconstruction data in the `DefinitionsLoadContext`, where it's retrieved and attached to the final `RepositoryDefinition`.

Stash, retrieve `StateBackedDefinitionsLoader` reconstruction data in `DefinitionsLoadContext` 

---

helm/dagster/schema/schema_tests/test_instance.py
helm/dagster/schema/setup.py
helm/dagster/templates/helpers/instance/_run-coordinator.tpl

we defined schema for it but did not thread it through the .tpl 
report from https://github.com/dagster-io/dagster/issues/15752
added test
[helm] the blockOpConcurrencyLimitedRuns section of queuedRunCoordinator now correctly templates the appropriate config

[helm] fix blockOpConcurrencyLimitedRuns

---

js_modules/dagster-ui/packages/ui-core/src/app/ContentRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/app/FeatureFlags.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/app/useVisibleFeatureFlagRows.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/AutomaterializeMiddlePanelWithData.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/auto-materialization/GlobalAutomaterializationContent.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillRunsTab.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/backfill/RunsFeedBackfillPage.tsx
js_modules/dagster-ui/packages/ui-core/src/overview/OverviewRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/overview/OverviewTabs.tsx
js_modules/dagster-ui/packages/ui-core/src/pipelines/PipelineRunsRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedTabs.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedUtils.tsx
js_modules/dagster-ui/packages/ui-core/src/schedules/ScheduleRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/sensors/SensorPageAutomaterialize.tsx

Flips the feature flag for enabling the runs feed to an opt out flag. Also removes the `getRunFeedPath` function since we don't need the `/runs-feed/` link anymore
Will wait to merge this for the 1.9 release
[ui] The new version of the Runs page is now enabled by default. To use the legacy version of the Runs page, toggle the "Revert to legacy Runs page" user setting

[1.9] flip runs feed feature flag to opt-out

---

js_modules/dagster-ui/packages/ui-core/src/assets/groupByPartition.tsx

https://linear.app/dagster-labs/issue/FE-387/assets-with-both-materializations-and-observations-can-have-plot
I used an asset which materializes more often than observations about it are emitted, and verified that previously there was part of the graph showing only observations, and afterwards the displayed timerange is only the later portion where both event types are loaded.
Before:
After:
[ui] Plots for assets that emit materialization and observation events at different rates no longer display a time period missing the more frequent event type.

[ui] Clip events if asset plots load data for different time ranges

---

python_modules/libraries/dagster-powerbi/dagster_powerbi/__init__.py
python_modules/libraries/dagster-powerbi/dagster_powerbi/assets.py
python_modules/libraries/dagster-powerbi/dagster_powerbi/resource.py
python_modules/libraries/dagster-powerbi/dagster_powerbi/translator.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/repos/pending_repo.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_asset_specs.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_translator.py

As part of migrating to the APIs mocked out in https://www.notion.so/dagster/Asset-integration-customization-options-11a18b92e462807c94c2f84675021120  and https://www.notion.so/dagster/Power-BI-semantic-model-API-options-11918b92e4628006a25af3f58a6b48d9, detaches the asset spec loading process from the Power BI resource, and
moves building asset definitions explicitly into user code.
```python
resource = PowerBIWorkspace(
credentials=PowerBIToken(api_token=fake_token),
workspace_id=workspace_id,
refresh_poll_interval=0,
)
powerbi_specs = load_powerbi_asset_specs(resource, translator=MyPowerBITranslator)
powerbi_specs_and_defs = [
build_semantic_model_refresh_asset_definition(resource_key="powerbi", spec=spec)
if spec.tags.get("dagster-powerbi/asset_type") == "semantic_model"
else spec
for …
```

[dagster-powerbi] Detach spec loading, assets def building from Power BI resource

---

python_modules/dagster/dagster/_core/definitions/asset_key.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py

having these overridden to throw better messages leads the type checker to think it is iterable/indexable so hide it
updated tests

[AssetKey] hide __iter__ and __getitem__ from type checker

---

.buildkite/dagster-buildkite/dagster_buildkite/python_version.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py

The `docs_snippets`, `docs_snippets_beta`, and `automation` packages all install large numbers of dagster packages in the same environment. This can sometimes cause second-order dependency collisions, particularly in older python versions. We reduce the likelihood of this occurring by only testing these packages against the default python version.
- In the case of `automation`, this is not a problem because `automation` code only runs internally.
- For `docs_snippets` and `docs_snippets_beta`, the loss in coverage is minimal since all the dagster code actually targeted by our snippets is tested on all (compatible) versions.
Existing test suite, with `test-all` to make sure the full suite (all specified versions) are tested in the branch build.

Skip all but default python version on docs_snippets, automation tests

---

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/dlt/asset_decorator.py

- `dlt_dagster_translator` has been replaced by `dagster_dlt_translator` for standard naming convention
[embedded-elt] removes deprecated parameter `dlt_dagster_translator`

[embedded-elt] rm deprecated dlt_dagster_translator param

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_instance.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/base_asset_operator.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/gql_queries.py
examples/experimental/dagster-airlift/dagster_airlift/in_airflow/partition_utils.py
examples/experimental/dagster-airlift/dagster_airlift/test/shared_fixtures.py
examples/experimental/dagster-airlift/examples/kitchen-sink/Makefile
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/airflow_dags/migrated_partitioned.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/airflow_dags/proxied_state/migrated_daily_interval_dag.yaml
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/airflow_dags/simple_unproxied.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/dagster_defs/mapped_defs.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink_tests/integration_tests/conftest.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink_tests/integration_tests/test_e2e_mapped.py
examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink_tests/integration_tests/test_e2e_observation.py
examples/experimental/dagster-airlift/setup.py
python_modules/dagster-graphql/dagster_graphql/schema/partition_sets.py

Adds a pluggable implementation to BaseAssetsOperator which handles mapping the current airflow run to a partitioned run in Dagster. By default, we do the same thing that we do in the sensor - we attempt to map the logical date directly to a partition. 
Important points to note:
- I make the simplifying assumption that all assets within a given task share the same partitions definition. This makes it so that we can keep to the "one run" constraint from a previous PR.
- There's two points of pluggability that I think make sense to expose. The first is the method get_partition_key(context, partition_keys), which allows users to pick a partition key from the list to use.
The second is a pluggable default implementation translate_logical_date_to_partition_key, which takes a list of partition …

[dagster-airlift][rfc] Proxy operator launches partitioned runs

---

python_modules/dagster/dagster/_core/storage/runs/migration.py
python_modules/dagster/dagster_tests/general_tests/compat_tests/test_back_compat.py
python_modules/libraries/dagster-mysql/dagster_mysql_tests/compat_tests/test_back_compat.py
python_modules/libraries/dagster-postgres/dagster_postgres_tests/compat_tests/test_back_compat.py

Adds a migration to fill out the `backfill_id` column for existing runs

runs table backfill_id column - data migration

---

python_modules/dagster/dagster/_core/storage/runs/migration.py
python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py
python_modules/dagster/dagster_tests/general_tests/compat_tests/test_back_compat.py
python_modules/libraries/dagster-mysql/dagster_mysql_tests/compat_tests/test_back_compat.py
python_modules/libraries/dagster-postgres/dagster_postgres_tests/compat_tests/test_back_compat.py

If the data migration to populate the `RunsTable.backfill_id` column has been run, we can use the column to power the `exclude_subruns` filter
updated backcompat tests to show that querying runs with the `exclude_subruns` filter works before and after the migration. 
Also ran some perf tests locally against a DB with ~9 million runs and observed that the Runs Feed loads in about a second
Added a new column to the Runs table to improve performance of the Runs page. To take advantage of these performance improvements, run `dagster instance migrate`. This migration involves a schema migration to add the new column, and a data migration to populate the new column for historical runs.

filter.exclude_subruns uses backfill_id column if present

---

.buildkite/dagster-buildkite/dagster_buildkite/pipelines/prerelease_package.py
scripts/build_and_publish.sh

Updates the logic of our single-package publish BK pipeline to:
1) Allow selecting any package, not just those with fixed versions in the codebase
2) If a package is selected that doesn't have a fixed version in the codebase [meaning, it is a package released weekly with typical dagster release version numbers] mandate that the release version is a rc, so it doesn't interrupt typical user installs
The intent is that we can use this pipeline to (1) freeform release packages we don't regularly publish, e.g. `dagster-airlift` and (2) allow us to easily release release candidates for packages we do regularly publish, e.g. `dagster-looker`
Successful release: 
https://buildkite.com/dagster/publish-single-python-package/builds/56#
Flagging non-rc version for traditional package: …

[bk] Update individual package publish pipeline to handle rcs

---

python_modules/libraries/dagster-looker/dagster_looker/api/dagster_looker_api_translator.py
python_modules/libraries/dagster-looker/dagster_looker_tests/api/test_build_defs.py

Standardizes the `DagsterLookerApiTranslator` format to have a central `get_asset_spec`, `get_asset_key` method. Updates all methods so that they receive a LookerStructureData object as input.
Updated unit tests

[dagster-looker] Standardize translator signature

---

js_modules/dagster-ui/packages/ui-core/src/app/FeatureFlags.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/app/useVisibleFeatureFlagRows.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceRoot.tsx

Remove the `flagCodeLocationPage` flag, permanently enabling the new code location pages in OSS.
View app with legacy nav turned on and off, navigate to Deployment. Click on code locations, verify that their new pages render correctly.
[ui] New code location pages with library versions, metadata, and definitions.

[ui] Turn on new code location pages

---

js_modules/dagster-ui/packages/ui-core/src/overview/OverviewRoot.tsx

Fix the `'unknown'` state for AMP flags, when navigating directly to `/overview/automation`.
This route currently redirects to `/automation` if the user is not using the legacy nav and if the AMP sensor flag state is not `'has-global-amp'`. Unfortunately, on initial pageload we may not yet have received the response from the GraphQL request that asks for the flag state, so this is likely to be `'unknown'`, and the page redirects.
Fix this by waiting until the query resolves before redirecting or rendering anything other than a `div`.
Test permutations of legacy nav and AMP sensor flag state.
- Verify that redirect to `/overview/automation` occurs when the flag is `'has-global-amp'`, on navigation and full pageload.
- Verify that when the flag is set to `'has-sensor-amp'`, the page …

[ui] Resolve AMP state before handling Overview AMP route

---

python_modules/libraries/dagster-tableau/dagster_tableau/translator.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_reconstruction.py

Standardizes the `DagsterTableauTranslator` format to have a central `get_asset_spec`, `get_asset_key` method.
Updated unit tests

[dagster-tableau] Standardize translator signature

---

python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
python_modules/libraries/dagster-sigma/dagster_sigma/translator.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/pending_repo_with_translator.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/test_translator.py

Standardizes the `DagsterSigmaTranslator` format to:
1) Have a central `get_asset_spec`, `get_asset_key` method
2) Pass the `asset_key` returned by `get_asset_key` to `get_asset_spec`
3) Enforce that the key returned by `get_asset_spec` matches the input key
Updated unit tests

[dagster-sigma] Standardize translator signature

---

python_modules/dagster/dagster/_core/storage/alembic/versions/045_16e3655b4d9b045_add_bulk_actions_job_name_column_and_.py
python_modules/dagster/dagster/_core/storage/alembic/versions/046_16e3655b4d9b045_add_bulk_actions_job_name_column_and_tags_table.py
python_modules/dagster/dagster/_core/storage/runs/schema.py
python_modules/dagster/dagster_tests/general_tests/compat_tests/test_back_compat.py
python_modules/libraries/dagster-mysql/dagster_mysql_tests/compat_tests/test_back_compat.py
python_modules/libraries/dagster-postgres/dagster_postgres_tests/compat_tests/test_back_compat.py

This is the base of a stack to add two things to our storage - a `BackfillTags` table and a `job_name` column to the `BulkActions` table.
Adding `BackfillTags` allows us to do efficient tags filtering on backfills, which is a capability we introduced with the new Runs Page 
Adding `job_name` column allows us to do efficient job_name filtering on backfills, which is a capability we introduced with the new Runs Page. 
Previously, both of these kinds of filtering were done by filtering the RunsTable/RunTagsTable which made the queries more expensive

schema migration to add job_name to bulk actions table and backfill tags table

---

python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py
python_modules/dagster/dagster_tests/general_tests/compat_tests/test_back_compat.py
python_modules/libraries/dagster-mysql/dagster_mysql_tests/compat_tests/test_back_compat.py
python_modules/libraries/dagster-postgres/dagster_postgres_tests/compat_tests/test_back_compat.py

See https://github.com/dagster-io/dagster/pull/25460 for additional context 
updates storage to write to the new backfill_tags and job_name table/column if they are present

write bulk actions job name and tags if new column/table exists

---

python_modules/dagster/dagster/_core/storage/runs/migration.py
python_modules/dagster/dagster_tests/general_tests/compat_tests/test_back_compat.py
python_modules/libraries/dagster-mysql/dagster_mysql_tests/compat_tests/test_back_compat.py
python_modules/libraries/dagster-postgres/dagster_postgres_tests/compat_tests/test_back_compat.py

See https://github.com/dagster-io/dagster/pull/25460 for additional context
Adds the data migration to populate BackfillTags table and BulkActionsTable.job_name with historical data

data migration for populating backfill job name and backfill tags

---

python_modules/dagster/dagster/_core/storage/runs/migration.py
python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py
python_modules/dagster/dagster_tests/general_tests/compat_tests/test_back_compat.py
python_modules/libraries/dagster-mysql/dagster_mysql_tests/compat_tests/test_back_compat.py
python_modules/libraries/dagster-mysql/dagster_mysql_tests/test_run_storage.py
python_modules/libraries/dagster-postgres/dagster_postgres_tests/compat_tests/test_back_compat.py

See https://github.com/dagster-io/dagster/pull/25460 for additional context
updates backfill queries to use the job_name column and backfill tags table if the migrations have run
Added a new column to the BulkActions table and a new BackfillTags table to improve performance when filtering Backfills. To take advantage of these performance improvements, run `dagster instance migrate`. This migration involves a schema migration to add the new column and table, and a data migration to populate the new column for historical backfills.

storage reads from backfill tags table and backfill job_name column if they are populated

---

python_modules/libraries/dagster-looker/dagster_looker/__init__.py
python_modules/libraries/dagster-looker/dagster_looker/api/dagster_looker_api_translator.py
python_modules/libraries/dagster-looker/dagster_looker/api/resource.py
python_modules/libraries/dagster-looker/dagster_looker_tests/api/mock_looker_data.py
python_modules/libraries/dagster-looker/dagster_looker_tests/api/test_build_defs.py

Adds the ability to filter incoming dashboards and models to the Looker API resource loading method.
```python
load_looker_asset_specs(
looker_resource,
looker_filter=LookerFilter(
dashboard_folders=[["my_folder", "my_subfolder"]],
only_fetch_explores_used_in_dashboards=True,
),
)
```
The optional `LookerFilter` object can include config to only fetch dashboards from specific folder paths, and also whether to optionally only fetch explores that dashboards reference.
New unit test.

[dagster-looker] Add ability to filter incoming dashboards, models

---

docs/sphinx/sections/api/apidocs/assets.rst
python_modules/dagster/dagster/_core/definitions/asset_out.py
python_modules/dagster/dagster/_core/definitions/asset_spec.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/source_asset_decorator.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_decorators.py
python_modules/dagster/dagster_tests/cli_tests/command_tests/test_telemetry.py
python_modules/dagster/dagster_tests/general_tests/test_internal_init_implementations.py

As title
The `auto_materialize_policy` and `freshness_policy` arguments have been hidden from the type signature of `AssetSpec`, `AssetOut`, `@asset`, and `@graph_asset`. Existing code using these arguments will continue to function, but they will not show up in typeahead or docs.
The `auto_observe_interval_minutes` and `freshness_policy` arguments of `@observable_source_asset` have similarly been hidden.

[1.9] Hide references to AutoMaterializePolicy / FreshenssPolicy from docs / type signatures

---

examples/experimental/dagster-airlift/examples/dbt-example/Makefile
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/constants.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/dbt_cloud_airflow.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/dbt_cloud_assets.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/dbt_cloud_utils.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/federated_airflow_dags/dags.py
examples/experimental/dagster-airlift/examples/dbt-example/dbt_example_tests/integration_tests/test_federated.py
examples/experimental/dagster-airlift/examples/dbt-example/setup.py
examples/experimental/dagster-airlift/examples/dbt-example/tox.ini
examples/experimental/dagster-dlift/dagster_dlift/translator.py

[dagster-airlift] [federation-demo] dbt cloud side

---

python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/storage/event_log/base.py
python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py
python_modules/dagster/dagster/_core/storage/legacy_storage.py
python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

We want to filter the number of partitions we scan for, so that we can optimize the restricted partition case.
BK

add partition filter to get_latest_storage_id_by_partition

---

python_modules/libraries/dagster-ssh/dagster_ssh/resources.py

Running pyright locally was giving the warning that some `# type: ignore` comments were unnecessary. This removes them.
```
make pyright
```

[dagster-ssh]: Removes unnecessary type ignores

---

.buildkite/dagster-buildkite/dagster_buildkite/pipelines/dagster_oss_main.py

indicates to the internal buildkite pipeline that this step has been triggered from an OSS merge. see https://github.com/dagster-io/internal/pull/11936

set DAGSTER_FROM_OSS in internal pipeline execution

---

js_modules/dagster-ui/packages/ui-core/src/assets/LaunchAssetChoosePartitionsDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadRoot.tsx

https://linear.app/dagster-labs/issue/FE-619/prevent-accidental-escape-and-clearing-on-launchpad-ui-if-a-change-is

Set canEscapeKeyClose to false on launchpad dialog

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py
python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/utils.py
python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
python_modules/dagster/dagster_tests/definitions_tests/asset_policy_sensors_tests/test_default_auto_materialize_sensors.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/500_eager_assets.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/backfill_simple_non_user_code.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/backfill_simple_user_code.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/backfill_with_runs_and_checks.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/custom_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/default_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/simple_non_user_code.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/simple_user_code.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_asset_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/test_automation_condition_sensor_definition.py
python_modules/dagster/dagster_tests/definitions_tests/test_repository_definition.py

This is the standard naming convention for sensors.
[breaking] Renamed the `asset_selection` parameter on `AutomationConditionSensorDefinition` to `target`, to align with existing sensor APIs.

[1.9] Update asset_selection paramter of AutomationConditionSensorDefinition to `target`

---

python_modules/dagster/dagster/_core/remote_representation/external.py

wait to call job_index.snapshot_id until its needed

[RemoteJob] lazy snapshot_id calculation

---

python_modules/dagster/dagster/_core/pipes/merge_streams.py
python_modules/libraries/dagster-polars/dagster_polars/io_managers/type_routers.py
python_modules/libraries/dagster-powerbi/dagster_powerbi/resource.py
python_modules/libraries/dagster-sigma/dagster_sigma/resource.py

As title. We're considering removing 3.8 support anyway, but this is a quick fix and the scope of removing this type hint is quite limited so I think it's easiest to just make this less specific.
EDIT: also tossed in another typing / version dependent fix. The issue is that version 3.9.1 is >= 3.9, meaning we were doing the typing import for versions of python that we shouldn't have been. I copied the 3.10 logic over from a different part of the codebase, so quite confident that it's correct
EDIT2: I assume importing `Sequence` from collections instead of typing was accidental @benpankow? That was also breaking on older python versions

Fix typehint that doesn't work on py3.8

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
azure-pipelines.yml
examples/experimental/dagster-blueprints/dagster_blueprints_tests/__snapshots__/test_load_defs_from_yaml.ambr
examples/experimental/dagster-blueprints/dagster_blueprints_tests/test_load_defs_from_yaml.py
pyright/alt-1/requirements-pinned.txt
pyright/master/requirements-pinned.txt
python_modules/dagster/dagster/_config/pythonic_config/config.py
python_modules/dagster/dagster/_model/__init__.py
python_modules/dagster/dagster/_model/pydantic_compat_layer.py
python_modules/dagster/dagster/_utils/pydantic_yaml.py
python_modules/dagster/dagster_tests/core_tests/pythonic_config_tests/test_constraints.py
python_modules/dagster/dagster_tests/core_tests/pythonic_config_tests/test_errors.py
python_modules/dagster/dagster_tests/core_tests/test_op_invocation.py
python_modules/dagster/dagster_tests/model_tests/test_dagster_model_serdes.py
python_modules/dagster/setup.py
python_modules/dagster/tox.ini
python_modules/libraries/dagster-databricks/dagster_databricks/resources.py
python_modules/libraries/dagster-dbt/dagster_dbt/core/resource.py
python_modules/libraries/dagster-dbt/tox.ini
python_modules/libraries/dagster-snowflake/dagster_snowflake/resources.py
python_modules/libraries/dagster-snowflake/tox.ini

Internal companion PR: https://github.com/dagster-io/internal/pull/12357
Bump min version of pydantic to 2.x in the `dagster` core. This rests on downstack work supporting pydantic 2 in some subsidiary packages. Changes include:
- Removing tox envs for pydantic 1/2-specific testing
- A bunch of code that branched on whether pydantic 1 vs 2 was installed in env
There is a whole additional "pydantic compat layer" that was designed to provide a uniform internal interface for our pydantic-using code depending on whether 1 or 2 was installed. I'll remove this in a followup.
`dagster` now requires `pydantic>=2`.

Remove pydantic 1.x support

---

integration_tests/test_suites/k8s-test-suite/tests/test_pipes.py
python_modules/dagster/dagster/_core/pipes/client.py
python_modules/dagster/dagster/_core/pipes/context.py
python_modules/dagster/dagster/_core/pipes/subprocess.py
python_modules/dagster/dagster/_core/pipes/utils.py
python_modules/dagster/dagster_tests/execution_tests/pipes_tests/in_process_client.py
python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/ecs.py
python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/emr.py
python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/emr_serverless.py
python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/glue.py
python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/lambda_.py
python_modules/libraries/dagster-databricks/dagster_databricks/pipes.py
python_modules/libraries/dagster-docker/dagster_docker/pipes.py
python_modules/libraries/dagster-k8s/dagster_k8s/pipes.py

https://github.com/dagster-io/dagster/pull/25541 makes `AssetExecutionContext` not a subclass of `OpExecutionContext`. This PR is the changes to Pipes libraries required to make that change. 
Includes updating type signatures to allow for `AssetExecutionContext`, since previously, type annotation of `OpExecutionContext` would have allowed `AssetExecutionContext` to be passed
For any `context` calls that needed to be updated, I've added a comment explaining the change 
existing test suite

[pipes] modify context type signatures and usage for making AssetExecutionContext a standalone class

---

python_modules/dagster-graphql/dagster_graphql/implementation/external.py
python_modules/dagster-graphql/dagster_graphql/implementation/run_config_schema.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql/schema/config_types.py
python_modules/dagster-graphql/dagster_graphql/schema/dagster_types.py
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/config.py
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/logger.py
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/mode.py
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/resource.py
python_modules/dagster-graphql/dagster_graphql/schema/resources.py
python_modules/dagster-graphql/dagster_graphql/schema/run_config.py
python_modules/dagster-graphql/dagster_graphql/schema/solids.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_config_types.py
python_modules/dagster/dagster/_core/workspace/context.py

go through the context for resolving pieces of information to facilitate different backing implementations in other workspace classes.
existing tests

[graphql] refactor node def, config, and type resolution from assets

---

python_modules/dagster/setup.py

A new release `4.0.0` of `croniter` introduces breaking changes in current dagster schedule definitions.
```python
@schedule(
cron_schedule="0 10 * * 7", 
)
def some_schedule(context: ScheduleEvaluationContext):
``` 
The current cron string should work. Instead, we are getting the error:
```
dagster._core.errors.DagsterInvalidDefinitionError: Found invalid cron schedule '0 10 * * 7' for schedule 'some_schedule''. Dagster recognizes standard cron expressions consisting of 5 fields.
```
Mentioned Issue: #25570
> Pins croniter below 4.0.0

Pins croniter<4.0.0

---

python_modules/dagster/dagster_tests/scheduler_tests/test_cron_string_iterator.py

Test that will fail if we break the ability to reference '7' for Sunday.

Add test that breaks when we upgrade to croniter 4

---

js_modules/dagster-ui/packages/ui-core/src/runs/useCursorPaginatedQuery.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/useRunsFeedEntries.tsx

This fixes an issue flagged here: https://dagsterlabs.slack.com/archives/C03CCE471E0/p1729870052943159, in which two uses of `useCursorPaginatedQuery` exist on the page and need to separately store their pagination state in the URL.
I chose to change the new `RunsFeed`'s cursor because 1) the runs feed is embedded within a variety of pages (eg: asset automation tab, sensor runs / schedule runs, etc), and I think it's likely to be the common element conflicting with other uses of the hook and 2) it's new, and uses a new cursor style, so any saved pre-1.9 links would be broken anyway.
I changed the cursor to `runs_before=abcd123`, which reflects how the cursor operates in the run feed API.
I repro'd the case in the slack discussion and verified that the offending scenario works correctly …

[ui] Change cursor query key used for runs feed

---

python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py

Switches the latest materializations by partition resolver to always use the optimized latest storage ids by partition call.
BK

always fetch storage_ids by partition for latest materializations call

---

js_modules/dagster-ui/packages/ui-core/src/app/ExecutionSessionStorage.tsx
js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadAllowedRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/ticks/DryRunRequestTable.tsx

As titled, fixes the above issue.
So the original implementation redirects to the `/setup` path which all it does is save the configuration to localStorage and then immediately redirects to the `/playground` route. This solution cuts out the middleman and just directly saves the config to localStorage and then opens `/playground` directly. This avoids the need to pass a large config via the URL.
Used the test sensor feature and opened one of the config's it returned.

Fix "Large launchpad configs returned by Test Sensor feature causes URL to be too long and page to be unloadable"

---

js_modules/dagster-ui/packages/ui-core/src/app/App.tsx
js_modules/dagster-ui/packages/ui-core/src/app/AppTopNav/AppTopNavLinks.tsx
js_modules/dagster-ui/packages/ui-core/src/app/FeatureFlags.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/app/useVisibleFeatureFlagRows.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/auto-materialization/AutomaterializationRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/overview/OverviewRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/overview/OverviewTabs.tsx
js_modules/dagster-ui/packages/ui-core/src/settings/SettingsMainPane.tsx

Eliminate `isLegacyNav` flag, put all users into new navigation structure.
Buildkite. Load app, verify that nav and routes are rendered properly.
[ui] Enable new top navigation and deployment pages for all users.

[ui] Eliminate legacy nav

---

examples/experimental/dagster-blueprints/dagster_blueprints_tests/test_load_defs_from_yaml.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
python_modules/dagster/dagster/_core/definitions/asset_graph_differ.py
python_modules/dagster/dagster/_core/definitions/asset_graph_subset.py
python_modules/dagster/dagster/_core/definitions/asset_layer.py
python_modules/dagster/dagster/_core/definitions/asset_selection.py
python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
python_modules/dagster/dagster/_core/execution/asset_backfill.py
python_modules/dagster/dagster/_core/execution/context/data_version_cache.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster_tests/asset_defs_tests/asset_graph_view_tests/test_basic_asset_graph_view.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_external_asset_graph.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/automation_condition_scenario.py
python_modules/dagster/dagster_tests/storage_tests/branching_io_manager_tests/utils.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_code_references.py
python_modules/libraries/dagster-sdf/dagster_sdf_tests/test_code_references.py

Rename this method to better communicate that getting the full set of asset keys may not be a "free" operation, as is the case in asset graph implementations that lazily load. This was motivated by the callsites updated in this PR that used `key in graph.all_asset_keys` instead of `graph.has(key)` which can be supported by more performant implementations. 

[asset graph] all_asset_keys -> get_all_asset_keys()

---

docs/content/integrations/dbt/reference.mdx
examples/docs_snippets/docs_snippets/integrations/dbt/dbt.py

As the title. Fixes [DS-402](https://linear.app/dagster-labs/issue/DS-402/add-dbt-and-dagster-branch-deployment-guide)
Docs preview
[dagster-dbt] A guide on how to use dbt defer with Dagster branch deployments has been added to the dbt reference.

[docs] Add dbt defer and Dagster branch deployments guide

---

python_modules/libraries/dagster-tableau/dagster_tableau/assets.py
python_modules/libraries/dagster-tableau/dagster_tableau/resources.py

Make `load_tableau_asset_specs` and `build_tableau_executable_assets_definition` experimental before releasing to 1.9

[dagster-tableau] Make new Tableau APIs experimental

---

python_modules/libraries/dagster-looker/dagster_looker/api/assets.py
python_modules/libraries/dagster-looker/dagster_looker/api/resource.py

Make `load_looker_asset_specs` and `build_looker_pdt_assets_definitions` experimental before releasing to 1.9

[dagster-looker] Make new Looker APIs experimental
