python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/slice_conditions.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/updated_since_cron_condition.py
As title -- just sorts the methods a bit to make thigns with similar purposes be next to each other. Also adds cached_method decorators to a few methods and adds a * to their type signatures (cached method does not support positional arguments)
=> [DS][37/n] Reorganize AssetGraphView methods

python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_condition.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_eager_condition.py
As title. This was alluded to in the initial eager policy PR, this is putting them in action. In the case that the latest run for an asset partition failed, we will not request the asset if we've already requested it within the last hour. This puts a natural "rate limit" on the asset in the case that it is repeatedly failing, but does not interfere if the asset is materializing as expected.
=> [DS][39/n] Use FailedSchedulingCondition and ScheduledSince condition in eager policy

python_modules/dagster/dagster/_core/definitions/auto_materialize_policy.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_condition.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_auto_materialize_policy_conversion.py
As title -- this is a more convenient way of converting a condition to a policy, as it doesn't require an additional import.
Also makes sure that the policy survives serdes and all that
=> [DS][40/n] Create an as_auto_materialize_policy method on SchedulingCondition

docs/content/integrations/dbt/quickstart.mdx
This PR updates the quickstart example for dbt + Dagster - it adds the steps to create a brand new Dagster project using the scaffold to wrap a dbt project.
This work is the continuation of #21240 
BK 
+
local
```
make mdx-full-format
```
=> Add brand new Dagster project example to dbt quickstart

helm/dagster/charts/dagster-user-deployments/values.yaml, helm/dagster/values.yaml
Resolves https://github.com/dagster-io/dagster/issues/21698
Removed occurrences in documentation where earlier it was mentioned that "dagster code-server start" and "dagster api grpc" take the same arguments.
=> Resolution for issue #21698

python_modules/libraries/dagster-looker/dagster_looker/asset_decorator.py, python_modules/libraries/dagster-looker/dagster_looker_tests/looker_projects/__init__.py, python_modules/libraries/dagster-looker/dagster_looker_tests/looker_projects/test_exception_derived_table/views/exception_derived_table.view.lkml, python_modules/libraries/dagster-looker/dagster_looker_tests/test_asset_decorator.py
Parse the Looker substitution syntax ($) using regex. See [https://cloud.google.com/looker/docs/sql-and-referring-to-lookml#substitution_operator_](https://cloud.google.com/looker/docs/sql-and-referring-to-lookml#substitution_operator_) for more details.
This is similar to how dbt parses their jinja model templates. If raw, non-templated tables are included in the SQL alongside templated Looker views from Looker substitution, we will only provide the templated Looker views as upstream dependencies.
For SQL definitions that only use non-templated tables, we will still parse them using `sqlglot`.
And with SQL definitions that only use non-templated tables, but have [Liquid templating](https://cloud.google.com/looker/docs/liquid-variable-reference), no parsing will occur.
pytest
=> feat(looker): represent looker views dependencies from substitution

docs/content/integrations/dbt/quickstart.mdx, examples/docs_snippets/docs_snippets/integrations/dbt/quickstart.py
This PR updates the quickstart example for dbt + Dagster - it adds the steps to update an existing Dagster project to wrap a dbt project.
This work is the continuation of #21240  and #21816
BK 
+
local
```
make mdx-full-format
```
=> Add existing Dagster project example to dbt quickstart

python_modules/libraries/dagster-looker/dagster_looker/asset_decorator.py, python_modules/libraries/dagster-looker/dagster_looker/asset_utils.py
Addresses https://github.com/dagster-io/dagster/pull/21687#discussion_r1592844429.
pytest
=> refactor(looker): build dashboard specs in a utility function

python_modules/dagster/dagster/_core/definitions/resolved_asset_deps.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection_error_informative.py
Adds another suggestion rule which looks for assets with the same name, but any prefix, if the user-specified key has no prefix.
unit test
=> provide asset suggestion for prefixed asset with same name

python_modules/libraries/dagster-looker/dagster_looker/asset_utils.py, python_modules/libraries/dagster-looker/dagster_looker/dagster_looker_translator.py, python_modules/libraries/dagster-looker/dagster_looker_tests/test_asset_decorator.py
Same thing as https://github.com/dagster-io/dagster/pull/21835, but for description, metadata, group name, owners, and tags.
pytest
=> feat(looker): allow customization of `AssetSpec` through `DagsterLookerTranslator`

js_modules/dagster-ui/packages/ui-core/src/app/QueryRefresh.tsx, js_modules/dagster-ui/packages/ui-core/src/overview/OverviewTimelineRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/types/useRunsForTimeline.types.ts, js_modules/dagster-ui/packages/ui-core/src/runs/useRunsForTimeline.tsx
Split up the RunTimelineQuery into 3 distinct queries.
Next PR will chunk these queries up and apply a limit.
Load the elementl Run timeline
https://app.datadoghq.com/rum/sessions?query=%40application.id%3A6d12cca2-0263-463b-a90e-cc6c524e14bd%20%40usr.email%3Amarco%40dagsterlabs.com%20%40type%3Aview&agg_m=count&agg_m_source=base&agg_q=%40issue.id&agg_q_source=base&agg_t=count&cols=&event=AgAAAY94QhVDg2Qy6QAAAAAAAAAYAAAAAEFZOTRRaFZEQUFDU2JrcW1QVkVJMWJPaAAAACQAAAAAMDE4Zjc4NDItNmU2Ny00OGU0LTk3Y2EtMTk1ZmQ5ZDYxZjAx&fromUser=true&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=6594261810473780884&tab=error&top_n=10&top_o=top&view=spans&viz=stream&x_missing=true&from_ts=1715709480599&to_ts=1715709600599&live=true
=> [1/2] Split up RunTimelineQuery

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_checks.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py
Save 4 characters per each selected dbt asset and check.
Before, we were being explicit that `fqn:` was being used. Instead, we can just let dbt figure that out. From https://docs.getdbt.com/reference/node-selection/methods, `fqn:` is one of the default selectors anyways.
This isn't going to make a huge dent in the most diabolical of cases, but might as well cash in on some character savings.
pytest
=> feat(dbt): omit `fqn:` when constructing a subssetted execution

python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_row_count_postprocessing.py
Fix for flaky dagster-dbt test which uses a standalone duckdb file for the row count test, to control for duckdb holding the file lock.
Replaces #21763 
bk
=> [dagster-dbt][fix] use standalone duckdb dbfile for row count test

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_row_count_postprocessing.py
Refactors the user-facing api to tell dbt to fetch row counts for users.
Makes `dbt.cli(...).stream()` return a `DbtEventIterator`, a thin wrapper around `collections.abc.Iterator` which holds some custom methods, in this case `fetch_row_counts`:
```python
yield from dbt.cli(["build"], context=context).enable_fetch_row_count().stream()
yield from dbt.cli(["build"], context=context).stream().fetch_row_counts()
```
The impl remains identical, but eventually we could move to a more generic impl under the hood that lets users apply their own transformations after materializations complete.
```python
yield from dbt.cli(["build"], context=context).stream().fetch_row_counts().map(lambda event: ...)
```
=> [dagster-dbt] refactor fetch-row-count user-facing API

python_modules/dagster/dagster/_core/definitions/metadata/table.py
This reflects the runtime type-checking we're doing inside the constructor.
This was causing problems, because we were loading values from the DB that had `None` values and then an outer class that was a Pydantic model was using the type annotations to validate them, and erroring.
```
records.0.0.extension.bool
Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]
For further information visit https://errors.pydantic.dev/2.6/v/bool_type
```
=> update TableRecord type annotation to accept None values

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py
Moves the generic param for `DbtEventIterator` to `typing.Generic` since `collections.abc.Iterator` is not generic in 3.8
Imported class successfully in 3.8 and 3.10 locally + bk
=> fix iterator behavior in 3.8

python_modules/dagster/setup.py
incompatibility manifests as: 
```
File "/Users/alangenfeld/dagster/python_modules/dagster/dagster/_core/storage/upath_io_manager.py", line 386, in load_partitions_async
awaited_objects = asyncio.get_event_loop().run_until_complete(collect())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/alangenfeld/.pyenv/versions/3.11.7/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File "/Users/alangenfeld/dagster/python_modules/dagster/dagster/_core/storage/upath_io_manager.py", line 373, in collect
raise result
File "/Users/alangenfeld/dagster/python_modules/dagster/dagster_tests/storage_tests/test_upath_io_manager.py", line 480, in load_from_path
fs = self.get_async_filesystem(path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```
=> pin fsspec in test

docs/next/components/FeedbackModal.tsx
- Feedback modal was lost when scrolled on the page, this persists the modal by setting the position to `fixed`
- Running locally
=> [docs] set feedback modal position as fixed

python_modules/dagster-graphql/dagster_graphql/implementation/telemetry.py, python_modules/dagster/dagster/_core/definitions/data_time.py, python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py, python_modules/dagster/dagster/_utils/__init__.py
Fixes issue mentioned by @psarka
Refactors method to explicitly specify timezone when converting from unix timestamp to ISO8601.
Subsequently retains or discards the timezone depending on existing functionality.
There is probably a good learning opportunity for me here. I used a snippet to validate the output was unchanged.
Please educate me about how you want to do this properly.
=> Replace deprecated utcfromtimestamp method

python_modules/libraries/dagster-looker/dagster_looker/dagster_looker_translator.py, python_modules/libraries/dagster-looker/dagster_looker_tests/test_asset_decorator.py
LookML element already exists: https://cloud.google.com/looker/docs/reference/param-lookml-dashboard-element
Instead, label it as a "LookML structure": https://cloud.google.com/looker/docs/lookml-terms-and-concepts#major_lookml_structures. A "LookML structure" can be a model, view, explore, etc. It's defined by a path to the file defining the structure, the structure type, and the parsed contents of the structure.
N/A, it's a rename.
=> refactor(looker): rename `lookml_element` to `lookml_structure`

python_modules/libraries/dagster-looker/dagster_looker/asset_utils.py, python_modules/libraries/dagster-looker/dagster_looker_tests/test_asset_decorator.py
We were making `N` dashboard specs corresponding to the dashboard's `N` upstream explore dependencies. Instead, make one dashboard spec with `N` dependencies.
pytest
=> fix(looker): collect all deps for a dashboard

python_modules/libraries/dagster-looker/dagster_looker/__init__.py, python_modules/libraries/dagster-looker/dagster_looker/asset_utils.py, python_modules/libraries/dagster-looker/dagster_looker/dagster_looker_translator.py, python_modules/libraries/dagster-looker/dagster_looker_tests/test_asset_decorator.py
Before, `DagsterLookerTranslator.get_asset_key(...)` only operated to generate the `key` of the `AssetSpec` in question. Now, it also operates on the `deps` of the `AssetSpec`.
Also, implement `DagsterLookerTranslator.get_deps(...)`.
pytest:
- See all keys of a `@looker_assets` instance change when overriding `get_asset_key`
- See `deps` change when overriding `get_deps`.
=> feat(looker): implement `get_deps` for `DagsterLookerTranslator`

python_modules/dagster-graphql/dagster_graphql/implementation/events.py, python_modules/dagster/dagster/__init__.py, python_modules/dagster/dagster/_core/definitions/metadata/__init__.py, python_modules/dagster/dagster/_core/definitions/metadata/source_code.py, python_modules/dagster/dagster_tests/asset_defs_tests/asset_package/__init__.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_defs_source_metadata.py
Adds the `link_to_source_control` utility fn which converts all local source code reference metadata in the passed assets to references to source control. These local paths are mapped to the path in source control using a user-passed local git root. The path from the git root to the file locally is used as the filepath within source control.
For example:
```python
@asset 
def my_asset() -> pd.DataFrame:
...
@asset 
def my_other_asset() -> pd.DataFrame:
...
assets=link_to_source_control(
with_source_code_references([my_asset, my_other_asset]),
source_control_url="https://github.com/dagster-io/dagster",
source_control_branch="master",
repository_root_absolute_path=file_relative_path(__file__, "../../"),
)
)
```
A stacked PR will introduce a utility method that will wrap …
=> [4/n] add python api for replacing local file references with source control links

docs/content/about/telemetry.mdx
We're adding frontend javascript based telemetry and we want to be transparent so we're updating the docs to point to that javascript. We're still not collecting any identifiable information about Dagster definitions.
=> Update telemetry docs

python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
=> remove get_event_records calls from graphql

python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster/dagster/_utils/caching_instance_queryer.py
=> remove get_event_records calls - from caching instance queryer

python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster/dagster/_core/storage/branching/branching_io_manager.py, python_modules/dagster/dagster/_utils/caching_instance_queryer.py
=> remove get_event_records calls from branching io manager

python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster/dagster/_core/definitions/asset_sensor_definition.py, python_modules/dagster/dagster/_core/storage/branching/branching_io_manager.py, python_modules/dagster/dagster/_utils/caching_instance_queryer.py
=> remove get_event_records calls from asset sensor definition

python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster/dagster/_core/definitions/asset_sensor_definition.py, python_modules/dagster/dagster/_core/execution/asset_backfill.py, python_modules/dagster/dagster/_core/storage/branching/branching_io_manager.py, python_modules/dagster/dagster/_utils/caching_instance_queryer.py
=> remove get_event_records calls from asset backfill

python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster/dagster/_core/definitions/asset_sensor_definition.py, python_modules/dagster/dagster/_core/definitions/multi_asset_sensor_definition.py, python_modules/dagster/dagster/_core/execution/asset_backfill.py, python_modules/dagster/dagster/_core/storage/branching/branching_io_manager.py, python_modules/dagster/dagster/_utils/caching_instance_queryer.py
We want to deprecate get_event_records calls in favor of narrower APIs.
This call-site has the most user-facing changes in converting from `get_event_records` -> `fetch_materializations`, mostly because we have to enforce a limit on a sensor method that we expose off of the context.
I'm not sure if there's a more elegant way to do this, based on the internals of the multi assent sensor, and knowing how many records we can advance per tick (I have a sneaking suspicion that we can do something more clever here).
This PR takes the crudest possible approach: batching calls for chunks in a loop, and warning when called without a limit.
BK
=> remove get_event_records calls from multi asset sensor

python_modules/libraries/dagster-dbt/dagster_dbt/cli/app.py, python_modules/libraries/dagster-dbt/dagster_dbt/include/setup.py.jinja, python_modules/libraries/dagster-dbt/dagster_dbt/version.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/cli/test_scaffold.py, python_modules/libraries/dagster-dbt/setup.py
Make the version upper bound of the dbt adapter explicit. Don't assume that it will follow the `dbt-core` pin from `dagster-dbt`.
pytest
=> feat(dbt): pin dbt adapters according to `dbt-core` version upper bound

python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py, python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_impls.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/legacy/legacy_context.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/legacy/rule_condition.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/asset_condition_scenario.py
This goal of this is to introduce a user-facing testing API for scheduling conditions that can be executed outside of the Asset Daemon. The process here is to extract the asset condition evaluation logic out of the `AssetDaemonContext` and into its own class that does not reference `AssetDaemonContext`. The general process is to hoist the properties on the `AssetDaemonContext` that these code paths need out of that class, and then change code to reference the constituent properties instead of the context.
This PR eliminates the `AssetDaemonContext` property from `LegacyRuleEvaluationContext`
BK
=> Hoist the asset daemon context out of the LegacyRuleEvaluationContext

python_modules/dagster/dagster/_core/definitions/asset_condition_evaluator.py, python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/legacy/legacy_context.py
Remove references to `AssetDaemonContext` in the just-introduced  `AssetConditionEvaluator`
BK
=> AssetConditionEvaluator no longer refers to AssetDaemonContext

python_modules/dagster/dagster/_config/pythonic_config/conversion_utils.py, python_modules/dagster/dagster/_config/pythonic_config/resource.py, python_modules/dagster/dagster/_config/pythonic_config/type_check_utils.py, python_modules/dagster/dagster/_utils/typed_dict.py, python_modules/dagster/dagster/_utils/typing_api.py, python_modules/dagster/dagster_tests/core_tests/pythonic_config_tests/test_utils.py, python_modules/dagster/dagster_tests/definitions_tests/test_op_definition.py
consolidate the `is_optional` check that was added for configurable resources in to the older `is_closed_python_optional_type` to support `|` based `Optional` types in `@op` and friends 
added test
=> [op] handle pipe union based optional

python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_user_space_ds_api.py
Add a rudimentary `execute_ds_tick` in test code as a proof of concept. We need to discuss what we want the real API to be, but this is a good intermediate milestone.
BK
=> Add execute_ds_tick in test code

python_modules/dagster/dagster/_daemon/daemon.py
Summary:
Allows daemons to be configured in such a way that they do not all hammer the DB simultaneously on startup
Test Plan: See corresponding internal PR
=> Add an "initial_jitter_seconds" field to DagsterDaemon

python_modules/dagster/dagster/_core/definitions/time_window_partitions.py, python_modules/dagster/dagster/_utils/cronstring.py, python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py
Summary:
For daily, hourly, and minute-ly partition sets, do basic math rather than enumerating every single partition key and counting them.
Test Plan: A representative large asset graph with many large partition sets goes from taking 65 seconds to computing counts on all assets to taking 0.4 seconds to compute counts on all assets
=> Speed up get_num_partitions for common cases

js_modules/dagster-ui/packages/ui-core/src/instance/InstanceConcurrency.tsx
The wrapper of the virtualized table container didn't have a max-height so the table was rendering every single key and fetching every single key. To fix this I added a wrapper higher up the tree `<Box flex={{direction: 'column'}} style={{overflow: 'auto', height: '100%'}}>`
I also added search filtering since you can no longer search with the browser's built in search now that the table is virtualized
Loaded a page from a customer with ~3,000 concurrency keys and saw the page not crash and burn.
video: https://dagsterlabs.slack.com/archives/C070G3UNNLW/p1715946929035669?thread_ts=1715895539.021559&cid=C070G3UNNLW
=> Actually virtualize concurrency page

python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_context.py
Delete the `_queryer_ property from `SchedulingContext`
BK
=> Delete the `_queryer_ property from `SchedulingContext`

python_modules/dagster/dagster/_core/definitions/declarative_scheduling/legacy/rule_condition.py
This is series of changes to make us more disciplined about accessing the `legacy_context`. Here just getting the top-level logger.
BK
=> Eliminate legacy_context reference in RuleCondition

python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_context.py
A chagne down the stack will create more copies of SchedulingContext. Moving this to a named tuple.
BK
=> SchedulingContext named tuple instead of DagsterModel

python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/updated_since_cron_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_context.py
This class exists purely for organizational purposes. I want to whitelist all the interacts that scheduling conditions do outside of the `AssetGraphView` system. The means no scheduling conditions directly access the queryer.
BK
=> Create NonAGVInstanceInterface to avoid accessing legacy_context directly in SchedulingContext

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py, python_modules/dagster/dagster/_core/definitions/asset_condition_evaluator.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_context.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_user_space_ds_api.py
Add supported, public, but awkwardly named method to access the inner queryer from an `AssetGraphView`. This is better than status quo of using `noqa` IMO.
BK
=> Add long but public access to we can get instance queryer instance off of AssetGraphView

python_modules/dagster/dagster/_core/definitions/asset_graph.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/legacy/legacy_context.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/slice_conditions.py
This logic that was in the scheduling context is really quite generic to the asset graph, so I moved it there.
BK
=> Extract materializable_in_same_run out of LegacyRuleEvaluationContext and call it directly from scheduling condition

python_modules/dagster/dagster/_core/definitions/declarative_scheduling/legacy/rule_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_context.py
Added a tripwire to accessing the legacy context object that is enabled by default. When calling into `evaluate_for_asset` on legacy auto-materialize rules we enable access
BK
=> Disallow legacy access in SchedulingCondiitions

python_modules/dagster/dagster/_core/definitions/asset_condition_evaluator.py, python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_user_space_ds_api.py
Making `AssetConditionEvaluator` more neutrally named by naming things differently than "auto-materialize"
BK
=> Just making the some of the names on AssetConditionEvalator not specific to AMP

python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/remote_representation/external_data.py, python_modules/dagster/dagster_tests/core_tests/host_representation_tests/test_external_data.py
When a user provides the owner string "team:x", we serialize it on the ExternalAssetNode as just "x". This limits our flexibility to allow unprefixed owner strings to mean other things in the future.
With this change, user-provided owner strings like "team:x" are now serialized as "team:x".
This change also handles the backcompat case where an older version of Dagster sends over an ExternalAssetNode with a "team:"-less owner.
=> serialize team owners with prefix

python_modules/dagster/dagster/_core/definitions/asset_graph.py, python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_decorators.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py, python_modules/libraries/dagster-looker/dagster_looker_tests/test_asset_decorator.py
Background:
- When someone provides an owner string to an `AssetsDefinition`, we internally convert it into either a `TeamAssetOwner` or a `UserAssetOwner`.
- These are not publicly exposed classes.
- Before sending owners over the wire, we convert them back into strings.
- I'm trying to replace the swarm of dictionaries in `AssetsDefinition` with a single `dict[AssetKey, AssetSpec]`.
- `AssetSpec` represents owners as strings, not `TeamAssetOwner` or `UserAssetOwner`.
This PR proposes removing these classes for the time being, which allows us to move forward with `AssetsDefinition` replacement without complicating `AssetSpec`s.
In retrospect, I think adding these classes was a little bit premature. Until we are ready to expose them publicly and finalize those APIs, I think it introduces …
=> [spec-ify-assets-def] remove TeamAssetOwner and UserAssetOwner

python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster/dagster/_core/definitions/asset_graph.py, python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/remote_representation/external_data.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_decorators.py, python_modules/dagster/dagster_tests/core_tests/host_representation_tests/test_external_data.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py, python_modules/libraries/dagster-looker/dagster_looker_tests/test_asset_decorator.py
This arg isn't used anywhere in the codebase, and it functions differently than the other args on `with_attributes` (overrides the prior value on conflicts, instead of erroring).
=> [spec-ify-assets-def] remove `descriptions_by_key` arg to `AssetsDefinition.with_attributes`

python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/metadata/source_code.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py, python_modules/dagster/dagster_tests/storage_tests/test_io_manager_asset_metadata.py
The argument functions differently than the other args on `with_attributes`, in that it overrides the existing value, rather than erroring on conflicts.
Rather than beef up `with_attributes` to handle different override strategies, it's clearer to just bypass it.
More context here: https://github.com/dagster-io/internal/discussions/9719#discussioncomment-9451281
=> [spec-ify-assets-def] remove metadata_by_key arg to with_attributes

js_modules/dagster-ui/packages/ui-core/src/runs/useRunsForTimeline.tsx
Due to the way we're filtering with `createdBefore` / `updatedAfter`, runs can appear in multiple buckets. Dedupe them to work around the issue while we think of a better approach.
Saw that a job spanning multiple buckets only shows up once.
=> [Run timeline] Dedupe runs

python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/source_asset.py, python_modules/dagster/dagster/_core/definitions/utils.py
The function named `validate_group_name` doesn't just validate the group name but also returns a normalized value (filling in "default" if the input `None`). The name `normalize_group_name` more accurately reflects this.
=> [spec-ify-assets-def] validate_group_name -> normalize_group_name

docs/dagster-university/pages/dagster-essentials/lesson-2/requirements-and-installation.md
Missed this while updating DU. There's a spot where we install the CLI first and then install Dagster 1.7 via the project, but we gotta probs update the CLI command too.
=> [du] updating to say install 1dot7

.buildkite/dagster-buildkite/dagster_buildkite/cli.py, .buildkite/dagster-buildkite/dagster_buildkite/pipelines/dagster_oss_nightly_pipeline.py, .buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py, .buildkite/dagster-buildkite/setup.py
Templates out a basic nightly OSS test to use for Snowflake integration tests w/ `dagster-dbt`, to avoid unnecessary cost.
=> [bk] add nightly oss pipeline

python_modules/dagster/dagster/_check/__init__.py, python_modules/dagster/dagster_tests/general_tests/check_tests/test_check.py
When `None` is passed to `opt_sequence_param`, a sequence is returned. Same with `opt_mapping_param` and `opt_set_param`. This changes `opt_iterable_param` to be consistent.
=> check.opt_iterable_param(None) == []

integration_tests/test_suites/backcompat-test-suite/webserver_service/pins.txt, python_modules/dagster/setup.py, python_modules/libraries/dagster-celery-docker/setup.py, python_modules/libraries/dagster-docker/setup.py
While we investigate breaking docker tests:
https://buildkite.com/dagster/dagster-dagster/builds/83562
=> Pin requests < 2.32.0

python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_code_references.py
Adds the option to a custom `DagsterDbtTranslator` to attach code reference metadata pointing to the dbt model files for each asset.
Unfortunately, this requires that we also get the `project_dir ` from the user, since that is only available at run time as part of the resource. Maybe there's a good way around this? The manifest used to have a `root_path` field, but this [was recently removed](https://github.com/dbt-labs/dbt-core/issues/6171).
```python
@dbt_assets(
manifest=...,
dagster_dbt_translator=DagsterDbtTranslator(
settings=DagsterDbtTranslatorSettings(attach_sql_model_code_reference=True)
),
project=DbtProject(...)
)
def my_dbt_assets():
...
```
Unit tests.
=> [dagster-dbt] add translator option to attach model files as code reference metadata

python_modules/dagster/dagster/_core/definitions/asset_check_result.py, python_modules/dagster/dagster/_core/definitions/events.py, python_modules/dagster/dagster_tests/definitions_tests/test_output_events.py, python_modules/dagster/dagster_tests/definitions_tests/test_replace_event_metadata.py, python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py
Stacks on #21666 to provide a shared abc/api for replacing metadata on event types which have it.
Unit tests
=> unify metadata replacement api across event types

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_checks.py
If you select an asset check and not the selected asset, just add it to the dbt selection instead of setting DBT_INDIRECT_SELECTION to empty and listing all tests
=> Use eager dbt test selection with extra tests

.gitignore
- [direnv](https://github.com/direnv/direnv) is a utility to automatically enable virtual environments when in a specific directory. It creates a `.direnv/` directory for the Python virtual environment. I would like for this to be excluded from version control like `.venv/` and `venv/`
- Confirmed `.direnv/` was not included in version control
=> Includes .direnv/ in .gitignore

python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py, python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill_with_backfill_policies.py
A user reported an issue where a backfill requested a parent and child asset partitions in separate runs, causing the child asset partition to fail since the parent had not yet been materialized. After some investigation, it looks like if multiple assets have the same partitions definition, different backfill policies, and were going to be requested in one tick of the backfill daemon, we requested each asset individually instead of grouping by backfill policy. This causes parent-child asset pairs that were going to be materialized together by that tick to be requested in different runs.
This PR changes the behavior so that we group by backfill policy. I think this change should be ok because we already know the assets have the same partitions def and requested partitions, and we know that …
=> fix assets with the same backfill policy not being materialized together

docs/next/pages/_app.tsx
- `broken-link-checker` identified malformed github links when `asPath` is root path `/`
- Ran next.js locally, ran broken-link-checker
=> [docs] fix malformed github link when asPath is root '/'

python_modules/libraries/dagster-polars/dagster_polars/io_managers/utils.py
Using the new standard metadata key for row count
=> use dagster/row_count metadata in dagster-polars

python_modules/dagster/dagster/_model/pydantic_compat_layer.py, python_modules/dagster/dagster/_utils/pydantic_yaml.py, python_modules/dagster/dagster/_utils/source_position.py, python_modules/dagster/dagster/_utils/yaml_utils.py, python_modules/dagster/dagster_tests/utils_tests/test_pydantic_yaml.py, python_modules/dagster/dagster_tests/utils_tests/test_source_position.py
Tools for parsing YAML files into pydantic models, preserving information about source positions, including those source positions in validation errors.
Adapted from @petehunt's versions of these in the internal repo.
=> [dagster-yaml] yaml pydantic parsing utils

python_modules/dagster-test/dagster_test/toys/user_computed_data_versions/__init__.py, python_modules/dagster-test/dagster_test/toys/user_computed_data_versions/external_system.py
Whenever I go to the definition of "AssetSpec" in my editor, this comes up. Renaming it to avoid the collision with the dagster class.
=> in toy, rename AssetSpec

.buildkite/dagster-buildkite/dagster_buildkite/cli.py, .buildkite/dagster-buildkite/dagster_buildkite/pipelines/dagster_oss_nightly_pipeline.py, .buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py, .buildkite/dagster-buildkite/dagster_buildkite/utils.py, python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/conftest.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_row_count_postprocessing.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/jaffle_shop/profiles.yml, python_modules/libraries/dagster-dbt/pytest.ini, python_modules/libraries/dagster-dbt/tox.ini
Adds Snowflake & BQ tests of new row-count functionality and fixes bug with `Table` return on certain warehouses (incl Snowflake).
Added to the new OSS nightly pipeline introduced in #21956 to avoid racking up unnecessary spend. We do already run some tests on these warehouses as part of normal builds for their respective integrations, so maybe it's fine to do the same here - open to either.
Nightly build run:
https://buildkite.com/dagster/full-moon-with-face-dagster-nightly/builds/9
=> [dagster-dbt] fix dbt row count behavior on warehouses, test row count code on snowflake & bigquery

python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/storage/event_log/base.py, python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py, python_modules/dagster/dagster/_core/storage/legacy_storage.py, python_modules/dagster/dagster_tests/storage_tests/test_asset_checks.py, python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
Adds an "AssetCheckState" API; which functions similarly to an AssetRecord. The core conceit is to be able to query just based on asset check key a set of information about the "state" of the asset check (most recent run, for now), without having any references to the event log.
For now, it's actually powered by the event log, however.
How I tested this
- Added a new semi-end-to-end test to our event log storage tests. This required me setting up an instance hooked up to an event log storage; which I think is nice to have anyway.
- There's one failing test here that's confusing me; test_get_event_records_sqlite. I changed it to use the instance passed in by fixture, which should in theory not change the results? But it seems like it has. Probably missing something here.
There will be a …
=> AssetCheckSummaryRecord

python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/sensor.py, python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_sensor.py
Uses the newly added get_asset_check_summary_record to implement the freshness check sensor.
Adds some more tests for previously under-handled cases; having an asset which is currently in planned state, and ensuring that cursoring works properly.
=> Fix freshness sensor to use assetchecksummaryrecord

js_modules/dagster-ui/packages/app-oss/src/App.tsx, js_modules/dagster-ui/packages/app-oss/src/extractInitializationData.ts, js_modules/dagster-ui/packages/app-oss/src/pages/_document.tsx, js_modules/dagster-ui/packages/ui-core/src/app/AppContext.tsx, js_modules/dagster-ui/packages/ui-core/src/app/AppProvider.tsx, js_modules/dagster-ui/packages/ui-core/src/overview/OverviewTimelineRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/HourlyDataCache/HourlyDataCache.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/HourlyDataCache/__tests__/HourlyDataCache.test.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/useRunsForTimeline.tsx, python_modules/dagster-webserver/dagster_webserver/webserver.py
Store the Run Timeline data in indexedb so that new page loads can reuse data from previous page loads.
Q: How is data cleared?
A: Whenever we load the page and create the cache instance we check if the cache has entries over a week old and delete them.
Q: How is data keyed in OSS?
A: We use the run_storage_id which is unique to the instance. That way if a user blows away their instance and start fresh they will get a completely separate cache.
Q: How is data keyed in Cloud?
A:  https://github.com/dagster-io/internal/pull/9828
Extensive use of the RunTimeline in cache + jest.
=> [4/5] Run Timeline IndexedDB Caching

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py, python_modules/dagster-graphql/dagster_graphql/implementation/loader.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster-graphql/dagster_graphql/schema/logs/events.py, python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py, python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py, python_modules/dagster-graphql/dagster_graphql/test/utils.py, python_modules/dagster/dagster/_core/loader.py, python_modules/dagster/dagster/_core/storage/dagster_run.py, python_modules/dagster/dagster/_core/workspace/context.py
Replace `BatchRunLoader` with `DataLoader` based abstractions
Adds:
* `InstanceLoadableBy[TKey]` - the parent class for objects loadable via the instance
* `LoadingContext` - the parent class for request contexts for scoping where loaders get cached
stacked on https://github.com/dagster-io/dagster/pull/21618
existing tests 
notably 
`python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_runs.py::test_asset_batching`
which was added to verify `BatchRunLoader` was batching succesfully
=> [DataLoader] make RunRecord loadable with scaffolding

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/schema/external.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_permissions.py
Fetching these off the workspace directly blocks them on loading the whole workspace, and in some environments that is costly.
Make it available off of the other code location scoped object for faster access.
updated test
=> [graphql] add permissions field to WorkspaceLocationEntryStatus

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt/core/utils.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_row_count_postprocessing.py
In preparation for supporting other post-dbt-materialization logic, moves the bulk of the "map operation across dbt events" logic to a util. Stacked PR will move to implementing an even more generic "map" style operation on `DbtEventIterator`.
=> [dagster-dbt] Refactor row count collection code

python_modules/dagster-graphql/dagster_graphql/client/client.py, python_modules/dagster-graphql/dagster_graphql/client/client_queries.py, python_modules/dagster-graphql/dagster_graphql_tests/client_tests/test_terminate_runs.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/client_backcompat/query_snapshots/CLIENT_SUBMIT_PIPELINE_RUN_MUTATION/1!0+dev-2024_05_16.graphql, python_modules/dagster-graphql/dagster_graphql_tests/graphql/client_backcompat/query_snapshots/GET_PIPELINE_RUN_STATUS_QUERY/1!0+dev-2024_05_16.graphql, python_modules/dagster-graphql/dagster_graphql_tests/graphql/client_backcompat/query_snapshots/RELOAD_REPOSITORY_LOCATION_MUTATION/1!0+dev-2024_05_16.graphql, python_modules/dagster-graphql/dagster_graphql_tests/graphql/client_backcompat/query_snapshots/SHUTDOWN_REPOSITORY_LOCATION_MUTATION/1!0+dev-2024_05_16.graphql, python_modules/dagster-graphql/dagster_graphql_tests/graphql/client_backcompat/query_snapshots/TERMINATE_RUNS_JOB_MUTATION/1!0+dev-2024_05_16.graphql, python_modules/libraries/dagster-looker/.coveragerc
This PR adds an extra method to the DagsterGraphQL python client to enable the possibility to terminate multiple runs at the same time.
This PR is related to the following issue: https://github.com/dagster-io/dagster/issues/21695
The PR contains a suit of unit tests similar to the other methods defined on the client, testing multiple edge cases for error handling.
=> Issue #21695 terminate runs

js_modules/dagster-ui/package.json, js_modules/dagster-ui/packages/ui-core/src/nav/ScheduleAndSensorDialog.tsx, js_modules/dagster-ui/packages/ui-core/src/schedules/ScheduleSwitch.tsx, js_modules/dagster-ui/packages/ui-core/src/schedules/types/ScheduleSwitch.types.ts, js_modules/dagster-ui/packages/ui-core/src/sensors/SensorSwitch.tsx, js_modules/dagster-ui/packages/ui-core/src/sensors/types/SensorSwitch.types.ts
In a previous PR, we stopped storing the RootWorkspaceQuery in the Apollo cache. However, this change affected the left navigation, which relied on data from the workspace context. As a result, the left navigation stopped receiving updates to the schedule/sensor state after mutations, since its data source was no longer tied to the Apollo cache.
To resolve this issue, I updated the left navigation to query for the latest status separately. This new query is stored in the Apollo cache, ensuring that any changes to the state on the sensor page or the left navigation are reflected in both places.
https://github.com/dagster-io/dagster/assets/2286579/39200fb1-ed51-4620-b725-66b3893d1c02
=> Fix sensor/schedule state in the left nav being outdated

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py
When using `dbt.cli(..., raise_on_error=False)`, users may still want to retrieve the error that would have been raised. `_errors` is private, so they couldn't put this together themselves either.
=> dbt cli get_error()

js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeOverview.tsx
=> [ui] Fix overflowing non-ideal state on the asset overview page

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorerFilters.tsx
This was pulling from the workspace's visible repos and not from the filter repo selection. On the global asset graph the code location filter does not sync to the workspace visible / hidden state.
Verify that toggling code locations on/off works on both the global asset graph and asset group graphs.
I tried to verify this behavior on the asset list / catalog pages as well, but the "all selected" feature is only in `useAssetGraphExplorerFilters` so no impact there
=> [ui] Fix “all selected” logic on the asset graph’s code location filter

js_modules/dagster-ui/packages/ui-core/src/app/InjectedComponentContext.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetValueGraph.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/RunActionsMenu.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/RunHeaderActions.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/RunTag.tsx
Related: FE-321
This PR adds a new InjectedComponent and uses it in the run actions menu and run header menu. When a component for the dialog is provided (only in Plus atm), the menu item appears and allows the dialog to be displayed.
Tested that this has no impact in OSS and appears in Dagster Plus.
=> [ui] Component injection site for run metrics

python_modules/dagster/dagster/_core/definitions/time_window_partitions.py, python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py
Summary:
owen tried to warn me about this on https://github.com/dagster-io/dagster/pull/21791/files, and in my hubris I did not listen - the test coverage here was not as thorough as i thought it was. Fix the fast calculations when you have a simple daily partitions definition (the existing logic gets messed up by DST boundaries when they are on opposite sides of the boundary).
Test Plan: BK, shadow graphql of an incorrect partitions count
=> Fix fast partition count calculations for daily partitions definition

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_postprocessing.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_row_count_postprocessing.py
Continues the restructuring of chaining async dbt work from #12943 to specify a `attach_metadata` method which can be used to specify a function which will run in a thread after each dbt event completes and will attach any additional user-specified metadata to that event before it is emitted.
Right now, it's classified as private so we can adjust the signature if need be before making it public - I'd like to unblock future work stacking on this shared impl, but I think we'll want to pass a single, proper context class rather than the loose `invocation`, `event` params.
Used internally for the `fetch_row_count` implementation.
Example unit test with `SUMMARIZE` SQL metadata.
=> [dagster-dbt] Add general attach_metadata method to chain async metadata fetches to dbt execution

js_modules/dagster-ui/packages/ui-core/src/app/AppError.tsx
Fixes https://linear.app/dagster-labs/issue/FE-371/dagsterinvalidconfigerror-not-return-in-the-ui
https://github.com/dagster-io/dagster/pull/21361/files Removed this logic because of a typescript error making me think the logic was wrong (and because I suspect it's breaking our type contracts). Turns out we're relying on this behavior already in the product in some places though.
What's a little unclear to me is why [internal](https://github.com/dagster-io/internal/blob/0b5e0e71a2f4104c5c76bb246d6537a19132a00d/dagster-cloud/js_modules/app-cloud/src/app/authLink.tsx#L14) doesn't have this logic. I suspect it needs it too so I'll add it there too. Although, if the error is nested inside, it's a little unclear to me if we should be forwarding this to the UI as I suspect it might be breaking …
=> Add back custom error handling logic

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_checks.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py
More thoughts on the line of https://github.com/dagster-io/dagster/pull/21851: we don't actually need
to rely on selecting by `fqn`, which can be very long.
Instead, we can use other markers of uniqueness, if we assume that a project is standalone. This is a reasonable assumption, considering that [multi-project setups are only supported by dbt Cloud](https://docs.getdbt.com/docs/collaborate/govern/project-dependencies). 
---
From https://docs.getdbt.com/reference/node-selection/methods:
> Selector methods return all resources that share a common property, using the syntax `method:value`. While it is recommended to explicitly denote the method, you can omit it (the default value will be one of `path`, `file` or `fqn`).
And https://docs.getdbt.com/faqs/models/unique-model-names:
> Within …
=> feat(dbt): divest from `fqn` in a subsetted execution

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/dlt/asset_decorator.py, python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/dlt/translator.py, python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/dlt_tests/test_dlt.py
Asset metadata is an essential component of assets definition in real projects. This PR adds a parameter in the DagsterDltTranslator to define resource specific metadata.
This is an idea to circumvent the fact that dlt does nor uses a configuration file such as Sling's replication.yaml, where would be natural to define metadata to be read by the translator.
make pyright
make ruff
python -m pytest python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/dlt_tests
=> Enable dlt asset metadata via translator

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/implementation/execution/backfill.py, python_modules/dagster-graphql/dagster_graphql/schema/backfill.py, python_modules/dagster-graphql/dagster_graphql/schema/inputs.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_partition_backfill.py, python_modules/dagster/dagster/_core/definitions/utils.py, python_modules/dagster/dagster/_core/execution/backfill.py, python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py, python_modules/dagster/dagster_tests/definitions_tests/test_utils.py
Discussed in a UI meeting that it would be nice for users to set titles for their backfills. these would not be used as the unique identifier for the backfill (ie for db queries), but would make it easier to navigate the backfill table in the UI
new unit tests
=> add title and description to PartitionBackfill

js_modules/dagster-ui/packages/app-oss/src/App.tsx, js_modules/dagster-ui/packages/ui-core/src/app/AppError.tsx
- Fix an issue where `response.networkError` object doesn't have a `result` key 
- Change errorLink to createErrorLink to reuse this logic for cloud instead of maintaining two implementations and allow passing in an arg for whether to toast or not
- Push useful data for a different type of error through to the UI
Tested with cloud and OSS.
=> Fix error link to not assume networkError type to be ServerError + handle other error type

python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py
There are diverse situations where it's useful to be able to pass around collections of definitions. Doing this in Dagster right now is quite awkward.
Relevant situations:
- Writing a factory that returns a few assets, a few checks, and a job that executes them together.
- A submodule defines a few assets, a job, and a schedule. A different submodule does the same. They should all be in the same code location.
- https://github.com/dagster-io/dagster/pull/21387#issuecomment-2081029765
- https://github.com/dagster-io/internal/discussions/8216
Unlike the [prior version of this PR](https://github.com/dagster-io/dagster/pull/21746), this PR does _not_ turn `Definitions` into a "dumb" data class. I.e. it still validates that all assets and jobs can be bound, at construction time.
=> Definitions.merge

js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeOverview.tsx
In a recent PR I removed the outdated automation policy section but in doing so introduced a bug since I didn't realize we were iterating over the sections to determine if an asset has any automations. This PR fixes that check.
=> Check if an asset node has an autoMaterializePolicy before showing there is no automation

python_modules/dagster/dagster/_core/definitions/asset_dep.py, python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenarios/multi_code_location_scenarios.py
This PR is the star of the ["[spec-ify-assets-def]" stack](https://github.com/dagster-io/dagster/pulls?q=is%3Aopen+is%3Apr+author%3Asryza+%22spec-ify-assets-def%22+).
It replaces all of these properties on `AssetsDefinition`:
```python
_asset_deps: Mapping[AssetKey, AbstractSet[AssetKey]]
_group_names_by_key: Mapping[AssetKey, str]
_metadata_by_key: Mapping[AssetKey, ArbitraryMetadataMapping]
_tags_by_key: Mapping[AssetKey, Mapping[str, str]]
_freshness_policies_by_key: Mapping[AssetKey, FreshnessPolicy]
_auto_materialize_policies_by_key: Mapping[AssetKey, AutoMaterializePolicy]
_code_versions_by_key: Mapping[AssetKey, Optional[str]]
_descriptions_by_key: Mapping[AssetKey, str]
_owners_by_key: Mapping[AssetKey, Sequence[str]]
```
with just:
```python
_specs_by_key: Mapping[AssetKey, …
```
=> [spec-ify-assets-def] replace dicts inside AssetsDefinition with dict of AssetSpecs

js_modules/dagster-ui/packages/ui-core/src/app/CloudOSSContext.tsx, js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadHooksContext.tsx, js_modules/dagster-ui/packages/ui-core/src/search/useGlobalSearch.tsx
Adds a new entry to `CloudOSSContext` to let us inject a function which can be used to augment global search results. Used in cloud to display users' full names in the search pane.
This allows you to search by a user's name in addition to (or in place of) their email.
Shadow dagit.
=> [ui][global search] Set up `useAugmentSearchResults` in `CloudOSSContext`

js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeOverview.tsx
Small tweak which uses the number formatter to add commas to the row count number.
local test
=> [ui] use number formatter for row count metadata

python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py
Grabs the dbt adapter_type from the manifest and uses it to set the `storage_kind` tag on dbt-output assets, by default.
Users can still override this behavior in the translator if they so desire.
Unit tests.
=> [dagster-dbt] attach `dagster/storage_kind` tag to dbt assets

js_modules/dagster-ui/packages/ui-core/src/ui/Filters/FilterDropdown.tsx
The `FilterDropdown` component is used to filter runs by tags and other options. When you pull up an individual tag, it will try to fetch all the tag values and display them as a suggestion. For instance, we tag with the CPU allocation of each job, so adding a filter for that tag shows these suggestions:
Our issue is that since we have a lot of runs it takes a very long time to load suggestions - **and you can't submit until the suggestions are loaded**. This means it takes a very long time to use any filter in the dagster UI. Here's what it looks like to add a tag filter in our dagster UI:
https://github.com/dagster-io/dagster/assets/3344958/779a2bd6-ebff-4d9c-b8fc-443ea892c400
To improve this situation, in this PR I make it possible to submit whatever you've currently typed by pressing …
=> [ui] FilterDropdown: allow submitting before suggestions are loaded

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py, python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/dbt_packages/test_columns_metadata.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_postprocessing.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_metadata/dbt_project.yml, python_modules/libraries/dagster-dbt/pytest.ini, python_modules/libraries/dagster-dbt/tox.ini
Adds a new `fetch_column_metadata` method which can be chained after a dbt CLI execution to fetch column lineage metadata, which is then attached to output and materialization events.
TODO in stacked PR: cache fetching column info for models we have already fetched 
Test deferred fetch alongside the existing fetching code in unit tests.
=> [dagster-dbt] add chained method to fetch column metadata, lineage async

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_condition_evaluations.py, python_modules/dagster-graphql/dagster_graphql/schema/backfill.py, python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py, python_modules/dagster/dagster/_core/definitions/asset_graph_subset.py, python_modules/dagster/dagster/_core/definitions/asset_subset.py, python_modules/dagster/dagster/_core/definitions/data_time.py, python_modules/dagster/dagster/_core/definitions/time_window_partition_mapping.py, python_modules/dagster/dagster/_core/definitions/time_window_partitions.py, python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_time_window_partition_mapping.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_subset.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_partitions_subset.py, python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py, python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
This class was created to make up for the fact that we had no efficient way of doing basic set operations efficiently on time-window-based subsets. We've since fixed these issues, and now the behavior of by, default, calling `my_time_partitions_def.subset_with_partition_keys(...)` returning a PartitionKeysTimeWindowPartitionsSubset is a performance liability, as it means that it will result in slow operations when used against TimeWindowPartitionsSubsets. Removing this class entirely greatly simplifies the mental model here.
Note that this means we can also remove the BaseTimeWindowPartitionsSubset class, I just wanted to keep this PR a bit smaller, so I'll do that in a follow up.
=> [TWP][2/n] Remove PartitionKeysTimeWindowPartitionSubset

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNodeMenu.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNodeStatusContent.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/SidebarAssetInfo.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetActionMenu.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeOverview.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetSidebarActivitySummary.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/LaunchAssetExecutionButton.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/RecentUpdatesTimeline.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/SimpleStakeholderAssetStatus.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/__fixtures__/LaunchAssetExecutionButton.fixtures.ts, js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/LaunchAssetExecutionButton.test.tsx
This PR is a fix for FE-365 (https://linear.app/dagster-labs/issue/FE-365/report-event-is-creating-materialization-events-on-external-assets) and reflects this goal:
Assets with isObservable=true should show "Last Observation", and allow you to click "Observe". All other assets should show materialization state. 
To date, we've used `isSource` in a lot of these places when we meant `isObservable`.
Note: Work here is likely not done. We still use `isSource` in places where we mean `isExecutable`, and there are places in the UI (screenshot below) we refer to "Source asset". We may need to take a tour through the remaining callsites on a quiet(er) day.
I created a source asset (below) with a materialization, and verified that I now see the materialization oriented stats. I also verified that …
=> [ui] Show materialization status for External Assets

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNode.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/types/AssetNode.types.ts, js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeOverview.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx, js_modules/dagster-ui/packages/ui-core/src/graph/KindTags.tsx, js_modules/dagster-ui/packages/ui-core/src/graph/OpTags.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedAssetRow.tsx
Implements a very basic visual tag for `storage_kind` on assets. Right now, this special rendering only displays on the catalog page, asset list, and asset graph. A stacked PR handles adding the filtering.
Uses the same iconset as compute kind.
=> [ui] introduce pill for `storage_kind` tag across UI

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorerFilters.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/useAssetCatalogFiltering.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/useAssetDefinitionFilterState.tsx, js_modules/dagster-ui/packages/ui-core/src/ui/Filters/useStorageKindFilter.tsx
Add frontend filters for storage kind to the asset list and asset graph pages.
Tested locally
=> [ui] add filters for storage kind

js_modules/dagster-ui/packages/ui-core/src/overview/OverviewTimelineRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/__tests__/useRunsForTimeline.test.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/fetchPaginatedBucketData.ts, js_modules/dagster-ui/packages/ui-core/src/runs/useRunsForTimeline.tsx
Currently when we're paginating we call `getMissingIntervals` within the paginated fetch loop. This is a bug because after the first fetch we add data for the time range and then `getMissingIntervals` ends up returning a 1 millisecond time range for the subsequent paginated fetches of that bucket. Instead we should be calling getMissingIntervals when determining the bucket to fetch and then when paginating we keep using the same bucket.
Loaded a timeline page, set the BATCH_LIMIT to 1 and made sure we paginated and fetched the rest of the runs for the bucket (current bug would result in just 1 run per bucket).
Wrote a jest test
=> Fix RunTimeline bucket pagination

python_modules/dagster/dagster/_core/definitions/asset_spec.py
This is a backwards compatible change, because it doesn't restrict the types that the constructor accepts.
=> for collections on AssetSpec, set types as not Optional

js_modules/dagster-ui/packages/ui-core/src/app/Flags.tsx, js_modules/dagster-ui/packages/ui-core/src/app/getVisibleFeatureFlagRows.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetTabs.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx
The asset overview feature flag gates the new asset details page and the catalog page in internal. This is already set to be "on" by default. 
Now that these pages are un-experimentalized, we can remove the feature flag and always rely on these pages.
https://linear.app/dagster-labs/issue/PLUS-1120/remove-asset-overviewcatalog-feature-flags
=> [ui] Remove asset overview feature flag

js_modules/dagster-ui/packages/ui-core/src/overview/OverviewTimelineRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/useRunsForTimeline.tsx
* fix the poorly performing `reduce` operation that would lock up the browser on a high volume of jobs/runs
* reduce the poll interval to limit the times we recalculate the timeline
profiled a deployment with many jobs & runs - memo updates reduced from 3+s to ~150ms
before
after
=> [ui] fix Timeline stutters

docs/content/integrations/dbt/reference.mdx, examples/docs_snippets/docs_snippets/integrations/dbt/dbt.py
This PR fixes DS-253 by adding examples on how configuring @dbt_assets for different use cases. Running an additional dbt command and flag is covered.
Doc preview
Code snippets tested locally
=> Add command and flag examples to dbt reference

python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
Summary:
I thought I included this in https://github.com/dagster-io/dagster/pull/22014 but it appears I did not. This should dramatically speed up counting partitions in TimeWindowPartitionsSubset that cover large time windows.
Test Plan: BK and speedscope over representative large asset graph
=> Speed up counting TimeWindowPartitionsSubset partitions

python_modules/dagster/dagster/_core/definitions/asset_job.py, python_modules/dagster/dagster/_core/definitions/base_asset_graph.py, python_modules/dagster/dagster/_core/definitions/graph_definition.py
Sometimes we use vanilla toposort and sometimes we use our utils variant. Let's only use our internal version
BK
=> Use dagster._utils.core.toposort in asset graph code

python_modules/dagster/dagster/_core/blueprints/load_from_yaml.py, python_modules/dagster/dagster_tests/core_tests/blueprint_tests/test_load_defs_from_yaml.py, python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/sling_tests/blueprints/test2.csv
Adds logic to automatically attach `LocalFileCodeReference`s to any assets returned from `build_defs_add_context_to_errors` in `load_defs_from_yaml`.
For now, this is pretty straightforward, since we have a correspondence between a single file and its blueprint. We pull the position in the file from the Blueprint's `_source_position_and_key_path`.
Add some assertions around code references to existing unit tests.
=> [blueprints] add LocalFileCodeReference to `load_defs_from_yaml`-loaded assets

python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py
There's no way to pass a retry policy to a dbt asset.  I assumed this was mostly an oversight, and not an explicit decision.
Might need to sanity check that retries make sense in the dbt world.
In a lot of cases, users will probably want to run `dbt retry` (instead of op-level retry) to not lose the per-model granularity of failures, but there is a case to be made to still configure a coarse-grained op-level retry with the standard retry options (e.g. delay, jitter, etc)
BK
=> pass through retry_policy for dbt assets

docs/content/concepts/assets/asset-checks/define-execute-asset-checks.mdx
Someone without intimate knowledge of Dagster internals may not always understand what an `op` is and, I would argue, does not always need to understand it. 
In this example, I replace `op` with `operation` but could also use words like `computation`. The idea is to communicate to the user what is happening without introducing a concept they may not necessarily need to know about. 
I recognize we are trading off some specificity here for simplicity, so thought I'd send this out for comments.
=> RFC: What if we didn't say op

python_modules/dagster/dagster/_core/blueprints/blueprint.py, python_modules/dagster/dagster/_core/blueprints/blueprint_assets_definition.py, python_modules/dagster/dagster/_core/blueprints/shell_command_blueprint.py, python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py, python_modules/dagster/dagster_tests/core_tests/blueprint_tests/test_shell_command_blueprint.py
This PR explores a few related ideas:
- Out-of-the-box blueprints corresponding to standard pipes clients (databricks & subprocess).
- Single-assets and multi-asset blueprints as separate blueprints.
- Base blueprint types for helping define out-of-the-box blueprints
One question that came up when implementing multi-asset blueprints was what to name the equivalent of `AssetSpec` in blueprint-land. Which points to a general question of what to name classes that are part of defining blueprints but don't correspond to code location-level definitions of their own.
This PR goes with `AssetSpecModel`. An alternative would have been `AssetSpecBlueprint`. However, the `Blueprint` base class currently has a `build_defs` method, which wouldn't make sense for `AssetSpecBlueprint`. We could …
=> `ShellCommandBlueprint` and `BlueprintAssetsDefinition`

docs/content/dagster-plus/deployment/agents/kubernetes/configuring-running-kubernetes-agent.mdx
This PR corrects the name of a token in the Dagster+ Kubernetes guide to `dagster-cloud`.
=> [docs] - Fix token name in Dagster+ Kubernetes docs

python_modules/dagster/dagster/_core/definitions/asset_spec.py, python_modules/dagster/dagster_tests/general_tests/test_internal_init_implementations.py
Implement  `dagster_internal_init` for `AssetSpec`, and modifies the sanity check test to handle `NamedTuple` properly (by inspecting `__new__` instead of `__init__`)
=> add dagster_internal_init to AssetSpec

python_modules/dagster/dagster/_core/definitions/external_asset.py, python_modules/dagster/dagster_tests/definitions_tests/test_external_assets.py
Makes sure tags are passed along from specs when calling `external_assets_from_specs`
New unit test
=> Pass `tags`, `owners` from `external_assets_from_specs`

js_modules/dagster-ui/packages/ui-core/src/code-links/CodeLink.tsx
Fixes these menu links, which didn't link properly to external URLs (instead prefixing with `dagster.cloud...`) - this was changed from a `MenuItem` w/ `onClick` right before merge and the new behavior wasn't validated 😅 
Also bounds the tooltips, which looks nicer.
=> [ui] fix external code links rendering as relative

python_modules/dagster/dagster/_core/remote_representation/job_index.py
Summary:
We believe that this invariant is no longer always true and is causing more trouble than it is worth.
Test Plan:
Load a subsetted single-asset run of an asset job, no more spurious graphql error
=> Remove overly defensive job index invariant

python_modules/dagster/dagster/_core/storage/event_log/base.py, python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
Summary:
get_assets_or_error returns a mix of assets that are in the database and assets that have definitions but are not yet in the database (e.g. because they have never been materialized). If you pass in the key of an asset that is in the latter list, the current logic here will not accept it as a valid cursor index since it is not in the list. Instead, make the logic here return any keys that are > the passed in cursor (like the implementation in SqlEventLogStorage does)
Test Plan: BK
=> Correctly cursor through asset keys when an asset key is passed in to EventLogStorage.get_asset_keys that is not in the list of asset keys

python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/sensor.py, python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_sensor.py
There's been confusion with when the freshness check sensor does/doesn't execute freshness checks. This attempts to rectify by improving the description, and yielding a skip reason when all checks get skipped.
How I tested this:
eyes + existing tests
=> Improved freshness check sensor description.

python_modules/dagster/dagster/_core/executor/step_delegating/step_delegating_executor.py, python_modules/dagster/dagster_tests/execution_tests/engine_tests/test_step_delegating_executor.py
Summary:
Ensures that we don't ever issue an unbounded events query while procesing events for a run. Note that if the offset field is set, it's important that the limit be greater than that offset to avoid looping over the same offsetted events forever.
Test Plan: BK
=> Apply a limit in the step delegating executor query

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt/utils.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/conftest.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/__init__.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_dbt_unit_tests/models/unit_tests.yml
Resolves https://github.com/dagster-io/dagster/issues/22216.
Another PR will follow to ensure that `AssetObservation`/`AssetCheckResult` is properly emitted for these new event types.
pytest
=> feat(dbt): support dbt projects with unit tests

python_modules/dagster/dagster/_core/definitions/asset_check_spec.py, python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/load_assets_from_modules.py
These check props can be handled internally, like the other asset key replacements.
Also, use empty collections instead of `None` to remove unnecessary degrees of freedom.
=> simpler AssetsDefinition.with_attributes args and remove check props

python_modules/dagster/dagster/_core/execution/context/compute.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_partitioned_assets.py, python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_execution_context.py
`AssetExecutionContext` currently has `has_partition_key`, but not `has_partition_key_range`.  Adding the latter was a request from a user, which seems reasonable.
I know there have been concerns in the past about large numbers of properties on the context object, so open to alternatives here as well.
=> `AssetExecutionContext.has_partition_key_range`

python_modules/dagster/dagster/_core/definitions/multi_asset_sensor_definition.py, python_modules/dagster/dagster/_core/definitions/sensor_definition.py, python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
Addresses #17461. Ensures the contextual info needed to set up sensor logging is properly passed through for multi-asset sensors.
Feels like we may want a `dagster_internal_init` pattern here for `SensorEvaluationContext`, but not sure we can do so for a subclass constructor, which has to call its superclass constructor.
New, previously failing unit test.
=> Fix multi-asset sensor logging

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/dlt/resource.py
We were running into a problem where `context.has_partition_key` was true even when the _dlt_ asset was not partitioned, thus `context.partition_keys` was undefined.
This is because `context.has_partition_key` is scoped to the _run_. I should note that this was relatively unclear to me, as I assumed that the property on the `AssetExecutionContext` would be scoped to the asset.
```
dagster._core.errors.DagsterInvariantViolationError: Cannot access partition_keys for a non-partitioned run
File "/opt/dagster/app/dagster_open_platform/assets/dlt.py", line 67, in thinkific_assets
yield from dlt.run(context=context)
File "/usr/local/lib/python3.11/site-packages/dagster_embedded_elt/dlt/resource.py", line 173, in run
last_partition_key = context.partition_keys[-1]
^^^^^^^^^^^^^^^^^^^^^^
File …
```
=> [dagster-embedded-elt] prepend partition to pipeline name only when asset is partitioned

python_modules/dagster-graphql/dagster_graphql/client/client.py
This will allow the user to get the relevant information on the real error that caused the exception (such as 403)
We encountered a GraphQL error and spent a few hours debugging it only to find out it was an 403 error. Sadly, this message was hidden by the general except clause. We believe this change may be helpful for other users.
Queried to get an 403 error on our servers and see the updated error message.
=> Stop hiding server errors

js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillPage.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillPartitionsTab.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillRunsTab.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/ExecutionTimeline.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/types/BackfillPage.types.ts, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/types/BackfillPartitionsTab.types.ts, js_modules/dagster-ui/packages/ui-core/src/overview/OverviewTimelineRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/HourlyDataCache/HourlyDataCache.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/RunTable.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/RunTimeline.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/RunsRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/__stories__/RunTimeline.stories.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/__tests__/useRunsForTimeline.test.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/useHourWindow.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/useRunsForTimeline.tsx
This PR adds a second "Runs" tab to the existing backfill detail page, which presets both list and timeline views of the runs launched by the backfill.
This feature is not behind a feature flag, since it's fairly low risk and available as an additional tab (not the default tab of this view).
=> [ui] Show a run timeline on backfill details pages

python_modules/dagster/dagster/_core/definitions/declarative_scheduling/__init__.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/__init__.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/slice_conditions.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_condition.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_requested_previous_tick_condition.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_will_be_requested_condition.py
As title -- also updated the name "RequestedThisTick" to "WillBeRequested".
If you're curious to get into the weeds on that decision, the next stack creates a "NewlyUpdated" condition, and so naming this new one "NewlyRequested" feels nice an symmetric, and "WillBeRequested" has better symmetry with "NewlyRequested" than "RequestedThisTick".
=> [DS][45/n] Create RequestedPreviousTickCondition

python_modules/dagster/dagster/_core/definitions/auto_materialize_policy.py, python_modules/dagster/dagster/_core/definitions/auto_materialize_rule.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operators/dep_operators.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_condition.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/asset_condition_scenario.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_dep_condition.py
As title -- previous iterations of this also added similar selection arguments to the ParentNewer condition. However, that didn't make a ton of sense because "ParentNewer" is purely a status like "code version updated" and calculating it in a different way is odd. Below this in the stack, we added a NewlyUpdated condition, which can compose with the AnyDepsCondition and take advantage of these arguments for users who want filter based on parent updates
=> [DS][50/n] Add include_selection and exclude_selection to DepSchedulingCondition

python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_perf.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_user_space_ds_api.py
Adds a perf test that lets us track how efficiently we can compute conditions against large asset graphs.
For now, because the perf test will fail without some of the upstack changes, disabling this on BK
=> [DS][51/n] Add perf test

python_modules/dagster/dagster/_core/definitions/asset_subset.py, python_modules/dagster/dagster/_core/definitions/partition.py, python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
It's a shame that we can't quite merge the PR that removes the PartitionKeysTimePartitionSubset yet, and instead we have to settle for this workaround sort of stuff.
=> [DS][53/n] Avoid slow get_partition_keys calls

python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_evaluation_info.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/serialized_objects.py
A simple one, where we use model_construct and simpler function calls across some hot code paths.
This kinda becomes obsolete upstack as I shift these things to NamedTuples anyway, but it doesn't hurt and it'd be annoying to remove this from the stack.
=> [DS][53/n] Make constructing objects less expensive

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operators/newly_true_operator.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operators/since_operator.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_context.py, python_modules/dagster/dagster_tests/asset_defs_tests/asset_graph_view_tests/test_basic_asset_graph_view.py, python_modules/dagster/dagster_tests/asset_defs_tests/asset_graph_view_tests/test_latest_time_window.py
It is not free to do isinstance checks, so I make two separate entrypoints for converting from asset subset to asset slice. For the common case, where we know that a subset is guaranteed to be valid, we skip the instance check entirely.
Also uses a cached_method for get_asset_slice, as the AssetSlice itself caches some properties/methods, and so returning the same object instance from get_asset_slice means different call sites get to share the same cache.
=> [DS][54/n] Make slice conversion more efficient

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py, python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/legacy/rule_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_context.py, python_modules/dagster/dagster/_utils/caching_instance_queryer.py
This needs to be updated, but the basic idea is that in the DS paradigm, if you have no previous cursor, you should not attempt to run a query that looks back across all history
=> [DS][55/n] Avoid looking back across all history on first tick

python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_impls.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/legacy/asset_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/legacy/legacy_context.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/parent_newer_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/slice_conditions.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operators/since_operator.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_condition_evaluator.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_context.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_evaluation_info.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/serialized_objects.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/asset_condition_scenario.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_user_space_ds_api.py
This is the first step in migrating us to using a slimmed-down cursor object within our internals. Currently, we store the entire AssetConditionEvaluationState object inside of our cursor. This object contains high-fidelity information about each node of computation in our graph. This _is_ necessary to store for use in the UI, as we want to record all relevant information about each node, but it is way more information than required for incremental calculations.
This PR splits off a simplified SchedulingConditionCursor class, which contains just a flattened mapping of condition node id to SchedulingConditionNodeCursor, which contains some relevant properties. We then refactor the internals to pull information off of this class. Because of this flattened structure, we have the freedom to …
=> [DS][56/n] Use slimmed cursor object for internal computation

python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py, python_modules/dagster/dagster/_core/definitions/asset_daemon_cursor.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/legacy/asset_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/legacy/legacy_context.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/parent_newer_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/slice_conditions.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operators/newly_true_operator.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operators/since_operator.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_condition_evaluator.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_context.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_evaluation_info.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/serialized_objects.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/asset_condition_scenario.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_asset_condition.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_legacy_missing_condition.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_parent_newer_condition.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_user_space_ds_api.py
This is the continuation of the previous PR's work, where now we actually store the slimmed-down cursor in our serialized objects.
One decision I made here was to (at least temporarily) not delete any information in the old format from the cursor, which makes it a bit easier to roll back this change in the event of an emergency. We can always go back and wipe out the old value later.
On case in perf_test.py, this PR results in the cursor becoming almost 30x smaller.
=> [DS][57/n] Use slimmed cursor object in storage

python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/legacy/legacy_context.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/slice_conditions.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_condition_evaluator.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_context.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_evaluation_info.py, python_modules/dagster/dagster/_core/definitions/declarative_scheduling/serialized_objects.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/asset_condition_scenario.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_asset_condition.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_legacy_missing_condition.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_result_value_hash.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_user_space_ds_api.py
This is a pretty red diff, as we were doing a lot of weird contortion in the past converting to and from different object types depending on the use case. This simplifies the model greatly, where at a high level we just have 3 object types to think about:
- SchedulingResult: An in-memory, non-serializable object that represetns the result of an evaluation. This is what gets returned when you evaluate a condition, and "thinks" in terms of AssetSlice objects.
- SchedulingConditionCursor: A serializable object that is used to track incremental state about an evaluation, to make future evaluations more efficient. It contains a list of SchedulingConditionNodeCursors, for condition nodes which require more specific bits of information in order to be computed efficiently. These are lightweight, …
=> [DS][58/n] Reorganize result objects

python_modules/dagster/dagster/_utils/pydantic_yaml.py, python_modules/dagster/dagster_tests/utils_tests/test_pydantic_yaml.py
Introduces some YAML utils which handle breaking apart a YAML list at the top level and parsing its elements into Pydantic models.
Unit tests.
=> [blueprints] add yaml utils for loading list of pydantic models

python_modules/dagster/dagster/_core/definitions/time_window_partitions.py, python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py
Long story short, this issue was lying in wait for a long time, but we never hit it because all of our BaseTimeWindowPartitionSubsets were in the "partition key" format rather than the "time window" format. If you check if <random non-time-window key, in the detected case, None> in <partition key set>, that's totally fine, but if you check if that same "invalid" key is in <time window set>, then you get an error.
This PR makes the time window set copy the same behavior of the non-time window set.
=> [DA] Fix error with freshness-based scheduling

python_modules/dagster/dagster/_core/blueprints/load_from_yaml.py, python_modules/dagster/dagster/_model/pydantic_compat_layer.py, python_modules/dagster/dagster_tests/core_tests/blueprint_tests/__snapshots__/test_load_defs_from_yaml.ambr, python_modules/dagster/dagster_tests/core_tests/blueprint_tests/test_load_defs_from_yaml.py
Introduces just the `YamlBlueprintsLoader` from #22017, CLI stuff will be more properly handled in a stacked PR.
A few tests to make sure we can extract a proper schema from the basic model case and the union case.
=> [blueprints] Introduce basic `YamlBlueprintsLoader` class

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_evaluator.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/updated_scenarios/asset_daemon_scenario.py
Discovered during manual testing -- in the weird case where you have non-subsettable multi assets with different policies, we need to do some hacking to make sure that the evaluation objects work out correctly. This was messed up in the refactor where we moved to NamedTuples, and it wasn't noticed as the `_replace()` method loses any type information.
=> Fix neighbor propagation

python_modules/dagster/dagster/_core/blueprints/load_from_yaml.py, python_modules/dagster/dagster/_model/pydantic_compat_layer.py, python_modules/dagster/dagster/_utils/pydantic_yaml.py, python_modules/dagster/dagster_tests/core_tests/blueprint_tests/__snapshots__/test_load_defs_from_yaml.ambr, python_modules/dagster/dagster_tests/core_tests/blueprint_tests/test_load_defs_from_yaml.py, python_modules/dagster/dagster_tests/core_tests/blueprint_tests/yaml_files/dir_of_lists_of_blueprints/list_of_blueprints1.yaml, python_modules/dagster/dagster_tests/core_tests/blueprint_tests/yaml_files/dir_of_lists_of_blueprints/list_of_blueprints2.yaml, python_modules/dagster/dagster_tests/core_tests/blueprint_tests/yaml_files/list_of_blueprints.yaml
Allows `load_blueprints_from_yaml` to take a type which is a `Sequence[Blueprint]`, meaning it will load many blueprints from the top level of a file.
=> [blueprints] add capability to load list of blueprints from file

python_modules/dagster/dagster/_utils/log.py
Summary:
This ensures that warnings.warnings calls get basic logging information like timestamps and don't look totally different from other warnings
Test Plan:
Load the following code:
```
from dagster import AutoMaterializePolicy, asset
@asset(auto_materialize_policy=AutoMaterializePolicy.lazy())
def my_asset():
print("HELLO")
```
Before, it looked like:
```
2024-06-03 17:16:59 -0500 - dagster - INFO - Launching Dagster services...
/Users/dgibson/dagster/python_modules/dagster/dagster/_core/definitions/auto_materialize_policy.py:243: ExperimentalWarning: Class `AutoMaterializePolicy` is experimental. It may break in future versions, even between dot releases. To mute warnings for experimental functionality, invoke warnings.filterwarnings("ignore", category=dagster.ExperimentalWarning) …
```
=> Use the default logging handler on warnings.warnings calls

python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
Summary:
I have not observed any bugs caused by this yet but stumbled on it while I was messing with TimeWindow APIs. Can't wait until we are off of pendulum and can compare datetimes in a reasonable way...
Test Plan: BK
=> Fix places where new partition subset operators were comparing datetimes directly instead of comparing timestamps

python_modules/dagster/dagster/_core/definitions/asset_check_factories/metadata_bounds_checks.py, python_modules/dagster/dagster/_core/definitions/utils.py, python_modules/dagster/dagster_tests/definitions_tests/test_metadata_bounds_checks.py
Removes any disallowed characters from the asset check name generated by `build_metadata_bounds_checks`.
This came up specifically with namespaced metadata, e.g. `dagster/row_count`.
New unit test.
=> strip special chars from build_metadata_bounds_checks check name

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetRunLinking.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetPartitionDetail.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/CurrentRunsBanner.tsx, python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
Summary:
This is a change that makes an explicit tradeoff for performance when displaying in progress runs in the asset graph and asset status UI - instead of doing granular step-level tracking of each run to determine whether it is literally in the middle of a step that intends to materialize that asset or not, which requires making expensive event log queries that can very plausibly time out for large runs, we consider the run to be 'in progress' for that asset if it is in an in-progress state and has not materialized the asset yet.
The product impact of this change would be that if a run has started but hasn't yet gotten around to the specific step that has materialized that asset yet, it would still be shown as an 'in progress run' for that asset.
I believe that if we feel step level …
=> Remove expensive step-level tracking when computing whether or not a run is in the middle of materializing an asset for display purposes

python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster/_daemon/backfill.py
stores backfill logs using the InstigationLogger. gated on an instance method that we can override to control roll out. 
related internal pr https://github.com/dagster-io/internal/pull/9879
=> store backfill logs using instigation logger

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/schema/backfill.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_backfill.py, python_modules/dagster/dagster/_core/captured_log_api.py, python_modules/dagster/dagster/_core/compute_log_api.py, python_modules/dagster/dagster/_core/execution/backfill.py, python_modules/dagster/dagster/_core/storage/captured_log_manager.py, python_modules/dagster/dagster/_core/storage/local_compute_log_manager.py, python_modules/dagster/dagster/_daemon/backfill.py, python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py, python_modules/dagster/dagster_tests/storage_tests/test_captured_log_manager.py
Fetches backfill logs using the captured log manager. 
Adds functionality to the captured log manager to read a sequence of files in a directory as if they are a single file by sorting the file names and then reading through the files N lines at a time. The majority of the logic is in the base CapturedLogManager class, but each implementor class will need to implement a method to get the log keys for a given directory. I implemented this method for the LocalComputeLogManager to enable testing, and follow up PRs can implement it for the remaining ComputeLogManagers. internal pr https://github.com/dagster-io/internal/pull/9879 that implements the method for the cloud compute log manager
Fetching logs via GQL is gated on an instance method we can override to control roll out
new unit tests …
=> fetch backfills logs in GQL

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_decorators.py
resolves https://github.com/dagster-io/dagster/issues/22239
we should probably have a better way of converting all of the asset varieties to `AssetsDefinition` that doesn't require unpacking all of the attributes into `x_by_output_name`  just so they can get repacked into AssetSpecs...
unit test
=> pass tags through graph multi asset

js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeOverview.tsx, js_modules/dagster-ui/packages/ui-core/src/metadata/TableSchema.tsx
Promotes the URI and Relation identifier metadata fields to the Definitions header in the asset page.
=> [ui] promote uri, relation id fields in catalog

python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py, python_modules/dagster/dagster/_core/definitions/decorators/assets_definition_factory.py, python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py
A ton of the complexity in this codepath is bookkeeping checks and assets to their respective inputs and outputs in the underlying op. In this case we move the logic of tracking which checks specs correspond to what outputs into its own property in the mapper
BK
=> Move check_specs_by_output_name into InOutMapper

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py, python_modules/dagster/dagster/_core/definitions/decorators/assets_definition_factory.py
Continues on the path of decomposing and moving complexity to the mapper. In this case the construction of the `outs` parameter to `AssetsDefinition`.
BK
=> Move outs parameter contruction to InOutMapper

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py, python_modules/dagster/dagster/_core/definitions/decorators/assets_definition_factory.py
We convert back and forth from non-spec code paths and then reconstruct the specs that *would* have been used to construct the `multi_asset`, which is a bit strange.
This moves that logic into the factory machinery.
BK
=> Move spec resolution into mapper

python_modules/libraries/dagster-dbt/setup.py, python_modules/libraries/dagster-dbt/tox.ini
We sometimes see flakes related to file locking across processes in our dbt tests:
https://buildkite.com/dagster/dagster-dagster/builds/85277#018fec98-397c-4dfb-806c-03189319e07c
I haven't dug very deep but naively I assume this is related to running these tests with higher parallelism. So this adds a [pytest-rerunfailures](https://pypi.org/project/pytest-rerunfailures/) retry to smooth out the flakiness.
=> Retry parallelized dbt tests

js_modules/dagster-ui/packages/ui-core/src/assets/AssetEventMetadataEntriesTable.tsx
`dagster/row_count` already has a top-level pill under the "Status" section. So remove this duplicate information from the metadata section.
local
=> feat(catalog): hide `dagster/row_count` from metadata section

.buildkite/dagster-buildkite/dagster_buildkite/python_packages.py
Determining buildkite pipeline steps locally is very slow (22s). I believe this is most likely due to __pycache__ directories or other similar files that are probably not an issue in CI. However, when iterating locally, it helps for this step to be as fast as possible, and these changes reduce local pipeline output from 22s to 2s. 
- visually inspected that the same packages are found
- modified a python file in a package and ensured that it was still picked up as a changed package
=> optimize buildkite python packages change detection

python_modules/dagster-graphql/dagster_graphql/implementation/execution/backfill.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_backfill.py, python_modules/dagster/dagster/_core/definitions/selector.py
Summary:
Asset backfills were incorrectly only letting you submit backfills with the partitionsByAssets field set if you were a deployment-wide Launcher, unlike the other codepaths which correctly look at the specific assets being backfilled and checking per-location permissions.
Test Plan: New test case that was failing before
=> Fix per-location permissions checks for asset backfills using the "partitionsByAssets" parameter

python_modules/libraries/dagster-deltalake/setup.py
deltalake 0.18 broke us it looks like
```
[2024-06-06T19:11:25Z] >       write_deltalake(  # type: ignore
--
  | [2024-06-06T19:11:25Z]             table_or_uri=connection.table_uri,
  | [2024-06-06T19:11:25Z]             data=reader,
  | [2024-06-06T19:11:25Z]             storage_options=connection.storage_options,
  | [2024-06-06T19:11:25Z]             mode=main_save_mode,
  | [2024-06-06T19:11:25Z]             partition_filters=partition_filters,
  | [2024-06-06T19:11:25Z]             partition_by=partition_columns,
  | [2024-06-06T19:11:25Z]             engine=engine,
  | [2024-06-06T19:11:25Z]             overwrite_schema=metadata.get("overwrite_schema") or overwrite_schema,
  | [2024-06-06T19:11:25Z]             custom_metadata=metadata.get("custom_metadata") or …
```
=> Pin deltalake to pre-.18

python_modules/dagster/dagster/_core/definitions/time_window_partitions.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_legacy_missing_condition.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/updated_scenarios/partition_scenarios.py
Summary:
This is a prereq to removing pendulum, because non-pendulum datetimes do not have a direct way to fetch the timezone information back from a datetime object. So to keep hte objects deserializable post-transition this serialization scheme will not work.
Test Plan: BK
=> Remove DatetimeFieldSerializer from time window partitions classes

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_partition_backfill.py, python_modules/dagster/dagster/_core/definitions/time_window_partitions.py, python_modules/dagster/dagster/_core/execution/asset_backfill.py, python_modules/dagster/dagster/_core/execution/backfill.py, python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py, python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill_with_backfill_policies.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/base_scenario.py, python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py
Summary:
Not 100% clear to me why this was not just a float since it is always in UTC, but such is life.
Test Plan: BK
=> Fully remove DatetimeFieldSerializer by removing it from AssetBackfillData

docs/content/integrations/dbt/reference.mdx, examples/docs_snippets/docs_snippets/integrations/dbt/dbt.py
This PR adds an example on what to avoid when it comes to dbt parse and creating `manifest.json`.
This error is pretty common and comes up a lot in support. Another PR specific to DbtProject across dbt docs will also mentions it as an option.
BK 
+
local
```
make mdx-full-format
```
=> [docs] Add `dbt parse` troubleshooting to dbt reference

js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/HourlyDataCache/HourlyDataCache.tsx, js_modules/dagster-ui/packages/ui-core/src/search/useGlobalSearch.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext.tsx
We recently added a prefix to all of our IndexedDB caches to take the deployment id into account but neglected to clean up the old databases which are just lying around. This PR cleans them up. 
Screenshot of prefixed vs unprefixed keys from production
Loaded pages and made sure nothing broke even if the database doesn't exist / was already deleted
=> Clean up unused indexeddb databases

python_modules/dagster-graphql/dagster_graphql/schema/instigation.py, python_modules/dagster/dagster/_api/snapshot_schedule.py, python_modules/dagster/dagster/_core/definitions/time_window_partitions.py, python_modules/dagster/dagster/_core/definitions/timestamp.py, python_modules/dagster/dagster/_core/execution/asset_backfill.py, python_modules/dagster/dagster/_core/remote_representation/code_location.py, python_modules/dagster/dagster/_scheduler/scheduler.py, python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_schedule_execution_data.py, python_modules/dagster/dagster_tests/core_tests/test_mask_user_code_errors.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_legacy_missing_condition.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/base_scenario.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/updated_scenarios/partition_scenarios.py
Summary:
Inching towards pendulum removal by passing around a different object that allows IANA timezone extraction in a similar fashion.
Test Plan: BK
=> Pass a TimestampWithTimezone into scheduler methods rather than a pendulum datetime

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py, python_modules/dagster/dagster/_core/definitions/decorators/assets_definition_factory.py, python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_resource_double_specify_errors.py
This moves nearly all the logic of `multi_asset` to the newly renamed `AssetsDefinitionBuilder`. It also just stashs all the args passed to `multi_asset` (after they are checked) into a standalone named tuple, which makes for less state shuffling.
BK
=> InOutMapping --> AssetsDefinitionBuilder

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py, python_modules/dagster/dagster/_core/definitions/decorators/assets_definition_factory.py
Use `AssetsDefinitionBuilder` in the `@asset` codepath. There is more consolidation to do but this is good start.
This is the most risky PR in this PR and we may want to wait until branch cut to mrege it to maximize soak time.
BK
=> Have @asset use AssetsDefinitionBuilder

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py, python_modules/dagster/dagster/_core/definitions/decorators/assets_definition_factory.py
Here is another example of the resource key manipulation that is duplicated in this code path. Using it in `@asset`. Eventual goal is remove it entirely but this is a good incremental step. This code path is quite risky and subtlely complicated so taking a conservative approach here.
BK
=> Use compute_required_resource_keys_for_underlying_op in @asset construction

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
There is super convoluted logic when we pass in an `io_manager_def` directly. This captures that in a class and explicitly documents it.
BK
=> Factor out strange resource-related logic into helper class RelatedResourceState

python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py, python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py, python_modules/dagster/dagster/_core/definitions/decorators/decorator_assets_definition_builder.py, python_modules/dagster/dagster/_core/definitions/decorators/source_asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py
Various pieces of good feedback raised by @sryza done here to avoid merge conflicts.
* More use of `NamedIn` and `NamedOut` rather than raw tuples
* outs_by_output_name instead of asset_outs_by_output_name
outs_by_output_name instead of asset_outs_by_output_name
* ins_by_input_name instead asset_ins_by_input_name
BK
=> Clarifying rename of AssetsDefinitionFactory-related classes and properties

python_modules/dagster/dagster/_core/storage/captured_log_manager.py
forgot to remove a parameter after moving it to an env var
=> remove unsued parameter in captured log manager read_log_lines_for_log_key_prefix

python_modules/dagster/dagster/_core/definitions/repository_definition/repository_data_builder.py, python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py
Throw a deprecation warning a custom `PartitionsDefinition` class is passed into a `Definitions` object. We can promote to a hard error on a minor release. Would've prevented the problem discussed here: https://dagsterlabs.slack.com/archives/C06K1DMN81W/p1716420434864219
=> Deprecate custom PartitionsDefinition subclass

js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeOverview.tsx, js_modules/dagster-ui/packages/ui-core/src/graph/KindTags.tsx
Adds an optional prop to the kind tag component to make it a clickable link to the asset list, filtered to that kind tag.
Enables this functionality on the asset details page, so you can easily navigate to peer assets w/ the same compute or storage kind.
=> [ui] click kind tag to open filtered asset list

python_modules/dagster/dagster/__init__.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/__init__.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_tester.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/rule_condition.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_automation_condition_tester.py
This is an initial forray into exposing a testing API for AutomationConditions. It's quite minimal at the moment, but contains the necessary functions for a user to test how either new materializations or the passage of time might impact the decisions made. It's inspired by the testing framework we use internally, but with a bit less magic.
One constraint here was that any return value from this must only use public APIs, meaning no `AssetKeyPartitionKey` or `AssetSubset`, hence the somewhat weird shape of the AutomationConditionTesterResult object, and the fact that we just log the evaluation results rather than return them outright.
This contains a single test at the moment, roughly indicating how a user might interface with this, but just wanted to put this out to assess the vibes on …
=> [DA][testing] RFC: Create AutomationConditionTester class

js_modules/dagster-ui/packages/ui-core/src/graph/KindTags.tsx, js_modules/dagster-ui/packages/ui-core/src/search/SearchResults.tsx, js_modules/dagster-ui/packages/ui-core/src/search/types.ts, js_modules/dagster-ui/packages/ui-core/src/search/useGlobalSearch.tsx
Use the asset's visual icons (compute/storage kind) to give more flavor to the asset's search result display. This way, users can start to differentiate results from a glance, rather than thoroughly inspecting the fuzzy match and full asset key name.
local
=> feat(catalog): visualize compute and storage kind tags in asset search results

python_modules/libraries/dagstermill/dagstermill/asset_factory.py, python_modules/libraries/dagstermill/dagstermill/examples/repository.py, python_modules/libraries/dagstermill/dagstermill_tests/test_assets.py
Adds the ability to specify `asset_tags` on `define_dagstermill_asset`. Could call this param just `tags` too - went with `asset_tags` just to explicitly differentiate from existing `op_tags` arg.
New unit test.
=> [dagstermill] add asset_tags arg to asset factory

python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py
Using `compute_required_resource_keys` in `asset_check` codepath.
BK
=> Use compute_required_resource_keys_for_underlying_op in @asset_check

js_modules/dagster-ui/packages/ui-core/src/pipelines/Description.tsx
Fixes https://linear.app/dagster-labs/issue/FE-392/issue-with-cut-off-asset-descriptions-and-no-expandscroll-option
Was able to reliably reproduce this loading http://localhost:3001/elementl/prod/assets/purina/cloud_reporting/reporting_deduped_internal_asset_materialization_metrics?view=overview&partition=2024-06-09-21%3A00. 
It appears that this happens because our markdown support is lazy-loaded, and if you navigate to this page and then hard-refresh, the Description element renders empty on the first render, and then fills with markdown content a few renders later. It's possible there's also some React 18 deferred rendering stuff going on, but I'm less sure.
This component is old and less sophisticated than MiddleTruncate. I updated it to use both a resize observer and a mutation …
=> [ui] Modernize Description component, handle async rendering of Markdown

js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeOverview.tsx, js_modules/dagster-ui/packages/ui-core/src/code-links/CodeLink.tsx
=> [ui] Fix two small CSS issues in asset overview sidebar

js_modules/dagster-ui/packages/ui-core/src/assets/AllIndividualEventsButton.tsx
This was caused by us storing the entire focused event in state, rather than just it’s timestamp. After the events refresh in the background, none of them `===` the focused one.
Tested by visiting /elementl/prod/assets/purina/cloud_reporting/reporting_deduped_internal_asset_materialization_metrics?view=partitions&partition=2024-06-09-21%3A00&showAllEvents=true, going to the most recent materializtion, and opening the modal for column_schema.
=> [ui] Fix historical events page being closed by background refresh

python_modules/dagster/dagster/_utils/caching_instance_queryer.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_newly_updated_condition.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenario_specs.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenario_state.py
Fixes https://linear.app/dagster-labs/issue/FOU-219/[schedulingcondition]-fix-handling-of-externalassets-with-the.
For observable external assets, AMP is unresponsive to reported asset materializations because it only looks for the most recent asset observation. This PR changes `CachingInstanceQueryer` to look for the most recent materialization or observation for observables, which allows AMP to respond to reported materializations.
Modified the unit tests for the `NewlyUpdated` conditions to include an observable asset.
=> Make AMP use most recent materialization OR observation for observable assets

python_modules/dagster/dagster/_check/__init__.py, python_modules/dagster/dagster/_model/decorator.py, python_modules/dagster/dagster_tests/general_tests/check_tests/test_check.py
Change the implementation of the generated checked `__new__` implementation for `@dagster_model` to just in time `exec` a copy of what you would have manually written to achieve performance parity with existing manually checked objects. 
before: 
`best of 5 trials of 500000 calls of CheckedNTDagsterModelmake_one(): 886.38 ns per call`
after:
`best of 5 trials of 500000 calls of CheckedNTDagsterModelmake_one(): 543.21 ns per call`
from https://gist.github.com/alangenfeld/43e5a8427702c4c01f9541296299b8d7
=> [dagster_model] JitCheckedNew

js_modules/dagster-ui/packages/ui-core/src/nav/useCodeLocationsStatus.tsx
I have no idea why this fixes it but I was able to repro only in Safari with a particular org who has a failing code location and this seems to fix it. Might be a bug in react-router-dom.
https://app.datadoghq.com/rum/error-tracking?query=%40application.id%3A7edc09bb-51d0-4555-90cd-b19ca483d1fe&fromUser=true&issueId=d9f40514-21a1-11ef-91cb-da7ad0900002&source=all&view=spans&from_ts=1717426770824&to_ts=1718031570824&live=true
Loaded insights in Safari for org with code location that is currently erroring
=> Fix "Attempt to use history.pushState() more than 100 times per 10 seconds" issue

.buildkite/dagster-buildkite/dagster_buildkite/step_builder.py
We're seeing some upticks in Buildkite flakes. I think it's safe to retry around them more systematically:
- [Exit 2 is showing up a occasionally](https://buildkite.com/dagster/dagster-dagster/builds/85297#018fedf7-f1d3-4826-90c6-f562e8c79307) on network related uv install failures.
- [Exit 143 is showing up occasionally](https://buildkite.com/dagster/dagster-dagster/builds/85751#018ffdff-32c9-49e6-a17f-712ac8e3edc8) when the [autoscaling group the cloudformation template provisions is removing an agent from rotation while it's in the middle of running a step](https://dagsterlabs.slack.com/archives/C03EQ628RS7/p1717428269503689?thread_ts=1717427551.865789&cid=C03EQ628RS7).
https://buildkite.com/docs/pipelines/command-step
=> Retry buildkite on additional error codes

js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillRunsTab.tsx, js_modules/dagster-ui/packages/ui-core/src/overview/OverviewTimelineRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/HourlyDataCache/HourlyDataCache.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/HourlyDataCache/__tests__/HourlyDataCache.test.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/RunTimeline.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/__tests__/fetchPaginatedBucketData.test.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/__tests__/useRunsForTimeline.test.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/fetchPaginatedBucketData.ts, js_modules/dagster-ui/packages/ui-core/src/runs/types/useRunsForTimeline.types.ts, js_modules/dagster-ui/packages/ui-core/src/runs/useRunsForTimeline.tsx
- Don't make the Run Timeline wait for FutureTicks to resolve before considering it complete because future ticks pulls the workspace snapshot and is really slow while the other queries tends to be fast.
- ~75% improvement in rendering performance by fixing needless re-rendering, N^2 isAdHoc job logic, and excessive spread usage
Jest tests.
Loaded the Run timeline on various organizations testing both uncached and cached loads and pagination forwards/backwards.
Performance comparison for a cached load of the RunTimeline for a particularly large org 
Before :1,770.62ms
After: 448ms
=> [Run Timeline] Improve rendering performance + Don't wait for future ticks before rendering

js_modules/dagster-ui/packages/ui-core/src/nav/LeftNav.tsx
This thing is super slow to render (~2s!!) (For one of our exceptionally large customers). I will investigate and fix in a follow up PR but for now lets not even render it if its not visible.
locally
=> Only render left nav if visible

python_modules/dagster-graphql/dagster_graphql/schema/backfill.py, python_modules/dagster/dagster/_core/storage/captured_log_manager.py, python_modules/dagster/dagster/_core/storage/local_compute_log_manager.py, python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py, python_modules/dagster/dagster_tests/storage_tests/test_captured_log_manager.py
adds support for IO types in the functions to `read_log_lines_for_log_key_prefix` and related methods
related internal pr https://github.com/dagster-io/internal/pull/10087
bk
=> support io types in captured log manager read_log_lines_for_log_key_prefix

python_modules/libraries/dagster-aws/dagster_aws/s3/compute_log_manager.py, python_modules/libraries/dagster-aws/dagster_aws_tests/s3_tests/test_compute_log_manager.py
implements `get_log_keys_for_log_key_prefix` for the S3 compute log manager so that it can support storing and loading backfill logs
=> add get_log_keys_for_log_key_prefix to s3 compute log manager

python_modules/libraries/dagster-aws/dagster_aws/s3/compute_log_manager.py, python_modules/libraries/dagster-aws/dagster_aws_tests/s3_tests/test_compute_log_manager.py, python_modules/libraries/dagster-gcp/dagster_gcp/gcs/compute_log_manager.py, python_modules/libraries/dagster-gcp/dagster_gcp_tests/gcs_tests/test_compute_log_manager.py
implements `get_log_keys_for_log_key_prefix` for the GCS compute log manager so that it can support storing and loading backfill logs
=> add get_log_keys_for_log_key_prefix to gcs compute log manager

python_modules/libraries/dagster-aws/dagster_aws/s3/compute_log_manager.py, python_modules/libraries/dagster-aws/dagster_aws_tests/s3_tests/test_compute_log_manager.py, python_modules/libraries/dagster-azure/dagster_azure/blob/compute_log_manager.py, python_modules/libraries/dagster-azure/dagster_azure_tests/blob_tests/test_compute_log_manager.py, python_modules/libraries/dagster-gcp/dagster_gcp/gcs/compute_log_manager.py, python_modules/libraries/dagster-gcp/dagster_gcp_tests/gcs_tests/test_compute_log_manager.py
implements get_log_keys_for_log_key_prefix for the Azure blob compute log manager so that it can support storing and loading backfill logs
=> add get_log_keys_for_log_key_prefix to azure compute log manager

js_modules/dagster-ui/packages/ui-core/src/app/CloudOSSContext.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillLogsTab.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillPage.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillRunsTab.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/__tests__/BackfillLogsTab.test.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/__tests__/BackfillPage.test.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/types/BackfillLogsTab.types.ts, js_modules/dagster-ui/packages/ui-core/src/runs/useCursorAccumulatedQuery.tsx, js_modules/dagster-ui/packages/ui-core/src/ticks/InstigationEventLogTable.tsx, js_modules/dagster-ui/packages/ui-core/src/ticks/TickLogDialog.tsx, js_modules/dagster-ui/packages/ui-core/src/ticks/types/InstigationEventLogTable.types.ts, js_modules/dagster-ui/packages/ui-core/src/ticks/types/TickLogDialog.types.ts
The backfill logs are implemented as a cursor-paginated resolver on partitionBackfill. To get the latest logs, you have to start at the first log (no cursor) and paginate to get to the last log. When you reach the last log, it returns `hasMore: false`, and we switch to polling that final cursor for additional logs and advancing it as they come in.
This does mean that showing the "tail" of the logs requires loading them all, but we're not super worried about this -- because the backend implementation stores the logs as files on S3, the underlying implementation doesn't support a "last N" retrieval.
I created a new query hook `useCursorAccumulatedQuery` which is similar to `useCursorPaginatedQuery` but effectively auto-pages and accumulates the data rather than returning a single page at a …
=> [ui] Add a coordinator logs tab to the backfill detail page

examples/assets_dbt_python/assets_dbt_python/__init__.py, examples/assets_dbt_python/assets_dbt_python/assets/forecasting/__init__.py, examples/assets_modern_data_stack/assets_modern_data_stack/__init__.py, examples/assets_modern_data_stack/assets_modern_data_stack/assets/forecasting.py
There are currently no asset checks in any of our example projects. This adds some basic freshness checks to two of our example projects.
=> Add freshness checks to example projects

python_modules/dagster/dagster/_utils/schedules.py
Summary:
The underlying check here is expensive when done repeatedly and (I am nearly certain?) can only possibly happen during these hours.
Test Plan: BK, benchmark generating a large set of representative partition keys drops from 47 seconds to 34 seconds
=> Short-circuit in expensive dst checks other than hours in which ambiguous or non-existant times are possible

python_modules/dagster/dagster/_seven/__init__.py, python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py, python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill_with_backfill_policies.py, python_modules/dagster/dagster_tests/core_tests/test_data_time.py, python_modules/dagster/dagster_tests/daemon_sensor_tests/test_asset_sensor_run.py, python_modules/dagster/dagster_tests/daemon_sensor_tests/test_pythonic_resources.py, python_modules/dagster/dagster_tests/daemon_sensor_tests/test_run_status_sensors.py, python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_failure_recovery.py, python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
More of the same - moving test callsites off of pendulum and into the new freeze_time helper function instead.
=> [2/n] Move all freeze_pendulum_time callsites into a helper function, part 2: sensor tests

integration_tests/test_suites/daemon-test-suite/test_dagster_daemon_health.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_condition_evaluations.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_partitions_subset.py, python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill_with_backfill_policies.py, python_modules/dagster/dagster_tests/core_tests/snap_tests/test_active_data.py, python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_asset_daemon.py, python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_schedule.py, python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/conftest.py, python_modules/dagster/dagster_tests/general_tests/compat_tests/test_back_compat.py, python_modules/dagster/dagster_tests/storage_tests/test_captured_log_manager.py, python_modules/libraries/dagster-gcp/dagster_gcp_tests/bigquery_tests/test_resource.py, python_modules/libraries/dagster-gcp/dagster_gcp_tests/gcs_tests/test_compute_log_manager.py, python_modules/libraries/dagster-snowflake/dagster_snowflake_tests/test_resources.py
Summary:
Rote replacement of the pendulum version for the (mockable) non-pendulum version
=> [4/n] Replace pendulum.now() with get_current_datetime and get_current_timestamp

python_modules/dagster/dagster/_core/test_utils.py, python_modules/dagster/dagster/_seven/__init__.py, python_modules/dagster/dagster/_seven/compat/datetime.py, python_modules/dagster/dagster_tests/asset_defs_tests/asset_graph_view_tests/test_basic_asset_graph_view.py, python_modules/dagster/dagster_tests/asset_defs_tests/asset_graph_view_tests/test_latest_time_window.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_subset.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_freshness_policy.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_partitioned_assets.py, python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill_with_backfill_policies.py, python_modules/dagster/dagster_tests/core_tests/partition_tests/test_partitioned_job.py, python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py, python_modules/dagster/dagster_tests/execution_tests/misc_execution_tests/test_metadata.py, python_modules/dagster/dagster_tests/scheduler_tests/test_cron_string_iterator.py, python_modules/dagster/dagster_tests/scheduler_tests/test_schedule_iterator.py
Another largely rote replacement - create_datetime has the same API as create_pendulum_time for ease of transition. POST_TRANSITION is replaced with fold=1. 
BK
=> [5/n] create_pendulum_time => create_datetime in tests

examples/assets_dynamic_partitions/assets_dynamic_partitions/assets.py, python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py, python_modules/dagster/dagster/_core/definitions/time_window_partitions.py, python_modules/dagster/dagster/_core/definitions/timestamp.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_partitioned_assets.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_partitions_subset.py, python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill_with_backfill_policies.py, python_modules/dagster/dagster_tests/core_tests/graph_tests/test_graph.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_legacy_missing_condition.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenario_specs.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenario_state.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/updated_scenarios/partition_scenarios.py, python_modules/dagster/dagster_tests/definitions_tests/test_flatten_time_window_ranges.py, python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py
Another largely rote one. Added `parse_with_timezone` to keep the nice property that pendulum had where it always ends up with a tzinfo.
BK
=> [6/n] Remove pendulum.instance and pendulum.parse in tests

js_modules/dagster-ui/packages/ui-core/src/jobs/JobsPageContent.tsx, js_modules/dagster-ui/packages/ui-core/src/overview/OverviewResourcesRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/overview/OverviewSchedules.tsx, js_modules/dagster-ui/packages/ui-core/src/overview/OverviewSensors.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceJobsRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceSchedulesRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceSensorsRoot.tsx
Lost some loading state stuff while rebasing these changes... adds back skipping the loading state if the workspace cache has data for us to use in it.
Also made WorkspaceSensors/WorkspaceSchedules pages use the workspace cache if available.
Load OverviewJobs/Sensors/Schedules/Resources for a large customer and see these pages load immediately.
=> [perf] Overview pages - don't show loading state when workspace cache available

js_modules/dagster-ui/packages/ui-components/src/components/TokenizingField.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetLineageElements.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetLink.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/Run.tsx, js_modules/dagster-ui/packages/ui-core/src/search/useGlobalSearch.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext.tsx
Missed a few spots in https://github.com/dagster-io/dagster/pull/22454
load the app and visit various pages without crashing + ts / jest
=> Stop reduce anti-pattern contagion 2

python_modules/dagster/dagster/_core/definitions/instigation_logger.py, python_modules/dagster/dagster/_core/definitions/schedule_definition.py, python_modules/dagster/dagster/_core/definitions/sensor_definition.py, python_modules/dagster/dagster/_daemon/backfill.py, python_modules/dagster/dagster_tests/storage_tests/test_instigation_logger.py
Adds a param to InstigationLogger to allow the user to pass in a custom logger name. For use with the backfill daemon so that we can continue to use the backfill daemon logger when storing backfill logs
manually ran a backfill and saw the logger change from `dagster` to `dagster.daemon.BackfillDaemon` with this change
=> allow other logger names in InstigationLogger

python_modules/dagster/dagster/_daemon/backfill.py
The backfill logging feature hasn't been released yet (and using pendulum to get the log key is an implementation detail and not used by users), so switching this to use the dagster time functions is safe
=> [backfill daemon] dont use pendulum when generating the log key

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
Seeing the following error in our build: https://buildkite.com/dagster/dagster-dagster/builds/86064#01900884-603a-40b5-9b3f-b6fca9570ba2/208-418
```
[2024-06-11T18:19:26Z] 2024-06-11 18:19:26 FATAL  Failed to upload and process pipeline: POST https://agent.buildkite.com/v3/jobs/01900884-603a-40b5-9b3f-b6fca9570ba2/pipelines: 422 The key "dagster-blueprints" has already been used by another step in this build
[2024-06-11T18:19:26Z] 🚨 Error: The command exited with status 1
```
We should be specifying the explicit package in the `EXAMPLE_PACKAGES_WITH_CUSTOM_CONFIG` instead.
bk, see build working: https://buildkite.com/dagster/dagster-dagster/builds/86076
=> chore(buildkite): remove custom package spec for `dagster-blueprints`

python_modules/dagster/dagster/_core/definitions/backfill_policy.py, python_modules/dagster/dagster/_core/definitions/job_definition.py, python_modules/dagster/dagster/_core/definitions/unresolved_asset_job_definition.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_unresolved_asset_job.py, python_modules/dagster/dagster_tests/core_tests/snap_tests/__snapshots__/test_active_data.ambr
Fixes #22254.
- When an unresolved asset job has multiple backfill policies in constituent assets, use the one with the lowest max partitions per run and print a warning. This replaces previous behavior of hard error for conflicting backfill policies.
- Ensure `JobDefinition.backfill_policy` is always non-null by normalizing null values to `BackfillPolicy.multi_run(max_partitions_per_run=1)`. This is handled by backfill machinery in the same way as a null policy, but has a more explicit display in the UI.
A longer term solution will involve allowing asset job backfills to actually use multiple backfill policies.
Modified existing tests.
=> Normalize asset job backfill policies

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py, python_modules/dagster/dagster/_core/definitions/decorators/decorator_assets_definition_builder.py
I am moving toward using DecoratorAssetsDefinitionBuilder in more codepaths (asset checks, graph assets) and things are going to get a little gnarly.
In this case I want to make it explicit which variables are used in these factory methods rather than relying on the grabbag "args" object.
BK
=> Use explicitly passed in arguments instead of args object in builder creation codepaths

python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py, python_modules/dagster/dagster/_core/definitions/decorators/decorator_assets_definition_builder.py
The general approach here will be to incrementally "eat" the current implementation of these decorators by creating the builders and then using their interior methods to incrementally replace the entire body of decorator-based construction.
In this case we will replace the call to `compute_required_resource_keys` with the one in the builder.
BK
=> Begin stack to use DecoratorAssetsDefinitionBuilder for asset-check-related decorators 

python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/decorators/decorator_assets_definition_builder.py
Right now we call `validate_and_assign_output_names_to_check_specs` when we get `check_specs_by_output_name` out of the builder. However this only is relevant to asset-decorator-based (as opposed to the asset checks) use cases so hoisting it to there and removing it from the general path.
BK
=> Move check spec validation into asset-decorator-only creation pathways

python_modules/dagster/dagster/_check/__init__.py
Let's flow type information in `list_param` and friends
Before:
=> add typing information to list_param variants

python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py, python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill_with_backfill_policies.py
When backfills runs are launched using `BackfillPolicy(max_partitions_per_run=1)`, ensure that `RunRequest.partition_key` gets set. This makes these run requests _almost_ equivalent to runs launched with `BackfillPolicy=None`-- the difference is that `BackfillPolicy(max_partitions_per_run=1)` will _also_ set the range tags.
This allows us to do away with null backfill policies in the backfill machinery, instead defaulting to `BackfillPolicy(max_partitions_per_run=1)` (upstack).
New unit test
=> Set `RunRequest.partition_key` when backfilling with policy with `max_partitions_per_run=1`

python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_def_metadata.py
Alternative to #22304 - simplify impl of dbt relation name generation by just concatenating db name, schema, and alias.
This doesn't make an effort to wrap aliases with special chars (e.g. dots), but does look nicer to the eye. The logic here is less complex than in #22304.
Unit test.
=> [dagster-dbt] simplify relation name generation

python_modules/libraries/dagster-polars/setup.py
https://buildkite.com/dagster/dagster-dagster/builds/86076#019008a4-2d77-45ab-8366-db8de4760ec5
> ModuleNotFoundError: The zoneinfo module is required, but could not be imported.  Run `pip install hypothesis[zoneinfo]` and try again.
bk
=> chore: add `zoneinfo` dependency for `dagster-polars` tests

python_modules/libraries/dagster-databricks/dagster_databricks/types.py
The `QUEUED` state is a possible lifecycle state for runs that have queueing enabled and are queried using Jobs API 2.0.
Existing tests pass. `QUEUED` is a non-terminal state, similar to `PENDING`.
=> Add missing QUEUED state to DatabricksRunLifeCycleState

python_modules/libraries/dagster-wandb/dagster_wandb/io_manager.py
Removing a parameter used in the W&B integration that was [deprecated](https://github.com/wandb/wandb/pull/6544).
=> fix: Remove usage of deprecated parameter

js_modules/dagster-ui/packages/ui-core/src/search/useIndexedDBCachedQuery.tsx
Recent changes to this file regressed the immediate fetch from the server in favor of only fetching from cache. This PR adds back the fetching from the server behavior to update the cache.
App proxy, see requests fire in the network panel:
=> Refetch indexeddb cached query immediately

js_modules/dagster-ui/packages/ui-core/src/nav/useCodeLocationsStatus.tsx
Now that useCodeLocationsStatus isn't in charge of the actual refetch it needs to manually check if any code location is not loading in order to stop showing the spinner
Update a code location and make sure the spinner next to the deployment tab stops showing when its done
=> [Workspace] Stop showing spinner when code locations are no longer loading

docs/content/concepts/assets/asset-jobs.mdx
Just fix a boken link in a doc page
the preview now shoes the link
=> docs: fix broken link

python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/last_update.py, python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/time_partition.py, python_modules/dagster/dagster/_core/definitions/asset_check_factories/utils.py, python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/conftest.py, python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_last_update_freshness.py, python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_time_partition_freshness.py
When last update timestamp metadata key isn't provided for an observation, prefer the latest materialization.
This has the potential to be wrong occasionally. The second-latest event could actually be an observation with the correct metadata, instead of the materialization, but figuring that out would require us performing an expensive query.
=> Fix observation handling for freshness checks

python_modules/dagster/dagster/_core/definitions/asset_spec.py, python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/external_asset.py, python_modules/dagster/dagster/_core/storage/asset_value_loader.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py, python_modules/dagster/dagster_tests/core_tests/host_representation_tests/test_external_data.py, python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py, python_modules/dagster/dagster_tests/storage_tests/test_asset_value_loader.py
Makes the `_node_def` property on `AssetsDefinition` optional. This means that:
- `AssetsDefinition`s constructed using `external_assets_from_specs` no longer include a dummy function.
- `AssetsDefinition`s created from `SourceAsset`s no longer include a dummy function.
- `{SYSTEM_METADATA_KEY_ASSET_EXECUTION_TYPE: "UNEXECUTABLE"}` goes away
- `external_assets_from_specs(spec)` now functions identically to `[AssetsDefinition(specs=[spec])]`
A question that came up while implementing this was: what to do about IO managers? `SourceAsset` has an `io_manager_key` attribute. IO manager keys are currently stored inside `OutputDefinition`s. Previously, when converting `SourceAsset`s to `AssetsDefinition`s, we were stashing the `io_manager_key` inside the output defs on the dummy node. This PR …
=> Make `AssetsDefinition.node_def` optional

js_modules/dagster-ui/packages/ui-core/src/instance/CodeLocationsPage.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/flattenCodeLocationRows.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/useCodeLocationPageFilters.tsx, js_modules/dagster-ui/packages/ui-core/src/nav/useCodeLocationsStatus.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedCodeLocationRow.tsx
Recent changes to the WorkspaceContext where we split fetched by location caused us show the code location error toast multiple times. Once for each code location update after we've detected an errored code location. The fix is to instead fire the effect off of the errored code locations and preserve the reference if they haven't changed. 
Also adding a "state" filter to the code locations page for use in the error toast so that if you have 132 locations you can easily see which ones failed.
Loaded an org with 132 code locations and saw a single error toast. Clicked on "view definitions" and saw it took me to the code location page with status = Failed as the filter.
=> Fix duplicate code location error toasts + Add status filter to code locations page

python_modules/dagster-graphql/dagster_graphql/implementation/execution/run_lifecycle.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_retry_execution.ambr, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_retry_execution.py, python_modules/dagster/dagster/_core/execution/api.py, python_modules/dagster/dagster/_core/execution/context/output.py, python_modules/dagster/dagster/_core/execution/plan/execute_step.py, python_modules/dagster/dagster/_core/execution/plan/plan.py, python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster_tests/core_tests/test_resolve_versions.py
This was originally put here as part of a project to be able to execute runs from a host process which we ended up moving away from. The only real utilty this serves is keeping that capability excercised on a critical path. Unfortunately, this can be the source of a class of desync issues when the execution plan is created on version N and then the run starts on version N+1. We also always build the execution plan from scratch in execute_step, so this puts the run code path back in line with that.
The changes that were required to make this work mostly fall out of the rebuild_from_snapshot code path effectively acting as a way to pass through `step_keys_to_execute` so we now just store that resolved value on `DagsterRun` where previously we would record `None` to mean "execute …
=> stop rebuilding execution plan from snapshot in execute_run

js_modules/dagster-ui/packages/ui-core/src/runs/QueuedRunCriteriaDialog.tsx
get runs queued against `applyLimitPerUniqueValue` rule, previously not displayed now:
=> [ui] show applyLimitPerUniqueValue entries in queue criteria

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py, python_modules/dagster/dagster/_cli/asset.py, python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster/_core/storage/event_log/base.py, python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py, python_modules/dagster/dagster/_core/storage/legacy_storage.py, python_modules/dagster/dagster/_core/storage/partition_status_cache.py, python_modules/dagster/dagster_tests/general_tests/compat_tests/test_back_compat.py, python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py, python_modules/dagster/dagster_tests/storage_tests/utils/partition_status_cache.py, python_modules/libraries/dagster-postgres/dagster_postgres_tests/compat_tests/test_back_compat.py
Summary:
Customize whether or not a given storage can write to the asset status cache.
Test Plan: BK
=> Add can_update_asset_cached_status_data to EventLogStorage

python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py
When using `@dbt_assets`, I get a bunch of errors like:
```
2024-06-13 11:06:20 -0400 - dagster - WARNING - /Users/rexledesma/dagster-labs/dagster/python_modules/dagster/dagster/_core/decorator_utils.py:203: ExperimentalWarning: Parameter `tags` of initializer `AssetOut.__init__` is experimental. It may break in future versions, even between dot releases. To mute warnings for experimental functionality, invoke warnings.filterwarnings("ignore", category=dagster.ExperimentalWarning) or use one of the other methods described at https://docs.python.org/3/library/warnings.html#describing-warning-filters.
return fn(*args, **kwargs)
2024-06-13 11:06:20 -0400 - dagster - WARNING - /Users/rexledesma/dagster-labs/dagster/python_modules/dagster/dagster/_core/decorator_utils.py:203: …
```
=> feat(dbt): suppress experimental warning when invoking `@dbt_assets`

docs/content/dagster-plus/deployment/serverless.mdx
Explain how the default filesystem IO manager is replaced in Serverless which could surprise users. Also address that this replacement is not appropriate for sensitive data, specifically warning certain customers (like those with a BAA) that appropriate use of the system forgoes using the default serverless io manager.
- reviewed the docs preview and link
=> Add serverless io manager appropriate usage for baa

python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py
Sprouting off of Nick's comment [here](https://github.com/dagster-io/dagster/pull/22165#discussion_r1638984982), this moves all the computation-related properties of `AssetsDefinition` into their own class.
While in this PR it's restricted to the internals of `AssetsDefinition`, I think that this object could eventually take on a wider role. It basically corresponds to the nodes on the right in this diagram I've been bandying about:
=> `AssetGraphComputation` inside `AssetsDefinition`

js_modules/dagster-ui/packages/ui-core/src/instance/InstanceBackfills.tsx
We were blocking on the instance health query but not the main content query, so add that.
=> [ui] block backfills page on main content

python_modules/dagster/dagster/_core/events/__init__.py, python_modules/dagster/dagster/_core/execution/api.py, python_modules/dagster/dagster_tests/core_tests/test_event_logging.py
This will allow us to retrieve step failure information in a performant way for large runs. I chose to retrieve "earliest" step failure event, since that's the one relevant to the state transition from "in progress" to "failed" run.
Some concern for if, in the future, we want to include more than just the latest step failure, we'll need to have some serdes logic to switch this new field to a list that includes more than just the latest event. It's also possible we can choose some non-comprehensive N of step failure events to occur, but I think I prefer just retrieving the earliest for now to keep it simple.
Added a test to ensure that we actually receive the earliest step failure.
=> [rfc] Add earliest step failure event to job failure event

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py
In some cases, the dbt exit code may be incorrect. The exit code is 0, but error logs were emitted by the invocation.
To confirm a successful dbt invocation, ensure that there are no error logs. Otherwise, mark the invocation as unsuccesful.
pytest
=> fix(dbt): mark invocations with error logs as unsuccessful

python_modules/libraries/dagster-postgres/dagster_postgres/event_log/event_log.py, python_modules/libraries/dagster-postgres/dagster_postgres/run_storage/run_storage.py, python_modules/libraries/dagster-postgres/dagster_postgres/schedule_storage/schedule_storage.py, python_modules/libraries/dagster-postgres/dagster_postgres/utils.py
AWS RDS Proxy does not support cli options, so setting any mandatory connection options via statement improves compatibility.
Any custom options are still passed through as prior
- dagster_postgres pytests
- `dagster dev` and connect via rds proxy and directly, storage loads as expected
Resolves: #11762
=> fix: set postgres timeout args via query

python_modules/libraries/dagster-pandas/setup.py, python_modules/libraries/dagster-pandera/setup.py, python_modules/libraries/dagster-wandb/setup.py
The release of numpy 2 broke several of our integration libraries. This PR pins numpy 2 in those libraries-- we can remove the pins when versions of the third-party libraries are released that either support numpy 2 or add appropriate pins.
=> Pin numpy<2 in dagster integration libs that depend on it

docs/content/concepts/partitions-schedules-sensors/sensors.mdx, examples/docs_snippets/docs_snippets/concepts/partitions_schedules_sensors/sensors/sensors.py
OpExecutionContext is missing in the imports for dagster in this particular snippet, so copy-pasting fails on import
Make sure I can copy-paste the snippet and things work
=> include OpExecutionContext in snippet

python_modules/dagster/dagster/_core/execution/submit_asset_runs.py
Summary:
These are showing up in the user-facing logs in a way that may be confusing, I don't think we need them?
Test Plan: Launch a backfill, no more debug line in logs
=> Remove debug log lines from asset backfill

python_modules/dagster-graphql/dagster_graphql/schema/backfill.py
Summary:
This is a non-nullable field, make it "" to match the other similar-ish cases
Test Plan: Load a backfill without logs yet, no more error in console
=> Fix error when you try to load backfill logs before there are any logs

js_modules/dagster-ui/packages/ui-core/src/runs/useRunsForTimeline.tsx
There's a missing dependency here since we stopped blocked on the future ticks query which would normally fill the gap while indexeddb loaded. Without this dependency we end up logging display done too early.
Take a sample locally: https://app.datadoghq.com/rum/sessions?query=%40application.id%3A6d12cca2-0263-463b-a90e-cc6c524e14bd%20%40usr.email%3Amarco%40dagsterlabs.com%20%40type%3Aaction&agg_m=count&agg_m_source=base&agg_q=%40issue.id&agg_q_source=base&agg_t=count&cols=&event=AgAAAZAn4VnigTg1mwAAAAAAAAAYAAAAAEFaQW40WXhoQUFERVNFNm1DeVo1blFBRAAAACQAAAAAMDE5MDI3ZTEtYmUyNS00ODZjLThkYTEtMDFlYzg3ZWM1YjFh&fromUser=false&tab=error&top_n=10&top_o=top&viz=stream&x_missing=true&from_ts=1718569637424&to_ts=1718656037424&live=true
=> Make display done wait for indexeddb cache to load 

python_modules/libraries/dagster-polars/dagster_polars/io_managers/delta.py
This log message was accidentally removed in my last dagster-polars PR. Fixing this.
=> :loud_sound: return the missing debub log message when loading partitions with PolarsDeltaIOManager

python_modules/libraries/dagster-gcp/dagster_gcp/gcs/io_manager.py
Example in the GCS I/O manager doc string incorrectly sets the GCS resource dependency for the I/O manager
=> GCS IO manager - update example in doc string

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/dlt/resource.py
Appending to the _dlt_ pipeline name results in unintended consequences in that _filesystem_ destinations will have file names that do not adhere to typical _dlt_ usage. This removes the appended partition to the pipeline name. For more context see the discussion below:
https://github.com/dagster-io/dagster/pull/22000#issuecomment-2174983213
- pytest
=> fix(dlt) do not append to pipeline name as results in unintended side-effects

python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py
We already implicitly expect this in various places in our code. E.g.:
- https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_core/definitions/assets.py#L328.
- https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_core/definitions/asset_layer.py#L294
I believe we assume a single materialization per asset (per partition) per run.
=> in AssetsDefinition construction, enforce single key per output name

integration_tests/test_suites/daemon-test-suite/auto_run_reexecution_tests/test_auto_run_reexecution.py, python_modules/dagster/dagster/_cli/api.py, python_modules/dagster/dagster/_daemon/auto_run_reexecution/auto_run_reexecution.py, python_modules/dagster/dagster/_utils/tags.py
Summary:
The logic here was checking for the non-None-ness of the tag value rather than the truthiness of the string tag value.
Test Plan: BK
=> Fix retry logic when setting dagster/retry_on_asset_or_op_failure to False in a job tag

python_modules/dagster/dagster/_check/__init__.py, python_modules/dagster/dagster_tests/general_tests/check_tests/test_check.py
Fix mishandling of processing `Union[A, B, C]` in to `check.inst_param(x, "x", of_type=(A, B, C))` 
added test
=> [check] fix build_check_call_str Union handling

python_modules/dagster/dagster/_core/definitions/asset_graph.py, python_modules/dagster/dagster/_core/definitions/asset_spec.py, python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_asset_partition_mappings.py, python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_multipartition_partition_mapping.py
This is an incremental step towards both:
- Removing `AssetsDefinition` from internals
- Enabling partitioning per-asset rather than per-`AssetsDefinition`
=> in AssetNode, get partition mapping from spec

docs/dagster-university/pages/dagster-dbt/lesson-5/2-connecting-dbt-models-to-dagster-assets.md
- Fixes indentation of code snippets for indented code blocks
- Previewed rendered markdown
=> [daggy-u] fix indentation of indented code snippets

python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py
Moving helper functions from `dagster_dbt/asset_decorator.py` to `dagster_dbt/asset_utils.py`.
bk
=> refactor(dbt): move `@dbt_assets` helper functions out of `asset_utils.py`

python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py
- Rename the helper function for `@dbt_assets` to `build_dbt_multi_asset_args`,
- Coalesce all logic associated with that functionality into `build_dbt_multi_asset_args`.
- Make the signature of `build_dbt_multi_asset_args` a subset of the arguments to `@dbt_assets`.
bk
=> refactor(dbt): coalesce the `@dbt_assets` helper logic

python_modules/libraries/dagster-dbt/dagster_dbt/__init__.py, python_modules/libraries/dagster-dbt/dagster_dbt/asset_specs.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py
Using `build_dbt_multi_asset_args`, transform its outputs to a set of `AssetSpec`. Put this in a named function called `build_dbt_asset_specs`.
Now, the user can create external assets for a dbt project. They do not need to specify the materialization function for a dbt project if that is managed elsewhere.
Later on, we can shift `@dbt_assets` from using `build_dbt_multi_asset_args` (which effectively uses `AssetOut`) to use `build_dbt_asset_specs` (uses `AssetSpec`) in its internal implementation. But since `build_dbt_asset_specs` uses `build_dbt_multi_asset_args` in its internal implementation, this shouldn't be a pressing need.
pytest
=> feat(dbt): implement `build_dbt_asset_specs` to build `AssetSpec` from a dbt project

python_modules/dagster/dagster_tests/core_tests/partition_tests/test_partition.py
Summary:
This was a very odd test that omitted a year, which appears to create a partitions definition that starts in 1900 (!) (which fails on Windows). Give it a year instead.
Test Plan: BK
=> Make partitions test include a year

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/dbt_packages/test_columns_metadata.py
On issues like https://github.com/dagster-io/dagster/issues/22358#issuecomment-2182522019, we should not fail the computation. Instead, we should surface the exception as a warning.
pytest
=> feat(dbt): catch exceptions when invoking adapter to build column lineage

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py
Just construct the relation directly. If an error occurs, it will be caught in the enclosing try/catch.
=> feat(dbt): do not invoke the adapter to build the table relation

js_modules/dagster-ui/packages/ui-core/src/nav/useCodeLocationsStatus.tsx
https://linear.app/dagster-labs/issue/FE-408/bug-error-popup-is-displayed-when-loading-the-code-locations-tab-with
Force a code location to error, then update it and refresh the page, make sure we don't show the error toast in this case.
=> Don't show error toast on a code location if its updating

examples/experimental/dagster-blueprints/examples/custom-blueprints/custom_blueprints/__init__.py, examples/experimental/dagster-blueprints/examples/custom-blueprints/custom_blueprints/curl_assets/cereals.yaml, examples/experimental/dagster-blueprints/examples/custom-blueprints/custom_blueprints/curl_assets/customers.yaml, examples/experimental/dagster-blueprints/examples/custom-blueprints/custom_blueprints/definitions.py, examples/experimental/dagster-blueprints/examples/custom-blueprints/pyproject.toml, examples/experimental/dagster-blueprints/examples/custom-blueprints/setup.cfg, examples/experimental/dagster-blueprints/examples/custom-blueprints/setup.py
=> add example with custom blueprints

js_modules/dagster-ui/packages/ui-core/src/resources/ResourceRoot.tsx
The core issue here was `resource.name` instead of `resource.resource.name`, but I renamed the top level var to make it more clear.
=> FE-414: Fix invalid links to resources on the resource page

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py
Fixes: #22625
Dbt integration fails to add row count materialization metadata when the asset's table
contains characters which require it to be quoted.
Modified code and ran locally on asset that is failing with current code from `master`
I would have added unit tests, but I didn't see any for the exising row count feature
so it wasn't clear where to start there/if they were necessary.
=> Quote table identifiers for row count query in dbt integration

examples/experimental/dagster-blueprints/dagster_blueprints/load_from_yaml.py, python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/metadata/source_code.py
Adds a utility that makes it easier to replace asset-level attributes on `AssetsDefinition`s.
=> AssetsDefinition.map_asset_specs

python_modules/dagster/dagster/_seven/__init__.py
=> Eliminate python-2-only codepath in seven.wait_for_process

python_modules/dagster/dagster/_grpc/impl.py, python_modules/dagster/dagster/_seven/__init__.py
Underlying contextlib.nullcontext available in all supported versions
BK
=> Eliminate seven.nullcontext

integration_tests/test_suites/daemon-test-suite/monitoring_daemon_tests/test_monitoring.py, integration_tests/test_suites/daemon-test-suite/utils.py, python_modules/dagster/dagster/_core/execution/compute_logs.py, python_modules/dagster/dagster/_grpc/server.py, python_modules/dagster/dagster/_seven/__init__.py, python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_ping.py, python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py
Eliminate `wait_for_process` in favor of `.communicate`. Note we no longer get the `timeout=30` default.
BK
=> Eliminate seven.wait_for_process

python_modules/dagster/dagster/_annotations.py, python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py, python_modules/dagster/dagster_tests/test_annotations.py, python_modules/libraries/dagster-dbt/dagster_dbt/asset_defs.py
A further extension to #22385, this proposes making an explicit `hidden_param` rather just a boolean flag on `deprecated_param`.
Two reasons why this could be a good idea.
1) This is more greppable. We could audit our uses of hidden versus deprecated trivially, rather than having to inspect every callsite.
2) We could use hidden params for the experimental use case as well, as a way to _introduce_ capabilities in our releases without polluting public signatures.
I think #2 potentially pretty compelling. I'm not super high conviction on this but writing this out made my think this is the right approach.
BK
=> Explicit hidden_param

js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/useAssetDefinitionFilterState.tsx, js_modules/dagster-ui/packages/ui-core/src/search/BuildAssetSearchResults.tsx, js_modules/dagster-ui/packages/ui-core/src/ui/Filters/useComputeKindTagFilter.tsx
Fixes https://linear.app/dagster-labs/issue/FE-357/bug-compute-kind-tags-should-ignore-capitalization
This is actually a bit nuanced -- once I updated the catalog home page to show `Airtable` and `airtable` compute kinds as a single option, I realized that clicking it led to the filtered catalog view where the filters were case-sensitive. 
This PR currently updates the grouping behavior for all groupings, but only makes compute kind search case insensitive. I think the `CaseInsensitiveCounters` may essentially be a no-op for other things, but are worth using for consistency. 
I tested this by making some mis-capitalized and lowercased compute kinds in my local repo, and also used the app-proxy to connect to prod and verify that dogfood's catalog landing page looks identical before and …
=> [ui] Make asset compute kind grouping and filtering case-insensitive

js_modules/dagster-ui/packages/ui-core/src/partitions/OpJobPartitionsView.tsx, js_modules/dagster-ui/packages/ui-core/src/partitions/PartitionGraph.tsx, js_modules/dagster-ui/packages/ui-core/src/partitions/RunMatrixUtils.tsx, js_modules/dagster-ui/packages/ui-core/src/partitions/usePartitionStepQuery.tsx, js_modules/dagster-ui/packages/ui-core/src/search/useIndexedDBCachedQuery.tsx
- Use a set to check if partitionNames array includes a partition  to avoid n^2 logic
- no-cache on queries to avoid long apollo cache frames
- more memoization
There's still a lot of work happening on the main thread but this is a big improvement
=> [perf] Fix long job partitions page frame when over 100k+ partitions

python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
An ephemeral asset job created with `materialize()` that fails, causes the `RunStatusSensorDefinition` to fail.
I modified the file in and ran locally.
=> fix #22665 - support ephemeral asset job in run_status_sensor

python_modules/dagster/dagster/_core/execution/asset_backfill.py, python_modules/dagster/dagster/_core/execution/backfill.py, python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py
Adds methods to make a backfill from an `AssetGraphSubset`. This will make emitting backfills from DA easier. 
new unit tests
=> make PartitionBackfill from AssetGraphSubset

docs/content/getting-started/quickstart.mdx, examples/docs_snippets/docs_snippets/getting-started/quickstart/assets.py, examples/docs_snippets/docs_snippets/getting-started/quickstart/configurations.py
- For ease of copying, make it so that the assets.py file is self contained
`dagster dev -f assets.py`
=> [docs] make quickstart self contained in assets.py

python_modules/dagster/dagster/_core/definitions/load_assets_from_modules.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_assets_from_modules.py
To my understanding, it should be possible to provide the `source_key_prefix` argument to `load_assets_from_modules` as a string and not only as a list of strings, just as is the case for `key_prefix`. However, this was not the case. Although passing validation checks, loading a SourceAsset with key `source_asset_key` with `source_key_prefix="prefix"` resulted in `AssetKey(['p', 'r', 'e', 'f', 'i', 'x', 'source_asset_key'])`.
Fixed the behavior by checking that `source_asset_key` is a list before applying it.
Added an additional assert to function `test_source_key_prefix` in `test_assets_from_modules.py`.
=> Bugfix handle string source key prefix

js_modules/dagster-ui/packages/ui-core/src/app/AppProvider.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx, js_modules/dagster-ui/packages/ui-core/src/hooks/__tests__/useThrottledMemo.test.tsx, js_modules/dagster-ui/packages/ui-core/src/hooks/useThrottledMemo.tsx, js_modules/dagster-ui/packages/ui-core/src/partitions/OpJobPartitionsView.tsx, js_modules/dagster-ui/packages/ui-core/src/partitions/PartitionGraph.tsx, js_modules/dagster-ui/packages/ui-core/src/partitions/PartitionStatus.tsx, js_modules/dagster-ui/packages/ui-core/src/partitions/PartitionStepStatus.tsx, js_modules/dagster-ui/packages/ui-core/src/partitions/useMatrixData.tsx, js_modules/dagster-ui/packages/ui-core/src/partitions/usePartitionStepQuery.tsx, js_modules/dagster-ui/packages/ui-core/src/search/__tests__/useIndexedDBCachedQuery.test.tsx, js_modules/dagster-ui/packages/ui-core/src/search/useIndexedDBCachedQuery.tsx, js_modules/dagster-ui/packages/ui-core/src/ui/Loading.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext.tsx
- Memoized a bunch of stuff to fix a re-render loop caused by references changing. 
- Hide partition graph if large
- Wrote a useThrottledMemo hook that can be used when dependencies are changing often. I wrote it to band-aid the re-render loop but then after more extensive memoization I fixed the actual source of the re-render loop. I'm keeping the hook around though because I think it'll be useful for the Gantt chart on the Runs page when there are a huge number of steps.
Jest tests + used this in partitions view:
Before (2s frames): 
After no re-rendering loop, much smaller frames (biggest frame is 450ms, and its apollo cache, will look into what it is caching):
=> [Performance] Partitioned job page - Memoize everything + hide partition graph if large

python_modules/dagster/dagster/_core/definitions/instigation_logger.py, python_modules/dagster/dagster/_daemon/backfill.py
The `InstigationLogger` creates a colored console logger to log messages to the console in addition to storing them in a blob. When we started using the `InstigationLogger` for the backfill daemon, this meant that the log messages were getting logged with the format of the colored console logger, not with the format specified by the dagster-daemon cli. This PR allows you to use the colored console logger or a different logger to additionally log the messages
`dagster-daemon run --log-format json`
```
2024-06-24 11:56:09 -0400 - dagster.daemon.BackfillDaemon - INFO - After BFS-should-backfill filter, asset partitions to request: {AssetKeyPartitionKey(asset_key=AssetKey(['the_hourly_asset']), partition_key='2024-06-02-11:00'), AssetKeyPartitionKey(asset_key=AssetKey(['the_hourly_asset']), …
```
=> use provided logger to log console messages in InstigationLogger

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorerFilters.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNode.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeOverview.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetTable.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/useAssetCatalogFiltering.tsx, js_modules/dagster-ui/packages/ui-core/src/graph/KindTags.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedAssetRow.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedAssetTable.tsx
Adds the ability to click on a compute kind or storage kind tag in the asset graph or asset list to filter to that kind.
=> [ui] add click-to-filter behavior in asset graph, list

js_modules/dagster-ui/packages/ui-core/src/pipelines/PipelineExplorerRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext.tsx
loading by snapshot id is faster in environments where the workspace is loaded from scratch to find the job by selector 
fresh page load on a job -> uses selector
in app navigation once `WorkspaceContext` is ready -> uses snapshot id and loads faster
=> [PipelineRootExplorer] load by snapshotId when available from WorkspaceContext

python_modules/dagster/dagster/_core/definitions/asset_layer.py, python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/graph_definition.py, python_modules/dagster/dagster/_core/definitions/job_definition.py, python_modules/dagster/dagster/_core/definitions/node_definition.py, python_modules/dagster/dagster/_core/definitions/op_definition.py, python_modules/dagster/dagster/_core/execution/plan/execute_step.py, python_modules/dagster/dagster/_core/remote_representation/external_data.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_job.py
In graph-backed assets, there ops that directly produce assets often depend on ops that don't directly produce assets. In various situations, we need to find all the ops within a graph-backed asset that need to be executed to materialize a particular asset. Or the inverse.
This PR aims to simplify the way we track this correspondence by consolidating it inside `AssetsDefinition`. Prior to this PR, it's tracked with a big dictionary in the asset layer, which is a little confusing because it makes it seems like these dependencies can cross `AssetsDefinition`.
The motivation for this PR is to have a smooth base for simplifications to this logic, which will ultimately help with refactoring the relationship between `AssetLayer` and `AssetGraph`.
Direct effects of this PR:
- `AssetLayer` loses …
=> consolidate graph asset op handle dependency logic

js_modules/dagster-ui/packages/ui-core/src/pipelines/PipelineExplorerRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/pipelines/PipelineOverviewRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext.tsx
missed some behavior differences in oss that cause this scheme to not work
=> Revert "[PipelineRootExplorer] load by snapshotId when available from WorkspaceContext (#22686)"

js_modules/dagster-ui/packages/ui-core/src/hooks/__tests__/useThrottledMemo.test.tsx, js_modules/dagster-ui/packages/ui-core/src/hooks/useThrottledMemo.tsx
Feedback on my last PR suggested I used a ref to access `factory` but I realize now that it's wrong because it causes different semantics from `useMemo` which uses stale closures until dependencies change. So I'm reverting that part.
ie. In this case we would want to keep the stale closure:
```
useMemo(() => {
arg3(arg1, arg2);
// @ts-ignore intentionally don't include arg3 in memo for xyz reason.
}, [arg1, arg2])
```
jest
=> [useThrottledMemo] Don't Access factory via ref.

.pre-commit-config.yaml
Internal companion PR: https://github.com/dagster-io/internal/pull/10219
Currently pre-commit will run all of our defined hooks pre-push. There is no point re-running hooks that also run pre-commit. This PR makes it so that only the pyright hook runs pre-push.
Pushed and observed executed hooks
=> [pre-commit] Only run pyright in pre-push

js_modules/dagster-ui/packages/ui-core/src/pipelines/PipelineExplorerRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/pipelines/PipelineOverviewRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext.tsx, python_modules/dagster-graphql/dagster_graphql/implementation/fetch_pipelines.py, python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_pipeline_snapshot.py
second pass of #22686 that also
* memoizes `explorerPath` to avoid re-renders
* updates the server to allow both snap and selector (preferring snap) 
added server tests
launched dagit and clicked through jobs ensuring they all load
=> [PipelineRootExplorer] load by snapshotId when available from WorkspaceContext (take 2)

python_modules/dagster/dagster/_utils/caching_instance_queryer.py
Summary:
This was reversing a randomly sorted list of partition keys, but I believe the intention was to sort the partition keys and then take the N most recent.
Test Plan: BK, run a dry run and verify that the most recent N partitions are getting sliced off now
=> Sort partition keys in MaterializeOnParentUpdatedRule before filtering

js_modules/dagster-ui/packages/ui-core/src/assets/AssetPartitions.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetsOverviewRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/__stories__/AssetPartitions.stories.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/AssetPartitions.test.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/AssetView.test.tsx
1. Removed the AssetOverviewRootQuery because it's a subset of what AssetViewDefinitionQuery fetches and it's only used to render the catalog if an asset doesn't exist. Instead I made AssetView redirect to the catalog table if the asset doesn't exist. This means that we do render the chrome of the AssetView while loading and then redirect to the catalog if the asset doesn't exist, IMO this trade off is worth making to avoid the waterfall. In a future PR I can update all of the tabs to show a loading state while their definition query is loading instead (I did this for the partitions tab).
2. Render the partitions tab while the definition query is loading so that it can fetch partition data in parallel
1. Loaded a url for an asset that doesn't exist and made sure we redirected to the …
=> [perf] Fix waterfall on asset partitions tab

python_modules/dagster/dagster/_core/definitions/definitions_class.py
This bad type annotation was hiding the complexity that I think underlies why we chose to pull defns off of the inputs rather than the repository definition;
because for a pending repository definition, we need to "force it to load" in order to retrieve assets defs.
Downstream PRs will attempt to address this state of affairs, but for now let's make this more clear.
=> Fix type annotation on defns util method

js_modules/dagster-ui/packages/ui-core/src/instance/useCodeLocationPageFilters.tsx, js_modules/dagster-ui/packages/ui-core/src/nav/LeftNavRepositorySection.tsx, js_modules/dagster-ui/packages/ui-core/src/ui/SectionedLeftNav.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext.tsx
With recent changes to `WorkspaceContext`, we would render the code locations view with partial data leading to a confusing user experience.
In this PR we update the `loading` logic of `WorkspaceContext` and only pass through entries in filtered code locations hook when loading is complete. 
loaded up a deployment with a slow code location and saw the page correctly block until all entries were present
=> [ui] fix code locations loading

python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_impls.py
Previously, we were generating "ValidAssetSubsets" as the default values when no previous information existed. However, these were valid asset subsets for the wrong asset (the child instead of the parent), which could cause errors.
=> [AMP][bug] Fix previous parent subset logic

python_modules/dagster/dagster/_core/definitions/base_asset_graph.py, python_modules/dagster/dagster/_core/definitions/partition_mapping.py
Was just doing some dry run spot checking and noticed two silly things. One is that `subset.size > 0` is far more expensive than `subset.empty`, and the other is that if you have an AllPartitionMapping (the default when you have an unpartitioned asset downstream of a partitioned asset), the mapping function calls `partitions_def.subset_with_all_partitions`, which does the inefficient thing of calculating every single partition key of an asset. This makes it so that we just use the efficient AllPartitionsSubset class when possible.
Took a representative trial run from 180s -> 25s.
=> [perf] Simple partition perf fixes

python_modules/dagster/dagster/_check/builder.py, python_modules/dagster/dagster_tests/general_tests/check_tests/test_check.py
Does a `check.inst` on the `bound` value.
=> support type-checking TypeVars in dagster_model

python_modules/dagster-graphql/dagster_graphql/implementation/events.py, python_modules/dagster-graphql/dagster_graphql/implementation/fetch_solids.py, python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py, python_modules/dagster-graphql/dagster_graphql/schema/solids.py, python_modules/dagster/dagster/_core/definitions/dependency.py, python_modules/dagster/dagster/_core/execution/context/output.py, python_modules/dagster/dagster/_core/execution/plan/compute.py, python_modules/dagster/dagster/_core/execution/plan/handle.py, python_modules/dagster/dagster/_core/execution/plan/plan.py, python_modules/dagster/dagster/_core/snap/execution_plan_snapshot.py, python_modules/dagster/dagster/_core/system_config/composite_descent.py, python_modules/dagster/dagster_tests/core_tests/snap_tests/test_repository_snap.py, python_modules/dagster/dagster_tests/definitions_tests/test_node_handle.py
Typical python practice is to implement `__str__` instead of `to_string`. `NodeHandle` currently has both, and they do the same thing. This removes `to_string`.
=> remove NodeHandle.to_string()

python_modules/dagster/dagster/_core/execution/job_execution_result.py
The `input_name` param of `StepExecutionContext.for_input_manager` has a `str` type annotation. However when I made a change elsewhere that enforced this type deeper in the stack, I found a callsite where a `None` value is passed in for this parameter.
I considered adding a constant for the value that's being passed in, but it's not referenced elsewhere. Can still do so though if preferred.
- Added type annotations to `_get_value`
- Observed that the type checker started to complain about the value passed to the `input_name` argument in `for_input_manager`
- Added my "fix"
- Observed that the type checker stopped complaining
=> fix unexpected type in JobExecutionResult._get_value()

python_modules/dagster/dagster/_core/definitions/metadata/__init__.py, python_modules/dagster/dagster/_core/definitions/metadata/source_code.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_defs_source_metadata.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_code_references.py
Deprecates the old `link_to_source_control` code references wrapper (should just be used internally) and creates the new `link_to_git` wrapper (to match `link_to_git_in_cloud`) which now can be provided with a more flexible local file->source control path mapping.
This mapping can either be specified as a pair of (path to a reference 'anchor' file locally, path to that 'anchor' file in source control), which is used to map all other files, or a custom user-provided fn.
Unit tests.
=> [code links] more flexible local->git filepath  mapping in link_to_git fn

python_modules/libraries/dagster-pandera/setup.py
our code and doc strings make heavy use of `SchemaModel` which was deprecated and no longer top level exported in `0.20.0` 
bk
=> [pandera] pin < 0.20.0

python_modules/libraries/dagster-dbt/dagster_dbt/asset_specs.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_specs.py
Looks like `external_assets_from_specs` enforces that some properties on `AssetSpec` are set to the defaults before converting them to `AssetsDefinition`. So ensure that `build_dbt_asset_specs` follows this invariant.
pytest
=> fix(dbt): ensure `external_assets_from_specs` composes with `build_dbt_asset_specs`

python_modules/automation/tox.ini
There has to be a better way than just installing all of these dependencies. But just cargo-culting for now to fix the build.
bk
=> fix: add `dagster-sdf` to automation tox suite dependencies

python_modules/dagster/dagster/_core/definitions/assets.py
`_build_graph_dependencies` used to be used for graphs that spanned multiple `AssetsDefinition` objects, but now it's just used within a single `AssetsDefinition`. That means we can simplify it a little bit.
=> remove unnecessary arg from _build_graph_dependencies in assets.py

js_modules/dagster-ui/packages/ui-components/.storybook/main.js, js_modules/dagster-ui/packages/ui-core/.storybook/main.js
Disable react-docgen in Storybook build, because pulling in massive generated GraphQL types is causing memory failures in CI/Vercel.
Add a memory-limited build command to package.json:
```
"build-storybook-limited": "NODE_OPTIONS=--max_old_space_size=2048 storybook build"
```
Run this to repro the memory failure. Kill docgen (as in the PR), rerun. Verify that the build completes correctly.
=> [ui] Fix Storybook memory bug

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNode.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/layout.ts
Fixes FE-263 - The problem here is that we recently added a "Checks" row to the nodes on the asset graph, which appears only if the live data indicates there are checks. Because the live data / checks info isn't loaded as part of the graph definition data, we don't know whether to leave space for the row in the graph layout. 
We'll likely move checks to definition data at some point, but I worry it could have perf implications (ideally maybe we just send a boolean). For now, we're just rendering extra space as if every asset has checks.
I also updated the other constants in the layout calculation to reflect the latest styles.
Before:
After: 
Large before:
Large after:
=> [ui] Update asset layout spacing to account for possible checks

examples/assets_pandas_type_metadata/assets_pandas_type_metadata/lib.py, examples/assets_pandas_type_metadata/setup.py, python_modules/libraries/dagster-pandera/dagster_pandera/__init__.py, python_modules/libraries/dagster-pandera/dagster_pandera_tests/test_dagster_pandera.py, python_modules/libraries/dagster-pandera/setup.py, python_modules/libraries/dagster-pandera/tox.ini
Pandera 0.20.0 removed a deprecated API we were using called `SchemaModel`. Update to the new name `DataFrameModel`, which has been around since at least 0.15.0 judging from the release notes.
Also drop numpy<2 pin, which new pandera release correctly handles on its own.
=> [dagster-pandera] Update SchemaModel to DataFrameModel

helm/dagster/schema/schema_tests/test_instance.py, helm/dagster/templates/helpers/instance/_run-launcher.tpl
When passing custom image config for the `k8sRunLauncher` in Helm values [here](https://github.com/dagster-io/dagster/blob/e25ecea78aa46ed357c16fbd55539f620bebd7bf/helm/dagster/values.yaml#L476-L479)
```yaml
runLauncher:
type: K8sRunLauncher
config:
k8sRunLauncher:
imagePullPolicy: "IfNotPresent"
image:
repository: "custom-image"
tag: "0.1"
pullPolicy: IfNotPresent
```
Helm fails with this error:
```shell
Error: INSTALLATION FAILED: template: dagster/templates/deployment-webserver.yaml:3:4: executing "dagster/templates/deployment-webserver.yaml" at <include "deployment-webserver" $data>:
error calling include: template: dagster/templates/helpers/_deployment-webserver.tpl:36:38: executing "deployment-webserver" at <include (print $.Template.BasePath "/configmap-instance.yaml") .>:
error …
```
=> Fix custom `job_image` in helm for `K8sRunLauncher`

js_modules/dagster-ui/packages/ui-core/src/app/AppError.tsx
Add operation name to `[Network Error]` log so that we can pinpoint queries causing OOMs / timeouts / etc.
Also added more logging to make sure we can always pinpoint the operation that is causing an ApolloError since by default it doesn't include the operation name.
https://app.datadoghq.com/rum/error-tracking?query=%40application.id%3A6d12cca2-0263-463b-a90e-cc6c524e14bd&fromUser=false&issueId=6c8df1bc-07c3-11ef-9600-da7ad0900002&source=all&view=spans&from_ts=1719512901245&to_ts=1719513801245&live=true
=> Add operation name to `[Network Error]` log so that we can pinpoint queries causing OOMs

python_modules/dagster/dagster/_core/definitions/asset_layer.py, python_modules/dagster/dagster/_core/definitions/dependency.py
This paves the way for using `NodeOutputHandle`s and `NodeInputHandle`s to represent paths to node outputs and inputs within an `AssetsDefinition`. `AssetsDefinitions` are often op-backed, in which case the `node_handle` will be `None`.
=> make `node_handle` optional on `NodeOutputHandle` and `NodeInputHandle`

python_modules/dagster/dagster/_core/definitions/asset_layer.py, python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/dependency.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py, python_modules/dagster/dagster_tests/definitions_tests/test_node_handle.py
The `asset_or_check_keys_by_dep_op_output_handle` and `dep_op_handles_by_asset_or_check_key` properties on `AssetsDefinition` return dictionaries that relate asset keys to ops within the `AssetsDefinition`.
We use `NodeHandle`s to identify the ops within the `AssetsDefinition`, but the way that we do so is non-standard way:
- A `NodeHandle` represents a path down the composition tree to a node within a graph, from the root of that graph. They do _not_ include the name of the outer graph definition, because that name might be aliased if it's embedded in a larger graph.
- The `NodeHandle`s returned in these dictionaries _do_ contain the name of the root graph definition.
We in fact do embed these asset-level graph definitions within a larger graph - the asset-job level graph. This means …
=> don't include outer node handle in AssetsDefinition asset/op deps

examples/experimental/dagster-blueprints/dagster_blueprints/cli.py
I noticed that, after running `dagster-blueprints configure-vscode`, there was a long pause before anything happened. Upon inspection, this occurred while running `code --list-extensions`.
This PR adds an echo to make it clear that to users that this is what's happening behind the scenes.
=> in blueprints CLI, echo checking whether redhat.vscode-yaml extension is installed

js_modules/dagster-ui/packages/ui-core/src/search/useIndexedDBCachedQuery.tsx
The `pipelineSelector` reference is changing every render, to make this less foot gunny I'm making useIndexedDBCachedQuery JSON.stringify the variables instead
tested with app proxy
=> [Asset graph]  Fix graph data refetch loop in job asset graph page

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_asset_condition.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_on_cron_condition.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_result_value_hash.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_updated_since_cron_condition.py
Two things:
This subtly changes the definition of the `eager()` condition to deal with a particular annoying case. Essentially, imagine you have assets A -> B -> C, each with an eager policy, and starting off missing.
On the first tick, all assets are detected as missing, and so a run is created targeting all of them. Now, this run progresses, and A is materialized.
At this point in time, if we evaluate `B`, we will notice that `A` has now been newly updated, which would then result in `B` being materialized again (similar things would happen for `C`).
In the AMP world, this is handled by fundamentally redefining the "parent updated" condition to ignore cases where the child will be materialized in the same run. While the same thing could be done here, I would argue that this pollutes the …
=> [DA] Update eager condition

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_partition_backfill.py, python_modules/dagster/dagster/_core/definitions/asset_daemon_context.py, python_modules/dagster/dagster/_core/execution/asset_backfill.py, python_modules/dagster/dagster/_core/execution/backfill.py, python_modules/dagster/dagster/_core/execution/submit_asset_runs.py, python_modules/dagster/dagster/_daemon/backfill.py, python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py, python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill_with_backfill_policies.py, python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py
Summary:
This replaces the retry logic in asset backfills from being code-server/agent faiure-specific to cover more classes of failures. It now works more like AMP retry logic, where the sequence of events is;
a) generate a candidate set of runs to launch, reserve run IDs for them, update the backfill data with those run IDs
b) launch each run one by one, at each step making sure that no run with that ID has previously been launched
c) once you're done, write that you're finished and are ready to move on
This guarantees idempotency because we're resilient to failures at any stage in the above:
- If we fail before the write in a), no writes have been done, so we're good and can start over
- If we fail partway through b), we have persisted which runs we want to launch, so we can check if …
=> Refactor asset backfill retry behavior to cover more classes of failures

python_modules/dagster/dagster/_core/execution/asset_backfill.py, python_modules/dagster/dagster/_core/execution/submit_asset_runs.py, python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py
Summary:
Followup from https://github.com/dagster-io/dagster/pull/22538 - which expands our retry behavior, but loses a nice property where if there was an error in the middle of a 25 run chunk, we would still correctly update the list of requested partitions (of course this wouldn't happen if there was a hard crash, but in a more 'expected' error like a user code server being down or an agent being unavailable, it's nice to keep the list of requested partitions up to date)
This PR brings back that behavior by simplifying the chunking behavior / removing submit_asset_runs_in_chunks entirely - instead, we check hte number of runs that have been submitted and update the written backfill every 25 runs. If there's an error, we do that write as well before re-raising the exception so that the …
=> Checkpoint requested_subset before re-raising when there is an error in the middle of an asset backfill

python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
Summary:e
Any time we do a requests call, it should have a timeout, or it can hang if the server is misbehaving: https://requests.readthedocs.io/en/latest/user/advanced/#timeouts
Test Plan: Bk
=> Add a timeout to fivetran connector requests call

python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster/_core/definitions/repository_definition/repository_data_builder.py, python_modules/dagster/dagster/_core/definitions/schedule_definition.py, python_modules/dagster/dagster/_core/definitions/sensor_definition.py, python_modules/dagster/dagster/_core/definitions/target.py, python_modules/dagster/dagster/_core/remote_representation/external_data.py
Refactor/clean up of schedule/sensor "target" abstractions.
- Consolidate `DirectTarget` and `RepoRelativeTarget` into a new `AutomationTarget` class. Existing names were inaccurate name since unresolved asset job defs are also repo-relative but were stored as `DirectTarget` instead of `RepoRelativeTarget`. The new class stores a `job_resolvable` (a job def, graph def, or job name) and an optional op selection. It exposes  `executable_def` and `has_executable_def` properties. Note that upstack we convert these into `job_def` and `has_job_def` respectively. `AutomationTarget` is also what the `target` parameter added upstack is resolved into.
- Delete methods on schedules/sensors around "loading" targets. These methods didn't actually load anything, they just returned the underlying …
=> target refactor

python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster/_core/definitions/repository_definition/repository_data_builder.py, python_modules/dagster/dagster/_core/definitions/schedule_definition.py, python_modules/dagster/dagster/_core/definitions/sensor_definition.py, python_modules/dagster/dagster/_core/definitions/target.py, python_modules/dagster/dagster_tests/definitions_tests/test_repository_definition.py, python_modules/dagster/dagster_tests/definitions_tests/test_schedule.py, python_modules/dagster/dagster_tests/definitions_tests/test_sensor.py
Update `{Sensor,Schedule}Definition` to no longer store a provided `GraphDefinition` directly as their target. Instead we convert to a `JobDefinition` immediately. This enables us to simplify the underlying `AutomationTarget` abstraction, which now holds either a `Union[JobDefinition, UnresolvedAssetJobDefinition]` instead of a `Union[JobDefinition, UnresolvedAssetJobDefinition, GraphDefinition]`. Methods on `AutomationTarget` referencing `executable_def` are correspondingly renamed to their `job_def` equivalent.
There are three behavior changes here:
- Provision of a `GraphDefinition` to a `{Schedule,Sensor}Definition` is now deprecated. The user receives a warning message.
- The error message when there is a naming collision between a provided graph and a job to a definitions object is …
=> Remove GraphDefinition from target

python_modules/dagster/dagster/_core/definitions/asset_graph.py, python_modules/dagster/dagster/_core/remote_representation/external_data.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py
Another step on my slow crusade to transition from `AssetsDefinition` to `AssetGraph` in our internals.
=> remove AssetsDefinitions from external_data.py

docs/content/deployment/guides/kubernetes/deploying-with-helm.mdx, examples/docs_snippets/docs_snippets/deploying/kubernetes/user_code_deployment_config.yaml
While customizing the env vars for my codelocations I found the following small discrepancy within the docs. If you put secrets in the format the docs suggest, you get the following error.
```bash
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
dagster:
- dagster-user-deployments.deployments.1.envSecrets.0: Invalid type. Expected: object, given: string
```
This is the change I had to make to get my helm chart to work. Validated by looking at the helm chart to see the actual implementation of the template [vars](https://github.com/dagster-io/dagster/blob/master/helm/dagster/charts/dagster-user-deployments/templates/deployment-user.yaml#L84-L87). The helm chart injects the yaml objects, not just the strings. Hence they need to be …
=> [docs] user deployment env config doc fix

python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py, python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py, python_modules/dagster/dagster/_core/definitions/decorators/decorator_assets_definition_builder.py, python_modules/dagster/dagster/_core/definitions/decorators/source_asset_decorator.py, python_modules/dagster/dagster/_core/definitions/external_asset.py, python_modules/dagster/dagster/_core/remote_representation/external_data.py, python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py
This gets rid of the SYSTEM_METADATA_KEY_ASSET_EXECUTION_TYPE metadata value (except for backcompat) and instead introduces an `execution_type` field on `AssetGraphComputation`.
=> AssetGraphComputation.execution_type

python_modules/dagster/dagster/_core/definitions/asset_layer.py, python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/dependency.py, python_modules/dagster/dagster/_core/definitions/graph_definition.py, python_modules/dagster/dagster/_core/definitions/job_definition.py, python_modules/dagster/dagster/_core/definitions/node_definition.py, python_modules/dagster/dagster/_core/definitions/op_definition.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_job.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py
For graph-backed multi-assets, depending on the asset selection, we sometimes only execute a subset of the ops and expect them to only produce a subset of their outputs.
This PR changes which ops are executed in some of these situations. The goals of this change are four-fold:
- Simplify the logic so that it's easier to understand and reason about (negative LOC, even with new test code).
- Avoid unnecessarily executing ops in some situations.
- Execute ops in some situations they probably should have been executed but were not being executed.
- Make it so that the logic doesn't require looking at asset-level dependencies. This will enable further refactoring of `AssetLayer`.
Op output X will be selected when asset A is selected iff there's at least one path in the graph from X to op …
=> change how we compute `upstream_dep_op_handles` and `downstream_dep_assets`

js_modules/dagster-ui/packages/ui-core/src/partitions/PartitionGraph.tsx
Update Run partitions graph to match graph styles elsewhere:
- Use `useRGBColorsForTheme` to pull colors from theme context, since we need raw `rgb` values for chart.js.
- Update monospace font, axis colors
- Use dataviz blurple for main data display color
View a job with partition runs, verify that the graph lines show up correctly in light and dark modes.
=> [ui] Update Run duration graph on Job Partitions view

js_modules/dagster-ui/packages/ui-core/src/sensors/SensorDetails.tsx
Instead of hiding the "Test sensor" button for sensors that are not `STANDARD` type, disable it and show a tooltip.
View sensors, verify that the button is visible in all cases, and disabled (with tooltip) for sensors that are not `STANDARD`.
=> [ui] Sensors: Disable "Test sensor" button instead of hiding it

docs/content/guides/migrations/migrating-airflow-to-dagster.mdx
- Removes `dagster-airflow` migration strategy
- Introduces "Choose your own adventure" migrations
* Pipelines using Airflow TaskFlow API
* Pipelines using Airflow KubernetesPodOperator
=> [docs] 2/n add airflow migration strategies: TaskFlow, Kubernetes

js_modules/dagster-ui/packages/ui-core/src/instigation/types/InstigationTick.types.ts, js_modules/dagster-ui/packages/ui-core/src/overview/OverviewSensors.tsx, js_modules/dagster-ui/packages/ui-core/src/partitions/types/PartitionRunList.types.ts, js_modules/dagster-ui/packages/ui-core/src/pipelines/types/PipelineRunsRoot.types.ts, js_modules/dagster-ui/packages/ui-core/src/runs/QueuedRunCriteriaDialog.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/QueuedRunCriteriaQuery.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/RunHeaderActions.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/RunTable.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/types/QueuedRunCriteriaQuery.types.ts, js_modules/dagster-ui/packages/ui-core/src/runs/types/RunTable.types.ts, js_modules/dagster-ui/packages/ui-core/src/runs/types/RunsRoot.types.ts, js_modules/dagster-ui/packages/ui-core/src/schedules/types/ScheduleRoot.types.ts, js_modules/dagster-ui/packages/ui-core/src/sensors/types/SensorPreviousRuns.types.ts, js_modules/dagster-ui/packages/ui-core/src/ui/SectionedLeftNav.tsx
Add "View queue criteria" to the overflow menu on the Run detail page header. This reuses the existing dialog from the Runs page, with a bit of refactoring:
- Strip down what the dialog requires from the `Run` object
- Query for the values needed for the dialog, which allows us to reuse the component without needing the exact same fragment object in both places.
- More context for the loading state
- An empty state when the dialog query fails
Overflow menu item:
Loading state:
Error state:
Queue some runs, verify that the dialog works from the Runs page and from the Run detail header.
Verify that the menu item is not present in the run is not queued.
=> [ui] Show run queue criteria on Run page header

js_modules/dagster-ui/packages/ui-core/src/runs/LogsProvider.tsx
Summary:
This matches the new default in the websocket case.
Test Plan: BK
=> Change default websocket-less event log batch size to 1000

docs/content/dagster-plus/managing-deployments/alerts.mdx
This type of alert is now available on all Dagster+ plans, as per [this Slack thread](https://dagsterlabs.slack.com/archives/C05K25X1KN1/p1719337936481989)
👀
=> [docs] Remove Dagster+ Pro requirement for Insights metric alerts

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/implementation/fetch_instigators.py, python_modules/dagster-graphql/dagster_graphql/schema/external.py, python_modules/dagster-graphql/dagster_graphql/schema/instigation.py, python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py, python_modules/dagster-graphql/dagster_graphql/schema/schedules/schedules.py, python_modules/dagster-graphql/dagster_graphql/schema/sensors.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_instigation.py, python_modules/dagster/dagster/_core/remote_representation/external.py, python_modules/dagster/dagster/_core/storage/schedules/sql_schedule_storage.py
* add `CompoundID` to wrap external origin + selector id components 
* change the `Schedule` `Sensor` and `Repository` id fields to return serialized CompoundIDs 
* update the `instigationStateOrError` to be able to fetch by id
* add `instigationStatesOrError` and support fetching all instigation states by their containing repository ID
Added tests
=> [graphql] instigation state by id

js_modules/dagster-ui/packages/ui-core/src/assets/PartitionHealthSummary.tsx
Looks like something changed on the backend and the __typename field isn't first in the object anymore. Instead lets compare the paths.
app-proxy
=> Compare asset key paths instead of comparing the entire asset key object

python_modules/libraries/dagster-dbt/dagster_dbt/cli/app.py, python_modules/libraries/dagster-dbt/dagster_dbt/include/scaffold/assets.py.jinja, python_modules/libraries/dagster-dbt/dagster_dbt/include/scaffold/definitions.py.jinja, python_modules/libraries/dagster-dbt/dagster_dbt/include/setup.py.jinja, python_modules/libraries/dagster-dbt/dagster_dbt_tests/cli/test_prepare_and_package.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/cli/test_scaffold.py
This PR renames the `--use-experimental-dbt-project` flag to `--use-dbt-project` in the dbt scaffold CLI, now that [DbtProject is no more experimental](https://github.com/dagster-io/dagster/pull/22578). 
This is the first step in making DbtProject the default and only strategy when scaffolding a dbt project. The goal is to facilitate the transition from the previous default strategy to that of DbtProject in our tutorials, courses and docs.
Once this is merged, next steps will be to
- update tutorials, courses and docs to use DbtProject.
- Since our examples heavily rely on the scaffold command, we'll be able to use `dagster-dbt project scaffold --use-dbt-project` with the updated flag
- make the DbtProject strategy the default and only one when using `dagster-dbt project scaffold`
- …
=> [DbtProject] Rename `--use-experimental-dbt-project` flag to `--use-dbt-project` in dbt scaffold CLI

js_modules/dagster-ui/packages/ui-core/src/instance/flattenCodeLocationRows.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/useCodeLocationPageFilters.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/CodeLocationRowSet.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/RepositoryLocationsList.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedCodeLocationRow.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceQueries.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/types/WorkspaceQueries.types.ts
Each code location has a status representation and full entry representation with all the definitions. We poll the small cheap status frequently and when changes are detected update the large entries. 
This PR brings this modeling to the code locations table by explicitly passing down status and entry objects. 
viewed and refreshed locations loading dagster dev at repo root
=> [ui] update code locations table to source from status and entries

python_modules/dagster/dagster/_core/remote_representation/grpc_server_registry.py, python_modules/dagster/dagster/_core/remote_representation/origin.py, python_modules/dagster/dagster/_core/workspace/context.py, python_modules/dagster/dagster/_daemon/controller.py, python_modules/dagster/dagster/_grpc/proxy_server.py, python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_grpc_server_registry.py
Summary:
This is now always set to 0 outside of tests.
Test Plan: BK
=> Remove unused GrpcServerRegistry.reload_interval parameter

python_modules/dagster-graphql/dagster_graphql/cli.py, python_modules/dagster-graphql/dagster_graphql_tests/test_cli.py
Summary:
This prevents queries from failing if they use the new async resolvers
Test Plan:
Existing dagster-graphql test suite
=> Use asyncio in dagster-graphql cli

python_modules/dagster/dagster/_utils/warnings.py, python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py, python_modules/dagster/dagster_tests/definitions_tests/test_schedule.py, python_modules/dagster/dagster_tests/definitions_tests/test_sensor.py
Limit nesting of manipulation of the `_warnings_on` context variable to one level. The motivation here is that, in certain niche cases (in particular observed in pytest), nested `finally` resets of the token sometimes occur out-of-order, which leads to the `_warnings_on` context variable being "permanently" reset to `False`. By avoiding this nesting, we can avoid this bug (whether it's a problem in python, pytest, or our own code, which is unclear).
This also re-enables the skipped assertions that surfaced this bug before.
Pushed this 5 times and did not observe previous inconsistently failing tests to fail.
=> Fix warnings

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
Adds the missing `owners` argument to `graph_asset` overload. Find myself having to ignore the line in mypy quite frequently.
=> add owners arg to `graph_asset` overload

js_modules/dagster-ui/packages/ui-core/src/insights/InsightsBarChart.tsx
Not sure why this is set to UTC as the timezone, but that's wrong.
View per-event asset insights, verify that timestamp labels on the x axis and tooltip are correct for my timezone.
=> [ui] Don't use UTC in per-event bar chart times

python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/dbt_packages/test_columns_metadata.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_metadata/models/sources.yml, python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_metadata/profiles.yml
Runs a test of our deferred fetch of column metadata/lineage on an actual Snowflake instance as part of the nightly build, to ensure that we support other warehouses properly.
Will do the same for BQ in follow-up, but the metadata project as written doesn't run directly on BQ right now.
https://buildkite.com/dagster/full-moon-with-face-dagster-nightly/builds/53
=> Add nightly Snowflake column lineage test

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py
- Consolidate the column lineage metadata logic together in a single conditional with a try/except similar to https://github.com/dagster-io/dagster/pull/22641.
- Divest from using the quoted `relation_name`, and just use the `database`, `schema`, `name`.
- Apply https://github.com/dagster-io/dagster/pull/22642 when building the column lineage.
This should probably be under nightly test against a real bigquery instance.
Locally, things work now.
Materializing with `.fetch_column_metadata()` resulted in:
```
dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "jaffle_shop_dbt_assets":
The above exception was caused by the following exception:
google.api_core.exceptions.BadRequest: 400 GET https://bigquery.googleapis.com/bigquery/v2/projects/%60dagster-c …
```
=> fix(dbt): divest from the quoted `relation_name` when building column lineage

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_metadata/dbt_project.yml, python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_metadata/models/schema.yml
When creating the `BaseRelation`, we want to use the name of the table that's created in the data warehouse so that we can properly query the relation.
Previously, we were using `dbt_resource_props["name"]` as the identifier, which is the dbt's reference to that table. Instead, we should use the underlying identifier name.
For dbt sources, this is `dbt_resource_props["identifier"]`. For dbt models and seeds, this is `dbt_resource_props["alias"]`.
pytest: added dbt aliases for source and model in existing `test_dagster_metadata` project
=> fix(dbt): use correct relation identifier when creating `BaseRelation`

js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/AssetTables.test.tsx, js_modules/dagster-ui/packages/ui-core/src/nav/__tests__/LeftNavRepositorySection.test.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/__tests__/RunFilterInput.test.tsx, js_modules/dagster-ui/packages/ui-core/src/testing/mocking.ts, js_modules/dagster-ui/packages/ui-core/src/ui/Filters/__tests__/FilterDropdown.test.tsx
Just added a 5th test file that needed this code, figured I'd move it to a shared helper. The shape of the function is a bit different than other mocks but I think that's required for this particular case.
Tests still pass
=> [ui] Move mocks for viewportClientRect to mocking utils

python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py, python_modules/dagster/dagster/_core/definitions/data_time.py, python_modules/dagster/dagster/_core/scheduler/instigation.py, python_modules/dagster/dagster/_core/storage/asset_check_execution_record.py, python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py, python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py, python_modules/dagster/dagster/_utils/__init__.py, python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
Summary:
This brings run records in OSS in line with run records that are returned over our API in that it has non-naive datetimes - UTC datetimes are strictly better than naive datetimes. It also allows us to remove this datetime_as_float utiliyt method which was designed as a way to reliably handle these naive datetimes coming out of sqlite - my claim is that the new syntax that I have replaced it with (utc_datetime_from_naive(...).timestamp()) is much clearer about what is going on.
Somewhat unfortunate that the field on RunRecord is "update_timestamp" and not "update_time", but that would be a breaking change.
=> Make run record datetime fields in UTC instead of naive datetimes, remove datetime_as_float

js_modules/dagster-ui/packages/ui-core/src/partitions/BackfillSelector.tsx, js_modules/dagster-ui/packages/ui-core/src/partitions/OpJobPartitionsView.tsx, js_modules/dagster-ui/packages/ui-core/src/partitions/PartitionGraph.tsx, js_modules/dagster-ui/packages/ui-core/src/partitions/__tests__/OpJobPartitionsViewContent.test.tsx
A user reported internal inconsistencies on the op job partitions page here: https://linear.app/dagster-labs/issue/FE-411/reporting-an-issue-with-the-backfill-launcher-ui-not-consistently
There are a few things going on:
- This page never updates the overall partition status bar after page load
- This page DOES update the run+step statuses, but only in the selected range
- This page DOES update the backfill status shown at the very bottom of the page in the table
This means that if a backfill is running, it's easy to get this page into a state where it's reporting different information in different places, especially the top bar. This is bad because it doesn't even refresh when you click "Launch backfill", and causes the UI elements in the modal (eg: failed checkbox) to behave …
=> [ui] Provide an explicit Refresh button to update op partition status FE-411

js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/types/AutomaterializeRunsTable.types.ts, js_modules/dagster-ui/packages/ui-core/src/gantt/types/RunGroupPanel.types.ts, js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, js_modules/dagster-ui/packages/ui-core/src/instigation/types/InstigationTick.types.ts, js_modules/dagster-ui/packages/ui-core/src/instigation/types/InstigationUtils.types.ts, js_modules/dagster-ui/packages/ui-core/src/nav/types/JobMetadata.types.ts, js_modules/dagster-ui/packages/ui-core/src/nav/types/LatestRunTag.types.ts, js_modules/dagster-ui/packages/ui-core/src/partitions/types/PartitionRunList.types.ts, js_modules/dagster-ui/packages/ui-core/src/pipelines/types/PipelineRunsRoot.types.ts, js_modules/dagster-ui/packages/ui-core/src/runs/RunUtils.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/__stories__/RunStatusPez.stories.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/types/RunTable.types.ts, js_modules/dagster-ui/packages/ui-core/src/runs/types/RunUtils.types.ts, js_modules/dagster-ui/packages/ui-core/src/runs/types/RunsRoot.types.ts, js_modules/dagster-ui/packages/ui-core/src/runs/types/useRunsForTimeline.types.ts, js_modules/dagster-ui/packages/ui-core/src/schedules/types/ScheduleRoot.types.ts, js_modules/dagster-ui/packages/ui-core/src/schedules/types/ScheduleUtils.types.ts, js_modules/dagster-ui/packages/ui-core/src/sensors/types/SensorFragment.types.ts, js_modules/dagster-ui/packages/ui-core/src/sensors/types/SensorPreviousRuns.types.ts, js_modules/dagster-ui/packages/ui-core/src/sensors/types/SensorRoot.types.ts, js_modules/dagster-ui/packages/ui-core/src/testing/generateRunMocks.ts, js_modules/dagster-ui/packages/ui-core/src/workspace/types/VirtualizedJobRow.types.ts, js_modules/dagster-ui/packages/ui-core/src/workspace/types/VirtualizedScheduleRow.types.ts, js_modules/dagster-ui/packages/ui-core/src/workspace/types/VirtualizedSensorRow.types.ts, python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
A recent user inquiry about the sorting of runs in the backfill runs table
(https://dagsterlabs.slack.com/archives/C064933ANQL/p1719328567183329) led to the discovery that what is listed as the "Create date" in the runs table UI is not actually the "Create time" of the underlying run record, but rather the `start_time` (when the run was launched) if it was defined, or if not the `update_time`.
This is both inaccurate and also causes the sorting in the table to be inscrutable in some cases, where there is a subtle deviation from sorting by "Created date".
This PR updates the UI to use the run record `creation_time` instead of `start_time` or `updated_time`. `creation_time` is always defined since it is set on record creation. This change both fixes the inaccuracy on the runs page and …
=> [bugfix] Show actual creation timestamp instead of `start_time` in runs table

python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
`GrapheneRun._get_run_record` is not necessary because `GrapheneRun` is always constructed with a `RunRecord`.
=> Eliminate GrapheneRun._get_run_record()

python_modules/dagster/dagster/_core/definitions/metadata/source_code.py, python_modules/dagster/dagster_tests/asset_defs_tests/asset_package/module_with_assets.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_defs_source_metadata.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_assets_from_modules.py
Avoids trying to attach code references automatically to graph-backed assets, which previously errored. Puts that case under test. Subsequent PR will actually properly attach a reference to the underlying graph to the asset metadata.
New test case.
=> [fix] fix err when trying to attach code references to graph-backed assets

python_modules/dagster/dagster/_core/definitions/decorators/graph_decorator.py, python_modules/dagster/dagster/_core/definitions/graph_definition.py, python_modules/dagster/dagster/_core/definitions/metadata/source_code.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_defs_source_metadata.py
Threads through the underlying fn which backs a graph-backed asset, which generated code references will point to.
For example:
```python
@op
def one():
return 1
@op
def multiply_by_two(input_num):
return input_num * 2
@graph_asset
def graph_backed_asset():
return multiply_by_two(one())
with_source_code_references([graph_backed_asset])
```
Unit test.
=> Properly attach code references to graph-backed assets

js_modules/dagster-ui/packages/ui-core/src/assets/LaunchAssetChoosePartitionsDialog.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/InstanceBackfills.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillPage.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillPartitionsTab.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillRunsTab.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/ExecutionTimeline.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/__tests__/BackfillPage.test.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/types/InstanceBackfills.types.ts, js_modules/dagster-ui/packages/ui-core/src/overview/OverviewTimelineRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/partitions/BackfillMessaging.tsx, js_modules/dagster-ui/packages/ui-core/src/partitions/BackfillSelector.tsx, js_modules/dagster-ui/packages/ui-core/src/partitions/types/BackfillMessaging.types.ts, js_modules/dagster-ui/packages/ui-core/src/runs/RunTimeline.tsx
This PR refines the backfill details page based on user feedback:
- The “duration” shown on the page ticks every second instead of every 60s if the backfill is in progress
- The detail page shows the “backfill daemon is not running” notice if needed, which makes it more obvious why the page may not be showing anything. (I also refactored the backfill list page to use a newer mechanism for fetching this info)
- The runs timeline / list no longer have a double scrollbar and their refresh button is visible in the tab bar.
- The timeline view defaults to a 1 hour time window instead of 12h
- The RunTable and timeline no longer suggest that you materialize or launch runs in the empty state, and the timeline empty state says “no runs /were executing/“, making it more obvious that the timeline …
=> [ui] Improvements to the backfill detail page + logs UI FE-406

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/__init__.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/code_version_changed_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/slice_conditions.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_code_version_changed_condition.py
Resolves a long-standing request to allow our asset automation system to respond to code version changes. Implementation is quite simple, it just detects when the code version has changed since the previous ticks.
All "memory" (required to keep track of cases where we're not able to immediately request a materialization in response to this stimulus) is delegated to the `since()` condition, leaving this implementation pretty clean.
=> [DA] add code_version_changed AutomationCondition

docs/content/_navigation.json, docs/content/guides/migrations/migrating-airflow-to-dagster.mdx, docs/content/guides/migrations/observe-your-airflow-pipelines-with-dagster.mdx, docs/content/integrations/airflow.mdx
[DRAFT]
- Adds tutorial on coexisting Airflow and Dagster through the emission of events from Airflow to Dagster -- allowing Dagster to act as the single pane of glass for all orchestration in an organization
=> [docs] 4/n dagster as single-pane-of-glass for organization workflows

python_modules/dagster/dagster/_record/__init__.py, python_modules/dagster/dagster/_serdes/serdes.py, python_modules/dagster/dagster_tests/general_tests/test_serdes.py
`__annotations__` will get set in subclasses, so use a different field. Also update some names from model to record
added test
=> [serdes] handle record subclasses

python_modules/dagster/dagster/_core/definitions/graph_definition.py, python_modules/dagster/dagster/_core/definitions/op_definition.py
This `TypeVar` is unused in `graph_definition.py` and has no effect in `op_definition.py`.
=> remove vestigial T_Handle

python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster_tests/storage_tests/test_input_manager.py
Resolves: https://github.com/dagster-io/dagster/issues/22789
Fixes issue which I believe was introduced by: https://github.com/dagster-io/dagster/issues/22165 (didn't dig that hard)
The core problem is this conversion: https://sourcegraph.com/github.com/dagster-io/dagster/-/blob/python_modules/dagster/dagster/_core/definitions/external_asset.py?L176
`observable_source_asset` does not set metadata on the `OutputDefinition` of its internal op. So when we initially convert a SourceAsset into an ol' fashioned `AssetsDefinition`, then call `to_source_assets()` on that, we end up losing the metadata field, as we were trying to pull it off of the `OutputDefinition`. This PR just pulls it off of the spec instead.
Added test fails before, passes now.
=> [bug] Fix issue where metadata got discarded in SourceAsset conversion

js_modules/dagster-ui/packages/ui-core/src/asset-graph/__fixtures__/AssetNode.fixtures.ts, js_modules/dagster-ui/packages/ui-core/src/assets/ChangedReasons.tsx, js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster/dagster/_core/definitions/asset_graph_differ.py, python_modules/dagster/dagster_tests/general_tests/asset_graph_differ_tests/asset_graph_scenarios/basic_asset_graph/branch_deployment_removed_asset.py, python_modules/dagster/dagster_tests/general_tests/asset_graph_differ_tests/test_asset_graph_differ.py
Allows the asset graph differ to mark an asset as removed in the case that an asset is present in the base branch but not the comparison branch.
In the branch deploymenet case this is currently not used, but is helpful to make the asset differ useful in other use-cases (e.g. tracking change history on a prod branch).
New unit test.
=> [asset differ] add "asset removed" change reason

.pre-commit-config.yaml, Makefile, pyproject.toml, python_modules/dagster/dagster/_core/definitions/op_invocation.py, python_modules/dagster/dagster/_core/definitions/repository_definition/repository_data_builder.py, python_modules/dagster/dagster/_core/workspace/load.py, python_modules/dagster/dagster_tests/core_tests/resource_tests/pythonic_resources/test_lifecycle_methods.py, python_modules/dagster/setup.py, python_modules/libraries/dagster-snowflake/dagster_snowflake_tests/test_resources.py, python_modules/libraries/dagstermill/dagstermill_tests/test_ops.py
Internal companion PR: https://github.com/dagster-io/internal/pull/10447
Bump ruff from 0.4.5 -> 0.5.1.
Some minor lint fixes due to rule updates.
=> [ruff] 0.4.5 -> 0.5.1

python_modules/dagster/dagster/_record/__init__.py, python_modules/dagster/dagster_tests/model_tests/test_dagster_model.py
Bumped in to this in https://github.com/dagster-io/dagster/pull/22855, its confusing (and breaks default resolution) to have record fields conflict with methods so defend against it.
added test
=> [record] defend against problematic collisions

js_modules/dagster-ui/packages/ui-core/src/app/AppProvider.tsx
Add an idempotency-key header to graphql operations. [[slack link for context](https://dagsterlabs.slack.com/archives/C03CCE471E0/p1720452388539319?thread_ts=1718990436.195549&cid=C03CCE471E0)]
Made sure the original operation and the retry of the operation shared the same idempotency-key.
=> Add idempotency-key header to graphql operations

docs/content/_navigation.json, docs/content/dagster-plus/managing-deployments/alerts.mdx, docs/content/dagster-plus/managing-deployments/setting-environment-variables-agents.mdx
This PR cleans up a few mentions of `dagster-plus` in the docs where it should be `dagster-cloud`, which came about as a result of stepping back from the product rename. **Note**: I'm opting not to rename URLs, as this will introduce more redirects and link updates that could break things.
=> [docs] - Clean up dagster-plus/dagster-cloud rename (DOC-272)

js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetLiveDataProvider.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-data/__tests__/AssetLiveDataProvider.test.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-data/util.ts, js_modules/dagster-ui/packages/ui-core/src/assets/AssetMetadata.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeInstigatorTag.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeOverview.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/useLatestPartitionEvents.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/useReportEventsModal.tsx, js_modules/dagster-ui/packages/ui-core/src/hooks/__tests__/usePredicateChangeSignal.test.tsx, js_modules/dagster-ui/packages/ui-core/src/hooks/usePredicateChangeSignal.tsx, js_modules/dagster-ui/packages/ui-core/src/live-data-provider/LiveDataThread.tsx, js_modules/dagster-ui/packages/ui-core/src/live-data-provider/util.ts, js_modules/dagster-ui/packages/ui-core/src/nav/useRepositoryLocationForAddress.ts
Fix a bunch of request waterfalls in the Asset Overview page.
1. Stop gating the overview tab on the definition loading, instead allow the overview tab to handle a null definition (indicating it is loading)
2. Allow a few utilities to take handle `null` / `undefined` while the assetNode is loading.
3. If available, use the all assets cache to figure out if an asset is partitioned to avoid waterfall for events query
4. Fix an issue where the ReportEvents dialog was querying for all partitions as soon as you loaded the page even if you the dialog wasn't open.
5. Increased the default number of parallel live data threads from 1 to 2 (to avoid waterfall on loading the main assets live data and its neighboring asset's live data which comes in after via the indexeddb cache or via …
=> [perf] Fix request waterfalls in asset overview

python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/resolved_asset_deps.py, python_modules/dagster/dagster/_core/selector/subset_selector.py
Now that specs are the source of truth on an `AssetsDefinition`'s dependencies, the `asset_deps` property is a derived property that's O(N) to compute, instead of its previous constant time.
This is a source of performance regressions: https://github.com/dagster-io/dagster/issues/22709.
This PR avoids using this property in favor of directly getting dependencies from the asset specs, which is a constant time operation.
=> avoid internal use of AssetsDefinition.asset_deps

python_modules/dagster/dagster/_core/definitions/assets.py
Now that specs are the source of truth on an AssetsDefinition's dependencies, the asset_deps property is a derived property that's O(N) to compute, instead of its previous constant time.
This is a source of performance regressions: https://github.com/dagster-io/dagster/issues/22709.
While https://github.com/dagster-io/dagster/pull/22874 moves away from using it internally, users could still be expecting constant time behavior.
More background here: https://github.com/dagster-io/dagster/pull/22874#pullrequestreview-2163916957
=> make AssetsDefinition.asset_deps a cached_property

python_modules/dagster/dagster/_core/definitions/asset_graph_differ.py
Lets us serialize a changereason enum value, for storing historical changes
=> [asset differ] allow serialization of ChangeReason

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
Move the `@experiemental` marker from the base class to the functions that we expect to make up the user facing API 
https://github.com/dagster-io/dagster/pull/22481#discussion_r1667091227
bk
=> [DA] move @experimental to constructor fns

docs/content/integrations/dbt/quickstart.mdx
This PR fixes some typos and formatting in the Dagster & dbt quickstart, including:
- Add headings to subsections to make them easy to find + linkable
- Put sections for different options into tabs
- Add a **Related** section with relevant links
- Update H2 headings to include `Step`, which matches our other guides
👀
=> [docs] - Update dbt quickstart

python_modules/dagster/dagster/_serdes/serdes.py, python_modules/dagster/dagster_tests/general_tests/test_serdes.py
Support using kwargs in constructors for `@record` serdes objects by adding a new `whitelist_for_serdes` argument `kwargs_fields` to capture what fields should still get handled by serdes from the kwargs bundle.
added tests
=> [serdes] add kwargs handling

python_modules/dagster/dagster/_core/execution/plan/compute_generator.py
This is part of the general project of removing `AssetsDefinition` from internals where it's not needed.
=> remove assets_def from _filter_expected_output_defs

python_modules/dagster/dagster/_utils/caching_instance_queryer.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_newly_updated_condition.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenario_specs.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenario_state.py
Resolves: https://github.com/dagster-io/dagster/issues/22850
The method `get_asset_subset_updated_after_cursor` had a somewhat-misguided pattern which I believe was originally intended as a performance optimization. In essence, for unpartitioned assets, it would simply check for the existence of an event after the provided cursor, rather than going through the more explicit `get_asset_partitions_updated_after_cursor` code path.
However, `get_asset_partitions_updated_after_cursor`:
a) already does that same check, and so is able to short-circuit on its own
b) handles data version changes for observable source assets, which is the focus of this fix
Had to make some updates to the testing framework to properly simulate observable source assets (side comment: this is quite rough at the …
=> [DA] fix observable source asset handling in AutomationCondition.newly_updated

.gitignore
Pulled out from the changes from here: https://github.com/dagster-io/dagster/pull/22718
MLflow creates an "mlruns" directory when the mlflow-integration unit tests are run. This change adds that test dir to the gitignore.
1. Ran the unit tests
2. Saw that the mlruns directory was created
3. Observed that git is ignoring that directory
=> Adding mlflow working dir 'mlruns' to gitignore (#22633)

python_modules/dagster/dagster/_core/definitions/base_asset_graph.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_tester.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/__init__.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/any_downstream_conditions_operator.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_any_downstream_conditions.py
This creates the "`lazy`" AutomationCondition. I have not fully decided on a name, but I felt like this was potentially more descriptive of what it's actually doing.
Handling the weird recursive cases is a bit tricky, hence the odd structure of the tests. Basically if you have:
A: any_downstream_conditions
B: any_downstream_conditions & foo
C: bar
, A->B->C, and you want to evaluate A, the naive approach would result in the following infinite loop behavior:
1. convert any_downstream_conditions to (any_downstream_conditions & foo, bar)
2. this expands to ((any_downstream_conditions & foo, bar) & foo, bar)
3. etc.
The way I avoid this is by not including a condition in the expansion if it's already part of the "call stack". So in this case, in step 2 we would just expand …
=> [DA] Create any_downstream_conditions AutomationCondition

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_asset_condition_evaluations.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_condition_evaluations.py
Resolves: https://github.com/dagster-io/dagster/issues/22787
The new Declarative Automation framework allows conditions which are evaluated against parents of a given asset. Those parents do not necessarily have the same partitions definition as the child.
The current UI was designed with the expectation that all sub-evaluations would reference the same PartitionsDefinition, and so results in errors when we (e.g.) try to construct a`GraphenePartitionedAssetConditionEvaluationNode` from an evaluation that was actually executed against an unpartitioned asset.
We are working on a larger redesign which should help remove this assumption from the core UI model, but for now we can prevent these errors by making it possible to construct a `...PartitionedEvaluationNode` from an unpartitioned …
=> [DA] Fix evaluation history UI

js_modules/dagster-ui/packages/ui-core/src/app/CloudOSSContext.tsx, js_modules/dagster-ui/packages/ui-core/src/app/analytics.tsx
We don't rely on useTrackPageView setting the current page anymore since we landed https://github.com/dagster-io/dagster/pull/21720 so lets remove the call here.
This fixes an issue where useTrackPageView ends up overriding the route set by our wrapped Route components.
Recorded a correct initial_load trace for an asset view route.
=> Remove setCurrentPage call in `useTrackPageView`

azure-pipelines.yml
Summary:
the pydantic 2 test suite is reliably timing out on windows - pydantic 1 appears to be notably faster, it seems more important to run the core suite on windows than test every permutation of pydantic dependencies.
Test Plan: BK,azure
=> remove pydantic 2 tests from windows

python_modules/dagster-graphql/dagster_graphql/schema/instigation.py, python_modules/dagster/dagster/__init__.py, python_modules/dagster/dagster/_core/definitions/__init__.py, python_modules/dagster/dagster/_core/definitions/dynamic_partitions_request.py, python_modules/dagster/dagster/_core/definitions/partition.py, python_modules/dagster/dagster/_core/definitions/run_request.py, python_modules/dagster/dagster/_core/definitions/sensor_definition.py, python_modules/dagster/dagster/_daemon/sensor.py
adding an import of `AssetGraphSubset` to `run_request.py` caused a circular import. This moves `AddDynamicPartitionsRequest` and  `DeleteDynamicPartitionsRequest` to a new module to break the circle.
=> move dynamic partitions add/delete requests to new module

python_modules/dagster/dagster/_serdes/serdes.py
I missed this when i reviewed https://github.com/dagster-io/dagster/pull/22881 but `kwargs_fields` was only added to `_whitelist_for_serdes` but not `whitelist_for_serdes`
=> whitelist_for_serdes kwargs_fields

python_modules/dagster/dagster_tests/general_tests/test_record.py, python_modules/dagster/dagster_tests/model_tests/test_dagster_model.py
`@record` started here to ensure parity with `DagsterModel` but now we should split it out to its own folder/file
bk
=> [refactor] split DagsterModel and @record tests

python_modules/dagster/dagster/_serdes/serdes.py
i goofed and forgot another spot for  `kwargs_fields`
=> kwargs_fields in whitelist_for_serdes overload

docs/dagster-university/yarn.lock
Just one dependabot alert in daggy u, fix it.
`yarn why ip`
=> [daggy u] Eliminate dependabot alert

python_modules/dagster/dagster/_core/definitions/asset_check_spec.py, python_modules/dagster/dagster/_core/definitions/asset_key.py, python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
This makes it easier to avoid circular imports
=> move AssetKeyOrCheckKey and AssetCheckKey to asset_key.py

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py, python_modules/dagster/dagster/_core/definitions/asset_out.py, python_modules/dagster/dagster/_core/definitions/asset_spec.py, python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/auto_materialize_policy.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/rule_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py, python_modules/dagster/dagster/_core/definitions/utils.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_decorators.py, python_modules/dagster/dagster_tests/cli_tests/command_tests/test_telemetry.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenario_state.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenarios/multi_code_location_scenarios.py, python_modules/dagster/dagster_tests/definitions_tests/test_asset_spec.py, python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/dlt_tests/test_dlt.py
As title. Backwards compatibility will be retained throughout this stack (i.e. you'll still be able to pass in auto_materialize_policy everywhere), but I'm refactoring the internals to accept (and primarily work in terms of) AutomationConditions.
=> [DA-Internals][1/n] Add automation_condition to AssetSpec

python_modules/dagster/dagster/_core/definitions/multi_asset_sensor_definition.py
The last vestige of framework calls to `get_event_records`.
BK
=> switch get_event_records => fetch_materializations for multi asset sensors

python_modules/dagster/dagster/_core/definitions/asset_checks.py, python_modules/dagster/dagster/_core/definitions/assets.py
As title. Here, we immediately convert input AutoMaterializePolicy objects to AutomationConditions.
=> [DA-Internals][2/n] AssetsDefinition updates

js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx
I'm not really sure what the original code was trying to do, it seems to have morphed a bit over the years. I believe just filtering by prefixPath is all we need to do here so removing all of the extraneous logic. It's totally possible I'm missing something but from my testing this works the same.
Loaded an asset catalog with 100k assets and saw that loading a folder view in that catalog didn't cause the page to hang. Also confirmed that the assets displayed for that folder were correct.
=> [perf] Remove n^2 logic in asset catalog

js_modules/dagster-ui/packages/ui-core/src/runs/CellTruncationProvider.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/LogsRow.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/LogsRowComponents.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/LogsScrollingTable.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/LogsScrollingTableHeader.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/LogsScrollingTableNew.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/Run.tsx
Use `@tanstack/react-virtual` for the logs scrolling table instead of `react-virtualized`. If I've done this correctly and haven't overlooked any features, the implementation of this component is now *much* simpler.
This was prompted by wanting to add some empty stats for cases where the filter settings yield no results, which was surprisingly difficult and buggy with our `react-virtualized` implementation. It should be much simpler with `@tanstack/react-virtual`.
There are only a couple of `react-virtualized` callsites left in the codebase.
We'll want to stress test this quite a bit just to make sure it doesn't introduce unexpected bugs.
View an existing run, verify that the virtualized scroll works correctly in the log table. Verify that:
- Filtering behaves correctly.
- Highlighting …
=> [ui] Use newer virtualizer for logs scrolling table

js_modules/dagster-ui/packages/ui-core/src/app/AppTopNav/AppTopNavLinks.tsx, js_modules/dagster-ui/packages/ui-core/src/app/AppTopNav/activePathMatchers.tsx, js_modules/dagster-ui/packages/ui-core/src/app/ContentRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/settings/SettingsLeftPane.tsx, js_modules/dagster-ui/packages/ui-core/src/settings/SettingsMainPane.tsx
For the IA flag, rename "Settings" to "Deployment". This includes changing `/settings` routes to `/deployment`.
There is a corresponding internal change as well.
Inside and outside IA feature flag, verify correct rendering and behavior of the top nav item and all routes and pages within that section of the app.
=> [ui] IA: Settings -> Deployment

examples/experimental/dagster-blueprints/dagster_blueprints/blueprint_assets_definition.py, python_modules/dagster/dagster/_core/definitions/asset_check_factories/utils.py, python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_last_update_freshness.py, python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_time_partition_freshness.py
Makes code less verbose and opens the path towards passing it collections that mix `AssetKey`s and `AssetCheckKey`s.
=> make unique_id_from_asset_and_check_keys operate on single collection

python_modules/dagster/dagster/_check/__init__.py, python_modules/dagster/dagster/_check/builder.py, python_modules/dagster/dagster/_core/test_utils.py, python_modules/dagster/dagster/_record/__init__.py, python_modules/dagster/dagster_tests/general_tests/check_tests/test_check.py, python_modules/dagster/dagster_tests/general_tests/test_record.py
The initial schemes for implicitly resolving ForwardRefs from frame capture are proving to not work out in some cases.
This adds a sure fire way to solve the problem by providing `ImportFrom` to be used with `Annotated` to create a lazy import in the
body of the generated `__new__`.
added tests
=> [record] ImportFrom annotation

python_modules/dagster/dagster/_check/builder.py, python_modules/dagster/dagster_tests/general_tests/check_tests/test_check.py
some typing types do not have `__name__` in 3.8 / 3.9 but they do have `_name` 
updated tests
=> [record] 3.8/3.9 fixes

examples/with_openai/setup.py, examples/with_openai/with_openai/assets.py
Summary:
Resolves a dependabot issue with the old version of langchain we are currently using in this example. Had to add a flag to indicate that the bytes that we are deserializing are from a trusted source (ourselves), but maybe there's a less scary-looking way to accomplish that.
Test Plan: Run example locally
=> Bump up langchain dependencies in with_openai example

examples/experimental/dagster-blueprints/dagster_blueprints/blueprint_assets_definition.py, python_modules/dagster/dagster/_core/definitions/asset_check_factories/utils.py, python_modules/dagster/dagster/_core/definitions/asset_layer.py, python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/execution/plan/execute_step.py, python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_last_update_freshness.py, python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_time_partition_freshness.py
The one place that calls it can get the information from the `AssetGraph` instead.
=> remove AssetLayer.get_spec_for_asset_check

python_modules/dagster/dagster_tests/storage_tests/test_event_log.py
Summary:
[test-all] This test is reliably failing on older sqlalchemy versions, and InMemoryEventLogStorage is only used for unit tests. Keep the branch green.
Test Plan: BK
=> Skip flaky InMemoryTestInMemoryEventLogStorage test on python 3.12 + sqlalchemy 1.4

js_modules/dagster-ui/packages/ui-core/src/assets/AssetTable.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx
The source of the page crash is using `.push(...items)` with an array of over 100k items.
Ticked the checkbox for a folder with over 100k items that would previously cause the page to crash and observe the page no longer crashes.
=> Fix page crash in asset catalog

python_modules/dagster/dagster/_record/__init__.py, python_modules/dagster/dagster/_serdes/serdes.py, python_modules/dagster/dagster_tests/general_tests/test_record.py, python_modules/dagster/dagster_tests/general_tests/test_serdes.py
provide a scheme for records to remap fields to how they are passed to `__new__` . This was motivated by upstack PR to move `TimeWindowPartitionsDefinition` to `@record` 
added tests
=> [record] field_to_new_mapping

python_modules/dagster-webserver/dagster_webserver/graphql.py, python_modules/dagster-webserver/dagster_webserver_tests/test_subscriptions.py
Seen some logs that seem to indicate we might be receiving multiple `START` messages and piling asyncio tasks. Just ignore these duplicate starts for the same operation id.
updated tests that failed before fixes
`dagster dev -f python_modules/dagster-test/dagster_test/toys/log_spew.py`
launch log_spew and monitor web socket in network tab of browser dev tools
=> [graphql] prevent repeated subscription starts

js_modules/dagster-ui/packages/ui-core/src/assets/AssetTable.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetWipeDialog.tsx, js_modules/dagster-ui/packages/ui-core/src/testing/StorybookProvider.tsx
1. Virtualize the AssetWipeDialog so that it doesn't make the page unresponsive
2. Add a container with a max height to make it easier to scroll
3. Show progress via progress bar + loading spinner on wipe button.
Confirmed in network panel that chunking progresses through all assets
Progress indicator
Virtualized list
=> Virtualize, chunk, and show progress in "wipe materializations" dialog 

python_modules/dagster/dagster/_core/definitions/declarative_automation/__init__.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_automation_condition_serdes.py
Because the subclasses of AutomationCondition are not exported from the top-level dagster module, `@whitelist_for_serdes` is not guaranteed to pick them up. In a previous PR, I moved around imports such that these were no longer incidentally imported when importing `AutomationCondition`, which is exported from the top level dagster module (because this helped avoid circular import errors).
This meant that if you deserialized an AutomationCondition before making some specific imports, this would fail.
To fix the circular import errors I needed to use the new ImportFrom mechanism.
Added a test which failed before and passes now.
=> [DA] fix automation condition serdes

python_modules/dagster/dagster/_core/definitions/run_request.py, python_modules/dagster/dagster/_core/definitions/sensor_definition.py, python_modules/dagster/dagster/_core/test_utils.py, python_modules/dagster/dagster/_daemon/sensor.py, python_modules/dagster/dagster_tests/daemon_sensor_tests/conftest.py, python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run_backfill_daemon.py
Modifies `RunRequest` to accept an `AssetGraphSubset`. If a `RunRequest` contains an `AssetGraphSubset`, the sensor daemon will launch a backfill for the `AssetGraphSubset` 
based on https://github.com/dagster-io/dagster/pull/18895
other iterations of this PR that got closed 
https://github.com/dagster-io/dagster/pull/22827
https://github.com/dagster-io/dagster/pull/22488
new tests
=> RunRequest can request backfills

python_modules/dagster/dagster/_record/__init__.py, python_modules/dagster/dagster_tests/general_tests/test_record.py
When working on https://github.com/dagster-io/dagster/pull/22860 I believed that class vars on abstract base classes acted similar to abstract property. While at runtime the class var does not exist if its not implemented on a child class, the type checker and runtime do not prevent you from omitting an implementation for that memeber on a concrete child class.
This address the issue by ensuring that NamedTuple fields that conflict are moved up to the `__dict__` of the generated type so that their precedance is greater than the abstract property definition on any base class. 
updated tests
=> [record] support abstract properties on base classes

integration_tests/test_suites/daemon-test-suite/dagster_dev_command_tests/test_dagster_dev_command.py, integration_tests/test_suites/daemon-test-suite/tox.ini
Summary:
This test previously detected dagit crashes on startup, but not issues with loading the toys repo. Now it does both.
Test Plan: BK (this test is failing in master currently due to an issue introduced by https://github.com/dagster-io/dagster/pull/22890)
=> Augment dagster dev sanity check test to actually verify that it could load the toys code location

python_modules/dagster-test/dagster_test/test_project/test_jobs/repo.py, python_modules/dagster/dagster/_core/executor/child_process_executor.py, python_modules/dagster/dagster/_core/executor/multiprocess.py, python_modules/dagster/dagster/_core/executor/step_delegating/step_delegating_executor.py, python_modules/dagster/dagster_tests/execution_tests/engine_tests/test_child_process_executor.py, python_modules/dagster/dagster_tests/launcher_tests/test_default_run_launcher.py, python_modules/libraries/dagster-docker/dagster_docker_tests/test_docker_executor.py, python_modules/libraries/dagster-docker/dagster_docker_tests/test_launch_docker.py
If there's a framework error that makes the run fail, terminate any in-progress steps.
BK
=> terminate running steps when multiprocess / step delegating executors unexpectedly raise an exception

python_modules/dagster/dagster/_core/definitions/asset_graph_computation.py, python_modules/dagster/dagster/_core/definitions/asset_layer.py, python_modules/dagster/dagster/_core/definitions/assets.py
`AssetsDefinition` contains several methods which only operate on data that's in the `AssetGraphComputation`. This moves those methods over to `AssetGraphComputation`.
=> move methods to AssetGraphComputation

docs/content/integrations/embedded-elt/dlt.mdx, examples/docs_snippets/docs_snippets/integrations/embedded_elt/dlt_dagster_translator.py, examples/docs_snippets/docs_snippets/integrations/embedded_elt/dlt_partitions.py, examples/docs_snippets/docs_snippets/integrations/embedded_elt/dlt_source_assets.py
- Adds "Advanced usage" section to dlt docs
- Introduces new examples:
* Using the translator to customize dlt -> dagster mapping
* Customizing metadata of source assets
* Using partitions with dlt_assets
=> [docs] dlt add examples for translator, sourceasset, partitions

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
https://github.com/dagster-io/dagster/blob/3a990132069004eea64c823bdb7676dca8b006fa/python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py#L488
The type signature of `multi_asset` claims to support any sequence, but the type checker expects a list.
Changed to check for sequence instead of list.
Ran asset tests.
=> Fix `multi_asset` specs arg to accept any sequence

python_modules/dagster/dagster/_core/execution/plan/compute_generator.py, python_modules/dagster/dagster_tests/execution_tests/misc_execution_tests/test_async.py
context managers around yields in generators leads to extremely bizarre behavior, so avoid it.
fixes https://github.com/dagster-io/dagster/issues/22606
added test that was previously failing
=> fix warnings contextvar in asyncio

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/rule_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/code_version_changed_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/slice_conditions.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/any_downstream_conditions_operator.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/newly_true_operator.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/since_operator.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/serialized_objects.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/asset_condition_scenario.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_asset_condition.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_dep_condition.py
Adds the ability to apply an arbitrary string label to an AutomationCondition.
For now, this requires adding an explicit `label` property to all AutomationCondition subclasses, but this can be simplified with an update to the @record system
Added unit test
=> [DA] Add with_label to AutomationCondition

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/schema/asset_condition_evaluations.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_condition_evaluations.py
For the new UI, I decided to just create a new field on the existing record class. The overall data model is a lot simpler, as we just have a single data type regardless of if the asset is partitioned or unpartitioned, and we no longer need to support the SpecificPartition UI.
=> [DA] Update GraphQL for AutomationCondition label

python_modules/dagster/dagster/_record/__init__.py, python_modules/dagster/dagster_tests/general_tests/test_record.py
avoids weird error if you use positional args
added test that was failing before change
=> [record] pass through *args in JitCheckedNew

js_modules/dagster-ui/packages/app-oss/src/pages/_document.tsx
Right now, this renders to e.g. `/manfiest.json` which does not load correctly when using a `path-prefix`.
I noticed when running with a `path-prefix`, I was getting 404 errors for the manifest and favicon specified from the top level, which were using absolute paths without the prefix.
In my local environment, I made the change, ran `./build_js.sh` then `pip install -e .` from the `python_modules/dagster-webserver` directory. Then I launched `dagster-webserver  --path-prefix /dagster-testing` and verified the correct behavior. The generated HTML now contains the following:
```
<link rel="manifest" href="/dagster-testing/manifest.json" crossorigin="use-credentials"/><link rel="icon" type="image/png" href="/dagster-testing/favicon.png"/><link rel="icon" type="image/svg+xml" …
```
=> [ui] Use relative links for manifest/favicon.

docs/content/dagster-plus/managing-deployments/alerts/pagerduty.mdx
I don't think this callout to contact support is necessary/good optically now that the feature has been available for a while. Also the contact method given is going to be deprecated in the near future. 
👀
=> [docs] remove support paragraph in PG alert doc

python_modules/dagster/dagster/_check/builder.py
`recursive_guard` got made keyword arg only in https://github.com/python/cpython/pull/118009 which released in `3.12.4` (we run an older version in buildkite so we missed it)
fixes https://github.com/dagster-io/dagster/issues/22985
on a fresh 3.12.4 venv
`pytest python_modules/dagster/dagster_tests/general_tests/test_record.py python_modules/dagster/dagster_tests/general_tests/check_tests/test_check.py`
which was failing before fix
=> [check builder] 3.12.4 fix

python_modules/dagster/dagster/_core/definitions/asset_layer.py, python_modules/dagster/dagster/_core/execution/plan/inputs.py, python_modules/dagster/dagster/_core/execution/plan/plan.py, python_modules/dagster/dagster/_core/execution/resolve_versions.py, python_modules/dagster/dagster/_core/execution/resources_init.py
Like other `StepInputSource` subclasses, `FromLoadableAssets` has properties for node handle and input name, but doesn't actually need them, because how the input gets loaded doesn't actually depend on where the input lives in the composition graph.
=> enable constructing FromLoadableAssets without node_handle and input_name

python_modules/dagster/dagster/_core/definitions/asset_selection.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection.py
We should be able to serialize an asset selection for owners, as you can select for owners in the catalog UI.
We should also do the same for an asset selection for code locations, but that involves changing how the BaseAssetGraph is constructed. So separating that into its own change.
pytest
=> feat(catalog): add `AssetSelection` method to select owners

examples/experimental/dagster-blueprints/dagster_blueprints/blueprint_assets_definition.py, examples/experimental/dagster-blueprints/dagster_blueprints_tests/test_shell_command_blueprint.py
=> support prefixed asset keys in blueprints, via `AssetKey.from_user_string`

python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
Summary:
Similar to if you call assetNodes on asset keys that do not exist in the graph anymore, or on a job that no longer exists in the repor return an empty list of nodes if you pass in a selector for a code location that does not exist.
=> Don't raise an error if assetNodes is called on a code location that does not exist or is in an error state

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/dbt_packages/test_columns_metadata.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_metadata/models/incremental_orders.sql
When writing an incremental model, you can use `{{ this }}` as a Jinja variable to self-reference the current model when generating the next batch of incremental rows. This made building column lineage fail, as we did not also pass the schema of the current model to the `sqlglot` optimization function.
This fixes that.
pytest -- updated incremental test would fail if current model's schema was not passed into `sqlglot` optimization.
=> feat(dbt): support column lineage for self-referential incremental models

python_modules/libraries/dagster-dbt/dagster_dbt/cli/app.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/cli/test_prepare_and_package.py
We refer to this command as `prepare-for-deployment` as part of our dbt GitHub actions that we drop in users' repositories as part of cloud setup (https://github.com/dagster-io/dagster-cloud-action/blob/main/github/serverless/dbt/deploy.yml#L70). While we can update the command name in the GitHub action going forward to match the recent rename, it won't carry over users who have already cloned the set of actions.
This PR leaves the old name as a hidden alias to support existing users.
Unit test for boht names.
=> [dagster-dbt] Keep dagster-dbt project prepare-for-deployment alias for backcompat

python_modules/dagster/dagster/_core/definitions/asset_selection.py, python_modules/dagster/dagster/_core/definitions/decorators/schedule_decorator.py, python_modules/dagster/dagster/_core/definitions/decorators/sensor_decorator.py, python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster/_core/definitions/repository_definition/repository_data_builder.py, python_modules/dagster/dagster/_core/definitions/schedule_definition.py, python_modules/dagster/dagster/_core/definitions/sensor_definition.py, python_modules/dagster/dagster/_core/definitions/target.py, python_modules/dagster/dagster_tests/definitions_tests/asset_policy_sensors_tests/test_default_auto_materialize_sensors.py, python_modules/dagster/dagster_tests/definitions_tests/automation_tests/test_basic_automations.py, python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py
Add new `target` param to `{Schedule,Sensor}Definition` and their associated decorators. A target is an executable entity that can be targeted by a schedule/sensor. This is intended as a replacement for the `job`/`job_name` parameters.
This PR builds off downstack work that consolidated `DirectTarget` and `RepoRelativeTarget` into a single `AutomationTarget` class. The primary addition here is an `AutomationTarget.from_coercible` class method that will accept an `AssetsDefinition` or `CoercibleToAssetSelection` and generate an anonymous asset job from it which is used as the job def for the `AutomationTarget`.
`AssetsDefinitions` that are passed directly as a target, rather than as `Definitions.assets`, are automatically included in the pool of assets for the `Definitions` object. This …
=> Add `target` param to `{Schedule,Sensor}Definition`

js_modules/dagster-ui/packages/ui-components/.storybook/blueprint.css, js_modules/dagster-ui/packages/ui-components/.storybook/preview.js, js_modules/dagster-ui/packages/ui-components/rollup.config.js, js_modules/dagster-ui/packages/ui-components/src/components/Box.tsx, js_modules/dagster-ui/packages/ui-core/.storybook/preview-head.html
A handful of storybook and build fixes:
- In `ui-components`, Blueprint CSS is not being imported properly. I'm not sure when this broke, but it works by just importing directly from the blueprintjs paths.
- Additionally, the `ui-components` build is broken because I didn't update the `Color` filepath. Fixed this.
- In `ui-core` Storybook, we no longer need the `preview-head.html` since we're not using Google fonts.
`yarn storybook` on `ui-components`, verify that components like `Menu` now render with the proper imported Blueprint CSS.
`yarn build` on `ui-components`, verify successful output.
`yarn storybook` on `ui-core`, verify that everything still works fine.
=> [ui] Fix build and storybook for ui-components

js_modules/dagster-ui/packages/ui-components/package.json, js_modules/dagster-ui/packages/ui-components/rollup.config.js, js_modules/dagster-ui/packages/ui-components/src/components/Suggest.tsx, js_modules/dagster-ui/packages/ui-components/src/components/__stories__/Suggest.stories.tsx, js_modules/dagster-ui/yarn.lock
Replace `react-virtualized` with the tanstack virtualizer in the Suggest component. This eliminates `react-virtualized` as a peer dep in `ui-components`.
View `Suggest` storybook example, verify correct rendering and behavior of input, list, list items. Includes hovering, clicking, keyboard navigation and selecting.
View use cases of `Suggest` in the app, verify same: launchpad config partition picker, asset graph sidebar search, compute log toolbar filter.
=> [ui] Use newer virtualizer for Suggest

python_modules/dagster/dagster/_core/execution/submit_asset_runs.py
Summary:
The intention here appears to have been to return None if there were no jobs, but right now this is returning a StopIteration if the list is empty. Add a default.
Test Plan: BK
=> Correctly return None if there are no base asset jobs that exist for a given asset key

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/schema/asset_condition_evaluations.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_condition_evaluations.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/code_version_changed_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/slice_conditions.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/any_downstream_conditions_operator.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/newly_true_operator.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/since_operator.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/serialized_objects.py
As title, this creates an expanded label field which recursively builds a string to be rendered in the UI. The logic is that an "expandedLabel" will ditch the user-provided label for that node (if any), and then render the full expression based on the in-code names of the underlying conditions.
It adds in a new "name" property to AutomationCondition, which is necessary because we can't repurpose "description" because that's meant to be a human-readable description of the precise situations under which the condition is true (i.e. it also contains information about the specific parameters of the computation), whereas the name is meant to be more of a machine / system property. The label needs to be fully user-customizable and rather than referring to a single node, it actually refers to the …
=> Create exapndedLabel GQL field for AutomationConditionEvaluationNode

python_modules/dagster/dagster/_core/definitions/asset_graph_computation.py, python_modules/dagster/dagster/_core/definitions/job_definition.py, python_modules/dagster/dagster/_core/definitions/op_selection.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py
Consider executing this graph-backed asset with just `asset2` selected:
`op1.out1` isn't required to compute `asset2`. We can get its value by just reading `asset1`. So ideally the user wouldn't yield it. However, if they omit it, they have a problem: `op2` will get skipped, because its `in1` is unsatisfied.
When subsetting a graph-backed asset, this PR proposes only including edges from outputs that are required to compute the selected assets.
=> don't skip steps downstream of non-yielded unselected asset keys

js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillRunsTab.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/ExecutionTimeline.tsx, js_modules/dagster-ui/packages/ui-core/src/overview/OverviewTimelineRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/overview/groupRunsByAutomation.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/RunTimeline.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/RunTimelineRowIcon.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/RunTimelineTypes.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/__stories__/RunTimeline.stories.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/__tests__/mergeStatusToBackground.test.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/__tests__/useRunsForTimeline.test.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/getAutomationForRun.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/mergeStatusToBackground.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/types/useRunsForTimeline.types.ts, js_modules/dagster-ui/packages/ui-core/src/runs/useRunsForTimeline.tsx, js_modules/dagster-ui/packages/ui-core/src/testing/generateRunMocks.ts
When the viewer is in the IA feature flag, re-bucket the run timeline by automations, i.e.: schedule, sensor, auto-materialize, and manually launched. (And no more "Ad hoc materializations".)
This is accomplished by retrieving run tags, and tracking automation data on each run. If the flag is true, take the existing bucketed state and re-bucket it for display. Additionally, I have done a lot of renaming from "job" to "row", since our components and utilities currently always assume that bucketing takes place strictly by job.
With the flag enabled and disabled, view the run timeline. Verify that bucketing is correct in each state, and that links work correctly.
=> [ui] IA: Batch timeline by automation

docs/content/guides/limiting-concurrency-in-data-pipelines.mdx
This PR updates a `dagster-cloud` straggler, which was caused a broken link in the **Limiting concurrency** guide.
👀
=> [docs] - Fix link in Limiting concurrency guide

python_modules/dagster/dagster/_core/definitions/asset_selection.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection.py
Add an `AssetSelection` subclass that represents a selection by code location.
Its selection method isn't implemented yet since we don't expect users to use this in code. Code location information for a given node in the asset graph is only available in a remote context, not an in-process context.
pytest
=> feat(catalog): add `AssetSelection` stub to select by code location

docs/dagster-university/pages/dagster-dbt/lesson-7/5-preparing-for-a-successful-run.md
This PR corrects an env var in `profiles.yml` in Lesson 7. This was incorrectly `MOTHERDUCK_TOKEN`, but the course uses `DUCKDB_TOKEN`.
=> [daggy-u] [dbt] - Correct DuckDB variable in Lesson 7

docs/content/concepts/partitions-schedules-sensors/backfills.mdx
Command uses `-j` instead of `-p`, can confirm this by running `dagster job backfill -h`
👀
=> [docs] update backfills CLI command examples

js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/AutomaterializeMiddlePanel.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/AutomaterializeMiddlePanelWithData.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/EvaluationConditionalLabel.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/GetEvaluationsQuery.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/PartitionSegmentWithPopover.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/PolicyEvaluationCondition.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/PolicyEvaluationTable.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/__stories__/PartitionSegmentWithPopover.stories.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/__stories__/PolicyEvaluationCondition.stories.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/__stories__/PolicyEvaluationTable.stories.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/flattenEvaluations.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/types/GetEvaluationsQuery.types.ts
Implement the updated automation policy evaluations table, showing operators and operands for individual evaluation nodes. This uses an `isLegacy` GraphQL field to determine how to render the evaluation. I also adjusted the density for the legacy table.
Legacy:
New:
Using some assets provided to me by @OwenKephart, let AMP run. Click to view assets and their evaluations, both legacy and non-legacy, and both partitioned and non-partitioned.
Verify that rendering is correct, including collapsed state, hover states, operators/operands, and partition popovers.
=> [ui] New automation evaluations table UI

python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py
The `assets` property on definition did something very different from `get_assets_def` property, and I found that very confusing. The only reason we needed public properties for the "dagster defs" within a definitions object was for `Definitions.merge`. Instead, let's just consolidate the original args into a typeddict that we can access easily, and makes it clear what we're retrieving.
=> Clarify properties on Definitions

python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster/_core/definitions/utils.py, python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py
There are cases where users can easily end up with the same assets definition object floating around in multiple places. Consider the following case:
- asset my_asset is in module module_1
- asset check my_check on my_asset is in module_2. This module imports my_asset from module 1.
- A user calls `load_...` on module_1 and module_2. In their top level `Definitions` object, we will throw an error for duplicate asset keys. 
The typical fix pattern here is actually pretty annoying. You either need to manually import all assets, or completely reorganize your project structure. Instead, we should just perform the deduping for them if there's reference equality across assetsdefinitions objects. We actually already do this in the individual load_... functions.
Added a new test for the deduping …
=> [rfc] Dedupe definitions by reference equality.

python_modules/dagster-pipes/dagster_pipes/__init__.py, python_modules/dagster/dagster/_core/pipes/context.py, python_modules/dagster/dagster_tests/execution_tests/pipes_tests/test_subprocess.py, python_modules/libraries/dagster-sdf/tox.ini
This PR adds PipesCliArgsParamsLoader to dagster_pipes. 
This ParamsLoader is needed for some external processes which do not support setting environment variables. 
Added tests with subprocess
=> [dagster-pipes] add PipesCliArgsParamsLoader

js_modules/dagster-ui/packages/ui-core/src/app/ExecutionSessionStorage.tsx, js_modules/dagster-ui/packages/ui-core/src/app/time/TimeContext.tsx, js_modules/dagster-ui/packages/ui-core/src/code-links/CodeLinkProtocol.tsx, js_modules/dagster-ui/packages/ui-core/src/hooks/useSetStateUpdateCallback.tsx, js_modules/dagster-ui/packages/ui-core/src/hooks/useStateWithStorage.tsx, js_modules/dagster-ui/packages/ui-core/src/nav/__tests__/LeftNavRepositorySection.test.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext.tsx
The return type lies to you. it tells you that you might get undefined as an argument to your setter but this is untrue. The argument you receive is always guaranteed to be type T, and if undefined is not included in it then you'll never get it.
this addresses pr feedback from https://github.com/dagster-io/internal/pull/10591/files#r1681728346
buildkite
=> Fix `useStateWithStorage`'s return type 

python_modules/dagster/setup.py
Summary:
Adding a pin until https://github.com/grpc/grpc/issues/37178 is fully resolved.
Test Plan:
pip install dagster locally, verify 1.64.1 is installed
=> Add a grpcio pin to < 1.65.0 to avoid logspew when running dagster locally

python_modules/dagster/dagster/_config/pythonic_config/conversion_utils.py, python_modules/dagster/dagster_tests/core_tests/pythonic_config_tests/test_pythonic_config_types.py
Resolve #8932
I believe this is a good start for supporting `Literal` type annotations in Dagster's configs. 
This implementation doesn't cover all cases, but the most common use case for `Literal[<some_strings>]` is already working. 
In the future we would probably want to cover: 
- mixed types: `Literal["a", 1]`
- Optionals: `Literal["a", "b"] | None`
Added tests for Literal types
=> :sparkles: support Literal types in Pythonic Configuration

js_modules/dagster-ui/packages/ui-core/src/assets/AssetPageHeader.oss.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetsOverviewRoot.oss.tsx
The view prop is needed for dagster+ to be able to conditionally show UI based on whether we're in an individual asset scoped view or whether we're looking at a catalog page.
buildkite
=> [quick pr] Add a view prop AssetView

js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/EvaluationConditionalLabel.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/PolicyEvaluationTable.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/__stories__/PolicyEvaluationTable.stories.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/__tests__/PolicyEvaluationTable.test.tsx
Add a test for `PolicyEvaluationTable` to sanity check which table is rendered for each type of evaluation, and that row collapse/expand behaves as expected.
Also:
- Update Storybook examples.
- Add `userLabel` behavior, which renders the user label as an operand with a tooltip that displays the full `expandedLabel` string.
User label:
Hover on user label:
Storybook, jest. Load evaluation tables, verify that they render and behave correctly.
=> [ui] Automation table tests, update userLabel usage

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/dbt_packages/test_columns_metadata.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_metadata/packages.yml
Logs a new warning message telling users who are using the log_column_level_metadata macro that it will be deprecated in 1.9, and pointing them to fetch_column_metadata instead.
Unit test.
=> [dagster-dbt] Log a deprecation warning for users using log_column_level_metadata

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py, python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
This reverts commit 6d6654bb09a55fe29d9978c5abeefb6ca13f5540. The frontend currently depends on this returning nothing if the asset is not in the graph, and its not currently providing any performacnce benefits.
Test Plan: Bk
=> Revert "Remove asset nodes fetch from assetsLatestInfo (#22285)"

js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetBaseDataProvider.tsx
In the asset detail view, we're encountering an error when reading `assetMaterializations` for assets that don't exist in the workspace. Make the code a little more defensive.
View an asset that exists in the workspace, verify that the page loads with no errors. View an asset that no longer exists, verify same.
=> [ui] Asset detail: fix missing materializations error

docs/content/dagster-plus/managing-deployments/setting-environment-variables-agents.mdx
This PR corrects a file name in the Hybrid agent env vars guide for Dagster+. The intro says the change for code locations will be made in `dagster.yaml`, but it's actually `dagster_cloud.yaml` as [per part 1 of this guide](https://docs.dagster.io/dagster-plus/managing-deployments/setting-environment-variables-agents#amazon-ecs-agents).
=> [docs] - Fix dagster.yaml > dagster_cloud.yaml in Hybrid agent env var guide

js_modules/dagster-ui/packages/ui-core/src/app/CloudOSSContext.tsx, js_modules/dagster-ui/packages/ui-core/src/search/SearchDialog.tsx, js_modules/dagster-ui/packages/ui-core/src/search/types.ts, js_modules/dagster-ui/packages/ui-core/src/search/types/useGlobalSearch.types.ts, js_modules/dagster-ui/packages/ui-core/src/search/useGlobalSearch.tsx
For catalog views we need access to the definition object in order to filter the results further based on the active catalog view.
buildkite
=> [quick pr] Add definition object to `SearchResult`

js_modules/dagster-ui/packages/ui-core/src/runs/LogsRowStructuredContent.tsx
https://linear.app/dagster-labs/issue/FE-450/in-the-event-log-show-both-metadata-and-error-when-present-on-an
Turns out this is a very trivial fix, the component already supports the display of metadataEntries and we just need to pass them through.
=> [ui] Show metadataEntries when displaying EngineEvent logs with errors

docs/content/guides/migrations/migrating-airflow-to-dagster.mdx, examples/docs_snippets/docs_snippets/guides/migrations/migrating_airflow_to_dagster.py
The last sentences of the guide were inside a code snippet.
This PR moves the sentences out of the code snippet. It also moves all code snippets to `examples/docs_snippets` to avoid this in the future.
`make mdx-full-format`
=> [docs] Fix formatting in Airflow migration guide

python_modules/dagster/dagster/_core/definitions/asset_layer.py, python_modules/dagster/dagster/_core/execution/context/compute.py, python_modules/dagster/dagster/_core/execution/context/system.py, python_modules/dagster/dagster/_core/execution/plan/execute_step.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_job.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py, python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py, python_modules/libraries/dagster-dbt/dagster_dbt/asset_defs.py, python_modules/libraries/dagster-dbt/dagster_dbt/cloud/asset_defs.py, python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud/test_asset_defs.py
This PR proposes a behavior change, for 1.8, to how we handle yielded outputs that correspond to assets that are unselected in the run. Previously, we would create an `AssetMaterialization` even for an unselected asset. After this change, we raise an error. I believe we should consider the current behavior a bug.
I.e. this now raises an error saying that an output was returned for "asset2" even thought it wasn't selected:
```python
@multi_asset(outs={"asset1": AssetOut(), "asset2": AssetOut()}, can_subset=True)
def assets():
return 1, 2
materialize([assets], selection=["asset1"])
```
Note that we already raise an error in this case, saying that "asset2" wasn't selected:
```python
@multi_asset(specs=[AssetSpec("asset1"), AssetSpec("asset2")], can_subset=True)
def assets():
yield …
```
=> [1.8] error on unselected outputs

docs/content/integrations/dbt/reference.mdx, examples/docs_snippets/docs_snippets/integrations/dbt/dbt.py, python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt/include/scaffold/definitions.py.jinja, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resources_v2.py
This was always allowed, but this failed type-hinting. Now it shouldn't fail type-hinting.
pytest, pyright
=> refactor(dbt): allow `Path` for `DbtCliResource` arguments

python_modules/dagster/dagster/_core/remote_representation/external.py, python_modules/dagster/dagster/_daemon/asset_daemon.py, python_modules/dagster/dagster_tests/definitions_tests/asset_policy_sensors_tests/test_default_auto_materialize_sensors.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_asset_daemon.py
Creates a one-time migration to handle the fact that we're updating the default sensor name. In these cases, we want to make sure that we preserve the history of these default sensors (particularly their cursors) so that this change is not disruptive.
Still working on creating tests.
=> [DA] Update default AutomationConditionSensorDefinition name

python_modules/libraries/dagster-dbt/dagster_dbt/core/resources_v2.py, python_modules/libraries/dagster-dbt/dagster_dbt/core/utils.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_postprocessing.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/jaffle_shop/models/customers.sql
Addresses https://github.com/dagster-io/dagster/issues/23109.
Ensures that any exception which is fired during the dbt execution (or any subsequent metadata fetch) is properly propagated through later metadata fetches. For example, if materializing a model fails, ensure that the exception fails the run.
Also ensure that any successful materializations have their metadata fetched before the run is failed (e.g. we get row count for all assets that do materialize).
Adds a test which ensures that failure behavior works as expected when fetching row counts.
Snowflake/bq test: https://buildkite.com/dagster/full-moon-with-face-dagster-nightly/builds/99
=> [dagster-dbt] Ensure exceptions properly propagate through deferred metadata fetches

python_modules/dagster/dagster/_core/definitions/data_version.py
Summary:
I am not immediately sure how to create a test case that reproduces this problem, but this get_num_partitions call is missing a required argument when the asset has dynamic partitions.
Test Plan: Reproduce on a test query that was hitting a 500 with this error:
"Failure condition: The instance is not available to load partitions. You may be seeing this error when using dynamic partitions with a version of dagster-webserver or dagster-cloud that is older than 1.1.18. The other possibility is that an internal framework error where a dynamic partitions store was not properly threaded down a call stack."
=> Fix missing dynamic_partitions_store argument in _exceeds_self_partition_limit

.buildkite/dagster-buildkite/dagster_buildkite/steps/dagster.py, .buildkite/dagster-buildkite/dagster_buildkite/utils.py, Makefile
We can install prettier globally for this, no need to use yarn or hijack js_modules.
=> Run prettier in the root folder instead of via yarn

examples/experimental/dagster-blueprints/dagster_blueprints_tests/test_load_defs_from_yaml.py, python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster/_core/definitions/reconstruct.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_deps_error_informative.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_source_asset_observation_job.py, python_modules/dagster/dagster_tests/core_tests/resource_tests/pythonic_resources/test_binding.py, python_modules/dagster/dagster_tests/core_tests/resource_tests/pythonic_resources/test_nesting.py, python_modules/dagster/dagster_tests/core_tests/snap_tests/test_repository_snap.py, python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_check_decorator.py, python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py
This PR proposes turning Definitions into a "dumb" data class for passing around diverse sets of definitions. This means that users won't encounter any validation errors for unsatisfied resources, duplicate asset keys, etc., until either:
- They run a code server to load the definitions
- They invoke `Definitions.validate_loadable`
Why do this?
- Less work will happen at module import time. This gives users more flexibility to determine where they want to incur the cost of this validation. It also helps enable a future world where run/step workers only need to load/validate the subset of definitions that they need to execute.
- Less repetition of resources. This was sited as an issue by the developers of our internal platform: https://dagsterlabs.slack.com/archives/C03AF3MMEEN/p17205461664 …
=> [1.8] don't validate `Definitions` on construction

python_modules/dagster/dagster/_core/definitions/time_window_partitions.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/asset_condition_tests/test_legacy_missing_condition.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/updated_scenarios/partition_scenarios.py, python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py
I went after this to be able to remove `is_pickleable` from `serdes`, and it proved to be a good complex case for flexing `@record` features. 
There is some goofy stuff going on with `TimeWindowPartitionsDefinition`  and its subclasses, but I think moving to `@record` and the required bits of added information make it a easier to understand than before. 
existing tests
=> [record] TimeWindowPartitionsDefinition

python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
=> Fix typo in time_window_partitions.py

python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud/utils.py
Remove the legacy dbt meta format that applied freshness and auto materialize-policies.
=> refactor(dbt)!: remove legacy dbt meta formats

python_modules/dagster/dagster/_generate/templates/CODE_LOCATION_NAME_PLACEHOLDER/CODE_LOCATION_NAME_PLACEHOLDER/__init__.py, python_modules/dagster/dagster/_generate/templates/CODE_LOCATION_NAME_PLACEHOLDER/CODE_LOCATION_NAME_PLACEHOLDER/definitions.py, python_modules/dagster/dagster/_generate/templates/CODE_LOCATION_NAME_PLACEHOLDER/pyproject.toml.tmpl, python_modules/dagster/dagster_tests/cli_tests/test_project_commands.py
This PR updates the scaffold - it removes Definitions from `__init__.py` and add them to `definitions.py`.
`dagster project scaffold --name my-dagster-project`
BK with alread existing tests
=> Move Definitions to definitions.py in scaffold

python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_cli_event.py, python_modules/libraries/dagster-dbt/dagster_dbt/core/resource.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/dbt_packages/test_columns_metadata.py
`resource.py` is over 2000 lines. Let's separate out its components to make the file more tractable.
Start by separating out `DbtCliEventMessage`.
bk
=> refactor(dbt): separate out `DbtCliEventMessage` to `dbt_cli_event.py`

python_modules/libraries/dagster-aws/dagster_aws/ecs/tasks.py, python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/conftest.py
Summary:
https://github.com/dagster-io/dagster/pull/20663 modified the current container definition to exclude the "healthCheck" key, which means that the deep-equality check here is no longer valid - prompting the issue described in https://github.com/dagster-io/dagster/discussions/23162. This fixes that issue by excluding the container by name instead of by deep equality.
BK (test change reproduced the problem in master)
=> Fix issue with EcsRunLauncher with include_sidecars set to True

js_modules/dagster-ui/packages/ui-core/src/runs/TickTagForRun.tsx
Repair misalignment of text and button-link in `TickTagForRun`.
View a run launched by a schedule, verify correct alignment of elements.
Tested in Chrome, FF, Safari.
=> [ui] Fix tag misalignment on TickTagForRun

python_modules/libraries/dagster-airflow/setup.py
Incompatible with dagster-airflow on python3.8
https://buildkite.com/dagster/dagster-dagster/builds/88420#0190c75d-1346-485c-bad5-5f87916e69e3
=> Pin setuptools < 71.0.0 in dagster-airflow

python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py
This reflects its post-https://github.com/dagster-io/dagster/pull/22909 role as a "dumb" data class.
=> make `Definitions` a record

python_modules/dagster/dagster/_record/__init__.py
- fixes "unnecessary type: ignore" warning from pyright
=> fix(pyright) rm unnecessary type: ignore

js_modules/dagster-ui/packages/ui-core/src/assets/useAssetDefinitionFilterState.oss.tsx, js_modules/dagster-ui/packages/ui-core/src/ui/Filters/useChangedFilter.tsx, js_modules/dagster-ui/packages/ui-core/src/ui/Filters/useComputeKindTagFilter.tsx
Don't use `isEqual` to compare groups in `useAssetDefinitionFilterState` because we're reusing the logic in catalog views and in that context the filters have a different ` __typename`. I could remove the typename before passing it to this abstraction but its more performant to just skip the intermediate objects and just directly compare the attributes we care about.
used this in catalog views 
buildkite.
=> Don't use `isEqual` to compare groups in `useAssetDefinitionFilterState`

python_modules/dagster/dagster/_core/launcher/default_run_launcher.py, python_modules/dagster/dagster_tests/launcher_tests/test_default_run_launcher.py, python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py, python_modules/libraries/dagster-celery-k8s/dagster_celery_k8s/launcher.py, python_modules/libraries/dagster-docker/dagster_docker/docker_run_launcher.py, python_modules/libraries/dagster-docker/dagster_docker_tests/test_launch_docker.py, python_modules/libraries/dagster-k8s/dagster_k8s/launcher.py
Summary:
Make this is a no-op rather than moving a run from a terminal state into a non-terminal state. Helps with an race condition during asset backfills where many runs are terminated at once while they might also be naturally finishing on their own.
=> return False when run launchers try to terminate a run that is already finished

python_modules/dagster-test/dagster_test/fixtures/docker_compose.py
when docker-compose up throws an exception, just dump docker logs to stdout. sometimes there isn't anything more revealing here than what we get in the initial exception, but sometimes it points to an issue with the underlying service that wasn't in the original exception
forced docker-compose to fail with a bad health check definition, and ensured that the dump_logs function was invoked and did print to stdout
=> PLA 509 dump docker compose logs on failure

docs/content/guides/dagster/transitioning-data-pipelines-from-development-to-production.mdx, examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/repository/repository_v1.py, examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/repository/repository_v2.py, examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/repository/repository_v3.py, examples/docs_snippets/docs_snippets/guides/dagster/using_environment_variables_and_secrets/repository_v2.py
Updating the examples in PR #23155 broke the docs snippets. This PR fixes them.
BK
=> Fix docs snippets after removing code from __init__.py in examples

python_modules/dagster/dagster/_core/definitions/metadata/source_code.py
Currently the git [code reference](https://docs.dagster.io/guides/dagster/code-references#in-any-dagster-environment) feature only works for URLs containing "gitlab.com" and "github.com". This doesn't work with self-hosted GitLab because the string "gitlab.com" is not in "gitlab.self-hosted.xyz".
https://github.com/dagster-io/dagster/issues/23135
Confirmed locally against self-hosted GitLab instance.
=> Update source_code.py to allow self-hosted GitLab for code references

js_modules/dagster-ui/packages/ui-core/src/automation/MergedAutomationRoot.tsx
Add filters to the merged Automations page: code location, running state, and automation type (schedule/sensor). Also add text search.
View `/automations/merged`, verify that filters behave as expected.
=> [ui] Filters for merged automation table

python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py
After this PR, the following no longer errors:
```python
defs1 = Definitions(resources={"resource1": 4})
defs2 = Definitions(resources={"resource1": 4})
merged = Definitions.merge(defs1, defs2)
```
=> in Definitions.merge, don't error on duplicate resource and logger values

python_modules/libraries/dagster-sdf/MANIFEST.in, python_modules/libraries/dagster-sdf/dagster_sdf/__init__.py, python_modules/libraries/dagster-sdf/dagster_sdf/asset_utils.py, python_modules/libraries/dagster-sdf/dagster_sdf/cli/app.py, python_modules/libraries/dagster-sdf/dagster_sdf/errors.py, python_modules/libraries/dagster-sdf/dagster_sdf/include/__init__.py, python_modules/libraries/dagster-sdf/dagster_sdf/include/pyproject.toml.jinja, python_modules/libraries/dagster-sdf/dagster_sdf/include/scaffold/assets.py.jinja, python_modules/libraries/dagster-sdf/dagster_sdf/include/scaffold/constants.py.jinja, python_modules/libraries/dagster-sdf/dagster_sdf/include/scaffold/definitions.py.jinja, python_modules/libraries/dagster-sdf/dagster_sdf/include/scaffold/schedules.py.jinja, python_modules/libraries/dagster-sdf/dagster_sdf/include/setup.py.jinja, python_modules/libraries/dagster-sdf/dagster_sdf/information_schema.py, python_modules/libraries/dagster-sdf/dagster_sdf/resource.py, python_modules/libraries/dagster-sdf/dagster_sdf_tests/cli/conftest.py, python_modules/libraries/dagster-sdf/dagster_sdf_tests/cli/test_scaffold.py, python_modules/libraries/dagster-sdf/dagster_sdf_tests/test_asset_decorator.py, python_modules/libraries/dagster-sdf/dagster_sdf_tests/test_information_schema.py, python_modules/libraries/dagster-sdf/setup.py
This PR contains the `dagster-sdf` scaffolding cli, which helps users quickly scaffold a dagster project from an existing sdf workspace. 
```
dagster-sdf workspace scaffold --project-name {dagster-project-name} --sdf-workspace-dir {path-to-sdf-workspace}
```
It creates the necessary `assets.py`, `constants.py`, `definitions.py` etc. to get a project off the ground.
Users can then run `dagster dev`, with `DAGSTER_SDF_COMPILE_ON_LOAD=1` to ensure the project is compiled before the information schema is loaded to determine the asset dag.
```
DAGSTER_SDF_COMPILE_ON_LOAD=1 dagster dev
```
See `dagster_sdf_tests/cli`.
=> [dagster-sdf] Add Project Scaffold

js_modules/dagster-ui/packages/ui-core/src/asset-graph/Utils.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedScheduleRow.tsx
@smackesey is introducing a new anonymous job prefix. We should handle this the same as the existing `__ASSET_JOB` prefix, which is to hide it aggressively throughout the app.
The simplest thing to do here seems to be to just add it as another check alongside the existing prefix check.
Run dagster dev with a target code location that includes sensors and schedules with anonymous jobs using the new prefix.
View Jobs list, verify that these jobs don't appear. View Schedules and Sensors lists, verify same.
=> [ui] Hide jobs with dunder anonymous prefix

python_modules/dagster/dagster/_core/storage/alembic/versions/043_add_run_tags_run_id_index.py, python_modules/dagster/dagster/_core/storage/runs/schema.py
While running jobs on frequent schedules we have noticed that as the amount of runs grows some ui operations become very slow. Looking at AWS monitoring we see that one query in particular seems to be very slow:
By analyzing the query we have noticed that it is related to run tag filtering. Here is an example of such a query with filled parameters:
```sql
EXPLAIN (ANALYSE, BUFFERS) SELECT runs.id,
runs.run_body,
runs.status,
runs.create_timestamp,
runs.update_timestamp,
runs.start_time,
runs.end_time
FROM runs
WHERE runs.run_id IN (SELECT run_tags.run_id
FROM run_tags
WHERE
run_tags.key = 'dagster/schedule_name' AND run_tags.value = 'quick_partitioned_job_schedule'
OR run_tags.key = '.dagster/repository' AND
run_tags.value = '__repository__@example-code'
GROUP BY run_tags.run_id
HAVING …
```
=> change: Changed run tag filtering and added additional run tag filter for better performance.

python_modules/dagster/dagster/_core/storage/alembic/versions/043_add_run_tags_run_id_index.py, python_modules/dagster/dagster/_core/storage/runs/schema.py, python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py
A followup to #22833 adding an optimized query for tag filtering.
While running jobs on frequent schedules we have noticed that as the amount of runs grows some ui operations become very slow. Looking at AWS monitoring we see that one query in particular seems to be very slow:
By analyzing the query we have noticed that it is related to run tag filtering. Here is an example of such a query with filled parameters:
```sql
EXPLAIN (ANALYSE, BUFFERS) SELECT runs.id,
runs.run_body,
runs.status,
runs.create_timestamp,
runs.update_timestamp,
runs.start_time,
runs.end_time
FROM runs
WHERE runs.run_id IN (SELECT run_tags.run_id
FROM run_tags
WHERE
run_tags.key = 'dagster/schedule_name' AND run_tags.value = 'quick_partitioned_job_schedule'
OR run_tags.key = '.dagster/repository' AND
run_tags.value …
```
=> change: Changed run tag filtering query for better performance.

python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py, python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py, python_modules/dagster/dagster/_serdes/__init__.py, python_modules/dagster/dagster/_serdes/serdes.py
Adds a path for avoiding re-entering context managers for each value when deserializing a list of items
updated some callsites, existing tests
=> [serdes] deserialize_values

python_modules/libraries/dagster-dbt/dagster_dbt/core/resource.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_postprocessing.py
Adds a `with_snowflake_insights` and `with_bigquery_insights` methods that can be chained to a `.stream()` call, simplifying using insights alongside other deferred fetches:
Before:
```python
@dbt_assets(manifest=snowflake_manifest_path)
def jaffle_shop_dbt_assets(
context: AssetExecutionContext,
dbt: DbtCliResource,
):
dbt_cli_invocation = dbt.cli(["build", "--profile", "unittest"], context=context)
yield from dbt_with_snowflake_insights(context, dbt_cli_invocation)
```
Now:
```python
@dbt_assets(manifest=snowflake_manifest_path)
def jaffle_shop_dbt_assets(
context: AssetExecutionContext,
dbt: DbtCliResource,
):
yield from dbt.cli(
["build", "--profile", "unittest"], context=context
).stream().with_snowflake_insights()
```
https://github.com/dagster-io/internal/pull/10731
=> [dagster-dbt] add `with_snowflake/bigquery_insights` chainable method

python_modules/dagster/dagster/_core/execution/context/op_execution_context.py
These methods are superseded by `partition_key`, `partition_time_window`, etc.
=> deprecate asset_partition_x_for_output methods on OpExecutionContext

python_modules/dagster/dagster/_record/__init__.py
it appears that when installed, `@record_custom` + `IHaveNew` is assuming `__new__` returns `None` instead of `Unknown` causing it to believe `x` is `None` for `x = RunRecord()` 
explicitly tag `__new__`'s return to `Self` to resolve
resolves https://github.com/dagster-io/dagster/issues/23214
manually made the change in `site-packages` of installed copy of `1.7.13`
=> [record] IHaveNew.__new__ Self return typehint

js_modules/dagster-ui/packages/ui-core/src/assets/useAssetCatalogFiltering.oss.tsx, js_modules/dagster-ui/packages/ui-core/src/hooks/useDebugChanged.tsx, js_modules/dagster-ui/packages/ui-core/src/ui/BaseFilters/FilterDropdown.tsx, js_modules/dagster-ui/packages/ui-core/src/ui/BaseFilters/useFilters.tsx, js_modules/dagster-ui/packages/ui-core/src/ui/Filters/useAssetGroupFilter.tsx
Two things:
1. We're passing the filterButton upwards to the CatalogViewProvider so that it can use it without having to recreate it from scratch. While doing that I encountered an infinite loop due to the provider updating the context which causes `useAssetCatalogFiltering.cloud` to re-render which causes `useAssetCatalogFiltering.oss` to re-render and it ends up creating new filter objects due to some aspects of it being unmemoized. To fix this I memoized things that were causing unnecessary re-renders. 
2. Added a `renderButton` return to `useFilters` which can be used to change the label on the button. I opted to just return a new prop instead of modifying the existing one to this in order to reduce the number of changes in this PR. In a future pr we can consolidate or figure out a …
=> [Filters] Memoize filter objects + renderFilterButton

python_modules/libraries/dagster-dbt/dagster_dbt/__init__.py, python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py
As the title.
- The class was not under test after `load_assets_from_dbt_XXX` was removed.
- The class is not mentioned in the docs.
- The current docs recommend directly using `DagsterDbtTranslator`.
N/A
=> refactor(dbt)!: remove `KeyPrefixDagsterDbtTranslator`

python_modules/libraries/dagster-dbt/dagster_dbt/utils.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_dbt_unit_tests/dbt_project.yml, python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_dbt_unit_tests/models/staging/stg_payments.sql
This PR fixes issue #22854.
An exception is raised when initializing `@dbt_assets` with a selector method "tag" passed to either `select` or `exclude`, only when the dbt project includes a `unit_test.yml` file.
The exception is caused because `node.tags == None` when running [this line of code](https://github.com/dbt-labs/dbt-core/blob/v1.8.4/core/dbt/graph/selector_methods.py#L266-L271) in `dbt.graph.selector_methods`.
Adding a tag in `unit_test.yml` does not fixed the problem. Eg.
```
unit_tests:
- name: test_unit_test
config:
tags:
- test
model: my model
```
Taking a closer look, `node.__class__  == 'dagster_dbt.utils.select_unique_ids_from_manifest.<locals>._DictShim'>` when running the selector method code [here](https://github.com/dbt-labs/dbt-core/blob/v1.8.4/core/dbt/graph/selector …
=> [dagster-dbt] Support @dbt_assets with select in a dbt-core>=1.8 project with unit tests

python_modules/dagster/dagster/_core/definitions/decorators/sensor_decorator.py, python_modules/dagster/dagster_tests/core_tests/definitions_tests/decorators_tests/test_sensor_decorator.py
This makes `@sensor` pass `name or eval_fn.__name__` to `SensorDefinition` (which is what schedules already do), preventing an invariant error when doing this, since jobless sensors/schedules require a set `name`:
```
@sensor(target=[...])
def my_sensor():
...
```
New unit test.
=> Make @sensor pass eval_fn name as SensorDefinition.name

python_modules/dagster/dagster/_core/definitions/events.py
Add an `AssetPartitionWipeRange` class to complement `AssetKeyPartitionKey`. This is used upstack in partition wiping PRs.
Like `AssetKeyPartitionKey`, this uses `None` for the `partition_range` if there is no range-- this is interpreted as "the whole asset".
This is called `AssetPartitionWipeRange` instead of just `AssetPartitionRange` to scope this abstraction explicitly to partition wiping for the time being. Later I expect to rename this to just `AssetPartitionRange` or similar as part of a broader rename of partition abstractions.
=> Add AssetPartitionWipeRange class

python_modules/dagster/dagster/_core/snap/execution_plan_snapshot.py, python_modules/dagster/dagster/_utils/caching_instance_queryer.py, python_modules/dagster/dagster_tests/core_tests/test_asset_events.py
Summary:
This gives us the ability to efficiently load asset selections for all runs without doing an event log scan for ASSET_MATERIALIZATION_PLANNED events. The asset selection is derived from the same place that we use to determine what ASSET_MATERIALIZATION_PLANNED events to emit (the execution plan snapshot)
Test Plan: BK
=> Fetch planned asset materializations from the execution plan snapshot, rather than doing an event log scan

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/implementation/fetch_schedules.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster-graphql/dagster_graphql/schema/external.py, python_modules/dagster-graphql/dagster_graphql/schema/schedules/schedules.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_scheduler.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py, python_modules/dagster/dagster/_core/definitions/sensor_definition.py, python_modules/dagster/dagster/_core/remote_representation/external.py, python_modules/dagster/dagster/_core/remote_representation/external_data.py, python_modules/dagster/dagster_tests/core_tests/snap_tests/__snapshots__/test_active_data.ambr
- Add an `asset_selection` param to `ScheduleSnap` and `Schedule` in GQL API
- Populate `asset_selection` on both `ScheduleSnap` and `SensorSnap` (which leads to population of corresponding fields in GQL) using the `target` passed to `ScheduleDefinition`/`SensorDefinition` for jobless automation.
Background: "jobless" (i.e. assets passed as `target`) schedules/sensors create an anonymous asset job under the hood. We do not want the UI to expose this asset job-- instead, we want it to just show the targeted assets. There is prior art here. Before the new `target` parameter, it was already possible to pass an `asset_selection` rather than `job` to `SensorDefinition`, and the UI would render the target accordingly.
This PR leverages/copies this existing "jobless sensor" infrastructure for …
=> [jobless-automation] Expose target as assetSelection in GQL

python_modules/dagster-graphql/dagster_graphql/implementation/execution/__init__.py, python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py, python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster/_core/storage/event_log/base.py, python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py, python_modules/dagster/dagster/_core/storage/legacy_storage.py
Internal companion PR: https://github.com/dagster-io/internal/pull/9993
The status quo is no API at all for performing partition-scoped asset wiping. This PR (together with its companion) adds support for partition wiping with cloud storage, but not OSS. The reason for this limitation is that we have no way to performantly store partition-specific wipe timestamps without the cloud-only `AssetPartitionsTable`. In the future we may be able to get around this by storing partition ranges directly in the DB, but there are unresolved questions around how to handle `StaticPartitionsDefinition` in this scenario.
How this PR works:
- GraphQL
- The existing `wipeAssets` mutation has been modified (downstack in #22249) to accept the existing `GraphenePartitionsByAssetSelector` instead of …
=> Add backend support for partition wiping

python_modules/dagster/dagster/_core/definitions/asset_daemon_cursor.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/serialized_objects.py
Discussed in standup, this is ultimately a better / safer way of handling name changes.
=> [DA] Use storage_name instead of old_storage_names

python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py
This enables passing `AssetSpec` objects to the `assets` argument of the `Definitions` constructor.
=> [1.8][external assets] Definitions accepts AssetSpec

js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillRow.tsx, python_modules/dagster/dagster/_core/execution/job_backfill.py, python_modules/dagster/dagster/_core/storage/dagster_run.py, python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py
the status for a job backfill and a pure asset backfill means different things. 
For a job backfill, the backfill is considered complete once all of the runs have been **submitted**. For a pure asset backfill, the backfill is considered complete once all runs have **finished**.
We also display the status differently in the UI:
For pure asset backfills, we mirror the backfill's status exactly
For job backfills, if the backfill has completed status, the backfill can be displayed as "In Progress" if runs are still in progress, or "Incomplete" if some runs have failed or were canceled manually.
This adds extra work for the front end and communicates different information to the user depending on what type of backfill was launched. 
This PR consolidates how we show the status of a backfill to …
=> make job backfill status consistent with asset backfill status

js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillRow.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillTable.tsx
The run status column on the backfills page cannot load for asset-job backfills if the backfill policy of the asset changes.  This is because we use run tags/db indices to determine the status of each partition. We need to look for different tags with different backfill policies, but dont store what the backfill policy was when the backfill ran. 
Rather than try to make the run status column work, we decided to remove the column for these reasons:
1. job-based backfills are less commonly used and a "secondary" feature. We don't show this run status information for pure asset backfills.
2. there is work being done for jobs to support multiple partition definitions in the future. when that happens, this graphic makes less sense since we'd need to include one bar per partition and that could …
=> [ui] remove run status column on backfills page

js_modules/dagster-ui/packages/ui-core/src/automation/VirtualizedAutomationScheduleRow.tsx, js_modules/dagster-ui/packages/ui-core/src/schedules/CronTag.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedScheduleRow.tsx
For schedule table rows, render human-readable cron strings in tags.
View Schedules list and merged automations list, verify rendering and behavior of cron tags, including hover states for tooltips and expanded human-readable string.
=> [ui] CronTag

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillActionsMenu.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillRow.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillTerminationDialog.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/__fixtures__/BackfillTable.fixtures.ts, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/__stories__/BackfillTable.stories.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/backfill/types/BackfillRow.types.ts, python_modules/dagster-graphql/dagster_graphql/schema/backfill.py, python_modules/dagster/dagster/_core/storage/dagster_run.py
As discussed in https://github.com/dagster-io/dagster/pull/23143, there are issues loading per-partition status for asset-job backfills. The `PartitionStatusCounts` field on `PartitionBackfill` also uses this partition status information and the backfill cancelation action uses the status counts to determine if it can cancel the backfill. We need to get the same information another way, so this PR introduces a new field on `PartitionBackfill` - `cancelableRuns` which returns any runs that are part of the backfill and are in a cancelable state. This lets us remove the problematic queries from the backfill pages entirely
=> [ui] remove partition statuses from backfill termination logic

python_modules/dagster/dagster/_utils/caching_instance_queryer.py
Summary:
AMP perf tests catch another regression! The old codepath was cached_method-ed, the new codepath is not
Test Plan: BK, run amp perf test that was timing out
=> Memoize get_planned_materializations_for_run in new codepath

js_modules/dagster-ui/packages/ui-core/src/automation/AutomationTargetList.tsx, js_modules/dagster-ui/packages/ui-core/src/automation/__stories__/AutomationTargetList.stories.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedSensorRow.tsx
For consistency, make the automation target list a tag (or list of tags, if multiple jobs) in all cases.
- If a job, link to the job.
- If multiple jobs, show multiple tags that each link to their jobs.
- If single asset, link to that asset.
- If multiple assets, open the dialog.
I also changed the dialog to prevent its height from jumping when opening/closing its sections, and fixed the virtualized table to window the list correctly.
View Sensors and Schedules list and individual pages. Verify correct rendering and link behavior of automation target tags, including asset dialog.
=> [ui] Make automation target a tag

js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillRow.tsx
@salazarm  i missed your comment here https://github.com/dagster-io/dagster/pull/23141#discussion_r1692456463 - this should resolve
=> [ui] replace BackfillStatusTag with BackfillStatusTagForPage

scripts/install_dev_python_modules.py
Update the script called by `make dev_install` to include `dagster-openai`.
Tested locally with `make dev_install`
=> [dagster-openai] Add dagster-openai to `make dev_install` script

python_modules/dagster/dagster/_core/definitions/asset_check_spec.py, python_modules/dagster/dagster_tests/definitions_tests/test_asset_check_spec.py
In line with @schrockn's proposal here: https://github.com/dagster-io/dagster/pull/22314. This makes it function the same as `AssetSpec`.
The direct motivation for this is https://github.com/dagster-io/dagster/pull/23191.
I would have also added a test to make sure it doesn't cause any errors on serialization, but discovered that `ExternalAssetCheck` doesn't actually have a metadata field yet, so this metadata is not currently serialized. I'll try to add that field as a followup if I can squeeze it in.
=> support unserializable metadata on `AssetCheckSpec`

python_modules/dagster/dagster/_core/definitions/asset_graph.py, python_modules/dagster/dagster/_core/definitions/external_asset.py
Also retroactively marks it as experimental, which was the original intention.
=> [1.8][external assets] deprecate external_assets_from_specs

python_modules/libraries/dagster-looker/dagster_looker_tests/test_asset_specs.py
With the deprecation of `external_assets_from_specs` in the ability to put `AssetSpec`s directly on `Definitions`, this is no longer needed.
=> remove usage of external_assets_from_specs in looker tests

python_modules/dagster/dagster/_utils/container.py
This constant represents a ceiling where a cgroup memory_limit is considered unconstrained, or basically, unlimited.
=> feat: add constant that represents an unconstrained memory limit in cgroup for reuse

docs/content/concepts/dagster-pipes/databricks.mdx, examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/databricks/databricks_asset_client.py, pyright/master/requirements-pinned.txt, python_modules/libraries/dagster-databricks/dagster_databricks/databricks.py, python_modules/libraries/dagster-databricks/dagster_databricks/databricks_pyspark_step_launcher.py, python_modules/libraries/dagster-databricks/dagster_databricks/pipes.py, python_modules/libraries/dagster-databricks/dagster_databricks/types.py, python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_databricks.py
Update dagster-databricks to support `databricks-sdk` 0.17.0.
#21232 bumped databricks-sdk to 0.17.0 but did not bump pyright pins. Though this PR passed our tests (which are pretty spotty for this package), it introduced many type errors against the newer `databricks-sdk` that manifested when bumping pyright pins.
The present PR fixes the type errors, allowing us to bump pyright pins and hopefully avoiding crashes against the newer databricks-sdk we now support.
Existing test suite, pyright.
=> [dagster-databricks] Update to support databricks-sdk<=0.17.0

examples/experimental/dagster-airlift/dagster_airlift/airflow_utils.py, examples/experimental/dagster-airlift/dagster_airlift_tests/airflow_project/dags/simple_dag.py, examples/experimental/dagster-airlift/examples/peering-with-dbt/peering_with_dbt/airflow_dags/dbt_dag.py, examples/experimental/dagster-airlift/examples/peering-with-dbt/peering_with_dbt/airflow_dags/lakehouse.py, pyright/master/exclude.txt, pyright/master/requirements-pinned.txt, pyright/master/requirements.txt
`dagster-airflift` was excluded from pyright checking when it was merged due to issues with updating pyright pins unrelated to the `dagster-airlift` PR (see #23254). Those issues are fixed downstack. This PR adds `dagster-airlift` to pyright and fixes some type errors.
=> [dagster-airlift] add pyright checking, fix type errors

python_modules/dagster/dagster/_core/pipes/client.py, python_modules/dagster/dagster/_core/pipes/context.py, python_modules/dagster/dagster/_core/pipes/subprocess.py, python_modules/dagster/dagster/_core/pipes/utils.py, python_modules/dagster/dagster_tests/execution_tests/pipes_tests/test_subprocess.py
this PR unexperimentalizes the core abstraction of Pipes, and its builtin client implementation PipesSubprocessClient.
subsequent docs update: https://github.com/dagster-io/dagster/pull/23250
added a unit test to ensure no pipes related experimental warnings are fired when invoking Pipes subprocess.
=> remove experimental tag for core pipes apis and PipesSubprocessClient 1/3

python_modules/libraries/dagster-aws/dagster_aws/pipes.py, python_modules/libraries/dagster-databricks/dagster_databricks/pipes.py, python_modules/libraries/dagster-k8s/dagster_k8s/pipes.py
This PR unexperimentalizes:
- Lambda Pipes
* PipesLambdaClient
* PipesLambdaLogsMessageReader
* PipesLambdaEventContextInjector
* note: PipesS3MessageReader isn't experimental in status quo which might have been an oversight
- K8s Pipes
* PipesK8sClient
* PipesK8sPodLogsMessageReader
- Databricks Pipes
* PipesDatabricksClient
* PipesDbfsContextInjector
* PipesDbfsMessageReader
* PipesDbfsLogReader
=> remove experimental tag for pipes k8s, lamdba, databricks 3/3

js_modules/dagster-ui/packages/ui-core/src/automation/VirtualizedAutomationScheduleRow.tsx, js_modules/dagster-ui/packages/ui-core/src/automation/VirtualizedAutomationSensorRow.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedScheduleRow.tsx
Use `AutomationTargetList` in the Schedules and merged Automations lists.
- Add a column in the Schedules-only lists.
- Replace the existing pipeline reference in the merged automations list.
Schedule that targets assets:
List of schedules with job targets:
Merged automation table:
View all schedules lists (overview and per-code location) and merged automation list. Verify correct rendering and behavior of target tag.
Repeat with the anonymous job schedules, verify that they show the asset selection target.
=> [ui] Show target in Schedules lists

python_modules/dagster/dagster/_config/pythonic_config/typing_utils.py, python_modules/dagster/tox.ini
context https://github.com/dagster-io/dagster/issues/17443, specifically
> Unless someone is able to find a clever solution it appears the only choice is to flip who gets the errors at some point.
looking at [pypi download stats](https://www.pepy.tech/projects/pydantic?versions=2.*&versions=1.*) pydantic 2 downloads are ballpark 30% more than pydantic 1
so opening this PR to discuss if now / `1.8.0` is the time
run `mypy` on
```
from dagster import Config
class MyConfig(Config): ...
```
pydantic 2: no error
pydantic 1: `error: Metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases  [misc]`
=> [1.8.0][config] change who gets mypy errors from pydantic 2 to pydantic 1 users

js_modules/dagster-ui/packages/ui-core/src/automation/AutomationBulkActionMenu.tsx, js_modules/dagster-ui/packages/ui-core/src/automation/AutomationStateChangeDialog.tsx, js_modules/dagster-ui/packages/ui-core/src/automation/MergedAutomationRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/automation/__fixtures__/AutomationState.fixtures.tsx, js_modules/dagster-ui/packages/ui-core/src/automation/__tests__/AutomationStateChangeDialog.test.tsx, js_modules/dagster-ui/packages/ui-core/src/sensors/__tests__/SensorStateChangeDialog.test.tsx
Add bulk start/stop to the merged automations table. This heavily reuses existing bulk actions for schedules/sensors, merging them into a single dialog with four possible mutations (start/stop for schedule/sensor).
I expect that the existing schedule/sensor tables will go away entirely at some point soon. Leaving them in place for now.
View merged automation table, select single and multiple schedules and sensors. Verify correct behavior of bulk action menu and dialog.
=> [ui] Bulk actions for merged automations table

docs/content/guides/dagster/recommended-project-structure.mdx, docs/dagster-university/pages/dagster-essentials/lesson-2/project-files.md
This PR updates the url for the project file reference in the recommended structure guide and Dagster University.
URL redirection is set for this reference and works correctly when navigating from the search bar, but fails when navigating from other pages in the docs. 
Link in other docs: Docs preview
Dagster University: tested locally
=> [docs] Fix broken link for project file reference

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
The build is breaking on these two versions. I'll add a task for us to get this working before this is taken out of experimentation.
=> Mark airlift as unsupported in 3.8 and 3.12

.pre-commit-config.yaml, pyproject.toml, python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_op.py, python_modules/dagster/setup.py
I want to take advantage of Ruff's new native language server: https://x.com/charliermarsh/status/1815475688688005615. In 0.5.3, it was recently marked stable.
Even though it's available in our current 0.5.1 version, there are some hiccups (e.g. random process failures that kill the native server). Hoping upgrading to a stable version will alleviate these issues.
bk
=> chore: upgrade to `ruff=0.5.5`

python_modules/dagster/dagster/_core/definitions/asset_graph.py, python_modules/dagster/dagster/_core/definitions/base_asset_graph.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_evaluator.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_tester.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py, python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py, python_modules/dagster/dagster/_core/remote_representation/external.py, python_modules/dagster/dagster/_core/remote_representation/external_data.py, python_modules/dagster/dagster/_daemon/asset_daemon.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenario_state.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_asset_daemon.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_automation_condition_tester.py
You can (with some effort) construct an observable asset that has an AutomationCondition. This was not previously possible, meaning there are some code paths which explicitly filter out observable assets. This PR removes those filters, and adds some tests ensuring that these assets get properly evaluated.
=> [DA] Update AssetDaemon and co. to handle observable assets with AutomationConditions

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
Airlift examples were previously not under test in bk.
=> [dagster-airlift] actually put examples under test

python_modules/dagster/dagster/_core/definitions/unresolved_asset_job_definition.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_partitioned_assets.py
Partitioning is inferred from the selected assets, so setting this is redundant.
=> deprecate `partitions_def` param on `define_asset_job`

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py, python_modules/libraries/dagster-dbt/dagster_dbt/core/resource.py, python_modules/libraries/dagster-dbt/setup.py, python_modules/libraries/dagster-dbt/tox.ini
`dbt-core==1.6.*` has been EOL since July 30, 2024: https://docs.getdbt.com/docs/dbt-versions/core.
Also, enforce that dbt-core>=1.7 on installation.
Same rodeo as #21518.
bk
=> feat(dbt): remove support for `dbt-core==1.6.*`

python_modules/dagster/dagster/_cli/asset.py, python_modules/dagster/dagster/_core/definitions/job_definition.py
Adds a `get_tags_for_partition_key` method to `JobDefinition`. This means that code paths trying to get the partition key for a run don't need to look at the `partitions_def` on the job.
For asset jobs, implements this method by looking at the selected assets, rather than the `partitions_def` on the job.
This will allow downstream PRs to build and use jobs that target assets with multiple `PartitionsDefinitions`, and to hide per-run `PartitionsDefinition` resolution from callers.
Also see it used here: https://github.com/dagster-io/dagster/pull/23287.
=> [single-implicit-asset-job] `get_tags_for_partition_key` on `JobDefinition`

python_modules/libraries/dagster-pandera/dagster_pandera/__init__.py, python_modules/libraries/dagster-pandera/dagster_pandera_tests/test_polars.py, python_modules/libraries/dagster-pandera/setup.py, python_modules/libraries/dagster-pandera/tox.ini
Resolves #20584.
Add support for `polars` to `dagster-pandera`. `polars` is added as an optional dependency under the new `polars` extra. The API of dagster-pandera remains the same except that `pandera_schema_to_dagster_type` now accepts `pandera.polars` schemas.
=> [dagster-pandera] add support for polars

js_modules/dagster-ui/packages/ui-core/src/graph/KindTags.tsx, js_modules/dagster-ui/packages/ui-core/src/nav/ReloadRepositoryLocationButton.tsx
https://github.com/dagster-io/dagster/pull/22705#discussion_r1653337561
Clean up all references that assign `window.location.href`.
bk
=> refactor: prefer `history.pushState` over assignment of `window.location.href`

python_modules/dagster/dagster/_core/definitions/job_definition.py, python_modules/dagster/dagster/_core/definitions/run_request.py, python_modules/dagster/dagster_tests/core_tests/definitions_tests/test_run_request.py, python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
This updates the implementation of `RunRequest.with_resolved_tags_and_config` to use the `get_tags_for_partition_key` method introduced in https://github.com/dagster-io/dagster/pull/23285.
The PR net deletes non-test LOC, but introduces a set of tests for `RunRequest.with_resolved_tags_and_config`.
=> [single-implicit-asset-job] no `partitions_def` in `with_resolved_tags_and_config`

python_modules/dagster-graphql/dagster_graphql/implementation/execution/run_lifecycle.py, python_modules/dagster/dagster/_cli/job.py, python_modules/dagster/dagster/_core/definitions/job_definition.py, python_modules/dagster/dagster/_core/definitions/run_request.py, python_modules/dagster/dagster/_core/execution/job_backfill.py, python_modules/dagster/dagster/_core/execution/submit_asset_runs.py, python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster/_core/remote_representation/code_location.py, python_modules/dagster/dagster/_core/test_utils.py, python_modules/dagster/dagster/_daemon/sensor.py, python_modules/dagster/dagster/_scheduler/scheduler.py, python_modules/dagster/dagster_tests/core_tests/definitions_tests/test_run_request.py, python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py, python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py, python_modules/dagster/dagster_tests/launcher_tests/test_default_run_launcher.py, python_modules/dagster/dagster_tests/launcher_tests/test_persistent_grpc_run_launcher.py
Small refactor that makes replaces the `asset_job_partitions_def: PartitionsDefinition` argument on `create_external_run` with an `asset_graph: AssetGraph` argument.
This reduces lines of code and also makes way for a world where a run can target assets with different `PartitionsDefinitions`, e.g. `DailyPartitionsDefinitions` with different start dates.
=> [single-implicit-asset-job] `create_external_run` accept asset graph, not partitions def

python_modules/dagster/dagster/_core/definitions/asset_job.py, python_modules/dagster/dagster/_core/definitions/job_definition.py, python_modules/dagster/dagster/_core/definitions/unresolved_asset_job_definition.py
`build_asset_job` builds a `JobDefinition` from a set of assets. Previously, it would error if the assets targeted by the job had different `PartitionsDefinition`s. This change adds a flag that basically suppresses this error.
In downstream PR https://github.com/dagster-io/dagster/pull/23293, which makes a single implicit asset job, this flag is used by the code paths that build implicit asset jobs. Farther into the future, when we're ready to allow users to make jobs with assets with different `PartitionsDefinition`s, we'll remove this flag entirely and never raise this error.
=> [single-implicit-asset-job] allow different partitions_defs on `build_asset_job`

python_modules/dagster/dagster/_core/definitions/asset_job.py, python_modules/dagster/dagster/_core/definitions/job_definition.py, python_modules/dagster/dagster/_core/definitions/unresolved_asset_job_definition.py, python_modules/dagster/dagster/_core/execution/context/system.py
In the case where a job doesn't have a `partitions_def`, but the asset inside it being executed does have a `partitions_def`, we want to use the `partitions_def` from the asset.
This requires moving `partition_time_window` from the plan context, which doesn't have access to the asset being executed, to the step context, which does.
=> [single-implicit-asset-job] in `context.partition_time_window`, use `partitions_def` from asset

js_modules/dagster-ui/packages/ui-core/src/app/time/TimeContext.tsx, js_modules/dagster-ui/packages/ui-core/src/insights/InsightsBarChart.tsx, js_modules/dagster-ui/packages/ui-core/src/insights/InsightsBarChartTooltip.tsx, js_modules/dagster-ui/packages/ui-core/src/insights/__stories__/InsightsBarChart.stories.tsx, js_modules/dagster-ui/packages/ui-core/src/schedules/TimestampDisplay.tsx
Fixing a bug I overlooked on Insights bar charts for asset metadata: the tooltip timezone and hour-cycle format are incorrect, as they are based on the default browser values instead of the user's settings. Fix this by passing the values through to the tooltip, which is rendered without the time context available.
Storybook example with an arbitrary timezone chosen. Verify on hover that the timezone and hour-cycle format are correct, matching the x axis of the chart.
=> [ui] Insights: Fix bar chart tooltip timezone

python_modules/dagster/dagster/_core/definitions/asset_out.py, python_modules/dagster/dagster/_core/definitions/asset_spec.py, python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_partitioned_assets.py, python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/scenario_state.py
Adds a `partitions_def` attribute to `AssetSpec`. This is a step towards deprecating `SourceAsset` in favor of `AssetSpec`.
The biggest question this raises is what happens to `@multi_asset`, which accepts `AssetSpec`s and also a `partitions_def` argument. This PR retains the constraint that all the assets within a multi-asset must have the same `partitions_def`, though I hope to relax it soon after.
Valid parameter combinations for `@multi_asset`:
- `partitions_def` passed to `@multi_asset` is `None`, and `partitions_def`s passed to individual `AssetSpec`s are all none -> use `None`.
- `partitions_def` passed to `@multi_asset` is X, and `partitions_def`s passed to individual `AssetSpec`s are all `None` -> use X.
- `partitions_def` passed to `@multi_asset` is X, and `partitions_def`s …
=> [1.8][external assets] partitions_def on AssetSpec

js_modules/dagster-ui/packages/ui-core/src/runs/useRunsForTimeline.tsx
We are currently retrieving too many runs for the run timeline due to our usage of `updated` time for windowing. (We should use start/end times instead, and an upcoming fix will handle this.)
These excess completed runs show up as a big chunk at the left side of the timeline.
To resolve this (for now), filter out runs (post-query) that don't belong in the visible window.
View timeline with lots of runs. Verify that the incorrect chunk of runs is no longer present on the timeline.
=> [ui] Filter out runs that are too old for timeline window

js_modules/dagster-ui/packages/ui-core/src/overview/GroupTimelineRunsBySelect.tsx, js_modules/dagster-ui/packages/ui-core/src/overview/OverviewTimelineRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/overview/useGroupTimelineRunsBy.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/useRunsForTimeline.tsx
Make it possible to toggle between grouping "by job" and "by automation" in the Run timeline.
If grouping by automation, the  fallback "ad hoc materializations" bucket is eliminated, and "Manually launched" is used to group runs that have no associated automation (sensor, schedule, AMP).
View run timeline, verify that toggling between group-by options works correctly.
=> [ui] Allow control of run timeline grouping

python_modules/dagster/dagster/_core/execution/context/op_execution_context.py
bumps the breaking version for removing AssetExecutionContext inheritance to 1.9
=> update asset execution context inheritance deprecation warning to 1.9

docs/content/concepts/ops-jobs-graphs/graphs.mdx, docs/content/guides/dagster/how-assets-relate-to-ops-and-graphs.mdx, examples/docs_snippets/docs_snippets/guides/dagster/assets_ops_graphs/op_graph_asset_input.py, python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/composition.py, python_modules/dagster/dagster_tests/core_tests/graph_tests/test_graph_source_asset_input.py
It's currently possible to pass a `SourceAsset` as an input in an op graph: https://docs.dagster.io/concepts/ops-jobs-graphs/graphs#loading-an-asset-as-an-input.
Like this:
```python
from dagster import asset, job, op
@asset
def emails_to_send(): ...
@op
def send_emails(emails) -> None: ...
@job
def send_emails_job():
send_emails(emails_to_send.to_source_asset())
```
`SourceAsset`s are being replaced by `AssetSpec`s, so this PR enables the same with `AssetSpec`s.
=> [1.8][external assets] enable passing `AssetSpec`s as graph inputs

js_modules/dagster-ui/packages/ui-core/src/assets/AssetPageHeader.oss.tsx
Force the `Breadcrumbs` items in the asset view header to render with `MiddleTruncate` to ensure that long keys in the path still show up. Otherwise, we can end up using the entire width with a single key and every breadcrumb gets pushed into the overflow menu.
Also tweaked the overflow menu to match popover behavior from our other components.
View assets with very long key elements in their paths, verify that middle truncate behaves correctly. It's not perfect because the middle-truncated strings have a little excess horizontal space in some cases, but it's an improvement.
=> [ui] Repair asset header breadcrumbs for long key strings

docs/content/concepts/assets/external-assets.mdx, examples/docs_snippets/docs_snippets/concepts/assets/external_assets/external_asset_deps.py, examples/docs_snippets/docs_snippets/concepts/assets/external_assets/external_asset_using_sensor.py, examples/docs_snippets/docs_snippets/concepts/assets/external_assets/normal_asset_depending_on_external.py, examples/docs_snippets/docs_snippets/concepts/assets/external_assets/single_declaration.py, examples/docs_snippets/docs_snippets/concepts/assets/external_assets/update_external_asset_via_op.py
Replaces them with direct usage of `AssetSpec`, which is enabled by https://github.com/dagster-io/dagster/pull/22961.
=> [1.8][external assets] remove `external_assets_from_specs` from concept docs

examples/assets_dbt_python/dagster_cloud.yaml, examples/assets_modern_data_stack/dagster_cloud.yaml, examples/experimental/external_assets/dagster_cloud.yaml
Following the fix in #23325
Some examples that were updated in #23155 and #20809 have a `dagster_cloud.yaml` file. This PR makes sure that dagster_cloud.yaml is updated for examples that are now using `definitions.py` instead of `__init__.py`. Quickstart examples were fixed in #23325.
=> Update dagster_cloud.yaml to use definitions.py in examples

python_modules/dagster/dagster/_utils/caching_instance_queryer.py
We have a specialized storage implementation for querying updated data versions, which doesn't fetch full materialization/observation asset tag history.
BK... really relying on existing test coverage for this
=> switch to check data version history with optimized storage method against partitioned data versions

python_modules/dagster/dagster/_core/definitions/decorators/source_asset_decorator.py, python_modules/dagster/dagster/_core/definitions/source_asset.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_job.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_materialize.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_partitioned_assets.py
`AssetSpec` can now be used instead.
=> [1.8][external assets] deprecate SourceAsset

examples/experimental/dagster-airlift/airflow_setup.sh, examples/experimental/dagster-airlift/conftest.py, examples/experimental/dagster-airlift/dagster_airlift/shared_fixtures.py, examples/experimental/dagster-airlift/dagster_airlift_tests/conftest.py, examples/experimental/dagster-airlift/dagster_airlift_tests/test_airflow_utils.py, examples/experimental/dagster-airlift/examples/peering-with-dbt/Makefile, examples/experimental/dagster-airlift/examples/peering-with-dbt/conftest.py, examples/experimental/dagster-airlift/examples/peering-with-dbt/peering_with_dbt_tests/conftest.py
Moves shared implementation to a shared fixture directory, and switches how we determine when airflow is stood up. This speeds up tests to take a few seconds instead of >20 minutes.
=> [dagster-airlift] improve unit test speed

examples/experimental/dagster-airlift/airflow_setup.sh, examples/experimental/dagster-airlift/conftest.py, examples/experimental/dagster-airlift/dagster_airlift/airflow_utils.py, examples/experimental/dagster-airlift/dagster_airlift/shared_fixtures.py, examples/experimental/dagster-airlift/dagster_airlift_tests/airflow_project/dags/simple_dag.py, examples/experimental/dagster-airlift/dagster_airlift_tests/conftest.py, examples/experimental/dagster-airlift/dagster_airlift_tests/test_airflow_utils.py, examples/experimental/dagster-airlift/examples/peering-with-dbt/Makefile, examples/experimental/dagster-airlift/examples/peering-with-dbt/conftest.py, examples/experimental/dagster-airlift/examples/peering-with-dbt/peering_with_dbt_tests/conftest.py
Fixes the materialization reporting order for asset keys mapped from airflow tasks to instead be topological.
Added a very basic test where a dependency between two tasks should always yield the downstream task being added after the upstream.
=> [dagster-airlift] Fix materialization reporting order for tasks

examples/experimental/dagster-airlift/dagster_airlift/__init__.py, examples/experimental/dagster-airlift/dagster_airlift/airflow_utils.py, examples/experimental/dagster-airlift/dagster_airlift_tests/test_airflow_utils.py, examples/experimental/dagster-airlift/examples/peering-with-dbt/peering_with_dbt/dagster_defs/definitions.py
Add AirflowInstance API, which vends out access to the airflow rest API.
This paves the way for having multiple auth backends supporting airlift utilities. Also just happens to feel nicer api-wise.
=> [dagster-airlift] AirflowInstance

python_modules/dagster/dagster/_core/definitions/events.py
It's typed as `Optional`, but we runtime-check that it's not `None`.
=> fix type annotation on `output_name` arg of `Output`

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNode.tsx
This turned out controversial, because of the alternative of introducing a new `kinds` attribute. So walking this back.
=> take storage_kind label off the asset node

python_modules/dagster/dagster/_core/executor/multiprocess.py, python_modules/dagster/dagster_tests/launcher_tests/test_default_run_launcher.py
Summary:
The dagster signal handler raises interrupts as DagsterExecutionInterruptedError, but sometimes ops can run code that installs its own signal handler, causing the interrupt to be raised as a KeyboardInterrupt (for example, the snowflake python connector does this: https://github.com/snowflakedb/snowflake-connector-python/blob/main/src/snowflake/connector/cursor.py#L663-L684). Handle both in the logic that decides if a run terminated cleanly or not.
Resolves https://github.com/dagster-io/dagster/issues/23406.
Test Plan: BK
=> Accept KeyboardInterruptError in multiprocess executor termination logic

python_modules/dagster/dagster/_core/events/__init__.py, python_modules/dagster/dagster/_core/execution/api.py, python_modules/dagster/dagster/_core/executor/child_process_executor.py, python_modules/dagster/dagster/_core/executor/multiprocess.py, python_modules/dagster/dagster_tests/launcher_tests/test_default_run_launcher.py
Summary:
The terminal event after
Once a user indicates that they want a run to terminate from the UI or via the API, if there's an exception that would normally fail the run, the run should still enter CANCELED rather than FAILURE. This ensures that retries will never fire after a run is put into a CANCELING state.
=> Transition runs to CANCELED rather than FAILURE if they fail after a user-initiated run cancellation

python_modules/dagster/dagster/_serdes/serdes.py, python_modules/dagster/dagster_tests/general_tests/test_serdes.py
`@record` classes are considered `PackableValue` thanks to `DataclassInstance`, but this doesn't cover `@record_custom` which currently causes type errors. To solve this we add the marker class `IHaveNew` that all `@record_custom` classes are expected to subclass to the `PackableValue` and `UnpackedValue` `Union`s.
added `-> None` to a test that previously caused type errors
=> [serdes] typehints to handle @record_custom

examples/experimental/dagster-airlift/dagster_airlift/airflow_utils.py, examples/experimental/dagster-airlift/dagster_airlift/mwaa/__init__.py, examples/experimental/dagster-airlift/dagster_airlift/mwaa/auth_backend.py, examples/experimental/dagster-airlift/dagster_airlift_tests/test_airflow_utils.py, examples/experimental/dagster-airlift/dagster_airlift_tests/test_mwaa_auth.py, examples/experimental/dagster-airlift/examples/peering-with-dbt/peering_with_dbt/dagster_defs/definitions.py, examples/experimental/dagster-airlift/setup.py, examples/experimental/dagster-airlift/tox.ini
Stacks on top of AirflowInstanceAPI to add a MwaaAuthBackend.
Requires vending webserver url from the backend instead of passing it directly, since this is procured from the session info in mwaa.
Tested this manually with our running mwaa instance, and verified that dag peering works. Example code:
```python
import os
from dagster import Definitions
from dagster_airlift import AirflowInstance, assets_defs_from_airflow_instance
from dagster_airlift.mwaa import MwaaSessionAuthBackend
os.environ["AWS_PROFILE"] = "the-profile-containing-mwaa"
mwaa_env = "mwaa-test-env"
assets=assets_defs_from_airflow_instance(
airflow_instance=AirflowInstance(
auth_backend=MwaaSessionAuthBackend(region="us-west-2", env_name=mwaa_env),
name=mwaa_env,
)
)
)
```
=> [dagster-airlift] mwaa auth backend

python_modules/automation/tox.ini
The library didn't make the branch cut.
=> Remove dagster-powerbi from release-1.8.0

python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py
Issue caught in dogfooding: prior to this PR, you'd hit an error if you tried to pass two `AssetSpec`s with different `partitions_def`s to the same `Definitions` object.
I hope that soon we'll be able to remove the single-`PartitionsDefinition` per `AssetsDefinition` constraint.
=> [1.8] support AssetSpecs with different partitionings in same Definitions

examples/experimental/dagster-airlift/dagster_airlift/__init__.py, examples/experimental/dagster-airlift/dagster_airlift/core/def_factory.py, examples/experimental/dagster-airlift/dagster_airlift/core/multi_asset.py, examples/experimental/dagster-airlift/dagster_airlift/dbt/multi_asset.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_dbt_multi_asset.py, examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/python_multi_assets_yaml/asset_specs/test_dag/test_dag__test_task.yaml, examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_python_multi_assets.py, examples/experimental/dagster-airlift/examples/peering-with-dbt/peering_with_dbt/dagster_defs/definitions.py, examples/experimental/dagster-airlift/examples/peering-with-dbt/peering_with_dbt/dagster_defs/defs/dbt_dag__build_dbt_models.yaml, examples/experimental/dagster-airlift/examples/peering-with-dbt/peering_with_dbt/dagster_defs/defs/load_lakehouse__load_iris.yaml, examples/experimental/dagster-airlift/examples/peering-with-dbt/tox.ini, examples/experimental/dagster-airlift/setup.py, examples/experimental/dagster-airlift/tox.ini
Eliminate blueprints dependency in airlift. Made the decision to make to `dataclass` from pydantic so we could use bare classes instead of having a wrapper set of classes to avoid pydantic forward ref issues.
BK
=> Eliminate blueprints dep

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/resources.py, python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/sling_event_iterator.py
Adds `SlingEventIterator` class which we can use to chain subsequent computation on Sling syncs. Motivated by stacked PR #23388.
Existing unit tests, inspect in editor to make sure type hints are happy.
=> [1/p][dagster-embedded-etl] add SlingEventIterator

js_modules/dagster-ui/packages/ui-components/src/components/ProductTour.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetPageHeader.oss.tsx
1. Don't propagate click events from the popover of ProductTour since by default blueprint's `Popover` seems to bubble them up to the element its wrapping (super weird!).
2. Remove overflow: hidden from the AssetPageHeader because this wraps a button that uses outerglow on hover and the overflow hidden ends up hiding the outerglow making it look weird.
=> Don't propagate click events from popover + remove unnecessary overflow hidden

js_modules/dagster-ui/packages/ui-core/src/runs/getRunFilterProviders.ts
Related: https://linear.app/dagster-labs/issue/FE-374/hide-planned-events-from-filter-typeahead-in-log-viewer
I verified that these logs are already filtered out of the log view itself, but they were not filtered from the typeahead text input above the log view. This list is mostly synthesized from the enum itself, so I added a filter to remove them.
Confirmed that they are no longer listed in the typeahead
=> [ui] Hide “materialization planned” events from the log filter bar

python_modules/libraries/dagster-snowflake-pyspark/dagster_snowflake_pyspark/constants.py, python_modules/libraries/dagster-snowflake-pyspark/dagster_snowflake_pyspark/snowflake_pyspark_type_handler.py, python_modules/libraries/dagster-snowflake-pyspark/dagster_snowflake_pyspark_tests/test_get_snowflake_options.py, python_modules/libraries/dagster-snowflake/dagster_snowflake/constants.py, python_modules/libraries/dagster-snowflake/dagster_snowflake/resources.py, python_modules/libraries/dagster-snowflake/dagster_snowflake_tests/test_ops.py, python_modules/libraries/dagster-snowflake/dagster_snowflake_tests/test_resources.py, python_modules/libraries/dagster-snowflake/tox.ini
As part of a partnership initiative with Snowflake, we'd like to track usage that originates from Dagster Snowflake integrations. 
- BK
- Validation from Snowflake specialists that connections are observed.
=> feat: add snowflake partner connection id to snowflake lib

python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster_tests/storage_tests/test_compute_log_manager.py
We've long since issued deprecation warnings on the legacy compute log manager interface.  This actually asserts that we have the captured log manager interface on all implementing instances.
The goal here (of this stack) is to:
1. Assert that we have implemented the new interface `CapturedLogManager`
2. Remove all callsites of the old interface
4. Replace all code for the old interface implementations
5. Shift the abstract interface from `CapturedLogManager` into the `ComputeLogManager`
This PR is step 1.
BK
=> assert that instance references captured log manager interface

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/dlt/translator.py, python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/dlt_tests/test_asset_decorator.py
For dlt `@dlt.transformer` resources, we currently generate upstream asset keys matching the transformer name. This usually doesn't map to the actual upstream source since the data is a transformation of other resources. For example, the course reviews here in reality comes from the same data source as courses:
This PR updates that mapping by walking up the list of parent resources and using the outermost, raw resource for the key name.
New unit test.
=> [dagster-embedded-elt] for dlt transformers, use base resource as parent

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/dlt/translator.py, python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/dlt_tests/dlt_test_sources/duckdb_with_transformer.py, python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/dlt_tests/test_asset_decorator.py
Little QoL feature for dlt assets - if a docstring is defined on the dlt resource, we'll pull it as the default asset description.
The mapping here is a little imprecise, since technically the docstring is describing the generic resource on the source class and not the specific instantiation (e.g. for GitHub, what repos we're looking at), but users can always customize that with a translator.
New unit test.
=> [dagster-embedded-elt] load docstrings as default dlt resource descriptions

examples/experimental/sling_decorator/sling_decorator/definitions.py, python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/resources.py, python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/sling_event_iterator.py, python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/sling_tests/test_asset_decorator.py, python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/sling_tests/test_fetch_metadata.py
After SQL modeling/transform integrations like dbt, ELT seems like an obvious place to drop in table metadata and extend Dagster's awareness of column lineage. This PR explores that direction with Sling, which helps expand column lineage in our own DOP data platform.
Adds a chain-able metadata fetch method for Sling syncs which attaches column schema and column lineage to assets output from a Sling sync.
```python
@sling_assets(replication_config=replication_config)
def my_assets(context, sling: SlingResource):
yield from sling.replicate(context=context).fetch_column_metadata()
```
Under the hood, invokes `sling conns discover [target conn] --pattern [target stream] --columns`, which uses Sling's underlying db adapters to fetch this metadata.
Lineage is inferred as 1:1 for all columns …
=> [2/p][dagster-embedded-etl] add ability to fetch columnar metadata for Sling assets

python_modules/dagster-graphql/dagster_graphql/schema/solids.py
Summary:
This locally fixes an issue introduced in https://github.com/dagster-io/dagster/pull/22747 that we were seeing where two separate dbt_assets with different subsets of the same manifest resulted in jobs without any assets attached to them. Still need to create a test that reproduces the problem.
=> Attempt to fix issue where asset nodes were getting incorrectly mapped to solids

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/resources.py
- remove experimental flag from `SlingResource` introduced in November, 2023
=> [sling] rm experimental decorator on SlingResource

python_modules/dagster-webserver/dagster_webserver/webserver.py, python_modules/dagster-webserver/dagster_webserver_tests/webserver/test_app.py, python_modules/dagster/dagster/_core/definitions/instigation_logger.py, python_modules/dagster/dagster/_core/execution/plan/execute_plan.py, python_modules/dagster/dagster/_core/storage/captured_log_manager.py, python_modules/dagster/dagster/_core/storage/compute_log_manager.py
This PR strips out the legacy compute log manager interface from the critical engine paths.
This includes:
1. the execution engine
2. the instigation logger path
3. the webserver / subscriptions
BK
=> update core callsites for compute log manager

python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster/_core/storage/event_log/base.py, python_modules/dagster/dagster/_core/storage/event_log/in_memory.py, python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py, python_modules/dagster/dagster/_core/storage/event_log/sqlite/sqlite_event_log.py, python_modules/dagster/dagster/_core/storage/legacy_storage.py, python_modules/dagster/dagster_tests/storage_tests/test_event_log.py, python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py, python_modules/libraries/dagster-postgres/dagster_postgres/event_log/event_log.py
Reverts dagster-io/dagster#23206
I believe we decided on a different approach here - reverting so I can back it out of 1.8.0
=> Revert "Return storage ID when adding to the event log"

js_modules/dagster-ui/packages/ui-core/src/assets/AssetEventMetadataEntriesTable.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/filterLogs.tsx
Related:  https://linear.app/dagster-labs/issue/FE-484/run-logs-search-doesnt-search-through-dictionary-logs
I implemented this in a pretty generic way so that we won't have to revisit this each time we add new events, BUT I think it'd also be fairly straightforward to write a big-ol switch statement that stringifies each unique type, down to switch to that if my "stringify all the metadata entry values" thing is too whacky :-) 
I tested this using a bunch of real-world run logs:
Examples:
A value or the key or both
A value inside "Show JSON"
=> [ui] Allow filtering run logs for metadata entry keys and values

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/dlt/asset_decorator.py
- Gives user more notice of this change.
=> [dlt] bump param deprecation warning for legacy translator name to 1.9

python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/dbt_packages/test_columns_metadata.py
The column lineage tests take a long time to run in our test suite. For the sake of speed, pare down the existing test suite by removing dialect tests against redshift and clickhouse.
pytest
=> test(dbt): remove column lineage tests against redshift and clickhouse

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py, python_modules/libraries/dagster-dbt/setup.py
Start testing `dagster-dbt` against python 3.12.
bk
=> chore(dbt): support python 3.12

js_modules/dagster-ui/packages/ui-components/src/components/TextInput.tsx, js_modules/dagster-ui/packages/ui-components/src/components/__stories__/TextInput.stories.tsx
Repair some slightly incorrect box-shadow values on `TextInput` and `TextArea`.
- The styled text input should have an inset box-shadow, but we appear to have overlooked this at some point. Fixing this allows the input and button controls to have the same default height, thus repairing the bug that brought this to our attention.
- Note that this effectively takes the `TextInput` height down from 34px to 32px, which may be noticeable in some parts of the app. It's more correct and consistent, but if there are places where we're depending on the incorrect height for alignment etc, we might notice some knock-on effects that we should clean up.
- I also reduced the focus ring box-shadow to 2px, again to match `Button`.
- The `TextArea` component has been ignoring its `strokeColor` prop, so …
=> [ui] Repair box-shadow on TextInput and TextArea

python_modules/libraries/dagster-shell/dagster_shell/ops.py, python_modules/libraries/dagster-shell/dagster_shell_tests/test_ops.py
deprecate dagster-shell integration in favor of Dagster Pipes subprocess.
specifically, this PR throws deprecation warnings in:
- `create_shell_command_op`
- `create_shell_script_op`
- unit test
- <img width="1358" alt="image" src="https://github.com/user-attachments/assets/3446aed8-684c-44b8-8b2a-a33ef04cfe0a">
=> deprecate dagster-shell integration

docs/dagster-university/pages/dagster-dbt/lesson-2/2-set-up-the-dagster-project.md
fastparquet requires admin privileges on PCs, and it isn't required for this course.
=> [du] remove fastparquet dependency [DEV-414]

js_modules/dagster-ui/packages/ui-core/src/runs/HourlyDataCache/HourlyDataCache.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/HourlyDataCache/__tests__/HourlyDataCache.test.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/__tests__/useRunsForTimeline.test.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/useRunsForTimeline.tsx
1. Add a version parameter to `HourlyDataCache`
2. If the version in the indexeddb cache  doesn't match the version in code then don't use the indexeddb cache data at all
3. Add version parameter to useRunTImeline
Loaded the run timeline using app-proxy and saw that the cache was cleared. Subsequent loads used the cache
=> Bust RunTimeline cache

python_modules/dagster/dagster/_core/remote_representation/external_data.py, python_modules/dagster/dagster/_core/snap/node.py
Resolves https://github.com/dagster-io/dagster/issues/22763#issuecomment-2260955966.
Experimental warnings shouldn't show up when constructing serializable representations of Dagster definitions.
- If experimental warnings are suppressed at definition time, they shouldn't appear at serialization time.
- Experimental warnings should be actionable from the location that they are emitted. When an warning is emitted in the serialization layer, the user does not know what to do, as it is not code they control.
Run `PYTHONWARNINGS=default dagster dev` for jaffle shop dbt, see no dagster warnings in the serialization layer.
Unsure to do this in an automated way. Also wonder if there's a better way to do this rather than dispersing this `suppress_dagster_warnings` decorator out.
=> feat: suppress dagster warnings when constructing serializable representations

examples/experimental/dagster-airlift/dagster_airlift/__init__.py, examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py, examples/experimental/dagster-airlift/dagster_airlift/core/defs_from_airflow.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_cacheable_asset.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_peering.py, examples/experimental/dagster-airlift/examples/peering-with-dbt/peering_with_dbt/dagster_defs/definitions.py
Rename the function `create_defs_from_airflow_instance` to `build_defs_from_airflow_instance`, and add a docstring.
For the sake of consistency with other defs builders, a la build_freshness_checks and kin.
=> [dagster-airlift] build_defs rename and docstring

python_modules/dagster-webserver/dagster_webserver/cli.py
Seeing the following error locally:
```diff
Downloads/projects/jaffle_dagster 🐍 (dagster)
❯ PYTHONWARNINGS=default dagster dev
2024-08-07 16:23:42 -0400 - dagster - INFO - Using temporary directory /Users/rexledesma/Downloads/projects/jaffle_dagster/tmpqbravcfj for storage. This will be removed when dagster dev exits.
2024-08-07 16:23:42 -0400 - dagster - INFO - To persist information across sessions, set the environment variable DAGSTER_HOME to a directory to use.
2024-08-07 16:23:42 -0400 - dagster - WARNING - /Users/rexledesma/dagster-labs/dagster/python_modules/dagster/dagster/_core/storage/sqlalchemy_compat.py:13: RemovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating …
```
=> chore: remove starlette lifespan warning

examples/experimental/dagster-airlift/dagster_airlift/__init__.py, examples/experimental/dagster-airlift/dagster_airlift/core/__init__.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_peering.py, examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_migration_state.py, examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_python_multi_assets.py, examples/experimental/dagster-airlift/examples/peering-with-dbt/peering_with_dbt/dagster_defs/definitions.py, examples/experimental/dagster-airlift/examples/peering-with-dbt/tox.ini, examples/experimental/dagster-airlift/setup.py, examples/experimental/dagster-airlift/tox.ini
Moves airlift core into it's own submodule. The in-dagster side should exist as its own component (which is core), and then the in-airflow side should exist as its own component.
=> [dagster-airlift] core submodule

js_modules/dagster-ui/packages/app-oss/tsconfig.json, js_modules/dagster-ui/packages/eslint-config/rules/no-oss-imports.js, js_modules/dagster-ui/packages/ui-core/jest.config.js, js_modules/dagster-ui/packages/ui-core/src/app/AppTopNav/AppTopNav.tsx, js_modules/dagster-ui/packages/ui-core/src/app/ContentRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/app/UserSettingsDialog/UserSettingsDialog.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphExplorerFilters.oss.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetGroupRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetTable.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetsGroupsGlobalGraphRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetsOverviewRoot.oss.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/filterAssetDefinition.test.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/useAssetCatalogFiltering.oss.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/useWipeModal.tsx, js_modules/dagster-ui/packages/ui-core/src/overview/OverviewAssetsRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/overview/OverviewPageHeader.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/RunActionsMenu.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/RunHeaderActions.tsx, js_modules/dagster-ui/packages/ui-core/tsconfig.json
I added `baseUrl` to make `src/...` imports work in OSS, instead of using baseUrl lets use paths with a regex.
This makes it so that we stop automatically recommending imports that start with "src/..."
yarn ts
=> [tsconfig] Remove base url from  tsconfig + src -> shared

python_modules/dagster/dagster/_core/scheduler/instigation.py, python_modules/dagster/dagster/_daemon/sensor.py, python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_failure_recovery.py, python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
This ports over a set of logic from the AssetDaemon, which stashes information on the tick in order to keep track of the runs that we want to request before we actually make the request.
Then, if the tick fails partway through submitting runs, the next time we execute we can pull the previous tick data and see that there were runs which we wanted to submit but were not able to. Then, instead of evaluating the sensor again, we can do a separate step to attempt to submit those unsubmitted runs once more.
=> [sensor-upgrades][2/n] Allow failed ticks to be resumed

python_modules/dagster/dagster/_core/definitions/run_request.py, python_modules/dagster/dagster/_core/definitions/sensor_definition.py, python_modules/dagster/dagster/_daemon/sensor.py
The UserCodeAutomationConditionSensorDefinition needs to be able to return the set of evaluations that were made during its tick (regardless of if it's managed by the sensor daemon or asset daemon -- currently it simply doesn't work). This adds a new field to the result object to allow us to return that information. It is implemented as a hidden parameter of the SensorResult object so that only framework code sets it. 
While this may at first glance seem overfit to one particular type of sensor, I'm imagining a future world in which you could have regular sensors also evaluate AutomationConditions, and which would also want to emit this type of information.
This uses the same failure-handling model as the Asset Daemon, in which we write the evaluations before submitting any runs, so that …
=> [sensor-upgrades][3/n] Add automation_condition_evaluations to SensorExecutionData & co.

python_modules/libraries/dagster-aws/dagster_aws/pipes.py, python_modules/libraries/dagster-aws/dagster_aws_tests/pipes_tests/fake_glue.py, python_modules/libraries/dagster-aws/dagster_aws_tests/pipes_tests/test_pipes.py
I decided it was a good idea to add an automatic Glue job cleanup handler as there is a change for Spark jobs to spend a lot of unnecessary resources otherwise.
Had to rewrite the fake Glue clients to implement non-blocking job execution via `subprocess.Popen`
Strong Inception vibes in this PR
=> [dagster-aws] Pipes AWS Glue Dagster run interruption handler

python_modules/dagster/dagster/_core/definitions/auto_materialize_sensor_definition.py, python_modules/dagster/dagster/_core/definitions/sensor_definition.py, python_modules/dagster/dagster/_core/storage/dagster_run.py, python_modules/dagster/dagster/_daemon/asset_daemon.py, python_modules/dagster/dagster/_daemon/sensor.py, python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_user_space_ds_api.py
As title -- this builds on the previous PRs which allow regular sensors to emit AutomationConditions and take advantage of checkpointing logic. Now, we flip a switch to have these user code sensors evaluated in the Sensor Daemon insteaad of the Asset Daemon.
We can consider moving the non-user code verison of these sensors to the Sensor Daemon at a later point.
=> [sensor-upgrades][4/n] Move UserCodeAutomationConditionSensorDefinition to Sensor Daemon

CHANGES.md
I think we need this to satisfy our linter
=> Add the 1.8.0 header

examples/docs_snippets/docs_snippets_tests/tutorial_tests/connecting/test_resources.py, python_modules/dagster/dagster/_config/pythonic_config/__init__.py, python_modules/dagster/dagster/_config/pythonic_config/io_manager.py, python_modules/dagster/dagster/_config/pythonic_config/resource.py, python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster/_core/definitions/decorators/repository_decorator.py, python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster/_core/definitions/job_definition.py, python_modules/dagster/dagster/_core/definitions/materialize.py, python_modules/dagster/dagster/_core/definitions/repository_definition/repository_data.py, python_modules/dagster/dagster/_core/definitions/repository_definition/repository_data_builder.py, python_modules/dagster/dagster/_core/definitions/repository_definition/repository_definition.py, python_modules/dagster/dagster/_core/definitions/resource_definition.py, python_modules/dagster/dagster/_core/definitions/resource_invocation.py, python_modules/dagster/dagster/_core/definitions/resource_requirement.py, python_modules/dagster/dagster/_core/definitions/source_asset.py, python_modules/dagster/dagster/_core/execution/context/init.py, python_modules/dagster/dagster/_core/execution/resources_init.py, python_modules/dagster/dagster/_core/remote_representation/external_data.py, python_modules/dagster/dagster/_core/types/config_schema.py, python_modules/dagster/dagster_tests/core_tests/host_representation_tests/test_custom_repository_data.py, python_modules/dagster/dagster_tests/core_tests/resource_tests/pythonic_resources/test_nesting.py, python_modules/dagster/dagster_tests/core_tests/resource_tests/test_with_resources.py, python_modules/dagster/dagster_tests/core_tests/test_job_init.py
This changes the scheme for how we resolve shared references to nested partially configured resource objects/dependencies.
Previously we would  create (in `Definitions` only) a map from object `id(...)` to resource key which would get bound using a collection of  `*WithKeyMapping` classes.
The new approach adds a `PartialResourceDependencyRequirement` to model the partial resource dependency and then makes the full set of resources available on to `InitResourceContext` and via a new `get_required_resource_keys(resource_defs)` to be able to resolve this dependency type. This scheme depends on  the memoization of `get_resource_definition` making it possible to do `is` comparisons for object equality. 
`ResourceRequirements` gains a new parent class with `ResourceKeyRequirement` to split the …
=> rework partial resource resolution

js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/useAllAssets.test.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetsCatalogTable.types.ts, js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_selections.py, python_modules/dagster-graphql/dagster_graphql/schema/roots/assets.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_assets.ambr, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
Summary:
The frontend passes in an ID which may have been emitted by get_unique_asset_id, which prepends a prefix before the path starts. Fix the asset key normalizer to account for that case.
=> Use a separate cursor field when paginating through the asset catalog

docs/content/_navigation.json, docs/content/concepts.mdx, docs/content/concepts/assets/external-assets.mdx
Takes the experimental marker off the concept page and associated links.
=> take experimental marker off of external assets in docs

examples/with_openai/setup.py
Required for PR #23207.
Pip's message "langchain-community 0.2.9 requires langchain<0.3.0,>=0.2.9, but you have langchain 0.2.7 which is incompatible."
Tested locally with dagster dev
=> Bump langchain version to 0.2.9 in with_openai

examples/experimental/dagster-airlift/Makefile, examples/experimental/dagster-airlift/build_and_publish.sh, examples/experimental/dagster-airlift/increment_pypi_version.sh, examples/experimental/dagster-airlift/setup.py
Adds a bunch of tooling so that all you have to run is `make pypi_adhoc`, and all the cruft will be handled.
Updates the version number in setup.py, then writes out pypirc (prompting for creds), then uploads to pypi. Finally, if things fail, reverts setup.py changes.
Tested live, including pypirc setup. Correctly incremented everything.
=> [dagster-airlift] Add better pypi tooling

python_modules/dagster-webserver/dagster_webserver/graphql.py
This allows subclasses to override the `graphql_request_context()` method and inject code around the graphql handler. Specifically this code runs in the same thread as the graphph resolver. 
Existing tests should be sufficient, since we're not changing any behavior.
=> Add graphql_request_context context manager to allow hooks around graphql request handling

js_modules/dagster-ui/packages/ui-core/src/asset-graph/SidebarAssetInfo.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/__stories__/SidebarAssetInfo.stories.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/types/SidebarAssetInfo.types.ts, js_modules/dagster-ui/packages/ui-core/src/assets/AssetSidebarActivitySummary.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/AutoMaterializeExperimentalBanner.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/AutomaterializeMiddlePanel.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/auto-materialization/DeclarativeAutomationBanner.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/auto-materialization/GlobalAutomaterializationContent.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/DaemonList.tsx, js_modules/dagster-ui/packages/ui-core/src/sensors/SensorPageAutomaterialize.tsx
Remove some existing references to "Auto-materialize" and replace some others with information about Declarative Automation.
TS, lint.
=> [ui] Clean up Auto-materialize references

js_modules/dagster-ui/packages/app-oss/next.config.js
Forgot to update this alias to use `shared/` instead but in doing so realized that next.js automatically picks up the aliases from `tsconfig.json` so we don't actually need this alias here.
yarn build
=> Remove next.js src alias

.github/workflows/build-docs.yml
fix a typo in the docs build step added in https://github.com/dagster-io/dagster/pull/23117
docs builds in the docs-prod branch are faling because of this:
- https://github.com/dagster-io/dagster/actions/runs/10311108286/job/28544589300
- https://github.com/dagster-io/dagster/actions/runs/10307006075/job/28531327009
we didn't encounter this until now because there was no docs pushes since the PR was landed 
build should succeed on docs-prod branch
=> fix docs publish gh action

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py, examples/experimental/dagster-airlift/dagster_airlift/core/airflow_instance.py, examples/experimental/dagster-airlift/dagster_airlift/core/sensor.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_airflow_instance.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_cacheable_asset.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_peering.py
A few of the links were broken for airlift.
- There's not actually a tasks page, just a task instances page. So from the task definition, link to the dag page.
- Link directly to the logs for each task from the asset materialization.
- Test links against running airflow for correctness
=> [dagster-airlift] fix& test links

python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py
This parameter is now deprecated and redundant with partition defs provided on the assets. This avoids deprecation warnings when running tests.
=> remove `partitions_def` from `define_asset_job` in graphql test repo

docs/content/dagster-plus/insights/integrating-snowflake-and-dbt.mdx
Current docs for the Snowflake-dbt Dagster insights integration references BigQuery instead of Snowflake
=> fix: typo in Snowflake-dbt insights integration

python_modules/libraries/dagster-ge/setup.py, python_modules/libraries/dagster-pandas/dagster_pandas_tests/test_constraints.py, python_modules/libraries/dagster-pandas/setup.py, python_modules/libraries/dagster-pandera/setup.py, python_modules/libraries/dagster-wandb/setup.py
Pandera, Pandas, and `wandb` now support `numpy>=2`
https://github.com/wandb/wandb/releases/tag/v0.17.2
https://github.com/unionai-oss/pandera/releases/tag/v0.20.0
https://pandas.pydata.org/docs/whatsnew/v2.2.2.html#pandas-2-2-2-is-now-compatible-with-numpy-2-0
=> [dagster-pandera,dagster-pandas,dagster-wandb] remove `numpy` pin

js_modules/dagster-ui/packages/ui-core/src/app/AppTopNav/AppTopNavLinks.tsx, js_modules/dagster-ui/packages/ui-core/src/app/AppTopNav/AppTopNavRightOfLogo.oss.tsx, js_modules/dagster-ui/packages/ui-core/src/app/AppTopNav/useJobStateForNav.tsx, js_modules/dagster-ui/packages/ui-core/src/app/__fixtures__/useJobStateForNav.fixtures.tsx, js_modules/dagster-ui/packages/ui-core/src/app/__tests__/AppTopNav.test.tsx, js_modules/dagster-ui/packages/ui-core/src/app/__tests__/useJobStateForNav.test.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext.tsx
In the experimental navigation, don't show a "Jobs" top nav item if there are no jobs in the workspace.
Load app with default toys repo, verify that the Jobs item appears. Load app with a repo that only contains an asset, verify that it does not appear.
=> [ui] Hide Jobs item from nav if there are no jobs

python_modules/libraries/dagster-datahub/dagster_datahub/resources.py, python_modules/libraries/dagster-datahub/setup.py
This pydantic requirement is needlessly strict give that the usage of Field is only in one file and uses only two parameters of it (both of which have not changed since the Pydantic 2.0 upgrade). This needlessly strict requirement is making it so that this won't resolve with other packages that require pydantic 2.0. Can we please loosen this restriction?
Used the forked repo via pip
=> [dagster-datahub] (loosen pydantic requirement)

docs/content/concepts/webserver/graphql.mdx
For larger deployments, getting all runs isn't very useful nor is it very performant. While we work on shifting the API to require pagination, let's make sure our examples represent best practice.
=> Guide users toward paginated runs queries

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/conftest.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_cacheable_asset.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_transitive_asset_deps.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/transitive_asset_deps_dags/first.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/transitive_asset_deps_dags/second.py
Was previously not properly handling transitive cross dag dependencies between assets when linking the "dag" asset to its constituent task assets. 
Tested by creating a transitive dependency between two dags, and ensuring that the correct task assets are considered "leaves"
=> [dagster-airlift] handle transitive dependencies between cacheable assets

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py, examples/experimental/dagster-airlift/dagster_airlift/core/airflow_instance.py, examples/experimental/dagster-airlift/dagster_airlift/core/sensor.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/conftest.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_airflow_instance.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_peering.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_transitive_asset_deps.py
Made the AirflowInstance vended classes more composable so we're not throwing around raw dicts everywhere. Added some utilities to trigger and wait for the completion of airflow runs, which are used in tests (for now...)
Made some refactors to the sensor after realizing we don't actually want to report in topological order... we want to report in task order. So instead, retrieve per-task info about each execution. Better testing of this new method is forthcoming, but existing tests already exercise the codepath.
=> [dagster-airlift] AirflowInstance, sensor refactor

python_modules/libraries/dagster-sdf/dagster_sdf/sdf_information_schema.py
This PR fixes an issue where remote tables are not available in the `table-deps` output of the information schema but are still included as internal asset deps.
=> [dagster-sdf] minor fix for internal asset deps issue

examples/experimental/dagster-airlift/dagster_airlift/in_airflow/__init__.py, examples/experimental/dagster-airlift/dagster_airlift/in_airflow/mark_as_migrating.py, examples/experimental/dagster-airlift/dagster_airlift/migration_state.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/correctly_marked_dag/dags/marked.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/correctly_marked_dag/migration_state/marked_dag.yaml, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/incorrectly_marked_dag/dags/marked.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/incorrectly_marked_dag/migration_state/some_other_dag.yaml, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_migrating_dag_correctly_marked.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_migrating_dag_incorrectly_marked.py
Function that allows users to mark airflow dags as "migrating", and injects a tag into the dag with information about the migration.
When placing the tag in the dag, there are two options:
1. Construct a new dag using essentially a shallow copy of the old dag, and then inject this into global scope.
2. Inject a tag into the existing dag object you find in global scope using the mutability of airflow dag's data structures.
I prefer (2) in this approach, because the surface area is way lower than (1), and it should be relatively resistant to changes in airflow's API other than this one tiny surface area ([which hasn't changed since 1.10, when tags were first introduced)](https://airflow.apache.org/docs/apache-airflow/1.10.10/_modules/airflow/models/dag.html#DAG). Unless we can figure out a …
=> [dagster-airlift] mark dags as migrating

examples/experimental/dagster-airlift/dagster_airlift/in_airflow/__init__.py, examples/experimental/dagster-airlift/dagster_airlift/in_airflow/dagster_operator.py, examples/experimental/dagster-airlift/dagster_airlift/in_airflow/gql_queries.py, examples/experimental/dagster-airlift/dagster_airlift/in_airflow/mark_as_migrating.py, examples/experimental/dagster-airlift/dagster_airlift/migration_state.py, examples/experimental/dagster-airlift/dagster_airlift/test/shared_fixtures.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/conftest.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/correctly_marked_dag/dags/marked.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/correctly_marked_dag/migration_state/marked_dag.yaml, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/incorrectly_marked_dag/dags/marked.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/incorrectly_marked_dag/migration_state/some_other_dag.yaml, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/operator_test_project/dags/migrated_dag.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/operator_test_project/dagster_defs.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_dagster_operator.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_migrating_dag_correctly_marked.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_migrating_dag_incorrectly_marked.py, examples/experimental/dagster-airlift/setup.py, examples/experimental/dagster-airlift/tox.ini
Dagster operator which is able to remotely invoke dagster via airflow.
It searches for a "node def" with the name that matches the task (and matches our opinionated file format for blueprints). 
Includes unit test which runs against live airflow and dagster, checks that runs of the respective assets are invoked for each task.
Tests are probably not entirely sufficient. I'd ideally like to run against a few other cases:
- workspace with multiple defined code locations
- multi asset with multiple keys. Ensure they all get picked up within same run.
The api surface area here won't actually be exposed to the user. What I'm imagining is something like this:
```python
... # dag code
create_migrating_dag(
migrating_dict={...},
dagster_instance=DagsterInstance(url=...) # or, in cloud case …
```
=> [dagster-airlift] dagster operator

python_modules/dagster/dagster_tests/storage_tests/test_event_log.py, python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py, python_modules/libraries/dagster-mysql/dagster_mysql_tests/test_event_log.py, python_modules/libraries/dagster-postgres/dagster_postgres_tests/test_event_log.py
Summary:
Allows us to add test cases to TestEventLogStorage that use the instance directly.
Test Plan: BK
=> Refactor event log storage tests to use instance as a fixture

docs/content/concepts/code-locations.mdx, docs/content/concepts/code-locations/workspace-files.mdx, docs/content/concepts/configuration/configured.mdx, docs/content/guides/dagster/branch_deployments.mdx, docs/content/guides/dagster/recommended-project-structure.mdx, docs/content/guides/dagster/software-defined-assets.mdx, docs/content/guides/dagster/transitioning-data-pipelines-from-development-to-production.mdx, docs/content/guides/dagster/using-environment-variables-and-secrets.mdx, docs/content/guides/understanding-dagster-project-files.mdx, docs/content/tutorial/connecting-to-external-services.mdx, docs/next/components/mdx/includes/dagster/DagsterDevTabs.mdx, examples/assets_pandas_pyspark/assets_pandas_pyspark/definitions.py, examples/docs_snippets/docs_snippets/concepts/repositories_workspaces/workspace_python_module.yaml, examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/branch_deployments/repository_v1.py, examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/repository/repository_v1.py, examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/repository/repository_v2.py, examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/repository/repository_v3.py, examples/docs_snippets/docs_snippets/guides/dagster/using_environment_variables_and_secrets/repository.py, examples/docs_snippets/docs_snippets/guides/dagster/using_environment_variables_and_secrets/repository_v2.py, examples/docs_snippets/docs_snippets/tutorial/connecting/connecting_with_envvar.py
This PR updates the recommended folder structure to include the Definitions object in `definitions.py` instead of `__init__.py`. It also updates related guides and references.
Tutorials in the docs are not yet updated. Will open more PRs:
- Update the project in examples/
- Update the tutorials in examples/
- Update tutorials in docs
- Update Dag Uni content
- Update Dag Uni starter projects once we have a PR for Dag Uni content
make mdx-full-format
=> [docs] Update recommended structure to remove Dagster code from `__init__.py`

docs/content/dagster-plus/managing-deployments/branch-deployments/using-branch-deployments.mdx
Doc: [Using Branch Deployments (CI) with the dagster-cloud CLI](https://docs.dagster.io/dagster-plus/managing-deployments/branch-deployments/using-branch-deployments#using-branch-deployments-ci-with-the-dagster-cloud-cli
)
Doc is Hybrid-centric so Serverless deployment users can be confused in some steps
👀
=> [docs] clarify steps exempt for Serverless deployment in CLI branch deployment

docs/content/guides/dagster/recommended-project-structure.mdx
This PR updates the URL to the file containing Definitions in project-fully-featured. That was moved from #23316 to this PR to avoid failure when running the doc tests - the file must exist before being referenced, and it is updated in #23345.
BK
=> [docs] Update URL to Definitions for project-fully-featured

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py, examples/experimental/dagster-airlift/airflow_setup.sh, examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py, examples/experimental/dagster-airlift/dagster_airlift/in_airflow/dagster_operator.py, examples/experimental/dagster-airlift/dagster_airlift/in_airflow/mark_as_migrating.py, examples/experimental/dagster-airlift/dagster_airlift/migration_state.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/airflow_op_switcheroo/dags/switcheroo_dag.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/airflow_op_switcheroo/dagster_defs.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/operator_test_project/dags/migrated_dag.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_operator_switcheroo.py
Adds functionality for `mark_as_dagster_migrating` to swizzle out an operator for the dagster operator.
Adds a test that runs against live airflow and dagster, and ensures that when a run of the dag marked as "migrated" is kicked off, that it results in an asset materialization appearing in dagster.
=> [dagster-airlift] airflow op swizzler

js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillTerminationDialog.tsx
https://github.com/dagster-io/dagster/pull/23147 tried to remove getting information about individual partition statuses from backfill cancellation logic. However it introduced a bug when determining if we show the run termination dialogue. The resolver to get partition statuses always returned an empty list for asset backfills, which made it skip showing the termination dialogue. that behavior wasn't replicated when we switched to checking for cancelable runs to decide if we should show the dialogue.
terminated a backfill from the backfill table and from the backfill details page and observed that the run termination dialogue did not appear, the backfill was immediately moved to CANCELING and the backfill daemon took care of canceling in progress runs
=> fix termination dialogue appearing when canceling asset backfills

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_asset_condition_evaluations.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_condition_evaluations.py, python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_condition_evaluations.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/serialized_objects.py, python_modules/dagster/dagster/_core/storage/schedules/sql_schedule_storage.py
For time-partitioned assets with many historical partition keys, it is very computationally expensive to compute the string values of each of those keys. Instead, we should rely solely on partition key ranges to power the frontend.
This PR removes fields on the evaluation record which eagerly compute the number of partition keys (making it impossible to accidentally use them), and adds a separate query on the frontend to fetch the specific set of partition keys where necessary. This change resulted in a fair amount of unused code being removed.
Specific differences for the frontend:
- Now use `numCandidates` instead of `candidateSubset` (as before, if this is `None`, that represents "all partitions at the time")
- Now use the new query …
=> [DA] Lazily compute partitionKeys for Automation tab on Asset Details page

js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/AutomaterializeMiddlePanelWithData.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/GetEvaluationsQuery.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/PartitionSegmentWithPopover.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/PartitionSubsetList.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/PartitionSubsetListQuery.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/PolicyEvaluationTable.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/__fixtures__/PartitionSegmentWithPopover.fixtures.ts, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/__stories__/PartitionSegmentWithPopover.stories.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/__stories__/PolicyEvaluationTable.stories.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/__tests__/PolicyEvaluationTable.test.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/types/GetEvaluationsQuery.types.ts, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/types/PartitionSubsetListQuery.types.ts, js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
Defer fetching partition keys affected by an automation policy evaluation.
For assets with tons of partitions, this page is slowed significantly by retrieving the parititon subsets up front. Instead, retrieve them when actually hovering over the evaluation data for the relevant row.
Load a repo with an asset with 200k partitions, then perform some automation evaluations. View an evaluation result, and hover over the "200,000 True" tag. Verify loading state for the partition key query, and correct rendering of partition list.
=> [ui] Evaluations table: Don't load all partition keys up front

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/sling_event_iterator.py
This is not working in Python 3.8. Fix that by removing the type hint.
bk
=> refactor(sling): remove `Pattern` type hint

python_modules/libraries/dagster-openai/dagster_openai/resources.py, python_modules/libraries/dagster-openai/dagster_openai_tests/test_resources.py
When creating an `OpenAIResource`, we might want to pass these additional arguments to the OpenAI `Client`.
I added a test case that validates that these new arguments are passed from the `OpenAIResource` to the `Client`.
=> Add Configuration to `OpenAIResource`

docs/content/integrations/airbyte-cloud.mdx, examples/docs_snippets/docs_snippets/integrations/airbyte/airbyte.py, python_modules/libraries/dagster-airbyte/dagster_airbyte/resources.py, python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/test_asset_defs.py, python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/test_cloud_resources.py, python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/test_load_from_instance.py, python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/test_ops.py
This PR updates the `AirbyteCloudResource` to support `client_id` and `client_secret` for authentication. The `api_key` can no longer be used for authentication because Airbyte is [deprecating portal.airbyte.com](https://reference.airbyte.com/reference/portalairbytecom-deprecation).
Tests and docs are updated to reflect the changes.
Two main questions for reviewers:
- this PR implements a pattern where the access token is refreshed before making a call to the API, if the token was fetched more than 2.5 minutes ago. Should we avoid this pattern and let users manage the resource lifecycle?
- [According to Airbyte](https://reference.airbyte.com/reference/portalairbytecom-deprecation), the access token expires after 3 minutes.
- The access token is initially fetched in `setup_for_execution`, …
=> [dagster-airbyte] Support `client_id` and `client_secret` in AirbyteCloudResource

python_modules/dagster/dagster/_check/builder.py, python_modules/dagster/dagster/_config/pythonic_config/resource.py, python_modules/dagster/dagster/_core/definitions/resource_requirement.py
call `_name` on each entry in a tuple to ensure older python logic (`_name`) gets applied
also moves around some code to avoid a `ForwardRef` for a `Union` which is hard to solve in `3.8`
test on 3.8
=> [check] fix tuple name resolution

python_modules/dagster/dagster/_core/definitions/asset_graph.py, python_modules/dagster/dagster/_core/definitions/asset_job.py, python_modules/dagster/dagster/_core/definitions/base_asset_graph.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_job.py, python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run_asset_checks.py
We include every unpartitioned asset in every implicit asset job.  This also includes every asset check that's not part of a partitioned `AssetsDefinition`.
=> freshness check asset job sensor fix

examples/experimental/dagster-airlift/dagster_airlift/core/__init__.py, examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py, examples/experimental/dagster-airlift/dagster_airlift/core/airflow_instance.py, examples/experimental/dagster-airlift/dagster_airlift/core/multi_asset.py, examples/experimental/dagster-airlift/dagster_airlift/migration_state.py, examples/experimental/dagster-airlift/dagster_airlift/test/shared_fixtures.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/conftest.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_dbt_multi_asset.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_operator_switcheroo.py, examples/experimental/dagster-airlift/examples/simple-migration/.gitignore, examples/experimental/dagster-airlift/examples/simple-migration/.vscode/settings.json, examples/experimental/dagster-airlift/examples/simple-migration/Makefile, examples/experimental/dagster-airlift/examples/simple-migration/README.md, examples/experimental/dagster-airlift/examples/simple-migration/conftest.py, examples/experimental/dagster-airlift/examples/simple-migration/setup.py, examples/experimental/dagster-airlift/examples/simple-migration/simple_migration/airflow_dags/dagster_migration/simple.yaml, examples/experimental/dagster-airlift/examples/simple-migration/simple_migration/airflow_dags/simple.py, examples/experimental/dagster-airlift/examples/simple-migration/simple_migration/dagster_defs/constants.py, examples/experimental/dagster-airlift/examples/simple-migration/simple_migration/dagster_defs/migrate.py, examples/experimental/dagster-airlift/examples/simple-migration/simple_migration/dagster_defs/observe.py, examples/experimental/dagster-airlift/examples/simple-migration/simple_migration/dagster_defs/peer.py, examples/experimental/dagster-airlift/examples/simple-migration/simple_migration/shared.py, examples/experimental/dagster-airlift/examples/simple-migration/simple_migration_tests/conftest.py, examples/experimental/dagster-airlift/examples/simple-migration/simple_migration_tests/test_load_dagster.py, examples/experimental/dagster-airlift/examples/simple-migration/tox.ini, pyright/master/requirements-pinned.txt, pyright/master/requirements.txt
Adds a simple example which shows what it looks like to have completed the peer, observe, and migrate steps, before having actually decommissioned the airflow instance.
Also includes some necessary changes for the demo.
=> [dagster-airlift] simple migration example

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py, examples/experimental/dagster-airlift/dagster_airlift/core/sensor.py, examples/experimental/dagster-airlift/dagster_airlift/core/utils.py
When a task is migrated, dagster will actually run the task. However, there will still be an airflow task execution representing that task. We have to make sure not to double count here.
=> [dagster-airlift] Fix sensor for migrated tasks

examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/lakehouse.py, examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/csv_to_duckdb_defs.py, examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/definitions.py, examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/shared/load_iris.py
As discussed offline, adds a custom operator for the lakehouse example. This should allow us to better demonstrate the step of "writing an operator to translate dagster code."
I think this leaves us with an unclear interstitial step for this type of asset. What's the "observe" phase look like here? Do we expect people to just provide an assetspec? We should sketch that out in a future PR.
=> [dagster-airlift] create a custom operator for lakehouse example

python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py
Summary:
This makes validate_loadable mirror the same checks that the code server does on startup: https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_grpc/server.py#L260-L269 - so now it will catch errors like a lazy-loaded job definition that doesn't raise an exception until its lambda is resolved. I think it would also make it a more useful tool for performance measurement of code server startup, although I know that wasn't why we added it.
Test Plan: BK (existing validate_loadable coverage)
=> Load all job definitions in validate_loadable

python_modules/dagster/setup.py
Summary:
grpcio yanked the version with egregious logspew and there is no logspew in the latest published versions (1.65.2 and 1.65.4) - there is still some minor logspew in 1.65.1 but I don't think its severe enough that we need a permanent pin.
Test Plan:
pip install -U grpcio, run dagster
=> Remove grpcio pin

examples/experimental/dagster-airlift/dagster_airlift/dbt/multi_asset.py, examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_dbt_multi_asset.py, examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/definitions.py
Allows for more flexible DbtProjectDefs. The idea here is to allow for both external assets and dbt-computable assets.
Makes the implementation more complex. I'm starting to think we kind of need an intermediate pattern beyond just `build_defs`...
=> [dagster-airlift] more flexible DbtProjectDefs params

js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationDefinitionsMain.tsx, js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationDefinitionsNav.tsx, js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationDefinitionsRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationOverviewRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationPageHeader.tsx, js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationSearchableList.tsx, js_modules/dagster-ui/packages/ui-core/src/code-location/__fixtures__/CodeLocationPages.fixtures.ts, js_modules/dagster-ui/packages/ui-core/src/code-location/__stories__/CodeLocationDefinitionsRoot.stories.tsx, js_modules/dagster-ui/packages/ui-core/src/code-location/__stories__/CodeLocationOverviewRoot.stories.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceQueries.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/types/WorkspaceQueries.types.ts
Components for the newly designed code location definitions page, which is a stripped down browse view intended to reduce some of the list view duplication we have throughout the app.
This is just in storybook for now, and implements only the jobs, schedules, sensors, and resources sections. Graphs are slightly trickier, and for ops I'm just going to transplant the existing ops viewer. Assets are also slightly different since we'll need to incorporate asset groups.
Yarn storybook, click on each nav item. Verify searchability, scrollability.
=> [ui] Code locations: new definitions page

python_modules/dagster/dagster/_config/config_type.py, python_modules/dagster/dagster/_config/snap.py, python_modules/dagster/dagster/_core/snap/config_types.py, python_modules/dagster/dagster_tests/core_tests/snap_tests/test_config_schema_snapshot.py, python_modules/dagster/dagster_tests/core_tests/snap_tests/test_snap_to_yaml.py
noticed some `check.opt_str_param` checks from these objects show up in the profiler - moving to record will inline that checks and make it faster
bk
=> [record] config/snap.py

CHANGES.md
=> 1.8.1 Changelog

docs/content/integrations/deltalake/reference.mdx
Fixed some typos, I like to read documentation without them
By the power of eye and thoughts.
=> docs(deltalake): correct typos

python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py
fix build_dbt_multi_asset_args to accept MultiParitionMapping:
- deps var was defined as a set, and was throwing an error when trying to insert an AssetDep with a MultiPartitionMapping
- MultiPartitionMapping is taking in a dict, making it unhashable
Error I was getting
```
File "/Users/username/dev/data_orchestrations/project/internals/assets/dbt_assets.py", line 21, in dbt_asset_factory
@dbt_assets(
^^^^^^^^^^^
File "/Users/username/dev/data_orchestrations/project/.venv/lib/python3.12/site-packages/dagster/_core/decorator_utils.py", line 223, in wrapped_with_context_manager_fn
return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^
File "/Users/username/dev/data_orchestrations/project/.venv/lib/python3.12/site-packages/dagster_dbt/asset_decorator.py", line 311, in dbt_assets
) = …
```
=> fix(dbt): support `MultiPartitionMapping`

docs/content/integrations/dbt/using-dbt-with-dagster-plus.mdx
Updates the CI/CD section to reflect the changes when using DbtProject
Tested in local docs preview with `make next-watch-build`
=> [docs] Update CI/CD example dbt & Dagster+ guide to use DbtProject

python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py, python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py, python_modules/libraries/dagster-fivetran/dagster_fivetran/utils.py, python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_load_from_instance.py, python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/utils.py
Pull `database` config from Fivetran destinations when loading assets from a live Fivetran instance. Join this with known schema and table info to produce a full `dagster/relation_identifier`.
Unit test, tested with live Fivetran instance.
=> [dagster-fivetran] add relation identifier metadata to fivetran assets

python_modules/dagster/dagster/_check/builder.py, python_modules/dagster/dagster_tests/general_tests/check_tests/test_check.py
A further step would be to check the args passed to `Callable`, but I think this is a useful start on its own.
=> support Callable annotations on record fields

helm/dagster/templates/helpers/instance/_compute-log-manager.tpl
This field is no longer mandatory and it breaks AzureBlobComputeLogManager in dagster-k8s.
Ran job in kubernetes with edited helm chart.
=> [dagster-k8s] fix: azureBlobComputeLogManagerConfig.secret_key is optional

python_modules/libraries/dagster-celery/dagster_celery/core_execution_loop.py
this fixes the issue with celery-executor, where terminating a job keeps it running, due to the default nature of `revoke`, by default for result.revoke `Terminate=False`, replacing it with `True` fixes the issue https://github.com/dagster-io/dagster/issues/23222
created a simple job and another one with executor as `celery-executor`, works as intended for both scenarios.
also the logs make it further clear that the tasks are terminated with signal `SIGTERM`
=> fix: use terminate to revoke celery task

docs/content/concepts/assets/multi-assets.mdx, examples/docs_snippets/docs_snippets/concepts/assets/multi_asset_conditional_materialization.py, examples/docs_snippets/docs_snippets/concepts/assets/multi_assets.py
=> [docs] on multi-asset concept page, use AssetSpec, not AssetOut

python_modules/libraries/dagster-celery/dagster_celery/core_execution_loop.py
This reverts commit 3a8a66f488340857f43c8df092d334d63bd2cd02 while we can figure out why it broke our celery-k8s integration tests.
=> Revert "fix: use terminate to revoke celery task (#23513)"

js_modules/dagster-ui/packages/ui-core/src/assets/useAssetCatalogFiltering.oss.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/useAssetDefinitionFilterState.oss.tsx
In cloud we want to conditionally call this hook, or an elastic search backed version of the hook, but we can't do that because it would break the rules of hooks. Unfortunately the place where we want to call it conditionally is inside of another hook used by multiple different components and even other hooks, so going to the parent component and making them conditionally pass 1 version of the hook or another would not be very elegant since there would be a lot of threading of hooks around from places which really shouldn't know anything about this hook or its implementation. So... instead of that what we're doing is calling both hooks, but only returning the results of the hook we're using. The problem is that this hook has global side effects (by way of CatalogViewProvider integration …
=> Add "isEnabled" prop to `useAssetcatalogFiltering` to allow calling hook hook while disabling all of its side effects.

js_modules/dagster-ui/packages/ui-core/src/assets/AssetActionMenu.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetPartitions.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetTable.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetTableFragment.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/DeleteDynamicPartitionsDialog.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/__fixtures__/PartitionHealth.fixtures.ts, js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/DeleteDynamicPartitionsDialog.test.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/LaunchAssetChoosePartitionsDialog.test.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetTableFragment.types.ts, js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetView.types.ts, js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetsCatalogTable.types.ts, js_modules/dagster-ui/packages/ui-core/src/assets/types/DeleteDynamicPartitionsDialog.types.ts, js_modules/dagster-ui/packages/ui-core/src/assets/types/useReportEventsModal.types.ts, js_modules/dagster-ui/packages/ui-core/src/assets/useDeleteDynamicPartitionsDialog.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/useReportEventsModal.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/useWipeModal.tsx, js_modules/dagster-ui/packages/ui-core/src/launchpad/ConfigEditorConfigPicker.tsx, js_modules/dagster-ui/packages/ui-core/src/partitions/CreatePartitionDialog.tsx, js_modules/dagster-ui/packages/ui-core/src/partitions/DimensionRangeWizard.tsx, js_modules/dagster-ui/packages/ui-core/src/partitions/DimensionRangeWizards.tsx, js_modules/dagster-ui/packages/ui-core/src/partitions/__tests__/CreatePartitionDialog.test.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedAssetRow.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedAssetTable.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedRepoAssetTable.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/types/VirtualizedRepoAssetTable.types.ts, js_modules/dagster-ui/packages/ui-core/src/workspace/types/WorkspaceAssetsRoot.types.ts
Fixes https://github.com/dagster-io/dagster/issues/14026
This PR adds a new "delete partitions" modal in both OSS and Plus that allows you to remove dynamic partitions from the UI.  The UI immediately updates to reflect the change.
During testing I also found that our current UI for adding dynamic partitions didn't work quite right in cases where the dynamic partition was one of the dimensions of a multi-dimensional partition def, because the `dimension.name` and the `dimension.dynamicPartitionsDefinitionName` are not the same, and the Add Partition mutation requires the latter.
The new dropdown option in these screenshots only appears if the asset has a dynamic partition dimension, so non-dynamic assets are unimpacted.
There's a new test file covering this modal!
I also tested this …
=> [ui] Allow deleting dynamic partitions from asset pages
