dagster-io/dagster

- python_modules/dagster/dagster/_core/remote_representation/code_location.py
- python_modules/dagster/dagster/_core/remote_representation/external_data.py
- python_modules/dagster/dagster/_grpc/impl.py
- python_modules/dagster/dagster/_grpc/server.py
- python_modules/dagster/dagster/_serdes/utils.py
- python_modules/dagster/dagster_tests/core_tests/host_representation_tests/test_external_data.py
- python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
- python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py
convert external_data.py named tuples to `@record`s 
bk
> [record] external_data

- python_modules/dagster/dagster/_core/remote_representation/external_data.py
> [external data] get rid of ExternalPresetData forward ref

- examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_cacheable_asset.py
Makes overrides optional when specifying task mappings. Doesn't feel necessary that users should specify this just for peering + observability
> [dagster-airlift] make override optional when specifying task mappings

- python_modules/libraries/dagster-aws/dagster_aws/pipes.py
- python_modules/libraries/dagster-aws/dagster_aws_tests/pipes_tests/fake_glue.py
- python_modules/libraries/dagster-aws/dagster_aws_tests/pipes_tests/test_pipes.py
Exploring if it's possible to rewrite the fake testing Glue client to run execute scripts in a  background process so we can test interruption
> pipes-glue-interruption-tests-wip

- python_modules/dagster/dagster/_daemon/sensor.py
This is a simple-ish refactor which gives a single _handle_run_requests entrypoint which does both backfills and regular run requests. A small side effect is that this means we can use the threadpool submitter for submitting backfills.
The overall goal here is to make the next PR in this stack easier to implement, as we're going to be further modifying this path.
> [sensor-upgrades][1/n] Refactor _handle_run_requests

- CHANGES.md
> changelog for 1.8.0

- js_modules/dagster-ui/packages/ui-core/src/schedules/ScheduleSwitch.tsx
- js_modules/dagster-ui/packages/ui-core/src/sensors/SensorSwitch.tsx
https://dagsterlabs.slack.com/archives/C03KE7K92TT/p1723064363721739 for context.
These refetchQueries are missing variables.
> Add missing variable to refetch query

- examples/experimental/dagster-airlift/build_and_publish.sh
- examples/experimental/dagster-airlift/setup.py
tooling to ad-hoc push dagster-airlift to pypi.
not sure if there's something more I need to do to avoid getting this released as part of the main publish process.
> [dagster-airlift] pypi

- CHANGES.md
> add missing 1.8.0 changelog entry and standardize contributor entries

- docs/content/concepts/dagster-pipes.mdx
oversight from https://github.com/dagster-io/dagster/pull/23250 
cmd + f on every page in dagster-pipes/ and dagster-pipes.mdx
> [easy] drop experimental mentions from pipes page

- examples/experimental/dagster-airlift/dagster_airlift/core/airflow_instance.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_airflow_instance.py
Tests for AirflowInstance utility methods.
> [dagster-airlift] instance tests

- python_modules/dagster/dagster/_core/execution/asset_backfill.py
accidentally left a debug line in the backfill logs
> remove debug message from backfill logs

- python_modules/libraries/dagster-mlflow/dagster_mlflow/resources.py
- python_modules/libraries/dagster-mlflow/dagster_mlflow_tests/test_resources.py
fix build... maybe something about unpinning some libraries unblocked some recent release?
BK
> update mlflow import

- python_modules/dagster/dagster/_core/execution/context/invocation.py
- python_modules/dagster/dagster/_core/execution/context/op_execution_context.py
- python_modules/dagster/dagster_tests/core_tests/test_op_invocation.py
> add `run_tags` to `build_op_context` and `build_asset_context`

- python_modules/dagster/dagster/_core/definitions/definitions_class.py
> add code example to apidoc for Definitions.merge

- MIGRATION.md
> migration guide for 1.8

- .github/workflows/build-docs.yml
> Fix broken docs build

- python_modules/dagster/dagster/_core/definitions/assets.py
> docstring for AssetsDefinition.get_asset_spec

- examples/experimental/dagster-airlift/README.md
Updated, more grounded Airlift README with code examples, etc.
v5: https://github.com/dagster-io/dagster/blob/4a5ae1fea216d141e9f8462c84412f7fc4d72bad/examples/experimental/dagster-airlift/README.md
Read
> README for Airlift

- examples/experimental/dagster-airlift/README.md
- examples/experimental/dagster-airlift/dagster_airlift/core/__init__.py
- examples/experimental/dagster-airlift/dagster_airlift/dbt/multi_asset.py
Export DefsFactory at dagster_airlift.core
BK
> Export DefsFactory at dagster_airlift.def_factory

- .github/workflows/build-docs-revamp.yml
Set up a new site to view the docs-revamp.
Inspection
> vercel docs revamp

- .github/workflows/build-docs-revamp.yml
Secrets for the revamp build are pointed at the wrong project id... I set up a new secret with the correct project id.
Inspection, hopefully this PR
> update dagster docs next project

- python_modules/libraries/dagster-databricks/dagster_databricks/databricks.py
- python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_databricks.py
- python_modules/libraries/dagster-databricks/setup.py
- Users are mentioning that this deprecated dependency is causing resolution issues
- Feature has been deprecated >1 year
- bk
> [dagster-databricks] rm deprecated databricks-cli

- js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
- js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
- python_modules/dagster-graphql/dagster_graphql/schema/inputs.py
- python_modules/dagster/dagster/_core/definitions/selector.py
Accompanies https://github.com/dagster-io/internal/pull/10911
> Add asset group selector type

- .buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
Fixes bk. This package is created in a downstream pr which hasn't landed, yet, I think this just passed due to bk on branch not running every step.
> [dagster-airlift] fix bk

- examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py
This was causing issues with DBTProjectDefs, since dbt_assets contain unserializable metadata.
> [dagster-airlift] fix munging of unserializable metadata

- python_modules/libraries/dagster-dbt/dagster_dbt/core/resource.py
> chore(dbt): log warning if the dbt adapter cannot be created

- docs/next/package.json
- docs/next/yarn.lock
Fix https://github.com/dagster-io/dagster/security/dependabot/573.
Buildkite
> [docs] Bump axios for dependabot

- examples/use_case_repository/use_case_repository/guides/pipes_cli_command.md
- examples/use_case_repository/use_case_repository/guides/snowflake_to_s3_embedded_elt.md
> Fix use-case tags in the use case repo

- js_modules/dagster-ui/yarn.lock
Resolve https://github.com/dagster-io/dagster/security/dependabot/562, https://github.com/dagster-io/dagster/security/dependabot/563, https://github.com/dagster-io/dagster/security/dependabot/564.
BK
> [ui] Bump elliptic for dependabot

- python_modules/dagster/dagster/_core/remote_representation/external.py
non trivial computation, non need to repeat 
bk
> memoize selector_id on external sensor & schedule

- python_modules/dagster/dagster/_core/definitions/asset_spec.py
> add docstring on partitions_def arg of AssetSpec

- js_modules/dagster-ui/packages/ui-core/src/assets/useWipeAssets.tsx
New export required for the tests that were added to the wipe modal.
> Export the asset wipe mutation so tests can be written

- js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/AutomaterializeMiddlePanel.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/auto-materialization/DeclarativeAutomationBanner.tsx
> [DA] Update UI links

- python_modules/dagster/dagster/_core/remote_representation/external_data.py
follow up to https://github.com/dagster-io/internal/pull/10910
bk
> [external data] remove LegacyNamedTupleMixin

- python_modules/libraries/dagster-azure/dagster_azure/blob/compute_log_manager.py
- fixes https://github.com/dagster-io/dagster/issues/23696
> fix: azure blob compute log manager serde

- python_modules/dagster/dagster/_core/execution/context/system.py
Summary:
For debugging purposes.
Test Plan: Bk (adding test)
> include the name of the input/output in the error for an invalid input/output

- python_modules/dagster/dagster/_utils/__init__.py
- python_modules/dagster/dagster_tests/general_tests/test_record.py
resolves https://github.com/dagster-io/dagster/issues/23698
added test
> [record] handle in make_hashable

- python_modules/libraries/dagster-polars/dagster_polars_tests/test_polars_delta.py
- python_modules/libraries/dagster-polars/setup.py
use `"delta_write_options": {"engine": "pyarrow"},` in partition tests 
bk
> unpin polars

- js_modules/dagster-ui/packages/ui-core/src/search/useIndexedDBCachedQuery.tsx
- js_modules/dagster-ui/packages/ui-core/src/ui/BaseFilters/useStaticSetFilter.tsx
as titled
scroll this section:
> Add scrollbar to overflowing filter popover

- .github/workflows/vale.yml
> [docs] Update vale to only run on docs-beta

- python_modules/dagster/dagster/_core/definitions/asset_spec.py
> update docstring for AssetSpec

- python_modules/dagster-test/dagster_test/toys/column_schema/__init__.py
- python_modules/dagster-test/dagster_test/toys/column_schema/column_schema_assets.py
- python_modules/dagster-test/dagster_test/toys/repo.py
> Add column schema toys

- python_modules/dagster-test/dagster_test/fixtures/docker_compose.py
When we first added this fixture, docker compose relatively early in its history and we had trouble getting it to run on buildkite. I'm opening this PR to see if things "just work" now that it's a few years later.
> Use the docker compose CLI

- examples/experimental/dagster-airlift/examples/dbt-example/.vscode/settings.json
- examples/experimental/dagster-airlift/examples/dbt-example/Makefile
- examples/experimental/dagster-airlift/examples/dbt-example/README.md
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/dbt_dag.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/lakehouse.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/__init__.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/constants.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/csv_to_duckdb_defs.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/migrate.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/observe.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/peer.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example_tests/test_load_dagster.py
I think it's valuable to show what the POM steps look like in isolation, so I created separate makefile commands + python targets to run each of them.
> [dagster-airlift] peer/observe/migrate for dbt example

- docs/docs-beta/README.md
> [docs-beta] value -> vale

- docs/docs-beta/README.md
This PR adds info about Vale, formatting, and clarification for a few things to the new docs README.
`NOCHANGELOG`
> Update docs-beta README

- CHANGES.md
> 1.8.3 changelog

- python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py
- python_modules/dagster/dagster/__init__.py
- python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
- python_modules/dagster/dagster/_core/definitions/repository_definition/repository_data_builder.py
- python_modules/dagster/dagster/_core/remote_representation/external_data.py
- python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
- python_modules/dagster/dagster_tests/definitions_tests/asset_policy_sensors_tests/test_default_auto_materialize_sensors.py
- python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/test_asset_daemon.py
- python_modules/dagster/dagster_tests/definitions_tests/auto_materialize_tests/user_space_ds_defs.py
- python_modules/dagster/dagster_tests/definitions_tests/test_automation_policy_sensor_definition.py
- python_modules/dagster/dagster_tests/definitions_tests/test_repository_definition.py
There's no need for these to be separate classes. I add a hidden kwarg to make it possible to toggle between the two behaviors
> [DA][1/n][user-code] Combine UserCodeAutomationConditionSensor into AutomationConditionSensor

- python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
As title. This is no longer being used anywhere, if we need this in the future we can always add it back in.
> [DA][3/n][user-code] Remove NonAGVInstanceInterface

- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_condition_evaluations.py
- python_modules/dagster/dagster/_core/definitions/asset_daemon_cursor.py
- python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_evaluation.py
- python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
- python_modules/dagster/dagster/_core/definitions/declarative_automation/serialized_objects.py
- python_modules/dagster/dagster/_core/remote_representation/external_data.py
- python_modules/dagster/dagster/_utils/test/schedule_storage.py
- python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_automation_condition.py
As title -- this allows us to know about automation conditions even if they are not possible to execute without access to user code.
> [DA][13/n][user-code] Add serializable snapshot to ExternalAssetNode

- .github/workflows/build-docs-revamp.yml
- docs/docs-beta/README.md
Updates the Github Action for Docs Revamp. 
NOCHANGELOG
> [docs-beta] Update GH Action

- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/lakehouse.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/lakehouse.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/migrate.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/observe.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/shared/dbt/models/iris_setosa.sql
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/shared/dbt/models/sources.yml
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/shared/load_iris.py
Code example could be signficantly more concise. Make some changes to do this.
> [dagster-airlift] make example code more concise

- js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationOverviewRoot.tsx
- js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationOverviewSectionHeader.tsx
- js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationServerSection.oss.tsx
Add an OSS placeholder for the code server metrics section of the new code location page.
BK, verify that the section is inserted correctly in the Plus UI.
NOCHANGELOG
> [ui] Code location page: Allow server section

- .buildkite/hooks/pre-command
Revert of https://github.com/dagster-io/dagster/pull/18510
`NOCHANGELOG`
> Re-enable test analytics

- examples/experimental/dagster-airlift/examples/tutorial-example/README.md
Tweak description of included DAGs.
> NOCHANGELOG
> [dagster-airlift][tutorial-example] tweak new example readme

- docs/docs-beta/README.md
This PR adds info about Mermaid diagrams to the new docs README.
`NOCHANGELOG`
> [docs-revamp] - Add diagrams to README

- docs/docs-beta/docs/guides/automation/asset-sensors.md
> [docs-beta] add spaces to user defined state in mermaid diagram

- examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py
- examples/experimental/dagster-airlift/dagster_airlift/core/defs_from_airflow.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_airflow_instance.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_cacheable_asset.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_transitive_asset_deps.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_build_defs.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/migrate.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/observe.py
- examples/experimental/dagster-airlift/examples/simple-migration/simple_migration/dagster_defs/migrate.py
- examples/experimental/dagster-airlift/examples/simple-migration/simple_migration/dagster_defs/observe.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/definitions.py
Allow passthrough via "defs" argument on builder.
Adds test for the passthrough behavior.
> [dagster-airlift] unorchestrated_defs passthrough

- examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py
- examples/experimental/dagster-airlift/dagster_airlift/core/defs_builders.py
- examples/experimental/dagster-airlift/dagster_airlift/core/defs_from_airflow.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_airflow_instance.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_cacheable_asset.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_transitive_asset_deps.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_build_defs.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_utils.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/migrate.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/observe.py
- examples/experimental/dagster-airlift/examples/simple-migration/simple_migration/dagster_defs/migrate.py
- examples/experimental/dagster-airlift/examples/simple-migration/simple_migration/dagster_defs/observe.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/definitions.py
combine_defs previously couldn't handle checks correctly (would incorrectly read as an asset)
> [dagster-airlift] support checks in combine_defs

- examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py
- examples/experimental/dagster-airlift/dagster_airlift/core/sensor.py
- examples/experimental/dagster-airlift/dagster_airlift/core/utils.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/conftest.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_build_defs.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_sensor.py
- python_modules/dagster/dagster/_core/definitions/repository_definition/repository_data.py
- python_modules/dagster/dagster/_core/definitions/repository_definition/repository_definition.py
This allows us to simplify the logic in spec builders
`NOCHANGELOG`
> [dagster-airlift] coerce passed in asset specs instead of ignoring

- examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py
- examples/experimental/dagster-airlift/dagster_airlift/core/defs_builders.py
- examples/experimental/dagster-airlift/dagster_airlift/core/sensor.py
- examples/experimental/dagster-airlift/dagster_airlift/core/utils.py
- examples/experimental/dagster-airlift/dagster_airlift/dbt/__init__.py
- examples/experimental/dagster-airlift/dagster_airlift/dbt/multi_asset.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/conftest.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_build_defs.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_sensor.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/dags.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/constants.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/lakehouse.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/migrate.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/observe.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/shared/dbt/models/iris_setosa.sql
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/shared/dbt/models/sources.yml
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/shared/dbt/profiles.yml
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/shared/load_iris.py
- python_modules/dagster/dagster/_core/definitions/repository_definition/repository_data.py
- python_modules/dagster/dagster/_core/definitions/repository_definition/repository_definition.py
Use spec builders for the observe and migrate steps of the dbt example.
> [dagster-airlift] use spec builders in dbt example

- examples/experimental/dagster-airlift/dagster_airlift/core/defs_builders.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/constants.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/observe.py
> [dagster-airlift] add freshness check

- docs/docs-beta/docs/dagster-plus/deployment/branch-deployments/testing.md
- docs/docs-beta/docs/guides/deployment/google-cloud-platform.md
- docs/docs-beta/docs/guides/deployment/kubernetes.md
This PR adds a few more stub pages to the new docs site.
NOCHANGELOG
> [docs-revamp] - More stub pages

- examples/docs_beta_snippets/docs_beta_snippets/guides/data-assets/passing-data-assets/passing-data-explicit.py
> [docathon] Clean up some rogue code

- docs/content/dagster-plus/deployment/agents/amazon-ecs.mdx
> [docs] fix 404ing URL

- js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillRunsTab.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunsRoot.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/usePaginatedRunsTableRuns.tsx
https://github.com/dagster-io/dagster/issues/23815
Extracted const PAGE_SIZE to function param to make it configurable from the outside.
Bug: Fix UI not showing last 5 runs on each page
> [UI] fix: missing last 5 runs on each run page

- docs/docs-beta/README.md
> [docs-revamp] - Add more Vale examples to readme

- docs/docs-beta/docs/guides/external-systems/authentication.md
- docs/docs-beta/docs/guides/external-systems/build-your-own.md
- docs/docs-beta/docs/guides/external-systems/non-python.md
> [docs-revamp] - Add resource stub pages

- examples/experimental/dagster-airlift/dagster_airlift/dbt/__init__.py
- examples/experimental/dagster-airlift/dagster_airlift/dbt/multi_asset.py
- examples/experimental/dagster-airlift/examples/dbt-example/Makefile
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/migration_state/dbt_dag.yaml
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/migration_state/load_lakehouse.yaml
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/complete.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/lakehouse.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/migrate.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/observe.py
Use `dag_defs` in dbt example
BK
NOCHANGELOG
> Use dag_defs in dbt_example"

- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/csv_to_duckdb_defs.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/definitions.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/duckdb_to_csv_defs.py
Use `dbt_defs` and `task_defs` in tutorial
BK
NOCHANGELOG
> Change tutorial to use dag_defs

- examples/experimental/dagster-airlift/README.md
Updates README to follow along porting the `tutorial-example`.
> Add migration steps to Airlift README

- examples/experimental/dagster-airlift/dagster_airlift/migration_state.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/airflow_op_switcheroo/dags/switcheroo_dag.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/correctly_marked_dag/migration_state/marked_dag.yaml
- examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/incorrectly_marked_dag/migration_state/some_other_dag.yaml
- examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_cacheable_asset.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/migration_state_yamls/extra_key/extra_key.yaml
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/migration_state_yamls/nonsense/nonsense_value.yaml
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/migration_state_yamls/valid/first.yaml
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/migration_state_yamls/valid/second.yaml
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_migration_state.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/migration_state/dbt_dag.yaml
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/migration_state/load_lakehouse.yaml
- examples/experimental/dagster-airlift/examples/simple-migration/simple_migration/airflow_dags/dagster_migration/simple.yaml
Switch migration state format to match https://github.com/dagster-io/dagster/pull/23756/files#r1729588955
> [dagster-airlift] update migration state format

- examples/experimental/dagster-airlift/README.md
Making code examples include all imports and eliminating direct usage of AssetKey for verbosity reduction.
Read
NOCHANGELOG
> Pass on tutorial for code example include-ability and reduced verbosity

- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_python_multi_assets.py
Fix broken test in airlift
BK and local pytest
NOCHANGELOG
> Fix broken test in airlift

- python_modules/dagster/dagster/_api/list_repositories.py
- python_modules/dagster/dagster/_api/snapshot_repository.py
- python_modules/dagster/dagster/_grpc/client.py
- python_modules/dagster/dagster_tests/api_tests/test_api_list_repositories.py
- python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_repository.py
- python_modules/dagster/setup.py
Summary:
Allows callsites to load multiple repositories in parallel.
> asyncio methods for grpc repository loading methods

- docs/docs-beta/docs/guides/quality-testing/unit-tests-assets-and-ops.md
- examples/docs_beta_snippets/docs_beta_snippets/guides/quality-testing/unit-testing-assets-and-ops/asset-combo.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/quality-testing/unit-testing-assets-and-ops/asset-config.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/quality-testing/unit-testing-assets-and-ops/asset-context.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/quality-testing/unit-testing-assets-and-ops/asset-dependency.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/quality-testing/unit-testing-assets-and-ops/asset-no-argument.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/quality-testing/unit-testing-assets-and-ops/asset-resource.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/quality-testing/unit-testing-assets-and-ops/op-combo.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/quality-testing/unit-testing-assets-and-ops/op-config.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/quality-testing/unit-testing-assets-and-ops/op-context.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/quality-testing/unit-testing-assets-and-ops/op-dependency.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/quality-testing/unit-testing-assets-and-ops/op-no-argument.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/quality-testing/unit-testing-assets-and-ops/op-resource.py
- examples/docs_beta_snippets/setup.py
Added guide for unit testing assets and ops
> [DOC-348] Docs for asset and op unit testing

- examples/experimental/dagster-airlift/README.md
- examples/experimental/dagster-airlift/examples/tutorial-example/Makefile
Update to use port 3000. Also add some env vars we need on the dagster end (that we lost when we moved off makefile)
`NOCHANGELOG`
> [airlift] Tweak ports to 3000 in tutorial, update readme

- js_modules/dagster-ui/README.md
We don't really describe what steps we would like external contributors to take when they put up pull requests. Here's a basic initial readme to give a bit of guidance.
Preview
NOCHANGELOG
> [ui] Add a brief readme to dagster-ui

- js_modules/dagster-ui/packages/app-oss/src/NUX/CommunityNux.tsx
- js_modules/dagster-ui/packages/app-oss/src/telemetryLink.tsx
- js_modules/dagster-ui/packages/eslint-config/CHANGES.md
- js_modules/dagster-ui/packages/eslint-config/package.json
- js_modules/dagster-ui/packages/ui-core/src/apollo-client/index.tsx
- js_modules/dagster-ui/yarn.lock
Also add the one exception to the newly added rule
NOCHANGELOG
> Update eslint-config package version 

- examples/experimental/dagster-airlift/README.md
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/dags.py
- examples/experimental/dagster-airlift/examples/tutorial-example/migrate.py
- examples/experimental/dagster-airlift/examples/tutorial-example/observe.py
- examples/experimental/dagster-airlift/examples/tutorial-example/standalone.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/airflow_dags/dags.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/definitions.py
Did a runthrough and found a few issues. Fixing here.
Went through the entire tutorial.
NOCHANGELOG
> Minor fixups to README from runthrough

- CHANGES.md
> 1.8.4 Changelog

- docs/docs-beta/docs/dagster-plus/deployment/serverless/run-isolation.md
- docs/vale/styles/config/vocabularies/Dagster/accept.txt
Ported run isolation docs. Cleaned up a bit of the prose but I didn't make too many changes.
Biggest missing thing is I don't know if deployment settings have a fixed yaml filename. Maybe my reviewer @shalabhc knows?
NOCHANGELOG
> [docathon] Port run isolation docs

- examples/experimental/dagster-airlift/examples/tutorial-example/Makefile
- examples/experimental/dagster-airlift/examples/tutorial-example/README.md
- examples/experimental/dagster-airlift/examples/tutorial-example/setup.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/airflow_dags/dags.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/migrate.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/migrate_with_check.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/peer_with_check.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/standalone.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/conftest.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_migrate_with_check_e2e.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_peer_with_check_e2e.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/utils.py
Adds a new step which showcases appending an asset check to the tutorial code
`NOCHANGELOG`
> [airlift] add asset check

- docs/docs-beta/docs/dagster-plus/deployment/code-locations.md
This doc outlines how to add code locations. I intentionally did not cover the UI "Add code location" button or NUX:
- For the NUX, the guide would be almost entirely screenshots
- For non-NUX, the "Add code location" button is not a path I recommend since it rarely does the right thing, and does not work for Hybrid users
vale
yarn start
NOCHANGELOG
> [DOC 364] lopp/doc-364-write-creating-dagster-code-locations

- docs/docs-beta/docs/dagster-plus/insights/google-bigquery-dbt.md
- docs/docs-beta/docs/dagster-plus/insights/google-bigquery.md
- examples/docs_beta_snippets/docs_beta_snippets/dagster-plus/insights/google-bigquery/bigquery-dbt-asset-insights.py
- examples/docs_beta_snippets/docs_beta_snippets/dagster-plus/insights/google-bigquery/bigquery-dbt-asset.py
- examples/docs_beta_snippets/docs_beta_snippets/dagster-plus/insights/google-bigquery/bigquery-resource-insights.py
- examples/docs_beta_snippets/docs_beta_snippets/dagster-plus/insights/google-bigquery/bigquery-resource.py
- examples/docs_beta_snippets/docs_beta_snippets/dagster-plus/insights/google-bigquery/constants.py
- examples/docs_beta_snippets/docs_beta_snippets/dagster-plus/insights/google-bigquery/dbt_project.yml
- examples/docs_beta_snippets/docs_beta_snippets/dagster-plus/insights/google-bigquery/dbt_project_insights.yml
- examples/docs_beta_snippets/docs_beta_snippets/dagster-plus/insights/google-bigquery/manifest.json
- examples/docs_beta_snippets/tox.ini
Adds a guide explaining how to integrate BigQuery usage information with Dagster Insights
NOCHANGELOG
> DOC-421 DOC-422 BigQuery Insights

- docs/docs-beta/docs/dagster-plus/insights/snowflake-dbt.md
- docs/docs-beta/docs/dagster-plus/insights/snowflake.md
- examples/docs_beta_snippets/docs_beta_snippets/dagster-plus/insights/google-bigquery/constants.py
- examples/docs_beta_snippets/docs_beta_snippets/dagster-plus/insights/snowflake/dbt_project.yml
- examples/docs_beta_snippets/docs_beta_snippets/dagster-plus/insights/snowflake/dbt_project_insights.yml
- examples/docs_beta_snippets/docs_beta_snippets/dagster-plus/insights/snowflake/manifest.json
- examples/docs_beta_snippets/docs_beta_snippets/dagster-plus/insights/snowflake/snowflake-dbt-asset-insights.py
- examples/docs_beta_snippets/docs_beta_snippets/dagster-plus/insights/snowflake/snowflake-dbt-asset.py
- examples/docs_beta_snippets/docs_beta_snippets/dagster-plus/insights/snowflake/snowflake-resource-insights.py
- examples/docs_beta_snippets/docs_beta_snippets/dagster-plus/insights/snowflake/snowflake-resource.py
Adds a guide for ingesting Snowflake usage info into Insights.
NOCHANGELOG
> DOC-424 DOC-425 Snowflake Insights Guide

- examples/experimental/dagster-airlift/Makefile
- examples/experimental/dagster-airlift/scripts/build_and_publish.sh
- examples/experimental/dagster-airlift/scripts/increment_pypi_version.sh
- examples/experimental/dagster-airlift/setup.py
A few things were broken about the release process:
- scripts had changed directory
- Failure during the last step wouldn't properly induce removal of directories
- Pypi version was wrong
> [dagster-airlift] fix release process

- examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py
- examples/experimental/dagster-airlift/examples/tutorial-example/README.md
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/airflow_dags/dags.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/definitions.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/migrate.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/migrate_with_check.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/standalone.py
- examples/experimental/dagster-airlift/scripts/update_readme_snippets.py
Few more touchups to tutorials and snippets based on a last run-through. Everything seemed to work except the migrated load csv step, which has some relative filepath trickiness that this PR fixes.
This PR also explicitly asks the user to work in the blank `definitions.py` file, which should hopefully remove another potential source of error.
> [airlift] One last tutorial pass

- examples/experimental/dagster-airlift/examples/tutorial-example/README.md
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/airflow_dags/dags.py
Minor changes to tutorial based on final runthrough
1. uv pip install 'dagster-airlift[dbt]'
2. Bolding Important for refresh code locations
3. Default dags.py to `MIGRATING = False`
Read
NOCHANGELOG
> Minor set of changes based on final runthrough

- examples/experimental/dagster-airlift/examples/tutorial-example/Makefile
- examples/experimental/dagster-airlift/examples/tutorial-example/scripts/airflow_setup.sh
- examples/experimental/dagster-airlift/examples/tutorial-example/setup.py
- examples/experimental/dagster-airlift/setup.py
Copy setup script, and refer to it instead of from parent file. Remove version from setup.py. Bump version to 0.0.11
> [airlift] mirror repo prep

- docs/docs-beta/docs/dagster-plus/access/authentication/azure-ad-sso.md
- docs/docs-beta/docs/dagster-plus/access/authentication/google-workspace-sso.md
- docs/docs-beta/docs/dagster-plus/access/authentication/okta-scim.md
- docs/docs-beta/docs/dagster-plus/access/authentication/okta-sso.md
- docs/docs-beta/docs/dagster-plus/access/authentication/onelogin-sso.md
- docs/docs-beta/docs/dagster-plus/access/authentication/pingone-sso.md
- docs/docs-beta/docs/partials/_TestSSO.md
- docs/vale/styles/config/vocabularies/Dagster/accept.txt
These docs were in pretty good shape. Mostly just copy paste with small changes here and there, image replacements, link changes, and formatting updates
NOCHANGELOG
> [docathon] Knock out all the SSO docs migrations DOC-390 DOC-391 DOC-392 DOC-393

- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/dags.py
- scripts/generate_changelog.py
A variety of small fixes to the changelog script
NOCHANGELOG
> Fixup changelog script

- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_migrate_with_check_e2e.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_migrating_e2e.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_observing_e2e.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_peer_with_check_e2e.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_peering_e2e.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/utils.py
Notice that these have been flaking occasionally - bump up potential wait time and explicitly wait for runs to finish.
> [airlift] some tweaks to prevent e2e test flakes

- docs/docs-beta/docs/dagster-plus/access/authentication/google-workspace-sso.md
> [docathon] fix broken anchor ref in google sso

- docs/docs-beta/docs/dagster-plus/access/rbac/teams.md
> [docs] Team Management in Dagster+ guide

- examples/experimental/dagster-airlift/setup.py
> Bump airlift version to 0.12.0

- docs/docs-beta/docs/dagster-plus/deployment/hybrid/agents/kubernetes.md
I'm not sure what balance we want to strike here between maximal configuration description and minimal path to getting set up.
> Refresh Dagster+ K8s agent install guide

- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_observing_e2e.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_peering_e2e.py
> [airlift] mute e2e tests for now

- docs/docs-beta/docs/guides/deployment/docker.md
- docs/docs-beta/docusaurus.config.ts
> [docs-beta] docker compose deployment guide

- docs/docs-beta/docs/dagster-plus/access/authentication.md
- docs/docs-beta/docs/dagster-plus/access/authentication/scim-provisioning.md
- docs/docs-beta/docs/dagster-plus/access/rbac/users.md
2 screenshots are missing - TODOs added in the guide.
> [docs] User Management in Dagster + guide

- docs/docs-beta/docs/about/releases.md
> [docs-beta] add content for releases & compatibility page

- docs/docs-beta/docs/dagster-plus/access/rbac/teams.md
- docs/docs-beta/docs/dagster-plus/access/rbac/users.md
- docs/docs-beta/docs/dagster-plus/deployment/hybrid/agents/kubernetes.md
> [docs-revap] - Fix links

- docs/docs-beta/docs/guides/data-modeling/asset-factories-with-deps.md
- examples/docs_beta_snippets/docs_beta_snippets/guides/data-modeling/asset-factories-with-deps/asset-factory-with-deps.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/data-modeling/asset-factories-with-deps/asset_downstream_of_factory_assets.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/data-modeling/asset-factories-with-deps/table_definitions.yaml
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/dags.py
> Add doc for asset factory with deps

- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/dags.py
- examples/experimental/dagster-airlift/setup.py
> [airlift] bump to 0.0.13

- examples/experimental/dagster-airlift/setup.py
Adds https://github.com/dagster-io/dagster/pull/24138
> [dagster-airlift] 0.0.14

- examples/experimental/dagster-airlift/setup.py
Includes https://github.com/dagster-io/dagster/pull/24142#event-14095431784 and https://github.com/dagster-io/dagster/pull/24143
> [dagster-airlift] 0.0.15

- python_modules/dagster/dagster/_generate/download.py
All examples need to be enumerated in this CLI file, adds this new example to the list to fix bk.
`NOCHANGELOG`
> include new example in cli code, fix bk

- examples/experimental/dagster-airlift/dagster_airlift/core/airflow_instance.py
- examples/experimental/dagster-airlift/dagster_airlift/test/__init__.py
- examples/experimental/dagster-airlift/dagster_airlift/test/airflow_test_instance.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_test_utils.py
Create an AirflowTestInstance class and some convenience methods to make test initialization less esoteric. 
Downstream PRs will replace the previous testing abstraction.
> [dagster-airlift] improved test utils

- js_modules/dagster-ui/packages/ui-core/src/graph/KindTags.tsx
- js_modules/dagster-ui/packages/ui-core/src/search/BuildAssetSearchResults.tsx
- js_modules/dagster-ui/packages/ui-core/src/search/SearchResults.tsx
- js_modules/dagster-ui/packages/ui-core/src/search/types.ts
- js_modules/dagster-ui/packages/ui-core/src/search/useGlobalSearch.tsx
- js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedAssetRow.tsx
More cleanup - will be stacked with above PR and an internal companion
https://github.com/dagster-io/internal/pull/11269
> [ui] Further remove references to storage kind

- python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
Summary:
Some storages can call .wipe(), others can only call .wipe_asset_key(). Also the tests that involved asset events were doing some funky stuff with generating events from an entirely separate instance that is no longer needed since the instance is a fixture and wiped after every test run.
Test Plan: BK
> Refactor TestEventLogStorage in advance of making all storages able to wipe assets

- examples/docs_beta_snippets/docs_beta_snippets/guides/data-assets/data-assets/asset_decorator.py
- Fixes ruff for recently added example
NOCHANGELOG
> fix(ruff) replace unused methods with context.log

- examples/experimental/dagster-airlift/dagster_airlift/core/airflow_instance.py
- examples/experimental/dagster-airlift/dagster_airlift/test/__init__.py
- examples/experimental/dagster-airlift/dagster_airlift/test/airflow_test_instance.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/conftest.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_build_defs.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_dbt_defs_migrated.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_sensor.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_test_utils.py
Refactors tests to use the new framework.
> [dagster-airlift] test refactors and fixes

- examples/experimental/dagster-airlift/setup.py
Adds https://github.com/dagster-io/dagster/pull/24147
> [dagster-airlift] 0.0.16

- docs/content/integrations/pandera.mdx
Docs only change.
Didn't.
> `NOCHANGELOG`
> Fix typo dagster-pandera

- python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_cli_invocation.py
Fixes bug where some raw dbt logs not getting handled correctly.
Blamerev: https://github.com/dagster-io/dagster/pull/22559/
Inspection
* [dagster-dbt] fix bug where some forms of raw dbt logs (empty newlines) were not being handled correctly
> handle json parsing errors from dbt log

- python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
> New test case that includes fetching the most recent asset+partition combo for materializations and observations

- docs/docs-beta/docs/guides/tbd/selection-syntax.md
> small tweak to selection syntax reference

- docs/docs-beta/docs/guides/ingestion-transformation/ingesting-data.md
> [docs-beta] re-introduce missing ingestion example

- examples/experimental/dagster-airlift/examples/tutorial-example/README.md
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/airflow_dags/plus_proxy_operator.py
- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/unit_tests/test_proxy_operators.py
Copy-paste example for a dagster plus proxy operator
> [dagster-airlift] dagster cloud proxy operator example

- js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationOverviewRoot.tsx
- js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationServerSection.oss.tsx
Add `locationName` as a prop on this Plus-only component.
TS.
NOCHANGELOG
> [ui] Provide locationName to code location server metrics

- docs/content/concepts/automation/schedules/automating-assets-schedules-jobs.mdx
This is what `make mdx-format` spit out.
> Fixup docs snippets

- examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example_tests/integration_tests/test_peer_with_check_e2e.py
> [dagster-airlift] skip flaky test

- python_modules/libraries/dagster-tableau/.coveragerc
- python_modules/libraries/dagster-tableau/LICENSE
- python_modules/libraries/dagster-tableau/MANIFEST.in
- python_modules/libraries/dagster-tableau/README.md
- python_modules/libraries/dagster-tableau/dagster_tableau/__init__.py
- python_modules/libraries/dagster-tableau/dagster_tableau/py.typed
- python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_version.py
- python_modules/libraries/dagster-tableau/setup.cfg
- python_modules/libraries/dagster-tableau/setup.py
- python_modules/libraries/dagster-tableau/tox.ini
Adds a barebones `dagster-tableau` package
Set up not to publish right now (no version.py)
BK with additional tests
> [1/n][dagster-tableau] Add dagster-tableau package

- docs/content/about/releases.mdx
> Add docs on version compatibility within a deployment

- CHANGES.md
> 1.8.5 Changelog

- CHANGES.md
Summary:
Hoping to just catch the last train out with this change.
Test Plan: BK
> Add k8s pipes fix to changelog

- .github/PULL_REQUEST_TEMPLATE.md
As title. Leaving the below sections unaltered to illustrate.
This workflow for selecting a category is a bit easier / more obvious.
> Update Changelog template

- python_modules/dagster/dagster/_core/remote_representation/external_data.py
> null out acs

- scripts/run-pyright.py
This updates `scripts/run-pyright.py` to guard against a very frustrating failure mode in environment buliding.
Editable installs place a `.pth` file into a python environment's `site-packages` directory. A "pth" file is resolved by the python import system to some directory that is not already present in `site-packages`.
There is a "modern" and "legacy" version of `pth` files. Build backends like `setuptools` (which is what we use for dagster packages) will generate a modern pth file by default during install. The modern pth file contains code that has to be executed, and **is not interpretable by pyright (or any other static static analyzer, to my knowledge)**. The legacy pth file format is simply an absolute path to the target directory. The legacy format is understood by pyright.
This …
> [pyright] Guard against modern editable installs in pyright envs

- examples/experimental/dagster-airlift/setup.py
- https://github.com/dagster-io/dagster/pull/24231
- https://github.com/dagster-io/dagster/pull/24236
- https://github.com/dagster-io/dagster/pull/24238
`NOCHANGELOG`
> [dagster-airlift] 0.0.22

- Makefile
> Use uv for make install_pyright

- docs/sphinx/conf.py
Small QOL change to avoid having to manually add packages to Sphinx imports.
make apidoc-build
vercel docs
NOCHANGELOG
> [docs] automate adding python modules to sphinx

- CHANGES.md
> Add bug fix for dbt assets downstream of Sling to changelog

- examples/experimental/dagster-airlift/dagster_airlift/core/airflow_cacheable_assets_def.py
- examples/experimental/dagster-airlift/dagster_airlift/core/sensor.py
- examples/experimental/dagster-airlift/dagster_airlift/core/utils.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_build_defs.py
- examples/experimental/dagster-airlift/examples/dbt-example/Makefile
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/migration_state/dbt_dag.yaml-e
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/migration_state/load_lakehouse.yaml-e
- examples/experimental/dagster-airlift/scripts/find_and_replace_in_yaml_dir.sh
- python_modules/dagster/dagster/_core/definitions/asset_out.py
- python_modules/libraries/dagster-dbt/dagster_dbt/asset_specs.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py
Use kinds tag, which means we can get rid of the multi asset bs we do.
This kind of unfurled a rabbit hole of changes.
`NOCHANGELOG`
Ran through the dbt tutorial to get everything working. There will probably be additional tests that break that I need to fix.
> [dagster-airlift] use kinds and cascade changes

- Makefile
bk isnt happy with this due to venv issues
> Revert "Use uv for make install_pyright (#24291)"

- python_modules/libraries/dagster-powerbi/dagster_powerbi/translator.py
> remove unused POWERBI_PREFIX constant

- docs/content/concepts/automation.mdx
> docs: update automation.mdx

- python_modules/libraries/dagster-polars/dagster_polars/io_managers/utils.py
- python_modules/libraries/dagster-polars/dagster_polars_tests/conftest.py
> [dagster-polars] :bug: fix decimal type

- examples/docs_beta_snippets/docs_beta_snippets/getting-started/hello-world.py
ruff suggests this reformatting
> ruff - reformat

- CHANGES.md
Summary:
Add fix for serverless IO manager issue.
> 1.8.6 changelog

- .github/workflows/build-docs-revamp.yml
> [docs-beta] push to prod on PRs

- python_modules/dagster/dagster/_core/execution/submit_asset_runs.py
Summary: https://github.com/dagster-io/dagster/pull/21631 was a little overzealous and assumed that any error raised during execution plan creation was retryable, but there are several that are not (for example, missing config, missing env vars, etc.). This PR walks that back and only triggers the retry on the invalid subset errors specifically.
Test Plan: We had a lovely automated test for this that was sadly reverted in https://github.com/dagster-io/dagster/pull/23777. For now, manually added raising a DagsterInvalidSubsetError and another error in the ExecutionPlanSnapshot grpc server call - verified that the former is retried when running an asset backfill and the latter is not.
> only retry asset run submission on DagsterInvalidSubsetError raised within a code server process, not all code server errors

- js_modules/dagster-ui/packages/ui-components/CHANGES.md
- js_modules/dagster-ui/packages/ui-components/package.json
- js_modules/dagster-ui/packages/ui-components/src/index.ts
Want to consolidate on using VirtualizedTable from ui-components
https://linear.app/dagster-labs/issue/FE-565/consolidate-on-using-virtualizedtable-from-ui-components-and-remove
NOCHANGELOG
> [1/n] Add VirtualizedTable export in ui-components

- docs/docs-beta/docs/guides/pipelines.md
- docs/docs-beta/sidebars.ts
Adds a Create a pipeline overview guide that walks through the 5 basic steps of building a pipeline. 
NOCHANGELOG
> [docs-beta] add Create a pipeline guide

- docs/docs-beta/docusaurus.config.ts
- Disabling Vercel build and re-introducing anchor checks now that we know it works
NOCHANGELOG
> [docs-beta] re-introduce anchor validation

- examples/experimental/dagster-airlift/setup.py
https://github.com/dagster-io/dagster/pull/24333
> [dagster-airlift] 0.0.23

- CHANGES.md
- scripts/generate_changelog.py
> 1.8.7 CHANGELOG

- docs/docs-beta/docs/dagster-plus/access/rbac/teams.md
- docs/docs-beta/docs/dagster-plus/deployment/branch-deployments/setting-up-branch-deployments.md
- docs/docs-beta/docs/dagster-plus/deployment/code-locations/code-location-history.md
- docs/docs-beta/docs/dagster-plus/deployment/environment-variables/dagster-ui.md
- docs/docs-beta/docs/dagster-plus/deployment/hybrid/agents/local.md
- docs/docs-beta/docs/dagster-plus/deployment/hybrid/architecture.md
- docs/docs-beta/docs/dagster-plus/deployment/serverless/run-isolation.md
- docs/docs-beta/docs/dagster-plus/deployment/serverless/transition-hybrid.md
- docs/docs-beta/docs/dagster-plus/insights/asset-metadata.md
> [docs-beta] rm "what you'll learn" from dagster+ guides

- docs/docs-beta/docs/dagster-plus/access/rbac/teams.md
- docs/docs-beta/docs/dagster-plus/deployment/branch-deployments/setting-up-branch-deployments.md
- docs/docs-beta/docs/dagster-plus/deployment/code-locations/code-location-history.md
- docs/docs-beta/docs/dagster-plus/deployment/environment-variables/dagster-ui.md
- docs/docs-beta/docs/dagster-plus/deployment/hybrid/agents/local.md
- docs/docs-beta/docs/dagster-plus/deployment/hybrid/architecture.md
- docs/docs-beta/docs/dagster-plus/deployment/serverless/run-isolation.md
- docs/docs-beta/docs/dagster-plus/deployment/serverless/transition-hybrid.md
- docs/docs-beta/docs/dagster-plus/insights/asset-metadata.md
- docs/docs-beta/docs/guides/apis.md
- docs/docs-beta/docs/guides/asset-factories-with-deps.md
- docs/docs-beta/docs/guides/asset-factories.md
- docs/docs-beta/docs/guides/automation.md
- docs/docs-beta/docs/guides/configuring-assets.md
- docs/docs-beta/docs/guides/custom-logging.md
- docs/docs-beta/docs/guides/databases.md
- docs/docs-beta/docs/guides/docker.md
- docs/docs-beta/docs/guides/ingesting-data.md
- docs/docs-beta/docs/guides/kubernetes.md
- docs/docs-beta/docs/guides/metadata.md
- docs/docs-beta/docs/guides/partitioning.md
- docs/docs-beta/docs/guides/pipelines.md
- docs/docs-beta/docs/guides/project-structure.md
- docs/docs-beta/docs/guides/transform-dbt.md
> [docs-beta] rm "what you'll learn" from guides

- docs/docs-beta/content-templates/guide-no-steps.md
- docs/docs-beta/content-templates/guide-with-steps.md
- docs/docs-beta/docs/dagster-plus/access/rbac/teams.md
- docs/docs-beta/docs/dagster-plus/deployment/branch-deployments/setting-up-branch-deployments.md
- docs/docs-beta/docs/dagster-plus/deployment/code-locations/code-location-history.md
- docs/docs-beta/docs/dagster-plus/deployment/environment-variables/dagster-ui.md
- docs/docs-beta/docs/dagster-plus/deployment/hybrid/agents/local.md
- docs/docs-beta/docs/dagster-plus/deployment/hybrid/architecture.md
- docs/docs-beta/docs/dagster-plus/deployment/serverless/run-isolation.md
- docs/docs-beta/docs/dagster-plus/deployment/serverless/transition-hybrid.md
- docs/docs-beta/docs/dagster-plus/insights/asset-metadata.md
- docs/docs-beta/docs/guides/apis.md
- docs/docs-beta/docs/guides/asset-factories-with-deps.md
- docs/docs-beta/docs/guides/asset-factories.md
- docs/docs-beta/docs/guides/automation.md
- docs/docs-beta/docs/guides/configuring-assets.md
- docs/docs-beta/docs/guides/custom-logging.md
- docs/docs-beta/docs/guides/databases.md
- docs/docs-beta/docs/guides/docker.md
- docs/docs-beta/docs/guides/ingesting-data.md
- docs/docs-beta/docs/guides/kubernetes.md
- docs/docs-beta/docs/guides/metadata.md
- docs/docs-beta/docs/guides/partitioning.md
- docs/docs-beta/docs/guides/pipelines.md
- docs/docs-beta/docs/guides/project-structure.md
- docs/docs-beta/docs/guides/transform-dbt.md
> [docs-beta] rm "what you'll learn" from content templates

- js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx
Make sure that cross-push issues are not cached
Inspection
> bump indexed cache key for asset graph data

- CHANGES.md
Summary:
I am still adjusting to the new workflow and neglected to add these.
> Add my 1.8.7 changelog entries

- js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/WorkspaceContext.tsx
- js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/types/WorkspaceQueries.types.ts
existing jest tests pass, still trying to confirm it fixes the issue, will due that shortly on Daniel's computer.
NOCHANGELOG
> Fix workspace context issue

- python_modules/dagster/dagster/_core/storage/dagster_run.py
> convert RunsFilter to @record

- js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/WorkspaceContext.tsx
- js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/__tests__/WorkspaceContext.test.tsx
With the help of ChatGPT this PR refactors WorkspaceContext by applying the Single Responsibility Principle to encapsulate logic into smaller functions and make WorkspaceContext easier to read at a high level.
Existing jest tests pass.
Load local host cloud normally.
NOCHANGELOG
> Refactor WorkspaceContext

- examples/experimental/dagster-airlift/dagster_airlift/test/shared_fixtures.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/dags.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example_tests/integration_tests/conftest.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example_tests/integration_tests/test_load_dagster.py
- examples/experimental/dagster-airlift/examples/dbt-example/tox.ini
- examples/experimental/dagster-airlift/examples/perf-harness/perf_harness_tests/test_e2e.py
DBT example tests were insufficient. Follow example of perf harness and improve testing.
> [dagster-airlift] better dbt example tests

- python_modules/libraries/dagster-k8s/dagster_k8s/client.py
- python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_client.py
From https://github.com/dagster-io/dagster/pull/24432 - hitting this exception 
```
container_status = next(
s for s in all_statuses if s.name not in exited_containers | ready_initcontainers
)
StopIteration
```	   
in our integration tests (that unfortunately do not run on external contributions) 
Due to not handling init containers that do not continue running and terminate quickly. Update the code to handle that case as well.
added test
> [k8s client] handle terminated init containers

- docs/docs-beta/docs/guides/asset-sensors.md
- examples/docs_beta_snippets/docs_beta_snippets/guides/automation/asset-sensor-with-config.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/automation/multi-asset-sensor.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/automation/simple-asset-sensor-example.py
> [docs-revamp] - Clean up Asset Sensors guide

- python_modules/libraries/dagster-powerbi/dagster_powerbi/resource.py
- python_modules/libraries/dagster-powerbi/dagster_powerbi/translator.py
- python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_asset_specs.py
- python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_translator.py
Introduces URL metadata to link to a PowerBI instance, along with new-style kind tags.
Updated a few unit tests
> [dagster-powerbi] Add url, kinds to PowerBI assets

- docs/content/about/releases.mdx
> fix typo on releases page

- python_modules/automation/tox.ini
> fix resource telemetry test

- js_modules/dagster-ui/packages/ui-core/src/search/SearchResults.tsx
Add "Enter" to the right
NOCHANGELOG
> Udate search result item

- docs/docs-beta/yarn.lock
- docs/next/yarn.lock
- js_modules/dagster-ui/yarn.lock
Clean up a whole bunch of dependabot alerts related to `express` and its dependencies.
`yarn why`
NOCHANGELOG
> [ui] Fix dependabot alerts related to express

- docs/docs-beta/docs/guides/ingesting-data.md
- examples/docs_beta_snippets/docs_beta_snippets/guides/data-ingestion/custom-data-ingestion.py
> [docs-revamp] - Clean up Ingesting data guide

- python_modules/libraries/dagster-docker/dagster_docker/docker_run_launcher.py
- python_modules/libraries/dagster-docker/dagster_docker_tests/test_launch_docker.py
Summary:
This will help diagnose transient issues where the docker api appears to be incorrectly returning that a container is running when it is not.
Test Plan: New automated test case, run a crashy docker op locally and check run logs
- `NEW` [dagster-docker] Added additional information about the container to the event log when a run using the `DockerRunLauncher` fails due to the container unexpectedly exiting.
> Include full docker container state in failure message when a run worker fails

- docs/content/guides/dagster/enriching-with-software-defined-assets.mdx
> [docs] fix typo

- js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedRoot.tsx
> fix bad import reference to fix build

- docs/dagster-university/package.json
- docs/dagster-university/yarn.lock
- docs/next/package.json
- docs/next/yarn.lock
Resolves: 
- https://github.com/dagster-io/dagster/security/dependabot/636
- https://github.com/dagster-io/dagster/security/dependabot/635
`yarn why`
NOCHANGELOG
> [ui] Bump next in docs and daggy u

- python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_runs_feed.py
> Add runs feed filters to graphene layer

- scripts/generate_changelog.py
This updates the changelog script to actually write to CHANGES.md
NOCHANGELOG
> Update generate_changelog script

- python_modules/dagster/dagster/_serdes/utils.py
you can pass the bytes in to constructor, skip update call
> tidy up hash_str

- docs/docs-beta/docs/guides/unit-tests-assets-and-ops.md
> [docs-revamp] - Clean up Unit testing guide

- python_modules/dagster/dagster/_core/definitions/partitioned_schedule.py
Example code will error without importing Definitions
👀
NOCHANGELOG
> [docs] Add missing import to build_schedule_from_partitioned_job docstring

- docs/docs-beta/docs/guides/schedules.md
- examples/docs_beta_snippets/docs_beta_snippets/guides/automation/schedule-with-partition-ops.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/automation/schedule-with-partition.py
> [docs-revamp] - Clean up Schedules guide

- .github/workflows/build-docs-revamp.yml
not sure, going to test in prod 😃 
`NOCHANGELOG`
> update build-docs-revamp gh action to default to configured custom domains

- CHANGES.md
- scripts/generate_changelog.py
> 1.8.8 Changelog

- js_modules/dagster-ui/packages/ui-core/src/assets/LaunchAssetExecutionButton.tsx
Arghhh vscode auto-import
Plus dev no longer dies.
Grep for `shared/` paths, verify that there are no others.
NOCHANGELOG
> [ui] Fix incorrect shared import

- docs/docs-beta/docs/guides/data-freshness-testing.md
- examples/docs_beta_snippets/docs_beta_snippets/guides/data-assets/quality-testing/freshness-checks/external-asset-freshness-check.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/data-assets/quality-testing/freshness-checks/materializable-asset-freshness-check.py
> [docs-revamp] - Clean up Data freshness guide

- docs/docs-beta/docs/guides/non-python.md
- examples/docs_beta_snippets/docs_beta_snippets/guides/non-python/pipes-asset.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/non-python/pipes-full-featured-javascript.js
> [docs-revamp] - Clean up Pipes guide

- docs/docs-beta/docs/guides/configuring-assets.md
- examples/docs_beta_snippets/docs_beta_snippets/guides/data-modeling/asset-factories/python-asset-factory.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/data-modeling/configuring-assets/config-schema.py
> [docs-revamp] - Clean up asset configuration guide

- docs/docs-beta/docs/guides/sensors.md
- examples/docs_beta_snippets/docs_beta_snippets/guides/automation/sensor-cursor.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/automation/simple-sensor-example.py
> [docs-revamp] - Clean up Sensors guide

- examples/experimental/dagster-airlift/examples/dbt-example/Makefile
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example_tests/integration_tests/conftest.py
- examples/experimental/dagster-airlift/examples/perf-harness/Makefile
- examples/experimental/dagster-airlift/examples/perf-harness/perf_harness_tests/conftest.py
Fix some nonsense about pytest fixture inheritance that was causing a misleading error to appear in the output. Also use better convention for makefile format.
> [dagster-airlift] fix test fixture inheritance

- python_modules/libraries/dagster-sigma/dagster_sigma/__init__.py
- python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
- python_modules/libraries/dagster-sigma/dagster_sigma/translator.py
- python_modules/libraries/dagster-sigma/dagster_sigma_tests/conftest.py
- python_modules/libraries/dagster-sigma/dagster_sigma_tests/test_translator.py
Introduces standard translator class to build Sigma specs. Pulls various pieces of metadata off assets, builds dependencies, and partial column schema for datasets.
Unit tests.
> NOCHANGELOG
> [4/n][dagster-sigma] Build out translator class

- docs/docs-beta/docs/guides/asset-factories.md
> [docs-revamp] - Clean up Asset factories guide

- docs/docs-beta/docs/guides/io-managers.md
- docs/vale/styles/Dagster/headings-casing.yml
- docs/vale/styles/config/vocabularies/Dagster/accept.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/external-systems/assets-with-io-managers.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/external-systems/assets-with-snowflake-io-manager.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/external-systems/assets-without-io-managers.py
> [docs-revamp] - Clean up I/O managers guide

- python_modules/dagster/dagster/_core/definitions/asset_graph.py
- python_modules/dagster/dagster/_core/definitions/asset_graph_computation.py
- python_modules/dagster/dagster/_core/definitions/asset_key.py
- python_modules/dagster/dagster/_core/definitions/asset_layer.py
- python_modules/dagster/dagster/_core/definitions/assets.py
- python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
- python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
As title, this replaces all "asset_or_check" / "AssetKeyOrCheckKey" occurences with the simpler "entity".
This paves the way for adding more types to this set in the future.
NOCHANGELOG
> [rename] AssetOrCheck -> Entity

- docs/docs-beta/docs/guides/asset-checks.md
- examples/docs_beta_snippets/docs_beta_snippets/guides/data-assets/quality-testing/asset-checks/asset-checks-with-schedule-and-sensor.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/data-assets/quality-testing/asset-checks/block-downstream-with-asset-checks.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/data-assets/quality-testing/asset-checks/multiple-asset-checks.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/data-assets/quality-testing/asset-checks/single-asset-check.py
> [docs-revamp] - Clean up Asset Checks guide

- python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
- python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/__init__.py
- python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/check_operators.py
- python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py
- python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_check_condition.py
- python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/scenario_state.py
Creates Any/AllChecksMatch operators to allow us to create AutomationConditions that depend on the status of a check.
NOCHANGELOG
> Create check operators

- python_modules/dagster/dagster/_core/asset_graph_view/entity_subset.py
- python_modules/dagster/dagster/_core/asset_graph_view/serializable_entity_subset.py
- python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
Just found this useful when debugging -- prints out the full AutomationResult in a human-readable way, similar to what you'd see in the UI.
NOCHANGELOG
> Pretty print AutomationResult, EntitySubset, SerializableEntitySubset

- python_modules/dagster/dagster/_record/__init__.py
- python_modules/dagster/dagster_tests/general_tests/test_record.py
As title -- this makes the test pass where it would not before.
NOCHANGELOG
> [record] Fix resolution of fields defined on base record classes.

- python_modules/dagster-webserver/dagster_webserver/graphql.py
This provides a hook to DagsterWebserver that allows you to monitor how long a request spends waiting for a thread to pick it up
Existing tests should be sufficient, these are just instrumentation hooks
> monitor thread queue latency in DagsterWebserver

- docs/content/integrations/sigma.mdx
- docs/next/next-env.d.ts
- docs/tox.ini
- examples/docs_snippets/docs_snippets/integrations/sigma/customize-sigma-asset-defs.py
- examples/docs_snippets/docs_snippets/integrations/sigma/multiple-sigma-organizations.py
- examples/docs_snippets/docs_snippets/integrations/sigma/representing-sigma-assets.py
- pyright/master/requirements-pinned.txt
- pyright/master/requirements.txt
Initial pass of `dagster-sigma` docs, unlisted, so we can send to design partners.
> [dagster-sigma][docs] Add basic dagster-sigma docs

- python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
> Fix subclassing

- examples/experimental/dagster-airlift/examples/dbt-example/Makefile
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/dags.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/migration_state/dbt_dag.yaml
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/migration_state/dbt_dag.yaml-e
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/migration_state/load_lakehouse.yaml
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/migration_state/load_lakehouse.yaml-e
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/migration_state/rebuild_iris_models.yaml
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/migration_state/rebuild_iris_models.yaml-e
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/complete.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/lakehouse.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/migrate.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/observe_with_check.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/utils.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example_tests/integration_tests/test_e2e.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example_tests/unit_tests/test_all_variants_loadable.py
- Add a "complete" section with schedule targeting all assets
- "zero in" to a single dag
Manual testing + existing unit.
`NOCHANGELOG`
> [dagster-airlift] example revamp

- js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
- js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
- python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py
- python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_runs_feed.py
- python_modules/dagster/dagster/_core/execution/backfill.py
- python_modules/dagster/dagster/_core/storage/dagster_run.py
adds filter parameters to the functions used by the GQL layer to get the runs feed
new unit tests
NOCHANGELOG
> support filtering in the runs feed

- js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
- js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
- python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py
- python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_runs_feed.py
- python_modules/dagster/dagster/_core/execution/backfill.py
Reverts dagster-io/dagster#24519
> Revert "support filtering in the runs feed"

- js_modules/dagster-ui/packages/ui-core/src/runs/RunActionsMenu.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunRoot.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedRoot.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedRow.tsx
> [2/n][Runs Feed] Add breadcrumb on backfill run + warning if backfill selected for bulk action

- js_modules/dagster-ui/packages/ui-core/src/app/ContentRoot.tsx
- js_modules/dagster-ui/packages/ui-core/src/app/FeatureFlags.oss.tsx
- js_modules/dagster-ui/packages/ui-core/src/app/useVisibleFeatureFlagRows.oss.tsx
- js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillActionsMenu.tsx
- js_modules/dagster-ui/packages/ui-core/src/instance/backfill/ExecutionTimeline.tsx
- js_modules/dagster-ui/packages/ui-core/src/instance/backfill/RunsFeedBackfillPage.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunRoot.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunRow.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedRow.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedTabs.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedUtils.tsx
Add feature gating for runs feed. Currently its commented out since we don't want to release it yet.
- Navigated to /runs
- Navigated to a backfill
- Clicked around RunsFeed making sure the routing worked correctly.
NOCHANGELOG
> [3/n][Runs feed] Feature gating

- python_modules/dagster/dagster/_serdes/serdes.py
- python_modules/dagster/dagster_tests/general_tests/test_serdes.py
`@whitelist_for_serdes` has a param `skip_when_empty_fields` that allows fields to be dropped from serialization when they are _either_ `None` or an empty collection. This erases the distinction between `None` and an empty collection, which sometimes needs to be preserved.
This PR adds the unfortunate `skip_when_none_fields`, which allows this distinction to be preserved.
New unit test.
NOCHANGELOG
> [serdes] Add new `skip_when_none_fields` param to `whitelist_for_serdes`

- examples/experimental/dagster-airlift/dagster_airlift/constants.py
- examples/experimental/dagster-airlift/dagster_airlift/core/dag_asset.py
- examples/experimental/dagster-airlift/dagster_airlift/core/dag_defs.py
- examples/experimental/dagster-airlift/dagster_airlift/core/defs_builders.py
- examples/experimental/dagster-airlift/dagster_airlift/core/load_defs.py
- examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
- examples/experimental/dagster-airlift/dagster_airlift/core/task_asset.py
- examples/experimental/dagster-airlift/dagster_airlift/core/utils.py
- examples/experimental/dagster-airlift/dagster_airlift/in_airflow/base_proxy_operator.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/operator_test_project/dagster_defs.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/conftest.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_airflow_asset_mapping.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_dag_defs.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py
> Change underlying metadata representation

- python_modules/dagster/dagster_tests/general_tests/test_record.py
> More precise skipif logic for record tests

- examples/docs_beta_snippets/docs_beta_snippets_tests/test_integration_files_load.py
> skip pandera test to unbreak release ci

- python_modules/libraries/dagster-dbt/dagster_dbt/__init__.py
As the title.
local, see no more warning
NOCHANGELOG
> fix(dbt): mark `dbt-core` as a non-dagster library

- docs/content/concepts/automation/declarative-automation.mdx
- docs/content/concepts/automation/declarative-automation/customizing-automation-conditions.mdx
As title.
- Got rid of some confusing sections in the customization guide which go a bit too deep into the internals of the system. 
- Added some examples which take advantage of newer features we've added (specifically the ".without()" bit, and the composite condition section
- Added some information in the overview section about applying these policies to AssetChecks
More information about AssetCheck conditions will be forthcoming, waiting on a PR that adds the ability to detect the status of an asset check -- until that lands the stuff you can do with them is fairly limited
NOCHANGELOG
> Update docs for Declarative Automation

- python_modules/libraries/dagster-dbt/dagster_dbt/core/resource.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resource.py
Updates the docstring for global config flags to reference the list of valid flags from `dbt --help`
BK.
NOCHANGELOG
> Update docstring for dbt global config command

- docs/docs-beta/docusaurus.config.ts
> [docs-beta] Update GitHub edit URL

- examples/experimental/dagster-airlift/dagster_airlift/core/load_defs.py
Example application of StateBackedDefinitionsLoader in Airlift
BK
NOCHANGELOG
> Use state-backed definition loader in Airlift

- python_modules/dagster/dagster/_cli/job.py
- python_modules/dagster/dagster/_core/execution/asset_backfill.py
- python_modules/dagster/dagster/_core/execution/backfill.py
- python_modules/dagster/dagster/_core/instance/__init__.py
- python_modules/dagster/dagster/_core/launcher/base.py
- python_modules/dagster/dagster/_core/run_coordinator/base.py
- python_modules/dagster/dagster/_core/workspace/context.py
- python_modules/dagster/dagster/_core/workspace/workspace.py
- python_modules/dagster/dagster/_daemon/monitoring/run_monitoring.py
- python_modules/dagster/dagster/_daemon/run_coordinator/queued_run_coordinator_daemon.py
At this point it does not appear that this interface adds anything over `BaseWorkspaceRequestContext` so drop it
existing tests
> remove IWorkspace

- examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_airflow_asset_mapping.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py
I should have done with in the downstack PR #24698 but decided to do it here. I can fold it in if desired. Caught a bug in a property not currently used in production code paths.
BK
NOCHANGELOG
> Add test_multiple_tasks_to_single_asset to test multi-task mapping

- docs/content/concepts/io-management/io-managers.mdx
- examples/docs_snippets/docs_snippets/concepts/io_management/source_asset.py
- python_modules/dagster/dagster/_core/definitions/asset_spec.py
Add docstring for `with_io_manager_key` and update concept docs to use it.
NOCHANGELOG
> concept docs and docstring for `with_io_manager_key`

- js_modules/dagster-ui/packages/ui-core/src/workspace/RepositoryCountTags.tsx
- js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedCodeLocationRow.tsx
Restore object counts on code location list rows.
View code locations list in OSS and Plus, verify that object counts are restored.
> [ui] Restore object counts in code location list

- python_modules/dagster/dagster/_core/definitions/assets.py
- python_modules/dagster/dagster/_core/definitions/decorators/source_asset_decorator.py
- python_modules/dagster/dagster/_core/definitions/source_asset.py
Add a `dagster_internal_init` method for `SourceAsset`.
NOCHANGELOG
> SourceAsset.dagster_internal_init

- examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
- examples/experimental/dagster-airlift/dagster_airlift/core/task_asset.py
> Renamed FetchedAirflowTask to MappedAirflowTaskData

- js_modules/dagster-ui/packages/ui-components/src/components/Icon.tsx
Add all icons from `icon-svgs` to the Icon component.
Storybook, TS, lint.
NOCHANGELOG
> [ui] Update icon list

- js_modules/dagster-ui/packages/ui-components/CHANGES.md
Update `CHANGES`.
None.
NOCHANGELOG
> [ui-components] Update changes.md before publish

- CHANGES.md
- scripts/generate_changelog.py
As title, plus updates to the generation script
NOCHANGELOG
> 1.8.9 Changelog

- docs/docs-beta/docusaurus.config.ts
- docs/docs-beta/src/theme/MDXComponents.tsx
- docs/sphinx/Makefile
- docs/sphinx/_ext/dagster-sphinx/dagster_sphinx/__init__.py
- docs/sphinx/_ext/sphinx-mdx-builder/sphinxcontrib/mdxbuilder/builders/mdx.py
- docs/sphinx/_ext/sphinx-mdx-builder/sphinxcontrib/mdxbuilder/writers/mdx.py
- docs/sphinx/conf.py
This adds an `id` to the `<dt>` tags that define header topics, e.g.
```python
<dt id="dagster.asset">@dagster.asset</dt>
```
This allows anchor-linking to API objects.
local test and click
NOCHANGELOG
> [docs-beta] add id attribute to api sig elements to allow anchor linking [DOC-527]

- .github/workflows/build-docs-revamp.yml
- docs/sphinx/_ext/dagster-sphinx/dagster_sphinx/__init__.py
- docs/sphinx/conf.py
Fixes the broken Vercel build and allows Sphinx to read source files in parallel
NOCHANGELOG
> [docs] Enable parallel read and add looker_sdk to conf.py

- docs/sphinx/sections/api/apidocs/libraries/dagster-looker.rst
- python_modules/libraries/dagster-looker/dagster_looker/__init__.py
- python_modules/libraries/dagster-looker/dagster_looker/api/dagster_looker_api_translator.py
- python_modules/libraries/dagster-looker/dagster_looker/api/resource.py
As the title.
make local docs
NOCHANGELOG
> docs(looker): add API docs for using `dagster-looker` with the Looker API

- docs/content/integrations/looker.mdx
- examples/docs_snippets/docs_snippets/integrations/looker/customize-looker-assets.py
- examples/docs_snippets/docs_snippets/integrations/looker/materializing-looker-pdts.py
- examples/docs_snippets/docs_snippets/integrations/looker/representing-looker-assets.py
As the title.
local
NOCHANGELOG
> docs(looker): add guide to setup `dagster-looker` with the Looker API

- js_modules/dagster-ui/packages/ui-core/src/instance/flattenCodeLocationRows.tsx
- js_modules/dagster-ui/packages/ui-core/src/search/useIndexedDBCachedQuery.tsx
- js_modules/dagster-ui/packages/ui-core/src/ui/BaseFilters/__stories__/useFilters.stories.tsx
- js_modules/dagster-ui/packages/ui-core/src/ui/BaseFilters/__tests__/useStaticSetFilter.test.tsx
- js_modules/dagster-ui/packages/ui-core/src/ui/BaseFilters/useStaticSetFilter.tsx
The complexity of having this potentially be uncontrolled is too great. Removing the uncontrolled feature to simplify the logic and eliminate a potential infinite loop that is reproing in dev.
Updated the few call sites that were uncontrolled.
jest
NOCHANGELOG
> Make useStaticSetFilter controlled

- python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py
Preps for upstream branches by refactoring `get_backfills` in reusable methods
corresponding internal pr https://github.com/dagster-io/internal/pull/11794
NOCHANGELOG
> refactor get_backfills

- python_modules/dagster/dagster/_core/definitions/tags/tag_set.py
- python_modules/dagster/dagster_tests/definitions_tests/tags_tests/test_tag_set.py
> allow literals in tag sets

- python_modules/libraries/dagster-powerbi/dagster_powerbi/resource.py
Define a `PowerBIWorkspaceDefsLoader` class inheriting from the new `StateBackedDefinitionsloader` and make `PowerBIWorkspace.build_defs()` use this class.
NOCHANGELOG
> [lazy-defs] [dagster-powerbi] Refactor dagster-powerbi to use the StateBackedDefinitionsLoader

- examples/experimental/dagster-airlift/examples/kitchen-sink/.gitignore
- examples/experimental/dagster-airlift/examples/kitchen-sink/Makefile
- examples/experimental/dagster-airlift/examples/kitchen-sink/README.md
- examples/experimental/dagster-airlift/examples/kitchen-sink/conftest.py
- examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/airflow_dags/migration_state/print_dag.yaml
- examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/airflow_dags/print_dag.py
- examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/dagster_defs/__init__.py
- examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/dagster_defs/constants.py
- examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/dagster_defs/print_defs.py
- examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink_tests/integration_tests/conftest.py
- examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink_tests/integration_tests/test_e2e.py
- examples/experimental/dagster-airlift/examples/kitchen-sink/pyproject.toml
- examples/experimental/dagster-airlift/examples/kitchen-sink/setup.py
- examples/experimental/dagster-airlift/examples/kitchen-sink/tox.ini
- pyright/master/requirements-pinned.txt
- pyright/master/requirements.txt
A dumping ground for live test cases/toys.
E2E test.
NOCHANGELOG
> [dagster-airlift] kitchen sink example

- python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
- python_modules/dagster/dagster/_core/asset_graph_view/entity_subset.py
- python_modules/dagster/dagster/_core/definitions/asset_graph.py
- python_modules/dagster/dagster/_core/definitions/automation_tick_evaluation_context.py
- python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
- python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_evaluator.py
- python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
- python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/check_not_subsettable.py
- python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_e2e.py
Replaces the patch functionality with a more precise handling of this situation, treating these required asset checks in the same way that we treat required multi asset neighbors.
NOCHANGELOG
> Properly handle non-subsettable assets+asset checks

- docs/Makefile
- docs/docs-beta/scripts/vercel-sync-api-docs.sh
- docs/tox.ini
> [docs] Update Makefile and Vercel sync script for mdx generation

- docs/docs-beta/docusaurus.config.ts
Updates the header bar now that we have a discussion
NOCHANGELOG
> [docs-beta] Update feedback link in announcement bar and footer

- docs/docs-beta/docs/dagster-plus.md
> [docs-beta] add dagster+ back to sidebar

- js_modules/dagster-ui/packages/ui-core/client.json
- js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeDefinition.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeOverview.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetNodeDefinition.types.ts
- js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetView.types.ts
- js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
- js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
- python_modules/dagster-graphql/dagster_graphql/schema/asset_condition_evaluations.py
- python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
- python_modules/dagster-graphql/dagster_graphql/schema/automation_condition.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_all_snapshot_ids.ambr
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_assets.ambr
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_solids.ambr
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py
As title
[ui] When setting an AutomationCondition on an asset, the label of this condition will now be shown in the sidebar on the Asset Details page.
> Render a label for AutomationConditions on the asset sidebar

- examples/experimental/dagster-airlift/dagster_airlift/core/load_defs.py
Renames some internals parameters from `defs` to `explicit_defs` per our new naming convention
BK
NOCHANGELOG
> Rename defs to explicit_defs where appropriate

- examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
- examples/experimental/dagster-airlift/dagster_airlift/core/load_defs.py
- examples/experimental/dagster-airlift/dagster_airlift/core/sensor.py
This substantially reduces the number of lines of code and paves the way for clean usage of Definitions.map_asset_specs
> Refactor construction code in terms of Definitions

- examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
- examples/experimental/dagster-airlift/dagster_airlift/core/airflow_instance.py
- examples/experimental/dagster-airlift/dagster_airlift/core/dag_asset.py
- examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
- examples/experimental/dagster-airlift/dagster_airlift/core/serialization/serialized_data.py
Move more of the dag spec construction logic to the reconstruction phase, eliminating the need for a bunch of serialization slop.
BK
NOCHANGELOG
> Move more of the dag spec construction logic to the reconstruction phase

- examples/experimental/dagster-airlift/dagster_airlift/core/dag_asset.py
- examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
I think we can call `compute_serialized_data` tamed now as it has been reduced to a couple imperative lines of code and a reasonable dict comprehension. Much easier to understand and manipulate now.
BK
NOCHANGELOG
> Final cleanup of compute_serialized_data 

- js_modules/dagster-ui/packages/ui-core/src/runs/RunTable.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedRoot.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedTable.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedTabs.tsx
- js_modules/dagster-ui/packages/ui-core/src/ui/IndeterminateLoadingBar.tsx
Extract the table to a separate component so that we can use it as a drop in replacement for RunTable.
load the runs feed, see nothing changed.
NOCHANGELOG
> Extract RunsFeedTable from RunsFeedRoot 

- examples/experimental/dagster-airlift/dagster_airlift/core/dag_asset.py
- examples/experimental/dagster-airlift/dagster_airlift/core/utils.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py
Adds dag asset kind rendering to peered dags.
Unit test for presence of tag, visual on dbt example
NOCHANGELOG
> [dagster-airlift] dag asset kind

- python_modules/dagster/dagster/_utils/concurrency.py
bad type check
pyright
NOCHANGELOG
> fix type for concurrency slot info

- python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_impls.py
filter out runless events '' run_id
> filter run_ids before calling get_runs

- examples/experimental/dagster-airlift/dagster_airlift/core/serialization/serialized_data.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/dags/simple_dag.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_airflow_instance.py
Add property to get `downstream_task_ids`
Added integration test
NOCHANGELOG
> Add downstream_task_ids property and test

- .buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
- examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/dagster_defs/airflow_instance.py
- examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/dagster_defs/automapped_defs.py
- examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/dagster_defs/mapped_defs.py
- examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink_tests/integration_tests/test_e2e_automapped.py
- examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink_tests/integration_tests/test_e2e_mapped.py
Add an integration test in the kitchen sink for automapped tasks. Documents that observing materializations doesn't work yet.
BK
NOCHANGELOG
> Add integration test for automapped tasks

- examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py
Embellish automapped tasks with nice metadata just like the dags
BK
NOCHANGELOG
> Bling up automapped task

- js_modules/dagster-ui/packages/ui-core/src/automation/MergedAutomationRoot.tsx
Add a little bit more useful content to the Automations empty state.
Force empty state, verify visually.
NOCHANGELOG
> [ui] A little more content for Automations page empty state

- python_modules/dagster/dagster/_core/workspace/context.py
- python_modules/dagster/dagster/_grpc/server_watcher.py
Type annotations for some workspace code.
NOCHANGELOG
> [typing] workspace types

- python_modules/dagster/dagster/_core/execution/plan/handle.py
- python_modules/dagster/dagster/_core/execution/stats.py
- python_modules/dagster/dagster/_serdes/serdes.py
- python_modules/dagster/dagster/_utils/__init__.py
- python_modules/dagster/dagster/_utils/alert.py
- python_modules/dagster/dagster/_utils/backoff.py
- python_modules/dagster/dagster/_utils/container.py
- python_modules/dagster/dagster/_utils/cronstring.py
- python_modules/dagster/dagster/_utils/forked_pdb.py
- python_modules/dagster/dagster/_utils/hosted_user_process.py
- python_modules/dagster/dagster/_utils/net.py
- python_modules/dagster/dagster/_utils/timing.py
A random collection of type annotations, mostly from utils. Also one local variable rename and docstring edit.
NOCHANGELOG
> [typing] misc

- python_modules/dagster/dagster/_cli/api.py
- python_modules/dagster/dagster/_cli/run.py
- python_modules/dagster/dagster/_core/execution/context/system.py
- python_modules/dagster/dagster/_core/execution/job_execution_result.py
- python_modules/dagster/dagster/_core/system_config/objects.py
- python_modules/dagster/dagster/_utils/indenting_printer.py
- python_modules/dagster/dagster/_utils/internal_init.py
- python_modules/dagster/dagster/_utils/log.py
A random collection of type annotations. Adding a few of these necessitated minor runtime changes (e.g. `check` call) to prevent type errors.
NOCHANGELOG
> [typing] misc 2

- python_modules/dagster/dagster/_core/definitions/selector.py
- python_modules/dagster/dagster/_core/execution/submit_asset_runs.py
- python_modules/dagster/dagster/_core/remote_representation/external.py
- python_modules/dagster/dagster/_core/remote_representation/origin.py
- python_modules/dagster/dagster/_core/scheduler/instigation.py
- python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py
- python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py
update NamedTuples to records
tests and pyright
> [record] selector.py

- python_modules/dagster/dagster/_core/storage/dagster_run.py
> remove legacy nt from RunFilter

- python_modules/dagster/dagster/_core/remote_representation/external.py
- python_modules/dagster/dagster/_core/remote_representation/handle.py
- python_modules/dagster/dagster/_core/remote_representation/origin.py
- python_modules/dagster/dagster_tests/daemon_tests/test_queued_run_coordinator_daemon.py
> [record] handle.py

- python_modules/dagster/dagster/_cli/api.py
- python_modules/dagster/dagster_tests/cli_tests/test_api_commands.py
This should be rare, but can happen in, for example, the sequence of events in https://github.com/dagster-io/dagster/issues/24889. If a step process manages to start while the run is in a CANCELING or CANCELED or FAILURE state, short circuit it early.
BK (new test case)
> Terminate execute-step process early when it runs on a run that is canceling or otherwise finisehed

- python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_runs_feed.py
Updates runs feed to support backfill id filters when in the consolidated view
NOCHANGELOG
> add backfill id filter support to backfills in runs feed

- examples/experimental/dagster-airlift/dagster_airlift/core/sensor.py
Remove materialization retrieval from what will soon be a pluggable implementation function.
Existing tests
NOCHANGELOG
> [dagster-airlift] materialization accumulation refactor

- examples/experimental/dagster-airlift/dagster_airlift/core/sensor/__init__.py
- examples/experimental/dagster-airlift/dagster_airlift/core/sensor/builder.py
- examples/experimental/dagster-airlift/dagster_airlift/core/sensor/event_translation.py
Sensor implementation was getting long in the tooth, so split it out into specialized files.
Existing tests
NOCHANGELOG
> [dagster-airlift] move utilities

- docs/content/tutorial/building-an-asset-graph.mdx
- docs/dagster-university/pages/dagster-dbt/lesson-7/4-creating-the-manifest-during-deployment.md
- python_modules/dagster/dagster/_config/validate.py
- python_modules/dagster/dagster/_serdes/serdes.py
- python_modules/dagster/dagster_tests/general_tests/compat_tests/test_back_compat.py
- python_modules/libraries/dagster-postgres/dagster_postgres_tests/compat_tests/test_back_compat.py
- scripts/check_schemas.py
> chore: remove repetitive words

- docs/docs-beta/docs/about/releases.md
> [docs-beta] Update API reference links in releases.md

- docs/content/integrations/dbt/using-dbt-with-dagster-plus/serverless.mdx
Update prerequisites for dbt and Dagster projects
- Mentions a dbt and Dagster project require a structure and certain files.
- Mentions the tutorial as a reference.
Doc preview
NOCHANGELOG
> [docs] Update dbt & Dagster+ guide for dbt and Dagster projects

- docs/content/integrations/deltalake/reference.mdx
- docs/content/integrations/deltalake/using-deltalake-with-dagster.mdx
Code snippets for Deltalake needed to be refreshed with make mdx-full-format - tests were failing.
BK
NOCHANGELOG
> [docs] Fix code snippets in Deltalake docs

- js_modules/dagster-ui/packages/ui-core/src/runs/RunRoot.tsx
> Change Runs page breadcrumb to "All runs"

- examples/experimental/dagster-airlift/dagster_airlift/k8s/__init__.py
- examples/experimental/dagster-airlift/dagster_airlift/k8s/asset.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/k8s_tests/test_k8s_pod_defs.py
- examples/experimental/dagster-airlift/examples/tutorial-example/README.md
- examples/experimental/dagster-airlift/setup.py
- examples/experimental/dagster-airlift/tox.ini
- python_modules/libraries/dagster-k8s/dagster_k8s/ops/k8s_job_op.py
Added a readme section on common provided operators.
N/A
`NOCHANGELOG`
> [dagster-airlift] readme section on common operators

- python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
- python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
- python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/slice_conditions.py
- python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_result_value_hash.py
- python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_e2e.py
No need to rush into this change, let's let this sit for a week
NOCHANGELOG
> Revert change to in_progress() condition

- python_modules/dagster/dagster/_core/snap/job_snapshot.py
- python_modules/dagster/dagster/_serdes/utils.py
Convert `JobSnapshot` and `JobLineageSnapshot` to `@record` from `NamedTuple`
NOCHANGELOG
> Convert JobSnapshot, JobLineageSnapshot to @record

- python_modules/dagster/dagster/_check/builder.py
avoid function call when we can 
bk
> [check builder] short circuit None on optional containers

- examples/experimental/dagster-airlift/CHANGES.md
> [dagster-airlift] 0.0.24 changelog

- examples/experimental/dagster-airlift/dagster_airlift/core/load_defs.py
- examples/experimental/dagster-airlift/dagster_airlift/core/sensor/__init__.py
- examples/experimental/dagster-airlift/dagster_airlift/core/sensor/builder.py
- examples/experimental/dagster-airlift/dagster_airlift/core/sensor/event_translation.py
> [dagster-airlift] bubble up translation fn

- docs/content/concepts/automation/schedules/automating-assets-schedules-jobs.mdx
- examples/docs_snippets/docs_snippets/concepts/partitions_schedules_sensors/schedules/basic_asset_schedule.py
> [docs] fix formatting of basic asset schedule snippet

- docs/content/concepts/assets/asset-checks/checking-for-data-freshness.mdx
I assume this is an out of date reference
eyes
> [docs] remove reference to build_last_update_freshness_checks

- examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
- examples/experimental/dagster-airlift/dagster_airlift/core/load_defs.py
- examples/experimental/dagster-airlift/dagster_airlift/core/sensor/builder.py
- examples/experimental/dagster-airlift/dagster_airlift/core/serialization/defs_construction.py
This way we don't need to provide the same information twice in the construction of the sensor.
existing tests
NOCHANGELOG
> [dagster-airlift][mapped-defs] vend airflow instance off of airflow data

- python_modules/dagster/dagster/_core/definitions/asset_selection.py
- python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection.py
There's a bunch of duplicated code in AssetSelection subclasses. This extracts some of it into common superclasses.
Very open to suggestions on the superclass names.
NOCHANGELOG
> pull common AssetSelection class patterns into superclasses

- python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py
- python_modules/dagster/dagster/_utils/concurrency.py
> [record] convert concurrency nts to record

- docs/content/dagster-plus/account/authentication.mdx
This setting isn't referenced in the Authentication section and can be obscure to track down. 
👀
NOCHANGELOG
> [docs] add note for how to set default SSO role

- examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
Previously, we were only checking for the non-automapped metadata key.
Existing tests. Previously kitchen sink wasn't running on airlift branches, which is how this got missed, but https://github.com/dagster-io/dagster/pull/24970 fixed that.
NOCHANGELOG
> [dagster-airlift][misc] use automapped metadata key

- examples/experimental/dagster-airlift/setup.py
> [dagster-airlift] 0.0.24

- examples/experimental/dagster-airlift/dagster_airlift/core/serialization/defs_construction.py
> Rename automapped task asset fn names to be clearly about assets

- python_modules/dagster/dagster/_core/pipes/__init__.py
Makes it easier to find them 
NOCHANGELOG
> [dagster-pipes] surface main Pipes objects to dagster._core.pipes

- python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
- python_modules/libraries/dagster-sigma/dagster_sigma_tests/test_resource.py
> mark methods on SigmaOrganization as public and private

- examples/experimental/dagster-airlift/dagster_airlift/core/load_defs.py
- examples/experimental/dagster-airlift/dagster_airlift/core/sensor/builder.py
- examples/experimental/dagster-airlift/dagster_airlift/core/sensor/event_translation.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/conftest.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_sensor.py
- examples/experimental/dagster-airlift/examples/kitchen-sink/Makefile
- examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/airflow_dags/simple_unproxied.py
- examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/dagster_defs/observation_defs.py
- examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink_tests/integration_tests/test_e2e_observation.py
Adds a new example of switching AssetMaterialization events to AssetObservation events using sensor pluggability point.
New example test
NOCHANGELOG
> [dagster-airlift][sensor] example of sensor pluggability

- examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
- examples/experimental/dagster-airlift/dagster_airlift/core/load_defs.py
- examples/experimental/dagster-airlift/dagster_airlift/core/sensor/builder.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_airflow_asset_mapping.py
Fix the arguments to the sensor builder to get it ready to be a top level export.
Existing tests
NOCHANGELOG
> [dagster-airlift][sensor] top level sensor builder

- examples/experimental/dagster-airlift/setup.py
Also includes pin upgrade to dagster 1.8.10
Existing ch
NOCHANGELOG
> [dagster-airlift] 0.0.25

- js_modules/dagster-ui/packages/ui-core/src/partitions/__tests__/OrdinalOrSingleRangePartitionSelector.test.tsx
this fails often enough to be disruptive
> delete flaky OrdinalOrSingleRangePartitionSelector test

- python_modules/dagster/dagster/_core/pipes/context.py
Add `dagster_tags` property to `PipesContex` which can be used to get various Dagster-specific tags such as `dagster.io/run_id` or `dagster.op/dagster_cloud_git_branch`. 
It's useful to attach these tags to jobs and resources launched by Pipes. Most of Pipes workflows would want to reuse them. 
~~Naming question: `dagster.io/run_id` or `dagster/run_id`?~~
~~The former FQDN format is often used in Kubernetes labels and maybe other services. It's slightly more verbose.~~
Decided to go with `dagster/<key>`
Any important tags I forgot? 
NOCHANGELOG
> [dagster-pipes] add centralized dict for common Dagster tags

- examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/dagster_defs/observation_defs.py
> [dagster-airlift] add typing to pluggability example

- python_modules/libraries/dagster-github/dagster_github/resources.py
- python_modules/libraries/dagster-github/dagster_github_tests/test_resources.py
Closes https://github.com/dagster-io/dagster/issues/25062
Unit test
> [dagster-github]: raise runtime error when graphql result contains errors

- docs/content/integrations/tableau.mdx
- examples/docs_snippets/docs_snippets/integrations/tableau/add-tableau-data-quality-warning.py
As title.
Docs preview
NOCHANGELOG
> [dagster-tableau] Update docs with Data Quality Warning and sensor

- examples/experimental/dagster-airlift/dagster_airlift/in_airflow/base_proxy_operator.py
Factors out all gql queries into standalone methods
existing
NOCHANGELOG
> [dagster-airlift] factor out gql queries to separate methods

- examples/experimental/dagster-airlift/dagster_airlift/in_airflow/base_proxy_operator.py
Some additional refactoring to processing of asset nodes. Introduce a "job identifier" (went with tuple over typeddict so it could be a dict key itself, namedtupled seemed too heavyweight) and move filtering of asset nodes to its own method (which will be itself refactored more later, since this is the crux of the implementation)
Existing tests
NOCHANGELOG
> [dagster-airlift] additional refactoring on assetnodes

- examples/experimental/dagster-airlift/dagster_airlift/in_airflow/base_proxy_operator.py
Previously, we were skipping assets that weren't executable. We should be erroring when those assets aren't executable.
Existing tests for now, but this could be better tested for sure.
NOCHANGELOG
> [dagster-airlift] Error if not executable

- docs/content/dagster-plus/deployment/serverless.mdx
[[IB] Clarify custom infrastructure limitation in Serverless guide](https://linear.app/dagster-labs/issue/DS-505/[ib]-clarify-custom-infrastructure-limitation-in-serverless-guide)
👀
NOCHANGELOG
> [docs] add custom infrastructure to Serverless limitations

- python_modules/dagster/dagster/_core/definitions/tags/tag_set.py
- python_modules/dagster/dagster_tests/definitions_tests/tags_tests/test_tag_set.py
- python_modules/libraries/dagster-powerbi/dagster_powerbi/translator.py
- python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_translator.py
This can be used inside `map_asset_spec` to control which assets to customize.
NOCHANGELOG
> add dagster-powerbi/asset-type tag

- js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
- js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
- python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py
- python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_runs_feed.py
Incorporates whether to include/exclude subruns when getting the number of results for a query
updates unit tests to assert on count
NOCHANGELOG
> [runs feed] incorporate includeRunsFromBackfills into counts query

- python_modules/dagster-graphql/dagster_graphql/implementation/execution/__init__.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
> Return a GrapheneAssetNotFoundError when you try to wipe an asset+partition that does not exist in the graph

- python_modules/libraries/dagster-powerbi/dagster_powerbi/translator.py
- python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_translator.py
Introduce `PowerBIMetadataSet` and use "dagster-powerbi/" instead of "dagster_powerbi/", because it's the package name.
NOCHANGELOG
> PowerBIMetadataSet

- python_modules/libraries/dagster-powerbi/dagster_powerbi/resource.py
- python_modules/libraries/dagster-powerbi/dagster_powerbi/translator.py
- python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/conftest.py
- python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_translator.py
Some semantic model types hold references to data sources that lack an ID - add some code to gracefully handle this case.
Updated unit test to include sample data source without an ID.
> [dagster-powerbi] Gracefully handle datasets without datasource IDs

- python_modules/dagster-graphql/dagster_graphql/implementation/external.py
- python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
- python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
- python_modules/dagster-graphql/dagster_graphql/schema/external.py
- python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
- python_modules/dagster/dagster/_core/remote_representation/external.py
- python_modules/dagster/dagster/_core/remote_representation/handle.py
restructure `GrapheneRepository` to init with minimal information and load objects when they are needed 
> [graphql] make GrapheneRepository lazy load the repository

- js_modules/dagster-ui/packages/ui-core/src/search/SearchResults.tsx
- js_modules/dagster-ui/packages/ui-core/src/search/types.ts
- js_modules/dagster-ui/packages/ui-core/src/search/useGlobalSearch.tsx
Introduce a new search result type for column tags, so we can use it in Plus
n/a
> [2/c] add column tag search result type

- python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py
As title, makes sure the asset key name shows up in the UI.
Will add tests in a followup
> Add name to EntityMatchesCondition

- python_modules/dagster-graphql/dagster_graphql/schema/external.py
restructure to init with minimal information and load objects when they are needed
bk
> [graphql] lazy load repository location

- python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
- python_modules/dagster-graphql/dagster_graphql/schema/external.py
- python_modules/dagster/dagster/_core/workspace/context.py
fix up typing and have `GrapheneAssetNode` fetch the job from the context level method 
pyright
> [graphql] look up job by selector

- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_condition_evaluations.py
As title -- this ensures that we always produce a correct label for dep conditions.
> Add regression test for labels of dep conditions

- js_modules/dagster-ui/packages/ui-core/src/assets/AssetPartitions.tsx
Linear: https://linear.app/dagster-labs/issue/FE-572/add-search-bar-to-partitions-tab
Video:
https://github.com/user-attachments/assets/6287b901-b89c-4be2-aa6c-68f59652eb84
yarn lint, ts, tested locally
- `NEW` [ui] added search bar to partitions tab
> add search bar to partitions tab

- js_modules/dagster-ui/packages/ui-core/src/app/AppTopNav/AppTopNav.tsx
- js_modules/dagster-ui/packages/ui-core/src/app/UserSettingsButton.tsx
Accidentally left some `flagSettingsPage` detritus in https://github.com/dagster-io/dagster/pull/25177.
> [ui] Clean up flag leftover

- CHANGES.md
> [changelog] 1.8.11

- examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
- examples/experimental/dagster-airlift/dagster_airlift/core/serialization/serialized_data.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_airflow_asset_mapping.py
Continuing the quest to simplify the implementation here.
This information can also be inferred from mapping info, so get rid of it.
NOCHANGELOG
> [dagster-airlift][dag] Remove SerializedTaskHandleData

- python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
- python_modules/dagster/dagster/_core/remote_representation/external.py
- python_modules/dagster/dagster/_core/test_utils.py
- python_modules/dagster/dagster/_core/workspace/workspace.py
- python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py
- python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py
refactor to make it more explicit the conditions in which RemoteAssetGraphs are built and ease future changes
existing tests
> [RemoteAssetGraph] from workspace and repository builders

- docs/docs-beta/yarn.lock
- docs/next/yarn.lock
- js_modules/dagster-ui/yarn.lock
Resolve dependabot alerts related to `cookie`.
`yarn`, then `yarn why cookie`
> [ui] Clean up cookie dependabot alerts

- python_modules/libraries/dagster-k8s/dagster_k8s/pipes.py
Noticed that this wasn't in API docs, felt like it should be
N/A
> [pipes][fix] make DagsterK8sPipesClient.run public APi

- python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
Aligns the docstring with the with experimental warning decorator in some places
n/a
> Aligns the experimental qualifier in the docstring with the experimental decorator

- python_modules/libraries/dagster-looker/setup.py
Pin `looker_sdk` after (possibly bad?) breaking release. Will fix BK.
BK
> Pin looker_sdk

- python_modules/libraries/dagster-looker/setup.py
Pin `looker_sdk` after (possibly bad?) breaking release. Will fix BK. (Take 2)
> Pin looker (take 2)

- js_modules/dagster-ui/packages/ui-components/CHANGES.md
- js_modules/dagster-ui/packages/ui-components/package.json
Want to publish ui-components so updated CHANGES.md and semver to 1.1.4
N/A
NOCHANGELOG
> [ui-components] update CHANGES.md and semver for ui-components publish

- examples/experimental/dagster-airlift/setup.py
> [dagster-airlift] 0.0.26

- python_modules/dagster/dagster/_check/functions.py
showed up in profiling, time to go 
pyright
> [check] remove cast

- python_modules/dagster/dagster/_record/__init__.py
avoid having to call a custom function most of the time
existing bool check test
> [record] only set __bool__ when no fields

- examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
- examples/experimental/dagster-airlift/dagster_airlift/core/sensor/event_translation.py
- examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
- examples/experimental/dagster-airlift/dagster_airlift/core/serialization/serialized_data.py
- examples/experimental/dagster-airlift/dagster_airlift/core/utils.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py
Introduce the notion of a "DagHandle" and use it in the AirflowDefinitionsData object for checking the sensor
Existing tests
NOCHANGELOG
> [dagster-airlift] Introduce dag handle, use in sensor

- examples/experimental/dagster-airlift/dagster_airlift/core/__init__.py
- examples/experimental/dagster-airlift/dagster_airlift/core/top_level_dag_def_api.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_dag_defs.py
Add a top level API for adding a dag override to a list of assets
Added a test for the behavior.
NOCHANGELOG
> [dagster-airlift][dag] Dag overrides top level API

- examples/experimental/dagster-airlift/dagster_airlift/in_airflow/proxied_state.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_proxied_state.py
Proxied state scaffolding for dag-level overrides
Tests for new behavior
NOCHANGELOG
> [dagster-airlift][dag] Dag-level override proxied state

- examples/experimental/dagster-airlift/dagster_airlift/cli.py
- examples/experimental/dagster-airlift/dagster_airlift/in_airflow/dag_proxy_operator.py
- examples/experimental/dagster-airlift/dagster_airlift/in_airflow/proxied_state.py
- examples/experimental/dagster-airlift/dagster_airlift/in_airflow/proxying_fn.py
- examples/experimental/dagster-airlift/dagster_airlift/in_airflow/scaffolding.py
- examples/experimental/dagster-airlift/dagster_airlift/test/__init__.py
- examples/experimental/dagster-airlift/dagster_airlift/test/test_utils.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/scaffold_test_airflow_home/airflow_dags/dags.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_scaffolding.py
- examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/test_proxied_state.py
- examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/airflow_dags/dag_level_proxied.py
- examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/airflow_dags/proxied_state/overridden_dag.yaml
- examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink/dagster_defs/mapped_defs.py
- examples/experimental/dagster-airlift/examples/kitchen-sink/kitchen_sink_tests/integration_tests/test_e2e_mapped.py
- examples/experimental/dagster-airlift/setup.py
Adds a CLI for automatically scaffolding the proxied_state directory for an airflow installation.
Added an integration test for ensuring that airflow state is properly read, and proxied state is correctly genned.
NOCHANGELOG
> [dagster-airlift][cli] dagster-airlift proxy scaffold cli

- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/observe_with_check.py
Use `assets_with_task_mappings` in the dbt example observe step.
BK
NOCHANGELOG
> [dagster-airlift] Convert observe_with_check to use traditional Definitions construction

- python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
- python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_evaluator.py
- python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
- python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/legacy_context.py
- python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/slice_conditions.py
- python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_check_condition.py
- python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/legacy_tests/scenarios/basic_scenarios.py
- python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/legacy_tests/scenarios/freshness_policy_scenarios.py
- python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/automation_condition_scenario.py
> Add `all_deps_blocking_checks_passed` condition

- python_modules/dagster/dagster/__init__.py
- python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/user_defined/test_user_defined_automation_condition.py
- python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/automation_condition_scenario.py
> Export AutomationContext and AutomationResult

- examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/scaffold_test_airflow_home/airflow_dags/dags.py
This file keeps disappearing and I don't know why
Existing tests now pass
NOCHANGELOG
> [dagster-airlift] fix master

- python_modules/dagster/dagster/_check/functions.py
- python_modules/dagster/dagster/_core/instance/__init__.py
- python_modules/dagster/dagster_tests/general_tests/check_tests/test_check.py
need to regroup on how to roll this out
> Revert "[check] dont allow str or bytes for sequence_param (#25262)"

- js_modules/dagster-ui/packages/eslint-config/CHANGES.md
- js_modules/dagster-ui/packages/eslint-config/package.json
- js_modules/dagster-ui/packages/ui-core/src/app/Flags.tsx
- js_modules/dagster-ui/yarn.lock
Update eslint-config dependencies. Just keeping things clean.
Buildkite.
> [eslint-config] Upgrade dependencies

- docs/docs-beta/src/components/CodeExample.tsx
- Introduces `lineStart` and `lineEnd` props to `CodeExample`; would we prefer a different convention?
- Propagates props to `CodeBlock` with `{...props}`, this allows us to use things like `showLineNumbers`
Confirmed the following rendered correctly:
```
<CodeExample filePath="integrations/airbyte.py" language="python" lineStart="5" lineEnd="10" showLineNumbers/>
```
> [docs,beta] support line numbers in CodeExample; propagate props

- CHANGES.md
> changelog for 1.8.12

- python_modules/dagster/dagster/_config/pythonic_config/config.py
- python_modules/dagster/dagster_tests/core_tests/pythonic_config_tests/test_pythonic_config_types.py
pydantic field aliases add an annoying wrinkle to this config processing we do. This PR fixes a misalignment with pre and post alias applied field name dicts that was causing us to blank out config values. 
added test that failed before
Fixed an issue where configuration values for aliased pydantic fields would be dropped
> [config] fix issues with aliases

- docs/content/integrations.mdx
Addresses https://github.com/dagster-io/dagster/discussions/9367#discussioncomment-11005951
👀
> [docs] link to community integration dagster-perian

- python_modules/dagster/dagster/_core/definitions/asset_graph.py
- python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
- python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
- python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py
As title. Before, these dependencies were being ignored
NOCHANGELOG
> Make additional_deps show up in parent_entity_keys for checks

- python_modules/dagster/dagster/_core/definitions/sensor_definition.py
We only use the CachingDynamicPartitionsLoader when there's a run request with partitions, and the CachingDynamicPartitionsLoader needs to hydrate the instance ref which is costly. to speed up the typical case, use @functools.cache to memoize the creation of the `CachingDynamicPartitionsLoader(context.instance)`
Ran 10k no-op sensor executions before and after the change, this dropped the latency from 20s to 2s
> don't instantiate instance if not needed in sensor execution

- python_modules/dagster/dagster/_core/definitions/asset_selection.py
- python_modules/dagster/dagster/_core/definitions/target.py
- python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection.py
- python_modules/libraries/dagster-dbt/dagster_dbt/dbt_manifest_asset_selection.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_selection.py
unlocks migrating `AssetKey` to `@record` 
existing tests
> [record] migrate AssetSelection

- python_modules/dagster/dagster/_core/op_concurrency_limits_counter.py
- python_modules/dagster/dagster_tests/daemon_tests/test_queued_run_coordinator_daemon.py
Default op concurrency limits were not being respected with the `block_op_concurrency_limited_runs` run queue configuration.
This PR changes the queued run coordinator such that unconfigured concurrency keys will inherit the default concurrency limit before decisions are made to queue/dequeue concurrency limited runs.
Reported in https://github.com/dagster-io/dagster/issues/25109
BK
- [bugfix] Fixed a bug with the `block_op_concurrency_limited_runs` feature in run queues where op concurrency keys that were not explicitly configured were not inheriting the default concurrency limit set by `default_op_concurrency_limit`.
> ensure op concurrency defaults are initialized in run coordinator if necessary

- python_modules/dagster-test/dagster_test/toys/auto_materializing/large_graph.py
- python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/perf_tests/test_perf.py
As title. Copied from https://github.com/dagster-io/dagster/pull/25302
Run test_perf.py
> Update test_perf.py to include asset checks

- js_modules/dagster-ui/packages/ui-core/src/assets/LaunchAssetExecutionButton.tsx
In this thread it was identified that there is a query waterfall in the Materialize button: 
https://dagsterlabs.slack.com/archives/C070G3UNNLW/p1724874261476729
These queries can be surprisingly expensive, taking 5-6s in some DD traces. There are three primary queries we make:
1) Loading the assets in the selection to get their dependencyKeys, backfill policies, partition definitions, asset checks and required resources.
2) Loading the assets upstream of the selection (which requires the dependencyKeys from (1)) with their last materialization to see if any upstream assets have never been materialized, in which case this materialization will likely fail. (This warning might not be worth the additional time, or the complexity of refactoring it to pull cached data / be faster)
3) Loading …
> [ui] Re-order logic in Materialize button to avoid pipeline resource check

- python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_reconstruction.py
Move to new apis introduced in #25436
> [dagster-tableau] Fix merge conflict related to repository_def_from_pointer

- examples/docs_beta_snippets/docs_beta_snippets/dagster-plus/deployment/hybrid/agents/kubernetes/resource_request_pipes.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/etl/transform-dbt/dbt_definitions_with_downstream.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/etl/transform-dbt/dbt_definitions_with_schedule.py
- examples/docs_beta_snippets/tox.ini
missed this in `AssetKey` change to disallow iteration 
also fixes up issues from https://github.com/dagster-io/dagster/pull/24265
pytest examples/docs_beta_snippets/docs_beta_snippets_tests/test_all_files_load.py
> [docs] fix deps call in dbt_definitions_with_downstream

- python_modules/dagster/dagster/_core/storage/alembic/versions/045_1aca709bba64_add_runs_table_backfill_id_index.py
- python_modules/dagster/dagster/_core/storage/runs/schema.py
- python_modules/dagster/dagster_tests/general_tests/compat_tests/test_back_compat.py
- python_modules/libraries/dagster-mysql/dagster_mysql_tests/compat_tests/test_back_compat.py
- python_modules/libraries/dagster-postgres/dagster_postgres_tests/compat_tests/test_back_compat.py
corresponding internal pr https://github.com/dagster-io/internal/pull/12315
> add backfill id index for runs table

- CHANGES.md
> [changelog] 1.8.13

- docs/content/integrations/powerbi.mdx
Adds a new section to our powerbi docs mentioning how to install the package.
> [dagster-powerbi][docs] Specifically mention pip installing `dagster-powerbi` package

- docs/content/integrations/tableau.mdx
Adds a new section to our tableau docs mentioning how to install the package.
> [dagster-tableau][docs] Specifically mention pip installing dagster-tableau package

- js_modules/dagster-ui/packages/ui-core/src/jobs/JobsPageContent.tsx
- js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/WorkspaceQueries.tsx
> [dagit] dont fetch Pipeline.tags

- docs/content/integrations/looker.mdx
Adds a new section to our Looker docs mentioning how to install the package.
> [dagster-looker][docs] Specifically mention pip installing dagster-looker package

- docs/content/integrations/sigma.mdx
Adds a new section to our Sigma docs mentioning how to install the package.
> [dagster-sigma][docs] Specifically mention pip installing dagster-sigma package

- docs/content/integrations/sigma.mdx
- examples/docs_snippets/docs_snippets/integrations/sigma/customize-sigma-asset-defs.py
> fix Sigma pyright docs issue

- python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/operands.py
- python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_result_value_hash.py
As title. Noticed that this was named incorrectly
NOCHANGELOG
> Fix name of run_in_progress AutomationCondition

- js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedRoot.tsx
> [ui] fix padding of runs tab

- docs/content/concepts/automation/declarative-automation.mdx
- docs/content/concepts/automation/declarative-automation/customizing-automation-conditions.mdx
- python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
As title, this does a quick refresh of the docs around automation conditions, and adds in a bit of information about the arbitrary python stuff
> [docs][1.9] Declarative Automation refresh

- examples/experimental/dagster-airlift/examples/dbt-example/.vscode/settings.json
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/airflow_dags/proxied_state/rebuild_iris_models.yaml-e
Adds ignored files to vscode env for airlift demo
> [dagster-airlift] ignore files

- python_modules/dagster/dagster/_core/pipes/merge_streams.py
> Actually fix type issue

- docs/content/integrations.mdx
> [docs] add `dagster-ray` to community integrations page

- python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
- python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py
- python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
- python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
- python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
- python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
- python_modules/dagster/dagster/_core/workspace/context.py
theres is a great deal of code that does `asset_graph.get` so instead of trying to reroute things through a new context method, lets just focus on improving that code path
existing tests
> [graphql] move asset node fetches back to asset_graph

- docs/content/concepts/partitions-schedules-sensors/backfills.mdx
small update to the backfill change to more accurately reflect ui behavior
> [docs] update wording in backfill page

- docs/content/integrations/sigma.mdx
- docs/sphinx/sections/api/apidocs/libraries/dagster-sigma.rst
- examples/docs_snippets/docs_snippets/integrations/sigma/customize-sigma-asset-defs.py
- examples/docs_snippets/docs_snippets/integrations/sigma/multiple-sigma-organizations.py
- examples/docs_snippets/docs_snippets/integrations/sigma/representing-sigma-assets.py
Updates our Sigma docs to incorporate the new specs-building pattern and norm of passing the resource to `Definitions`.
> [dagster-sigma] Update Sigma documentation to showcase new API patterns

- python_modules/libraries/dagster-powerbi/dagster_powerbi/assets.py
See [comment](https://github.com/dagster-io/dagster/pull/25591#pullrequestreview-2402076112) in #25591
> [dagster-tableau] Make new Power BI semantic model refresh fn experimental

- docs/content/integrations/tableau.mdx
- docs/sphinx/sections/api/apidocs/libraries/dagster-tableau.rst
- examples/docs_snippets/docs_snippets/integrations/tableau/add-tableau-data-quality-warning.py
- examples/docs_snippets/docs_snippets/integrations/tableau/customize-tableau-asset-defs.py
- examples/docs_snippets/docs_snippets/integrations/tableau/multiple-tableau-workspaces.py
- examples/docs_snippets/docs_snippets/integrations/tableau/refresh-and-materialize-tableau-assets.py
- examples/docs_snippets/docs_snippets/integrations/tableau/representing-tableau-cloud-assets.py
- examples/docs_snippets/docs_snippets/integrations/tableau/representing-tableau-server-assets.py
Updates our Tableau docs to incorporate the new specs-building pattern, norm of passing the resource to `Definitions`, and the new pattern for building executable asset definitions.
> [dagster-tableau] Update Tableau documentation to showcase new API patterns

- python_modules/libraries/dagster-k8s/dagster_k8s/executor.py
- python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_executor.py
Dagster currently requires that k8s config at the op-level be defined statically with no option for configuring at launch-time (#22138).
This was resolved for the celery-k8s-job-executor in #23053. This PR aims to add an identical solution to the k8s-job-executor.
I added a unit test in the k8s package to test that the executor per_step_k8s_config overwrites other sources (op-tag, job-tag, executor step_k8s_config).
[dagster-k8s] Added a per_step_k8s_config configuration option to the k8s_job_executor, allowing the k8s configuration of individual steps to be configured at run launch time.
> Add per_step_k8s_config to k8s_job_executor

- docs/content/integrations/looker.mdx
- docs/sphinx/sections/api/apidocs/libraries/dagster-looker.rst
- examples/docs_snippets/docs_snippets/integrations/looker/filtering-looker-assets.py
Add a section about dashboard and explore filtering in Looker documentation and mention potential performance issue.
> [dagster-looker] Update Looker documentation to showcase filtering

- js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/types/GetEvaluationsQuery.types.ts
- js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
- js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
- python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
> one more int => bigint change

- docs/content/integrations/looker.mdx
> [docs] Fix typo in Looker filtering docs

- python_modules/libraries/dagster-tableau/dagster_tableau/resources.py
- python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_asset_specs.py
This exception was encountered when dogfooding the `dagster-tableau` integration:
```bash
File "/Users/owen/src/dagster/scratch/tableau.py", line 27, in <module>
tableau_specs = load_tableau_asset_specs(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/owen/src/dagster/python_modules/dagster/dagster/_core/decorator_utils.py", line 203, in wrapped_with_pre_call_fn
return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^
File "/Users/owen/src/dagster/python_modules/libraries/dagster-tableau/dagster_tableau/resources.py", line 485, in load_tableau_asset_specs
.build_defs()
^^^^^^^^^^^^
File "/Users/owen/src/dagster/python_modules/dagster/dagster/_core/definitions/definitions_load_context.py", line 181, in build_defs
else self.fetch_state()
^^^^^^^^^^^^^^^^^^
File …
```
> [dagster-tableau] Raise exception on invalid or empty workbook data

- js_modules/dagster-ui/packages/ui-core/client.json
- js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/GetEvaluationsQuery.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/types/GetEvaluationsQuery.types.ts
Summary:
This is now vestigial.
BK
> remove unused evaluation ID field

- CHANGES.md
- MIGRATION.md
- examples/assets_dbt_python/assets_dbt_python/assets/forecasting.py
- examples/assets_modern_data_stack/assets_modern_data_stack/assets/forecasting.py
- python_modules/dagster/dagster/_core/definitions/decorators/hook_decorator.py
- python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/scenario_state.py
- python_modules/libraries/dagster-aws/dagster_aws/ssm/resources.py
> 1.9 Changelog and Migration Guide

- docs/content/integrations/tableau.mdx
- docs/sphinx/sections/api/apidocs/libraries/dagster-tableau.rst
- examples/docs_snippets/docs_snippets/integrations/tableau/add-tableau-data-quality-warning.py
- examples/docs_snippets/docs_snippets/integrations/tableau/refresh-and-materialize-tableau-assets.py
- python_modules/libraries/dagster-tableau/dagster_tableau/asset_utils.py
> [dagster-tableau] Update Tableau docs to use helper parser fn

- .buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
- examples/experimental/dagster-dlift/dagster_dlift/cloud_instance.py
- examples/experimental/dagster-dlift/dagster_dlift/gql_queries.py
- examples/experimental/dagster-dlift/dagster_dlift/test/instance_fake.py
- examples/experimental/dagster-dlift/dagster_dlift_tests/test_instance.py
- examples/experimental/dagster-dlift/kitchen-sink/dlift_kitchen_sink_tests/test_instance_methods.py
Method to retrieve dbt sources via rest api.
Unit + live.
> [dagster-dlift] get_sources method

- examples/experimental/dagster-dlift/dagster_dlift/cloud_instance.py
- examples/experimental/dagster-dlift/dagster_dlift/gql_queries.py
- examples/experimental/dagster-dlift/dagster_dlift/test/instance_fake.py
- examples/experimental/dagster-dlift/dagster_dlift_tests/test_instance.py
- examples/experimental/dagster-dlift/kitchen-sink/dlift_kitchen_sink/instance.py
- examples/experimental/dagster-dlift/kitchen-sink/dlift_kitchen_sink_tests/conftest.py
- examples/experimental/dagster-dlift/kitchen-sink/dlift_kitchen_sink_tests/test_instance_from_env.py
- examples/experimental/dagster-dlift/kitchen-sink/dlift_kitchen_sink_tests/test_instance_methods.py
Method for retrieving dbt tests via rest API.
Live + unit
> [dagster-dlift] get_tests

- examples/experimental/dagster-dlift/dagster_dlift/client.py
- examples/experimental/dagster-dlift/dagster_dlift/test/client_fake.py
- examples/experimental/dagster-dlift/dagster_dlift_tests/test_instance.py
- examples/experimental/dagster-dlift/dagster_dlift_tests/test_test_utils.py
- examples/experimental/dagster-dlift/kitchen-sink/dlift_kitchen_sink/instance.py
- examples/experimental/dagster-dlift/kitchen-sink/dlift_kitchen_sink_tests/conftest.py
- examples/experimental/dagster-dlift/kitchen-sink/dlift_kitchen_sink_tests/test_instance_from_env.py
- examples/experimental/dagster-dlift/kitchen-sink/dlift_kitchen_sink_tests/test_instance_methods.py
In preparation for adding more classes - this fits better the function of this class.
Existing
> [dagster-dlift] rename DbtCloudInstance to DbtCloudClient

- python_modules/dagster/dagster/_core/definitions/definitions_load_context.py
Factor out a `get_or_fetch_state` method that allows us to retrieve state without needing to build `Definitions`. This will be used in downstream PRs, since dlift does not implement `build_defs`.
Existing tests
> [dagster-dlift] factor out state fetching

- examples/experimental/dagster-dlift/dagster_dlift/project.py
- examples/experimental/dagster-dlift/dagster_dlift/test/client_fake.py
- examples/experimental/dagster-dlift/dagster_dlift/translator.py
- examples/experimental/dagster-dlift/dagster_dlift_tests/conftest.py
- examples/experimental/dagster-dlift/dagster_dlift_tests/test_environment.py
- examples/experimental/dagster-dlift/dagster_dlift_tests/test_translator.py
- python_modules/dagster/dagster/_utils/names.py
Project-level methods to retrieve asset specs.
> [dagster-dlift] project-level asset spec methods

- docs/next/.versioned_content/_versions_with_static_links.json
manually performing this failed step: https://elementl.dagster.cloud/prod/runs/fe14e428-4934-4efc-bd09-2e4cb54349b1?logFileKey=lpidvdei&selection=%22publish_docs%22&logs=query%3A%22publish_docs%22
no merge conflict
> Automation: versioned docs for 1.9.0

- python_modules/dagster-graphql/dagster_graphql/implementation/external.py
- python_modules/dagster-graphql/dagster_graphql/implementation/fetch_schedules.py
- python_modules/dagster-graphql/dagster_graphql/implementation/fetch_sensors.py
- python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
- python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
- python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
- python_modules/dagster/dagster/_core/definitions/selector.py
- python_modules/dagster/dagster/_core/remote_representation/code_location.py
- python_modules/dagster/dagster/_core/remote_representation/external.py
- python_modules/dagster/dagster/_core/workspace/context.py
consolidate how these are resolved in the request context
> [graphql] rework schedules, sensors and assets for job

- python_modules/dagster/dagster/_core/definitions/asset_dep.py
- python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
why have 2 when we can have 1
existing covergage
> consolidate AssetDep coerce functions

- .buildkite/dagster-buildkite/dagster_buildkite/pipelines/dagster_oss_nightly_pipeline.py
- .buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
- examples/experimental/dagster-dlift/dagster_dlift/client.py
- examples/experimental/dagster-dlift/dagster_dlift/compute.py
- examples/experimental/dagster-dlift/dagster_dlift/project.py
- examples/experimental/dagster-dlift/dagster_dlift/test/client_fake.py
- examples/experimental/dagster-dlift/dagster_dlift/translator.py
- examples/experimental/dagster-dlift/dagster_dlift/utils.py
- examples/experimental/dagster-dlift/dagster_dlift_tests/conftest.py
- examples/experimental/dagster-dlift/kitchen-sink/dlift_kitchen_sink/instance.py
- examples/experimental/dagster-dlift/kitchen-sink/dlift_kitchen_sink_tests/conftest.py
- examples/experimental/dagster-dlift/kitchen-sink/dlift_kitchen_sink_tests/test_instance_methods.py
Methods for manipulating jobs, launching runs, and retrieving run artifacts.
Had to make a few changes to unit tests to support. Also added a new live test which creates a job, runs a few methods on the job, launches a run, waits for it's completion, and then destroys the job.
> [dagster-dlift] job + run methods

- examples/experimental/dagster-dlift/kitchen-sink/dlift_kitchen_sink_tests/test_instance_methods.py
Unblocks the build for this failing test until we can get this more stable
BK
> mark cloud job API test as failing

- python_modules/dagster/dagster_tests/general_tests/compat_tests/test_back_compat.py
Creates sqlite connection using storage interface... trying to fix conn contextmanager issues on windows tests.
BK / azure pipelines
> cleanly close sqlite conn for windows backcompat test failures

- python_modules/dagster/dagster_tests/execution_tests/pipes_tests/test_subprocess.py
- python_modules/dagster/dagster_tests/execution_tests/pipes_tests/utils.py
Going to reuse this in a bunch of places
> [pipes, tests] add common utils.py to Pipes tests

- js_modules/dagster-ui/packages/ui-core/src/search/SearchResults.tsx
- js_modules/dagster-ui/packages/ui-core/src/search/types.ts
Corresponding internal PR: https://github.com/dagster-io/internal/pull/12126
> Add table name filter type

- docs/content/integrations/tableau.mdx
- docs/sphinx/sections/api/apidocs/libraries/dagster-tableau.rst
- examples/docs_snippets/docs_snippets/integrations/tableau/add-tableau-data-quality-warning.py
- examples/docs_snippets/docs_snippets/integrations/tableau/materialize-tableau-assets-advanced.py
- examples/docs_snippets/docs_snippets/integrations/tableau/refresh-and-materialize-tableau-assets.py
- python_modules/libraries/dagster-tableau/dagster_tableau/asset_utils.py
> [dagster-tableau] Update Tableau docs with custom materialization example

- python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
`automation_condition` is GA as of 1.9.0
👀
> remove "experimental" for automation_condition in asset docstring

- python_modules/dagster-test/dagster_test/toys/column_schema/column_schema_assets.py
As the title
Locally loaded this example
NOCHANGELOG
> Add table name and column tags example to toys

- .buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
- examples/experimental/dagster-airlift/examples/dbt-example/Makefile
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/constants.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/dbt_cloud_airflow.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/dbt_cloud_assets.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/dbt_cloud_utils.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/federated_airflow.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/federated_airflow_defs.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/jaffle_shop.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/utils.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/dagster_defs/with_dbt_cloud_defs.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example/federated_airflow_dags/dags.py
- examples/experimental/dagster-airlift/examples/dbt-example/dbt_example_tests/integration_tests/test_federated.py
- examples/experimental/dagster-airlift/examples/dbt-example/setup.py
- examples/experimental/dagster-airlift/examples/dbt-example/tox.ini
- examples/experimental/dagster-dlift/dagster_dlift/translator.py
Adds a downstream dbt model to the federated airflow instance.
Added new test handling for the dbt cloud assets. Tested manually.
> [dagster-airlift][federated-demo] dbt cloud defs

- .buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
Currently breaking the build, need to investigate the failures more deeply.
> [dagster-airlift] skip example tests

- .buildkite/dagster-buildkite/dagster_buildkite/pipelines/dagster_oss_nightly_pipeline.py
- .buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
- .buildkite/dagster-buildkite/dagster_buildkite/utils.py
In an upcoming PR, we'll be running against live dbt cloud. Let's only run these tests on commit and the nightly.
> only run dbt example on nightly and commits

- docs/sphinx/_ext/dagster-sphinx/dagster_sphinx/docstring_flags.py
- python_modules/dagster/dagster/_utils/warnings.py
Fix the grammar within the docs for superseded
> Fix Docs Typo

- python_modules/dagster/dagster/_utils/caching_instance_queryer.py
See changelog
Fixed issue with `AutomationCondition.run_in_progress` that would cause it to ignore queued runs.
> [DA] Fix issue with run_in_progress calculation

- python_modules/dagster-graphql/dagster_graphql/implementation/fetch_asset_condition_evaluations.py
- python_modules/dagster-graphql/dagster_graphql/schema/asset_condition_evaluations.py
> Don't iterate the whole asset graph to generate asset condition evaluation records

- docs/content/_navigation.json
Added missing navigation entry for Step Launchers -> Pipes migration guide
> [docs] add navigation entry for step launchers -> pipes migration guide

- js_modules/dagster-ui/packages/ui-core/src/runs/RunsFilterInput.tsx
Fixes build failing for https://github.com/dagster-io/dagster/commit/042e7e51a5fb9e7a65ee1adc6e6f26c10e694bc7
Tested locally, bk
NOCHANGELOG
> fix ui-core build

- docs/content/_navigation.json
- docs/content/integrations/airlift.mdx
- docs/content/integrations/airlift/reference.mdx
- docs/content/integrations/airlift/tutorial/overview.mdx
- docs/content/integrations/airlift/tutorial/peer.mdx
- docs/content/integrations/airlift/tutorial/setup.mdx
Docs for the peering stage. Mostly kept intact from the original tutorial, but changed the wording in the beginning, and added linkage to the rest of the tutorial.
> [dagster-airlift] peering stage docs

- docs/content/_navigation.json
- docs/content/integrations/airlift.mdx
- docs/content/integrations/airlift/full_dag.mdx
> [dagster-airlift] Dag level tutorial

- docs/content/integrations.mdx
> [docs] add link to community dingtalk integration

- python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/emr.py
Attach AWS EMR metadata to Pipes results in `PipesEMRClient`
[dagster-aws] `PipesEMRClient` now attaches AWS EMR metadata to Dagster results produced during Pipes invocation
> [dagster-aws] attach Dagster tags in PipesEMRClient

- docs/dagster-university/pages/dagster-dbt/lesson-2/2-set-up-the-dagster-project.md
- docs/dagster-university/pages/dagster-essentials/lesson-2/requirements-and-installation.md
Updates references in DU course of v1.7 to 1.9.
> [du] update references to dagster 1.7 to 1.9

- examples/project_du_dbt_starter/setup.py
Updates DU dbt starter to v1.9.*
> [du] update dbt starter to 1.9.*

- python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
Adds some debug logging which a user can manually enable, which tracks Sigma load process.
> [dagster-sigma][ez] Add info/debug logging

- CHANGES.md
> 1.9.2 changelog

- js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx
Add a useCallback here so that the reference doesnt change every render.
> Use useCalback in AssetGraphExplorer

- CHANGES.md
add late picks and reorder ui above libraries
> 1.9.2 other changes

- docs/content/dagster-plus/account/managing-users/managing-user-roles-permissions.mdx
Building docs for custom RBAC
Built Locally
> Docs for Custom RBAC

- docs/sphinx/sections/api/apidocs/libraries/dagster-airlift.rst
- examples/experimental/dagster-airlift/dagster_airlift/core/airflow_instance.py
Publicize the instance methods that are useful for the federation use case and add docstrings.
eyes
> [dagster-airlift][federation-apis] Airflow instance methods

- pyright/master/requirements-pinned.txt
Pins were messed up.
This didn't fail for me on branch; not sure why.
> [dagster-airlift] Fix pyright

- python_modules/dagster/dagster/_core/definitions/antlr_asset_selection/antlr_asset_selection.py
- python_modules/dagster/dagster/_core/definitions/asset_selection.py
- python_modules/dagster/dagster_tests/asset_defs_tests/test_antlr_asset_selection.py
- python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection.py
Fix for https://dagsterlabs.slack.com/archives/C03EQ628RS7/p1731620977027869
> Default include_sources in AntlrAssetSelectionParser

- docs/content/concepts/automation/declarative-automation.mdx
> Add missing dg. prefix to declarative automation docs

- python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
- python_modules/libraries/dagster-sigma/dagster_sigma_tests/conftest.py
Fixes pagination behavior for large Sigma fetches - previously we were incorrectly checking truthiness of this value.
Tested on large workspace, updated unit test.
> [dagster-sigma] Fixed an issue where API fetches did not paginate properly.
> [dagster-sigma] fix pagination behavior

- docs/dagster-university/yarn.lock
- docs/docs-beta/yarn.lock
Resolve https://github.com/dagster-io/dagster/security/dependabot/702.
Resolve https://github.com/dagster-io/dagster/security/dependabot/701.
Buildkite
> [ui] Fix cross-spawn dependabot alerts in docs

- python_modules/dagster/dagster/_serdes/__init__.py
- python_modules/dagster/dagster/_serdes/serdes.py
- python_modules/dagster/dagster_tests/general_tests/test_serdes.py
provide a utility to resolve the storage name of a serdes object
added test
> [serdes] get_storage_name

- examples/airlift-migration-tutorial/README.md
- examples/experimental/dagster-airlift/scripts/mirror_tutorial.sh
- examples/experimental/dagster-airlift/setup.py
Just released a new version of airlift which contains federation APIs. Includes a slight formatting fix to the tutorial readme, as well as fixes to the mirroring script.
> [dagster-airlift] Airlift 0.0.28 plus tutorial updates

- examples/airlift-federation-tutorial/README.md
- examples/airlift-migration-tutorial/README.md
- examples/experimental/dagster-airlift/Makefile
- examples/experimental/dagster-airlift/scripts/mirror_federation_tutorial.sh
- examples/experimental/dagster-airlift/scripts/mirror_tutorial.sh
- examples/experimental/dagster-airlift/setup.py
This PR adds a script to mirror the federation tutorial to github, and fleshes out the readme.
> [dagster-airlift] Federation tutorial mirroring

- docs/content/integrations/airlift/federation-tutorial/setup.mdx
- docs/content/integrations/airlift/tutorial/setup.mdx
- examples/airlift-federation-tutorial/README.md
- python_modules/dagster/dagster/_generate/download.py
- python_modules/libraries/dagster-airlift/dagster_airlift/__init__.py
Previously, airlift tutorials used a completely bespoke mirroring process. Let's consolidate on using the existing dagster example scaffolding in tutorials.
> [dagster-airlift][cleanup] Switch airlift examples to use normal scaffolding

- python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_ops.py
use semi-persisted instance instead of in mem
> fix fivetran 3.12 flake

- docs/content/integrations.mdx
> [docs] add GCP cloud run launcher to integration listing

- js_modules/dagster-ui/packages/ui-core/src/nav/__tests__/useRepositoryLocationReload.test.tsx
> Skip flakey test

- docs/docs-beta/docs/reference/api-lifecycle.md
- docs/docs-beta/docs/reference/index.md
- docs/docs-beta/docusaurus.config.ts
- docs/docs-beta/sidebars.ts
Adds API Lifecycle stages to the beta docs
> [docs-beta] Add API Lifecycle Stages reference guide

- python_modules/libraries/dagster-powerbi/dagster_powerbi/translator.py
- python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_translator.py
Like #26027 but for Power BI
Updated unit test with BK
> [dagster-powerbi] Use get_asset_spec().key in DagsterPowerBITranslator

- docs/content/integrations/sigma.mdx
- examples/docs_snippets/docs_snippets/integrations/sigma/customize-sigma-asset-defs.py
> [dagster-sigma] Update custom translator example in Sigma docs

- examples/project_atproto_dashboard/.gitignore
- examples/project_atproto_dashboard/README.md
- examples/project_atproto_dashboard/dagster.yaml
- examples/project_atproto_dashboard/project_atproto_dashboard/definitions.py
- examples/project_atproto_dashboard/setup.py
- Generates dynamic partitions in `starter_pack_snapshot` as user IDs in `actor_feed_snapshot`
> [devrel] use dynamic partitions for user feeds

- examples/project_atproto_dashboard/.gitignore
- examples/project_atproto_dashboard/README.md
- examples/project_atproto_dashboard/dagster.yaml
- examples/project_atproto_dashboard/project_atproto_dashboard/definitions.py
- examples/project_atproto_dashboard/setup.py
Creates snapshot of the Data People Starter Pack to be used as a dynamic partition key for getting user feeds.
> [devrel] add snapshotting of bsky starter packs

- examples/project_atproto_dashboard/.gitignore
- examples/project_atproto_dashboard/README.md
- examples/project_atproto_dashboard/dagster.yaml
- examples/project_atproto_dashboard/project_atproto_dashboard/definitions.py
- examples/project_atproto_dashboard/setup.py
Ingests snapshot of (currently hardcoded) user feed to S3 (R2 in this case).
Next stack will make this dynamically partitioned to get multiple feeds.
> [devrel] add data ingestion for atproto feeds (bsky social)

- docs/content/integrations/looker.mdx
- examples/docs_snippets/docs_snippets/integrations/looker/customize-looker-assets.py
Like #26029 but for Looker API
> [dagster-looker] Update custom API translator example in Looker docs

- docs/content/integrations/looker.mdx
One line was copied from Power BI but not updated.
> [dagster-looker][docs] Fix prerequisites in Looker docs

- docs/content/integrations/powerbi.mdx
As title, like for the other BI integrations. The section was originally added for other BI docs after receiving user feedback.
> [dagster-powerbi][docs] Add setup env section in Power BI docs

- python_modules/dagster/dagster/__init__.py
- python_modules/dagster/dagster/_components/cli/generate.py
- python_modules/dagster/dagster/_generate/templates/COMPONENT_TYPE/COMPONENT_TYPE_NAME_PLACEHOLDER.py.jinja
- python_modules/dagster/dagster_tests/cli_tests/test_generate_commands.py
> [components] Clean up tests and fix mounting of `dg generate` subcommands

- docs/content/integrations/powerbi.mdx
- examples/docs_snippets/docs_snippets/integrations/power-bi/customize-power-bi-asset-defs.py
> [dagster-powerbi] Update custom translator example in Power BI docs

- python_modules/libraries/dagster-tableau/dagster_tableau/translator.py
See comments [here](https://github.com/dagster-io/dagster/pull/26052#issuecomment-2499026767) and [here](https://github.com/dagster-io/dagster/pull/26036#pullrequestreview-2459593578). Same thing but for Tableau.
> [dagster-tableau] Update deprecation message for get_asset_key in DagsterTableauTranslator

- python_modules/dagster/dagster/_cli/asset.py
https://github.com/dagster-io/dagster/issues/26221
No tests performed.
> Adds clearer usage help (`dagster asset materialize --select`)

- examples/experimental/dagster-blueprints/dagster_blueprints_tests/__snapshots__/test_load_defs_from_yaml.ambr
- python_modules/dagster/setup.py
resolves https://github.com/dagster-io/dagster/issues/26203
bk
> shift pydantic upper bound to 3.0.0

- docs/docs-beta/scripts/vercel-sync-api-docs.sh
> [docs-beta] rm source cargo for uv use

- docs/content/integrations/airlift.mdx
- docs/content/integrations/airlift/tutorial.mdx
Let me know if you'd prefer it here, or in https://docs.dagster.io/integrations/airlift#airlift
> [docs] include link to airlift video in tutorial

- python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
Need more traces in debugging spurious sqlite threaded tests.
BK
> raise exceptions if encountered in threaded concurrency test

- python_modules/dagster/setup.py
- python_modules/libraries/dagster-mlflow/setup.py
resolves https://github.com/dagster-io/dagster/issues/25398
> protobuf ceiling bump

- docs/content/concepts/automation/declarative-automation/automation-conditions-explained.mdx
- docs/content/concepts/automation/declarative-automation/customizing-automation-conditions.mdx
- examples/docs_snippets/docs_snippets/concepts/declarative_automation/all_parents_condition.py
- examples/docs_snippets/docs_snippets/concepts/declarative_automation/allow_dependencies_cron.py
- examples/docs_snippets/docs_snippets/concepts/declarative_automation/allow_missing_upstreams.py
- examples/docs_snippets/docs_snippets/concepts/declarative_automation/blocking_checks_condition.py
- examples/docs_snippets/docs_snippets/concepts/declarative_automation/ignore_dependencies_cron.py
- examples/docs_snippets/docs_snippets/concepts/declarative_automation/update_older_time_partitions.py
- examples/docs_snippets/docs_snippets/concepts/declarative_automation/update_specific_older_partition.py
This splits up the existing customizing-automation-conditions page into two. The first is a slimmed-down version of the original page that stays much more focused on specific use cases. I also took the liberty of backing out of the original sin of directly embedding python into the mdx (now it's broken out into separate python files, at least for the new stuff).
The second page is a more advanced conceptual guide for the ins and outs of AutomationConditions. This is not necessary information for the majority of users, but I think it is valuable to have in some place to give interested users a more detailed conceptual understanding of how the system fits together, especially if they have highly-specific use cases that require deep manipulation of the APIs.
Also, some of the existing code …
> [DA] Update docs

- examples/experimental/dagster-components/dagster_components/impls/sling_replication.py
- examples/experimental/dagster-components/dagster_components_tests/integration_tests/test_sling_integration_test.py
- examples/experimental/dagster-components/dagster_components_tests/stub_code_locations/sling_location/components/ingest/defs.yml
Add nesting to the sling componet configuration, so that we can add more things to it.
BK
> [components] Add nesting to sling component config

- python_modules/libraries/dagster-components/dagster_components/impls/dbt_project.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_templated_custom_keys_dbt_project.py
In similar fashion, this allows customization of groups. 
BK
> [components] Allow customization of group

- js_modules/dagster-ui/packages/ui-core/src/automation/VirtualizedAutomationScheduleRow.tsx
- js_modules/dagster-ui/packages/ui-core/src/automation/VirtualizedAutomationSensorRow.tsx
- js_modules/dagster-ui/packages/ui-core/src/ticks/EvaluateTickButtonSchedule.tsx
- js_modules/dagster-ui/packages/ui-core/src/ticks/EvaluateTickButtonSensor.tsx
Linear: https://linear.app/dagster-labs/issue/FE-697/implement-updated-designs-initial-renames-[1n]
Everything in Linear ticket
tested locally
> [7/n] [RFC] Implement updated designs: Initial renames [1/N]

- python_modules/libraries/dagster-components/dagster_components/core/component_defs_builder.py
- python_modules/libraries/dagster-components/dagster_components/generate.py
- python_modules/libraries/dagster-components/dagster_components/impls/dbt_project.py
- python_modules/libraries/dagster-components/dagster_components/impls/sling_replication.py
- python_modules/libraries/dagster-components/dagster_components_tests/cli_tests/test_generate_commands.py
Went through some rounds of iteration on getting the demo flow to work, uncovering some bugs along the way
NOCHANGELOG
> [components] Minor tweaks to make the demo flow work

- docs/content/_navigation.json
- docs/content/integrations/airlift.mdx
- docs/content/integrations/airlift/operator-migration/bash-operator-dbt.mdx
- docs/content/integrations/airlift/operator-migration/overview.mdx
- examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/bash_operator_dbt.py
- examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/using_dbt_assets.py
Scaffolds out guide structure for dealing with operator migrations. That is, for a given operator in Airflow, how do you migrate it to Dagster? We'll write one of these for each of the common airflow operators (and will likely add more in the future).
> [dagster-airlift] Operator Migration guides

- docs/content/integrations/airlift/airflow-dagster-equivalents.mdx
Actually update the equivalencies page to be accurate. Some of these are not updated; sometimes there needs to be additional fields.
> [dagster-airlift] Update equivalencies page

- docs/content/integrations/airlift/reference.mdx
Write a blurb on how we think users should engage with a migration. I think that the actual "best practices" here deserve some vetting as well.
> [dagster-airlift] Migration best practices

- docs/content/_navigation.json
- docs/content/integrations/fivetran/fivetran-legacy.mdx
As title, new docs to be added in next PR.
See preview.
> [docs] Move legacy Fivetran docs

- python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran/translator.py
> [dagster-fivetran] Update docstrings for DagsterFivetranTranslator and FivetranWorkspace

- docs/content/concepts/assets/asset-checks.mdx
> Fix typos in asset check docs

- js_modules/dagster-ui/packages/ui-core/src/app/DefaultFeatureFlags.oss.tsx
- js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx
Adding a URL search param that can be used to enable the feature flag since we don't yet want to expose the flag to users
> [Asset selection syntax] Add url search param to enable hidden featue flag

- docs/content/_navigation.json
Missed this bit of config in the first go-around
NOCHANGELOG
> [docs] Add automation-conditions-explained

- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project.py
As title -- we already have a reference to the dbt resource from the component loading codepath, and so threading it through Definitions doesn't actually make much sense.
It's free to construct one of these things (it doesn't have to do any expensive spinup), and this way we don't need to worry about situations where we have multiple dbt project components with conflicting resource keys
Other integrations where resource construction is not free will not be able to use this pattern, but this sort of thing is quite common
NOCHANGELOG
> [components] Add execute method to dbt project, remove resource from defs

- python_modules/libraries/dagster-airlift/dagster_airlift/in_airflow/materialize_assets_operator.py
- python_modules/libraries/dagster-airlift/dagster_airlift_tests/integration_tests/materialize_assets_operator_test_project/dags/dag.py
- python_modules/libraries/dagster-airlift/dagster_airlift_tests/integration_tests/materialize_assets_operator_test_project/dagster_defs.py
- python_modules/libraries/dagster-airlift/dagster_airlift_tests/integration_tests/test_materialize_assets_operator.py
In response to recent product review where we decided to standardize the interpolation of asset keys.
> [dagster-airlift] Standardize asset key interpolation

- docs/docs-beta/yarn.lock
- docs/next/yarn.lock
- js_modules/dagster-ui/yarn.lock
Clear several dependabot alerts:
- https://github.com/dagster-io/dagster/security/dependabot/717
- https://github.com/dagster-io/dagster/security/dependabot/716
- https://github.com/dagster-io/dagster/security/dependabot/713
- https://github.com/dagster-io/dagster/security/dependabot/712
- https://github.com/dagster-io/dagster/security/dependabot/711
Buildkite
> [ui] Clean up Dependabot alerts

- python_modules/libraries/dagster-dg/dagster_dg/cli/generate.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/list.py
- python_modules/libraries/dagster-dg/dagster_dg/generate.py
- python_modules/libraries/dagster-dg/dagster_dg/utils.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_generate_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py
Improve the docstrings for `dg` commands. Also convert them to use `Path` instead of `str` where possible.
> [components] Improve docstrings and clean up code in dagster-dg

- python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/dlt/dlt_event_iterator.py
Same as #26424 but for `DltEventIterator`
> [dagster-embedded-elt][dlt] Subclass typing.Iterator in DltEventIterator

- python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/sling_event_iterator.py
Same as #26424 but for `SlingEventIterator`
> [dagster-embedded-elt][sling] Subclass typing.Iterator in SlingEventIterator

- python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/generate.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/list.py
- python_modules/libraries/dagster-dg/dagster_dg/component.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/error.py
- python_modules/libraries/dagster-dg/dagster_dg/generate.py
- python_modules/libraries/dagster-dg/dagster_dg/utils.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_generate_commands.py
General clean up of `dagster-dg` code-- standardizing names, removing some detritus, etc. No significant behavior changes.
> [components] dagster-dg general code cleanup

- CHANGES.md
> [changelog] 1.9.5

- python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/dlt/dlt_event_iterator.py
Same as #26455 but for DltEventIterator
> [dagster-embedded-elt][dlt] Use Iterator[T] in DltEventIterator

- python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/sling_event_iterator.py
Same as #26455 but for SlingEventIterator
> [dagster-embedded-elt][sling] Use Iterator[T] in SlingEventIterator

- docs/content/dagster-plus/deployment/azure/blob-compute-logs.mdx
> make mdx-format

- python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py
Summary:
This test currently leaves backfill storage on, potentially causing issues for other tests. Make it a fixture instead.
Test plan BK,: Should unblock test failures on https://github.com/dagster-io/dagster/pull/26189
NOCHANGELOG
> Cleanup instance  changes in test_asset_backfill_logs after test

- examples/assets_modern_data_stack/setup.py
> fix assets_modern_data_stack

- examples/docs_beta_snippets/tox.ini
> fix docs build

- python_modules/libraries/dagster-components/dagster_components/core/dsl_schema.py
- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project.py
- python_modules/libraries/dagster-components/dagster_components/lib/pipes_subprocess_script_collection.py
- python_modules/libraries/dagster-components/dagster_components/lib/sling_replication.py
- python_modules/libraries/dagster-components/dagster_components_tests/code_locations/python_script_location/components/scripts/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_dbt_project.py
- python_modules/libraries/dagster-components/dagster_components_tests/stub_code_locations/dbt_project_location/components/jaffle_shop_dbt/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_pipes_subprocess_script_collection.py
> [components] allow automation_condition to be set with AssetSpecModel

- python_modules/dagster-graphql/dagster_graphql/schema/solids.py
Allows leveraging overridden implemntation for resolving theses assets
> [graphql] use get_assets_in_job in Solid.assetNodes

- docs/docs-beta/CONTRIBUTING.md
- Adds some pointers on migrating between legacy and new docs
> [docs-beta] add contributing migration section

- pyright/master/requirements.txt
Was an oversight that this is not present.
pyright
> [components] Add dagster-dg to pyright env

- python_modules/dagster/dagster/_core/snap/node.py
> [record] snap/node.py

- python_modules/dagster/dagster/_core/pipes/context.py
- python_modules/dagster/dagster/_core/pipes/utils.py
Small Pipes edits which makes it easier to test Pipes (needed for Java pipes tests)
Existing tests
> [pipes] small improvements to make Pipes more test-friendly

- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/core/component_rendering.py
- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project.py
This builds on the previous PR such that we actually use the rendering enginer / do pre-processing on the raw data in component.yaml before loading it in as structured params
NOCHANGELOG
> [components] pass renderer through ComponentLoadContext

- python_modules/libraries/dagster-components/dagster_components/core/component_rendering.py
- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project.py
- python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_component_rendering.py
As title -- nicer interface that just stacks on top of the existing Pydantic Field class
NOCHANGELOG
> [components] Simplify ScopedField creation

- js_modules/dagster-ui/packages/ui-core/src/launchpad/useLaunchMultipleRunsWithTelemetry.ts
- js_modules/dagster-ui/packages/ui-core/src/runs/RunConfigDialog.tsx
- js_modules/dagster-ui/packages/ui-core/src/ticks/DryRunRequestTable.tsx
- js_modules/dagster-ui/packages/ui-core/src/ticks/EvaluateScheduleDialog.tsx
- js_modules/dagster-ui/packages/ui-core/src/ticks/SensorDryRunDialog.tsx
- js_modules/dagster-ui/packages/ui-core/src/ticks/__fixtures__/EvaluateScheduleDialog.fixtures.tsx
- js_modules/dagster-ui/packages/ui-core/src/ticks/__fixtures__/SensorDryRunDialog.fixtures.tsx
- js_modules/dagster-ui/packages/ui-core/src/ticks/__tests__/EvaluateScheduleDialog.test.tsx
- js_modules/dagster-ui/packages/ui-core/src/ticks/__tests__/SensorDryRunDialog.test.tsx
https://dagsterlabs.slack.com/archives/C06QU0WBCQ5/p1734625511029539
Will test in dogfood replicating this situation
> [ui] use jobName as fallback if only launching 1 job

- docs/docs-beta/CONTRIBUTING.md
Link to old and new docs image directories to help folks migrating content.
> Update new docs CONTRIBUTING with image directory links

- python_modules/libraries/dagster-components/dagster_components/lib/definitions_component.py
Adding basic scaffolding logic for this one. Want to discuss what the right testing harness is for stuff because it is potentially a huge pain.
Manual
> [components] Generate logic for DefinitionsComponent

- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project.py
This is done in `load_params`, so not necessary in the subclass.
BK
> [components] Remove duplicative pushd

- docs/content/integrations/airbyte/airbyte-cloud.mdx
- examples/docs_snippets/docs_snippets/integrations/airbyte-cloud/customize_airbyte_cloud_asset_defs.py
- examples/docs_snippets/docs_snippets/integrations/airbyte-cloud/customize_airbyte_cloud_translator_asset_spec.py
- examples/docs_snippets/docs_snippets/integrations/airbyte-cloud/multiple_airbyte_cloud_workspaces.py
- examples/docs_snippets/docs_snippets/integrations/airbyte-cloud/representing_airbyte_cloud_assets.py
- examples/docs_snippets/docs_snippets/integrations/airbyte-cloud/sync_and_materialize_airbyte_cloud_assets.py
> [docs] Add docs for reworked Airbyte Cloud API

- python_modules/libraries/dagster-dg/dagster_dg/templates/COMPONENT_TYPE/COMPONENT_TYPE_NAME_PLACEHOLDER.py.jinja
Fix broken import not caught by lint because it's in a template.
BK
> [components] fix broken import in scaffold template

- python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
> mark test_threaded_concurrency as flaky

- python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/last_update.py
- python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/sensor.py
- python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/time_partition.py
- python_modules/dagster/dagster/_core/definitions/asset_check_factories/metadata_bounds_checks.py
- python_modules/dagster/dagster/_core/definitions/asset_check_factories/schema_change_checks.py
reason: these APIs feel "not quite done", and we may want to refactor them in the future. In particular, building a sensor for freshness checks might not make the most sense -- we may want to just automatically add AutomationConditions to the checks
> [core-api][experimental] freshness checks

- python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/last_update.py
- python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/sensor.py
- python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/time_partition.py
- python_modules/dagster/dagster/_core/definitions/asset_check_factories/metadata_bounds_checks.py
- python_modules/dagster/dagster/_core/definitions/asset_check_factories/schema_change_checks.py
- python_modules/dagster/dagster/_core/definitions/asset_out.py
- python_modules/dagster/dagster/_core/definitions/asset_spec.py
- python_modules/dagster/dagster/_core/definitions/assets.py
- python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
- python_modules/dagster/dagster/_core/definitions/external_asset.py
- python_modules/dagster/dagster/_core/definitions/input.py
- python_modules/dagster/dagster/_core/definitions/metadata/source_code.py
- python_modules/dagster/dagster/_core/definitions/reconstruct.py
- python_modules/dagster/dagster/_core/definitions/run_request.py
- python_modules/dagster/dagster/_core/instance/__init__.py
- python_modules/dagster/dagster/_core/storage/dagster_run.py
reason: this set of features seems like it may change in the future, at least in terms of recommended API. the current entrypoints are a bit clunky.
> [core-api][experimental] source code metadata

- js_modules/dagster-ui/packages/ui-core/jest/mocks/ComputeGraphData.worker.ts
- js_modules/dagster-ui/packages/ui-core/src/app/DefaultFeatureFlags.oss.tsx
- js_modules/dagster-ui/packages/ui-core/src/app/FeatureFlags.oss.tsx
- js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx
- js_modules/dagster-ui/packages/ui-core/src/asset-graph/ComputeGraphData.types.ts
- js_modules/dagster-ui/packages/ui-core/src/asset-graph/ComputeGraphData.worker.ts
- js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx
- js_modules/dagster-ui/packages/ui-core/src/asset-selection/AntlrAssetSelection.ts
- js_modules/dagster-ui/packages/ui-core/src/asset-selection/useAssetSelectionInput.tsx
- js_modules/dagster-ui/packages/ui-core/src/gantt/GanttChart.tsx
- js_modules/dagster-ui/packages/ui-core/src/run-selection/AntlrRunSelection.ts
- js_modules/dagster-ui/packages/ui-core/src/runs/Run.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunActionButtons.tsx
Originally we thought we might release these independently but we're just going to release them together since there is overlap in their docs.
> Consolidate `flagRunSelectionSyntax` and `flagAssetSelectionSyntax` to just `flagSelectionSyntax`

- js_modules/dagster-ui/packages/ui-core/src/asset-selection/input/AssetSelectionInput.oss.tsx
- js_modules/dagster-ui/packages/ui-core/src/gantt/GanttChartSelectionInput.tsx
- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionAutoCompleteInput.tsx
- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionAutoCompleteInputParser.ts
> Track engagement of new selection syntax

- python_modules/dagster-test/dagster_test/fixtures/docker_compose.py
if the network name is specified in the docker compose file, use that
> use network name in docker-compose file if specified

- python_modules/libraries/dagster-components/dagster_components/lib/__init__.py
- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/generator.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_dbt_project.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_templated_custom_keys_dbt_project.py
Move generator and runtime component of dbt_project into separate files/modules
BK
> [components] Separate out runtime component and generator in dbt_project

- python_modules/libraries/dagster-components/dagster_components/lib/__init__.py
- python_modules/libraries/dagster-components/dagster_components/lib/definitions_component/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/definitions_component/generator.py
- python_modules/libraries/dagster-components/dagster_components/lib/sling_replication.py
Refactor the `DefinitionsComponent` and the `SlingComponent` to use the generator class
BK
> [components] Refactor DefinitionsComponent and SlingComponent to use ComponentGenerator

- python_modules/libraries/dagster-components/dagster_components/core/component_generator.py
- python_modules/libraries/dagster-components/dagster_components/lib/test/all_metadata_empty_asset.py
- python_modules/libraries/dagster-components/dagster_components/lib/test/simple_asset.py
Add a implementation of the generator that serves as a default implementation and use it in tests.
BK
> [components] Add default component generator and use it in some test components

- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/test/simple_asset.py
- python_modules/libraries/dagster-components/dagster_components/lib/test/simple_pipes_script_asset.py
Moves another test class to the new generator
BK
> [components] Convert SimplePipesScriptAssetComponent to generator

- python_modules/libraries/dagster-components/dagster_components/__init__.py
- python_modules/libraries/dagster-components/dagster_components/cli/generate.py
- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/generate.py
- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/generator.py
- python_modules/libraries/dagster-components/dagster_components/lib/definitions_component/generator.py
- python_modules/libraries/dagster-components/dagster_components/lib/sling_replication.py
- python_modules/libraries/dagster-components/dagster_components/lib/test/simple_pipes_script_asset.py
Remove the adapter classes and associated code paths with the migration to the new generator classed-based approach
BK
> [components] Eliminate adapters and temporary code for generator

- js_modules/dagster-ui/packages/ui-core/src/app/GraphQueryImpl.ts
- js_modules/dagster-ui/packages/ui-core/src/assets/AssetsGlobalGraphRoot.tsx
As titled
[ui] Asset selection filtering is now case insensitive
> Make selection filtering case insentive

- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/core/component_defs_builder.py
- python_modules/libraries/dagster-components/dagster_components/core/component_rendering.py
- python_modules/libraries/dagster-components/dagster_components/core/dsl_schema.py
- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/pipes_subprocess_script_collection.py
- python_modules/libraries/dagster-components/dagster_components/lib/sling_replication.py
- python_modules/libraries/dagster-components/dagster_components_tests/rendering_tests/test_component_rendering.py
- python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_spec_processing.py
- python_modules/libraries/dagster-components/setup.py
As title. We're calling this process "rendering", so it makes sense for the class to be a renderer instead of a resolver
NOCHANGELOG
> [components] Resolver -> Renderer

- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_auto_materialize_paused.py
> rename pause amp graphql test

- python_modules/libraries/dagster-components/dagster_components_tests/code_locations/custom_sling_location/custom_sling_location/components/debug_sling_component/component.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_commands.py
Updated the sling replication component, some tests need to change
NOCHANGELOG
> [components] Fix master

- js_modules/dagster-ui/packages/ui-core/src/assets/overview/Common.tsx
Adds an option to pass interactions/buttons to the section empty state
> [ui] Add option to pass interactions/buttons to SectionEmptyState

- python_modules/libraries/dagster-airlift/setup.py
Retrieved from https://raw.githubusercontent.com/apache/airflow/constraints-2.10.3/constraints-3.12.txt
> [dagster-airlift] [TEST-ALL] pin marshmallow airlift 3.12

- python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_component_with_optional_generator.py
Demonstrate how ComponentGeneratorUnavailableReason would be used
BK
> [components] Show example usage of ComponentGeneratorUnavailableReason

- js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedRoot.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedTable.tsx
> [RunsFeed] Add terminate all runs button

- js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx
- js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx
> Fix "query error" on asset graph showing when loading

- python_modules/dagster/dagster/_daemon/asset_daemon.py
- python_modules/dagster/dagster_tests/declarative_automation_tests/daemon_tests/test_asset_daemon.py
- python_modules/dagster/dagster_tests/declarative_automation_tests/scenario_utils/asset_daemon_scenario.py
- python_modules/dagster/dagster_tests/declarative_automation_tests/scenario_utils/scenario_specs.py
> scenario that works

- python_modules/dagster/dagster_tests/declarative_automation_tests/daemon_tests/test_asset_daemon.py
- python_modules/dagster/dagster_tests/declarative_automation_tests/scenario_utils/asset_daemon_scenario.py
> trying to test with threads

- examples/project_ask_ai_dagster/project_ask_ai_dagster/assets/ingestion.py
Minor fixes for ask-ai project that I discovered and fixed while making demo video. 
Ran Successfully
> add text splitting for the docs scrape

- docs/next/styles/globals.css
- docs/sphinx/_ext/sphinx-mdx-builder/sphinxcontrib/mdxbuilder/writers/mdx.py
Updates the CSS for superseded and deprecated flags as discussed [here](https://github.com/dagster-io/dagster/pull/26819#discussion_r1907864313)
> [docs] Update CSS for superseded and deprecated flags

- python_modules/dagster/dagster/_core/definitions/module_loaders/load_defs_from_module.py
- python_modules/dagster/dagster_tests/definitions_tests/module_loader_tests/test_module_loaders.py
Same as https://github.com/dagster-io/dagster/pull/26546 but for current module
> [module-loaders] Add load_definitions_from_current_module

- helm/dagster/schema/schema/charts/dagster/subschema/compute_log_manager.py
- helm/dagster/schema/schema_tests/test_instance.py
- helm/dagster/templates/helpers/instance/_compute-log-manager.tpl
- helm/dagster/values.schema.json
- helm/dagster/values.yaml
- python_modules/libraries/dagster-azure/dagster_azure/blob/compute_log_manager.py
https://github.com/dagster-io/dagster/pull/27010 follow-up
> [azure] helm and ruff fixes

- python_modules/libraries/dagster-dg/dagster_dg/utils.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_type_commands.py
Fix straightforward boolean with a flipped boolean in a conditional check.
Existing test suite (tests were failing).
> [components] Fix bug with reversed boolean for managed env

- python_modules/dagster/dagster/_core/definitions/module_loaders/load_defs_from_module.py
> [module-loaders] Add docstring for load_definitions_from_module

- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/code_locations/templated_custom_keys_dbt_project_location/components/jaffle_shop_dbt/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_templated_custom_keys_dbt_project.py
Same as the below PR, but for the dbt integration
NOCHANGELOG
> [components] Update translator handling in DbtProjectComponent

- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/core/component_defs_builder.py
- python_modules/libraries/dagster-components/dagster_components/core/component_rendering.py
- python_modules/libraries/dagster-components/dagster_components/core/dsl_schema.py
- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/pipes_subprocess_script_collection.py
- python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components/utils.py
- python_modules/libraries/dagster-components/dagster_components_tests/code_locations/dbt_project_location/components/jaffle_shop_dbt/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/rendering_tests/test_component_rendering.py
- python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_spec_processing.py
Changes terminology from "render" to "resolve"
NOCHANGELOG
> [components][rfc] rendering -> resolution

- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/rendering_tests/test_component_rendering.py
misc changes that helped with the dop-c transition
NOCHANGELOG
> [components] DbtComponent QoL improvements

- python_modules/dagster/dagster/_core/execution/asset_backfill.py
Summary:
This ensures that this error is properly processed and classified.
> Add a missing DaemonErrorCapture callsite

- js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/AssetTable.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx
- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionAutoCompleteHighlighter.ts
- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionAutoCompleteInput.tsx
> Expand Selection auto-complete input when focused

- python_modules/libraries/dagster-aws/dagster_aws_tests/pipes_tests/test_emr.py
> [dagster-aws] a basic test for PipesEMRClient

- docs/content/integrations/embedded-elt.mdx
Fixes this [comment](https://github.com/dagster-io/dagster/pull/27074#pullrequestreview-2551337375) in #27074 
Docs preview
> [docs] Update language in /integrations/embedded-elt

- python_modules/automation/tox.ini
Fix tests in `test_resource_telemetry.py`, see failing tests [here](https://buildkite.com/dagster/dagster-dagster/builds/108147#01946a78-ad2b-4931-abc7-276da848ebb3).
BK
> [automation] Add dagster-dlt and dagster-sling in tox

- python_modules/automation/automation_tests/telemetry/test_resource_telemetry.py
Fix [comment](https://github.com/dagster-io/dagster/pull/27125#issuecomment-2593639612) in #27125. PR was already merged to get green build when comment was addressed.
> [automation] Update comment in test_resource_telemetry

- docs/docs-beta/docs/integrations/libraries/anthropic.md
- docs/docs-beta/docs/integrations/libraries/gemini.md
- docs/docs-beta/docs/integrations/libraries/weaviate.md
in a rush, will do a follow up to move the python code to proper python files under tests.
local loads
> [docs] new integration pages: anthropic, gemini, weaviate

- docs/docs-beta/docs/guides/build/project-structure/creating-a-component.md
- docs/docs-beta/docs/guides/build/project-structure/existing-code-location.md
- docs/docs-beta/docs/integrations/libraries/anthropic.md
- docs/docs-beta/docs/integrations/libraries/gemini.md
- docs/docs-beta/docs/integrations/libraries/weaviate.md
check out my beautiful previews:
- https://dagster-docs-beta-5n2fijm13-elementl.vercel.app/integrations/libraries/anthropic
- https://dagster-docs-beta-5n2fijm13-elementl.vercel.app/integrations/libraries/weaviate
- https://dagster-docs-beta-5n2fijm13-elementl.vercel.app/integrations/libraries/gemini
> fix vercel build - fix broken todo anchor

- docs/docs-beta/docs/integrations/libraries/chroma.md
same as https://app.graphite.dev/github/pr/dagster-io/dagster/27118/docs-new-integration-pages-anthropic-gemini-weaviate
will move code snippet to python file in a followon pr  
local loads
> [docs] chroma

- docs/docs-beta/docs/integrations/libraries/weaviate.md
> [docs] Fix Weaviate icon

- .buildkite/dagster-buildkite/dagster_buildkite/steps/dagster.py
> Ensure uv venv is built for Pyright Buildkite step

- python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/code_location.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/component.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/component_type.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/deployment.py
- python_modules/libraries/dagster-dg/dagster_dg/utils.py
Factor out commonly used motif `click.echo(click.style(..., fg="red"))` into a utility fuction. Simplifies CLI entry point code.
> [components] Factor out click error message code

- integration_tests/test_suites/daemon-test-suite/dagster_dev_command_tests/test_dagster_dev_command.py
- python_modules/dagster/dagster/_cli/dev.py
Add a flag which can disable the new "single grpc server" behavior.
This provides an easy out if there are unintended consequences with the behavior change.
Added a test and ensured the old behavior was preserved (we spin up 4 servers). Test only runs on unix
> [single-grpc-server] add disablement flag

- integration_tests/test_suites/daemon-test-suite/dagster_dev_command_tests/test_dagster_dev_command.py
- python_modules/dagster/dagster/_cli/code_server.py
- python_modules/dagster/dagster/_cli/dev.py
- python_modules/dagster/dagster/_core/remote_representation/grpc_server_registry.py
- python_modules/dagster/dagster/_core/remote_representation/origin.py
- python_modules/dagster/dagster/_core/types/loadable_target_origin.py
- python_modules/dagster/dagster/_core/workspace/config_schema.py
- python_modules/dagster/dagster/_core/workspace/context.py
- python_modules/dagster/dagster/_core/workspace/load.py
- python_modules/dagster/dagster/_daemon/controller.py
- python_modules/dagster/dagster/_grpc/proxy_server.py
- python_modules/dagster/dagster/_grpc/server.py
- python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_grpc_server_registry.py
- python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_persistent.py
- python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_ping.py
This PR makes the entrypoint configurable when using the GrpcServerRegistry. 
Added new parameterizations for the entrypoint in the grpcserverregistry tests.
> Use code server start in process context use cases

- integration_tests/test_suites/dagster-azure-live-tests/integration_tests/test_compute_log_manager.py
- Add new shell cmd fields with minimal coverage
- Incoming PR to add a test with the azure cli.
> [dagster-azure] testing shell cmd

- integration_tests/test_suites/dagster-azure-live-tests/integration_tests/conftest.py
- integration_tests/test_suites/dagster-azure-live-tests/integration_tests/test_compute_log_manager.py
- python_modules/libraries/dagster-azure/dagster_azure/blob/compute_log_manager.py
- Tests that the shell command we provide to retrieve logs with Azure CLI works.
- BK
> [dagster-azure] Testing shell cmd to download logs with azure cli in integration tests

- docs/docs-beta/docs/guides/build/assets/asset-jobs.md
- examples/docs_beta_snippets/docs_beta_snippets/guides/data-modeling/asset-jobs/asset-jobs.py
Update code examples for asset-jobs
CodeExamples
Hardcoded - updated to `import dagster as dg` format
> [docs] Update asset-jobs CodeExample

- docs/docs-beta/docs/guides/build/assets/defining-assets-with-asset-dependencies.md
- examples/docs_beta_snippets/docs_beta_snippets/guides/data-modeling/asset-dependencies/asset-dependencies.py
Added code references for this [ticket](https://linear.app/dagster-labs/issue/DOC-714/docsguidesbuildassetsdefining-assets-with-asset-dependenciesmd)
> DOC-714-add code references for dependant assets

- docs/docs-beta/docs/guides/automate/asset-sensors.md
- examples/docs_beta_snippets/docs_beta_snippets/guides/automation/multi-asset-sensor.py
Added code reference for `@multi_asset_sensors` for new docs. 
The code works & how it displays on the page.
> add code reference

- python_modules/dagster/dagster/_utils/error.py
- python_modules/dagster/dagster_tests/core_tests/test_mask_user_code_errors.py
Using a python logger here lets users customize the formatting of the log messages (e.g. to make them JSON).
BK, Run an asset that fails with DAGSTER_REDACT_USER_CODE_ERRORS on, view output
When using the `DAGSTER_REDACT_USER_CODE_ERRORS` environment variable to mask user code errors, the unmasked log lines are now written using a `dagster.masked` Python logger instead of being written to stderr, allowing the format of those log lines to be customized.
> Use a python logger instead of stderr write when logging redacted user code information

- docs/next/pages/api/code-snippet.ts
Sanitize filepath from dot and colon chars
> [docs] sanitize docs snippet filepath

- examples/docs_snippets/docs_snippets/guides/dagster/asset_tutorial/non_argument_deps.py
fixes docs build
`pytest examples/docs_snippets/docs_snippets_tests/guides_tests/asset_tutorial_tests/test_non_argument_deps.py`
> [docs snippets] update vercel link to github

- docs/content/concepts/dagster-pipes/pyspark.mdx
- examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/emr-containers/dagster_code.py
> [chore] fix broken build

- CHANGES.md
Add the 1.9.9 changelog
Inspection
> 1.9.9 changelog

- docs/sphinx/conf.py
> [docs-beta] revert title change

- docs/dagster-university/pages/dagster-dbt/lesson-2/2-set-up-the-dagster-project.md
- examples/project_dagster_university_start/setup.py
- examples/project_du_dbt_starter/setup.py
Required for use on Windows as described here:
* https://github.com/dagster-io/dagster/discussions/26234#discussioncomment-11855658
NOCHANGELOG
> [du] pin kaleido 0.1.*

- CHANGES.md
Summary:
Forgot to update changelog entry in the PR before landing
eyes
NOCHANGELOG
> update changelog with correct logger name

- python_modules/dagster-pipes/dagster_pipes/__init__.py
This PR fixes Pipes log capturing on Databricks. Apparently `sys.__stdout__` and `sys.__stderr__` are the original stdout/stderr files and aren't replaced by `OutStream` in Databricks, unlike `sys.stdout` and `sys.stderr`. 
```
pytest 'python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_pipes.py::test_pipes_client[True-True]'
```
[bug] fixed Dagster Pipes log capturing when running on Databricks
> [pipes] more reliable log capturing

- docs/docs-beta/docusaurus.config.ts
> [docs] update docusaurus title to remove 'Beta'

- docs/docs-beta/docusaurus.config.ts
- docs/docs-beta/src/styles/custom.scss
> [docs] remove announcement bar indicating that site is in preview

- python_modules/libraries/dagster-dlt/dagster_dlt/translator.py
> [2/n][dagster-dlt] Move logic to default fns in DagsterDltTranslator

- python_modules/libraries/dagster-dg/setup.py
This was missing -- just copied the dep from the main dagster package
NOCHANGELOG
> [dagster-dg] Add PyYAML as a dependency

- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInput.tsx
- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInputAutoCompleteResults.tsx
As titled, enter to submit query.
> [Selection input] Enter to submit

- docs/docs-beta/docs/integrations/libraries/looker.md
Fixes API docs link.
Local build is green.
> Fix API docs link in new docs

- .github/workflows/build-docs-revamp.yml
> [docs] prevent docs from deploying on draft PRs

- python_modules/dagster/dagster/_core/execution/stats.py
We want to be able to serialize step stats, which contain the step event status.
BK
> make step event status serializable

- python_modules/libraries/dagster-looker/dagster_looker/lkml/dagster_looker_lkml_translator.py
- python_modules/libraries/dagster-looker/dagster_looker_tests/lkml/test_asset_specs.py
Same as #27140 but for Looker lkml.
> [2/n][dagster-looker] Move logic to default fns in DagsterLookerLkmlTranslator

- python_modules/libraries/dagster-looker/dagster_looker/lkml/dagster_looker_lkml_translator.py
Use `DagsterLookerLkmlTranslator._default_*` fns in `get_asset_spec`. To make sure custom translators are not breaking, we also use the resolve back compat fn.
> [3/n][dagster-looker] Resolve back compat in DagsterLookerLkmlTranslator.get_asset_spec

- docs/docs-beta/src/plugins/scoutos/index.js
> [docs] improve formatting of AI button

- python_modules/dagster/dagster/_generate/download.py
> [project-llm-fine-tune] fix cli generate assertion

- .github/workflows/build-docs-revamp.yml
> [docs] revert change that only builds PR when not draft

- docs/docs-beta/src/theme/DocCard/index.tsx
> [docs] set height to be max of parent for doc cards

- python_modules/dagster/dagster/_core/run_coordinator/queued_run_coordinator.py
- python_modules/dagster/dagster_tests/daemon_tests/test_queued_run_coordinator_daemon.py
> fix queued run coordinator tests to handle different pool granularity

- docs/docs-beta/docusaurus.config.ts
Add tutorials back to top nav of new docs.
Local builld.
> Re-add tutorials section to top nav

- python_modules/libraries/dagster-components/dagster_components/cli/scaffold.py
- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/core/component_scaffolder.py
- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/scaffolder.py
- python_modules/libraries/dagster-components/dagster_components/lib/definitions_component/scaffolder.py
- python_modules/libraries/dagster-components/dagster_components/lib/test/simple_pipes_script_asset.py
Missed renaming this when renaming the equivalent method on Component
NOCHANGELOG
> [components] Rename get_params_schema_type

- docs/docs-beta/docs/integrations/libraries/dbt/dbt-cloud.md
- docs/docs-beta/docs/integrations/libraries/dbt/dbt-core.md
> [docs] fix dbt logos

- docs/docs-beta/vercel.json
Add missing redirects from marketing emails and UI.
> Add missing redirects

- docs/docs-beta/scripts/vercel-validate-redirects.js
> [docs] add script for validating redirects in vercel.json

- python_modules/libraries/dagster-components/dagster_components_tests/utils.py
Update the `generate_component_lib_pyproject_toml` test function to create `pyproject.toml` using our new markers for code location and component lib.
> [components] Update generate_component_lib_pyproject_toml util

- docs/docs-beta/src/plugins/scoutos/index.js
> [docs] update copilot ID

- docs/docs-beta/vercel.json
> [docs] fix 404s

- .github/workflows/build-docs-revamp.yml
Follow up to #27279 -- I think the additional `type`s might do the trick.
> Only run docs build on non-draft PRs

- docs/docs-beta/docs/etl-pipeline-tutorial/automate-your-pipeline.md
- docs/docs-beta/docs/etl-pipeline-tutorial/create-a-sensor-asset.md
- docs/docs-beta/docs/etl-pipeline-tutorial/create-and-materialize-a-downstream-asset.md
- docs/docs-beta/docs/etl-pipeline-tutorial/create-and-materialize-assets.md
- docs/docs-beta/docs/etl-pipeline-tutorial/create-and-materialize-partitioned-asset.md
- docs/docs-beta/docs/etl-pipeline-tutorial/ensure-data-quality-with-asset-checks.md
- docs/docs-beta/docs/etl-pipeline-tutorial/index.md
- docs/docs-beta/docs/etl-pipeline-tutorial/refactor-your-project.md
- docs/docs-beta/docs/guides/monitor/index.md
> Address feedback from new docs rollout

- docs/docs-beta/docs/intro.md
- docs/docs-beta/docusaurus.config.ts
- docs/docs-beta/static/img/getting-started/icon-education.svg
> [docs] Add DU links to landing page

- docs/docs-beta/docs/guides/build/projects/creating-a-new-project.md
Fix note
`yarn start` confirmed on page
> [docs] Fix note in `creating-a-new-project`

- docs/vercel.json
Prevent indexing of legacy docs.
NOCHANGELOG
> [DOC-774][docs-legacy] noindex

- docs/docs-beta/static/robots.txt
- docs/docs-beta/vercel.json
User reported issue with contributing [link](https://github.com/dagster-io/dagster/issues/27344).
Google Search console also found 2 404 links (Airlift related) as well as not having a robots.txt file. 
Added robots.txt file IAW [docusaurus](https://docusaurus.io/docs/seo#robots-file)
> DOC-redirects-and-404

- docs/docs-beta/vercel.json
Added an additional link, to get user reported [issue](https://github.com/dagster-io/dagster/issues/27344) to resolve.
> DOC-add-additional-link

- docs/docs-beta/vercel.json
> [docs] add airlift redirect

- docs/docs-beta/docusaurus.config.ts
- docs/docs-beta/package.json
- docs/docs-beta/yarn.lock
> [DOC-788][docs] add GA4 tag; make algolia and ga4 conditionally configured

- docs/docs-beta/docs/guides/deploy/deployment-options/docker.md
> [docs] Update the dagster docker docs to be up-to-date

- js_modules/dagster-ui/packages/app-oss/src/NUX/CommunityNux.tsx
> [ui] show DU and docs in NUX

- python_modules/dagster/dagster_tests/core_tests/resource_tests/pythonic_resources/test_general_pythonic_resources.py
Guard against regression of #27223
Local run + BK
> Add test to stop a future nested config regression

- docs/docs-beta/docs/api/api-lifecycle.md
> [docs-beta] Remove dead stage in API lifecycle guide

- docs/docs-beta/docs/etl-pipeline-tutorial/create-and-materialize-partitioned-asset.md
> fix: heading number in etl pipeline docs

- docs/docs-beta/docs/etl-pipeline-tutorial/create-a-sensor-asset.md
> fix: sensor name in etl pipeline tutorial

- python_modules/dagster/dagster/_cli/dev.py
> Use TemporaryDirectory instead of TemporaryNamedFile in dagster dev

- docs/docs-beta/docs/dagster-plus/deployment/deployment-types/hybrid/kubernetes/configuration.md
> [docs] list kubernetes configuration

- docs/docs-beta/docs/etl-pipeline-tutorial/index.md
> [docs] add missing script

- CHANGES.md
Add 1.9.11 changelog
Inspection
> add changelog for 1.9.11

- python_modules/libraries/dagster-azure/dagster_azure/adls2/io_manager.py
- python_modules/libraries/dagster-azure/dagster_azure/adls2/resources.py
Adds examples to the ADLS resource api docs. Updates the examples for the ADLS I/O manger examples to use pythonic resources
> fix api docs example for adls resource and i/o manager

- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_type_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Prior to this PR, we were using generated code locations, which scaffold a new venv containing `dagster-components`, for the environment for most tests. When we wanted to test in a non-code-location env we did some hackery.
This PR adds fixtures to generate a generic virtual environment containing `dagster-components` as well as a component library (but non-code-location project). These are more appropriate fixtures to use for commands that don't rely on a code location.
Modified existing unit tests.
> [components] Better-scoped test environments

- examples/docs_beta_snippets/docs_beta_snippets/guides/tutorials/etl_tutorial/etl_tutorial/definitions.py
> [docs] fix typo where passed condition should be when no nulls are counted

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/1-help.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/18-dg-list-component-types.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/7-dg-list-component-types.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/8-dg-list-component-types.txt
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs.py
Adjust the index page so console outputs are a little less wide
> [docs][components][ez] reduce width of cli output for index page

- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_custom_help_format.py
The width of the help output generated by certain tests in `dagster-dg` varied depending on environment. This caused these tests to fail when run locally with `tox` (but oddly not my base env). This PR modifies the tests to ensure a fixed width in all environments.
Ran existing tests in tox, they now pass.
> [components] Standardize terminal width in dagster-dg help output tests (BUILD-646)

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/deployments/6-code-location-pyproject.toml
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/4-pyproject.toml
Updates some `docs_beta_snippets` to fix BK.
> [components] Fix BK: docs_beta_snippets

- python_modules/dagster/dagster/_core/definitions/step_launcher.py
> [docs] update message on superseded step launchers functionality

- docs/docs-beta/docs/integrations/libraries/sling.md
fix typo and added more context
> [DOC] - Fix typo on Sling Page

- docs/docs-beta/CONTRIBUTING.md
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/README.md
Adds a brief section on how to use `CliInvocationExample` to CONTRIBUTING.md
> [docs-beta] Add CliInvocationExample to CONTRIBUTING.md

- js_modules/dagster-ui/packages/ui-core/package.json
- js_modules/dagster-ui/packages/ui-core/src/app/Util.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/useAllAssets.test.tsx
- js_modules/dagster-ui/packages/ui-core/src/nav/__tests__/LeftNavRepositorySection.test.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/HourlyDataCache/HourlyDataCache.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/HourlyDataCache/__tests__/HourlyDataCache.test.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/__tests__/useRunsForTimeline.test.tsx
- js_modules/dagster-ui/packages/ui-core/src/search/__tests__/useIndexedDBCachedQuery.test.tsx
- js_modules/dagster-ui/packages/ui-core/src/search/useIndexedDBCachedQuery.tsx
- js_modules/dagster-ui/packages/ui-core/src/util/__tests__/idb-lru-cache.test.ts
- js_modules/dagster-ui/packages/ui-core/src/util/__tests__/lru-cache.test.ts
- js_modules/dagster-ui/packages/ui-core/src/util/idb-lru-cache.ts
- js_modules/dagster-ui/packages/ui-core/src/util/lru-cache.ts
- js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/__tests__/WorkspaceContext.test.tsx
- js_modules/dagster-ui/yarn.lock
Building our own since `idb-lru-cache` doesnt provide much functionality
existing jest tests for things relying on the utility + new jest tests for the utility
> Remove `idb-lru-cache` dependency

- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionAutoCompleteProvider.tsx
> Don't use `key` as prop name.

- docs/docs-beta/docs/integrations/libraries/dbt/using-dbt-with-dagster/index.md
As title.
Before
After
Docs preview
> [docs-beta] Fix layout in dbt & Dagster guide

- docs/docs-beta/vercel.json
> [docs] redirect non-root paths for docs-preview, and new-docs

- docs/docs-beta/vercel.json
> [docs] include root path in addition to paths for redirects

- .buildkite/dagster-buildkite/dagster_buildkite/utils.py
> [uv] bump pin

- docs/tox.ini
Fix docs build by adding missing dep
Ran `make sphinx-mdx` in docs and it worked
> Fix docs build dataproc

- docs/content/deployment/dagster-instance.mdx
- docs/docs-beta/docs/guides/deploy/dagster-instance-configuration.md
> [docs] fix formatting of tree file structure

- python_modules/libraries/dagster-sdf/dagster_sdf/asset_decorator.py
- python_modules/libraries/dagster-sdf/dagster_sdf/resource.py
- python_modules/libraries/dagster-sdf/dagster_sdf/sdf_workspace.py
decision: experimental (beta) -> ga
reason: dagster-sdf has been stable for quite some time now (over 6 months). The integration would require more docs though.
docs exist: no, we would need at least a guide.
> [integrations-api][ga] dagster-sdf

- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs.py
- examples/docs_beta_snippets/docs_beta_snippets_tests/test_all_files_load.py
- python_modules/dagster/dagster/_cli/workspace/cli_target.py
#27501 introduced a regression in setting the working directory of code pointers correctly for certain entry points-- this fixes it.
Docs beta snippet that was failing now passes.
> [cli-refactor] Fix regression with code pointer dict working directory

- python_modules/libraries/dagster-powerbi/dagster_powerbi/assets.py
- python_modules/libraries/dagster-powerbi/dagster_powerbi/resource.py
reason: We're still working with design partners to improve the integration, but it has been out there for some time, so we should avoid breaking things in patch releases.
> [integrations-api][beta] dagster-powerbi

- docs/content/deployment/dagster-instance.mdx
As title, fixes failing build https://buildkite.com/dagster/dagster-dagster/builds/110529
bk
> [docs] Fix formatting in dagster-instance.mdx

- python_modules/libraries/dagster-tableau/dagster_tableau/assets.py
- python_modules/libraries/dagster-tableau/dagster_tableau/resources.py
reason: We're still working with design partners to improve the integration, but it has been out there for some time, so we should avoid breaking things in patch releases.
> [integrations-api][beta] dagster-tableau

- python_modules/libraries/dagster-looker/dagster_looker/api/assets.py
- python_modules/libraries/dagster-looker/dagster_looker/api/resource.py
- python_modules/libraries/dagster-looker/dagster_looker/lkml/asset_specs.py
- python_modules/libraries/dagster-looker/dagster_looker/lkml/dagster_looker_lkml_translator.py
reason: We're still working with design partners to improve the integration, but it has been out there for some time, so we should avoid breaking things in patch releases.
> [integrations-api][beta] dagster-looker

- python_modules/dagster/dagster/_cli/definitions.py
Reduce the default amount of logging for `dagster definitions validate` by
- Clearing the root logger's handlers, if any are set (right now, importing `dbt` in user code sets a handler)
- Captures warnings, meaning any error message from a code location failing to load isn't directly printed but instead piped through to the `validate` code.
```bash
$ dagster definitions validate
2025-02-04 14:41:18 -0800 - dagster - INFO - Validation successful for code location dagster_test.toys.repo.
2025-02-04 14:41:18 -0800 - dagster - INFO - All code locations passed validation.
```
```bash
$ dagster definitions validate
2025-02-04 14:41:04 -0800 - dagster - ERROR - Validation failed for code location dagster_test.toys.repo:
dagster._core.errors.DagsterInvalidDefinitionError: Input asset …
```
> [dagster definitions validate] Minimize validate logging

- python_modules/libraries/dagster-sigma/dagster_sigma/assets.py
- python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
reason: We're still working with design partners to improve the integration, but it has been out there for some time, so we should avoid breaking things in patch releases.
> [integrations-api][beta] dagster-sigma

- python_modules/libraries/dagster-pandas/dagster_pandas/constraints.py
- python_modules/libraries/dagster-pandas/dagster_pandas/data_frame.py
- python_modules/libraries/dagster-pandas/dagster_pandas/validation.py
reason: decorator was missing. It has been out there for quite some time, but is not mature enough for GA.
docs exist: yes, but beta flag/note should be added
> [integrations-api][beta] dagster-pandas

- python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/glue.py
decision: experimental -> ga
reason: this pipes client has been around for quite some time now. It is well documented and adopted.
> [integrations-api][ga] PipesGlueClient in dagster-aws

- python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/emr.py
- python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/emr_serverless.py
- python_modules/libraries/dagster-dbt/dagster_dbt/cloud/ops.py
decision: experimental -> ga
reason: this pipes client has been around for quite some time now. It is well documented and adopted.
> [integrations-api][ga] PipesEMRClient in dagster-aws

- pyright/alt-1/requirements-pinned.txt
- pyright/master/requirements-pinned.txt
I was unable to rebuild_pyright due to some conflict with `triton` pin so rebuild 
bk
> rebuild pyright pins

- docs/dagster-university/pages/dagster-dbt/lesson-1/4-project-preview.md
- docs/dagster-university/pages/dagster-essentials/lesson-1/project-preview.md
Update project links after reorganization of Dagster U
https://github.com/dagster-io/project-dagster-university/pull/47
> [du] Update Dagster U project links

- docs/docs-beta/docusaurus.config.ts
- docs/docs-beta/src/plugins/segment/index.js
> [docs] add segment to docs
