js_modules/dagster-ui/packages/ui-core/src/graph/KindTags.tsx
python_modules/dagster/dagster/_core/definitions/op_definition.py
python_modules/dagster/dagster/_core/definitions/tags/__init__.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py
python_modules/dagster/dagster_tests/general_tests/compat_tests/test_back_compat.py

Removes the storage kind tag set, since storage kinds have been sundowned, and also removes the very-legacy op compute kind tag remapping logic.

Various 1.9 kind cleanups

---

python_modules/libraries/dagster-powerbi/dagster_powerbi/resource.py

Updates the `load_powerbi_asset_specs` function as experimental for 1.9.

[dagster-powerbi] Mark PowerBI loading method as experimental

---

python_modules/dagster/dagster/_core/storage/runs/migration.py

Updates the migration for setting the `backfill_id` column of the `runs` table to use the `run_tags` table rather than iterate through each run
before this change, running the migration on my local db took about a minute and a half, after it took about 5 seconds.

do runs table backfill id migration by run tags table

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_cli_event.py
python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_cli_invocation.py
python_modules/libraries/dagster-dbt/dagster_dbt/core/resource.py
python_modules/libraries/dagster-sdf/dagster_sdf/sdf_cli_event.py
python_modules/libraries/dagster-sdf/dagster_sdf/sdf_cli_invocation.py
python_modules/libraries/dagster-sdf/dagster_sdf/sdf_information_schema.py

https://github.com/dagster-io/dagster/pull/25541 makes `AssetExecutionContext` not a subclass of `OpExecutionContext`. This PR is the changes to the sdf integration required to make that change. 
Includes updating type signatures to allow for `AssetExecutionContext`, since previously, type annotation of `OpExecutionContext` would have allowed `AssetExecutionContext` to be passed
For any `context` calls that needed to be updated, I've added a comment explaining the change 
existing tests

[sdf] modify context type signatures and usage for making AssetExecutionContext a standalone class

---

python_modules/libraries/dagster-celery/example/example_code/definitions.py
python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_cli_event.py
python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_cli_invocation.py
python_modules/libraries/dagster-dbt/dagster_dbt/core/resource.py
python_modules/libraries/dagster-sdf/dagster_sdf/sdf_cli_event.py
python_modules/libraries/dagster-sdf/dagster_sdf/sdf_cli_invocation.py
python_modules/libraries/dagster-sdf/dagster_sdf/sdf_information_schema.py

https://github.com/dagster-io/dagster/pull/25541 makes `AssetExecutionContext` not a subclass of `OpExecutionContext`. This PR updates an example to use the `AssetExecutionContext` type annotation
existing tests

[celery] modify context type signatures and usage for making AssetExecutionContext a standalone class

---

python_modules/dagster/dagster/_core/definitions/source_asset.py
python_modules/dagster/dagster/_core/execution/context/asset_execution_context.py
python_modules/dagster/dagster/_core/execution/context/op_execution_context.py
python_modules/dagster/dagster/_core/execution/plan/compute.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_decorators.py
python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_execution_context.py
python_modules/dagster/dagster_tests/core_tests/execution_tests/test_context.py
python_modules/libraries/dagster-celery/example/example_code/definitions.py
python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_cli_event.py
python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_cli_invocation.py
python_modules/libraries/dagster-dbt/dagster_dbt/core/resource.py
python_modules/libraries/dagster-sdf/dagster_sdf/sdf_cli_event.py
python_modules/libraries/dagster-sdf/dagster_sdf/sdf_cli_invocation.py
python_modules/libraries/dagster-sdf/dagster_sdf/sdf_information_schema.py

Now that all of the libraries have been updated to support `AssetExecutionContext`, we can make `AssetExecutionContext` not a subclass of `OpExecutionContext`
`AssetExecutionContext` is marked to be made a standalone class (ie not a subclass of `OpExecutionContext`) in 1.9. These are the changes in the core dagster module that are required to make that happen. It's just removing the metaclass that enables the `isinstance` check to raise a deprecation warning, and removing the actual inheritance. 
I also delete the tests that ensure `OpExecutionContext` and `AssetExecutionContext` implement the same methods since we don't need/want to enforce that now that they are separate classes. 
existing tests
`AssetExecutionContext` is no longer a subclass of `OpExecutionContext`. At this release, …

[core] modify context type signatures and usage for making AssetExecutionContext a standalone class

---

python_modules/dagster/dagster/_cli/project.py
python_modules/dagster/dagster/_generate/__init__.py
python_modules/dagster/dagster/_generate/download.py
python_modules/dagster/dagster/_generate/generate.py
python_modules/dagster/dagster/_generate/templates/CODE_LOCATION_NAME_PLACEHOLDER/pyproject.toml.tmpl
python_modules/dagster/dagster/_generate/templates/CODE_LOCATION_NAME_PLACEHOLDER/setup.cfg.tmpl
python_modules/dagster/dagster/_generate/templates/PROJECT_NAME_PLACEHOLDER/PROJECT_NAME_PLACEHOLDER/definitions.py.jinja
python_modules/dagster/dagster/_generate/templates/PROJECT_NAME_PLACEHOLDER/README.md.jinja
python_modules/dagster/dagster/_generate/templates/PROJECT_NAME_PLACEHOLDER/pyproject.toml.jinja
python_modules/dagster/dagster/_generate/templates/PROJECT_NAME_PLACEHOLDER/setup.cfg.jinja
python_modules/dagster/dagster/_generate/templates/PROJECT_NAME_PLACEHOLDER/setup.py.jinja
python_modules/dagster/dagster_tests/cli_tests/test_project_commands.py
scripts/install_dev_python_modules.py

PEP 621 (Nov 2020) introduced pyproject.toml.
Setuptools is fully compatible with pyroject. 
All the config in setup.cfg and setup.py will also be in pyproject.toml project template if this is merged. 
Minimalist config to make adopting dagster easy.
See #25244 
Last time I tried the run the test suite it failed because my macbook has an intel chipset.
(CLI) 
`dagster project scaffold`: Add option to create dagster projects from templates with excluded files/filepaths
`dagster project scaffold-code-location`: Refactored to leverage scaffold command with excludes flag. Deprecated.

feat(cli.project): enable optional minimalist configuration in templates

---

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py

Missed in https://github.com/dagster-io/dagster/pull/25240, we are now failing when an `AssetKey` is passed to `deps`. This used to work since you could iterate over it and get back just the `path` which is coerces back to the same `AssetKey`. 
Our callsites which exhibit this problem here https://github.com/dagster-io/dagster/pull/25462/files
added test

AssetKey as deps backcompat

---

python_modules/dagster/dagster/_core/definitions/repository_definition/repository_data_builder.py
python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py

Custom `PartitionsDefinition` subclasses were deprecated for conversion to error in 1.9. This PR implements the change.
Updated existing test.
Passing a custom `PartitionsDefinition` subclass into a `Definitions` object now issues an error instead of a deprecation warning.

Convert deprecation to error for custom PartitionsDefinition subclass

---

python_modules/libraries/dagster-tableau/dagster_tableau/resources.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_asset_specs.py

When we use the Tableau resource at load time to load asset specs, we need to manually open a context to ensure that env vars are resolved.

Process Tableau workspace resources when loading specs

---

examples/deploy_docker/docker-compose.yml

Docker Compose example deployment for Dagster throws errors on initialisation because the webserver and daemon do not wait for the postgreSQL database to be ready before attempting to connect.
Added healthcheck to postgresql container to fix this issue.
Works on my machine and a new EC2 instance with relevant bits installed.

Fix: Docker Compose Example

---

python_modules/libraries/dagster-snowflake/dagster_snowflake/resources.py
python_modules/libraries/dagster-snowflake/dagster_snowflake_tests/test_resources.py

This PR adds an optional argument `ignore_missing_tables: Optional[bool] = False` to `dagster_snowflake.fetch_last_updated_timestamps`. When true, this argument will not raise an error when a table is not found in Snowflake. Instead, it will just continue and exclude the table from the resulting freshness map.
This is useful when you deploy a dagster project to multiple environments, where your development environment may not have all tables available. We use this function to generate observation events for source tables, and this allows us to generate observations for the tables that do exist, but ignore tables that don't.
Linked issue: https://github.com/dagster-io/dagster/issues/24245
Unit test is included.
> `dagster_snowflake.fetch_last_updated_timestamps` now supports ignoring …

[snowflake] Support ignoring missing tables when using `fetch_last_updated_timestamps`

---

python_modules/dagster/dagster/_scheduler/scheduler.py

In case the scheduler daemon has a stale version of the workspace when the schedule is turned on, we do not want to delete.
BK (internal)

fix race condition for deleting state

---

docs/docs-beta/docs/dagster-plus/deployment/serverless.md
docs/docs-beta/docs/dagster-plus/deployment/serverless/runtime-environment.md
docs/docs-beta/docs/dagster-plus/deployment/serverless/security.md

- This fixes the broken Docusaurus build due to malformed anchor tags

[docs-beta] fix broken build due to typo in anchor

---

python_modules/libraries/dagster-snowflake/dagster_snowflake_tests/test_resources.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_asset_specs.py

This change fix the `test_fetch_last_updated_timestamps_missing_table` function in the Snowflake resource tests.

fix(dagster-snowflake): fix test_fetch_last_updated_timestamps_missing_table

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/__init__.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_load_from_instance.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/utils.py

Our BI integrations (Power BI, Sigma, Tableau, Looker) and DBT integration use a translator pattern to allow users to customize the assets they load from the external tool. We want to do the same for Fivetran.
[Fivetran] Introduced `DagsterFivetranTranslator` to customize assets loaded from Fivetran.

[PLUS-1409] Introduce translator pattern for Fivetran

---

docs/content/_navigation.json

- Add links to the integration guides underneath the "Integrations" heading
- Add missing link to Sigma API docs

add BI integrations to docs navigation

---

js_modules/dagster-ui/packages/ui-core/src/app/ContentRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationDefinitionsRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationOverviewRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationTabs.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/code-location/findRepositoryInLocation.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/CodeLocationRowSet.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedCodeLocationRow.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceRoot.tsx

When a code location is in an error state, link to its permalink so that metadata is available.
The current app behavior is to show an empty state when attempting to load an unloadable code location. This change replaces the empty state with the code location overview page.
If the code location has no repositories available (because it's in an error state), disable the "Definitions" tab.
https://github.com/user-attachments/assets/714141b6-ac88-485e-bad2-7764482f0194
Load the app locally, cause a Python error in `toys`, reload the code location. Verify that the code location goes into an errored state but is linked from the Code locations page.
Click the link, verify that I arrive at the code location permalink, with metadata and the code location error available.

[ui] Handle failure in code location permalink

---

docs/docs-beta/sidebars.ts

I forgot to add managing concurrency to the sidebar. In the old docs this was in an "Advanced" section. I think it might make sense under "Build/Configure", but am open to moving it to a different or even a new section!

add managing concurrency to sidebar

---

docs/content/dagster-plus/managing-deployments/alerts/slack.mdx

1. Fixes name of Slack bot in our docs to match the name still used in Slack app
2. Elaborates instructions for adding the bot to channels
👀

[docs] fix and extend instructions for adding Dagster Slack app to channels

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
python_modules/libraries/dagster-ge/setup.py

Second order dependencies prevent `dagster-ge` from being supported on 3.9.
[dagster-ge] The minimum Python version for `dagster-ge` is now 3.10.

[dagster-ge] Drop python 3.9 support

---

docs/content/integrations/looker.mdx
docs/sphinx/sections/api/apidocs/libraries/dagster-looker.rst
examples/docs_snippets/docs_snippets/integrations/looker/customize-looker-assets.py
examples/docs_snippets/docs_snippets/integrations/looker/materializing-looker-pdts.py
examples/docs_snippets/docs_snippets/integrations/looker/representing-looker-assets.py

Updates our Looker docs to incorporate the new specs-building pattern, norm of passing the resource to `Definitions`, and the new pattern for building executable asset definitions.

[dagster-looker] Update Looker documentation to showcase new API patterns

---

python_modules/dagster/dagster/_cli/definitions.py
python_modules/dagster/dagster_tests/cli_tests/command_tests/definitions_command_projects/valid_project/valid_project/gated_definitions.py
python_modules/dagster/dagster_tests/cli_tests/command_tests/test_definitions_validate_command.py

Our design partners would like to have more control on the code and its behavior when in validation mode: different credentials, etc.
This PR updates `dagster definitions validate` to set the env var `DAGSTER_IS_DEFS_VALIDATION_CLI` when the command is running , like we do so `DAGSTER_IS_DEV_CLI` and `dagster dev`. This will allow users to control the code using the env var like:
```
import os
if os.getenv("DAGSTER_IS_DEFS_VALIDATION_CLI"):
...
```
Additional unit test

[cli] Set `DAGSTER_IS_DEFS_VALIDATION_CLI` in `dagster definitions validate`

---

python_modules/dagster/dagster/_core/definitions/decorators/schedule_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/sensor_decorator.py
python_modules/dagster/dagster/_core/definitions/schedule_definition.py
python_modules/dagster/dagster/_core/definitions/sensor_definition.py

For 1.9, `target` on schedules/sensors is no longer experimental.

[jobless-automation] Unexperimentalize `target`

---

python_modules/dagster/dagster/_core/definitions/asset_job.py
python_modules/dagster/dagster/_core/definitions/repository_definition/repository_data_builder.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/test_repository_snap.py

`ResourceSnap` has a list of jobs using a resource that gets shown on the Resource Detail page in the UI. Anonymous asset jobs created by passing an `AssetSelection` to the `target` parameter of a schedule/sensor were leaking through here.
This PR filters out these jobs when setting the list of jobs, the same way the base asset job is filtered out.
Modified existing unit tests.

[jobless-automation] Exclude anonymous jobs from ResourceSnap job_ops_using list

---

js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/AutomaterializeMiddlePanelWithData.tsx

This is a small fix for a bug on the Asset > Automations page.
If no runs were requested, we were loading the table anyway with the Runs filter `{runIds: []}`.  The backend (in `SqlRunStorage._add_filters_to_query`), sees that value as falsy and does not add a filter, returning all runs instead of no runs.
I think a backend change would likely also be helpful, but it seems like it'd need to be made carefully. In the meantime we should short-circuit loading of the table entirely, since it's guaranteed to return no runs.
I tested this manually on the Asset > Automations page and viewed the new empty state. 
I also looked through the other RunsFeed callsites and I don't believe there are any other places where an empty query is likely.

[ui] Skip runs feed load for automation ticks with no requested run IDs

---

python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py

broken in https://github.com/dagster-io/dagster/pull/25580 because not tested, discovered in manual QA 
added test

[graphql] handle asset key that does not exist in assetNodes

---

docs/content/integrations/looker.mdx
docs/content/integrations/powerbi.mdx
docs/content/integrations/sigma.mdx
docs/content/integrations/tableau.mdx
examples/docs_snippets/docs_snippets/integrations/looker/customize-looker-assets.py
examples/docs_snippets/docs_snippets/integrations/power-bi/customize-power-bi-asset-defs.py
examples/docs_snippets/docs_snippets/integrations/sigma/customize-sigma-asset-defs.py
examples/docs_snippets/docs_snippets/integrations/tableau/customize-tableau-asset-defs.py

Fixes the custom translator examples for all four BI integrations - Looker, Power BI, Sigma and Tableau. Previous examples raised that error:
`dagster._core.errors.DagsterInvalidDefinitionError: Invalid owner 'my_team' for asset 'AssetKey(['My_Workbook'])'. Owner must be an email address or a team name prefixed with 'team:'.`
Also fixes comments and the method that is overloaded for Sigma.

[docs] Fix custom owners examples in BI integrations docs

---

python_modules/libraries/dagster-looker/dagster_looker/api/assets.py
python_modules/libraries/dagster-looker/dagster_looker/api/dagster_looker_api_translator.py
python_modules/libraries/dagster-looker/dagster_looker/api/resource.py
python_modules/libraries/dagster-looker/dagster_looker_tests/api/mock_looker_data.py
python_modules/libraries/dagster-looker/dagster_looker_tests/api/test_build_defs.py

Attaches new metadata to point to a Looker dashboard/explore's URL, as well as fetching user emails for dashboards and attaching those as owners.
New unit test.
> [dagster-looker] Looker assets now by default have owner and URL metadata.

[dagster-looker] Attach URL metadata, owners to dashboards, explores

---

examples/experimental/dagster-airlift/dagster_airlift/core/airflow_instance.py
examples/experimental/dagster-airlift/dagster_airlift/test/shared_fixtures.py

For some reason kitchen sink dags take extra long to load on 2.10.2. For now, just going to wait extra long on 3.12 (the tests that use 2.10.2)
Existing tests actually pass on 3.12 now

[dagster-airlift] Fix kitchen sink test on 3.12

---

js_modules/dagster-ui/packages/ui-core/src/automation/VirtualizedAutomationScheduleRow.tsx
js_modules/dagster-ui/packages/ui-core/src/automation/VirtualizedAutomationSensorRow.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/VirtualizedInstanceConcurrencyTable.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillRow.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedJobRow.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedScheduleRow.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedSensorRow.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedWorkspaceTable.tsx

Context: https://dagsterlabs.slack.com/archives/C04J8BRN9ST/p1730307470251059?thread_ts=1730304382.266269&cid=C04J8BRN9ST
`useDelayedRowQuery` doesn't cancel inflight queries when you navigate away which seems to be causing queueing somewhere (unclear where it's coming from, maybe apollo, maybe chrome, maybe the server???).
app proxy to canary-test-1
Navigate to automations, then navigate to a specific sensor while queries are still inflight

[perf] Kill `useDelayedRowQuery`

---

js_modules/dagster-ui/packages/ui-core/src/instance/InstanceBackfills.tsx
js_modules/dagster-ui/packages/ui-core/src/overview/OverviewRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/overview/OverviewTabs.tsx

Keeps the backfill page for everyone regardless of what version of the runs feed they are using. We have a banner explaining that the backfills will be moving and linking to the Runs page 
The experience is a bit odd if they have the legacy runs page enabled because the link to the runs page does not include backfills. I'm not quite sure what to do about this, but want to start the review process while we figure it out
An alternative is to still hide the backfill page if the new runs feed is being used, and add a banner to the Overview page that says "backfills have moved to the Runs page, or you can revert to the old behavior"
👀

bring backfill page back and add banner

---

js_modules/dagster-ui/packages/ui-core/src/runs/__tests__/useRunsForTimeline.test.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/useRunsForTimeline.tsx

Minor, but for consistency we should grab all in progress runs.  Currently, we ignore `STARTING` state, but that should be included.
Inspection

adjust the timeline runs status filter to match all in progress runs

---

docs/content/integrations/tableau.mdx
docs/sphinx/sections/api/apidocs/libraries/dagster-tableau.rst
examples/docs_snippets/docs_snippets/integrations/tableau/add-tableau-data-quality-warning.py
examples/docs_snippets/docs_snippets/integrations/tableau/refresh-and-materialize-tableau-assets.py
python_modules/libraries/dagster-tableau/dagster_tableau/__init__.py
python_modules/libraries/dagster-tableau/dagster_tableau/assets.py
python_modules/libraries/dagster-tableau/dagster_tableau/resources.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_reconstruction.py

Updates fn name to `build_tableau_materializable_asset_definitions` to be consistent with Dagster external vs materializable assets.
Subsequent PR will add an asset spec parser function that users could use to split their asset specs in external and materializable asset specs - the goal is to make the Tableau boilerplate more elegant and easy to implement. 
Updated tests

[dagster-tableau] Rename Tableau asset builder fn

---

.buildkite/dagster-buildkite/dagster_buildkite/package_spec.py
.buildkite/dagster-buildkite/dagster_buildkite/pipelines/dagster_oss_nightly_pipeline.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
.buildkite/dagster-buildkite/dagster_buildkite/utils.py
examples/experimental/dagster-dlift/dagster_dlift/cloud_instance.py
examples/experimental/dagster-dlift/dagster_dlift/gql_queries.py
examples/experimental/dagster-dlift/dagster_dlift/test/instance_fake.py
examples/experimental/dagster-dlift/dagster_dlift/test/utils.py
examples/experimental/dagster-dlift/dagster_dlift_tests/test_instance.py
examples/experimental/dagster-dlift/dagster_dlift_tests/test_test_utils.py
examples/experimental/dagster-dlift/kitchen-sink/.gitignore
examples/experimental/dagster-dlift/kitchen-sink/Makefile
examples/experimental/dagster-dlift/kitchen-sink/README.md
examples/experimental/dagster-dlift/kitchen-sink/conftest.py
examples/experimental/dagster-dlift/kitchen-sink/dlift_kitchen_sink/instance.py
examples/experimental/dagster-dlift/kitchen-sink/dlift_kitchen_sink_tests/test_instance_from_env.py
examples/experimental/dagster-dlift/kitchen-sink/pyproject.toml
examples/experimental/dagster-dlift/kitchen-sink/setup.py
examples/experimental/dagster-dlift/kitchen-sink/tox.ini

- Scaffold a live testing environment for dlift. 
- Make live tests run on any commit with [dagster-dlift] in the message, and also on the nightly OSS build.
- Introduce an "instance" for interacting with the dbt cloud rest API.
- Introduce an "instance fake" for spec-ing out fake results from the rest API to be used in unit tests.
- All the testing I added, some tests for the testing utils as well.

[dagster-dlift] scaffold testing environment

---

python_modules/libraries/dagster-tableau/dagster_tableau/__init__.py
python_modules/libraries/dagster-tableau/dagster_tableau/asset_utils.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_reconstruction.py

Adds `parse_tableau_external_and_materializable_asset_specs` as an helper function, to make it easier for users to parse external and materializable asset specs for Tableau.
Updated boilerplate to build materializable asset definitions:
```python
tableau_specs = load_tableau_asset_specs(
workspace=tableau_workspace,
)
external_asset_specs, materializable_asset_specs = (
parse_tableau_external_and_materializable_asset_specs(tableau_specs)
)
defs = dg.Definitions(
assets=[
build_tableau_materializable_assets_definition(
resource_key="tableau",
specs=materializable_asset_specs,
refreshable_workbook_ids=["b75fc023-a7ca-4115-857b-4342028640d0"],
),
*external_asset_specs,
],
resources={"tableau": tableau_workspace},
)
```
Updated tests
[dagster-tableau] the helper function …

[dagster-tableau] Add helper fn to parse Tableau asset specs

---

examples/experimental/dagster-dlift/dagster_dlift/cloud_instance.py
examples/experimental/dagster-dlift/dagster_dlift/gql_queries.py
examples/experimental/dagster-dlift/dagster_dlift/test/instance_fake.py
examples/experimental/dagster-dlift/dagster_dlift_tests/test_instance.py
examples/experimental/dagster-dlift/kitchen-sink/dlift_kitchen_sink/constants.py
examples/experimental/dagster-dlift/kitchen-sink/dlift_kitchen_sink_tests/test_instance_from_env.py
examples/experimental/dagster-dlift/kitchen-sink/dlift_kitchen_sink_tests/test_instance_methods.py

Add method to retrieve models from the rest API. 
Added both a live test and a unit test.

[dagster-dlift] get_models

---

python_modules/dagster-graphql/dagster_graphql/implementation/execution/__init__.py

Fix the asset wipe mutation for dynamically partitioned assets.
Will add test in a follow up PR.
Fixes an issue where wiping a dynamically partitioned asset causes an error.

Fix asset wipe mutation with missing dynamic partitions store

---

docs/content/integrations/looker.mdx

A duplicated `</details>` closing tag was added by mistake in #25526, resulting in the Looker docs page returning an HTTP 404 error, see [here](https://dagster-docs-52e9achy6-elementl.vercel.app/integrations/looker).
This PR fixes this by removing the duplicated closing tag.
The main problem here is that the page disappeared silently. My understanding is that the compilation of this page failed because of the duplicated tag, but that was not flagged when deploying the preview.
Docs preview, the [page is back](https://maxime-fix-looker-docs-404.dagster.dagster-docs.io/integrations/looker)

[dagster-looker] Remove duplicated closing tag to fix Looker docs

---

examples/experimental/dagster-dlift/dagster_dlift/loader.py
examples/experimental/dagster-dlift/dagster_dlift/project.py
examples/experimental/dagster-dlift/dagster_dlift/translator.py
examples/experimental/dagster-dlift/dagster_dlift_tests/test_loader.py

Introduce a state loader for dlift. As mentioned in the previous PR, this one doesn't implement build_defs and instead uses the fetched state directly.
New test for loader.

[dagster-dlift] defs loader

---

docs/content/guides/migrations/from-step-launchers-to-pipes.mdx
docs/content/integrations/spark.mdx

[docs] add references to StepLauncher supersession announcement

---

python_modules/libraries/dagster-polars/dagster_polars/io_managers/__init__.py

Addressing #25705
Created a new virtual environment in which I installed the dagster-polars package from the local source. Then created a script which imported dagster_polars, reproducing the ImportError. Then I added the exception for dagster-polars[gcp], which allowed the package to import successfully.
> Preventing dagster-polars from raising ImportError when bigquery libraries are not installed

[dagster-polars] Preventing import errors when users don't have gcp modules installed

---

js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/filterAssetDefinition.test.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/useAssetDefinitionFilterState.oss.tsx

As titled https://linear.app/dagster-labs/issue/FE-658/make-client-side-filtering-case-insensitive
[ui] Filtering on owners/groups/tags is now case-insensitive.

Make filtering case insensitive

---

js_modules/dagster-ui/packages/ui-core/src/runs/RunRoot.tsx

as titled
[ui] The Run page now displays the partition(s) a run was for.

Display partition id in run view

---

js_modules/dagster-ui/packages/ui-core/src/assets/useAssetDefinitionFilterState.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedAssetRow.tsx

As titled
I clicked on a folder link and saw the filters persist to the new page
[ui] Filters in the asset catalog now persist when navigating subdirectories.

Make applied filters persist when navigating to catalog directories

---

js_modules/dagster-ui/packages/ui-core/package.json
js_modules/dagster-ui/packages/ui-core/src/assets/OverdueTag.tsx
js_modules/dagster-ui/packages/ui-core/src/nav/LeftNavItem.tsx
js_modules/dagster-ui/packages/ui-core/src/nav/ScheduleAndSensorDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/nav/ScheduleOrSensorTag.tsx
js_modules/dagster-ui/packages/ui-core/src/schedules/CronTag.tsx
js_modules/dagster-ui/packages/ui-core/src/schedules/ScheduleDetails.tsx
js_modules/dagster-ui/packages/ui-core/src/schedules/__tests__/hourOffsetFromUTC.test.ts
js_modules/dagster-ui/packages/ui-core/src/schedules/__tests__/humanCronString.test.ts
js_modules/dagster-ui/packages/ui-core/src/schedules/hourOffsetFromUTC.tsx
js_modules/dagster-ui/packages/ui-core/src/schedules/humanCronString.ts
js_modules/dagster-ui/yarn.lock

Modify the tooltip on the cron tag for schedules to display the human-readable cron value with the user's timezone setting. This should hopefully make it a bit easier to compare the cron value with recent run timing.
Note that this change is not perfect due to a bug in cronstrue. If the timezone offset on a daily/weekly/etc. cron. value would cause the day or date value to go up or down by one, the day/date does not always shift correctly. I added a test to indicate this bug, and cronstrue gets a fix and we update to use it, we'll see the test fail.
The question is whether this bug is important or confusing enough to block the change.
PST execution, CST for user:
PST execution, Adelaide for user:
Note the date bug below. This schedule should run at midnight PST on day 1 of the month PST, …

[ui] Use TZ offset to display cron string for user timezone

---

python_modules/dagster-graphql/dagster_graphql/implementation/utils.py
python_modules/dagster/dagster/_core/definitions/asset_selection.py
python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
python_modules/dagster/dagster/_core/execution/asset_backfill.py
python_modules/dagster/dagster/_core/selector/subset_selector.py

makes a few changes to facilitate loading only the relevant nodes instead of the whole graph to resolve information about an asset backfill 

[asset backfill] tweaks to avoid loading full graph

---

python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_decorators.py
python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_check_decorator.py

This makes sure the `@asset_check` function docstring is used as description if the `description` parameter is not given. This makes it consistent with the behavior of `@asset`
Closes https://github.com/dagster-io/dagster/issues/23048
Added unit tests. Also added similar tests for the `@asset` decorator

Use asset check docstring as description

---

python_modules/dagster/dagster/_core/remote_representation/grpc_server_registry.py
python_modules/dagster/dagster/_core/remote_representation/origin.py
python_modules/dagster/dagster/_core/workspace/context.py
python_modules/dagster/dagster/_daemon/controller.py
python_modules/dagster/dagster/_grpc/proxy_server.py
python_modules/dagster/dagster/_grpc/server.py

Adds a segment to the gRPC timeout error explaining where the value is sourced from. Since this value propagates differently in different scenarios, the actual explanatory message is passed down the callstack.

Instruct users how to configure gRPC timeout

---

js_modules/dagster-ui/packages/ui-core/src/runs/useCursorAccumulatedQuery.tsx

There was a report during dogfooding that the Coordinator logs tab does not transition from loading to empty for old backfills like this one: https://dogfood-test-1.dogfood.dagster.cloud/prod/runs/b/zjexmmzx?tab=logs
This UI actually implements both loading and empty states, but the empty state wasn't reached because `useCursorAccumulatedQuery` uses an `AccumulatingDataFetcher`, and the fetcher's `.fetch()` method never called `onData` if the first page of results was empty.  I think it should so that consumers have a way to transition from loading > empty.
I tested these changes on the coordintor logs page viewing the backfill linked above. At the moment, this is the only place `AccumulatingDataFetcher` or `useCursorAccumulatedQuery` are used. It looks like they still need tests, but …

[ui] Fix backfill coordinator logs not transitioning from loading => empty

---

js_modules/dagster-ui/packages/ui-core/src/assets/RecentUpdatesTimeline.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/clipEventsToSharedMinimumTime.test.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/clipEventsToSharedMinimumTime.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/groupByPartition.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/usePaginatedAssetEvents.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/useRecentAssetEvents.tsx

The previous fix I wrote for https://linear.app/dagster-labs/issue/FE-387/assets-with-both-materializations-and-observations-can-have-plot in #25416 put the "clipping to a shared time range" logic in `useGroupedEvents`, which had an unintended side-effect I noticed this morning. 
This code wasn't verifying that one of the datasets contained `limit` items before clipping them both to the shared timerange. This meant that if you had an asset with a history of materializations, and then emitted an observation for it, the older materializations would disappear from the asset plots. More concerningly they also disappeared from the Asset > Evetns page, which was using `useGroupedEvents` because it can perform grouping on super old non-SDAs that don't have a defined parititon space.
I moved the …

[ui] Fix events missing on Asset > Events when mat + observations both present

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py

BK was unhappy with non-alphanumeric chars in the release branch step names

[bk] Remove spaces from dlift package spec names

---

python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/test_launching.py

It is currently very difficult to get cost and performance tracking information for specific jobs and runs without doing a bunch of kung-fu with `run_task_kwargs` and job definitions. This PR allows tags set on a Dagster run to be selectively propagated to the ECS task used to carry out the run, to simplify cost tracking and enable tracking based on tags that are only available at runtime such as partition key and job name.
Added a set of unit tests for the propagate_tags functionality. Booted up a Dagster environment and launched runs using different `propagate_tags` configurations and checked that the ECS tasks created had the correct tags applied.

[dagster-aws] Adding EcsRunLauncher config option for propagating tags from Dagster run to ECS task

---

python_modules/dagster/dagster/_core/storage/sql.py

Revert partially the change to check alembic revision within the stamp call from https://github.com/dagster-io/dagster/pull/25740/
BK

partial revert - stop threaded check of alembic version

---

python_modules/libraries/dagster-powerbi/dagster_powerbi/translator.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/conftest.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_translator.py

Pull owner metadata as well as columnar metadata from PowerBI, if available.
Update unit tests.
> [dagster-powerbi] When using a full workspace scan, owner and column metadata is now attached automatically to assets.

[dagster-powerbi] Pull owners, additional asset metadata

---

pyright/master/requirements.txt
python_modules/dagster/setup.py

Move types-sqlalchemy into managed pyright environment
If you're using sqlalchemy 2, then this type package is no longer correctly representing the sqlalchemy types. This change moves the pinned package into the managed pyright environment instead of being in the pyright extra.
make pyright
The `types-sqlalchemy` package is no longer included in the `dagster[pyright]` extra package.

Move types-sqlalchemy to requirements.txt

---

.buildkite/dagster-buildkite/dagster_buildkite/utils.py
examples/with_airflow/tox.ini
python_modules/libraries/dagster-airflow/dagster_airflow_tests/marks.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_dagster_job_factory/test_dag_run_conf.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_dagster_job_factory/test_load_assets.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_dagster_job_factory/test_load_assets_airflow_2.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_dagster_job_factory/test_load_dag_bag.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_dagster_job_factory/test_load_dag_bag_airflow_2.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_dagster_operator.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_dagster_pipeline_factory/test_dependency_structure_translation.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_dagster_pipeline_factory/test_load_connections.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_dagster_pipeline_factory/test_load_dag_bag.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_dagster_pipeline_factory/test_load_dag_bag_airflow_2.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_dagster_pipeline_factory/test_op_execution.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_dagster_pipeline_factory/test_tags.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_persistent_db/test_persistent_airflow_2_db.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_persistent_db/test_persistent_airflow_db.py
python_modules/libraries/dagster-airflow/setup.py
python_modules/libraries/dagster-airflow/tox.ini

* bump `uv` pin
* enable `uv` for `airflow` `tox` setups
* remove need to import `dagster_airflow_tests` by directly using `pytest.mark`
* pin `pendulum` next to existing "temporary" `airflow` pin to < 2.8

uv bump and use on airflow

---

examples/experimental/dagster-airlift/dagster_airlift/test/shared_fixtures.py
examples/experimental/dagster-airlift/dagster_airlift/test/test_utils.py
examples/experimental/dagster-airlift/dagster_airlift_tests/integration_tests/test_scaffolding.py
examples/experimental/dagster-airlift/examples/dbt-example/Makefile
examples/experimental/dagster-airlift/examples/kitchen-sink/Makefile
examples/experimental/dagster-airlift/examples/perf-harness/Makefile
examples/experimental/dagster-airlift/scripts/airflow_setup.sh

Demo requires us running two airflow instances at once. As a result, we need to be able to change which port each airflow goes to, and scaffold airflow home to two different directories.
Existing tests continue to work

[dagster-airlift][federation-demo] setup script changes

---

python_modules/dagster/dagster/_core/storage/runs/migration.py

instead of adding the cursor WHERE clause to a static base query, we were repeatedly appending the WHERE clauses onto the query 
Fixed an issue where running `dagster instance migrate` on Dagster version 1.9.0 constructed a SQL query that exceeded the maximum allowed depth.

fix backfill_id migration query issue where query was repeated appended with cursor

---

python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py

See changelog
Fixed bug that could cause a GraphQL error on certain views when running `dagster dev` on a code location after removing an asset.

Check if asset graph has asset before getting it

---

js_modules/dagster-ui/packages/ui-components/src/components/PageHeader.tsx

This was noticed during the runs feed testing but wasn't specific to the runs feed. In general, if you make the page narrow enough that the page header wraps, there is no padding and the top text touches the navbar. We also didn't mandate padding to the left of the right-side actions, and this PR adds a gap there as well.
Tested manually on a variety of pages + screen sizes

[ui] Add padding to page headers for scenarios when they wrap

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/SidebarAssetInfo.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/PartitionHealthSummary.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/__stories__/PartitionHealthSummary.stories.tsx

I was testing another bug and noticed that selecting assets in the asset graph with 200k+ partitions was freezing the UI for 30+ seconds.  I dug into this and found this component was still iterating over the partition space to find the number of materialized partitions. This is now available via `liveData.partitionStats`, and the component is only used in one place with no `selections` passed in.
I think this code used to be necessary because the component was also used in other contexts where there were either 1) multiple assets being displayed as a single health bar or 2) a subset of the partition space in `selections`, but with just this one callsite left there's no reason to not just show the counts from the asset health data.
Tested manually with large assets that load slowly. …

[ui] Fix poor performance when selecting assets with many partitions

---

python_modules/dagster/dagster/_core/definitions/asset_graph.py
python_modules/dagster/dagster_tests/core_tests/host_representation_tests/test_external_data.py

`execution_set_identifier` behavior diverged when passing `AssetSpec` directly to `Definitions` due to the 
`AssetsDefinition` that is created in that code path causing `execution_set_identifier` to group unexecutable assets. 
Change`get_execution_set_identifier` to return for unexecutable assets. 
added test that previously failed

dont return an execution set identifier for unexecutable assets

---

python_modules/dagster/dagster/_core/remote_representation/external.py

If a user has this setting turned off, then we shouldn't construct a sensor for them. 
Note: this only impacts cases where the user code server is on a lower dagster version than the host process, as in dagster>=1.9.0, the user code server will be constructing this sensor anyway.
Fixed issue which would cause a `default_automation_condition_sensor` to be constructed for user code servers running on dagster version < 1.9.0 even if the legacy `auto_materialize: use_sensors` configuration setting was set to `False`.

Respect `auto_materialize_use_sensors`

---

.buildkite/dagster-buildkite/dagster_buildkite/cli.py
.buildkite/dagster-buildkite/dagster_buildkite/package_spec.py
.buildkite/dagster-buildkite/dagster_buildkite/utils.py

dlift live tests were running on every master PR bc this skip_reason bs was completely wrong. Add a bunch of documentation / generally make it work properly.
dlift live doesn't run on this branch. The real test will be to make sure that it doesn't run on master once this commit lands.

Fix buildkite live tests

---

js_modules/dagster-ui/packages/ui-core/src/app/DefaultFeatureFlags.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/app/FeatureFlags.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/app/Flags.tsx
js_modules/dagster-ui/packages/ui-core/src/app/UserSettingsButton.tsx
js_modules/dagster-ui/packages/ui-core/src/app/UserSettingsDialog/UserSettingsDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/app/__tests__/Flags.test.tsx
js_modules/dagster-ui/packages/ui-core/src/setupTests.ts

We want to support having a default value if a feature flag was never set before. To do this we need to distinguish between a flag being off because it was explicitly turned off or off because it was never turned on/off before. To do that I updated our localStorage schema to store an object with boolean values (on/off). The absence of a key in the object means the flag is unset and we should use the default value.
I also opted to use a BroadcastChannel for broadcasting feature flag updates across multiple tabs (probably overkill but still useful IMO).
I added logic to migrate from the old array localStorage schema to the new schema.
jest.
Toggle flags on/off
Used in cloud for https://github.com/dagster-io/internal/pull/12543

(feat.) Update Feature Flags to support default values.

---

examples/with_openai/setup.py

Bump to latest versions available following https://github.com/dagster-io/dagster/pull/25641 and https://github.com/dagster-io/dagster/pull/25620
`dagster dev` with with_openai

Bump versions for langchain, langchain-community and langchain-openai

---

python_modules/libraries/dagster-tableau/dagster_tableau/resources.py
python_modules/libraries/dagster-tableau/dagster_tableau/translator.py

Also `TableauContentData` and `TableauContentType` which are used by `TableauWorkspaceData`
BK with previous tests

[dagster-tableau] Whitelist TableauWorkspaceData

---

python_modules/dagster-graphql/dagster_graphql/schema/pipelines/logger.py
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/resource.py

I dropped some handling here https://github.com/dagster-io/dagster/pull/25552/files#r1833202428 thinking it was for `mode` which is now defunct, but this can still happen so handle it. Since the config type is nullable the behavior is the same so this just gracefully handles the condition without error.
loaded a job in the UI that was previously failing, now loads without error

[graphql] handle config mapped resources

---

js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/PolicyEvaluationTable.tsx

See changelog -- core thing is that numCandidates is Null when all partitions are evaluated
[ui] Fixed issue which would cause the "Partitions evaluated" label to incorrectly display "0" in cases where all partitions were evaluated.

[ui] Fix issue with candidate count

---

python_modules/libraries/dagster-tableau/dagster_tableau/resources.py

Updates the state methods to return and receive a `TableauWorkspaceData` object now that it is whitelisted.
Also cleans `fetch_tableau_workspace_data` to simplify the return statement.

[dagster-tableau] Clean `fetch_tableau_workspace_data` and state methods

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_cli_event.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/conftest.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/dbt_packages/test_columns_metadata.py

When using a dbt manifest that was built on a Windows machine but executed on a Unix machine, Dagster does not correctly resolve the sql filepath of the model's backing file.
This PR handles and tests that case.
New unit test.
> [dagster-dbt] Fixed an error arising when fetching column lineage for dbt assets using a manifest built on Windows machines.

[dagster-dbt] Fix generating column metadata when manifest uses Windows-style filepaths

---

docs/dagster-university/pages/dagster-dbt/lesson-3/5-loading-dbt-models-into-dagster-as-assets.md

community member [told us](https://dagster.slack.com/archives/C01U5LFUZJS/p1731056410596729) that this [link](https://pythonalgos.com/generator-functions-yield-and-yield-from-in-python/) explains the difference between yield and yield from redirects to a spam site. 
I removed the link in the course.

removed yield from link, site is now spam redirect

---

js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/AssetChecks.tsx

This closes https://github.com/dagster-io/dagster/issues/23829 and makes the rendering of the `asset_check` description the same as `asset` description
Ran locally with the following definitions file and checked the description rendering in the asset, asset_check with description, and asset_check without description:
```
from dagster import Definitions, asset_check, asset
@asset
def my_asset():
""" A simple asset with a docstring
And some more text
"""
return None
@asset_check(asset=my_asset)
def my_asset_check():
""" Asset check for my_asset
With a docstring
With some more text
"""
return None
@asset_check(asset=my_asset)
def my_asset_check2():
return None
assets=[my_asset],
asset_checks=[my_asset_check, my_asset_check2],
)
```
The result in the UI looks like this:

Render asset check description with the Description component

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py

Another callsite where we pass in a small number of asset keys and don't need to fetch the full graph.

Don't fetch the whole asset graph in get_additional_required_keys

---

python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
python_modules/dagster/dagster_tests/definitions_tests/test_sensor_invocation.py

Ffor testing `run_status_sensor` we currently only support using `build_run_status_sensor_context` and directly invoking the sensor to exercise just the decorated function. If a user wants to ensure that they have all of the arguments set correctly on their status sensors and that they react to an `instance` as expected when events happen they currently can not. 
This PR makes a small tweak to the code origin match logic to match when both are `None` to allow in process execution matches. This makes it so it as at least possible to use `evaluate_tick` on a `@run_status_sensor` with in process execution to test how it would react. 
Theres more that could be done to make this easier, but this at least makes it possible. 
added test

[run status sensor] allow matching None origins for testing

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py

Since this is a namedtuple, we can convert it to a serializable tuple and back rather than whitelisting this integration class.
Unit test.

[dagster-fivetran] avoid whitelisting fivetran meta class for serdes

---

python_modules/dagster/dagster/_check/functions.py
python_modules/dagster/dagster/_check/record.py
python_modules/dagster/dagster/_core/definitions/partition.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster/_record/__init__.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection.py
python_modules/dagster/dagster_tests/core_tests/partition_tests/test_partition.py
python_modules/dagster/dagster_tests/definitions_tests/test_definition_errors.py
python_modules/dagster/dagster_tests/general_tests/check_tests/test_check.py

expanded version of reverted attempt #25262, this also  disallows `@records` (including in tuple checks) and  hits all of the sequence and iterable variants 
added tests 
ensure existing cloud customers workspace snapshots can still load

[check] dont allow str, bytes, or record for sequence or iterable

---

docs/content/_navigation.json

`Declarative Automation` is GA as of 1.9.0
👀

remove "(Experimental)" from Declarative Automation menu title

---

python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py
python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py

I wanted to use AutomationCondition.code_version_changed with dbt seeds. Unfortunately, from what I was able to determine, code_version is not set for seeds. Or maybe I should say it is, but all seeds have same value because function default_code_version_fn, that is used as a default, sets it based on “raw_sql” or “raw_code” from dbt_resource_props and what I saw for seeds, value of those is an empty string. That wouldn’t be a problem if there was a function like get_code_version in DagsterDbtTranslator that one can override. I didn’t find any open issue on that topic, so I decided to try to implement that.
It’s the first time I’m contributing to any open-source project. I tried to do my best to comply to any standards I could find so please be understanding 😊
I’ve added unit tests …

Add get_code_version to DagsterDbtTranslator

---

js_modules/dagster-ui/packages/ui-core/src/runs/RunsFilterInput.tsx

Linear: https://linear.app/dagster-labs/issue/FE-571/fix-placeholder-text-of-partition-filter
Partition filter's placeholder text incorrectly says backfill ID
Tested locally
NOCHANGELOG

[ui] fix partition filter placeholder text

---

python_modules/dagster/dagster/__init__.py
python_modules/dagster/dagster/_loggers/__init__.py

Summary:
This provides a way for you to specify the dagster-specific JsonFormatter that the json_console_logger uses as a formatter option under python_logs in your dagster.yaml file.

Pull out the JsonFormatter used by json_console_logger into a top-level import

---

python_modules/dagster/dagster/_config/pythonic_config/config.py
python_modules/dagster/dagster/_config/pythonic_config/conversion_utils.py
python_modules/dagster/dagster/_config/pythonic_config/io_manager.py
python_modules/dagster/dagster/_utils/typing_api.py

Now that we're targeting Python 3.9+, I suspect we can remove this 3.7 back-compatibility logic.
bk

removes logic for 3.7 back-compatibility

---

.buildkite/dagster-buildkite/dagster_buildkite/package_spec.py
.buildkite/dagster-buildkite/dagster_buildkite/python_version.py
.buildkite/dagster-buildkite/dagster_buildkite/step_builder.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/integration.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/test_project.py

to enable building the pipeline in newer python versions as well as the current version
https://github.com/python/cpython/issues/100458
bk

[buildkite] stop using str Enum

---

docs/content/_navigation.json
docs/content/integrations/airlift/tutorial/observe.mdx
docs/content/integrations/airlift/tutorial/overview.mdx
docs/content/integrations/airlift/tutorial/peer.mdx

Docs for the observe stage. Again, mostly kept intact except for wording at the beginning. One main change:
- Add more explanation for the partitions stage, and actually explain how to kick off a backfill of a partition + clear airflow instance history.

[dagster-airlift] Observe stage

---

docs/content/integrations/airlift/tutorial.mdx
docs/content/integrations/airlift/tutorial/observe.mdx
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/migrate.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/migrate_with_check.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/standalone.py

The migration+completion steps of the tutorial were previously not partitioned. This adds partitioning information.

[dagster-airlift] Partitioned migration steps

---

docs/content/_navigation.json
docs/content/integrations/airlift/tutorial/migrate.mdx
docs/content/integrations/airlift/tutorial/observe.mdx
docs/content/integrations/airlift/tutorial/overview.mdx

Migration section. I didn't pull in the asset checks section, I think that one is going to need to be split up / interspersed with the other sections.

[dagster-airlift] Migration

---

docs/content/_navigation.json
docs/content/integrations/airlift/tutorial/decomission.mdx
docs/content/integrations/airlift/tutorial/migrate.mdx
docs/content/integrations/airlift/tutorial/overview.mdx

Section on decomissioning the airflow dag + relevant links. very little change on this one.

[dagster-airlift] decomission section

---

docs/content/integrations/airlift/tutorial.mdx
docs/content/integrations/airlift/tutorial/observe.mdx
docs/content/integrations/airlift/tutorial/peer.mdx
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/observe_check_on_asset.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/observe_with_partitions.py
examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/dagster_defs/stages/peer_with_check.py

[dagster-airlift] Add check to observe step, ensure it's present at each stage.

---

python_modules/dagster/dagster/_utils/caching_instance_queryer.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/builtins/test_in_progress_condition.py

See changelog
Added test -- it failed before the changes, and passes now
Fixed issue with `AutomationCondition.execution_in_progress` which would cause it to evaluate to True for unpartitioned assets that were part of a run that was in progress, even if the asset itself had already been materialized.

[DA] Fix unpartitioned in_progress calculation

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/translator.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/utils.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/experimental/conftest.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/experimental/test_asset_specs.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/experimental/test_resources.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/experimental/test_translator.py

This PR implements `FivetranWorkspaceData.to_fivetran_connector_table_props_data()`, a method that converts a `FivetranWorkspaceData` object to a list of FivetranConnectorTableProps.
To create the asset spec, we need one `FivetranConnectorTableProps` object per connector table. This method parses the API raw data to create the FivetranConnectorTableProps` object, which is compatible with the `DagsterFivetranTranslator`. 
This will be used in the `defs_from_state` method of the stated-backed defs loader in a subsequent PR. 
Additional unit test

[5/n][dagster-fivetran] Implement `FivetranWorkspaceData` to `FivetranConnectorTableProps` method

---

python_modules/dagster/dagster/_utils/caching_instance_queryer.py

Summary:
Speed up this calculation when the needed information is already on the asset record.
Run test_unpartitioned using a fixture pointed at an instance with that method True
NOCHANGELOG

Include asset_records_have_last_planned_materialization_storage_id in get_in_progress_asset_subset

---

python_modules/libraries/dagster-databricks/dagster_databricks/pipes.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_pipes.py

Attach tags & metadata in `PipesDatabricksClient`
[dagster-databricks] `PipesDatabricksClient` now attaches Databricks metadata to Dagster results produced during Pipes invocation and adds Dagster tags to the Databricks job

[dagster-databricks] attach tags and metadata in PipesDatabricksClient

---

python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/ecs.py
python_modules/libraries/dagster-aws/dagster_aws_tests/pipes_tests/fake_ecs.py
python_modules/libraries/dagster-aws/dagster_aws_tests/pipes_tests/test_pipes.py

Attach tags & metadata in `PipesECSClient`
[dagster-aws] `PipesECSClient` now attaches AWS ECS metadata to Dagster results produced during Pipes invocation and adds Dagster tags to the ECS task

[dagster-aws] attach tags and metadata for PipesECSClient

---

python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/emr_serverless.py
python_modules/libraries/dagster-aws/dagster_aws_tests/pipes_tests/test_pipes.py

Attach tags & metadata with `PipesEMRServerlessClient`
[dagster-aws] `PipesEMRServerlessClient` now attaches AWS EMR Serverless metadata to Dagster results produced during Pipes invocation and adds Dagster tags to the job run

[dagster-aws] attach tags and metadata in PipesEMRServerlessClient

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/experimental/conftest.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/experimental/test_asset_specs.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/experimental/test_resources.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/experimental/test_translator.py

This PR implements the `FivetranWorkspaceDefsLoader` to be used to load asset specs. `account_id` is added as a parameter to `FivetranWorkspace` - we need a unique ID for the Fivetran workspace to implement `defs_key`.
Updated unit tests

[6/n][dagster-fivetran] Implement FivetranWorkspaceDefsLoader

---

python_modules/dagster-graphql/dagster_graphql/schema/pipelines/mode.py
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py

for the job portion of the id, just use `resolve_id` directly instead of always using the identifying snapshot id. This will use the more effecient override in `GrapheneJob` when we have a live job definition. 
updated test

[graphql] change mode id scheme

---

python_modules/libraries/dagster-looker/dagster_looker/lkml/dagster_looker_lkml_translator.py
python_modules/libraries/dagster-looker/dagster_looker/lkml/liquid_utils.py
python_modules/libraries/dagster-looker/dagster_looker/lkml/sqlglot_utils.py
python_modules/libraries/dagster-looker/dagster_looker_tests/lkml/test_asset_specs.py
python_modules/libraries/dagster-looker/dagster_looker_tests/looker_projects/__init__.py
python_modules/libraries/dagster-looker/dagster_looker_tests/looker_projects/test_liquid/views/liquid_derived_table.view.lkml
python_modules/libraries/dagster-looker/dagster_looker_tests/looker_projects/test_union_no_distinct/views/union_table.view.lkml

try/catch guards the sqlglot optimize of looker derived tables, in case the optimization fails but the parse succeeds, we may still be able to extract lineage.
Also fixes an issue where Looker union syntax supports not specifying unique/distinct criteria, but sqlglot errors - do this by constructing a custom sqlglot dialect.
New unit test.
> `[dagster-looker] More gracefully handle errors in optimizing derived table parsing. Properly handle unions without unique/distinct criteria.`

[dagster-looker] Fix lkml parsing of unions, try/except optimize

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
python_modules/dagster-graphql/dagster_graphql/schema/backfill.py
python_modules/dagster/dagster/_core/asset_graph_view/serializable_entity_subset.py
python_modules/dagster/dagster/_core/definitions/asset_graph_subset.py
python_modules/dagster/dagster/_core/definitions/data_time.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/valid_asset_subset.py
python_modules/dagster/dagster/_core/definitions/partition.py
python_modules/dagster/dagster/_core/definitions/time_window_partition_mapping.py
python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
python_modules/dagster/dagster/_core/execution/asset_backfill.py
python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_time_window_partition_mapping.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_entity_subset.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_partitions_subset.py
python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py
python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

This was intended as a perf optimization in the distant past, but improvements to common operations in the TimeWindowPartitionsSubset class have made this obsolete.
Future changes in this stack will further pare down code in these areas that has outlived its usefulness
NOCHANGELOG

[cleanup] Delete PartitionKeysTimeWindowPartitionsSubset

---

python_modules/dagster/dagster/_core/workspace/autodiscovery.py
python_modules/dagster/dagster_tests/cli_tests/workspace_tests/autodiscovery_tests/autodiscover_in_module_multiple/__init__.py
python_modules/dagster/dagster_tests/cli_tests/workspace_tests/autodiscovery_tests/autodiscover_in_module_multiple/defs1.py
python_modules/dagster/dagster_tests/cli_tests/workspace_tests/autodiscovery_tests/autodiscover_in_module_multiple/defs2.py
python_modules/dagster/dagster_tests/cli_tests/workspace_tests/autodiscovery_tests/test_autodiscovery.py

Ran into this with a user - the "Cannot have more than one Definitions object defined at module scope." error can be a bit of a rabbithole to track down. The case we hit in particular was
when one of the `Definitions` objects was being imported unknowingly.
This PR updates the error message to include the names of all the located `Definitions` objects, so it's easier to track down where they're coming from and rectify the error.
Update unit tests.
> Errors raised from defining more than one `Definitions` object at module scope now include the object names so that the source is easier to determine.

Make 'multiple Definitions objects' error message more actionable

---

python_modules/libraries/dagster-sigma/setup.py

Pin `aiohttp<3.11`, which released this morning, since it is not compatible with `aioresponses`, which we use for testing.

[dagster-sigma][bk] Add aiohttp pin

---

python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/test_resource.py

Adds an optional config option to loading Sigma data which allows users to skip loading column lineage.
New unit test.
> `[dagster-sigma]` Add `skip_fetch_column_data` option to skip loading Sigma column lineage, which can speed up loading large instances.

[dagster-sigma] Add option to skip fetching column-level data for workbooks to speed loading

---

integration_tests/test_suites/auto_materialize_perf_tests/test_asset_daemon_perf.py

As title. This is a consequence of getting rid of the special-purpose PartitionKeysTimeWindowPartitionsSubset. Long story short, these perf tests are not very representative of real-world perf scenarios, and mostly exist as a backstop in case anything massively changes. This change is also completely irrelevant to the Declarative Automation perf characteristics, which are more important and have their own separate perf tests.
TL;DR: We'll probably remove this test in the near future, for now we're just making it stop failing
NOCHANGELOG

Add buffer time to perf test

---

examples/airlift-federation-tutorial/Makefile
examples/airlift-federation-tutorial/airlift_federation_tutorial/dagster_defs/stages/with_specs.py
examples/airlift-federation-tutorial/airlift_federation_tutorial_tests/conftest.py
examples/airlift-federation-tutorial/airlift_federation_tutorial_tests/test_specs_stage.py
examples/experimental/dagster-airlift/dagster_airlift/core/__init__.py
examples/experimental/dagster-airlift/dagster_airlift/core/load_defs.py

Add an initial stage to the federation tutorial which instantiates an upstream and downstream dag asset, as well as a sensor for each instance.
New test that "acts out" a replacement of the code with the completed stage and ensures module loads correctly.

[dagster-airlift][federation-tutorial] Add initial stage to add specs to federation tutorial

---

examples/airlift-federation-tutorial/airlift_federation_tutorial/dagster_defs/stages/executable_and_da.py
examples/airlift-federation-tutorial/airlift_federation_tutorial_tests/test_executable_stage.py

Adds an additional stage to the federation tutorial where we actually make the downstream asset executable and add an automation condition.

[dagster-airlift][federation-tutorial] Add executable stage to federation tutorial

---

docs/content/_navigation.json
docs/content/integrations/airlift.mdx
docs/content/integrations/airlift/federation-tutorial/overview.mdx

Scaffold out federation tutorial docs. Will fill in in downstream PRs.

[dagster-airlift][federation-tutorial] Scaffold federation tutorial docs

---

js_modules/dagster-ui/packages/ui-core/src/app/Flags.tsx
js_modules/dagster-ui/packages/ui-core/src/app/UserSettingsDialog/UserSettingsDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/app/__tests__/Flags.test.tsx

Fixes an issue where the user settings dialog would immediately save default feature flag values to localStorage
jest + manual testing:
With local host cloud I opened the user settings dialog and output my localStorage in the console and confirmed that it hadn't saved the default value:
Next I switched to a branch deployment where the default value is off and confirmed that it defaulted to off and still the default value was not saved in localStorage.

Fix user settings dialog saving default values on open

---

python_modules/dagster/dagster/_core/definitions/antlr_asset_selection/antlr_asset_selection.py
python_modules/dagster/dagster/_core/definitions/asset_selection.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection.py

We want to use the new `AntlrAssetSelectionParser` in our backend to parse the new asset selection syntax into an `AssetSelection`. This should go in a try/catch inside the `AssetSelection.from_string` method for backwards compatibility.

Use AntlrAssetSelectionParser in AssetSelection.from_string

---

js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/EvaluationList.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/EvaluationListRow.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/EvaluationStatusTag.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/__fixtures__/EvaluationList.fixtures.ts
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/__stories__/EvaluationList.stories.tsx

Create an evaluation list table view based on design.
Clicking the timestamp opens a dialog with the evaluations. Clicking the "X runs" link will open the runs table.
Just a Storybook example for now.
Storybook.

[ui] New Evaluations list table

---

python_modules/dagster/dagster/_core/executor/multiprocess.py

https://github.com/dagster-io/dagster/pull/22839 started keeping processes around in the multiprocess executor to track whether they were still running at termination time, preventing those subprocess objects from being GCed after the step was completed, causing resource buildup issues.
Resolves https://github.com/dagster-io/dagster/issues/25132.
Existing automated testing, plus run the following job locally:
```
def op_factory(i: int):
@dg.op(name=f"op_{i}")
def the_op() -> int:
return i
return the_op
@dg.job
def job_with_many_steps():
for i in range(400):
op_factory(i)()
```
Before this change, lsof -p <run pid> grew over time for that job, now it stays steady.
- Fixed an issue where the default multiprocess executor kept holding onto subprocesses after their step …

Fix subprocess resource leak in multiprocess executor

---

examples/experimental/dagster-airlift/dagster_airlift/core/load_defs.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py

A method to load asset specs for a given airflow dag. This better conforms to the BI/dbt integration format that we've previously established, and will form the basis of our federation APIs.
new unit tests for basic fxnality.

[dagster-airlift][federation-apis] Load airflow dag asset specs

---

examples/experimental/dagster-airlift/dagster_airlift/core/__init__.py
examples/experimental/dagster-airlift/dagster_airlift/core/load_defs.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/sensor_builder.py

Previously our fxn was creating a Definitions object. Let's change to creating a SensorDefinition directly.

[dagster-airlift][federation-apis] Standalone sensor def creation fxn

---

docs/sphinx/sections/api/apidocs/libraries/dagster-airlift.rst
examples/experimental/dagster-airlift/dagster_airlift/core/__init__.py
examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
examples/experimental/dagster-airlift/dagster_airlift/core/airflow_instance.py
examples/experimental/dagster-airlift/dagster_airlift/core/load_defs.py
examples/experimental/dagster-airlift/dagster_airlift/core/sensor/sensor_builder.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
examples/experimental/dagster-airlift/dagster_airlift/core/serialization/defs_construction.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_airflow_asset_mapping.py
examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py

This PR is now being used to accumulate federation API commits before landing.
ORIGINAL DESCRIPTION:
Right now, all airlift internals which operate over mapped airflow assets take in a fully-qualified Definitions object. This PR changes them to instead operate over an iterable of assets, and leaves the definitions munging to the callsites.
After making this change, it becomes easy to add asset-oriented airlift methods - and I demonstrate that with a standalone method to enrich airflow assets. We'll eventually be able to re-implement the full defs loader on top of this.
New test for the new method, existing test suite.
NOCHANGELOG

[dagster-airlift][federation-apis] federation APIs accumulator

---

python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/glue.py
python_modules/libraries/dagster-aws/dagster_aws_tests/pipes_tests/fake_glue.py
python_modules/libraries/dagster-aws/dagster_aws_tests/pipes_tests/test_pipes.py

Add AWS Glue metadata injection to `PipesGlueClient`
Also, when CloudWatch logging is not enabled for a Glue job, the client now logs a warning message instead of failing.
[dagster-aws] `PipesGlueClient` now attaches AWS Glue metadata to Dagster results produced during Pipes invocation

[dagster-aws] attach tags and metadata in PipesGlueClient

---

js_modules/dagster-ui/packages/ui-core/src/assets/RecentUpdatesTimeline.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/__stories__/RecentUpdatesTimeline.stories.tsx

This is a small change to the RecentUpdatesTimeline so that it 1) doesn't change height when it transitions from loading to populated and 2) uses the skeleton component.
It does change the "empty, no events" state -- that one was shorter and just had a text label in it, and we now show the bar and the "none to display" message over on the right where the count is displayed.
Storybook!

[ui] Use skeleton to improve Asset “Recent Updates” loading state

---

python_modules/dagster/dagster/_core/storage/event_log/base.py
python_modules/dagster/dagster/_core/storage/partition_status_cache.py
python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

Noticed this while working in this area -- the LoadingContext system expects the output of these methods to be in the same order as the input, which is not currently guaranteed. The AssetStatusCacheValues don't have a reference to what asset key they came from, meaning we can't reconstruct this mapping from an unordered list.
Simplest solution is to just not use dictionaries at all.
Surprised this hasn't caused issues, to be honest!
Internal: https://github.com/dagster-io/internal/pull/12702
NOCHANGELOG

Get rid of risk of order dependence

---

python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/definitions/five_runs_required.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_e2e.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_failure_recovery.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/asset_daemon_scenario.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/scenario_utils/base_scenario.py

Add ThreadPoolExecutor for AssetDaemon run submission

---

python_modules/dagster/dagster/_core/definitions/definitions_class.py
python_modules/dagster/dagster/_core/definitions/repository_definition/repository_data_builder.py
python_modules/dagster/dagster/_core/definitions/utils.py
python_modules/dagster/dagster_tests/general_tests/test_cacheable_assets_defs.py

This pushes the addition of the default automation condition sensor further down the stack, to a point at which the CacheableAssetsDefinitions are guaranteed to be resolved.
Resolves: https://github.com/dagster-io/dagster/issues/25924
Fixed a bug which could cause code location load errors when using `CacheableAssetsDefinitions` in code locations that contained `AutomationConditions`.

Fix CacheableAssetsDefinition / default_automation_condition_sensor interaction

---

docs/content/dagster-plus/deployment/serverless.mdx

Summary:
The default here is a little ambiguous because the CLI defaults to 3.9 if nothing is set, but a newly scaffolded Github action specifies 3.10. Make the docs just specify what is allowed and how to change it.
NOCHANGELOG

Update default python version language in docs

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetEventMetadataEntriesTable.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeOverview.tsx
js_modules/dagster-ui/packages/ui-core/src/metadata/MetadataEntry.tsx

This PR makes the behavior of the asset metadata entries table more consistent:
- Some asset metadata entries are internal / used to implement features and are never displayed
- Some asset metadata entries are hidden on the overview page specifically because they appear in the right sidebar (row count, table name, and URI)
We were previously hiding row_count everywhere, and not hiding table_name or uri on the overview, which was inconsistent.
Used the dev proxy to look at a bunch of production assets that have this metadata populated.
[ui] Asset metadata entries like `dagster/row_count` appear on the events page and are properly hidden on the overview page where they appear in the sidebar.

[ui] Consistently hide metadata entries shown in the asset overview sidebar

---

docs/content/dagster-plus/deployment/serverless.mdx

I confirmed the freshness of these IPs during the writing of the docs beta replacement page: https://docs-preview.dagster.io/dagster-plus/deployment/serverless/dagster-ips
Just want to update in the original docs too since they're still staying up.
👀

[docs] update Serverless IP address date

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py

As title. All other new APIs for Fivetran are marked as experimental, but I missed this one.

[dagster-fivetran] Mark FivetranWorkspace as experimental

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_all_snapshot_ids.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_assets.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_solids.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py
python_modules/dagster/dagster/_core/execution/asset_backfill.py

in https://github.com/dagster-io/dagster/pull/25736 I mistakenly thought filtering down to the nodes in the target set in the first pass would act as the previous `if k in self.target_subset.asset_keys` but the list becomes filled with `parent_keys` so need to preserve that check
updated test so it failed without this fix 
[ui] no longer display extraneous assets in the asset backfill page, a problem introduced in 1.9.2

[graphql] fix backfill target keys

---

python_modules/libraries/dagster-polars/dagster_polars/io_managers/delta.py
python_modules/libraries/dagster-polars/tox.ini

Add support for `polars>=1.14` in `dagster-polars`.
Existing test suite, plus testing on polars<1.14.

[dependencies] Make dagster-polars compatible with polars>=1.14

---

python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/test_resource.py

Adds an optional config field to `SigmaFilter` to hide datasets which are unused by any workbook.
> [dagster-sigma] Added include_unused_datasets field to `SigmaFilter` to disable pulling datasets that aren't used by a downstream workbook.

[dagster-sigma] Add filter option to hide unused datasets

---

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster_tests/asset_defs_tests/asset_graph_view_tests/test_basic_asset_graph_view.py

Summary:
This was using the partition mapping in the wrong direction. It is not currently used though.
BK (modified tests)
NOCHANGELOG

Fix get_child_subset partition mapping

---

js_modules/dagster-ui/packages/ui-core/src/app/FeatureFlags.oss.tsx

as titled.
Not actually exposing the flag to users just yet, but do want to gate the code with it so landing the flag and will enable manually with JS.

[oss] Add feature flag for new asset selection syntax 

---

docs/dagster-ui-screenshot/setup.py
python_modules/libraries/dagster-deltalake-pandas/setup.py
python_modules/libraries/dagster-deltalake-polars/setup.py
python_modules/libraries/dagster-deltalake/setup.py

We no longer target these versions of Python; open to discussion on better ways of maintaining accuracy of these classifiers.
bk

removes legacy python classifiers from setup.py

---

python_modules/dagster/dagster/_check/builder.py
python_modules/dagster/dagster_tests/general_tests/check_tests/test_check.py

`TypedDict` doesn't allow `isinstance` or `issubclass` calls against it so in order to let them flow through check builder we coerce any `dict` subclass to `dict` inst checks. 
added test cases

[check] handle TypedDict

---

python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
python_modules/libraries/dagster-sigma/dagster_sigma/translator.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/conftest.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/test_translator.py

Sigma workbooks typically depend on datasets, which passthrough data from a database to structured tables that users can refresh or rename. However, you can also point workbooks directly at tables in your warehouse. This PR allows our integration to be aware of the latter, creating upstream external assets for each table.
Update unit test, test locally against real Sigma instance.
> [dagster-sigma] Added support for direct workbook->warehouse table dependencies.

[dagster-sigma] Add support for direct workbook->table deps

---

js_modules/dagster-ui/packages/eslint-config/index.js
js_modules/dagster-ui/packages/ui-core/src/assets/AssetGroupRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeLineageGraph.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetsGlobalGraphRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/hooks/useOpenInNewTab.tsx
js_modules/dagster-ui/packages/ui-core/src/insights/InsightsBarChart.tsx
js_modules/dagster-ui/packages/ui-core/src/pipelines/PipelineExplorerRoot.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/pipelines/PipelineOverviewRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunHeaderActions.tsx

Stacking on https://github.com/dagster-io/dagster/pull/25909, lint against using `window.open`. This is because our current usage generally ignores any `basePath` value that might be in place in the app, e.g. a deployment path prefix in Dagster+.
The result is that opening the new tab may lead to a redirect that opens the path in a default fallback deployment, instead of the viewer's current deployment.
To avoid this, `useOpenInNewTab` prepends the basePath to the path value. I have added a lint rule to error on `window.open` usage and push users toward this hook instead.

[ui] Lint against window.open

---

python_modules/libraries/dagster-openai/dagster_openai_tests/test_resources.py

`mock.not_called` is deprecated in Python 3.12, using `not mock.called` instead.
BK, local tests with Python 3.12

[dagster-openai] Fix not called assertion in tests for Python 3.12

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNode.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/__fixtures__/AssetNode.fixtures.ts
js_modules/dagster-ui/packages/ui-core/src/asset-graph/__stories__/AssetNode.stories.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/__tests__/AssetNode.test.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/layout.ts
js_modules/dagster-ui/packages/ui-core/src/graph/asyncGraphLayout.ts

This fixes a couple specific issues with the asset graph and updates our AssetNode stories:
- Lower the truncation threshold for asset names to prevent wrapping. I think the previous value 38 must have been for a smaller font size, or for a previous asset node width. I verified the current font size (14px) is what is specified in Josh's latest designs and added a story for this case.
- Update the `getAssetNodeDimensions` function to reflect what is actually rendered and ensure the `AssetNodeBox` is always centered in the layout box so that horizontal edges hit the middle of the box. To make this easier I updated the storybooks to show the overall box in a gray color and draw a midline where edges will arrive. I think it'd been a while since we updated this and in a bunch of cases there …

[ui] Fix vertical centering of arrows on the asset graph, asset name wrapping

---

js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadSession.tsx

Requested here: https://linear.app/dagster-labs/issue/FE-685/add-a-warning-when-submitting-launchpad-for-partitioned-job-with-no, it turns out this already existed but only for old op jobs.
FE-674
- Verified that for a partitioned asset job, the warning appears if you do not choose a partition in the launchpad's top right dropdown
I think this highlights the need for some automated tests of the launchpad but it looks like it'll be a bit of an undertaking to get some written.
- Launching partitioned asset jobs from the launchpad now warns if no partition is selected.

[ui] Fix the launchpad’s “no partition specified” warning for asset jobs

---

js_modules/dagster-ui/packages/ui-components/src/components/NewConfigEditor.tsx
js_modules/dagster-ui/packages/ui-components/src/components/configeditor/codemirror-yaml/lint.js

We currently override CodeMirror's global lint addon with a custom implementation that conflicts with the original addon. This incompatibility surfaced while developing the new asset selection syntax input; specifically, loading the launchpad and then accessing the new syntax input triggers JavaScript errors due to the overridden lint behavior.
To fix this issue, this PR stops patching the global lint addon and instead uses a separate patchedLint namespace. By doing so, our custom lint functionality is isolated to specific editor instances, allowing the original lint addon to operate correctly in other editors without interference.
Use the launchpad and see that it lints and surfaces errors correctly by starting with a valid config, adding invalid stuff, and then making it valid again and …

CodeMirror lint: stop patching global lint

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphFilterBar.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphExplorerFilters.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/ui/BaseFilters/useFilter.tsx

[Asset-graph] Rename a few props

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphFilterBar.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/Sidebar.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphExplorerFilters.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-selection/useAssetSelectionFiltering.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-selection/useAssetSelectionInput.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-selection/useAssetSelectionState.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetTable.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/AssetTables.test.tsx
js_modules/dagster-ui/packages/ui-core/src/search/types.ts
js_modules/dagster-ui/packages/ui-core/src/search/useGlobalSearch.tsx
js_modules/dagster-ui/packages/ui-core/src/ui/BaseFilters/useFilter.tsx

Add asset selection filtering to asset catalog table.
Manually tested
[ui] The asset catalog now supports filtering using the asset selection syntax.

[2/4] Add asset selection filtering to asset catalog table.

---

python_modules/libraries/dagster-powerbi/dagster_powerbi/translator.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_translator.py

Gracefully handles the case where a report doesn't have a dependency on a dataset specified.
New unit test.
> [dagster-powerbi] Fixed an issue where reports without an upstream dataset dependency would fail to translate to an asset spec.

[dagster-powerbi][fix] Gracefully handle reports with no dataset

---

python_modules/libraries/dagster-sigma/dagster_sigma/cli.py
python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/pending_repo_snapshot.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/test_asset_specs.py
python_modules/libraries/dagster-sigma/setup.py

Introduces a utility CLI for `dagster-sigma` which loads a code location containing one or more `SigmaOrganizationDefsLoader`s and serializes the repository load data to a file. Adds the capability for the Sling defs loader to ingest this snapshot from a file, allowing orgs with large amounts of Sigma data to ingest at CI time or manually vs each code location load.
In the future, we expect to subsume this behavior into a framework level solution which doesn't tie loading external state into code location load. For now, this is a bit of a workaround.
```shell
dagster-sigma snapshot --python-module my_dagster_package --save-to snapshot.snap
```
```python
...
specs = load_sigma_asset_specs(sigma_workspace, snapshot_path=Path(__file__).parent / "snapshot.snap")
...
```
Unit tests.
> …

[dagster-sigma] Add dagster-sigma snapshot CLI, which allows persisting the contents of a Sigma workspace to a file

---

python_modules/libraries/dagster-airlift/setup.py

Make setup.py for airlift compliant with all the other packages. Previously it had it's own bespoke release process.

[dagster-airlift][cleanup] compliant setup.py

---

python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/remote_representation/job_index.py
python_modules/dagster/dagster/_core/snap/__init__.py
python_modules/dagster/dagster/_core/snap/job_snapshot.py
python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py
python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/test_active_data.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/test_execution_plan.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/test_job_snap.py
python_modules/dagster/dagster_tests/definitions_tests/test_reconstructable.py
python_modules/dagster/dagster_tests/general_tests/compat_tests/test_change_snapshot_structure.py
python_modules/dagster/dagster_tests/storage_tests/utils/run_storage.py

Test Plan: BK, verify that a daemon keeps this value across multiple runs within a single backfill (and better yet, consecutive backfill ticks when the code has not changed)
NOCHANGELOG

Memoize job snapshot ID when called repeatedly on the same object

---

python_modules/libraries/dagster-airlift/dagster_airlift/mwaa/auth.py
python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/mwaa_tests/test_mwaa_auth.py

In the 1.9 rush I incorrectly updated MwaaSessionAuthBackend to take a mwaa_session instead of a mwaa_client. This has been fixed.

[dagster-airlift] mwaa_session -> mwaa_client

---

helm/dagster/values.schema.json

Summary:
2.10.0 appears to have introduced a benign schema change when its regenerated - I guess because this field is a Literal[true] instead of a boolean in the schema.
Test Plan: BK
NOCHANGELOG

regenerate helm schema with pydantic 2.10.0

---

js_modules/dagster-ui/packages/ui-core/src/app/GraphQueryImpl.ts
js_modules/dagster-ui/packages/ui-core/src/asset-selection/AntlrAssetSelection.ts
js_modules/dagster-ui/packages/ui-core/src/asset-selection/AntlrAssetSelectionVisitor.ts
js_modules/dagster-ui/packages/ui-core/src/asset-selection/__tests__/AntlrAssetSelection.test.ts

Now that we support the new asset selection syntax on the backend, we want to support it on the frontend. This requires implementing the visitor methods of the `AssetSelectionVisitor` class generated by ANTLR to perform the various asset selection operations.
Ran `AntlrAssetSelection.test.ts`

[OPER-1486] Implement AntlrAssetSelectionVisitor on frontend

---

docs/content/dagster-plus/deployment/serverless.mdx
docs/docs-beta/docs/dagster-plus/deployment/serverless/ci-cd-in-serverless.md

Looking at [the code in internal,](https://github.com/dagster-io/internal/blob/1.9.2/dagster-cloud/python_modules/dagster-cloud-dagit/dagster_cloud_dagit/server/resources/github/app.py#L549) we are trying to add new CI/CD files no matter what, so as long as the branch is protected this workaround won't work.
👀

[docs] remove manual set up of GitHub Actions workflows workaround for Import Dagster NUX 

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-selection/AntlrAssetSelection.ts
js_modules/dagster-ui/packages/ui-core/src/asset-selection/AntlrAssetSelectionVisitor.ts
js_modules/dagster-ui/packages/ui-core/src/asset-selection/__tests__/AntlrAssetSelection.test.ts

We want to hook up the new asset selection syntax on the frontend which lives in the `useAssetGraphData` hook.
`AntlrAssetSelection.test.ts`

Hook up ANTLR in useAssetGraphData.tsx

---

js_modules/dagster-ui/packages/app-oss/src/App.tsx
js_modules/dagster-ui/packages/ui-core/src/app/AppProvider.tsx

as titled.
hardcoded mutations to return an error and saw us hit this codepath
[ui] In OSS, mutations are no longer retried.

[oss] Don't retry mutations

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_scheduler.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py
python_modules/dagster/dagster/_core/definitions/asset_selection.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_antlr_asset_selection.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection.py
python_modules/dagster/dagster_tests/definitions_tests/asset_policy_sensors_tests/test_default_auto_materialize_sensors.py

On the backend, `AssetSelection` is a nice serializable representation of an asset selection, which we might generate through a few methods:
- From an Antlr asset selection string
- From a set of frontend filters, saved in a catalog view
- Potentially from snapshotted user code, though we don't do this right now (for example, examining an asset job or sensor/schedule target and being able to copy an Antlr-ready string)
We don't have a good way to convert this selection back into a user-readable Antlr string. There are a few possible solutions here:
- Save the user-specified Antlr string alongside a selection. This seems like a promising approach when the initial source of truth is an Antlr string.
- Generate an Antlr string. This is the approach we'll need if the source of truth is user …

[asset selection] Introduce AssetSelection.to_selection_str

---

python_modules/libraries/dagster-airlift/setup.py

Get rid of rich Airlift description within setup.py - make sure it's not dependent on any other files which might not be downloaded as part of the package for now.

[dagster-airlift] Dep-less setup.py

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_automation_condition.py

Imagine you have:
```python
a = (AutomationCondition.foo() & AutomationCondition.bar()).with_label("something")
b = a & AutomationCondition.baz()
```
The implementation of `__and__` automatically transforms `And(And(c1, c2), c3)` into `And(c1, c2, c3)`. This process is generally desirable, as this reduces the number of levels in the hierarchy, making it easier to parse and understand expressions.
However, if an expression has a label, then this indicates that it has its own semantic meaning, which gets erased by this process.
We should prevent this automatic collapsing in cases where the existing condition's label is not `None`.
The same applies to `__or__`!
Added unit tests in python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/fu …

Do not collapse `AutomationCondition`s with labels

---

python_modules/dagster/dagster/_core/instance/__init__.py

We want to restrict the type of events we support fetching records for, for performance sake.
Inspection

mark get_event_records as deprecated

---

js_modules/dagster-ui/packages/ui-components/src/components/MiddleTruncate.tsx
js_modules/dagster-ui/packages/ui-components/src/components/__stories__/MiddleTruncate.stories.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/AssetKeysDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/BackfillPreviewModal.tsx
js_modules/dagster-ui/packages/ui-core/src/instigation/TickDetailsDialog.tsx

https://linear.app/dagster-labs/issue/FE-684/targeted-assets-dialog-is-too-aggressive-with-middle-truncate
Thankfully this turned out to be a quick fix - I verified in the docs that `offsetWidth` shouldn't have other implications beyond this:
Tested manually in the "Upstream assets modal" with some long asset names and also via a new storybook + verification that no other MiddleTruncate storybooks were impacted.
[ui] Fixed unnecessary middle truncation occurring in dialogs.

[ui] Fix unnecessary middle truncation occurring in dialogs

---

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_decorators.py

when defining a `@graph_multi_asset`, the `owners` added to `AssetOuts` were not being pulled out and passed to the underlying AssetsDefinition. 
unit test 
Tested that owners is shown in the UI  for this graph multi asset 
```python
@dg.op
def op1():
return 1
@dg.op
def op2(input1):
return input1 + 1
@dg.op
def op3(input2):
return input2 + 1
@dg.graph_multi_asset(
outs={
"asset1": dg.AssetOut(owners=["team:team_name1"]),
"asset2": dg.AssetOut(owners=["team:team_name2"])
}
)
def my_graph_multi_asset():
result1 = op1()
result2 = op2(result1)
result3 = op3(result2)
return {"asset1": result2, "asset2": result3}
```
Fixed a bug where `owners` added to `AssetOut`s when defining a `@graph_multi_asset` were not added to the underlying `AssetsDefinition`

fix owners not propogated to graph_multi_asset

---

examples/with_wandb/with_wandb/assets/example/fashion_data.py
integration_tests/test_suites/auto_materialize_perf_tests/perf_scenario.py
pyproject.toml
python_modules/dagster-webserver/dagster_webserver_tests/test_subscriptions.py
python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
python_modules/dagster/dagster/_core/execution/plan/execute_step.py
python_modules/dagster/dagster/_core/pipes/utils.py
python_modules/dagster/dagster/_core/test_utils.py
python_modules/dagster/dagster/_serdes/serdes.py
python_modules/dagster/dagster_tests/cli_tests/command_tests/test_schedule_commands.py
python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py
python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py
python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_failure_recovery.py
python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
python_modules/dagster/dagster_tests/daemon_tests/test_backfill_failure_recovery.py
python_modules/dagster/dagster_tests/daemon_tests/test_dagster_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_asset_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_e2e.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_failure_recovery.py
python_modules/dagster/dagster_tests/execution_tests/pipes_tests/in_process_client.py
python_modules/dagster/dagster_tests/execution_tests/pipes_tests/test_subprocess.py
python_modules/libraries/dagster-airlift/perf-harness/perf_harness/cli.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/test_launching.py
python_modules/libraries/dagster-azure/dagster_azure_tests/blob_tests/test_compute_log_manager.py
python_modules/libraries/dagster-celery-k8s/dagster_celery_k8s_tests/test_executor.py
python_modules/libraries/dagster-databricks/dagster_databricks/databricks_step_main.py
python_modules/libraries/dagster-docker/dagster_docker_tests/test_launch_docker.py
python_modules/libraries/dagster-mlflow/dagster_mlflow_tests/test_resources.py

Fix a minor inconsistency. ~There's no effect, because most pyupgrade rules aren't included.~
~(I'd be happy to introduce the pyupgrade rules, if people are open to it.)~

Update the target Python version for Ruff commands

---

python_modules/libraries/dagster-tableau/dagster_tableau/translator.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_reconstruction.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_translator.py

Following an internal discussion [here](https://github.com/dagster-io/internal/discussions/12670) and product review [here](https://www.notion.so/dagster/Product-Reviews-1805443bfd5d4d40b3f6be8c79897295?p=13f18b92e4628020bd6fd3ac45f28af0&pm=s), get_asset_spec().key is the new recommended way to access the asset key in the Translator.
Asset keys can now be customized in a custom translator using `replace_attributes`, like:
```python
class MyCustomTableauTranslator(DagsterTableauTranslator):
def get_asset_spec(self, data: TableauContentData) -> dg.AssetSpec:
default_spec = super().get_asset_spec(data)
return replace_attributes(
default_spec,
key=default_spec.key.with_prefix("prefix"),
)
```
This PR stack will be merged after #25941 lands, so that `replace_attributes()` can be called as …

[dagster-tableau] Use get_asset_spec().key in DagsterTableauTranslator

---

python_modules/dagster/dagster/_core/execution/stats.py
python_modules/dagster/dagster/_core/storage/event_log/base.py

By default, we calculate step stats by fetching all of the events and filtering in-memory to construct the step stat summary.
This PR changes the event fetch to pass in an event type filter.
This has the biggest impact for runs that have a lot of unstructured events and that do not directly inherit from the SqlEventLogStorage (e.g. some Cloud storage implementations)
BK

Change the default implementation to calculate step stats more efficiently

---

python_modules/libraries/dagster-tableau/dagster_tableau/translator.py

Mark DagsterTableauTranslator.get_asset_key as deprecated. To be removed in 1.10.
This PR stack will be merged after #25941 lands, so that `replace_attributes()` can be called as `AssetSpec().replace_attributes()`
[dagster-tableau] `DagsterTableauTranslator.get_asset_key` is deprecated in favor of `DagsterTableauTranslator.get_asset_spec().key`

[dagster-tableau] Mark get_asset_key as deprecated in DagsterTableauTranslator

---

docs/content/integrations/tableau.mdx
examples/docs_snippets/docs_snippets/integrations/tableau/customize-tableau-asset-defs.py

Update the custom translator example in the Tableau docs to reflect `get_asset_spec().key`.
This PR stack will be merged after #25941 lands, so that `replace_attributes()` can be called as `AssetSpec().replace_attributes()`

[dagster-tableau] Update custom translator example in Tableau docs

---

python_modules/libraries/dagster-sigma/dagster_sigma/translator.py

Like #26028 but for Sigma
[dagster-sigma] `DagsterSigmaTranslator.get_asset_key` is deprecated in favor of `DagsterSigmaTranslator.get_asset_spec().key`

[dagster-sigma] Mark get_asset_key as deprecated in DagsterSigmaTranslator

---

python_modules/libraries/dagster-looker/dagster_looker/api/dagster_looker_api_translator.py
python_modules/libraries/dagster-looker/dagster_looker_tests/api/test_build_defs.py

Like #26027 but for Looker API
Updated unit test with BK

[dagster-looker] Use get_asset_spec().key in DagsterLookerApiTranslator

---

python_modules/libraries/dagster-looker/dagster_looker/api/dagster_looker_api_translator.py

Like #26028 but for Looker API
[dagster-looker] `DagsterLookerApiTranslator.get_asset_key` is deprecated in favor of `DagsterLookerApiTranslator.get_asset_spec().key`

[dagster-looker] Mark asset key methods as deprecated in DagsterLookerApiTranslator

---

Makefile
docs/content/community/contributing.mdx
python_modules/automation/automation/docker/images/buildkite-test/Dockerfile
scripts/install_dev_python_modules.py

Resolve #26078
The change in instructions reflects how I set up my local environment.
I verified that I can build the Buildkite image using `dagster-image build --name buildkite-test  --dagster-version unused -v 3.12`, and that dependencies are installed on the resulting image, but the CI tests are not running using the updated image.
Avoided unnecessary pyenv usage in environment setup step of contributing guide.

Avoid unnecessary pyenv usage in environment setup

---

python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_daemon/auto_run_reexecution/auto_run_reexecution.py

Small PR, just makes run_retries_retry_on_asset_or_op_failure available via `instance.run_retries_retry_on_asset_or_op_failure`
Associated internal PR: https://github.com/dagster-io/internal/pull/12763

[auto run retry tags] 1/n - make run_retries retry_on_asset_or_op_failure setting available on instance

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_checks.py

we already wipe in the context fixture 
https://github.com/dagster-io/dagster/blob/master/python_modules/dagster-graphql/dagster_graphql_tests/graphql/graphql_context_test_suite.py#L792
so this just messes up places that change that out
bk

[graphql] dont wipe instance in checks test

---

docs/content/integrations/powerbi.mdx
python_modules/libraries/dagster-powerbi/dagster_powerbi/resource.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_asset_specs.py

Defaults-on the admin scan behavior for `dagster-powerbi`, since this gives us more data to work with including better representation of direct connections to warehouses. Updates docs to instruct users how to disable this behavior and revert to the current, individual API accesses if need be.
> [dagster-powerbi] Opts in to using admin scan APIs to pull data from a Power BI instance. This can be disabled by passing `load_powerbi_asset_specs(..., use_workspace_scan=False)`.

[dagster-powerbi] Default-on admin scan APIs

---

js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillAssetPartitionsTable.tsx

Fix stretched tags on Backfill table.
The row cells are flex column containers with no `alignItems` value set, so the children stretch, causing `Tag` elements to occupy the entire cell width.
It's not really safe to change `RowCell` to have `align-items: flex-start` since that would have broader/riskier impact on other table views, so the simple thing to do here is just wrap the `Tag` elements in `div`s.
View a backfill table with tags, verify that they no longer stretch.
[ui] Fix stretched tags in backfill table view for non-partitioned assets.

[ui] Fix tags on backfill table

---

js_modules/dagster-ui/packages/ui-components/src/components/MiddleTruncate.tsx
js_modules/dagster-ui/packages/ui-components/src/components/PageHeader.tsx
js_modules/dagster-ui/packages/ui-components/src/components/__stories__/MiddleTruncate.stories.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetPageHeader.oss.tsx

Fixes the flickering observed in https://dagsterlabs.slack.com/archives/C03CZRZCZQQ/p1732546935350479.  When the sizing is async, the height of the element was briefly reduced to the height of the `•••`, which causes an infinite loop of re-rendering. The "30px" minimum height is the default value that would be set if we were not overriding it here.
Also added a storybook so we can easily verify this behavior in the future:
I added a storybook with the same code as the header and verified the flickering is no longer an issue.

[ui] Add min-height to breadcrumbs to fix layout loop caused by MiddleTruncate RAF

---

.gitignore
python_modules/dagster/dagster/__init__.py
python_modules/dagster/dagster/_cli/__init__.py
python_modules/dagster/dagster/_components/__init__.py
python_modules/dagster/dagster/_components/cli/__init__.py
python_modules/dagster/dagster/_components/cli/generate.py
python_modules/dagster/dagster/_core/definitions/load_assets_from_modules.py
python_modules/dagster/dagster/_generate/generate.py
python_modules/dagster/dagster/_generate/templates/CODE_LOCATION_NAME_PLACEHOLDER/pyproject.toml.jinja
python_modules/dagster/dagster/_generate/templates/COMPONENT_TYPE/COMPONENT_TYPE_NAME_PLACEHOLDER.py.jinja
python_modules/dagster/dagster/_utils/__init__.py
python_modules/dagster/dagster_tests/cli_tests/test_generate_commands.py
python_modules/dagster/setup.py

This is an initial implementation of scaffolding for components. It adds a new CLI `dg` rather than a subcommand to `dagster`. There is other work in flight but this seemed like a good place to cut the bottom of the stack. Implements:
- `dg generate deployment`
- `dg generate code_location`
- `dg generate component-type`
- `dg generate component-instance`
What is NOT in this PR:
- global component registry based on entrypoints-- instead this only resolves component types local to the code location
- anything resembling final `Component` API. This uses a very bare-bones prototype implementing `build_defs` and `generate_files` that will be replaced.
- Calling out to `uv` in scaffolding commands.
- Thoroughly polished output for scaffold commands.
- Final names for commands …

[components] Initial implementation of component project scaffolding

---

python_modules/libraries/dagster-k8s/dagster_k8s/client.py

Summary:
Since this is a private method being overridden, it needs to add the same of the class that defines it due to private name mangling.
Test Plan:
Log lines confirm that patched implementation is now being called, k8s e2e tests verify that it functionally launches runs and makes other k8s api calls

correctly override k8s ApiClient private method in PatchedApiClient

---

python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/test_resource.py

Ensure we don't fetch lineage, schema information for workbooks that a user has indicated they want to filter out - previously even though we wouldn't return these objects we'd still perform some fetched for them.
Mock & check call count to make sure we only fetch workbook data when appropriate.
> [dagster-sigma] Workbooks filtered using a `SigmaFilter` no longer fetch lineage information.

[dagster-sigma] avoid fetching lineage info for filtered workbooks

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/experimental/conftest.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/experimental/test_resources.py

This PR reworks legacy resync method and implements it in the `FivetranClient`:
-  `start_resync` is added based on legacy `start_resync`
- `start_resync` leverages `_start_sync` introduced in #25911 
- a [resync in Fivetran](https://fivetran.com/docs/rest-api/api-reference/connectors/resync-connector) is historical data sync - the endpoint and result is different, but logic around how to call and handle a resync is the same as a sync.
- a resync can be done with or without resync parameters, using a different endpoint.
Tests mock the request API calls and make sure that all calls are made.
Additional unit tests with BK

[dagster-fivetran] Implement base resync method in FivetranClient

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/experimental/conftest.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/experimental/test_resources.py

This PR uses the sync and poll methods implemented in previous PRs to implement `sync_and_poll` in `FivetranClient`. This method will be used in a subsequent PR to materialize Fivetran assets.
Tests are added to test the full sync and poll behavior.
Additional unit tests with BK

[dagster-fivetran] Implement sync_and_poll method in FivetranClient

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/experimental/test_resources.py

This PR uses the resync and poll methods implemented in previous PRs to implement `resync_and_poll` in `FivetranClient`. This method will be used in a subsequent PR to materialize Fivetran assets.
Tests are added to test the full sync and poll behavior.
Additional unit tests with BK

[dagster-fivetran] Implement resync_and_poll method in FivetranClient

---

python_modules/libraries/dagster-looker/dagster_looker/api/dagster_looker_api_translator.py
python_modules/libraries/dagster-looker/dagster_looker_tests/api/test_build_defs.py

Right now, the object-specific methods of `get_asset_spec` call other object-specific methods to generate deps, meaning that if a user overrides `get_asset_spec` it is not properly called in these cases.
Update unit test to ensure deps are properly prefixed

[dagster-looker] Fix calling lower-level spec methods for deps

---

python_modules/dagster/dagster/__init__.py
python_modules/dagster/dagster/_components/__init__.py
python_modules/dagster/dagster/_components/impls/python_script_component.py
python_modules/dagster/dagster/_generate/templates/COMPONENT_TYPE/COMPONENT_TYPE_NAME_PLACEHOLDER.py.jinja
python_modules/dagster/dagster_tests/components_tests/code_locations/python_script_location/scripts/script_one.py
python_modules/dagster/dagster_tests/components_tests/code_locations/python_script_location/scripts/script_two.py
python_modules/dagster/dagster_tests/components_tests/test_python_script_component.py

This stands up the python API for instantiating a component, and provides a sample implementation. Upstack, utilities are provided for instantiating a component from a config blob.
Also provides a ComponentCollection class, which is a generic way to encapsulate multiple components of the same type. This becomes more useful in the config-based instantiation paths.
NOCHANGELOG

[components] Basic PythonScript component implementation

---

python_modules/dagster/dagster/_components/__init__.py
python_modules/dagster/dagster/_components/impls/python_script_component.py
python_modules/dagster/dagster_tests/components_tests/test_python_script_component.py

This adds a separate construction path for Components, which takes a dictionary of config that conforms to the class's config schema.
Because there's no generalized way to auto-generate a config schema or a conversion function, I think we'll end up relying in most cases on users subclassing an iniital simple implementation that just allows for some configured specs and maybe some unstrctured params, hence the AssetsComponent.

[components] Add ability to load a component using config

---

python_modules/dagster/dagster/_core/definitions/automation_tick_evaluation_context.py
python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py

Fixes https://github.com/dagster-io/dagster/issues/25328.
Currently, when asset backfills launch, all the checks for the selected assets are executed. However, these checks aren't explicitly included on the `asset_check_selection` property of the `DagsterRun`.  A consequence of this is that, when the run is re-executed, the asset checks aren't included in the subset job, which causes the error described in the issue linked above.
This problem points to some deeper mismatched assumptions that would be good to fix as well.  I.e. it seems like we should either:
- be stricter about the selections included on runs in general
- be looser about how we construct subsetted jobs when doing re-execution
Ran through the reproduction steps listed on https://github.com/dagster-io/dagster/issues/25328 …

explicitly include asset check selection on backfill runs

---

python_modules/dagster/dagster/_components/__init__.py
python_modules/dagster/dagster/_components/impls/python_script_component.py
python_modules/dagster/dagster_tests/components_tests/code_locations/python_script_location/scripts/defs.yml
python_modules/dagster/dagster_tests/components_tests/test_python_script_component.py

This allows us to use the config loading system to load components from a path directly. All `defs.yaml` files conform to the same schema of:
```yaml
component_type: <component type>
component_params: <component-specific params>
```
NOCHANGELOG

[components] Add ability to load directly from path

---

python_modules/dagster/dagster/_core/storage/event_log/sqlite/consolidated_sqlite_event_log.py
python_modules/dagster/dagster/_core/storage/event_log/sqlite/sqlite_event_log.py
python_modules/dagster/dagster_tests/cli_tests/command_tests/test_concurrency_command.py

With the WAL enabled on SQLite, global op concurrency should be supported on the default SQLite storage.
BK
Enables global op concurrency on the default SQLite storage.  Deployments that have not been migrated since `1.6.0` may need to run `dagster instance migrate` to enable.

Enable global op concurrency on default sqlite storage

---

examples/temp_pins.txt
python_modules/libraries/dagster-snowflake/setup.py

Summary:
Workaround for breaking pin change in the snowflake-connector-python package - see linked issue
Test Plan:
BK (assets_smoke_test should now pass)

Add pyopenssl pin to dagster-snowflake to work around breaking upstream package change

---

python_modules/libraries/dagster-powerbi/dagster_powerbi/translator.py

Like #26028 but for Power BI
[dagster-powerbi] `DagsterPowerBITranslator.get_asset_key` is deprecated in favor of `DagsterPowerBITranslator.get_asset_spec().key`

[dagster-powerbi] Mark asset key methods as deprecated in DagsterPowerBITranslator

---

python_modules/dagster/dagster/_components/__init__.py
python_modules/dagster/dagster/_components/impls/python_script_component.py
python_modules/dagster/dagster_tests/components_tests/code_locations/python_script_location/scripts/defs.yml
python_modules/dagster/dagster_tests/components_tests/test_python_script_component.py

This removes the ComponentCollection concept, and replaces it with a FileCollectionComponent, which is just a subclass that makes it easier to do per-file operations.
My feeling was that the ComponentCollection thing was over-specified, and added a weird layer of indirection to the system. As can be seen in the diff, this change made implementation a fair amount simpler for a variety of things, while not making the PythonScript component implementation much different.
The key thing here is that it feels very unlikely that someone would want to use a given component type both within and without of a Collection wrapper (i.e. if it's designed to go inside a Collection, it will always be in a collection). If that's the case then we should just have them define the collection component …

[components] Remove nested component concept, pass path directly through init_context

---

python_modules/dagster/dagster/_components/__init__.py
python_modules/dagster/dagster/_components/cli/generate.py
python_modules/dagster/dagster/_generate/generate.py
python_modules/dagster/dagster_tests/cli_tests/test_generate_commands.py

Prior to this PR, component types would get registered as `module.path[component-type-name]`. This PR changes it to just `component-type-name`. I don't think this is a final decision, but this is a useful simplification for now since it allows us to punt on decisions about the module name for locally defined components.

[components] Change registered component name to just Component.registered_name

---

integration_tests/test_suites/daemon-test-suite/auto_run_reexecution_tests/test_auto_run_reexecution.py
python_modules/dagster/dagster/_core/storage/tags.py
python_modules/dagster/dagster/_daemon/auto_run_reexecution/auto_run_reexecution.py

Adds a `dagster/auto_rety_run_id=<run_id>` tag to any run that had a retry launched by the auto run reexecution daemon. This allows us to determine if a run is waiting to be retried by looking at the values of `dagster/will_retry` and `dagster/auto_rety_run_id` 
Examples:
`dagster/will_retry=False` - no retry will be launched for this run
`dagster/will_retry=True` - a retry will be launched for this run, but has not been launched yet
`dagster/will_retry=True` and `dagster/auto_rety_run_id=<run_id>` - a retry has been launched for this run
associated internal pr https://github.com/dagster-io/internal/pull/12787

[auto run retry tags] 3/n - when a run is retried, add the`auto_retry_run_id` tag

---

python_modules/dagster/dagster/_record/__init__.py

Currently `@record` objects do not display nicely in the vscode debugger since it tries to iterate over namedtuples to display all their fields. 
To fix that this PR just leaves iteration on when a debugger env var is present. 
pause in the VSCode debugger and be able to see the values inside a `@record`

[record] allow iteration in debugger

---

js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillAssetPartitionsTable.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillOpJobPartitionsTable.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/backfill/__tests__/BackfillPage.test.tsx
js_modules/dagster-ui/packages/ui-core/src/partitions/PartitionStatus.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedRow.tsx

Related: https://linear.app/dagster-labs/issue/FE-689/backfill-ui-partition-range-display-issue
This is a handful of small fixes for the backfill partitions pages:
- These tags were rendering full-width, and the terminology (succeeded vs completed) was inconsistent. Clicking it takes you to a view of Succeeded runs, so I changed both to succeeded:
- On this page, the two gray colors used in the bars were very similar, which was confusing - now using `backgroundDisabled()`:
- When viewing a backfill, there is a color bar that is not related to the color bars above - it indicates the success or failure of the _subset of partitions you chose to backfill_. This can be sorta confusing (why does this bar not have the gray bands from the previous screenshot?).  I added a small caption: "100% …

[ui] FIx backfill partition range coloring, clarify meaning of progress bars

---

python_modules/dagster-pipes/dagster_pipes/__init__.py

Adding new abstract classes for `PipesLogWriter` Pipes component. 
This is meant to be an escape hatch for execution environments which don't have a clean way of accessing logs, such as Databricks or AWS EMR. 
More tests involving Dagster are in upstack.
Added a new Dagster Pipes component - `PipesLogWriter`.

[pipes] add PipesLogWriter

---

python_modules/dagster-pipes/dagster_pipes/__init__.py
python_modules/dagster-pipes/dagster_pipes_tests/test_log_writer.py

This PR adds:
- `PipesStdioLogWriter` - an partial implementation for `PipesLogWriter` abstract class which captures stdout/err of the current process. It doesn't handle writing logs, only capturing. Child classes should implement writing.
- `PipesStdioFileLogWriter` - an implementation for `PipesStdioLogWriter` which writes logs to the local filesystem (to a given directory)
---
The solution relies on `tee` command so only works on Linux and MacOS. This is required for real-time logs capturing because `tee` creates a normal file where stdout/stderr is duplicated, and it's possible to read from this file immediately (in oppose to other methods such as just running `os.dup2`).  
Added tests
Added a test. Tests for the Dagster side are upstream.
No changelog

[pipes] add PipesStdioLogWriter

---

python_modules/dagster-pipes/dagster_pipes/__init__.py
python_modules/dagster-pipes/dagster_pipes_tests/test_log_writer.py
python_modules/dagster/dagster/_core/pipes/context.py
python_modules/dagster/dagster/_core/pipes/subprocess.py
python_modules/dagster/dagster/_core/pipes/utils.py
python_modules/dagster/dagster_tests/execution_tests/pipes_tests/test_log_writer.py

This PR adds a new `PipesDefaultLogWriter` which writes stdout/stderr via the `PipesMessageWriter` messages. 
It emits messages of a new type `log_external_stream`.  
Added tests
[dagster-pipes] Experimental: A new Dagster Pipes message type `log_external_stream` has been added. It can be used to forward external logs to Dagster via Pipes messages.

[pipes] add PipesDefaultLogWriter (send logs via Pipes messages)

---

python_modules/dagster-pipes/dagster_pipes/__init__.py
python_modules/dagster-pipes/dagster_pipes_tests/test_log_writer.py
python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/emr.py
python_modules/libraries/dagster-aws/dagster_aws/pipes/message_readers.py

Add a new `include_stdio_in_messages` parameter to `PipesS3MessageReader`. It enables log forwarding to Dagster via Pipes messages. 
Executed a real AWS EMR job and confirmed we are getting the logs
[dagster-pipes, dagster-aws] `PipesS3MessageReader` now has a new parameter `include_stdio_in_messages` which enables log forwarding to Dagster via Pipes messages.

[pipes] use PipesDefaultLogWriter for AWS EMR

---

python_modules/libraries/dagster-aws/dagster_aws_tests/pipes_tests/test_pipes.py

Fixing a flaky `PipesCloudWatchMessageReader` which fails sometimes due to race conditions in writing and reading cloud watch events

[dagster-aws] fix flaky PipesCloudWatchMessageReader test

---

examples/experimental/components/examples/hello_world_deployment/code_locations/hello_world/hello_world/definitions.py
python_modules/dagster/dagster/_components/__init__.py
python_modules/dagster/dagster/_components/impls/python_script_component.py

Removing `LoadableComponent` and `FileCollectionComponent` as I think these are quite overfit right now and just add layers of indirection for little value. I think we need to get more variants of components implemented before we build layers of abstractions.
Load hello world

[components] Remove class hierarchy from components for now

---

examples/experimental/components/examples/hello_world_deployment/code_locations/hello_world/hello_world/components/a_script_collection/defs.yml
examples/experimental/components/examples/hello_world_deployment/code_locations/hello_world/hello_world/definitions.py
python_modules/dagster/dagster/_components/impls/pipes_subprocess_script_collection.py
python_modules/dagster/dagster_tests/components_tests/code_locations/python_script_location/scripts/defs.yaml
python_modules/dagster/dagster_tests/components_tests/test_pipes_subprocess_script_collection.py

Renames PythonScriptCollection to PipesSubprocessScriptCollection which is more accurate and specific. Also have it provide its own pipes client for now for convenience.
dagster dev hello and BK

[components] Rename to be pipes-specific and provide resource out of the box

---

python_modules/dagster/dagster/_components/__init__.py
python_modules/dagster/dagster/_components/impls/pipes_subprocess_script_collection.py
python_modules/dagster/dagster/_core/definitions/definitions_class.py

While we are developing this thing I want to silence experimental warnings.
* Added scoped warning filter around `AssetSpec` construction
* Added `Definitions.merge_internal` for internal use cases.
`dagster dev` in hello world. no warnings seen.

[components] Silence experimental warnings in components code paths in development

---

python_modules/dagster/dagster/_components/impls/pipes_subprocess_script_collection.py
python_modules/dagster/dagster_tests/components_tests/code_locations/python_script_location/components/scripts/defs.yml
python_modules/dagster/dagster_tests/components_tests/test_pipes_subprocess_script_collection.py

This changes `PipesSubprocessScriptCollection` to rely less on automatic registration of scripts and instead relies on more explicit configuration. The behavior was really unexpected and there is no way to opt out of it (e.g. if there is a shared python file for common code).
I think we re-add some autodiscovery capabilities but built on this foundation.
BK

[components] Explicit schema for PipesSubprocessScriptCollection

---

python_modules/dagster/dagster/_components/core/component_defs_builder.py
python_modules/dagster/dagster/_components/impls/pipes_subprocess_script_collection.py
python_modules/dagster/dagster/_core/definitions/definitions_class.py

Addressing feedback in https://github.com/dagster-io/dagster/pull/26201
* Use `suppress_dagster_warnings` instead of `warnings`
* Do not have `Definitions.merge_internal`.
BK

[components] Remove Definitions.merge_internal. Use suppress_dagster_warnings

---

docs/content/dagster-plus/deployment/agents/amazon-ecs/configuration-reference.mdx

Fix a field name that is inconsistent with code and other configuration reference for agent queues configuration. 
- Validated looking at code and other example
> NOCHANGELOG

docs: fix agent queues property in ECS config reference

---

python_modules/dagster/dagster_tests/components_tests/test_pipes_subprocess_script_collection.py

Changing this test to run against ephemeral instance. It was running against the default system before which leaves file system turds if you do not have DAGSTER_HOME set
Local test run. Saw no file system turds.

[components] [easy] Use ephemeral instance in test

---

js_modules/dagster-ui/packages/ui-core/src/instigation/TickDetailsDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/instigation/TickHistory.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/TickTagForRun.tsx
js_modules/dagster-ui/packages/ui-core/src/ticks/TickLogDialog.tsx

Users have found it a bit confusing that sensor tick logs are buried under an extra click under the "N materializations requested" button-link. Move these out into their own dialog, opened via a "View logs" button in the table.
Plus a couple other changes I made while in there:
- Middle-truncate the cursor value, which is currently long and may or may not wrap, depending on its contents.
- Clean up some loading and empty states in the dialogs.
View a running sensor. Verify that the "View logs" button is present in the row, and opens the dialog correctly. Verify with forced dialog height that the logs table is scrollable, and that the footer sits on top of the log table lines.
Verify that the cursor is middle-truncated, and that loading and empty states look correct for various ticks.
[ui] …

[ui] Separate sensor logs into their own dialog

---

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt_tests/dlt_tests/dlt_test_sources/duckdb_with_transformer.py
python_modules/libraries/dagster-embedded-elt/setup.py

Removes hard-coded double underscore `table_name` in example `@transformer`; this is a reserved naming convention for children tables by `dlt` and causes unwanted behavior in metadata extraction for primary tables. This will likely, or should not, exist in real-world scenarios.
pytest / bk

[dagster-embedded-elt][dlt] remove forced double-underscore in transformer

---

python_modules/dagster/dagster/_core/storage/upath_io_manager.py

Linear: https://linear.app/dagster-labs/issue/BUILD-32/change-copy-of-the-io-manager-does-not-support-single-run-backfills-to
Tweak `UPathIOManager` error message to advise users to opt out of IO managers by setting the return type to `None`.

Fix multi-partition IO manager message

---

python_modules/dagster/dagster/_utils/schedules.py
python_modules/dagster/dagster_tests/scheduler_tests/test_cron_string_iterator.py

Croniter validates these strings but they error when you try to iterate them, since they produce no dates. Instead, fail them at definition time.
BK
Fixed an issue where invalid cron strings like "0 0 30 2 *" that represented invalid dates in February were still allowed as Dagster cron strings, but then failed during schedule execution. Now, these invalid cronstrings will raise an exception when they are first loaded.

Disallow 2/30 and 2/31 cronstrings

---

python_modules/libraries/dagster-aws/dagster_aws_tests/pipes_tests/test_pipes.py

Looks like Moto's `put_log_events` does not guarantee correct ordering for multiple calls.

[dagster-aws] stabilize flaky cloudwatch message reader test

---

python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py

This updates the `default_code_version_fn` in `dagster-dbt` to read from `dbt_resource_props["checksum"]["checksum"]` if available (suggested [here](https://github.com/dagster-io/dagster/pull/25387#issuecomment-2474701457)). This gives dbt seeds a valid model version.
An alternative implementation could be to always read from the checksum field and ignore the `raw_sql` and `raw_code` fields. This would simplify the code version getter, but this would cause all current code versions of dbt models to be updated. Perhaps something for a breaking release?
Closes https://github.com/dagster-io/dagster/issues/25947
Added test
`dagster-dbt` now gives dbt seeds a valid code version

[dagster-dbt] updates `default_code_version_fn` to take from dbt checksum if available

---

js_modules/dagster-ui/packages/ui-core/src/ui/TagActions.tsx

Fix the structure and styles of links within the tag actions popover. Namely, links are rendered outside `button` elements, which isn't valid, and the separation border doesn't render correctly.
Before:
After:
Hover on tag actions on a run tick tag.

[ui] Fix styles for tag actions link

---

examples/experimental/dagster-components/dagster_components/impls/sling_replication.py
examples/experimental/dagster-components/dagster_components_tests/stub_code_locations/sling_location/components/ingest/defs.yml
examples/experimental/dagster-components/dagster_components_tests/stub_code_locations/sling_location/components/ingest/replication.yaml
examples/experimental/dagster-components/dagster_components_tests/stub_code_locations/sling_location/input.csv
examples/experimental/dagster-components/dagster_components_tests/test_pipes_subprocess_script_collection.py
examples/experimental/dagster-components/dagster_components_tests/test_sling_replication.py
examples/experimental/dagster-components/dagster_components_tests/utils.py
examples/experimental/dagster-components/setup.py
examples/experimental/dagster-components/tox.ini

This implements a basic SlingReplicationComponent, which does a few things:
1. On generation, creates a mostly-empty `replication.yaml` file
2. Uses the existing sling_assets decorator to build an AssetsDefinition based on this replication.yaml file
3. Configures connection info based off of information stored in the `defs.yaml` file
This final bit is the first toe in the water of resource configuration handling. In this case, I just embed the resource directly into the config schema, which works out quite nicely in practice.
It's a bit tricky to set up tests for this, as we need to create a temporary directory so that there's an absolute path that we can reference in the stream config. Set up a fixture for this purpose
NOCHANGELOG

Basic SlingReplicationComponent

---

examples/experimental/dagster-components/dagster_components/__init__.py
examples/experimental/dagster-components/dagster_components/cli/generate.py
examples/experimental/dagster-components/dagster_components/core/component.py
examples/experimental/dagster-components/dagster_components/impls/sling_replication.py
examples/experimental/dagster-components/dagster_components/templates/COMPONENT_INSTANCE_NAME_PLACEHOLDER/defs.yml.jinja
examples/experimental/dagster-components/dagster_components_tests/cli_tests/test_generate_commands.py
examples/experimental/dagster-components/dagster_components_tests/test_sling_replication.py
examples/experimental/dagster-components/setup.py
examples/experimental/dagster-components/tox.ini

As title. Does two things:
1. create a global component registry with some hard-coded components pre-loaded
2. adds a template for generating instances of a component
```
dg generate deployment my_deployment
cd my_deployment
dg generate code-location my_location
cd my_location
dg generate component sling_replication file_ingest
```
, also a unit test which does the same
NOCHANGELOG

Add CLI support

---

python_modules/dagster/dagster/_core/definitions/schedule_definition.py
python_modules/dagster/dagster_tests/definitions_tests/test_schedule.py

Linear: https://linear.app/dagster-labs/issue/BUILD-435/fix-scheduledefinitionwith-updated-job
Make `ScheduleDefinition.with_updated_job` correctly copy the `tags` on the `ScheduleDefinition`.
New unit test.

[bugfix] Make ScheduleDefinition.with_job pass tags correctly

---

js_modules/dagster-ui/packages/ui-core/src/asset-selection/AntlrAssetSelection.ts
js_modules/dagster-ui/packages/ui-core/src/asset-selection/__tests__/AntlrAssetSelection.test.ts
js_modules/dagster-ui/packages/ui-core/src/gantt/__tests__/toGraphQueryItems.test.ts
js_modules/dagster-ui/packages/ui-core/src/gantt/toGraphQueryItems.tsx
js_modules/dagster-ui/packages/ui-core/src/run-selection/AntlrRunSelection.ts
js_modules/dagster-ui/packages/ui-core/src/run-selection/AntlrRunSelectionVisitor.ts
js_modules/dagster-ui/packages/ui-core/src/run-selection/__tests__/AntlrRunSelection.test.ts

We now want to implement the visitor methods for `RunSelectionVisitor`. This requires having access to the metadata for each run to get the status. This is not available on type `GraphQueryItem`, so a new type `RunGraphQueryItem` was added to include the metadata.
`AntlrRunSelection.test.ts`

Implement AntlrRunSelectionVisitor on frontend

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_partition_backfill.py

Had an error cause these tests to hang indefinitely, prevent that from happening again
bk

[graphql] defend against hang in backfill test

---

python_modules/libraries/dagster-k8s/dagster_k8s/launcher.py

Summary:
This callsite was correctly gated in the other places it is called, but we missed the one in terminate. Consolidate calsites so that anything that might need to fetch this information checks whether the experimental run resume feature is enabled or not.
[dagster-k8s] Fixed an issue where run termination sometimes timed out when terminating runs with many events.

Fix callsite in k8s run launcher termination where we were making an unneeded and potentially expensive event log fetch

---

python_modules/dagster/dagster/_core/definitions/asset_graph_subset.py
python_modules/dagster/dagster/_core/execution/asset_backfill.py
python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py

The backfill daemon doesn't account for run retries. See https://github.com/dagster-io/internal/discussions/12460 for more context. We've decided that we want the daemon to account for automatic and manual retries of runs that occur while the backfill is still in progress. This requires two changes: ensuring the backfill isn't marked completed if there is an in progress run or a failed run that will be automatically retried; and updating the daemon to take the results of retried runs into account when deciding what partitions to materialize in the next iteration.
This PR addresses the second point, updating the backfill daemon to take the results of retried runs into account when deciding what partitions to materialize in the next iteration.
Currently the backfill gets a list of the …

[backfill daemon run retries 2/n] backfill daemon incorporates retries runs when launching new runs

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/__init__.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_decorator.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/translator.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/experimental/conftest.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/experimental/test_asset_specs.py

This PR implements the `fivetran_assets` decorator and the `build_fivetran_assets_definitions` factory.
- `fivetran_assets` can be used to create all assets for a given Fivetran connector, i.e. one asset per table in the connector.
- `build_fivetran_assets_definitions` can be used to create all Fivetran assets defs, one per connector. It uses `fivetran_assets`.
Both the asset decorator and factory use `load_fivetran_asset_specs`. This is motivated by the current implementation of `dagster-dbt`, `dagster-dlt` and `dagster-sling` - each leverages an asset decorator that loads the asset specs by itself.
To avoid calling the Fivetran API each time `load_fivetran_asset_specs` is called, it is cached using `functools.lru_cache`. `load_fivetran_asset_specs` uses the state-backed defs, so …

[10/n][dagster-fivetran] Implement fivetran_assets and build_fivetran_assets_definitions

---

js_modules/dagster-ui/packages/ui-components/CHANGES.md
js_modules/dagster-ui/packages/ui-components/package.json

Bump ui-components lib to 1.2.0 following the styled-components upgrade.
`yarn build` to verify correct build output locally.

[ui] Bump ui-components version to 1.2.0

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetTable.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx

We added asset selection based filtering to the catalog page but need to make sure the page properly waits for that filtering to occurring
app-proxy

Fix asset catalog loading state showing "No assets found" while asset selection filtering is loading.

---

integration_tests/test_suites/daemon-test-suite/auto_run_reexecution_tests/test_auto_run_reexecution.py

Adds some additional test cases to our auto re-execution test suite to test for things like daemon failures at specific points in the iteration

add more tests for auto reexecution behavior

---

.buildkite/dagster-buildkite/dagster_buildkite/pipelines/dagster_oss_nightly_pipeline.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/integration.py
docs/content/deployment/dagster-instance.mdx
examples/docs_snippets/docs_snippets/deploying/dagster_instance/dagster.yaml
helm/dagster/schema/schema/charts/dagster/subschema/compute_log_manager.py
helm/dagster/schema/schema_tests/test_instance.py
helm/dagster/templates/helpers/instance/_compute-log-manager.tpl
helm/dagster/values.schema.json
helm/dagster/values.yaml
integration_tests/test_suites/dagster-azure-live-tests/azure_test_proj/defs.py
integration_tests/test_suites/dagster-azure-live-tests/dagster.yaml
integration_tests/test_suites/dagster-azure-live-tests/integration_tests/conftest.py
integration_tests/test_suites/dagster-azure-live-tests/integration_tests/test_compute_log_manager.py
integration_tests/test_suites/dagster-azure-live-tests/setup.py
integration_tests/test_suites/dagster-azure-live-tests/tox.ini
python_modules/libraries/dagster-azure/dagster_azure/blob/compute_log_manager.py
python_modules/libraries/dagster-azure/dagster_azure/blob/fake_blob_client.py
python_modules/libraries/dagster-azure/dagster_azure_tests/blob_tests/test_compute_log_manager.py

Azure integrations aren't under live test anywhere. This fixes by introducing a test suite for running against live azure.
To start, test the compute log manager against live azure. 
I based a lot of these components on what we built for airlift/dlift - specifically fixtures for standing up airflow, dagster, etc. that could probably live in a shared module somewhere. 
An important consideration here is we don't want to take a dependency across all our builds on azure. So **this new test suite will only run when on a branch that touches dagster-azure, or on the nightly oss build.** 
New tests

[dagster-azure] live tests

---

integration_tests/test_suites/dagster-azure-live-tests/integration_tests/test_compute_log_manager.py
python_modules/libraries/dagster-azure/dagster_azure/blob/compute_log_manager.py
python_modules/libraries/dagster-azure/dagster_azure/blob/fake_blob_client.py

See comments for additional context.
This PR changes the Azure compute log manager to generate a URL by default instead of capturing the logs.
There's a few considerations here:
- If the blob storage is private, the url will not be publicly accessible. Instead you'll have to go to the azure portal and type in the url - I think this is fine to start.
- We need to make this configurable.
Switches the tests to pull out the stdout/stderr urls and read the results.
**This changes the test behavior from the previous PR**.  We were previously reading stdout and stderr in reverse (pulling them out of a list of arbitrary order instead of ensuring we were reading the correct file). So the stdout and stderr readouts flip in this PR, as is to be expected.

[dagster-azure] Generate URL from compute log manager

---

docs/content/_navigation.json
docs/content/dagster-plus/deployment/azure/aks-agent.mdx
docs/content/dagster-plus/deployment/azure/overview.mdx

This PR is the first in a stack creating a "zero to one" guide for deploying Dagster on azure infrastructure. The idea is to make Dagster on azure feel more first class and provide a richly linked, linear, guided experience for setting up a deployment. Everything from initial agent setup to CI/CD to compute logs.
Adds initial docs on setting up an AKS agent. Includes the azure specific incantations necessary to get kubectl working + stand up the helm chart on an AKS cluster (including perms).
I would like someone more knowledgeable than me on K8s best practices to vet what I've written here and make sure we're not walking people into security issues.

[azure-docs][rfc] docs on setting up AKS agent

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/experimental/test_asset_specs.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/experimental/test_translator.py

Updates load_fivetran_asset_specs() and state-backed definitions to accept an instance of `DagsterFivetranTranslator`.
See more about the motivation in the original thread [here](https://github.com/dagster-io/dagster/pull/25944#issuecomment-2495112807).
Additional unit tests to test custom translators with BK
[dagster-fivetran] `load_fivetran_asset_specs` is updated to accept an instance of `DagsterFivetranTranslator` or custom subclass.

[dagster-fivetran] Use Fivetran translator instance in load specs fn and state-backed defs

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/resources.py

Builds out a very barebones resource and client classes for the new version of the Airbyte cloud integration.
Tests will be added in subsequent PRs.

[1/n][dagster-airbyte] Scaffold AirbyteCloudWorkspace and AirbyteClient for rework

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/resources.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/translator.py

Builds out a very barebones translator and props classes for the new version of the Airbyte cloud integration.
Tests will be added in subsequent PRs.

[2/n][dagster-airbyte] Scaffold DagsterAirbyteTranslator for rework

---

js_modules/dagster-ui/packages/ui-core/src/workspace/RepositoryLocationErrorDialog.tsx

Used in https://github.com/dagster-io/internal/pull/12903 for cases where we're showing a historical error, not a current error (which might prompt a reload)

[ui] make reload button on RepositoryLocationErrorDialog optional

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/__init__.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/resources.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/experimental/conftest.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/experimental/test_resources.py

This PR implements the base `_make_request` method for AirbyteCloudClient and the methods that are required to handle the creation of the access token.
About the access token, the logic was taken and reworked from this [previous implementation](https://github.com/dagster-io/dagster/pull/23451). TL;DR, Airbyte now requires a client ID and secret to generate an access token - this access token expires every 3 minutes. See more [here](https://reference.airbyte.com/reference/portalairbytecom-deprecation).
Additional tests

[3/n][dagster-airbyte] Implement base request method in AirbyteCloudClient

---

examples/experimental/dagster-components/dagster_components/core/component_decl_builder.py
examples/experimental/dagster-components/dagster_components/core/component_defs_builder.py
examples/experimental/dagster-components/dagster_components_tests/test_pipes_subprocess_script_collection.py

This refactoring makes these functions more generic, so you can create `Definitions` and load components at arbitrary spots in the component hiearchy
BK

[components] Refactor definition buider code to operate on nodes rather than folders

---

python_modules/libraries/dagster-dbt/tox.ini

Summary:
[test-all] The removal of our protobuf pin caused us to hit an issue where older dbt-core 1.7 versions were missing their own protobuf pin.
Test Plan: BK

[test-all] Add 1.7 dbt-core lower bound pin

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/resources.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/experimental/conftest.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/experimental/test_resources.py

This PR implements the `get_connections`, `get_connection_details` and `get_destination_destails` in the `AirbyteCloudClient`.
Note that we need to use the [internal Airbyte Configuration API](https://airbyte-public-api-docs.s3.us-east-2.amazonaws.com/rapidoc-api-docs.html#overview) to get the stream configs in the connection details. The other methods are using the public REST API.
Additional unit tests with BK

[4/n][dagster-airbyte] Implement connection and destination methods in AirbyteClient

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/resources.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/translator.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/experimental/test_asset_specs.py

This PR implements `AirbyteCloudWorkspace.fetch_airbyte_workspace_data`, that fetches the connections and destinations included in a given workspace.
Additional unit tests with BK.

[5/n][dagster-airbyte] Implement fetch_airbyte_workspace_data

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/__init__.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/resources.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/translator.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/experimental/test_asset_specs.py

This PR implements the `load_airbyte_cloud_asset_specs` function:
```python
from dagster_airbyte import AirbyteCloudWorkspace, load_airbyte_cloud_asset_specs
airbyte_cloud_workspace = AirbyteCloudWorkspace(
workspace_id=dg.EnvVar("AIRBYTE_CLOUD_WORKSPACE_ID"),
client_id=dg.EnvVar("AIRBYTE_CLOUD_CLIENT_ID"),
client_secret=dg.EnvVar("AIRBYTE_CLOUD_CLIENT_SECRET"),
)
airbyte_cloud_specs = load_airbyte_cloud_asset_specs(airbyte_cloud_workspace)
defs = dg.Definitions(assets=airbyte_cloud_specs, resources={"airbyte": airbyte_cloud_workspace}
```
Additional unit test
[dagster-airbyte] The `load_airbyte_cloud_asset_specs` function is added. It can be used with the `AirbyteCloudWorkspace` resource and `DagsterAirbyteTranslator` translator to load your Airbyte Cloud connection …

[8/n][dagster-airbyte] Implement load_airbyte_cloud_asset_specs

---

examples/experimental/dagster-components/dagster_components/cli/generate.py
examples/experimental/dagster-components/dagster_components/core/component.py
examples/experimental/dagster-components/dagster_components/generate.py
examples/experimental/dagster-components/dagster_components/impls/dbt_project.py
examples/experimental/dagster-components/dagster_components/templates/COMPONENT_INSTANCE_NAME_PLACEHOLDER/defs.yml.jinja
examples/experimental/dagster-components/setup.py
examples/experimental/dagster-components/tox.ini

Reworks https://github.com/dagster-io/dagster/pull/26283/files to be less fancy.
Just a generic json blob that gets passed through params. Future PR will add an alternative entrypoint with fancier behavior so you don't have to pass in raw json.
```
dg generate component dbt_project my_project --params "{\"project_path\": \"../../../dagster/\"}"
```
NOCHANGELOG

[components] Allow generate_files to be paramterized

---

examples/experimental/dagster-components/dagster_components/impls/sling_replication.py
examples/experimental/dagster-components/dagster_components_tests/integration_tests/test_sling_integration_test.py

Similar to #26319 but for tags.
Note how this passes through to `op_tags` whereas the #26319 passed through to `name`. Nesting under `op:` makes it much more clear what is going on
BK

[components] Allow for the parameterization of op tags

---

examples/experimental/dagster-components/dagster_components_tests/integration_tests/test_dbt_project.py

Moving slow-running `test_dbt_project.py` to the `integration_tests` folder.
BK

[components] Move test_dbt_project.py into integration+_tests

---

.buildkite/dagster-buildkite/dagster_buildkite/pipelines/dagster_oss_nightly_pipeline.py

Similar to on regular oss test suite we need to use the docker queue here; this test is pretty beefy.
Successful run: https://buildkite.com/dagster/full-moon-with-face-dagster-nightly/builds/252#01939d1d-7357-4208-80c7-e4f529d72397

[dagster-airlift] Fix demo on oss nightly pipeline

---

python_modules/libraries/dagster-components/dagster_components/cli/generate.py
python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components/impls/dbt_project.py
python_modules/libraries/dagster-components/dagster_components_tests/cli_tests/test_generate_commands.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_dbt_project.py

Allows you to pass arguments to an underlying cli invocation, rather than via a raw json blob
For now, we don't do any auto-generation of the parameter schema for the cli invocation. There are existing libraries that do this sort of thing (convert pydantic models to click commands), which we could potentially consider hooking into.
```
dg generate component dbt_project my_project -- --project-path abc
dg generate component dbt_project my_project -- --init
```
NOCHANGELOG

[components] Nicer parameter handling

---

python_modules/libraries/dagster-components/dagster_components/core/dsl_schema.py
python_modules/libraries/dagster-components/dagster_components/impls/dbt_project.py
python_modules/libraries/dagster-components/dagster_components/impls/sling_replication.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_dbt_project.py
python_modules/libraries/dagster-dbt/dagster_dbt/dbt_project.py

See title. This also moves `OpSpecBaseModel` to core/dsl_schema for reuse.
BK

[components] Make op name and tags configurable on DbtProjectComponent

---

python_modules/dagster/dagster/_cli/project.py

Fix breaking scaffolding tests. PyPI changed it's behavior so that hitting https://pypi.org/pypi/<package_name> ALWAYS returns a 200-- we were hitting this URL and ensuring the response was not 200 for the scaffolded package name to ensure no conflict with an already published package. That no longer works. However, the old semantics old if you just hit https://pypi.org/pypi/<package_name>/json instead.

Make PyPI existence check use /json suffix when scaffolding

---

python_modules/automation/automation_tests/telemetry/test_resource_telemetry.py
python_modules/libraries/dagster-components/dagster_components/__init__.py

Fix automation tests by adding `dagster-components` to the library registry.

[components] Add dagster-components to DagsterLibraryRegistry

---

python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py
python_modules/libraries/dagster-aws/dagster_aws/ecs/tasks.py

Looks like #23337 introduced a regression by checking if the user has set `DAGSTER_CURRENT_IMAGE` in the code location too early.
This image is not used when a task definition is provided directly by the user (instead of generating one automatically), so this check was too early. 
I moved the check to the appropriate location, provided correct type annotations for the `image` argument to prevent similar confusion in the future, and improved the exception message to be more explicit. 
Resolve #26138
[dagster-aws] Resolved a bug in the ECSRunLauncher that prevented it from accepting a user-provided task definition when DAGSTER_CURRENT_IMAGE was not set in the code location.

[dagster-aws] correctly use image from task definition in ECSRunLauncher

---

python_modules/dagster/dagster/__init__.py
python_modules/dagster/dagster/_core/definitions/asset_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/sensor_definition.py

Publicly export the union that defines valid `@sensor` function output.
bk
`SensorReturnTypesUnion` is now exported for typing the output of sensor functions

publicly export union of valid sensor return types

---

python_modules/dagster-graphql/dagster_graphql/implementation/execution/backfill.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_all_snapshot_ids.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_solids.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_partition_backfill.py
python_modules/dagster/dagster/_core/execution/asset_backfill.py
python_modules/dagster/dagster/_core/execution/backfill.py
python_modules/dagster/dagster/_core/execution/job_backfill.py

Canceling a job backfill just marks the backfill as canceled, but does nothing to the already launched runs. This gets us in an awkward situation with the new runs feed. A canceled backfill is not shown in the "in progress" tab, but it's launched runs could still be queued or in progress. This effectively hides a bunch of runs from the user.
This PR updates the canceling logic for job backfills to follow how asset backfills handle cancelation. The daemon will first ensure that all launched runs are marked canceled and in a terminal state before marking the backfill as canceled. 
This means that the backfill will be in a "CANCELING" state (and therefore appear in the "in progress" tab) until all of it's runs are canceled/finished 
When canceling a backfill of a job, the backfill daemon …

update job backfill canceling iteration

---

examples/project_du_dbt_starter/.gitignore

User reported that they were accidentally checking in `.duckdb` files to version control. This ensures that the `.gitignore` file in the starter has the appropriate ignores that are already present in the `project-dagster-university` repo.
Takes the `.gitignore` from the `project-dagster-university` repo:
https://github.com/dagster-io/project-dagster-university/blob/module/dagster-and-dbt-starter/.gitignore

[du] updates du dbt starter gitignore with standard ignores

---

js_modules/dagster-ui/packages/ui-core/src/ticks/EvaluateScheduleDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/ticks/SensorDryRunDialog.tsx

Linear: https://linear.app/dagster-labs/issue/FE-627/add-launch-all-frontend
Add "Launch all" button to these evaluation result modals
Tested locally

[2/n] [RFC] add 'Launch all' button on sensor/schedule evaluation result modals

---

js_modules/dagster-ui/packages/ui-core/src/automation/VirtualizedAutomationScheduleRow.tsx
js_modules/dagster-ui/packages/ui-core/src/automation/VirtualizedAutomationSensorRow.tsx
js_modules/dagster-ui/packages/ui-core/src/schedules/ScheduleDetails.tsx
js_modules/dagster-ui/packages/ui-core/src/sensors/SensorDetails.tsx
js_modules/dagster-ui/packages/ui-core/src/ticks/EvaluateTickButtonSchedule.tsx
js_modules/dagster-ui/packages/ui-core/src/ticks/EvaluateTickButtonSensor.tsx

Linear: https://linear.app/dagster-labs/issue/FE-628/add-manual-tick-button-to-all-rows-in-automations-table
Video:
https://github.com/user-attachments/assets/8a7993ff-babe-4fa2-8526-a448ef1e7c2b
yarn lint, ts, tested locally

[3/n] [RFC] add manual tick button to all rows in automation table

---

js_modules/dagster-ui/packages/ui-core/client.json
js_modules/dagster-ui/packages/ui-core/src/app/Telemetry.tsx
js_modules/dagster-ui/packages/ui-core/src/launchpad/useLaunchMultipleRunsWithTelemetry.ts
js_modules/dagster-ui/packages/ui-core/src/runs/RunUtils.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/types/RunUtils.types.ts
js_modules/dagster-ui/packages/ui-core/src/ticks/SensorDryRunDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/util/buildExecutionParamsList.ts

Linear: https://linear.app/dagster-labs/issue/FE-624/[fe]-implement-launch-all-frontend-sensor
Adds the frontend for 'launch all' for manual tick sensors
Video:
https://github.com/user-attachments/assets/222b35c2-19c7-4bb9-a975-85f9ae56c328
yarn ts, lint, make graphql

[5/n] [RFC] add launch all frontend functionality for sensors

---

js_modules/dagster-ui/packages/ui-core/src/launchpad/useLaunchMultipleRunsWithTelemetry.ts
js_modules/dagster-ui/packages/ui-core/src/ticks/EvaluateScheduleDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/ticks/EvaluateTickButtonSchedule.tsx
js_modules/dagster-ui/packages/ui-core/src/ticks/__tests__/EvaluateScheduleDialog.test.tsx
js_modules/dagster-ui/packages/ui-core/src/util/buildExecutionParamsList.ts

Linear: https://linear.app/dagster-labs/issue/FE-654/[fe]-implement-launch-all-frontend-schedule
Adds the frontend for 'launch all' for manual tick schedules
Video:
https://github.com/user-attachments/assets/1d3a9315-cc05-4142-8964-5e86e077403b
tested the launch all runs flow locally
yarn lint, ts, jest, generate-graphql in ui-core

[6/n] [RFC] add launch all frontend functionality for schedules

---

python_modules/libraries/dagster-dbt/dagster_dbt/include/pyproject.toml.jinja

This PR modifies the `dagster-dbt` to compatible with uv by modify a `pyproject.toml`. The pyproject.toml that generated by `dagster-dbt` is a bit different from the `dagster` is that the pyproject.toml didn't include `pytest` as an dev dependency.
Closes #26224 
1. Clone the jaffle_shop and follow the profile setup from https://docs.dagster.io/integrations/dbt/using-dbt-with-dagster/set-up-dbt-project.
2. In `python_modules/libraries/dagster-dbt`, run `typer dagster_dbt/cli/app.py run project scaffold --project-name hello_dbt --dbt-project-dir jaffle-shop-classic`. The `hello_dbt` should be generated successfully.
3. Open the `pyproject.toml` in `hello_dbt`, the dependencies (and optional-dependencies) and project information should be added.
4. Run the pipeline with `uv run --extra dev …

Make dagster-dbt project scaffold compatible with uv

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/translator.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/experimental/conftest.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/experimental/test_resources.py

Implements `get_columns_config_for_table` with tests, to be used #26110.

[dagster-fivetran] Implement get_columns_config_for_table in FivetranClient

---

js_modules/dagster-ui/packages/ui-core/src/assets/auto-materialization/GlobalAutomaterializationContent.tsx

In the global AMP view, the tick timeline is broken when paginating to older ticks. The (paginated) table view sets the parent's time range, but the time range isn't being used as a signal to refetch the list of ticks used by the timeline. Fix this with an effect.
View AMP overview for Discord. Page backward in time, verify that the timeline updates with the correct ticks displayed.
[ui] Fix global auto-materialize tick timeline when paginating.

[ui] Global AMP: Fix timeline pagination

---

js_modules/dagster-ui/packages/ui-core/src/ticks/DryRunRequestTable.tsx
js_modules/dagster-ui/packages/ui-core/src/ticks/__fixtures__/EvaluateScheduleDialog.fixtures.tsx
js_modules/dagster-ui/packages/ui-core/src/ticks/__fixtures__/SensorDryRunDialog.fixtures.tsx
js_modules/dagster-ui/packages/ui-core/src/ticks/__tests__/DryRunRequestTable.test.tsx
js_modules/dagster-ui/packages/ui-core/src/ticks/__tests__/EvaluateScheduleDialog.test.tsx
js_modules/dagster-ui/packages/ui-core/src/ticks/__tests__/SensorDryRunDialog.test.tsx
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_run_launcher.py

Linear: https://linear.app/dagster-labs/issue/FE-713/add-jest-tests-for-sensors-and-schedules
Adds jest tests for launch all
yarn jest, ts, lint

[11/n] [RFC] add jest tests

---

python_modules/dagster/dagster/_core/storage/event_log/sqlite/consolidated_sqlite_event_log.py

Consolidated SQLite storage is probably not used outside of tests, but we're probably hanging connections / locking db files because we're not using the context manager for connections in these table checks.
BK
- Fixed database locking bug for the `ConsolidatedSqliteEventLogStorage`, which is mostly used for tests.

use context manager for sqlite table connection

---

docs/content/_navigation.json
docs/content/integrations/airlift/operator-migration/kubernetes-pod-operator.mdx
docs/content/integrations/airlift/operator-migration/overview.mdx
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/k8s_eks_fake_example.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/kubernetes_pod_operator.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/using_k8s_pipes.py

Adds a guide on migrating the kubernetes pod operator to Dagster. The core idea is that the equivalent to the kubernetes pod operator is an asset in dagster which uses the k8spipesclient

[dagster-airlift] KubernetesPodOperator guide

---

docs/content/_navigation.json
docs/content/integrations/airlift/operator-migration/bash-operator-general.mdx
docs/content/integrations/airlift/operator-migration/overview.mdx
docs/content/integrations/airlift/operator-migration/python-operator.mdx
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/bash_operator_general.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/pyop_asset_shared.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/pyop_multi_asset_complete.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/python_operator.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/shared.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/using_pipes_subprocess.py

Adds a migration guide for the python operator. The idea is that a multi asset / asset decorated fxn is more or less equivalent in Dagster.

[dagster-airlift] Python operator docs

---

docs/content/_navigation.json
docs/content/integrations/airlift/airflow-dagster-equivalents.mdx
examples/docs_snippets/docs_snippets/integrations/airlift/equivalents/airflow_dag.py
examples/docs_snippets/docs_snippets/integrations/airlift/equivalents/airflow_data_interval.py
examples/docs_snippets/docs_snippets/integrations/airlift/equivalents/airflow_hook.py
examples/docs_snippets/docs_snippets/integrations/airlift/equivalents/airflow_sensor.py
examples/docs_snippets/docs_snippets/integrations/airlift/equivalents/airflow_task.py
examples/docs_snippets/docs_snippets/integrations/airlift/equivalents/airflow_xcom.py
examples/docs_snippets/docs_snippets/integrations/airlift/equivalents/custom_operator.py
examples/docs_snippets/docs_snippets/integrations/airlift/equivalents/dagster_asset.py
examples/docs_snippets/docs_snippets/integrations/airlift/equivalents/dagster_partition.py
examples/docs_snippets/docs_snippets/integrations/airlift/equivalents/dagster_resource.py
examples/docs_snippets/docs_snippets/integrations/airlift/equivalents/dagster_sensor.py
examples/docs_snippets/docs_snippets/integrations/airlift/equivalents/factory_asset.py
examples/docs_snippets/docs_snippets/integrations/airlift/equivalents/scheduled_asset.py
examples/docs_snippets/docs_snippets/integrations/airlift/equivalents/task_equiv_asset.py

This adds a page which discusses each airflow concept in detail and provides an equivalent example in Dagster.

[dagster-airlift] Airflow-dagster equivalents

---

docs/content/integrations/airlift/airflow-dagster-equivalents.mdx

There's a useful cheatsheet from the old Airflow docs site that I'm moving to the new equivalencies page.
There are a few edits that I'll need to make, and i'm doing that in a downstream.
For what it's worth, this page is not currently referenced by SEs:
https://dagsterlabs.slack.com/archives/C05NC7H3W1Y/p1732322179226279

[dagster-airlift] Move cheatsheet to equivalents page

---

python_modules/libraries/dagster-components/dagster_components/cli/generate.py
python_modules/libraries/dagster-components/dagster_components/generate.py
python_modules/libraries/dagster-components/dagster_components/templates/CODE_LOCATION_NAME_PLACEHOLDER/pyproject.toml.jinja
python_modules/libraries/dagster-components/dagster_components_tests/cli_tests/test_generate_commands.py
python_modules/libraries/dagster-components/setup.py

Add an `--use-editable-dagster` flag to `dg generate code-location`. This causes the command to read the `$DAGSTER_GIT_REPO_DIR` environment variable and set up the code location to use editable installs from this location. This is done by adding `tool.uv.sources` to the generated pyproject.toml:
```
[tool.uv.sources]
dagster = { path = "/path/to/dagster/python_modules/dagster", editable=true }
dagster-webserver = { path="/path/to/dagster/python_modules/dagster-webserver", editable=true }
dagster-pipes = { path="/path/to/dagster/python_modules/dagster-pipes", editable=true }
dagster-components = { path = "/path/to/dagster/python_modules/libraries/dagster-components", editable=true }
```
We may also wish a path to be passable on the command line, or for this to be somehow hidden from users …

[components] Add --use-editable-dagster to dg generate code-location

---

python_modules/libraries/dagster-components/dagster_components/core/deployment.py
python_modules/libraries/dg-cli/dg_cli/cli/__init__.py
python_modules/libraries/dg-cli/dg_cli/cli/list.py
python_modules/libraries/dg-cli/dg_cli/context.py
python_modules/libraries/dg-cli/dg_cli_tests/cli_tests/test_generate_commands.py
python_modules/libraries/dg-cli/dg_cli_tests/cli_tests/test_list_commands.py

Add some useful CLI commands for seeing what is available for scaffolding:
- `dg list code-locations`
- `dg list component-types`
- `dg list components`

[components] dg list

---

python_modules/libraries/dagster-components/dagster_components/generate.py
python_modules/libraries/dagster-components/dagster_components/lib/sling_replication.py
python_modules/libraries/dg-cli/dg_cli_tests/cli_tests/test_generate_commands.py

Status quo: `Component.generate_files()` could be defined with or without a `params` argument. Then it would get called with or without params depending on whether params were passed, rather than function sig.
Change: `Component.generate_files()` always takes `params`. `None` will be passed if you didn't pass any on the command line.
This fixed errors I was encountering in manual testing.
Unit tests + manually.

[components] Standardize generator param passing

---

js_modules/dagster-ui/packages/ui-core/jest/mocks/ComputeGraphData.worker.ts
js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/ComputeGraphData.ts
js_modules/dagster-ui/packages/ui-core/src/asset-graph/ComputeGraphData.types.ts
js_modules/dagster-ui/packages/ui-core/src/asset-graph/ComputeGraphData.worker.ts
js_modules/dagster-ui/packages/ui-core/src/asset-graph/__tests__/throttleLatest.test.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/throttleLatest.ts
js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/AssetView.test.tsx

The use of Lodash's `throttle` caused incorrect promise handling due to its behavior: 
> "Subsequent calls to the throttled function return the **result of the last func invocation**."  
> ([Lodash docs](https://lodash.com/docs/#throttle))
This led to promises resolving with stale results from previous requests. 
To fix this, I replaced `throttle` with a custom `throttleLatest` implementation that ensures the promise returned corresponds to the current request, not a previous one.
Additionally, I resolved a potential issue with worker listeners not being cleaned up properly, ensuring correct promise resolution.
- Added Jest tests for `throttleLatest` with the required behavior.
- Verified that the asset graph renders correctly on initial load in the UI.
[ui] Fixed an issue that would …

Fix asset graph throttling

---

python_modules/libraries/dg-cli/setup.py

Renames package from `dg-cli` -> `dagster-dg` since PyPI rejects `dg-cli` (even though it's not taken, it's too similar to some other package). Change in name of source module will be in a follow-up.
Existing test suite, publishing to PyPI.

[components] Rename dg-cli -> dagster-dg (pkg name only)

---

python_modules/dagster/dagster/_core/definitions/decorators/op_decorator.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_decorators.py

I think this test was previously weird; we should be asserting on the expected error message, not the _lack_ of an error message. 
Also, fix the error message itself, the argument doesn't need to be a "keyword" argument. Just an argument.

[easy] fix graph test  + error message

---

python_modules/libraries/dagster-components/dagster_components/cli/generate.py
python_modules/libraries/dagster-components/dagster_components/generate.py
python_modules/libraries/dg-cli/dg_cli_tests/cli_tests/test_generate_commands.py

Fix bug with the component_type name inserted into the `component.yaml` of generated components-- now is the fully qualified name rather than last component.
Unit tests.

[components] Fix component type name in generated component.yaml

---

python_modules/libraries/dg-cli/dg_cli/generate.py
python_modules/libraries/dg-cli/dg_cli/templates/CODE_LOCATION_NAME_PLACEHOLDER/pyproject.toml.jinja

`uv` package sources only work for direct dependencies of a package. This makes sure all dagster packages needed by a scaffolded code location are direct dependencies and have a listed uv source (fixes bug in tutorial).
Manual testing.

[components] Add extra dagster-* editable dependencies to generated pyproject.toml

---

js_modules/dagster-ui/packages/ui-core/jest/mocks/ComputeGraphData.worker.ts
js_modules/dagster-ui/packages/ui-core/src/asset-graph/ComputeGraphData.types.ts
js_modules/dagster-ui/packages/ui-core/src/asset-graph/ComputeGraphData.worker.ts
js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx

Similar to https://github.com/dagster-io/dagster/pull/26315, moves `buildGraphData` for the `useFullAssetGraphData` hook into a webworker.
Tested using app-proxy and loading a big asset graph

Move `useFullAssetGraphData` to use webworker too

---

python_modules/dagster/dagster/_core/execution/asset_backfill.py

Updates the log message when a backfill is waiting for runs to retry to log the run ids it is waiting on. 
forced a backfill into a situation where these logs get printed. output
```
2024-12-09 15:40:44 -0500 - dagster.daemon.BackfillDaemon - INFO - The following runs for the backfill will be retried, but have not been launched. Backfill is still in progress:
1908f288-6c03-4620-92ec-36b8fb24888e
af189906-96ba-467d-9ea0-d74be361a880
9a98a638-2ab5-4cd0-8d27-02cf40352adc
```

change backfill log message when waiting for runs to retry

---

python_modules/dagster/dagster/_core/storage/cloud_storage_compute_log_manager.py
python_modules/dagster/dagster/_core/storage/compute_log_manager.py
python_modules/dagster/dagster/_core/storage/local_compute_log_manager.py
python_modules/dagster/dagster/_core/storage/noop_compute_log_manager.py
python_modules/dagster/dagster_tests/storage_tests/test_compute_log_manager.py
python_modules/libraries/dagster-gcp/dagster_gcp_tests/gcs_tests/test_compute_log_manager.py

While working with backfill logs locally i observed that we were doing a very large number of existtance checks for `stdout` files that we didnt even want.
To avoid this I moved around some effectively duplicate code to the base class and made it so that we can fetch the data for only the stream we care about.

[compute logs] shift interface to avoid over-reading

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/translator.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/experimental/conftest.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/experimental/test_translator.py

Add the destination type to the Airbyte asset tags. Users can now what is the kind of destination for their Fivetran assets.
Updated unit test with BK

[dagster-airbyte] Add destination_type to kind tags in Airbyte asset specs

---

js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillRow.tsx

This is a tiny fix for https://linear.app/dagster-labs/issue/FE-703/backfill-table-non-partitioned-assets-show-0-partitions
I verified this manually, but I don't think it's worth writing a test for it because this backfills page may be getting folded away into the runs feed soon. Also verified that the new runs feed doesn't have this issue.

[ui] Avoid a “0 partitions” tag when an un-partitioned asset is backfilled

---

js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedRow.tsx

This is a small fix for https://linear.app/dagster-labs/issue/FE-707/clickable-launched-by-column-for-runs-feed
I also discussed the removal of the `display:block` with Marco, it fixes the centering of the popover menu and truncation still works with it gone. Hypothesis is that the change we made to the RowCell default styling fixed it.
[ui] Sensors and schedules that appear in the runs feed are now clickable

[ui] Make sensor and schedule links from the run feed list clickable

---

js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillOpJobPartitionsTable.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillRow.tsx
js_modules/dagster-ui/packages/ui-core/src/pipelines/PipelineReference.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/AssetTagCollections.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunAssetTags.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunRow.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunTargetLink.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedRow.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/__stories__/AssetKeyTagCollection.stories.tsx

We’ve had reports that users who launch small N numbers of assets together find the new run feed UI difficult to use, since it shows either “asset name” or “2 assets” in the Target column. The "2 assets" form makes it difficult to scan for a run you have in mind:
This PR:
- Makes the target column a bit wider
- Shows as many asset / check tags as will fit in the available space, and then “X more”
The implementation of this uses a new hook `useAdjustChildVisibilityToFill`. The idea is that your component renders some reasonable max number of tags (10) and a more tag, and the hook uses a resize observer + layout effect to show/hide the tags to fit the available space.  I tried doing this using React state, but it looks bad because you can see it adding / removing tags, especially as you …

[ui] For runs targeting assets, show >1 asset in the Target column

---

python_modules/libraries/dagster-dg/dagster_dg/generate.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_generate_commands.py

Run `uv sync` to generate the virutal environment immediately after scaffolding a code location. This is a more natural place to run it than the first time you try to e.g. list component types.
Unit tests.

[components] create venv when scaffolding code location

---

js_modules/dagster-ui/packages/ui-core/src/launchpad/useLaunchMultipleRunsWithTelemetry.ts

Previous error message was not clear to users when their "Launch all runs" operation fails due to ill-defined RunRequests. The feature requires RunRequests having job_name defined which is optional:
https://github.com/dagster-io/dagster/blob/54b39a2595408ae723e77830919fc3219f268c70/python_modules/dagster/dagster/_core/definitions/run_request.py#L81
Tested locally

[ui] add more detail in launch multiple runs' error text

---

python_modules/libraries/dagster-k8s/dagster_k8s/ops/k8s_job_op.py

This is a follow up of https://github.com/dagster-io/dagster/pull/22784
Such logging is still necessary to have even after `delete_failed_k8s_jobs` implementation, because such option isn't feasible in production or/and highly dynamic environments.
Addressed previous comments of @gibsondan 
Tested locally by inducing an error. Logging was successful as expected.
Output k8s pod logs when pods fail.

Add pod logging

---

examples/starlift-demo/dbt_example/dagster_defs/utils.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/decorators/decorator_assets_definition_builder.py
python_modules/dagster/dagster/_core/definitions/op_definition.py
python_modules/dagster/dagster/_utils/merger.py
python_modules/dagster/dagster_tests/definitions_tests/test_asset_spec.py

This PR changes `AssetsDefinition.map_asset_specs` to allow adding additional deps to an `AssetSpec`.
To do this, we create `Nothing` inputs under the hood which map to the asset dependency in question.
This is important mostly for integration cases where we use the decorator pattern `@dbt_assets`, `@fivetran_assets`, etc. If you want to link an asset dependency to assets defined with those decorators, it's currently not feasible for users.
**Only supports op-backed assets**
This PR adds support only for op-backed assets, not graph-backed assets. I attempted to add support and found myself blocked since graph-backed assets currently do not support non-argument deps (at least from what I could gather). I added a linear issue to track this and referenced it in the relevant place in code. …

Handle adding and removing deps in AssetsDefinition.map_asset_specs

---

examples/docs_snippets/docs_snippets/guides/migrations/migrating_airflow_to_dagster.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/kubernetes_pod_operator.py
examples/experimental/external_assets/airflow_example.py
python_modules/dagster/dagster/_generate/download.py
python_modules/dagster/dagster_tests/core_tests/pythonic_config_tests/test_basic_pythonic_config.py
python_modules/dagster/dagster_tests/storage_tests/test_upath_io_manager.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/resources.py
python_modules/libraries/dagster-databricks/dagster_databricks/databricks.py
python_modules/libraries/dagster-databricks/dagster_databricks/ops.py
python_modules/libraries/dagster-deltalake/dagster_deltalake/io_manager.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
python_modules/libraries/dagster-ge/dagster_ge/factory.py
python_modules/libraries/dagster-prometheus/dagster_prometheus/resources.py
python_modules/libraries/dagster-pyspark/dagster_pyspark/resources.py
python_modules/libraries/dagster-shell/dagster_shell/ops.py
python_modules/libraries/dagster-tableau/dagster_tableau/assets.py

fixes for pyright issues that manifested with updated pins
bk

fix pyright

---

python_modules/libraries/dagster-dg/dagster_dg/cli/generate.py
python_modules/libraries/dagster-dg/dagster_dg/generate.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_generate_commands.py
python_modules/libraries/dagster-dg/setup.py

Have `dagster-dg` throw an error when both `--json-params` and `EXTRA_ARGS` are passed to `dg generate component`. These are mutually exclusive ways of specifying parameters.

[components] Error on passing both --json-params and EXTRA_ARGS to `dg generate component`

---

python_modules/libraries/dagster-aws/dagster_aws/pipes/message_readers.py
python_modules/libraries/dagster-aws/dagster_aws_tests/pipes_tests/test_pipes.py

When triggering an ECS task it usually takes 30s plus for the container to start up, and so the log stream typically isn't available for that period.
Currently we attempt to get_log_events() before the log stream is available which causes errors to show on Dagster.
This change catches the errors so they don't show. They will still appear in stderr but not in the Events output. This also fixes the result of the run showing on the materialized asset at the end of the run, where as previously the thrown error would stop it receiving the required messages back from the ECS task.
Simlarly, sometimes ThrottlingException's are thrown if you have a few
tasks on the go querying logs. This will handle this as well so it
doesnt' pollute the event view and break the result materialization.
Again, …

[dagster_aws][pipes] Don't cause an error when get_log_events raises certain exceptions

---

python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components/lib/__init__.py
python_modules/libraries/dagster-components/dagster_components/lib/dbt_project.py
python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_registry.py

Add support for extras in component discovery in `dagster-components`. Alternative to #26417 (conditional entry point loading) that instead uses conditional import statements:
- Discovery mechanism has changed so that submodules of the target module of an entry point are no longer traversed. Instead we look only at the specified module for declared components.
- Because we load everything coming from the entry point target, and we unconditionally load every declared entry point, we place the burden on component library authors to examine the environment and skip loading any components corresponding to uninstalled extras.
- Implementation of this approach in `dagster_components.lib`, where we condition imports of components for the `dbt` and `sling` extras on the presence of `dagster-dbt` …

[components] Add support for extras (conditional imports version)

---

python_modules/libraries/dagster-components/dagster_components/generate.py
python_modules/libraries/dagster-dg/dagster_dg/generate.py

There were very confusion calls to `generate_project` and `generate_subtree` in our scaffolding code that did nothing but generate a folder, even though they referred to nonexistent templates. 
Turns out this worked because `os.walk` silent returns an empty generator when it points to a directory that does not exist.
Just changing this to a `mkdir_p` call for clarity and simplicity.
Manual test. BK

[components] Simplify component folder creation

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_event_iterator.py

Subclass `typing.Iterator` instead of `abc.Iterator` in `DbtEventIterator`. This is motivated by [this discussion](https://github.com/dagster-io/dagster/pull/26396#discussion_r1881167290).

[dagster-dbt] Subclass typing.Iterator in DbtEventIterator

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_decorator.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py

As title. The example should be using the new `AssetSpec.replace_attributes(...)` pattern.
Docs preview

[dagster-fivetran] Update custom translator example in docstrings for Fivetran asset decorator and factory

---

python_modules/libraries/dagster-dg/dagster_dg/cli/generate.py
python_modules/libraries/dagster-dg/dagster_dg/generate.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_generate_commands.py

Tests for this were broken by the extras support PR, since components local to a code location now to be added to `lib/__init__.py`. This fixes the component-type scaffolding and tests.

[components] Fix dagster-dg component type scaffold and tests

---

python_modules/libraries/dagster-k8s/dagster_k8s/client.py
python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_client.py

A more complete fix for issue #23497. The recent change in PR #24432 exits the loop if all sidecar init containers are in a ready state, and doesn't wait until the regular (non init container). If the main (dagster) container takes longer to startup, for example if it's using a large image, the code fails when it attempts to read the log.
* Fixed the existing unit tests to represent the full state of the pod when we expect it to be ready. The existing tests did not ensure that the main container is ready, and instead returned when the init containers were ready (or terminated)
* Tested locally with our k8s deployment and deployed to production to fix the issue for our jobs

[bugfix] k8s client now waits for main container to be ready

---

python_modules/dagster-graphql/dagster_graphql/implementation/events.py
python_modules/dagster-graphql/dagster_graphql/schema/logs/events.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_expectations.py

These were passing in the python object directly instead of constructing graphene objects, likely a longstanding issues.
Test Plan: BK
NOCHANGELOG

Fix events fields on GrapheneRunStepStats

---

python_modules/libraries/dagster-dg/dagster_dg/generate.py
python_modules/libraries/dagster-dg/dagster_dg/utils.py

- `uv sync` was being incorrectly invoked using `uv run`
- Now all `uv` commands are run in an environment with `VIRTUAL_ENV` unset, to get rid of the warnings about the uv-resolved environment not matching the shell `VIRTUAL_ENV`
Observed test output.

[components] Fix `uv` error messages/warnings in dagster-dg tests

---

js_modules/dagster-ui/packages/ui-core/src/gantt/RunGroupPanel.tsx

During dogfooding of some changes to retry logic, @anuthebananu pointed out that the title for the lineage of retried runs was a bit confusing. It's currently the name of the job, which for asset jobs leaks the internal  `__ASSET_JOB` name 
This PR renames it `Re-executions`. 
Renamed the run lineage sidebar on the Run details page to `Re-executions`.

Rename run group side bar to Re-executions instead of the job name

---

python_modules/dagster/dagster/_core/storage/asset_check_execution_record.py
python_modules/dagster/dagster/_core/storage/event_log/base.py
python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py
python_modules/dagster/dagster/_core/storage/legacy_storage.py
python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py
python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

This is in preparation to make some fixes to the freshness check sensor, which needs to understand both when a check is in flight, and the last completed execution of the check.
Previously, on an AssetCheckExecutionSummaryRecord, we were only storing the latest record regardless of status. For freshness checks, we additionally need to know the latest _completed_ execution of a check. This PR adds that behavior by making it possible to query check execution history based on status; a cloud PR companion will follow up if we think this is reasonable.
Here's my intuition regarding perf:
- In most cases, this will retrieve the latest 2 check executions at most.
- In some degenerate cases, we could potentially have to scan many check execution records if there are many in flight checks at once …

[freshness-checks][rfc] Retrieve latest completed check execution in summary records.

---

python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/sensor.py
python_modules/dagster/dagster/_core/storage/asset_check_execution_record.py
python_modules/dagster/dagster/_core/storage/event_log/base.py
python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py
python_modules/dagster/dagster/_core/storage/legacy_storage.py
python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py
python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_sensor.py
python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

Attempts to fix tickets for freshness checks: https://linear.app/dagster-labs/issue/BUILD-527/%5Bfreshness-sensor%5D-check-for-newer-materialization-when-last-check and https://linear.app/dagster-labs/issue/BUILD-528/%5Bfreshness-sensor%5D-catch-long-runtime-issues-even-when-checks-are#comment-8cfd22cb.
The exact cases in question:
- When the asset becomes overdue because the evaluation is taking too long, and there is a planned freshness check evaluation as part of the run, we should still kick off a run of the check so that users can get alerted.
- When there's a materialization more recent than the latest check result, kick off another evaluation of the check.
I added new tests for the previously failing cases.
[bugfixes]
- Previously, the freshness check sensor would not re-evaluate …

[freshness-checks][rfc] fix tickets

---

docs/content/dagster-plus/deployment/azure/acr-user-code.mdx

Updates the Azure Container Registry (ACR) user code documentation with missing instructions for configuring GitHub Actions and Dagster Cloud. Adds detailed steps for setting up environment variables, updating other step of the CI/CD workflow, and configuring the `dagster_cloud.yaml` file to work with ACR.
- All changes are resulting from reproducing and fixing omissions in the previous version.
- NOCHANGELOG

[azure-docs] refine deployment with ACR docs

---

docs/content/dagster-plus/deployment/azure/acr-user-code.mdx
docs/content/dagster-plus/deployment/azure/blob-compute-logs.mdx

Updates the Azure Blob Storage compute logs documentation to clarify the setup process and fix issues with workload identity configuration. Adds specific instructions for using the Dagster+ Helm chart and includes a new "Next steps" section in the ACR user code guide.
- Verified all commands and configurations work in an Azure Kubernetes Service (AKS) environment
- NOCHANGELOG

[azure-docs] refine AzureBlobComputeLogManager guide

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/fivetran_event_iterator.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py

This PR adds at basic `FivetranEventIterator` that wraps materializations yielded by `FivetranWorkspace.sync_and_poll`. This `FivetranEventIterator` will be used to implement fetch_column_metadata in the next stacked PR.

[dagster-fivetran] Implement FivetranEventIterator

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_event_iterator.py

Following changes in #26424, we subclass DbtEventIterator with Iterator[T] and remove Generic[T] 

[dagster-dbt] Use Iterator[T] in DbtEventIterator

---

python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster/_serdes/serdes.py
python_modules/dagster/dagster_tests/api_tests/api_tests_repo.py
python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_repository.py
python_modules/dagster/dagster_tests/cli_tests/test_api_commands.py
python_modules/dagster/dagster_tests/general_tests/test_serdes.py

We are working towards a change in how the dagster cloud agent uploads definition snapshots to the server. An issue we currently face in that work is that the grpc server returns `JobDataSnap` but we want to upload and persist only its inner `JobSnap`.
To facilitate this as efficiently and safely as possible this PR adds a method to do the extraction quickly falling back to safely and a series of tests to defend it. 
added tests

add extract_serialized_job_snap_from_serialized_job_data_snap

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/fivetran_event_iterator.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/translator.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/utils.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/experimental/conftest.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/experimental/test_columns_metadata.py

This PR implements `FivetranEventIterator.fetch_column_metadata`, which can be called when using the asset decorator like:
```python
from dagster_fivetran import FivetranWorkspace, fivetran_assets
fivetran_workspace = FivetranWorkspace(
account_id=dg.EnvVar("FIVETRAN_ACCOUNT_ID"),
api_key=dg.EnvVar("FIVETRAN_API_KEY"),
api_secret=dg.EnvVar("FIVETRAN_API_SECRET"),
)
@fivetran_assets(
connector_id="fivetran_connector_id",
workspace=fivetran_workspace,
)
def fivetran_connector_assets(context: dg.AssetExecutionContext, fivetran: FivetranWorkspace):
yield from fivetran.sync_and_poll(context=context).fetch_column_metadata()
```
[dagster-fivetran] Column metadata can be fetched for Fivetran assets using …

[dagster-fivetran] Support fetch_column_metadata in FivetranWorkspace.sync_and_poll

---

python_modules/dagster/dagster/_core/execution/asset_backfill.py
python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py

Currently the evaluation for determining what can be run together in an asset backfill looks at the previous results that have been resolved so far during breadth first search over the topo-sorted graph. For self dependencies, the `len(asset_partitions_to_request_map[parent.asset_key]) == parent_target_subset.size` would fail since `parent` is the `candidate` and we in the middle of filling `asset_partitions_to_request_map` with `parent_target_subset`. This failure would cause the backfill to issue the partitions of the self dependency iteratively. This additionally created a mismatch in expectations between the backfill and how the runs would end up getting split up, causing dependencies to not be respected. 
Both of these issues are fixed by disregarding that check if we are evaluating …

[asset backfill] fix self dependency with backfill policy issues

---

python_modules/automation/automation_tests/test_repo.py
python_modules/libraries/dagster-components/dagster_components/__init__.py
python_modules/libraries/dagster-components/setup.py
python_modules/libraries/dagster-dg/dagster_dg/cli/generate.py
python_modules/libraries/dagster-dg/dagster_dg/generate.py
python_modules/libraries/dagster-dg/dagster_dg/templates/CODE_LOCATION_NAME_PLACEHOLDER/pyproject.toml.jinja
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_generate_commands.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py

Removes the forced use of an editable installation for `dagster-dg`-generated code locations. Allows for dependencies to be added incrementally.
`dg generate code-location` takes a `--use-editable-dagster` option. This can either be used as a flag, in which case env var `DAGSTER_GIT_REPO_DIR` will be read, or takes a value pointing to the directory containing the dagster repo.
Unit tests and ran through demo using published code on this branch.

[components] Stop forcing editable dagster for `dg generate code-location`

---

js_modules/dagster-ui/packages/ui-core/src/ticks/EvaluateScheduleDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/ticks/SensorDryRunDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/ticks/__tests__/EvaluateScheduleDialog.test.tsx
js_modules/dagster-ui/packages/ui-core/src/ticks/__tests__/SensorDryRunDialog.test.tsx

Linear: https://linear.app/dagster-labs/issue/FE-719/add-tracking-to-the-launch-all-button
Adds tracking to the launch all button in the preview tick result modal
Tested locally

[ui] add tracking to launch all button

---

python_modules/libraries/dagster-components/dagster_components/cli/list.py
python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components/core/deployment.py
python_modules/libraries/dagster-components/dagster_components/lib/pipes_subprocess_script_collection.py
python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py
python_modules/libraries/dagster-dg/dagster_dg/cli/info.py
python_modules/libraries/dagster-dg/dagster_dg/cli/list.py
python_modules/libraries/dagster-dg/dagster_dg/component.py
python_modules/libraries/dagster-dg/dagster_dg/context.py
python_modules/libraries/dagster-dg/dagster_dg/utils.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_info_commands.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py

Adds summary output to `dg list component-types` and a new `dg info component-type` command.
`dg info component-type` takes any of `--description`, `--generate-params-schema`, or `--component-params-schema` to print a single field. If none of these are passed than all fields are printed. 
Unit tests, manually.
Example output from manual test in env with all `dagster-components` extras installed:
```
$ dg list component-types
dagster_components.dbt_project
dagster_components.pipes_subprocess_script_collection
Assets that wrap Python scripts executed with Dagster's PipesSubprocessClient.
dagster_components.sling_replication
```
```
$ dg info component-type dagster_components.dbt_project
dagster_components.dbt_project
Generate params schema:
{
"properties": {
"init": {
"default": false, …
```

[components] Access more detailed component information from `dg` CLI

---

python_modules/libraries/dagster-sigma/dagster_sigma/__init__.py
python_modules/libraries/dagster-sigma/dagster_sigma/assets.py
python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
python_modules/libraries/dagster-sigma/dagster_sigma/translator.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/conftest.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/materialize_workbook.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/rebuild_workbook.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/test_asset_specs.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/test_translator.py

Introduces asset definitions builder to allow materializing Sigma workbooks. Runs each scheduled materialization for the provided workbook. 
Unit test, tested against Sigma instance.

[dagster-sigma] Implement materializing workbooks

---

js_modules/dagster-ui/packages/ui-core/src/op-selection/AntlrOpSelection.ts
js_modules/dagster-ui/packages/ui-core/src/op-selection/AntlrOpSelectionVisitor.ts
js_modules/dagster-ui/packages/ui-core/src/op-selection/__tests__/AntlrOpSelection.test.ts

Implement visitor pattern for op selection syntax.
`AntlrOpSelection.test.ts`

Implement AntlrOpSelectionVisitor on frontend

---

python_modules/dagster/dagster/_core/snap/node.py

Summary:
Iterating through big lists is slow, indexing into a mapping is fast.
Test Plan: BK, speedscope on large multi-asset with many outputs

memoize inputs and outputs in op/graph snapshots

---

js_modules/dagster-ui/packages/ui-core/src/assets/BackfillPreviewModal.tsx

If you select a group of assets to backfill and select a range such that a subset of the assets have no partitions in that range, the Backfill Preview modal shows spinners for those assets 
For example - for the following asset graph 
If you select only the latest hour to materialize, the daily asset will have no valid partitions to materialize (materializing today's asset isn't available until tomorrow)
If you then click the "Backfill Preview" button, we show an infinite spinner for the daily asset 
This PR adds a message when we know an asset wont have any partitions targeted by the backfill
[ui] Fixed a bug in the Backfill Preview where a loading spinner would spin forever if an asset had no valid partitions targeted by the backfill

[ui] backfill preview modal - if an asset won't launch any partitions show a message instead of a spinner

---

helm/dagster/schema/schema/charts/dagster/subschema/daemon.py
helm/dagster/schema/schema/charts/dagster/subschema/flower.py
helm/dagster/schema/schema/charts/dagster/subschema/run_launcher.py
helm/dagster/schema/schema/charts/dagster/subschema/webserver.py
helm/dagster/schema/schema_tests/test_celery_queues.py
helm/dagster/schema/schema_tests/test_dagit.py
helm/dagster/schema/schema_tests/test_dagster_daemon.py
helm/dagster/templates/deployment-celery-queues.yaml
helm/dagster/templates/deployment-daemon.yaml
helm/dagster/templates/deployment-flower.yaml
helm/dagster/templates/helpers/_deployment-webserver.tpl
helm/dagster/values.schema.json
helm/dagster/values.yaml

Address #26311 (partially) and #26284 (duplicate issues)
tl;dr: the `check-db-ready` container can be part of a race condition with other initContainers that are responsible for enabling the DB connection. Externally managed DBs (i.e. not the postgres container optionally included in this chart) can be validated before Helm installation so this step is not strictly required.
1. Wrote some tests
2. Installed the chart to minikube with
```
helm install dagster . --set dagsterWebserver.image.tag=latest --set dagsterDaemon.image.tag=latest --set pipelineRun.image.tag=latest --set dagsterWebserver.checkDbReadyInitContainer=true
```
And observed the initContainers present. Then ran it again with `false`
```
helm install dagster . --set dagsterWebserver.image.tag=latest --set …
```

Add value flag to disable check-db-ready initContainers in Helm chart

---

python_modules/libraries/dagster-components/dagster_components/__init__.py
python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components/generate.py
python_modules/libraries/dagster-components/dagster_components/lib/dbt_project.py
python_modules/libraries/dagster-components/dagster_components/lib/sling_replication.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_generate_commands.py

I'm in the process of creating scaffolding for generic custom components and want to customize the scaffolding process more. This means giving more explicit control to users to define their own scaffolding to some degree.
Hence I'm making it so that the user explicitly invokes the creation of a component.yaml file rather than having our framework do it. This lets the user customize the behavior. I also think this is more obvious and understandable, at the cost of an extra import.
In order to ensure that a custom component author doesn't screw this up, we add a check after `generate_files` to ensure that `component.yaml` exists. 
BK and manual

[components] Refactor generate files to call explicit function to build component.yaml

---

python_modules/dagster/dagster/_core/execution/retries.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_daemon/auto_run_reexecution/auto_run_reexecution.py

A reorganization of the `auto_reexecution_should_retry_run` function to take the run failure reason. This removes an implicit dependency on a tag's existence that was causing some errors in the associated internal pr
associate internal pr https://github.com/dagster-io/internal/pull/13039
existing tests

[auto-reexecution] make run_failure_reason a parameter to determine if should retry

---

python_modules/dagster/setup.py

This allows installing Meltano alongside Dagster.
See https://github.com/kiorky/croniter/blob/5.0.1/CHANGELOG.rst
I ran `make dev_install`. I believe this is valid syntax.
> Allow croniter >= 5.0.1, but not 4.0.0, to reallow DayOfWeek as 7.

Allow croniter 5.0.1, but not 4.0.0

---

python_modules/dagster/dagster/_core/execution/stats.py
python_modules/dagster/dagster/_core/storage/event_log/base.py
python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py

This reduces the number of events fetched for the base implementation of `get_run_stats`
BK

reduce the number of logs queried for run stats in base implementation

---

js_modules/dagster-ui/packages/ui-core/src/runs/LogsProvider.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/LogsScrollingTable.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunMetadataProvider.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/StepLogsDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/filterLogs.tsx
js_modules/dagster-ui/packages/ui-core/src/util/flattenOneLevel.tsx

We received a bug report from an org with some very, very long log output on some of their runs. Specifically, hundreds of thousands of large logs for individual runs. I noticed two issues during testing:
- When a chunk of logs loads and indicates that there are more older logs left to stream, we consider that a "loading" state and simply don't show any logs in the logs table at all.
- This is unnecessary, since we're streaming logs in. Instead, just show the loading state if there are no logs available yet at all.
- First, we're using the spread-to-concat antipattern in the subscription handler reducer, which means iterating over the entire existing list of nodes before adding the newly received logs.
- To resolve this, I'm changing the state array to track *chunks* of logs instead of …

[ui] Fix endless log loading

---

js_modules/dagster-ui/packages/ui-core/src/launchpad/useLaunchMultipleRunsWithTelemetry.ts

Linear: https://linear.app/dagster-labs/issue/AD-728/sensor-triggered-asset-materialization-error
Since useLaunchMultipleWithTelemetry is based off of useLaunchWithTelemetry, here is the relevant code in useLaunchWithTelemetry: https://github.com/dagster-io/dagster/blob/279d44aa2f325f2d2a883807da6f29bf3a2b10e1/js_modules/dagster-ui/packages/ui-core/src/launchpad/useLaunchWithTelemetry.oss.ts#L29-L31
Tested locally

[ui] add pipelineName in consideration with launching all runs

---

docs/content/integrations/fivetran/fivetran.mdx
docs/docs-beta/docs/integrations/libraries/fivetran.md

As title, in both current and new docs sites.
Docs preview

[dagster-fivetran][docs] Add setup env section in Fivetran docs

---

python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
python_modules/dagster/dagster/_core/event_api.py
python_modules/dagster/dagster/_core/storage/event_log/base.py
python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py
python_modules/dagster/dagster/_core/storage/event_log/sqlite/sqlite_event_log.py
python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

We want to be able to increase the throughput of run status sensors that target specific jobs by filtering in the run status event DB query instead of filtering in memory, against storages that support such filtering
BK

add job name filter support for run status sensors

---

python_modules/libraries/dagster-gcp/dagster_gcp/dataproc/configs.py
python_modules/libraries/dagster-gcp/dagster_gcp/dataproc/resources.py
python_modules/libraries/dagster-gcp/dagster_gcp_tests/dataproc_tests/test_resources.py

It's currently not possible to attach labels to Dataproc clusters created with `DataprocResource`. 
This PR implements changes to `DataprocResource` so it accepts a `labels` optional parameter to be attached on cluster creation.
- Added a new test assessing the setting for `labels` on DataprocResource
- Tested locally and verified that the labels were correctly attached
> [dagster-gcp] `DataprocResource` now receives an optional parameter `labels` to be attached to Dataproc clusters.

Enabling Dataproc cluster labels

---

docs/content/deployment/run-monitoring.mdx

[docs] fix broken markdown hyperlink

---

docs/docs-beta/CONTRIBUTING.md

Looks like people have been using Markdown tables in new docs to replace `<ReferenceTable>` elements in old docs, so I think that's the recommendation we should go with for now.

Update new docs CONTRIBUTING: Current <ReferenceTable> replacement is a markdown table

---

python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py
python_modules/libraries/dagster-dg/dagster_dg/cli/generate.py
python_modules/libraries/dagster-dg/dagster_dg/cli/info.py
python_modules/libraries/dagster-dg/dagster_dg/cli/list.py
python_modules/libraries/dagster-dg/dagster_dg/config.py
python_modules/libraries/dagster-dg/dagster_dg/context.py
python_modules/libraries/dagster-dg/dagster_dg/generate.py
python_modules/libraries/dagster-dg/dagster_dg/utils.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_generate_commands.py

Add a global `AppContext` and `DgConfig` object in `dagster-dg`. The purpose of these abstractions is to capture global configuration and pass it throughout the system. Global configuration is supported via top-level options passed to `dg` on the command line.
`AppContext` may appear premature in this PR, since it just wraps `DgConfig`. Upstack we add the cache to it.
Unit tests.

[components] Add dagster-dg global config and AppContext

---

python_modules/libraries/dagster-dg/dagster_dg/cache.py
python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py
python_modules/libraries/dagster-dg/dagster_dg/config.py
python_modules/libraries/dagster-dg/dagster_dg/context.py
python_modules/libraries/dagster-dg/dagster_dg/utils.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_generate_commands.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_info_commands.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py
python_modules/libraries/dagster-dg/dagster_dg_tests/test_cache.py
python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py

Initial implementation of a cache for `dagster-dg`. Currently just caches the registered components for a code location. Cache key is (code loc abs path, env hash, type of payload). The environment hash is calculated over the file metadata of `uv.lock` and the content of `pkg.lib` (i.e. where local component types can be defined).
New unit tests + manual testing (running `dg list component-types` multiple times in the same code loc, observing speedup).

[components] Add cache to dagster-dg

---

js_modules/dagster-ui/packages/ui-core/src/pipelines/Description.tsx
js_modules/dagster-ui/packages/ui-core/src/ui/MarkdownWithPlugins.tsx

Default syntax highlighting colors from `highlight.js` were not always clearly visible in dark mode. Adding our custom colors improves the contrast and ensures we'll always have good contrast in light and dark mode.
run `dagster dev` on the sample dbt project and look at dbt asset descriptions. 
Below are screenshots of various sql code blocks from the dbt asset descriptions, illustrating the new colors in light and dark mode.

Add custom colors to markdown code block for syntax highlighting

---

js_modules/dagster-ui/packages/ui-core/src/runs/AssetTagCollections.tsx

Linear: https://linear.app/dagster-labs/issue/FE-692/implement-ordering-for-asset-checks-in-run-view
Tested locally

[ui] add sorting order to show more assets and asset checks

---

docs/docs-beta/docs/dagster-plus/deployment/deployment-types/serverless/ci-cd-in-serverless.md
docs/docs-beta/docs/dagster-plus/deployment/deployment-types/serverless/index.md
docs/docs-beta/docs/dagster-plus/deployment/deployment-types/serverless/run-isolation.md
docs/docs-beta/docs/dagster-plus/deployment/deployment-types/serverless/runtime-environment.md
docs/docs-beta/docs/dagster-plus/deployment/deployment-types/serverless/security.md
docs/docs-beta/docs/dagster-plus/getting-started.md

* Clean up formatting of Serverless docs
* Clean up Dagster+ "Getting started" page (copyedits, formatting, language)

DOC-621 Clean up Serverless docs and Dagster+ getting started page

---

python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components/core/component_defs_builder.py
python_modules/libraries/dagster-components/dagster_components/lib/dbt_project.py
python_modules/libraries/dagster-components/dagster_components/lib/pipes_subprocess_script_collection.py
python_modules/libraries/dagster-components/dagster_components/lib/sling_replication.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_dbt_project.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_sling_integration_test.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_templated_custom_keys_dbt_project.py
python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_pipes_subprocess_script_collection.py
python_modules/libraries/dagster-components/dagster_components_tests/utils.py

Simplifies the load path a few ways:
1. `from_decl_node()` -> `load()`: this is just one fewer concept for the user to think about
2. just pass in `context`: same as above
3. adds a load_params() method to ComponentLoadContext: this is something we were doing in all subclasses anyway, this is just simpler to manage
NOCHANGELOG

[components] cleanup component loading

---

python_modules/libraries/dagster-components/dagster_components/core/component_rendering.py
python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_component_rendering.py

This is the initial layer for a jinja-based rendering engine for the contents of `components.yaml`. To keep this diff simpler, I didn't hook this up to anythin quite yet.
The key bit here is that in some cases, we want to defer the templating logic until a point in time where we will have more context available. For example, the asset translation logic for the dbt_project component needs to apply its template to each individual node, which won't be available until runtime.
Other fields need to be substituted in before the initial load, such as those being passed into resources used during the component init process.
This allows us to distinguish between these two cases by setting metadata in the generated json schema, which is then used to determine if rendering should be deferred or not. …

[components] Rendering engine

---

python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components/core/component_defs_builder.py
python_modules/libraries/dagster-components/dagster_components/core/component_rendering.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_templated_custom_keys_dbt_project.py
python_modules/libraries/dagster-components/dagster_components_tests/utils.py

Copies over work from: https://app.graphite.dev/github/pr/dagster-io/dagster/26340/componenet-Enable-dsl-access-to-os-environ-as-var
NOCHANGELOG

[components] Add env to the default ComponentLoadContext renderer

---

python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py

Should fix https://app.graphite.dev/github/pr/dagster-io/internal/13096/fix-serverless-run-launcher

[dagster-aws] revert ECSRunLauncher.get_image_for_run staticmethod change

---

python_modules/dagster/dagster/_core/definitions/load_assets_from_modules.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets_from_modules.py

This code path was highly crufty - code smell here is "iterating through big list and doing a ton of things at once". Solution is to create a lookup table of cacheable properties and imperatively call properties as you need them (stole this pattern from @schrockn when we were working on airlift stuff) I think the code is a lot clearer now.
I also got rid of an error message we were devoting a lot of lines to that felt very outdated; nobody is using with_resources, and repository_def is misleading.
I think we also end up catching a few hidden error states; for example, we weren't checking assetsdefs against sourceassets with the same key, sourceasset collision checking felt more like a side effect.
Existing tests

[module-loaders] Simplify module asset loader code path

---

python_modules/dagster/dagster/_core/definitions/asset_spec.py
python_modules/dagster/dagster/_core/definitions/load_assets_from_modules.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets_from_modules.py

Continue editing the load_assets_from_modules code path to simplify what is an even bigger source of complication; replacing attributes on the assets.
This code path does the same thing of trying to do like 5 different things at once in a serial loop; and it makes the code very difficult to understand. For example, the source_key_prefix vs key_prefix, the many inlined set comprehensions over asset keys, sometimes it feels like asset check behavior is a side-effect rather than a first class thing.
Introduce a new class `ResolvedAssetObjectList` which allows us to apply sequential transformations to lists of asset objects of varying kinds. Splitting out the different kinds of transformations makes the code much more readable IMO.
There's still quite a bit of complexity incurred mostly by …

[module-loaders] Handle attribute mapping properly

---

examples/docs_snippets/docs_snippets_tests/guides_tests/asset_tutorial_tests/test_cereal.py
examples/docs_snippets/docs_snippets_tests/guides_tests/asset_tutorial_tests/test_serial_asset_graph.py
python_modules/dagster/dagster/_core/code_pointer.py
python_modules/dagster/dagster/_core/definitions/load_asset_checks_from_modules.py
python_modules/dagster/dagster/_core/definitions/load_assets_from_modules.py
python_modules/dagster/dagster/_core/workspace/autodiscovery.py

Make use of the new asset loading internal APIs under the hood on the checks loaders. This allows us to actually delete the old `prefix_assets` method, which was still in use here. 
A lot of the added code lines here are explicit coercion to "asset checks definitions" from assetsdefinitions after they have had attributes replaced. I wonder if this is actually necessary and can't be removed in another PR which handles that case holistically.
But now at least everything is using the same stuff under the hood, and we're able to remove this tangled mess of helper methods.

[module-loaders] Use new loader code in checks loaders

---

python_modules/dagster/dagster/_core/execution/asset_backfill.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/instance/config.py
python_modules/dagster/dagster/_core/instance/ref.py
python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster/_daemon/backfill.py
python_modules/dagster/dagster/_daemon/controller.py
python_modules/dagster/dagster/_daemon/daemon.py
python_modules/dagster/dagster/_daemon/sensor.py
python_modules/dagster/dagster/_scheduler/scheduler.py
python_modules/dagster/dagster/_utils/__init__.py
python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py
python_modules/dagster/dagster_tests/daemon_tests/test_dagster_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/daemon_tests/test_e2e.py
python_modules/dagster/dagster_tests/scheduler_tests/conftest.py

Some users are running into situations where they kick off a backfill that takes hours to process and it holds up every other backfill until it finishes. Adding a thread pool can alleviate this in most situations, where there is one of a handful of long-running backfills; in the unlikely case where all of the backfills being executed in parallel take hours, this still won't help.
Existing tests, plus changing e2e tests to use thread pool for backfills.
Added the option to use a thread pool to process backfills in parallel.

Add a thread pool to process backfills in parallel

---

python_modules/dagster/dagster/_core/execution/stats.py
python_modules/dagster/dagster_tests/storage_tests/test_event_log.py

For extremely large runs, we'd like to build up the run stats calculations without fetching all required events in a single go.
This enables the incremental calculation of run stats.
BK

add support for incremental run stats calculations

---

docs/content/guides/limiting-concurrency-in-data-pipelines.mdx

Phil's work makes it so concurrency limits work by default, even when using the sqlite database.
This removes the note that it's experimental and only supporting certain storages.
NOCHANGELOG

[docs] remove note that concurrency is only supported for non-sqlite databases

---

helm/dagster/templates/deployment-celery-queues.yaml
helm/dagster/templates/deployment-daemon.yaml
helm/dagster/templates/deployment-flower.yaml
helm/dagster/templates/helpers/_deployment-webserver.tpl
helm/dagster/templates/helpers/_helpers.tpl
helm/dagster/values.yaml

The postgresql chart uses the "registry" value to prefix the image name. This value was not already set in the values.yaml so I had to dig into the chart.
Additionally, the Dagster helm templates don't use this registry value to create the image name. So if you do provide a custom registry: "myprivate.acr.io", then it will be correctly used in the postgresql helm, but not in the dagster initdbcontainerReady creation, since there the registry is missing, and it will fail to pull the image.

fix(helm): registry missing in postgresql templating

---

python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/decorator_assets_definition_builder.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_deps.py
python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_check_decorator_secondary_assets.py

Previously, we would hard error if both deps and ins existed within a particular utility function `build_named_ins` in the asset decorator code paths. This would lead to us doing all sorts of gymnastics in various decorator pathways contorting the code to fit that path, while still allowing that invariant to be true (multi_asset is the most egregious example here, where we literally call the function twice with two different parameterizations).
However, downstream code paths are actually pretty good at handling this gracefully. We have ways of synthesizing and deduping asset specs from a list of asset ins and deps, so I don't think we need to be so strict here.
What we _do_ need to be strict about is the contents of the provided AssetIn. We should be hard erroring if the user tries to …

[io-managers-deps] Allow deps and ins to coexist at decorator layer

---

python_modules/dagster/dagster/_core/definitions/asset_in.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/decorator_assets_definition_builder.py
python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_check_decorator.py

This PR attempts to add support for argument-based dependency override on the multi_asset_check decorator. 
The idea is that for any dependent asset in an asset check, you can specify the dependent asset as an AssetIn (or we can coerce it for you) and you can read the io-managed value using that.
Adds a bunch of new tests for arg-based dep behavior
The `@multi_asset_check` decorator now supports loading the io-managed value of a checked asset.

[io-managers-deps] Support argument-based dep override on multi-asset checks

---

python_modules/dagster/dagster/_core/definitions/asset_in.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/decorator_assets_definition_builder.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_deps.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py
python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_check_decorator.py

Properly handle deps in the multi_asset decorator. Previously, the behavior when various combinations of multi_asset deps-related args were smashed together was not really under test. 
Now that build_and_validate_named_ins can handle overlaps in deps and ins, we can simplify the logic in this part of the decorator significantly. Still leaving a hefty comment about why we disallow unmapped inputs _outside_of build_and_validate_named_ins.
I added a bunch of new test cases for all the possible interactions.

[io-managers-deps] Properly handle deps mapping in multi_asset decorator

---

python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/storage/event_log/base.py
python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py
python_modules/dagster/dagster/_core/storage/event_log/sqlite/sqlite_event_log.py
python_modules/dagster/dagster/_core/storage/legacy_storage.py
python_modules/dagster/dagster_tests/storage_tests/test_event_log.py
python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

Summary:
The underlying storage changes were already ready to go for this and it was just a matter of removing gating and tweaking some tests.
BK
Run retries can now be used while using Sqlite storage.

add support for run retries with default sqlite storage

---

docs/docs-beta/docs/dagster-plus/deployment/management/dagster-cloud-cli/dagster-cloud-cli-reference.md
docs/docs-beta/docs/dagster-plus/deployment/management/dagster-cloud-cli/installing-and-configuring.md

[docs-beta] migrate - dagster-cloud-cli docs

---

python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/load_assets_from_modules.py

We can further simplify the load_asset_from_x code path by making the asset checks loader return AssetsDefinitions, and changing the assertions to just make sure that the returned assets only contain checks.
Altered existing tests

[module-loaders] Further simplify asset checks path

---

python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py
python_modules/libraries/dagster-dg/dagster_dg/cli/generate.py
python_modules/libraries/dagster-dg/dagster_dg/cli/info.py
python_modules/libraries/dagster-dg/dagster_dg/cli/list.py
python_modules/libraries/dagster-dg/dagster_dg/utils.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_custom_help_format.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_integrity.py

This customizes `click` commands and groups so that help messages now include non-help parent options.
Before:
```
$ dg generate component --help
Usage: dg generate component [OPTIONS] COMPONENT_TYPE COMPONENT_NAME [EXTRA_ARGS]...
Generate a scaffold of a Dagster component.
... description ...
Options:
--json-params TEXT  JSON string of component parameters.
-h, --help          Show this message and exit.
```
After:
```
$ dg generate component --help
Usage: dg [OPTIONS] generate component [OPTIONS] COMPONENT_TYPE COMPONENT_NAME [EXTRA_ARGS]...
Generate a scaffold of a Dagster component.
... description ...
Options:
--json-params TEXT  JSON string of component parameters.
-h, --help          Show this message and exit.
Options (dg):
--builtin-component-lib TEXT  Specify a builitin …
```

[components] Make dagster-dg help messages include parent options

---

python_modules/dagster/dagster/_core/definitions/automation_tick_evaluation_context.py
python_modules/dagster/dagster/_core/execution/asset_backfill.py
python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill_with_backfill_policies.py

As title -- we were unnecessarily forking these code paths, which limited a pretty easy to support bit of functionality
Previously, asset backfills could only target selections of assets in which all assets had a `BackfillPolicy`, or none of them did. Mixed selections are now supported.

[fix] Allow a backfill to target a selection of assets of which only a subset have backfill policies

---

python_modules/libraries/dagster-components/dagster_components/cli/generate.py
python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components/generate.py
python_modules/libraries/dagster-components/dagster_components/lib/dbt_project.py
python_modules/libraries/dagster-dg/dagster_dg/cli/generate.py
python_modules/libraries/dagster-dg/dagster_dg/generate.py
python_modules/libraries/dagster-dg/dagster_dg/utils.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_generate_commands.py

Exposes CLI params (if defined) for component types in `dagster-dg`.
- `dg generate component` used to take the component type as an argument, but now dynamically generates a subcommand for each component type.
- We no longer define `cli` as a static method on components. Instead we just send the schema over the wire to `dagster-dg`, where it is automatically converted into click options (fields with an object type take a JSON param).
- Because component types are subcommands, we no longer use the special `-- --key1=val1 --key2=val2 ...` CLI syntax to set params. Instead they are passed as normal params to the subcommand.
- All component subcommands can still take `--json-params` instead of individual options. It is an error to pass `--json-params` _and_ individual options.
- User-defined …

[components] Expose generation CLI params in dagster-dg

---

js_modules/dagster-ui/packages/ui-core/src/app/FeatureFlags.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/launchpad/OpSelector.tsx
js_modules/dagster-ui/packages/ui-core/src/op-selection/AntlrOpSelection.ts

We want to hook up the new op selection syntax so that it is being used on the frontend.

Hook up op selection syntax to frontend

---

pyright/alt-1/requirements-pinned.txt
pyright/master/requirements-pinned.txt
pyright/master/requirements.txt

Summary:
For whatever reason the current constraints are producing a fastapi version from 2019 that is getting flagged by dependabot. Give it a hint to produce a version that is more modern.
Test Plan: BK

Regenerate pyright pins with a more reasonable fastapi pin

---

python_modules/dagster/dagster/_core/definitions/asset_check_spec.py
python_modules/dagster/dagster/_core/definitions/asset_graph.py
python_modules/dagster/dagster/_core/definitions/asset_key.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/cacheable_assets.py
python_modules/dagster/dagster/_core/definitions/load_assets_from_modules.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_unresolved_asset_job.py
python_modules/dagster/dagster_tests/general_tests/test_cacheable_assets_defs.py

This was one of the most confusing parts of the original code path; that asset check key changing was happening _implicitly_ within with_attributes when you changed output_asset_keys.
Instead, provide a top-level, explicit way to remap asset check keys. I think the old behavior was highly mysterious. I found myself questioning what the heck was happening. This is much more; "what it says on the tin."

[module-loaders] Make asset check coercion explicit in with_attributes

---

python_modules/dagster/dagster/_cli/asset.py
python_modules/dagster/dagster/_cli/job.py
python_modules/dagster/dagster/_cli/workspace/cli_target.py
python_modules/dagster/dagster_tests/cli_tests/command_tests/assets.py
python_modules/dagster/dagster_tests/cli_tests/command_tests/test_asset_list_command.py
python_modules/dagster/dagster_tests/cli_tests/command_tests/test_materialize_command.py

Continuation of #26069:
> I was browsing the repo for good first issues as a new contributor, and found #16802 interesting. It looks like @sam-goodwin's PR #20979 is nearly complete, except for a change needed for one of the imports. I used that PR's solution, but also resolved the import issue.
Which is a continuation of #20979:
> > This change adds support for -c, --config and --config-json in the dagster asset materialize CLI command.
> > Our motivation is to simply materialize a whole graph as part of CI/CD and use run_config to specify parameters that scope down that materialization for the sake of CI/CD. A single partition of our asset graph can take a long time to run and for CI/CD we don't need the whole thing.
- [dagster-cli] Adds support for `--config-json` to the `dagster asset …

 feat: allow passing config for dagster asset materialize cli [#26069 continued]

---

python_modules/dagster/dagster/_core/definitions/module_loaders/load_asset_checks_from_modules.py
python_modules/dagster/dagster/_core/definitions/module_loaders/load_assets_from_modules.py
python_modules/dagster/dagster/_core/definitions/module_loaders/object_list.py
python_modules/dagster/dagster/_core/definitions/module_loaders/utils.py

The object list utils were previously defining behavior mostly in terms of assets. Genericize the utilities to instead refer to "DagsterObjects" where appropriate; in preparation for handling other types of dagster definitions.
Existing tests

[module-loaders] Genericize object list utils

---

js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/EvaluationList.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/EvaluationListRow.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/EvaluationStatusTag.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/__stories__/EvaluationList.stories.tsx

We don't need so much fragment data for the evaluation list, so let's require less so that consumers don't need to overquery.
TS, lint, storybook.

[ui] Limit the amount of asset info required for evaluation list

---

python_modules/dagster/dagster/_core/definitions/module_loaders/object_list.py
python_modules/dagster/dagster/_core/definitions/module_loaders/utils.py
python_modules/dagster/dagster_tests/definitions_tests/module_loader_tests/test_module_loaders.py

Actually genericize `ModuleScopedDagsterObjects` to handle taking in all types of Dagster objects - sensors, schedules, and jobs. I explicitly left out resources and loggers, because I don't think it makes sense to scoop those up at module load - since they need to be associated with a key.
Added a new test file `test_module_loaders` which scaffolds out a module fake for a given test spec, and ensures that either an error is thrown or the correct number of attributes are accessible on the underlying list.

[module-loaders] Genericize object list functionality to take in all sensors, jobs, schedules

---

python_modules/dagster/dagster/_core/definitions/module_loaders/load_defs_from_module.py
python_modules/dagster/dagster/_core/definitions/module_loaders/object_list.py
python_modules/dagster/dagster_tests/definitions_tests/module_loader_tests/test_module_loaders.py

This PR is a prototype of a top-level API to load dagster definitions from across a module into a single returned `Definitions` object. It is not intended for landing yet. Just want to align on direction.
For any user who is bought into a module structure making use of `load_assets_from_x`, we are currently making their life unnecessarily more difficult by not bringing in other objects that are scoped at module-load time. Those users agree - we've received requests for an API to do that numerous times.
In absence of a compelling replacement for our current project structure, I think the existence of this API is a good stopgap to improve module ergonomics.
It seems like the most straightforward way to support these objects without some sort of additional magic. Since we force you to …

[module-loaders] [rfc] Definitions from module loader

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/trigger.py

6 is to short to do lookup in github
10 seems to be what is used elsewhere

[buildkite] use longer commit hash in linked builds

---

docs/docs-beta/CONTRIBUTING.md

Adds guidance on how to add line break and lists to Markdown tables.

Table formatting how-to

---

python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

Add flag to TestEventLogStorage for storages that don't implement get_logs_for_all_runs_by_log_id

---

CHANGES.md

1.9.6 changelog

---

docs/docs-beta/docs/dagster-plus/deployment/deployment-types/hybrid/kubernetes/configuration.md

Broken links converted to `/todo`:
```
- Broken link on source page path = /dagster-plus/deployment/deployment-types/hybrid/kubernetes/configuration:
-> linking to /dagster-plus/deployment/agents/kubernetes/configuring-running-kubernetes-agent
-> linking to /dagster-plus/managing-deployments/code-locations
-> linking to /dagster-plus/managing-deployments/dagster-cloud-yaml
-> linking to /dagster-plus/managing-deployments/environment-variables-and-secrets
-> linking to /guides/dagster/using-environment-variables-and-secrets
-> linking to /deployment/guides/kubernetes/customizing-your-deployment#per-job-kubernetes-configuration
-> linking to /deployment/guides/aws#using-s3-for-io-management
```
NOCHANGELOG

[docs-beta] migrate - kubernetes agent docs

---

docs/docs-beta/docs/dagster-plus/deployment/management/rate-limits.md

Broken links converted to `/todo`:
```
- Broken link on source page path = /dagster-plus/deployment/management/rate-limits:
-> linking to /concepts/logging#structured-event-logs
-> linking to /concepts/logging#raw-compute-logs
```
NOCHANGELOG

[docs-beta] migrate - rate limits doc

---

docs/docs-beta/docs/dagster-plus/features/insights/export-metrics.md

Broken links marked as `/todo`:
```
- Broken link on source page path = /dagster-plus/features/insights/export-metrics:
-> linking to /dagster-plus/insights
-> linking to /dagster-plus/insights#available-metrics
-> linking to /dagster-plus/account/managing-user-agent-tokens#managing-user-tokens
-> linking to /concepts/webserver/graphql-client
```
NOCHANGELOG

[docs-beta] migrate - Insights docs (export)

---

docs/docs-beta/docs/dagster-plus/deployment/code-locations/dagster-cloud-yaml.md

Following links need to be updated:
```
- Broken link on source page path = /dagster-plus/deployment/code-locations/dagster-cloud-yaml:
-> linking to /dagster-plus/deployment/agents/docker/configuration-reference
-> linking to /dagster-plus/deployment/agents/amazon-ecs/configuration-reference
-> linking to /dagster-plus/deployment/agents/kubernetes/configuration-reference
```
NOCHANGELOG

[docs-beta] migrate - code locations docs

---

python_modules/dagster/dagster/_core/definitions/decorators/sensor_decorator.py

Resolves #26223 
`@multi_asset_sensor` was deprecated with a message saying to use `AutomationCondition`, but `AutomationCondition` cannot cover all of `@multi_asset_sensor` uses cases (like running jobs), as discussed in #26223.
Deprecation of `@multi_asset_sensor` has been rolled back.

Roll back deprecation of multi-asset sensor

---

python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components/core/component_defs_builder.py
python_modules/libraries/dagster-components/dagster_components/core/component_rendering.py
python_modules/libraries/dagster-components/dagster_components_tests/rendering_tests/custom_scope_component/component.py
python_modules/libraries/dagster-components/dagster_components_tests/rendering_tests/custom_scope_component/component.yaml
python_modules/libraries/dagster-components/dagster_components_tests/rendering_tests/test_component_rendering.py
python_modules/libraries/dagster-components/dagster_components_tests/rendering_tests/test_custom_scope.py

Small change, big usability upgrade. This lets users define custom scope for users of their component to take advantage of.
This scope can be anything from convenience string constants to complex functions that return raw python types.
In the unit test, I have an example showing how this could let someone set up a custom automation condition constructor, but the possibilities here are kinda endless. For example, you could easily imagine creating more complex translator methods without having to fully give up the yaml world using this capability.
NOCHANGELOG

[components] Add custom scope for custom components

---

js_modules/dagster-ui/packages/ui-core/src/launchpad/useLaunchMultipleRunsWithTelemetry.ts
js_modules/dagster-ui/packages/ui-core/src/ticks/EvaluateScheduleDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/ticks/SensorDryRunDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/util/buildExecutionParamsList.ts

We want to fallback to jobName if its not specified in request.jobName
Will test in canary, jest

[ui] fix job names

---

python_modules/dagster/dagster/_core/execution/stats.py
python_modules/dagster/dagster_tests/storage_tests/test_event_log.py

This is the counterpart of https://github.com/dagster-io/dagster/pull/26550, but for step stats instead of run stats.
The step stats calculations are a little more complicated because it relies on intermediate state in between dagster events to be held.  This includes the `previous_attempt_start` time for a given step.  This PR introduces a field in the snapshot to carry over this state, which should only be used in the incremental calculation.
Another change made here is that marker events (e.g. resource init/teardown) can be associated with a step, but generally occur before the step has started.  That means that previously step snapshots did not include these marker events if the step had not yet started.  This PR changes that behavior so that every step will have a snapshot if it has …

add support for incremental step stats calculations

---

python_modules/libraries/dagster-dg/dagster_dg/cache.py
python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py
python_modules/libraries/dagster-dg/dagster_dg/cli/generate.py
python_modules/libraries/dagster-dg/dagster_dg/context.py
python_modules/libraries/dagster-dg/dagster_dg/generate.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_generate_commands.py
python_modules/libraries/dagster-dg/dagster_dg_tests/test_cache.py
python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py

Add a top-level `--rebuild-component-registry` option that clears the cache and refetches the component registry for the current environment. The reason this is called `--rebuild-component-registry` instead of `--rebuild-cache` is:
- It is scoped to just the current environment, whereas the cache encompasses multiple environments
- We may cache other info later
Also add `--skip-venv` option to `dg generate code-location` to avoid automatic venv setup and cache population on construction. Mostly useful for testing.
We also invoke this immediately after `uv sync` when constructing a new code location, so that the cache is loaded.
New unit tests + manual test of code location generation.

[components] Add --rebuild-component-registry option, `--skip-venv` option, build cache on code loc construction

---

docs/content/integrations/embedded-elt/dlt.mdx

- A community member pointed out that by setting this you can reduce the reads on your database when the Dagster daemon polls to refresh definitions
Closes https://github.com/dagster-io/dagster/issues/26627
NOCHANGELOG

[docs] add note of defer_table_reflect to dlt docs

---

python_modules/dagster/dagster/_core/execution/context/asset_execution_context.py
python_modules/dagster/dagster/_core/execution/context/metadata_logging.py
python_modules/dagster/dagster/_core/execution/context/system.py
python_modules/dagster/dagster/_core/execution/plan/execute_step.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_partitioned_assets.py

Introduce an `AssetExecutionContext.add_asset_metadata` method, which will add metadata to materialization events (but not output events).
Storing metadata only on asset events seems like a naturally good thing to do. It's primarily what we display in the UI / is primarily what is queryable by users, and not storing it on output events saves db write size.
For partitioned assets, you are able to specify per-partition metadata that will only be added to the relevant partitioned materialization. This solves a long-standing user request to have per-partition handling in `add_output_metadata` more naturally.
Added a bunch of new tests for both non-partitioned and partitioned cases.
A new `AssetExecutionContext.add_asset_metadata` method, which allows you to add metadata to materialization …

[partition-metadata][rfc] add_asset_metadata

---

python_modules/dagster/dagster/_core/execution/context/invocation.py
python_modules/dagster/dagster_tests/core_tests/test_op_invocation.py

We changed the partition_keys implementation on the main execution context class, which made it incompatible with DirectExecutionContext
Added test failed before, passes now
NOCHANGELOG

Fix direct invocation for partition ranges

---

python_modules/dagster/dagster/_core/execution/context/asset_execution_context.py
python_modules/dagster/dagster/_core/execution/context/metadata_logging.py
python_modules/dagster/dagster/_core/execution/context/system.py
python_modules/dagster/dagster/_core/execution/plan/execute_step.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_partitioned_assets.py

I was finding that complex series of ternaries really hard to parse. Most of the complexity is the result of using the same dictionary to represent metadata per output name, and metadata per output name and mapping key. 
Instead, have a top-level accumulator class and add an "OutputMetadataHandle", so that every metadata dictionary has the same scope level. We keep the same checks in place as before, but the logic is much simpler now.
Existing tests

[partition-metadata] add_output_metadata refactor

---

docs/content/concepts/partitions-schedules-sensors/backfills.mdx

I noticed the docs of the backfill page for single runs are out of date with 1.8 based on the changes here: https://github.com/dagster-io/dagster/pull/21259
Starting this PR to correct that - the note on the backfill was incorrent in its current form. 
- potentially should add an example when using with jobs
- add an example with multipartitions (Static + Date Range)
It seems if you do try and run a job with multiple different backfill polices it will default to the policy with least max_partitions_per_run, failing that it will default to using multi_run(max_partitions_per_run=1)

Update backfills docs with more up to date info on single runs

---

docs/content/concepts/webserver/graphql.mdx

If I start up the example project locally with `dagster dev` and then try to connect to the GraphQL endpoint with`gql` using the link in the example, I get an `SSL_WRONG_VERSION` error. I also get this error if I use `dagster_graphql.DagsterGraphQLClient` with `use_https=True`.
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='127.0.0.1', port=3000): Max retries exceeded with url: /graphql (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:992)')))
```
I figured out that the error means I'm trying to connect to something that doesn't use HTTPS. Here's an example of someone explaining the error: https://github.com/psf/requests/issues/5943#issuecomment-925930558
If I change the link to instead use HTTP, `gql` successfully connects and queries …

[docs] change HTTPS to HTTP in GraphQL API example

---

python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py

As title -- prepares us for a world in which the DagsterDbtTranslator just returns an AssetSpec
NOCHANGELOG

[dagster-dbt][refactor] Use AssetOut.from_spec() to create AssetOuts for dbt_assets decorator

---

python_modules/dagster/dagster/_core/definitions/asset_out.py
python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py
python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py

As title. This lets individual dbt models have distinct partitions definitions
NOCHANGELOG

[dagster-dbt] Add get_partitions_def() method to DagsterDbtTranslator

---

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/dlt/asset_decorator.py
python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/asset_decorator.py

I realize now that we we're not exposing `op_tags` for `dlt_assets` which would be beneficial in setting concurrency limits for dlt assets. This exposes this parameter to the `multi_asset`
- [dagster-dlt] allow customization of `op_tags` in `dlt_assets`

[dagster-dlt] allow op_tag customization for dlt_assets to be used in concurrency limits

---

python_modules/libraries/dagster-components/dagster_components/cli/__init__.py
python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components/lib/test/__init__.py
python_modules/libraries/dagster-components/dagster_components/lib/test/all_metadata_empty_asset.py
python_modules/libraries/dagster-components/dagster_components/lib/test/simple_asset.py
python_modules/libraries/dagster-components/dagster_components/lib/test/simple_pipes_script_asset.py
python_modules/libraries/dagster-components/dagster_components_tests/lib/__init__.py
python_modules/libraries/dagster-components/setup.py
python_modules/libraries/dagster-dg/dagster_dg_tests/test_cache.py

Move the `dagster-components` test component library from `dagster_components_tests.lib` to `dagster_components.lib.test`. This lets us simplify entry point loading code (eliminate call to `ensure_dagster_components_tests_import`) and also ensures these components are accessible whether from a published `dagster-components` or local (we don't include our test packages in published distributions as a rule)

[components] Move dagster-components test component lib to dagster_components.lib.test

---

python_modules/libraries/dagster-dg/dagster_dg/generate.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_generate_commands.py

Make it so that the editable sources included in `pyproject.toml` when generating a code location are constructed from a crawl of the dagster repo rather than hardcoded. Preemptively provides editable sources for integrations we may add components for.

[components] Make dg generate code-location --use-editable-dagster include all dagster libs

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py

Following [this discussion](https://github.com/dagster-io/dagster/pull/26432#discussion_r1890538958) for Airbyte Cloud - `FivetranWorkspace.sync_and_poll` should only accept context of type `AssetExecutionContext`.

[dagster-fivetran] Remove OpExecutionContext support in FivetranWorkspace.sync_and_poll

---

examples/experimental/components/examples/hello_world_deployment/code_locations/hello_world/hello_world/definitions.py
python_modules/libraries/dagster-components/dagster_components/__init__.py
python_modules/libraries/dagster-components/dagster_components/cli/generate.py
python_modules/libraries/dagster-components/dagster_components/cli/list.py
python_modules/libraries/dagster-components/dagster_components/core/component_decl_builder.py
python_modules/libraries/dagster-components/dagster_components/core/component_defs_builder.py
python_modules/libraries/dagster-components/dagster_components/core/deployment.py
python_modules/libraries/dagster-components/dagster_components_tests/code_locations/custom_sling_location/custom_sling_location/definitions.py
python_modules/libraries/dagster-dg/dagster_dg/templates/CODE_LOCATION_NAME_PLACEHOLDER/CODE_LOCATION_NAME_PLACEHOLDER/definitions.py
python_modules/libraries/dagster-dg/dagster_dg/templates/COMPONENT_TYPE/COMPONENT_TYPE_NAME_PLACEHOLDER.py.jinja

Does a couple things
* Renames the top-level entry point from `build_defs_from_toplevel_components_folder` to `build_component_defs`
* Changes the scaffolding to make it a top-level export of `dagster_components`
* Removes upwards traversal in the folder hiearchy. Instead requires targeting of the exact directory. This avoids magic and makes errors more explicit
Generated empty code location from scaffolding and loaded it.
BK

[components] Rename build_defs_from_toplevel_components_folder to build_component_defs and make it less magical

---

python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components/core/component_defs_builder.py
python_modules/libraries/dagster-components/dagster_components/core/deployment.py

This increases the flexibility of code layout in components-enabled code location by allowing `build_components_defs` to load any arbitrary folder as the components folder. This will be useful for codebases where users have their own folder layout conventions, as well as for testing (we could have many componet folders for a single code location directory for example).
Manual

[components] Make the components folder parameterizable

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_decorator.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py

Following [this discussion](https://github.com/dagster-io/dagster/pull/26559#discussion_r1889463330) for Airbyte Cloud, we add the translator as metadata as the spec loader level

[dagster-fivetran] Move DagsterFivetranTranslator metadata to Fivetran specs loader

---

docs/docs-beta/docs/guides/deploy/deployment-options/docker.md

It is invalid syntax to have a comment after a `\` in your Dockerfile.
Ran locally.

[docs-beta] rm comment in dockerfile as is invalid syntax

---

python_modules/dagster/dagster/_core/definitions/module_loaders/object_list.py
python_modules/dagster/dagster/_core/definitions/source_asset.py

Fix some goofiness regarding source asset group_name remapping;
- If you try to remap the group name to have the same group name, then allow that.
- In the error message, tell us what the original group_name is and what we're trying to change it to.
- We were hitting an error in DOP because we were trying to set group_name back to itself, which is not currently allowed. So fix that as well (although that is now allowed).
Existing tests

Fix asset loader for sourceassets

---

docs/docs-beta/CONTRIBUTING.md

Since we don't have dark theme images for old screenshots, let's just format images with Markdown for now instead of using the ThemedImage` component. Later, we'll do a big screenshot sweep to create dark theme images and switch from Markdown to the component.

Use markdown for images in new docs

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetPartitions.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/AssetPartitions.test.tsx

Linear: https://linear.app/dagster-labs/issue/FE-735/bug-partition-filter-in-ui-for-multipartitionsdefinition-f
Make searchValues state an array of searchValue
Tested with multi_partitions asset with app-proxy to dogfood-test-1

[ui] fix searching for multi partitions

---

docs/next/pages/_document.js

When browsing Dagster's docs, I noticed that the "Ask AI" button's font seems to have a different font from the rest of the page. It seemed to use the default sans-serif font rather than the one in the theme. This is what it looked like on Chrome (v 131.0.6778.204 on Linux):
And on Firefox (v133.0.3, also on Linux):
It's a really minor thing, but I looked into the source code, saw TailwindCSS, and thought I might as well make a PR :)
I made changes in the browser inspector and verified that these changes look alright. I also ran the documentation website locally. Here's a screenshot of the result:

Make 'Ask AI' button font consistent with page

---

docs/docs-beta/docs/dagster-plus/deployment/deployment-types/hybrid/multiple.md

Found a link we dont have in the new docs for Dagster Agent. Created linear [ticket](https://linear.app/dagster-labs/issue/DOC-649/add-dagster-instance).

migrated multiple agent page

---

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/definitions/partition_mapping.py
python_modules/dagster/dagster_tests/asset_defs_tests/asset_graph_view_tests/test_basic_asset_graph_view.py

Adds a way to raise on invalid upstream partition definitions for callsites using EntitySubset/AssetGraphView.
New test case
NOCHANGELOG

Expose a way to get nonexistant partition keys from an upstream partition mapping using AssetGraphView

---

js_modules/dagster-ui/packages/ui-core/src/util/__tests__/weakMapMemoize.test.ts
js_modules/dagster-ui/packages/ui-core/src/util/weakMapMemoize.ts

Introduces a memoize function thats more powerful than what lodash offers. Lodash memoize only works with string keys, and so it requires you to take your arguments and somehow serialize it to a string. Depending on the object this can be very slow if the object is big. To avoid the headache of serialization I'm adding a weakMapMemoize which is much more flexible and can cache any function mixing both primitives and objects. 
Going to use this to memoize the `filterByQuery` helpers for the GanttChart since it looks like we call the utility in a lot of different places separately and having them coordinate so that there's only 1 call is a bit tricky.
jest tests

Add weakMapMemoize utility.

---

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
python_modules/dagster/dagster/_core/definitions/partition.py
python_modules/dagster/dagster/_core/definitions/partition_mapping.py
python_modules/dagster/dagster/_core/definitions/time_window_partition_mapping.py
python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
python_modules/dagster/dagster/_core/execution/context/input.py
python_modules/dagster/dagster/_core/execution/context/system.py
python_modules/dagster/dagster_tests/asset_defs_tests/asset_graph_view_tests/test_basic_asset_graph_view.py
python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_asset_partition_mappings.py
python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_multipartition_partition_mapping.py
python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_time_window_partition_mapping.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_partitioned_assets.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_partitions_subset.py
python_modules/dagster/dagster_tests/definitions_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_automation_condition_tester.py
python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py
python_modules/dagster/dagster_tests/storage_tests/test_fs_io_manager.py

Summary:
This allows us to make the method on AssetGraphView compute_parent_subset_and_required_but_nonexistent_subset instead of still working in terms of a list of partition keys.
I'm a little trepeditious about this because I could imagine cases where the invalid upstream partition is so invalid that it can't even be expressed as part of a PartitionsSubset? I guess in that case we could just raise an exception when you try to do the mapping like we already do in many cases (e.g. the timezones not matching).
The trickiest bit here was making sure that it was still possible to create and pass around an 'invalid' partitions subset (since we are a bit inconsistent in our APIs about whether or not we allow that when doing the various transformations from keys to subset and back).
Test Plan: …

Make UpstreamPartitionsResult subset-aware

---

docs/docs-beta/docs/guides/build/components.md

This is a draft of the initial docs page for Dagster components. It is a guide nested under the "Build" section.
It currently contains just the first part of the tutorial. It will be expanded/adjusted in multiple followups.
Browsed preview.

[components] [docs] Initial components guide

---

python_modules/libraries/dagster-components/dagster_components/generate.py

Without this the `component.yaml` files trigger prettier errors.
Manual.

[components] Fix component.yaml generation to have a trailing newline

---

python_modules/libraries/dagster-k8s/dagster_k8s/client.py
python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_launcher.py

Summary:
Both work, but string matching on a reason is more error-pone.
BK

Replace string reason check in k8s client with status check

---

python_modules/automation/automation/docker/images/dagster-celery-k8s-editable/Dockerfile
python_modules/automation/automation/docker/images/dagster-celery-k8s/Dockerfile
python_modules/automation/automation/docker/images/dagster-k8s-editable/Dockerfile
python_modules/automation/automation/docker/images/dagster-k8s/Dockerfile

Summary:
Attempt to resolve reported memory leak versions with . Apparently the underlying issue is also resolved in python 3.13, so once we officially support that in dagster, we could potentially move these images to 3.13 and remove this.
Test Plan:
Deploy the helm chart locally with these built images
Changelog:
Added a pin to the grpcio version  used by the Dagster Helm chart daemon and webserver images, to a version that has been reported to avoid memory leaks.

add grpcio 1.57.0 pin to provided helm chart images

---

python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py
python_modules/libraries/dagster-dg/dagster_dg/cli/code_location.py
python_modules/libraries/dagster-dg/dagster_dg/cli/component.py
python_modules/libraries/dagster-dg/dagster_dg/cli/component_type.py
python_modules/libraries/dagster-dg/dagster_dg/cli/deployment.py
python_modules/libraries/dagster-dg/dagster_dg/cli/global_options.py
python_modules/libraries/dagster-dg/dagster_dg/config.py
python_modules/libraries/dagster-dg/dagster_dg/context.py
python_modules/libraries/dagster-dg/dagster_dg/generate.py
python_modules/libraries/dagster-dg/dagster_dg/utils.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_code_location_commands.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_custom_help_format.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_integrity.py
python_modules/libraries/dagster-dg/dagster_dg_tests/test_cache.py
python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py

This changes the options scheme in `dagster-dg` so that options are no longer hierarchically processed and passed down the command tree, _except_ in the special case of `dg component generate` subcommands, where global options are defined on the containing group.
Now, all leaves of the tree (except for `dg component generate` subcommands) have the same set of "global options" appended to their options list. These are visually separated in the help message. We correspondingly simplify the Usage message to have a single `[OPTIONS]` input spot.
There are also now fewer apparent global options because two of the old ones, `--clear-cache` and `--rebuild-component-registry`, must be executed as standalone pseudo-commands (e.g. `dg --clear-cache`) rather than used as modifiers to other commands. …

[components] Move global options to subcommands

---

python_modules/dagster/dagster/_core/definitions/instigation_logger.py
python_modules/dagster/dagster_tests/storage_tests/test_instigation_logger.py

This prevents issues with the compute log manager from failing a schedule or sensor tick in which the logging call is happening.
BK
Exceptions that are raised when a schedule or sensor are writing logs will now write an error message to stdout instead of failing the tick.

Add error boundaries to prevent write stream errors in InstigationLogger from failing schedule/sensor ticks

---

docs/content/integrations/pandera.mdx

#23299 introduced support for Polars, but the docs weren't updated accordingly (which I learned when trying to figure out whether there was a reason only pandas was supported).
If so desired, I can update to also include Polars examples.

[docs] Include Polars as supported Pandera backend

---

.github/ISSUE_TEMPLATE/report_bug.yml

Remove unnecessary "Code of Conduct" link in `Message from the maintainers` so it matches the [feature request issue template](https://github.com/dagster-io/dagster/edit/master/.github/ISSUE_TEMPLATE/request_a_feature.yml)
👀

Remove unnecessary "Code of Conduct" link in bug report template's `Message from the maintainers` block

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/resources.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/experimental/conftest.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/experimental/test_resources.py

Implement endpoint to start a sync job in Airbyte Cloud. To be used in subsequent PRs in sync and poll process.

[9/n][dagster-airbyte] Implement base sync method in AirbyteCloudClient

---

docs/content/deployment/guides/kubernetes/deploying-with-helm.mdx

The command to retrieve webserver pod doesn't return anything if the filter on label is incorrect
https://docs.dagster.io/deployment/guides/kubernetes/deploying-with-helm#get-the-name-of-the-webserver-pod
I think the value comes from here https://github.com/dagster-io/dagster/blob/master/helm/dagster/values.yaml#L41
There is a small typo
Merry Christmas 🎅 🎁 🎄

docs(helm): fix the label component=dagster-webserver

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/resources.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/experimental/conftest.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/experimental/test_resources.py

Implement endpoint to cancel a job in Airbyte Cloud. To be used in subsequent PRs in sync and poll process.

[11/n][dagster-airbyte] Implement cancel_job method in AirbyteCloudClient

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/__init__.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/resources.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/translator.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/experimental/conftest.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/experimental/test_resources.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/experimental/utils.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/test_cloud_resources.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/test_resources.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/utils.py

Implement full sync and poll process in `AirbyteCloudClient`. This will be used in a subsequent PR in `AirbyteCloudWorkspace.sync_and_poll` to materialize Airbyte assets.

[12/n][dagster-airbyte] Implement sync_and_poll method in AirbyteCloudClient

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/__init__.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/asset_decorator.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/asset_defs.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/resources.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/experimental/conftest.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/experimental/test_asset_specs.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/experimental/test_translator.py

This PR implements the `airbyte_assets` decorator and the `build_airbyte_assets_definitions` factory.
- `airbyte_assets` can be used to create all assets for a given Airbyte connection, i.e. one asset per table in the connection.
- `build_airbyte_assets_definitions` can be used to create all Airbyte assets defs, one per connection. It uses `airbyte_assets`.
These can be used with `AirbyteCloudWorkspace`, and the goal would be to use these with the workspace for Airbyte OSS as well.
Additional unit tests with BK.
[dagster-airbyte] The `airbyte_assets` decorator is added. It can be used with the `AirbyteCloudWorkspace` resource and `DagsterAirbyteTranslator` translator to load Airbyte tables for a given connection as assets in Dagster. The `build_airbyte_assets_definitions` factory can be …

[13/n][dagster-airbyte] Implement airbyte_assets and build_airbyte_assets_definitions

---

python_modules/libraries/dagster-airlift/dagster_airlift/core/airflow_instance.py
python_modules/libraries/dagster-airlift/dagster_airlift/test/shared_fixtures.py
python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/airflow_dags/has_retries.py
python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/dagster_defs/mapped_defs.py
python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink_tests/integration_tests/test_e2e_mapped.py

Airflow only has task-level, not dag-level, retries, but let's make sure we handle them gracefully with a test.
This test uses dagster-airlift[core] dag-triggering utilities to trigger a dag whose sole task only succeeds on retry. Ensure that the polling mechanism successfully waits for all retries of this task to complete.

[dagster-airlift] airflow-side retries test behavior

---

python_modules/libraries/dagster-airlift/dagster_airlift/in_airflow/base_asset_operator.py
python_modules/libraries/dagster-airlift/dagster_airlift/in_airflow/dag_proxy_operator.py
python_modules/libraries/dagster-airlift/dagster_airlift/in_airflow/materialize_assets_operator.py
python_modules/libraries/dagster-airlift/dagster_airlift/in_airflow/task_proxy_operator.py

- Airlift assumes an Airflow 2 installation, particularly for connecting with Airflow's REST API stabilized in `airflow=2` for the Peering phase. That said, we are figuring out ways to extend the usage of Airlift for older Airflow instances (sans peering). 
One issues ran with using Airlift on Airflow 1.x is the imports. Below's my attempt at making the imports compatible with Airflow 1. 
- Inspecting import paths in Airflow v1.10
- Ran `make ruff`
- `make pyright` failed for me (when installing `pendulum`) so I wasn't able to run type checks
> [dagster-airlift] Make Airflow imports compatible with Airflow 1

[dagster-airlift] ✨ Support Airflow 1 imports

---

python_modules/libraries/dagster-airlift/dagster_airlift/__init__.py

When moving this into the python_modules/libraries directory, accidentally introduced a dagster dependency on `dagster-airlift`. 
Instead, gate the dagster import on access to the dagster package in the environment.
- The `dagster-airlift` package erroneously introduced a dependency on `dagster`. This has been rectified - `dagster` is only required for the `dagster-airlift[core]` submodule.

[dagster-airlift] remove dagster dep

---

python_modules/libraries/dagster-k8s/dagster_k8s/executor.py
python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_executor.py

Allow run time configuration of dynamic steps using the `k8s_job_executor`. Previously, dynamic steps would not be configured when using `per_step_k8s_config`. Now doing something along line of the following:
```yml
execution:
config:
per_step_k8s_config:
dyn_sink:
container_config:
resources:
requests:
cpu: '300m'
```
Given the following job:
```python
@job
def dynamic_producer_consumer_job():
@op(out=DynamicOut(int))
def dyn_producer():
yield from (DynamicOutput(i, str(i)) for i in range(3))
@op
def dyn_sink(producer: int): ...
```
Will configure **all** `dyn_sink` ops with the following modified config.
cc @Kuhlwein
resolves #26588
Red green coverage given a dynamic job. Revert the following [line](https://github.com/dagster-io/dagster/pull/26670/files#diff-e1b8a7f982ea59869272b4bc9529e …

[dagster-k8s] per_step_k8s_config working with dynamic jobs

---

js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/AutomaterializeMiddlePanelWithData.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/EvaluationListRow.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/auto-materialization/GlobalAutomaterializationContent.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillRunsTab.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedTable.tsx
js_modules/dagster-ui/packages/ui-core/src/schedules/ScheduleRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/sensors/SensorPageAutomaterialize.tsx
python_modules/dagster/dagster/_core/definitions/automation_tick_evaluation_context.py

The runs table for a DA evaluation was not showing backfills when DA requested a backfill
This is because the the `selectedEvaluation.runIds` could be run ids or a backfill id, but we were always adding them as run id filters. Then the value was a backfill id, it would return no results.
This add some (admittedly a bit hacky) logic to determine if the id is a backfill id, and set the correct filter if so. A more long term solution would be to store run ids and backfill ids as separate lists on the evaluation, but this will fix the problem until we can make the more sustainable change. 
I also had to update the `RunsFeedTableWithFilters` component to take a bool `includeRunsFromBackfills` so that we would only show the backfill row, not the runs that the backfill launched. I had to then …

[ui] Update DA evaluation page to show backfill in table if a backfill was requested

---

python_modules/dagster/dagster/_core/remote_representation/code_location.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster/_grpc/impl.py
python_modules/dagster/dagster/_grpc/server.py
python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_job.py

Summary:
This is intended to guard against a class of issues where you make a change to your code that introduces a new asset but the daemon is using slightly out of date snapshots - so we might end up launching a run on the previous image targeting assets or asset checks that don't exist yet
It doesn't perfectly guard against all classes of issues (for example, the code updating between generating the job snapshot and the execution plan snapshot, or jobs without subsets) but should help in many cases.
BK, manually test going from one asset to two assets with a sensor targeting them and see the image change immediately.
Fixed an race condition where immediately after adding a new asset to the graph, a freshness check sensor targeting that asset might raise an InvalidSubsetError in its …

Send back the RepositoryPythonOrigin on job subset grpc calls, use it in the resulting created RemoteJob

---

integration_tests/test_suites/dagster-azure-live-tests/integration_tests/dagster-yamls/access-key-credential.yaml
integration_tests/test_suites/dagster-azure-live-tests/integration_tests/test_compute_log_manager.py
python_modules/libraries/dagster-azure/dagster_azure/blob/compute_log_manager.py

Adds back support of asset keys and sas tokens to the azure compute log manager under a new configurable parameter;
`access_key_or_sas_token`. I'm torn on whether these should be two separate variables, but since they're handled identically it seems reasonable to have them live in the same field. Downside is ugly name.
We should also add back support for credential under the old name and issue a deprecation warning.
Added a new parametrization of the compute log manager integration test suite. Currently failing in bk because credentials need to be rotated, but passes local for me with a real access key.
[dagster-azure] A new `access_key_or_sas_token` parameter to the `AzureBlobComputeLogManager`, which allows you to authenticate via either access key or sas token.

[dagster-azure] explicitly support access key and sas token in compute log manager

---

integration_tests/test_suites/daemon-test-suite/auto_run_reexecution_tests/test_auto_run_reexecution.py
integration_tests/test_suites/daemon-test-suite/auto_run_reexecution_tests/test_event_log_consumer.py
python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster/_daemon/auto_run_reexecution/auto_run_reexecution.py
python_modules/dagster/dagster/_daemon/auto_run_reexecution/event_log_consumer.py
python_modules/dagster/dagster/_daemon/backfill.py
python_modules/dagster/dagster/_daemon/daemon.py
python_modules/dagster/dagster/_daemon/monitoring/run_monitoring.py
python_modules/dagster/dagster/_daemon/run_coordinator/queued_run_coordinator_daemon.py
python_modules/dagster/dagster/_daemon/sensor.py
python_modules/dagster/dagster/_daemon/utils.py
python_modules/dagster/dagster/_scheduler/scheduler.py
python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py

Summary:
- Run all logger.exception calls in the daemon through DaemonErrorCapture.on_exception
- Always require and include a logger, without one it never logs
- When a daemon re-raises due to a UserCodeUnreachableError, ensure that the exception that is re-raised is also a UserCodeUnreachable error, so that it still gets classified as a user code error
Test Plan:
BK (existing tests include verifying that schedules and sensors retry on unreachable errors - verify), run a failed schedule, sensor, backfill, and AMP tick and inspect resulting daemon logs.

Improve DaemonErrorCapture coverage and accuracy

---

python_modules/dagster/dagster/_core/definitions/asset_key.py
python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py
python_modules/libraries/dagster-dbt/dagster_dbt/asset_specs.py
python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py
python_modules/libraries/dagster-dbt/dagster_dbt/cloud/asset_defs.py
python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_cli_event.py
python_modules/libraries/dagster-dbt/dagster_dbt/core/resource.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_checks.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py

This was mostly a passion project, but it preempts some work that needed to get done in this area in the near future anyway.
We have a bunch of complex logic going on here, purely because we are not taking advantage of the features around passing specs into @multi_asset (because this code predates asset specs!)
Crucially, before this change, we were manually creating internal_asset_deps, AssetIns, and AssetOuts independently, alongside juggling a bunch of different dictionaries to keep track of it all.
Now, I've created a single `get_asset_spec` method. Once we're ready, this can essentially be copy-pasted into the DagsterDbtTranslator class once we're ready, but for now this is purely-internal construct.
The only change in the constructed object is that we no longer have control over the …

[dagster-dbt][refactor] Clean up multi-asset creation

---

python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py
python_modules/libraries/dagster-dbt/dagster_dbt/cloud/asset_defs.py
python_modules/libraries/dagster-dbt/dagster_dbt/cloud/utils.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud/utils.py

Updates the dbt cloud integration to be more spec-native, taking advantage of existing utilities for generating specs from a dbt project.
This results in the ability to delete a large amount of code.
NOCHANGELOG

[dagster-dbt] Spec-ify dbt cloud integration

---

python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/test_resource.py

Adds the option to skip fetching lineage for Sigma workbooks, for users who may want to build this lineage themselves.
Add new unit test.
> [dagster-sigma] Added the option to skip fetching lineage for workbooks in cases where users want to build this information themselves.

[dagster-sigma] Add option to skip fetching lineage information

---

.buildkite/dagster-buildkite/dagster_buildkite/pipelines/dagster_oss_nightly_pipeline.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/integration.py
integration_tests/test_suites/dagster-azure-live-tests/integration_tests/conftest.py
integration_tests/test_suites/dagster-azure-live-tests/integration_tests/test_compute_log_manager.py

This PR adds a step to delete all blobs created by the integration tests.
Previously they were just building up.
Existing tests still pass

[dagster-azure] delete blobs after test in integration tests

---

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/asset_graph_view/bfs.py
python_modules/dagster/dagster/_core/definitions/asset_graph_subset.py
python_modules/dagster/dagster_tests/asset_defs_tests/asset_graph_view_tests/test_bfs.py

Summary:
Pulling out the new BFS utility added in https://github.com/dagster-io/dagster/pull/25997 to its own function with its own tests to keep the PR size manageable.
Test Plan: New tests
NOCHANGELOG

New BFS method for use in asset backfills

---

python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components/core/component_rendering.py
python_modules/libraries/dagster-components/dagster_components/core/dsl_schema.py
python_modules/libraries/dagster-components/dagster_components/lib/dbt_project.py
python_modules/libraries/dagster-components/dagster_components/lib/sling_replication.py
python_modules/libraries/dagster-components/dagster_components_tests/rendering_tests/test_component_rendering.py
python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_spec_processing.py

This adds a rendering scope to AssetAttributes, allowing its values to depend on the spec that's currently being evaluated. This is useful for setting properties of a spec based off of other properties (e.g. based off of a tag, set an automation condition)
Refactors component_rendering.py to be more class-based
NOCHANGELOG

[components] Templating for asset_attributes

---

python_modules/libraries/dagster-components/dagster_components/core/component_rendering.py
python_modules/libraries/dagster-components/dagster_components/core/dsl_schema.py
python_modules/libraries/dagster-components/dagster_components/lib/dbt_project.py
python_modules/libraries/dagster-components/dagster_components/lib/pipes_subprocess_script_collection.py
python_modules/libraries/dagster-components/dagster_components_tests/rendering_tests/test_component_rendering.py

This changes up how we manage marking objects as having deferred fields. The result is a lot more terse, and generally easier to work around.
The base class exposes a method to get all of the rendered properties, which can be overridden in scenarios where we want to customize this. For now, our only existing usage can just use this raw properties dictionary directly
NOCHANGELOG

[components] Replace RequiredScope with RenderedModel

---

python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/test_resource.py

Adds an option to the `SigmaFilter` which lets users filter to specific workbooks rather than folders.
New unit test.
> [dagster-sigma] Added the option to filter to specific workbooks in addition to folders.

[dagster-sigma] Add ability to filter to specific workbooks

---

python_modules/dagster-graphql/dagster_graphql/implementation/execution/backfill.py

Fix a mistaken inconsistency; see https://github.com/dagster-io/dagster/pull/26731#discussion_r1900183152.
BK
Added validation of `title` for asset backfills (not just for job backfills).

Also validate backfill `title` for asset backfills

---

python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/last_update.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/sensor.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/time_partition.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/metadata_bounds_checks.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/schema_change_checks.py
python_modules/dagster/dagster/_core/definitions/input.py

decision: experimental params -> superseded
reason: InputDefinition is a very old API that does not really exist in modern-day dagster. explicitly categorizing params for such an old API as experimental seems wasteful, so I just marked the entire class as superseded

[core-api][experimental] `InputDefinition`

---

python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/last_update.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/sensor.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/time_partition.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/metadata_bounds_checks.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/schema_change_checks.py
python_modules/dagster/dagster/_core/definitions/external_asset.py
python_modules/dagster/dagster/_core/definitions/input.py

decision: experimental -> deprecated
reason: this was actually marked as both experimental and deprecated, which doesn't make sense

[core-api][experimental] `create_external_assets_from_specs`

---

python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/last_update.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/sensor.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/time_partition.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/metadata_bounds_checks.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/schema_change_checks.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/external_asset.py
python_modules/dagster/dagster/_core/definitions/input.py

reason: we are using this pattern heavily internally, and generally have built up a lot of APIs around making this sort of thing work. we want people to be using this pattern in other places (e.g. multi_asset), so it shouldn't be marked as experimental

[core-api][experimental] AssetsDefinition `specs`

---

python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/last_update.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/sensor.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/time_partition.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/metadata_bounds_checks.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/schema_change_checks.py
python_modules/dagster/dagster/_core/definitions/asset_out.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/external_asset.py
python_modules/dagster/dagster/_core/definitions/input.py

reason: we like having tags on our objects, this is no exception, I see no reason why we would ever change this behavior

[core-api][experimental] AssetOut tags

---

python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/last_update.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/sensor.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/time_partition.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/metadata_bounds_checks.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/schema_change_checks.py
python_modules/dagster/dagster/_core/definitions/asset_out.py
python_modules/dagster/dagster/_core/definitions/asset_spec.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/external_asset.py
python_modules/dagster/dagster/_core/definitions/input.py

reason: this has existed for a long time and we do not have plans to change it

[core-api][experimental] `owners`

---

python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/last_update.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/sensor.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/time_partition.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/metadata_bounds_checks.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/schema_change_checks.py
python_modules/dagster/dagster/_core/definitions/asset_out.py
python_modules/dagster/dagster/_core/definitions/asset_spec.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/external_asset.py
python_modules/dagster/dagster/_core/definitions/input.py
python_modules/dagster/dagster/_core/definitions/run_request.py
python_modules/dagster/dagster/_core/instance/__init__.py

reason: been in use for a long time, and we're committed to the feature

[core-api][experimental] `report_runless_asset_event`

---

python_modules/dagster/dagster/_core/storage/cloud_storage_compute_log_manager.py
python_modules/libraries/dagster-aws/dagster_aws_tests/s3_tests/test_compute_log_manager.py

Fixed an issue where sensor and schedule tick logs could accumulate disk usage over time.
BK
Fixed an issue where sensor and schedule tick logs would accumulate disk over time on Dagster code servers.

Cleanup local logs after a cloud storage compute log manager uses them to upload to cloud storage

---

python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/last_update.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/sensor.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/time_partition.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/metadata_bounds_checks.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/schema_change_checks.py
python_modules/dagster/dagster/_core/definitions/asset_out.py
python_modules/dagster/dagster/_core/definitions/asset_spec.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/external_asset.py
python_modules/dagster/dagster/_core/definitions/input.py
python_modules/dagster/dagster/_core/definitions/run_request.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/storage/dagster_run.py

reason: we rely on this functionality fairly heavily internally, making it unlikely that we could change it even if we wanted to (beyond a name change, which is easy enough to do in a non-breaking way in the future)

[core-api][experimental] exclude_subruns

---

python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/last_update.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/sensor.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/time_partition.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/metadata_bounds_checks.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/schema_change_checks.py
python_modules/dagster/dagster/_core/definitions/asset_out.py
python_modules/dagster/dagster/_core/definitions/asset_spec.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/external_asset.py
python_modules/dagster/dagster/_core/definitions/input.py
python_modules/dagster/dagster/_core/definitions/reconstruct.py
python_modules/dagster/dagster/_core/definitions/run_request.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/storage/dagster_run.py

reason: this is a 4 year old API, there are niche situations in which it is useful, and I see zero reason that we would break it

[core-api][experimental] `build_reconstructable_job`

---

python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/last_update.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/sensor.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/time_partition.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/metadata_bounds_checks.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/schema_change_checks.py
python_modules/dagster/dagster/_core/definitions/asset_out.py
python_modules/dagster/dagster/_core/definitions/asset_spec.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/external_asset.py
python_modules/dagster/dagster/_core/definitions/input.py
python_modules/dagster/dagster/_core/definitions/metadata/source_code.py
python_modules/dagster/dagster/_core/definitions/reconstruct.py
python_modules/dagster/dagster/_core/definitions/run_request.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/storage/dagster_run.py

reason: this is an endorsed pattern that we encourage people to use

[core-api][experimental] AutomationConditionSensorDefinition

---

python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/last_update.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/sensor.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/time_partition.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/metadata_bounds_checks.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/schema_change_checks.py
python_modules/dagster/dagster/_core/definitions/asset_out.py
python_modules/dagster/dagster/_core/definitions/asset_spec.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/external_asset.py
python_modules/dagster/dagster/_core/definitions/input.py
python_modules/dagster/dagster/_core/definitions/metadata/source_code.py
python_modules/dagster/dagster/_core/definitions/multi_asset_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/reconstruct.py
python_modules/dagster/dagster/_core/definitions/run_request.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/storage/dagster_run.py

decision: experimental -> superseded
reason: while this API does support some cases that DA does not, in the vast majority of cases it will be significantly easier to implement equivalent functionality in DA, so we want to avoid retaining documentation for this pattern and potentially causing confusion. There's no reason for existing users to stop using multi asset sensors though, hence this not being marked as deprecated
docs exist: no (on purpose)

[core-api][experimental] multi_asset_sensor

---

python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/last_update.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/sensor.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/time_partition.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/metadata_bounds_checks.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/schema_change_checks.py
python_modules/dagster/dagster/_core/definitions/asset_out.py
python_modules/dagster/dagster/_core/definitions/asset_spec.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/external_asset.py
python_modules/dagster/dagster/_core/definitions/input.py
python_modules/dagster/dagster/_core/definitions/metadata/source_code.py
python_modules/dagster/dagster/_core/definitions/multi_asset_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/reconstruct.py
python_modules/dagster/dagster/_core/definitions/result.py
python_modules/dagster/dagster/_core/definitions/run_request.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/storage/dagster_run.py

reason: given that we've bought in heavily to MaterializeResult, it seems natural to promote this pattern as well
docs exist: no (api only, needs to be added to: https://docs.dagster.io/concepts/assets/asset-observations#asset-observations)

[core-api][experimental] ObserveResult

---

python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/last_update.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/sensor.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/time_partition.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/metadata_bounds_checks.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/schema_change_checks.py
python_modules/dagster/dagster/_core/definitions/asset_out.py
python_modules/dagster/dagster/_core/definitions/asset_spec.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/external_asset.py
python_modules/dagster/dagster/_core/definitions/input.py
python_modules/dagster/dagster/_core/definitions/metadata/source_code.py
python_modules/dagster/dagster/_core/definitions/multi_asset_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/reconstruct.py
python_modules/dagster/dagster/_core/definitions/result.py
python_modules/dagster/dagster/_core/definitions/run_request.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/storage/dagster_run.py

reason: we might want to subtly change the default behavior of this (e.g. how far down the tree it looks)

[core-api][experimental] AutomationCondition.any_downstream_conditions

---

python_modules/libraries/dagster-dbt/setup.py
python_modules/libraries/dagster-dbt/tox.ini

Summary:
This force-flaky business does not appear to retry if the test crashes. Try a new pytest setting that claims to do so.
BK

Attempt to make dagster-dbt test failures retry on crashes

---

js_modules/dagster-ui/packages/ui-core/src/asset-selection/input/AssetSelectionInput.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-selection/useAssetSelectionInput.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-selection/useAssetSelectionState.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/AssetTables.test.tsx
js_modules/dagster-ui/packages/ui-core/src/selection/SelectionAutoCompleteInput.tsx

[Asset selection input] Show auto-complete suggestions immediately on focus.

---

python_modules/dagster-graphql/dagster_graphql/schema/asset_selections.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_scheduler.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py

Updates the asset selection strings we return to the UI from GraphQL to implicitly include the code location they're targeting.
Tested locally - todo unit tests

[ui] Display currently-implicit code location selection in asset selection strings

---

examples/docs_snippets/docs_snippets/integrations/power-bi/customize-power-bi-asset-defs.py
examples/project_atproto_dashboard/project_atproto_dashboard/dashboard/definitions.py
python_modules/libraries/dagster-powerbi/dagster_powerbi/resource.py
python_modules/libraries/dagster-powerbi/dagster_powerbi/translator.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_asset_specs.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_translator.py

This PR implements `PowerBITranslatorData`, a container class containing a `PowerBIContentData` object (props) and a `PowerBIWorkspaceData` object (context), to pass contextual data to the translator without breaking the `get_asset_spec` signature or requiring context to be passed to the `__init__` method of the `DagsterPowerBITranslator`.
This is PR is an alternative to the proposals mentioned in https://github.com/dagster-io/dagster/pull/26617.
[dagster-powerbi] Type hints in the signature of `DagsterPowerBITranslator.get_asset_spec` have been updated - the parameter `data` is now of type `PowerBITranslatorData` instead of `PowerBIContentData`. Custom Power BI translators should be updated.

[dagster-powerbi] Move contextual data from DagsterPowerBITranslator to PowerBITranslatorData

---

examples/docs_snippets/docs_snippets/integrations/tableau/customize-tableau-asset-defs.py
python_modules/libraries/dagster-tableau/dagster_tableau/resources.py
python_modules/libraries/dagster-tableau/dagster_tableau/translator.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_asset_specs.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_translator.py

Same as #26654 but for Tableau.
[dagster-tableau] Type hints in the signature of `DagsterTableauTranslator.get_asset_spec` have been updated - the parameter `data` is now of type `TableauTranslatorData` instead of `TableauContentData`. Custom Tableau translators should be updated.

[dagster-tableau] Move contextual data from DagsterTableauTranslator to TableauTranslatorData

---

examples/docs_snippets/docs_snippets/integrations/looker/customize-looker-assets.py
python_modules/libraries/dagster-looker/dagster_looker/api/assets.py
python_modules/libraries/dagster-looker/dagster_looker/api/dagster_looker_api_translator.py
python_modules/libraries/dagster-looker/dagster_looker/api/resource.py
python_modules/libraries/dagster-looker/dagster_looker_tests/api/test_build_defs.py

Same as #26654 but for Looker.
[dagster-looker] Type hints in the signature of `DagsterLookerApiTranslator.get_asset_spec` have been updated - the parameter `looker_structure` is now of type `LookerApiTranslatorStructureData` instead of `LookerStructureData`. Custom Looker API translators should be updated.

[dagster-looker] Move contextual data from DagsterLookerApiTranslator to LookerApiTranslatorStructureData

---

docs/content/integrations/looker.mdx
examples/docs_snippets/docs_snippets/integrations/looker/customize-looker-assets.py
python_modules/libraries/dagster-looker/dagster_looker/api/assets.py
python_modules/libraries/dagster-looker/dagster_looker/api/resource.py
python_modules/libraries/dagster-looker/dagster_looker_tests/api/test_build_defs.py

Same as #26734 but for Looker.
BK
[dagster-looker] `load_looker_asset_specs` and `build_looker_pdt_assets_definitions` are updated to accept an instance of `DagsterLookerApiTranslator` or custom subclass.

[dagster-looker] Use Looker API translator instance in spec loader and state-backed defs

---

docs/content/integrations/powerbi.mdx
examples/docs_snippets/docs_snippets/integrations/power-bi/customize-power-bi-asset-defs.py
examples/project_atproto_dashboard/project_atproto_dashboard/dashboard/definitions.py
python_modules/libraries/dagster-powerbi/dagster_powerbi/resource.py
python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_asset_specs.py

Updates `load_powerbi_asset_specs()` and state-backed definitions to accept an instance of `DagsterPowerBITranslator`.
See #26133 for more details about the motivation.
BK
[dagster-powerbi] `load_powerbi_asset_specs` is updated to accept an instance of `DagsterPowerBITranslator` or custom subclass.

[dagster-powerbi] Use Power BI translator instance in spec loader and state-backed defs

---

docs/content/integrations/tableau.mdx
examples/docs_snippets/docs_snippets/integrations/tableau/customize-tableau-asset-defs.py
python_modules/libraries/dagster-tableau/dagster_tableau/resources.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_asset_specs.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_reconstruction.py

Same as #26734 but for Tableau.
BK
[dagster-tableau] `load_tableau_asset_specs` is updated to accept an instance of `DagsterTableauTranslator` or custom subclass.

[dagster-tableau] Use Tableau translator instance in spec loader and state-backed defs

---

docs/content/guides/limiting-concurrency-in-data-pipelines.mdx

Add a pointer that the UI / CLI settings changes are deployment settings
inspection

add deployment settings pointer for concurrency docs

---

python_modules/dagster/dagster/_annotations.py
python_modules/dagster/dagster/_utils/warnings.py

Fixes [AD-735](https://linear.app/dagster-labs/issue/AD-735/add-preview-annotation) in the API Lifecycle project.
Adding new Preview Python utils. Similar to #25363 
This is done in alignment with the new [API lifecycle](https://www.notion.so/dagster/API-Lifecycle-Refresh-f72f6e199da3409c8c5da297a109b3c8).
The raised warning is a `Warning`.
Docs to be updated in subsequent PR.

[utils] add preview warning and decorator

---

examples/docs_snippets/docs_snippets/integrations/sigma/customize-sigma-asset-defs.py
python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
python_modules/libraries/dagster-sigma/dagster_sigma/translator.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/test_translator.py

Same as #26654 but for Sigma.
[dagster-sigma] Type hints in the signature of `DagsterLookerApiTranslator.get_asset_spec` have been updated - the parameter `data` is now of type `Union[SigmaDatasetTranslatorData, SigmaWorkbookTranslatorData]` instead of `Union[SigmaDataset, SigmaWorkbook]`. Custom Looker API translators should be updated.

[dagster-sigma] Move contextual data from DagsterSigmaTranslator to container classes

---

python_modules/libraries/dagster-sigma/dagster_sigma/resource.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/pending_repo_with_translator_legacy.py
python_modules/libraries/dagster-sigma/dagster_sigma_tests/test_asset_specs.py

Same as #26734 but for Sigma.
BK
[dagster-sigma] `load_sigma_asset_specs` is updated to accept an instance of `DagsterSigmaTranslator` or custom subclass.

[dagster-sigma] Use Sigma translator instance in spec loader and state-backed defs

---

js_modules/dagster-ui/packages/ui-core/src/app/Util.tsx
js_modules/dagster-ui/packages/ui-core/src/app/apolloLinks.tsx
js_modules/dagster-ui/packages/ui-core/src/app/useVisibleFeatureFlagRows.oss.tsx

We're not really using this feature flag and the one call site using it is logging operation information that we can easily see in the network tab now that we include the operation name in the URL.

Remove debug console logging feature flag.

---

python_modules/dagster/dagster/_annotations.py
python_modules/dagster/dagster/_utils/warnings.py

Fixes [AD-736](https://linear.app/dagster-labs/issue/AD-736/add-beta-annotation) in the API Lifecycle project.
Adding new Beta Python utils. Similar to #25363 
This is done in alignment with the new [API lifecycle](https://www.notion.so/dagster/API-Lifecycle-Refresh-f72f6e199da3409c8c5da297a109b3c8).
The raised warning is a `Warning`.
Docs to be updated in subsequent PR.

[utils] add beta warning and decorator

---

python_modules/libraries/dagster-looker/dagster_looker/api/dagster_looker_api_translator.py

As title - wording was incorrect (copy paste error). This is minor, but updating since the `LookerApiTranslatorStructureData` class is user facing.

[dagster-looker] Fix wording in LookerApiTranslatorStructureData docstring

---

docs/docs-beta/docs/dagster-plus/deployment/deployment-types/serverless/runtime-environment.md
docs/docs-beta/src/components/CodeExample.tsx

We want to make sure that the CodeExample block is included in the statically generated HTML for the site so that it's included in SEO. Currently since we use a `useEffect` we only fetch the content on the client.
To fix this we need to make sure we have the content on the server. To this end I added a check to see if we're on the server and if we are then we synchronously require the content for the codeblock inline during render and use it. Otherwise, if we're on the client, we import the content dynamically and rely on Suspense to avoid unmounting the SSR'd content during the initial render. 
`yarn build`
`yarn serve`
Looked at the source in `view-source:http://localhost:3002/` and confirmed the HTML includes the codeblocks.
There's a brief flash of the light theme but confirmed on the …

Make CodeExample block SSRd for better SEO.

---

python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/resources.py

This fixes an issue where Sling materialisations fail if a stream has an empty config.
A fix for #25515 and #25925
Original code by @Westm7
I had a failing config, which no longer fails after this change.

[embedded-elt][sling] Correctly get an object_key when a stream has an empty config

---

python_modules/dagster/dagster/_grpc/impl.py
python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_partition.py

Summary:
The current implementation here requires fetching every partition key in the set, which can be very slow. We don't appear to use that for anything other than filtering out keys that aren't in the set, which seems like a reasonable thing to require the callsite to check instead.
BK

Remove slow validation code in get_partition_set_execution_param_data

---

js_modules/dagster-ui/packages/ui-core/src/app/FeatureFlags.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/app/useVisibleFeatureFlagRows.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/launchpad/OpSelector.tsx
js_modules/dagster-ui/packages/ui-core/src/op-selection/AntlrOpSelection.ts
js_modules/dagster-ui/packages/ui-core/src/op-selection/AntlrOpSelectionVisitor.ts
js_modules/dagster-ui/packages/ui-core/src/pipelines/GraphExplorer.tsx
js_modules/dagster-ui/packages/ui-core/src/pipelines/OpGraphSelectionInput.tsx

1. Consolidate `flagOpSelectionSyntax` into `flagSelectionSyntax`
2. Add a selection syntax input for the op graph and use it if the feature flag is enabled

Add new selection syntax to job op graphs

---

js_modules/dagster-ui/packages/ui-core/src/app/AppProvider.tsx
js_modules/dagster-ui/packages/ui-core/src/selection/SelectionAutoCompleteInputParser.ts

I've noticed these lint warnings recently. Just tidying up.
`yarn lint`, no wranings remain.

[ui] Lint cleanup

---

python_modules/libraries/dagster-airlift/setup.py

Some magical dep change changed out the version of marshmallow we were installing for tests, which broke validation airflow-side for airflow 2.7.3. 
This fixes for Airflow 2.7.3 / python under 3.12. I'll also pin for python >= 3.12 if the error recurs there.
For posterity's sake, I found the correct pin via the relevant airflow constraints file: https://raw.githubusercontent.com/apache/airflow/constraints-2.7.3/constraints-3.11.txt
Local tox

[dagster-airlift] Pin marshmallow

---

.buildkite/dagster-buildkite/dagster_buildkite/pipelines/dagster_oss_nightly_pipeline.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/integration.py
integration_tests/test_suites/dagster-gcp-live-tests/gcp_test_proj/defs.py
integration_tests/test_suites/dagster-gcp-live-tests/integration_tests/conftest.py
integration_tests/test_suites/dagster-gcp-live-tests/integration_tests/dagster-yamls/json-credentials.yaml
integration_tests/test_suites/dagster-gcp-live-tests/integration_tests/test_compute_log_manager.py
integration_tests/test_suites/dagster-gcp-live-tests/setup.py
integration_tests/test_suites/dagster-gcp-live-tests/tox.ini

Similar to what we introduced for azure, introduce live testing for gcp. Starting with the compute log manager.
Just like the azure tests, this runs on branches which touch dagster-gcp, as well as on the oss nightly pipeline.
Most of the files here are a relative copy-paste job from the azure tests. There is some new functionality, and I've added comments pointing to where that lives.
New tests pass.

[dagster-gcp] live tests

---

python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_op.py

Test behavior when a bare asset check result is yielded inside an op (both invocation and execution).
Similar test cases exist elsewhere; but I think it's useful to have one specifically targeted at the op decorator.

Document bare check result in op behavior

---

docs/docs-beta/src/components/CodeExample.tsx

- We need to include `props`, notable `lineStart` and `lineEnd` in the content cache for code blocks to render the correct content, otherwise the first value will be used without line filtering
- This also refactors the logic into `loadModule`
`yarn start`
NO CHANGELOG

[docs] use CodeExample props as cache key

---

python_modules/dagster/dagster/_core/definitions/multi_asset_sensor_definition.py

user tried passing something else and got confusing stack trace

check MultiAssetSensorEvaluationContext.advance_cursor arg

---

js_modules/dagster-ui/packages/ui-core/src/search/SearchResults.tsx

Only highlight exact string matches in global search results. When fuzzy match results are highlighted, the results list can look a little weird and broken.
Based on the `matches` list, I'm not sure that it's _wrong_ for fuzzy matches, exactly, but it doesn't match user expectations of what should appear highlighted.
A drawback here might be that extended search behavior (https://www.fusejs.io/examples.html#extended-search) might not surface any highlights at all in most cases, but that's probably not in heavy use, and I imagine that highlighted substrings would also be pretty weird for these anyway.
Before:
After. Note that fuzzy matches are shown but have no substring highlighting:
Perform global searches, verify that only the exact typed match is highlighted in the results.
[ui] Fix …

[ui] Highlight exact matches in global search labels

---

docs/sphinx/_ext/sphinx-mdx-builder/sphinxcontrib/mdxbuilder/writers/mdx.py

After (left) and Before (right)

[docs-beta] Fix duplicate text when reference also contains an inline literal

---

python_modules/dagster/dagster_tests/general_tests/test_import.py

Make finding the instructions for debugging import performance issues more obvious.
I ran code where I end up with an indirect `grpc` import, and the output now looks like:
```python
expensive_imports = [f"`{lib}`" for lib in expensive_library if lib in import_profile]
>       assert not expensive_imports, (
"The following expensive libraries were imported with the top-level `dagster` module, "
f"slowing down any process that imports Dagster: {', '.join(expensive_imports)}; to debug, "
"`pip install tuna`, then run "
"`python -X importtime python_modules/dagster/dagster_tests/general_tests/simple.py &> /tmp/import.txt && tuna /tmp/import.txt`."
)
E       AssertionError: The following expensive libraries were imported with the top-level `dagster` module, slowing down any process that …
```

Surface how to visualize import performance issues

---

python_modules/libraries/dagster-components/dagster_components/cli/generate.py
python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components/core/component_generator.py
python_modules/libraries/dagster-components/dagster_components/generate.py
python_modules/libraries/dagster-components/dagster_components/lib/dbt_project.py

Beginning of a stack to separate out generator code from runtime component. This modularizes things and sets up to install generator/scaffolding code as an extra when appropriate.
BK

[components] Separate out generator into separate class that can be dynamically imported

---

docs/content/dagster-plus/managing-deployments/alerts.mdx
docs/docs-beta/docs/dagster-plus/features/alerts/creating-alerts.md

This behavior is undocumented. I tested and confirmed it in my Dagster+ org.

[docs] add note about alert behavior with RetryPolicy

---

docs/content/concepts/types.mdx

This is a really quick typo fix to the amazing documentation
"Complimentary" means something is free of charge or expresses praise. 
"Complementary" means something completes or goes well with something else.
N/A - Documentation.

Small Typo (Complimentary → Complementary)

---

js_modules/dagster-ui/packages/ui-core/src/app/AppProvider.tsx
js_modules/dagster-ui/packages/ui-core/src/app/usePrefixedCacheKey.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx

`usePrefixedCacheKey` currently lives in `AppProvider`, so callsites that import it are importing a big component with an increased risk of circular dependencies.
This is a pretty slim function that just needs `AppContext`, which is defined separately from the provider, so we can just move it out into its own file to mitigate the risk.
Buildkite.

[ui] Move usePrefixedCacheKey into its own file

---

python_modules/libraries/dagster-airlift/dagster_airlift/in_airflow/base_asset_operator.py
python_modules/libraries/dagster-airlift/dagster_airlift/in_airflow/dag_proxy_operator.py
python_modules/libraries/dagster-airlift/dagster_airlift/in_airflow/task_proxy_operator.py

This is an optional PR to keep the Python code compatible with older Python versions. 
If we want to maximize the reach of Airlift as a migration tool, it could support older Airflow deployments running on older versions of Python. 
In my use case, the target environment is Python 3.7, which does not support the walrus operator (`:=`). 
> [dagster-airlift] Support Python 3.7

[dagster-airlift] ✨Support Python 3.7

---

python_modules/dagster/dagster/_generate/download.py

Fixes
https://buildkite.com/dagster/dagster-dagster/builds/106984#019441db-3189-4954-90d0-98297bbc4174/805-1256 and makes the example available via:
```
dagster project from-example --example project_ask_ai_dagster
```

Add project_ask_ai_dagster to available examples

---

python_modules/libraries/dagster-components/dagster_components/core/component_rendering.py
python_modules/libraries/dagster-components/dagster_components/core/dsl_schema.py
python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_templated_custom_keys_dbt_project.py

This converts to using the AssetAttributesModel inside the translator. This is nice because it reduces duplicated code (e.g. the AssetKey.from_user_string() conversion), and in general having fewer distinct types flying around is good. (note: the `group_name` key was erroneously called just `group` before, this is something that we now no longer need to worry about)
Unfortunately, the translator code is still a mess on account of not having a unified `get_asset_spec()` method, meaning we have to implement a bunch of individual fns. However, once that's implemented, the translator can become as simple as:
```python
class XComponentTranslator(XTranslator):
def __init__(self, params: AssetAttributes, resolver): ...
def get_asset_spec(self, x: ...) -> AssetSpec:
base_spec = …
```

[components] Use AssetAttributesModel instead of DbtTranslatorParams

---

python_modules/libraries/dagster-components/dagster_components/lib/__init__.py
python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/generator.py
python_modules/libraries/dagster-components/dagster_components_tests/code_locations/custom_sling_location/custom_sling_location/components/debug_sling_component/component.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_sling_integration_test.py

Add a component generator the sling replication component collection. Produces a `replication.yaml` file and a `component.yaml` file that points to that one replication.yaml file.
In addition to the default/demo case being easier, if you want to rename `replication.yaml` or add a new one, I think this is still a better user experience.
Ran through Components README

[components] Add generator to SlingReplicationComponentCollection

---

docs/content/_navigation.json
docs/content/integrations/fivetran.mdx
docs/content/integrations/fivetran/fivetran.mdx

Fivetran docs were moved to /integrations/fivetran/fivetran and /integrations/fivetran/fivetran-legacy, which means /integrations/fivetran is currently 404ing. This PR adds a landing page for the Fivetran section in docs.

Fix 404ing Fivetran page

---

docs/sphinx/sections/api/apidocs/definitions.rst
python_modules/dagster/dagster/__init__.py
python_modules/dagster/dagster/_core/definitions/module_loaders/load_defs_from_module.py

Exposes load_definitions_from_module as a public API, and mark it as experimental for now
Existing tests
- A new function `load_definitions_from_module`, which can load all the assets, checks, schedules, sensors, and job objects within a module scope into a single Definitions object. Check out the documentation to learn more: https://docs.dagster.io/_apidocs/definitions#dagster.load_definitions_from_module

Make load_definitions_from_module public

---

js_modules/dagster-ui/packages/ui-core/src/assets/usePartitionHealthData.tsx

Use a set so that we're not iterating over every partition key
before:
after:

Fix O(n^2) code

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql/schema/external.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
python_modules/dagster-graphql/dagster_graphql/schema/solids.py
python_modules/dagster/dagster/_core/definitions/asset_graph_differ.py

Summary:
AssetGraphDiffer does non-trivial data fetching so defer loading it until we actually fetch the field that uses it.
BK, load asset graph in and out of branch deployment context
NOCHANGELOG

Lazily load AssetGraphDfifer in GrapheneAssetNode

---

python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster/dagster/_core/definitions/asset_graph_differ.py
python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
python_modules/dagster/dagster_tests/general_tests/asset_graph_differ_tests/test_asset_graph_differ.py

Summary:
Advances in asset graph technology have allowed us to accomplish the goal of this original code (fetching only the repo-scoped asset node) without having to fetch the whole asset graph for that repository.
Test Plan: BK
NOCHANGELOG

Load individual asset nodes in AssetGraphDiffer instead of the entire asset graph

---

docs/docs-beta/docs/dagster-plus/deployment/management/managing-compute-logs-and-error-messages.md
docs/docs-beta/docs/dagster-plus/features/ci-cd/branch-deployments/change-tracking.md
docs/docs-beta/docs/dagster-plus/features/ci-cd/branch-deployments/testing.md
docs/docs-beta/docs/guides/operate/io-managers.md
docs/docs-beta/docs/integrations/libraries/airbyte/airbyte-cloud.md
docs/docs-beta/docs/integrations/libraries/fivetran.md

Fixes broken `<Link>` hrefs created by `PyObject` instances.
This PR is stacked on https://github.com/dagster-io/dagster/pull/26942
`yarn build` locally; waiting for BK
NOCHANGELOG

[docs-beta] fix broken pyobject API references

---

docs/docs-beta/CONTRIBUTING.md
docs/docs-beta/docs/dagster-plus/deployment/management/managing-compute-logs-and-error-messages.md
docs/docs-beta/docs/dagster-plus/features/ci-cd/branch-deployments/change-tracking.md
docs/docs-beta/docs/dagster-plus/features/ci-cd/branch-deployments/testing.md
docs/docs-beta/docs/etl-pipeline-tutorial/create-and-materialize-assets.md
docs/docs-beta/docs/guides/operate/io-managers.md
docs/docs-beta/docs/integrations/libraries/airbyte/airbyte-cloud.md
docs/docs-beta/docs/integrations/libraries/fivetran.md
docs/docs-beta/src/components/PyObject.tsx

* Implements `PyObject` for the Docusaurus version of docs
* Note, we don't have access to the Sphinx search context like we did in the Next.js version of docs, so for now, I'm proposing that we require the user to explicitly define the section via the `section` prop
Because we use the `<Link>` component, Docusaurus auto-magically validates broken links, revealing the following which I will work on in a stacked PR.
```
Exhaustive list of all broken anchors found:
- Broken anchor on source page path = /dagster-plus/deployment/management/managing-compute-logs-and-error-messages:
-> linking to /api/python-api/assets#dagster._core.storage.noop_compute_log_manager.NoOpComputeLogManager
- Broken anchor on source page path = /dagster-plus/features/ci-cd/branch-deployments/change-tracking:
-> …
```

[DOC-630][docs-beta] update PyObject to create /api/python-api/ href

---

python_modules/libraries/dagster-databricks/dagster_databricks/pipes.py

Addresses bug #26434 where an error is thrown for any Databricks Pipes where extras have not been provided for the pipe. 
Update checks if extras is available in params first to prevent the bug from being thrown

[dagster-databricks] Fix Cluster Drive Log Root Error when no extras provided for pipe

---

python_modules/libraries/dagster-aws/setup.py

Somehow I forgot to remove `boto3-stubs` from the main runtime dependencies when moving them to `stubs` extras. 
Fixing this issue.

[dagster-aws] remove stubs from runtime dependencies

---

js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/EvaluationDetailDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AutomaterializeTagWithEvaluation.tsx

Fix "View evaluation" links from `AutomaterializeTagWithEvaluation`, which shows asset keys and evaluation links in a popover, e.g. on a Run. When clicking the link, open the evaluation detail dialog.
Additionally:
- Added the asset (or asset check) information in a tag in the dialog header, because otherwise it's not clear what asset you're looking at.
- Added a footer button to link to the asset's Automation tab, cursored to the currently viewed evaluation ID. This is to allow a look at recent history.
View a run that has this tag. Verify that the popover link opens the dialog correctly, and that the asset tag renders in the header.
[ui] Open the evaluation detail dialog from the "Automation condition" tag popover on Runs.

[ui] Open evaluation detail dialog from automaterialize tag

---

js_modules/dagster-ui/packages/ui-core/src/pipelines/PipelineExplorerRoot.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/util.ts

When viewing an asset job as an asset graph the `PIPELINE_EXPLORER_ROOT_QUERY` is unused. This is slowing down the default case unnecessarily. Short circuit to bypass it. 
Note that this uses the `useJob` hook which relies on our workspace fetching abstraction. If the workspace isn't fetched then we go down the slow path and its effectively a race between the query and the workspace fetching.
app-proxy
rum: https://app.datadoghq.com/rum/sessions?query=%40view.id%3A8063e1a8-0612-4aae-8992-0c5ff1623c88%20%40type%3Aview&agg_m=count&agg_m_source=base&agg_t=count&cols=&event=AwAAAZRH7cXuh-qITwAAABhBWlJIN2NYdUFBQ2RXOTdVUDVxYWFMc2gAAAAkMDE5NDQ3ZWQtZWM0OC00ZTQxLWJjOWUtNDcyN2VhNzBhMjMwAAAAGQ&fromUser=false&track=rum&viz=stream&from_ts=1736287373547&to_ts=1736373773547&live=true

[perf] Skip expensive `PIPELINE_EXPLORER_ROOT_QUERY` query if viewing an asset job and prefer asset rendering is enabled

---

docs/content/about/releases.mdx
docs/markdoc-component-documentation.md
docs/next/components/markdoc/Badges.tsx
docs/next/components/mdx/MDXComponents.tsx
docs/next/markdoc/tags.js
docs/next/styles/globals.css
docs/sphinx/_ext/dagster-sphinx/dagster_sphinx/__init__.py
docs/sphinx/_ext/dagster-sphinx/dagster_sphinx/docstring_flags.py
docs/sphinx/sections/api/apidocs/utilities.rst

Same as #25362 but for the new preview decorator introduced in https://github.com/dagster-io/dagster/pull/26747

[docs] display preview warning and decorator info

---

docs/content/about/releases.mdx
docs/markdoc-component-documentation.md
docs/next/components/markdoc/Badges.tsx
docs/next/components/mdx/MDXComponents.tsx
docs/next/markdoc/tags.js
docs/next/styles/globals.css
docs/sphinx/_ext/dagster-sphinx/dagster_sphinx/__init__.py
docs/sphinx/_ext/dagster-sphinx/dagster_sphinx/docstring_flags.py
docs/sphinx/sections/api/apidocs/utilities.rst

Same as https://github.com/dagster-io/dagster/pull/25362 but for the new beta decorator introduced in https://github.com/dagster-io/dagster/pull/26748

[docs] display beta warning and decorator info

---

CHANGES.md

Changelog for 1.9.7. Also fix non-standard headers that creeped in in last several months.   Version headers are now always level 1, which simplifies parsing.

[changelog] 1.9.7

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetEdges.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/assetKeyTokensInRange.ts
js_modules/dagster-ui/packages/ui-core/src/asset-graph/layout.ts
js_modules/dagster-ui/packages/ui-core/src/assets/AssetPartitions.tsx
js_modules/dagster-ui/packages/ui-core/src/gantt/GanttChart.tsx
js_modules/dagster-ui/packages/ui-core/src/gantt/GanttChartLayout.ts
js_modules/dagster-ui/packages/ui-core/src/gantt/GanttStatusPanel.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillRow.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/StepLogsDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/ui/SectionedLeftNav.tsx

Use a set to avoid searching an array within `runStatusForPartitionKey` because it's already being called on an array of partition keys.

Fix O(n^2) logic part 2

---

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py

Summary:
Returning None in the situation described here does not work, and has not worked for some time. Update the comment to explain how you actually conditionally output a result from an asset.

Update out of date "output_required" explanation on @asset

---

docs/sphinx/_ext/sphinx-mdx-builder/sphinxcontrib/mdxbuilder/writers/mdx.py

Map the Preview, Beta and Superseded flags to warning level for Docusaurus/docs beta styling. See comment [here](https://github.com/dagster-io/dagster/pull/26821#issuecomment-2573210418).

[docs-beta] Map API lifecycle flags to style levels for docs beta

---

docs/docs-beta/scripts/vercel-sync-api-docs.sh

- The `sync-api-docs` previously only worked on Linux (Vercel) due to locale settings
- This makes the script platform agnostic for easier local building of API docs
`yarn sync-api-docs`
NOCHANGELOG

[docs-beta] make sync-api-docs directive platform agnostic

---

CHANGES.md

Add changelog entry for run status sensor change in `1.9.6`, will modify GH release notes manually.
Inspection

add changelog entry to 1.9.6 for job name filtering

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/__init__.py
python_modules/dagster-graphql/dagster_graphql/schema/paging.py

Remove a class with no references (that also happens to be one of the few "questionable" `graphene.Int` uses left in the codebase).
BK

[graphql] Remove the unused `GrapheneCursor` class

---

python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py
python_modules/libraries/dagster-dg/dagster_dg/cli/code_location.py
python_modules/libraries/dagster-dg/dagster_dg/cli/global_options.py
python_modules/libraries/dagster-dg/dagster_dg/config.py
python_modules/libraries/dagster-dg/dagster_dg/context.py
python_modules/libraries/dagster-dg/dagster_dg/generate.py
python_modules/libraries/dagster-dg/dagster_dg/utils.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_code_location_commands.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_type_commands.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_custom_help_format.py
python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
python_modules/libraries/dagster-dg/setup.py
python_modules/libraries/dagster-dg/tox.ini

Add a global option to disable manage of environment with `uv` (`--[no-]dg-managed-environment`) to `dagster-dg`. This has a few effects:
- Prevent any `dg` command from automatically creating a venv in the root directory and corresponding `uv.lock`.
- Causes all calls to the `dagster-components` CLI (which is used to retrieve registered components) to use the current python environment instead of `uv run`.
- Disables the cache.
NOTE: The reason we disable the cache is that caching logic currently depends on `uv.lock` to generate the cache key. It is possible we will later introduce support for the cache without `uv` by falling back to an alternative mechanism to derive a cache key from the python environment.

[components] Add `--[no-]-use-dg-managed-environment` option to `dagster-dg`

---

docs/docs-beta/docs/guides/build/external-pipelines/aws-lambda-pipeline.md
docs/docs-beta/docs/guides/build/external-pipelines/databricks-pipeline.md
docs/sphinx/sections/api/apidocs/libraries/dagster-databricks.rst
docs/sphinx/sections/api/apidocs/libraries/dagster-pipes.rst

While working on new "build" docs, I noticed that some classes were missing from our API docs. This PR updates the relevant `rst` files and corresponding `<PyObject /> `  components in markdown docs.

DOC-680 Update rst files with missing classes and update PyObjects in docs

---

python_modules/libraries/dagster-components/dagster_components/cli/list.py
python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py
python_modules/libraries/dagster-dg/dagster_dg/cli/component_type.py
python_modules/libraries/dagster-dg/dagster_dg/context.py
python_modules/libraries/dagster-dg/dagster_dg/utils.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_type_commands.py

Remove the restrictions on `dg component-type list` and `dg component-type info` that they function inside a code location directory.
`dg component-type generate` still requires a code location directory, since without it we don't know where to place the generated component type.

[components] Allow dg component-type list to function outside code location

---

python_modules/dagster/dagster/_core/definitions/decorators/decorator_assets_definition_builder.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_partitioned_assets.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py

In the case that a partitions_def was passed in, the previous logic would override both the group name and the partitions def. This handles those two cases separately
New unit tests
[dagster-dbt] Fixed an issue where group names set on partitioned dbt assets created using the `@dbt_assets` decorator would be ignored

[bug] Fix issue when passing in a top-level partitions definition with specs that have a group name

---

js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/WorkspaceContext.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/__fixtures__/Workspace.fixtures.ts
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/__tests__/WorkspaceContext.test.tsx

The main issue is that `previousLocationVersionsRef.current` was only being updated after ALL code locations were fetched. That means that whenever a code location was fetched, we'd think that all of the code locations were stale again, including the one we just fetched, because `previousLocationVersionsRef.current` was still pointing to the old version. To fix this I instead update `previousLocationVersionsRef.current` after each individual fetch. In addition, I added some extra guards within `fetchLocationData` itself to prevent overfetching due to someone calling `refetch` multiple times.
Added a jest test that failed without these changes.

Fix WorkspaceContext over-fetching code locations on cascading updates.

---

python_modules/dagster/dagster/_core/definitions/module_loaders/load_defs_from_module.py
python_modules/dagster/dagster_tests/definitions_tests/module_loader_tests/test_module_loaders.py

Same as https://github.com/dagster-io/dagster/pull/26546 but for a package module given its name. 

[module-loaders] Add load_definitions_from_package_name

---

python_modules/dagster/dagster/_core/definitions/module_loaders/load_asset_checks_from_modules.py
python_modules/dagster/dagster/_core/definitions/module_loaders/load_assets_from_modules.py
python_modules/dagster/dagster/_core/definitions/module_loaders/object_list.py
python_modules/dagster/dagster_tests/definitions_tests/module_loader_tests/checks_module/__init__.py
python_modules/dagster/dagster_tests/definitions_tests/module_loader_tests/test_load_assets_from_modules.py

Previously, even when specs weren't getting loaded, we began erroring on collisions involving them.
This fixes by excluding specs from collision detection if they aren't getting loaded. This is still a bit hacky - ideally we can specify up front exactly what we want to load in a more principled manner.
Added new test case for the expected behavior - that when include_specs is not set, we don't error when a duplicate spec exists, and do error when it does.
- Fixed a bug with load_assets_from_x functions where we began erroring when a spec and AssetsDefinition had the same key in a given module. We now only error in this case if include_specs=True.

Fix spec error conditions in loaders

---

docs/docs-beta/docs/api/api-lifecycle.md

As title, following requested changes in this [PR stack](https://github.com/dagster-io/dagster/pull/26747).
Docs preview

[docs-beta] Change preview and beta language in API lifecycle guide

---

python_modules/libraries/dagster-components/dagster_components/cli/generate.py
python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components/core/component_generator.py
python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/generator.py
python_modules/libraries/dagster-components/dagster_components/lib/definitions_component/component.py
python_modules/libraries/dagster-components/dagster_components/lib/definitions_component/generator.py
python_modules/libraries/dagster-components/dagster_components/lib/pipes_subprocess_script_collection.py
python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
python_modules/libraries/dagster-components/dagster_components/lib/test/simple_asset.py
python_modules/libraries/dagster-components/dagster_components/lib/test/simple_pipes_script_asset.py
python_modules/libraries/dagster-components/dagster_components_tests/rendering_tests/custom_scope_component/component.py

I want to play around with more generic components, and I think having this be a classmethod is both more consistent with other methods a user might implement (e.g. `load`), and also more flexible

[components] Convert params schema from classvar to classmethod

---

python_modules/libraries/dagster-components/dagster_components/core/dsl_schema.py
python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
python_modules/libraries/dagster-components/dagster_components/utils.py
python_modules/libraries/dagster-components/dagster_components_tests/code_locations/dbt_project_location/components/jaffle_shop_dbt/component.yaml
python_modules/libraries/dagster-components/dagster_components_tests/code_locations/sling_location/components/ingest/component.yaml
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_sling_integration_test.py
python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_spec_processing.py

The translator language was fairly confusing. Went through some iterations but arrived in a place where the translation layer can be overridden in yaml using the `asset_attributes` field. This field will have the domain-specific object in scope, meaning you can use that to set attributes if desired.
At the same time, this leaves open the ability for users to specify a python-based translator to override the default one.
Made the following changes:
1. Because we want to use the key `asset_attributes` to replace `translator`, this conflicts with the global `asset_attributes` field, so I renamed this to be `asset_transforms`. This gives a better sense of the fact that you're doing specific operations over all assets (imo)
2. Removed the weird subclassing stuff with the existing asset …

[components] Remove translator terminology from SlingReplicationCollectionComponent

---

python_modules/libraries/dagster-components/dagster_components/core/component_rendering.py
python_modules/libraries/dagster-components/dagster_components/core/dsl_schema.py
python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
python_modules/libraries/dagster-components/dagster_components_tests/rendering_tests/test_component_rendering.py

This creates a new FieldInfo subclass, which carries additional metadata about what the resolved field will look like, and what data will be available to resolve it.
We have to create a subclass of FieldInfo because pydantic will only recognize things inside of the `Annotated[]` block if they are instances of FieldInfo, and the base FieldInfo does not have any fields that we can stash arbitrary objects in.
NOCHANGELOG

[components] Allow specification of rendering scope

---

helm/dagster/schema/schema/charts/dagster/subschema/daemon.py
helm/dagster/schema/schema/charts/dagster/subschema/migrate.py
helm/dagster/schema/schema/charts/dagster/subschema/webserver.py
helm/dagster/schema/schema_tests/test_dagster_daemon.py
helm/dagster/schema/schema_tests/test_instance_migrate.py
helm/dagster/templates/deployment-daemon.yaml
helm/dagster/templates/helpers/_deployment-webserver.tpl
helm/dagster/templates/job-instance-migrate.yaml
helm/dagster/values.schema.json
helm/dagster/values.yaml

This PR adds support for sidecar containers for all Dagster pods, for versions of K8s after 1.29 ([Native Sidecars](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/)).
Note: This is a copy of the PR #24834 from September 2024. The original author @tdipadova3rd has submitted this feature but, unfortunately, hasn't responded to some follow-up comments. The CI/CD pipeline also failed due to code formatting issues. I reintegrated his changes into the latest upstream version while fixing the code formatting issues. 
Original summary: Google recommends using Cloud SQL Auth Proxy to connect to Cloud SQL from Kubernetes. The proxy is deployed as a sidecar container, allowing application pods to connect to PostgreSQL as localhost while the proxy handles authentication and …

Sidecar Container Support (updated)

---

python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/test_launching.py

When ECS Run Launcher is used it calculates ECS Task `networkConfiguration` [here](https://github.com/dagster-io/dagster/blob/0f2de9b6a006e45cd70f886cad0c8eebd7512036/python_modules/libraries/dagster-aws/dagster_aws/ecs/tasks.py#L375). This works well for AWS Tasks with `awsvpc` networkMode, but for other networkModes the configuration should not be passed to the run task API call ([documentation](https://docs.aws.amazon.com/cli/latest/reference/ecs/run-task.html)).
The problem is that if you set `networkConfiguration` to null, example:
```
run_launcher:
module: "dagster_aws.ecs"
class: "EcsRunLauncher"
config:
task_definition: arn:aws:ecs:...
container_name: ...
run_task_kwargs:
networkConfiguration: null
```
then the null value will be passed "as is" to the API call, causing a following …

Enable removing networkConfiguration from AWS ECS Run Task API call

---

helm/dagster/schema/schema/charts/dagster/subschema/daemon.py
helm/dagster/schema/schema/charts/dagster/subschema/migrate.py
helm/dagster/schema/schema/charts/dagster/subschema/webserver.py

https://github.com/dagster-io/dagster/pull/26934 added the old style `List` which is not imported anymore and tests are currently broken.
The `helm` suite in buildkite tests should pass.

Fix type annotation List -> list

---

docs/sphinx/conf.py
python_modules/dagster/MANIFEST.in
python_modules/dagster/dagster/_utils/schedules.py
python_modules/dagster/dagster/_vendored/README.md
python_modules/dagster/dagster/_vendored/croniter/LICENSE
python_modules/dagster/dagster/_vendored/croniter/__init__.py
python_modules/dagster/dagster/_vendored/croniter/croniter.py
python_modules/dagster/setup.py

Summary:
The author of croniter has stated their intention to abandon the project and potentially remove it from PyPI. Guard against future breakages by vendoring.
Test Plan: BK
The `croniter` package is now vendored in dagster.

vendor croniter

---

python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

Summary:
This can happen if a step worker dies before the step starts. Not sure if what we are testing here is the desired behavior, but gives us a test case to change if we chagne the underlying behavior.

Add test case for step stats with a retry event before a step start event

---

python_modules/dagster/dagster/_core/scheduler/instigation.py
python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster/_daemon/sensor.py
python_modules/dagster/dagster/_scheduler/scheduler.py
python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
python_modules/dagster/dagster_tests/declarative_automation_tests/daemon_tests/test_asset_daemon_failure_recovery.py
python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py

Add a field to TickData capturing the number of consecutive times that this schedule or sensor has failed (across multiple ticks). This differs from the existing failure_count field, which tracks whether or not a particular tick should retry or not before moving on. This allows you to determine when a given sensor has failed more than a certain number of times consecutively.
New test cases
NOCHANGELOG

Add a "consecutive_failure_count" field to TickData

---

docs/docs-beta/src/theme/DocCard/index.tsx
docs/docs-beta/static/images/integrations/placeholder_64x64.svg

Instead of showing a placeholder image, show no logo at all if one is not defined.
**Before**
**After**
NOCHANGELOG

[docs-beta] show no logo instead of placeholder if none is defined

---

CHANGES.md
scripts/generate_changelog.py

To match how our doc parser expected them to be structred.

Change header level for changelog

---

.dockerignore

.yarn is checked in and should be copied over to access the yarn executable

dont dockerignore .yarn

---

js_modules/dagster-ui/packages/ui-core/src/runs/RunTimeline.tsx

The "+X more" link in the timeline popover is broken for segments for  "Ad hoc materializations" and automations without specific code objects.
Remove the link and virtualize the list instead.
View a timeline that has chunks with lots of runs in them. Hover, verify that the virtualized list renders and behaves properly.
Find a chunk with just a couple of runs, verify that the popover height is not excessive.
[ui] In the run timeline, replace the "+ more" link in the hover popover by displaying all run IDs and timings in the list.

[ui] Virtualize timeline run popover list

---

integration_tests/test_suites/dagster-azure-live-tests/integration_tests/dagster-yamls/access-key-credential.yaml
integration_tests/test_suites/dagster-azure-live-tests/integration_tests/dagster-yamls/default-credential.yaml
integration_tests/test_suites/dagster-azure-live-tests/integration_tests/dagster-yamls/secret-credential.yaml

Fixes integration tests after most recent PR which disabled default log capture
Existing tests now work

[dagster-azure] fix integration tests

---

examples/experimental/dagster-blueprints/examples/builtin-blueprints/builtin_blueprints/pipelines/process_customers.yaml
python_modules/dagster/dagster/_utils/pydantic_yaml.py
python_modules/dagster/dagster/_utils/source_position.py
python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components/core/component_decl_builder.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions/validation_error_file/component.yaml
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions/validation_error_file/definitions.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/validation/basic_component_invalid_value/component.yaml
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/validation/basic_component_missing_value/component.yaml
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/validation/basic_component_success/component.yaml
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/validation/nested_component_invalid_values/component.yaml
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/validation/nested_component_missing_values/component.yaml
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_definitions_component.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/validation_tests/basic_components.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/validation_tests/test_component_validation.py

Ports over the YAML line tracking functionality to enrich Pydantic `ValidationErrors` thrown when instantiating components. The filepath of the loaded YAML file & offending line number are appended to the error message.
```python
E       ValidationError: 2 validation errors for MyNestedComponentSchema
E         `nested.foo.an_int at /var/folders/bc/4npnrqyd46l4vbbkdsdsw3_h0000gn/T/tmpte2ox0bw/component.yaml:6`
E           Field required [type=missing, input_value={'a_string': 'test'}, input_type=dict]
E             For further information visit https://errors.pydantic.dev/2.8/v/missing
E         `nested.baz.a_string at /var/folders/bc/4npnrqyd46l4vbbkdsdsw3_h0000gn/T/tmpte2ox0bw/component.yaml:11`
E           Field required [type=missing, input_value={'an_int': 10}, input_type=dict]
E …
```

[components] Enrich pydantic validation errors with filepaths, line numbers

---

python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/test_launching.py

This provides a way to adjust the task definitions created by the EcsRunLauncher. For example, if you're worried about hitting a revision limit, this gives you a way to start over.
BK
[dagster-aws] Added a `task_definition_prefix` argument to `EcsRunLauncher`, allowing the name of the task definition families for launched runs to be customized. Previously, the task definition families always started with `run`.

Add a "task_definition_prefx" config option for EcsRunLauncher.

---

python_modules/libraries/dagster-components/dagster_components/core/schema/base.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/validation/basic_component_extra_value/component.yaml
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/validation/nested_component_extra_values/component.yaml
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/validation_tests/basic_components.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/validation_tests/test_component_validation.py

Updates `ComponentSchemaBaseModel` to explicitly disallow extra inputs (though users can override this in their own component schema classes). We augment extra input errors like other validation errors.
New test cases.

[components] Default disallow extra inputs

---

python_modules/dagster/dagster/_core/definitions/module_loaders/load_asset_checks_from_modules.py
python_modules/dagster/dagster/_core/definitions/module_loaders/load_assets_from_modules.py
python_modules/dagster/dagster/_core/definitions/module_loaders/object_list.py
python_modules/dagster/dagster_tests/definitions_tests/module_loader_tests/test_module_loaders.py

Fixes https://github.com/dagster-io/dagster/issues/27051.
Previously, even when we weren't actually going to return them, `DagsterObjectList` would load all objects of loadable type.
This PR allows you to specify up front which types to load. This allows us to avoid making changes to objects which we aren't actually loading.
A new test which showcases prefix behavior with load_assets_from_module with and without asset specs.
- Fixed a bug with `load_assets_from_modules` where AssetSpec objects were being given the key_prefix instead of the source_key_prefix. Going forward, when load_specs is set to True, only the source_key_prefix will affect AssetSpec objects.

Allow specifying up front which objects to load

---

python_modules/dagster-graphql/dagster_graphql/schema/logs/events.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_runs.py

Steps that have a step up for retry event before the step start event will have a null status.
BK
- Fixes a bug where the UI will hit an unexpected error when loading details for a run containing a step retry before the step has started.

add graphql step stats fix for non-status steps

---

python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/emr.py
python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/utils.py

This function will be reused downstack in the Pipes client for AWS EMR Containers
Simple refactor so no testing (pyright is enough)

[dagster-aws] reusable function for injecting env vars into EMR configurations

---

js_modules/dagster-ui/packages/ui-core/src/runs/HourlyDataCache/HourlyDataCache.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/HourlyDataCache/__tests__/HourlyDataCache.test.tsx

There's a race condition where if someone subscribes to data before the indexeddb cache has loaded then they never get notified by about the data from the indexeddb cache. To fix this I ensure the indexeddb cache data has loaded before notifying subscribers to the data.
jest

[HourlyDataCache] Wait for indexeddb data to load before notifying subscriber of existing data on initial subscription

---

python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_check_decorator.py
python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_decorator_with_check_specs.py

Previously, `keys_by_input_name` did not contain the ins specified by additional_ins or additional_deps in the @asset_check decorator. 
This fixes to include those keys as part of the property.
This was causing https://github.com/dagster-io/dagster/issues/27003#issuecomment-2583349296 in some yet to be determined way. We've been able to confirm the fix, but have not yet pinpointed a straightforward repro.
- Fixes the problematic edge case. Add a bunch of new assertions to prevent regressions in the future.
- Fixed a bug with asset checks where additional_deps/additional_ins were not being threaded through properly in certain cases, and would result in errors at job creation.

fix additional_deps not showing up on assetsdefinition

---

python_modules/libraries/dagster-aws/dagster_aws/ecs/tasks.py
python_modules/libraries/dagster-aws/dagster_aws/ecs/utils.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/test_launching.py

We observed an issue where subtly different formats of linuxParameters and/or specifying taskRoleArn in differnet formats was causing this logic to incorrectly create a new task definition for each run.
The risk of this is that you might encounter a situation where you try to make a config change and it isn't automatically propagated to runs until you redeploy. Plan is to separately address that by giving you a way to configure a prefix on the run launcher so that you can bump the task definition name when needed.
New test cases
[dagster-aws] Fixed an issue with the EcsRunLauncher where it would sometimes create a new task definition revision for each run if the "task_role_arn" or "execution_role_arn" parameters were specified without the `arn:aws:iam:` prefix.

Make EcsRunLauncher task definition deduping less strict

---

js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillAssetPartitionsTable.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunStatuses.tsx

https://linear.app/dagster-labs/issue/FE-717/fix-links-to-runs-page-from-backfill-overview-page
- With the "legacy runs page" FF turned on, clicking the header links go to the main runs list, with the filters applied
- With the new run feed, the backfill has it's own Runs tab. The header link takes you to that run tab which expands the runs within the backfill by default and keeps you within the backfill nav.
I also updated this code to re-use the RunStatus lists we use elsewhere, and made a note indicating why the "in progress" column includes queued in this case to match the backend calculation.
[ui] Clicking to view runs with a specific status from the backfill overview switches to the new backfill runs tab with your filters applied, instead of the global runs page.

[ui] When clicking backfill header links to runs, expand runs within backfills

---

js_modules/dagster-ui/packages/ui-core/src/assets/CurrentRunsBanner.tsx

As titled - I also changed this text slightly to make it more direct.

[ui] Fix incorrect “Run are queued” copy in the current run banner

---

python_modules/libraries/dagster-components/dagster_components/cli/check.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/validation_tests/test_cases.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/validation_tests/test_component_validation.py

Some of the raw pyright errors are not very clear when displayed inline - in particular the "missing field" error, which with `dg check` renders pointing at the preceding field.
This PR updates that error message to be more direct:
Before:
```python
/Users/ben/repos/components_demo/jaffle_platform/jaffle_platform/components/ingest_files/component.yaml:5 - sling_replication_collection params.replications.0.path Field required
| 
4 |   replications:
5 |     - {}
|       ^ Field required
| 
```
After:
```python
/Users/ben/repos/components_demo/jaffle_platform/jaffle_platform/components/ingest_files/component.yaml:5 - sling_replication_collection params.replications.0.path Field required
| 
4 |   replications:
5 |     - {}
|       ^ Field `path` is required but not provided
|
```
Update unit …

[dg][cli] augment certain pyright errors for dg check

---

js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/AutomaterializeMiddlePanelWithData.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/EvaluationDetailDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/EvaluationListRow.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/runTableFiltersForEvaluation.tsx

Update `EvaluationDetailDialog` to have two tabs: Evaluation and Runs. The first shows what the dialog currently shows, which is the details of the evaluation itself. The second is a filtered Runs table with the runs associated with the evaluation.
View dialog from automation sensor and asset automations list. Verify that the tabs behave and render correctly.
[ui] When viewing details of an automation evaluation, show the relevant runs in a tab within the same dialog.

[ui] Add tabs to evaluation dialog

---

python_modules/dagster/dagster/_utils/pydantic_yaml.py
python_modules/libraries/dagster-components/dagster_components/cli/check.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/validation/invalid_component_file_model/component.yaml
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/validation_tests/test_cases.py

We separately populate the Pydantic model for `ComponentFileModel` before processing the component decl itself. If we hit a yaml error here, we should print the enriched message, and handle it properly in `dg component check`
```python
/Users/ben/repos/components_demo/jaffle_platform/jaffle_platform/components/ingest_files/component.yaml:1 - type Input should be a valid string
| 
1 | type: {}
|       ^ Input should be a valid string
2 | 
3 | params:
4 |   rasdfasdf
| 
/Users/ben/repos/components_demo/jaffle_platform/jaffle_platform/components/ingest_files/component.yaml:4 - params Input should be an object
| 
1 | type: {}
2 | 
3 | params:
4 |   rasdfasdf
|   ^ Input should be an object
|
```

[dg][cli] Properly augment top-level ComponentFileModel Pydantic errors

---

python_modules/libraries/dagster-components/dagster_components/lib/test/__init__.py
python_modules/libraries/dagster-components/dagster_components/lib/test/complex_schema_asset.py
python_modules/libraries/dagster-components/dagster_components_tests/cli_tests/test_commands.py
python_modules/libraries/dagster-dg/dagster_dg/cli/component_type.py
python_modules/libraries/dagster-dg/dagster_dg/docs.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_commands.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_type_commands.py
python_modules/libraries/dagster-dg/dagster_dg_tests/utils_tests/test_sample_yaml.py
python_modules/libraries/dagster-dg/setup.py

Extremely bare-bones sample yaml schema generator.
Currently this spits out a "maximal" version of the schema, including all optional parameters, which is better suited for docs usecases.
If we adapt this to be used in the component generation sequence, we'll probably want to use a minimal example.
The one thing here that adds an unfortunate amount of complexity is the injection of comments into the generated yaml (particularly to denote the available scope). Yaml libraries don't handle comments very nicely and so we need to do some fancy stuff to get this to work.
NOCHANGELOG

[components][docs] Schema viewer

---

python_modules/libraries/dagster-components/dagster_components/core/schema/metadata.py
python_modules/libraries/dagster-components/dagster_components_tests/rendering_tests/test_schema_resolution.py

Fixes a weird issue I ran into. In essence, in pydantic 3.8.x, the generated json schema will have the `json_schema_extras` stored on dereferenced json schemas of any subtype, whereas in 3.10.x, the extras will be stored on the reference itself. No idea why this is different but it is what it is.
NOCHANGELOG

[components][fix] Fix issue with additional scope determination

---

python_modules/dagster-graphql/dagster_graphql/schema/instigation.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py
python_modules/dagster/dagster/_core/utils.py

Fix an issue we observed where ticks that emitted backfills were producing an error.
BK (new test case)
Fixed an issue where the tick timeline wouldn't load for an automation condition sensor that emitted a backfill.

fix querying for runs on a tick that emits backfill IDs as well as runs

---

docs/next/util/redirectUrls.json

From Izzy:
> The fivetran [Docs overview](https://dagster.io/integrations/dagster-fivetran) button leads to a [404](https://docs.dagster.io/integrations/fivetran)
NOCHANGELOG

[docs] add redirect for /integrations/fivetran

---

python_modules/libraries/dagster-components/dagster_components/__init__.py
python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components/lib/test/all_metadata_empty_asset.py
python_modules/libraries/dagster-components/dagster_components/lib/test/complex_schema_asset.py
python_modules/libraries/dagster-components/dagster_components/lib/test/simple_asset.py
python_modules/libraries/dagster-components/dagster_components/lib/test/simple_pipes_script_asset.py
python_modules/libraries/dagster-dg/dagster_dg/templates/COMPONENT_TYPE/COMPONENT_TYPE_NAME_PLACEHOLDER.py.jinja
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_commands.py

This updates `dg component-type generate` to use the newer generation format and generally polishes its output. It also adds a test to make sure that a generated component type can successfully generate a component instance right out of the gate.
Also updates test lib components to new component format.
New unit tests, manually generated component type, component instance from type, loaded via `dagster dev`.

[components] Update component type generation and test components

---

MIGRATION.md
docs/docs-beta/docs/guides/migrate/version-migration.md

- Includes `MIGRATION.md` external content as `/guides/migration/version-migration`
`yarn start`
NO CHANGELOG

[DOC-640][docs-beta] add version migration external reference

---

python_modules/libraries/dagster-k8s/dagster_k8s/ops/k8s_job_op.py

Should fix the bug described here - https://github.com/dagster-io/dagster/issues/26626
The `execute_k8s_job` method uses `watch.stream()` to stream logs from k8s pods. When the client enters a stale state, we should call `stream` again. See the bug report for more information.
I was unable to fix a repeatable way for recreating the issue and there are not existing tests for `execute_k8s_job`.
I deployed a similar fix to our dev and prod environments, and the problem has not appear yet. At the very least I can say that it didn't degrade the stability of this method. 

[bugfix] Restart k8s log stream on urllib3 failure

---

docs/dagster-university/pages/dagster-dbt/lesson-2/2-set-up-the-dagster-project.md
docs/dagster-university/pages/dagster-essentials/lesson-2/create-dagster-project.md
docs/dagster-university/pages/dagster-essentials/lesson-2/requirements-and-installation.md

Removes unnecessary quotations for `pip install` commands, as suggested by user:
https://github.com/dagster-io/project-dagster-university/issues/42
NOCHANGELOG

[dagster-university] update pip install quoting

---

docs/content/integrations.mdx
examples/project_dagster_modal_pipes/project_dagster_modal_pipes/pipeline_factory.py
examples/project_dagster_modal_pipes/project_dagster_modal_pipes/resources.py
examples/project_dagster_modal_pipes/setup.py
pyright/master/requirements-pinned.txt

It was determined that the `-contrib-` differentiator in package names is not necessary, so the `dagster-contrib-modal` has been refactored and re-published as `dagster-modal`. This updates the example project using the package.
NOCHANGELOG

[project_dagster_modal_pipes] rename dagster-contrib-modal to dagster-modal

---

docs/next/util/__tests__/paginatedChangelog.test.ts

- Test has been updated to reflect new h2 heading level for releases in CHANGES.md
NOCHANGELOG

[docs] update changelog pagination test with new structure

---

docs/content/concepts/automation/declarative-automation/customizing-automation-conditions.mdx
examples/docs_snippets/docs_snippets/concepts/declarative_automation/update_specific_older_partition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py
python_modules/dagster/dagster_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_automation_condition.py

Users often want to make small changes to the existing policies. There is an existing utility to remove a sub-condition (`.without(…)`), and you can add a new sub-condition with `&`.
However, these utilities aren't always the most ergonomic for certain use cases.
This would allow the following types of changes to our examples:
[Older time window partitions](https://docs.dagster.io/concepts/automation/declarative-automation/customizing-automation-conditions#update-an-older-time-partition-when-using-automationconditionon_cron)
before:
```python
condition = five_days_ago_condition & AutomationCondition.eager().without(
AutomationCondition.in_latest_time_window(),
)
```
after:
```python
AutomationCondition.eager().replace(
"in_latest_time_window", five_days_ago_condition
)
```
Added unit …

Implement `AutomationCondition.replace()` function

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py
python_modules/dagster/dagster_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_automation_condition.py

If I have `my_big_complex_condition` and I modify a small piece, I can always relabel, but maybe I don't want to automatically lose the label.
One new unit test + existing tests.
Using `AndAutomationCondition.without()` no longer removes the condition's label.

Keep label upon `AndAutomationCondition.without()`

---

python_modules/libraries/dagster-databricks/dagster_databricks/pipes.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_pipes.py

Currently we do not support log forwarding in Databricks Pipes in the case where the job is being executed on a shared Databricks cluster. 
This PR makes this possible by adding an option for enabling log forwarding via Pipes messages with the  `PipesDefaultLogWriter` in the remote Pipes session. 
Added a test
[dagster-databricks] Databricks Pipes now support log forwarding when running on existing clusters. It can be enabled by setting `PipesDbfsMessageReader(include_stdio_in_messages=True)`.

[dagster-databricks] forward logs from shared clusters

---

pyright/alt-1/requirements-pinned.txt
pyright/master/requirements-pinned.txt
python_modules/libraries/dagster-aws/dagster_aws/pipes/__init__.py
python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/__init__.py
python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/emr.py
python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/emr_containers.py
python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/utils.py
python_modules/libraries/dagster-aws/dagster_aws_tests/pipes_tests/test_emr.py
python_modules/libraries/dagster-aws/dagster_aws_tests/pipes_tests/test_emr_containers.py
python_modules/libraries/dagster-aws/setup.py

This PR adds `PipesEMRContainersClient` - a Pipes client for running workloads on AWS [EMR on EKS](https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/emr-eks.html) with Dagster. 
`emr-containers` is the correct AWS service name for EMR on EKS.
The only supported message reader is `PipesS3MessageReader`. 
CloudWatch logs appear under "random" prefixes (the internal container id is injected) and are not reliable enough. 
1. Mock which checks the correctness of the `start_job_run` call
2. Manual tests against a real AWS EMR Containers cluster. Tested a few combinations of parameters. Tested reading messages from S3.
[dagster-aws] Added `PipesEMRContainersClient` - a Dagster Pipes client for running and monitoring workloads on [AWS EMR on …

[dagster-aws] add PipesEMRContainersClient

---

python_modules/libraries/dagster-polars/setup.py

BK started failing upon PyArrow 19 release (and I can replicate it on my machine); it's probably an issue with Polars not supporting it properly.
I don't see any issues on the Polars repo yet, so will see if something pops up tomorrow before trying to debug anything Dagster-specific—would expect that to be quite unlikely.
BK

[dagster-polars] Pin `pyarrow<19.0.0` during tests

---

Makefile

I noticed we are not using `uv` when running `make install_pyright`. Fixing it.

[chore] use uv to install pyright deps

---

python_modules/libraries/dagster-components/dagster_components/core/deployment.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/component_loader.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_code_location_commands.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_commands.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_type_commands.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_custom_help_format.py
python_modules/libraries/dagster-dg/dagster_dg_tests/test_cache.py
python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py

- Fix a bug when scaffolding components that would cause the scaffolded component to be generated at the wrong path when the code location had a hyphenated name (would end up at `foo-bar/components/xxx` instead of `foo_bar/components/xxx`).
- Update tests so that the default test code location is now named `foo-bar` instead of `bar` so that the hyphenated case is tested.
Updated unit tests.

[components] Fix component scaffolding when code location has hyphenated name

---

python_modules/dagster/dagster_tests/definitions_tests/test_op_io.py

Since the collections iterator/iterable types are Python types, this error is no longer thrown, breaking in https://buildkite.com/dagster/dagster-dagster/builds/108268#_. In order to keep this codepath under test (catching non-python, non Dagster types), we alias and import from typing.
Test succeeds locally in 3.10, was not succeeding before.

fix test_not_type_input

---

python_modules/dagster/dagster/_core/execution/plan/objects.py

Summary:
Noticed this while testing user code masking. The error emits the message, then to_string(), which contains the message.
Test Plan:
Launch a run with the redaction env var on, raise an Exception from the asset, view output
Changelog:
Fixed an issue where runs with the `DAGSTER_REDACT_USER_CODE_ERRORS` environment variable enable emitted the same log message twice.

fix redacted errors outputting the message twice

---

integration_tests/test_suites/daemon-test-suite/dagster_dev_command_tests/test_dagster_dev_command.py
python_modules/dagster/dagster/_cli/dev.py
python_modules/dagster/dagster/_core/remote_representation/origin.py
python_modules/dagster/dagster/_core/types/loadable_target_origin.py
python_modules/dagster/dagster/_core/workspace/config_schema.py
python_modules/dagster/dagster/_core/workspace/context.py
python_modules/dagster/dagster/_core/workspace/load.py
python_modules/dagster/dagster/_grpc/proxy_server.py
python_modules/dagster/dagster/_grpc/server.py
python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_grpc_server_registry.py

Same as https://app.graphite.dev/github/pr/dagster-io/dagster/26818/Use-a-single-code-server just for running windows tests
- Previously, the `dagster dev` command would spin up two separate processes for each code location - one for the daemon, and one for the webserver. We've consolidated this to spin up a single set of processes that are used across both the daemon and webserver.

[windows] Use a single code server

---

integration_tests/test_suites/daemon-test-suite/dagster_dev_command_tests/test_dagster_dev_command.py
python_modules/dagster/dagster/_cli/code_server.py
python_modules/dagster/dagster/_cli/dev.py
python_modules/dagster/dagster/_core/remote_representation/grpc_server_registry.py
python_modules/dagster/dagster/_core/remote_representation/origin.py
python_modules/dagster/dagster/_core/types/loadable_target_origin.py
python_modules/dagster/dagster/_core/workspace/config_schema.py
python_modules/dagster/dagster/_core/workspace/context.py
python_modules/dagster/dagster/_core/workspace/load.py
python_modules/dagster/dagster/_daemon/controller.py
python_modules/dagster/dagster/_grpc/proxy_server.py
python_modules/dagster/dagster/_grpc/server.py
python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_grpc_server_registry.py
python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_persistent.py
python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_ping.py

Pre-emptive work before switching the grpc entrypoint of the workspace context from `dagster api grpc` to `dagster code-server start`.
Previously, if the calling process of `dagster code-server start` never explicitly terminated the process, the proxy server could become orphaned. This fixes by introducing a heartbeat mechanism which will automatically shut down the proxy server if a heartbeat hasn't happened in X amount of time.
Added a test for the termination behavior - terminate the underlying grpc server, and then after the requisite amount of time has elapsed, the proxy server should automatically shut down as well.

[single-grpc-server][rfc] introduce a heartbeat to proxy server

---

python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_partitioned_assets.py

Create a helper method `get_partition_key` on `TimeWindowPartitionsDefinition` that allows to get a string representation of a partition key using a string, datetime or date. This can be convenient for hourly/daily/weekly/monthly partitioned assets, as the method will automatically use the relevant partition definition format.
The current implementation will error if it gets a date/datetime that is not a valid partition key for the given partition definition.
Added tests in `test_partitioned_assets.py`. Also, tested in a local Dagster.
> Add get_partition_key helper method that can be used on hourly/daily/weekly/montly partitioned assets to get partition key using date or datetime.

time_window_partitions: add get_partition_key helper method that converts date/datetime to str partition key

---

python_modules/dagster/dagster/_core/events/__init__.py
python_modules/dagster/dagster/_core/storage/compute_log_manager.py
python_modules/libraries/dagster-azure/dagster_azure/blob/compute_log_manager.py

External cloud storage based compute log managers are often configured to only collect and show the url. However, in the case of the AzureBlobComputeLogManager, the provided URL will not be clickable if the storage account or container are private, which is a reasonable choice for commercial users using this feature for security and compliance on Dagster+.
This supports these users by providing both a more easily readable path and a clickable shell command to retrieve the log locally.
How this is implemented is by adding new fields to CapturedLogData to pass the path as well as extra azure specific information so that the frontend can render the shell cmd.
This is a rework of #26982 - applying the changes requested and discussed. 
- dagster dev local (with the AzureBlobComputeLogManager …

[dagster-azure]: Add Azure specific information to captured logs

---

docs/docs-beta/docs/guides/build/project-structure/components.md
docs/docs-beta/docs/guides/build/project-structure/creating-a-component.md
docs/docs-beta/docs/guides/build/project-structure/existing-code-location.md
docs/docs-beta/docs/guides/build/project-structure/using-a-component.md

Unlist components docs -- they can still be accessed via direct URL, but will not appear in the sidebar.
Local build.

Unlist components docs

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/implementation/events.py
python_modules/dagster-graphql/dagster_graphql/schema/logs/events.py

Added support for shell commands in log retrieval by introducing a new `GrapheneLogRetrievalShellCommand` type and extending the `GrapheneLogsCapturedEvent` to include stdout and stderr shell command information.
- Rework of #26983 with requested changes
- See top stack PR.

[dagster-graphql] Add shell cmd to the LogsCapturedData payload

---

python_modules/dagster/dagster/_utils/yaml_utils.py
python_modules/dagster/dagster_tests/utils_tests/test_source_position.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/validation_tests/test_cases.py

This fixes a long-standing bug that would label the source position of the key of a dictionary with the source position of where its value started.
Note that the changed tests make more sense now
NOCHANGELOG

[bug] Fix issue with source position yaml loading

---

python_modules/libraries/dagster-dg/dagster_dg/component.py
python_modules/libraries/dagster-dg/dagster_dg/context.py
python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_type_commands.py

Tweak the behavior of `dg` so that it will _not_ assume a uv-managed virtual environment if we are outside of a declared dg code location. This makes it much easier to use in a regular python env.
Modified existing unit tests.

[components] Don't use uv-managed environment by default when outside code location

---

docs/docs-beta/src/components/CodeExample.tsx

- Adds ability to specify strings, `startAfter` and `endBefore` for filtering `CodeExample` lines
Example usage:
```
<CodeExample
filePath="getting-started/hello-world.py"
language="python"
startAfter="start_after_marker"
endBefore="end_before_marker"
/>
```
```
@dg.asset
def hello(context: dg.AssetExecutionContext):
context.log.info("Hello!")
@dg.asset(deps=[hello])
def world(context: dg.AssetExecutionContext):
context.log.info("World!")
defs = dg.Definitions(assets=[hello, world])
if __name__ == "__main__":
dg.materialize(hello)
dg.materialize(world)
```
NOCHANGELOG

[DOC-723][docs-beta] add startAfter and endBefore props to CodeExample

---

docs/docs-beta/src/components/CodeExample.tsx

Now that code examples have been updated, we can remove the try/catch block so that the build fails when a code example is missing. This will allow us to catch broken examples at build time.
NOCHANGELOG

[docs-beta] remove try/catch block for missing code examples

---

python_modules/libraries/dagster-polars/setup.py

Probably was partially premature in blaming Polars; they are probably just using the Rust crate under the hood to write Parquet, but the issue actually needs to be fixed on Arrow side. Linking the [issue](https://github.com/apache/arrow/issues/45283) so have something to track.

[chore] Add GitHub issue to comment on PyArrow pin

---

python_modules/dagster/dagster/_core/definitions/automation_tick_evaluation_context.py
python_modules/dagster/dagster_tests/declarative_automation_tests/daemon_tests/definitions/hourly_observable_with_partitions.py
python_modules/dagster/dagster_tests/declarative_automation_tests/daemon_tests/test_e2e.py

DA currently creates invalid backfills that never complete when using observable source assets. The simple DA-specific workaround is we just don't do backfills from DA if there are observable source assets.
Added e2e test.
Fix issue wherein declarative automation created (invalid) backfills for observable source assets.

Don't backfill observable assets during flood fill

---

docs/content/_navigation.json
docs/content/concepts/dagster-pipes/pyspark.mdx
docs/next/next-env.d.ts
examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/emr-containers/Dockerfile
examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/emr-containers/dagster_code.py
examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/emr-containers/script.py
examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/pyspark/Dockerfile
examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/pyspark/dagster_code.py
examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/pyspark/docker-compose.yml
examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/pyspark/script.py

This PR adds a detailed tutorial for using Dagster Pipes with (most likely self-hosted) PySpark. 
Everything can be run with `docker compose up`. 
[docs] added a tutorial for using Dagster Pipes with PySpark

[pipes] PySpark tutorial

---

python_modules/libraries/dagster-snowflake/dagster_snowflake/resources.py

Previously, it was not possible to pass a non-base64 encoded private key to the SnowflakeResource, as the `TypeError` would be thrown, as `private_key` was a string, and not bytes when read directly as a parameter and not a file.
This encodes the private key, which allows it to be loaded via `load_pem_private_key`. Now, when the parameter is base64 encoded, and `load_pem_private_key` will throw a `ValueError` and the key will be decoded as a fallback.
Functionality was confirmed working by running the two files below locally, one with the key base64 encoded, and the other with plaintext.
---
Confirmed functionality with plaintext private key.
```
from dagster_snowflake import SnowflakeResource
@dg.asset(kinds={"snowflake"})
def example_snowflake_asset(
context: …
```

[dagster-snowflake] fix bug where private key was required to be base64 encoded

---

.github/workflows/build-docs.yml

Update the vercel publish trigger to only care about release branches and docs prod/master.

disable vercel deploys for PR branches

---

docs/content/concepts/automation/declarative-automation/customizing-automation-conditions.mdx
examples/docs_snippets/docs_snippets/concepts/declarative_automation/allow_dependencies_cron.py
examples/docs_snippets/docs_snippets/concepts/declarative_automation/ignore_dependencies_cron.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py
python_modules/dagster/dagster_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_automation_condition.py

Users often want to make small changes to the existing built-in policies. However, these utilities aren't always the most ergonomic for certain use cases. For example, dep conditions support allowing or ignoring an asset selection, but this has to be done individually for each sub-condition of a complex condition.
Added unit tests.
Implement the `.allow()` and `.ignore()` methods on boolean conditions, which will propagate the asset selection down to any contained dep sub-conditions.

Add `.allow()` and `.ignore()` for bool conditions

---

python_modules/dagster-pipes/dagster_pipes/__init__.py
python_modules/dagster/dagster/_core/definitions/metadata/table.py
python_modules/dagster/dagster/_core/pipes/context.py
python_modules/dagster/dagster_tests/execution_tests/pipes_tests/test_subprocess.py

Right now most of the table metadata types are not supported in pipes. The support for "TableMetadataValue" actually doesn't work right now.
This PR adds support for table-related metadata values: table, table schema, and table column lineage.
One important consideration is what the format should be for nested metadata values; something like TableColumn, for example. Should you have to specify the "type": and "raw_value": keys? My hunch is no, that should only be required at the top level.
Ultimately, in a downstream, I'd like to move all this implementation onto the metadata values themselves so that this can be used more broadly than just pipes.
Added to existing tests.

Support table metadata in pipes

---

python_modules/dagster-pipes/dagster_pipes/__init__.py
python_modules/dagster/dagster/_core/pipes/context.py
python_modules/dagster/dagster_tests/execution_tests/pipes_tests/test_subprocess.py

Adds support for timestamp metadata, which also was unfortunately left behind by pipes.
Additional assertions
- Timestamp metadata is now supported by `dagster-pipes`. It can be set like so:
```python
{"my_key": {"raw_value": 111, "type": "timestamp"}}
```

[dagster-pipes] support timestamp metadata

---

docs/content/concepts/metadata-tags/asset-metadata/table-metadata.mdx
examples/docs_snippets/docs_snippets/concepts/metadata-tags/schema_change_checks.py

Adds a section to the "table metadata" doc on column schema change checks, which are highly relevant to the section but not otherwise mentioned in the documentation.
Docs site + eyes
- A new docs section has been added on checking for columnar schema changes. This can be found in: https://docs.dagster.io/concepts/metadata-tags/asset-metadata/table-metadata#table-metadata

Section on schema change

---

docs/content/concepts/metadata-tags/asset-metadata/table-metadata.mdx
examples/docs_snippets/docs_snippets/concepts/metadata-tags/schema_change_checks.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/schema_change_checks.py

The docstring on schema change checks did not describe how to use them effectively at all - especially egregious given how tedious it is to set columnar metadata outside of dbt use cases.
This PR adds actual code examples.
Eyes
- Improve the docstring of build_coulmn_schema_change_checks to include code examples.

Improve docstring on schema change checks

---

docs/content/concepts/dagster-pipes/aws-ecs.mdx
docs/content/concepts/dagster-pipes/aws-emr-serverless.mdx
docs/content/concepts/dagster-pipes/aws-emr.mdx
docs/content/concepts/dagster-pipes/aws-glue.mdx
docs/content/concepts/dagster-pipes/dagster-pipes-details-and-customization.mdx
docs/content/concepts/metadata-tags/asset-metadata/table-metadata.mdx
examples/docs_snippets/docs_snippets/concepts/metadata-tags/schema_change_checks.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/schema_change_checks.py

This PR adds references to the rich metadata section from the previous PR; wherever we use the rich metadata in a previously undocumented way.
Eyes in docs site.
- [dagster-pipes][docs] Added references to new pipes rich metadata section wherever we make use of the format.

[dagster-pipes] add references to metadata section

---

.gitignore
docs/content/concepts/dagster-pipes/aws-ecs.mdx
docs/content/concepts/dagster-pipes/aws-emr-serverless.mdx
docs/content/concepts/dagster-pipes/aws-emr.mdx
docs/content/concepts/dagster-pipes/aws-glue.mdx
docs/content/concepts/dagster-pipes/dagster-pipes-details-and-customization.mdx
docs/content/concepts/dagster-pipes/subprocess/reference.mdx
docs/content/concepts/metadata-tags/asset-metadata/table-metadata.mdx
examples/docs_snippets/docs_snippets/concepts/metadata-tags/schema_change_checks.py
examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/subprocess/rich_metadata/json_metadata.py
examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/subprocess/rich_metadata/markdown_metadata.py
examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/subprocess/rich_metadata/notebook_metadata.py
examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/subprocess/rich_metadata/path_metadata.py
examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/subprocess/rich_metadata/table_column_lineage.py
examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/subprocess/rich_metadata/table_metadata.py
examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/subprocess/rich_metadata/table_schema_metadata.py
examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/subprocess/rich_metadata/timestamp_metadata.py
examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/subprocess/rich_metadata/url_metadata.py
python_modules/dagster/dagster/_core/definitions/asset_check_factories/schema_change_checks.py

Currently, the formats for setting rich metadata in `dagster-pipes` are undocumented. This PR adds docs for the rich metadata formats that are supported.
Eyes on docs site
- [dagster-pipes][docs] A new section describing how to set rich metadata in dagster pipes that can display effectively in the Dagster UI.

[dagster-pipes] rich metadata docs

---

python_modules/libraries/dagster-sling/dagster_sling/asset_decorator.py
python_modules/libraries/dagster-sling/dagster_sling/dagster_sling_translator.py

Move the asset spec creation from the asset decorator to a `get_asset_spec` method in the translator.

[1/n][dagster-sling] Move asset spec creation to DagsterSlingTranslator.get_asset_spec

---

python_modules/libraries/dagster-sling/dagster_sling/dagster_sling_translator.py

Move the logic in `DagsterSlingTranslator.get_*` methods to `DagsterSlingTranslator._default_*_fn` methods
This is motivated by two main reasons: 
1. To keep `get_asset_spec` implementation as clean as possible in subsequent PR.
2. `DagsterSlingTranslator.get_*` methods will be deprecated in a subsequent PR, but it would be great to keep to docstrings in the code after these will be removed, to help users if needed.

[2/n][dagster-sling] Move logic to default fns in DagsterSlingTranslator

---

python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_sling_integration_test.py
python_modules/libraries/dagster-sling/dagster_sling/dagster_sling_translator.py
python_modules/libraries/dagster-sling/dagster_sling_tests/test_asset_decorator.py
python_modules/libraries/dagster-sling/dagster_sling_tests/test_dagster_sling_translator.py

Use `get_asset_spec(...)` in other `get_*` methods to access the spec attributes. The goal is to only use `get_asset_spec`, `get_*` methods will be deprecated in a subsequent PR.
Some tests were incorrect before - updated in this PR.

[3/n][dagster-sling] Leverage get_asset_spec in DagsterSlingTranslator.get_*

---

python_modules/libraries/dagster-sling/dagster_sling/dagster_sling_translator.py

[4/n][dagster-sling] Mark DagsterSlingTranslator.get_* methods as superseded

---

python_modules/libraries/dagster-sling/dagster_sling/resources.py
python_modules/libraries/dagster-sling/dagster_sling_tests/test_dagster_sling_translator.py

Update all `get_*` callsites to use `get_asset_spec(...)` instead

[5/n][dagster-sling] Update callsites with DagsterSlingTranslator.get_asset_spec

---

python_modules/libraries/dagster-sling/dagster_sling/dagster_sling_translator.py

Update docstring examples to use get_asset_spec. Also fixes a docstring that was incorrect.

[6/n][dagster-sling] Update docs with DagsterSlingTranslator.get_asset_spec

---

python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/emr_serverless.py

Resolve #27217
Checked https://docs.aws.amazon.com/emr/latest/EMR-Serverless-UserGuide/job-states.html again
[dagster-aws] fix PipesEMRServerlessClient failing with QUEUED job state

[dagster-aws] fix QUEUED state in PipesEMRServerlessClient

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py
python_modules/dagster/setup.py

Because [Pyright doesn't support type narrowing on `hasattr()`](https://github.com/microsoft/pyright/issues/6717) (and apparently can't handle the complex `isinstance()` check either without further narrowing using `TypeIs`).
BK

Use `isinstance()` over `hasattr()` for type guard

---

python_modules/libraries/dagster-sling/dagster_sling/dagster_sling_translator.py
python_modules/libraries/dagster-sling/dagster_sling_tests/test_asset_decorator.py

Use `_default` fns in `DagsterSlingTranslator.get_*` to avoid any recursion error. 
The previous implementation will break any custom translator implementation calling `super().get_*()`. This should be avoided because overriding `get_asset_key` by implementing `super().get_asset_key(...).with_prefix(...)` is a very common pattern.
The implementation of `get_asset_spec` is left as-is - we should call `_default` fns in `get_asset_spec` and avoid calling superseded methods.
Updated tests with BK.

[dagster-sling] Use _default fns in DagsterSlingTranslator.get_* fns

---

python_modules/dagster/dagster/_annotations.py

Add a `beta_param` decorator to go with the `beta` decorator added in https://github.com/dagster-io/dagster/pull/26748. The `beta_param` decorator will replace the `experimental_param`.

[utils] Add beta_param decorator

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_all_snapshot_ids.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_pipeline_snapshot.ambr
python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/decorator_assets_definition_builder.py
python_modules/dagster/dagster/_core/definitions/decorators/op_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/source_asset_decorator.py
python_modules/dagster/dagster/_core/definitions/graph_definition.py
python_modules/dagster/dagster/_core/definitions/node_definition.py
python_modules/dagster/dagster/_core/definitions/op_definition.py
python_modules/dagster/dagster/_core/execution/plan/active.py
python_modules/dagster/dagster/_core/execution/plan/plan.py
python_modules/dagster/dagster/_core/execution/plan/step.py
python_modules/dagster/dagster/_core/op_concurrency_limits_counter.py
python_modules/dagster/dagster/_core/snap/execution_plan_snapshot.py
python_modules/dagster/dagster/_core/snap/node.py
python_modules/dagster/dagster_tests/core_tests/execution_tests/test_active.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/__snapshots__/test_active_data.ambr
python_modules/dagster/dagster_tests/core_tests/snap_tests/__snapshots__/test_execution_plan.ambr
python_modules/dagster/dagster_tests/core_tests/snap_tests/__snapshots__/test_job_snap.ambr
python_modules/dagster/dagster_tests/execution_tests/engine_tests/test_op_concurrency.py
python_modules/dagster/dagster_tests/execution_tests/engine_tests/test_step_delegating_executor.py

Tags are a bad mechanism for specifying concurrency controls.  Adds a top-level argument `pool` to asset/op definitions to replace the use of op tags to specify concurrency conditions.
This provides more cues for what you can place concurrency limits on (e.g. op defs not graph defs, asset defs not asset specs)
BK
Adds a top-level argument `pool` to asset/op definitions to replace the use of op tags to specify concurrency conditions.

add pool as top-level definition arg

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_all_snapshot_ids.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_pipeline_snapshot.ambr
python_modules/dagster/dagster/_core/definitions/asset_graph.py
python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/decorator_assets_definition_builder.py
python_modules/dagster/dagster/_core/definitions/decorators/op_decorator.py
python_modules/dagster/dagster/_core/definitions/decorators/source_asset_decorator.py
python_modules/dagster/dagster/_core/definitions/graph_definition.py
python_modules/dagster/dagster/_core/definitions/node_definition.py
python_modules/dagster/dagster/_core/definitions/op_definition.py
python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
python_modules/dagster/dagster/_core/execution/plan/active.py
python_modules/dagster/dagster/_core/execution/plan/plan.py
python_modules/dagster/dagster/_core/execution/plan/step.py
python_modules/dagster/dagster/_core/op_concurrency_limits_counter.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster/_core/snap/execution_plan_snapshot.py
python_modules/dagster/dagster/_core/snap/node.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_external_asset_graph.py
python_modules/dagster/dagster_tests/core_tests/execution_tests/test_active.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/__snapshots__/test_active_data.ambr
python_modules/dagster/dagster_tests/core_tests/snap_tests/__snapshots__/test_execution_plan.ambr
python_modules/dagster/dagster_tests/core_tests/snap_tests/__snapshots__/test_job_snap.ambr
python_modules/dagster/dagster_tests/execution_tests/engine_tests/test_op_concurrency.py
python_modules/dagster/dagster_tests/execution_tests/engine_tests/test_step_delegating_executor.py

Makes pool information available on the remote representation of assets.
BK

thread pool info to remote representation of assets

---

python_modules/libraries/dagster-dlt/dagster_dlt/asset_decorator.py
python_modules/libraries/dagster-dlt/dagster_dlt/resource.py
python_modules/libraries/dagster-dlt/dagster_dlt/translator.py
python_modules/libraries/dagster-dlt/dagster_dlt_tests/test_asset_decorator.py

Move the asset spec creation from the asset decorator to a `get_asset_spec` method in the translator.
Also updates adds tests. No additional test was added for group names, owners, automation condition and auto-materialize policies. It is not recommended to update these values by overriding `get_asset_spec` because they are not related to dlt specifically.
Updated and new tests with BK

[1/n][dagster-dlt] Move asset spec creation to DagsterDltTranslator.get_asset_spec

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql/schema/solids.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_all_snapshot_ids.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_assets.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_solids.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py

Adds a pools graphql field for ops and assets
BK

thread pool information to graphql layer

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql/schema/instance.py
python_modules/dagster-graphql/dagster_graphql/schema/solids.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_all_snapshot_ids.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_assets.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_solids.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_daemon/run_coordinator/queued_run_coordinator_daemon.py
python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py

For ease of use, https://github.com/dagster-io/dagster/pull/26931 consolidates concurrency settings (including queued run coordinator settings) into a single deployment settings block.
This PR makes it so that run queue settings are now accessed off of the instance, instead of off of the run coordinator.
The run coordinator is a standalone-configured module.  This makes it difficult to incorporate instance settings from other places.
BK

hoists the run queue config from the run coordinator up to the instance

---

docs/.cursorrules
docs/.windsurfrules
docs/docs-beta/docusaurus.config.ts
docs/docs-beta/src/plugins/scoutos/index.js

Adds embedded Ask AI chat as a Docusaurus plugin.
Local, waiting to see how previews look.
NOCHANGELOG

[DOC-730][docs-beta] creates ScoutOS Docusaurus plugin for embedded chat

---

python_modules/libraries/dagster-dlt/dagster_dlt/translator.py
python_modules/libraries/dagster-dlt/dagster_dlt_tests/test_asset_decorator.py

Use `DagsterDltTranslator._default_*` fns in `get_asset_spec`. To make sure custom translators are not breaking, we also use the resolve back compat fn.

[3/n][dagster-dlt] Resolve back compat in DagsterDltTranslator.get_asset_spec

---

python_modules/libraries/dagster-dlt/dagster_dlt/translator.py

As title.
[dagster-dlt] `DagsterDltTranslator.get_*` methods are superseded in favor of `DagsterDltTranslator.get_asset_spec`

[4/n][dagster-dlt] Mark DagsterDltTranslator.get_* methods as superseded

---

python_modules/dagster/dagster/_core/errors.py
python_modules/dagster/dagster/_core/execution/plan/utils.py
python_modules/dagster/dagster/_utils/error.py
python_modules/dagster/dagster_tests/core_tests/test_mask_user_code_errors.py

Follow-on to the functionality introduced in #18688. The original PR ensures that if the `DAGSTER_REDACT_USER_CODE_ERRORS` env var is set to `1`, instances of `DagsterUserCodeExecutionError` which are serialized are masked so that their potentially sensitive contents are not leaked. However, there is a class of errors that can still expose elements of user code: system/framework errors or interrupts, for example, will include their stack trace and snippets of user code.
This PR attempts to handle this second class of errors, in a few ways:
- Any error which is raised in a user code context has its stacktrace logged and then cleared, so if the error makes it to serialization, it will only include the error message.
- User code exceptions have their `original_exc_info` purged.
- A global …

More aggressively mask user code errors when masking enabled

---

helm/dagster/schema/schema_tests/test_dagster_daemon.py
helm/dagster/templates/configmap-instance.yaml
helm/dagster/values.yaml

Adds parameter to configure run monitoring with max_runtime_seconds in the helm chart.
Closes https://github.com/dagster-io/dagster/issues/26641
Added a test

[helm] - Make max runtime seconds configurable in the helm chart

---

docs/content/integrations/dlt.mdx
examples/docs_snippets/docs_snippets/integrations/dlt/dlt_dagster_translator.py

[5/n][dagster-dlt] Update dlt docs to use DagsterDltTranslator.get_asset_spec

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_all_snapshot_ids.ambr
python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_pipeline_snapshot.ambr
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster/_core/snap/execution_plan_snapshot.py
python_modules/dagster/dagster/_core/snap/node.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/__snapshots__/test_active_data.ambr
python_modules/dagster/dagster_tests/core_tests/snap_tests/__snapshots__/test_execution_plan.ambr
python_modules/dagster/dagster_tests/core_tests/snap_tests/__snapshots__/test_job_snap.ambr

Unsure if I also need to change `AssetNodeSnap` in [`external_data.py`](https://github.com/dagster-io/dagster/blob/1839f8722767ff47838de3c2da31b340fab2616c/python_modules/dagster/dagster/_core/remote_representation/external_data.py#L1387)
Triggered an internal build https://buildkite.com/dagster/internal/builds/92846

skip snapshot pools when empty

---

docs/docs-beta/sidebars.ts

Turns out these sidebar entries hide on prod even though we've explicitly included them - in local dev they're fine.
Refers to the components page by url rather than name in hopes that they won't get filtered out this way.

[docs-beta] Fix components sidebar

---

python_modules/dagster/dagster/_core/definitions/partition.py
python_modules/dagster/dagster/_core/execution/plan/execute_step.py
python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py

Fixes an issue where `ASSET_MATERIALIZATION` events emitted for each partition in a multi-partition run were getting the same partition key tags because each event was using the same tags dictionary. The impact of this is that when we fetch these events from the event log, the reconstructed event has the wrong partition key, because we source the key from the tags
unit tests
[bug fix] Fixed an issue where querying for Asset Materialization events from multi-partition runs would assign incorrect partition keys to the events

fix asset materialization events getting the wrong partition because of dictionary overloading

---

python_modules/dagster/dagster/_config/pythonic_config/resource.py
python_modules/dagster/dagster_tests/core_tests/resource_tests/pythonic_resources/test_nesting.py

The implementation of `_is_fully_configured` previously would mark partial/configure-at-runtime resources as fully populated if all values had defaults. This means the config values couldn't be overridden at runtime properly.
This PR ensures that partial/configure-at-runtime resources can always have fields overridden at runtime.
Previously failing unit test.

[pythonic resources] never treat partial resources as resolved

---

js_modules/dagster-ui/packages/ui-components/src/components/Radio.tsx
js_modules/dagster-ui/packages/ui-components/src/components/__stories__/Radio.stories.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/LaunchAssetChoosePartitionsDialog.tsx

Make the disabled state for radio buttons a little more visible.
Before:
After:
Storybook example.

[ui] Adjust the disabled state for Radio

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx

This is due to the full asset graph data not being available. Not really sure why the fetchResult.loading is false when the data is not available yet... but for now fixing it this way until I can investigate deeper.

[Asset graph] Fix query error notice

---

docs/docs-beta/docusaurus.config.ts
docs/docs-beta/package.json
docs/docs-beta/yarn.lock

Add redirects from old to new docs site using the [Docusaurus client-side redirects plugin](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects).
Here's the [spreadsheet ](https://docs.google.com/spreadsheets/d/1pMfYCIwF1zkpq3ELxKriy_SoBhYPjJdwL-ngLz_htHw/edit?gid=0#gid=0)of old and new paths for all docs.
This will need to be tested in production.

DOC-564 Add redirects from old to new docs paths

---

python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/instance/config.py
python_modules/dagster/dagster/_core/run_coordinator/queued_run_coordinator.py
python_modules/dagster/dagster_tests/core_tests/instance_tests/test_config/error_run_coordinator_concurrency_mismatch.yaml
python_modules/dagster/dagster_tests/core_tests/instance_tests/test_config/error_run_queue_concurrency_mismatch.yaml
python_modules/dagster/dagster_tests/core_tests/instance_tests/test_config/merged_run_coordinator_concurrency.yaml
python_modules/dagster/dagster_tests/core_tests/instance_tests/test_config/merged_run_queue_concurrency.yaml
python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance_config.py

This PR enables setting run concurrency settings from the run_queue configuration block into the `concurrency` deployment settings block.
This is to simplify concepts from a configuration standpoint.
The hypothesis is that most people will not need to even know about the run coordinator, and instead will only interact with this concurrency section.
BK
Moves run queue configuration from its standalone deployment setting into the `concurrency` deployment setting, along with new settings for pools.

add new concurrency config to consolidate concurrency settings

---

python_modules/libraries/dagster-looker/dagster_looker/lkml/asset_utils.py
python_modules/libraries/dagster-looker/dagster_looker/lkml/dagster_looker_lkml_translator.py
python_modules/libraries/dagster-looker/dagster_looker_tests/lkml/test_asset_specs.py

Move the asset spec creation from the asset decorator to a `get_asset_spec` method in the translator.
Also updates adds tests. No additional test was added for group names, owners and tags. It is not recommended to update these values by overriding `get_asset_spec` because they are not related to Looker specifically.
Updated and new tests with BK

[1/n][dagster-looker] Move asset spec creation to DagsterLookerLkmlTranslator.get_asset_spec

---

python_modules/dagster/dagster/_core/instance/config.py
python_modules/dagster/dagster/_core/op_concurrency_limits_counter.py
python_modules/dagster/dagster/_core/run_coordinator/queued_run_coordinator.py
python_modules/dagster/dagster/_core/storage/dagster_run.py
python_modules/dagster/dagster/_daemon/run_coordinator/queued_run_coordinator_daemon.py
python_modules/dagster/dagster_tests/core_tests/instance_tests/test_config/merged_run_coordinator_concurrency.yaml
python_modules/dagster/dagster_tests/core_tests/instance_tests/test_config/merged_run_queue_concurrency.yaml
python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance_config.py
python_modules/dagster/dagster_tests/daemon_tests/test_locations/concurrency_limited_workspace.py
python_modules/dagster/dagster_tests/daemon_tests/test_queued_run_coordinator_daemon.py

Enables setting run granularity enforcement of pools in the queued run coordinator, to limit the concurrency of in-progress runs containing a particular op / asset.
BK
- Enables run granularity concurrency enforcement of pool limits

add support for run-granularity op concurrency

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetEventList.tsx

The run status dot in the left pane of Asset events is misleading, since the materialization may have occurred even when the run is marked as failed -- a red dot makes it look as though the materialization also failed, even when it didn't.
Replace the dot with a `run` icon. For more details on the run itself, the user can click to view the materialization event.
View asset events, verify that the icon appears in the tag instead of the status dot.
[ui] Remove misleading run status dot from the asset events list.

[ui] Remove status dot from Asset events left pane

---

js_modules/dagster-ui/packages/ui-core/src/selection/SelectionAutoCompleteVisitor.ts
js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInput.tsx
js_modules/dagster-ui/packages/ui-core/src/selection/__tests__/SelectionAutoComplete.test.ts

We only want to surround values with double quotes if they contain special characters. 
Also add a space after each attribute value so that to auto-complete suggests `and`/`or`. Otherwise, since we removed the double quotes, it would keep suggesting other attribute values since without the quotes its not clear that the value is complete
jest tests

[1/3][Selection Input] Add double quotes only if necessary

---

js_modules/dagster-ui/packages/ui-core/src/asset-selection/input/AssetSelectionInput.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/selection/SelectionAutoCompleteVisitor.ts
js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInput.tsx
js_modules/dagster-ui/packages/ui-core/src/selection/__tests__/SelectionAutoComplete.test.ts

1. Add clear selection button. This will likely change once I have official designs but for now its engineer design.
2. Allow overriding the default linter in AssetSelection input. This is for alerts which will use a different linter without elastic search filters.
manually tested.

[2/3][Selection Input] Add clear selection button

---

js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillActionsMenu.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillPage.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillRow.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillTerminationDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/backfill/RunsFeedBackfillPage.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedRow.tsx

Previously the backfill cancellation button had two titles "Cancel backfill submission" and "Terminate unfinished runs". Over time it seems that most of the cases when "Terminate unfinished runs" was shown got phased out, and "Cancel backfill submission" is a misnomer because it doesn't stop the backfill from being added to the DB, it cancels the backfill and all runs it has launched. 
Additionally, in the remaining case when "Terminate unfinished runs" was shown, it used a different code path to just cancel the runs launched by the backfill and didn't cancel the backfill itself, potentially leading to a confusing state where a user has "canceled" the backfill but the backfill is still running and submitting new runs. 
This PR consolidates the button so that it just has one behavior: …

[ui] update backfill cancel button to only have one option

---

python_modules/libraries/dagster-looker/dagster_looker/lkml/dagster_looker_lkml_translator.py

As title.
[dagster-looker] `DagsterLookerLkmlTranslator.get_*` methods are superseded in favor of `DagsterLookerLkmlTranslator.get_asset_spec`

[4/n][dagster-looker] Mark DagsterLookerLkmlTranslator.get_* methods as superseded

---

docs/docs-beta/src/styles/custom.scss
docs/docs-beta/src/theme/NotFound/Content/index.tsx

Links were not formatted well, and I don't think they are necessary for now.
We can revisit a fun Daggy-themed 404 in the future.
**before**
**after**

[docs] remove 404 links

---

js_modules/dagster-ui/packages/ui-core/client.json
js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetBaseDataProvider.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-data/__tests__/AssetLiveDataProvider.test.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-data/__tests__/util.ts
js_modules/dagster-ui/packages/ui-core/src/asset-data/types/AssetBaseDataProvider.types.ts
js_modules/dagster-ui/packages/ui-core/src/asset-graph/Utils.tsx

freshnessInfo is expensive to fetch, and our graphene layer can't parallelize fetching it with other data it fetches... so fetch it separately.
host cloud, 
You can see the AssetFreshness queries at the top of the network tab here:

[perf] Fetch freshnessInfo separately from other asset data

---

js_modules/dagster-ui/packages/ui-core/src/runs/RunsFilterInput.tsx
js_modules/dagster-ui/packages/ui-core/src/ui/BaseFilters/__tests__/useSuggestionFilter.test.tsx
js_modules/dagster-ui/packages/ui-core/src/ui/BaseFilters/useSuggestionFilter.tsx

We don't show all possible schedules and sensors in the "Launched by" filter on Runs, as we limit which results come from the backend, and schedules/sensors that don't exist in the current workspace aren't available.
To provide a fallback option for searching for schedules/sensors that are otherwise not available, show freeform options.
To achieve this while maintaining the behavior of allowing only one launched-by value, I also added a couple of features to suggestion filters that didn't previously exist:
- An optional `allowMultipleSelections` property, like with the static set filter
- An optional `freeformResultPosition` to allow customizing whether to show results at the top or bottom of the list.
- In this case, I think we don't want to surface freeform options at the top, since the …

[ui] Allow freeform schedule/sensor name in launched-by Runs filter

---

python_modules/libraries/dagster-dg/dagster_dg/yaml_utils/__init__.py
python_modules/libraries/dagster-dg/dagster_dg/yaml_utils/source_position.py

Mirror the `dagster._utils` YAML parsing utils in `dagster-dg` so no dep is needed.
dupe test

Mirror YAML parsing utils in dagster-dg
