dagster-io/dagster

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/defining-resolvable-field.py
- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/base.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/metadata.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/resolver.py
- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/test/complex_schema_asset.py
- python_modules/libraries/dagster-components/dagster_components_tests/rendering_tests/test_schema_resolution.py
- python_modules/libraries/dagster-dg/dagster_dg/docs.py
This changes the logic for how we determine which fields to defer resolution for.
We want to eagerly resolve a field as long as it:
a) has no additional required scope
b) will not change its type if you resolve it
This allows us to eagerly resolve stuff like environment variables and simple string parameters (which makes resource construction simpler), while safely ignoring resolution for fancier structured objects, or objects that need to be resolved in a more complex scope
NOCHANGELOG
> [components] Update resolution deferral logic

- python_modules/libraries/dagster-dg/dagster_dg/docs.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils_tests/test_sample_yaml.py
This simplifies the docs commenting logic by re-using the source-position loader. In essence, we dump the yaml, then parse it again so we can map the values to source positions, then emit comments on lines where we need to.
This is a lot easier to build off of and less sketchy than the previous implementation.
NOCHANGELOG
> [components] Update docs commenting logic

- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/core/component_decl_builder.py
- python_modules/libraries/dagster-components/dagster_components/core/component_defs_builder.py
- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/definitions_component/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/pipes_subprocess_script_collection.py
- python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_dbt_project.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_sling_integration_test.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_templated_custom_keys_dbt_project.py
- python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_pipes_subprocess_script_collection.py
This makes way for a new PythonComponentDecl that I'd like to add upstack, but I also just think this is net a better implementation regardless.
In particular, the fact that we needed to call `loaded_params = context.load_params(cls.get_schema())` in every single `load()` method was a big red flag.
NOCHANGELOG
> [components] Explicitly pass params to Component.load

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-build-defs.py
- python_modules/libraries/dagster-components/dagster_components/cli/check.py
- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/core/component_decl_builder.py
- python_modules/libraries/dagster-components/dagster_components/core/component_defs_builder.py
- python_modules/libraries/dagster-components/dagster_components/lib/test/complex_schema_asset.py
- python_modules/libraries/dagster-components/dagster_components/lib/test/simple_asset.py
- python_modules/libraries/dagster-components/dagster_components/lib/test/simple_pipes_script_asset.py
- python_modules/libraries/dagster-components/dagster_components/utils.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_templated_custom_keys_dbt_project.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/validation_tests/basic_components.py
- python_modules/libraries/dagster-components/dagster_components_tests/rendering_tests/custom_scope_component/component.py
- python_modules/libraries/dagster-dg/dagster_dg/templates/COMPONENT_TYPE/COMPONENT_TYPE_NAME_PLACEHOLDER.py.jinja
This moves the load method onto the individual DeclNode classes, which simplifies the logic a bit and just generally is a bit better organized.
The impetus for this is cleaning up the house a bit in preparation for adding a PythonDeclNode
NOCHANGELOG
> [components] Refactor component load behavior

- python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
Received feedback from a user that it would be helpful to have an example of using `output_required` in the docs—specifically, to highlight that the conditional `Output` needs to be yielded.
> Add example of using `output_required` to API docs

- js_modules/dagster-ui/packages/ui-components/src/components/Text.tsx
Adds new text styles from https://github.com/dagster-io/dagster/pull/21450 which was reverted in https://github.com/dagster-io/dagster/pull/21517.
I'm adding the new styles, and updating a couple of the existing ones (Title and Heading are the main changes, they're bigger now). Assuming this is fine since we did this in the original PR.
briefly went around the app and everything looked fine. The only concrete changes are going to be title/headline are bigger now which seems like the intention in the original PR:
> Update text styles

- python_modules/libraries/dagster-dg/dagster_dg/docs.py
Fix mistaken import from `dagster` yaml utils instead of local `dagster_dg` yaml utils.
BK
> [components] fix import from dagster

- js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
- js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
- python_modules/dagster-graphql/dagster_graphql/schema/instance.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/graphql_context_test_suite.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_instance.py
- python_modules/dagster/dagster/_core/execution/plan/instance_concurrency_context.py
- python_modules/dagster/dagster/_core/op_concurrency_limits_counter.py
- python_modules/dagster/dagster/_core/storage/alembic/versions/048_7e2f3204cf8e_add_column_concurrency_default_limit.py
- python_modules/dagster/dagster/_core/storage/event_log/base.py
- python_modules/dagster/dagster/_core/storage/event_log/schema.py
- python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py
- python_modules/dagster/dagster/_core/storage/legacy_storage.py
- python_modules/dagster/dagster/_utils/concurrency.py
- python_modules/dagster/dagster_tests/core_tests/execution_tests/test_instance_concurrency_context.py
- python_modules/dagster/dagster_tests/general_tests/compat_tests/test_back_compat.py
- python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
Currently, the event log storage returns a `ConcurrencyKeyInfo` to represent the information about a particular pool.  This info includes the number of slots available, but it doesn't have enough information to distinguish between the following cases:
1. no pool limit is explicitly set and there is no default value
2. no pool limit is explicitly set but there is a default value
3. a pool limit is explicitly set to 0
This PR adds more information to the returned object to help distinguish between cases 1 and 2.  Specifically, there's a new nullable `limit` value, which returns the configured limit regardless of whether the pool has been initialized to create the corresponding slot rows.  A limit value of `None` indicates an unconfigured pool, with no default limit.
BK
> separate configured limit from slot count

- .github/workflows/build-docs.yml
- docs/docs-beta/docusaurus.config.ts
- docs/docs-beta/vercel.json
> [docs] handle multi-redirects for dagster plus; misc fixes

- python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_freshness.py
- python_modules/dagster-webserver/dagster_webserver_tests/webserver/conftest.py
- python_modules/dagster-webserver/dagster_webserver_tests/webserver/test_app.py
- python_modules/dagster/dagster/_core/workspace/context.py
instead of creating new ones of these for each asset node, share them for the scope of a request
this also switches over to using the workspace scoped asset graph which I am not cetain of
> [graphql] request context scoped caching resolvers

- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/core/component_decl_builder.py
- python_modules/libraries/dagster-components/dagster_components/lib/pipes_subprocess_script_collection.py
- python_modules/libraries/dagster-components/dagster_components_tests/code_locations/python_script_location/components/script_python_decl/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/code_locations/python_script_location/components/script_python_decl/cool_script.py
- python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_pipes_subprocess_script_collection.py
Adds an `@component_loader` decorator and the corresponding infrastructure to allow users to write arbitrary python code to load their Components.
Note that the convention I've gone with here has the user manually call `XComponent.load()`, rather than going through the `__init__`. My thought here was basically just that this feels like better practice as it provides a common shared format between the python and yaml interfaces.
In short, the way to use this is to have a `component.py` file instead of a `component.yaml` file, which will look something like:
```python
from dagster_components import ComponentLoadContext, component_loader
from ... import MyComponentClass
@component_loader
def load(context: ComponentLoadContext) -> MyComponentClass:
return MyComponentClass.load(
params=..., …
```
> [components][rfc] `@component_loader` decorator

- docs/docs-beta/docs/guides/build/components/index.md
Adds a brief note to the tutorial explaining how to use local `dg` in development instead of PyPI `dg`.
Installed this way myself.
> [components] Add note to Components README telling how to use local dg

- python_modules/dagster-graphql/dagster_graphql/schema/backfill.py
- python_modules/dagster/dagster/_cli/job.py
- python_modules/dagster/dagster/_core/execution/asset_backfill.py
- python_modules/dagster/dagster/_core/execution/backfill.py
- python_modules/dagster/dagster/_core/execution/job_backfill.py
- python_modules/dagster/dagster/_daemon/backfill.py
- python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py
We don't store the time a backfill ends on the `PartitionBackfill` object. Instead we query for all of the runs in the backfill and find the one with the most recent end time. This results in noticeably slow load times (~10seconds on our deployment) on the Backfills tab of the Runs page because we have to fetch every run for every backfill on the page. 
The PR stores the current time when a backfill is moved into a terminal state. Then we can access this value in the GQL resolver. If the end timestamp doesn't exist on the backfill object we fall back to calculating based on run end times. Maybe we could also write this value to the db after we've computed it?
> store end timestamp on PartitionBackfill

- js_modules/dagster-ui/packages/ui-core/src/assets/AssetPageHeader.oss.tsx
We received a report that long asset key path values are broken in the Asset page header breadcrumbs. We had fixed this before, but a recent change to fix some incorrect React node re-use looks like it also inadvertently affected measurement for truncation.
To fix this, remove wrapper spans and put the key on the `TruncatedHeading` elements themselves.
I'm not sure if this will reintroduce the flashing issue noted in https://github.com/dagster-io/dagster/pull/25188, but I don't see any flashing when I test this with very long keys.
View an asset with long keys, verify truncation.
[ui] Fix Asset page header display of long key values.
> [ui] Fix long asset key display in header

- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionAutoCompleteVisitor.ts
- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInput.tsx
- js_modules/dagster-ui/packages/ui-core/src/selection/__tests__/SelectionAutoComplete.test.ts
Undoes most of dagster-io/dagster#27262.
We decided we do want to always use double quotes. Reason is that it makes the flow of keyboard auto-complete simpler.
> [Selection Input] Always add double quotes again

- docs/docs-beta/src/styles/theme-globals.scss
Specify the font style and font weight range for Geist, in particular to avoid weird incorrect weights in Safari.
Before:
After:
Run docs-beta app, open in Safari. Verify that bold text looks correct.
> [docs] Fix font-face

- js_modules/dagster-ui/packages/ui-core/src/assets/AssetPartitions.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/AssetPartitions.test.tsx
We represent partition health using ranges, eg: “0->1000 are green, 1000 -> 1005 are red”, etc. We need to apply the search filtering /after/ we are finished filtering by health ranges, because the filtering changes the index of partitions in the partition space.
Fixes https://linear.app/dagster-labs/issue/FE-759/ui-bug-with-filter-and-partition-selection-on-asset-partitions-tab
We actually have tests for this page (!!) and I added another test that reproduced this bug without the patch + verifies the fix. 🙌 
I tested this manually against this page: http://localhost:3001/elementl/prod/assets/poll_snowflake_query_history_hour?view=partitions&status=FAILED%2CMATERIALIZING%2CMISSING. Unchecking "Materialized" and then filtering to "2025" returned no results.
[ui] Fixes an issue with the …
> [ui] Fix search filter on the asset partitions page when health filters are enabled

- docs/docs-beta/static/img/getting-started/icon-education.svg
> [docs] fix education icon color

- python_modules/libraries/dagster-components/dagster_components/cli/list.py
- python_modules/libraries/dagster-components/dagster_components/test/test_cases.py
- python_modules/libraries/dagster-components/dagster_components_tests/cli_tests/test_commands.py
- python_modules/libraries/dagster-dg/dagster_dg/cache.py
- python_modules/libraries/dagster-dg/dagster_dg/component.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/utils.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_check.py
Begins to cache local component type info in dg CLI cache, so that the schema can be re-used easily. These are cached separately
so that only the updated local component types are re-fetched when they do change.
New unit test to test caching behavior.
> [dg] Cache local component type schemas to speed up repeated dg check calls

- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_deployment_commands.py
Remove any dagster-cloud-specific files from the `dg` scaffolded deployment. These are underdeveloped and probably incomplete, we can add them back when we document, explain, and test them.
Modified existing unit tests
> [components] Remove dagster-cloud yaml files from deployment

- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/validation/basic_component_missing_type/component.yaml
- python_modules/libraries/dagster-dg/dagster_dg/cli/component.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_check.py
Raises a validation error, which is enriched visually, when a component type doesn't exist:
```bash
$ dg component check
/Users/ben/repos/components_demo/code_locations/jaffle_platform/jaffle_platform/components/ingest_files/component.yaml:1 -  Unable to locate local component type '.sling_replication_colldection' in /Users/ben/repos/components_demo/code_locations/jaffle_platform/jaffle_platform/components/ingest_files.
| 
1 | type: .sling_replication_colldection
| ^ Unable to locate local component type '.sling_replication_colldection' in /Users/ben/repos/components_demo/code_locations/jaffle_platform/jaffle_platform/components/ingest_files.
2 | 
3 | params:
4 |   replications:
5 |     - path: {}
6 |     - path: {}
| 
```
New unit test.
> [dg check] Gracefully error when component type isnt found

- python_modules/libraries/dagster-components/dagster_components/cli/list.py
- python_modules/libraries/dagster-components/dagster_components_tests/cli_tests/test_commands.py
Adds a `dagster-components` CLI command used to generate a schema for component files, which ORs all component types available in a given code location.
This schema can be used to type check all component files for a code location.
New unit test.
> [components] add cli command to generate schema for code location component types

- python_modules/libraries/dagster-dg/dagster_dg/cli/component.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/global_options.py
- python_modules/libraries/dagster-dg/dagster_dg/utils.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_custom_help_format.py
- python_modules/libraries/dagster-dg/setup.py
This updates `dagster-dg` to use the rich/colored help style borrowed from [typer](https://github.com/fastapi/typer) (which in turn borrowed it from an older package called `rich-cli`).
This began as an effort to convert the entire app over to `typer`, which would have granted us this kind of output by default. However, it turns out that typer isn't sufficiently flexible for our needs. Among the difficulties I ran into trying to port to typer:
- dynamic subcommand generation-- we do this for `dagster-dg`, and it is "last minute" generation that is dependent on callbacks for the groups in `dg component scaffold <component>` executing before the subcommands are generated. Couldn't figure out how to do this in `typer`.
- The `--use-editable-dagster` command can optionally take an argument …
> [components] Typer help output

- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInput.tsx
Resolve https://github.com/dagster-io/dagster/security/code-scanning/63.
Not sure of the right way to test this. I tried forcing the `value` prop with strings containing newlines, and the code correctly replaces the `\n`'s, but I'm not sure how this is supposed to appear in the UI.
> [ui] Replace all newlines in SelectionInput

- python_modules/libraries/dagster-sling/setup.py
Problem: currently, installing `sling` using `uv` in a fresh virtual environment on macOS with the cache disabled will incorrectly install `sling-linux-amd64` instead of the correct `sling-mac-arm64`. This causes the package to be unimportable.
```
mkdir test-sling && cd test-sling
uv venv
uv pip install --no-cache sling
uv run python -c 'import sling'
File "<string>", line 1, in <module>
File "/Users/smackesey/stm/code/elementl/tmp/testsling-editable-2/.venv/lib/python3.12/site-packages/sling/__init__.py", line 39, in <module>
exec('from sling_mac_arm64 import SLING_BIN')
File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sling_mac_arm64'
```
This bites us when installing `dagster-sling` (a dependency of …
> [dagster-sling] Add explicit sling-mac-arm64 dependency for uv compatibility

- docs/docs-beta/docs/dagster-plus/deployment/management/settings/customizing-agent-settings.md
Updates our docs to match the most current TTL configuration format, and explain default TTL values.
> [docs] Explain TTL defaults, scope TTL example to branch & full

- python_modules/dagster/dagster/_core/definitions/op_definition.py
- python_modules/dagster/dagster/_core/execution/plan/active.py
- python_modules/dagster/dagster/_core/op_concurrency_limits_counter.py
https://github.com/dagster-io/dagster/pull/27250 addressed the snapshot stability issue when concurrency keys are not specified on any ops.  
This PR changes it so that the new `pool` snapshot field is not available using the legacy tag-based API (specifying `dagster/concurrency_key` either.  Previously, we coalesced both the tag and the `pool` argument into the pool property at the definition level.  Now, we keep both separate and rely on the consumer (graphql / run coordinator / executor) to be aware of the appropriate changes.
BK
> defer merging legacy concurrency tag with pools until after snapshot

- docs/docs-beta/docs/dagster-plus/deployment/management/settings/customizing-agent-settings.md
- docs/docs-beta/docs/guides/build/assets/metadata-and-tags/kind-tags.md
- docs/docs-beta/docs/integrations/libraries/airlift/airflow-to-dagster/observe.md
- docs/docs-beta/docs/integrations/libraries/airlift/airflow-to-dagster/peer.md
Using `<img>` tags prevents the warning displayed by Docusaurus:
```
[WARNING] The image at "/Users/<>/src/dagster/docs/docs-beta/static/images/integrations/airlift/peer_materialize.svg" can't be read correctly. Please ensure it's a valid image.
unsupported file type: undefined (file: /Users/<>/src/dagster/docs/docs-beta/static/images/integrations/airlift/peer_materialize.svg)
```
`yarn start`
NOCHANGELOG
> [docs] fix warnings for svg images being parsed by Docusaurus

- python_modules/dagster/dagster/_core/storage/runs/migration.py
- python_modules/dagster/dagster_tests/general_tests/compat_tests/test_back_compat.py
- python_modules/libraries/dagster-mysql/dagster_mysql_tests/compat_tests/test_back_compat.py
- python_modules/libraries/dagster-postgres/dagster_postgres_tests/compat_tests/test_back_compat.py
Data migration for adding an end timestamp for backfills. 
backcompat unit tests. Also ran the migration on my local db, and 1. visually confirmed that the end timestamp was added for backfills; 2. loaded the ui page that accesses the end timestamp and confirmed it did not call the path that queries all runs for a backfil.
Optional data migration to improve performance of the Runs page. Run `dagster instance migrate` to run the date migration. The migration will update serialized backfill objects in the database with an end timestamp attribute computed by querying the runs launched by that backfill to determine the when the last run completed.
> data migration for backfill end timestamp

- docs/docs-beta/docs/integrations/libraries/pagerduty.md
- docs/sphinx/sections/api/apidocs/libraries/dagster-pagerduty.rst
Package name should use dashes (`dagster_pagerduty` -> `dagster-pagerduty`)
NOCHANGELOG
> [docs] use dash in dagster-pagerduty package name

- python_modules/dagster/dagster/_config/pythonic_config/config.py
- python_modules/dagster/dagster/_config/pythonic_config/conversion_utils.py
- python_modules/dagster/dagster_tests/core_tests/pythonic_config_tests/test_default_values.py
Ensures that default values on Pythonic Config get properly propagated to inner Config classes, e.g.
```python
class ANestedOpConfig(Config):
an_int: int = 1
a_bool: bool = True
class AnOpConfig(Config):
a_string: str = "foo"
a_nested: ANestedOpConfig = ANestedOpConfig(an_int=5)
```
An alternative impl which uses some utils in a stacked PR can be found at #27209.
New unit test; todo add a few more
> [pythonic config] properly propagate default values set at the top level for nested config classes

- docs/sphinx/_ext/sphinx-mdx-builder/sphinxcontrib/mdxbuilder/writers/mdx.py
Literal blocks in the rendered MDX were escaping brackets. 
> [sphinx] Fix incorrect escaping in sphinx mdx writer for literal blocks

- docs/docs-beta/docs/guides/build/external-pipelines/using-dagster-pipes/reference.md
Fix typo, and capitalize after "**Note**:" for consistency with other docs.
BK
> Remove extraneous grave before `PipesContext` link

- docs/docs-beta/docs/guides/automate/declarative-automation/index.md
The steps for setting up the default_automation_condition_sensor has the wrong steps. It lives in the automations tab now, not overview > Sensors  
> Fixing DA docs sensor steps

- python_modules/libraries/dagster-dg/dagster_dg/cli/component_type.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_type_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_custom_help_format.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
- python_modules/libraries/dagster-dg/setup.py
Linear: https://linear.app/dagster-labs/issue/BUILD-637/generate-a-table-output-for-dg-component-type-list
Changes the output of `dg component-type list` to be a table. Uses the `rich` library (which is already a dependency of `typer`). Probably we will eventually completely remove the `typer` dependency and just use `rich` directly to style all output.
Adjusted existing tests.
> [components] Make dg component-type list output a table with colors (BUILD-637)

- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/definitions_component/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/registry_tests/test_registry.py
Introduced docstring summaries for published component types. This change ensures all components have proper documentation and enables better component type inspection.
- Added a new test `test_all_dagster_components_have_defined_summary` to verify all components have defined summaries
> [components] Add a summary to all published components (BUILD-634)

- scripts/install_dev_python_modules.py
Make sure `dagster-components` gets installed when rebuild dev env.
> [components] Add dagster-components to install_dev_python_modules script

- python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
Add some tests that ensure we handle queries like the 'fetch all events of a certain type' case correctly.
BK
NOCHANGELOG
> Add tests that exercise get_records_for_run with event type filters

- scripts/install_dev_python_modules.py
`dagster-ge`'s setup.py specifies a 3.10 version bound - respect it in the install script.
> Update dev python modules script to only install dagster-ge on python>=3.10

- python_modules/dagster-graphql/dagster_graphql/schema/instance.py
- python_modules/dagster/dagster/_core/instance/__init__.py
- python_modules/dagster/dagster/_core/instance/config.py
- python_modules/dagster/dagster/_core/op_concurrency_limits_counter.py
- python_modules/dagster/dagster/_core/run_coordinator/queued_run_coordinator.py
- python_modules/dagster/dagster/_daemon/run_coordinator/queued_run_coordinator_daemon.py
- python_modules/dagster/dagster_tests/core_tests/instance_tests/test_config/legacy_run_queue_default_run_blocking.yaml
- python_modules/dagster/dagster_tests/core_tests/instance_tests/test_config/legacy_run_queue_disabled_run_blocking.yaml
- python_modules/dagster/dagster_tests/core_tests/instance_tests/test_config/legacy_run_queue_enabled_run_blocking.yaml
- python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py
- python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance_config.py
Creates a new concurrency config typed object, to carry config from settings into the queued run coordinator, and into the graphql layer.
Separates it out from the existing `RunQueueConfig` since it can now carry settings that control concurrency at the op level, not just the run level.
BK
> extract instance concurrency config

- js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
- js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
- python_modules/dagster-graphql/dagster_graphql/schema/instance.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_instance.py
- python_modules/dagster/dagster/_core/instance/__init__.py
- python_modules/dagster/dagster/_core/instance/config.py
- python_modules/dagster/dagster/_core/op_concurrency_limits_counter.py
- python_modules/dagster/dagster/_core/run_coordinator/queued_run_coordinator.py
- python_modules/dagster/dagster/_core/storage/event_log/base.py
- python_modules/dagster/dagster/_daemon/run_coordinator/queued_run_coordinator_daemon.py
- python_modules/dagster/dagster_tests/core_tests/instance_tests/test_config/legacy_run_queue_default_run_blocking.yaml
- python_modules/dagster/dagster_tests/core_tests/instance_tests/test_config/legacy_run_queue_disabled_run_blocking.yaml
- python_modules/dagster/dagster_tests/core_tests/instance_tests/test_config/legacy_run_queue_enabled_run_blocking.yaml
- python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py
- python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance_config.py
- python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
We want to load some concurrency settings from user code during execution, so that we can respect deployment settings for op-level concurrency during run execution.
To do that, we need to load some deployment settings from the host cloud (via the event log storage), as opposed to the local agent instance.
This PR creates a base event log storage method to fetch the pool configuration, so that this can be overridden in Cloud.
BK
> add base pool config storage method

- python_modules/libraries/dagster-dg/dagster_dg/cli/code_location.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/component.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/component_type.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/utils.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/component_command_tests/test_check.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/component_command_tests/test_component_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_type_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Currently some `dagster-dg` commands fail with an ugly error message if `dagster-components` is not found on the path. This can happen if you are not using a dg-managed environment.
This PR runs a check for `dagster-components` on the path (when it is needed) and also does some refactoring of our validation code more generally.
Prior error message was an uncaught subprocess error (`dagster-components` not found) with a backtrace.
New error message:
```
Could not find the `dagster-components` executable on the system path.
The `dagster-components` executable is installed with the `dagster-components` PyPI package and is necessary for `dg` to interface with Python environments containing Dagster definitions. `dagster-components` is installed by default when a code location is scaffolded by …
```
> [components] Provide good error message if dagster-components is not available (BUILD-633)

- python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg/completion.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_install_completion.py
This adds a CLI endpoint, `dg --install-completion`, to automatically install shell completion.
`click` provides functionality to generate completion scripts, but doesn't provide auto-installation functionality. `typer`, however, does provide auto-installation. But by default, it will only install it's own `typer`-compatible completion scripts, which aren't compatible with our plain-click application.
Nonetheless, there is nothing about `typer`'s shell auto-installation logic that is specific to the content of its completion scripts. Therefore, if we supply it with our own completion script (generated by click), it gets the job done. There isn't a public API to do this, so it required a little hackery, but it works well.
Testing is quite challenging for this, since we are talking about …
> [components] Add completion with auto-installation to dagster-dg (BUILD-563)

- python_modules/libraries/dagster-dg/setup.py
Hard-pin `typer` in `dagster-dg`. We do this because we use some internal APIs which might suddenly be changed. We can get away with this because `dg` is designed to be used from an isolated environment, so we are not going to hit dependency conflicts.
> [components] hard-pin typer==0.15.1

- docs/docs-beta/docs/guides/build/components/setting-up-a-deployment.md
Tweak the ending of the "Setting up a Deployment" tutorial:
- add `executable_path` settings to the `workspace.yaml`, ensuring code locations load in their correct environments
- run `dagster dev` with `uv tool run`
Stepped through the outlined tutorial
> [components] tweaks to deployment doc for better final dagster dev

- examples/experimental/dagster-dlift/kitchen-sink/tox.ini
- examples/experimental/dagster-dlift/tox.ini
- integration_tests/test_suites/dagster-azure-live-tests/tox.ini
- integration_tests/test_suites/dagster-gcp-live-tests/tox.ini
- python_modules/libraries/dagster-airlift/kitchen-sink/tox.ini
- python_modules/libraries/dagster-airlift/tox.ini
- python_modules/libraries/dagster-census/tox.ini
- python_modules/libraries/dagster-tableau/tox.ini
We use `make` in a bunch of toxfiles without allowlisting it. This didn't seem to be an issue until #27456 updated the buildkite runner images, potentially unintentionally bumping some other dep. Explicitly allowlists `make` to fix several tests that were broken on master: https://buildkite.com/dagster/dagster-dagster/builds/109948
> [fix][bk] allow make in toxfiles

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/custom-subclass/basic-subclass.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/custom-subclass/custom-scope.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/custom-subclass/debug-mode.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/defining-resolvable-field.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/empty.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-build-defs.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-config-schema.py
- python_modules/libraries/dagster-components/dagster_components/__init__.py
- python_modules/libraries/dagster-components/dagster_components/core/component_decl_builder.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/base.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/metadata.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/resolver.py
- python_modules/libraries/dagster-components/dagster_components/lib/__init__.py
- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/pipes_subprocess_script_collection.py
- python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/test/complex_schema_asset.py
- python_modules/libraries/dagster-components/dagster_components/test/basic_components.py
- python_modules/libraries/dagster-components/dagster_components/utils.py
- python_modules/libraries/dagster-components/dagster_components_tests/code_locations/custom_sling_location/custom_sling_location/components/debug_sling_component/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/code_locations/python_script_location/components/script_python_decl/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions/local_component_sample/__init__.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions/other_local_component_sample/__init__.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_sling_integration_test.py
- python_modules/libraries/dagster-components/dagster_components_tests/rendering_tests/custom_scope_component/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/rendering_tests/custom_scope_component/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/rendering_tests/test_schema_resolution.py
- python_modules/libraries/dagster-dg/dagster_dg/templates/COMPONENT_TYPE/COMPONENT_TYPE_NAME_PLACEHOLDER.py.jinja
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils_tests/test_sample_yaml.py
This is a larger rework of how the yaml resolution logic works in service of creating a clear separation between the `__init__` args and the params schema.
Each params schema is now a `ResolvableModel`, which defines an explicit function to turn the blob of configuration into an explicit object type.
This also removes the "first pass" of the resolution logic, which was way too confusing.
> [components] Rework resolvable model

- python_modules/dagster/dagster/_core/scheduler/instigation.py
- python_modules/dagster/dagster/_daemon/asset_daemon.py
- python_modules/dagster/dagster/_daemon/sensor.py
Small change to make the zipped list of requested run ids and their associated run requests a property on the tick, rather than something we compute each time we need it, and potentially have the implementations drift
> make reserved run ids and run requests tuples a tick property

- python_modules/dagster/dagster/_core/scheduler/instigation.py
- python_modules/dagster/dagster/_daemon/asset_daemon.py
- python_modules/dagster/dagster/_daemon/sensor.py
- python_modules/dagster/dagster_tests/daemon_sensor_tests/conftest.py
- python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
Version of https://github.com/dagster-io/dagster/pull/26958 for vanilla sensors.
While submitting runs, polls the status of the sensor after every N runs are submitted. If the sensor gets turned off, we stop submitting runs and mark the tick as SKIPPED so that we don't try to resubmit the remaining runs in the future.
The motivation for this is to allow users to stop sensors if they are submitting a large number of unexpected runs (usually due to a configuration error or some other error in the sensor logic). They'll want to 1. prevent the remaining runs from getting submitted, and 2. fix the sensor before starting it back up. When they do start it back up, we want to make sure we don't continue submitting the runs from the old/bad tick, which is why we mark the tick as skipped. …
> sensors stopped while submitting runs stop submitting runs

- python_modules/dagster/dagster/_grpc/server.py
- python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_ping.py
- python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_watch_server.py
- python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py
The previous logic made it very easy to accidentally miss a parameter. Instead, construct as dict of kwargs and pass them through.
Existing dagster dev commands, launch dagster dev with force_port set to true or false
Fixed an issue where the "Reload definitions" button didn't work when using `dagster dev` on Windows, starting in the 1.9.10 release.
> Consolidate codepath for passing params into open_server_process

- docs/docs-beta/docs/dagster-plus/deployment/deployment-types/hybrid/amazon-ecs/configuration-reference.md
Summary:
Explain the config to set to enable shelling into tasks launched by the ECS agent.
> Document `enable_ecs_exec` in the EcsUserCodeLauncher

- python_modules/dagster/dagster/_generate/templates/PROJECT_NAME_PLACEHOLDER/pyproject.toml.jinja
- python_modules/dagster/dagster_tests/cli_tests/test_project_commands.py
- python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/templates/CODE_LOCATION_NAME_PLACEHOLDER/pyproject.toml.jinja
- python_modules/libraries/dagster-dg/dagster_dg/utils.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_code_location_commands.py
The `tool.dagster` section in our scaffolded `pyproject.toml` contained a `project_name` field. However, this isn't actually read by our tooling. What _is_ read is a `code_location_name` field. This renames the `project_name` field to `code_location_name`. It affects both `dagster` and `dagster-dg` (which had started by copying the `pyproject.toml` scaffolding from dagster core).
Tweaked unit tests.
> [components] project_name -> code_location_name in scaffolded pyproject.toml

- python_modules/automation/automation/utils.py
- python_modules/automation/automation_tests/test_repo.py
- python_modules/libraries/dagster-census/MANIFEST.in
- Add `py.typed` to all Python packages (anything with a setup.py that can be installed into an environment)
- Add a test ensuring all packages have `py.typed`, and all published packages include it in their `MANIFEST.in`
There are a few reasons for this:
- In published packages, type annotations from a package will not always be used by a static analyzer if `py.typed` is not present. In particular, pyright/pylance will not use annotations from a non-`py.typed` package unless `useLibraryCodeForTypes` is enabled (and we don't control whether our users enable this). Not all of our packages are 100% typed, but they at least do not provide _wrong_ type information (which some packages, especially those using fancy metaprogramming, do), which means it is safe to expose the type information …
> Ensure py.typed is present in all packages (BUILD-660)

- python_modules/libraries/dagster-components/dagster_components/cli/__init__.py
Adds info to the help output of `dagster-components` (via the docstring) clarifying that it is a private API/implementation detail of `dg`.
> [components] Add help message to `dagster-components` CLI clarifying it is private (BUILD-535)

- js_modules/dagster-ui/packages/ui-core/src/asset-selection/input/util.ts
- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionAutoCompleteVisitor.ts
- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInput.tsx
- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInputAutoCompleteResults.tsx
- js_modules/dagster-ui/packages/ui-core/src/selection/__tests__/SelectionAutoComplete.test.ts
Kind tags already show up under the `kind:` filter, so removing them from showing up under the `tag:` filter.
locally, didn't add a jest test for the getAttributes function because I'm in the middle of refactoring all of this logic to be more flexible/robust.
The SelectionAutoComplete  jest test covers the second part of this PR
> [Selection input] Filter out kind tags from tags + Remove contains match filter as first option in empty case

- python_modules/dagster-graphql/dagster_graphql/cli.py
- python_modules/dagster-webserver/dagster_webserver/cli.py
- python_modules/dagster/dagster/_cli/api.py
- python_modules/dagster/dagster/_cli/asset.py
- python_modules/dagster/dagster/_cli/code_server.py
- python_modules/dagster/dagster/_cli/definitions.py
- python_modules/dagster/dagster/_cli/dev.py
- python_modules/dagster/dagster/_cli/job.py
- python_modules/dagster/dagster/_cli/run.py
- python_modules/dagster/dagster/_cli/schedule.py
- python_modules/dagster/dagster/_cli/sensor.py
- python_modules/dagster/dagster/_cli/workspace/__init__.py
- python_modules/dagster/dagster/_cli/workspace/cli_target.py
- python_modules/dagster/dagster/_daemon/cli/__init__.py
- python_modules/dagster/dagster_tests/cli_tests/workspace_tests/test_job_load.py
- python_modules/dagster/dagster_tests/cli_tests/workspace_tests/test_repository_load.py
- python_modules/libraries/dagster-sigma/dagster_sigma/cli.py
This is the base of a stack that aims to generally improve up the `dagster` CLI. The goals of the stack are to:
- Establish strong typing by immediately validating untyped bags of "kwargs" and converting to typed value objects at all entry points (currently we pass these bags of "kwargs" fairly deep into our code)
- Ensure consistency across CLI entry points. There are many shared options, we want to make sure validation is being done the same way, etc.
- Reduce code volume and improve clarity. The current code is quite convoluted and often inconsistent in its terminology, both internally and with abstractions deeper in the codebase.
This first PR:
- Updates the name of shared click option groups to use "options" instead of "argument", e.g. `python_origin_target_argument` -> …
> [cli-refactor] Standardize format and naming of click option decorators

- examples/experimental/dagster-blueprints/dagster_blueprints/cli.py
- python_modules/dagster-webserver/dagster_webserver/cli.py
- python_modules/dagster/dagster/_cli/definitions.py
- python_modules/dagster/dagster/_cli/dev.py
- python_modules/dagster/dagster/_cli/job.py
- python_modules/dagster/dagster/_cli/utils.py
- python_modules/dagster/dagster/_cli/workspace/cli_target.py
- python_modules/dagster/dagster/_daemon/cli/__init__.py
Some widely used CLI utilities were defined in random modules instead of the dedicated `dagster._cli.utils` module. Move to utils.
> [cli-refactor] Centralize utilities in dagster._cli.utils

- js_modules/dagster-ui/packages/ui-core/src/workspace/CodeLocationSource.tsx
- js_modules/dagster-ui/packages/ui-core/src/workspace/__tests__/CodeLocationSource.test.tsx
Try to resolve:
- https://github.com/dagster-io/dagster/security/code-scanning/18
- https://github.com/dagster-io/dagster/security/code-scanning/19
Within `CodeLocationSource`, we currently check whether `github.com` or `gitlab.com` are included in the hostname at all. This only affects how we render the outbound link or button, but even so, we should be more restrictive about this.
`yarn jest CodeLocationSource`
> [ui] Restrict CodeLocationSource hostnames

- python_modules/libraries/dagster-dbt/dagster_dbt/core/resource.py
- python_modules/libraries/dagster-dbt/dagster_dbt/dbt_project.py
- python_modules/libraries/dagster-dbt/dagster_dbt/errors.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resource.py
Same as #21108 but for `profiles_dir` and `profile`.
In response to PR #26928, fixes issue #26504
[dagster-dbt] Specifying a dbt profiles directory and profile is now supported in `DbtProject`.
> [dagster-dbt] Support profiles_dir and profile in DbtProject

- js_modules/dagster-ui/packages/ui-core/src/ui/MarkdownWithPlugins.tsx
Modify the syntax highlighting in markdown rendering to be a little closer to the launchpad styles.
View an asset with raw SQL values rendered via markdown, verify colors.
> [ui] Tweak markdown syntax highlighting colors

- python_modules/dagster/dagster/_core/code_pointer.py
- python_modules/dagster/dagster/_core/workspace/autodiscovery.py
- python_modules/dagster/dagster/_utils/__init__.py
- python_modules/dagster/dagster_tests/cli_tests/command_tests/asset_with_process_pool_executor.py
- python_modules/dagster/dagster_tests/cli_tests/command_tests/test_materialize_command.py
- python_modules/dagster/dagster_tests/cli_tests/workspace_tests/autodiscovery_tests/test_autodiscovery.py
The goal of cleaning after ourselves here is understandable, but prevents user code that depends on being able to re-import the same module implicitly (like ProcessPoolExecutor) from working correctly.
Fixed an issue where assets using ProcessPoolExecutor or multiprocessing with a spawn context sometimes failed to work with a ModuleNotFoundError.
> Keep the passed in working directory in sys.path after the initial import of user code

- docs/docs-beta/src/styles/custom.scss
- docs/sphinx/_ext/dagster-sphinx/dagster_sphinx/docstring_flags.py
- python_modules/dagster/dagster/_core/definitions/step_launcher.py
Adds just a little bit of breathing room on the API docs.
| Before | After |
|---|---|
| ![image](https://github.com/user-attachments/assets/f11eabb3-7f7a-4805-96a6-95baa6f60d4a) | ![image](https://github.com/user-attachments/assets/ff2c9fdf-bad3-4b1d-b0c0-eca9f028dc95) |
NOCHANGELOG
> [docs] add some margin and padding to api docs

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/custom-subclass/basic-subclass.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/custom-subclass/custom-scope.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/custom-subclass/debug-mode.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/empty.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/resolving-resolvable-field.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-build-defs.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-config-schema.py
- python_modules/libraries/dagster-components/dagster_components/__init__.py
- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/definitions_component/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/pipes_subprocess_script_collection.py
- python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/test/all_metadata_empty_asset.py
- python_modules/libraries/dagster-components/dagster_components/lib/test/complex_schema_asset.py
- python_modules/libraries/dagster-components/dagster_components/lib/test/simple_asset.py
- python_modules/libraries/dagster-components/dagster_components/lib/test/simple_pipes_script_asset.py
- python_modules/libraries/dagster-components/dagster_components/test/basic_components.py
- python_modules/libraries/dagster-components/dagster_components_tests/code_locations/custom_sling_location/custom_sling_location/components/debug_sling_component/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions/local_component_sample/__init__.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions/other_local_component_sample/__init__.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_sling_integration_test.py
- python_modules/libraries/dagster-components/dagster_components_tests/registry_tests/test_registry.py
- python_modules/libraries/dagster-components/dagster_components_tests/rendering_tests/custom_scope_component/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_registered_component.py
- python_modules/libraries/dagster-dg/dagster_dg/templates/COMPONENT_TYPE/COMPONENT_TYPE_NAME_PLACEHOLDER.py.jinja
Internal companion PR: https://github.com/dagster-io/internal/pull/13565
Rename `@component_type` -> `@registered_component_type`
> [components] component_type -> registered_component_type (BUILD-655)

- docs/docs-beta/docs/guides/build/components/index.md
- docs/docs-beta/docs/guides/build/components/setting-up-a-deployment.md
- docs/docs-beta/src/components/CliInvocationExample.tsx
- docs/docs-beta/src/styles/custom.scss
Right now, the CLI invocation example component takes a snippet as input, but sometimes it's nice to be able to inline a command directly in the docs file. This PR adds that as an optional param to the component.
It also removes the dashed bottom divider & re-enables rounding the box, in cases where the command has no output.
> [docs] Tweak CliInvocationExample to take contents directly, gracefully handle no-result case

- .github/workflows/build-docs-revamp.yml
- docs/docs-beta/docs/guides/build/components/index.md
The docs beta deploy GitHub Action constructs links to changed pages based on the filepath, stripping `.mdx`. This doesn't work for index pages, which do not include `index` in the URL.
Strips out a trailing `index` before the `.md(x)` suffix on a file, when turning it into a URL for the GitHub Action comment.
See below.
> [docs-beta][tool] Fix links to /index pages from docs beta deploy GH Action

- python_modules/libraries/dagster-dbt/dagster_dbt/core/resource.py
The lack of default here causes issues with the automatic component schema generation.
> [dagster-dbt] Set None as default for state_path

- python_modules/dagster-graphql/dagster_graphql/cli.py
- python_modules/dagster-webserver/dagster_webserver/cli.py
- python_modules/dagster/dagster/_cli/api.py
- python_modules/dagster/dagster/_cli/asset.py
- python_modules/dagster/dagster/_cli/code_server.py
- python_modules/dagster/dagster/_cli/definitions.py
- python_modules/dagster/dagster/_cli/dev.py
- python_modules/dagster/dagster/_cli/job.py
- python_modules/dagster/dagster/_cli/run.py
- python_modules/dagster/dagster/_cli/schedule.py
- python_modules/dagster/dagster/_cli/sensor.py
- python_modules/dagster/dagster/_cli/workspace/__init__.py
- python_modules/dagster/dagster/_cli/workspace/cli_target.py
- python_modules/dagster/dagster/_daemon/cli/__init__.py
- python_modules/dagster/dagster_tests/cli_tests/workspace_tests/test_job_load.py
- python_modules/dagster/dagster_tests/cli_tests/workspace_tests/test_repository_load.py
- python_modules/libraries/dagster-sigma/dagster_sigma/cli.py
- Eliminate the term "target" from shared option groups (e.g. `@repository_target_options` -> `@repository_options`). This was confusing since it didn't correspond to actual `*Target*` classes in the code.
- `@python_origin_target_options` -> `@python_pointer_options`. "pointer" was chosen because the Python pointer options mostly correspond (and are ultimately parsed to) `CodePointer` objects.
- `@python_job_config_option` -> `@run_config_option`. Another misleading name, as this was used outside the context of job config.
- Replace some (randomly?) varying subsets of workspace-specifying options with the standard, full set of workspace-specifying options
- e.g. `dagster definitions validate` accepted `--workspace`, `--python-file`, and `--module-name` but none of the other …
> [cli-refactor] Standardize shared option groups (part 2)

- python_modules/dagster/dagster/_cli/api.py
- python_modules/dagster/dagster/_cli/asset.py
- python_modules/dagster/dagster/_cli/code_server.py
- python_modules/dagster/dagster/_cli/job.py
- python_modules/dagster/dagster/_cli/utils.py
- python_modules/dagster/dagster/_cli/workspace/cli_target.py
- python_modules/dagster/dagster_tests/cli_tests/command_tests/test_asset_list_command.py
- python_modules/dagster/dagster_tests/cli_tests/command_tests/test_cli_commands.py
- python_modules/dagster/dagster_tests/cli_tests/command_tests/test_execute_command.py
- python_modules/dagster/dagster_tests/cli_tests/command_tests/test_materialize_command.py
- python_modules/dagster/dagster_tests/cli_tests/command_tests/test_scaffold_command.py
- python_modules/libraries/dagster-sigma/dagster_sigma/cli.py
First PR in the stack that replaces passing around "kwargs" with entry point validation and typing.
- Add a `PythonPointerOpts` value object corresponding to the `@python_pointer_opts` decorator.
- Wherever `@python_pointer_opts` is used:
- Immediately parse the untyped bag of cli_opts into a `PythonPointerOpts` object.
- Generally clean up the signatures of the targeted click commands, ensuring all other opts are passed as arguments instead of inside the generic bag of CLI opts.
> [cli-refactor] Type and validate python_pointer_opts at entry point

- Makefile
- python_modules/libraries/dagster-components/dagster_components/test/test_cases.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/validation/invalid_yaml_invalid_char/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/validation/invalid_yaml_missing_quote/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/validation_tests/test_component_validation.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/check_utils.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/component.py
Slurp up `yaml.scanner.ScannerErrors` and pass them into our nice error message formatter, that way `dg check` calls don't early-exit if we hit a parsing error.
> [dg] Nicely format YAML parsing errors in dg check CLI

- python_modules/dagster/dagster/_serdes/ipc.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/dev.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_dev_command.py
- python_modules/libraries/dagster-dg/setup.py
- python_modules/libraries/dagster-dg/tox.ini
Add the `dg dev` command.
- Unlike `dagster dev`, you cannot pass a target (like `--python-file ...`) to `dg dev`. Instead, `dg dev` works by inferring the target from the context:
- In a code location context, `dg dev` will run `uv run dagster dev ...` against the code location environment.
- In a deployment context, `dg dev` will construct a temporary workspace file that points at all defined code locations and `uv tool run --with dagster-webserver dagster dev`
- `dg dev` accepts almost all the arguments of `dagster dev` that make sense, and forwards them.
There is a discussion here about how to support venvs in the deployment root-- this PR takes the position that regardless of what we decide to do there, we should just use `uv tool run` if no venv is present.
New unit tests. I …
> [components] Add `dg dev` command (BUILD-578)

- docs/docs-beta/vercel.json
Resolves DOC-753.
There are two options suggested for this sub-domain redirect. Through the `vercel.json` or through a configuration on the DNS provider. Since I don't have access to the latter, I will move forward with doing it at the web server level for now.
https://github.com/vercel/vercel/discussions/5622#discussioncomment-4094899
NOCHANGELOG
> [docs] add redirect from docs-preview to docs

- .buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
- .buildkite/dagster-buildkite/dagster_buildkite/utils.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/1-help.txt
- python_modules/libraries/dagster-dg/dagster_dg/cli/check_utils.py
#27481 introduced a (very minor) change to `dg --help` that adjusted the snapshot, but this test never ran on the branch. Updates our BK logic to always run the docs snippets tests when the dg or dagster-components packages are updated.
> [bk] run components/dg CLI tests when either package is updated

- js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx
**Problem:** The full asset graph data (used only for sidebar/context menu lineage dialogs) was causing delays in rendering asset job lineage graphs while waiting for complete data loading.
**Solution:** Pass partial asset graph data to lineage components during initial load while full data loads in the background. This optimizes rendering performance and resolves query errors encountered during initial loading.
- Verified query error issue goes away using local testing with app proxy
- Confirmed lineage dialogs remain functional with partial data
-
> Allow rendering asset graph without full asset graph data

- docs/docs-beta/docs/integrations/libraries/duckdb/using-duckdb-with-dagster.md
> docs: fix typo

- python_modules/dagster/dagster/_config/config_type.py
- python_modules/dagster/dagster/_config/errors.py
- python_modules/dagster/dagster/_config/evaluate_value_result.py
- python_modules/dagster/dagster/_config/post_process.py
- python_modules/dagster/dagster/_config/stack.py
- python_modules/dagster/dagster/_config/traversal_context.py
- python_modules/dagster/dagster/_config/type_printer.py
- python_modules/dagster/dagster/_config/validate.py
- python_modules/dagster/dagster/_core/remote_representation/external_data.py
- python_modules/dagster/dagster_tests/core_tests/config_types_tests/test_type_printer.py
Cut repeat config processing time roughly in half by
* updating some namedtuples to `@record` 
* refining some memoization
* making various small tweaks informed by profiler output
bk
> [config] clean-up and perf pass

- docs/Makefile
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/deployments/5-tree.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/10-tree-jaffle-platform.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/3-tree.txt
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs.py
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs_deployments.py
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/utils.py
Comparing `tree` output cross platform sucks. Adds custom comparison logic to ignore the ordering.
This also means that `make test_cli_snippets_simulate_bk` works locally, good for local debugging. This cmd now opens pdb too if it fails.
> [dg docs] Improve frustrating tree comparison in CLI output

- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs.py
#27501 introduced a change where we must pass the working directory to `dagster assets materialize` - adds that to our dg docs tests
> fix components docs test

- docs/docs-beta/docs/guides/build/components/setting-up-a-deployment.md
- docs/docs-beta/sidebars.ts
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/deployments/12-workspace.yaml
Update the components deployment tutorial to use `dg dev` instead of manually creating `workspace.yaml`.
Stepped through the tutorial manually plus the existing tests
> [components] Update deployment doc with dg dev

- python_modules/libraries/dagster-ge/setup.py
we were previosuly resolving to sub 1.0.0 in tests so we didn't catch this but our integration is built around `DataContext` which was removed in `1.0.0` so set the pin correctly
bk
> update great_expectations pin

- docs/docs-beta/docs/guides/build/external-pipelines/gcp-dataproc-pipeline.md
- examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/gcp/dataproc_job/Dockerfile
- examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/gcp/dataproc_job/dagster_code.py
- examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/gcp/dataproc_job/dev.Dockerfile
- examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/gcp/dataproc_job/init.sh
- examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/gcp/dataproc_job/script.py
- examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/gcp/dataproc_job/upload_artifacts.py
- python_modules/libraries/dagster-gcp/dagster_gcp/pipes/clients/dataproc_job.py
This PR adds a tutorial for `PipesDataprocJobClient`. 
[docs] added a tutorial for using GCP Dataproc with Dagster Pipes
> [dagster-gcp] PipesDataprocJobClient tutorial

- python_modules/libraries/dagster-dbt/dagster_dbt/cloud/asset_defs.py
- python_modules/libraries/dagster-dbt/dagster_dbt/cloud/ops.py
- python_modules/libraries/dagster-dbt/dagster_dbt/cloud/resources.py
- python_modules/libraries/dagster-dbt/dagster_dbt/cloud/types.py
decision: no decorator (preview/beta?) -> ~~superseded~~ beta
reason: ~~dbt Cloud in dagster-dbt is no longer best practice, Dlift is. Since Dlift is still in preview, dbt Cloud in dagster-dbt should be superseded and not deprecated. Once Dlift is GA, we can deprecate dbt Cloud.~~ Dlift is not ready to be marked as an alternative to dbt cloud. Decorator was initially missing, so using the beta decorator here.
> [integrations-api][beta] dbt Cloud in dagster-dbt

- python_modules/libraries/dagster-dbt/tox.ini
dbt tests are incredibly flaky lately.
We get one error and one warning in each failed test:
`Fatal Python error: PyEval_SaveThread: the function must be called with the GIL held, but the GIL is released (the current Python thread state is NULL)`
and
`/usr/local/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdo`wn
Posts found online suggest that this is related to the number of thread/memory. 
We are unable to repro locally - dropping `--numprocesses 6` to see if it helps.
See this thread https://dagsterlabs.slack.com/archives/C03A0D72A6T/p1738592567816529
BK
> [dagster-dbt] Drop --numprocesses in dagster-dbt tests

- examples/experimental/dagster-dlift/dagster_dlift/client.py
- examples/experimental/dagster-dlift/dagster_dlift/compute.py
- examples/experimental/dagster-dlift/dagster_dlift/env_client.py
- examples/experimental/dagster-dlift/dagster_dlift/loader.py
- examples/experimental/dagster-dlift/dagster_dlift/project.py
- examples/experimental/dagster-dlift/dagster_dlift/translator.py
decision: no decorator (preview/beta?) -> preview
reason: dlift is still in its early development and testing stage, in `/examples/experimental`.
docs exist: not yet, would be required for beta
> [integrations-api][preview] dagster-dlift

- python_modules/libraries/dagster-airflow/dagster_airflow/dagster_asset_factory.py
- python_modules/libraries/dagster-airflow/dagster_airflow/dagster_factory.py
- python_modules/libraries/dagster-airflow/dagster_airflow/dagster_job_factory.py
- python_modules/libraries/dagster-airflow/dagster_airflow/hooks/dagster_hook.py
- python_modules/libraries/dagster-airflow/dagster_airflow/links/dagster_link.py
- python_modules/libraries/dagster-airflow/dagster_airflow/operators/dagster_operator.py
- python_modules/libraries/dagster-airflow/dagster_airflow/resources/airflow_ephemeral_db.py
- python_modules/libraries/dagster-airflow/dagster_airflow/resources/airflow_persistent_db.py
decision: no decorator (preview/beta?) -> superseded
reason: dagster-airflow is no longer best practice, Airlift is. Since Airlift is still beta, dagster-airflow should be superseded and not deprecated. Once Airlift is GA, we can deprecate dagster-airflow.
> [integrations-api][superseded] dagster-airflow

- python_modules/libraries/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/airflow_instance.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/basic_auth.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/load_defs.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/multiple_tasks.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/sensor/sensor_builder.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/serialization/serialized_data.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/top_level_dag_def_api.py
- python_modules/libraries/dagster-airlift/dagster_airlift/dbt/multi_asset.py
- python_modules/libraries/dagster-airlift/dagster_airlift/in_airflow/base_asset_operator.py
- python_modules/libraries/dagster-airlift/dagster_airlift/in_airflow/dag_proxy_operator.py
- python_modules/libraries/dagster-airlift/dagster_airlift/in_airflow/proxied_state.py
- python_modules/libraries/dagster-airlift/dagster_airlift/in_airflow/proxying_fn.py
- python_modules/libraries/dagster-airlift/dagster_airlift/in_airflow/task_proxy_operator.py
- python_modules/libraries/dagster-airlift/dagster_airlift/k8s/asset.py
- python_modules/libraries/dagster-airlift/dagster_airlift/mwaa/auth.py
decision: no decorator (preview/beta?) -> beta
reason: After discussion with @dpeng817, we consider that Airlift requires more design partners and feedback before being marked as GA.
> [integrations-api][beta] dagster-airlift

- python_modules/libraries/dagster-openai/dagster_openai/resources.py
decision: experimental (beta) -> GA
reason: dagster-openai has been stable for quite some time now (almost a year) and is used by several users.
> [integrations-api][ga] dagster-openai

- python_modules/libraries/dagster-sling/dagster_sling/sling_event_iterator.py
decision: experimental (beta) -> ga
reason: methods to fetch metadata in SlingEventIterator are a commonly used pattern (fetch_column_metadata, etc.) in other integrations like dbt.
docs exist: no, we would need a guide or section.
> [integrations-api][ga] SlingEventIterator in dagster-sling

- python_modules/libraries/dagster-dlt/dagster_dlt/dlt_event_iterator.py
- python_modules/libraries/dagster-dlt/dagster_dlt/resource.py
decision: experimental (beta) -> ga
reason: methods to fetch metadata in DltEventIterator are a commonly used pattern (fetch_row_count, etc.) in other integrations like dbt. DltResource is stable, adopted by many users and well documented.
docs exist: not for `fetch_row_count`, we would need a guide or section. Yes for the resource.
> [integrations-api][ga] dagster-dlt

- python_modules/dagster/dagster/_core/execution/run_metrics_thread.py
- python_modules/dagster/dagster/_utils/container.py
- python_modules/dagster/dagster_tests/core_tests/execution_tests/test_run_metrics_thread.py
Fix failed cgroup detection on serverless and ensure failure is graceful - stopping metric collection thread without failing the run - if other cases arise. 
NOCHANGELOG
> fix: run metrics thread capture cgroups support more acurately and exits gracefully

- python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_decorator.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran/fivetran_event_iterator.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran/managed/reconciliation.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran/ops.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
decision: 
- new pattern (asset decorator, translator): experimental -> beta
- old pattern (cacheable assets, load fns): ga -> superseded
reason: the new Fivetran pattern is not mature enough to be GA, but since the behavior is very similar to the previous pattern, we can say it's not preview. The old pattern is superseded by the new one.
> [integrations-api][beta][superseded] dagster-fivetran

- python_modules/libraries/dagster-airbyte/dagster_airbyte/asset_decorator.py
- python_modules/libraries/dagster-airbyte/dagster_airbyte/asset_defs.py
- python_modules/libraries/dagster-airbyte/dagster_airbyte/managed/reconciliation.py
- python_modules/libraries/dagster-airbyte/dagster_airbyte/resources.py
- python_modules/libraries/dagster-airbyte/dagster_airbyte/translator.py
decision: 
- new pattern (asset decorator, translator): experimental -> beta
- old pattern (cacheable assets, load fns): ga -> superseded
reason: the new Airbyte cloud pattern is not mature enough to be GA, but since the behavior is very similar to the previous pattern, we can say it's not preview. The old pattern is superseded by the new one.
> [integrations-api][beta][superseded] Airbyte Cloud in dagster-airbyte

- python_modules/libraries/dagstermill/dagstermill/asset_factory.py
- python_modules/libraries/dagstermill/dagstermill/context.py
- python_modules/libraries/dagstermill/dagstermill/factory.py
- python_modules/libraries/dagstermill/dagstermill/io_managers.py
- python_modules/libraries/dagstermill/dagstermill/manager.py
reason: decorator was missing. This integration may be a good fit for Pipes - so it should be beta and be superseded/deprecated if we implement it in Pipes.
docs exist: yes, but beta flag/note should be added
> [integrations-api][beta] dagstermill

- python_modules/libraries/dagster-pandera/dagster_pandera/__init__.py
reason: decorator was missing. It has been out there for quite some time, but is not mature enough for GA.
docs exist: yes, but beta flag/note should be added
> [integrations-api][beta] dagster-pandera

- python_modules/libraries/dagster-ssh/dagster_ssh/resources.py
reason: decorator was missing and we don't consider this integration mature enough to be GA.
Note: we consider deprecating and replacing with guide on how to customize resources.
docs exist: the API docs [page](https://docs.dagster.io/_apidocs/libraries/dagster-ssh#ssh-sftp-dagster-ssh) is empty 
> [integrations-api][beta] dagster-ssh

- python_modules/libraries/dagster-github/dagster_github/resources.py
decision: no decorator -> superseded
reason: we consider that it does not make sense to host a GitHub resource officially.
> [integrations-api][deprecated] dagster-github

- python_modules/libraries/dagster-aws/dagster_aws/ecs/executor.py
- python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/ecs.py
decision:
pipes: experimental -> ga
executor: experimental -> ga
reason: the pipes client has been around for quite some time now. It is well documented and adopted. The executor should have been GA already, removing the experimental decorator.
> [integrations-api][ga] PipesECSClient and ECS executors in dagster-aws

- python_modules/libraries/dagster-aws/dagster_aws/ssm/resources.py
reason: decorator was missing. It has been out there for quite some time, but is not mature enough for GA.
Note: to be deprecated when the new pattern is implemented.
docs exist: no, we would need a guide
> [integrations-api][beta] AWS SSM in dagster-aws

- python_modules/libraries/dagster-aws/dagster_aws/secretsmanager/resources.py
- python_modules/libraries/dagster-aws/dagster_aws/secretsmanager/secrets.py
reason: decorator was missing. It has been out there for quite some time, but is not mature enough for GA.
Note: to be deprecated when the new pattern is implemented.
docs exist: API docs only, no guide
> [integrations-api][beta] AWS Secrets Manager in dagster-aws

- python_modules/libraries/dagster-aws/dagster_aws/cloudwatch/loggers.py
- python_modules/libraries/dagster-aws/dagster_aws/pipes/message_readers.py
pipes: experimental -> ga
old pattern:  ga -> deprecated
reason: new pipes pattern has been around for quite some time and should be GA like other pipes for 1.9. Old pattern is deprecated now that the new pattern is GA.
docs exist:
- message read: no, we would need a guide
- log reader: only API docs, we would need a guide
> [integrations-api][deprecated][ga] Cloudwatch old pattern and pipes in dagster-aws

- python_modules/libraries/dagster-aws/dagster_aws/ecr/resources.py
reason: decorator was missing.
Note: we consider deprecating and replacing with guide on how to write/customize resources.
docs exist: No - a guide may not be required since we consider deprecating this. Let's focus on the guide on how to write/customize resources.
> [integrations-api][beta] AWS ECR in dagster-aws

- python_modules/libraries/dagster-datadog/dagster_datadog/resources.py
reason: decorator was missing and we don't consider this integration mature enough to be GA.
Note: we consider deprecating and replacing with guide on how to write/customize resources.
docs exist: the API docs [page](https://docs.dagster.io/_apidocs/libraries/dagster-datad) only, no guide - the guide may not be required since we consider deprecating this. Let's focus on the guide on how to write/customize resources.
> [integrations-api][beta] dagster-datadog

- python_modules/libraries/dagster-ge/dagster_ge/factory.py
reason: decorator was missing and we don't consider this integration mature enough to be GA.
Note: we consider deprecating and replacing with guide on how to write/customize resources.
docs exist: the API docs [page](https://docs.dagster.io/_apidocs/libraries/dagster-ge) only, no guide - the guide may not be required since we consider deprecating this. Let's focus on the guide on how to write/customize resources.
> [integrations-api][beta] dagster-ge

- python_modules/libraries/dagster-dg/dagster_dg/cli/component.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/component_type.py
- python_modules/libraries/dagster-dg/dagster_dg/component.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_type_commands.py
Refactors the RemoteComponentRegistry to use separate types for the different types of keys rather than separate dictionaries.
NOCHANGELOG
> [components] Refactor RemoteComponentRegistry

- python_modules/libraries/dagster-components/dagster_components/cli/list.py
- python_modules/libraries/dagster-components/dagster_components/cli/scaffold.py
- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/core/component_decl_builder.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/component_loader.py
- python_modules/libraries/dagster-components/dagster_components_tests/registry_tests/test_registry.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/check_utils.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/component.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/component_type.py
- python_modules/libraries/dagster-dg/dagster_dg/component.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_type_commands.py
Makes the following changes to our ontology:
- The `ComponentKey` refers to an in-memory object that bundles together all information necessary to locate a ComponentType (name and namespace). This term is not intended to be user-visible.
- The "typename" of a component refers to the fully-disambiguated string that the user will use to refer to a component type, e.g. `dbt_project@dagster_dbt`. Users will see this as an argument to CLI commands (component-type = ...), and in error messages ("component type xyz@abc not found"). 
- The "name" of a component type is the name of the component type within a particular namespace. This is what gets passed into the `@register_component_type` decorator as the "name" argument.
- The "namespace" of a component type is the container that this component …
> [components] Update naming conventions and error messages

- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs.py
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs_deployments.py
- examples/experimental/components/examples/hello_world_deployment/code_locations/hello_world/hello_world/definitions.py
- python_modules/libraries/dagster-components/dagster_components/cli/list.py
- python_modules/libraries/dagster-components/dagster_components/cli/scaffold.py
- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/core/component_decl_builder.py
- python_modules/libraries/dagster-components/dagster_components/core/component_key.py
- python_modules/libraries/dagster-components/dagster_components_tests/cli_tests/test_commands.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/component_loader.py
- python_modules/libraries/dagster-components/dagster_components_tests/registry_tests/test_registry.py
- python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_component_key_synced.py
- python_modules/libraries/dagster-components/setup.py
- python_modules/libraries/dagster-components/tox.ini
- python_modules/libraries/dagster-dg/dagster_dg/cli/check_utils.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/component.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/component_type.py
- python_modules/libraries/dagster-dg/dagster_dg/component.py
- python_modules/libraries/dagster-dg/dagster_dg/component_key.py
- python_modules/libraries/dagster-dg/dagster_dg/docs.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/component_command_tests/test_check.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_type_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_custom_help_format.py
This separates out the ComponentKey class into its own separate file in both dagster-dg and dagster-components, and updated dagster-components to distinguish between local and global keys.
Unfortunately, we're forced to copy-past code for the time-being as there's not a good way of sharing code between these libraries, but at least now it's easy to copy paste between the files to keep them in sync.
NOCHANGELOG
> [components] Synchronize dagster-dg and dagster-components ComponentKey class

- docs/docs-beta/versioned_docs/version-1.9.10/guides/build/assets/defining-assets.md
The link wasn't clickable and i wanted to click it. 
Used the Github rich markdown preview to test that it works as expected. 
> [docs] Fixed the markdown link towards assets metadata from assets

- docs/docs-beta/versioned_docs/version-1.9.10/integrations/libraries/shell.md
Versioned /integrations/libraries/shell.md doc points to example code that no longer exists. This PR embeds that old example code in the doc to fix the failing build.
> Embed old code in /integrations/libraries/shell.md to fix build

- js_modules/dagster-ui/packages/ui-core/src/ui/MarkdownWithPlugins.tsx
Apply an additional (wrapper) classname to `ReactMarkdown` to ensure that our custom hljs styles can take precedence over GitHub styles.
Leaving the GitHub styles in place for now since we may be relying on some classnames that aren't being overridden here, and I don't want to hunt for those right now.
View Storybook examples, verify that colors are correct, double check Chrome devtools to verify CSS precedence.
> [ui] Bump specificity of markdown syntax highlighting CSS

- python_modules/libraries/dagster-gcp/dagster_gcp/dataproc/ops.py
- python_modules/libraries/dagster-gcp/dagster_gcp/dataproc/resources.py
reason: decorator was missing. This integration may be a good fit for Pipes - so it should be beta and be superseded/deprecated if we implement it in Pipes.
docs exist: API docs only, a guide might not be required if we deprecate it in favor of Pipes.
> [integrations-api][beta] GCP Dataproc in dagster-gcp

- python_modules/libraries/dagster-prometheus/dagster_prometheus/resources.py
reason: decorator was missing and we don't consider this integration mature enough to be GA.
Note: we consider deprecating and replacing with guide on how to write/customize resources.
docs exist: the API docs [page](https://docs.dagster.io/_apidocs/libraries/dagster-prometheus) only, no guide - the guide may not be required since we consider deprecating this. Let's focus on the guide on how to write/customize resources.
> [integrations-api][beta] dagster-prometheus

- python_modules/dagster/dagster/_core/definitions/asset_spec.py
- python_modules/dagster/dagster/_core/definitions/decorators/decorator_assets_definition_builder.py
- python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py
- python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py
Fixes a regression in dagster-dbt after converting it to use spec-based creation. The core thing here is that we need a way to pass a DagsterType into the system when using specs.
Before, it was assumed that if you were passing an io_manager_key, this meant that you definitely wanted that IOManager to handle all of the outputs, hence the DagsterType was set to DagsterAny instead of the default Nothing.
However, this is not actually a safe assumption in all cases, as with the dagster-dbt integration it's useful to set the io_manager_key so that downstream assets can know how to consume these outputs.
This PR follows patterns we've used in the past of adding another bit of named metadata to the spec that allows us to wire this sort of information into the op construction logic.
Because this …
> [dagster-dbt] Fix error when using dbt_assets decorator with io_manager_key

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/deployments/11-component-type-list.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/deployments/12-workspace.yaml
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/deployments/7-component-type-list.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/deployments/8-component-type-list.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/11-component.yaml
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/18-dg-list-component-types.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/19-dg-component-type-info.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/20-dg-scaffold-jdbt.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/21-component-jdbt.yaml
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/22-project-jdbt.yaml
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/7-dg-list-component-types.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/8-dg-list-component-types.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/9-dg-scaffold-sling-replication.txt
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs.py
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs_deployments.py
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/utils.py
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/utils.py
- examples/docs_beta_snippets/tox.ini
Previously, scaffolding code locations in the docs snippet dg CLI tests would install production copies of the components library. This PR ensures in every place we use solely editable packages, to prevent any cross-version incompatibility issues.
> [dg docs test] Use solely editable packages in components docs test, re-enable

- python_modules/libraries/dagster-mlflow/dagster_mlflow/hooks.py
- python_modules/libraries/dagster-mlflow/dagster_mlflow/resources.py
reason: decorator was missing. This integration may be a good fit for Pipes - so it should be beta and be superseded/deprecated if we implement it in Pipes.
docs exist: Only API docs [page](https://docs.dagster.io/_apidocs/libraries/dagster-mlflow) only
> [integrations-api][beta] dagster-mlflow

- python_modules/libraries/dagster-dbt/dagster_dbt/asset_specs.py
- python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_event_iterator.py
- python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py
- python_modules/libraries/dagster-dbt/dagster_dbt/freshness_builder.py
decision:
- event iterator: experimental (beta) -> ga
- asset spec builder: experimental (beta) -> ga
- freshness check builder: experimental (beta) -> beta
- translator methods: experimental (beta) -> beta
reason: methods to fetch metadata in DbtEventIterator are commonly used and stable(fetch_row_count, etc.). The asset spec builder is also stable. The freshness check builder could be tested more before going to GA. Translator methods will soon be deprecated.
docs exist: Yes, but we could have more examples for the asset spec and freshness check builders.
> [integrations-api][beta][ga] dbt in dagster-dbt

- python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
- python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_impls.py
- python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
- python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/operands.py
- python_modules/dagster/dagster/_utils/caching_instance_queryer.py
- python_modules/dagster/dagster_tests/declarative_automation_tests/automation_condition_tests/builtins/test_data_version_changed.py
This closes a gap we've had for awhile -- we have a `code_version_changed` condition but not a `data_version_changed` one. This is useful for users who make heavy use of data versions to avoid triggering materializations in response to upstream updats that don't change the data version
Added a new `AutomationCondition.data_version_changed()` condition.
> [da] Create `data_version_changed` AutomationCondition

- python_modules/libraries/dagster-docker/dagster_docker/docker_executor.py
- python_modules/libraries/dagster-docker/dagster_docker/ops/docker_container_op.py
- python_modules/libraries/dagster-docker/dagster_docker/pipes.py
pipes: experimental -> ga
old pattern: ga -> deprecated
reason: new pipes pattern has been around for quite some time and should be GA like other pipes for 1.9. Old pattern is deprecated now that the new pattern is GA.
docs exist: API docs only, we would need a guide.
> [integrations-api][beta][ga] Docker old pattern and pipes in dagster-docker

- .buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
- python_modules/libraries/dagster-dbt/dagster_dbt/utils.py
- python_modules/libraries/dagster-dbt/tox.ini
Fixed: https://github.com/dagster-io/dagster/issues/27007
Today I upgraded dbt to 1.9.1 but encountered an error while running dagster.
In the end, I found that UnitTestDefinition was not properly parsed.
In dbt, [this is also how they create UnitTestDefinition](https://github.com/dbt-labs/dbt-core/blob/8a8857a85c0cc66c7e3de9eb7e9ca7fd63d553a4/core/dbt/parser/unit_tests.py#L609).
Here are the details:
Updated the instantiation of UnitTestDefinition in the `__getattr__`
method to utilize the from_dict method instead of the constructor. This
change enhances the clarity and consistency of the code when handling
unit test nodes from the manifest JSON.
Verified `test_dbt_with_unit_tests()` passes with both `fqn:*` and `tag:test` selectors. …
> [dagster-dbt] Refactor UnitTestDefinition instantiation in utils.py to use `from_dict` method

- python_modules/libraries/dagster-gcp/dagster_gcp/bigquery/io_manager.py
reason: rename the decorator to use the new API lifecycle language.
> [integrations-api][beta] GCP Bigquery in dagster-gcp

- python_modules/libraries/dagster-k8s/dagster_k8s/ops/k8s_job_op.py
reason: rename the decorator to use the new API lifecycle language.
> [integrations-api][beta] K8s old pattern in dagster-k8s

- js_modules/dagster-ui/packages/ui-core/jest/mocks/ComputeGraphData.worker.ts
- js_modules/dagster-ui/packages/ui-core/src/app/Flags.tsx
- js_modules/dagster-ui/packages/ui-core/src/asset-graph/ComputeGraphData.types.ts
- js_modules/dagster-ui/packages/ui-core/src/asset-graph/ComputeGraphData.worker.ts
- js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx
- js_modules/dagster-ui/packages/ui-core/src/graph/asyncGraphLayout.ts
- js_modules/dagster-ui/packages/ui-core/src/search/createSearchWorker.tsx
- js_modules/dagster-ui/packages/ui-core/src/workers/Worker.oss.ts
- js_modules/dagster-ui/packages/ui-core/src/workers/WorkerThread.oss.ts
- js_modules/dagster-ui/packages/ui-core/src/workers/dagre_layout.worker.ts
- js_modules/dagster-ui/packages/ui-core/src/workers/fuseSearch.worker.ts
1. Added a `createWorkerThread` utility to be used inside of web-worker threads. This utility handles setting up feature flags and forwarding errors back to the main thread. In cloud it will also receive cloud specific flags.
2. Added a `Worker` class to be used in place of the global Worker class.  This class forwards feature flags and receives errors. It's a shared component so that cloud can inject custom behavior.
In a follow-up PR I will figure out mocking with these utilities and add lint rules to make us go through our custom Worker abstraction once we feel its ready for prime time. 
I stopped forwarding the `flagSelectionSyntax` flag manually for `ComputeGraphData.worker` and saw that it was correctly handling the selection syntax when the flag was on and not when it was off.
> Add basic utility/class for WebWorkers

- python_modules/libraries/dagster-polars/dagster_polars/io_managers/bigquery.py
- python_modules/libraries/dagster-polars/dagster_polars/io_managers/delta.py
- python_modules/libraries/dagster-polars/dagster_polars/io_managers/parquet.py
decision: experimental -> ga
reason: these IO managers have been around for quite some time now and are stable.
docs exist: yes - API docs only but it includes a guide, see [here](https://docs.dagster.io/_apidocs/libraries/dagster-polars)
> [integrations-api][ga] IO Managers in dagster-polars

- python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/emr_containers.py
decision: experimental -> preview
reason: PipesEMRContainersClient is pretty new, so using the preview decorator. We can use the beta decorator if @danielgafni thinks the feature is a beta stage.
docs exist: yes https://docs.dagster.io/guides/build/external-pipelines/aws-emr-containers-pipeline
> [integrations-api][preview] PipesEMRContainersClient

- js_modules/dagster-ui/packages/ui-core/src/util/idb-lru-cache.ts
as titled, prefixing the db name so that we don't try and re-use any existing DBs and have a fresh new one while we work out any back-compat issues.
> `idb-lru-cache` Change database name to avoid being blocked by old versions

- python_modules/dagster/dagster/_core/execution/plan/compute.py
- python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_job.py
Ran into this when running a Sling sync that got separated into multiple steps bc of some upstream deps.
Previously failing test.
> Fixed an issue where emitting `AssetResult` when ops or multi-assets are triggered multiple times in the same run
> Fix issue emitting AssetResult with multiple steps for same op

- python_modules/libraries/dagster-aws/dagster_aws/pipes/clients/emr_containers.py
- python_modules/libraries/dagster-dbt/dagster_dbt/cloud/asset_defs.py
decision: experimental_param -> beta_param
reason: experimental_param will be removed and the alternative is the beta_param
> [integrations-api][beta_param] use beta_param for dbt Cloud

- python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resource.py
Follow up for PR https://github.com/dagster-io/dagster/pull/27562
Duckdb 1.2.0 was released earlier this afternoon - only one test failing in BK since the new version instead of random flaky tests. It's always the same tests, for dbt core 1.7: https://buildkite.com/dagster/dagster-dagster/builds/111070#0194d668-40aa-440e-a2e4-a039389e8967
Skipping this test until we resolve the lock issue.
BK
> [dagster-dbt] Skip failing test with lock issue for Duckdb

- .prettierignore
`make prettier` is broken due to some files added for testing broken components yaml, this fixes it by adding a `.prettierignore` file.
`make prettier`
> [prettier] Fix `make prettier`

- python_modules/dagster/dagster/_cli/api.py
Summary:
This makes it easier to debug when verify_step prevents a step from running
BK, launch a job with the docker executor and inspect structured logs
NOCHANGELOG
> Correctly attribute verify_step engine events to the proper step

- python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
reason: this is an unfortunate case where a fairly-new option actually ended up needing to reference the superseded repository API. we should fix that before making this GA (and this is a fairly niche option)
> [core-api][experimental] repository_def in RunStatusSensorDefinition

- python_modules/dagster/dagster/_core/definitions/definitions_class.py
- python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
reason: these seem a bit more speculative -- `get_all_asset_specs()` has somewhat unituitive behavior as `Definitions(assets=[AssetSpec("a", deps="b")]).get_all_asset_specs()` actually returns two specs. the reconstruction metadata bit also feels subject to change in the future
> [core-api][experimental] Definitions.get_all_asset_specs, Definitions.with_reconstruction_metadata

- python_modules/dagster/dagster/_core/definitions/definitions_class.py
- python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
- python_modules/dagster/dagster/_core/storage/fs_io_manager.py
reason: doubt many people are using this, but it has existed for many many years and there is no reason for us to remove support for it
> [core-api][experimental] `custom_path_fs_io_manager`

- python_modules/dagster/dagster/_core/definitions/definitions_class.py
- python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
- python_modules/dagster/dagster/_core/storage/fs_io_manager.py
reason: we are leaning heavily on this behavior in components-land, and generally see this as a good tool when organizing a code location. we should formally endorse it
docs exist: no (will likely need to create some sort of guide along the lines of "organizing code locations", which would reference this)
> [core-api][experimental] `Definitions.merge`

- python_modules/dagster/dagster/_core/definitions/data_version.py
- python_modules/dagster/dagster/_core/definitions/definitions_class.py
- python_modules/dagster/dagster/_core/definitions/events.py
- python_modules/dagster/dagster/_core/definitions/resource_definition.py
- python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
- python_modules/dagster/dagster/_core/storage/fs_io_manager.py
reason: many of these APIs have not been publicized and are not part of core code paths. want to retain the option of changing the naming / structure in the future
docs exist: n/a (but no)
> [core-api][experimental] DataVersion assorted APIs

- python_modules/dagster/dagster/_core/definitions/asset_selection.py
- python_modules/dagster/dagster/_core/definitions/data_version.py
- python_modules/dagster/dagster/_core/definitions/definitions_class.py
- python_modules/dagster/dagster/_core/definitions/events.py
- python_modules/dagster/dagster/_core/definitions/resource_definition.py
- python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
- python_modules/dagster/dagster/_core/storage/fs_io_manager.py
reason: this has existed for a long time, we need to support it for the new asset selection syntax, and there's no reason that we would not want to support this behavior
docs exist: yes (API only, which is ok)
> [core-api][experimental] AssetSelection.tag

- python_modules/dagster/dagster/_core/definitions/asset_selection.py
- python_modules/dagster/dagster/_core/definitions/assets.py
- python_modules/dagster/dagster/_core/definitions/data_version.py
- python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
- python_modules/dagster/dagster/_core/definitions/definitions_class.py
- python_modules/dagster/dagster/_core/definitions/events.py
- python_modules/dagster/dagster/_core/definitions/resource_definition.py
- python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
- python_modules/dagster/dagster/_core/storage/fs_io_manager.py
decision: experimental -> public (could be convinced otherwise)
reason: this has existed for a long time, and even if it isn't directly recommended in most cases at the moment, we're moving to a world where more locally-scoped resource definitions are the norm and so this seems fair to support.
docs exist: api only
> [core-api][experimental] direct resource passing

- python_modules/dagster/dagster/_core/definitions/asset_selection.py
- python_modules/dagster/dagster/_core/definitions/assets.py
- python_modules/dagster/dagster/_core/definitions/data_version.py
- python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
- python_modules/dagster/dagster/_core/definitions/definitions_class.py
- python_modules/dagster/dagster/_core/definitions/events.py
- python_modules/dagster/dagster/_core/definitions/partition_mapping.py
- python_modules/dagster/dagster/_core/definitions/resource_definition.py
- python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
- python_modules/dagster/dagster/_core/storage/fs_io_manager.py
reason: these APIs have existed for many years without change, and are intertwined with serialized objects, making it extremely unlikely that we would change them
> [core-api][experimental] multi partition mappings

- python_modules/dagster/dagster/_core/definitions/asset_selection.py
- python_modules/dagster/dagster/_core/definitions/assets.py
- python_modules/dagster/dagster/_core/definitions/auto_materialize_policy.py
- python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_impls.py
- python_modules/dagster/dagster/_core/definitions/data_version.py
- python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
- python_modules/dagster/dagster/_core/definitions/definitions_class.py
- python_modules/dagster/dagster/_core/definitions/events.py
- python_modules/dagster/dagster/_core/definitions/partition_mapping.py
- python_modules/dagster/dagster/_core/definitions/resource_definition.py
- python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
- python_modules/dagster/dagster/_core/storage/fs_io_manager.py
decision: experimental -> deprecated
reason: it's deprecated, these callsites were missed earlier
> [core-api][experimental] AMP

- python_modules/dagster/dagster/_core/definitions/asset_selection.py
- python_modules/dagster/dagster/_core/definitions/assets.py
- python_modules/dagster/dagster/_core/definitions/auto_materialize_policy.py
- python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_impls.py
- python_modules/dagster/dagster/_core/definitions/data_version.py
- python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
- python_modules/dagster/dagster/_core/definitions/definitions_class.py
- python_modules/dagster/dagster/_core/definitions/events.py
- python_modules/dagster/dagster/_core/definitions/partition_mapping.py
- python_modules/dagster/dagster/_core/definitions/resource_definition.py
- python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
- python_modules/dagster/dagster/_core/storage/fs_io_manager.py
reason: we will likely retain some version of this parameter, but low confidence on this being the final name / form
docs: n/a
> [core-api][experimental] execution type

- python_modules/dagster/dagster/_core/definitions/asset_selection.py
- python_modules/dagster/dagster/_core/definitions/assets.py
- python_modules/dagster/dagster/_core/definitions/auto_materialize_policy.py
- python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_impls.py
- python_modules/dagster/dagster/_core/definitions/data_version.py
- python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
- python_modules/dagster/dagster/_core/definitions/definitions_class.py
- python_modules/dagster/dagster/_core/definitions/events.py
- python_modules/dagster/dagster/_core/definitions/partition_mapping.py
- python_modules/dagster/dagster/_core/definitions/resource_definition.py
- python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
- python_modules/dagster/dagster/_core/definitions/source_asset.py
- python_modules/dagster/dagster/_core/storage/fs_io_manager.py
decision: experimental -> deprecated
reason: FreshnessPolicy is deprecated
> [core-api][experimental] freshness_policy param

- python_modules/dagster/dagster/_core/definitions/asset_selection.py
- python_modules/dagster/dagster/_core/definitions/assets.py
- python_modules/dagster/dagster/_core/definitions/auto_materialize_policy.py
- python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_impls.py
- python_modules/dagster/dagster/_core/definitions/data_version.py
- python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
- python_modules/dagster/dagster/_core/definitions/definitions_class.py
- python_modules/dagster/dagster/_core/definitions/events.py
- python_modules/dagster/dagster/_core/definitions/partition_mapping.py
- python_modules/dagster/dagster/_core/definitions/resource_definition.py
- python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
- python_modules/dagster/dagster/_core/definitions/source_asset.py
- python_modules/dagster/dagster/_core/storage/fs_io_manager.py
reason: this is a bit of glue code for users still using `@repository`, but there's no reason to delete it and we have no plans of changing it (plus it has existed for years).
> [core-api][experimental] `create_repository_using_definitions_args`

- python_modules/dagster/dagster/_annotations.py
- python_modules/dagster/dagster/_core/definitions/asset_selection.py
- python_modules/dagster/dagster/_core/definitions/assets.py
- python_modules/dagster/dagster/_core/definitions/auto_materialize_policy.py
- python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_impls.py
- python_modules/dagster/dagster/_core/definitions/backfill_policy.py
- python_modules/dagster/dagster/_core/definitions/data_version.py
- python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
- python_modules/dagster/dagster/_core/definitions/definitions_class.py
- python_modules/dagster/dagster/_core/definitions/events.py
- python_modules/dagster/dagster/_core/definitions/partition_mapping.py
- python_modules/dagster/dagster/_core/definitions/resource_definition.py
- python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
- python_modules/dagster/dagster/_core/definitions/source_asset.py
- python_modules/dagster/dagster/_core/storage/fs_io_manager.py
reason: this requires a final pass on our end to feel comfortable marking as GA, but I think it is worth doing in the near future as this is a powerful feature
docs exist: no (will need to)
> [core-api][experimental] BackfillPolicy

- python_modules/dagster/dagster/_annotations.py
- python_modules/dagster/dagster/_core/definitions/asset_selection.py
- python_modules/dagster/dagster/_core/definitions/assets.py
- python_modules/dagster/dagster/_core/definitions/auto_materialize_policy.py
- python_modules/dagster/dagster/_core/definitions/auto_materialize_rule_impls.py
- python_modules/dagster/dagster/_core/definitions/backfill_policy.py
- python_modules/dagster/dagster/_core/definitions/data_version.py
- python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
- python_modules/dagster/dagster/_core/definitions/definitions_class.py
- python_modules/dagster/dagster/_core/definitions/events.py
- python_modules/dagster/dagster/_core/definitions/partition_mapping.py
- python_modules/dagster/dagster/_core/definitions/resource_definition.py
- python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
- python_modules/dagster/dagster/_core/definitions/source_asset.py
- python_modules/dagster/dagster/_core/execution/context/asset_execution_context.py
- python_modules/dagster/dagster/_core/execution/context/op_execution_context.py
- python_modules/dagster/dagster/_core/storage/fs_io_manager.py
decision: experimental -> public (uncertain)
reason: this has existed for years without change. even if this is not a commonly-used API, we should probably just make the call that we're not changing it at this point
> [core-api][experimental] `get_asset_provenance`

- python_modules/dagster/dagster/_check/decorator.py
- python_modules/dagster/dagster_tests/general_tests/test_checked.py
Probably about 6 years overdue, add a decorator that inserts a wrapping function that performs `check` calls based on annotations.
added test
> add @checked

- examples/docs_snippets/docs_snippets/concepts/partitions_schedules_sensors/sensors/sensor_alert.py
- python_modules/dagster/dagster/_core/execution/execution_result.py
- python_modules/dagster/dagster_tests/core_tests/test_event_logging.py
- python_modules/dagster/dagster_tests/core_tests/test_job_execution.py
- python_modules/dagster/dagster_tests/definitions_tests/test_sensor_invocation.py
Not a public API, so shouldn't be a problem
> ExecutionResult.get_job_failure_event -> get_run_failure_event

- python_modules/libraries/dagster-dg/dagster_dg/cli/component.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/component_type.py
- python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/component_command_tests/test_component_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_type_commands.py
Previously, running `dg component scaffold some.component` would fail with a missing subcommand error (from `click`) if the component wasn't installed. This customizes the error message to be about the component being unregistered.
New unit test
> [components] Improve error message for `dg component scaffold <uninstalled-component>` (BUILD-666)

- js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx
- js_modules/dagster-ui/packages/ui-core/src/asset-selection/input/AssetSelectionInput.oss.tsx
as titled. 
Switching to useLayoutEffect to avoid a render where the loading spinner disappears.
> [easy][Asset Graph] useLayoutEffect + wait for supplementary data 

- python_modules/dagster/dagster/_core/execution/stats.py
- python_modules/dagster/dagster_tests/storage_tests/test_event_log.py
Sometimes step worker failures can cause step retries to hang.  Our step stats calculations do not handle the case where a step worker fails (and requests a retry) before the step has started.
BK
Fixed the step stats calculations for steps that fail + retry before the step starts, which happens if a failure happens in the step worker before the compute function begins execution.  This should help with sporadic hanging of step retries.
> fix step stats for steps that fail + retry before the step starts

- python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/code_locations/sling_location/components/ingest/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_sling_integration_test.py
After recent changes, we no longer do a pre-resolution step for the params schema, which means we need to explicitly resolve parameters passed to resources.
This should probably be done using a separate wrapper class but for now we can just do the simple fix that restores previous behavior.
A similar thing should be done for dbt
NOCHANGELOG
> [components] Fix SlingResource resolution

- .buildkite/dagster-buildkite/dagster_buildkite/steps/dagster.py
These were being run as part of the legacy docs test suite, which was dropped in #27627
> [bk] re-enable examples tests

- js_modules/dagster-ui/packages/ui-core/src/instance/ConcurrencyTabs.tsx
- js_modules/dagster-ui/packages/ui-core/src/instance/InstanceConcurrency.tsx
- js_modules/dagster-ui/packages/ui-core/src/instance/InstanceConcurrencyKeyInfo.tsx
Split Concurrency page into tabs. This was previously done on Cloud and not here, but the virtualized concurrency key list doesn't work as desired in the single page view of all concurrency information.
View Concurrency page. Verify that it is split into tabs, and that the tabs behave and render correctly. Verify that the concurrency key list is correctly virtualized, with batches of `SingleConcurrencyKeyQuery` requests appropriately sliced.
[ui] Fix excessive rendering and querying on Concurrency configuration page.
> [ui] Split Concurrency page

- js_modules/dagster-ui/packages/ui-core/src/runs/LogsRowStructuredContent.tsx
Asset check events in the run logs link to a seconds-based timestamp on the corresponding asset permalink, since the value coming from GraphQL is seconds-based. The value on the permalink query param needs to be msec-based.
I think it would be better if all of our timestamp fields consistently provided msec-based timestamps, but even within the relevant GraphQL types involved in this narrow use case (asset evaluation and materialization timestamps), I see a mix of seconds-based and msec-based...so this is potentially a gnarly change to take on here. cc @OwenKephart 
View run logs where the issue repros. Filter to `type:ASSET_CHECK_EVALUATION`, verify that permalinks to assets have correct `asOf` values, and that navigation to those pages results in appropriate timestamps in the UI.
[ui] …
> [ui] Repair asset check asOf param from run logs

- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/component_command_tests/test_component_commands.py
Ran into this in the new `product-operations` purina code location, which didn't have the same python module name as the code location name. The error message gave me the runaround.
New unit test.
> [dg cli] More clearly error if module name doesn't match what we expect

- .github/workflows/vale.yml
- docs/docs/touch.md
My understanding of this doc step is that we eventually want to use it, but we consider it non-blocking on docs PRs today?
In that case, should we tell GitHub Actions that it's okay for this step to fail? I think that'll prevent all of our docs PRs from having a big red failure status. Thoughts?
> Ignore vale failures

- docs/docs/dagster-plus/deployment/deployment-types/serverless/dagster-ips.md
- docs/docs/dagster-plus/deployment/management/dagster-ips.md
We already did this once before as a statuspage update:
https://dagstercloud.statuspage.io/incidents/qgrszl3p61b7
We get asked from time to time and these don't really change that often so let's stick them in a doc for now. Similar to how we treat our Serverless IPs.
> Document our dagster+ IP addresses

- js_modules/dagster-ui/packages/ui-core/src/overview/useGroupTimelineRunsBy.tsx
Storage persistence of the group-by option on the run timeline is currently broken. More specifically, the value may be persisted, but it's not being used -- the default value (`job`) always ends up as the initial value.
I'm not sure that the default behavior of `useQueryAndLocalStoragePersistedState` is quite right for this use case (namely, `Syncs changes back to localStorage`) so I'm trying to simplify the behavior here specifically without changing `useQueryAndLocalStoragePersistedState` itself and risking breaking other callsites.
- If the query param is present, use it.
- If not, use the stored value.
- If that's not set, use the default value.
- When changing the group-by option with the dropdown, update the query param and set the localStorage value.
Ideally this should allow …
> [ui] Run timeline: Fix group-by persistence

- python_modules/libraries/dagster-components/setup.py
- python_modules/libraries/dagster-dg/dagster_dg/config.py
- python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/component_command_tests/test_check.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/component_command_tests/test_component_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_code_location_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_type_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
- python_modules/libraries/dagster-dg/setup.py
`tomlkit` will allow us to programmatically manipulate TOML while preserving comments and spacing.
> [components] Move to tomlkit from tomli/tomli_w for TOML handling

- docs/sphinx/_ext/dagster-sphinx/dagster_sphinx/__init__.py
- docs/sphinx/_ext/dagster-sphinx/dagster_sphinx/docstring_flags.py
- docs/sphinx/_ext/sphinx-mdx-builder/sphinxcontrib/mdxbuilder/writers/mdx.py
As title - the experimental language doesn't exist anymore with the new API lifecycle stages.
> [docs] Delete experimental and experimental_param annotations in Sphinx

- python_modules/dagster/dagster/_core/definitions/metadata/metadata_value.py
- python_modules/dagster/dagster/_core/definitions/metadata/table.py
reason: this has existed for awhile, and has comprehensive docs, seems unlikely that we would change it in any meaningful way
> [core-api][experimental] Table metadata

- python_modules/dagster/dagster/_core/definitions/metadata/metadata_value.py
- python_modules/dagster/dagster/_core/definitions/metadata/table.py
- python_modules/dagster/dagster/_core/definitions/time_window_partition_mapping.py
reason: this is a fairly niche option, and we might want to change the name in the future
> [core-api][experimental] allow_nonexistent_upstream_partitions

- python_modules/dagster/dagster/_core/definitions/decorators/source_asset_decorator.py
- python_modules/dagster/dagster/_core/definitions/metadata/metadata_value.py
- python_modules/dagster/dagster/_core/definitions/metadata/table.py
- python_modules/dagster/dagster/_core/definitions/time_window_partition_mapping.py
reason: we have aspirations of simplifying the ways in which we define asset observation computations, let's leave the option value open to change names on these APIs
> [core-api][experimental] observable_source_asset, multi_observable_source_asset

- python_modules/dagster/dagster/_core/definitions/antlr_asset_selection/antlr_asset_selection.py
- python_modules/dagster/dagster/_core/definitions/asset_selection.py
- python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_tester.py
- python_modules/dagster/dagster/_core/definitions/decorators/source_asset_decorator.py
- python_modules/dagster/dagster/_core/definitions/metadata/metadata_value.py
- python_modules/dagster/dagster/_core/definitions/metadata/table.py
- python_modules/dagster/dagster/_core/definitions/observe.py
- python_modules/dagster/dagster/_core/definitions/time_window_partition_mapping.py
- python_modules/dagster/dagster/_core/definitions/utils.py
- python_modules/dagster/dagster_tests/asset_defs_tests/test_antlr_asset_selection.py
- python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection.py
- python_modules/dagster/dagster_tests/definitions_tests/asset_policy_sensors_tests/test_default_auto_materialize_sensors.py
decision: experimental -> GA (after parameter change)
reason: if we're going to make this change, we should acompany it with marking this API as stable (i.e. we should only make the name change once). "source assets" as a concept no longer really exist, and external assets is the more general term (and more accurate to what these parameters were actually filtering for.
> [core-api][experimental] include_sources -> include_external_assets

- python_modules/dagster/dagster/_core/definitions/partition_mapping.py
- python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_asset_partition_mappings.py
- python_modules/dagster/dagster_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_automation_condition_tester.py
Summary:
Only needed in cases like the one in the added test, but could produce an invalid subset before.
BK (new test)
NOCHANGELOG
> Fix current_time not being passed through in IdentityPartitionMapping

- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_partition_backfill.py
- python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
- python_modules/dagster/dagster/_core/execution/asset_backfill.py
- python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py
- python_modules/dagster/dagster_tests/declarative_automation_tests/legacy_tests/scenarios/partition_scenarios.py
This PR changes the core asset backfill eligibility logic to make it work with subsets instead of individual asset partition keys. This makes things more complicated (instead of returning a boolean + string in the bfs logic, we have to return the subset that passed and the subsets + reasons that they didn't pass, but much faster for large partition sets. A backfill of 125k partition keys that used to take 20 minutes to compute now takes about 10 seconds.
asset back, dry runs on existing large backfills
Performance improvements for backfills of large partition sets.
> Make asset backfill eligibility logic subset-aware instead of iterating through partition keys individually

- python_modules/dagster/dagster/_core/execution/plan/active.py
- python_modules/dagster/dagster/_core/execution/plan/instance_concurrency_context.py
- python_modules/dagster/dagster_tests/core_tests/execution_tests/conftest.py
- python_modules/dagster/dagster_tests/core_tests/execution_tests/test_active.py
- python_modules/dagster/dagster_tests/core_tests/execution_tests/test_instance_concurrency_context.py
- python_modules/dagster/dagster_tests/execution_tests/engine_tests/conftest.py
- python_modules/dagster/dagster_tests/execution_tests/engine_tests/test_step_delegating_executor.py
Previously, op concurrency tags were only used to enforce limits for global op concurrency.
Now, with the introduction of pools, we support an API where pool limits are only enforced at the run level.  This means that we are unnecessarily constraining ops at the op level.
This PR changes the behavior of op execution to no longer require the acquisition of a pool slot if the pool granularity is set for runs.
BK
> Change step execution to be aware of pool granularity

- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_partition_backfill.py
- python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
- python_modules/dagster/dagster/_core/definitions/partition.py
- python_modules/dagster/dagster/_core/execution/asset_backfill.py
- python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py
Clears out the other places in the asset backfill daemon where we were iterating through AssetKeyPartitionKeys, in favor of using AssetGraphSubsets.
BK
NOCHANGELOG
> Remove asset key iteration from backfill daemon, part 2

- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/definitions_component/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/pipes_subprocess_script_collection.py
- python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/test/all_metadata_empty_asset.py
- python_modules/libraries/dagster-components/dagster_components/lib/test/complex_schema_asset.py
- python_modules/libraries/dagster-components/dagster_components/lib/test/simple_asset.py
- python_modules/libraries/dagster-components/dagster_components/lib/test/simple_pipes_script_asset.py
- python_modules/libraries/dagster-components/dagster_components/test/basic_components.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions/local_component_sample/__init__.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions/other_local_component_sample/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg/templates/COMPONENT_TYPE/COMPONENT_TYPE_NAME_PLACEHOLDER.py.jinja
Doing this has a few benefits. The first is that we force people to use ResolvableModel as the base class for their component schemas, which means we're able to inject additional stuff into that class in the future.
The second is that we can create a default `load()` method, which pretty significantly reduces boilerplate for these component types.
NOCHANGELOG
> [components] Enforce that all component schemas are of type ResolvableModel

- python_modules/dagster/dagster/_cli/schedule.py
- python_modules/dagster/dagster/_cli/sensor.py
- python_modules/dagster/dagster_tests/cli_tests/command_tests/test_schedule_commands.py
The schedule and sensor CLI groups both were using an unnecessarily complex scheme where schedule/sensor names were passed as a list but at most one could be used at a time. This was a hack to achieve an optional sensor/schedule argument.
This PR simplifies it to use the `required` field of `click.argument` without changing behavior. It also adds type annotations to the schedule/sensor CLI.
> [cli-refactor] Clean up schedule/sensor CLI args

- docs/docs/guides/build/assets/metadata-and-tags/index.md
As title - the correct flag for this feature is beta, and this is the last place where the experimental partial is used.
> [docs] use beta partial in metadata-and-tags/index.md

- python_modules/dagster/dagster/_cli/debug.py
- python_modules/dagster/dagster/_core/instance/__init__.py
- python_modules/dagster/dagster/_core/storage/legacy_storage.py
- python_modules/dagster/dagster/_core/storage/runs/base.py
- python_modules/dagster/dagster/_core/storage/runs/in_memory.py
- python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py
- python_modules/dagster/dagster_tests/storage_tests/utils/run_storage.py
This was added in https://github.com/dagster-io/dagster/pull/5728
The value of this capability isn't as high as it was then, and the complexity of having snapshot mismatch is greater so lets remove it.
bk
> [run storage] remove snapshot_id override

- scripts/generate_changelog.py
Always have to go delete it, else it is a formatting violation.
> Remove extraneous space at end of Changelog header

- python_modules/dagster/dagster/_core/op_concurrency_limits_counter.py
- python_modules/dagster/dagster_tests/daemon_tests/test_queued_run_coordinator_daemon.py
Fixes the run coordinator limits counter to consider allocated slots for runs that have been in progress for at least 5 seconds.
TBD - looking at why existing tests didn't catch this.
> fix op concurrency limits counter in daemon

- js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/AssetsOverviewRoot.oss.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/LaunchAssetChoosePartitionsDialog.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/useAssetViewParams.test.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/useAssetViewParams.tsx
If you don't provide useQueryPersistedState with a `decode` method, our default coerces boolean and number types (so it's easier to say `useQueryPersistedState<boolean>({queryKey: "enabled"})`).  It looks like the only place in the app we pass a partition as a clean query param is in `useAssetViewParams` and this was the source of the crash. Putting a custom decoder on here resolves the issue.
https://linear.app/dagster-labs/issue/FE-750/bug-error-tpartitionsplit-is-not-a-function-when-viewing
Fixes https://github.com/dagster-io/dagster/issues/26793
I set up this asset and made sure I can view, launch, poke around through all the asset pages, etc. following the changes here. Also wrote new tests!
```
static_partitions_booleans = StaticPartitionsDefinition(["true", "false"]) …
```
> [ui] Fix crash when a partition definitions has boolean partition keys

- examples/deploy_ecs/terraform/README.md
- examples/deploy_ecs/terraform/dagster-code-location/main.tf
- examples/deploy_ecs/terraform/dagster-code-location/outputs.tf
- examples/deploy_ecs/terraform/dagster-code-location/variables.tf
- examples/deploy_ecs/terraform/dagster-deployment/alb.tf
- examples/deploy_ecs/terraform/dagster-deployment/cloudwatch.tf
- examples/deploy_ecs/terraform/dagster-deployment/iam.tf
- examples/deploy_ecs/terraform/dagster-deployment/main.tf
- examples/deploy_ecs/terraform/dagster-deployment/outputs.tf
- examples/deploy_ecs/terraform/dagster-deployment/variables.tf
Adding Terraform code with minimal configuration for Dagster deployment on AWS ECS.
There are 2 modules added: `dagster-deployment` and `dagster-code-location`. 
The first one can be configured to automatically create resources for IAM, CloudWatch logs, and a load balancer. 
I have been using this code to deploy Dagster in my personal AWS account. 
[dagster-aws] added sample Terraform modules for Dagster deployment on AWS ECS
> [dagster-aws] Terraform samples for ECS deployment

- docs/sphinx/sections/api/apidocs/libraries/dagster-azure.rst
- python_modules/libraries/dagster-azure/dagster_azure/blob/__init__.py
- python_modules/libraries/dagster-azure/dagster_azure/blob/resources.py
- python_modules/libraries/dagster-azure/dagster_azure_tests/blob_tests/test_resources.py
Added Azure Blob Storage Resource.
- Tested against real azure storage account. tested all credentials options: SAS token, shared-key, anonymous, default-credentials.
- Added mock-tests.
Add Azure Blob Storage Resource
> Azure Blob Storage Resource

- docs/sphinx/Makefile
- docs/sphinx/_ext/dagster-sphinx/dagster_sphinx/__init__.py
- docs/sphinx/_ext/sphinx-mdx-builder/sphinxcontrib/mdxbuilder/writers/mdx.py
Resolves DOC-653
*Before:*
*After*
`yarn start`
- [docs] Fixed bug where API docs were truncating doc strings for function parameters
> [docs] fix bug in Sphinx API doc build where text is truncate

- python_modules/dagster/dagster_tests/cli_tests/command_tests/test_cli_commands.py
Removes unnecessary and incorrect `working_directory` parameters from test fixtures in CLI command tests. After #27718 this started to be where it was previously ignored, causing test failures.
Verified that all CLI command tests continue to pass without the `working_directory` parameter.
> Fix launch/print tests

- python_modules/libraries/dagster-sigma/dagster_sigma/cli.py
It should have been in https://github.com/dagster-io/dagster/pull/27688 - we will remove experimental warnings [here](https://github.com/dagster-io/dagster/pull/27641) for the API Lifecycle project
> [dagster-sigma] Use beta_warning in sigma_snapshot_command

- helm/dagster/schema/schema_tests/test_instance.py
- helm/dagster/templates/configmap-instance.yaml
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/conftest.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/graphql_context_test_suite.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_data_versions.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sync_run_launcher.py
- python_modules/dagster-graphql/dagster_graphql_tests/test_cli.py
- python_modules/dagster/dagster/_core/instance/ref.py
- python_modules/dagster/dagster/_core/instance_for_test.py
- python_modules/dagster/dagster/_core/run_coordinator/default_run_coordinator.py
- python_modules/dagster/dagster/_core/run_coordinator/immediately_launch_run_coordinator.py
- python_modules/dagster/dagster/_core/run_coordinator/sync_in_memory_run_coordinator.py
- python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py
- python_modules/dagster/dagster_tests/daemon_sensor_tests/conftest.py
- python_modules/dagster/dagster_tests/daemon_sensor_tests/test_run_status_sensors.py
- python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
- python_modules/dagster/dagster_tests/daemon_tests/conftest.py
- python_modules/dagster/dagster_tests/daemon_tests/test_dagster_daemon.py
- python_modules/dagster/dagster_tests/declarative_automation_tests/daemon_tests/test_asset_daemon.py
- python_modules/dagster/dagster_tests/declarative_automation_tests/daemon_tests/test_asset_daemon_failure_recovery.py
- python_modules/dagster/dagster_tests/declarative_automation_tests/daemon_tests/test_e2e.py
- python_modules/dagster/dagster_tests/scheduler_tests/conftest.py
- python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py
- python_modules/libraries/dagster-dask/dagster_dask_tests/test_graphql.py
We want the default instance to support run concurrency features.
Planning on deferring this until the 1.10 branch is cut, but putting up for review now.
BK
- Changed the default run coordinator to be the queued run coordinator
> change default run coordinator to be the queued run coordinator

- python_modules/dagster/dagster/_annotations.py
- python_modules/dagster/dagster/_utils/warnings.py
New API lifecycle annotations should be disabled when using `supress_dagster_warnings` and copyable from an object to another.
> Add new API Lifecycle annotations to disabled_dagster_warnings and copy_annotations

- docs/docs/guides/automate/asset-sensors.md
- docs/docs/guides/automate/declarative-automation/customizing-automation-conditions/arbitrary-python-automation-conditions.md
- docs/docs/guides/build/assets/asset-versioning-and-caching.md
- docs/docs/guides/build/partitions-and-backfills/backfilling-data.md
- docs/docs/guides/deploy/execution/run-monitoring.md
- docs/docs/guides/monitor/logging/index.md
- docs/docs/guides/monitor/logging/python-logging.md
- examples/assets_pandas_type_metadata/notebooks/bollinger.ipynb
- examples/docs_snippets/docs_snippets/deploying/dagster_instance/dagster.yaml
- examples/experimental/sling_decorator/README.md
- python_modules/dagster/dagster/_core/definitions/decorators/schedule_decorator.py
- python_modules/dagster/dagster/_core/definitions/resolved_asset_deps.py
- python_modules/dagster/dagster/_core/definitions/schedule_definition.py
- python_modules/dagster/dagster/_core/instance/__init__.py
As title.
Every remaining occurrence of "experimental" could not be removed:
- referencing "Experimental features" in the UI
- referencing the experimental folder containing dlift, etc.
- referencing external softwares
> Final pass to remove experimental language

- js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx
Related: 
https://linear.app/dagster-labs/issue/FE-775/why-does-the-materialize-button-take-so-long-to-appear
https://dagsterlabs.slack.com/archives/C03CCE471E0/p1738864658944059
Josh observed recently that the Materialize button takes a long time to appear on asset pages - it appears /after/ all of the overview content loads and after all the queries are finished, which is very odd.
There are two things going on:
We were waiting to show the button until we identified the `upstream` assets. This line was added long ago in https://github.com/dagster-io/dagster/pull/8143/files#diff-4364c6a0e68584bc05e5254172348b3bbee4dcf46dcf4c667ecdc10c915a7447R148, when we were passing the upstream assets into the button for one of the pre-flight checks that is run when you click Materialize. We stopped …
> [ui] Show the Materialize button faster when loading asset pages

- js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/AssetCheckDetailDialog.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/AssetCheckExecutionList.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/AssetChecks.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/VirtualizedAssetCheckTable.tsx
- python_modules/dagster-test/dagster_test/toys/asset_checks.py
https://linear.app/dagster-labs/issue/FE-569/add-latest-execution-and-description-to-execution-history-table
Figma: https://www.figma.com/design/irNgXWVRRcoNAItvtPaqOS/Dagster-UI-2024-Q3?node-id=779-2017&t=aCrjpJ4t82kw7CG6-0
- I tested these changes using the asset checks repo in `toys`. I updated the checks to emit descriptions, including a description with a link that validates the rendering is markdown.
[ui] The latest asset check evaluation is shown in the Evaluation History tab, and `AssetCheckResult` descriptions are rendered in the table making it easier to publish a summary of check evaluation.
> [ui] Add Latest Execution and Description to Execution History table

- docs/docs/guides/deploy/deployment-options/running-dagster-locally.md
- python_modules/dagster/dagster/_cli/utils.py
This will make it easier for consumer projects to manage these directories, e.g., add them to `.gitignore` files, with less risk of picking up unintended files.
> use prefix for DAGSTER_HOME temp directory

- docs/docs/etl-pipeline-tutorial/create-and-materialize-a-downstream-asset.md
- docs/docs/etl-pipeline-tutorial/ensure-data-quality-with-asset-checks.md
The text for these two links did not align with the page it took you to.
> [docs] Fix etl-pipeline-tutorial links

- js_modules/dagster-ui/packages/ui-core/src/runs/QueuedRunCriteriaDialog.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedRow.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunsFeedTable.tsx
Fixes the two issues Daniel flagged in https://linear.app/dagster-labs/issue/FE-777/fix-deep-linking-for-concurrency-keys-in-queue-criteria-dialog
Tested against elementl prod which has a few concurrency keys. Opened the queue modal, clicked a link to make sure its fixed, and left the modal open for ~5 minutes to make sure it is not closed when the row disappears from view.
[ui] The queue details modal for a run no longer closes as new runs arrive and links to the correct concurrency page.
> [ui] Fix link to deployment concurrency, stop modal from closing as runs arrive

- python_modules/dagster/dagster/_core/definitions/antlr_asset_selection/antlr_asset_selection.py
- python_modules/dagster/dagster/_core/definitions/asset_selection.py
- python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_tester.py
- python_modules/dagster/dagster/_core/definitions/observe.py
- python_modules/dagster/dagster/_core/definitions/utils.py
- python_modules/dagster/dagster_tests/asset_defs_tests/test_antlr_asset_selection.py
- python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection.py
- python_modules/dagster/dagster_tests/definitions_tests/asset_policy_sensors_tests/test_default_auto_materialize_sensors.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py
This is a whitelist_for_serdes field, and while we can handle the backcompat case through the serdes layer, I don't have conviction that this is a useful change to begin with given that:
- this is a very niche option
- we might want to represent this parameter in a different way in the future anyway (i.e. a separate class or something), so not worth the thrash in the short term
NOCHANGELOG
> Rename `include_external_assets` back to `include_sources`

- python_modules/dagster/dagster/_annotations.py
Tests for docs snippets are failing because we dagster-cloud from pypi, which uses the experimental annotation/decorator.
This PR adds a temp experimental decorator using the beta decorator, to be removed after 1.10 is released - dagster-cloud was updated but changes will be reflected in pypi after the release.
BK + tested locally
> Fix docs snippets test with temp experimental decorator

- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cli/test_scaffold.py
Using `result.stdout` causes problems in BK, see [here](https://buildkite.com/dagster/dagster-dagster/builds/111921#0194f5ea-38cc-4c76-a6d3-b368a249840a), let's use `result.output` instead which fixes the issue.
BK
> [dagster-dbt] Fix tests for dbt scaffold

- python_modules/dagster/dagster/_core/definitions/sensor_definition.py
- python_modules/dagster/dagster_tests/definitions_tests/test_sensor_invocation.py
Fix the error message recommending workaround for the resource generator contextmanager issue
BK
- Fixed the issue where a resource initialization error within a sensor definition test incorrectly recommended using `build_schedule_context` instead of `build_sensor_context`.
> error message resource generator sensor

- python_modules/dagster/dagster/_cli/dev.py
- python_modules/dagster/dagster_tests/cli_tests/command_tests/dagster_dev_command_tests/test_dagster_dev_command.py
Previously I set up the `dagster dev` tests on Windows to manually terminate the full process tree. I did this because I could not get the full tree to terminate on its own from issuing an interrupt event. The theory was that `CTRL_BREAK_EVENT` was not propagating correctly in a windows CI environment due to the process tree not sharing a console.
I think this theory was wrong, and in fact what was happening is that `CTRL_BREAK_EVENT` (aka `SIGBREAK`) does not trigger a `KeyboardInterrupt` exception by default-- instead it just wipes out the process. The logic that handles graceful shutdown of the process tree relies on a `KeyboardException` being triggered.
This PR sets up the correct signal handling in `dagster dev` for `SIGBREAK` to trigger a `KeyboardInterrupt`. This causes the full …
> Properly set up SIGBREAK handling for dagster dev on windows

- docs/vercel.json
Add additional redirect for https://docs.dagster.io/integrations/airlift/tutorial/migrate to 
https://docs.dagster.io/integrations/libraries/airlift/airflow-to-dagster/
> Update Airlift Migrate Redirect on docs

- .github/workflows/build-docs.yml
- .github/workflows/vale.yml
Updates Vale and docs build GH actions:
- Vale: don't run on draft PRs
- Docs build: trigger when examples/docs_snippets, examples/docs_projects, examples/getting_started_etl_tutorial, and examples/airlift-migration-tutorial are updated, since code in these directories is referenced in docs.
> Update Vale and docs build GH actions

- python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
If the selector is not passed via graphql, we currently raise a builtin assertion error, but lets handle that explicitly and throw a `DagsterInvariantViolationError` instead
> PLA-957 explicitly handle empty graph selector

- js_modules/dagster-ui/packages/ui-core/src/graph/KindTags.tsx
- js_modules/dagster-ui/packages/ui-core/src/search/links.tsx
- js_modules/dagster-ui/packages/ui-core/src/search/useGlobalSearch.tsx
The link utilities are used broadly across the app which causes a circular dependency for our filtering utilities because they depend on KingTags.tsx which uses one of those link utilities which ends up in a circular dependency with our CatalogViewProvider in cloud.
bk
> Move utilities out of useGlobalSearch to avoid circular dependency.

- python_modules/dagster/dagster/_core/definitions/asset_dep.py
- python_modules/dagster/dagster/_core/definitions/asset_spec.py
- python_modules/dagster/dagster/_record/__init__.py
- python_modules/dagster/dagster_tests/definitions_tests/test_asset_spec.py
- python_modules/dagster/dagster_tests/general_tests/test_record.py
Prior to these changes, both added tests would fail. Updated AssetSpec to be an `@record` so that it could take advantage of these changes.
The core issue is that the pydantic internals assume that all namedtuple subclasses can be instnatiated with positional args based on their fields, which is not the case for records, which are kw-only (and is not the case for explicit NamedTuple subclasses which define `__new__`).
This was the least-gross way I could find to handle this behavior, and in reality is not particularly invasive to the `record` framework (import is deferred, just a single extra attribute)
NOCHANGELOG
> [record] Fix handling of record classes with pydantic

- js_modules/dagster-ui/packages/ui-core/src/instance/InstanceConcurrencyKeyInfo.tsx
Starting with `1.10.0`, the queued run coordinator treats unspecified granularity as run granularity.
BK
> swap the default granularity displayed

- docs/CONTRIBUTING.md
- docs/docs/getting-started/concepts.md
- docs/docs/guides/automate/asset-sensors.md
- docs/docs/guides/build/assets/defining-assets.md
Applying the same color palette to the other mermaid diagrams to match concepts page. Not as profound of a difference as expected:
**Before**
**After**
Leaving the stateDiagram in `asset-sensors` the same since that already had custom colors set
> [docs] Standardize mermaid diagrams palette

- python_modules/dagster/dagster/_core/remote_representation/code_location.py
- python_modules/dagster/dagster/_core/remote_representation/grpc_server_registry.py
- python_modules/dagster/dagster/_core/remote_representation/origin.py
- python_modules/dagster/dagster/_core/workspace/context.py
- python_modules/dagster/dagster_tests/daemon_tests/test_queued_run_coordinator_daemon.py
- python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_grpc_server_registry.py
This is causing issues when using the proxy server entrypoint because we set a fixed server ID (the value of which the frontend uses when deciding whether to reload information from the backend) and then don't update it when the underlying code server process changes. Instead, just rely on the code servers themselves to tell us what the underlying server ID is, which will automatically be updated correctly in both entrypoints when the process is reloaded.
Existing test coverage 
Load definitions in dagster dev with one resource, add a second resource, reload definitions in the UI
Before: server ID is fixed and does not update, so the frontend doesn't update either
Now: server ID changes, and frontend updates
Fixed an issue where when using `dagster dev`, some changes were not reflected in …
> Remove fixed-server-id tracking from grpcserverregistry

- python_modules/libraries/dagster-components/dagster_components/__init__.py
- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/base.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py
- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/definitions_component/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/pipes_subprocess_script_collection.py
- python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components/test/basic_components.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions/local_component_sample/__init__.py
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/custom_scope_component/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/custom_scope_component/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_model.py
This subjectively feels the best out of the options so far.
By making Component a BaseModel, we avoid needing to create a completely separate class to encode the types of individual resolved fields. This also means we get pydantic's type checking for free on Component class, and we have the option of auto-generating the schema for simple cases in the future if we so desire.
I don't include the code to do this in this PR, but it'd be fairly straightforward to automatically validate that a given Component class actually matches up with the data provided by its resolved schema.
This is also just about as terse as it's ever been.
NOCHANGELOG
> [components] Component is a BaseModel, add field_resolver

- js_modules/dagster-ui/packages/ui-core/src/instance/ConcurrencyTabs.tsx
- js_modules/dagster-ui/packages/ui-core/src/instance/InstanceConcurrency.tsx
Put pools more prominently on the concurrency page
Inspection, loaded dagit.
> rearrange tabs for concurrency page

- js_modules/dagster-ui/packages/ui-core/src/app/GraphQueryImpl.ts
- js_modules/dagster-ui/packages/ui-core/src/app/__tests__/GraphQueryImpl.test.ts
Now here's a long-standing one! The traversal code used to navigate the asset graph for `asset++` was doing depth-first and not breadth-first search, which meant an asset connected via multiple paths of varying length might not be included in the result.  This is important for the lineage view because under the hood, because a filter of "Distance: 3" might not include an asset that is connected via both distance=4 and distance=3 paths
https://linear.app/dagster-labs/issue/FE-779/lineage-ui-bug-displaying-upstream-assets-assigned-to-ui-team
I added new tests and also manually verified the specific case in the ticket is resolved.
[ui] The traversal operators on the asset graph (`asset++`) correctly include assets connected to the target asset by paths of varying distance.
> [ui] Switch graph traversal operators to BFS to ensure shortest path is used

- docs/sphinx/sections/api/apidocs/libraries/dagster-mysql.rst
- python_modules/libraries/dagster-mysql/dagster_mysql/__init__.py
- python_modules/libraries/dagster-mysql/dagster_mysql/resources.py
- python_modules/libraries/dagster-mysql/dagster_mysql_tests/test_resources.py
Add MySQLResource, wrapping `mysql.connector.connect`.
Similar to the other tests in the dagster-mysql module, wrote unit-tests against a real local mysql instance.
Added MySQLResource.
> Add MySQL Resource

- docs/sphinx/sections/api/apidocs/libraries/dagster-aws.rst
- python_modules/libraries/dagster-aws/dagster_aws/rds/__init__.py
- python_modules/libraries/dagster-aws/dagster_aws/rds/resources.py
- python_modules/libraries/dagster-aws/dagster_aws_tests/conftest.py
- python_modules/libraries/dagster-aws/dagster_aws_tests/rds_tests/test_resources.py
Added dagster resource to wrap  [AWS-RDS](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds.html), and [AWS-RDS-DATA](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds-data.html), under dagster_aws.rds.
- Tested locally with a real AWS RDS Instance (both the management, and data APIs).
- Wrote unit-tests with moto (mock boto) library.
Added AWS RDSResource
> Add AWS RDS Resource

- python_modules/dagster/dagster/_core/instance/config.py
- python_modules/dagster/dagster/_core/run_coordinator/queued_run_coordinator.py
- python_modules/dagster/dagster_tests/daemon_tests/test_queued_run_coordinator_daemon.py
Turns on the concurrency run-blocking by default... previously, since we didn't want to change behavior in a minor release, we used configuring a `pool` setting as a proxy for it.  That's no longer needed since this is for a major release and we should just change the behavior.
BK
* Turns on run-blocking for concurrency keys / pools by default.  For op granularity, runs are dequeued if there exists at least one op that can execute once the run has started.  For run granularity, runs are dequeued if all pools have available slots.
> turn on the op concurrency counter for the run queue by default

- python_modules/libraries/dagster-components/setup.cfg
- python_modules/libraries/dagster-dg/setup.cfg
Ignore `CHANGELOG.md` in the `dagster-components` and `dagster-dg` `MANIFEST.in` files.
Ran `check-manifest` locally
> Ignore CHANGELOG.md in components/dg MANIFEST.in

- docs/docs/guides/preview/components/creating-a-component.md
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/defining-resolver.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/resolving-resolvable-field.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-build-defs.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-config-schema.py
- python_modules/libraries/dagster-components/dagster_components/__init__.py
- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/base.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/context.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py
- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/definitions_component/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/pipes_subprocess_script_collection.py
- python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/test/complex_schema_asset.py
- python_modules/libraries/dagster-components/dagster_components/test/basic_components.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions/local_component_sample/__init__.py
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/custom_scope_component/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/custom_scope_component/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_model.py
- python_modules/libraries/dagster-dg/dagster_dg/templates/COMPONENT_TYPE/COMPONENT_TYPE_NAME_PLACEHOLDER.py.jinja
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils_tests/test_sample_yaml.py
This is (hopefully) the final change on the core engine side of the world
Now when we resolve from a ResolvableSchema, we check the target type to see if it has any `@field_resolvers` defined. If so, we invoke those methods when resolving into those fields. If not, we just do the basic `context.resolve_value()` on the given field. To handle cases where we don't want to modify the target type (e.g. AssetSpec), we can define a special class on the schema itself, called FieldResolvers. This bit is subject to change as for now this is an internal-only construct (i.e. users will not immediately need to do this sort of thing, so we can work out other options).
NOCHANGELOG
> [components] Update resolution engine, @field_resolver

- docs/docs/guides/preview/components/creating-a-component.md
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/19-dg-component-type-info.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-build-defs.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-class-defined.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-custom-scope.py
- python_modules/libraries/dagster-components/CHANGELOG.md
- python_modules/libraries/dagster-components/MANIFEST.in
- python_modules/libraries/dagster-components/dagster_components/__init__.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/base.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py
- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/pipes_subprocess_script_collection.py
- python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/cli_tests/test_commands.py
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_model.py
- python_modules/libraries/dagster-dg/MANIFEST.in
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_type_commands.py
This adds support for a more terse method of defining field resolvers which avoids creating explicit decorators and updates all internal usage to use this pattern (as well as the docs).
NOCHANGELOG
> [components] Add support for Annotated[type, FieldResolver]

- examples/docs_beta_snippets/docs_beta_snippets/integrations/fivetran/customize_fivetran_asset_defs.py
- examples/docs_beta_snippets/docs_beta_snippets/integrations/fivetran/fetch_column_metadata_fivetran_assets.py
Add missing / implied `Definition` to an example code snippet for adding column-level metadata to a Fivetran asset. This makes it so users can copy-paste the code snippet into their Dagster project and use it without needing to add the `Definition` themselves.
Also adds some comments to make it clear where a user needs to replace placeholder with real value for Fivetran connector id.
- Set up a Fivetran connector
- Set up new Dagster project
- Copy the example into `definitions.py`, replacing values as specified.
- Run `dagster dev`, verify no errors
- Verify the Fivetran asset has column-level metadata
> Fix code snippets in Fivetran integration docs

- python_modules/libraries/dagster-dg/dagster_dg/cli/component_type.py
- python_modules/libraries/dagster-dg/dagster_dg/docs.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_type_commands.py
I selfishly want this functionality for e2e tests, but I also think users might find it helpful
> [dg] Add option to output html docs to file instead of tmpfile/browser

- python_modules/libraries/dagster-airlift/dagster_airlift/core/load_defs.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/sensor/sensor_builder.py
Allow changing the default sensor status of the Airflow sensor. Right now it's always running.
- [dagster-airlift] The polling sensor can now be configured "off" by default using the `default_sensor_status` param.
> Default sensor status

- python_modules/libraries/dagster-airlift/dagster_airlift/core/airflow_instance.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/load_defs.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/sensor/sensor_builder.py
- python_modules/libraries/dagster-airlift/dagster_airlift/test/airflow_test_instance.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink_tests/integration_tests/test_api.py
Properly handle batched runs in the airlift sensor.
Previously, we were always stopping after the first batch. Now, we re-run the request until we're out of runs.
Tested on mwaa instance with 500 runs + new unit tests.
- [dagster-airlift] fixed a bug when handling large batches of dag runs at once.
> [dagster-airlift] properly handle dag run batching

- .buildkite/dagster-buildkite/dagster_buildkite/cli.py
- .buildkite/dagster-buildkite/dagster_buildkite/pipelines/prerelease_dg.py
- .buildkite/dagster-buildkite/setup.py
- scripts/build_and_publish_dg_and_components.sh
Makes a variant of the single package ad-hoc release script for dg and components, to release in lock-step.
https://buildkite.com/dagster/publish-dagster-dg-and-dagster-components/builds/1
> [bk] add build-and-release script to lock-step release dg and components

- python_modules/dagster/dagster/_daemon/asset_daemon.py
- python_modules/dagster/dagster_tests/declarative_automation_tests/daemon_tests/definitions/always_evaluates.py
- python_modules/dagster/dagster_tests/declarative_automation_tests/daemon_tests/definitions/defs_with_source_assets.py
- python_modules/dagster/dagster_tests/declarative_automation_tests/daemon_tests/test_e2e.py
Summary:
Prevents an issue where a source asset targeted by one sensor could incorrectly trigger the actual materializable asset key from another code location.
Fixed an issue where Declarative Automation sensors in code locations that included source assets referencing assets with automation conditions in other code locations would sometimes cause duplicate runs to be created.
> use repo-scoped asset graph when deciding whether or not a given asset key is eligible for a given sensor

- docs/docs/guides/operate/managing-concurrency.md
- js_modules/dagster-ui/packages/ui-core/src/instance/InstanceConcurrencyKeyInfo.tsx
- python_modules/dagster/dagster/_core/execution/plan/active.py
- python_modules/dagster/dagster/_core/execution/plan/instance_concurrency_context.py
- python_modules/dagster/dagster/_core/op_concurrency_limits_counter.py
- python_modules/dagster/dagster_tests/core_tests/execution_tests/test_active.py
- python_modules/dagster/dagster_tests/core_tests/execution_tests/test_instance_concurrency_context.py
Because switching the enforcement granularity in cloud is a host-cloud process, this is a big change.  This walks back some of the concurrency defaults to be in line with current behavior
BK
> change the defaults of the pool granularity back to `op`

- examples/docs_beta_snippets/docs_beta_snippets/integrations/sling.py
Sling won't find the keys otherwise, e.g.:
```python
2025-02-12 14:51:21 -0700 - dagster - ERROR - __ASSET_JOB - a73dbc0a-8b73-4d72-adde-1955ff7b825f - 23923 - my_sling_assets - STEP_FAILURE - Execution of step "my_sling_assets" failed.
dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "my_sling_assets"::
Exception: 2:51PM INF Sling CLI | https://slingdata.io
fatal:
~ Error parsing replication config
did not find 'source' key
Sling command failed
Stack Trace:
File "/Users/deepyaman/github/dagster-io/dogfood-sling/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
yield
File "/Users/deepyaman/github/dagster-io/dogfood-sling/.venv/lib/python3.12/site-packages/dagster/_utils/__init__.py", …
```
> [dagster-sling] Fix replication key capitalization

- js_modules/dagster-ui/packages/ui-core/src/instance/InstanceBackfills.tsx
We'll ship this in next week's release:
and then merge this PR to remove the page for the March 6th release:
https://github.com/dagster-io/dagster/pull/27811
[ui] The Instance Backfills page is being removed in the upcoming March 6 release in favor of the new Runs > Backfills view.
> [ui] Update the Backfills page sunset banner

- python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_job_partitions.py
- python_modules/dagster/dagster/_core/remote_representation/external.py
This resolver was failing if all the assets were unpartitioned.
New test case
Fixed an issue where a "Message: Cannot return null for non-nullable field PartitionKeys.partitionKeys." error was raised in the launchpad for jobs with unpartitioned assets.
> Fix partitionKeysOrError for asset jobs with just unpartitioned assets

- azure-pipelines.yml
- python_modules/libraries/dagster-dg/dagster_dg/cache.py
- python_modules/libraries/dagster-dg/dagster_dg/completion.py
- python_modules/libraries/dagster-dg/dagster_dg/config.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg/utils/editor/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/component_command_tests/test_component_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_code_location_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_type_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_custom_help_format.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_dev_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_install_completion.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
- python_modules/libraries/dagster-dg/tox.ini
`dagster-dg` is currently broken on Windows. I found this out by trying to add Windows testing. This PR fixes `dg` for Windows and adds Windows testing.
- Modify our azure pipeline specification to also test `dagster-dg`.
- Make sure all paths are handled with `Path` and don't contain embedded "/"
- Handle process shutdown appropriately on Windows for `dg dev`
- Some adjustments to the tests of console output, since sometimes the box character used to draw tables and panels differ on Windows.
NOTE: There are still some problems with `dg dev` testing in the CLI environment on Windows, so the `dg dev` tests are skipped in this PR. They will be re-added upstack.
Test suite now passes on Windows.
> [components] Add windows testing to dagster-dg (BUILD-672)

- python_modules/libraries/dagster-dg/dagster_dg/cli/component_type.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_type_commands.py
Added a new `--json` flag to the `component-type list` command, allowing users to output component type information in JSON format instead of the default table view. This enables easier programmatic consumption of component type data.
- Added a new test case `test_component_type_list_json_succeeds` that verifies the JSON output format
> [components] Add --json flag for dg component-type list

- python_modules/libraries/dagster-airlift/dagster_airlift/constants.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/airflow_instance.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/dag_asset.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/load_defs.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/sensor/sensor_builder.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/serialization/compute.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/serialization/serialized_data.py
- python_modules/libraries/dagster-airlift/dagster_airlift/test/airflow_test_instance.py
- python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/airflow_instance.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink_tests/integration_tests/test_api.py
By default, when over a certain number of DAGs, switch to not retrieving source code. I also make this default state overridable for users who determine that the tradeoff is worth it.
Similar to the downstack, this significantly speeds up initial load, for 200 dags from 50s down to 20-odd seconds.
Additional tests changing the default scaling limits and ensuring that they are respected.
> Handle source code scaling

- python_modules/libraries/dagster-airlift/dagster_airlift/constants.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/airflow_instance.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/dag_asset.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/load_defs.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/sensor/sensor_builder.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/serialization/compute.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/serialization/serialized_data.py
- python_modules/libraries/dagster-airlift/dagster_airlift/test/airflow_test_instance.py
- python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_airflow_asset_mapping.py
- python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py
- python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_sensor.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/airflow_instance.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink_tests/integration_tests/test_api.py
Changes airlift internals to only make expensive dag-level calls for task info when absolutely necessary. 
This speeds up initial load significantly. For 200 dags, 90s -> 50s.
- [dagster-airlift] fixed some scaling issues which were causing slow initial load times for code locations including dagster-airlift code.
> only retrieve task-level info for mapped dags

- python_modules/libraries/dagster-airlift/dagster_airlift/constants.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/airflow_instance.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/dag_asset.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/load_defs.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/sensor/sensor_builder.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/serialization/compute.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/serialization/serialized_data.py
- python_modules/libraries/dagster-airlift/dagster_airlift/test/airflow_test_instance.py
- python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_airflow_asset_mapping.py
- python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py
- python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_sensor.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/airflow_instance.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/dagster_defs/automapped_defs.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/dagster_defs/mapped_defs.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/dagster_defs/observation_defs.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/dagster_multi_code_locations/first_dag_defs.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/dagster_multi_code_locations/second_dag_defs.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink_tests/integration_tests/test_api.py
Make the default sensor interval way slower. 1 second is incredibly aggressive for real life use cases.
Existing tests
- [dagster-airlift] The default sensor interval on the airflow polling sensor has been brought down to 30 seconds.
> Change default sensor interval

- python_modules/libraries/dagster-airlift/dagster_airlift/constants.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/airflow_instance.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/dag_asset.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/load_defs.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/sensor/sensor_builder.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/serialization/compute.py
- python_modules/libraries/dagster-airlift/dagster_airlift/core/serialization/serialized_data.py
- python_modules/libraries/dagster-airlift/dagster_airlift/test/airflow_test_instance.py
- python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_airflow_asset_mapping.py
- python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py
- python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_sensor.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/airflow_instance.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/dagster_defs/automapped_defs.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/dagster_defs/mapped_defs.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/dagster_defs/observation_defs.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/dagster_multi_code_locations/first_dag_defs.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/dagster_multi_code_locations/second_dag_defs.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink_tests/integration_tests/test_api.py
List dags API on `AirflowInstance` currently only retrieves the first batch of results. Change to receive all batches.
New API test, ensured that live load works across multiple batches.
- [dagster-airlift] previously, if there were over the limit of dags retrieved in a single batch within the Airflow instance, we would not retrieve them all. This has been fixed.
> Make list dags batchable

- python_modules/dagster/dagster/_core/op_concurrency_limits_counter.py
- python_modules/dagster/dagster_tests/daemon_tests/test_queued_run_coordinator_daemon.py
Fix run blocking with unconfigured keys to fail open
tests
> only fetch the concurrency info for configured keys

- python_modules/dagster/dagster_tests/daemon_tests/test_queued_run_coordinator_daemon.py
When we switched back the default granularity to op, this test needed to change but didn't.
The bug fixed in https://github.com/dagster-io/dagster/pull/27853 masked the test breakage.
BK
> fix broken test

- js_modules/dagster-ui/packages/ui-core/src/asset-selection/input/AssetSelectionInput.oss.tsx
- js_modules/dagster-ui/packages/ui-core/src/asset-selection/input/util.ts
- js_modules/dagster-ui/packages/ui-core/src/gantt/GanttChartSelectionInput.tsx
- js_modules/dagster-ui/packages/ui-core/src/gantt/useGanttChartSelectionAutoCompleteProvider.tsx
- js_modules/dagster-ui/packages/ui-core/src/pipelines/OpGraphSelectionInput.tsx
- js_modules/dagster-ui/packages/ui-core/src/pipelines/useOpGraphSelectionAutoCompleteProvider.tsx
- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionAutoCompleteProvider.tsx
- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInput.tsx
- js_modules/dagster-ui/packages/ui-core/src/selection/__tests__/createSelectionLinter.test.ts
- js_modules/dagster-ui/packages/ui-core/src/selection/createSelectionLinter.ts
Recently we consolidated all of our asset selection grammars (branch deployment, OSS, Cloud) into just a single grammar in OSS that includes the attributes of all the grammars combined. This is to allow the AssetSelection parser in python to to parse strings from the UI and store/transport them to the UI, but also so that we can throw custom error messages rather than returning the default Antlr error which isn't very human friendly.
Used this in OSS / Branch Deployments / Cloud / Alerts
> [Selection syntax] Add custom error messages for invalid attributes.

- python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
- python_modules/dagster/dagster/_daemon/asset_daemon.py
- python_modules/dagster/dagster_tests/declarative_automation_tests/daemon_tests/test_e2e.py
Ensures that if you inadvertently have the same asset key in two code locations, each with a DA sensor, that we don't create duplicate runs.
New test case
Fixed an issue where if two separate code locations defined the same asset key with an automation condition, duplicate runs could be created by Declarative Automation.
> Only launch a single run in DA from keys that are materializable and part of multiple repositories when using DA sensors

- js_modules/dagster-ui/packages/ui-core/client.json
- js_modules/dagster-ui/packages/ui-core/src/runs/QueuedRunCriteriaDialog.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/QueuedRunCriteriaQuery.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/types/QueuedRunCriteriaQuery.types.ts
Instead of referencing root concurrency keys, we should reference pools and use the pool tags component.
Inspection
- Changed the queue criteria dialog to reference pools instead of concurrency keys
> update queue criteria to use pool terminology

- python_modules/dagster-webserver/dagster_webserver/cli.py
- python_modules/dagster/dagster/_cli/dev.py
- python_modules/dagster/dagster/_daemon/cli/__init__.py
- python_modules/dagster/dagster/_serdes/ipc.py
- python_modules/dagster/dagster_tests/cli_tests/command_tests/dagster_dev_command_tests/test_dagster_dev_command.py
- python_modules/dagster/dagster_tests/cli_tests/test_shutdown_pipe.py
- python_modules/dagster/tox.ini
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_dev_command.py
`dagster dev` spins up webserver and daemon subprocesses. Currently, on being interrupted,  it attempts to shutdown those processes by sending an interrupt signal to each of them.
This is an unreliable mechanism for shutting down subprocesses on Windows, because the ability of one process to signal another process is dependent on them sharing a console. This is a particularly unreliable condition in a CI environment. Quoting ChatGPT:
>On Windows, CTRL_BREAK_EVENT (and similarly CTRL_C_EVENT) only works when the calling process and the target processes share a console. By default, Python’s subprocess.Popen with CREATE_NEW_PROCESS_GROUP spawns the child into its own new process group but does not automatically attach it to the same console as the parent (and in many CI environments, there …
> Switch dagster dev IPC mechanism to pipe from signal

- python_modules/dagster/dagster/_annotations.py
dagster-cloud has been released with the API lifecycle fixes with 1.10. We can remove the temp experimental annotation.
BK
> Remove temp experimental annotation

- python_modules/libraries/dagster-fivetran/dagster_fivetran/translator.py
Connector URL was previously broken - it should use only the connector ID, not the service and table names. It is now updated.
Manually tested in Dagster and Fivetran
> [dagster-fivetran] Fix connector url in FivetranConnector

- python_modules/libraries/dagster-components/dagster_components/test/test_cases.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/validation/basic_component_extra_top_level_value/component.yaml
- python_modules/libraries/dagster-dg/dagster_dg/cli/check_utils.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/component.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/component_command_tests/test_check.py
Sets `additionalProperties` to `False` on the top-level component file decl schema, ensuring we error on `dg component check` when extra top-level fields are provided.
Also improves extra field errors to point to the offending field instead of its parent, which `jsonschema` points to by default.
```sh
dg component check
/Users/ben/repos/components_demo/my-deployment/code_locations/jaffle-platform/jaffle_platform/components/defs_example/component.yaml:6 - asset_attributes Additional properties are not allowed ('asset_attributes' was unexpected)
| 
1 | type: definitions@dagster_components
2 | 
3 | params:
4 |   definitions_path: definitions.py
5 | 
6 | asset_attributes: foo
| ^ Additional properties are not allowed ('asset_attributes' was unexpected)
| 
```
New test case.
> [BUILD-706][dg components check] Error on extra top-level keys, better extra param errors

- python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py
- python_modules/dagster/dagster_tests/general_tests/compat_tests/test_back_compat.py
Makes the code safe even on unmigrated instances
https://github.com/dagster-io/dagster/issues/27876
BK
- Fixes the `psycopg2.errors.UndefinedColumn` database error when trying to set a concurrency key without first having run `dagster instance migrate`
> fix database error in setting concurrency key

- python_modules/dagster/dagster/_core/asset_graph_view/bfs.py
- python_modules/dagster/dagster/_core/definitions/asset_graph_subset.py
- python_modules/dagster/dagster/_core/execution/asset_backfill.py
- python_modules/dagster/dagster_tests/asset_defs_tests/asset_graph_view_tests/test_bfs.py
- python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py
Summary:
AssetGraphSubset.empty() returns an empty subset. What we wanted here was a boolean that tells you whether the subset was empty. This was (in master) causing asset backfills to always log that there was nothing to request, even if they then went on to request things
Test Plan:
New test case, Launch an asset backfill and view the logs, verify that output now includes the asset partitions being requested.
> Fix asset backfill subset logging

- python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py
- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/definitions_component/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/pipes_subprocess_script_collection.py
- python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
Drops in a bunch of Pydantic field description metadata to most of our core components.
Switches to using Pydantic dataclasses - sadly `dataclasses.field` does not have a description field. I don't think perf will be meaningfully different.
Existing unit tests, test schema hinting locally.
> [dagster-components] Layer field descriptions into built-in components

- js_modules/dagster-ui/packages/ui-core/src/instance/PoolTag.tsx
Pools no longer accept `/` characters, but for back-compat for op tags, we should fix the pool tag links.
BK
https://github.com/user-attachments/assets/bccf77be-6874-4031-add6-3d8d185549cf
- Fixed concurrency link escaping in the `View queue criteria` dialog
> fix escaping in pool tag link

- docs/README.md
- docs/docusaurus.config.ts
* Adds conditional logic for displaying the versioned drop down menu in production releases and local development.
* Adds explanation of this to the README
https://vercel.com/docs/projects/environment-variables/system-environment-variables#VERCEL_ENV
Confirmed drop down menu displays correctly with these commands:
```
yarn start  # shows dropdown
```
```
VERCEL_ENV=production yarn start  # shows dropdown
```
```
VERCEL_ENV=preview yarn start  # shows "Latest version"
```
NOCHANGELOG
> [docs] make version dropdown conditional on preview deployments

- python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
- python_modules/dagster/dagster/_core/workspace/context.py
The full context is designed around serving the current live deployment, but if we want to be able to represent base deployments at a specific point and time we need more constrained target. Opted for the asset graph in this case. 
bk
> [branch deployments] change from base context to base asset graph

- python_modules/dagster/dagster/_core/execution/asset_backfill.py
Summary:
The output already lists the subset in a more readable way, so don't include the __repr__ version as well.
Test Plan:
Launch a backfill, old failure reason:
```
The following assets were considered for materialization but not requested:
- multi_partitions: {3|c, 1|a, 2|a, 1|b, 2|c, 2|b, 1|c, 3|b, 3|a}
Reason: EntitySubset<AssetKey(['multi_partitions'])>(DefaultPartitionsSubset(subset={'3|c', '1|a', '2|a', '1|b', '2|c', '2|b', '1|c', '3|b', '3|a'})) already requested by backfill
```
New failure reason:
```
The following assets were considered for materialization but not requested:
- multi_partitions: {3|c, 1|a, 2|a, 1|b, 2|c, 2|b, 1|c, 3|b, 3|a}
Reason: Already requested by backfill
```
> Clean up asset backfill failure reasons a bit

- js_modules/dagster-ui/packages/ui-components/src/components/TextInput.tsx
I noticed that disabled text inputs have a hover state in which the box-shadow changes color. I don't think it should, so I'm removing it.
Hover on disabled text input, verify that the box shadow doesn't change color.
> [ui] Remove hover style on disabled text input

- docs/Makefile
- docs/README.md
- docs/docs/about/contributing.md
- docs/package.json
- docs/scripts/vercel-sync-api-docs.sh
* Deprecated `make mdx` and `make mdx-copy` for `yarn build-api-docs`.
* Update README and CONTRIBUTING to reference new directive
- Ran `yarn build-api-docs` locally ✅ 
- Confirmed execution in Vercel ✅ 
NOCHANGELOG
> [docs] add `yarn build-api-docs` directive

- helm/dagster/schema/schema/charts/dagster/subschema/webserver.py
- helm/dagster/schema/schema_tests/test_dagit.py
- helm/dagster/templates/helpers/_helpers.tpl
- helm/dagster/values.schema.json
- helm/dagster/values.yaml
- python_modules/dagster-webserver/dagster_webserver/cli.py
- python_modules/dagster/dagster/_core/instance/__init__.py
- python_modules/dagster/dagster/_core/storage/event_log/base.py
- python_modules/dagster/dagster/_core/storage/legacy_storage.py
- python_modules/dagster/dagster/_core/storage/runs/base.py
- python_modules/dagster/dagster/_core/storage/schedules/base.py
- python_modules/libraries/dagster-mysql/dagster_mysql/event_log/event_log.py
- python_modules/libraries/dagster-mysql/dagster_mysql/run_storage/run_storage.py
- python_modules/libraries/dagster-mysql/dagster_mysql/schedule_storage/schedule_storage.py
- python_modules/libraries/dagster-mysql/dagster_mysql_tests/test_instance.py
- python_modules/libraries/dagster-mysql/dagster_mysql_tests/test_wait_timeout.py
- python_modules/libraries/dagster-postgres/dagster_postgres/event_log/event_log.py
- python_modules/libraries/dagster-postgres/dagster_postgres/run_storage/run_storage.py
- python_modules/libraries/dagster-postgres/dagster_postgres/schedule_storage/schedule_storage.py
- python_modules/libraries/dagster-postgres/dagster_postgres_tests/test_instance.py
Aims to fix issue #26400 where the QueuePool used by PostgresEventLogStorage overflows when manually launching a materialisation of a big number of assets.
The root cause seems to be the graphql client in the webserver launching multiple queries to fetch/update status of the many assets. It causes a spike in connections which overflows the pool.
Both `PostgresRunStorage` and `PostgresScheduleStorage` share the same default pool config. I chose not to change anything as we didn't experience any issues with those.
Vendored dagster-postgres into our Dagster project. Launching manual materializations of 2000+ assets works, despite being quite slow.
Removed the cap on PostgresEventLogStorage QueuePool by setting max_overflow to -1 (see SQLAlchemy …
> [dagster-postgres] Fix QueuePool overflow

- python_modules/dagster/dagster/_core/definitions/job_definition.py
Noticed it wasn't rendering properly:
> Fix malformed docstring for `execute_in_process()`

- python_modules/libraries/dagster-dg/dagster_dg/cli/code_location.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/dev.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_code_location_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_custom_help_format.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/test_cache.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Our executable resolution story has gotten more complicated since explicit venv resolution was added in #27799. This PR refactors the way we resolve executables, getting rid of some standalone utility methods and making everything flow through the new `DgContext.resolve_executable`. In the process, we also fix a bug in executable resolution in the `dg dev` command run from a deployment, where the executable was being resolved with the wrong root directory, leading to `error: No project detected in pyproject.toml` warnings messages.
Existing test suite, observed warning messages went away.
> [components] Make all executable resolution flow through DgContext (BUILD-712)

- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/utils.py
- python_modules/libraries/dagster-components/dagster_components_tests/registry_tests/test_registry.py
- python_modules/libraries/dagster-components/dagster_components_tests/utils.py
- python_modules/libraries/dagster-components/setup.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_component_type_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Currently if there is an error when loading a `dagster-components` entry point, the whole process terminates unceremoniously with an ugly error.
This PR changes this behavior:
Entry points are loaded in a try-catch block. We wrap any error when loading in a `ComponentsEntryPointLoadError`. This and the backtrace flow up to the output of the instigating `dg` command, which then caps it off with a clean error message about the `dagster-components` command failing.
This has the two keys properties of being debuggable and _ending_ the output with a clear error message.
New unit test and manually (running `dg component-type list` in an env with a bad entry point).
> [components] Better error message for failing entry points (BUILD-647)

- python_modules/dagster/dagster/_core/execution/asset_backfill.py
- python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py
We were including failed partitions in both the in progress list and the failed list. Now we aren't.
Test Plan:
Launch a backfill that fails an asset, view backfill log output
New test case
Fixed an issue where asset backfills included failed partitions in the in-progress list in logging output.
> Exclude failed subset when logging "Assets requested or in progress" in asset backfills

- js_modules/dagster-ui/packages/ui-core/src/ui/MarkdownWithPlugins.tsx
Adding the ignoreMissing flag as recommended here: https://github.com/orgs/remarkjs/discussions/1013
Attempted first to upgrade rehype + react-markdown but saw an error so backed that out for now. Did not investigate deeply.
Loaded a asset page that was previously crashing:
after:
[ui] Fixed an issue that caused markdown with code blocks in languages not supported for syntax highlighting to crash the page.
> [Markup] Ignore missing language errors

- python_modules/dagster/dagster/_core/definitions/partition_mapping.py
- python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_asset_partition_mappings.py
Similar to https://github.com/dagster-io/dagster/pull/27681 but for upstream traversal instead of downstream traversal. Haven't found any actual problems that this was causing yet, but was just looking for other places we might not be setting current_time correctly since other similar issues were causing bugs.
New test case that was failing before
NOCHANGELOG
> Add one more missing current_time callsite in IdentityPartitionMapping

- docs/docs/guides/build/assets/asset-versioning-and-caching.md
Just fixing a small typo on https://docs.dagster.io/guides/build/assets/asset-versioning-and-caching
`multipled_number` -> `multiplied_number`
I didn't.
> docs: Update typo in `asset-versioning-and-caching.md`

- docs/docs/guides/build/assets/metadata-and-tags/index.md
Fix a broken link in the [Asset Metadata](https://docs.dagster.io/guides/build/assets/metadata-and-tags) page.
[Local development and build](https://github.com/dagster-io/dagster/tree/master/docs#local-development)
Before:
After:
> [docs] fix metadata docs link

- python_modules/dagster-graphql/dagster_graphql/implementation/execution/__init__.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_run_cancellation.py
Summary:
This mutation can fail a permissions check (in a somewhat odd edge case where the run doesn't exist at all...) so it should include this response type.
Test Plan:
BK
> Include GrapheneUnauthorizedError in  GrapheneTerminateRunsResultOrError

- js_modules/dagster-ui/packages/ui-core/src/runs/useRunsForTimeline.tsx
Currently, if the FutureTicksQuery itself fails we recover by returning the ongoing runs and complete runs data that we have.
However, if the query doesn't fail then we end up iterating over all of the locations within it and constructing a `jobs` array with all of the rows of the timeline. The problem is that this construction relies on the jobs returned by FutureTicksQuery. If FutureTicksQuery doesn't return a particular job then we drop the data for that job completely. To fix this track which keys we've added via the FutureTicksQuery and then do a second pass where we add data for any jobs that were not in the FutureTicksQuery
Loaded the Run timeline for a customer with a failing location entry
> [Run Timeline] Don't drop job data if locations within the FutureTicksQuery fails

- python_modules/dagster/dagster/_core/definitions/automation_tick_evaluation_context.py
- python_modules/dagster/dagster/_core/execution/asset_backfill.py
- python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py
- python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill_with_backfill_policies.py
- python_modules/dagster/dagster_tests/declarative_automation_tests/legacy_tests/scenarios/asset_graphs.py
- python_modules/dagster/dagster_tests/declarative_automation_tests/scenario_utils/base_scenario.py
When using self-dependant assets and backfill policies, runs need to go one at a time.
Now that we're using subsets we can no longer rely on the backfill iteration going partition by partition and stopping once the total number of partitions being materialized has exceeded the max_partitions_per_run setting on the backfill policy. Instead, we add an explicit filtering step that detects this case and returns the first N partitions.
New test cases, wondering if I should add some other weird ones though
Run an asset like that manually, verify that it sequences the runs individually again
> Handle self-dependant assets with backfill policies that limit the number of partitions that can be materialized per run

- js_modules/dagster-ui/packages/ui-core/src/selection/BaseSelectionVisitor.ts
- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionAutoCompleteVisitor.ts
- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInputUtil.ts
Turns out the auto-complete suggestions weren't working as expected due to comparing constructor names which get minified in the built app. I will research a better approach than this but for now comparing to the name of the classes works.
built the app and tested the auto-complete behavior
> [Selection input autocomplete] Don't compare constructor names to hardcoded string

- js_modules/dagster-ui/packages/ui-core/src/runs/RunAlertNotifications.oss.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunHeaderActions.tsx
Corresponds to https://github.com/dagster-io/internal/pull/13843.
Create a shared component to allow rendering alert notification information into the Run page header.
Viewing cloud, navigate to a run that triggered alerts. Verify that the button renders and behaves correctly.
> [ui] Shared component for alerts in Run header

- python_modules/dagster/dagster/_core/storage/db_io_manager.py
- python_modules/dagster/dagster_tests/storage_tests/test_db_io_manager.py
IO managers expect exact type matches, which means supplying classes inheriting of a supported type makes the asset fail.
I privately added a test on `test_snowflake_io_manager.py` to ensure that this case failed on `master` and passed on my branch. There should be a better place to put a test on this, though. Let me know where.
Fix an issue with `DbIOManagers` being unable to process subclasses of handled types.
> Fix inheritance type check fails on asset outputs

- python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
- python_modules/dagster/dagster/_core/definitions/asset_graph_differ.py
- python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
fix issues caused by https://github.com/dagster-io/dagster/pull/27872
and update AssetGraphDiffer to always expect a graph (which may be empty) instead of being able to take `None`
> fix asset graph diffing

- docs/package.json
- docs/scripts/build-api-docs.sh
- docs/tox.ini
Resolves issue where some users reported the following error message occurs when `LC_ALL` is not set.
```
locale_dir docs/sphinx/locales/en/LC_MESSAGES does not exist
```
`yarn build-api-docs`
NOCHANGELOG
> [docs] use -W for sphinx mdx build

- examples/docs_beta_snippets/docs_beta_snippets_tests/ensure_snapshot_deps.sh
We need `tree` for our component tutorials, which is by default not available in buildkite. This script installs it using `apt-get`, but we want to install using `brew` if developers on OSX run the command without having `tree` installed.
> [ez] Brew install tree when rebuilding component docs on  mac

- docs/docs/dagster-plus/deployment/management/deployments/deployment-settings-reference.md
- docs/docs/dagster-plus/deployment/management/deployments/managing-deployments.md
- docs/docs/guides/deploy/execution/customizing-run-queue-priority.md
- docs/docs/guides/operate/managing-concurrency.md
The `run_queue` is now superseded by `concurrency` in our deployment settings
Inspection
- [docs] Changed our Dagster+ deployment settings reference to match the new concurrency config
> sync deployment settings reference with the latest on concurrency

- js_modules/dagster-ui/packages/ui-core/src/instance/backfill/useReexecuteBackfill.tsx
https://dagsterlabs.slack.com/archives/C03KE7K92TT/p1740048483455839
https://app.datadoghq.com/error-tracking?query=%40application.id%3A7edc09bb-51d0-4555-90cd-b19ca483d1fe%20%40issue.id%3Ae2aa3e7c-ef77-11ef-b02f-da7ad0900002&fromUser=false&issueId=e2aa3e7c-ef77-11ef-b02f-da7ad0900002&refresh_mode=sliding&source=all&from_ts=1740095728752&to_ts=1740110128752&live=true
I'm unable to repro the exception in DD calling `history.createHref` and it has only impacted one user so far.  The `useReexecuteBackfill` code is also pretty much identical to `useReexecuteJob`.
This is the only import of `useHistory` from `react-router` and not `react-router-dom`, so I think this is a likely cause. The parent component uses useHistory from dom, which means both are in use at the same time in this tree.
> [ui] Fix reference to react-router’s useHistory

- js_modules/dagster-ui/packages/ui-core/src/assets/AssetPartitions.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/LaunchAssetChoosePartitionsDialog.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/LaunchAssetExecutionButton.test.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/usePartitionDimensionSelections.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/useReportEventsDialog.tsx
- js_modules/dagster-ui/packages/ui-core/src/partitions/DimensionRangeWizard.tsx
https://linear.app/dagster-labs/issue/FE-786/dont-default-the-backfill-modal-to-all-partitions-make-the-user-choose
https://app.usepylon.com/issues?conversationID=ca84fb9d-928b-4992-b2d9-0e11e3ff7926
I tested this manually and added additional tests. This behavior is a bit nuanced because on the asset partitions page, your selection on the page is transferred into the modal via the query param. I verified that still works (for all selections other than "All"). I also tested with Dynamic / Static partitions as well as time range partitions just to be safe.
I added a new disabled tooltip in case this change is jarring to users and they don't know what they need to do:
- [ui] The launch backfill modal no longer defaults to the "All" partition selection - choose All, Latest, or a custom range …
> [ui] Stop defaulting the launch backfill asset selection to “all”

- docs/CONTRIBUTING.md
- docs/docs/guides/deploy/deployment-options/aws.md
- docs/docs/guides/deploy/dev-to-prod.md
- docs/docs/integrations/libraries/jupyter/using-notebooks-with-dagster.md
- docs/src/components/CodeReferenceLink.tsx
- docs/src/theme/MDXComponents.tsx
Resolves DOC-685.
Creates component, and updates references marked with _TODO_.
Verified links work as expected.
---
---
NOCHANGELOG
> [docs] adds CodeReferenceLink component

- js_modules/dagster-ui/packages/ui-core/src/schedules/ScheduleDetails.tsx
- js_modules/dagster-ui/packages/ui-core/src/schedules/useScheduleAlertDetails.oss.tsx
- js_modules/dagster-ui/packages/ui-core/src/sensors/SensorDetails.tsx
- js_modules/dagster-ui/packages/ui-core/src/sensors/useSensorAlertDetails.oss.tsx
Corresponds to https://github.com/dagster-io/internal/pull/13887.
Add shared components for rendering Alert details in schedule and sensor details. This is effectively a no-op in OSS.
See test plan on internal change.
> [ui] Alerts: Add shared components for Schedules/Sensors

- docs/docs/guides/labs/components/components-etl-pipeline-tutorial.md
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/1-help.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/19-dg-component-type-info.txt
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs.py
- python_modules/libraries/dagster-dg/CHANGELOG.md
- python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/inspect.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_environment_validation.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_info_commands.py
Rename `dg info` -> `dg inspect` (verb, more general).
> [components] dg info -> dg inspect

- js_modules/dagster-ui/packages/ui-core/src/schedules/ScheduleAlertDetails.oss.tsx
- js_modules/dagster-ui/packages/ui-core/src/schedules/ScheduleDetails.tsx
- js_modules/dagster-ui/packages/ui-core/src/sensors/SensorAlertDetails.oss.tsx
- js_modules/dagster-ui/packages/ui-core/src/sensors/SensorDetails.tsx
Corresponds to https://github.com/dagster-io/internal/pull/13892.
Shared pieces for displaying alerts on Schedules/Sensors can just be components instead of hooks.
> [ui] Alerts: Component instead of hook for shared schedule/sensor

- docs/docs/guides/labs/components/components-etl-pipeline-tutorial.md
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/23-dg-component-check-error.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/25-dg-component-check.txt
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs.py
- python_modules/libraries/dagster-dg/CHANGELOG.md
- python_modules/libraries/dagster-dg/dagster_dg/cli/check.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_check_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_environment_validation.py
Renames `dg check component` to `dg check yaml`. This opens the door for `dg check definitions`.
> [components] Rename `dg check component` -> `dg check yaml`

- python_modules/dagster/dagster/_core/execution/asset_backfill.py
- python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py
Since there are very plausible scenarios in which this can happen currently (e.g. a run that succeeds but doesn't materialize all its expected partitions), downgrade the severity of the error message here a bit. Make it a warning instead of an exception, no longer say "contact the Dagster team", and move it into a CANCELED state.
Updated test
Asset backfills will now move into a CANCELED state instead of a FAILURE state when not every requested partition has been marked as materialized or failed by the backfill.
> Update error message when not every partition is completed in a canceling backfill

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/1-help.txt
- python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/utils.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_configure_editor_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_environment_validation.py
Move `dg configure-editor code-location` -> `dg utils configure-editor`.
> [components] `dg configure-editor code-location` -> `dg utils configure-editor` [BUILD-727]

- python_modules/libraries/dagster-dg/dagster_dg/config.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/test_context.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Now that we converged on the concept of workspaces, we no longer need the `extend` key in config for inheritance. This PR simplifies config merging:
- If the closest config file to CWD is a workspace config file, that's our only config
- If the closest config file to CWD is not a workspace config, then look for the workspace config and merge the two files if you find one
Also adds some previously missing tests for config inheritance and invalid config keys.
Unit tests.
> [components] Remove `extend` key from config (BUILD-635)

- js_modules/dagster-ui/packages/ui-core/src/runs/RunAssetTags.tsx
As titled
👀 
[ui] Fixed an issue where certain jobs weren't showing the assets they targeted.
> Show asset selection for hidden asset jobs

- js_modules/dagster-ui/packages/ui-core/src/instance/InstanceConcurrencyKeyInfo.tsx
Adds queued run information on the pool info page, even if the pool granularity is set to "run".
Inspection
- Adds queued run information on the pool info page, even if the pool granularity is set to `run`.
> Show queued runs on op granularity pool info page

- docs/docs/guides/deploy/execution/run-coordinators.md
- docs/scripts/build-api-docs.sh
- docs/sphinx/Makefile
- docs/tox.ini
Parallelized Sphinx builds are not working on M3 Macs and don't work on Windows, so don't parallelize local builds. (We can still parallelize the Vercel/production build.)
> Do not parallelize local API docs build

- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/definitions_component/component.py
Refactor the code in the definitions component to call a method of the `ComponentLoadContext`. We make a lot of decisions in that code that should be system policy as there will be other use cases where we load in user-defined code in the definitions build process.
BK
NOCHANGELOG
> [components] Create load_component_relative_python_module on ComponentLoadContext and document

- python_modules/libraries/dagster-dg/dagster_dg/cli/check.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/dev.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_environment_validation.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_validate_command.py
Introduces `dg definitions validate`, which calls the underlying `dagster definitions validate` with appropriate parameters for the current deployment or code location project. Largely cribbed from `dg dev`.
We could rename this to just `dg validate` or `dg definitions-validate` to avoid adding another top-level CLI.
```sh
dagster ~/repos/components_demo/my-deployment-2
$ dg definitions validate
Using ephemeral dagster definitions validate
2025-02-14 16:02:57 -0800 - dagster - INFO - Using temporary directory /Users/ben/repos/components_demo/my-deployment-2/tmpaxze6pxy for storage. This will be removed when dagster definitions validate exits.
2025-02-14 16:02:57 -0800 - dagster - INFO - To persist information across sessions, set the environment variable DAGSTER_HOME to a directory to …
```
> [dg] add check definitions command

- python_modules/libraries/dagster-components/dagster_components/cli/list.py
- python_modules/libraries/dagster-components/dagster_components_tests/cli_tests/test_commands.py
- python_modules/libraries/dagster-components/setup.py
Fix `params`->`attributes` migration when generating schema for all component types, used in editor hinting.
Update unit test to actually validate this schema against a component file.
> [dagster-components] Fix component schema generation params->attributes

- python_modules/libraries/dagster-components/dagster_components/cli/list.py
- python_modules/libraries/dagster-components/dagster_components_tests/cli_tests/test_commands.py
The Pydantic schema we construct for component files defaults to permissively allowing extra keys. This PR changes that config to explicitly disallow extra keys, so they'll e.g. error in the user's editor.
Nested component schemas should by default already disallow extra fields: https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-components/dagster_components/core/schema/base.py#L28
Though this may not always be the case if user-defined schema classes don't inherit from one of our bases classes with this property.
> [dagster-components] Disallow extra top-level fields on "all components schema"

- docs/docs/dagster-plus/deployment/deployment-types/hybrid/azure/index.md
- docs/docs/dagster-plus/deployment/deployment-types/hybrid/azure/key-vault.md
Added documentation for using Azure Key Vault to manage secrets in Dagster+ AKS deployments. This enables users to securely store and retrieve credentials, including the Dagster Cloud Agent Token, using Azure's native secret management solution.
- Verified all CLI commands and YAML configurations for accuracy
- Tested the secret provider setup with a sample pod
- Confirmed the integration steps with Dagster+ Helm chart values
- Tested with the local doc server
- [docs] Guide on using Azure Key Vault on Dagster+ AKS
> [docs] How to use Azure Key Vault in Dagster+ with AKS

- js_modules/dagster-ui/packages/ui-components/src/components/Popover.tsx
- js_modules/dagster-ui/packages/ui-core/src/asset-selection/input/AssetSelectionInput.oss.tsx
- js_modules/dagster-ui/packages/ui-core/src/selection/CustomErrorListener.ts
- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInput.tsx
- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInputHighlighter.ts
- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInputParser.ts
- js_modules/dagster-ui/packages/ui-core/src/selection/__tests__/createSelectionLinter.test.ts
- js_modules/dagster-ui/packages/ui-core/src/selection/createSelectionLinter.ts
- js_modules/dagster-ui/packages/ui-core/src/selection/useSelectionInputLintingAndHighlighting.tsx
Note that updating the usefulness of the error messages is outside of the scope of this PR. Currently just returning what ANTLR gives us but I think we can do better in the future.
Stop using CodeMirror's linter functionality and instead running linting ourselves in order to have control over the error tooltip rendering beyond just the class name.
Manual testing
> [Selection input] Update error styles

- python_modules/dagster/dagster/_core/execution/compute_logs.py
- python_modules/dagster/dagster_tests/storage_tests/test_compute_log_manager.py
If you had a resource that seeded the python RNG (or RLG in this case) in could cause every step to be assigned the same key, causing them to overwrite each other. This fixes that by temporarily reseeding the RNG during log key construction. 
New test case that was failing before
Fixed issue where seeding the random number generator during code import or when initializing a resource could cause every step to write to the same stdout or stderr key.
> Fix issue where seeding the random number generator during import or resource init time could cause every step to write to the same compute log key

- python_modules/dagster/dagster/_core/op_concurrency_limits_counter.py
- python_modules/dagster/dagster_tests/execution_tests/execution_plan_tests/test_execution_plan_reexecution.py
- python_modules/dagster/dagster_tests/storage_tests/utils/run_storage.py
Step selections should affect which pools limit a given run.
BK
- Fix a bug where run step selections were not affecting the pool limits affecting a specific run.
> make pool calculations take into account steps to execute

- python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/check.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/dev.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/docs.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/init.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/inspect.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/list.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/utils.py
This is a minor refactor that makes our CLI commands/signatures a bit more clear.
> [components] Use `click.get_current_context()` instead of `click.pass_context`

- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/utils.py
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/utils.py
- examples/docs_beta_snippets/tox.ini
Standardize output width for duckdb commands in docs snippets. We do this by executing them in a pseudoterminal using `pexpect` and setting duckdb's `.maxwidth` setting.
DuckDB's `.maxwidth` setting is extremely finicky and annoying. It is often silently ignored. The only way I could get it to reliably actuate was when running interactively from the command line. It seems to change it's behavior based on the kind of output stream it's hooked up to.
The solution here is unfortunately complex, but so far as I can tell there is no way at all to get `duckdb` to respect `.maxwidth` outside of a terminal environment. I tried using an `-init` script and many other things. It just silently ignores `.maxwidth` unless you are in a terminal. So we simulate a terminal with `pexpect`, which works. …
> [components] Standardize duckdb table width when generating CLI snippet output

- python_modules/dagster/dagster/_core/definitions/utils.py
Decouple the condition `is_valid_asset_owner` from the `validate_asset_owner` function. 
The new `is_valid_asset_owner` will be used in subsequent PR to test asset owners in `dagster-powerbi`
Existing tests
> [utils] move validate_asset_owner condition to is_valid_asset_owner

- python_modules/libraries/dagster-powerbi/dagster_powerbi/translator.py
- python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_translator.py
A bug was reported by a user, where the value of semantic model's `configuredBy` was a UUID instead of a valid email. The `configuredBy` field is used to set the asset owner value in AssetSpec - this causes an exception because a UUID is not a valid asset owner.
> configuredBy | string | The dataset owner
Looking at the `configuredBy` field in PowerBI API docs, the string format for this field is not mentioned. See in [this page](https://learn.microsoft.com/en-us/rest/api/power-bi/admin/datasets-get-datasets-in-group-as-admin).
This is also true for report's `createdBy`.
To fix this, let's use `is_valid_asset_owner` for both cases to make sure we don't pass an invalid asset owner value to AssetSpec, which would cause an exception.
> [dagster-powerbi] Handle invalid asset owners for reports and semantic models

- python_modules/dagster/dagster/_daemon/sensor.py
- python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
- python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py
Sensors are supposed to skip subsequent `RunRequests` that have the same run key as a previous run. This works across ticks but not for `RunRequests` within the same tick-- currently two runs will be launched with the same key from within the same tick.
This PR amends the sensor daemon logic to ensure that sensor `RunRequests` with the same run key are handled the same as they are across runs.
User @Gw1p submitted an initial attempt [here](https://github.com/dagster-io/dagster/pull/27322) at fixing this but an alternative approach was required to ensure identical handling of cross-tick and same-tick duplicates.
New unit test.
Fixed a bug where a sensor emitting multiple `RunRequests` with the same run key within a single tick would cause two runs with the same key to be executed. Now only …
> Skip sensor runs from same tick that use same run key

- js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx
As titled.
Loaded the asset lineage view
> Fix asset node lineage when new selection syntax flag is on.

- docs/docs/guides/build/assets/defining-assets.md
Fixes the broken link in this section of the docs: https://docs.dagster.io/guides/build/assets/defining-assets#next-steps
> [docs] fix broken link in defining-assets.md

- docs/sphinx/_ext/dagster-sphinx/dagster_sphinx/docstring_flags.py
- docs/sphinx/_ext/sphinx-mdx-builder/sphinxcontrib/mdxbuilder/writers/mdx.py
This cleans up the formatting of deprecation flags in the extensions.
The mdx writer should not know about Dagster internals as much as
possible. Instead, the dagster_sphinx extension removed the unwanted
strings from the API documentation.
1. Before changes to docstring_flags.py:
<span className="flag flag-danger">deprecated</span><cite>deps</cite> instead.)
2. After changes to docstring_flags.py:
<span className="flag flag-danger">deprecated</span>  Deprecated, use deps instead.
> [docs-sphinx] Clean up flags logic in sphinx extensions

- js_modules/dagster-ui/packages/ui-components/src/theme/darkThemeColors.tsx
- js_modules/dagster-ui/packages/ui-components/src/theme/lightThemeColors.tsx
Fix disabled state fill color of Checkbox switches, particularly in dark mode.
Prod:
With this change:
yarn storybook
> [ui] Restore disabled checkbox fill color

- js_modules/dagster-ui/packages/ui-core/src/assets/AssetPartitionDetail.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/FailedRunSinceMaterializationBanner.tsx
It is confusing for partitions that were not materialized due to canceled runs do not show any messaging indicating that a failure or cancellation occurred on the asset partition detail page.
This is because we only show the banner if the run failed. Update this to show a banner if it was canceled as well. Use a "warning" intent for the cancellation banner, to help visually distinguish it from the failed run.
Also updated the copy a bit, since it's the runs that fail or are canceled.
View partition that failed to materialize due to cancellation. Verify that the yellow banner appears.
View partition that failed to materialize due to failed run. Verify that the red banner appears.
[ui] For asset partitions that fail to materialize due to a run cancellation, show this information on the …
> [ui] Show warning on partitions that did not materialize due to canceled runs

- js_modules/dagster-ui/packages/ui-core/src/assets/AssetPageHeader.oss.tsx
Resolves https://github.com/dagster-io/dagster/issues/26471.
Repair links in the breadcrumb overflow menu.
These are currently unaware of react-router context, so they have no access to the `basePath` value. Unfortunately, Blueprint doesn't appear to give us any way to override how these menu items are rendered -- the `overflowProps` specifically omit `overflowRenderer` and `visibleItemRenderer` from being specified by client code.
To work around this, apply the `basePath` value to all of the hrefs to make it available to the overflow menu, and remove it from rendered breadcrumb elements, which use react-router Link components.
View an asset with a long key path, shrink the viewport horizontally to make the breadcrumbs collapse. Open the overflow menu, verify that links are correctly …
> [ui] Fix links on breadcrumb overflow menu

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/workspace/1-dg-init.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/workspace/2-tree.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/workspace/6-component-type-list.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/workspace/7-scaffold-project.txt
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs_workspace.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/init.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_environment_validation.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_init_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Resolves https://linear.app/dagster-labs/issue/BUILD-734/allow-the-parameterization-of-the-name-of-the-workspace-directory.
Also changes the default name from "workspace" to "dagster-workspace", which probably merits a quick discussion.
BK, run the two commands locally
> Add `dg scaffold workspace` command and make the workspace name configurable

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/4-pyproject.toml
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/workspace/4-project-pyproject.toml
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs.py
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs_workspace.py
- python_modules/libraries/dagster-dg/dagster_dg/config.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/templates/PROJECT_NAME_PLACEHOLDER/pyproject.toml.jinja
- python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_environment_validation.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Removes `is_component_lib` and `component_lib_package` settings. Instead, a package is now a component library if it has at least one entry point in the `"dagster.components"` group. The scaffolding location for new component types is the first defined entry point in this group.
Tweaked existing unit tests.
> [components] Remove is_component_lib, source component_lib_module from entry point

- python_modules/libraries/dagster-components/dagster_components/__init__.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py
- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/test/complex_schema_asset.py
- python_modules/libraries/dagster-components/dagster_components_tests/code_locations/dbt_project_location/components/jaffle_shop_dbt/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_spec_processing.py
This changes the name of the top-level "transforms" attribute of the sling and dbt components to "post_processors". "transforms" was quite confusing because it communicates nothing about when it is applied relative to the dbt/sling translator, which is configured by `"asset_attributes"`. `"post_processors"` still requires some explanation (we should probably inject explanatory commentary when generating the component.yaml) but is more clear.
> [components] Change top level attribute "transforms" to "post_processors" (BUILD-725)

- python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_sling_integration_test.py
- python_modules/libraries/dagster-sling/dagster_sling/sling_event_iterator.py
This adds a top level attribute `include_metadata` on `SlingReplicationCollection`. This is a list that can include `"column_metadata"` and `"row_count"` to match the methods on the `SlingEventIterator`. The default value includes both these fields.
Also cleans up the test code for sling a little bit.
New unit test.
> [components] Add attributes to control metadata on materialized sling assets

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/existing-project/2-pyproject.toml
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/1-help.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/4-pyproject.toml
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/workspace/3-pyproject.toml
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/workspace/4-project-pyproject.toml
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs.py
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs_existing_project/test_existing_code_location.py
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs_migrating_definitions/my-existing-project/pyproject.toml
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs_workspace.py
- python_modules/libraries/dagster-dg/dagster_dg/cache.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/global_options.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/init.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/config.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/templates/PROJECT_NAME_PLACEHOLDER/pyproject.toml.jinja
- python_modules/libraries/dagster-dg/dagster_dg/templates/WORKSPACE_NAME_PLACEHOLDER/pyproject.toml.jinja
- python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_check_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_custom_help_format.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/test_context.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Overhaul the `dg` config system. This is essential for a stable foundation going forward.
The config system reads config from three sources and merges them all together.
- the context root config file
- a containing workspace config file
- CLI options
Even though the kinds of options you can set in these different locations differ (for example, you can't set `is_workspace` from the CLI), they are currently all treated as having the same type. This:
- makes our validation much looser than it should be
- makes the code harder to follow
The implicit complexity will become a problem as we scale.
- The basic approach of reading config from the above three sources is unchanged, but there is now much stronger typing and consequently tighter validation. Error messages for missing or wrong values …
> [components] [RFC] Overhaul DgConfig, replace `is_{workspace,project}` with `directory_type` field

- docs/docs/guides/automate/asset-sensors.md
- examples/docs_beta_snippets/docs_beta_snippets/guides/automation/multi-asset-sensor.py
Fixes `multi-asset-sensor.py` example to remove circular reference and clarifies `multi_asset_sensor` can also trigger op jobs.
👀 and ran example locally
> [docs] fix multi-asset-sensor code example

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/1-help.txt
- python_modules/libraries/dagster-components/dagster_components/cli/__init__.py
- python_modules/libraries/dagster-components/dagster_components/cli/list.py
- python_modules/libraries/dagster-components/dagster_components/cli/scaffold.py
- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/test/test_cases.py
- python_modules/libraries/dagster-components/dagster_components/utils.py
- python_modules/libraries/dagster-components/dagster_components_tests/cli_tests/test_commands.py
- python_modules/libraries/dagster-components/dagster_components_tests/utils.py
- python_modules/libraries/dagster-components/setup.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/global_options.py
- python_modules/libraries/dagster-dg/dagster_dg/component.py
- python_modules/libraries/dagster-dg/dagster_dg/config.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_custom_help_format.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/test_cache.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/test_context.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Remove the janky `--builtin-component-lib` option that got forwarded through `dagster-dg` to `dagster-components`. This was very weird and made entry point loading confusing. The new system:
`dg` has a new (hidden, bc for tests) option `--use-component-module` (can be passed multiple times). If this is set, then `dg` will instruct `dagster-components` to load only from these modules rather than loading from entry points (which is the default behavior). This is a much cleaner system.
Also:
- Remove the `dagster_components.test` entry point-- now no test components are exposed via entry points, you have to explicitly target them.
- Some config validation improvements necessitated by `use_component_modules` being a `list[str]`
Upstack we can move the test components out of …
> [components] Replace `--builtin-component-lib` option with `--use-component-module`

- python_modules/libraries/dagster-components/CHANGELOG.md
- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components/utils.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_dbt_project.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_sling_integration_test.py
- python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_utils.py
`get_wrapped_translator_class` is a utility for converting user-supplied `asset_attributes` into a translator, for Sling and dbt. It currently omits some fields, so e.g. user-supplied `metadata`, `description` etc for  `asset_attributes` are silently swallowed, not setting the relevant attributes on the targeted assets.
e.g. the following does not set owners, but validates and loads just fine
```yaml
type: dbt_project@dagster_components
attributes:
asset_attributes:
owners:
- ben@dagsterlabs.com
```
This PR fixes these missing connections, explicitly erroring on any the base integration translators do not support, and puts the list of translator fields under test.
New unit test to sanity check `get_wrapped_translator_class` wraps expected fields.
Also iterate over all fields and ensure …
> [dagster-components] Ensure we properly wrap all translator fields

- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_dbt_project.py
Right now, the dbt component doesn't natively support subselection or exclusion. Adds two new top-level params to enable this functionality - taken from https://github.com/dagster-io/internal/pull/13989
```yaml
type: dbt_project@dagster_components
attributes:
dbt:
project_dir: jaffle_shop
exclude: my_excluded_pattern
```
> [dagster-components] Add support for dbt select, exclude in dbt component

- python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py
- python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_dbt_project.py
Introduces a new `backfill_policy` schema entry to `OpSpecSchema`, which is resolved to an actual `BackfillPolicy` during its conversion to an `OpSpec`:
```yaml
type: dbt_project@dagster_components
attributes:
op:
backfill_policy:
type: multi_run
max_partitions_per_run: 5
```
> [dagster-components] Introduce resolved OpSpec, backfill_policy

- docs/docs/dagster-plus/deployment/migration/self-hosted-to-dagster-plus.md
- docs/docs/dagster-plus/index.md
- docs/docs/guides/deploy/index.md
Removing this unlisted doc and links to it for now, since it's a blank page that is being indexed by Google, possibly because there were internal links to it. I have a task to complete this guide end of March / beginning of April.
> [Docs] Temporarily remove blank OSS -> Dagster+ migration guide

- js_modules/dagster-ui/packages/ui-core/src/runs/CapturedLogPanel.tsx
- python_modules/dagster/dagster/_core/storage/compute_log_manager.py
get websocket and polling versions aligned with a smaller chunk size 
load large compute logs with websockets on and off
> [compute logs] standardize on fetching 1MB at a time

- js_modules/dagster-ui/packages/ui-core/src/runs/RunMetadataProvider.tsx
Tested with the gzip run debug file in the ticket 
[ui] Steps properly transition to failed in the Run gantt chart when resource initialization fails.
> [ui] Treat RESOURCE_INIT_FAILURE as a terminal step event

- js_modules/dagster-ui/packages/ui-core/src/hooks/usePrevious.tsx
- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInput.tsx
as titled.
https://github.com/user-attachments/assets/14cd6219-0d3f-4cdc-9adf-752218b320ec
> [selection input] Don't reset selected index when dropdown results don't change

- js_modules/dagster-ui/packages/ui-core/src/assets/overview/AutomationDetailsSection.tsx
As titled.
before:
after:
[ui] Fixed an issue where assets with automation conditions wouldn't show the jobs/sensors/schedules targeting them.
> [FE-769] Show other automations if an asset has an automation condition

- python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
Clarify behavior of `output_required` on `@asset` with respect to `return`.
> Update `@asset.output_required` docstring to clarify it does not work for `return`

- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_dev_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_validate_command.py
These tests were mistakenly using latest published `dagster-components` when they should be using editables.
> [components] Fix workspace dev tests that need editable install for projects

- python_modules/dagster/dagster/_core/definitions/module_loaders/load_assets_from_modules.py
- python_modules/libraries/dagster-components/dagster_components/core/component.py
In 0.1.17 relies on behavior of modified utility `find_subclasses_in_module` in `dagster`. But a `dagster` with the updated utility is not published yet, leading to an error using newest `dg` in the wild. This reverts the change to the utility function and inlines the logic in `dagster-components`.
Existing test suite + manually using editable `dagster-components` w/ published `dagster`.
> [components] Inline the Component subclass discovery logic for Component discovery

- python_modules/libraries/dagster-dg/dagster_dg/cli/check.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_environment_validation.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_validate_command.py
To be consistent with `defs` change `dg check definitions` to `dg check defs`
```
(dagster-dev-3.11.11-2024-12-08) ➜  p1 dg check defs
Using /Users/schrockn/code/scratch/component_workspaces/dw-7/projects/p1/.venv/bin/dagster
```
NOCHANGELOG
> Change dg check definitions to dg check defs

- python_modules/libraries/dagster-datahub/setup.py
Until wheels are published:
https://github.com/confluentinc/confluent-kafka-python/issues/1927
> Pin confluent-kafka<2.8.1 in dagster-datahub

- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cli/test_scaffold.py
Testing result.output and result.stdout has caused recurring problems for dbt tests, specifically for Python 3.9 and 3.10, see [here](https://buildkite.com/dagster/dagster-dagster/builds/111921#0194f5ea-38cc-4c76-a6d3-b368a249840a) and [here](https://buildkite.com/dagster/dagster-dagster/builds/111921#0194f5ea-38cc-4c76-a6d3-b368a249840a).
Let's skip these assertions for now while we investigate the root cause of the problem.
BK
> [dagster-dbt] Skip output and stdout assertions for Python 3.9 and 3.10

- python_modules/libraries/dagster-gcp/dagster_gcp/gcs/io_manager.py
- python_modules/libraries/dagster-gcp/dagster_gcp_tests/gcs_tests/test_io_manager.py
Mirrors a similar change for the s3 io manager: https://github.com/dagster-io/dagster/pull/20562/files
https://cloud.google.com/python/docs/reference/storage/latest/google.cloud.storage.blob.Blob indicates that replacing blobs is allowed (you can set a versioning policy to keep the old one around, but its in a versioned state and the 'real' one is the one that's replaced)
New test case
[dagster-gcp] The `PickledObjectGCSIOManager` now replaces the underlying blob when the same asset is materialized multiple times, instead of deleting and then re-uploading the blob.
> Replace blobs rather than deleting then rewriting them in PickledObjectGCSIOManager

- python_modules/libraries/dagster-datahub/setup.py
This reverts commit eafa35e9058d06b4c9db0ba56af31149c246c0b5.
To land once wheels are published. Ideally before we cut our next release.
> Revert "Pin confluenct-kafka<2.8.1 in dagster-datahub"

- python_modules/libraries/dagster-components/dagster_components/utils.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_dbt_project.py
Right now, when users specify custom e.g. `metadata` to attach to assets as part of  `asset_attributes`, this overrides any metadata set by the default translator.
I think in nearly every case, a user will want to keep these metadata keys and simply append their own. This PR changes that behavior.
Previously, the following would null out existing `dagster/...` and `dagster-dbt/...` metadata keys:
```yaml
type: dbt_project@dagster_components
attributes:
asset_attributes:
metadata:
- foo: bar
```
New unit test.
> [dagster-components] Merge dict asset_attributes fields

- python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/sensor.py
- python_modules/dagster/dagster/_core/definitions/run_request.py
- python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_sensor.py
Interface for [build_sensor_for_freshness_checks](https://github.com/dagster-io/dagster/blob/64ea57c11c086e91523525011eb52df006bb126d/python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/sensor.py#L38) is really limited; this helps add some flexibility.
I don't know if it's necessary to add a whole test for this. I could modify one of the existing tests and check that the `run_request` in the test has the right tags?
Added support for passing `tags` to the created `RunRequest` when using `build_sensor_for_freshness_checks()`.
> Support `tags` for freshness checks sensor factory

- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_dev_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_validate_command.py
There was a method of resolution from modules to paths that relied on using `importlib.util.find_spec_from_module`. This was behaving flakily in certain test contexts, leading to mysterious failures. This PR changes the method of resolution to skip importlib and instead just perform a straightforward conversion to path. It only works for modules that are part of the project root but that's the only thing we were using it for anyway.
Reenabled test that was failing before.
> [components] Fix flaky module -> path resolution

- .gitattributes
As https://app.graphite.dev/github/pr/dagster-io/internal/14067 demonstrates we should ignore .ambr files 
Read file
NOCHANGELOG
> Ignore *.ambr files in diffs, just like uv.lock files

- python_modules/libraries/dagster-components/dagster_components/core/component_scaffolder.py
- python_modules/libraries/dagster-components/dagster_components/scaffoldable/decorator.py
- python_modules/libraries/dagster-components/dagster_components/scaffoldable/scaffolder.py
- python_modules/libraries/dagster-components/dagster_components_tests/scaffoldable_tests/test_decorator.py
This stack changes our scaffolding infrastructure in components to a lightweight, composable framework that could be reused in other other contexts. 
We plan on extending the scaffolding framework to concepts like the project and possibly vanilla definitions.
Even if we do not do that in the short-term, I believe this is a superior structure that makes the Components base class more focused and leaves scaffodling as a standalone component.
The first step is to implement the replacement decorator `scaffoldable` and to move the generic scaffodling classes (to be renamed upstack) to `dagster_component.scaffoldable`. The eventual home of scaffoldable will be `dagster.scaffoldable` or possibly a standalone package.
BK
NOCHANGELOG
> [dg] Implement scaffoldable as generic module to replace component-specific scaffolding features

- python_modules/libraries/dagster-components/dagster_components/cli/scaffold.py
- python_modules/libraries/dagster-components/dagster_components/components/definitions_component/component.py
- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/scaffold.py
- python_modules/libraries/dagster-components/dagster_components/scaffoldable/decorator.py
- python_modules/libraries/dagster-components/dagster_components_tests/scaffoldable_tests/test_decorator.py
Here we add a backwards compatibility layer where an existing `Component` class can use the decorator and make the `get_scaffolder` automatically fail if called. This allows us to add `scaffoldable` decorators incrementally, which we do so to `DefinitionsComponent`
BK
NOCHANGELOG
> [dg] Backwards compatability layer for existing Components to allow incremental adoption of scaffoldable

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/2-shell-command-empty.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-scaffolder.py
- python_modules/dagster-test/dagster_test/components/all_metadata_empty_asset.py
- python_modules/dagster-test/dagster_test/components/complex_schema_asset.py
- python_modules/dagster-test/dagster_test/components/simple_asset.py
- python_modules/dagster-test/dagster_test/components/simple_pipes_script_asset.py
- python_modules/libraries/dagster-components/dagster_components/components/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/components/definitions_component/component.py
- python_modules/libraries/dagster-components/dagster_components/components/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/scaffoldable_tests/test_decorator.py
- python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_component_with_optional_scaffolder.py
- python_modules/libraries/dagster-dg/dagster_dg/templates/COMPONENT_TYPE/COMPONENT_TYPE_NAME_PLACEHOLDER.py.jinja
This PR converts all existing components to use `scaffoldable`, setting us up to delete scaffoldling from the `Component` base class.
BK
NOCHANGELOG
> [dg] Convert all existing Component use to scaffoldable

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-scaffolder.py
- python_modules/dagster-test/dagster_test/components/simple_pipes_script_asset.py
- python_modules/libraries/dagster-components/dagster_components/cli/scaffold.py
- python_modules/libraries/dagster-components/dagster_components/components/dbt_project/scaffolder.py
- python_modules/libraries/dagster-components/dagster_components/components/definitions_component/scaffolder.py
- python_modules/libraries/dagster-components/dagster_components/components/sling_replication_collection/scaffolder.py
- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/scaffold.py
- python_modules/libraries/dagster-components/dagster_components/scaffoldable/scaffolder.py
- python_modules/libraries/dagster-components/dagster_components_tests/cli_tests/test_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_info_commands.py
This was already halfway done, but this is an opportunity to complete it. This PR adopts "params" terminology for scaffolding rather than "schema" which 1) makes more sense given how it is exposed to users (CLI) and 2) clearly disambiguates from component yaml schema.
BK
NOCHANGELOG
> [dg] Change naming conventions around scaffolding parameterization from schema to params

- python_modules/libraries/dagster-components/dagster_components/cli/scaffold.py
- python_modules/libraries/dagster-components/dagster_components/components/definitions_component/scaffolder.py
- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/scaffold.py
- python_modules/libraries/dagster-components/dagster_components/scaffoldable/decorator.py
- python_modules/libraries/dagster-components/dagster_components_tests/scaffoldable_tests/test_decorator.py
- python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_component_with_optional_scaffolder.py
Completely eliminate `scaffolder_from_component_type` and just use vanilla `get_scaffolder` function.
BK
NOCHANGELOG
> [dg] Eliminate scaffolder_from_component_type

- python_modules/dagster/dagster/_core/storage/runs/migration.py
realized this migration has the same bug as the internal one, where we'll call `get_end_timestamp_for_backfill` on a  backfill in a canceling state and throw an error
> [quick] fix backfill status check in end timestamp migration

- python_modules/libraries/dagster-dg/dagster_dg/cli/check.py
By defaulting to `warning` instead of `info` and adding a success method we can make `dg check defs` feel better.
```
➜  test-project dg check defs
Using /Users/schrockn/code/scratch/component_workspaces/dw-0305-0516/projects/test-project/.venv/bin/dagster
All definitions loaded successfully.
➜  test-project
```
NOCHANGELOG
> [dg] Default dg check defs to warning and print success message

- js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/useDeleteDynamicPartitionsDialog.tsx
The extra components provided by these three hooks are dialogs and are not rendering additional buttons, so I re-ordered them so that they don't contribute padding to the end of the flexbox. Also changed one element that was intended to be conditional from a `<span />` to undefined like the others.
Before:
After:
> [ui] Fix for extra padding on Materialize button

- js_modules/dagster-ui/packages/ui-core/src/assets/AssetPartitions.tsx
- js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillActionsMenu.tsx
These are interchangeable in the tests (they both work), but at some point React started printing errors about data-testId in the console:
```Warning: React does not recognize the `data-testId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `data-testid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.```
> [ui] Replace references with data-testId => data-testid

- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_custom_help_format.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_docs_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_environment_validation.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_info_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_init_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/test_cache.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Now that the test components live in `dagster-test` instead of `dagster-components`, we don't want to target them by default in tests since the `dagster-test` package is not installed in non-editable scaffolded projects. This was leading to confusing error messages about `dagster-test` not being installed in new tests.
> [components] Switch dagster-dg tests to explicitly opt in to fixed test components

- python_modules/libraries/dagster-fivetran/dagster_fivetran/__init__.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_decorator.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/beta/conftest.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/beta/test_asset_specs.py
Fixes [AD-780](https://linear.app/dagster-labs/issue/AD-780/[dagster-fivetran]-support-connection-filter).
This PR adds ConnectorSelectorFn to support connector selection/filter in the new integration. 
In the legacy integration, connectors could be filtered based on their name, id, database and service, using a callback of type `Callable[[FivetranConnectionMetadata], bool]`.
The new `ConnectorSelectorFn` is a callback of type `Callable[[FivetranConnector], bool]` - `FivetranConnector` is the container class that we are using in the new integration for Fivetran connectors
```
from dagster_fivetran import FivetranFilterFn, FivetranWorkspace, load_fivetran_asset_specs
fivetran_workspace = FivetranWorkspace(
account_id=dg.EnvVar("FIVETRAN_ACCOUNT_ID"), …
```
> [RFC][dagster-fivetran] Implement ConnectorSelectorFn

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/existing-project/2-pyproject.toml
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs_existing_project/test_existing_code_location.py
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs_migrating_definitions/my-existing-project/pyproject.toml
- python_modules/libraries/dagster-dg/dagster_dg/cli/check.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/dev.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/config.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_check_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/test_context.py
- `tool.dg.project.components_module` config setting -> `defs_module`
- `DgContext.components_module_name` -> `defs_module_name`
- `DgContext.definitions_module_name` -> `code_location_load_target_module_name`
- `*components_library` -> `*component_library` (internally-facing only)
- `*module` -> `*module_name` (internally facing only, config settings are just "module" since it is clear in that context it is a name and not an actual module ref)
> [components] Rename tool.dg.project.components_module -> defs_module and internal property renames

- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/test_context.py
There was a discrepancy where the `code_location_load_target_module_name` was hardcoded to `<root_module>/definitions.py` instead of being read from `tool.dagster`. This changes it to read from `tool.dagster`. This is an intermediate step to the elimination of `tool.dagster` from projects.
New unit test.
> [components] Read project code location name/target from `tool.dagster`

- python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran/translator.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/beta/conftest.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/beta/test_asset_specs.py
Fixes AD-881.
The `schemas` field is marked as required in Fivetran docs for the `connections/{connection_id}/schemas`, but is missing for any connection that has not already been synced. 
Updating the logic to consider schemas as optional, and to discard connectors without schemas/that have not been synced yet.
> [dagster-fivetran] Handle missing schemas for unsynced connectors

- docs/docs/guides/operate/managing-concurrency.md
- examples/docs_beta_snippets/docs_beta_snippets/guides/operate/concurrency-run-scoped-op-concurrency.py
Seeing uptick in questions about run-scoped op concurrency limits since `1.10.0`... Hopefully will head some of that off.
Inspection
[docs] added concurrency section about run-scoped op concurrency
> add section on run-scoped op concurrency limits

- python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
Add the message suggested [here](https://github.com/dagster-io/dagster/pull/28080#pullrequestreview-2654826757) to warn users when a Fivetran connector is discarded/when connector schemas are missing.
> [dagster-fivetran] Add warning message for missing connector schemas in FivetranWorkspace

- js_modules/dagster-ui/packages/ui-core/client.json
- js_modules/dagster-ui/packages/ui-core/src/assets/RecentUpdatesTimeline.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/SimpleStakeholderAssetStatus.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/overview/AssetNodeOverview.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/types/useLatestEvents.types.ts
- js_modules/dagster-ui/packages/ui-core/src/assets/useLatestEvents.tsx
Fixes https://linear.app/dagster-labs/issue/FE-589/metadata-plots-only-work-in-asset-catalog-when-most-recent-partition, https://github.com/dagster-io/dagster/issues/24600
It was flagged by a user that the new Asset Overview page shows the metadata and schema for the most recent PARTITION, or empty states if that partition is not present. This is somewhat confusing because these sections can render empty while the tag at the top still shows the latest event. (Screenshot above)
I think at some point the tag at the top of the page was also restricted to showing the latest partition, so this made sense. However, it seems problematic because for any daily partitioned asset, it is missing for some portion of the day and all the information disappears for that period.
The fix in this PR is just …
> [ui] Make asset overview show metadata, schema of latest event, not “latest partition or null"

- js_modules/dagster-ui/packages/ui-core/src/assets/RecentUpdatesTimeline.tsx
Moves the calculation of the date bounds to a convenience method so that we can add a better fallback than `?? 0`
Before:
After:
> [ui] When the recent updates timeline is empty, default to “last week”

- js_modules/dagster-ui/packages/ui-core/src/assets/AssetPartitions.tsx
- js_modules/dagster-ui/packages/ui-core/src/launchpad/ConfigEditorConfigPicker.tsx
This is just a drive-by, noticed this was busted when I was fixing the overview page issue.  I think the original intention was for the sort button to appear to the right of the input, and for the dimension name to appear below (maybe?)
- I made the sort indicator the right-hand element of the input
- I made the dimension name part of the placeholder text, which simplifies the header a bit
Before:
After:
Tested on single- and multi- dimensional assets. Also checked that you can still fill in the input and change the A/Z order
> [ui] Fix whacky rendering of multi-dimension partition headers

- python_modules/libraries/dagster-components/dagster_components/components/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_dbt_project.py
Refactoring the `DbtProjectComponent` to use explicit resolvers in all cases. This is part of the process to remove all instances that rely on the `ResolvableSchema` indirection magic so we can eliminate and build up mappings in the other direction.
BK
NOCHANGELOG
> [dg] Make DbtProject resolvers explicit

- python_modules/libraries/dagster-components/dagster_components/components/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_dbt_project.py
Have `DbtProjectComponent` use `dataclasses.dataclass` rather than the `pydantic` variant, which is much more lightweight.
BK
NOCHANGELOG
> [db] Make DbtProjectComponent vanilla dataclass

- docs/vercel.json
Changes most temporary redirects (307) to permanent redirects (308). I did leave some temporary redirects in place because it is possible we will want to use those source paths again, but I can change those as well if we don't want to deal with the minor SEO hit.
> [DOC-923] Change most temporay redirects to permanent

- python_modules/libraries/dagster-dg/dagster_dg/cli/check.py
Avoid raising an additional python exception w/ stacktrace if the subprocess for `dg defs` fails.
Tested locally
> [dg][ez] dg check defs exits without extra stacktrace on failure

- python_modules/dagster/dagster/_config/pythonic_config/resource.py
- python_modules/dagster/dagster_tests/core_tests/resource_tests/pythonic_resources/test_env_vars.py
Ran into a bad error message experience on DOP here where we just get a Pydantic error if an env var silently fails to load. This forwards the error to the user instead.
Test
> Improved error message experience for resources expecting an env var which was not provided.
> [pythonic resources][ez] Better error message when resolving env vars for resources

- examples/docs_snippets/docs_snippets/integrations/bigquery/reference/pandas_and_pyspark.py
Use a working import path.
However, it's probably separately worth looking at exposing this rather than keeping it in a private, underscore-prefixed path.
Tried this before:
```pycon
>>> from dagster import DbTypeHandler
File "<stdin>", line 1, in <module>
ImportError: cannot import name 'DbTypeHandler' from 'dagster' (/Users/deepyaman/github/dagster-io/community-integrations/libraries/dagster-iceberg/.venv/lib/python3.12/site-packages/dagster/__init__.py)
```
> Correct the `import` statement for `DbTypeHandler`

- python_modules/libraries/dagster-components/dagster_components/core/schema/resolvable_from_schema.py
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_from_schema.py
This introduces ResolvableFromSchema as a successor to ResolvableSchema. We think this is going to be a more sustainable path forward with better structure and a more obvious API.
This adds a minimal implementation that makes the following test case possible:
```python
def test_simple_resolveable_from_schema():
class HelloSchema(DSLSchema):
hello: str
@dataclass
class Hello(ResolvableFromSchema[HelloSchema]):
hello: Annotated[
int, DSLFieldResolver.from_parent(lambda context, schema: int(schema.hello))
]
hello = resolve_as(HelloSchema(hello="1"), Hello, ResolutionContext.default())
assert isinstance(hello, Hello)
assert hello.hello == 1
```
This is largely forked from the existing implementation in the other direction in `base.py` (which will be deleted). However there are important …
> [dg] Introduce ResolvableFromSchema

- python_modules/libraries/dagster-components/dagster_components/core/schema/resolvable_from_schema.py
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_from_schema.py
Makes the default resolver behavior operate on the field that matches the name field that the resolver is annotated on. 
This allows you to write
```python
@dataclass
class Hello(ResolvableFromSchema[HelloSchema]):
hello: Annotated[int, DSLFieldResolver(int)]
```
instead of
```python
@dataclass
class Hello(ResolvableFromSchema[HelloSchema]):
hello: Annotated[
int, DSLFieldResolver.from_parent(lambda context, schema: int(schema.hello))
]
```
NOCHANGELOG
> [dg] Syntax for DSLFieldResolver that hoists field

- python_modules/libraries/dagster-components/dagster_components/components/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py
Continues the process of removing dependencies on the dynamic dispatch behavior of `ResolvableSchema`. When we no longer depend on it we can remove the generic argument.
BK
NOCHANGELOG
> [dg] Make SlingReplicationCollectionComponent no longer depend on dynamic dispatch features of ResolvableSchema

- python_modules/libraries/dagster-components/dagster_components/components/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/components/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/resolvable_from_schema.py
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_from_schema.py
This begins to show the patterns we can use to reduce boilerplate, and I think we can go farther.
What this PR is implement these functions on `ResolvableFromSchema`:
```python
class ResolvableFromSchema(Generic[TSchema]):
@classmethod
def from_schema(cls, context: "ResolutionContext", schema: TSchema) -> Self:
return resolve_schema_to_resolvable(
schema=schema, resolvable_from_schema_type=cls, context=context
)
@classmethod
def from_optional(
cls, context: "ResolutionContext", schema: Optional[TSchema]
) -> Optional[Self]:
return cls.from_schema(context, schema) if schema else None
@classmethod
def from_seq(cls, context: "ResolutionContext", schema: Sequence[TSchema]) -> Sequence[Self]:
return [cls.from_schema(context, item) for item in schema]
@classmethod
def from_optional_seq(
cls, …
```
> [dg] Use prefab helpers to eliminate boilerplate

- python_modules/libraries/dagster-components/dagster_components/components/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/components/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/resolvable_from_schema.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_dbt_project.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_sling_integration_test.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_templated_custom_keys_dbt_project.py
If we inherit from `ResolvableFromSchema` we shouldn't have to implement `get_schema`. This does that.
We also implement the need to override `load` in converted components.
BK
NOCHANGELOG
> [dg] Make implementing get_schema unnecesseary when inheriting from ResolvableFromSchema

- python_modules/libraries/dagster-components/dagster_components/components/definitions_component/component.py
- python_modules/libraries/dagster-components/dagster_components/core/component.py
For simple components that do not require resolution logic, we current require the declaration of a redundant Schema class. This doesn't feel great. Here we allow components to declare themselves as schema directly.
BK
NOCHANGELOG
> [dg] For simple components with no resolution logic, do not require schema classes

- python_modules/libraries/dagster-components/dagster_components/core/schema/resolvable_from_schema.py
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_transformer.py
Sometimes you have existing business objects you do not want to modify (e.g. `AssetSpec`) that you want to apply resolution logic on. This leaves an unfortunate situation where one would need to add a separate class that users would have to instantiate in order a reasonable reuse story. This PR proposes an approach which solves that problem.
The core insight is that `ResolvableFromSchema` is actually the composition of two concepts:
1. A _specification_ of how to perform the resolution process
2. The target type that you want to instantiate
This PR formally encodes that composability by adding a more
generic function
```python
def resolve_schema_using_spec(
schema: EitherSchema,
resolution_spec: type[TResolutionSpec],
context: "ResolutionContext",
target_type: type[T],
) -> T:
```
Which …
> [dg] Add ResolutionSpec

- docs/docs/integrations/libraries/dbt/reference.md
Notes that `default_automation_conditition_sensor` must be enabled for conditions to be evaluated
👀
> [docs] add note to dbt automation conditions

- python_modules/libraries/dagster-components/dagster_components/components/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/components/sling_replication_collection/component.py
this is capturing references to the unbound methods which doesn't work at runtime on 3.9 
run tests on py3.9
> [dg] move staticmethod resolvers back to functions

- python_modules/dagster/dagster/_cli/definitions.py
- python_modules/dagster/dagster/_utils/error.py
- python_modules/dagster/dagster_tests/cli_tests/command_tests/definitions_command_projects/invalid_project_exc/invalid_project_exc/definitions.py
- python_modules/dagster/dagster_tests/cli_tests/command_tests/definitions_command_projects/invalid_project_exc/pyproject.toml
- python_modules/dagster/dagster_tests/cli_tests/command_tests/test_definitions_validate_command.py
Tries to make `dg check defs` error messages more relevant by stripping out the framework junk around a user code error.
Before:
```python
2025-03-04 15:06:30 -0800 - dagster - ERROR - Validation failed for code location dagster_open_platform:
dagster._core.errors.DagsterUserCodeLoadError: Error occurred during the loading of Dagster definitions in
module_name=dagster_open_platform.definitions, working_directory=/Users/ben/repos/internal/python_modules/dagster-open-platform
Stack Trace:
File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_core/workspace/context.py", line 819, in _load_location
else origin.create_location(self.instance)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ben/repos/dagster/python_modules/dagster/dagster/_core/remote_representation/origin.py", line …
```
> [dagster definitions validate] Unwrap, truncate user code errors

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/4-pyproject.toml
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/workspace/4-project-pyproject.toml
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs.py
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs_workspace.py
- python_modules/dagster/dagster/_core/workspace/load_target.py
- python_modules/dagster/dagster_tests/cli_tests/workspace_tests/toml_tests/test_toml_loading.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/check.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/dev.py
- python_modules/libraries/dagster-dg/dagster_dg/config.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/templates/PROJECT_NAME_PLACEHOLDER/pyproject.toml.jinja
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_dev_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_validate_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/test_context.py
Eliminate all use of `tool.dagster` in scaffolded projects. Where previously scaffolded projects were created with a `tool.dagster.{module_name,code_location_name}`, we now omit the `tool.dagster` section. There are two new `tool.dg.project` settings to replace them:
- `tool.dg.project.code_location_load_target_module` (default to `<root_package>.definitions`)
- `tool.dg.project.code_location_name` (default to the project name)
It is rare that either of these should need to be set. `code_location_load_target_module` is a mouthful but calling it `definitions_module` would be very confusing now that there is `defs_module`.
> [components] Remove tool.dagster from scaffolded projects

- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/test_context.py
We permit `tool.dg.cli` in standalone project configs, but when a project is inside a workspace we want to use only the `tool.dg.cli` section in the workspace config to avoid ambiguity about which section should apply when operating on a project from within a workspace. This PR emits a warning and ignores `tool.dg.cli` in a project config that is inside a workspace.
New unit test.
> [components] Ignore and warn about `tool.dg.cli` in project inside workspace

- python_modules/libraries/dagster-components/dagster_components/components/pipes_subprocess_script_collection.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/resolvable_from_schema.py
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_transformer.py
This is not perfect yet, but provides a fairly condense syntax for dealing with collection types.
What we really need is a more dynamic engine that knows how to descend over the built-in `typing` types.
So that 
```python
@dataclass
class SomeObject(ResolvableFromSchema[SomeObjectSchema]):
specs: Annotated[
Sequence[AssetSpec],
DSLFieldResolver(AssetSpecResolutionSpec.resolver_fn(AssetSpec).from_seq),
]
```
Can become
```python
ResolvedAssetSpec: TypeAlias = Annotated[AssetSpec, DSLFieldResolver(...)]     # exact syntax tbd
@dataclass
class SomeObject(ResolvableFromSchema[SomeObjectSchema]):
specs:  Sequence[ResolvedAssetSpec]
```
but we can do that as a followup
BK
NOCHANGELOG
> [dg] Demonstrate pattern for how we can support sequences generically

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/10-tree-jaffle-platform.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/3-tree.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/workspace/2-tree.txt
- python_modules/libraries/dagster-components/dagster_components/core/component_defs_builder.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
We should include `defs/__init__.py` to communicate to people this is just a python package.
> [components] Add __init__.py to scaffolded project defs folder

- python_modules/dagster/dagster/_cli/definitions.py
- python_modules/dagster/dagster/_utils/error.py
- python_modules/dagster/dagster_tests/cli_tests/command_tests/definitions_command_projects/invalid_project_exc/invalid_project_exc/definitions.py
- python_modules/dagster/dagster_tests/cli_tests/command_tests/test_definitions_validate_command.py
When running `dg check defs`/`dagster definitions validate`, remove all dagster system frames, not just the ones before the user code error.
e.g.
```python
2025-03-06 10:25:57 -0800 - dagster - ERROR - Validation failed for code location definitions.py:
dagster._core.errors.DagsterInvalidDefinitionError: "invalid!op/name" is not a valid name in Dagster. Names must be in regex ^[A-Za-z0-9_]+$.
Stack Trace:
[9 dagster system frames hidden, run with --verbose to see the full stack trace]
File "/Users/ben/repos/dagster/python_modules/dagster/dagster_tests/cli_tests/command_tests/definitions_command_projects/invalid_project_exc/invalid_project_exc/definitions.py", line 4, in <module>
@dg.op(name="invalid!op/name")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[6 dagster system frames hidden]
```
Update test
> [dagster definitions validate] Truncate all system frames

- python_modules/dagster/dagster/_cli/definitions.py
- python_modules/dagster/dagster/_cli/dev.py
- python_modules/dagster/dagster/_core/workspace/context.py
- python_modules/dagster/dagster/_grpc/server.py
- python_modules/dagster/dagster/_utils/env.py
- python_modules/dagster/dagster_tests/cli_tests/command_tests/dagster_dev_command_tests/test_dagster_dev_command.py
- python_modules/dagster/dagster_tests/cli_tests/command_tests/test_definitions_validate_command.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/dev.py
Defaults similar behavior to `dagster definitions validate` for `dagster dev`, `dg dev`.
Before:
```python
2025-03-06 11:50:35 -0800 - dagster - INFO - Using temporary directory /Users/ben/repos/dagster/python_modules/dagster/dagster_tests/cli_tests/command_tests/definitions_command_projects/invalid_project_exc/invalid_project_exc/.tmp_dagster_home_cn04zjkx for storage. This will be removed when dagster dev exits.
2025-03-06 11:50:35 -0800 - dagster - INFO - To persist information across sessions, set the environment variable DAGSTER_HOME to a directory to use.
2025-03-06 11:50:35 -0800 - dagster.code_server - INFO - Starting Dagster code proxy server for file definitions.py in process 80665
2025-03-06 11:50:36 -0800 - dagster.code_server - INFO - Starting Dagster code server for file …
```
> [dagster dev] By default, collapse and deduplicate stack traces

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/2-shell-command-empty.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/custom-schema-resolution.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/empty.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/resolving-resolvable-field.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-build-defs.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-class-defined.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-config-schema.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-custom-scope.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-scaffolder.py
- python_modules/dagster-test/dagster_test/components/complex_schema_asset.py
- python_modules/libraries/dagster-components/dagster_components/__init__.py
- python_modules/libraries/dagster-components/dagster_components/components/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/components/definitions_component/component.py
- python_modules/libraries/dagster-components/dagster_components/components/pipes_subprocess_script_collection.py
- python_modules/libraries/dagster-components/dagster_components/components/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py
- python_modules/libraries/dagster-components/dagster_components/core/schema/resolvable_from_schema.py
- python_modules/libraries/dagster-components/dagster_components/test/basic_components.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions/local_component_sample/__init__.py
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/custom_scope_component/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_field_utilites.py
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_from_schema.py
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_model.py
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_transformer.py
- python_modules/libraries/dagster-dg/dagster_dg/templates/COMPONENT_TYPE/COMPONENT_TYPE_NAME_PLACEHOLDER.py.jinja
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils_tests/test_sample_yaml.py
Per discussion yesterday, we are going to refer to this system as `Resolved`.
Core renames:
- Schema —> Model. ResolveableModel
- ResolveableFromSchema —> ResolvedFrom
- ResolutionSpec → ResolvedKwargs
- FieldResolver.from_parent —> FieldResolver.from_model
BK
NOCHANGELOG
> [dg] Rename core concepts in Resolved

- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInput.tsx
Default to -1 index so that `enter` can continue to submit the query, but also so that it can select autocomplete entries if its not -1.
locally.
You can see the first item is no longer immediately highlighted now
> [selection input auto complete] Default to -1 index

- js_modules/dagster-ui/packages/ui-core/src/assets/AssetTable.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx
- js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedAssetRow.tsx
- js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedAssetTable.tsx
There's already logic to do this (used in the asset graph) but we need to prop drill the asset selection setter down from the catalog root.
locally. Will look into more jest tests in a follow up
> [Asset Selection + Catalog table] Make filtering by kind use asset selection

- js_modules/dagster-ui/packages/ui-core/src/selection/useSelectionInputLintingAndHighlighting.tsx
The error messages are not super human friendly but give more context that is useful than just saying "Unexpected input".
locally
before:
after:
> [Selection input] Use antlr error message

- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionAutoCompleteProvider.tsx
Renaming from Exact match because we allow wild cards here and the exact match label suggests otherwise.
> [Selection input autocomplete] Rename exact match -> `key` / `name`

- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_component_invariant_errors.py
Components right now must inherit from either `ResolvableModel` or `ResolveFrom`. This checks that invariant at load time.
Ideally we would detect this at class declaration time. A metaclass is difficult to do because the way our users can mixin other frameworks that themselves use metaclasses.
BK
NOCHANGELOG
> [dg] Better error message

- python_modules/libraries/dagster-components/dagster_components/cli/list.py
- python_modules/libraries/dagster-components/dagster_components/core/defs.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/list.py
- python_modules/libraries/dagster-dg/dagster_dg/defs.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_environment_validation.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py
Basic implementation of `dg list defs`. This is a project-scoped command that outputs tables showing the definitions defined by the target project. It currently lists assets, schedules, sensors, and jobs. It puts each type of definition in a separate table.
More thought is going to need to go in to how exactly to present all the metadata associated with various definition types. In this PR, only assets show a significant amount of metadata. Example output:
```
$ dg list defs
Assets
┏━━━━━━━━━┳━━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃ Key     ┃ Group   ┃ Deps  ┃ Kinds ┃ Description      ┃
┡━━━━━━━━━╇━━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ alpha   │ group_1 │       │ sling │                  │
│ beta    │ group_2 │       │ dbt   │ This is beta.    │
│ delta   │ group_2 │ alpha …
```
> [components] Add `dg list defs`

- python_modules/libraries/dagster-components/dagster_components/components/definitions_component/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions/definitions_object_multiple/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions/definitions_object_multiple/my_defs.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions/definitions_object_relative_imports/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions/definitions_object_relative_imports/my_defs.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions/definitions_object_relative_imports/some_file.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions/definitions_object_relative_imports/some_other_file.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_definitions_component.py
This changes the behavior of the DefinitionsComponent to explicitly handle cases where a `Definitions` object is defined. Previously, these objects would be ignored entirely.
NOCHANGELOG
> [components] Allow Definitions component to pick up raw Definitions objects

- python_modules/libraries/dagster-components/dagster_components/components/definitions_component/component.py
- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/core/component_decl_builder.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions_implicit/definitions_object_relative_imports/my_defs.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions_implicit/definitions_object_relative_imports/other_file.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions_implicit/definitions_object_relative_imports/some_file.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions_implicit/multiple_files/other_file.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions_implicit/multiple_files/some_file.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions_implicit/single_file/some_file.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_definitions_component_implicit.py
This changes the default behavior of the Definitions component to scan the entire directory for python files if no path is defined.
It then allows for the Definitions component to be used in cases where there is no `component.yaml` or `component.py` file available.
> [components] Allow for implicit defs loading

- python_modules/libraries/dagster-components/dagster_components/components/shim_components/asset.py
- python_modules/libraries/dagster-components/dagster_components/components/shim_components/base.py
- python_modules/libraries/dagster-components/dagster_components/components/shim_components/schedule.py
- python_modules/libraries/dagster-components/dagster_components/components/shim_components/sensor.py
- python_modules/libraries/dagster-components/dagster_components/core/component_decl_builder.py
- python_modules/libraries/dagster-components/dagster_components/dagster.py
- python_modules/libraries/dagster-components/dagster_components/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/list.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_environment_validation.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
This is a bit of a hack, which creates Components that represent raw definitions of assets, schedules, and sensors.
This lets you do stuff like:
```
dg scaffold asset some/path
dg scaffold schedule some/path
```
I needed to create components here so metadata about the scaffolder could make its way through to the dg CLI, but obviously the "correct" solution here is to separate out a command that forwards scaffolder-specific information.
NOCHANGELOG
> [dg] create shims classes for a selection of dagster definitions

- python_modules/libraries/dagster-polars/dagster_polars/io_managers/delta.py
- python_modules/libraries/dagster-polars/setup.py
the deltalake IOManager is broken on never versions of `deltalake`: 
```python
ValueError: Partition filters can only be used with PyArrow engine, use predicate instead. PyArrow engine will be deprecated in 1.0
File "/usr/local/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
yield
File "/usr/local/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 480, in iterate_with_context
next_output = next(iterator)
^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/dagster/_core/execution/plan/execute_step.py", line 767, in _gen_fn
gen_output = output_manager.handle_output(output_context, output.value)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> [dagster-polars, chore]: update to deltalake 0.25.0

- js_modules/dagster-ui/packages/ui-core/src/asset-selection/useAssetSelectionState.oss.tsx
- js_modules/dagster-ui/packages/ui-core/src/hooks/__tests__/useQueryPersistedState.test.tsx
- js_modules/dagster-ui/packages/ui-core/src/hooks/useQueryPersistedState.tsx
Add push behavior so that we can use this for selection syntax to allow *back* to go to the previous syntax.
jest + local testing
> Add `push` behavior to `useQueryPersistedState`

- python_modules/libraries/dagster-dg/dagster_dg/config.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_check_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/test_context.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Cleanup/enhancement of some of the TOML utilities we use for validation and modification of TOML files. The enhancements are needed upstack when we start adding `[[tool.dg.workspace.projects]]` entries.
- Change utility method `modify_pyproject.toml` to more general `modify_toml`
- Add `modify_toml_as_dict` to get a plain dict instead of a TOML document object. This is useful in config testing where it's fine to nuke styling and write the modified dict back as new TOML. Modifying the `TOMLDocument` object is more involved.
- Allow TOML paths used for TOML accessors to include array indices
This entire TOML util section will leave `dg` and become a part of a factored out utility package when we do that (if we cannot find a well-maintained library that supports this stuff, which I was …
> [components] Clean up TOML

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/workspace/3-pyproject.toml
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/workspace/7-scaffold-project.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/workspace/8-project-list.txt
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs_workspace.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/dev.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/init.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/list.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/config.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_init_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_validate_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/test_context.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
- Make the `tool.dg.workspace.projects` list the source of truth for the projects in a workspace. This replaces the behavior of just relying on the content of the hardcoded "projects" folder of the workspace.
- The elements of `tool.dg.workspace.projects` are called "project specs"-- currently there is just a single key, `path`, a path relative to the workspace root.
- If you choose to have `dg init` scaffold a project, it will always do so inside a created "projects" folder.
- `dg scaffold project` now expects its argument to be a path rather than just a name. Intermediate folders will be created for you.
- The `dg list project` command now prints a list of project paths instead of names.
> [RFC] [components] Make pyproject.toml source of truth for deployment code locations (BUILD-652)

- python_modules/dagster/dagster/_cli/definitions.py
- python_modules/dagster/dagster/_cli/workspace/cli_target.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/check.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/dev.py
This PR refactors the code path of `dg check defs` to eliminate this [code smell](https://github.com/dagster-io/internal/discussions/14241)
BK
NOCHANGELOG
> [dg] Refactor check defs to use context manager 

- js_modules/dagster-ui/packages/ui-core/src/app/DefaultFeatureFlags.oss.tsx
As titled
[ui] An updated asset selection syntax is now available in the asset graph, All assets, insights, and alerts. The new syntax  allows combining logical operators, lineage operators and attribute filters.
> Turn on asset selection syntax by default

- js_modules/dagster-ui/packages/ui-core/src/app/Util.tsx
- js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx
- js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/AssetNodeLineageGraph.tsx
- js_modules/dagster-ui/packages/ui-core/src/graph/OpEdges.tsx
- js_modules/dagster-ui/packages/ui-core/src/graph/asyncGraphLayout.ts
- js_modules/dagster-ui/packages/ui-core/src/hooks/useDebugChanged.tsx
- js_modules/dagster-ui/packages/ui-core/src/hooks/usePrevious.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/filterLogs.tsx
- js_modules/dagster-ui/packages/ui-core/src/search/useIndexedDBCachedQuery.tsx
Currently when you change filters in the asset graph it immediately shows a spinner while it calculates the new graph. One unintended side effect of this is that in the filter menu if you check a filter we immediately show the spinner and effectively only allow you to select 1 filter at a time. To remedy this, instead of showing the spinner, lets just add an indeterminate loading bar and keep the previous graph rendered until the new one is ready. This allows users to move fast while filtering without waiting for potentially slow layout re-rendering.
locally
https://github.com/user-attachments/assets/39a9147a-6a43-403d-a683-1160b42fb9b3
> [Asset Graph] Show an indeterminate loading bar instead of un-rendering graph and showing spinner.

- js_modules/dagster-ui/packages/ui-core/src/schedules/__tests__/humanCronString.test.ts
Really not sure how I didn't see this coming when I wrote these tests!
Fix DST issues in `humanCronString` by extracting the actual timezone shorthand name for the specified canonical timezone name.
`yarn jest humanCronString`
> [ui] Fix humanCronString.test for DST

- python_modules/dagster/dagster/_core/storage/runs/migration.py
```
Running migration:
Updating run storage...
Skipping already applied data migration: run_partitions
Skipping already applied data migration: run_repo_label_tags
Skipping already applied data migration: bulk_action_types
Starting data migration: run_backfill_id
Querying run storage.
Finished data migration: run_backfill_id
Starting data migration: backfill_job_name_and_tags
Querying run storage.
100%|██████████| 6/6 [00:00<00:00, 22.32it/s]
Finished data migration: backfill_job_name_and_tags
Starting data migration: backfill_end_timestamp
Querying run storage.
0%|          | 0/6 [00:00<?, ?it/s]
File "/.venv/bin/dagster", line 8, in <module>
sys.exit(main())
File "/.venv/lib/python3.9/site-packages/dagster/_cli/__init__.py", line 50, in main …
```
> Migration fix (backfill_end_timestamp)

- docs/docs/getting-started/quickstart.md
There is a bullet in the Quickstart that implies we're creating multiple assets in this tutorial when in fact we're creating only one.
> Correct the description of assets in the quickstart tutorial

- docs/docs/dagster-plus/features/alerts/configuring-an-alert-notification-service.md
Our MS Teams alerting docs still link to Microsoft connectors, which have been deprecated in favor of workflows. This PR updates the reference and instructions.
- https://linear.app/dagster-labs/issue/OPER-1663/update-msteams-webhook-instructions#comment-54f80344
Viewed docs locally.
NOCHANGELOG
> Update MS Teams alerts docs to reference workflows

- python_modules/libraries/dagster-dg/dagster_dg/cache.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/check.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg/utils/filesystem.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_check_commands.py
Adds some filesystem watching utils, used to power `dg component check --watch`. Users can run this in the background to get near-instant updates on the correctness of their components when they save a component file, add/remove a Python dependency etc.
I also imagine this being useful to auto-update the language server YAML schema file, e.g. `dg code-location generate-schema --watch`.
```sh
/Users/ben/repos/components_demo/my-deployment/code_locations/jaffle-platform/jaffle_platform/components/defs_example/component.yaml:1 -  Component type 'definidtions@dagster_components' not found.
| 
1 | type: definidtions@dagster_components
| ^ Component type 'definidtions@dagster_components' not found.
2 | 
3 | params:
4 |   definitions_path: definitions.py
| 
Updated at 12:56:36, watching for …
```
> [dg] Add filesystem watch utils, `dg components check --watch`

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/workspace/3-pyproject.toml
- python_modules/libraries/dagster-dg/dagster_dg/cli/init.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/config.py
- python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_init_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/test_context.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Add `tool.dg.workspace.new_project_options`. Currently this can only take two options:
- `use_editable_dagster`
- `use_editable_components_package_only`
If you `dg init` with either option it will be set in the workspace `pyproject.toml`, ensuring new projects are created with the corresponding option.
Since these options are internal, this should be considered a private detail for now, we will likely change it in the future when we have a stronger project scaffolding customization story.
Relevant prior discussion/decision: https://www.notion.so/dagster/Outstanding-dg-API-ergonomics-questions-1a318b92e462807a855ff198b6d285ae?pvs=4#1a318b92e46280a8bebef5351bb44334
New unit tests
> [components] Scaffold project options

- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/core/component_defs_builder.py
- python_modules/libraries/dagster-components/dagster_components_tests/code_locations/component_component_deps/defs/depends_on_my_python_defs/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/code_locations/component_component_deps/defs/depends_on_my_python_defs/definitions.py
- python_modules/libraries/dagster-components/dagster_components_tests/code_locations/component_component_deps/defs/my_python_defs/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/code_locations/component_component_deps/defs/my_python_defs/definitions.py
- python_modules/libraries/dagster-components/dagster_components_tests/code_locations/component_component_deps_custom_component/defs/depends_on_my_python_defs/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/code_locations/component_component_deps_custom_component/defs/depends_on_my_python_defs/custom_component.py
- python_modules/libraries/dagster-components/dagster_components_tests/code_locations/component_component_deps_custom_component/defs/my_python_defs/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/code_locations/component_component_deps_custom_component/defs/my_python_defs/custom_component.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/component_loader.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_cross_component_deps.py
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_custom_scope.py
- python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_pipes_subprocess_script_collection.py
Enables user code to depend on defs from a component in another file. This can be accessed directly through the `ComponentLoadContext`, which is provided to `build_defs` or newly available as a contextvar:
```python
class MyCustomComponent(Component):
def build_defs(self, context: ComponentLoadContext) -> dg.Definitions:
from my_module.defs import my_python_defs
assets_from_my_python_defs = cast(
Sequence[dg.AssetsDefinition],
context.build_defs_from_component_module(my_python_defs).assets,
)
@dg.asset(deps=assets_from_my_python_defs)
def downstream_of_all_my_python_defs():
pass
return dg.Definitions(assets=[downstream_of_all_my_python_defs])
```
```python
from my_module.defs import my_python_defs
ctx = ComponentLoadContext.current()
assets_from_my_python_defs = cast( …
```
> [dagster-components] Add ability to load defs from other components thru context

- python_modules/dagster/dagster/_grpc/proxy_server.py
- python_modules/dagster/dagster_tests/general_tests/grpc_tests/slow_grpc_repo.py
- python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_persistent.py
Before, we started the heartbeat clock right away, then started loading up the subprocess and loading code. If the latter took a while, the server would immediatley heartbeat fail as soon as the import finished.
New test that was failing before
Fixed an issue where `dagster dev` would fail to load code that took more than 45 seconds to import unless the `--use-legacy-code-server-behavior` flag was used.
> Fix issue where code that took more than 45 seconds to load was failing the initial code server heartbeat when using dagster dev

- python_modules/dagster/dagster/_cli/dev.py
Fixes a regression with the new dagster dev behavior - we were passing this log level through to the subprocesses but not using it in the parent process.
Run `dagster dev`, no more logspew about proxy servers and code servers
Run with --code-server-log-level=INFO, logspew returns
NOCHANGELOG
> Make dagster dev less logspew-y

- python_modules/dagster/dagster/_config/pythonic_config/resource.py
- python_modules/dagster/dagster/_core/execution/build_resources.py
- python_modules/dagster/dagster/_core/execution/context/init.py
- python_modules/dagster/dagster/_core/execution/context/invocation.py
- python_modules/dagster/dagster/_core/execution/context/system.py
- python_modules/dagster/dagster/_core/execution/context_creation_job.py
- python_modules/dagster/dagster/_core/execution/plan/compute.py
- python_modules/dagster/dagster/_core/execution/resources_init.py
- python_modules/dagster/dagster/_utils/test/__init__.py
- python_modules/dagster/dagster_tests/core_tests/test_job_init.py
- python_modules/dagster/dagster_tests/execution_tests/misc_execution_tests/test_async.py
- python_modules/libraries/dagster-dlt/dagster_dlt_tests/test_asset_decorator.py
- python_modules/libraries/dagstermill/dagstermill/manager.py
Add support for async context manager backed resources by passing the same event loop to resource init and core execution. 
The biggest bit of awkwardness here is that to ensure the same event loop is used for both resource init and execution in the direct execution case you have to manually pass the loop in to context creation and then use it to execute your asset/op. This is demonstrated in the test. 
resolves https://github.com/dagster-io/dagster/issues/27974
added tests
* `async def yield_for_execution`  is now supported on `ConfigurableResource`. An `event_loop` argument has been added to context builders to support direct execution.
> [resources] support async yield_for_execution

- js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNodeMenu.tsx
On the lineage page for an asset we don't show the asset selection syntax input (this seems to be intentional, but maybe we should revisit this decision at some point?). Currently the "Show upstream/downstream" options relies on the asset selection syntax input to work. Since this input doesn't exist on this page the options don't actually end up doing anything. So lets just not show them in this context.
manual testing:
> [Asset graph] Hide "show upstream/downstream" options in Asset lineage page

- python_modules/libraries/dagster-dbt/dagster_dbt/cloud/resources.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud/preview/test_specs.py
This PR adds the `load_dbt_cloud_asset_specs` and `load_dbt_cloud_check_specs` methods.
These methods leverages state-backed definitions. The state loader uses `build_dbt_specs` to create both asset and check specs - this function is used in dbt Core to load specs. This function takes a manifest file, which we fetch from dbt Cloud using `DbtCloudWorkspace.fetch_workspace_data`, and a `DagsterDbtTranslator`.
The goal here is to make sure that:
- assets for dbt Core and dbt Cloud are both loaded using the manifest file
- the same translator can be used with dbt Core or dbt Cloud.
```python
from dagster_dbt.cloud.resources import (
DbtCloudCredentials,
DbtCloudWorkspace,
load_dbt_cloud_asset_specs,
load_dbt_cloud_check_specs,
)
creds = DbtCloudCredentials( …
```
> [5/n][dagster-dbt] Implement load_dbt_cloud_asset_specs and load_dbt_cloud_check_specs

- python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/test_cache.py
`dg --clear-cache` would throw an ugly error if you tried to use it outside of a project context. This PR makes it work anywhere.
New unit test.
> [components] Allow `dg --clear-cache` to work anywhere (BUILD-733)

- python_modules/libraries/dagster-dg/dagster_dg/cli/shared_options.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
Adds a new environment variable `DG_USE_EDITABLE_DAGSTER`. When set, the `--use-editable-dagster` flag is on by default when scaffolding new projects.
I considered warning whenever `DAGSTER_GIT_REPO_DIR` is set and an editable option wasn't used, but this seemed too likely to generate a lot of test noise.
New unit test.
> [components] Add DG_USE_EDITABLE_DAGSTER env var

- python_modules/libraries/dagster-dg/dagster_dg/cli/dev.py
- python_modules/libraries/dagster-dg/setup.py
psutil is a heavy dependency, and SIGTERM seems to work just as well as SIGINT for terminating the dagster dev process.
BK, run uv tool run dg dev and terminate it with a signal -15 from the command line
> Remove psutil dependency from dagster-dg

- python_modules/dagster/dagster/_core/storage/db_io_manager.py
Causes Pyright violations in my code, because it doesn't make sense for a table name to come back `None` from this.
> Fix return type of the `get_table_name()` function

- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInput.tsx
Reset selected index so that if you close the dropdown and hit enter we don't end up submitting the last option you had selected when the dropdown was open.
manual testing
> [Selection input] Reset selected index when dialog is opened/closed

- python_modules/dagster/dagster/_cli/dev.py
Now that we're no longer logging on code server startup it can take a while before dagster dev logs anything. This moves the 'Launching Dagster services...' log line earlier so that it logs right away.
Run 'dagster dev' locally
NOCHANGELOG
> Move initial dagster dev log command earlier

- python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/beta/test_asset_specs.py
Fixes AD-913.
Setting a default group name on multi assets in `build_fivetran_assets_definitions` prevents users from customizing their group names later.
Additional test to cover this specific use case, BK
> [dagster-fivetran] Remove default group_name in build_fivetran_assets_definitions

- python_modules/libraries/dagster-airbyte/dagster_airbyte/asset_defs.py
- python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/beta/test_asset_specs.py
Fixes AD-914.
Setting a default group name on multi assets in `build_airbyte_assets_definitions` prevents users from customizing their group names later.
Additional test to cover this specific use case, BK
> [dagster-airbyte] Remove default group_name in build_airbyte_assets_definitions

- python_modules/dagster/dagster/_core/definitions/asset_job.py
- python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_job.py
The key issue here is that we were using `keys_by_input_name` as a way to determine which execution dependencies we cared about, when we actually have a kinda nuanced system for determining this, which depends on if the node contains only asset checks or not.
The code here is fairly verbose, but I wanted to factor it in a way that maximized explainability, given how weird this stuff is.
Fixed a bug that could cause invalid circular dependency errors when using asset checks with additional dependencies.
> Fix issue with cycle resolution when using additional_deps

- python_modules/libraries/dagster-components/dagster_components/components/definitions_component/component.py
- python_modules/libraries/dagster-components/dagster_components/components/shim_components/asset.py
- python_modules/libraries/dagster-components/dagster_components/components/shim_components/schedule.py
- python_modules/libraries/dagster-components/dagster_components/components/shim_components/sensor.py
- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/core/component_decl_builder.py
- python_modules/libraries/dagster-components/dagster_components_tests/cli_tests/test_commands.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/component_loader.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_definitions_component_implicit.py
- python_modules/libraries/dagster-components/dagster_components_tests/utils.py
Assorted bugfixes and improvements for the new scaffolding functionality.
Core Stuff:
1. changed asset / sensor / schedule scaffolding to write to asset.py / sensor.py / schedule.py instead of definitions.py
2. changed the scaffolding to output a ruff-compliant file (no leading newline, two newlines between imports and definition)
3. allow all ComponentDeclNode types to access the `path` property
Test Stuff:
4. updated the test framework to add `__init__.py` files in the relevant places (this caused some existing tests to fail before the above changes)
5. updated the test framework to avoid caching issues when dynamically creating multiple projects
Most of these changes are actually fixing up test code. I was able to confirm that without those changes, tests would still pass if i ran them …
> [dg] demo fixes for scaffolding

- python_modules/libraries/dagster-components/dagster_components/components/shim_components/asset.py
- python_modules/libraries/dagster-components/dagster_components/components/shim_components/base.py
- python_modules/libraries/dagster-components/dagster_components/components/shim_components/schedule.py
- python_modules/libraries/dagster-components/dagster_components/components/shim_components/sensor.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
Doesn't create a new folder for each scaffolded asset, and instead writes directly into a path.
A bit hacky right now as the scaffolding system currently auto-creates a directory for you, which I end up removing, but I'm thinking through a larger update to the scaffolding system anyway so I figured the patch solution isn't hurting anything for now
NOCHANGELOG
> [dg] Update output location of sensor / schedule / asset

- python_modules/libraries/dagster-dg/dagster_dg/templates/PROJECT_NAME_PLACEHOLDER/.gitignore.jinja
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
Include `.gitignore` with "!lib" in scaffolded projects. This will override upstream ignores of "lib", which Github's default Python gitignore includes.
Tweaked unit test and also manually tested that this actually works to override upstream ignores.
> [components] Include .gitignore with "!lib" in scaffolded projects

- python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/ComponentDetails.tsx
Move example up on the page, since schema is a huge unweildy json blob right now.
> [dg docs][ui] Move schema after example yaml

- python_modules/libraries/dagster-dg/dagster_dg/cli/check.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_check_defs_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_docs_commands.py
Nearly identical impl to #28307 which implicitly runs `dg check yaml` before `dg check defs`.
> [dg] implicitly run check yaml before check defs

- docs/CONTRIBUTING.md
- docs/README.md
- docs/docs/about/contributing.md
Closes DOC-850.
- Updates contributing guide for documentation at `/about/contributing`
- Updates `docs/CONTRIBUTING.md` with additional guidance
n/a
NOCHANGELOG
> [docs] update /about/contributing guide

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/custom-schema-resolution.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-blueprint.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-build-defs.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-class-defined.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-custom-scope.py
- python_modules/dagster-test/dagster_test/components/complex_schema_asset.py
- python_modules/libraries/dagster-components/dagster_components/__init__.py
- python_modules/libraries/dagster-components/dagster_components/components/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/components/pipes_subprocess_script_collection.py
- python_modules/libraries/dagster-components/dagster_components/components/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components/resolved/core_models.py
- python_modules/libraries/dagster-components/dagster_components/resolved/model.py
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_field_utilites.py
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_from_schema.py
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_model.py
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_transformer.py
This updates renames `FieldResolver` to `Resolver` and adds
* `Resolver.from_annotation()` takes care of resolving potentially nested `ResolvedFrom` types from their associated `ResolvableModel`
* `Resolver.from_resolved_kwargs(KwargsCls)` takes care of resolving potentially nested target type from the associated ResolvableModel type.
* `Resolver.from_template_injection()` marks fields that expect to be resolved via template injection. 
Additionally
* deriving field resolvers fails on unexpected types instead of assuming things will work.
* `ResolvedKwargs` is now generic over both its `TModel` source and its `T` target type to facilitate nested resolution.
updated and existing tests
> [resolved] field resolution update

- python_modules/dagster/dagster/_core/definitions/asset_out.py
- python_modules/dagster/dagster/_core/definitions/asset_spec.py
- python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py
I noticed the `kinds` argument was missing in `dagser.AssetOut`. This PR fixes it. 
Added a test
[core] Added `kinds` argument to `dagster.AssetOut`. Asset kinds can now be specified in `@multi_asset`.
> [core] support kinds in AssetOut

- docs/Makefile
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs.py
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/utils.py
- examples/docs_beta_snippets/tox.ini
When the docs integrations tests fail, the tempdirs are cleaned up and evidence of the project state at the time the test failed is erased. This PR adds a new makefile target `make regenerate_cli_snippets_and_test_debug` which runs tests in `/tmp/cli_snippets/{test_file_name}`, so that the results are preseved afterwards to inspect in the case of success or failure.
```sh
$ make regenerate_cli_snippets_and_test
...
============================================= short test summary info ==============================================
FAILED docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs.py::test_components_docs_index - subprocess.CalledProcessError: Command 'dg check yzaml && echo "PWD=$(pwd);"' returned non-zero exit status 2.
Snippet regeneration failed. …
```
> [docs tests] Add debug makefile entrypoint for docs tests

- python_modules/libraries/dagster-dg/dagster_dg/utils/editor/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_configure_editor_commands.py
When the specified editor isn't found on the PATH, raises an exception rather than printing (and later failing on invocation of the command).
Tested locally, verified early exit.
> [dg] Exit properly upon not finding editor in PATH

- python_modules/dagster/dagster/_daemon/daemon.py
- python_modules/dagster/dagster/_scheduler/scheduler.py
This allows us to instrument how far behind the expected "next iteration time" for a schedule we're running
> PLA-1052 add scheduler delay instrumentation

- js_modules/dagster-ui/packages/ui-core/src/asset-selection/__tests__/isUnmatchedValueQuery.test.ts
- js_modules/dagster-ui/packages/ui-core/src/asset-selection/input/AssetSelectionInput.oss.tsx
- js_modules/dagster-ui/packages/ui-core/src/asset-selection/isUnmatchedValueQuery.ts
A lot of users are using their muscle memory and doing:
1. Type partial asset key
2. Hit enter
3. Error -> No results
4. Give up.
Lets just do the right thing for these users by automatically converting their invalid query into a valid one!
https://github.com/user-attachments/assets/f8533af6-81db-4b38-8e2e-ed2a6e18640e
> [Asset Selection] Make submitting an invalid query with only a single value convert to a key substring filter.

- python_modules/dagster/dagster/_utils/error.py
- python_modules/dagster/dagster_tests/core_tests/test_errors.py
I figured out why `raise ... from None` was not working as expected when we went through serializable errors - we were not respecting the flag that gets set.
https://docs.python.org/3/library/exceptions.html
added test
> [SerializableErrorInfo] respect __surpress_context__

- python_modules/libraries/dagster-components/dagster_components/components/dbt_project/component.py
- python_modules/libraries/dagster-components/dagster_components/components/sling_replication_collection/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_dbt_project.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_sling_integration_test.py
Rehash of #28334 which depends on #28438 to do the heavy lifting. Now it's just a one-liner!
Makes the base `AssetSpec` generated by the underlying default Dagster translator available as scope for dbt & Sling.
> [dagster-components] Make "spec" available in scope for asset_attributes

- python_modules/libraries/dagster-components/dagster_components/cli/list.py
- python_modules/libraries/dagster-components/dagster_components/core/component.py
- python_modules/libraries/dagster-components/dagster_components/scaffold.py
- python_modules/libraries/dagster-components/dagster_components/test/basic_components.py
- python_modules/libraries/dagster-components/dagster_components_tests/cli_tests/test_commands.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/component.py
This lets non-component-types get discovered within a given project. Instead of just checking for subclasses of Components, we now check for objects with `__dg_library_object__` set.
NOCHANGELOG
> [dg] Allow for non-components to be loaded and listed as library-objects

- js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx
- js_modules/dagster-ui/packages/ui-core/src/graph/asyncGraphLayout.ts
- js_modules/dagster-ui/packages/ui-core/src/workers/workerSpawner.ts
1. Have a layout worker sitting idly by to handle next layout request asap. Improves initial load a bit.
2. Noticed locally that I had 2 layout workers spinning because the layout props changed before the previous layout completed.  In this case just terminate the previous worker before spawning the new one.
local testing
> [Asset Graph][perf] Prepare layout worker in advance + allow only a single worker at a time

- python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/ComponentDetails.tsx
- python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/ComponentSchema.tsx
- python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/css/ComponentSchema.module.css
- python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/schema/ArrayTag.tsx
- python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/schema/TypeTag.tsx
- python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/schema/css/TypeTag.module.css
Some tweaks to the nested JSONSchema display, including:
- Move the schema back above the example
- Better determination of expandability
- Fix overflow and wrapping for smaller viewports
Still a little concerned about pathological nesting cases here and various flavors of schema that this might not handle fully yet, but it seems decent for the current test case.
https://github.com/user-attachments/assets/581802ec-c685-4c08-a69b-3d56fb01eaed
Would like to try this on more examples.
dg docs, do some expanding/collapsing on the schema view.
> [dg docs] Iteration on JSONSchema

- python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/ComponentDetails.tsx
- python_modules/libraries/dagster-dg/dagster_dg/docs/app/css/globals.css
- python_modules/libraries/dagster-dg/dagster_dg/docs/app/packages/[pkg]/[component]/ComponentPage.module.css
- python_modules/libraries/dagster-dg/dagster_dg/docs/app/packages/[pkg]/[component]/page.tsx
- Example `component.yaml`
- Lock scrolling for TOC on the right
dg docs
> [dg docs] Change example header, lock TOC

- python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/ComponentDetails.tsx
- python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/ComponentHeader.tsx
- python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/PackageDetails.tsx
- python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/css/ComponentHeader.module.css
- python_modules/libraries/dagster-dg/dagster_dg/docs/app/page.tsx
- python_modules/libraries/dagster-dg/dagster_dg/docs/package.json
- python_modules/libraries/dagster-dg/dagster_dg/docs/yarn.lock
Render component description with react-markdown.
- In the list view of components, use `plaintext` rendering since we render these descriptions within an anchor.
- In the component page itself, use `remark-gfm` to get the usual markdown output.
ts, lint.
dg docs serve, verify rendering. `yarn build` the `docs` project, then `npx serve` to verify that the static build also works correctly.
> [dg docs] Render description with react-markdown

- python_modules/dagster/dagster/_utils/error.py
- python_modules/dagster/dagster_tests/cli_tests/command_tests/dagster_dev_command_tests/test_dagster_dev_command.py
- python_modules/dagster/dagster_tests/cli_tests/command_tests/test_definitions_validate_command.py
Treat all of our code as "system frames" instead of just `dagster` module specifically
motivation was turning
https://gist.github.com/alangenfeld/73d62dce1c0b0699bcfaea33ee0113af
in to 
https://gist.github.com/alangenfeld/2f4bf5b1ba1215dd58b3854afb853ec9
manual, can add test
> [defs validate] hide frames for all dagster libraries

- python_modules/libraries/dagster-airlift/dagster_airlift/core/load_defs.py
Super minor tweak, but I found myself confused by this type signature & I think it's a better user facing experience to have the full signature available on hover rather than making the user navigate into the library impl to understand what to pass.
> [dagster-airlift] rm alias from user-facing type signature

- python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/ComponentDetails.tsx
- python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/ComponentHeader.tsx
- python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/PackageDetails.tsx
- python_modules/libraries/dagster-dg/dagster_dg/docs/app/page.tsx
- python_modules/libraries/dagster-dg/dagster_dg/docs/package.json
- python_modules/libraries/dagster-dg/dagster_dg/docs/yarn.lock
Some description tweaks:
- In the package list view, truncate the config description to its first line. Use regular markdown formatting, minus anchors, since these are linked items and we want to avoid nesting an anchor within an anchor.
- In the component view, render the full markdown.
TS, lint. Test dev and build versions to verify correct rendering, and that there are no errors due to invalid DOM.
> [dg docs] Truncate description with markdown

- python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/PackageTree.tsx
- python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/PackageTreeInner.tsx
- python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/css/PackageTree.module.css
- python_modules/libraries/dagster-dg/dagster_dg/docs/app/layout.tsx
Some improvements to the dg docs left nav.
- Allow packages to be expanded/collapsed without actually navigating anywhere
- When loading a package or component page, automatically expand the left nav to show it in the package tree
- Use a different icon for the package
TS, lint. Test left nav behavior as described, in both dev and build versions.
> [dg docs] Left nav improvements

- examples/docs_beta_snippets/docs_beta_snippets/guides/dg/migrating-definitions/2-definitions-before.py
- examples/docs_beta_snippets/docs_beta_snippets/guides/dg/migrating-project/6-initial-definitions.py
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/dg/test_migrating_definitions/my-existing-project/my_existing_project/definitions.py
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/dg/test_migrating_definitions/test_migrating_definitions.py
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/dg/test_migrating_project/my-existing-project/my_existing_project/definitions.py
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/dg/test_migrating_project/test_migrating_project.py
isort has different behavior depending on what environment you run in, so just ignore isort and hide the skip in the output
NOCHANGELOG
> [dg] Fix docs snippets build

- python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/beta/conftest.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/beta/test_asset_specs.py
Fixes AD-936.
This PR handles incomplete and broken connectors fetched from a Fivetran workspace.
Context:
Incomplete connectors in a Fivetran workspace are causing an exception in `fetch_fivetran_workspace_data`.
```
Stack Trace:
File "/Users/maximearmstrong/Documents/Repositories/dagster-io/dagster/examples/test/definitions.py", line 14, in <module>
@fivetran_assets(
^^^^^^^^^^^^^^^^
[1 dagster system frames hidden]
File "/Users/maximearmstrong/Documents/Repositories/dagster-io/dagster/python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_decorator.py", line 118, in fivetran_assets
for spec in workspace.load_asset_specs(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1 dagster system frames hidden]
File "/Users/maximearmstrong/Documents/Repositories/dagster-io/dagster/python_modules/libraries/d …
```
> [dagster-fivetran] Fix fetch_fivetran_workspace_data for incomplete and broken connectors

- docs/sphinx/_ext/sphinx-mdx-builder/README.md
- docs/sphinx/_ext/sphinx-mdx-builder/sphinxcontrib/mdxbuilder/__init__.py
- docs/sphinx/_ext/sphinx-mdx-builder/sphinxcontrib/mdxbuilder/builders/mdx.py
- docs/sphinx/_ext/sphinx-mdx-builder/sphinxcontrib/mdxbuilder/writers/mdx.py
- docs/src/styles/custom.scss
- docs/yarn.lock
Closes DOC-820.
Adds source links to GitHub for API docs.
Currently points to _master_, however, when we automate the release process, we will be able to update this to point to the target version branch.
```
yarn build-api-docs && yarn start
```
- [docs] added source links to API docs
> [docs] adds `[source]` links to API docs

- python_modules/libraries/dagster-sling/dagster_sling/resources.py
- python_modules/libraries/dagster-sling/dagster_sling_tests/test_streaming_replicate.py
This pull request add streaming option for SlingResource Replicate function 
motivation:
Old dagster sling method doesn't support streaming sling log to dagster log and push that information only after sling complete. This makes it hard to track pipelines process in real time.  Furthermore, asset materialization only happens after sling complete all streams. This might make it vulnerable to longer jobs that fail after some pipeline complete causing differentiated between asset metadata and real data in the database (only possibility not sure if real problem observed yet.) 
New streaming option was developed with these two limitations in mind. Optional streaming offers a possibility to stream output to log in real time solving first problem. Also, the method is developed so that asset …
> [dagster-sling] allow streaming option for SlingResource replicate function.

- python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
broke main bc the run id wasn't in the runs table so the archive event log storage wasn't able to store the right archive status
> [fix] Use a run that is in the runs table for event log storage tests

- python_modules/libraries/dagster-dg/dagster_dg/cli/init.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/shared_options.py
- python_modules/libraries/dagster-dg/dagster_dg/config.py
- python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_check_defs_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_dev_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_init_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/test_context.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Summary:
Once we are releasing components and dg in parallel with dagster, we don't need this anymore (and adding dagster-shard is not playing nicely with it). So remove the flag altogether and install everything editably.
> Remove components only editable flag

- python_modules/dagster-webserver/dagster_webserver_tests/webserver/test_asset_events.py
- python_modules/dagster/dagster/__init__.py
- python_modules/dagster/dagster/_core/definitions/asset_check_evaluation.py
- python_modules/dagster/dagster/_core/execution/context/op_execution_context.py
- python_modules/dagster/dagster/_core/execution/plan/compute.py
- python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py
- python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
Lets you yield an AssetCheckEvaluation from an op, just like you can yield an AssetMaterialization. Requires some light storage changes to relax the restriction that a PLANNED event already exists for every asset materialization.
New test cases
`AssetCheckEvaluation` can now be yielded from Dagster ops to log an evaluation of an asset check outside of an asset context.
> Allow yielding AssetCheckEvaluation objects from ops

- python_modules/libraries/dagster-looker/setup.py
2.0 release appears to have broken this import;
```
from liquid.builtin.literal import LiteralNode, Token
```
BK
[dagster-looker] Added a `python-liquid<2.0` pin.
> Add python-liquid pin

- python_modules/dagster/dagster/_core/workspace/load_target.py
- python_modules/dagster/dagster_tests/cli_tests/workspace_tests/toml_tests/test_toml_loading.py
Fix reading and test of accessing `tool.dg.code_location_target_module` from `dagster dev`. This was looking for the wrong variable and inadequately tested.
New unit test.
> [components] Fix code_location_target_module reading for dagster dev

- js_modules/dagster-ui/packages/ui-core/src/runs/RunActionButtons.tsx
The backend is expecting [the old step selection syntax](https://github.com/dagster-io/dagster/blob/d301505e189a1636c8675da65c0674af227c2b9e/python_modules/dagster/dagster/_core/execution/api.py#L287-L292) format [here](https://github.com/dagster-io/dagster/blob/d301505e189a1636c8675da65c0674af227c2b9e/python_modules/dagster/dagster/_core/selector/subset_selector.py#L385): 
tested locally that re-execution from steps works
[ui] Fixed a bug where Re-execute from selected would fail to launch asset-checks.
> [Runs][Re-execute from selected] pass legacy step selection

- python_modules/dagster/dagster/_core/definitions/asset_check_evaluation.py
- python_modules/dagster/dagster_tests/definitions_tests/test_replace_event_metadata.py
Fixes AD-943. Supports with_metadata in AssetCheckEvalution, which is required for AssetCheckEvaluation to be used in DbtEventIterator in subsequent PR
> Support with_metadata for AssetCheckEvaluation

- python_modules/dagster/dagster/_daemon/asset_daemon.py
This is usually no longer relevant, but logs on every fresh dagster dev spinup for a new instance. Only log if it actually does any work.
BK, run dagster dev locally on a fresh instance
NOCHANGELOG
> Remove spammy log line on each initial 'dagster dev' invocation

- python_modules/libraries/dagster-components/setup.py
Summary:
Once dagster-components is being released weekly in lockstep with dagster, it should be pinned to dagster like all our other integrations.
Test Plan:
Do a dry run OSS release, check resulting pins in the release branch
> Pin dagster-components to dagster

- python_modules/libraries/dagster-components/dagster_components/resolved/core_models.py
- python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_transformer.py
Resolves #28530
Unit test has been updated
- [dagster-components] fix how `AssetSpecModel` resolves dep asset keys
> [dagster-components] fix how `AssetSpecModel` resolves dep asset keys

- js_modules/dagster-ui/packages/ui-core/src/assets/LaunchAssetChoosePartitionsDialog.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/MultipartitioningSupport.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/MultipartitioningSupport.test.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/usePartitionHealthData.test.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/usePartitionHealthData.tsx
After you create a dynamic partition, asset health data refreshes but some assets data may be pulled from cache while other data is fresh. This creates a scenario where your selection of assets have inconsistent number of partitions. 
We've been supporting this by sidestepping an assertion in the code. This PR goes a step further and adds code + tests to clarify the desired behavior in this case and removes the assertion. 
To test this I simulated the asset health data loading very slowly and noticed a separate bug where smashing Launch Run after creating a new dynamic partition would send `null` as the partitionName if none of the assets' health info had refreshed.  I made the code detect that this is happening and briefly disable the Launch button.  We could alternatively display a …
> [ui] Handle intermediate states after creating dynamic partitions

- python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
- python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/__init__.py
- python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py
- python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/check_operators.py
- python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/utils.py
- python_modules/dagster/dagster_tests/declarative_automation_tests/automation_condition_tests/builtins/test_check_condition.py
This is a powerful utility for `any_deps_match` / `all_deps_match`, and is valuable for similar reasons for `any_checks_match` / `all_checks_match`.
Also refactored the `has_allow_ignore` method out into a separate utils file for cleanliness
NOCHANGELOG
> [da] Add .allow() and .ignore() to CheckOperator

- python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_cli_event.py
- python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_cli_invocation.py
- python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_event_iterator.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_checks.py
Additional tests with bk
[dagster-dbt] `AssetCheckEvaluations` are now yielded from `ops` leveraging `DbtCliResource.cli(...)` when asset checks are included in the dbt asset lineage.
> Emit AssetCheckEvaluation instead of AssetObservation when an op runs dbt tests that map to asset checks

- docs/vercel.json
https://dagsterlabs.slack.com/archives/C03ATLSRZMF/p1741698330657639
It's not recommended to leave the behavior undefined, as per https://vercel.com/docs/project-configuration#trailingslash
Another example: https://docs.dagster.io/dagster-plus/deployment/hybrid/ will 404; https://docs.dagster.io/dagster-plus/deployment/hybrid will redirect
(In the end, #28387 fixed the architecture issue, but this should still be an improvement, given Vercel explicitly warns against leaving trailing slash behavior undefined.)
Defined the redirect behavior on the Dagster website with respect to trailing slashes to avoid broken links.
> [docs] Specify vercel.json trailing slash behavior

- python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
- python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/operands.py
- python_modules/dagster/dagster_tests/declarative_automation_tests/automation_condition_tests/builtins/test_newly_requested_condition.py
Previously, we used the cursor of the root context to determine if a given entity was newly requested, which doesn't work in cases where the asset key is not the same as they of the root target.
This stashes the full daemon cursor on the context and changes the previous_requested_subset from a property to a function that takes the asset key.
We still want to keep the `_cursor` around as a reference to the root target's cursor as other properties/methods use this in ways that do actually want that cursor (e.g. getting the previous max storage id for an asset).
Added test failed before, succeeds now.
Fixed issue with `AutomationCondition.newly_requested()` which could cause it to fail when nested within `AutomationCondition.any_deps_match()` or `AutomationCondition.all_deps_match()`.
> [dg] Update newly_requested to allow invocation in deps context

- js_modules/dagster-ui/packages/ui-core/src/asset-selection/__tests__/SyntaxUpgraderVisitor.test.ts
- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInput.tsx
Theres a Heisenberg visual glitch if you try to set the value of the codemirror instance in a layout effect. Since it's inconsistent I suspect it's be a timing issue with their own internal layout effects so moving the `setValue` call to a rAF which seems to consistently upgrade the syntax visually.
> [SelectionInput] Move `instance.setValue` into raf. 

- python_modules/dagster-graphql/dagster_graphql/test/utils.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_data_versions.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_reconstruction_metadata.py
- python_modules/dagster/dagster/_core/definitions/decorators/repository_decorator.py
- python_modules/dagster/dagster/_core/definitions/definitions_load_context.py
- python_modules/dagster/dagster/_core/definitions/reconstruct.py
- python_modules/dagster/dagster/_grpc/server.py
- python_modules/dagster/dagster_tests/execution_tests/engine_tests/test_step_delegating_executor.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/dagster_defs/mapped_defs.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink_tests/integration_tests/test_e2e_mapped.py
Fix a longstanding regression in reconstruction metadata routing that was introduced in #25436. Prior to that PR, reconstruction metadata during initial repository load was stored on `Definitions` objects in the `metadata` field. Integrations that used the reconstruction metadata API were expected to return a `Definitions` object that would be merged into the final `Definitions` object for the code location. This final `Definitions` object would then contained the merged reconstruction metadata for any integrations using the API:
```
my_integration_resource = MyIntegrationResource(...)
integration_defs = build_my_integration_defs(my_integration_resource)
defs = Definitions.merge(
integration_defs,
)
```
#25436 aimed to eliminate the restriction that integrations using reconstruction …
> Fix reconstruction metadata routing through DefinitionsLoadContext

- js_modules/dagster-ui/packages/ui-core/src/automation/MergedAutomationRoot.tsx
- js_modules/dagster-ui/packages/ui-core/src/hooks/__tests__/useQueryAndLocalStoragePersistedState.test.tsx
- js_modules/dagster-ui/packages/ui-core/src/hooks/__tests__/useQueryPersistedState.test.tsx
- js_modules/dagster-ui/packages/ui-core/src/hooks/useQueryPersistedState.tsx
Repair an issue when filtering on multiple tags. This was reported for Automation filtering specifically, but since this uses `useQueryPersistedState`, the same issue would occur elsewhere.
It is worth noting that since tags are treated as an `AND` filter and not an `OR` filter, so users may still end up with empty result sets that they didn't anticipate. (This is not a bug.)
Tags are defined as `{key: string; value: string}`, but currently, when we encode these in the URL, we use `bracket` indexing in `qs`. Thus, an array of tag objects like this:
...results in an encoded output like this:
```
tags%5B%5D%5Bkey%5D=foo&tags%5B%5D%5Bvalue%5D=bar&tags%5B%5D%5Bkey%5D=zombo&tags%5B%5D%5Bvalue%5D=com
```
This decodes as:
```
tags[][key]=foo&tags[][value]=bar&tags[][key]=zombo&tags[][value]=com …
```
> [ui] Fix tag filter encoding

- python_modules/dagster/dagster/_daemon/asset_daemon.py
- python_modules/dagster/dagster_tests/declarative_automation_tests/daemon_tests/test_asset_daemon.py
Can be used by operators to temporarily disable AMP evaluation for a particular asset key without code changes being required.
New test case
> Env var to skip certain AMP keys

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/1-help.txt
- python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/plus.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/plus_tests/test_plus_login_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_environment_validation.py
- python_modules/libraries/dagster-shared/dagster_shared/plus/config.py
- python_modules/libraries/dagster-shared/dagster_shared/plus/login_server.py
- python_modules/libraries/dagster-shared/dagster_shared/utils/__init__.py
Moves the Plus CLI auth flow to dagster-shared, impls in the `dg` CLI as `dg plus login`.
A corresponding internal PR will cut over to using the shared impl for the `dagster-cloud` CLI.
Unit test.
> [dg] Add `dg plus login` CLI flow

- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/resources.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/conftest.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_resources.py
Fixes AD-947.
Users can pass a custom ad hoc job name to their DbtCloudWorkspace object instead of using the default name created by Dagster.
Additional test with bk
> [dagster-dbt] Enable user-defined job name in DbtCloudWorkspace

- python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py
- python_modules/dagster/dagster/_core/storage/event_log/base.py
- python_modules/dagster/dagster/_core/storage/partition_status_cache.py
- python_modules/dagster/dagster/_utils/caching_instance_queryer.py
- python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
In https://github.com/dagster-io/internal/pull/14045 I update the name of the method used to check if planned events are stored in the table to encompass failed events too. this propogates that change to OSS
> update AssetKeyTable schema check method name

- python_modules/dagster/dagster/_core/definitions/metadata/metadata_value.py
Fixes #16743
This PR updates the TableRecord documentation to reflect the current API. The existing documentation showed an outdated parameter-based constructor format which no longer works. I've updated the examples to demonstrate the correct method of creating TableRecord objects using the new data dictionary format.
The motivation for this change is to prevent user confusion and errors that arise from following outdated documentation. Issue #16743 reported that users attempting to follow the current documentation examples were encountering errors because the API has changed to require a data dictionary parameter rather than individual parameters.
Environment Setup
1. Create a fork
2. Create a branch for an issue
3. Followed environment setup
To run the Dagster documentation website …
> docs(metadata): update TableRecord documentation - issue #16743

- docs/docs/dagster-plus/deployment/management/deployments/deployment-settings-reference.md
Addresses [AD-722](https://linear.app/dagster-labs/issue/AD-772/[ib]-document-that-sso-default-role-can-be-set-to-no-access)
`NO_ACCESS` setting for `sso_default_role` was not documented. Also fixed some typos on the same page. 
👀
> [docs] document that sso_default_role can be set to NO_ACCESS

- python_modules/libraries/dagster-dbt/dagster_dbt_tests/conftest.py
Cloud v2 tests are included in dbt core test suite because of how dbt tests are selected (pytest.mark), include them in dbt cloud test suite instead.
Before:
After:
BK
> [dagster-dbt] Include cloud v2 tests in dbt cloud test suite

- .github/workflows/build-docs.yml
- docs/dagsterVersions.json
- docs/docusaurus.config.ts
Closes DOC-757.
- Makes current link in release dropdown the most recent version (eg. 1.10.4)
- Updates GH action to deploy to `main.archive.dagster.io` on push to _master_
- Updates GH action Production deployment on push to `release-*` prefixed branches
- Updates GH action to only deploy previews on `event_name == 'pull_request'`
- Removes `docs-prod` target for deployments as we will deploy new previews on merget to `master`
---
NOCHANGELOG
> [docs] adhere to weekly release procedure for docs.dagster.io

- js_modules/dagster-ui/packages/ui-core/src/instance/backfill/RunsFeedBackfillPage.tsx
If you have enough backfill runs to trigger scrolling and the "daemon not running" alert is visible, the runs feed table was overflowing off the page by ~2 rows following the change I made in #28503.
Tested the scroll behavior of all three tabs with and without the "daemon not running" alert
> [ui] Fix overflow of long runs feed table on backfill page

- python_modules/dagster/dagster/_core/instance/__init__.py
- python_modules/dagster/dagster/_core/storage/event_log/base.py
- python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py
- python_modules/dagster/dagster/_core/storage/legacy_storage.py
- python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
OSS counterpart to https://github.com/dagster-io/internal/pull/14334
Allows us to store failed to materialize events on the `AssetEntry`. Also has the event log storage stub method for `fetch_failed_materializations`
> add materialization failure attrs to AssetEntry and `fetch_failed_materialization` method stubs

- python_modules/libraries/dagster-components/dagster_components/resolved/context.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/validation_tests/test_component_validation.py
Include a snippet of the relevant yaml when printing out errors that occur during check defs
example from test output: 
https://gist.github.com/alangenfeld/53551b1914c96ac182f3e8514b2b4289
updated tests
> [dg] yaml preview in check defs errors

- python_modules/libraries/dagster-components/dagster_components/resolved/context.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/validation_tests/test_component_validation.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/check_utils.py
- python_modules/libraries/dagster-shared/dagster_shared/yaml_utils/source_position.py
For most of the check defs errors, we know we want to point at the value in the yaml file and not they key - so add a flag that says to do that to `source_error`
updated tests
```
2025-03-14 15:45:24 -0500 - dagster - ERROR - Validation failed for code location jaffle-platform:
dagster_components.resolved.context.ResolutionException: /Users/alangenfeld/playground/dg/jaffle-platform/jaffle_platform/defs/ingest_files/component.yaml:7 - attributes.replications.0.asset_attributes.metadata
|
5 |   - path: replication.yaml
6 |     asset_attributes:
7 |       metadata: "{{ barf() }}"
|                       ^ 'barf' is undefined
|
UndefinedError: 'barf' not found in scope, available scope is: env, automation_condition, stream_definition, spec
Stack Trace:
[12 dagster system frames hidden, run …
```
> [resolved] add flag to point at value in yaml error snippets

- python_modules/libraries/dagster-components/dagster_components/resolved/model.py
- python_modules/libraries/dagster-components/dagster_components/utils.py
* `at_path` in to `asset_attributes` in `resolve_translator`
* avoid using the `from_model` resolver in the default recurse case 
* `from_seq` adds index (got lost in rebases) 
before
```
|
2 |
3 | attributes:
4 |   replications:
|               ^ 'barf' is undefined
5 |   - path: replication.yaml
6 |     asset_attributes:
7 |       metadata: "{{ barf() }}"
|
```
after
```
|
5 |   - path: replication.yaml
6 |     asset_attributes:
7 |       metadata: "{{ barf() }}"
|                       ^ 'barf' is undefined
|
```
> [resolved] tweaks for accurate yaml pathing

- python_modules/dagster/dagster/_core/definitions/events.py
- python_modules/dagster/dagster/_core/events/__init__.py
- python_modules/dagster/dagster/_core/instance/__init__.py
- python_modules/dagster/dagster/_core/storage/event_log/base.py
- python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py
- python_modules/dagster/dagster/_core/storage/legacy_storage.py
- python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
Small refactor of the `AssetFailedToMaterializeData` class to accept an `AssetMaterializationFailure` class. This class is like the `AssetMaterialization` and `AssetObservation` classes. We'll need the `AssetMaterializationFailure` class in order to report runless failed materializations (ie for airlift) and it makes some of the GQL changes in the stacked PR follow existing convention a bit better
internal pr https://github.com/dagster-io/internal/pull/14413
> AssetMaterializationFailure class

- docs/docusaurus.config.ts
- docs/src/plugins/sidebar-scroll-into-view/index.js
Closes DOC-888.
Introduces plugin to automatically `scrollIntoView()`the active left sidebar item.
```
plugins: [
require.resolve('./src/plugins/sidebar-scroll-into-view'),
],
``` 
This is a temporary workaround until it is re-introduced upstream (pending since 2022): [see source code](https://github.com/facebook/docusaurus/blob/f31bfec3c9a7e9e032a36ccd9b405b0e2c2f6957/packages/docusaurus-theme-common/src/hooks/useTOCHighlight.ts#L158).
* https://github.com/facebook/docusaurus/pull/6748
* https://github.com/facebook/docusaurus/issues/6319
* https://github.com/facebook/docusaurus/issues/7980
Confirmed working as expected on localhost.
- [docs] automatically scroll left sidebar into view on direct link to documentation
> [docs] fix scroll into view for sidebar

- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/client.py
- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/resources.py
- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/types.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/conftest.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_resources.py
Fixes AD-949.
This PR uses the project name and environment name, if available, to create the ad hoc job. We fallback to project ID and environment ID if the names are not returned in the API responses - the name field is not required in both responses.
Updated tests with BK. 
Tested locally with a live instance:
> [dagster-dbt] Improve default ad hoc job name for DbtCloudWorkspace

- js_modules/dagster-ui/packages/ui-components/src/components/Toaster.tsx
- js_modules/dagster-ui/packages/ui-components/src/components/__stories__/Toaster.stories.tsx
- js_modules/dagster-ui/packages/ui-core/src/app/AppProvider.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/useReportEventsDialog.tsx
- js_modules/dagster-ui/packages/ui-core/src/instance/backfill/useReexecuteBackfill.tsx
- js_modules/dagster-ui/packages/ui-core/src/instance/backfill/useResumeBackfill.tsx
- js_modules/dagster-ui/packages/ui-core/src/partitions/BackfillMessaging.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunUtils.tsx
We received user feedback that with the new toasts, kicking off a materialization does not currently allow command-click to view the launched run in a new tab. This is a regression from previous toasts, which just rendered a link when an href was provided.
To resolve this, allow `showSharedToaster` to receive a `custom` action, which allows rendering a custom element in the toast. This lets callsites specify an `AnchorButton` to enable react-router-based navigation on click, or command-click to open the link in a new tab.
This required moving `GlobalStyleProvider` under the `BrowserRouter` provider in the `AppProvider` root, in order to enable react-router links to be rendered within toasts. This seems safe to me, since `GlobalStyleProvider` is mostly responsible for injecting global …
> [ui] Allow toast actions to be links

- python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
Right now, when building the global asset graph, we merge multiple copies of the same asset into a canonical definition.
This generally prefers executable assets to specs, but provides no disambiguation if the only representations for an asset are non-executable specs.
This can lead to a poor UX if, for example, a user adds a kind-and-description-augmented spec to one code location and in another location has a spec autogenerated for an upstream dependency. It's very possible for the bare, auto-generated spec to take precedence.
This PR  de-prioritizes autogenerated specs in this disambiguation logic.
> When merging assets from multiple code locations, autogenerated specs are now prioritized lower than customized external asset specs.
> [ez] When merging external assets from multiple code locations, prefer non-stub asset specs

- python_modules/libraries/dagster-dbt/dagster_dbt_tests/conftest.py
- python_modules/libraries/dagster-dbt/tox.ini
Even with their own marker, kitchen sink tests are collected by pytest - they are not executed, but we raise an exception in the kitchen test suite when env vars are not set, which is enough to break dbt tests, see [here](https://buildkite.com/dagster/dagster-dagster/builds/115687#0195b4f1-e08a-4eae-acdc-100d8977bd99).
This PR also removes the kitchen sink marker to avoid confusion - `--ignore=./kitchen-sink` excludes the tests, not the marker.
BK
> [dagster-dbt] Exclude kitchen sink from pytest in .tox

- python_modules/dagster/dagster/_core/definitions/asset_graph_subset.py
When you create an AssetBackfill from the point of failure, and the original root asset had all of its partitions succeed, this creates a target AssetGraphSubset that looks like:
```python
AssetGraphSubset(
non_partitioned_keys=[...],
partitions_subsets_by_key={
AssetKey("root"): DefaultPartitionsSubset([]),
...
}
)
```
That's totally fine and expected! And the asset backfill code mostly graciously handles finding the new roots and all that. The issue is this line: https://sourcegraph.com/github.com/dagster-io/dagster/-/blob/python_modules/dagster/dagster/_core/execution/asset_backfill.py?L239
Where we check if we have successfully found all of the partitions in the target set by mapping from the root partitions. The thing is... we have! It's just that the target set has that …
> [asset-backfill] Fix bug when target subset contains empty PartitionsSubset

- js_modules/dagster-ui/packages/ui-core/src/ticks/SensorDryRunDialog.tsx
When testing sensors, we can visualize requests to add dynamic partitions, but the `Launch all` action does not apply dynamic partition requests.
This change applies the dynamic partition mutation requests associated with a test sensor result.
https://github.com/user-attachments/assets/94d6eed3-4e95-4ec7-a79c-0a6c847554c8
- Applying changes from sensor test results now also apply changes from dynamic partition requests
> add dynamic partitions from sensor test result

- examples/docs_beta_snippets/docs_beta_snippets/guides/dg/dagster-definitions/1-scaffold.txt
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/dg/test_dagster_definitions.py
- python_modules/libraries/dagster-components/dagster_components/components/shim_components/asset.py
- python_modules/libraries/dagster-components/dagster_components/components/shim_components/base.py
- python_modules/libraries/dagster-components/dagster_components/components/shim_components/schedule.py
- python_modules/libraries/dagster-components/dagster_components/components/shim_components/sensor.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_environment_validation.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
This updates the traditional dagster def scaffolding logic:
1. `dg scaffold asset` -> `dg scaffold dagster.asset`
2. Scaffolded files now have functions with the name of the definition populated
3. Raise a nicer-looking exception if the user supplies an invalid scaffolding path
"integration" test with the docs system handles actually instantiating these in a "real" environment.
workflow is basically
`dg scaffold dagster.asset my_great_asset.py` 
this creates a file called `my_great_asset.py` which has a stub asset-decorated function `def my_great_asset(context: AssetExecutionContext)`
NOCHANGELOG
> [dg] Polish for scaffolding traditional dagster definitions

- js_modules/dagster-ui/packages/ui-core/src/search/__tests__/useIndexedDBCachedQuery.test.tsx
- js_modules/dagster-ui/packages/ui-core/src/search/useIndexedDBCachedQuery.tsx
- js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/__tests__/WorkspaceContext.test.tsx
Goal here is to extract the core logic outside of the hooks so that I can use this logic outside of the context of React in my upcoming workspace refactor.
existing jest tests for `useIndexedDBCachedQuery` + `WorkspaceContext` tests which make extensive use of it.
Also local testing.
> Refactor `useIndexedDBCachedQuery`

- js_modules/dagster-ui/packages/ui-core/jest/mocks/ComputeGraphData.worker.ts
- js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx
Currently when you have the catalog view dialog open there are two instances of `useAssetGraphData`. one that belongs to the dialog and the other belongs to the catalog table in the background. Currently what is happening is that the dialog one is killing the worker for the one that belongs to the page causing an infinite loading state when you save your catalog view.
Tested locally.  Hard to write jests tests since it involves workers but in my queue is to look into improving how we test workers.
[ui] Fixed an issue where updating a catalog view caused an infinite loading state.
> [Asset selection filtering] Move workerSpawner into hook 

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/18-dg-list-component-types.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/7-dg-list-component-types.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/8-dg-list-component-types.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/3-dg-list-component-types.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/dg/migrating-project/8-dg-list-component-types.txt
- python_modules/libraries/dagster-components/dagster_components/components/defs_module/component.py
- python_modules/libraries/dagster-components/dagster_components/dagster.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/integration_test_defs/definitions_autoload/definitions_at_levels_with_config/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/integration_test_defs/definitions_autoload/definitions_at_levels_with_config/defs_object/asset.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/integration_test_defs/definitions_autoload/definitions_at_levels_with_config/defs_object/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/integration_test_defs/definitions_autoload/definitions_at_levels_with_config/defs_object/definitions.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/integration_test_defs/definitions_autoload/definitions_at_levels_with_config/defs_object/inner/asset.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/integration_test_defs/definitions_autoload/definitions_at_levels_with_config/loose_defs/asset.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/integration_test_defs/definitions_autoload/definitions_at_levels_with_config/loose_defs/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/integration_test_defs/definitions_autoload/definitions_at_levels_with_config/loose_defs/inner/asset.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/integration_test_defs/definitions_autoload/definitions_at_levels_with_config/loose_defs/inner/innerer/another_level/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/integration_test_defs/definitions_autoload/definitions_at_levels_with_config/loose_defs/inner/innerer/another_level/in_init/__init__.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/integration_test_defs/definitions_autoload/definitions_at_levels_with_config/loose_defs/inner/innerer/another_level/innerest/definitions.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/integration_test_defs/definitions_autoload/definitions_at_levels_with_config/loose_defs/inner/innerer/asset.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/integration_test_defs/definitions_autoload/definitions_at_levels_with_config/top_level.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_definitions_autoload.py
This is an alternative version of https://github.com/dagster-io/dagster/pull/28624, in which we create a wrapper component type instead of a new config file format.
The functionality is generally the same -- I copied over the exact test from the other PR, and just updated the files:
Before:
```yaml
asset_post_processors:
- target: "*"
attributes:
tags:
foo: "bar"
```
After:
```yaml
type: dagster_components.dagster.DefsModuleComponent
attributes:
asset_post_processors:
- target: "*"
attributes:
tags:
foo: "bar"
```
(and renaming from defs.yaml to component.yaml)
The main differences that I think make this a bit less appealing long-term:
1. It can't be used inside a single component's directory (because it itself is a component)
2. Right now, a component conceptually "takes over" the …
> [dg] DefsModuleComponent

- python_modules/libraries/dagster-dg/dagster_dg/cli/plus.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/plus_tests/test_plus_login_command.py
- python_modules/libraries/dagster-shared/dagster_shared/plus/config.py
- python_modules/libraries/dagster-shared/dagster_shared/utils/config.py
Based on feedback in https://github.com/dagster-io/dagster/pull/28586#issuecomment-2743680003, remaps `~/.dg/config` to live in platform-dependent `config.toml` file.
Updates the Plus config shared code to automatically read from `~/.dagster_cloud_cli/config` (YAML) or dg `config.toml`, nested under the `cli.plus` field.
Update tests.
> [dagster-shared][dg] Use toml for dg cli config, plus config

- python_modules/automation/Makefile
- python_modules/automation/automation/parse_dataproc_configs.py
- python_modules/automation/automation/parse_spark_configs.py
- python_modules/automation/automation/printer.py
- python_modules/automation/automation_tests/test_parse_dataproc_configs.py
- python_modules/automation/automation_tests/test_parse_spark_configs.py
- python_modules/automation/automation_tests/test_printer.py
- python_modules/libraries/dagster-gcp/dagster_gcp/dataproc/configs_dataproc_cluster.py
- python_modules/libraries/dagster-gcp/dagster_gcp/dataproc/configs_dataproc_job.py
- python_modules/libraries/dagster-gcp/dagster_gcp/dataproc/types_dataproc_cluster.py
- python_modules/libraries/dagster-gcp/dagster_gcp/dataproc/types_dataproc_job.py
In order to update the Spark configuration, I needed to be able to get the automation working.
Local runs and BK.
Only additions:
```diff
(dagster) deepyaman@Deepyamans-MacBook-Pro dagster % diff <(python dataproc_job_config_before.py) <(python dataproc_job_config_after.py)
0a1,7
> ('driverSchedulingConfig_memoryMb', 'Int')
> ('driverSchedulingConfig_vcores', 'Int')
> ('flinkJob_args', 'Array')
> ('flinkJob_jarFileUris', 'Array')
> ('flinkJob_mainClass', 'String')
> ('flinkJob_mainJarFileUri', 'String')
> ('flinkJob_savepointUri', 'String')
15a23,27
> ('prestoJob_clientTags', 'Array')
> ('prestoJob_continueOnFailure', 'Bool')
> ('prestoJob_outputFormat', 'String')
> ('prestoJob_queryFileUri', 'String')
> ('prestoJob_queryList_queries', 'Array')
24a37
> ('scheduling_maxFailuresTotal', …
```
> Fix automation of Spark and Dataproc configuration

- python_modules/automation/automation/parse_spark_configs.py
- python_modules/libraries/dagster-aws/dagster_aws/emr/configs_spark.py
- python_modules/libraries/dagster-spark/dagster_spark/configs_spark.py
Updated to latest Spark version without changing the set of fields pulled.
BK
```diff
(dagster) deepyaman@Deepyamans-MacBook-Pro dagster % diff <(python emr_config_before.py) <(python emr_config_after.py)         
2,11c2,4
< ('spark_blacklist_application_fetchFailure_enabled', 'StringSourceType')
< ('spark_blacklist_application_maxFailedExecutorsPerNode', 'StringSourceType')
< ('spark_blacklist_application_maxFailedTasksPerExecutor', 'StringSourceType')
< ('spark_blacklist_enabled', 'StringSourceType')
< ('spark_blacklist_killBlacklistedExecutors', 'StringSourceType')
< ('spark_blacklist_stage_maxFailedExecutorsPerNode', 'StringSourceType')
< ('spark_blacklist_stage_maxFailedTasksPerExecutor', 'StringSourceType')
< ('spark_blacklist_task_maxTaskAttemptsPerExecutor', 'StringSourceType')
< …
```
> Update `parse_spark_configs.py` to use latest docs

- docs/docs/guides/labs/dg/multiple-projects.md
- examples/docs_beta_snippets/docs_beta_snippets/guides/dg/workspace/1-dg-init.txt
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/dg/test_dg_docs_workspace.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/init.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_init_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Let you go through scaffolding fully via CLI. You can pass in an empty string to skip the project scaffold.
BK, run same commands locally
[dagster-dg] The `dg init` command now accepts optional `--workspace-name` and `--project-name` options to allow scaffolding an initial workspace and project via CLI options instead of prompts.
> Allow passing in the workspace name and/or project name to 'dg init'

- python_modules/libraries/dagster-dg/dagster_dg/cli/check.py
- python_modules/libraries/dagster-dg/dagster_dg/config.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/utils/telemetry.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_environment_validation.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_telemetry.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/test_context.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
- python_modules/libraries/dagster-shared/dagster_shared/plus/config.py
Adds a `@cli_telemetry_wrapper` annotation which logs calls to the dg CLI. For this PR, just adds to the check CLI commands:
```python
@check_group.command(name="defs", cls=DgClickCommand)
@dg_global_options
@click.pass_context
@cli_telemetry_wrapper
def check_definitions_command(
...
) -> None: ...
```
This can be disabled through the config file at `~/.dg/config.yaml` or in `$DAGSTER_HOME/dagster.yaml`
New tests that ensure all commands have coverage and that check the shape of output telemetry.
> [dg] Introduce telemetry wrapper

- python_modules/libraries/dagster-airlift/dagster_airlift/in_airflow/base_asset_operator.py
- python_modules/libraries/dagster-airlift/dagster_airlift/in_airflow/dag_proxy_operator.py
- python_modules/libraries/dagster-airlift/dagster_airlift/in_airflow/proxied_state.py
- python_modules/libraries/dagster-airlift/dagster_airlift/in_airflow/proxying_fn.py
- python_modules/libraries/dagster-airlift/dagster_airlift/in_airflow/task_proxy_operator.py
- python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/in_airflow_tests/import_script.py
- python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/in_airflow_tests/import_script_with_airflow.py
- python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/in_airflow_tests/test_no_dagster_install.py
Beta annotations were creating an implicit dependency on dagster from within the `in-airflow` subpackage.
This is the second time this has happened unintentionally. To ensure it doesn't happen again, I've added a new test which news up a fresh uv venv, and ensures that the airflow-only install path works correctly.
New unit test
- [dagster-airlift] APIs from within the `[in-airflow]` submodule have had the beta banner removed.
> [dagster-airlift] remove beta annotations from in-airflow subpackage

- python_modules/libraries/dagster-components/dagster_components/core/defs_module.py
- python_modules/libraries/dagster-components/dagster_components/utils.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/integration_test_defs/pythonic_components/relative_import/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/integration_test_defs/pythonic_components/relative_import/other_file.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_pythonic_components.py
`load_module_from_path` can be replaced by the superior `load_defs_relative_python_module` on `ComponentLoadContext` which handles relative imports
BK
* Bug fix: Python files with Pythonic Components (i.e. defined with `@component`) can now contain relative imports.
> [dg] Eliminate load_module_from_path

- .buildkite/dagster-buildkite/dagster_buildkite/pipelines/dagster_oss_main.py
- .buildkite/dagster-buildkite/dagster_buildkite/steps/docs.py
- .buildkite/dagster-buildkite/dagster_buildkite/utils.py
Closes DOC-859.
- Adds buildkite workflow for building docs: `yarn build-api-docs`, `yarn build`, `yarn test`
- Adds check for `BUILDKITE_DOCS` string in buildkite message to force check when `docs/` or `examples/` are unmodified
bk
NOCHANGELOG
> [buildkite] Adds step to build docs in buildkite

- python_modules/libraries/dagster-dlt/dagster_dlt/asset_decorator.py
- python_modules/libraries/dagster-dlt/dagster_dlt_tests/test_asset_decorator.py
Fixes
[#25720](https://github.com/dagster-io/dagster/issues/25720).
This PR should allow dlt pipelines to be able to backfill multiple partitions without the dreaded [concurrency bug](https://github.com/dlt-hub/dlt/issues/1102)
Test suite and manual testing.
> [dagster-dlt] Add backfill policy to dlt_assets, defaulting to single-run

- .buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
- .buildkite/dagster-buildkite/dagster_buildkite/utils.py
The kitchen sink for dbt cloud was under examples and not libraries in buildkite, hence why it was only running on no skip.
BK
> [buildkite] Add dbt Cloud kitchen sink to library packages

- examples/docs_beta_snippets/docs_beta_snippets_tests/test_all_files_load.py
Fixes the build, not sure where bk is currently pulling the dagster-cloud version from but confirmed that locally these snippets work fine with the latest version of the internal repo.
Will investigate how to get these under test again tomorrow, just fixing the build for now
NOCHANGELOG
> [fix] Fix build by ignoring problematic dagster-plus snippets

- docs/docs/guides/automate/declarative-automation/customizing-automation-conditions/example-customizations.md
This section is shown twice on the site, 
https://docs.dagster.io/guides/automate/declarative-automation/customizing-automation-conditions/example-customizations#wait-for-all-blocking-asset-checks-to-complete-before-executing
Simply removed a few repeated lines
> Remove repeated section in example-customizations.md

- python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_cli_event.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_materialization_execution_duration.py
There is a problem with `LogModelResult` log messages, if a model is incremental-microbatch: such logs lack `node_finished_at` and `node_status` properties. These properties are required for the freshness metrics and the fact that they are missing makes [dagster-dbt/.../dbt_cli_event.py](https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_cli_event.py#L351) skip such logs is why they never get transformed into asset events consumed by Datadog.
Tested e2e after importing this version of `dagster-dbt` into Dagster cloud, executing `dbt build` for an incremental-microbatch model in Snowflake --> I observed `ASSET_MATERIALIZATION` event being emitted.
> patch: fallback to `data` dbt log properties when creating asset event

- docs/docs/guides/operate/graphql/graphql-client.md
For some reason the `PyObject` that links to [the API docs for the GraphQL Python Client](https://docs.dagster.io/api/python-api/libraries/dagster-graphql#python-client) does not display the name of the client methods. This PR hard codes in the method names and links to their sections.
Before:
After:
👀
> [docs] hard code names of GraphQL API Python client method

- python_modules/libraries/dagster-airlift/dagster_airlift/test/shared_fixtures.py
`make wipe` is failing
https://buildkite.com/dagster/dagster-dagster/builds/116060/steps?sid=0195cda7-07e8-4b3f-a6cd-825a136fd624
because something is writing to the directory while the `rm -rf` is processing which i assume is this airflow process
so wait for the process to exit before moving on 
bk
> [dagster-airlift] wait for process termination in test fixture

- docs/vercel.json
Closes DOC-951.
Confirmed redirect worked as expected on preview deployment:
https://dagster-docs-9b7i8pplc-elementl.vercel.app/guides/build/external-pipelines/aws/aws-emr-containers-pipeline
NOCHANGELOG
> [docs] remove duplicate entry for EMR guide redirect in vercel.json

- python_modules/libraries/dagster-components/dagster_components/cli/list.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/list.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py
Summary:
Make this command create an instance, which causes it to load from a local .env file.
New test case
[dagster-dg] `dagster list defs` will now read environment variables from a local .env file if present when constructing the definitions.
> Inject env vars in dagster-components list definitions

- python_modules/dagster/dagster/_core/definitions/run_request.py
Closes DOC-955.
- Fixes misplaced docstring for `RunRequest` affecting API docs
* Docstring was placed after parameters instead of class definition
`yarn build-api-docs && yarn start`
NOCHANGELOG
> Fixes misplaced docstring affecting API docs for RunRequest

- docs/vercel.json
Closes DOC-968.
- Removes redundant redirects as configured at domain level in Vercel; ensures these domains aren't crawled
NOCHANGELOG
> [docs] remove unused redirects: docs-preview, new-docs

- docs/sphinx/sections/api/apidocs/schedules-sensors.rst
Also added `MultiAssetSensorDefinition`. While it's marked superseded, that's helpful info for people still using it.
Local build.
> DOC-956 Add @multi_asset_sensor to API docs

- js_modules/dagster-ui/packages/ui-core/src/selection/SelectionAutoCompleteProvider.tsx
- js_modules/dagster-ui/packages/ui-core/src/selection/__tests__/SelectionAutoComplete.test.ts
as titled
jest + manual testing
[ui] Fixes an issue with the Run step selection input autocomplete where it would suggest `key:"*substring*"` instead  of `name:"*substring*"`.
> [SelectionAutoComplete] Use primaryAttributeKey for substring match suggestion

- python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_decorator.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py
`replace_attributes` is now a method of `AssetSpec`, but it used to be a function of the `asset_spec` module. Fix example to be accurate with the current state.
> [dagster-fivetran] Remove replace_attributes import from docstring

- docs/sphinx/sections/api/apidocs/libraries/dagster-ssh.rst
- python_modules/libraries/dagster-ssh/dagster_ssh/resources.py
Closes DOC-954.
Adds docstrings to `dagster-ssh` class and methods.
NOCHANGELOG
> [docs] update API docs for dagster-ssh

- python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/operands.py
- python_modules/dagster/dagster_tests/declarative_automation_tests/automation_condition_tests/builtins/test_initial_evaluation_condition.py
This is actually more aligned with the purpose of this condition, as you could imagine having an unpartitioned asset with `AutomationCondition.eager()` being turned into a static-partitioned asset with 100s of partitions and experiencing the bad behavior of all partitions updating.
It's also more accurate that this is the "initial_evaluation" of those partitions in this case.
The `AutomationCondition.initial_evaluation` condition has been updated to become true for all partitions of an asset whenever the PartitionsDefinition of that asset changes, rather than whenever the structure of the condition changes.
> [da] Update initial_evaluation condition to only detect partitions_def changes

- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/client.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/conftest.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_resources.py
- python_modules/libraries/dagster-dbt/kitchen-sink/dagster_dbt_cloud_kitchen_sink_tests/test_client_methods.py
This PR adds the list_run_artifacts method that will be needed in the polling sensor. We need this because not all runs will have a `run_results.json` artifact, so we'll want to request and verify that it is in the list of artifacts for a given run before fetching it.
New tests with BK
> [dagster-dbt] Add list_run_artifacts to DbtCloudWorkspaceClient

- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/19-dg-scaffold-jdbt.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/9-dg-scaffold-sling-replication.txt
- examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/4-scaffold-instance-of-component.txt
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs.py
- examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs_creating_a_component.py
- python_modules/libraries/dagster-components/dagster_components/components/sling_replication_collection/component.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_custom_help_format.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_environment_validation.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_launch_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
When you scaffold a component, you can now do this via
`dg scaffold foo.bar.Component` instead of `dg scaffold component foo.bar.Component`.
Essentially, this makes scaffolding a uniform action that can be taken against any scaffoldable object, rather than having special-casing for components.
We very likely should rework all the special-purpose commands (e.g. `dg scaffold workspace`) to use the `scaffold_with` framework, but that will require some updates / extension to the ScaffolderSnap to represent the "scope" of the command (i.e. are you scaffolding a completely parallel directory tree (project, workspace), something that lives in an arbitrary spot in a given project (component-type), or something that lives in the `defs` module (dagster.asset, any component)
When scaffolding a …
> [dg] Remove `component` subcommand

- python_modules/libraries/dagster-dg/tox.ini
- scripts/templates_create_dagster_package/tox.ini.tmpl
To help understand where speedup opportunities can be found.
> output the duration of the slowest 10 dagster-dg tests in buildkite

- examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/pyspark/dagster_code.py
It's important to return the result after closing the session, to avoid [this race condition](https://github.com/dagster-io/dagster/blob/b985d57aadc7d9bf88d8dcbd32b16d3487e433cc/python_modules/dagster/dagster/_core/pipes/utils.py#L706-L713)
Fix a bug in example code for pyspark
> Fix a bug in the pyspark guide example code

- docs/docs/guides/automate/sensors/index.md
We don't document anywhere else what this value can also be so users would have to hunt it down in the source code: https://github.com/dagster-io/dagster/blob/23d649b22c4f60b1ee60d51d331bcb076ae20cb8/python_modules/dagster/dagster/_core/definitions/sensor_definition.py#L78
👀
> [docs] Note that DefaultSensorStatus can be STOPPED

- docs/yarn.lock
Bumps the npm_and_yarn group with 1 update in the /docs directory: [vite](https://github.com/vitejs/vite/tree/HEAD/packages/vite).
Updates `vite` from 6.2.2 to 6.2.3
- [Release notes](https://github.com/vitejs/vite/releases)
- [Changelog](https://github.com/vitejs/vite/blob/v6.2.3/packages/vite/CHANGELOG.md)
- [Commits](https://github.com/vitejs/vite/commits/v6.2.3/packages/vite)
updated-dependencies:
- dependency-name: vite dependency-type: indirect dependency-group: npm_and_yarn ...
NOCHANGELOG
> [docs] Bump vite in /docs in the npm_and_yarn group across 1 directory

- js_modules/dagster-ui/packages/ui-core/src/automation/MergedAutomationRoot.tsx
In automation tag filtering, we're depending on the `__typename` key/value pair that I discarded in https://github.com/dagster-io/dagster/pull/28583. Tag filtering is currently broken because of its removal. Revert that change.
I think I missed this because the tag set that I was checking appeared to result in an expected empty set.
View automations with a tag filter, verify that it works correctly. Add multiple tags to filter, verify that this continues to work correctly.
[ui] Fix tag filtering on automations list.
> [ui] Restore __typename to tag filtering on automations

- js_modules/dagster-ui/packages/ui-core/src/runs/__tests__/RunFilterInput.test.tsx
- js_modules/dagster-ui/packages/ui-core/src/ui/BaseFilters/__stories__/useFilters.stories.tsx
- js_modules/dagster-ui/packages/ui-core/src/ui/BaseFilters/__tests__/useTimeRangeFilter.test.tsx
- js_modules/dagster-ui/packages/ui-core/src/ui/BaseFilters/useTimeRangeFilter.tsx
Similar to the change I made to useStaticSetFilter in https://github.com/dagster-io/dagster/pull/24772.
Make useTimeRangeFilter controlled.
jest + local testing used with https://github.com/dagster-io/dagster/pull/28755
> Make useTimeRangeFilter controlled

- python_modules/dagster/dagster/_config/pythonic_config/config.py
- python_modules/dagster/dagster/_core/definitions/metadata/metadata_set.py
- python_modules/dagster/dagster/_core/definitions/tags/tag_set.py
- python_modules/libraries/dagster-shared/dagster_shared/dagster_model/pydantic_compat_layer.py
fix up some callsite where we are calling `model_fields` on the instance instead of the class generating new warnings
```
pydantic.warnings.PydanticDeprecatedSince211: Accessing this attribute on the instance is deprecated, and will be removed in Pydantic V3. Instead, you should access this attribute from the model class. Deprecated in Pydantic V2.11 to be removed in V3.0.
```
bk
> update model fields access

- examples/docs_snippets/docs_snippets/guides/components/index/18-dg-list-component-types.txt
- examples/docs_snippets/docs_snippets/guides/components/index/7-dg-list-component-types.txt
- examples/docs_snippets/docs_snippets/guides/components/index/8-dg-list-component-types.txt
- examples/docs_snippets/docs_snippets/guides/components/shell-script-component/3-dg-list-component-types.txt
- examples/docs_snippets/docs_snippets/guides/dg/migrating-project/8-dg-list-component-types.txt
- python_modules/libraries/dagster-components/dagster_components/dagster.py
- python_modules/libraries/dagster-components/dagster_components/lib/defs_module/component.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/integration_test_defs/definitions_autoload/definitions_at_levels_with_config/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/integration_test_defs/definitions_autoload/definitions_at_levels_with_config/defs_object/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/integration_test_defs/definitions_autoload/definitions_at_levels_with_config/loose_defs/component.yaml
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/integration_test_defs/definitions_autoload/definitions_at_levels_with_config/loose_defs/inner/innerer/another_level/component.yaml
As title
The `DefsModuleComponent` has been renamed to `DefsFolderComponent`.
> [dg] Rename DefsModuleComponent

- js_modules/dagster-ui/packages/ui-components/src/palettes/ColorName.tsx
- js_modules/dagster-ui/packages/ui-components/src/palettes/colorNameToVar.tsx
- js_modules/dagster-ui/packages/ui-components/src/theme/darkNoRedGreenThemeColors.tsx
- js_modules/dagster-ui/packages/ui-components/src/theme/lightNoRedGreenThemeColors.tsx
- js_modules/dagster-ui/packages/ui-components/src/theme/lightThemeColors.tsx
The mapping on dataviz `green` colors goes to a nonexistent color in colorblind themes, which leads to a JS error when we try to extract the color for Insights line charts. Fix this by mapping to a core cobalt color instead.
Also clean up a couple of unused color names.
Switch to system colorblind theme, view Insights. Verify that the chart loads, with no JS errors.
[ui] Fix line charts for colorblind themes.
> [ui] Fix colorblind color mapping in Insights

- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/resources.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/conftest.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_reconstruction.py
- python_modules/libraries/dagster-dbt/pytest.ini
- python_modules/libraries/dagster-dbt/setup.py
Updates `fetch_workspace_data` to use the state loader. The goal is to avoid reloading the workspace data more than once when using the method in the polling sensor (subsequent PR)
New tests with bk
> [dagster-dbt] Leverage state-backed defs in DbtCloudWorkspace.fetch_workspace_data()

- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/client.py
- python_modules/libraries/dagster-dbt/kitchen-sink/dagster_dbt_cloud_kitchen_sink_tests/test_client_methods.py
Updates the `get_runs_batch` method to return the total count of runs. `_make_request` is also updated to support this feature. This is required for the polling sensor.
Updated test with BK.
> [dagster-dbt] Support total_count in DbtCloudWorkspaceClient.get_runs_batch

- js_modules/dagster-ui/packages/ui-components/src/components/PageHeader.tsx
This is the same fix from https://github.com/dagster-io/dagster/pull/25752 back in November, it looks like it got squashed out on the same day i what I think was a merge conflict mishap.
Before:
After:
Also tested this on the job page, which has the same problem, and verified that this additional padding does not impact other pages like the asset header, because 52-(8px x 2) leaves enough room for buttons.
> [ui] Fix padding on headers when they wrap

- js_modules/dagster-ui/packages/ui-core/src/instigation/TickHistory.tsx
- js_modules/dagster-ui/packages/ui-core/src/sensors/SensorDetails.tsx
- js_modules/dagster-ui/packages/ui-core/src/sensors/__tests__/SensorDetails.test.tsx
https://linear.app/dagster-labs/issue/OPER-1581/improve-cursor-display-for-run-status-sensor-in-ui-and-disallow
New test, manual testing against impacted sensors
Before:
After:
> [ui] Clean up rendering of serialized cursor tuples on sensor details page

- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_integrity.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
This adds a test to make sure that `dg` successfully executes in an isolated environment. This prevents accidentally depending on packages only present in the test env in runtime code.
New test, made sure it fails when there is a test dependency import in runtime code.
> [dg] Add test for installation that an isolated dg can execute

- python_modules/libraries/dagster-dg/dagster_dg/cli/check.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/dev.py
Currently, `dg check` and `dg dev` always use `uv run` in a project context. This changes them to make them use the ambient environment if we're not using dg management.
Manually by running in a project not using `uv`. Will need to add automated tests in a followup.
> [dg] Make `dg check` and `dg dev` work without assuming `uv`

- js_modules/dagster-ui/packages/ui-core/src/assets/AssetPageHeader.oss.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/overview/DefinitionSection.tsx
- js_modules/dagster-ui/packages/ui-core/src/instigation/TickHistory.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunActionsMenu.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunConfigDialog.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunHeaderActions.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunRowTags.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunTags.tsx
- js_modules/dagster-ui/packages/ui-core/src/schedules/SchedulesNextTicks.tsx
- js_modules/dagster-ui/packages/ui-core/src/ticks/DryRunRequestTable.tsx
- js_modules/dagster-ui/packages/ui-core/src/ui/CopyButton.tsx
related: https://linear.app/dagster-labs/issue/FE-637/add-button-to-copy-all-tags-in-tags-modal
This PR adds a “Copy Tags” button to the run tags modal and the run “view configuration” modal  (which also shows the tags) which copies all the tags as a yaml block.
In building this I realized we have a handful of copy buttons and their behaviors (icons, toasts, etc) differ slightly, so I consolidated them down to two - an icon and a standard button. We could alternatively keep different buttons and push more toaster behavior into the hook, but I think it’s nice to standardize on a single icon + behavior. The version in the asset header is quite nice and I moved them all to that, but with the larger click target.
There is one that I didn't touch, which is pulled in from dagster dg - maybe we …
> [ui] Add “Copy tags” option to tags modals, unify copy behavior

- js_modules/dagster-ui/packages/ui-core/src/assets/LaunchAssetExecutionButton.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/LaunchAssetExecutionButton.test.tsx
https://linear.app/dagster-labs/issue/FE-798/improve-tooltip-for-button-with-no-selection
Before:
After:
Other cases are unchanged, I just unwound a mega-ternary into a function  (probably my doing...)  and added a new case at the top.  Verified the other cases still work by selecting non-executable and observable assets.
> [ui] Fix awkward messaging on the “Materialize” button when selection is empty

- python_modules/libraries/dagster-components/dagster_components/cli/scaffold.py
- python_modules/libraries/dagster-components/dagster_components/component_scaffolding.py
- python_modules/libraries/dagster-components/dagster_components/scaffold/scaffold.py
- python_modules/libraries/dagster-components/dagster_components_tests/cli_tests/test_commands.py
- python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_sling_integration_test.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_custom_help_format.py
Just getting the double layer cli layering working before implementing the business logic.
* `dg` has a flag (`--format`) that defaults to `yaml`)
* `dagster_componets` has a non-optional flag (`--scaffold-format`). Renamed to avoid collision with python built-in `format`.
```
(dagster-dev-3.11.11-2024-12-08) ➜  standalone_project dg scaffold dagster_components.dagster.DefinitionsComponent test_component_1 --format python
Using /Users/schrockn/code/scratch/dg-workspaces/standalone_project/.venv/bin/dagster-components
File "/Users/schrockn/code/scratch/dg-workspaces/standalone_project/.venv/bin/dagster-components", line 10, in <module>
sys.exit(main())
^^^^^^
File "/Users/schrockn/code/dagster/python_modules/libraries/dagster-components/dagster_components/ …
```
> [dg] Get cli plumbing working for new --format argument

- python_modules/libraries/dagster-components/dagster_components/component_scaffolding.py
Implement `--format python` option of scaffold command.
```
(dagster-dev-3.11.11-2024-12-08) ➜  standalone_project dg scaffold dagster_components.dagster.DefinitionsComponent test_component_11 --format python
Using /Users/schrockn/code/scratch/dg-workspaces/standalone_project/.venv/bin/dagster-components
(dagster-dev-3.11.11-2024-12-08) ➜  standalone_project cat standalone_project/defs/test_component_11/component.py
from dagster_components import component, ComponentLoadContext
from dagster_components.dagster import DefinitionsComponent
@component
def load(context: ComponentLoadContext) -> DefinitionsComponent: ...
```
Added the abiility to scaffold Python components
> [dg] Implement actual scaffolding

- js_modules/dagster-ui/packages/ui-components/src/components/ButtonGroup.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/LogsToolbar.tsx
https://linear.app/dagster-labs/issue/FE-97/disable-stdoutstderr-tab-if-no-steps-were-run
I tested that these are disabled for a queued run and immediately become available when the run starts executing the first 
(Rendering with disabled state below)
> [ui] If no steps have started, disable the stdout/stderr tabs of the run page

- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/client.py
- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/resources.py
- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/types.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/conftest.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_reconstruction.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_resources.py
This PR moves project.name and environment.name to cached properties, and support account_name as a cached_property too. 
This was originally done in the polling sensor PR, but moving the changes here to prevent the other PR from getting messy.
BK
> [dagster-dbt] Implement cached properties for account, project and environment names in DbtCloudWorkspace

- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/client.py
- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/run_handler.py
- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/sensor_builder.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/conftest.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_resources.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_sensor.py
- python_modules/libraries/dagster-dbt/kitchen-sink/dagster_dbt_cloud_kitchen_sink_tests/test_client_methods.py
This PR adds the polling sensor for the new dbt Cloud integration.  For now, only asset materializations are added to the sensor results.
This sensor is based on the polling sensor in `dagster-airlift`.
New tests with BK.
> [dagster-dbt] Add polling sensor for dbt Cloud v2

- python_modules/libraries/dagster-aws/dagster_aws/ecs/executor.py
- python_modules/libraries/dagster-aws/dagster_aws/ecs/utils.py
- python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/executor_tests/test_executor.py
- python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/test_utils.py
Fix for https://github.com/dagster-io/dagster/issues/28653. Sanitize the step key before using it as a tag. We don't use this tag anywhere so the sanitized value shouldn't cause any problems in the Dagster machinery.
Test Plan: New tests
> Sanitize step keys before using them as tags in the ECS executor

- python_modules/libraries/dagster-dbt/kitchen-sink/dagster_dbt_cloud_kitchen_sink_tests/test_client_methods.py
This PR fixes flaky non deterministic tests in dbt Cloud kitchen sink https://buildkite.com/dagster/dagster-dagster/builds/116737#0195de67-299a-42b6-bb26-09f268735405
If the test is executed in more than one PRs at the same time, there might be more than one run in the list of batched runs.
BK
> [dagster-dbt] Fix flaky test for runs batch in dbt Cloud kitchen sink

- js_modules/dagster-ui/packages/ui-core/src/assets/LaunchAssetChoosePartitionsDialog.tsx
- js_modules/dagster-ui/packages/ui-core/src/instance/backfill/useReexecuteBackfill.tsx
- js_modules/dagster-ui/packages/ui-core/src/partitions/BackfillMessaging.tsx
- js_modules/dagster-ui/packages/ui-core/src/partitions/BackfillSelector.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunUtils.tsx
Now that toasts are within the scope of the top-level `BrowserRouter`, they no longer need special link behavior, and `history.createHref` will in fact double the base path in the URL if used in conjunction with react-router links like `AnchorButton`.
This change fixes broken toast links when launching backfills.
Launch a backfill in cloud, verify that the link in the resulting toast goes to the correct backfill page.
[ui] Fix link in toast messages that appear when launching backfills.
> [ui] Fix backfill toast URL

- examples/oss-metadata-to-plus/metadata_to_plus/migrate_metadata_job.py
All checks were passing on https://github.com/dagster-io/dagster/pull/28710, but for some reason, new pyright errors appeared in `master` after I merged.
> Fix pyright errors in OSS -> Plus example

- docs/sphinx/_ext/sphinx-mdx-builder/sphinxcontrib/mdxbuilder/writers/mdx.py
Closes DOC-986.
Do not show an "Edit this page" link for API docs, as they do not have corresponding markdown files in version control.
```
yarn build-api-docs && yarn start
```
NOCHANGELOG
> [docs] rm "Edit this page" link for API docs

- python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
- python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
The fact that each of these calls had a different current_timestamp and potentially invoke get_last_partition_window. which can be surprisingly expensive if the cronstring is unusual,was making this call unneccesarily slow for certain partitions definitions.
run a slow dry run script of PartitionHealthQuery on a 2D multipartitions definition that was slow before, now is fast.
Performance improvements for loading the partitions page for multi-partitioned assets.
> perf improvements when fetching partition ranges in get_2d_run_length_encoded_partitions

- js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
- js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
- js_modules/dagster-ui/packages/ui-core/src/instance/JobMenu.tsx
- js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchButton.tsx
- js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadAllowedRoot.tsx
- js_modules/dagster-ui/packages/ui-core/src/launchpad/TagEditor.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/ReexecutionDialog.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunActionButtons.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/RunActionsMenu.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/__fixtures__/Reexecution.fixtures.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/__tests__/ReexecutionDialog.test.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/__tests__/useJobReExecution.test.tsx
- js_modules/dagster-ui/packages/ui-core/src/runs/useJobReExecution.tsx
- python_modules/dagster-graphql/dagster_graphql/implementation/execution/launch_execution.py
- python_modules/dagster-graphql/dagster_graphql/schema/inputs.py
- python_modules/dagster-graphql/dagster_graphql/schema/roots/mutation.py
https://linear.app/dagster-labs/issue/OPER-1624/override-run-tags-when-performing-a-re-execution-from-failure
This PR exposes the `extra_tags` option on re-execution (already available in the python API) via graphql, and allows the user to put in additional tags when re-executing using one of the two core strategies (ALL_STEPS and FROM_FAILURE)
We allow re-execution from a bunch of places, and I put the new UI into the `ReexecutionDialog` which is used when you select multiple runs on the runs feed view and chose the bulk action.   For other re-execute menu items, including the individual run actions, the job page "reexecute last run" option, and the run details page options, I added menu item tooltips and made shift-clicking open the dialog so you can add tags there too.
**Q: Why not …
> [ui] Allow overriding run tags when performing re-execution

- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/cli_invocation.py
- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/resources.py
- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/run_handler.py
- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/sensor_builder.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_run_events.py
This PR updated `DbtCloudCliInvocation` to accept manifest objects instead of the workspace.
This is required for the subsequent PR - when `DbtCloudWorkspace.cli(...)` is called in the asset decorator, we need to pass the manifest used to create the asset definitions to the `DbtCloudJobRunHandler` object, not the manifest of the workspace. Because of that, we need to pass a manifest object instead of the workspace object.
Other parameters like `job_id` and `client` also added because we are not passing the workspace anymore.
Updated tests with BK.
> [dagster-dbt] Update DbtCloudCliInvocation to accept manifest

- python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py
Fixes https://linear.app/dagster-labs/issue/DOC-927/ecs-run-launcher-api-docs-in-dagster-aws-are-missing
Local build.
> DOC-927 Add params to EcsRunLauncher docstring

- python_modules/dagster/dagster/_core/instance/ref.py
- python_modules/dagster/dagster/_core/secrets/env_file.py
- python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/dev.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/list.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/utils.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_dev_command.py
Defaults dagster to loading the `PerProjectEnvFileLoader` SecretsLoader, which can be manually configured to provide a mapping from code location to directory with an `.env` file, or can be supplied through the `DAGSTER_PROJECT_ENV_FILE_PATHS` env var.
Allows `dg dev` to pass a mapping for each project in a workspace, so we can load project-level .env contents.
> Introduce new default PerProjectEnvFileLoader SecretsLoader

- python_modules/libraries/dagster-deltalake/dagster_deltalake/io_manager.py
- python_modules/libraries/dagster-duckdb/dagster_duckdb/io_manager.py
- python_modules/libraries/dagster-gcp/dagster_gcp/bigquery/io_manager.py
- python_modules/libraries/dagster-snowflake/dagster_snowflake/snowflake_io_manager.py
`if table_slice.partition_dimensions` already ensures a non-empty sequence; the length check is unnecessary.
BK
> Drop an unnecessary length check from if statement

- python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py
- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/resources.py
- python_modules/libraries/dagster-dbt/dagster_dbt/core/resource.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_resources.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_checks.py
This PR uses the asset execution context passed from the asset decorator to update the cli invocation args in `DbtCloudWorkspace.cli(...)`.
In a subsequent PR, the context will be used downstream to enable yielding `Outputs` and `AssetCheckResults` when calling the cli invocation from the asset decorator.
> [dagster-dbt] Update args with context in DbtCloudWorkspace.cli(..)

- examples/docs_snippets/docs_snippets/guides/operate/concurrency-no-more-than-1-job.py
On page https://docs.dagster.io/guides/operate/managing-concurrency#prevent-runs-from-starting-if-another-run-is-already-occurring-advanced in the "advanced" example only the `STARTED` status is mentioned, which is not always enough in real (production) use-cases.
It would be great to have a more complete example ;-)
We already use it this way to avoid overloading the queue.
Note: not sure how the dark-gray background (highlighted part of the example code) is done on the docs page... I hope it will work.
> docs: Update concurrency-no-more-than-1-job.py to add more statuses

- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/cli_invocation.py
- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/resources.py
- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/run_handler.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_resources.py
This PR leverages the context in `DbtCloudJobRunResults.to_default_asset_events`. Now, when assets events are yielded in an asset definition, e.g. in the `dbt_cloud_assets` asset decorator, an output is yielded instead of an asset materialization for materialized assets.
Updated test with BK
> [dagster-dbt] Support context in default asset events for dbt Cloud

- python_modules/libraries/dagster-dg/dagster_dg/cli/env.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/plus.py
- python_modules/libraries/dagster-dg/dagster_dg/env.py
- python_modules/libraries/dagster-dg/dagster_dg/utils/plus/gql.py
- python_modules/libraries/dagster-dg/dagster_dg/utils/plus/gql_client.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/plus_tests/conftest.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/plus_tests/test_plus_login_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/plus_tests/test_pull_env_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/plus_tests/utils.py
Implements a `dg plus env pull` command, which fetches a list of env vars available for the local scope for a project (or all projects, in a workspace).
Unit tests for project, workspace, non-authed cases.
> [dg] `dg plus env pull`

- examples/docs_snippets/docs_snippets/guides/components/index/26-component-ingest-automation.yaml
- examples/docs_snippets/docs_snippets/guides/components/index/27-component-jdbt-automation.yaml
- examples/docs_snippets/docs_snippets/guides/components/shell-script-component/with-build-defs.py
- examples/docs_snippets/docs_snippets/guides/components/shell-script-component/with-custom-scope.py
- examples/docs_snippets/docs_snippets/guides/dg/migrating-project/1-tree.txt
- Current version of _master_ expects `ResolvedAssetSpec` to be imported from root `dagster_components`
* Updates docs to align with that in preparation for this weeks release.
- `yarn start` and walk through tutorial
NOCHANGELOG
> [docs] fix ResolvedAssetSpec imports in component authoring tutorial

- .buildkite/dagster-buildkite/dagster_buildkite/step_builder.py
the downside here is that we don't short circuit a test that was never going to complete, but that needs to be weighed against the chance that a test that *would* pass just hasnt yet. the latter is more common than the former (though the former has happened recently), so lets increase the timeout
these are just test step default changes
> increase default bk timeout to 45

- js_modules/dagster-ui/packages/ui-core/src/nav/__tests__/LeftNavRepositorySection.test.tsx
This flaked on a BK build https://buildkite.com/dagster/dagster-dagster/builds/117076, but I'm not really sure why. Refactor a little bit to change how we're awaiting the rendered output and performing user events.
BK
> [ui] Clean up LeftNavRepositorySection.test

- docs/docs/dagster-plus/features/alerts/configuring-an-alert-notification-service.md
Add the note that "A Pro plan is required to use this feature." from [in our legacy doc](https://legacy-docs.dagster.io/dagster-plus/managing-deployments/alerts/pagerduty) that didn't get ported over. 
👀
> [docs] add note that PagerDuty Alerts are Pro plan feature

- python_modules/dagster/dagster/_core/definitions/cacheable_assets.py
- python_modules/dagster/dagster_tests/general_tests/test_cacheable_assets_defs.py
Sending this out for discussion. The problem with the implementation here is that if there is any non-determinism in the resource config, the ID here changes on each deploy, causing various problems and race conditions. For example, the dbt cli resource is currently non-deterministic since it sets an absolute path as one of its fields that can change on each deploy.
I can't think of a situation where a CacheableAssetsDefinition would ever need to co-exist with itself with with_resources called on it (unless there is some odd case i'm not thinking of?) so I would expect it to be safe to keep the same unique ID after with_resources is applied to it.
New test case
[dagster-fivetran] Fixed an issue where new runs of code locations using fivetran assets would sometimes raise a "Failure …
> Make the unique_id on a CacheableAssetsDefinition when you run it through with_resources more stable

- python_modules/libraries/dagster-fivetran/dagster_fivetran/__init__.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_decorator.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran/translator.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/beta/test_asset_specs.py
This PR moves the logic to select Fivetran connector using the connector_selector_fn from `fetch_fivetran_workspace_data()` to `defs_from_state()` in the state-backed defs.
The main motivation here is that the workspace data should include all connectors that are active and valid, then we should create definitions for a subset of connectors based on the logic in `connector_selector_fn` when users are using the spec loader. This way, the users can create multiple assets with different `connector_selector_fns` in the same workspace.
> [dagster-fivetran] Move connector selection to state-backed defs

- python_modules/dagster/dagster/_config/pythonic_config/resource.py
- python_modules/dagster/dagster/_config/pythonic_config/typing_utils.py
- python_modules/dagster/dagster_tests/core_tests/resource_tests/pythonic_resources/test_nesting.py
Slight tweak of @HynekBlaha's contribution in #28836 - this version adjusts our Pydantic union behavior for resources to account for a change in Pydantic 2.5.0 which uses 'smart unions' (https://github.com/pydantic/pydantic-core/pull/867). This smart union behavior attempted to initialize each member of the union using the input data, which called the constructor for `PartialResource` with invalid inputs.
This PR enforces left-to-right union evaluation, similar to what occurred pre-Pydantic 2.5.0.
Unit test introduced in #28836.
Fixed an issue where using partial resources in Pydantic >= 2.5.0 could result in an unexpected keyword argument TypeError. (Thanks [@HynekBlaha](https://github.com/HynekBlaha)!)
> Fix regression when creating nested ConfigurableResource with pydantic >= v.2.5.0

- js_modules/dagster-ui/packages/ui-core/src/ui/BaseFilters/__tests__/useTimeRangeFilter.test.tsx
- js_modules/dagster-ui/packages/ui-core/src/ui/BaseFilters/useTimeRangeFilter.tsx
There is a timezone-related issue in the Datepicker-based filter that causes date mismatches when the user's local browser timezone and their Dagster timezone (as set in User Settings) do not match.
For instance, if my local timezone is America/Chicago and my Dagster timezone is Australia/Darwin, and I choose "April 1", react-dates will take this to mean April 1 in Chicago. When I make my selection, however, the Dagster UI will see this timestamp and render it as "April 2", the current date based on my Dagster timezone selection.
To repair this, set the moment timezone globally when opening the datepicker. We currently only use `moment` or `moment-timezone` in this one use case (grepped to check) so I don't want to pull the dependency out into the top-level context provider. But changing …
> [ui] Repair timezone bug in custom date selection

- docs/docs/guides/labs/components/building-pipelines-with-components/adding-components.md
- python_modules/dagster-test/dagster_test/components/simple_pipes_script_asset.py
- python_modules/dagster/dagster/components/cli/list.py
- python_modules/dagster/dagster/components/component/component.py
- python_modules/dagster/dagster/components/core/defs_module.py
- python_modules/dagster/dagster/components/core/snapshot.py
- python_modules/dagster/dagster/components/test/basic_components.py
- python_modules/dagster/dagster_tests/components_tests/cli_tests/test_commands.py
- python_modules/dagster/dagster_tests/components_tests/integration_tests/integration_test_defs/definitions/other_local_component_sample/__init__.py
- python_modules/dagster/dagster_tests/components_tests/utils.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_utils_inspect_command.py
I think we should rename `get_schema` to `get_model_cls`. Assuming everyone agrees wiill update docs as well.
BK
* `Component.get_schema` has been renamed to `Component.get_model_cls`. Override that instead to customize the frontend of your component. `Component.get_schema`  will continue to work for the time being but will be removed at some point.
> [dg] Rename get_schema to get_model_cls

- CHANGES.md
- docs/vercel.json
Addresses https://linear.app/dagster-labs/issue/DOC-985/fix-broken-docs-links-in-changelog -- this fixes all broken links on the changelog page. In many cases, I just removed a link entirely because there was no good alternative and no way to redirect it.
Staging preview (can't test redirects locally)
> DOC-985 Fix broken links in changelog

- python_modules/libraries/dagster-dg/dagster_dg/cli/check.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/dev.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_dev_command.py
Ensures that uv venv matches expected env before running `dg dev`
prev. failing test
> [dg][BUILD-769] Ensure uv sync run before dagster dev

- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/asset_decorator.py
- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/resources.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/conftest.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_asset_decorator.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_specs.py
This PR updates the code to allow users to pass `select` and `exclude` strings to the `dbt_cloud_assets` decorator, and the spec loader functions for dbt Cloud.
> [dagster-dbt] Support dbt selections for dbt Cloud

- docs/docs/integrations/libraries/airbyte/airbyte-cloud.md
- docs/docs/integrations/libraries/airlift.md
- docs/docs/integrations/libraries/aws/glue.md
- docs/docs/integrations/libraries/aws/lambda.md
- docs/docs/integrations/libraries/aws/redshift.md
- docs/docs/integrations/libraries/aws/s3.md
- docs/docs/integrations/libraries/azure-adls2.md
- docs/docs/integrations/libraries/census.md
- docs/docs/integrations/libraries/chroma.md
- docs/docs/integrations/libraries/cube.md
- docs/docs/integrations/libraries/databricks.md
- docs/docs/integrations/libraries/datadog.md
- docs/docs/integrations/libraries/dlt/index.md
- docs/docs/integrations/libraries/docker.md
- docs/docs/integrations/libraries/fivetran.md
- docs/docs/integrations/libraries/hashicorp.md
- docs/docs/integrations/libraries/hightouch.md
- docs/docs/integrations/libraries/java.md
- docs/docs/integrations/libraries/qdrant.md
- docs/docs/integrations/libraries/rust.md
- docs/docs/integrations/libraries/typescript.md
- docs/docs/integrations/libraries/weaviate.md
Addresses https://linear.app/dagster-labs/issue/DOC-1002/delete-logo-from-integrations-docs-metadata -- removes `logo` from integrations docs metadata, since it's been deprecated in favor of `sidebar_custom_props > logo`
> DOC-1002 Remove `logo` prop from integrations docs metadata

- js_modules/dagster-ui/packages/ui-core/src/asset-selection/useAssetSelectionFiltering.tsx
I added this logic to side step using the results from selection filtering if there is no asset selection but overlooked that the favorites feature in cloud hooks into the selection filtering (via useAssetGraphData) in order to affect which assets are shown. I will add a test case in internal for this.
used favorites locally.
> Always use graphAssetKeys in `useAssetSelectionFiltering`

- js_modules/dagster-ui/packages/ui-core/src/app/FeatureFlags.oss.tsx
- js_modules/dagster-ui/packages/ui-core/src/app/useVisibleFeatureFlagRows.oss.tsx
Disable turning off the selection syntax flag for now. In a follow-up PR i remove all of the code but for now just want to remove the flag so that new features I'm working on don't need to consider the case when the 
flag is off.
BK, open feature flags dialog.
> Remove selection syntax feature flag part 1

- examples/docs_snippets/docs_snippets/guides/components/shell-script-component/2-shell-command-empty.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/templates/COMPONENT_TYPE/COMPONENT_TYPE_NAME_PLACEHOLDER.py.jinja
- python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
While `Component` itself is agnostic to what framework is used to define properties (e.g. they could Pydantic or their own handrolled system) but that shouldn't prevent us from providing an easy path in the default case. So we are going to default to use `@dataclass` but allow an opt-out.
BK
NOCHANGELOG
> [dg] Default to dataclass in component type generation with an opt-out

- python_modules/libraries/dagster-dg/dagster_dg/config.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/test_context.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Adds support for `dg.toml` in place of `pyproject.toml`. Settings in `pyproject.toml` are set under `tool.dg`, but in `dg.toml` they are set directly at the top level. `pyproject.toml` and `dg.toml` may both be used either in a project or workspace.
Switching the default config for workspace to `dg.toml` will be added upstack.
Add support for `dg.toml` files. `dg` settings in `pyproject.toml` are set under `tool.dg`, but in `dg.toml` they are set at the top level. A `dg.toml` may be used in place of `pyproject.toml` at either the project or workspace level.
> [dg] Add dg.toml support (BUILD-878)

- js_modules/dagster-ui/packages/ui-core/src/nav/LeftNavRepositorySection.tsx
- js_modules/dagster-ui/packages/ui-core/src/nav/__fixtures__/LeftNavRepositorySection.fixtures.tsx
- js_modules/dagster-ui/packages/ui-core/src/nav/__tests__/LeftNavRepositorySection.test.tsx
- js_modules/dagster-ui/packages/ui-core/src/nav/__tests__/RepoOptionVisibility.test.tsx
- js_modules/dagster-ui/packages/ui-core/src/ui/SectionedLeftNav.tsx
- js_modules/dagster-ui/packages/ui-core/src/ui/__stories__/SectionedLeftNav.stories.tsx
Break apart `LeftNavRepositorySection.test`, which is demonstrating some maddening heisenbugs and may just be putting too much under test at once given what we're actually trying to look at here.
I'm creating two separate tests that I think effectively cover what we wanted to test, which is that a) the rendering of the left nav reflects the hidden/visible state tracked in localStorage, and b) the left nav shows expanded states with jobs and asset groups.
- Make `LeftNavRepositorySection.test` test that visible `DagsterRepoOption` items are in fact visible as expected, including expansion of the contained jobs and asset groups.
- This is now independent of `WorkspaceProvider`, and the supplied repo options are mocked and passed in as props.
- To test the existing localStorage behavior used …
> [ui] Break up LeftNavRepositorySection.test

- examples/docs_snippets/docs_snippets/guides/dg/workspace/2-tree.txt
- examples/docs_snippets/docs_snippets/guides/dg/workspace/3-dg.toml
- examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/dg/test_dg_docs_workspace.py
- examples/docs_snippets/tox.ini
- python_modules/libraries/dagster-dg/dagster_dg/cli/dev.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/templates/WORKSPACE_NAME_PLACEHOLDER/dg.toml.jinja
- python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_init_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Change scaffolded workspaces to include a `dg.toml` instead of `pyproject.toml`.
Adapted existing unit tests.
`dg`-scaffolded workspaces now include a `dg.toml` instead of `pyproject.toml` file.
> [dg] Change workspace scaffolding to create dg.toml instead of pyproject.toml

- python_modules/dagster/dagster/_utils/container.py
This appears to be an expected case in common scenarios, so make the logger about failing to fetch it much less noisy.
Confirmed existing test coverage for this case
Fixed an issue where Dagster run metrics produced large amounts of error lines when running in containers without a CPU limit set on the container.
> Downgrade logs on CPU quota fetch failures from errors to debug

- docs/docs/guides/labs/components/creating-new-component-types/creating-and-registering-a-component-type.md
- examples/docs_snippets/docs_snippets/guides/components/index/3-tree.txt
- examples/docs_snippets/docs_snippets/guides/components/shell-script-component/2-shell-command-empty.py
- examples/docs_snippets/docs_snippets/guides/components/shell-script-component/with-build-defs.py
- examples/docs_snippets/docs_snippets/guides/components/shell-script-component/with-config-schema.py
- examples/docs_snippets/docs_snippets/guides/dg/migrating-definitions/1-tree.txt
- examples/docs_snippets/docs_snippets/guides/dg/migrating-definitions/5-tree-after.txt
- examples/docs_snippets/docs_snippets/guides/dg/migrating-definitions/6-tree-after-all.txt
- examples/docs_snippets/docs_snippets/guides/dg/migrating-project/1-tree.txt
- python_modules/libraries/dagster-dg/dagster_dg/templates/COMPONENT_TYPE/COMPONENT_TYPE_NAME_PLACEHOLDER.py.jinja
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
Current docs promote `__init__` methods for defining YAML schema. This updates the tutorial to use data classes.
```
yarn start
```
NOCHANGELOG
> [docs] updates docs to favor @dataclass for component authoring

- examples/docs_snippets/docs_snippets/guides/dg/workspace/2-tree.txt
- examples/docs_snippets/docs_snippets/guides/dg/workspace/3-dg.toml
- examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/dg/test_dg_docs_workspace.py
- examples/docs_snippets/tox.ini
- python_modules/libraries/dagster-dg/dagster_dg/cli/dev.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/templates/WORKSPACE_NAME_PLACEHOLDER/dg.toml.jinja
- python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_init_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/test_context.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Prior to this PR, `dg` would crash when working with projects with an `src`-based layout. This makes it compatible with `src`-layout projects.
The implementation is a little rough-- we just look for packages in both `src` and in root. The reason for this is that there's not an otherwise reliable great way to detect `src`-based layout. You could try reading `pyproject.toml` and looking for config of well-known build tools, but that's a can of worms. I suspect this solution will work well.
Upstack we are actually going to change the default new project layout to be src-based.
New unit test.
Fixed a bug where `dg` would crash when working with Python packages with an src-based layout.
> [dg] Make DgContext work with src-based layout

- CHANGES.md
- python_modules/dagster/dagster/components/test/test_cases.py
- python_modules/dagster/dagster_tests/components_tests/integration_tests/integration_test_defs/validation/basic_component_extra_value_in_a_subfolder/subfolder/component.yaml
- python_modules/libraries/dagster-dg/dagster_dg/check.py
Now that we allow for more flexible `defs` structure, let `dg check yaml` walk all `defs` subfolders to find components.
unit test
> [dg check yaml] walk nested subdirs, not just top level dirs in defs

- examples/docs_snippets/docs_snippets/guides/components/index/11-component.yaml
- examples/docs_snippets/docs_snippets/guides/components/shell-script-component/5-scaffolded-component.yaml
- python_modules/dagster/dagster/components/component_scaffolding.py
Summary:
Noticed that our scaffolded YAML indents lists in a way that is technnically correct but offends my aesthetic sensibilities. Applying the workaround I found on https://github.com/yaml/pyyaml/issues/234 to indent lists by 2 spaces relative to their parent.
Test Plan:
Automated tests, scaffold some components locally as a sanity check -  see updated docs snippets for an example of the change
> fix indentation of lists in component scaffolding

- python_modules/dagster/dagster/_generate/download.py
Summary:
New example added in https://github.com/dagster-io/dagster/pull/29001 is presumably not ready for download as a public scaffolded example yet by dagster project from-example (exact future of that command unclear in a post-dg world anyway)
Not positive when docs_beta_snippets became eligible here but presumably that is not eligible as well
Test Plan:
BK
> Fix test_available_examples_in_sync_with_example_folder

- python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/last_update.py
- python_modules/dagster/dagster/_core/definitions/asset_check_factories/freshness_checks/time_partition.py
- python_modules/dagster/dagster/_core/definitions/asset_check_factories/utils.py
- python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_last_update_freshness.py
- python_modules/dagster/dagster_tests/definitions_tests/freshness_checks_tests/test_time_partition_freshness.py
No reason _not_ to do this. Allows freshness checks to be blocking.
Added tests that the flag is set as expected. No reason to reinvent the wheel on how blocking itself is tested I think.
- a new `blocking` parameter has been added to `build_last_update_freshness_checks` and `build_time_partition_freshness_checks`.
> Allow freshness checks to be blocking

- examples/docs_snippets/docs_snippets/guides/components/index/3-tree.txt
- examples/docs_snippets/docs_snippets/guides/dg/dagster-definitions/2-tree.txt
- examples/docs_snippets/docs_snippets/guides/dg/scaffolding-project/2-tree.txt
- examples/docs_snippets/docs_snippets/guides/dg/workspace/2-tree.txt
- python_modules/libraries/dagster-dg/dagster_dg/cli/init.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_init_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
It's also standard to have a `tests` folder rather than something with the project name in it.
`dg init --project-name new_format_2`
```
pyproject.toml src            tests          uv.lock
(dagster-dev-3.11.11-2024-12-08) ➜  new_format_2 tree .
.
├── pyproject.toml
├── src
│   └── new_format_2
│       ├── __init__.py
│       ├── __pycache__
│       │   └── __init__.cpython-311.pyc
│       ├── definitions.py
│       ├── defs
│       │   └── __init__.py
│       └── lib
│           ├── __init__.py
│           └── __pycache__
│               └── __init__.cpython-311.pyc
├── tests
│   └── __init__.py
└── uv.lock
```
> rename tests folder

- python_modules/dagster/dagster/_core/definitions/partition_mapping.py
- python_modules/dagster/dagster/_core/definitions/time_window_partition_mapping.py
- python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_asset_partition_mappings.py
- python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_multipartition_partition_mapping.py
- python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_static_partition_mapping.py
- python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py
- python_modules/dagster/dagster_tests/storage_tests/test_fs_io_manager.py
Adds a new method that does basic sanity checking of the upstream and downstream defs to make sure that they are not incompatible. Can then be used during definitions loading or "dagster definitions validate" to verify that all partition mappings are valid. Previously the only way to get this information was to actually attempt a partition mapping, so it was cumbersome to check at definition time.
New test cases
> Add a "validate_partition_mapping" method on PartitionMapping

- python_modules/libraries/dagster-shared/dagster_shared/libraries/__init__.py
- python_modules/libraries/dagster-shared/dagster_shared/telemetry/__init__.py
- python_modules/libraries/dagster-shared/dagster_shared_tests/test_libraries.py
Summary:
This way we get a consistent dagster version logged in telemetry even from dg (and don't have to worry about a rogue dagster import sneaking in)
Test Plan: BK
> derive dagster core version from dagster-shared version in telemetry

- python_modules/libraries/dagster-dg/dagster_dg/cli/init.py
Summary:
Noticed this in the DSL demo - backticks make sense for markdown but not in this context. Not sure what the proper formatting is here, but single quotes seems better.
How I Tested These Changes:
eyes
> [ez] backtick to single quotes in dg init

- python_modules/libraries/dagster-dg/dagster_dg/cli/list.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py
We were displaying schedules in the sensors section. This fixes that.
Manual
- Fixed bug where schedules were displayed in the sensors section of `dg list defs`.
> [dg] Correctly display sensors in the sensors section of dg list

- docs/docs/guides/labs/components/creating-new-component-types/creating-and-registering-a-component-type.md
- examples/docs_snippets/docs_snippets/guides/components/shell-script-component/2-shell-command-empty.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg/templates/COMPONENT_TYPE/COMPONENT_TYPE_NAME_PLACEHOLDER.py.jinja
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
On reflection it was a bit silly to default to `dataclass` since we want the full YAML system (including Resolved things) to work out of the box.
BK
* Scaffolding a component type defaults to inheriting from `dagster.components.Model` instead of getting decorated by `@dataclasses.dataclass`
> [dg] Default dagster.components.Model instead of @dataclass

- python_modules/dagster/dagster/components/resolved/base.py
- python_modules/dagster/dagster/components/resolved/core_models.py
- python_modules/dagster/dagster_tests/components_tests/resolution_tests/test_resolved_asset_checks.py
This adds `ResolvedAssetCheckSpec` which behaves very similarly to `ResolvedAssetSpec`. Will use up the stack to flesh out the factory.
BK
NOCHANGELOG
> [dg] Add ResolvedAssetCheckSpec

- js_modules/dagster-ui/packages/ui-core/src/hooks/useQueryPersistedState.tsx
Spent too long investigating something caused by this weird behavior. Since its intended to catch issues with the replace mode I'm gating it to just the replace behavior
local host cloud
> [useQueryPersistedState] Gate confusing dev only behavior to replace behavior

- js_modules/dagster-ui/packages/dg-docs-components/src/CopyButton.tsx
Add a try/catch to the clipboard write on the dg-docs-components CopyButton, to see if it helps surface issues seen by @schrockn.
Also added an `await` on the `writeText` call to be a bit more correct with subsequent behavior, since the function returns a Promise.
`dg docs serve`, verify that copy works as expected on code blocks.
> [dg] Docs: wrap copy behavior in a try/catch

- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_environment_validation.py
Update error messages for a missing `dagster-components` executable (they still referenced the `dagster-components` package).
Modified existing tests.
> [dg] Fix missing `dagster-components` error messages

- python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/beta/conftest.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/beta/test_resources.py
This PR handles paused connectors in `FivetranWorkspace.sync_and_poll` - methods `FivetranClient.sync_and_poll` and `FivetranClient.resync_and_poll` return None if the sync is paused and log a warning.
Before this PR, syncing a paused connector raised an exception, caused by `connector.validate_syncable()` in `FivetranClient.start_sync`. We keep that behavior here - users can call that method directly in their code, and will raise an exception if the connector is paused.
The difference between `FivetranClient.sync_and_poll` and `FivetranClient.start_sync` is that the former is responsible for returning a `FivetranOutput` when a connector is synced, and he latter is a wrapper around the Fivetran API endpoint to start a sync.
```
dagster._core.definitions.events.Failure: Connector …
```
> [dagster-fivetran] Handle paused connector in FivetranWorkspace.sync_and_poll

- docs/docs/guides/labs/components/creating-new-component-types/creating-and-registering-a-component-type.md
- examples/docs_snippets/docs_snippets/guides/components/shell-script-component/with-config-schema-meta.py
Explains how to set `owners` and `tags` on Component using `get_spec`.
`yarn start`
NOCHANGELOG
> [components,docs] add explanation of overridden `get_spec` on `Component`

- docs/docs/guides/labs/components/creating-new-component-types/creating-and-registering-a-component-type.md
- examples/docs_snippets/docs_snippets/guides/components/shell-script-component/with-config-schema-meta.py
- js_modules/dagster-ui/packages/dg-docs-components/src/ComponentHeader.tsx
- js_modules/dagster-ui/packages/dg-docs-components/src/ComponentTags.tsx
- js_modules/dagster-ui/packages/dg-docs-components/src/types.ts
- js_modules/dagster-ui/packages/ui-core/src/dg-docs/DGDocs.tsx
- python_modules/dagster-test/dagster_test/components/simple_asset.py
- python_modules/dagster/dagster/_core/definitions/utils.py
- python_modules/dagster/dagster/components/__init__.py
- python_modules/dagster/dagster/components/component/component.py
- python_modules/dagster/dagster/components/core/snapshot.py
- python_modules/dagster/dagster_tests/components_tests/cli_tests/test_commands.py
- python_modules/libraries/dagster-dg/dagster_dg/docs.py
- python_modules/libraries/dagster-shared/dagster_shared/serdes/objects/package_entry.py
Closes BUILD-819.
Enables adding component metadata via the `get_spec` method for defining `tags`, `owners`, and overriding the `__doc__` with `description`.
- Adds `ComponentSpec`
- Adds `get_spec` to `Component`
- Updates `PackageObjectSnap` to include `owners` and `tags` for inclusion in JSON dump in `dagster-components list library` (used by `dg docs server`).
Follow-up work will support logos as we need to determine how to either encode or bundle them alongside the component metadata.
Unit tests, and `dg docs serve` for the screenshot above.
- [components] Adds `get_spec` on `Component` for defining metadata like `tags` and `owners`.
> [components] adds ability to set `tags` and `owners` metadata on Component with `get_spec`

- python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/beta/test_reconstruction.py
- python_modules/libraries/dagster-fivetran/setup.py
- python_modules/libraries/dagster-fivetran/tox.ini
Updates `fetch_fivetran_workspace_data` to use the state loader. The goal is to avoid reloading the workspace data more than once when using the method. The workspace data should be loaded only once.
New tests with bk
> [dagster-fivetran] Leverage state-backed defs in FivetranWorkspace.fetch_fivetran_workspace_data()

- .buildkite/dagster-buildkite/dagster_buildkite/defines.py
- python_modules/dagster-pipes/tox.ini
- python_modules/dagster/tox.ini
- python_modules/libraries/dagster-gcp-pyspark/tox.ini
- python_modules/libraries/dagster-polars/tox.ini
- python_modules/libraries/dagster-shared/tox.ini
- python_modules/libraries/dagster-wandb/tox.ini
- scripts/templates_create_dagster_package/tox.ini.tmpl
We stopped running coveralls years ago but never cleaned up the remaining cruft in our tox.ini files.
> Clean up COVERAGE_ARGS in tox.ini

- python_modules/dagster/dagster/_core/definitions/asset_graph.py
- python_modules/dagster/dagster/_core/definitions/definitions_class.py
- python_modules/dagster/dagster/_core/definitions/repository_definition/repository_definition.py
- python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_asset_partition_mappings.py
Fixes an issue where if you had an invalid partition mapping between two assets (like timezones not matching) it wouldn't be caught until DA tried to execute it. This doesn't capture every class of issues (notably invalid partition mappings between two different code locations or repositories within the same code location) but should help with the common case where the offending assets are in the same code location.
`Definitions.validate_loadable` and `dagster definitions validate` will now raise an error on assets with invalid partition mappings, like a `TimeWindowPartitionMapping` between two time-based partitions definitions with different timezones. Previously, these invalid partition mappings would not raise an error until they were used to launch a run.
> Validate partition mappings when a repository is first loaded

- python_modules/dagster/dagster/components/cli/list.py
- python_modules/dagster/dagster/components/core/defs_module.py
- python_modules/dagster/dagster_tests/components_tests/integration_tests/integration_test_defs/validation/basic_component_missing_declared_env/component.yaml
- python_modules/dagster/dagster_tests/components_tests/integration_tests/integration_test_defs/validation/basic_component_with_env/component.yaml
- python_modules/libraries/dagster-dg/dagster_dg/check.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/check.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/dev.py
- python_modules/libraries/dagster-dg/dagster_dg/component.py
- python_modules/libraries/dagster-dg/dagster_dg/utils/editor/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_check_yaml_command.py
Adds a new top-level key to the component file which allows declaring requirements, including `env` vars (and in the future, resources and UDFs for the profiles system).
```yaml
type: ...
attributes: ...
requirements:
env:
- MY_ENV_VAR
```
This enables us to validate if dependencies are fully satisfied without fully loading a code location.:
```sh
$ dg check yaml
/Users/ben/repos/components_demo/03-28-env-demo/projects/data_ingest/data_ingest/defs/sling_elt/component.yaml:1 - requirements.env Component uses environment variables that are not specified in the component file: GROUP_NAME
| 
1 | type: dagster_sling.SlingReplicationCollectionComponent
| ^ Component uses environment variables that are not specified in the component file: GROUP_NAME
2 | attributes:
3 |   replications:
4 |   - …
```
> [components] Update components schema to allow declaring env var requirements, validate in check yaml

- python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/beta/conftest.py
- python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/beta/test_resources.py
Fixes AD-1026
Previously, we were fetching connections for a group without iterating using the cursor and passing a maximum limit for the number of connectors to fetch - the default limit per call which is set to 100, see [here](https://fivetran.com/docs/rest-api/api-reference/groups/list-all-connections-in-group#limit), so we were fetching a maximum of 100 connectors per group ID (destination ID). This poses serious limitations for organizations with large numbers of connectors per destination.
This PR implement the code to support passing a limit and iterate on the pages of the responses for that endpoint.
BK, dagster dev
[dagster-fivetran] A bug causing the Fivetran integration to fetch only 100 connectors per destination has been fixed, all connectors are now fetched for a given …
> [dagster-fivetran] Support limit and pagination cursor in FivetranClient.list_connectors_for_group

- python_modules/libraries/dagster-airlift/dagster_airlift/test/shared_fixtures.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink_tests/integration_tests/conftest.py
- python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink_tests/integration_tests/test_api.py
New kitchen sink tests were failing on 3.12 because of increased airflow spinup time.
Fix by waiting until all dags exist in scope to move forward with testing.
> [dagster-airlift] fix tests on 3.12

- python_modules/dagster/dagster/_core/definitions/definitions_class.py
- python_modules/dagster/dagster/components/resolved/core_models.py
- python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py
Adds a top-level "map_asset_specs" method to Definitions, which takes in an optional asset selection and an AssetSpec -> AssetSpec transformation function.
The idea is to enable last-mile transformation of asset specs on a Definitions object; similar to what `asset_post_processors` does, but for non-components Definitions. In fact, most of this implementation is ripped directly from the asset_post_processors code path, and we reimplement that on top of this functionality.
- Additional test_definitions_class.py tests.
- A `Definitions.map_asset_specs` method, which allows for transforming asset specs from any passed in AssetSpec or AssetsDefinition objects which match an asset selection.
> [RFC] Definitions.map_asset_specs

- python_modules/dagster/dagster/__init__.py
- python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
- python_modules/dagster/dagster/_core/definitions/multi_dimensional_partitions.py
- python_modules/dagster/dagster/_core/definitions/partition.py
- python_modules/dagster/dagster/_core/definitions/temporal_context.py
- python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
- python_modules/dagster/dagster/_core/test_utils.py
- python_modules/dagster/dagster/_core/types/pagination.py
- python_modules/dagster/dagster_tests/core_tests/partition_tests/test_partition.py
- python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py
- python_modules/dagster/dagster_tests/definitions_tests/test_dynamic_partitions.py
- python_modules/dagster/dagster_tests/definitions_tests/test_multi_partitions.py
- python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py
Reapplies #28311, but with the time_window based pagination ripped out because it was unnecessary and changed the underlying non-paginated implementation.
BK - ran the automaterialization perf tests locally and saw a 30% increase in perf.
> Reapply partition key pagination APIs

- python_modules/dagster-test/dagster_test/utils/data_factory.py
allows you to pass in `dagster_event(event_type=DagsterEventType.STEP_SUCCESS)` or whatever instead of forcing you to remember to do `.value`
> small QOL data factory improvement

- js_modules/dagster-ui/packages/ui-core/src/assets/AssetEvents.tsx
We were passing an array to the query but it expects an enum. Convert from array to enum.
local host cloud
[ui] Fixed a bug preventing filtering on the asset events page.
> Fix asset events filtering

- js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx
- js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/AssetsGlobalGraphRoot.tsx
- js_modules/dagster-ui/packages/ui-core/src/graph/asyncGraphLayout.ts
Only take favorites into account when on the global asset graph and catalog.
If you're visiting the lineage of a specific asset (even if its from within the favorites view), do not limit the lineage by favorites.
locally:
> Only use favorites in global asset graph and catalog

- examples/docs_snippets/docs_snippets/guides/components/shell-script-component/with-config-schema-meta.py
- python_modules/dagster-test/dagster_test/components/simple_asset.py
- python_modules/dagster/dagster/components/__init__.py
- python_modules/dagster/dagster/components/component/component.py
After chatting with Ben it was determined that `ComponentTypeSpec` is more appropriate.
N/A
NOCHANGELOG
> [components] rename `ComponentSpec` to `ComponentTypeSpec`

- .buildkite/dagster-buildkite/dagster_buildkite/steps/integration.py
- integration_tests/test_suites/k8s-test-suite/tox.ini
Eyeballing this test suite, our longest runtime seem to be dominated by the monitoring tests. So let's just split them out into their own tox factors to run in parallel.
4 of the 8 longest runtimes for this test suite are monitoring related:
And it's one of our longer test suites in general:
> Split out K8s integration monitoring tests

- .buildkite/dagster-buildkite/lints.py
We don't have a great way of stacking pytest.ini files now and these subdirectory ones can confusingly prevent our root pyproject.toml or root conftest.py from getting discovered.
> Lint to avoid subdirectory pytest.ini file

- python_modules/dagster/dagster/_grpc/utils.py
100MB should be more tractable due to recent technological advances on the upload side.
The default byte size limit for gRPC requests and responses is now 100MB instead of 50MB. This value can be adjusted by setting the DAGSTER_GRPC_MAX_RX_BYTES and DAGSTER_GRPC_MAX_SEND_BYTES environment variables on the gRPC client and server processes.
> increase default grpc max send/rx bytes

- js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/AssetsGlobalGraphRoot.tsx
- js_modules/dagster-ui/packages/ui-core/src/assets/useFavoriteAssets.oss.tsx
Pass loading state down so that we don't flash all asssets.
Added a skip: true to the favorites query and observed we stayed in a loading state.
> [1/2][Favorites] wait for favorites to load

- docs/docs/guides/migrate/airflow-to-dagster/federation/observe.md
- examples/airlift-federation-tutorial/Makefile
- examples/airlift-federation-tutorial/scripts/airflow_setup.sh
Federation tutorial had a few issues when Paul ran through:
- Airflow install also needs duckdb and pandas
- Didn't get pointed at definitions.py to add code
There were some others, but this fixes at least a few of them.
Existing tests. Unfortunately, these wouldn't have gotten caught by the existing test suite and it's nontrivial to add support.
- Fixed some missing package installs from the Airlift federation tutorial.
> Fix federation tutorial issues

- python_modules/libraries/dagster-shared/dagster_shared/utils/config.py
Change the user dg config file from `dg.toml` to `.dg.toml` on Unix. This means that there will be no `dg.toml` file in the home directory that will be discovered as a containing workspace.
Manually, by checking that settings from `~/.dg.toml` were inherited and those from `~/dg.toml` were not. Used this approach because it's hard to use an automated test when reading from the home directory.
The `dg` user config file on Unix is now looked for at `~/.dg.toml` instead of `~/dg.toml`.
> [dg] Change sure config from dg.toml -> .dg.toml

- docs/docs/guides/labs/components/components-etl-pipeline-tutorial.md
- docs/docs/guides/labs/components/creating-new-component-types/creating-and-registering-a-component-type.md
- examples/docs_snippets/docs_snippets/guides/components/index/17-dg-list-plugins.txt
- examples/docs_snippets/docs_snippets/guides/components/index/7-dg-list-plugins.txt
- examples/docs_snippets/docs_snippets/guides/components/index/8-dg-list-plugins.txt
- examples/docs_snippets/docs_snippets/guides/components/shell-script-component/3-dg-list-plugins.txt
- examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/components/test_components_docs.py
- examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/components/test_components_docs_creating_a_component.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/list.py
- python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_environment_validation.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/test_cache.py
Remove `dg list component-type`. Convert `dg list component-type` tests to use `dg list plugins` instead.
Modified existing tests.
The `dg list component-type` command has been removed. There is a new `dg list plugins` with output that is a superset of `dg list component-type`.
> [dg] Remove dg list component-type

- docs/docs/guides/deploy/deployment-options/running-dagster-locally.md
Just added a basic code snippet example of using `DAGSTER_IS_DEV_CLI` env var
👀
> [docs] add code example for using DAGSTER_IS_DEV_CLI

- .buildkite/dagster-buildkite/dagster_buildkite/step_builder.py
- .buildkite/hooks/pre-command
- conftest.py
This checks the Buildkite API for a list of test cases that have been "muted" via the Buildkite UI. On every branch but the release branch, it annotates muted tests with a pytest "skip" annotation. That way, we can quarantine and triage broken or flaky tests without our build staying broken while we work on a fix.
Future versions of the buildkite-test-collector plan to support this use case more directly so we might be able to remove this custom implementation in the near future.
https://buildkite.com/docs/test-engine/flaky-test-management
A version of this is already running on our internal repo but this sets it up for this repo before I start evangelizing this functionality more broadly.
> Enable Buildkite Test Engine muting

- python_modules/libraries/dagster-dg/dagster_dg/cli/plus.py
- python_modules/libraries/dagster-dg/dagster_dg/cli/utils.py
- python_modules/libraries/dagster-dg/dagster_dg/context.py
- python_modules/libraries/dagster-dg/dagster_dg/templates/deploy_uv_Dockerfile.jinja
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/plus_tests/test_plus_deploy_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/plus_tests/test_plus_login_command.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Lots to do here as evidenced by the many TODOs, but this is sufficient to deploy a dg project to serverless. It:
- checks that you are logged in
- Creates a dagster_cloud.yaml (only used under the hood) derived from the pyproject.toml for the project
- scaffolds a uv-friendly Dockerfile if none exists
- Builds the project using that Dockerfile and pushes it to the remote serverless repository
- Deploys the project, at which point it will be available in Dagster+.
Also would like to improve the testing coverage here with a real test harness that deploys to a locally available cloud instance (just mocking out the call to the dagster-cloud ci leaves a lot of things untested, although each of those underlying commands also have separate unite tests)
> dg deploy initial serverless + docker implementation

- docs/docs/guides/labs/components/creating-new-component-types/creating-a-library-of-components.md
Update the "Creating a library of components" doc to reflect the current state of the codebase (e.g. removing old config specification).
This will be followed by another update to this doc when `dg list plugins` is released.
> [dg] Update "Creating a library of components" doc (BUILD-930)

- python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
- python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Fix line added to `<project>/lib/__init__.py`.
Formerly:
```
from my_project.lib.shell_command import ShellCommand
```
Now:
```
from my_project.lib.shell_command import ShellCommand as ShellCommand
```
Modified a test.
Fix formatting of line added to `project/lib/__init__.py` when scaffolding a component type.
> [dg] Fix lib/__init__.py addition for component type scaffolding (BUILD-925)

- docs/dagsterVersions.json
- docs/docusaurus.config.ts
See title -- to keep the version switcher from getting super long, only create new entries in the version picker for minor versions.
Since the 1.10.10 release branch has already been cut, I set the most recent release to 1.10.11.
> [Docs] Only create version dropdown entries for minor versions

- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/asset_decorator.py
- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/cli_invocation.py
- python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/run_handler.py
- python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_resources.py
This PR updates the `dbt_cloud_assets` decorator to pass the check specs to the multi-asset definition, and updates `DbtCloudJobRunResults.to_default_asset_events` to yield AssetCheckResults when asset check are executed in an asset execution context.
Updated test with BK
> [dagster-dbt] Support asset checks in dbt_cloud_assets

- docs/docs/guides/labs/components/building-pipelines-with-components/adding-components.md
- docs/docs/guides/labs/components/creating-new-component-types/creating-and-registering-a-component-type.md
- python_modules/libraries/dagster-sling/dagster_sling/components/sling_replication_collection/component.py
Update documentation to no longer refer to `dg scaffold component`
Read
NOCHANGELOG
> [dg] Update docs to no longer refer to 'dg project scaffold'

- docs/docs/guides/labs/components/building-pipelines-with-components/adding-components.md
- docs/docs/guides/labs/components/creating-new-component-types/creating-and-registering-a-component-type.md
- js_modules/dagster-ui/packages/dg-docs-components/src/ComponentScaffolding.tsx
- python_modules/libraries/dagster-sling/dagster_sling/components/sling_replication_collection/component.py
`dg scaffold component` no longer a command so changing it in the docs
Read
NOCHANGELOG
> [dg] Eliminate 'component' in 'dg scaffold component' in dg docs as it is no longer valid

- python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
- python_modules/dagster-graphql/dagster_graphql/schema/asset_health.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_all_snapshot_ids.ambr
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_solids.ambr
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_checks.py
- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
Computes the health status for the asset checks for an asset
Rules:
- `HEALTHY` - the latest completed execution for every check is a success. Note the latest completed execution for each check may not have executed based on the most recent materialization of the asset
- `WARNING` -  the latest completed execution for any asset check failed with severity `WARN`(and no checks failed with severity `ERROR`). Note the latest completed execution for each check may not have executed based on the most recent materialization of the asset
- `DEGRADED` - the latest completed execution for any asset check failed with severity `ERROR`. Note the latest completed execution for each check may not have executed based on the most recent materialization of the asset    
- `UNKNOWN` - any asset checks have …
> [asset health] asset check health status calculations

- python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_run_cancellation.py
instead of "nope" for a non-existent runID, just uses a UUID instead
unit tests
> use uuid for runID in test
