docs/docs-beta/docs/guides/operate/managing-concurrency.md

Another editing pass for correctness
Inspection
Corrected docs on managing concurrency

fix wrong instructions for concurrency docs

---

js_modules/dagster-ui/packages/ui-core/src/app/Util.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/HourlyDataCache/HourlyDataCache.tsx
js_modules/dagster-ui/packages/ui-core/src/search/useIndexedDBCachedQuery.tsx

Bump to 4 due to https://dagsterlabs.slack.com/archives/C08CN04KDSL

Bump indexeddb version

---

js_modules/dagster-ui/packages/ui-core/src/app/Util.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/HourlyDataCache/HourlyDataCache.tsx
js_modules/dagster-ui/packages/ui-core/src/search/useIndexedDBCachedQuery.tsx

Change indexeddb names

---

examples/project_dagster_university_start/README.md
examples/project_du_dbt_starter/README.md
python_modules/dagster/dagster/_generate/templates/PROJECT_NAME_PLACEHOLDER/README.md.jinja

Update old links to docs.dagster.cloud

DOC-831 Update docs.dagster.cloud links

---

docs/docs-beta/docs/integrations/libraries/airbyte/airbyte-cloud.md
python_modules/libraries/dagster-airbyte/dagster_airbyte/managed/reconciliation.py

[integrations-api][docs] Update dagster-airbyte docs to use beta language

---

docs/docs-beta/docs/integrations/libraries/fivetran.md

[integrations-api][docs] Update dagster-fivetran docs to use beta language

---

CHANGES.md

[changelog] 1.9.12

---

scripts/generate_changelog.py

Tweak changelog script so that generated bullets match rest of changelog. From this:
```
*  I have leading extra whitespace and a *
```
To this
```
- I match the rest of the changelog
```
Generated changelog

Tweak changelog script for better bullets

---

docs/docs-beta/docs/dagster-plus/deployment/deployment-types/hybrid/kubernetes/setup.md

I was running through this recently and bumped up against:
```
Error: unknown flag: --install
```
I'm not sure if this is just a typo or reflects a change in the helm CLI but I'm guessing the former.

Fixup k8s helm install command

---

examples/docs_beta_snippets/docs_beta_snippets/guides/data-assets/data-assets/multi_asset_decorator.py

have to yield these, does nothing if they are not output from the function 
eyes

[new docs] fix multi_asset

---

docs/docs/partials/_Deprecated.md

[docs-beta] Add Deprecated warning in partials

---

python_modules/libraries/dagster-tableau/dagster_tableau/resources.py
python_modules/libraries/dagster-tableau/dagster_tableau/translator.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/conftest.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_resources.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_translator.py

As title. The bugs were known when merging #27641 - the goal was to help speed up the debugging process for the user.
BK

[dagster-tableau] Fix pyright and ruff

---

python_modules/dagster/dagster_tests/test_annotations.py

We're about to delete the experimental annotation and its tests. 
This PR reuses the tests for the experimental annotation for the preview annotation.
BK

Add tests for preview annotation

---

python_modules/dagster/dagster_tests/test_annotations.py

Same as #27636 but for the beta annotation
BK

Add tests for beta annotation

---

python_modules/dagster/dagster_tests/test_annotations.py

Same as #27636 but for the superseded annotation
BK

Add tests for superseded annotation

---

python_modules/dagster/dagster_tests/test_annotations.py

Delete tests for experimental and experimental_param annotations

---

python_modules/libraries/dagster-components/dagster_components/core/schema/base.py
python_modules/libraries/dagster-components/dagster_components/core/schema/context.py
python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py

Adds a bunch of overloads so that the type system can give better information about the types of things that come out of the resolve_value method. 
NOCHANGELOG

[components] Better type support for `resolve_value`

---

python_modules/libraries/dagster-components/dagster_components/core/schema/base.py
python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
python_modules/libraries/dagster-components/dagster_components/lib/pipes_subprocess_script_collection.py
python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_model.py

As title -- makes things a bit less verbose
NOCHANGELOG

[components] don't require additional_fields

---

python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components/core/component_decl_builder.py
python_modules/libraries/dagster-components/dagster_components/core/schema/base.py
python_modules/libraries/dagster-components/dagster_components/core/schema/context.py
python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py
python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
python_modules/libraries/dagster-components/dagster_components/lib/pipes_subprocess_script_collection.py
python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
python_modules/libraries/dagster-components/dagster_components/utils.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_dbt_project.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_sling_integration_test.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_templated_custom_keys_dbt_project.py
python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/custom_scope_component/component.py
python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_model.py
python_modules/libraries/dagster-dg/dagster_dg/templates/COMPONENT_TYPE/COMPONENT_TYPE_NAME_PLACEHOLDER.py.jinja

Removes the generic stuff, as well as the class methods, moving that onto the context object.
NOCHANGELOG

[components] Simplify ResolvableModel

---

python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components_tests/code_locations/python_script_location/components/script_python_decl/component.py

[componets] Rename `@component_loader` to `@component`

---

docs/sphinx/_ext/dagster-sphinx/dagster_sphinx/__init__.py
docs/sphinx/_ext/dagster-sphinx/dagster_sphinx/docstring_flags.py

[docs] Support beta_param annotation in Sphinx

---

docs/sphinx/sections/api/apidocs/external-assets.rst
docs/sphinx/sections/api/apidocs/internals.rst
docs/sphinx/sections/api/apidocs/io-managers.rst
docs/sphinx/sections/api/apidocs/libraries/dagster-aws.rst
docs/sphinx/sections/api/apidocs/libraries/dagster-azure.rst
docs/sphinx/sections/api/apidocs/libraries/dagster-gcp.rst
docs/sphinx/sections/api/apidocs/partitions.rst
docs/sphinx/sections/api/apidocs/utilities.rst

[docs] Remove experimental from API docs and rst files in Sphinx

---

python_modules/dagster/dagster/_annotations.py
python_modules/dagster/dagster/_core/definitions/asset_selection.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py

Accidentally deleted the beta param decorator and forgot to delete my placeholder thing
NOCHANGELOG

[core-api-audit] cleanup

---

python_modules/dagster/dagster/_core/execution/plan/instance_concurrency_context.py
python_modules/dagster/dagster_tests/core_tests/execution_tests/test_active.py

If we start short-circuiting the `claim` call, we should clear the in-memory state to no longer block the run.
tbd

resolve changing pool info situation

---

python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py
python_modules/libraries/dagster-aws/dagster_aws/ecs/utils.py

Allow this method to be used in other places
BK
NOCHANGELOG

Pull is_transient_task_stopped_reason into a util module

---

docs/docs/guides/preview/components/creating-a-component.md
examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/defining-resolvable-field.py
examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/defining-resolver.py
examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/resolving-resolvable-field.py
examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-build-defs.py
examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-config-schema.py
examples/experimental/dagster-blueprints/dagster_blueprints/blueprint_assets_definition.py
examples/experimental/dagster-blueprints/dagster_blueprints_tests/test_databricks_blueprint.py
examples/experimental/dagster-blueprints/dagster_blueprints_tests/test_shell_command_blueprint.py
python_modules/libraries/dagster-components/dagster_components/__init__.py
python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components/core/schema/base.py
python_modules/libraries/dagster-components/dagster_components/core/schema/context.py
python_modules/libraries/dagster-components/dagster_components/core/schema/metadata.py
python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py
python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/component.py
python_modules/libraries/dagster-components/dagster_components/lib/definitions_component/component.py
python_modules/libraries/dagster-components/dagster_components/lib/pipes_subprocess_script_collection.py
python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/component.py
python_modules/libraries/dagster-components/dagster_components/lib/test/complex_schema_asset.py
python_modules/libraries/dagster-components/dagster_components/test/basic_components.py
python_modules/libraries/dagster-components/dagster_components/utils.py
python_modules/libraries/dagster-components/dagster_components_tests/code_locations/python_script_location/components/script_python_decl/component.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions/local_component_sample/__init__.py
python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/custom_scope_component/component.py
python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_model.py
python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_spec_processing.py
python_modules/libraries/dagster-dg/dagster_dg/templates/COMPONENT_TYPE/COMPONENT_TYPE_NAME_PLACEHOLDER.py.jinja
python_modules/libraries/dagster-dg/dagster_dg_tests/utils_tests/test_sample_yaml.py

If we're going to enforce that this is always used with Components, we should probably name it something more specific.
NOCHANGELOG

[components][rfc] Rename "ResolvableModel" to "ComponentSchema"

---

examples/google_drive_factory/google_drive_factory/definitions.py
examples/google_drive_factory/pyproject.toml

Added a couple dependencies to pytoml and a fetch metadata function to the Goolge Drive Class.

Google Drive Asset Factory Example updates

---

python_modules/libraries/dagster-azure/dagster_azure/adls2/file_manager.py
python_modules/libraries/dagster-azure/dagster_azure/adls2/io_manager.py
python_modules/libraries/dagster-azure/dagster_azure/adls2/resources.py
python_modules/libraries/dagster-azure/dagster_azure/adls2/utils.py
python_modules/libraries/dagster-azure/dagster_azure/blob/compute_log_manager.py
python_modules/libraries/dagster-azure/dagster_azure/blob/utils.py
python_modules/libraries/dagster-azure/dagster_azure_tests/adls2_tests/test_adls2_file_manager.py

Adds dagster-azure type annotations to improve developer experience while working with the library
No functional changes were made and unit tests ran succesfully

[dagster-azure] add dagster-azure type annotations

---

python_modules/dagster/dagster/_cli/utils.py
python_modules/dagster/dagster_tests/cli_tests/command_tests/dagster_dev_command_tests/test_dagster_dev_command.py

Fix dagster dev test to expect correct instance dir

---

js_modules/dagster-ui/packages/ui-core/src/app/FeatureFlags.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/app/useVisibleFeatureFlagRows.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetSidebarActivitySummary.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/overview/ComputeDetailsSection.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/ConcurrencyTabs.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/InstanceConcurrency.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/InstanceConcurrencyKeyInfo.tsx
js_modules/dagster-ui/packages/ui-core/src/instance/VirtualizedInstanceConcurrencyTable.tsx
js_modules/dagster-ui/packages/ui-core/src/pipelines/SidebarOp.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunHeaderActions.tsx

For `1.10.0` launch, this is ungated
Inspection

remove UI feature gating for pools

---

examples/project_du_dbt_starter/dagster_university/assets/trips.py

Updated in the project repo but need to update the dbt starter code which includes this as a finished product.
https://github.com/dagster-io/project-dagster-university/pull/55

[du] DU dbt starter project link

---

docs/docs/etl-pipeline-tutorial/automate-your-pipeline.md
docs/docs/etl-pipeline-tutorial/create-a-sensor-asset.md
docs/docs/etl-pipeline-tutorial/create-and-materialize-assets.md
docs/docs/etl-pipeline-tutorial/create-and-materialize-partitioned-asset.md
docs/docs/etl-pipeline-tutorial/refactor-your-project.md

- `automate-your-pipeline.md` - add Definitions code
- `create-a-sensor-asset.md` - improve clarity
- `create-and-materialize-assets.md` - fix typo
- `create-and-materialize-partitioned-assets.md` - fix typo
- `refactor-your-projects.md` - add Partitions section, remove `lineStart` and `lineEnd` properties
- Fix errors in https://github.com/dagster-io/dagster/issues/27427
- Fix typos
[Local development and build](https://github.com/dagster-io/dagster/tree/master/docs#local-development)

[docs] fix etl pipeline tutorial

---

python_modules/dagster/dagster/_core/definitions/op_definition.py
python_modules/dagster/dagster_tests/definitions_tests/test_definitions.py

Should be more restrictive in what is a valid pool name
BK
- Added sanitation checks on valid pool names

add sanitation check in pool param

---

.github/workflows/build-docs.yml

[docs] trigger deployment on release- tag

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNode.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNodeMenu.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/Sidebar.tsx
js_modules/dagster-ui/packages/ui-core/src/graph/KindTags.tsx

Make 'Show upstream graph` and `Show downstream graph` options use the new syntax if the feature flag is enabled
https://github.com/user-attachments/assets/068f9c57-25f7-465c-a429-9c6cdae3117b

[Asset Selection] Use new syntax for asset graph actions

---

python_modules/dagster/dagster/_check/builder.py
python_modules/dagster/dagster/_check/decorator.py
python_modules/dagster/dagster/_record/__init__.py
python_modules/dagster/dagster_tests/general_tests/test_checked.py
python_modules/dagster/dagster_tests/general_tests/test_record.py

wire up default value handling over from `@record` to `@checked` 
added test

[checked] handle defaults

---

python_modules/libraries/dagster-dbt/setup.py

new version seems to be causing unexpected concurrency issues in tests
bk

pin dbt-duckdb in tests

---

python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/schedule_definition.py

Summary:
run status sensors was still recommending schedule, and schedule was recommending sensor.
Inspection

Fix a couple more incorrect comments of which build_xx_context to use

---

python_modules/dagster/dagster/_api/list_repositories.py
python_modules/dagster/dagster/_grpc/client.py

Allow callsites to override fields like timeout.
BK
NOCHANGELOG

add kwargs to gen_list_repositories_grpc

---

docs/docs/integrations/libraries/airlift/index.md

Fix links on Airlift integration index page.

Fix airlift links

---

python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py
python_modules/libraries/dagster-dlt/dagster_dlt/asset_decorator.py
python_modules/libraries/dagster-dlt/dagster_dlt_tests/test_asset_decorator.py
python_modules/libraries/dagster-sling/dagster_sling/asset_decorator.py
python_modules/libraries/dagster-sling/dagster_sling_tests/test_asset_decorator.py

Adds pool support for dbt/dlt/sling multi assets
BK
- Adds the pool support for dbt/dlt/sling integrations.

Thread pool argument through integration multi_asset calls

---

python_modules/libraries/dagster-components/CHANGELOG.md
python_modules/libraries/dagster-dg/CHANGELOG.md

[dagster-components][dagster-dg] adds changelog files

---

docs/docs/integrations/libraries/teradata.md

Added documentation for dagster-teradata

Added dagster-teradata documentation

---

python_modules/libraries/dagster-components/dagster_components/core/schema/base.py
python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_model.py

Removes the decorator pattern
NOCHANGELOG

[components][cleanup] Remove support for decorator field resolver pattern

---

python_modules/dagster/dagster_tests/declarative_automation_tests/daemon_tests/test_e2e.py

fix pyright error in tests

---

docs/docs/examples/llm-fine-tuning/index.md
examples/docs_projects/project_llm_fine_tune/project_llm_fine_tune/assets.py

I found a few minor issues when Dog fooding this project. 
1. Asset check context in asset check
2. project name in tutorial index page.

Fine Tuning Tutorial Fixes

---

python_modules/libraries/dagster-openai/dagster_openai/resources.py

Fix pyright error in LLM project

---

docs/docusaurus.config.ts

[docs] rename API reference to API

---

CHANGES.md

1.10.1 changelog

---

python_modules/dagster/dagster/_cli/job.py
python_modules/dagster/dagster/_core/telemetry.py

random test site for adding `@checked`, found via looking for a file with volume of `check.` 
bk

use checked in cli.job.py

---

docs/docs/dagster-plus/features/alerts/creating-alerts.md

We updated the alert creation flow, and this updates the docs to account for it. 

Updating Alert Creation Docs

---

python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

Add tests to fill in a test coverage gap
BK

fix tests for changing initialize concurrency slot calls

---

js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInput.tsx

On the run page we programmatically update the selection syntax when you click on a step in the Gantt chart. Currently, when this happens we end up making the auto-complete results dropdown popup. This is unintentional behavior. Fix that behavior by not showing the dropdown if we're programmatically updating the value.

[Selection Input] Don't show auto-complete dropdown when programmatically updating the value

---

.github/workflows/build-docs.yml

[docs] archive previews on *.archive.dagster-docs.io

---

examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-scaffolder.py
python_modules/libraries/dagster-components/dagster_components/__init__.py

[dagster-components] export scaffold_component_yaml at top level

---

docs/docs/guides/build/assets/defining-assets.md

Fixes #27743
[Local development and build](https://github.com/dagster-io/dagster/tree/master/docs#local-development)
Change `my_data_asset` to `weekly_sales_report`

[docs] fix asset name

---

examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/2-shell-command-empty.py
examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/empty.py
examples/docs_beta_snippets/docs_beta_snippets/guides/monitor-alert/custom-logging/asset-job-example.py
examples/docs_beta_snippets/docs_beta_snippets/guides/monitor-alert/custom-logging/ops-job-example.py
examples/docs_beta_snippets/docs_beta_snippets/guides/tutorials/multi-asset-integration/integration.py
examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_component_docs_existing_code_location/my-existing-project/my_existing_project/assets.py
examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs_migrating_definitions/my-existing-project/my_existing_project/analytics/assets.py
examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs_migrating_definitions/my-existing-project/my_existing_project/elt/assets.py
examples/docs_beta_snippets/docs_beta_snippets_tests/test_all_files_load.py
examples/docs_beta_snippets/docs_beta_snippets_tests/test_integration_files_load.py

[docs] update docs_beta_snippets to use `import dagster as dg`

---

js_modules/dagster-ui/packages/ui-core/src/workspace/workspacePath.ts

[Asset Selection] Update runs page "View asset lineage" link to use new syntax if feature enabled

---

docs/Makefile
examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/conftest.py
examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs_creating_a_component.py
examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/utils.py
examples/docs_beta_snippets/tox.ini

Since screenshot generation is somewhat flaky, make it an opt-in process.

[components docs] Opt-in to regenerating screenshots

---

CHANGES.md

[changelog] 1.10.2

---

python_modules/dagster-graphql/dagster_graphql/test/utils.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_reload_repository_location.py
python_modules/dagster-webserver/dagster_webserver/debug.py
python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py
python_modules/dagster/dagster/_core/test_utils.py
python_modules/dagster/dagster/_core/workspace/context.py
python_modules/dagster/dagster/_core/workspace/workspace.py
python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster/_daemon/sensor.py
python_modules/dagster/dagster/_scheduler/scheduler.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_external_asset_graph.py
python_modules/dagster/dagster_tests/core_tests/workspace_tests/test_request_context.py
python_modules/dagster/dagster_tests/general_tests/asset_graph_differ_tests/test_asset_graph_differ.py
python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py

make room for the snapshot name to represent a persisted snapshot of a workspace
bk

WorkspaceSnasphot -> CurrentWorkspace

---

docs/docs/guides/build/assets/asset-jobs.md
examples/docs_beta_snippets/docs_beta_snippets/guides/data-modeling/asset-jobs/asset-jobs.py

Resolves DOC-761.
Example was incorrectly showing marker comment.
`yarn start`
NOCHANGELOG

[docs] fix code snippet markers for asset jobs

---

python_modules/dagster/dagster/_check/builder.py
python_modules/dagster/dagster_tests/general_tests/check_tests/test_check.py

[check builder] Optional[Callable[...]]

---

js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInputAutoCompleteResults.tsx

[Selection syntax] Add view documentation link

---

js_modules/dagster-ui/packages/ui-core/src/app/PythonErrorInfo.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/CellTruncationProvider.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/LogsRow.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/SummarizeErrorWithAIButton.oss.tsx

As titled adds a shared component.
Also converts a couple of small components from class based to functional.
With cloud PR https://github.com/dagster-io/internal/pull/13878

Add shared component for "Summarize error with AI button"

---

docs/docs/examples/bluesky/index.md
docs/docs/examples/llm-fine-tuning/index.md

Include video link in the examples docs for fine tuning

Include video link fine tuning example

---

docs/docs/guides/deploy/code-locations/managing-code-locations-with-definitions.md

recommenced → recommended
Correct spelling helps understanding and reputation.
n/a

fix typo in managing-code-locations-with-definitions.md

---

docs/docs/guides/labs/components/building-pipelines-with-components/adding-components.md
docs/docs/guides/labs/components/building-pipelines-with-components/customizing-components.md
docs/docs/guides/labs/components/components-etl-pipeline-tutorial.md
docs/docs/guides/labs/components/creating-new-component-types/creating-and-registering-a-component-type.md

[docs] fix components usage of params

---

docs/sphinx/_ext/sphinx-click/sphinx_click/ext.py

Fixes cli sub-commands formatted with `sphinx-click` being truncated.
Workaround until fix is landed upstream:
* https://github.com/click-contrib/sphinx-click/issues/150
**Before**
**After**
`yarn start`
- [docs] fixes CLI commands being truncated in API documentation

[docs] fix truncated cli sub commands

---

python_modules/automation/automation_tests/test_repo.py

[docs] fix automation tests

---

python_modules/automation/automation_tests/test_repo.py

[docs] fix py.typed location sphinx-click

---

docs/docs/guides/labs/components/components-etl-pipeline-tutorial.md

Switch `dagster dev` to `dg dev`

[Components] Switch `dagster dev` to `dg dev`

---

docs/dagsterVersions.json
docs/docusaurus.config.ts

Add version dropdown entries for 1.10.0, 1.10.1, and 1.10.2 (master for now).

DOC-906 [Docs] Add 1.10.0, 1.101. and 1.10.2 entries to version dropdown

---

.github/workflows/build-docs.yml
docs/README.md

Lightly reorganize the docs README to clarify how to run a full local build to check for broken links and other build errors.

[Docs] Clarify steps for running local build to check for errors

---

.github/workflows/build-docs.yml

[DOCS] Correctly exclude README, CONTRIBUTING, and content-templates paths from triggering docs build

---

python_modules/dagster/dagster/_core/remote_representation/origin.py
python_modules/dagster/dagster/_daemon/sensor.py

no need to serialize and hash these if we can just comapre these simple records directly

[sensors] compare selectors directly

---

python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_dbt_project.py

Adds a little test case mirroring some of the custom scope we'd like to use in our internal data platforms.

[dagster-components][ez] Add test case showcasing user-defined scope relying on nodes

---

integration_tests/test_suites/daemon-test-suite/auto_run_reexecution_tests/test_auto_run_reexecution.py
python_modules/dagster/dagster/_daemon/auto_run_reexecution/auto_run_reexecution.py

If the run group doesn't exist we were raising an error. This catches the error and logs an engine event.  In the case where the run group doesn't exist, the run is not retried. 
A run group wouldn't exist if the root run for the run group is deleted 
unit tests

handle missing run group when determining if a run should be retried

---

js_modules/dagster-ui/packages/ui-core/src/runs/CapturedLogPanel.tsx

[compute logs] fix download link in limit exceeded message

---

js_modules/dagster-ui/packages/ui-core/src/runs/RawLogContent.tsx

[compute logs] fix truncation prefix message in ui

---

python_modules/dagster-graphql/dagster_graphql/implementation/execution/__init__.py

* we were exiting with stuff still in the queue since we were just checking the subscription before exiting 
* we were blocking main thread with downloads since we do a `fetch` on `subscribe` 
existing coverage, look compute logs in `dagster dev` and dagster+

[compute logs] fix subscription

---

examples/project_dagster_university_start/dagster_university/__init__.py
examples/project_dagster_university_start/dagster_university/assets/metrics.py
examples/project_du_dbt_starter/dagster_university/__init__.py
examples/project_du_dbt_starter/dagster_university/assets/metrics.py
examples/project_du_dbt_starter/dagster_university/assets/requests.py
examples/project_du_dbt_starter/dagster_university/assets/trips.py
examples/project_du_dbt_starter/dagster_university/jobs/__init__.py
examples/project_du_dbt_starter/dagster_university/partitions/__init__.py
examples/project_du_dbt_starter/dagster_university/resources/__init__.py
examples/project_du_dbt_starter/dagster_university/schedules/__init__.py
examples/project_du_dbt_starter/dagster_university/sensors/__init__.py

Update the starter projects for both Dagster University modules to use `import dagster as dg` statements

[du] Change to `import dg`

---

js_modules/dagster-ui/packages/ui-core/src/selection/SelectionAutoCompleteProvider.tsx

[Selection input] Middle truncate auto-complete results

---

docs/dagsterVersions.json
docs/docusaurus.config.ts

Update docs for latest release.

[DOC-911] Add 1.10.2 versioned docs and set latest to 1.10.3

---

python_modules/dagster/dagster_tests/cli_tests/command_tests/test_materialize_command.py

Make an existing test case more clear, and add the test case I thought was covered.
BK

Create test case for materializing upstream assets

---

docs/docs/guides/labs/components/creating-new-component-types/creating-and-registering-a-component-type.md

[dg] Change docs to refer to scaffoldable

---

python_modules/libraries/dagster-components/dagster_components/__init__.py
python_modules/libraries/dagster-components/dagster_components/cli/scaffold.py
python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components/core/component_scaffolder.py
python_modules/libraries/dagster-components/dagster_components/scaffold.py
python_modules/libraries/dagster-components/dagster_components/scaffoldable/decorator.py
python_modules/libraries/dagster-components/dagster_components/scaffoldable/scaffolder.py
python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_component_with_optional_scaffolder.py

[dg] Move ComponentScaffolderUnavailableReason to dagster_components.scaffoldable

---

examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-scaffolder.py
python_modules/dagster-test/dagster_test/components/simple_pipes_script_asset.py
python_modules/libraries/dagster-components/dagster_components/__init__.py
python_modules/libraries/dagster-components/dagster_components/cli/scaffold.py
python_modules/libraries/dagster-components/dagster_components/components/dbt_project/scaffolder.py
python_modules/libraries/dagster-components/dagster_components/components/definitions_component/scaffolder.py
python_modules/libraries/dagster-components/dagster_components/components/sling_replication_collection/scaffolder.py
python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components/core/component_scaffolder.py
python_modules/libraries/dagster-components/dagster_components/scaffold.py
python_modules/libraries/dagster-components/dagster_components/scaffoldable/decorator.py
python_modules/libraries/dagster-components/dagster_components/scaffoldable/scaffolder.py
python_modules/libraries/dagster-components/dagster_components_tests/scaffoldable_tests/test_decorator.py
python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_component_with_optional_scaffolder.py

Eliminate all Component prefixes on what are now totally generic classes.
BK
NOCHANGELOG

[dg] Eliminate Component prefix on generic scaffolding classes

---

docs/docs/integrations/libraries/fivetran.md
docs/sphinx/sections/api/apidocs/libraries/dagster-fivetran.rst
examples/docs_beta_snippets/docs_beta_snippets/integrations/fivetran/select_fivetran_connectors.py
examples/docs_beta_snippets/docs_beta_snippets_tests/test_integration_files_load.py

[docs] add ConnectorSelectorFn example in Fivetran guide

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py

Add a _log property to be used in subsequent PR. Related to this [comment](https://github.com/dagster-io/dagster/pull/28080#pullrequestreview-2654826757).

[dagster-fivetran] Add logger in FivetranWorkspace

---

python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py
python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_spec_processing.py

Move body of dbt project resolvers to static function in order to allow for more easy invocations of them from different arrangments of code
BK
NOCHANGELOG

[components] Extract resolves to static functions

---

python_modules/libraries/dagster-components/dagster_components/components/dbt_project/component.py
python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components/core/schema/base.py
python_modules/libraries/dagster-components/dagster_components/core/schema/context.py
python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py

Just extracting these methods to functions with no behavior changes so we can reuse from other contexts
BK

[dg] Refactor all logic in ResolvableSchema into functions for easier refactoring

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/storage/event_log/base.py
python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py
python_modules/dagster/dagster/_core/storage/partition_status_cache.py
python_modules/dagster/dagster/_utils/caching_instance_queryer.py
python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

[wip] batch write paths for asset failure events

---

docs/vercel.json

See https://docs.google.com/spreadsheets/d/11E13JxnylpXR08BaJtsbeyzCveZ8XxPjHl6a53R567o/edit?gid=1881228454#gid=1881228454

[DOCS] Add redirects for 404ing paths with traffic

---

python_modules/libraries/dagster-components/dagster_components/components/sling_replication_collection/component.py

As title. Convert to SlingReplicationComponent to use ResolvableFromSchema
BK
NOCHANGELOG

[dg] SlingReplicationComponent to use ResolvableFromSchema

---

docs/docs/dagster-plus/features/authentication-and-access-control/rbac/user-roles-permissions.md

Comment out the TODOs in the user-roles-permissions page

[docs] Correct TODOs user-roles-permissions page

---

examples/project_dagster_university_start/setup.py
examples/project_du_dbt_starter/setup.py

[du] DU 1.10

---

python_modules/libraries/dagster-components/dagster_components/components/sling_replication_collection/component.py

[dg] Eliminate references to ResolvableSchema in the sling component

---

python_modules/libraries/dagster-components/dagster_components/components/definitions_component/component.py

[dg] Eliminate Resolvable in DefinitionsComponent

---

python_modules/libraries/dagster-components/dagster_components/components/dbt_project/component.py

[dg] Eliminate ResolvableSchema reference in DbtProjectComponent

---

python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py
python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/custom_scope_component/component.py
python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_model.py

Ferreting out all peripheral uses of ResovlableSchema. These are a couple test cases.
BK
NOCHANGELOG

[dg] Port test_resolvable_model to new format

---

python_modules/libraries/dagster-components/dagster_components/components/pipes_subprocess_script_collection.py
python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py

As title. Changing PipesSubprocessScriptCollectionComponent to use the ResolvableFrom system
BK
NOCHANGELOG

[dg] Convert everything in PipesSubprocessScriptCollectionComponent except for AssetSpec

---

python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py
python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_transformer.py

Use `ResolutionSpec` to add support for `AssetSpec` and test.
BK
NOCHANGELOG

[dg] Implement a resolution spec for asset spec

---

python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py
python_modules/libraries/dagster-components/dagster_components/core/schema/resolvable_from_schema.py

This was a bit of a thorny one to unwrap. Added some better typehecking and invariant checking that would have caught the error.

[dg] Move AssetAttributes hierarchy to DSLSchema

---

python_modules/libraries/dagster-components/dagster_components/core/schema/resolvable_from_schema.py
python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_field_utilites.py

Resolution specs did not handle inheritance. This fixes that and also consolidates codepaths to it works on all classes in a single codepath
BK
NOCHANGELOG

[dg] Allow resolution specs to handle inheritance

---

python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py

[dg] Add shared class for AssetSpecResolutionSpec and AssetAttributesResolutionSpec to elim duplication

---

python_modules/libraries/dagster-components/dagster_components/core/schema/context.py
python_modules/libraries/dagster-components/dagster_components/test/basic_components.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/validation/basic_component_scope_exc/component.yaml
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/validation_tests/test_component_validation.py

wrap exceptions that occur during template evaluation for better UX
added test

[dg] improve experience when udfs throw

---

CHANGES.md

[changelog] 1.10.4

---

examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/2-shell-command-empty.py
examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/custom-schema-resolution.py
examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/empty.py
examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/resolving-resolvable-field.py
examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-build-defs.py
examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-class-defined.py
examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-config-schema.py
examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-custom-scope.py
examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-scaffolder.py
python_modules/libraries/dagster-components/dagster_components/__init__.py
python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components/core/schema/resolvable_from_schema.py
python_modules/libraries/dagster-components/dagster_components/test/basic_components.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions/local_component_sample/__init__.py
python_modules/libraries/dagster-dg/dagster_dg/templates/COMPONENT_TYPE/COMPONENT_TYPE_NAME_PLACEHOLDER.py.jinja

Move docs snippets to DSLSchema. It is quite pleasing. Will not rewrite docs until renames are complete
BK
NOCHANGELOG

[dg] Move Docs examples to resolvable schema

---

python_modules/dagster-test/dagster_test/components/complex_schema_asset.py
python_modules/libraries/dagster-components/dagster_components/__init__.py
python_modules/libraries/dagster-components/dagster_components/components/dbt_project/component.py
python_modules/libraries/dagster-components/dagster_components/components/pipes_subprocess_script_collection.py
python_modules/libraries/dagster-components/dagster_components/components/sling_replication_collection/component.py
python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py
python_modules/libraries/dagster-components/dagster_components/utils.py
python_modules/libraries/dagster-components/dagster_components_tests/code_locations/python_script_location/defs/script_python_decl/component.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_dbt_project.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_templated_custom_keys_dbt_project.py
python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/custom_scope_component/component.py
python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_spec_processing.py

Renamed a chunk of schemas to models and got to reasonable stopping point.
BK
NOCHANGELOG

[dg] Rename a chunk of schema classes to model

---

examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/resolving-resolvable-field.py
examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-build-defs.py
examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-class-defined.py
examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-config-schema.py
examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-custom-scope.py
examples/docs_beta_snippets/docs_beta_snippets/guides/components/shell-script-component/with-scaffolder.py
python_modules/libraries/dagster-components/dagster_components/__init__.py
python_modules/libraries/dagster-components/dagster_components/components/pipes_subprocess_script_collection.py
python_modules/libraries/dagster-components/dagster_components/components/sling_replication_collection/component.py
python_modules/libraries/dagster-components/dagster_components/core/component.py
python_modules/libraries/dagster-components/dagster_components/core/schema/objects.py
python_modules/libraries/dagster-components/dagster_components/core/schema/resolvable_from_schema.py
python_modules/libraries/dagster-components/dagster_components/utils.py
python_modules/libraries/dagster-components/dagster_components_tests/code_locations/python_script_location/defs/script_python_decl/component.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/components/definitions/local_component_sample/__init__.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_sling_integration_test.py
python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/custom_scope_component/component.py
python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_from_schema.py
python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_model.py
python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolvable_transformer.py
python_modules/libraries/dagster-components/dagster_components_tests/unit_tests/test_spec_processing.py
python_modules/libraries/dagster-dg/dagster_dg_tests/utils_tests/test_sample_yaml.py

Renamed all remaining schema classes to model classes
BK
NOCHANGELOG

[dg] All model renames complete

---

python_modules/dagster/dagster/_core/definitions/asset_selection.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection.py

This can't be called in user code, but can be called in a daemon context that has access to repo information.
BK
NOCHANGELOG

Make CodeLocationAssetSelection work for alert targeting

---

python_modules/dagster-test/dagster_test/utils/data_factory.py
python_modules/dagster/dagster_tests/storage_tests/utils/run_storage.py
python_modules/libraries/dagster-mysql/tox.ini
python_modules/libraries/dagster-postgres/tox.ini

instead of attaching as static methods to a class, just put these sorts of things in their own data factory module

add test util data factory

---

python_modules/libraries/dagster-aws/tox.ini
python_modules/libraries/dagster-azure/tox.ini
python_modules/libraries/dagster-gcp-pandas/tox.ini
python_modules/libraries/dagster-gcp-pyspark/tox.ini
python_modules/libraries/dagster-gcp/tox.ini

https://github.com/dagster-io/dagster/pull/28279 added this dependency

add dagster-test to more tox.ini's

---

python_modules/libraries/dagster-components/dagster_components/components/pipes_subprocess_script_collection.py

more of https://github.com/dagster-io/dagster/pull/28262
run test on py39

[dg] fix pipes staticmethod resolver

---

python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py

Fix list_defs tests

---

docs/dagsterVersions.json
docs/docusaurus.config.ts

[DOC-920] Add 1.10.3 docs to version dropdown and bump current version to 1.10.4

---

pyright/alt-1/requirements-pinned.txt
pyright/master/requirements-pinned.txt
python_modules/libraries/dagster-deltalake/dagster_deltalake/handler.py
python_modules/libraries/dagster-deltalake/setup.py
python_modules/libraries/dagster-polars/dagster_polars/io_managers/delta.py
python_modules/libraries/dagster-polars/setup.py

See title. Updated @danielgafni's work to include rebuilt pyright pins.
bk
- [dagster-polars] update deltalake dependency to 0.25.0

[dagster-polars] update deltalake to 0.25.0

---

python_modules/libraries/dagster-dg/dagster_dg/cli/check.py
python_modules/libraries/dagster-dg/dagster_dg/cli/dev.py
python_modules/libraries/dagster-dg/dagster_dg/cli/utils.py

A lot of duplicated logic between these two commands. Consolidate them.
Manual and BK
NOCHANGELOG

[dg] Consolidate dg check defs and dg dev on common codepaths

---

js_modules/dagster-ui/packages/ui-core/src/assets/globalAssetGraphPathToString.tsx
js_modules/dagster-ui/packages/ui-core/src/gantt/GanttChart.tsx
js_modules/dagster-ui/packages/ui-core/src/ui/GraphQueryInput.tsx

[Selection syntax] Update logic using old syntax to use new syntax when feature flag is enabled

---

python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster/_daemon/sensor.py

adds ability to instrument sensor latency

instrument asset daemon

---

python_modules/libraries/dagster-dg/setup.py

add watchdog to dagster-dg deps

---

python_modules/libraries/dagster-dg/dagster_dg/cli/list.py
python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_check_defs_command.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_check_yaml_command.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_dev_command.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_init_command.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_utils_inspect_command.py

Renames some internal and test functions and files for consistency and to line up with our CLI command names.

[components] Internal function renames

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-selection/input/AssetSelectionInput.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-selection/input/useAssetSelectionInput.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetTable.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx
js_modules/dagster-ui/packages/ui-core/src/op-selection/AntlrOpSelection.ts
js_modules/dagster-ui/packages/ui-core/src/pipelines/GraphNotices.tsx
js_modules/dagster-ui/packages/ui-core/src/run-selection/AntlrRunSelection.ts
js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInput.tsx
js_modules/dagster-ui/packages/ui-core/src/selection/createSelectionLinter.ts

[Asset selection] better error message on invalid input

---

js_modules/dagster-ui/packages/ui-core/src/selection/BaseSelectionVisitor.ts
js_modules/dagster-ui/packages/ui-core/src/selection/SelectionAutoCompleteVisitor.ts
js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInput.tsx
js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInputUtil.ts
js_modules/dagster-ui/packages/ui-core/src/selection/__tests__/SelectionAutoComplete.test.ts
js_modules/dagster-ui/packages/ui-core/src/selection/useSelectionInputLintingAndHighlighting.tsx

fix this bug:
https://github.com/user-attachments/assets/9c345c26-67da-4650-8d8f-8e184cacc795
jest + manual testing.
https://github.com/user-attachments/assets/47b67b69-3d3a-47b7-8b8e-aa5935648556

[Selection syntax auto complete] Fix autocomplete for tag values that have a key and a value.

---

js_modules/dagster-ui/packages/ui-core/src/search/links.tsx
js_modules/dagster-ui/packages/ui-core/src/search/types.ts

As titled.
Manually tested asset search in cloud.

[Selection syntax] Update search links

---

examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/k8s_eks_fake_example.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/pyop_asset_shared.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/pyop_multi_asset_complete.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/using_dbt_assets.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/using_k8s_pipes.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/using_pipes_subprocess.py

DG-ify operator guides

---

examples/airlift-federation-tutorial/airlift_federation_tutorial/dagster_defs/definitions.py
examples/airlift-federation-tutorial/snippets/federated_execution.py
examples/airlift-federation-tutorial/snippets/observe.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/k8s_eks_fake_example.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/pyop_asset_shared.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/pyop_multi_asset_complete.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/using_dbt_assets.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/using_k8s_pipes.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/using_pipes_subprocess.py

DG-ify code snippets in federation tutorial.
Eyes, existing tests

DG-ify federation tutorial

---

examples/airlift-federation-tutorial/airlift_federation_tutorial/dagster_defs/definitions.py
examples/airlift-federation-tutorial/snippets/federated_execution.py
examples/airlift-federation-tutorial/snippets/observe.py
examples/airlift-migration-tutorial/tutorial_example/dagster_defs/stages/standalone.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/k8s_eks_fake_example.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/pyop_asset_shared.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/pyop_multi_asset_complete.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/using_dbt_assets.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/using_k8s_pipes.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/using_pipes_subprocess.py

Improve highlighting on the "decomission airflow dag" code example
Existing, eyes

Highlight standalone

---

examples/airlift-federation-tutorial/airlift_federation_tutorial/dagster_defs/definitions.py
examples/airlift-federation-tutorial/snippets/federated_execution.py
examples/airlift-federation-tutorial/snippets/observe.py
examples/airlift-migration-tutorial/tutorial_example/dagster_defs/stages/migrate_dag_level.py
examples/airlift-migration-tutorial/tutorial_example/dagster_defs/stages/standalone.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/k8s_eks_fake_example.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/pyop_asset_shared.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/pyop_multi_asset_complete.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/using_dbt_assets.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/using_k8s_pipes.py
examples/docs_snippets/docs_snippets/integrations/airlift/operator_migration/using_pipes_subprocess.py

Improving dag-level migration highlighting, and dg-ifying code
Eyes, unit

Migrate dag level better highlighting

---

docs/docs/guides/labs/components/creating-new-component-types/creating-and-registering-a-component-type.md

fix docs build for components docs

---

docs/docs/guides/labs/components/components-etl-pipeline-tutorial.md

[docs] eliminate tab from component docs

---

js_modules/dagster-ui/packages/ui-core/src/app/CustomAlertProvider.tsx
js_modules/dagster-ui/packages/ui-core/src/app/Flags.tsx

Expose a method to toggle a feature flag outside of the normal flow
used with https://github.com/dagster-io/internal/pull/14314

Add method to toggle feature flag

---

docs/yarn.lock
js_modules/dagster-ui/yarn.lock

Resolves several dependabot alerts:
- https://github.com/dagster-io/dagster/security/dependabot/783
- https://github.com/dagster-io/dagster/security/dependabot/782
- https://github.com/dagster-io/dagster/security/dependabot/781
- https://github.com/dagster-io/dagster/security/dependabot/780
BK

[ui] Clean up babel dependabot alerts

---

python_modules/libraries/dagster-dg/dagster_dg/docs/.next/trace
python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/ComponentSchema.tsx
python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/css/ComponentSchema.module.css
python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/schema/ArrayTag.tsx
python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/schema/TypeTag.tsx
python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/schema/css/ArrayTag.module.css
python_modules/libraries/dagster-dg/dagster_dg/docs/app/components/schema/css/TypeTag.module.css
python_modules/libraries/dagster-dg/dagster_dg/docs/package.json
python_modules/libraries/dagster-dg/dagster_dg/docs/yarn.lock

Progress on rendering the JSONSchema for dg docs.
This is fairly broken right now, so keep your expectations low. JSONSchema is no picnic to render, so I'll need a few more passes (and some design help) to nail everything down.
dg docs, view schema section. Expand and collapse sections, verify that things sort of work the way I want them to.

[dg] Docs component schema UI initial attempt

---

python_modules/dagster/dagster/_daemon/daemon.py
python_modules/dagster/dagster/_daemon/sensor.py

add instrumentation hook for sensor daemon to track how much time has elapsed since last tick

instrument sensor daemon

---

docs/docs/examples/bluesky/index.md

Corrections to the project overview.

Bluesky example typos

---

examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/1-help.txt
python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py

Update dg help command to be less components-specific

---

js_modules/dagster-ui/packages/ui-core/src/gantt/GanttChartSelectionInput.tsx
js_modules/dagster-ui/packages/ui-core/src/pipelines/OpGraphSelectionInput.tsx

Similar to https://github.com/dagster-io/dagster/pull/28435
locally

[Op Selection] Make submitting an invalid query with only a single value convert to a name substring filter.

---

python_modules/libraries/dagster-dg/MANIFEST.in

dn exclude .yarn folder

---

docs/vercel.json

See https://linear.app/dagster-labs/issue/DOC-947/add-missing-redirects-for-airlift-docs
Staging build.

DOC-947 Add missing Airlift docs redirects

---

docs/docs/guides/build/assets/asset-selection-syntax/examples.md
docs/docs/guides/build/assets/asset-selection-syntax/index.md
docs/docs/guides/build/assets/asset-selection-syntax/reference.md

Fix links in asset selection syntax docs

---

python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py

Summary:
Missed a spot in https://github.com/dagster-io/dagster/pull/28345
BK

fix dagster-dg tests

---

js_modules/dagster-ui/packages/ui-core/src/setupTests.ts

[jest] Add worker stub

---

python_modules/libraries/dagster-components/dagster_components/resolved/context.py
python_modules/libraries/dagster-components/dagster_components/resolved/model.py
python_modules/libraries/dagster-components/dagster_components/test/basic_components.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/integration_test_defs/validation/basic_component_resolve_exc/component.yaml
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/test_sling_integration_test.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/validation_tests/test_component_validation.py

include yaml source and resolution context when a Resolver function raises an exception
example screenshot:
added test

[resolved] embelish resolver exceptions

---

python_modules/libraries/dagster-dg/dagster_dg/cli/docs.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_dev_command.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_docs_commands.py
python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py

[dg docs] Allow port to be configured by user, default to 3004

---

docs/docs/guides/labs/components/building-pipelines-with-components/adding-components-python.md
docs/docs/guides/labs/components/building-pipelines-with-components/adding-components.md
docs/docs/guides/labs/dg/incrementally-adopting-dg/migrating-definitions.md
docs/docs/guides/labs/dg/incrementally-adopting-dg/migrating-project.md

Fixes dg and components docs links to fix docs build.
Local build.

[DOCS] Fix build

---

docs/dagsterVersions.json
docs/docusaurus.config.ts

Updates versioned docs for 1.10.5 release.

DOC-941 Update versioned docs for 1.10.5 release

---

docs/docs/guides/labs/dg/scaffolding-a-project.md
examples/docs_beta_snippets/docs_beta_snippets/guides/dg/scaffolding-project/1-scaffolding-project.txt
examples/docs_beta_snippets/docs_beta_snippets/guides/dg/scaffolding-project/2-tree.txt
examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/test_components_docs.py
examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/utils.py
examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/dg/test_scaffolding_project.py

Add short guide on "Scaffolding a project". This just shows you how to run `dg scaffold project` and describes the resulting structure.
New snippet tests.

[components] "Scaffolding a project" guide

---

docs/docs/guides/labs/dg/uv-integration.md

Add guide on `dg`'s `uv integration`. This describes the current state of things and is likely to change very soon.

[components] uv integration guide

---

docs/sphinx/sections/api/apidocs/assets.rst

[docs] adds AutomationResult

---

docs/yarn.lock

[docs] update yarn.lock

---

docs/docs/about/releases.md

As title. Fixed AD-937.
Docs preview

[docs] Update Releases and compatibility guide with new API lifecycle language

---

python_modules/libraries/dagster-components/dagster_components/components/dbt_project/component.py
python_modules/libraries/dagster-components/dagster_components/components/sling_replication_collection/component.py
python_modules/libraries/dagster-dg/dagster_dg/cli/list.py

I added more lengthy descriptions for the demo and I think we should keep them.
NOCHANGELOG

[dg] Copy changes to for demo

---

docs/docs/guides/build/external-pipelines/using-dagster-pipes/reference.md
examples/docs_snippets/docs_snippets/guides/dagster/dagster_pipes/subprocess/with_asset_check/dagster_code.py

Fix broken example for Pipes subprocess asset check.

[docs] Correct pipes asset check example

---

python_modules/libraries/dagster-polars/dagster_polars/io_managers/delta.py
python_modules/libraries/dagster-polars/dagster_polars_tests/test_polars_parquet.py
python_modules/libraries/dagster-polars/dagster_polars_tests/test_upath_io_managers.py
python_modules/libraries/dagster-polars/dagster_polars_tests/test_upath_io_managers_lazy.py

Summary:
Apparently this is the correct way to indicate streaming now.

Attempt to fix dagster-polars tests

---

python_modules/libraries/dagster-polars/dagster_polars/io_managers/delta.py
python_modules/libraries/dagster-polars/dagster_polars_tests/test_polars_parquet.py
python_modules/libraries/dagster-polars/dagster_polars_tests/test_upath_io_managers.py
python_modules/libraries/dagster-polars/dagster_polars_tests/test_upath_io_managers_lazy.py

Summary:
Reverts my original fix and apply a more tactical change to work around the specifc upstream bug that was introduced
See https://github.com/pola-rs/polars/issues/21799 for context

Polars test fix, take 2

---

python_modules/automation/automation_tests/test_repo.py
python_modules/automation/tox.ini

Fix automation tests from dagster-shared package

---

docs/docs/guides/labs/components/building-pipelines-with-components/adding-components.md

Fixes #28494
- [docs] fix component templating example

[docs] fix component templating example

---

examples/docs_beta_snippets/docs_beta_snippets/guides/components/custom-subclass/custom-scope.py

Resolves #28522
- [docs] fix component with custom scopes example in docs

[docs] fix component with custom scopes example in docs

---

python_modules/libraries/dagster-dg/dagster_dg/context.py

Resolves #28521
- [dagster-dg] exclude `__pycache__` from `dg list component`

[dagster-dg] exclude `__pycache__` from `dg list component`

---

python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_checks.py

Fixes indent in test so that test is properly run. See comment [here](https://github.com/dagster-io/dagster/pull/28481#discussion_r1999592037).
BK

Fix AssetCheckEvaluation in dagster-dbt

---

scripts/generate_changelog.py

New changelog section for dg/components in `generate_changelog.py` script.

[dg] Add section to changelog template for components/dg

---

js_modules/dagster-ui/packages/ui-core/src/selection/CustomErrorListener.ts
js_modules/dagster-ui/packages/ui-core/src/selection/SelectionAutoCompleteProvider.tsx
js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInput.tsx
js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInputAutoCompleteResults.tsx
js_modules/dagster-ui/packages/ui-core/src/selection/__tests__/createSelectionLinter.test.ts

[Selection input] More pronounced error state + empty state

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py

Just didn't want to block the PR underneath this 
NOCHANGELOG

[cleanup] Minor aesthetic improvements

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/client.py

[dagster-dbt] Make DbtCloudWorkspaceClient.list_jobs request limit configurable by env var

---

docs/docs/dagster-plus/deployment/deployment-types/hybrid/azure/index.md

Reported by a customer. Looks akin to https://github.com/dagster-io/dagster/pull/28387.
(Waiting for docs preview...)

Fix broken links on Dagster+ Azure deployment docs

---

docs/package.json
docs/src/components/CodeExample.tsx
docs/src/utils/codeExampleUtils.test.ts
docs/src/utils/codeExampleUtils.ts
docs/vitest.config.ts
docs/vitest.mocks.ts
docs/vitest.setup.ts
docs/yarn.lock

[docs] adds unit tests for `filterNoqaComments` and `trimMainBlock`

---

examples/starlift-demo/dbt_example/dagster_defs/migrate.py
examples/starlift-demo/dbt_example/dagster_defs/observe.py
examples/starlift-demo/dbt_example/dagster_defs/peer.py
examples/starlift-demo/dbt_example/migrating_airflow_dags/proxied_state/rebuild_iris_models.yaml

Change polling interval for starlift demo.

[starlift-demo] polling interval

---

.gitignore

Not sure if we want to exclude or write our own. For now I'm just excluding to get git to leave me alone 😆

Exclude CLAUDE.md context file using gitignore

---

js_modules/dagster-ui/packages/ui-core/src/graph/SVGConsts.ts
js_modules/dagster-ui/packages/ui-core/src/graph/SVGViewport.tsx

Allow zooming out a lot more.
https://github.com/user-attachments/assets/c7dbb488-7734-4f7e-803c-9ddba795bc54
[ui] Asset graph can now zoom out a lot more.

[Asset graph] Allow zooming out more.

---

python_modules/libraries/dagster-dg/dagster_dg/cli/check_utils.py
python_modules/libraries/dagster-shared/dagster_shared/yaml_utils/source_position.py

shuffle around how we produce formatted yaml errors so we can improve the ones we throw from definition validation 

[dg] refactor yaml error sourcing

---

CHANGES.md

[changelog] 1.10.6

---

python_modules/libraries/dagster-embedded-elt/setup.py

Avoid confusion with the pre-release

Add pins to dagster-sling and dagster-dlt in dagster-embedded-elt

---

pyright/alt-1/requirements-pinned.txt
pyright/master/requirements-pinned.txt
pyright/master/requirements.txt

Add dagster-dbt Kitchen Sink to pyright pins

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/client.py
python_modules/libraries/dagster-dbt/kitchen-sink/conftest.py
python_modules/libraries/dagster-dbt/kitchen-sink/dagster_dbt_cloud_kitchen_sink/defs.py
python_modules/libraries/dagster-dbt/kitchen-sink/dagster_dbt_cloud_kitchen_sink/resources.py
python_modules/libraries/dagster-dbt/kitchen-sink/dagster_dbt_cloud_kitchen_sink/utils.py
python_modules/libraries/dagster-dbt/kitchen-sink/dagster_dbt_cloud_kitchen_sink_tests/conftest.py
python_modules/libraries/dagster-dbt/kitchen-sink/dagster_dbt_cloud_kitchen_sink_tests/test_client_methods.py
python_modules/libraries/dagster-dbt/kitchen-sink/dagster_dbt_cloud_kitchen_sink_tests/test_workspace_from_env.py

This PR adds defs and tests for the DbtCloudWorkspace in the dbt Cloud kitchen sink. We are testing the client connection and client methods.
Tested locally + BK

[dagster-dbt] Add resource definitions and tests in dbt Cloud kitchen sink

---

python_modules/dagster/dagster/_core/definitions/time_window_partitions.py

Still investigating exactly how this can happen -- it seems to be something where the `AllPartitionsSubset` behaves a bit strangely when handling certain intersection operations, but we're gonna need this code to handle objects that were serialized before the fix anyway.
Fixed an issue that could cause automation condition evaluations to fail to render in the UI in rare cases.

[time-window-partitions][fix] Fix calculation of num_partitions for subsets with negative ranges

---

python_modules/libraries/dagster-dbt/kitchen-sink/dagster_dbt_cloud_kitchen_sink_tests/test_client_methods.py
python_modules/libraries/dagster-deltalake-pandas/dagster_deltalake_pandas_tests/test_type_handler.py
python_modules/libraries/dagster-polars/dagster_polars/io_managers/delta.py
python_modules/libraries/dagster-polars/dagster_polars_tests/test_polars_parquet.py
python_modules/libraries/dagster-polars/dagster_polars_tests/test_upath_io_managers.py
python_modules/libraries/dagster-polars/dagster_polars_tests/test_upath_io_managers_lazy.py

#28635 shifted pins around and surfaced new type erros mostly in tests
this just squelches them 
pyright

fix pyright

---

python_modules/libraries/dagster-dbt/kitchen-sink/dagster_dbt_cloud_kitchen_sink_tests/conftest.py
python_modules/libraries/dagster-dbt/kitchen-sink/dagster_dbt_cloud_kitchen_sink_tests/test_client_methods.py

Ad title. Endpoints added in https://github.com/dagster-io/dagster/pull/28552
BK

[dagster-dbt] Add project and environment endpoints to dbt Cloud kitchen sink

---

docs/docs/dagster-plus/features/authentication-and-access-control/rbac/audit-logs.md

[docs] remove placeholder to "Add screenshot"

---

python_modules/dagster/dagster/_core/storage/asset_check_execution_record.py
python_modules/dagster/dagster_tests/declarative_automation_tests/automation_condition_tests/builtins/test_check_condition.py

[checks] Update logic for determining if an asset check evaluation targets the latest materialization event.

---

docs/sphinx/_ext/sphinx-mdx-builder/sphinxcontrib/mdxbuilder/writers/mdx.py
docs/src/styles/custom.scss

Closes DOC-642.
https://github.com/user-attachments/assets/0764d3ac-6245-4201-abce-0214fd41b605
`yarn start`
- [docs] added hash links for anchors to functions and classes in API docs

[docs] adds hash-link to function signatures and classes

---

docs/docs/guides/operate/graphql/index.md

[docs] fix link to graphql client

---

python_modules/automation/Makefile
python_modules/automation/tox.ini

Part of the problem with the existing config generation is that it's not enforced in any way, to ensure it's up to date. This adds it to the CI.
BK

Ensure up-to-date Dataproc and Spark configuration

---

docs/docs/guides/monitor/logging/index.md

[docs] fix python guide href

---

.buildkite/dagster-buildkite/dagster_buildkite/utils.py
docs/tox.ini
examples/assets_pandas_pyspark/tox.ini
examples/docs_beta_snippets/tox.ini
examples/docs_snippets/tox.ini
examples/project_fully_featured/tox.ini
examples/with_pyspark/tox.ini
examples/with_pyspark_emr/tox.ini
python_modules/automation/tox.ini
python_modules/dagster-test/tox.ini
python_modules/libraries/dagster-airflow/tox.ini
python_modules/libraries/dagster-aws/tox.ini
python_modules/libraries/dagster-azure/tox.ini
python_modules/libraries/dagster-databricks/tox.ini
python_modules/libraries/dagster-duckdb-pyspark/tox.ini
python_modules/libraries/dagster-gcp-pyspark/tox.ini
python_modules/libraries/dagster-ge/tox.ini
python_modules/libraries/dagster-pagerduty/build-constraints
python_modules/libraries/dagster-pagerduty/setup.cfg
python_modules/libraries/dagster-pagerduty/tox.ini
python_modules/libraries/dagster-pyspark/build-constraints
python_modules/libraries/dagster-pyspark/setup.cfg
python_modules/libraries/dagster-pyspark/tox.ini
python_modules/libraries/dagster-snowflake-pyspark/tox.ini
scripts/run-pyright.py

pin setuptools to avoid pyspark issue

---

.buildkite/dagster-buildkite/dagster_buildkite/utils.py

Changes made to the dbt Cloud kitchen sink itself where not included to the no skip. 
BK

[buildkite] Run dbt Cloud kitchen sink when tests are updated

---

examples/docs_snippets/docs_snippets_tests/integrations_tests/test_dagstermill.py
examples/docs_snippets/tox.ini
python_modules/libraries/dagstermill/dagstermill/test_utils.py
python_modules/libraries/dagstermill/dagstermill_tests/test_io.py
python_modules/libraries/dagstermill/dagstermill_tests/test_ops.py

I switched over to uv while fixing the setuptools issue which caused these test import to surface.
This just moves things to `dagstermill.test_utils`
bk

[dagstermill] fix test imports

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/client.py

[dagster-dbt] Add missing docstrings for artifacts endpoints in DbtCloudWorkspaceClient

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
.buildkite/dagster-buildkite/dagster_buildkite/utils.py
python_modules/libraries/dagster-dbt/kitchen-sink/tox.ini

[dagster-dbt] Fix pyproject.toml path in dbt Cloud kitchen sink

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py

Moving this test into it's own class so that we don't run it in internal. Will re-implement for internal in https://github.com/dagster-io/internal/pull/14393

move asset materialization history test

---

python_modules/dagster/dagster/_utils/warnings.py
python_modules/libraries/dagster-shared/dagster_shared/utils/warnings.py

Required for `dagster._serdes`
NOCHANGELOG

[dagster-shared] `dagster.utils._warnings`

---

docs/docs/dagster-plus/deployment/deployment-types/serverless/run-isolation.md

Addresses https://github.com/dagster-io/dagster/issues/15749
👀

[docs] update non-isolated runs content and show how to use `dagster/isolation` tag

---

docs/docs/dagster-plus/deployment/management/environment-variables/agent-config.md

Addresses [DSE-1](https://linear.app/dagster-labs/issue/DSE-1/[ib]-document-what-happens-if-the-same-environment-variable-is)
👀

[docs] add note about env var precedence in agent config

---

python_modules/libraries/dagster-dg/dagster_dg/cli/plus.py
python_modules/libraries/dagster-dg/dagster_dg/utils/plus/gql.py
python_modules/libraries/dagster-dg/dagster_dg/utils/plus/gql_client.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/plus_tests/test_plus_login_command.py
python_modules/libraries/dagster-shared/dagster_shared/plus/config.py

Prompts the user to select a default deployment when setting up the CLI.

[dg] Add GQL client, default deployment selection to dg login flow

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
js_modules/dagster-ui/packages/ui-core/src/search/__fixtures__/Search.fixtures.tsx
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py

Follow ups from https://github.com/dagster-io/dagster/pull/28506 to add cursoring based on event log id

[gql] cursoring for asset materialization history endpoint

---

docs/docs/guides/automate/schedules/testing-schedules.md
docs/docs/guides/automate/schedules/using-resources-in-schedules.md
docs/docs/guides/automate/sensors/testing-sensors.md
docs/docs/guides/automate/sensors/using-resources-in-sensors.md
docs/docs/guides/operate/configuration/advanced-config-types.md
docs/docs/guides/operate/configuration/run-configuration.md
docs/src/components/CodeExample.tsx
docs/src/utils/codeExampleUtils.test.ts
docs/src/utils/codeExampleUtils.ts

Closes DOC-746.
- [docs] added `dedent` prop to `CodeExample` component

[docs] add dedent prop to CodeExample

---

python_modules/libraries/dagster-dg/dagster_dg/docs/package.json
python_modules/libraries/dagster-dg/dagster_dg/docs/yarn.lock

Resolve https://github.com/dagster-io/dagster/security/dependabot/792.
`dg docs serve`, `yarn build`

[dg] Dependabot update in dg docs

---

examples/docs_beta_snippets/docs_beta_snippets/guides/components/index/2-scaffold.txt
examples/docs_beta_snippets/docs_beta_snippets_tests/snippet_checks/guides/components/utils.py
python_modules/libraries/dagster-dg/dagster_dg/cli/dev.py
python_modules/libraries/dagster-dg/dagster_dg/cli/docs.py
python_modules/libraries/dagster-dg/dagster_dg/cli/init.py
python_modules/libraries/dagster-dg/dagster_dg/cli/launch.py
python_modules/libraries/dagster-dg/dagster_dg/cli/list.py
python_modules/libraries/dagster-dg/dagster_dg/cli/plus.py
python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
python_modules/libraries/dagster-dg/dagster_dg/cli/utils.py
python_modules/libraries/dagster-dg/dagster_dg/utils/telemetry.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_telemetry.py

Wraps the remainder of dg cli commands in the telemetry wrapper.
Existing sanity tests.

[dg] add telemetry to remaining commands

---

docs/dagsterVersions.json
docs/docusaurus.config.ts

Merge this after 1.10.7 release.

DOC-965 Add link to 1.10.6 docs to version dropdown (WAIT TO MERGE)

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_cli_event.py
python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_cli_invocation.py
python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_event_iterator.py

[dagster-dbt] Update docstring with AssetCheckEvaluation in dbt core library

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/check_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py
python_modules/dagster/dagster_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_result_value_hash.py

[da] Remove AssetSelection information from DepsCondition/ChecksCondition

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/client.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/conftest.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_resources.py
python_modules/libraries/dagster-dbt/kitchen-sink/dagster_dbt_cloud_kitchen_sink_tests/test_client_methods.py

This PR adds the `get_runs_batch` method that will be needed in the polling sensor for dbt Cloud.
New tests with BK

[dagster-dbt] Add get_runs_batch to DbtCloudWorkspaceClient

---

js_modules/dagster-ui/packages/ui-core/src/search/useIndexedDBCachedQuery.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/__tests__/WorkspaceContext.test.tsx

This reverts commit 10bce4e657f7efc1bd68be3b3a82dbcf4c34c29e.

Revert "Refactor `useIndexedDBCachedQuery` (#28629)"

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/Sidebar.tsx

cast querystring from object to array before setting it

---

Makefile
docs/docs/partials/_InstallDg.md

Summary:
This is a big pain now that dagster-shared is in the mix - add a Makefile command to make it less of a pain.

Makefile command for building uv tool environments editably

---

python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_telemetry.py

Simplify telemetry tests, now just checks that all commands are annotated except explicitly ignored commands.

[dg] simplify telemetry tests

---

docs/docs/guides/build/partitions-and-backfills/defining-dependencies-between-partitioned-assets.md

Addresses https://github.com/dagster-io/dagster/issues/16023
👀

[docs] note that custom PartitionMapping is not supported

---

python_modules/libraries/dagster-components/dagster_components/component/component.py
python_modules/libraries/dagster-components/dagster_components/resolved/base.py
python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_field_utilites.py
python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolved.py
python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolved_from.py

inspect the `__init__` signature to determine the fields, works for `Resolved` and `ResolvedFrom`
added tests

[resolved] handle classes with __init__

---

python_modules/libraries/dagster-dg/setup.py

add gql dep to dagster-dg

---

docs/docs/guides/automate/sensors/index.md
js_modules/dagster-ui/packages/ui-core/src/pipelines/PipelineExplorerRoot.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/search/__tests__/useIndexedDBCachedQuery.test.tsx
js_modules/dagster-ui/packages/ui-core/src/search/useIndexedDBCachedQuery.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/__tests__/WorkspaceContext.test.tsx

Redo of https://github.com/dagster-io/dagster/pull/28629 but this time with automatic refetching when variables change.
Added a test case for this previously untested behavior + local testing with the job graphs and switching between them using the left nav.

Redo Refactor useIndexedDBCachedQuery 

---

python_modules/libraries/dagster-components/dagster_components/__init__.py

add Resolvable to dagster_components top level

---

CHANGES.md

[dg] Changelog updates for 1.10.7

---

python_modules/libraries/dagster-shared/dagster_shared/telemetry/__init__.py

Fix dagster.yaml telemetry load when empty file

---

docs/docs/dagster-plus/features/authentication-and-access-control/rbac/audit-logs.md
docs/docs/dagster-plus/features/authentication-and-access-control/rbac/teams.md
docs/docs/dagster-plus/features/authentication-and-access-control/rbac/user-roles-permissions.md
docs/docs/dagster-plus/features/authentication-and-access-control/rbac/users.md
docs/docs/guides/build/external-pipelines/javascript-pipeline.md

Addresses the following Linear tickets:
* https://linear.app/dagster-labs/issue/DOC-899/update-documentation-with-new-dagster-iodagster-pipes-npm-package
* https://linear.app/dagster-labs/issue/DOC-918/port-over-custom-roles-content-into-new-docs
Also generally cleans up RBAC docs.
Local build.

[Docs] Fixes for DOC-899 and DOC-918

---

examples/docs_snippets/docs_snippets/guides/components/shell-script-component/with-scaffolder.py
python_modules/dagster-test/dagster_test/components/simple_pipes_script_asset.py
python_modules/libraries/dagster-components/dagster_components/__init__.py
python_modules/libraries/dagster-components/dagster_components/component/component_scaffolder.py
python_modules/libraries/dagster-components/dagster_components/component_scaffolding.py
python_modules/libraries/dagster-components/dagster_components/lib/dbt_project/scaffolder.py
python_modules/libraries/dagster-components/dagster_components/lib/definitions_component/scaffolder.py
python_modules/libraries/dagster-components/dagster_components/lib/sling_replication_collection/scaffolder.py
python_modules/libraries/dagster-components/dagster_components_tests/integration_tests/lib/duckdb_component/step_four.py

In preparation for generalizing scaffolding, renaming `scaffold_component_yaml` to `scaffold_component`
BK
NOCHANGELOG

[dg] Rename scaffold_component_yaml to scaffold_component

---

python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py

[dg] Fix help text for project / workspace / component-type

---

python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

so we can emit batch events in https://github.com/dagster-io/internal/pull/14120
new unit test

support batch write in `report_dagster_event`

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/rule_condition.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/any_downstream_conditions_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/check_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/newly_true_operator.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/since_operator.py
python_modules/dagster/dagster_tests/declarative_automation_tests/automation_condition_tests/builtins/test_on_cron_condition.py
python_modules/dagster/dagster_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_result_value_hash.py

Make rule unique IDs more resilient to dependencies being added in the middle of an AllDepsCondition

---

examples/docs_snippets/docs_snippets/guides/components/shell-script-component/2-shell-command-empty.py
python_modules/libraries/dagster-components/dagster_components/resolved/base.py
python_modules/libraries/dagster-components/dagster_components_tests/resolution_tests/test_resolved.py
python_modules/libraries/dagster-dg/dagster_dg/templates/COMPONENT_TYPE/COMPONENT_TYPE_NAME_PLACEHOLDER.py.jinja

switch to `Resolvable` and  `__init__` method (least opinionated option) 
bk

update component type scaffold

---

python_modules/libraries/dagster-dg/dagster_dg/cli/docs.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_docs_commands.py

Fix `dg docs serve` in master, for editable installs. Still need to do subsequent work to get the packaged python module working properly.

[dg docs] temp fix for new js location

---

docs/docs/dagster-plus/features/authentication-and-access-control/rbac/user-roles-permissions.md

Fixing broken RBAC table

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/client.py

As title. Also, we move the way we get the value for the "data" key, now done in the user facing client methods. Fixes the comment [here](https://github.com/dagster-io/dagster/pull/28796#discussion_r2017764177). 
BK

[dagster-dbt] Return raw response in DbtCloudWorkspaceClient._make_request()

---

python_modules/dagster/dagster/_generate/download.py

Fixes these test failures: https://buildkite.com/dagster/dagster-dagster/builds/116887

Fix even more failing tests

---

examples/docs_snippets/docs_snippets/guides/components/index/26-component-ingest-automation.yaml
examples/docs_snippets/docs_snippets/guides/components/index/27-component-jdbt-automation.yaml

[dg] Fix build

---

js_modules/dagster-ui/packages/ui-core/src/assets/useAssetCatalogFiltering.oss.tsx

Use loading state for client side filtering

---

python_modules/libraries/dagster-components/dagster_components/cli/list.py

This property is actually not displayed at all...
BK
NOCHANGELOG

[dg] use automation_condition.get_label rather than __name__

---

docs/docs/guides/labs/components/creating-new-component-types/creating-and-registering-a-component-type.md

[docs] fix typo in component authoring

---

docs/CONTRIBUTING.md
docs/sphinx/README.md

Addresses https://linear.app/dagster-labs/issue/DOC-989/document-how-to-write-api-docstrings
👀 

DOC-989 Document how to write API docs

---

js_modules/dagster-ui/packages/ui-core/src/integrations/IntegrationIcon.tsx
js_modules/dagster-ui/packages/ui-core/src/integrations/IntegrationPage.tsx
js_modules/dagster-ui/packages/ui-core/src/integrations/IntegrationTag.tsx
js_modules/dagster-ui/packages/ui-core/src/integrations/MarketplaceHome.tsx
js_modules/dagster-ui/packages/ui-core/src/integrations/__stories__/IntegrationPage.stories.tsx
js_modules/dagster-ui/packages/ui-core/src/integrations/__stories__/MarketplaceHome.stories.tsx
js_modules/dagster-ui/packages/ui-core/src/integrations/css/IntegrationPage.module.css
js_modules/dagster-ui/packages/ui-core/src/integrations/types.tsx
js_modules/dagster-ui/packages/ui-core/src/ui/CopyButton.tsx

Add Storybook components for first pass at Integrations Marketplace and individual Integration pages.
yarn storybook, verify hover, text entry, copy behavior.

[dg] Integrations Marketplace in Storybook

---

docs/sphinx/sections/api/apidocs/libraries/dagster-k8s.rst
docs/vercel.json

Fix broken link in dagster-k8s API doc and add redirect

---

python_modules/dagster/dagster/_core/remote_representation/origin.py

ManagedGrpcPythonEnvCodeLocationOrigin uses @record
BK
NOCHANGELOG

ManagedGrpcPythonEnvCodeLocationOrigin

---

python_modules/dagster/dagster/_core/remote_representation/origin.py

RegisteredCodeLocationOrigin

---

python_modules/dagster/dagster/_core/remote_representation/origin.py

InProcessCodeLocationOrigin

---

python_modules/dagster/dagster/_core/remote_representation/origin.py

GrpcServerCodeLocationOrigin

---

python_modules/dagster/dagster/_core/remote_representation/origin.py

RemoteRepositoryOrigin

---

python_modules/dagster/dagster/_core/remote_representation/origin.py

RemoteJobOrigin

---

python_modules/dagster/dagster/_core/remote_representation/origin.py

RemoteInstigatorOrigin

---

python_modules/dagster/dagster/_core/remote_representation/origin.py

RemotePartitionSetOrigin

---

python_modules/dagster/dagster/_core/workspace/load_target.py

Convert load_target.py to record

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/logs/events.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
python_modules/dagster-test/dagster_test/toys/seed_asset_failure_events.py
python_modules/dagster/dagster/_core/definitions/events.py
python_modules/dagster/dagster/_core/events/__init__.py
python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

test out failure type and reason

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/operands.py
python_modules/dagster/dagster_tests/declarative_automation_tests/automation_condition_tests/builtins/test_executed_with_tags_condition.py

Fixed an issue with `AutomationCondition.executed_with_tags()` that would cause the `tag_keys` argument to not be respected.
Updated the display name of `AutomationCondition.executed_with_tags()` to contain the relevant tag_keys and tag_values.

[da] Update executed_with_tags

---

python_modules/dagster/dagster_tests/daemon_tests/test_queued_run_coordinator_daemon.py

add retry to test_op_concurrency_root_progress

---

CHANGES.md

Changelog 1.10.8

---

python_modules/automation/automation/docker/image_defs.py

Updated our image to point at the directory that we moved to here https://github.com/dagster-io/dagster/pull/28879

Fixup building k8s example image

---

python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_cli_event.py

Summary:
If I am understanding this case correctly, this copy is missing a "not"?
BK, eyes

Fix copy for missing asset check selection

---

CHANGES.md

changelog 1.10.9

---

examples/components_yaml_checks_dsl/existing_code/checks.yaml
examples/components_yaml_checks_dsl/existing_code/engine.py
examples/components_yaml_checks_dsl/existing_code/loader.py

This is just an import of code that will never be executed, but this example is implementing a version of this using Components. Placing it outside the package to make that clear.
None.
NOCHANGELOG

Import code and format

---

python_modules/libraries/dagster-gcp/dagster_gcp/gcs/resources.py

- Close #28578 
- Remove context manager from the GCS resource example
- Local build and test

[docs] fix dagster-gcp gcs resource example

---

examples/docs_snippets/docs_snippets/guides/components/index/1-help.txt
python_modules/libraries/dagster-dg/dagster_dg/cli/init.py
python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py

Summary:
Explain that by default only a project is initialized.
BK

Update dg init help text

---

python_modules/dagster/dagster/_daemon/monitoring/run_monitoring.py
python_modules/dagster/dagster_tests/daemon_tests/test_monitoring_daemon.py

This is a somewhat unexpected case, but currently runs are in a NOT_STARTED state briefly after being created, before they transition to QUEUED (Ideally they would move right into QUEUED in a transaction, but that would be a larger change).
Ensure that in the unlikely event that a run gets stuck in NOT_STARTED state that it is eventually cleaned up by run monitoring.
New test case
Fixed an issue where run monitoring sometimes didn't fail runs that were stuck in a NOT_STARTED status instead of a STARTING status.

Ensure that run monitoring covers runs in a NOT_STARTED case

---

docs/dagsterVersions.json
docs/docusaurus.config.ts

DOC-990 Bump docs version for 1.10.9 release

---

python_modules/dagster/dagster/components/cli/list.py
python_modules/dagster/dagster/components/cli/scaffold.py
python_modules/dagster/dagster/components/component/component.py
python_modules/dagster/dagster/components/core/defs_module.py
python_modules/dagster/dagster/components/core/package_entry.py
python_modules/dagster/dagster/components/core/snapshot.py
python_modules/dagster/dagster/components/scaffold/scaffold.py
python_modules/dagster/dagster_tests/components_tests/cli_tests/test_commands.py
python_modules/dagster/dagster_tests/components_tests/registry_tests/test_registry.py
python_modules/dagster/dagster_tests/components_tests/test_integrity.py
python_modules/dagster/dagster_tests/components_tests/unit_tests/test_library_object_key.py
python_modules/libraries/dagster-components/dagster_components/__init__.py
python_modules/libraries/dagster-dg/dagster_dg/check.py
python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py
python_modules/libraries/dagster-dg/dagster_dg/cli/check_utils.py
python_modules/libraries/dagster-dg/dagster_dg/cli/docs.py
python_modules/libraries/dagster-dg/dagster_dg/cli/list.py
python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
python_modules/libraries/dagster-dg/dagster_dg/cli/utils.py
python_modules/libraries/dagster-dg/dagster_dg/component.py
python_modules/libraries/dagster-dg/dagster_dg/context.py
python_modules/libraries/dagster-dg/dagster_dg/docs.py
python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
python_modules/libraries/dagster-shared/dagster_shared/serdes/objects/__init__.py
python_modules/libraries/dagster-shared/dagster_shared/serdes/objects/package_entry.py

Internal rename to align with upstack changes
NOCHANGELOG

[dg] LibraryObject -> PackageEntry

---

.buildkite/dagster-buildkite/dagster_buildkite/pipelines/dagster_oss_nightly_pipeline.py

[nightly] finish ripping out gcp live tests

---

python_modules/libraries/dagster-dg/dagster_dg/cli/list.py

This reworks the output of `dg list defs` to be prettier / more in line with `dg list packages`
In service of that goal, I created the bare-minimum "framework" to standardize the pattern both of these use, which is to have a single "outer table" which contains multiple "inner tables". This will of course evolve over time to handle more custom use cases but for now I just wanted to avoid code duplication.
Before:
After:
NOCHANGELOG

[dg] Rework `dg list defs` output

---

python_modules/dagster/dagster/components/resolved/base.py
python_modules/dagster/dagster_tests/components_tests/resolution_tests/test_resolved.py

make sure we preserve any `Field()` properties that were set like `description` 
added test

[resolvable] preserve original FieldInfo settings

---

python_modules/dagster/dagster/_daemon/backfill.py

Missed this during https://github.com/dagster-io/dagster/pull/26189 - we create the logger outside of the threadpool, so there's no guarantee that it will still be active inside the threadpool. Instead, move its creation and teardown inside the function that executes inside the threadpool
BK, run 4 backfills simultaneously in an environment using InstigatorLogger and verify that the logs are correctly written to the different files simultaneously

Fix logger threading when launching multiple backfills simultaneously

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/useFavoriteAssets.oss.tsx

As titled.
Existing tests + local host cloud

Add first class support for favorites

---

python_modules/dagster/dagster/_daemon/run_coordinator/queued_run_coordinator_daemon.py

Summary: "on error" => "an error"
Test Plan: Eyes

[ez] fix typo in daemon error message

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetEventList.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetEvents.tsx

[AssetEvents] Use backgroundDefault for asset event list

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_health.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_health.py
python_modules/dagster/dagster/_core/instance/__init__.py

Stubs for the gql api for asset health - implementations in stacked prs

[gql] asset health api

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/resources.py
python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/sensor_builder.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_reconstruction.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_run_events.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_specs.py

Same as #29106 but for dbt Cloud

[dagster-dbt] Use get_or_fetch_workspace_data in DbtCloudWorkspace

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/cli_invocation.py
python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/run_handler.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/conftest.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_resources.py

As title. Fixes AD-1016, in response to this [comment](https://github.com/dagster-io/dagster/pull/28152#discussion_r2021957408).
New test with BK

[dagster-dbt] Add timeout param in DbtCloudCliInvocation.wait()

---

python_modules/dagster-webserver/dagster_webserver/webserver.py
python_modules/dagster-webserver/dagster_webserver_tests/webserver/test_app.py

Looks like #29026 broke master pretty hard. Reverting to get master green for everyone to wake up to.
BK
NOCHANGELOG

Revert "Use StaticFiles for directories in static routes (#29026)"

---

marketplace/api/index.ts

[marketplace] use dirname in paths

---

python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py
python_modules/libraries/dagster-dbt/dagster_dbt/components/dbt_project/component.py
python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py

just moving it over in this first PR, will promote it upstack 

[dbt] move get_asset_spec to translator

---

marketplace/.prettierrc.json
marketplace/api/index.ts
marketplace/vercel.json

The integration registry is a public API, so allow CORS. Also fix the broken file paths and remove some excess whitespace.
vercel dev

[marketplace] Allow cors

---

python_modules/dagster/dagster/_core/definitions/multi_dimensional_partitions.py
python_modules/dagster/dagster/_core/definitions/partition.py
python_modules/dagster/dagster/_core/definitions/time_window_partitions.py

The current set of UIs are a little bit slower with 100K partitions, but manageable.
BK

bump recommended limit on partitions

---

python_modules/dagster/dagster/_core/events/__init__.py
python_modules/dagster/dagster/_core/run_coordinator/queued_run_coordinator.py
python_modules/dagster/dagster/_daemon/run_coordinator/queued_run_coordinator_daemon.py
python_modules/dagster/dagster_tests/core_tests/run_coordinator_tests/test_queued_run_coordinator.py
python_modules/dagster/dagster_tests/daemon_tests/test_queued_run_coordinator_daemon.py

This just provides the event log with some more information about the origin of the run
could use pointers on what the relevant tests might be here

add context to run start

---

docs/docs/integrations/libraries/dbt/reference.md
examples/docs_snippets/docs_snippets/integrations/dbt/dbt.py

[dagster-dbt] Add profiles_dir, profile and target to dbt reference

---

examples/docs_snippets/docs_snippets/integrations/dbt/dbt.py

[docs] Fix downstream deps code display in dbt reference

---

CHANGES.md

[changelog] 1.10.10

---

js_modules/dagster-ui/packages/ui-core/src/ui/IndeterminateLoadingBar.tsx

as titled.
loaded the page and observed the animation is unchanged

[perf] Use transform to animate IndeterminateLoadingBar

---

docs/docs/guides/labs/dg/using-resources.md
examples/docs_snippets/docs_snippets/guides/dg/using-resources/1-asset-one.py
examples/docs_snippets/docs_snippets/guides/dg/using-resources/2-resources-at-defs-root.py
examples/docs_snippets/docs_snippets/guides/dg/using-resources/3-resource-defs-at-project-root.py
examples/docs_snippets/docs_snippets_tests/test_all_files_load.py

There's been a few questions about how to add resources to a `dg` project. This documents the current state.
Read.
NOCHANGELOG

[dg] Add docs for using resources in dg projects

---

docs/docs/integrations/libraries/looker/using-looker-with-dagster.md
examples/docs_snippets/docs_snippets/integrations/looker/customize_upstream_dependencies.py
examples/docs_snippets/docs_snippets_tests/test_integration_files_load.py

[docs] Add upstream deps guide for Looker

---

docs/docs/integrations/libraries/sigma/using-sigma-with-dagster.md
examples/docs_snippets/docs_snippets/integrations/sigma/customize_upstream_dependencies.py
examples/docs_snippets/docs_snippets_tests/test_integration_files_load.py

[docs] Add upstream deps guide for Sigma

---

docs/docs/integrations/libraries/fivetran.md
examples/docs_snippets/docs_snippets/integrations/fivetran/define_downstream_dependencies.py
examples/docs_snippets/docs_snippets_tests/test_integration_files_load.py

[docs] Add downstream deps guide for Fivetran

---

docs/docs/integrations/libraries/airbyte/airbyte-cloud.md
examples/docs_snippets/docs_snippets/integrations/airbyte_cloud/define_downstream_dependencies.py
examples/docs_snippets/docs_snippets_tests/test_integration_files_load.py

[docs] Add downstream deps guide for Airbyte Cloud

---

docs/docs/integrations/libraries/dlt/using-dlt-with-dagster.md
examples/docs_snippets/docs_snippets/integrations/dlt/customize_upstream_dependencies.py
examples/docs_snippets/docs_snippets_tests/test_integration_files_load.py

[docs] Add upstream deps guide for dlt

---

docs/docs/integrations/libraries/tableau.md
examples/docs_snippets/docs_snippets/integrations/tableau/customize_upstream_dependencies.py
examples/docs_snippets/docs_snippets_tests/test_integration_files_load.py

[docs] Add upstream deps guide for Tableau

---

docs/docs/integrations/libraries/powerbi/index.md
examples/docs_snippets/docs_snippets/integrations/power-bi/customize_upstream_dependencies.py
examples/docs_snippets/docs_snippets_tests/test_integration_files_load.py

[docs] Add upstream deps guide for PowerBI

---

docs/docs/integrations/libraries/dlt/using-dlt-with-dagster.md
examples/docs_snippets/docs_snippets/integrations/dlt/define_downstream_dependencies.py
examples/docs_snippets/docs_snippets_tests/test_integration_files_load.py

[docs] Add downstream deps guide for dlt

---

docs/docs/integrations/libraries/dlt/using-dlt-with-dagster.md
examples/docs_snippets/docs_snippets/integrations/dlt/customize_upstream_dependencies.py

Fix a copy paste error
Docs preview

[docs] Fix upstream deps guide for dlt

---

docs/docs/integrations/libraries/sling.md
examples/docs_snippets/docs_snippets/integrations/sling/customize_upstream_dependencies.py
examples/docs_snippets/docs_snippets_tests/test_integration_files_load.py

[docs] Add upstream deps guide for Sling

---

docs/docs/integrations/libraries/sling.md
examples/docs_snippets/docs_snippets/integrations/sling/define_downstream_dependencies.py
examples/docs_snippets/docs_snippets_tests/test_integration_files_load.py

[docs] Fix downstream deps guide for Sling

---

python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py

Merged a PR that passed ruff checks before the version upgrade
BK

fix ruff with updated version

---

docs/docs/integrations/libraries/fivetran.md
examples/docs_snippets/docs_snippets/integrations/fivetran/define_upstream_dependencies.py
examples/docs_snippets/docs_snippets_tests/test_integration_files_load.py

[docs] Add upstream deps guide for Fivetran

---

python_modules/dagster-test/dagster_test/toys/freshness.py
python_modules/dagster-test/dagster_test/toys/repo.py
python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py

Add a dedicated repository and a few assets with internal freshness policies to toys

add freshness policy assets and repository to toys

---

docs/docs/guides/labs/components/building-pipelines-with-components/adding-components.md

iirc, it's still `dg docs serve` (disclaimer: i couldnt get my local env on editable dg with my limited time, so plz correct me if my info outdated!)

[dg docs] dg docs serve

---

python_modules/automation/tox.ini
python_modules/libraries/dagster-cloud-cli/MANIFEST.in

[NO_SKIP] manifest update for dagster-cloud-cli

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetHealthSummary.tsx

Fix asset health summary text for missing partitions

---

js_modules/dagster-ui/packages/ui-core/src/assets/useAssetEventsFilters.tsx

as titled
👀 
[ui] Fixed a bug that prevented filtering asset events by type.

Fix type filter gating

---

python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/commands/config.py
python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/config_utils.py
python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/utils.py
python_modules/libraries/dagster-shared/setup.py

Updates `dagster-cloud-cli` to use login code from `dagster-shared`
Tested locally, e2e tests in https://github.com/dagster-io/internal/pull/14425

[dagster-cloud-cli] Use dagster-shared login code

---

python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_asset_decorator.py

[dagster-dbt] Fix asset names in dbt Cloud tests

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
python_modules/libraries/dagster-dg/tox.ini

Splits out dg tests into three suites, dg docs, plus cli, and everything else

[dg] split out docs, plus tests in bk

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetHealthSummary.tsx

Remove duplicate 'ago' from materialization timestamp copy in asset health summary

---

python_modules/dagster-graphql/dagster_graphql/implementation/utils.py

capture_error should be able to handle both async and sync functions

make capture error async agnostic

---

examples/docs_snippets/docs_snippets/guides/components/index/16-duckdb-select.txt

This snippet changed due to some update to sling or duckdb that changed a default. Fixes BK on master.

[dg] Fix duckdb table snippet

---

js_modules/dagster-ui/packages/ui-core/src/asset-selection/AntlrAssetSelectionVisitor.oss.ts
js_modules/dagster-ui/packages/ui-core/src/asset-selection/AssetSelectionSupplementaryDataVisitor.tsx

[Catalov2] Make status asset selection filtering case insensitive

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/sensor_builder.py

As title, previous doctring was outdated

[dagster-dbt] Update docstring for build_dbt_cloud_polling_sensor

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetCatalogAssetGraph.tsx

[CatalogV2] Allow right sidebar in catalog asset graph

---

js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetHealthDataProvider.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/AssetCatalogTablev2.test.tsx

Intended to enable this feature flag for the test but did it globally... oops
jest

Enable feature flag during test

---

CHANGES.md

changelog 1.10.11

---

examples/experimental/dagster-dlift/dagster_dlift/translator.py
examples/experimental/dagster-dlift/dagster_dlift_tests/test_translator.py
python_modules/dagster/dagster/_utils/names.py

To be used in subsequent PR.
BK

[utils] Rename clean_asset_name to clean_name

---

python_modules/libraries/dagster-dg/dagster_dg/cli/plus/constants.py
python_modules/libraries/dagster-dg/dagster_dg/cli/plus/deploy.py
python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
python_modules/libraries/dagster-dg/dagster_dg/utils/plus/build.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/plus_tests/test_plus_deploy_command.py

Test Plan:
BK, run dg plus deploy locally

Derive agent type to use for dg deploy from graphql

---

python_modules/libraries/dagster-dg/dagster_dg/cli/plus/deploy.py

Summary:
For example, in the github action, this file won't be set.

allow running dg deploy with no plus config file set

---

python_modules/libraries/dagster-dg/dagster_dg/templates/build-location-fragment.yaml

[dg scaffold] fix image registry templating

---

python_modules/libraries/dagster-dg/dagster_dg/templates/build-location-fragment.yaml

[dg scaffold] fix image registry templating II

---

python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/mcp_tests/test_mcp_serve.py

[mcp] fix unit tests

---

.buildkite/dagster-buildkite/dagster_buildkite/python_packages.py
python_modules/dagster/dagster/_cli/instance.py
python_modules/dagster/dagster/_cli/utils.py
python_modules/dagster/dagster/_core/workspace/load_target.py
python_modules/dagster/dagster/components/cli/__main__.py
python_modules/dagster/dagster_tests/general_tests/test_import.py

its not expensive on subsequent imports, but the initial import in a fresh env is costly which we do repeatedly in test suites
added test

defer tomli import

---

js_modules/dagster-ui/packages/dg-docs-components/src/ComponentHeader.tsx
js_modules/dagster-ui/packages/dg-docs-components/src/types.ts
python_modules/libraries/dagster-dg/dagster_dg/cli/docs.py
python_modules/libraries/dagster-dg/dagster_dg/context.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_docs_commands.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
python_modules/libraries/dagster-shared/dagster_shared/serdes/objects/package_entry.py
python_modules/libraries/dagster-shared/dagster_shared/yaml_utils/sample_yaml.py

not sure why we were filtering on this, maybe just accident
eyes

[component] include components without schema in docs

---

python_modules/libraries/dagster-dbt/dagster_dbt/cli/app.py

this is an optional dep so only import if `--components` flag is used 
bk

[dbt] defer dagster_dg import

---

python_modules/libraries/dagster-dg/dagster_dg/cli/plus/deploy_session.py
python_modules/libraries/dagster-dg/dagster_dg/templates/deploy_uv_Dockerfile.jinja
python_modules/libraries/dagster-dg/dagster_dg/templates/deploy_uv_editable_Dockerfile.jinja

Build this dockerfile before and after uv add dagster-cloud

Fail the dockerfile build if dagster-cloud is not included in the built image

---

python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py

[ez] clarify workspace build.yaml vs. project build.yaml

---

python_modules/libraries/dagster-dg/dagster_dg/templates/registry_fragments/ecr-login-fragment.yaml

Summary:
These appear to be drop-in replacements with no scary warnings when you use them.

bump scaffolded aws action versions

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py

Summary:
This is half to confirm my understanding, and half to hopefully help others confirm their understanding more quickly in the future. I didn't grasp that this is like an accumulator (maybe 'at_any_time_since' would make that clearer?)

clarify DA since() behavior in a comment

---

python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py

Use the same logic we use to determine the branch deploymnet repo name to determine the github web URL.
Test Plan: BK

Fix github web URI when an https url is passed in

---

python_modules/libraries/dagster-dg/dagster_dg/component.py
python_modules/libraries/dagster-dg/dagster_dg_tests/test_cache.py

Currently `dg` chokes with an inscrutable error when it reads from a cache in an outdated data format (causing deserialization errors). This PR changes the behavior so that deserialization errors are caught and treated the same as a missing cache entry (a message is printed saying the cache is outdated or invalidated).
Cache deserialization errors are now ignored. Previously, when the `dg` contents of the cache were in an outdated format, `dg` could crash. Now it will just rebuild the cache.

[dg] Rebuild cache on deserialization error (BUILD-997)

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/resources.py
python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/types.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/conftest.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_asset_decorator.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_reconstruction.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_specs.py

As title. Required for subsequent PR implementing the schedule builder.

[dagster-dbt] Add workspace jobs to dbt Cloud workspace data

---

python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/core/pex_builder/pex_registry.py

Summary:
These mutations are safe to retry on read timeouts, add the flag that allows them to do that.
Test Plan:
BK

Add 'idempotent_mutation=True' to PEX url generation mutations

---

python_modules/dagster/dagster/_core/storage/asset_check_execution_record.py

needed for https://github.com/dagster-io/internal/pull/15221

whitelist_for_serdes AssetCheckExecutionResolvedStatus

---

python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/commands/ci/__init__.py
python_modules/libraries/dagster-dbt/dagster_dbt/cli/app.py
python_modules/libraries/dagster-dbt/dagster_dbt/components/dbt_project/component.py

refactor fn out of #29221 to use in `manage-state` as well 
#29221 tests
[dagster-cloud-cli] the `dagster-cloud ci dagster-dbt project manage-state` cli now supports `--components` for handling `DbtProjectComponent`

[dbt component] manage_state cli support

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/resources.py
python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/resources.py

Same as #29446 but for Airbyte Cloud

[dagster-airbyte] Add memoization to AirbyteCloudWorkspace.fetch_airbyte_workspace_data

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/resources.py

Same as #29446 but for dbt Cloud v2

[dagster-dbt] Add memoization to DbtCloudWorkspace.fetch_workspace_data

---

python_modules/libraries/dagster-powerbi/dagster_powerbi/resource.py

Same as #29446 but for PowerBI

[dagster-powerbi] Add memoization to _fetch_powerbi_workspace_data

---

python_modules/libraries/dagster-tableau/dagster_tableau/resources.py

Same as #29446 bur for Tableau

[dagster-tableau] Add memoization to fetch_tableau_workspace_data

---

python_modules/libraries/dagster-looker/dagster_looker/api/resource.py

[dagster-looker] Add memoization to fetch_looker_instance_data

---

js_modules/dagster-ui/packages/ui-core/src/app/Util.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx
js_modules/dagster-ui/packages/ui-core/src/workers/Worker.oss.ts

`indexeddbAsyncMemoize` was swallowing errors/promise rejections being thrown by the async code it was caching. Now it properly surfaces them without "caching" the rejection.
Loaded the asset graph a bunch of times using a known state that would trigger the infinite loading.
[ui] Fixed an issue where the asset graph looked like it was still loading when it wasn't.

Propagate promise rejections in indexeddbAsyncMemoize to fix infinite loading state in asset graph

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx

Fix the selection syntax query here. I'm not sure what this powers tbh and haven't noticed any issues but this should have been using the new syntax.

Fix selection syntax query for non-lineage view

---

marketplace/scripts/generate.ts

[marketplace] remove logoPath entry

---

python_modules/dagster-graphql/dagster_graphql/schema/asset_health.py

fix instance method names. not sure how this didn't get caught in the original pr with NO_SKIP in the commit message

fix asset health test

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py

This was created before the hidden_param decorator was merged, update to use the new pattern
NOCHANGELOG

Use hidden_params in AutomationResult

---

scripts/install_dev_python_modules.py

add dagster-dg to dev install

---

python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/mcp_tests/test_mcp_serve.py

`mcp` isn't available for 3.9, so we skip the tests accordingly.

[NO_SKIP] Disable mcp tests on 3.9

---

python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/test_dbt_project_component.py

avoid the subprocess jump
[TEST_PYTHON_VERSIONS=test-all] to ensure passes on 3.9 and 3.10

[dbt] fix test_project_prepare_cli

---

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/definitions/declarative_automation/operands/operands.py

Due to a rebase mishap, this code got put in the wrong spot
NOCHANGELOG

[da] Fix build

---

python_modules/dagster/dagster/components/core/defs_module.py

The contextual `ComponentLoadContext` was introduced before we used the recursive component loading framework we now have set up. Unfortuantely, it doesn't accurately match the actual component being loaded (in terms of `ComponentLoadContext.current().path` being accurate, for example).
This PR ensures we update the contextual context each time we build defs or load a nested component.

[components] Ensure the contextual ComponentLoadContext matches the load dir

---

python_modules/dagster/dagster/components/__init__.py
python_modules/dagster/dagster/components/component/component.py
python_modules/dagster/dagster/components/component/component_loader.py
python_modules/dagster/dagster/components/core/context.py
python_modules/dagster/dagster/components/core/defs_module.py
python_modules/dagster/dagster/components/core/load_defs.py
python_modules/dagster/dagster/components/definitions.py
python_modules/dagster/dagster/components/lib/pipes_subprocess_script_collection.py
python_modules/dagster/dagster/components/resolved/base.py
python_modules/dagster/dagster/components/resolved/context.py
python_modules/dagster/dagster/components/resolved/core_models.py
python_modules/dagster/dagster/components/resolved/model.py
python_modules/dagster/dagster/components/scaffold/scaffold.py
python_modules/libraries/dagster-dg/dagster_dg_tests/utils_tests/test_sample_yaml.py

update `dagster.componenets` `__init__.py` and annotate everything with `@public` and `@preview` 
bk

[components] annotate public api

---

python_modules/libraries/dagster-dg/dagster_dg/cli/plus/constants.py
python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
python_modules/libraries/dagster-dg/dagster_dg/cli/utils.py
python_modules/libraries/dagster-dg/dagster_dg/config.py
python_modules/libraries/dagster-dg/dagster_dg/context.py
python_modules/libraries/dagster-dg/dagster_dg/utils/plus/build.py
python_modules/libraries/dagster-dg/dagster_dg/utils/plus/gql.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/plus_tests/test_plus_deploy_command.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/plus_tests/test_scaffold_plus_commands.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/plus_tests/utils.py

Similar to build.yaml, pre-scaffolded based on auto-detection of your agent type.
New test cases, actually deploy to serverless and hybrid as well

container_context.yaml support for dg plus deploy

---

python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/plus_tests/test_scaffold_plus_commands.py
python_modules/libraries/dagster-dg/tox.ini

Summary:
Clearly this was needed since it immediately caught several formatting errors!
BK

Add validation test for example scaffolded container_context.yaml in github actions

---

python_modules/libraries/dagster-ge/dagster_ge_tests/__snapshots__/test_validation.ambr

rebuild dagster-ge snapshots

---

examples/docs_snippets/docs_snippets/guides/components/index/21-component-jdbt.yaml
examples/docs_snippets/docs_snippets/guides/dg/migrating-definitions/1-tree.txt
examples/docs_snippets/docs_snippets/guides/dg/migrating-definitions/5-tree-after.txt
examples/docs_snippets/docs_snippets/guides/dg/migrating-definitions/6-tree-after-all.txt
python_modules/dagster/dagster/components/cli/scaffold.py
python_modules/dagster/dagster/components/component_scaffolding.py
python_modules/dagster/dagster/components/scaffold/scaffold.py
python_modules/libraries/dagster-dbt/dagster_dbt/components/dbt_project/scaffolder.py
python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py

get rid of weird relative pathing hack by using newly added `{{ project_root }}` template context

[dbt scaffold] use project_root scope

---

python_modules/libraries/dagster-snowflake-pandas/setup.py
python_modules/libraries/dagster-snowflake-pandas/tox.ini

Per workaround recommendation here to unbreak the
dagster-snowflake-pandas tests:
https://status.snowflake.com/incidents/txclg2cyzq32

Pin certifi in dagster-snowflake-pandas test

---

js_modules/dagster-ui/packages/ui-core/src/partitions/AssetJobPartitionsView.tsx

https://dagsterlabs.slack.com/archives/C03A0D72A6T/p1745604325823389

Add some memoization

---

js_modules/dagster-ui/packages/ui-components/jest.config.js
js_modules/dagster-ui/packages/ui-components/package.json
js_modules/dagster-ui/packages/ui-core/jest.config.js
js_modules/dagster-ui/packages/ui-core/package.json
js_modules/dagster-ui/yarn.lock

Followed instructions in https://www.npmjs.com/package/buildkite-test-collector and executed yarn add --dev buildkite-test-collector in both directories containing a jest.config.js file to update the associated package and yarn files.
Same test plan as https://github.com/dagster-io/internal/pull/15269

Add BuildKite test collector configuration

---

js_modules/dagster-ui/packages/ui-core/client.json
js_modules/dagster-ui/packages/ui-core/src/assets/__fixtures__/AssetTables.fixtures.ts
js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/AssetCatalogTablev2.test.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/AssetView.test.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/useAllAssets.test.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/types/useAllAssets.types.ts
js_modules/dagster-ui/packages/ui-core/src/assets/useAllAssets.tsx

rename this query to align with the resolver its using.

[ez] Rename query

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetCatalogTableV2.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogInsights.oss.tsx

Context in internal PR https://github.com/dagster-io/internal/pull/15297
Locally viewed
NOCHANGELOG

Pass asset keys to insights queries

---

python_modules/dagster/dagster/components/core/defs_module.py
python_modules/dagster/dagster_tests/components_tests/integration_tests/test_definitions_autoload.py

i believe this is what is causing weird `DefsFolderComponent` instances
existing tests

[components] ignore empty directories

---

js_modules/dagster-ui/packages/ui-core/src/integrations/MarketplaceHome.tsx

fix the qs marketplace build error

---

python_modules/dagster/dagster/_core/definitions/job_definition.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster/components/core/defs_module.py
python_modules/dagster/dagster/components/resolved/model.py
python_modules/libraries/dagster-airlift/dagster_airlift/core/components/airflow_instance/component.py
python_modules/libraries/dagster-airlift/dagster_airlift/core/load_defs.py
python_modules/libraries/dagster-airlift/dagster_airlift/core/serialization/serialized_data.py
python_modules/libraries/dagster-airlift/dagster_airlift/core/utils.py
python_modules/libraries/dagster-airlift/kitchen-sink/Makefile
python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/component_utils.py
python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/dagster_defs/inner_component_defs/airlift/component.yaml
python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/dagster_defs/inner_component_defs/airlift/dag_mapped/component.yaml
python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/dagster_defs/inner_component_defs/airlift/maps_downstream_print_task/component.yaml
python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/dagster_defs/inner_component_defs/airlift/maps_print_task/component.yaml
python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink/dagster_defs/inner_component_defs/airlift/task_mapped/component.yaml

Mapped assets components

---

python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
python_modules/dagster/dagster/_core/definitions/definitions_class.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/storage/legacy_storage.py
python_modules/dagster/dagster/_core/storage/runs/base.py
python_modules/dagster/dagster/_core/test_utils.py
python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
python_modules/libraries/dagster-airlift/dagster_airlift/core/components/airflow_instance/component.py
python_modules/libraries/dagster-airlift/dagster_airlift/core/monitoring_job/event_stream.py
python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_component_defs.py
python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_monitoring_job.py
python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink_tests/integration_tests/test_e2e_components.py

Apply the downstack storage changes to Airlift - specifically:
- Create correctly dated historical runs
- Create correctly dated events
- Altered existing tests to have additional assertions around timing.

[dagster-airlift] apply storage changes to airlift

---

examples/docs_snippets/docs_snippets/guides/external-systems/apis/use_configurable_resource_in_asset.py

Fix typo in use_configurable_resource_in_asset.py

---

.buildkite/dagster-buildkite/dagster_buildkite/utils.py

bump uv to 0.7.2

---

python_modules/libraries/dagster-k8s/dagster_k8s/component.py
python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_pipes.py

Adds a component that creates a pipes k8s multi asset using config to describe the k8s pod workload. 
added basic test
[components][dagster-k8s] PipesK8sComponent has been added

[components] PipesK8sComponent

---

js_modules/dagster-ui/packages/ui-core/src/assets/useRecentAssetEvents.tsx
python_modules/dagster-test/dagster_test/toys/big_honkin_asset_graph.py

This is causing an error in dogfood

Rm unused fragment

---

python_modules/libraries/dagster-tableau/dagster_tableau/translator.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/conftest.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_translator.py

As title, this will be used in subsequent PRs to select data sources that can be refreshed because they have extracts.
BK with updated test

[1/n][dagster-tableau] Add has_extracts to datasource spec metadata

---

python_modules/libraries/dagster-tableau/dagster_tableau/asset_utils.py
python_modules/libraries/dagster-tableau/dagster_tableau/resources.py
python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_reconstruction.py

Cleanup and moving things around to facilitate the implementation of refreshable Tableau assets in subsequent PR.

[3/n][dagster-tableau] Refactor client methods to refresh Tableau assets

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphAssetSelectionInput.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNodeMenu.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/Sidebar.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-selection/filterAssetSelectionByQuery.oss.ts
js_modules/dagster-ui/packages/ui-core/src/asset-selection/input/useAssetSelectionInput.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/globalAssetGraphPathToString.tsx
js_modules/dagster-ui/packages/ui-core/src/gantt/GanttChart.tsx
js_modules/dagster-ui/packages/ui-core/src/op-selection/AntlrOpSelection.ts
js_modules/dagster-ui/packages/ui-core/src/pipelines/GraphExplorer.tsx
js_modules/dagster-ui/packages/ui-core/src/run-selection/AntlrRunSelection.ts
js_modules/dagster-ui/packages/ui-core/src/runs/Run.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunActionButtons.tsx
js_modules/dagster-ui/packages/ui-core/src/search/links.tsx

Remove a bunch of selection syntax flag gating now that the flag is always on.
bk

Remove selection syntax flag gating

---

scripts/install_dev_python_modules.py

add dagster-cloud-cli to make dev script

---

python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_assets.py

Additional test for changes made in https://github.com/dagster-io/dagster/pull/29682
BK

[dagster-tableau] Add test for mutually exclusive refreshable IDs in asset builder

---

js_modules/dagster-ui/packages/ui-components/src/quarantine-test-utils/custom-jest-environment.ts
js_modules/dagster-ui/packages/ui-components/src/quarantine-test-utils/quarantined-tests.ts
js_modules/dagster-ui/packages/ui-core/src/quarantine-test-utils/custom-jest-environment.ts
js_modules/dagster-ui/packages/ui-core/src/quarantine-test-utils/quarantined-tests.ts

Covered in https://github.com/dagster-io/internal/pull/15467

Add Jest functionality to support skipping

---

python_modules/libraries/dagster-dbt/dagster_dbt/components/dbt_project/component.py
python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/test_dbt_project_component.py

resolves #29745
added test
[components][dagster-dbt] The `DbtProjectComponent` now has a `translation_settings` argument for adjusting `DagsterDbtTranslatorSettings`

[dbt component] expose translator settings

---

python_modules/dagster/dagster/components/core/defs_module.py

This pushd is problematic for a couple of reasons:
- If you have code that depends on this working directory being a certain value, it will not work (an example would be storing a relative path that you want to use later)
- It assumes that the folder actually exists on disk, which is not true for some of the change preview features we have been experimenting with.
This PR removes that pushd. We will need to document this and probably touch up the changelog entry a bit, maybe with a before/after example?
First seeing what 
Dagster components no longer change the working directory while they are being loaded. This allows components to store relative paths and ensure that they will still work when accessed outside of the component loading codepath. This change may affect user-defined …

Remove pushd from components load flow

---

.github/workflows/build-docs.yml

Make sure docs build when Dagster version updated.

Add dagster versions.py to docs build GHA

---

js_modules/dagster-ui/packages/ui-core/src/code-links/CodeLinkProtocol.tsx

Add cursor and windsurf URL formats to code link settings.
Tested locally w/ cursor, windsurf.

[ui] Add Cursor, Windsurf editor URL protocols to code link settings

---

examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/components/test_components_docs.py
python_modules/libraries/dagster-dbt/dagster_dbt/components/dbt_project/component.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/test_dbt_project_component.py

another resolution self own. I missed that the tutorial integration test was overwriting the scaffolded value before check defs.
added and updated tests

[dbt component] path resolution fix

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/tox.py

random guess at what is causing sporadic hash mismatches when installing this
bk

[bk] dont force-reinstall uv

---

python_modules/dagster/dagster/_core/loader.py
python_modules/dagster/dagster_tests/utils_tests/test_dataloader.py

Add the ability to narrow the specific `LoadingContext` type a `LoadableBy` can work with
updated test

[Loadable] add context type generic

---

CHANGES.md

changelog 1.10.14

---

python_modules/dagster/dagster/components/core/defs_module.py

Ignore glob patterns in crawl

---

js_modules/dagster-ui/packages/ui-core/src/workspace/types/VirtualizedJobRow.types.ts
python_modules/dagster-graphql/dagster_graphql/implementation/events.py

[gql] handle failed to materialize events in run logs

---

docs/docs/guides/migrate/airflow-to-dagster/dag-level-migration/index.md
docs/docs/guides/migrate/airflow-to-dagster/index.md

- Fix #29212 
- Local build and test
- Replace relative paths with full paths
- Fix broken link and typo

[docs] fix airflow migration docs

---

python_modules/libraries/dagster-gcp/dagster_gcp/dataproc/configs_dataproc_cluster.py
python_modules/libraries/dagster-gcp/dagster_gcp/dataproc/types_dataproc_cluster.py

This reverts commit ad8131daa78d40fb4dcbccd2b1e94eb05a590643.
Seems they changed it back...?
BK

Remove changes introduced to Spark Pythonic config

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
python_modules/dagster/dagster_tests/general_tests/utils_tests/utils.py
python_modules/dagster/dagster_tests/utils_tests/test_annotations.py
python_modules/dagster/dagster_tests/utils_tests/test_pydantic_yaml.py
python_modules/dagster/tox.ini

not sure when this got accidentally removed
bk

[dagster tests] add missing tox entry

---

python_modules/dagster/dagster_tests/component_tests/shim_components/shim_test_utils.py
python_modules/dagster/dagster_tests/component_tests/shim_components/test_asset.py
python_modules/dagster/dagster_tests/component_tests/shim_components/test_resources.py

This adds a test for the asset scaffolder and also extracts out the common functionality to a shared utility
BK
NOCHANGELOG

[dg] Add test for asset shim and extract common function

---

python_modules/dagster/setup.py
python_modules/libraries/dagster-dg/setup.py

To get to a healthy build. We'll triage out fixing the broken behavior and relaxing the pin before this week's release.

Pin click < 8.2

---

python_modules/libraries/dagster-cloud-cli/setup.py

On spot I missed in https://github.com/dagster-io/dagster/pull/29919

Pin click < 8.2 in dagster-cloud-cli

---

.buildkite/dagster-buildkite/dagster_buildkite/pipelines/dagster_oss_main.py

Same logic and testing as committed in internal
https://github.com/dagster-io/internal/pull/15497

Add skip and mute step logic to dagster_oss_main.py

---

python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/conftest.py

As title, unused fixture parameters in conftest.
BK

[dagster-fivetran] Clean unused fixtures in Fivetran tests

---

js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetHealthDataProvider.tsx
js_modules/dagster-ui/packages/ui-core/src/live-data-provider/Factory.tsx
js_modules/dagster-ui/packages/ui-core/src/live-data-provider/LiveDataThread.tsx
js_modules/dagster-ui/packages/ui-core/src/live-data-provider/LiveDataThreadManager.tsx

increase default batch size to 250 and number of parallel threads to 4.
checked network tab

[Asset Health] Increase default batch size

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/AssetSidebarNode.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/Sidebar.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetHealthSummary.tsx

[Observe] Use asset health status in asset graph sidebar

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/execution.py
python_modules/dagster-graphql/dagster_graphql/schema/inputs.py

[ui] Backend changes

---

python_modules/dagster/dagster_tests/declarative_automation_tests/perf_tests/test_perf.py

[da] bump perf limit

---

js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/useAllAssets.test.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/useAllAssets.tsx

Lower batch limit.
Also delete indexeddb data if its out of date.
app-proxy with dogfood-test-1

[AssetsRecordQuery] Lower batch limit

---

CHANGES.md

add 1.10.15 changelog

---

js_modules/dagster-ui/packages/ui-core/src/partitions/AssetJobPartitionsView.tsx

https://dagsterlabs.slack.com/archives/C08SM6N2RC2/p1747323574829359

Memoize the pipelineSelector on asset job partitions page

---

CHANGES.md

add dg windows fix to changelog

---

conftest.py

We were seeing some mutes non-deterministcally apply depending on whether or not they were returned in the first page.
This implements pagination against Buildkite's pagination spec:
https://buildkite.com/docs/apis/rest-api#pagination
Bail after 10 seconds to avoid accidental infinite loops if something ends up being malformed about how Buildkite is returning responses.

Paginate mute list

---

python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
python_modules/dagster/dagster_tests/general_tests/utils_tests/test_cached_method.py

[asset graph] bring back keys methods memoization

---

python_modules/dagster-test/dagster_test/definitions.py
python_modules/dagster-test/dg.toml
python_modules/dagster-test/setup.py

Revert "[dg] Make dagster-test a dg project (#30022)"

---

js_modules/dagster-ui/packages/ui-components/src/quarantine-test-utils/quarantined-tests.ts
js_modules/dagster-ui/packages/ui-core/src/quarantine-test-utils/quarantined-tests.ts

Edited and added to internal https://github.com/dagster-io/internal/pull/15781

Paginate quarantined tests

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_decorator.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_asset_specs.py

Same as #29976 but for the new Fivetran integration

[dagster-fivetran]  Raise custom exception on conflicting group_name in Fivetran asset decorator

---

python_modules/libraries/dagster-dlt/dagster_dlt/asset_decorator.py
python_modules/libraries/dagster-dlt/dagster_dlt_tests/test_asset_decorator.py

Same as #29976 but for the dlt integration

[dagster-dlt] Raise custom exception on conflicting group_name in dlt asset decorator

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
python_modules/libraries/dagster-airlift/dagster_airlift/core/components/airflow_instance/component.py
python_modules/libraries/dagster-airlift/dagster_airlift_tests/mwaa_integration_tests/airflow_project/requirements.txt
python_modules/libraries/dagster-airlift/dagster_airlift_tests/mwaa_integration_tests/airflow_project/simple_dag.py
python_modules/libraries/dagster-airlift/dagster_airlift_tests/mwaa_integration_tests/dagster_defs/defs.py
python_modules/libraries/dagster-airlift/dagster_airlift_tests/mwaa_integration_tests/dagster_defs/inner/component.yaml
python_modules/libraries/dagster-airlift/dagster_airlift_tests/mwaa_integration_tests/test_mwaa_backend.py
python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_component_defs.py
python_modules/libraries/dagster-airlift/tox.ini

Adds a mwaa backend to the airflow instance component
Added new integration test for connecting to live running mwaa instance. I need to make the upload flow less shoddy, working on that.

Mwaa backend component

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/asset_decorator.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_asset_decorator.py

Same as #29976 but for the new dbt Cloud integration

[dagster-dbt] Raise custom exception on conflicting group_name in dbt Cloud asset decorator

---

python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

event log storage test that `FAILED_TO_MATERIALIZE` events get deleted on `asset_wipe` for https://github.com/dagster-io/internal/pull/15756
unit test

test for deleting asset failures on wipe

---

python_modules/libraries/dagster-dg/dagster_dg/cli/check.py
python_modules/libraries/dagster-dg/dagster_dg/cli/dev.py
python_modules/libraries/dagster-dg/dagster_dg/cli/list.py
python_modules/libraries/dagster-dg/dagster_dg/cli/plus/__init__.py
python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
python_modules/libraries/dagster-dg/dagster_dg/cli/utils.py
python_modules/libraries/dagster-dg/dagster_dg/component.py
python_modules/libraries/dagster-dg/dagster_dg/config.py
python_modules/libraries/dagster-dg/dagster_dg/context.py
python_modules/libraries/dagster-dg/dagster_dg/env.py
python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/import_perf_tests/test_import_perf.py
python_modules/libraries/dagster-shared/dagster_shared/libraries/__init__.py
python_modules/libraries/dagster-shared/dagster_shared/serdes/objects/package_entry.py
python_modules/libraries/dagster-shared/dagster_shared/serdes/serdes.py
python_modules/libraries/dagster-shared/dagster_shared/telemetry/__init__.py
python_modules/libraries/dagster-shared/dagster_shared/utils/config.py

Summary:
still some more juice to squeeze from the rock here. Gets importing the launch CLI down to ~0.125 seconds.

dg import speedups part 2

---

python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/import_perf_tests/simple_import.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/import_perf_tests/test_import_perf.py
python_modules/libraries/dagster-shared/dagster_shared/serdes/serdes.py

Plus make the test a little more realistic and invoke an actual (no op) cli command
BK

dg import speedup part 3 - pydantic removal

---

python_modules/dagster/dagster/_cli/project.py
python_modules/dagster/dagster/_generate/download.py
python_modules/dagster/dagster/_generate/generate.py
python_modules/dagster/dagster/components/resolved/context.py
python_modules/dagster/dagster_tests/general_tests/test_import.py

Summary:
Easy 60ms off CLI import time.
BK

defer requests and jinja2 in cli import

---

python_modules/libraries/dagster-dg/dagster_dg/config.py
python_modules/libraries/dagster-dg/dagster_dg/context.py
python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/import_perf_tests/test_import_perf.py
python_modules/libraries/dagster-shared/dagster_shared/utils/config.py

Summary:
The juice squeeze continues.
Test Plan:
BK

dg import part 4 - tomlkit

---

python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py
python_modules/libraries/dagster-dg/dagster_dg/cli/check.py
python_modules/libraries/dagster-dg/dagster_dg/context.py
python_modules/libraries/dagster-dg/dagster_dg/env.py
python_modules/libraries/dagster-dg/dagster_dg/utils/filesystem.py
python_modules/libraries/dagster-dg/dagster_dg/utils/paths.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/import_perf_tests/test_import_perf.py

Summary:
I think this is the last one for now.

dg import part 5 - watchdog/dotenv

---

python_modules/dagster/dagster/_core/remote_representation/origin.py
python_modules/dagster/dagster/_core/types/loadable_target_origin.py
python_modules/libraries/dagster-shared/dagster_shared/record/__init__.py

these two are nearly the same, consolidate down to one 
bk

[record] consolidate NamedTuple compat classes

---

python_modules/dagster/dagster/_core/code_pointer.py

[record] code_pointer.py

---

python_modules/dagster/dagster/_core/definitions/module_loaders/object_list.py
python_modules/dagster/dagster_tests/definitions_tests/module_loader_tests/test_module_loaders.py

an issue a user hit migrating from `Definitions` to component autoloading 
added test
[bugfix] functions that load all definitiosn from modules like `load_definitions_from_modules` now handle duplicate `AssetSpec`s

[load_defs_from_module] allow multiple AssetSpecs that are equal

---

CHANGES.md

1.10.16 Changelog

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py

[bk] turn off dg/components docs snapshot tests

---

python_modules/dagster/dagster/components/resolved/base.py
python_modules/dagster/dagster_tests/components_tests/resolution_tests/test_resolved.py

added this trying to repro something so keep it around
added a test

[resolved] add scope to resolve_from_yaml

---

python_modules/dagster/dagster/_config/pythonic_config/resource.py
python_modules/dagster/dagster/_core/remote_representation/external_data.py
python_modules/dagster/dagster/components/cli/list.py
python_modules/libraries/dagster-dg/dagster_dg/cli/list.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py
python_modules/libraries/dagster-shared/dagster_shared/serdes/objects/definition_metadata.py

Adds resources to the list of objects shown via `dg list defs`:
```sh
dg list defs
┌───────────┬──────────────────────────────────────────────────────────────┐
┃ Section   ┃ Definitions                                                  ┃
┡━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ Assets    │ ┏━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━┳━━━━━━━┳━━━━━━━━━━━━━┓        │
│           │ ┃ Key        ┃ Group   ┃ Deps ┃ Kinds ┃ Description ┃        │
│           │ ┡━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━╇━━━━━━━╇━━━━━━━━━━━━━┩        │
│           │ │ my_asset_1 │ default │      │       │             │        │
│           │ ├────────────┼─────────┼──────┼───────┼─────────────┤        │
│           │ │ my_asset_2 │ default │      │       │             │        │
│           │ …
```

[dg] Add resources to dg list defs output

---

python_modules/libraries/dagster-pyspark/setup.py

Missed dagster-pyspark somehow (🙄🙄🙄) somehow in https://github.com/dagster-io/dagster/pull/30207
BK

Pin `dagster-pyspark` to <4

---

python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py

Add `dg scaffold defs inline-component` command. It takes the typename as an argument and an optional superclass option. It produces this:
```
$ dg scaffold defs inline-components some/component --typename SomeComponent
```
```
type: SomeComponent
attributes: {}
```
```
class SomeComponent(dg.Component, dg.Model, dg.Resolvable):
def build_defs(self, context: dg.ComponentLoadContext) -> dg.Definitions:
return dg.Definitions()
```
`dg scaffold defs inline-component` can now be used to create inline components and corresponding instances.

[dg] [ontology] dg scaffold inline-component (BUILD-1201)

---

python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py

Add substring matching for `dg scaffold defs` subcommands.
For one match it looks like this:
```
No exact match found for 'DefsFolder'. Did you mean this one?
dagster.components.DefsFolderComponent
Choose (y/n) [y]: 
Using defs scaffolder: dagster.components.DefsFolderComponent
Creating a component at /Users/smackesey/stm/code/elementl/tmp/myp/src/myp/defs/bar.
```
For multiple matches it looks like this:
```
$ dg scaffold defs Def qux
No exact match found for 'Def'. Did you mean one of these?
(1) dagster.components.DefinitionsComponent
(2) dagster.components.DefsFolderComponent
(n) quit
Select an option (number) [1]: 1
Using defs scaffolder: dagster.components.DefinitionsComponent
Creating a component at /Users/smackesey/stm/code/elementl/tmp/myp/src/myp/defs/qux.
```
Upstack I add an …

[dg] [ontology] Substring matching for `dg scaffold defs` subcommands (BUILD-1200)

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/components/workspace_component/component.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/components/workspace_component/scaffolder.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_component.py

Simple scaffolder which takes creds for the Fivetran component.
Unit test.

[dagster-fivetran][components] Introduce a scaffolder for the fivetran workspace component

---

js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogMetricUtils.tsx

Used in https://github.com/dagster-io/internal/pull/15907

Define freshness pass rate metric key

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py

Skip mcp dg test on python 3.9

---

python_modules/libraries/create-dagster/setup.py
python_modules/libraries/create-dagster/tox.ini
python_modules/libraries/dagster-dg-core/dagster_dg_core/context.py
python_modules/libraries/dagster-dg-core/dagster_dg_core_tests/utils.py

Immediately followup will be to add a test that prevents this.
Adjusted test suite so the dep was failing before

fix dagster_dg_core => dagster dep that was introduced at the last minute

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/asset_defs.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/resources.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/beta/test_asset_specs.py

Mirrors the behavior of the connection filter in the Fivetran integration, allows a user to subset the set of Airbyte connections that they pull from the Airbyte Cloud API.

[dagster-airbyte] Add connection_filter_fn to Airbyte Cloud load method

---

examples/docs_snippets/docs_snippets/deploying/asset_job_retries.py

Fix example formatting

---

js_modules/dagster-ui/packages/ui-core/src/app/time/ThemeSelect.tsx

Fix an import that breaks Cloud storybook.
internal `yarn storybook`

[ui] Fix import in ThemeSelect

---

python_modules/dagster/dagster_tests/components_tests/template_vars_tests/test_basic_template_vars.py

A bad rebase #30243 broke master. This fixes it.
BK
NOCHANGELOG

Remove incorrect import

---

python_modules/libraries/create-dagster/create_dagster/templates/PROJECT_NAME_PLACEHOLDER/.gitignore.jinja
python_modules/libraries/create-dagster/create_dagster_tests/test_scaffold_commands.py

Without lib we don't need this anymore
BK

[dg] remove .gitignore from project scaffold

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_misc.py
python_modules/dagster-graphql/dagster_graphql_tests/test_cli_repo.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_job.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/test_dbt_project_component.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/test_templated_custom_keys_dbt_project.py

pytest 8.4 fixes

---

python_modules/dagster/dagster/components/lib/executable_component/component.py
python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_executable_component_in_memory.py

Committing the basic skeleton of the `ExecutableComponent`, which we have used a bit in our internal repo.
We anticipate this becoming a frequently used primitive in the component system. It can eventually serve as a drop-in replacement for `@asset`, `@multi_asset`, `@asset_check`, `@multi_asset_check`. Assuming we land https://github.com/dagster-io/dagster/pull/30070 or something like it `@observable_source_asset` and `@multi_observable_source` asset will also be brought into the fold.
One nice property this has is the clean separation of metadata and compute. 
The user specifies asset specs, asset check specs, and other metadata, and then writes a POPF (Plain 'Ole Python Function) do perform the execution against those specs.
In this way, we can effectively bury the concept of the op, …

Initial Commit of `ExecutableComponent`

---

examples/docs_snippets/docs_snippets/guides/dg/workspace/1-dg-scaffold-workspace.txt
examples/docs_snippets/docs_snippets/guides/dg/workspace/4-dg.toml
examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/dg/test_dg_docs_workspace.py

fix docs snippets tests for workspace

---

python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_executable_component_in_memory.py

Ask and ye shall receive. Add a basic test for resource handling in `ExecutableComponent`
BK

Add unit test for resource usage in ExecutableComponent

---

python_modules/dagster/dagster/components/lib/executable_component/component.py
python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_asset_check_only.py

Adds support for asset checks in ExecutableComponent, as long as there as assets.
BK

Support asset checks in ExecutableComponent when there are assets

---

python_modules/dagster/dagster/components/lib/executable_component/component.py
python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_asset_check_only.py

Adding support for resources on checks in the `ExecutableComponent`
BK

Support resources in asset check only executable component

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py

attempt to fix buildkite on dagster-dg-cli on release branches

---

python_modules/dagster/dagster/_core/definitions/decorators/asset_check_decorator.py
python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_check_decorator.py
python_modules/dagster/dagster_tests/execution_tests/engine_tests/test_op_concurrency.py

added test
* [dagster] `multi_asset_check` now supports the `pool` argument

add pool to multi_asset_check

---

python_modules/libraries/create-dagster/create_dagster/cli/scaffold.py
python_modules/libraries/create-dagster/create_dagster/scaffold.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/check.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/dev.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/plus/__init__.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/scaffold.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/utils.py
python_modules/libraries/dagster-dg-core/dagster_dg_core/context.py
python_modules/libraries/dagster-dg-core/dagster_dg_core_tests/test_context.py

Clarifies that this is distinct from running the command at the workspace root - i previously thought is_project and is_workspace were mutually exclusive.
BK

Rename DgContext.is_workspace to is_in_workspace

---

python_modules/dagster/dagster_tests/components_tests/template_vars_tests/test_basic_template_vars.py

Summary:
Known problem, skipping for now to keep build green.
BK

skip components test on python 3.9

---

python_modules/dagster/dagster/components/lib/executable_component/component.py
python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_asset_check_only.py
python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_executable_component_in_memory.py

With #30434 in play, I have higher conviction that this is the right name. Taking it out of RFC status.
BK

ExecutionSpec

---

CHANGES.md

[changelog] 1.10.19

---

python_modules/dagster/dagster/components/lib/executable_component/subprocess_component.py
python_modules/dagster/dagster/components/lib/executable_component/uv_run_component.py
python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_pipes_subprocess.py
python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_uv_run_component.py

This adds a component very similar to SubprocessComponent (soon to be PythonScriptComponent) that runs a script standalone with `uv run` with embedded script dependencies.
BK

Add UvRunComponent

---

python_modules/libraries/dagster-dg-core/setup.py

0.13.3 has a breaking bug, skip this version.

Skip bad tomlkit version

---

python_modules/dagster/dagster/_core/definitions/unresolved_asset_job_definition.py

[record] UnresolvedAssetJobDefinition

---

python_modules/dagster/dagster/_core/definitions/job_definition.py
python_modules/dagster/dagster_tests/definitions_tests/test_job.py

add JobDefinition.with_metadata

---

python_modules/dagster/dagster/_core/definitions/unresolved_asset_job_definition.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_unresolved_asset_job.py

UnresolvedAssetJobDefinition.with_metadata

---

python_modules/dagster/dagster/_core/definitions/sensor_definition.py

[record] SensorExecutionData

---

python_modules/dagster/dagster/_core/definitions/asset_spec.py

Unless there was some intentional reason this was omitted it just seems like an oversight.
Eyes

Add automation_condition to AssetSpec

---

python_modules/dagster/dagster/components/testing.py

Refactoring out logic to load a component and its definition from path for upstack use. No behavior changes.
BK

Extract get_all_components_defs_from_defs_path

---

python_modules/dagster/dagster/_core/definitions/asset_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/decorators/sensor_decorator.py
python_modules/dagster/dagster/_core/definitions/multi_asset_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
python_modules/dagster/dagster/_core/definitions/sensor_definition.py
python_modules/dagster/dagster_tests/definitions_tests/test_sensor.py
python_modules/libraries/dagster-shared/dagster_shared/check/functions.py
python_modules/libraries/dagster-shared/dagster_shared_tests/test_check.py

same as schedules, pipe jobs through shared `with_attributes`
added test

SensorDefinition.with_attributes

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/utils.py

[dagster-fivetran] Clean connector name in asset factory

---

python_modules/libraries/dagster-dg-cli/setup.py

Summary:
For reasons that are not clear to me this seems to be causing ruff failures on the release branch in the current format - make it match the other way we handle pins elsewhere.

Fix up dagster-dg-cli setup.py

---

python_modules/dagster/dagster/_core/definitions/asset_check_spec.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py

enable updating asset and and asset check metadata on an `AssetsDefinition`
added test

add metadata_by_key to AssetsDefinition.with_attributes

---

js_modules/dagster-ui/packages/app-oss/next-env.d.ts
js_modules/dagster-ui/packages/app-oss/package.json
js_modules/dagster-ui/yarn.lock

Upgrade app-oss from Next 14 to 15, for https://github.com/dagster-io/dagster/security/dependabot/820.
There doesn't appear to be anything concerning in https://nextjs.org/docs/app/guides/upgrading/version-15 for our use case, and I have found that the upgrade to React 19 is not actually required at this point.
We have a fair amount of work to do to get ourselves onto React 19, given our dependencies, so we shouldn't be blocked on that upgrade.
Load the app in JS dev, click around and verify that everything seems to be working normally.
Run a full static build, verify same.

[ui] Upgrade to Next 15

---

js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogInsightsLineChart.tsx

Make a couple of style changes to the insights charts.
- Use compact number formatting on y axis
- Fix font color and use monospace on y axis
- Make tooltip styles a little more compact
Before
After
View home charts, verify that they behave and render correctly.

[ui] Style tweaks to new insights charts

---

python_modules/dagster-webserver/dagster_webserver_tests/test_app.py

test_app.py checks for the title tag in the built output of the app, and this has been slightly modified by the Next upgrade. Update the test.
pytest

[ui] Fix test_app.py

---

python_modules/dagster/dagster/_core/execution/plan/compute_generator.py
python_modules/dagster/dagster/components/lib/executable_component/component.py
python_modules/dagster/dagster/components/lib/executable_component/function_component.py
python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_executable_component_in_memory.py

This is just a pretty clear missing feature. FunctionComponent now accepts config arguments just like their underlying decorators.
BK

Support config in FunctionComponent

---

python_modules/dagster/dagster/components/testing.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/test_dbt_project_component.py
python_modules/libraries/dagster-sling/dagster_sling_tests/test_sling_replication_collection_component.py

Patterns off of #30622 which lets components ensure they support all op customization options.

[refactor][tests] Unify op customization testing into util

---

python_modules/dagster/dagster/components/testing.py

This was causing issues on 3.9

rm static call

---

python_modules/libraries/dagster-sling/setup.py

Released this morning - pinning until we introduce a fix for the breaking changes.

Pin sling<1.4.10

---

python_modules/dagster/dagster/_daemon/backfill.py

Summary:
Follow-on to https://github.com/dagster-io/dagster/commit/c558554129ec4b402c3f13fff520af05e0a70f83. I think that change largely addresses the problem, but even better is to wait to refetch the backfill object until you are certain that the future that is potentially modifying it has finished running.
Launch multiple backfills simultaneously locally with the threadpool on and the thread

Another tweak to the logic for the backfill daemon when using the threadpool

---

js_modules/dagster-ui/packages/ui-core/src/selection/SelectionAutoCompleteProvider.tsx
js_modules/dagster-ui/packages/ui-core/src/selection/__tests__/SelectionAutoComplete.test.ts

As titled
jest + manual testing

Treat * as wildcard in auto-complete results for key attribute

---

python_modules/libraries/dagster-tableau/dagster_tableau/assets.py
python_modules/libraries/dagster-tableau/dagster_tableau/resources.py

[dagster-tableau] Mark old asset factory and methods pattern as superseded

---

python_modules/libraries/dagster-tableau/dagster_tableau/resources.py

[dagster-tableau] Remove deprecated build_defs method

---

examples/docs_snippets/docs_snippets/integrations/tableau/customize-tableau-asset-defs.py
examples/docs_snippets/docs_snippets/integrations/tableau/customize_upstream_dependencies.py

[docs] Simply tableau examples to use only top-level api

---

python_modules/libraries/dagster-dbt/dagster_dbt/include/pyproject.toml.jinja
python_modules/libraries/dagster-dbt/dagster_dbt/include/setup.py.jinja

Fix Incident 165 https://app.incident.io/dagsterlabs/incidents/165

[dagster-dbt] Pin dbt-core in dbt NUX scaffold

---

js_modules/dagster-ui/packages/dg-docs-site/.next/trace

[dg docs site] rm .next/trace

---

CHANGES.md

CHANGELOG 1.10.21

---

python_modules/dagster/dagster/components/resolved/base.py
python_modules/dagster/dagster_tests/components_tests/resolution_tests/test_resolved.py

added test
`Resolved` subclasses now support `Enum` fields

[resolved] handle Enum

---

python_modules/dagster/dagster/components/component/component.py

[ADOPT-1600] fix Components docstring

---

examples/docs_snippets/docs_snippets/guides/components/index/17-dg-list-components.txt
examples/docs_snippets/docs_snippets/guides/components/index/26-dg-list-components.txt
examples/docs_snippets/docs_snippets/guides/components/index/4-dg-list-components.txt
examples/docs_snippets/docs_snippets/guides/components/index/6-dg-list-components.txt
examples/docs_snippets/docs_snippets/guides/components/integrations/dlt-component/4-tree.txt
examples/docs_snippets/docs_snippets/guides/components/shell-script-component/3-dg-list-components.txt
examples/docs_snippets/docs_snippets/guides/dg/migrating-definitions/1-tree.txt
examples/docs_snippets/docs_snippets/guides/dg/migrating-definitions/5-tree-after.txt
examples/docs_snippets/docs_snippets/guides/dg/migrating-definitions/6-tree-after-all.txt
examples/docs_snippets/docs_snippets/guides/dg/migrating-project/11-list-components.txt
examples/docs_snippets/docs_snippets/guides/dg/using-env/4-dg-list-components.txt
python_modules/dagster/dagster/__init__.py
python_modules/dagster/dagster/components/lib/executable_component/function_component.py
python_modules/dagster/dagster/components/lib/executable_component/python_script_component.py
python_modules/dagster/dagster/components/lib/executable_component/uv_run_component.py
python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_pipes_subprocess.py
python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_uv_run_component.py
python_modules/dagster/dagster_tests/components_tests/registry_tests/test_registry.py
python_modules/dagster/dagster_tests/components_tests/testing_tests/test_defs_sandbox.py

Allows these to show up in `dg list defs` et.al, also easier to type
NOCHANGELOG

[components] Export FunctionComponent and friends from the top level

---

js_modules/dagster-ui/yarn.lock

Update `pbkdf2` based on Dependabot alert.
`yarn why pbkdf2`, verify that only 3.1.3 is installed.

[ui] Fix dependabot alert

---

js_modules/dagster-ui/packages/ui-core/src/selection/SelectionAutoCompleteProvider.tsx
js_modules/dagster-ui/packages/ui-core/src/selection/__tests__/SelectionAutoComplete.test.ts

Fix an error when using a wildcard string eg: `"*"`. 
jest

Fix wildcard error in selection syntax

---

python_modules/dagster/dagster/_core/instance/config.py
python_modules/dagster/dagster/_core/instance/ref.py
python_modules/dagster/dagster/_daemon/controller.py
python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py

Forgot to add this in
NOCHANGELOG

[freshness] Add daemon config

---

python_modules/dagster/dagster/components/resolved/base.py

[components][ADOPT-1605] Resolvable

---

python_modules/dagster/dagster/__init__.py
python_modules/dagster/dagster/components/__init__.py
python_modules/dagster/dagster/components/resolved/core_models.py

[components][ADOPT-1607] AssetPostProcessorModel

---

python_modules/dagster/dagster/components/resolved/model.py

[components][ADOPT-1608] Model

---

python_modules/dagster/dagster/components/scaffold/scaffold.py

Remove preview, update docblocks.

[ADOPT-1612] Remove @preview from Scaffolder

---

python_modules/dagster/dagster/components/resolved/model.py

Add resolver docblock, rm preview

[ADOPT-1609] Add docblock, remove preview from Resolver

---

python_modules/dagster/dagster_tests/asset_defs_tests/test_freshness_policy.py

Make sure legacy_freshness_policy is non-null

---

python_modules/dagster/dagster/__init__.py

top level template_var export

---

examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/components/test_components_docs_creating_a_component.py
examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/components/test_customizing_existing_component.py
examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/dg/test_adding_components_to_existing_project/test_components_existing_project.py
examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/dg/test_dagster_definitions.py
examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/dg/test_migrating_definitions/test_migrating_definitions.py
examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/dg/test_migrating_project/test_migrating_project.py
examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/labs/airlift_v2/test_setup.py

[snippet tests] skip expensive operations (dg launch) when updating snippets

---

examples/docs_snippets/docs_snippets_tests/snippet_checks/README.md
examples/docs_snippets/docs_snippets_tests/snippet_checks/utils.py

narrowly scope tox command suggested to user to the file which failed

[docs snippet tests] in err message, tell user to invoke tox with specific test

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/asset_decorator.py
python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/cli_invocation.py
python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/client.py
python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/resources.py
python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/run_handler.py
python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/sensor_builder.py
python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/types.py

[dagster-dbt] Mark dbt Cloud v2 as beta

---

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/mcp/server.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/mcp_tests/test_mcp_serve.py

remove no longer required uv layer of interaction 

[dg mcp] remove uv run

---

MIGRATION.md

not sure why this started failing since the file hasn't been altered

prettier MIGRATION.md

---

python_modules/dagster/dagster_tests/components_tests/registry_tests/test_registry.py

[fix] fix registry test by forcing sling to import [NOSKIP=true]

---

.gitignore

Summary:
Better safe than sorry

Add .env~ to gitignore

---

python_modules/dagster/dagster/components/component/component_loader.py

rm preview from component_instance decorator

---

.buildkite/dagster-buildkite/dagster_buildkite/utils.py

bump uv pin

---

python_modules/dagster/dagster/_utils/caching_instance_queryer.py

This validation keeps issues from happening when you change the partition definiton  of an asset. This codepath is somewhat deprecated at some point but the validation issues can still come up in legacy codepaths.
BK, DA dry run of an asset that was failing before

Add partition key validation to get_asset_partitions_updated_after_cursor

---

js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/WorkspaceContext.tsx

dont override recoilroot

---

python_modules/automation/tox.ini

[fix] fix telemetry automation test, add new snowflake polars lib

---

python_modules/dagster/dagster/_core/op_concurrency_limits_counter.py
python_modules/dagster/dagster/_daemon/run_coordinator/queued_run_coordinator_daemon.py

Summary:
If you have, say, 5000 runs, fetch this once every 5 seconds instead of 50 times every 5 seconds.
I think we could probably fetch this even less frequently (like once per minute instead of on every dequeuer iteration?) but this is an easy start.
Existing dequeuer tests, set batch size to 1 locally and verify that pools are still working as expected
Performance improvements for run dequeuing when there are many queued runs using pools.

Fetch concurrency info once per dequeuer daemon iteration instead of once per batch of 100 runs

---

examples/docs_snippets/docs_snippets/concepts/declarative_automation/eager/data_version_changed_condition.py

the previous example was subtly incorrect
NOCHANGELOG

[da] Update docs snippet

---

CHANGES.md

1.11.1 changelog

---

js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetSelectionSummaryTile.module.css
js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetSelectionSummaryTile.tsx

Minor style tweaks to the saved selection tiles

Clean up saved selection tile styles

---

js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphSupplementaryData.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-selection/AssetSelectionSupplementaryDataVisitor.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-selection/parseAssetSelectionQuery.ts

If it's a RecognitionException then it's just a basic syntax error and lets ignore it. If it's something else then lets log it.

Mute asset selection error

---

examples/docs_snippets/docs_snippets_tests/test_integration_files_load.py

Fixes failing BK build https://buildkite.com/dagster/dagster-dagster/builds/127913#0197e727-8453-4738-acd0-c2ef61a5a4d6

[docs] Exclude dbt cloud code snippets from tests

---

js_modules/dagster-ui/packages/ui-core/src/app/FeatureFlags.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/app/useVisibleFeatureFlagRows.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/runs/RunActionButtons.tsx

Forgot to remove this feature flag -- this should be turned on for everyone now.
NOCHANGELOG

Enable flagAssetRetries globally

---

js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetCatalogTableV2.tsx

[Telemetry] Don't block page load if there are 0 assets in the workspace.

---

examples/docs_snippets/docs_snippets/guides/components/index/1-help.txt
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/__init__.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/ai.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_ai_command.py

A starting point for accelerating AI driven development of Dagster projects, help kick off productive CLI agent sessions with an opening prompt. 
Added tests, ran `dg ai` in DOP

[dg] add ai subcommand

---

python_modules/dagster/dagster/_cli/workspace/cli_target.py

The impl of `_get_code_pointer_dict_from_python_pointer_opts` needs to determine the repository name in order to produce its return dict - to do so it needs to fully initialize a repository.
This results in several very silly cases where we initialize a repository just to reinitialize it a few lines later!
https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_cli/job.py#L464-L469
Now that most entrypoints use `Definitions` or `LazyDefinitions`, repo names are typically just the singleton, so short-circuit in these cases.

Do not initialize repo unnecessarily in _get_code_pointer_dict_from_python_pointer_opts impl

---

Makefile
python_modules/dagster/dagster/components/list/list.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/__snapshots__/test_list_commands.ambr
python_modules/libraries/dagster-shared/dagster_shared/serdes/objects/definition_metadata.py

[dg list] add asset owners

---

python_modules/libraries/dagster-dbt/dagster_dbt/components/dbt_project/component.py

[dbt component] add desc and examples

---

python_modules/dagster-graphql/dagster_graphql/implementation/execution/__init__.py
python_modules/dagster-graphql/dagster_graphql/schema/backfill.py
python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/definitions/assets/graph/base_asset_graph.py
python_modules/dagster/dagster/_core/definitions/automation_tick_evaluation_context.py
python_modules/dagster/dagster/_core/definitions/partitions/definition/multi.py
python_modules/dagster/dagster/_core/definitions/partitions/definition/partitions_definition.py
python_modules/dagster/dagster/_core/definitions/partitions/definition/time_window.py
python_modules/dagster/dagster/_core/definitions/partitions/subset/partitions_subset.py
python_modules/dagster/dagster/_core/execution/asset_backfill.py
python_modules/dagster/dagster/_core/execution/context/input.py
python_modules/dagster/dagster/_core/execution/context/invocation.py
python_modules/dagster/dagster/_core/execution/context/op_execution_context.py
python_modules/dagster/dagster/_core/execution/context/output.py
python_modules/dagster/dagster/_core/execution/context/system.py
python_modules/dagster/dagster/_core/execution/job_backfill.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster_tests/execution_tests/misc_execution_tests/test_asset_backfill.py

Similar as the previous PR, but for partition key range related methods
NOCHANGELOG

[partition-context] partition key range methods

---

js_modules/dagster-ui/packages/ui-core/src/live-data-provider/util.ts

Allow URL parameter to override batch size / threads for asset health tuning

---

python_modules/dagster/dagster/components/core/tree.py

fix rename

---

python_modules/dagster/dagster/_core/definitions/sensor_definition.py
python_modules/dagster/dagster_tests/definitions_tests/test_sensor.py

surfaced via kitchen sink integration test, we were not handling all permutations of targeting 
updated test

[sensor] with_attributes fix

---

python_modules/dagster/dagster_tests/declarative_automation_tests/legacy_tests/scenarios/asset_graphs.py
python_modules/dagster/dagster_tests/execution_tests/misc_execution_tests/test_asset_backfill.py

Test that fails if child subsets are incorrectly materialized alongside parent subsets

---

.claude/coding_conventions.md
CLAUDE.md

Added naming conventions for `@record` methods and emphasized the importance of running `make ruff` after code changes. The PR establishes a clear pattern for immutable record methods by recommending the `with_*` naming convention to indicate that methods return new instances rather than mutating the original object.
Note: I continue to have to make ruff commands be more aggressive. It stopped doing it after one round of context compaction.
Note: I also asked claudes if emojis are good sigils for context and it replied:
```
⏺ Looking at the .claude/coding_conventions.md file, I see emojis are used specifically as semantic markers:
- ✅ for good examples (lines 36-38)
- ❌ for bad examples (lines 39-40)
My assessment:
Helpful for Claude: Yes, these emojis are actually beneficial. They serve …
```

Update coding conventions and project documentation

---

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/utils.py

* remove uv invocation
* handle the auto-updating claud code configuration which recommends aliases
`dg utils configure-mcp claude-code` locally

[dg mcp] update configure command

---

CHANGES.md

1.11.3 changelog

---

python_modules/dagster/dagster/_core/execution/asset_backfill.py
python_modules/dagster/dagster_tests/execution_tests/misc_execution_tests/test_asset_backfill.py

Ensure that all candidate partitions are being considered again after a parent updates

---

integration_tests/test_suites/k8s-test-suite/tests/test_executor.py

failing sometimes, see if more time helps
bk

[k8s] double test_executor timeout

---

python_modules/automation/automation/docstring_lint/validator.py
python_modules/automation/automation_tests/docstring_lint_tests/test_enhanced_section_headers.py
python_modules/automation/automation_tests/docstring_lint_tests/test_known_valid_symbols.py

Enhances docstring validation with improved detection and error messaging for malformed section headers. This ends up having much clearer error messages.
The changes focus on three key improvements:
1. Added detection for common section header issues:
- Missing colons (e.g., `Args` instead of `Args:`)
- Incorrect capitalization (e.g., `args:` instead of `Args:`)
- Incorrect spacing (e.g., `Args :` instead of `Args:`)
- Corrupted headers (e.g., `Argsjdkfjdkjfdk:`)
2. Enhanced error messages for RST parsing issues related to section headers:
- More helpful messages for "Unexpected indentation" errors
- Better guidance for "Block quote ends without a blank line" errors
3. Added comprehensive test suite for the new validation features
These improvements will help developers quickly identify …

Add enhanced section header error detection

---

python_modules/automation/automation_tests/telemetry/test_resource_telemetry.py

dagster_duckdb is not installed in 3.12 and later and causes these tests to fail. Adding this so that local running of tests is easier
Run in pytest locally

Skip certain tests in automation on 3.12 and later

---

python_modules/automation/automation/docstring_lint/validator.py
python_modules/automation/automation_tests/docstring_lint_tests/test_validator.py

Fixed a false positive in the docstring validator that was incorrectly flagging words ending with periods as malformed section headers. The validator was mistakenly identifying words like "returned." as potential section headers. The fix modifies the validation logic to only flag text as a possible malformed section header if it ends with a colon, which is the proper indicator of a section header.
Added two test cases:
1. A general test that verifies words ending with periods don't trigger section header warnings
2. A specific test that validates the fix works for the exact pattern from dagster.asset that was causing the false positive

Fix bug section header parsing

---

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/mcp_server.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/utils.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/mcp/server.py

i think this grouping makes more sense
`dg mcp configure`

[dg mcp] move configure to mcp group

---

python_modules/dagster/dagster/_core/asset_graph_view/bfs.py
python_modules/dagster/dagster_tests/execution_tests/misc_execution_tests/test_asset_backfill.py

[backfill] Merge asset graph subsets together

---

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/mcp/server.py

start a claude session and ask it to filter to specific assets

[dg mcp] list defs asset selection

---

python_modules/dagster/dagster/_core/execution/asset_backfill.py

Summary:
Use the method that modifies the partitions def if needed instead of requiring them to match perfectly.
Test Plan:
Dry run on an old backfill that was failing before

fix backfills if you change the partitions def of the target subset in the middle of the backfill

---

examples/docs_projects/project_atproto_dashboard/src/project_atproto_dashboard/defs/modeling.py

[project-atproto-dashboard] update dbt translator to use asset spec

---

CHANGES.md

[CHANGELOG] 1.11.4

---

.buildkite/buildkite-shared/buildkite_shared/quarantine.py
.buildkite/dagster-buildkite/dagster_buildkite/pipelines/dagster_oss_main.py

Matching internal PR https://github.com/dagster-io/internal/pull/17243

Unify quarantine_utils to buildkite-shared package

---

.buildkite/dagster-buildkite/dagster_buildkite/cli.py
.buildkite/dagster-buildkite/dagster_buildkite/defines.py
.buildkite/dagster-buildkite/dagster_buildkite/pipelines/dagster_oss_main.py
.buildkite/dagster-buildkite/dagster_buildkite/pipelines/dagster_oss_nightly_pipeline.py
.buildkite/dagster-buildkite/dagster_buildkite/pipelines/prerelease_package.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/dagster.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/dagster_ui.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/docs.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/helm.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/integration.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/test_project.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/tox.py
.buildkite/dagster-buildkite/dagster_buildkite/utils.py
.buildkite/dagster-buildkite/ruff.toml
.buildkite/dagster-buildkite/setup.py

Most of it is conversions from List to list type things

Remove old ruff type checker from dagster-buildkite

---

python_modules/dagster/dagster/_core/definitions/partitions/definition/multi.py

[partitions] filter invalid multi-partition keys

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/docs.py

Added a new docstring validation step to the Buildkite CI pipeline. This step installs the automation module with Buildkite dependencies and runs a script to check all docstrings in the codebase.
BK

CI for docstring validation

---

python_modules/dagster/dagster/_core/definitions/metadata/table.py

update these to gain `@record`s check short circuting , and generally clean things up 
loading a large repository snapshot containing table metadata
before:
`12005023 function calls (11941521 primitive calls)`
after:
`11695540 function calls (11632031 primitive calls)`

[record] table metadata

---

python_modules/dagster-graphql/dagster_graphql/implementation/execution/backfill.py
python_modules/dagster-graphql/dagster_graphql/implementation/utils.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_backfill.py
python_modules/dagster/dagster/_core/execution/asset_backfill.py
python_modules/dagster/dagster/_core/workspace/context.py
python_modules/dagster/dagster_tests/execution_tests/misc_execution_tests/test_asset_backfill.py

This reverts commit 8fa42bfe4ea2b54408d93c5312352da7bac9fd28. It has a problem with, you guessed it, dynamic parititons.

Revert "Raise an exception at backfill submission time when it targets partitions whose parents do not yet exist (#31537)"

---

python_modules/dagster/dagster/_core/instance/instance.py
python_modules/dagster/dagster/_core/instance/scheduling/__init__.py
python_modules/dagster/dagster/_core/instance/storage/__init__.py
python_modules/dagster/dagster/_core/instance/storage/storage_domain.py

This PR extracts storage-related functionality from the monolithic DagsterInstance class into a dedicated StorageDomain class. This refactoring moves dynamic partition management, storage optimization, and directory management operations into `storage/storage_domain.py`.
**Key Changes:**
- Created new StorageDomain class that encapsulates all storage operations
- Moved dynamic partition methods: get_dynamic_partitions(), add_dynamic_partitions(), delete_dynamic_partition(), has_dynamic_partition()
- Moved storage optimization methods: optimize_for_webserver(), reindex(), dispose()
- Moved directory management: file_manager_directory(), storage_directory(), schedules_directory()
- Moved storage ID operations: get_latest_storage_id_by_partition()
- Added backward compatibility alias …

Refactor DagsterInstance: Extract storage operations into StorageDomain

---

python_modules/dagster-test/dagster_test/utils/data_factory.py

required for https://github.com/dagster-io/internal/pull/17407 testing

allow kwargs in create_dagster_run test util

---

js_modules/dagster-ui/packages/ui-core/src/app/UserSettingsDialog/UserPreferences.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/app/UserSettingsDialog/useShowAssetsWithoutDefinitions.tsx
js_modules/dagster-ui/packages/ui-core/src/app/UserSettingsDialog/useShowStubAssets.tsx
js_modules/dagster-ui/packages/ui-core/src/app/UserSettingsDialog/useUserSettingDefaults.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/GraphSettings.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-selection/AntlrAssetSelectionVisitor.oss.ts
js_modules/dagster-ui/packages/ui-core/src/search/useGlobalSearch.tsx

As titled.  Adds new user settings to change this default
https://github.com/user-attachments/assets/88f9c3cf-a816-4222-9c26-276f6d00fef2

Add setting to toggle visibility of assets without definitions

---

python_modules/dagster/dagster/_symbol_annotations/lifecycle.py

when this fires in a hot path, the lambda based condition performs worse than a partial bound regular function 
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
...
35621    0.070    0.000    0.073    0.000 lifecycle.py:702(<lambda>)
```
after
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
...
35621    0.005    0.000    0.008    0.000 lifecycle.py:677(_param_is_used)
```

[lifecycle] avoid lambda for condition check

---

python_modules/dagster/dagster/_core/instance/runs/run_domain.py
python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py

Now that it has been validated for back-compat concerns.
BK

Revert "revert setting partitions subset on DagsterRun (main branch) (#31605)"

---

CHANGES.md

1.11.5 CHANGELOG

---

python_modules/dagster/dagster/_core/instance/assets/asset_domain.py
python_modules/dagster/dagster/_core/instance/instance.py

This change moves two asset-related methods from `DagsterInstance` to `AssetDomain` to follow the established architectural pattern where complex asset business logic resides in domain classes.
The moved methods are:
- `get_status_by_partition()` - Gets partition status for assets (materialized, failed, in-progress)
- `get_latest_data_version_record()` - Gets the latest data version record for assets
Both methods now live in `AssetDomain` with their complete business logic implementation, while `DagsterInstance` maintains simple delegation methods to preserve the public API. This refactoring improves code organization by consolidating asset-related functionality within the asset domain.
Existing test suite covers the functionality. All pyright type checks and ruff code quality checks …

Move get_status_by_partition and get_latest_data_version_record to AssetDomain

---

python_modules/dagster/dagster/_core/instance/events/event_domain.py
python_modules/dagster/dagster/_core/instance/instance.py

This PR extracts logging handler methods from DagsterInstance to EventDomain as part of the ongoing domain separation effort. The changes move three key logging methods:
- **get_yaml_python_handlers()**: Processes YAML-defined Python logging configuration and returns configured handlers
- **get_event_log_handler()**: Creates and configures the EventListenerLogHandler for capturing events
- **get_handlers()**: Aggregates all logging handlers (event log handler + YAML-defined handlers)
The methods are moved from DagsterInstance to EventDomain with the public API remaining unchanged. The DagsterInstance.get_handlers() method now delegates to the EventDomain implementation.
Existing test suite validates the refactored functionality.

Extract logging handlers from DagsterInstance to EventDomain

---

conftest.py

We've been using this to naively parallelize tests in some of our other tests suites so I'm upstreaming the tool to dagster in case we choose to begin using it there.

Add --split to conftest.py

---

python_modules/libraries/dagster-dbt/dagster_dbt/include/pyproject.toml.jinja

This file does not parse, now it does.
Apply change locally during dbt nux

fix missing comma in dbt nux pyproject.toml

---

.claude/agents/agent-coach.md
.claude/agents/buildkite-error-detective.md
.claude/agents/buildkite-stack-inspector.md

Adds a new `buildkite-stack-inspector` Claude Code agent that specializes in analyzing CI/CD build failures across Graphite stacks. This agent is designed to navigate complex PR stacks, examine build statuses, and pinpoint exactly where errors were first introduced in the development workflow.
The agent provides comprehensive stack analysis through four core capabilities:
- **Stack Navigation**: Uses `gt log` and Graphite commands to understand complete stack structure, branch relationships, and PR statuses
- **Build Status Analysis**: Examines Buildkite build results for each branch to identify failed builds, test failures, compilation errors, and other CI issues
- **Error Attribution**: Determines which branch first introduced each specific error by comparing error patterns across stack …

Add buildkite-stack-inspector: Agent for analyzing build failures across Graphite stacks

---

.claude/agents/buildkite-stack-inspector.md
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_scheduler.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py
python_modules/dagster/dagster/_core/instance/instance.py
python_modules/dagster/dagster/_core/instance/mixins/instigator_mixin.py

Extracts all instigator, schedule, and sensor-related functionality from the  class into a new  class. This refactoring improves code organization by separating concerns and follows the existing mixin pattern used in the codebase.
The  provides all the instigator-related methods including:
- Schedule control (start/stop/reset schedules)
- Sensor control (start/stop/reset sensors)  
- Instigator state management
- Tick operations and queries
- Maintenance operations
Existing test suite covers all moved functionality.
No public API changes - this is an internal refactoring.

Extract instigator functionality into InstigatorMixin

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/tox.py

So we can parallelize our builds on Buildkite using:
https://github.com/dagster-io/dagster/pull/31639

Thread --splits through tox

---

python_modules/dagster/dagster/_core/instance/runs/run_domain.py
python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py

Use the new partitions subset to efficiently store a subset for dynamic partition ranges as well.
New test case

Include dynamic partition subsets in DagsterRun at creation time

---

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/scaffold/branch.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_scaffold_branch_command.py

Adds basic ability to record inputs/ouputs of scaffold branch command for later analysis 
updated tests
`dg scaffold branch fix-stuff --record /tmp/scaffold`

[dg] scaffold branch --record

---

python_modules/dagster-graphql/dagster_graphql/implementation/execution/backfill.py
python_modules/dagster-graphql/dagster_graphql/implementation/utils.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_backfill.py
python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
python_modules/dagster/dagster/_core/execution/asset_backfill.py
python_modules/dagster/dagster/_core/workspace/context.py
python_modules/dagster/dagster_tests/asset_defs_tests/asset_graph_view_tests/test_basic_asset_graph_view.py
python_modules/dagster/dagster_tests/execution_tests/misc_execution_tests/test_asset_backfill.py

Now with the correct partition loading context (by using a new method on AssetGraphView)
New test cases

Bring back subset-based backfill validation at submission time

---

python_modules/dagster/dagster/_core/definitions/partitions/definition/time_window.py
python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py

- Add more tests for get_last_time_window
- Fix a bug those tests uncovered where if you combine end_date with end_offset < 0 it incorrectly always slices off the last end_offset partitions before end_date, even once they become eligible
- Add an efficient version of get_last_time_window for other offsets, allowing us to simplify the implementation of get_partition_keys. Fairly gnarly and might be worth stepping through together to double check that the logic is sound or that more test cases aren't needed to be totally confident.

Make computing last time window on a time window partition set efficient when the end offset is not 0

---

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/scaffold/branch.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_scaffold_branch_command.py

Added early validation to check if the current directory is within a git repository before executing the scaffold branch command. This prevents confusing errors that would occur later in the process when git commands are attempted in non-git directories.
dThe implementation includes a new `_check_git_repository()` function that runs `git rev-parse --git-dir` to verify the presence of a git repository. If the check fails with a "not a git repository" error, it provides helpful instructions to run `git init`.
BK. Manually tested as well.
```
(scaffold-branch-1) ➜  no-git dg scaffold branch
Error: This command must be run within a git repository.
To initialize a new git repository, run:
git init
(scaffold-branch-1) ➜  no-git
```
---
_Summary updated on Wed Aug 13 16:08:28 PDT 2025_

Add early git repository validation to scaffold branch command

---

python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/databricks_configs.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/configs/resources/jobs.yml
python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/test_configs.py

Support Python wheel tasks in DatabricksConfigs.
BK

[dagster-databricks] Support Databricks Python wheel tasks in asset bundle component

---

python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/databricks_configs.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/configs/resources/jobs.yml
python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/test_configs.py

Support Spark jar tasks in DatabricksConfigs.
BK

[dagster-databricks] Support Databricks Spark Jar tasks in asset bundle component

---

python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/databricks_configs.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/configs/resources/jobs.yml
python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/test_configs.py

Support Job tasks in DatabricksConfigs.
BK

[dagster-databricks] Support Databricks Job tasks in asset bundle component

---

python_modules/libraries/dagster-dg-cli/MANIFEST.in
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/scaffold/branch/CLAUDE.md
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/scaffold/branch/dg_scaffold_pr_sequencing_plan.md
python_modules/libraries/dagster-dg-cli/setup.cfg

This PR adds a detailed implementation plan for transforming `dg scaffold branch` from a basic scaffolding tool into an intelligent, context-aware code generation system. The plan focuses on rapid iteration, quality improvement, and comprehensive project understanding.
**Key additions:**
- **Planning document** (`dg_scaffold_pr_sequencing_plan.md`): 14-phase roadmap prioritizing fast feedback loops and quality assessment
- **Package distribution fix**: Added new markdown file to `MANIFEST.in` to prevent CI failures  
- **Documentation enhancement**: Added critical package distribution guidelines to prevent future `check-manifest` issues
The plan emphasizes documentation-first development where all discovered patterns and best practices are immediately captured, using code generation …

Add comprehensive planning document for dg scaffold branch enhancements

---

CLAUDE.md

Disallow git pushes in CLAUDE.md without user confirmation
Read

Discourage git push in CLAUDE.md

---

js_modules/dagster-ui/packages/ui-core/src/assets/LaunchAssetChoosePartitionsDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadAllowedRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadSession.tsx
js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadTransientSessionContainer.tsx

need to do a push without this before pushing the FE
NOCHANGELOG

Revert "[backfills] Frontend for backfill configuration (#31779)"

---

python_modules/dagster/dagster/_core/definitions/asset_selection.py

[asset selection] raise DagsterError on bad input

---

.claude/commands/ai_update_pr.md

Update /ai_update_pr to scale length and complexity of ai-generated diff summary with underlying change.
_This section was automatically generated based on the diff analysis:_
This change enhances the AI Update PR documentation by adding specific complexity guidelines that scale the detail level of generated summaries based on the underlying changes. The update introduces a tiered approach ranging from single bullet points for simple fixes to expansive analysis for complex architectural changes, ensuring AI-generated content matches the appropriate level of detail.
Documentation update verified through content review.

Update /ai_update_pr to scale length and complexity of ai-generated diff summary with underlying change.

---

js_modules/dagster-ui/packages/ui-core/src/assets/LaunchAssetChoosePartitionsDialog.tsx
js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadAllowedRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadSession.tsx
js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadTransientSessionContainer.tsx

Reapply "[backfills] Frontend for backfill configuration (#31779)"

---

python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/component.py
python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/resource.py
python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/scaffolder.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/conftest.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/test_component.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/test_scaffolder.py

Implement a thin wrapper around WorkspaceClient that will be used as a resource to materialize Databricks assets
BK

[dagster-databricks] Add Databricks resource for DatabricksAssetBundleComponent

---

python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/component.py
python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/configs.py
python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/resource.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/test_component.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/test_resource.py

Support task dependencies when creating SubmitTask objects in submit_and_poll.
BK

[dagster-databricks] Support dependencies in DatabricksWorkspace.submit_and_poll

---

js_modules/dagster-ui/packages/ui-core/client.json
js_modules/dagster-ui/packages/ui-core/src/asset-graph/__tests__/useAssetGraphSupplementaryData.test.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphSupplementaryData.oss.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-selection/input/__tests__/util.test.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-selection/input/util.ts
js_modules/dagster-ui/packages/ui-core/src/assets/AssetTableFragment.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetCatalogTableV2.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetTableFragment.types.ts
js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetsCatalogTable.types.ts
js_modules/dagster-ui/packages/ui-core/src/assets/useAllAssets.tsx
js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/types/WorkspaceQueries.types.ts
js_modules/dagster-ui/packages/ui-core/src/workspace/types/WorkspaceAssetsQuery.types.ts

As titled.
https://www.notion.so/dagster/Asset-Selection-Status-Filtering-Proposal-25318b92e462800c924cc5033b1971f2
jest
https://github.com/user-attachments/assets/dd88d037-ecde-437e-82ce-fa38f912020e

Add asset selection sub-status filtering

---

python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/component.py
python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/configs.py
python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/resource.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/test_resource.py

Support cluster config when creating SubmitTask objects in submit_and_poll
BK

[dagster-databricks] Support cluster configs in DatabricksWorkspace.submit_and_poll

---

python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/configs.py
python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/resource.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/configs/resources/jobs.yml
python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/test_resource.py

Create task as expected by the Databricks sdk for each type of task and pass it to the SubmitTask in submit_and_poll
BK

[dagster-databricks] Transform tasks to databricks sdk tasks in DatabricksWorkspace.submit_and_poll

---

python_modules/dagster/dagster/_core/instance/instance.py
python_modules/dagster/dagster/_core/storage/defs_state/__init__.py
python_modules/dagster/dagster/_core/storage/defs_state/base.py
python_modules/dagster/dagster/_core/storage/defs_state/defs_state_info.py
python_modules/dagster/dagster/_core/storage/defs_state/run_storage_state_storage.py
python_modules/dagster/dagster/_grpc/server.py
python_modules/dagster/dagster_tests/core_tests/instance_tests/test_state_storage_lifecycle.py
python_modules/dagster/dagster_tests/storage_tests/test_state_storage.py
python_modules/dagster/dagster_tests/storage_tests/utils/state_storage.py

Reworks some earlier PRs. This creates a new StateStorage abstraction and allows it to be fetched contextually. It supports operations to upload and download files to the state store, as well as fetch the latest available versions of all files.
NOCHANGELOG

[1/n] StateStorage base class and lifecycle

---

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/scaffold/branch/ai.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/scaffold/branch/claude/sdk_client.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/scaffold/branch/command.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/scaffold/branch/planning.py

thread through options so they get used
`dg scaffold branch "Scaffold a new component that runs a Python script over Dagster pipes representing a single asset." --verbose`
observe correct models in debug output

[dg scaffold branch] actually use model choices

---

python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/component.py
python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/configs.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/test_component.py

[dagster-databricks] Support custom op spec in DatabricksAssetBundleComponent

---

python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/component.py

As requested [here](https://github.com/dagster-io/dagster/pull/31711#discussion_r2279570451)

[dagster-databricks] Use get_asset_spec to get dep asset key

---

python_modules/libraries/dagster-databricks/setup.py

[dagster-databricks] Support pre-releases when resolving library version

---

js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInput.tsx

This seems to fix it honestly not sure why

[SelectionInput] Fix pasting strings with multiple spaces

---

python_modules/dagster/dagster/_core/definitions/asset_health/asset_check_health.py

UNKNOWN => NOT_APPLICABLE when there are no asset checks

---

js_modules/dagster-ui/packages/ui-core/src/integrations/IntegrationListRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/integrations/SingleIntegrationRoot.tsx

Track pageviews on Integrations list and individual page.
View app, navigate to integrations and individual integration page. Verify pageview tracking in console.

[ui] Track pageviews on Integrations

---

js_modules/dagster-ui/packages/ui-core/src/assets/useAllAssets.tsx
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_asset_checks.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py

we started pre-computing this when we create the nodes but did not use it here
existing tests

[graphql] use RemoteAssetNode.check_keys for hasAssetChecks

---

python_modules/dagster/dagster/_core/workspace/load_target.py

for use elsewhere, no behavior changes

refactor load from pyproject.toml

---

CHANGES.md

Changelog 1.11.8

---

js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetHealthDataProvider.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/AssetHealthSummary.tsx
js_modules/dagster-ui/packages/ui-core/src/assets/useAllAssets.tsx

Reverts dagster-io/dagster#31979

Revert "[Observe][perf] Only query health data for SDAs"

---

python_modules/dagster/dagster/components/resolved/base.py
python_modules/dagster/dagster_tests/components_tests/resolution_tests/test_resolved.py

THe new test would not work before, now it does.
One jank thing: we only allow string keys

[resolved] Allow dictionary values

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/run_handler.py

[dagster-dbt] Support missing unique_id in DbtCloudJobRunResults.to_default_asset_events

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/asset_decorator.py
python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/cli_invocation.py
python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/client.py
python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/resources.py
python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/run_handler.py
python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/sensor_builder.py
python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/types.py

It has been available for a while now and is pretty stable

[dagster-dbt] Mark dbt Cloud v2 APIs as GA

---

.buildkite/buildkite-shared/buildkite_shared/python_version.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/integration.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py

Summary:
[test-all] To stay below buildkite's 1000 job limit

[test-all] reduce buildkite versions when all versions are tested

---

CHANGES.md

1.11.9 CHANGELOG

---

js_modules/dagster-ui/packages/ui-components/src/components/css/ListItem.module.css

Make list items use text-default color for main text

---

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py

These docstrings were not specific enough.
NOCHANGELOG

[da] update misleading docstrings

---

python_modules/dagster/dagster/_daemon/sensor.py

Summary:
This is needed for DA user code sensors which count the number of partitions when adding DA evaluations.
Have a local repro that goes away, working on a repro of before/after

Add a partition loading context in sensor evaluation

---

python_modules/libraries/dagster-omni/dagster_omni/component.py
python_modules/libraries/dagster-omni/dagster_omni/objects.py
python_modules/libraries/dagster-omni/dagster_omni/translation.py
python_modules/libraries/dagster-omni/dagster_omni/workspace.py
python_modules/libraries/dagster-omni/dagster_omni_tests/test_defs.py
python_modules/libraries/dagster-omni/dagster_omni_tests/test_users.py
python_modules/libraries/dagster-omni/dagster_omni_tests/test_workspace.py
python_modules/libraries/dagster-omni/dagster_omni_tests/utils.py

Also include more detailed user information so we can add owner information
NOCHANGELOG

[dagster-omni] Fetch user information

---

RUN_API_IMPLEMENTATION_PLAN.md
RUN_API_SPECIFICATION.md
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/api_layer/api/run.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/api_layer/api/run_event.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/api_layer/graphql_adapter/run.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/api_layer/graphql_adapter/run_event.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/api_layer/schemas/run.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/api_layer/schemas/run_event.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/api/cli_group.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/api/run.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/api/run_event.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/__snapshots__/test_dynamic_command_execution.ambr
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/run_tests/Makefile
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/run_tests/__snapshots__/test_business_logic.ambr
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/run_tests/recordings/success_canceled_run/01_response.json
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/run_tests/recordings/success_failed_run/01_response.json
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/run_tests/recordings/success_single_run/01_response.json
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/run_tests/recordings/success_single_run_text/01_response.json
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/run_tests/scenarios.yaml
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/run_tests/test_business_logic.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/run_tests/test_schema_only.py

Add runs to dg api

---

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/defs_state.py

AI generated some unnecessarily complex code here, just cleaning it up
NOCHANGELOG

[sbc] minor cleanup of `refresh-defs-state` code

---

examples/docs_snippets/README.md

Include so more details on how to run specific tests and some of the hidden testing

[docs] Include details on docs testing

---

python_modules/dagster/dagster/_core/execution/plan/active.py
python_modules/dagster/dagster_tests/execution_tests/dynamic_tests/test_dynamic_execution.py

See the added test case. Essentially, when you have a blocking asset check, this gets wired in as an additional dependency to every input of any downstream op that consumes the asset that the check is checking. This ends up being a `FromMultipleSourcesLoadSingleSource` step input source. 
My assumption is that the reason we were looking for all upstream outputs to be skipped in order to skip is simply that this makes sense for the (admittedly rare) fan-in case, where you may have N upstream outputs that fan into a single input (note: this never happens with assets, it just happens with ops). However, it seems worthwhile to retain that behavior while updating the behavior in this case.
Fixed a bug which would cause steps downstream of an asset with `skippable=True` and a blocking asset …

[exec] Fix bug when asset is downstream of blocking asset check and non-required upstream output

---

python_modules/libraries/dagster-omni/dagster_omni/objects.py
python_modules/libraries/dagster-omni/dagster_omni/translation.py
python_modules/libraries/dagster-omni/dagster_omni/workspace.py

Adds some additional information to the metadata
NOCHANGELOG

[dagster-omni] Include favorites / view counts

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/__init__.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/components/workspace_component/component.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/resources.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/beta/test_component.py

[dagster-airbyte] Add back AirbyteCloudWorkspaceComponent

---

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql
js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/execution.py

I messed up originally and made the type of assetSelection list[string] instead of list[GrapheneAssetKey].
NOCHANGELOG

[ui] Add assetKeys property to GrapheneExecutionPlan

---

CHANGES.md

1.11.11 CHANGELOG

---

helm/dagster/values.yaml

[helm] use bitnamilegacy for internal redis

---

python_modules/libraries/dagster-deltalake/dagster_deltalake/handler.py

[dagster-deltalake] simplify deltalake>=1.0.0 support

---

python_modules/dagster/dagster/_utils/schedules.py

Fixes an issue where the cron iterator creates two consecutive ticks with identical timestamps at the DST boundary for an hourly cron ("0 * * * *"), leading `get_smallest_cron_interval` to return an incorrect smallest interval of 0 (should be 1 hour).
existing test suite

Fix dst issue in `get_smallest_cron_interval`

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/resources.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/beta/conftest.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/beta/test_asset_specs.py

Fixes #32271 
> [dagster-airbyte] Fix the pagination url issue for the Airbyte API

[dagster-airbyte] Fix the pagination url issue for the Airbyte API

---

pyright/master/exclude.txt
python_modules/dagster/dagster/_generate/download.py

[examples] remove entries in scaffolder for deleted examples

---

CHANGES.md

[changelog] 1.11.12

---

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/api_layer/api/secret.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/api_layer/graphql_adapter/secret.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/api_layer/schemas/secret.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/api/API_IMPLEMENTATION_PLAN.md
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/api/cli_group.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/api/formatters.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/api/secret.py
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/__snapshots__/test_dynamic_command_execution.ambr
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/secret_tests/Makefile
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/secret_tests/__snapshots__/test_business_logic.ambr
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/secret_tests/recordings/success_multiple_secrets/01_response.json
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/secret_tests/recordings/success_multiple_secrets_text/01_response.json
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/secret_tests/recordings/success_single_secret/01_response.json
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/secret_tests/recordings/success_single_secret_text/01_response.json
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/secret_tests/recordings/success_single_secret_with_value/01_response.json
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/secret_tests/recordings/success_single_secret_with_value_text/01_response.json
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/secret_tests/scenarios.yaml
python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/secret_tests/test_business_logic.py

```
▸ dg api secret list --location basics
Name: SNOWFLAKE_USER
Locations: All code locations
Scopes: Full Deployment, All Branch Deployments, Local Deployment
Can Edit: Yes
Can View Value: Yes
Updated By: <redacted>
Updated: 2023-05-04 19:14:15
```
```
▸ dg api secret get --location basics SNOWFLAKE_KEY
Name: SNOWFLAKE_KEY
Locations: All code locations
Scopes: Full Deployment, All Branch Deployments, Local Deployment
Permissions:
Can Edit: Yes
Can View Value: Yes
Value: <hidden - use --show-value to display>
Updated By: <redacted>
Updated: 2025-09-10 17:02:38
```
- [dg] adds `dg api secret list` and `dg api secret get`

[dg] adds `dg api secret list` and `dg api secret get`

---

js_modules/dagster-ui/packages/ui-core/client.json
js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetHealthDataProvider.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-data/__tests__/AssetHealthDataProvider.test.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-data/types/AssetHealthDataProvider.types.ts

Reverts dagster-io/dagster#32330

Revert "fetch latest failure timestamp in asset health query"

---

js_modules/dagster-ui/packages/ui-core/client.json
js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetHealthDataProvider.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-data/__tests__/AssetHealthDataProvider.test.tsx
js_modules/dagster-ui/packages/ui-core/src/asset-data/types/AssetHealthDataProvider.types.ts

Reverts dagster-io/dagster#32356
now with the fixed tests

Revert "Revert "fetch latest failure timestamp in asset health query""

---

python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py

had some unintended consequences
bk

Revert "[graphql] improve isAssetJob resolution (#32322)"

---

CHANGES.md

Changelog 1.11.13

---

python_modules/dagster/dagster/components/utils/translation.py
python_modules/libraries/dagster-dbt/dagster_dbt/components/dbt_project/component.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/test_dbt_project_component.py

Users of the DbtProjectComponent should be able to write arbitrary python code to determine the translation behavior of their component, but right now that's pretty hard to do. Now, you can just subclass the DbtProjectComponent and override `get_asset_spec` / `get_asset_check_spec` to completely customize the behavior.
[dagster-dbt] The `DbtProjectComponent` now supports overriding `get_asset_spec` and `get_asset_check_spec` methods when subclassing.

[dagster-dbt] Allow `get_asset_spec` to be overridden on the component class

---

python_modules/libraries/dagster-fivetran/dagster_fivetran/components/workspace_component/component.py
python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_component.py

As title
[dagster-fivetran] The `FivetranAccountComponent` now has a `get_asset_spec` method that can be overridden by subclasses.

[dagster-fivetran] Add a `get_asset_spec` method to FivetranAccountComponent

---

examples/docs_projects/project_ask_ai_dagster/pyproject.toml
examples/docs_projects/project_ask_ai_dagster/src/project_ask_ai_dagster/definitions.py
examples/docs_projects/project_ask_ai_dagster/uv.lock
examples/docs_projects/project_atproto_dashboard/pyproject.toml
examples/docs_projects/project_atproto_dashboard/src/project_atproto_dashboard/definitions.py
examples/docs_projects/project_atproto_dashboard/uv.lock
examples/docs_projects/project_dagster_modal_pipes/pyproject.toml
examples/docs_projects/project_dagster_modal_pipes/src/project_dagster_modal_pipes/definitions.py
examples/docs_projects/project_dagster_modal_pipes/uv.lock
examples/docs_projects/project_dbt/pyproject.toml
examples/docs_projects/project_etl_tutorial/pyproject.toml
examples/docs_projects/project_etl_tutorial/uv.lock
examples/docs_projects/project_llm_fine_tune/pyproject.toml
examples/docs_projects/project_llm_fine_tune/src/project_llm_fine_tune/definitions.py
examples/docs_projects/project_llm_fine_tune/uv.lock
examples/docs_projects/project_prompt_eng/pyproject.toml
examples/docs_projects/project_prompt_eng/src/project_prompt_eng/definitions.py
examples/docs_projects/project_prompt_eng/uv.lock

Update older examples to match newer dg/components format

Consistent dg in examples

---

js_modules/dagster-ui/packages/ui-core/client.json
js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadAllowedRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadRoot.tsx
js_modules/dagster-ui/packages/ui-core/src/launchpad/types/LaunchpadAllowedRoot.types.ts

This can be a lot faster when you are materializing a single asset within a very large asset job.
Materialize an individual asset, an asset job without an asset selection, an asset job with an asset selection, and a non asset job

Pass in asset selection to launchpad query

---

python_modules/dagster/README.md

- Use `import dagster as dg` in README example
NOCHANGELOG

Updates README.md to use "import ... as ..." syntax

---

python_modules/dagster/dagster/_core/definitions/asset_selection.py

Summary:
In selections where we already know we are iterating over all or most assets in the graph, avoid repeated point fetches, which may be more expensive than just using the in memory dictionary.

avoid repeated point fetches in asset selections

---

examples/docs_projects/project_etl_tutorial/dashboard/package-lock.json
examples/docs_projects/project_etl_tutorial/dashboard/package.json

Looks like I missed a couple spots in `project_etl_tutorial`.
npm install, verify updates.

Dependabot followup on project_etl_tutorial
