js_modules/dagster-ui/packages/ui-core/src/assets/MaterializationTag.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/SimpleStakeholderAssetStatus.tsx
Helpful to contextualize the last materialization time.
- [ui] Added elapsed time to last materialization tags on asset overview pages
=> add elapsed time to last materialization / observation / failure

js_modules/dagster-ui/packages/ui-core/client.json, js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetBaseDataProvider.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-data/types/AssetBaseDataProvider.types.ts, js_modules/dagster-ui/packages/ui-core/src/asset-graph/__fixtures__/AssetNode.fixtures.ts, js_modules/dagster-ui/packages/ui-core/src/assets/MaterializationTag.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/SimpleStakeholderAssetStatus.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedAssetRow.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/types/VirtualizedAssetRow.types.ts
Especially for multi-assets with asset selections, the stepKey can change across runs and cannot be trusted.  This results in broken experience when using the materialization tag to link to runs.
Should be able to satisfy without doing any extra data fetching (although it is passing an extra string per node).
https://github.com/user-attachments/assets/401a5ce4-5e39-4004-965c-eb18bceb78b2
- [ui] Fixed a bug where the materialization status tag would sometimes deep link to the wrong step key in the materializing run.
=> use historic step key vs current step key for asset materialization link

docs/docs/integrations/libraries/spark.md
As title, to make the PySpark guide more discoverable.
Docs preview
=> [docs] Reference PySpark guide in Spark page

examples/docs_snippets/docs_snippets/guides/components/index/1-help.txt, examples/docs_snippets/docs_snippets/guides/dg/workspace/1-dg-init.txt, examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/dg/test_dg_docs_workspace.py, python_modules/libraries/dagster-dg/dagster_dg/cli/init.py, python_modules/libraries/dagster-dg/dagster_dg/scaffold.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_init_command.py
Change the `dg init` command in a few ways:
- a `DIRNAME` argument is added
- `--workspace-name` option is removed, replaced by `--workspace` flag
- `DIRNAME` may be set to `.` to create (either workspace or project) in the current directory
- default workspace prompt is now (`.`)
Examples:
- `dg init`: creates a project, prompts for project name
- `dg init .`: scaffold a new project in the CWD
- `dg init helloworld`: scaffold a new project in new dir `helloworld`
- `dg init -workspace dagster-workspace`: scaffold a new workspace in new dir `dagster-workspace`, prompt for project name
- `dg init --workspace .`: scaffold a new workspace in the CWD, prompt for project anme
- `dg init --workspace --project-name helloworld .`: scaffold a new workspace in the CWD, create project named …
=> [dg] Make init command work with a dirname arg (BUILD-893) (BUILD-919)

pyproject.toml, python_modules/dagster/setup.py
To avoid hanging tests like we ran into here:
https://dagsterlabs.slack.com/archives/C03EQ628RS7/p1744219888323539
We might need to tune this actual number a bit although the longest avg
test duration I see in Test Engine this week is ~3.5 minutes:
https://buildkite.com/organizations/dagster/analytics/suites/dagster/tests/70058306-3987-85dc-8cbf-8da39d8ebaad?period=7days&tags=scm.branch%3Amaster
=> Enforce global pytest timeout

python_modules/dagster/dagster/components/resolved/base.py, python_modules/dagster/dagster_tests/components_tests/resolution_tests/test_resolved.py
During use, we hit an error when a `@dataclass` used as a field in a `Resolvable` `@dataclass` was not also `Resolvable`. 
This PR makes a conservative improvement for this problem by 
* adding some newlines to highlight the problematic annotation 
* calling out explicitly that a `Resolvable` subclass is one of the expected conditions
added test
=> [resolvable] cite Resolvable subclass in error message

python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py
We could do another env var, but wanted to float just having this one.
Line of thought here is that `IS_DEV_CLI` -> "is development cli" and `dg` is our local development CLI 
tbd
=> RFC [dg] set DAGSTER_IS_DEV_CLI

python_modules/dagit/tox.ini, python_modules/dagster-webserver/tox.ini, python_modules/libraries/dagster-gcp/tox.ini, python_modules/libraries/dagstermill/tox.ini
Just weird situations where either a lack of a space of some strange duplication makes passing of positional arguments to tox not work locally.
=> Fixup bad posargs

python_modules/dagit/dagit_tests/test_cli.py
When we investigate while it's hanging. Ideally we'd just mute this in Buildkite, but since it still runs under xfail, we still hit our hang.
=> Skip hanging dagit test

python_modules/dagster/dagster/_core/execution/plan/compute.py, python_modules/dagster/dagster/_core/execution/plan/outputs.py, python_modules/dagster/dagster_tests/core_tests/snap_tests/test_old_execution_plan_snapshot.py
This appears to be unused in 2025. Retain the serialized field for any old versions that might still be using it, but make the name clearer that it is unused.
New back-compat test case
=> Deprecate/remove 'should_materiailze' field on StepOutput

python_modules/dagit/dagit_tests/test_cli.py
This adds some more safety around our subprocess calls.
I think what's happening here is that terminate is sending SIGTERM, in some cases, dagit isn't responding to it, and then wait is just blocking indefinitely.
This instead calls terminate, gives it 10 seconds, and then calls SIGKILL.
I don't have a lead on why dagit is sometimes ignoring SIGTERM (nor am I digging into it right now) but it's pretty irrelevant to this particular test case which just makes sure we're correctly redirecting folks to dagster-webserver.
=> Reintroduce hanging dagit test

js_modules/dagster-ui/packages/ui-components/src/components/Skeleton.tsx
using `transform` allows us to take advantage of GPU acceleration. 
In-depth explanation here https://www.smashingmagazine.com/2016/12/gpu-animation-doing-it-right/
Side by side comparison: left is current, right is this PR.
https://github.com/user-attachments/assets/a75693d0-89b5-4378-a767-0ac4036e67f6
=> Animate skeleton component with transform

js_modules/dagster-ui/packages/ui-components/src/components/Skeleton.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedAssetTable.tsx
as titled
With only 1 tab open compare cpu/gpu usage
Before vs after
=> [Performance] Skeleton - use css contain + isolate

docs/docs/guides/build/ops/dynamic-graphs.md, examples/docs_snippets/docs_snippets/concepts/ops_jobs_graphs/dynamic.py
Our current doc for a dynamic job uses two small code snippets as examples, but these stub necessary methods/ops and it isn't clear how to use them. I extended these snippets by using them in a full working example.
👀
=> [docs] extend dynamic job code snippets with full example

js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx
as titled
Logged into an organization where job names are not unique across deployments and saw that we correctly filtered assets to the right job by including the repository location and name.
=> [Job graph] Include respository from pipeline selector in filtering

python_modules/dagster-test/dagster_test/toys/asset_health.py, python_modules/dagster-test/dagster_test/toys/repo.py
starting a small code location that we can deploy to dogfood to make it easier to test asset health. Most of our assets in the toys repo always succeed or always fail, making it hard to test state transitions. We'll probably need to add some more assets+checks as testing continues, but this will get us started 
=> toys code location for testing asset health

python_modules/libraries/dagster-postgres/MANIFEST.in, python_modules/libraries/dagster-postgres/conftest.py, python_modules/libraries/dagster-postgres/dagster_postgres_tests/conftest.py
I originally had this nested down a level and was bumping into:
https://docs.pytest.org/en/stable/how-to/writing_plugins.html#requiring-plugins-in-non-root-conftests
So I did direct imports.
But sticking it in the conftest.py in the package's root dir (not our monorepo root dir) satisfies where pytest expects to be able to lookup these plugins and lets us avoid the nasty ignore/noqa annotations.
=> Correctly add pytest plugins

pyproject.toml
```
-r chars              Show extra test summary info as specified by chars:
(f)ailed, (E)rror, (s)kipped, (x)failed, (X)passed,
(p)assed, (P)assed with output, (a)ll except passed
(p/P), or (A)ll. (w)arnings are enabled by default (see
--disable-warnings), 'N' can be used to reset the list.
(default: 'fE').
```
Historically we've only printed errors. But this changes it to print summaries of:
- failures
- errors
- skips (and their reason)
- xfailed (expected to fail and their reasons - this should show muted tests that actually fail)
- xpassed (expected to fail but actually passed and their reasons - this should show tests that are muted but maybe shouldn't be anymore)
=> Print muted tests at end of test run

integration_tests/test_suites/k8s-test-suite/tests/test_pipes.py, python_modules/libraries/dagster-k8s/dagster_k8s/pipes.py, python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_pipe_log_reader.py
This is a fix for two issues in the pipes client:
- Transient network errors failing the run even though the underlying container is still running
- Lack of any read timeouts causing sporadic hangs
To fix this, add a retry layer, using timestamps to prevent the same logs from being logged again.
Once we can dedupe, we can set a default request timeout as well and retry after its hit, since we can't reliably count on the long-standing HTTP connection to not hang.
New unit and integration test cases
[dagster-k8s] Reliability improvements to PipesK8sClient log streaming when transient networking errors occur. The default behavior of the PipesK8sClient is now to reconnect to the stream of logs every hour (this value can be overridden by setting the …
=> Add retry layer and default read timeout to k8s pipe client consume_pod_logs

python_modules/dagster/dagster/components/core/defs_module.py, python_modules/dagster/dagster/components/core/load_defs.py, python_modules/dagster/dagster/components/lib/definitions_component/__init__.py, python_modules/libraries/dagster-sling/dagster_sling_tests/test_sling_replication_collection_component.py
The wrapped components were confusing me so I took a spin at refactoring to try to simplify things.
`get_component()` for (maybe) getting a `Component` at `context.path` 
`DefsFolderComponent.get()` for expecting to get a `DefsFolderComponent` like for `defs` folder 
=> [component] remove DefsModuleComponent

js_modules/dagster-ui/packages/ui-core/src/runs/LogFilterSelect.tsx
On the run page, show `X/Y` instead of just `X` for the number of level types selected for the logs display filtering.
Materialize an asset, view the run. Verify that the button label has the full `X/Y` string.
[ui] On the run page, show the number of log levels selected as well as the number of log levels available.
=> [ui] Show levels fraction on run page

python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py, python_modules/libraries/dagster-dbt/dagster_dbt/cloud/asset_defs.py, python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/run_handler.py, python_modules/libraries/dagster-dbt/dagster_dbt/components/dbt_project/component.py, python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_cli_event.py, python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py, python_modules/libraries/dagster-dbt/dagster_dbt/dbt_manifest_asset_selection.py, python_modules/libraries/dagster-dbt/dagster_dbt/utils.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud/test_asset_defs.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/test_dbt_project_component.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_materialization_execution_duration.py
Make `get_asset_spec` authoritative by moving all internal call sites to calling that to get access to properties like the key.
This changes the API signature of `get_asset_spec` from its previous set to a much more manageable `manifest: Mapping[...], unique_id: str, project: Optional[DbtProject]`. 
`project` getting thread through when needed when `enable_code_references` is on is the biggest concern. 
=> [dbt] cutover callsites to translator.get_asset_spec

docs/docs/guides/labs/dg/configuring-dg.md, docs/docs/guides/labs/dg/python-environment-management-and-uv-integration.md, examples/docs_snippets/docs_snippets/guides/dg/configuring-dg/project-config.toml, examples/docs_snippets/docs_snippets/guides/dg/configuring-dg/user-config.toml, examples/docs_snippets/docs_snippets/guides/dg/configuring-dg/workspace-config.toml, examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/dg/test_configuring_dg.py, examples/docs_snippets/tox.ini, python_modules/libraries/dagster-dg/dagster_dg/config.py, python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Add a guide on "Configuring `dg`". This explains the various kinds of configuration files and how they interact with CLI options. It also provides a comprehensive list of settings.
The list of settings was done in an _ad hoc_ way-- in the future I think we'll want to machine-generate this like API docs, but we need something out there now.
Note that there was (accidentally) a pre-existing but unlisted page in `master` called "Configuring `dg`" that was an alternative version of the current uv integration page. So this PR just edits that and makes it visible, rather than introducing a new page.
Simple tests to make sure the snippets load and validate.
=> [dg] Add configuring dg guide (BUILD-820)

python_modules/libraries/dagster-dg/dagster_dg/scaffold.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
Fix bug in `dg scaffold project` when not using editable dagster-- scaffolded project did not have `dagster` as a dependency.
New unit test.
Fixed a bug where new projects scaffolded with `dg scaffold project` were lacking `dagster` as a dependency.
=> [dg] Add `dagster` dep to scaffolded project

docs/docs/guides/labs/components/components-etl-pipeline-tutorial.md
The components ETL tutorial currently breaks after generating a DBT component because the `project_dir` relative path is generated incorrectly as `../../../dbt/jdbt` when it should be `../../../../dbt/jdbt`. The necessary path changed after the change to `src`-based layout. 
I'm not sure of how the logic needs to be changed to generate the right path, but this PR just inserts a note into the tutorial warning users about this bug so they can fix the path and proceed with the tutorial. We should remove this when we fix the bug and make the next release.
This was not being caught by our tests because we don't actually load defs in the tests with the initially generated `component.yaml`, and subsequent edits silently update the path to the correct `../../../../dbt/jdbt`.
Did the tutorial …
=> [dg] Add note telling users to fix broken path in components ETL tutorial DbtProjectComponent

python_modules/libraries/dagster-dg/dagster_dg/cli/check.py, python_modules/libraries/dagster-dg/dagster_dg/cli/dev.py, python_modules/libraries/dagster-dg/dagster_dg/context.py, python_modules/libraries/dagster-dg/dagster_dg/utils/version.py, python_modules/libraries/dagster-dg/dagster_dg_tests/utils_tests/test_versions.py
This helps avoid back-compat issues when dg is running a different dagster version than the underlying uv tool run command. The main target is for dg deploy, which always invokes uv tool run currently, but I figured it could be useful for the other places we run uv tool run too.
new test case, locally batch __version for dg and run dg dev and dg deploy and dg check
=> Pin dagster/dagster-cloud version used by dg when using uv tool run

js_modules/dagster-ui/packages/ui-core/client.json, js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetHealthDataProvider.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-data/types/AssetHealthDataProvider.types.ts, js_modules/dagster-ui/packages/ui-core/src/assets/AssetCatalogTableV2.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetHealthSummary.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetRecentUpdatesTrend.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx
1. Add descriptions.
2. Fix the order of events in the health trend.
=> [1/n][Asset Health] Add descriptions to health summary card

docs/docs/guides/migrate/airflow-to-dagster/index.md
Fix relative links in Airflow migration index page.
Local build.
=> DOC-1072 Fix broken Airflow migration links in documentation

docs/docs/guides/labs/components/components-etl-pipeline-tutorial.md, examples/docs_snippets/docs_snippets/guides/components/index/26-jaffle-dashboard-clone.txt, examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/components/test_components_docs.py
- Uses Dagster owned jaffle-dashboard repository
NOCHANGELOG
=> [components] use dagter-io/jaffle-dashboard in components ETL tutorial

js_modules/dagster-ui/packages/ui-core/client.json, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetRunLogObserver.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/types/AssetRunLogObserver.types.ts
Observe this event to trigger refetch asset live data so that we show failed status immediately.
=> [AssetRunLogObserver] Observe failed to materialize event

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_health.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_all_snapshot_ids.ambr, python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py, python_modules/dagster/dagster/_core/definitions/freshness.py, python_modules/dagster/dagster/_core/instance/__init__.py
Includes the freshness status of each asset in asset health. Follows these rules:
- `HEALTHY` - the freshness policy is in a PASS-ing state
- `WARNING` - the freshness policy is in a WARN-ing state
- `DEGRADED` - the freshness policy is in a FAIL-ing state
- `UNKNOWN` - the freshness policy has never been evaluated or is in an UNKNOWN state
- `NOT_APPLICABLE` - the asset does not have a freshness policy defined.
I need to access the freshness getter function from OSS, so i added an instance method for it. This could also be solved by moving the storage methods to a shared storage class (Run or EventLog probably). I don't have a preference and picked adding the Instance method for no specific reason. Similarly, I needed to move `FreshnessRecord` and `FreshnessRecordBody` to OSS so that I …
=> [asset health] include freshness in asset health

js_modules/dagster-ui/packages/ui-core/src/assets/LaunchAssetChoosePartitionsDialog.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/LaunchAssetExecutionButton.test.tsx, js_modules/dagster-ui/packages/ui-core/src/launchpad/uiExecutionTags.tsx, js_modules/dagster-ui/packages/ui-core/src/launchpad/useLaunchMultipleRunsWithTelemetry.ts, js_modules/dagster-ui/packages/ui-core/src/launchpad/useLaunchWithTelemetry.oss.ts, js_modules/dagster-ui/packages/ui-core/src/partitions/BackfillSelector.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/ReexecutionDialog.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/RunTag.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/__tests__/ReexecutionDialog.test.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/__tests__/useJobReExecution.test.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/useJobReExecution.tsx, js_modules/dagster-ui/packages/ui-core/src/ticks/__fixtures__/EvaluateScheduleDialog.fixtures.tsx, js_modules/dagster-ui/packages/ui-core/src/ticks/__fixtures__/SensorDryRunDialog.fixtures.tsx
This is a small change but it applies to:
- Job execution / materialization
- Job backfills
- Asset graph materialization
- Asset graph backfills
- Run re-execution (via extraTags)
- Multiple-run launching
- Evaluating schedules
- Sensor dry runs
Context: https://dagsterlabs.slack.com/archives/C058CBEL230/p1743459307738509
https://linear.app/dagster-labs/issue/FE-828/add-a-tag-that-indicates-that-a-run-was-triggered-by-a-user-via-the-ui
Allows filtering for runs created from the UI:
I manually tested most of the workflows above, and I also made changes to the tests I placed this code very close to the mutations to make sure it's always sent.
[ui] Runs launched from the Dagster UI get a `dagster/from_ui = true` tag, making it easy to filter for them.
=> [ui] Append a dagster/from_ui tag to every run launched from the UI

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster-graphql/dagster_graphql/schema/partition_keys.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
Add paginated partition materializations field on asset node graphql fields.
BK
=> add paginated partition key graphql fields to partitioned asset nodes

examples/docs_snippets/docs_snippets/guides/dg/migrating-definitions/1-tree.txt, examples/docs_snippets/docs_snippets/guides/dg/migrating-definitions/5-tree-after.txt, examples/docs_snippets/docs_snippets/guides/dg/migrating-definitions/6-tree-after-all.txt, examples/docs_snippets/docs_snippets/guides/dg/migrating-project/1-tree.txt, examples/docs_snippets/docs_snippets/guides/dg/scaffolding-project/2-tree.txt
minor nit
if user blindly copies the commands on [this page](https://docs.dagster.io/guides/labs/dg/dagster-definitions#scaffold-an-asset), `tree` prints out parent dir
:eye
=> [dg docs] include cd my-project

examples/docs_snippets/docs_snippets/guides/components/index/19-component-jdbt.yaml, examples/docs_snippets/docs_snippets/guides/components/index/20-project-jdbt-incorrect.yaml, examples/docs_snippets/docs_snippets/guides/components/index/21-dg-component-check-error.txt, examples/docs_snippets/docs_snippets/guides/components/index/22-project-jdbt.yaml, examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/components/test_components_docs.py, python_modules/dagster/dagster/components/resolved/context.py, python_modules/dagster/dagster/components/resolved/core_models.py, python_modules/dagster/dagster/components/utils.py, python_modules/libraries/dagster-dbt/dagster_dbt/components/dbt_project/component.py, python_modules/libraries/dagster-dbt/dagster_dbt/components/dbt_project/scaffolder.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/code_locations/dbt_project_location/defs/jaffle_shop_dbt/component.yaml, python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/code_locations/dependency_on_dbt_project_location/defs/jaffle_shop_dbt/component.yaml, python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/code_locations/templated_custom_keys_dbt_project_location/defs/jaffle_shop_dbt/component.yaml, python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/test_dbt_project_component.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/test_templated_custom_keys_dbt_project.py
Attempt to get a simpler and more python friendly API for this component. 
* Instead of taking the cli resource as `dbt`, we take `DbtProject` as `project` which also now can just be the directory string in simple cases
* `asset_attributes` and `translator` have been replaced with `translation`, which has a yaml schema similar to the previous `translator` arg but can just be a function when defined in python. 
updated existing tests
added tests for pythonic instantiation 
[experiemental][dagster-dbt] `DbtProjectComponent` has been reworked, changing both the python api and the yaml schema. `dbt` has been replaced with `project` with a slightly different schema, and `asset_attributes` with `translation` .
=> rework DbtProjectComponent

python_modules/libraries/dagster-dg/dagster_dg/utils/git.py
Probably a longer-term fix we should make here, but in the short-term, calling logging.debug instead of a particular causes it to lazily initialize the root logger and change the default log level for every logger(!)
dg plus deploy start no longer emits surprising INFO logs
=> Don't use the root logger in get_local_branch_name

js_modules/dagster-ui/packages/dg-docs-components/src/ComponentHeader.tsx, js_modules/dagster-ui/packages/dg-docs-components/src/css/ComponentHeader.module.css
Small tweak to drop in default icon for component docs
=> use default icon for component header

python_modules/dagster/dagster/_core/storage/event_log/base.py
Ths fix in https://github.com/dagster-io/dagster/pull/28113 trades off correctness for performance - failed status on assets is reliably correct now, but single-run backfills may take a lot longer to create runs since they are creating
Until we can make the requisite schema changes to give us the best of both worlds (single event per asset per run, and also correct partition failure calculations) make the default to be slower but correct, with the ability oto opt in if you prefer faster but not always correct.
Ran TestSqliteEventLogStorage with this new env var set to True
=> Add an opt-in env var to re-enable emitting partition subsets from planned events in OSS

docs/vercel.json
Flagged by @mlarose -- looks like some old API docs links redirects are still in place, causing strange behavior with updated API docs links.
Will need to check on staging, since redirects don't work locally.
=> Fix old API docs links redirects

.github/CODEOWNERS
Use @dagster-io/docs instead of @neverett for CODEOWNERS. This way, we can add/remove people from the docs team as needed.
=> Use docs team for CODEOWNERS

js_modules/dagster-ui/packages/ui-core/src/insights/DateRangeText.tsx, js_modules/dagster-ui/packages/ui-core/src/insights/types.tsx
Corresponding internal diff: https://github.com/dagster-io/internal/pull/15118
=> Support hourly insights granularity

python_modules/dagster/tox.ini, python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/commands/ci/__init__.py, python_modules/libraries/dagster-dg/dagster_dg/cli/plus/deploy.py, python_modules/libraries/dagster-dg/dagster_dg/cli/plus/deploy_session.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/plus_tests/test_plus_deploy_command.py, python_modules/libraries/dagster-dg/setup.py, python_modules/libraries/dagster-dg/tox.ini
Calls `dagster-cloud-cli` fns directly rather than shelling out using `uv`, by depending on `dagster-cloud-cli`.
Update tests.
=> [dg deploy] Eliminate process boundary for dg deploy calls to dagster-cloud-cli

python_modules/dagster-test/dagster_test/toys/freshness.py
Short fail window (60s) and warn window (30s) for quicker testing
=> Add a toy asset with internal freshness policy that fails quickly

python_modules/dagster/dagster/components/resolved/base.py, python_modules/dagster/dagster_tests/components_tests/resolution_tests/test_field_utilites.py
This prevents the `__DAGSTER_UNSET_DEFAULT__` thing from showing up all over the docs, I believe. Also good for tooling in general, as it makes the default values get represented in the json schema where possible.
Sometimes, the default value will not be serializble (e.g. it's a default factory or a complex object type), and then we fall back to the unsightly string
NOCHANGELOG
=> [resolved] Propagate default value to inner ResolvableModel schema when possible

python_modules/libraries/dagster-dg/dagster_dg/cli/plus/deploy.py, python_modules/libraries/dagster-dg/dagster_dg/cli/plus/deploy_session.py, python_modules/libraries/dagster-dg/dagster_dg/cli/utils.py, python_modules/libraries/dagster-dg/dagster_dg/config.py, python_modules/libraries/dagster-dg/dagster_dg/context.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/plus_tests/test_plus_deploy_command.py, python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Summary:
- each command can now be run in either a workspace or project context. if you run in a workspace context you can pass in a list of location names to filter it down to specific projects.
- workspace-level defaults for the build.yaml file
=> Allow dg deploy to run in a workspace or project context

js_modules/dagster-ui/packages/ui-components/src/components/Skeleton.module.css, js_modules/dagster-ui/packages/ui-components/src/components/Skeleton.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNode.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNode2025.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetActionMenu.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetCatalogTableV2.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetCatalogV2VirtualizedTable.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetHealthSummary.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetRecentUpdatesTrend.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetsCatalogTable.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/Stale.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/useAssetDefinition.ts, js_modules/dagster-ui/packages/ui-core/src/insights/InsightsIcon.tsx, js_modules/dagster-ui/packages/ui-core/src/ui/IndeterminateLoadingBar.module.css, js_modules/dagster-ui/packages/ui-core/src/ui/IndeterminateLoadingBar.tsx
1. Update asset health cards with new copy from https://www.figma.com/design/wXU4we6PavPVZt5dHZNQkY/Dagster-Observe---2025?node-id=1483-16917&m=dev
2. Fix flickering due to re-entering loading state temporarily
3. Use a css module + define keyframes once for skeleton component
4. Bunch of design nits.
=> [Catalogv2] Update asset health summary cards + fix flickering + skeleton perf + css

examples/docs_snippets/docs_snippets/guides/dg/scaffolding-project/1-scaffolding-project.txt, examples/docs_snippets/docs_snippets/guides/dg/scaffolding-project/2-tree.txt, examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/dg/test_scaffolding_project.py, python_modules/libraries/dagster-dg/dagster_dg/cli/init.py, python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_init_command.py, python_modules/libraries/dagster-shared/dagster_shared/check/__init__.py, python_modules/libraries/dagster-shared/dagster_shared/check/functions.py, python_modules/libraries/dagster-shared/dagster_shared_tests/test_check.py
Make `dg init` prompt to create a venv in the created project after it runs:
```
$ dg init my-project --use-editable-dagster
Creating a Dagster project at /Users/smackesey/stm/code/elementl/tmp/my-project.
Scaffolded files for Dagster project at /Users/smackesey/stm/code/elementl/tmp/my-project.
Run `uv sync` to bootstrap a uv.lock and virtual environment (y/n)? [y]: 
... venv creation
uv.lock and virtual environment created.
Your project is configured with `project.python_environment = "active"`, so you will need to activate the created virtual environment to use it with your `dg` project. To activate the virtual environment, run:
source my-project/.venv/bin/activate
```
This prompt only appears if:
- the `--python-environment` option is set to `active` (the default) (in `uv_managed` …
=> [dg] Prompt to create venv when running dg init

examples/docs_snippets/docs_snippets/guides/components/index/1-help.txt, python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py, python_modules/libraries/dagster-dg/dagster_dg/cli/check.py, python_modules/libraries/dagster-dg/dagster_dg/cli/dev.py, python_modules/libraries/dagster-dg/dagster_dg/cli/docs.py, python_modules/libraries/dagster-dg/dagster_dg/cli/launch.py, python_modules/libraries/dagster-dg/dagster_dg/cli/list.py, python_modules/libraries/dagster-dg/dagster_dg/cli/plus/__init__.py, python_modules/libraries/dagster-dg/dagster_dg/cli/plus/deploy.py, python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py, python_modules/libraries/dagster-dg/dagster_dg/cli/shared_options.py, python_modules/libraries/dagster-dg/dagster_dg/cli/utils.py
Summary:
This is for the github action, which may want to, say, run dg deploy commands in a different folder than the current cwd without needing to pushd or gross workarounds like that.
Test Plan: BK gives us coverage that the right path is being passed in
=> Allow sourcing root path from cli input instead of assuming Path.cwd()

python_modules/libraries/dagster-dg/dagster_dg/cli/plus/deploy_session.py, python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py, python_modules/libraries/dagster-dg/dagster_dg/templates/build-location-fragment.yaml, python_modules/libraries/dagster-dg/dagster_dg/templates/hybrid-github-action.yaml, python_modules/libraries/dagster-dg/dagster_dg/templates/registry_fragments/azure-container-registry-login-fragment.yaml, python_modules/libraries/dagster-dg/dagster_dg/templates/registry_fragments/dockerhub-login-fragment.yaml, python_modules/libraries/dagster-dg/dagster_dg/templates/registry_fragments/ecr-login-fragment.yaml, python_modules/libraries/dagster-dg/dagster_dg/templates/registry_fragments/gcr-login-fragment.yaml, python_modules/libraries/dagster-dg/dagster_dg/templates/registry_fragments/github-container-registry-login-fragment.yaml, python_modules/libraries/dagster-dg/dagster_dg/templates/serverless-github-action.yaml, python_modules/libraries/dagster-dg/dagster_dg/utils/plus/build.py, python_modules/libraries/dagster-dg/dagster_dg/utils/plus/gql.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/plus_tests/test_scaffold_github_actions_command.py
Stacks on #28962. Implements `dg scaffold github-action` for hybrid orgs.
`dg scaffold github-action` queries Plus to figure out which agent type is in use, and scaffolds the corresponding GitHub actions file. It looks for a `regsitry.yaml` file to determine which registry type to log in to, and scaffolds a build step and dockerfile (if one doesn't yet exist) for each location.
Mocked unit tests.
=> [dg] Add `dg scaffold github-action` command support for hybrid orgs

python_modules/dagster/dagster/_core/execution/plan/compute.py, python_modules/dagster/dagster_tests/execution_tests/misc_execution_tests/test_require_typed_event_stream.py
Fixes: https://github.com/dagster-io/dagster/issues/26244
The core issue is that the original code was not filtering down the expected output names to the ones that were actually selected for computation.
This system in general is likely long-overdue for a rework, but this is a minimal change that gets to the heart of the issue.
unit
Fixed a bug that would multi-assets defined with `can_subset=True` to error when using `dagster-pipes` if not all outputs were emitted.
=> [pipes] Fix issue with pipes and subsettable multi assets

python_modules/libraries/dagster-dg/dagster_dg/config.py, python_modules/libraries/dagster-dg/dagster_dg/context.py, python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py, python_modules/libraries/dagster-dg/dagster_dg/utils/warnings.py, python_modules/libraries/dagster-dg/dagster_dg_tests/test_context.py, python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Add an API for suppressing warnings. Each warning we emit gets a string id. There is a new setting `cli.suppress_warnings` that takes a list of these ids, and will suppress these warnings.
Warnings are echoed directly to stderr by `click`, styled in yellow, and do not go through Python's `warnings.warn`. All warnings messages have a trailer that explains how to suppress them. Example:
New unit tests
A new `dg` setting `cli.suppress_warnings` available. This takes a list of warning types to suppress.
=> [dg] Add warning suppression API

examples/docs_snippets/tox.ini, python_modules/libraries/dagster-dg/dagster_dg/cli/plus/deploy.py, python_modules/libraries/dagster-dg/dagster_dg/cli/plus/deploy_session.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/plus_tests/test_plus_deploy_command.py, python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Summary:
These args in the github action and just needed to be passed through.
=> Add missing args to dg plus deploy and dg plus deploy start for parity with dagster-cloud ci init

js_modules/dagster-ui/packages/ui-core/client.json, js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetHealthDataProvider.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-data/types/AssetHealthDataProvider.types.ts, js_modules/dagster-ui/packages/ui-core/src/assets/AssetHealthSummary.tsx
didn't notice this in the other PR, but we are using the number of missing partitions when the asset is in the failed state. in this case we want to report on the number of failed partitions
=> [ui] [asset health] fix helper text for failed partitions

python_modules/dagster/dagster/_core/execution/plan/compute.py, python_modules/dagster/dagster/_core/execution/plan/outputs.py, python_modules/dagster/dagster_tests/core_tests/snap_tests/__snapshots__/test_execution_plan.ambr
Adds the execution type for each asset in a run to the step output properties so that we can use it in https://github.com/dagster-io/internal/pull/15127
=> add asset execution type to step output properties

js_modules/dagster-ui/packages/ui-core/src/assets/AssetHealthSummary.tsx
Fixes two things found while dogfooding
Now there is a space between `checks` and `failed`
when partitions are missing from an asset, the label text is "Missing partitions" rather than "No materializations" and updates the triangle warning icon to be the line version, not the filled version
👀
=> [ui] asset health copy updates

python_modules/libraries/dagster-dg/dagster_dg/cli/entrypoint.py
Summary:
This allows pex files to run e.g.
dagster-cloud.pex -m dagster_dg.cli.entrypoint
To invoke the CLI. Mimics similar functionality in dagster-cloud-cli
=> Add an entrypoint.py to dagster_dg.cli

python_modules/libraries/dagster-dg/dagster_dg/config.py
Removed the `code_location_name` field from `DgWorkspaceProjectSpec`. This was a dead param not being used anywhere (code location name is sourced from the project config itself when creating a workspace.yaml)
=> [dg] Remove code_location_name from DgWorkspaceProjectSpec (BUILD-969)

js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetHealthDataProvider.tsx
External assets when requested do not get included in the response by the assetNodes resolver, so as a workaround lets just include them manually on the frontend but with a null assetHealth object so that they get classified as "Unknown"
Saw the external assets in the unknown section
=> [CatalogV2] Include external assets in asset health result to fix infinite loading + skip health query if feature flag disabled

python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/sensor_builder.py, python_modules/libraries/dagster-dbt/dagster_dbt/utils.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/conftest.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_sensor.py
Fix name format for the dbt Cloud polling sensor
Before:
```bash
2025-04-16 17:10:04 -0400 - dagster.code_server - ERROR - dagster._core.errors.DagsterInvalidDefinitionError: "Dagster Labs_Analytics_test__run_status_sensor" is not a valid name in Dagster. Names must be in regex ^[A-Za-z0-9_]+$.
Stack Trace:
[8 dagster system frames hidden, run with --verbose to see the full stack trace]
File "/Users/maximearmstrong/Documents/Repositories/dagster-io/dagster/examples/test/definitions.py", line 31, in <module>
sensors=[build_dbt_cloud_polling_sensor(workspace=workspace)],
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[7 dagster system frames hidden]
```
BK
=> [dagster-dbt] Clean name for dbt Cloud polling sensor

examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/dg/test_migrating_project/test_migrating_project.py, python_modules/dagster/dagster/components/core/context.py, python_modules/dagster/dagster/components/core/load_defs.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/component_loader.py, python_modules/dagster/dagster_tests/components_tests/resolution_tests/test_custom_scope.py, python_modules/dagster/dagster_tests/components_tests/unit_tests/test_pipes_subprocess_script_collection.py
Manually tested.
```python
from dagster.components import Component, ComponentLoadContext, Model, Resolvable
class TakesStringComponent(Component, Model, Resolvable):
value: str
def build_defs(self, context: ComponentLoadContext) -> dg.Definitions:
print("**********")
print(self.value)
print("**********")
return dg.Definitions()
```
and then
```yaml
type: project_path_test.lib.TakesStringComponent
attributes:
value: "{{project_root}}"
```
NOCHANGELOG
=> [dg] Thread project path into ComponentLoadContext

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNode.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNode2025.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNodeHealthRow.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/__tests__/AssetNode.test.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetHealthSummary.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/AssetChecksStatusSummary.tsx
This PR updates the "status bar" at the bottom of asset nodes, and the coloring that is displayed on them when you zoom out, to reflect the new Observe UI "health" concept.
This feature flag may be used in tandem with the new faceted asset node designs, but both feature flags can also be used independently. Having four different possible cases makes the code a bit dense, but we'll clean it up when the feature flags go GA! 
Because the asset nodes include other elements from live data (the last event, asset check statuses, stale and change reason tags, etc), the nodes use BOTH `useAssetLiveData` and `useAssetHealthData` when the observe UI is enabled. I think this is nice but the data does load at separate times. So far it doesn't seem like an issue.
I tested this against dogfood in all …
=> [ui] Update asset nodes to reflect the observe UI feature flag

python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/conftest.py, python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
`dg scaffold --help` has been quite slow, we end up defining the subcommands repeatedly, which calls out to the `dagster-components` CLI. Turns out we have a cache here and just never set it as complete.
Before:
```sh
dg scaffold --help
Usage: dg scaffold [OPTIONS] COMMAND [ARGS]...                                                                                                                                                                                                                                                                                                                                                                                          
Commands for scaffolding Dagster code. …
```
=> [dg] Properly cache dg scaffold subcommands, making --help faster

.github/workflows/automate-stale-issues.yml
Recreation of https://github.com/dagster-io/dagster/pull/20588
Closes DR-1008.
The Dagster repository has accumulated many issues and pull requests that are likely no longer relevant or actively being worked on. This Github action automates the process of marking issues and pull requests as "stale", and closing them after a certain period of time after that staleness marker has been applied. Overall, the following automations will occur:
- `stale` label is added to issues and pull requests after 365 days of inactivity
- `stale` issue or PR is closed after 30 days of inactivity after being marked (365 + 30 days total inactivity)
- Remove stale label and restart timer if an update/comment occurs
NOCHANGELOG
=> Automatically marks inactive PRs / issues as stale and close

python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py, python_modules/libraries/dagster-dg/dagster_dg/cli/utils.py, python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_utils_inspect_command.py
Changes the error message when you run `dg scaffold nonexistent.object` to refer to "plugin object" instead of "component", this is more accurate.
Changed existing unit tests.
=> [dg] Improve missing object error message for `dg scaffold` (BUILD-988)

python_modules/libraries/dagster-dg/dagster_dg/cli/plus/deploy_session.py, python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py, python_modules/libraries/dagster-dg/dagster_dg/config.py, python_modules/libraries/dagster-dg/dagster_dg/utils/plus/build.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/plus_tests/test_plus_deploy_command.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/plus_tests/test_scaffold_plus_commands.py
Adds a dg command to scaffold a Dockerfile for building a dg project.
`dg scaffold github-actions` now relies on having a Dockerfile in the serverless context.
New unit test, update hybrid actions tests.
=> Add dg scaffold build-artifacts

python_modules/dagster/dagster/_cli/instance.py
this ends up bringing sqlalchemy on cli init when its not needed
`python -X importtime -m dagster.components.cli &> /tmp/import_time.txt && tuna /tmp/import_time.txt`
=> defer import for bigint migration

Makefile
We added dagster-cloud-cli as a dependency but did not update this makefile command
Scaffolded new project. Was able to run `dg`
NOCHANGELOG
=> [dg] Update install_editable_uv_tools with dagster-cloud-cli

python_modules/libraries/dagster-dg/dagster_dg/cli/init.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_init_command.py
Added a warning message when users choose not to run `uv sync` (or when there is a pre-existing venv) during project initialization. This message informs users that they need to manually install their project package using either `uv sync` or `pip install --editable .` before running `dg` commands against their project.
Updated the existing test case to verify that the warning message appears when the `--use-preexisting-venv` flag is used.
Added a warning message to inform users they need to install their project package when skipping automatic environment setup.
=> [dg] Add warning if using pip or not using uv sync

js_modules/dagster-ui/packages/ui-core/src/assets/AssetEvents.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/usePaginatedAssetEvents.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/useRecentAssetEvents.tsx
We have quite a bit of complicated front-end code to group recent asset events by partition.  This code only gets exercised when we're viewing an asset page for an asset whose definition has been removed from the workspace.
I posit that this view is rarely used.  The asset page itself is extremely buried - it doesn't show up in the assets view.  You have to dig it out from a historical run view.
The by-partition implementation also needs to be qualified.  This isn't fetching all events by partition.  It's fetching the last 100 events and then grouping them by partition key IF there is even a partition key on the materializations to be grouped by.
If we actually want to support this view, we could probably implement it by creating some new, different resolvers.  We could fetch all unique …
=> remove partition view on asset events for non-sda assets

python_modules/dagster/dagster/_core/code_pointer.py, python_modules/dagster/dagster_tests/components_tests/utils.py, python_modules/libraries/dagster-dbt/dagster_dbt/cli/app.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/test_dbt_project_component.py, python_modules/libraries/dagster-dbt/tox.ini, python_modules/libraries/dagster-shared/dagster_shared/seven/__init__.py
add a flag to process all `DbtProjectComponent` in the target project directory
part of #28546
added test
[dagster-dbt] the `dagster-dbt project prepare-and-package` cli now supports `--components` for handling `DbtProjectComponent`
=> [dagster-dbt cli] add ability to target components

python_modules/libraries/dagster-dg/dagster_dg/cli/list.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py
Currently you get a kind of odd empty table if there are no defs:
```
No definitions are defined for this project.
┏━━━━━━━━━┳━━━━━━━━━━━━━┓
┃ Section ┃ Definitions ┃
┡━━━━━━━━━╇━━━━━━━━━━━━━┩
└─────────┴─────────────┘
```
This PR drops the table:
```
No definitions are defined for this project.
```
Changed existing test
=> [dg] Don't show empty table when no definitions for list defs (BUILD-1016)

python_modules/dagster/dagster/_core/definitions/asset_selection.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection.py
Selection syntax in the UI passes strings of format `repo@code_location`. Let's make the python implementation handle that. This fixes asset selection issues in the new insights view.
BK
NOCHANGELOG
=> Fix asset selection by code location

python_modules/dagster/dagster/components/resolved/core_models.py, python_modules/dagster/dagster_tests/components_tests/resolution_tests/test_resolved.py, python_modules/dagster/dagster_tests/components_tests/unit_tests/test_spec_processing.py
we set `model_field_type` to the underlying model instead of the `Resolvable` derived one which has the actual strict validation for asset attributes
added test that was previously failing
=> [components] fix AssetPostProcessor

python_modules/libraries/dagster-dg/dagster_dg/cli/list.py
`dg list defs` fails the user (or a tool that the load defs pathway invokes) emits anything to stdout while loading defintiions. See [issue](https://linear.app/dagster-labs/issue/BUILD-1027/dg-list-defs-not-resilient-to-anyone-printing-to-stdour-during-project)
Manual on project that prints out string when it loads + BK
NOCHANGELOG
=> [dg] Temporary fix to make list defs more robust

python_modules/libraries/dagster-k8s/dagster_k8s/client.py, python_modules/libraries/dagster-k8s/dagster_k8s/pipes.py, python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_client.py
Right now if there's a failure after a long pod run it writes out the full output. Return the last N lines instead.
Also remove a confusing comment that I suspect was copy-pasted incorrectly from elsewhere.
Existing pipes integration tests include an error case (verify, inspect output)
[dagster-k8s] K8sPipeClient failures will now include the last 100 lines of the logs of the pod that failed, instead of the full log output.
=> Only show last N lines in pipes pod failure logs

python_modules/libraries/dagster-dg/dagster_dg/context.py, python_modules/libraries/dagster-dg/dagster_dg_tests/test_context.py, python_modules/libraries/dagster-dg/setup.py
This enables reading entry points in `dagster-dg` from `setup.cfg` (as opposed to `pyproject.toml`). This is necessary for projects that use `setup.py` rather than `pyproject.toml`. We read from `setup.cfg` instead of `setup.py` because there is no reliable way to read `setup.py` (since it's arbitrary Python code).
New unit test.
=> [dg] Add setup.cfg support for reading entry points (BUILD-1034)

examples/docs_snippets/docs_snippets/guides/components/index/1-help.txt, python_modules/libraries/dagster-dg/dagster_dg/cache.py, python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py, python_modules/libraries/dagster-dg/dagster_dg/component.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_environment_validation.py, python_modules/libraries/dagster-dg/dagster_dg_tests/test_cache.py, python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
"Component registry" is an old name. This is a one-off "action option" (`dg --rebuild-component-registry`)-- it is highly unlikely anyone was programming against this API, so I did not implement backcompat for this.
`dg --rebuild-component-registry` has been renamed to `dg --rebuild-plugin-cache`.
=> [dg] Rename --rebuild-component-registry to --rebuild-plugin-cache (BUILD-1023)

examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/components/test_components_docs.py, examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/components/test_components_docs_creating_a_component.py, examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/components/utils.py, examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/dg/test_dagster_definitions.py, examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/dg/test_migrating_project/test_migrating_project.py, python_modules/libraries/dagster-dg/dagster_dg/component.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_custom_help_format.py, python_modules/libraries/dagster-dg/dagster_dg_tests/test_cache.py
This adds a message whenever the cache is being rebuilt. It is more user-friendly than our existing cache log messages, which only show up in `--verbose` mode anyway.
=> [dg] Print a message when rebuilding the plugin object cache (BUILD-1005)

js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetLiveDataProvider.tsx
https://github.com/dagster-io/dagster/pull/16290 added logic to observe the latest run for asset checks but causes an issue where we observe  runs regardless of whether they're inprogress. To do that we open a websocket connection for every unique run id of every asset check of every visible asset. I believe the intention was to only observe runs that are in progress but currently we have no way of knowing that for asset checks and end up observing the latest run regardless of its state.
There are no existing jest tests for this... I can look into that if we want to re-enable this behavior.
=> Remove asset check run observations

python_modules/dagster/dagster_tests/components_tests/cli_tests/test_commands.py, python_modules/libraries/dagster-dg/dagster_dg/cli/list.py, python_modules/libraries/dagster-dg/dagster_dg/component.py, python_modules/libraries/dagster-dg/dagster_dg/config.py, python_modules/libraries/dagster-shared/dagster_shared/match.py, python_modules/libraries/dagster-shared/dagster_shared/serdes/objects/definition_metadata.py, python_modules/libraries/dagster-shared/dagster_shared/serdes/serdes.py, python_modules/libraries/dagster-shared/dagster_shared_tests/test_match.py
- Moves `match_type` utility function from `dagster-dg` to `dagster-shared`
- Use this in `deserialize_value`
This permits stuff like:
```
deserialize_value(val, list[SomeSerdesType])
```
Where previously you needed to do `check.is_list(deserialize_value(val), of_type=SomeSerdesType)`. The new form will throw a `DeserializationError` instead of a check error.
This was motivated by the desire to detect deserialization errors in dg when loading the cache so that we can gracefully ignore them and refetch: https://github.com/dagster-io/dagster/pull/29434
=> Allow deserialize_value to take generic type

js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx
We got a report that the materialize button on the asset page was materializing a previously visited page. This suggests that we're reusing the <LaunchAssetExecutionButton/> in the page header and likely other elements on the page. To prevent this issue lets set a key so that we don't re-use the component instance.
=> Wrap AssetView with key

python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
Summary:
If you have N different build_fivetran_assets_definitions calls, we call this N times on the workspace, even though the underlying data hasn't changed.  Since the underlying data does not change, only call it once.
[dagster-fivetran] Performance improvements for code locations with multiple calls to build_fivetran_assets_definitions.
=> Add memoization to fetch_fivetran_workspace_data

examples/docs_snippets/docs_snippets/guides/components/index/34-dg-component-check-defs.txt, python_modules/libraries/dagster-dg/dagster_dg/cache.py, python_modules/libraries/dagster-dg/dagster_dg/cli/check.py, python_modules/libraries/dagster-dg/dagster_dg/context.py, python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py
`dagster-dg` currently uses a crude logging system where we conditionally `print()` if `verbose` is set.
This PR transitions the system to use loggers, setting us up for more controlled logging output. There's no behavior change, the loggers are currently configured to just print to stdout and not propagate.
This is laying the groundwork for further changes discussed here: https://www.notion.so/dagster/Logging-in-dg-1d918b92e462800aa05efda464ba2315?pvs=4
Existing test suite (which checks for logging output)
=> [dg] Add loggers to dg

python_modules/dagster/dagster/_core/definitions/asset_graph.py, python_modules/dagster/dagster/_core/definitions/asset_job.py, python_modules/dagster/dagster/_core/definitions/job_definition.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_job.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py
I believe this restores the originally-intended behavior of these codepaths, although it's been like 4 years since I've looked at this.
Regardless, this allows the system to have more flexibility when generating a JobDefinition for a subset (asset selection) of an existing JobDefinition.
Previously, we would use the job-scoped AssetGraph from the parent job, which meant that any multi-assets which were cleaved within that parent job would remain as separate ops in the child job.
Now, when we create a job-scoped AssetGraph, we retain a reference to the original global asset graph, which allows us to access that at the appropriate time.
This means that creating a subset job from an existing job will result in an identical job structure to just creating that job directly on the Definitions …
=> [BCOR-56] Make multi_assets recombine when possible

python_modules/dagster/dagster/_core/execution/plan/resume_retry.py, python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster/_core/remote_representation/external.py, python_modules/dagster/dagster/_core/storage/tags.py, python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance_reexecution.py
This adds in a new `FROM_ASSET_FAILURE` re-execution option. Its functionality is quite simple, just:
- compute the set of unexecuted asset keys and asset check keys from the parent run
- create a new run request that is a subset of the original job targeting just those selected assets and checks
This causes a brand new job snapshot / execution plan to be created, allowing the asset job construction machinery to be re-invoked to satisfy the new request.
Currently, there is no do this from the UI.
Added unit tests, also tested locally.
NOCHANGELOG
=> [BCOR-54] Add `FROM_ASSET_FAILURE` re-execution option

python_modules/dagster/dagster/components/resolved/base.py, python_modules/dagster/dagster/components/resolved/core_models.py, python_modules/dagster/dagster/components/resolved/model.py, python_modules/dagster/dagster_tests/components_tests/resolution_tests/test_resolved.py
These got dropped in the Resolved v2 changes. 
Bring them back by adding arguments to `Resolver` to use on non-pydantic `Resolvable` classes.
[components] descriptions and examples have been restored for core models such as `ResolvedAssetSpec`. `description` and `examples` arguments have been added to `Resolver` for documenting fields on non-pydantic model based `Resolvable` classes.
=> [components] bring back field docs for core models

js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetHealthDataProvider.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetLiveDataProvider.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphSupplementaryData.oss.tsx
Also add some memoization because in `useAssetGraphSupplementaryData` because the reference seems to be changing more often than necessary... stopgap for now.
app proxy load the app and see that the catalog home page no longer makes AssetGraphLiveQuery calls.
=> Stop fetching asset graph live query from asset health hook

.buildkite/dagster-buildkite/dagster_buildkite/step_builder.py
We are not including the BUILDKITE_BUILD_URL in the code to create a buildkite step. So instead of seeing:
we see 
[
](url)
in the BuildKite test page.
By making this change, we now explicitly add the environment variable to the list of variables included in the command.
Locally tested by running and confirming the output included the environment variable in the yaml file
`BUILDKITE_DOCKER_QUEUE=test BUILDKITE_BRANCH=test BUILDKITE_MEDIUM_QUEUE=test BUILDKITE_COMMIT=test BUILDKITE_MESSAGE=test  dagster-buildkite`
I will also check the BuildKite run for this PR to see if the url is now included
=> Add BUILDKITE_BUILD_URL environment variable to buildkite step builder

python_modules/dagster/dagster/components/cli/list.py, python_modules/libraries/dagster-dg/dagster_dg/cli/list.py, python_modules/libraries/dagster-dg/dagster_dg/cli/utils.py, python_modules/libraries/dagster-dg/dagster_dg/context.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py, python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py, python_modules/libraries/dagster-shared/dagster_shared/ipc.py, python_modules/libraries/dagster-shared/dagster_shared/libraries/__init__.py
This makes `dg list defs` use a tempfile for its channel instead of stdout. This makes it robust to other output being printed to stdout during code location definitions loading, which could otherwise pollute the JSON stream read by `dg`.
New unit tests (that also pass on windows, where non-stdio IPC is always a concern)
Fixed a bug where `dg list defs` would crash if anything was written to stdout while loading a project's definitions.
=> [dg] Make dg list defs use a tempfile channel (BUILD-1027)

js_modules/dagster-ui/packages/dg-docs-site/.next/trace, python_modules/libraries/dagster-dg/dagster_dg/cli/utils.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_configure_editor_commands.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_environment_validation.py
Adds a command to generate a JSON schema for a given code location. Drops the schema in the location referenced by the VS Code extension, so this can be used to update the schema without the other rigamarole involved with that command.
```sh
dg code-location generate-component-schema --output-file foo.json
```
When #27863 lands, I intend to add a `--watch` flag to this command as well, so you can live-update the schema if the set of components changes.
Brief test, the underlying `dagster-components` CLI tests correctness.
=> [dagster-dg] Add separate command to generate JSON schema for code location

examples/docs_snippets/docs_snippets/guides/components/index/19-dg-list-plugins.txt, examples/docs_snippets/docs_snippets/guides/components/index/28-dg-list-plugins.txt, examples/docs_snippets/docs_snippets/guides/components/index/7-dg-list-plugins.txt, examples/docs_snippets/docs_snippets/guides/components/index/9-dg-list-plugins.txt, examples/docs_snippets/docs_snippets/guides/components/shell-script-component/3-dg-list-plugins.txt, examples/docs_snippets/docs_snippets/guides/dg/migrating-project/10-list-plugins.txt, python_modules/dagster/dagster/components/components.py, python_modules/dagster/dagster/components/lib/shim_components/multi_asset.py, python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
Adds a new shim type for `dagster.multi_asset`. Also does some surgery on the scaffold param generation to turn `list` inputs into `multi=True` click arguments, so the user can pass multiple individual options rather than a single list.
```sh
$ dg scaffold dagster.multi_asset assets/my_multi_asset.py
```
```python
@dg.multi_asset(
specs=[
dg.AssetSpec(key=dg.AssetKey(["my_multi_asset", "first_asset"]),
dg.AssetSpec(key=dg.AssetKey(["my_multi_asset", "second_asset"]),
]
)
def my_multi_asset(context: dg.AssetExecutionContext): ...
```
```sh
$ dg scaffold dagster.multi_asset assets/my_multi_asset.py --asset-key key_one --asset-key key_two
```
```python
@dg.multi_asset(
specs=[
dg.AssetSpec(key=dg.AssetKey(["key_one"]), …
```
=> [dg scaffold] Add multi_asset shim

python_modules/libraries/dagster-dg/dagster_dg/context.py, python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_environment_validation.py
Adds a user-facing hint when a dg command is run in a directory not matching the current required type (project/workspace), if a parent or immediate child dir does match the required type:
```sh
$ dg scaffold github-actions
Using /Users/ben/.pyenv/versions/dagster/bin/dagster-components
This command must be run inside a Dagster workspace or project directory. Ensure that the nearest pyproject.toml has `tool.dg.directory_type = "project"` or `tool.dg.directory_type = "workspace"` set.
You may have wanted to run this command in the following directory:
- /Users/ben/repos/april-seventeenth-test/april-seventeenth
```
Test cases.
=> [dg] User hints for project/workspace validation

js_modules/dagster-ui/packages/dg-docs-components/package.json, js_modules/dagster-ui/packages/dg-docs-components/src/ComponentHeader.tsx, js_modules/dagster-ui/packages/dg-docs-components/src/ComponentSchema.tsx, js_modules/dagster-ui/packages/dg-docs-components/src/css/PackagePageDetails.module.css, js_modules/dagster-ui/packages/dg-docs-site/package.json, js_modules/dagster-ui/yarn.lock
This PR makes a couple drive-by changes:
- The positioning of the content anchoring icon no longer changes as you switch between the list and detail pages of docs. I used a bit of a non-standard padding value but it's a lot less jarring I think?
- The descriptions use the first text block of the parsed markdown, not the first line of the unparsed markdown, which fixes 
- There was a remaining reference to a prop called ref, and it needed to be $ref to avoid a React deprecation crash.
=> [ui] Fix dg-docs error on some schemas, visual nits

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_partition_subsets.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_health.py
Moves the asset health computations to `asset_health.py` instead of in `asset_graph.py` with the other assetNode resolvers. This makes it more organized (all asset health related GQL stuff is in one file) and makes it so that you can query for just the freshness status and not have to recompute all other statuses.
no logic changes, just moving code
existing tests
=> refactor asset health computations

marketplace/scripts/generate.ts, marketplace/scripts/types.ts
- `layout` has been removed, so we now filter integrations on if they are not `index.md` files
- Adds the `pypi` and `source` meta fields
- Updates `excerpt` to be `description`
- Built-by has been removed and replaced by `tags: ['dagster-supported']` or `tags: ['community-supported']`
`yarn generate && yarn start`
NOCHANGELOG
=> [marketplace] fix generate; add pypi and source

python_modules/dagster/dagster_tests/cli_tests/command_tests/dagster_dev_command_tests/test_dagster_dev_command.py
`test_dagster_dev_command_grpc_port` was using my persistent DAGSTER_HOME on local and kept picking up queued runs from previous runs of this test; then throwing spurious errors in the command log. Confused me to no end.
Fix by setting DAGSTER_HOME to the created tempdir.
Test still passes, this time without the errors about "can't find code location" referencing the previous run's code location.
=> Fix dev test inconsistency

python_modules/dagster/dagster/components/resolved/core_models.py, python_modules/dagster/dagster/components/utils.py, python_modules/dagster/dagster_tests/components_tests/unit_tests/test_spec_processing.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/test_dbt_project_component.py, python_modules/libraries/dagster-sling/dagster_sling_tests/test_sling_replication_collection_component.py
Currently we just have `AssetAttributes` which we use to power both `Definitions` post processing as well as pre-definitions `AssetSpec` customization. 
Unfortunately, these two context have different constraints. We do not support changing the key of an asset spec inside of an already formed `AssetsDefinition` as its difficult to ensure it could safely handle that transformation in all cases. 
This change separates the two cases, and adds `key_prefix` for the spec only update condition. 
added tests
=> [resolved] split asset defs update and asset spec update handling

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNode2025.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNodeFreshnessRow.tsx
This is a small update that improves support for "Freshness Policy" on the new faceted asset nodes.
This row supports the old freshness policy concept all the time, and the new one if the `Observe UI` feature flag is enabled and a new freshness policy is present. (It's valid to have Observe UI turned on and an old style freshness policy)
Example of an asset with an old freshness policy:
Example of an asset with a new freshness policy and the Observe UI feature enabled:
I verified these on live assets and also in the storybook
=> [ui] Support new freshness row on faceted asset nodes

examples/docs_snippets/docs_snippets/guides/dg/migrating-definitions/1-tree.txt, examples/docs_snippets/docs_snippets/guides/dg/migrating-definitions/5-tree-after.txt, examples/docs_snippets/docs_snippets/guides/dg/migrating-definitions/6-tree-after-all.txt, examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/dg/test_migrating_definitions/test_migrating_definitions.py, python_modules/dagster/dagster/components/cli/list.py, python_modules/dagster/dagster/components/core/package_entry.py, python_modules/dagster/dagster_tests/components_tests/cli_tests/test_commands.py, python_modules/dagster/dagster_tests/components_tests/registry_tests/test_registry.py, python_modules/libraries/dagster-dg/dagster_dg/cache.py, python_modules/libraries/dagster-dg/dagster_dg/cli/list.py, python_modules/libraries/dagster-dg/dagster_dg/component.py, python_modules/libraries/dagster-dg/dagster_dg/context.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py, python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py, python_modules/libraries/dagster-shared/dagster_shared/serdes/objects/package_entry.py
- Change `dagster-components list library` -> `list plugins`. This should have been done when the `dg` command was converted.
- The output format has been changed. `list libraries` outputs a `list[PluginObjectSnap]`. `list plugins` outputs a `PluginManifest`. The `PluginManifest` contains a `list[PluginObjectSnap]` but also a list of all modules scanned. This means it contains information about which plugins were scanned but contained no objects. This is useful to detect the situation where a project declares an entry point but it isn't registered (see [upstack](https://github.com/dagster-io/dagster/pull/29514)).
- `dg` will detect when it's dealing with a version with `list plugins` or `list libraries` and call the appropriate command. It also normalizes the differing output formats to …
=> [dg] Update dg list plugin IPC

python_modules/libraries/dagster-dg/dagster_dg/component.py, python_modules/libraries/dagster-dg/dagster_dg/utils/warnings.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_custom_help_format.py, python_modules/libraries/dagster-dg/dagster_dg_tests/test_context.py, python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Emit a warning when a project defines a `dagster_dg.plugin` entry point, but the targeted module is not present in the `PluginManifest` retrieved via `dagster-components list plugins`. This can help users avoid the frustrating situation where they've defined an entry point but their custom components aren't showing up. The warning is:
```
Your package defines a `dagster_dg.plugin` entry point, but this module was not
found in the plugin manifest for the current environment. This means either that
your project is not installed in the current environment, or that the entry point
metadata was added after your module was installed. Python entry points are
registered at package install time. Please reinstall your package into the current
environment to ensure the entry point is registered. …
```
=> [dg] Warn when package defines entry point but its missing from manifest (BUILD-1030)

python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_internal_freshness.py, python_modules/dagster/dagster/_core/instance/__init__.py
Adds a new dagster instance property `internal_asset_freshness_enabled` to allow gating freshness policy gql apis.
Relies on https://github.com/dagster-io/internal/pull/15253
=> Gate internal freshness policy gql

python_modules/libraries/dagster-datadog/dagster_datadog/resources.py, python_modules/libraries/dagster-datadog/dagster_datadog_tests/test_resources.py
When sending metric data points at the end of a pipeline, sometimes the buffer won't have the time to flush before termination.
- added methods to test suite
- [dagster-datadog] exposes flush and wait_for_pending dogstatsd methods
=> [dagster-datadog] exposes flush and wait_for_pending dogstatsd methods

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/check_operators.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/serialized_objects.py, python_modules/dagster/dagster_tests/declarative_automation_tests/automation_condition_tests/builtins/test_eager_condition.py
This will be used to provide the UI with more semantic information about how a given condition works.
To start, we'll use this to help determine the collapsed state of each node in the evaluation tree, but we may also end up using this for other parts of the rendering to make it more obvious how results are being combined together.
NOCHANGELOG
=> Add `operator_type` to AutomationConditionNodeSnapshot

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/serialized_objects.py
This is used upstack to add additional metadata to the evaluation of a SinceCondition.
This likely has other applications as well (e.g. the EntityMatches condition could store AssetKeyMetadataValues to be a bit more explicit about what asset is getting evaluated).
While it's a bit funky to use SubsetsWithMetadata for this sort of thing, I deemed this safer than adding a whole extra parallel storage field. It's sorta nice to just reuse what we have here.
NOCHANGELOG
=> [da] Allow AutomationResult to take a `metadata` parameter

python_modules/libraries/dagster-k8s/dagster_k8s/client.py, python_modules/libraries/dagster-k8s/dagster_k8s/launcher.py, python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_launcher.py
We use karpenter as our k8s autoscaler. Karpenter's handling of daemonsets sometimes leads to pod preemption in k8s (see their [FAQ](https://karpenter.sh/docs/faq/#when-deploying-an-additional-daemonset-to-my-cluster-why-does-karpenter-not-scale-up-my-nodes-to-support-the-extra-daemonset) for reference). As such, we increased the backoff_limit on our dagster jobs using the K8sRunLauncher.
Unfortunately, this is leading to false failure detection in k8s run monitoring. Here's an example of a dagster job that was declared failed.
```
spec:
backoffLimit: 2
completionMode: NonIndexed
completions: 1
manualSelector: false
parallelism: 1
podReplacementPolicy: TerminatingOrFailed
...
status:
active: 1
failed: 1
ready: 1
startTime: "2025-04-17T19:52:23Z"
terminating: 0
uncountedTerminatedPods: {} …
```
=> dagster-k8s: handle jobs with backoff retries

examples/docs_snippets/docs_snippets/guides/components/shell-script-component/1-dg-scaffold-shell-command.txt, examples/docs_snippets/docs_snippets/guides/dg/dagster-definitions/1-scaffold.txt, examples/docs_snippets/docs_snippets_tests/conftest.py, examples/docs_snippets/tox.ini, pyright/alt-1/requirements-pinned.txt, pyright/master/requirements-pinned.txt, python_modules/libraries/dagster-dg/dagster_dg/cache.py, python_modules/libraries/dagster-dg/dagster_dg/cli/__init__.py, python_modules/libraries/dagster-dg/dagster_dg/component.py, python_modules/libraries/dagster-dg/dagster_dg/config.py, python_modules/libraries/dagster-dg/dagster_dg/context.py, python_modules/libraries/dagster-dg/dagster_dg/utils/warnings.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py, python_modules/libraries/dagster-dg/dagster_dg_tests/conftest.py, python_modules/libraries/dagster-dg/dagster_dg_tests/test_cache.py, python_modules/libraries/dagster-dg/dagster_dg_tests/test_context.py, python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py, python_modules/libraries/dagster-dg/setup.py, python_modules/libraries/dagster-shared/dagster_shared/libraries/__init__.py
Warns when a newer version of `dagster-dg` is available.
- If the cache is enabled, then PyPI will only be hit once per hour.
- The check can be prevented from ever running by suppressing the `dg_outdated` warning.
- A special private env var `DAGSTER_DG_UPDATE_CHECK_ENABLED` is also checked. We set this to 0 in tests to prevent bombing the PyPI API in CI.
The warning looks like this:
```
There is a new version of `dagster-dg` available:
Latest version: 0.26.11
Installed version: 0.26.11rc1
Update your dagster-dg installation to keep up to date:
[uv tool]  $ uv tool upgrade dagster-dg
[uv local] $ uv sync --upgrade dagster-dg
[pip]      $ pip install --upgrade dagster-dg
To suppress this warning, add "dg_outdated" to the `cli.suppress_warnings` list in your configuration.
```
New unit …
=> [dg] Warn on outdated dagster-dg (BUILD-998)

python_modules/libraries/dagster-dg/dagster_dg/context.py, python_modules/libraries/dagster-dg/dagster_dg_tests/test_context.py, python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Exit with an error when the `dg` version is less than the dagster in the in-scope environment. We have to transform the "core version" of `dagster` to a "library version" in order to perform the comparison.
The check is run whenever we spawn a `dagster-components` subprocess.
`dg` will now fail with an error message if it's version is below the minimum supported version for the version of `dagster` in your environment.
=> [dg] Fail on dagster-dg version less than dagster version (BUILD-1041)

python_modules/libraries/dagster-dg/dagster_dg/context.py, python_modules/libraries/dagster-dg/dagster_dg_tests/test_context.py
Fix a bug where `DgContext.dagster_version` was resolved using a different environment then the `dagster-components` executable.
New unit test.
=> [dg] Fix dagster_version resolution

python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/test_dbt_project_component.py
well, the test all python versions flag didn't work in #29544 so that didn't fix it
stop validating via `stdout` (which I belive is having issues on `3.9` & `3.10` due to dbt cli using `rich.Console` and some complexity there)
and just make sure the `manifest.json` got made
bk and more carefully validate all py versions were run
=> [dbt] fix test_project_prepare_cli take 2

python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py, python_modules/dagster/dagster_tests/declarative_automation_tests/automation_condition_tests/builtins/test_eager_condition.py
As title / changelog entry. Test that was added failed before and passes now. Basically updates to self-dependent assets would always be ignored.
Fixed issue that would cause the `AutomationCondition.any_deps_updated()` condition to evaluate to `False` when evaluated on a self-dependency.
=> [da] Fix bug with executed_with_root_target condition and self-dependent assets

python_modules/libraries/dagster-k8s/dagster_k8s/client.py
1. Set _request_timeout of 10 seconds for job creation to prevent Run queue from hanging
2. Catch urllib3.exceptions.ProtocolError exception and allow retries on it for job creation also
Relates to #28314  and #28910
=> dagster-k8s hotfixes for recent AKS connectivity issue/regression:

python_modules/libraries/dagster-shared/dagster_shared/serdes/utils.py
[EDIT 04/23] - based on PR feedback, limiting this PR to docstring only, will remove direct usages of `SerializableTimeDelta` in cloud code.
--- 
I ran into a pretty subtle "bug" with `SerializableTimeDelta` - or an accessibility issue, really -  when trying to use it for some datetime arithmetic. This PR adds some docstrings and a `total_seconds()` method as guardrails to hopefully make it less likely to bite someone else in future. 
Let's say you create a `SerializableTimeDelta` from a `datetime.timedelta` that is 24 hours long:
```
td = datetime.timedelta(hours=24)
serializable_td = SerializableTimeDelta.from_timedelta(td)
```
If you now want to get the duration of `serializable_td` in seconds, you may naturally reach for the `seconds` attribute. You would expect this to equal 86,400 …
=> Clarify `SerializableTimeDelta` is for internal use only in docstring

python_modules/libraries/dagster-dg/dagster_dg/cli/plus/deploy_session.py
Summary:
On e.g. origin/master this returns HEAD. Detect that case and don't try to create a branch for HEAD.
Test Plan:
Run dg deploy with origin/master checked out
=> fix branch vs. prod deployment detection when running on an origin branch

python_modules/dagster/dagster/components/cli/list.py, python_modules/libraries/dagster-dg/dagster_dg/context.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py
Collapse error messages when loading a repo for the purposes of `dg list defs`, in a similar vein to what we do for `dg dev` and `dg check defs`:
```sh
$ dg list defs
Using /Users/ben/repos/components_demo/missing-resource-demo/.venv/bin/dagster-components
Loading location missing-resource-demo failed:
dagster._core.errors.DagsterInvalidDefinitionError: resource with key 'my_resource' required by op 'my_asset' was not provided. Please provide a ResourceDefinition to key 'my_resource', or change the required key to one of the following keys which points to an ResourceDefinition: ['io_manager']
Stack Trace:
[15 dagster system frames hidden, run dg check defs --verbose to see the full stack trace]
An error occurred while executing a `dagster-components` command in the Python environment at …
```
=> [dg] Collapse load errors when invoking dg list defs

python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py
Summary:
Maybe there's a smarter way to do this - prevents extra whitespace from being added on the left of this sentinel value
dg scaffold github-actions, view whitespace
=> Fix whitespace in github action scaffold

python_modules/dagster/dagster/components/cli/list.py, python_modules/dagster/dagster/components/core/package_entry.py, python_modules/dagster/dagster_tests/components_tests/registry_tests/test_registry.py, python_modules/libraries/dagster-dg/dagster_dg/component.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py, python_modules/libraries/dagster-shared/dagster_shared/error.py
Improve the error message when an entry point blows up.
Before:
After:
=> improve entry point errors (BUILD-985)

python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt/asset_specs.py, python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py, python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/resources.py, python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/run_handler.py, python_modules/libraries/dagster-dbt/dagster_dbt/core/resource.py, python_modules/libraries/dagster-dbt/dagster_dbt/dbt_manifest_asset_selection.py, python_modules/libraries/dagster-dbt/dagster_dbt/utils.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_selection.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/jaffle_shop/selectors.yml
We support select and exclude, we should also support selector
unit
`@dbt_assets` and `build_dbt_manifest_asset_selection` now support a `selector` argument, allowing you to use yaml-based selectors.
=> [dagster-dbt] Add support for `--selector`

examples/docs_snippets/docs_snippets/integrations/dlt/define_downstream_dependencies.py, python_modules/libraries/dagster-dlt/dagster_dlt/asset_decorator.py, python_modules/libraries/dagster-dlt/dagster_dlt/resource.py, python_modules/libraries/dagster-dlt/dagster_dlt/translator.py, python_modules/libraries/dagster-dlt/dagster_dlt_tests/test_asset_decorator.py
Includes the pipeline object in the `DltResourceTranslatorData` bundle. This allows users to reference e.g. the pipeline's dataset name (schema etc) for purposes of generating their asset key.
Existing tests, new unit test.
=> [dagster-dlt] Include pipeline in DltResourceTranslatorData

python_modules/dagster/dagster/_core/definitions/asset_check_result.py, python_modules/dagster/dagster/_core/execution/plan/compute.py, python_modules/dagster/dagster/_core/execution/plan/execute_step.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py, python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_decorator_with_check_specs.py, python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_op.py
Part of a stack to enable dbt sources as asset checks.
Right now in the system, we throw an explicit error if the user emits an asset check result for an asset check that is not part of the selection. This PR proposes _allowing_ unselected checks to be executed; and instead throw a warning.
There are two reasons to add support for this:
- I think it's a reasonable default behavior to warn instead of error here. Leave it up to the user to determine the severity.
- It helps enable dbt source checks - our asset check default selection semantics make it very difficult to select an asset check that doesn't directly target an asset part of the underlying assets definition. And somewhat impossible to do it by default without breaking changes. The way forward is to enable dbt source checks to be …
=> [source-checks][RFC] Allow unselected checks to be yielded with a warning.

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py, python_modules/dagster/dagster/_core/definitions/decorators/decorator_assets_definition_builder.py, python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_asset_decorator_with_check_specs.py
Adds a hidden flag to the multi asset decorator which disables the assertions governing which checks can be added to which assets definition. By default, the behavior is that you can only create checks which target assets produced within the same definition. Enabling the flag allows totally arbitrary asset checks to exist on the same assetsdefinition as any asset.
This is necessary to support dbt source checks - sources are stub assets produced at definitions creation time, not materializable assets part of the assets definition. We could also allow for "target upstreams of assets in the assets definition" but that feels like very narrow behavior.
=> [source-checks]Allow arbitrary checks in multi_asset decorator if flag is set

python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py, python_modules/libraries/dagster-dbt/dagster_dbt/core/dbt_cli_event.py, python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_checks.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_asset_checks/models/sources.yml
This enables dbt source tests to run as asset checks instead of just yielding observations as we currently do. The behavior is hidden behind a flag by default so as not to break existing users.
It relies on the core behavioral changes from downstack PRs. We haven't been able to come up with a satisfactory way to "select" the dbt source checks by default whenever a model downstream of the targeted source is selected; so instead; we create a "composite selection" of checks which automatically adds the source checks to the tests which will actually be executed.
This mirrors the existing behavior; where source tests are run whenever the source is loaded and indirect selection does not disable tests.
Adds tests for the following scenarios:
- Explicitly select downstream model
- No selection
- …
=> [dagster-dbt][source-checks] source tests as checks

python_modules/libraries/dagster-dg/dagster_dg/config.py, python_modules/libraries/dagster-dg/dagster_dg_tests/test_context.py
Improves error messages for invalid config:
Before:
After:
Modified unit tests, also manually.
Error message when an invalid configuration file is detected is now shorter and more clear.
=> [dg] Improve invalid config error messages (BUILD-1002)

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py, python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
PersistedTimeWindow starts with a UTC timestamp, so transforming this into a datetime just to transform it back into a UTC timestamp is inefficient. Furthermore we have some evidence of lock contention in cached_property calls in python versions < 3.12, so we can avoid using a cached_property in a hot path that we don't need.
The main unfortunate thing here is that there are callsites that mix the user-facing TimeWindow class (which does not have a start_timestamp or end_timestamp property) with this PersistedTimeWindow class that does. Typechecking should help us avoid errors here but we could consider adding the properties to TimeWindow as well as a backstop.
BK
=> Replace calls to PersistedTimeWindow.start.timestamp() and PersistedTimeWindow.end.timestamp() with start_timestamp and end_timestamp properties

js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/LocationBaseDataFetcher.ts, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/TimingControls.ts, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/WorkspaceContext.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/WorkspaceManager.ts, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/WorkspaceStatusPoller.ts, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/__tests__/WorkspaceContext.test.tsx
Adds back a refetch function that causes an immediate fetch of the CodeLocationStatusQuery triggering only changed code locations to refetch (or to be deleted if they no longer exist). 
Jest tests + manual testing
=> [WorkspaceContext] Add back refetch but smarter

js_modules/dagster-ui/packages/ui-core/src/assets/AssetTabs.tsx
Don't persist query params across asset tabs. Some tabs use the same parameter names (e.g. `status`) but encode them differently, leading to JS errors or unexpected behavior when those values are preserved across tab navigation.
Load app, view an asset, navigate to "Events" and change the filters so that I get a `status` query param. Click "Partitions", verify that the query params are removed from the new URL and that no JS errors occur.
[ui] Fix navigation between asset tabs by no longer preserving query parameters from one tab to the next.
=> [ui] Don't persist asset view params across tabs

python_modules/libraries/dagster-dg/setup.py, python_modules/libraries/dagster-dlt/dagster_dlt/__init__.py, python_modules/libraries/dagster-dlt/dagster_dlt/components/dlt_load_collection/component.py, python_modules/libraries/dagster-dlt/dagster_dlt_tests/test_dlt_load_collection_component.py, python_modules/libraries/dagster-dlt/setup.py, python_modules/libraries/dagster-dlt/tox.ini
Introduces a `DltLoadCollectionComponent`, which takes in a list of dlt pipeline and source objects, provided via Python module path.
Subsequent PRs will handle actually customizing the asset specs.
```yaml
type: dagster_dlt.DltLoadCollectionComponent
attributes:
loads:
pipeline: .loads.my_pipeline
source: .loads.my_source
```
Will retrieve a dlt source and pipeline defined in `component/loads.py`.
Unit tests.
=> [dagster-dlt] Introduce basic dlt component

python_modules/libraries/dagster-dlt/dagster_dlt/components/dlt_load_collection/component.py, python_modules/libraries/dagster-dlt/dagster_dlt_tests/test_dlt_load_collection_component.py
Adds translator/`asset_attributes` support to the dlt component, similar to sling/dbt:
```yaml
type: dagster_dlt.DltLoadCollectionComponent
attributes:
loads:
- source: ...
pipeline: ...
translation:
tags:
foo: bar
```
unit tests.
=> [dagster-dlt] Add translation customization to dlt component

python_modules/libraries/dagster-dlt/dagster_dlt/components/dlt_load_collection/component.py, python_modules/libraries/dagster-dlt/dagster_dlt/components/dlt_load_collection/scaffolder.py, python_modules/libraries/dagster-dlt/dagster_dlt_tests/test_dlt_load_collection_component.py
Introduces a dlt component scaffolder. By default (no args), generates a sample `loads.py` file with a barebones dlt source and pipeline:
```yaml
type: dagster_dlt.DltLoadCollectionComponent
attributes:
loads:
- source: .loads.my_load_source
pipeline: .loads.my_load_pipeline
```
```python
import dlt
@dlt.source
def my_source():
@dlt.resource
def hello_world():
return "hello, world!"
return hello_world
my_load_source = my_source()
my_load_pipeline = dlt.pipeline()
```
If the user instead provides a `--source` and `--destination`, under the hood calls `dlt init [source] [destination]` and adapts the results to be ready-to-use for components. This is some `ast` magic and might be a little more complex than we want out of a scaffolder, but I do think the results are pretty convincing:
```yaml …
```
=> [dagster-dlt] Introduce component YAML scaffolder

python_modules/dagster/dagster/_core/definitions/base_asset_graph.py
@cached_property can induce lock contention even across instances as in python<3.12 it is backed by a global lock. For these fields that are easy to compute, we can avoid this by just re-computing when they are accessed
Nothing should be affected other than performance in the edge case
=> remove @cached_property from several fields of BaseAssetGraph

python_modules/libraries/dagster-aws/dagster_aws/s3/sensor.py, python_modules/libraries/dagster-aws/dagster_aws_tests/s3_tests/test_s3_sensor.py
`get_objects` must return an empty list if no files can be found later than a given `last_modified_date`.
Closes #25890. There's an inactive open PR for this as well: #25891.
- Added a unittest.
> S3 sensor's `get_objects` now returns an empty list if no new files can be found since `since_last_modified` parameter.
=> Fix `get_objects` return value in case of no new files since `since_last_modified`

python_modules/dagster/dagster/_grpc/server.py, python_modules/dagster/dagster/_utils/__init__.py, python_modules/dagster/dagster_tests/cli_tests/workspace_tests/test_grpc_server_workspace.py, python_modules/libraries/dagster-shared/dagster_shared/utils/__init__.py
For environments where you're only allowed to use a certain subset of ports.
New test case, run with DAGSTER_PORT_RANGE set locally and force_port = True
Added the ability to restrict the list of ports that `dagster dev` is allowed to use to open subprocesses when running on Windows, by setting the `DAGSTER_PORT_RANGE` env var to a string of the form "<start>=<end>" - for example "20000-30000"
=> Allow locking down the port range for dagster dev with a "DAGSTER_PORT_RANGE" env var

python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_docs_commands.py
This defers the actual execution of `find_free_port()` until the test has started which produces a subtle difference to the pytest test output:
Before:
```
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_docs_commands.py::test_docs_component_type_success[None] PASSED [ 50%]
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_docs_commands.py::test_docs_component_type_success[52039] PASSED           [100%]
```
After:
```
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_docs_commands.py::test_docs_component_type_success[None] PASSED [ 50%]
python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_docs_commands.py::test_docs_component_type_success[find_free_port] PASSED  [100%]
```
This is useful because it lets us instrument …
=> Defer find_free_port parameterization

python_modules/dagster/dagster/_core/definitions/asset_daemon_cursor.py, python_modules/dagster/dagster/_core/definitions/automation_tick_evaluation_context.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_tester.py, python_modules/dagster/dagster_tests/declarative_automation_tests/automation_condition_tests/builtins/test_initial_evaluation_condition.py, python_modules/dagster/dagster_tests/declarative_automation_tests/daemon_tests/test_asset_daemon_cursor.py, python_modules/dagster/dagster_tests/declarative_automation_tests/scenario_utils/automation_condition_scenario.py
This fixes a bug as described in the changelog entry.
The existing logic for updating the AssetDaemonCursor ensured that we would never "forget" about the cursor of any asset that was ever evaluated by a given process.
This is a bit of a holdover from the world of AMP + global AMP evaluation in which:
1. it was possible for a single code-location to be unavailable while the rest of the evaluation was proceeding normally
2. it was very bad (perf-wise) if an AMP cursor was lost to the void
So the existing code was the safest possible measure -- we just literally always propagate old cursors forward. This means that over time, if you change asset names or change how things are automated, your cursor just hold on to a lot of baggage.
This PR makes a small step in the direction of clearing out …
=> [da] Fix initial_evaluation condition handling of missing automation conditions (BUILD-684)

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_asset_health.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_health.py, python_modules/dagster-graphql/dagster_graphql/test/utils.py, python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster/_streamline/asset_check_health.py
Enables the asset check health resolvers to use data provided by streamline, if available. This should make this query more performant 
- adds a `streamline_read_supported` instance method that is `False` for OSS and has a corresponding internal implementation
- adds a `get_asset_check_health_state_for_asset` that is None for OSS and will fetch the asset check health data from streamline for internal
- refactors the asset check health resolver so that the streamline results and results from manually computing asset check statuses are translated into a common type of the number of each type of check status. Then we can determine the health based on those numbers. 
also adds a gql test util to execute a query within an async test
internal pr https://github.com/dagster-io/internal/pull/15233 …
=> asset check health uses streamline

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
A handful of tests fail only on the release branch because we're running library tests on python versions that the library doesn't support.
airflow doesn't support 3.12
dask doesn't support 3.9
will need to merge into release
=> skip failing release tests

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/implementation/execution/run_lifecycle.py, python_modules/dagster-graphql/dagster_graphql/implementation/external.py, python_modules/dagster-graphql/dagster_graphql/implementation/utils.py, python_modules/dagster-graphql/dagster_graphql/schema/inputs.py, python_modules/dagster-graphql/dagster_graphql/schema/roots/mutation.py, python_modules/dagster/dagster/_api/snapshot_execution_plan.py, python_modules/dagster/dagster/_core/execution/api.py, python_modules/dagster/dagster/_core/execution/plan/execute_plan.py, python_modules/dagster/dagster/_core/execution/plan/execute_step.py, python_modules/dagster/dagster/_core/execution/plan/plan.py, python_modules/dagster/dagster/_core/executor/multiprocess.py, python_modules/dagster/dagster/_core/remote_representation/code_location.py, python_modules/dagster/dagster/_core/remote_representation/external_data.py, python_modules/dagster/dagster/_core/snap/execution_plan_snapshot.py, python_modules/dagster/dagster/_core/workspace/context.py, python_modules/dagster/dagster/_grpc/impl.py, python_modules/dagster/dagster/_grpc/types.py, python_modules/dagster/dagster/components/resolved/model.py, python_modules/libraries/dagster-airlift/dagster_airlift/constants.py, python_modules/libraries/dagster-airlift/dagster_airlift/core/components/airflow_instance/component.py, python_modules/libraries/dagster-airlift/dagster_airlift/core/monitoring_job/event_stream.py, python_modules/libraries/dagster-airlift/dagster_airlift/core/monitoring_job/utils.py, python_modules/libraries/dagster-airlift/dagster_airlift/in_airflow/base_asset_operator.py
=> Handle migrated runs

python_modules/dagster/dagster/_utils/pydantic_yaml.py, python_modules/dagster/dagster/components/core/defs_module.py, python_modules/dagster/dagster/components/resolved/base.py, python_modules/dagster/dagster_tests/components_tests/utils.py, python_modules/dagster/dagster_tests/utils_tests/test_source_position.py, python_modules/libraries/dagster-dg/dagster_dg/check.py, python_modules/libraries/dagster-shared/dagster_shared/yaml_utils/__init__.py, python_modules/libraries/dagster-shared/dagster_shared/yaml_utils/sample_yaml.py
* Change `parse_yaml_with_source_positions` to be accurately typed as returning non-optional type.
* Add `try_parse_yaml_with_source_positions` which allows returning of `None`
* Have the core logic be in terms of N yaml hunks delimited by `---`, which python `yaml` supports.
BK
NOCHANGELOG
=> [dg] Accurately type parse_yaml_with_source_positions

python_modules/dagster/dagster/components/core/defs_module.py, python_modules/dagster/dagster/components/lib/pipes_subprocess_script_collection.py, python_modules/dagster/dagster_tests/components_tests/code_locations/python_script_location/defs/triple_dash_scripts/component.yaml, python_modules/dagster/dagster_tests/components_tests/code_locations/python_script_location/defs/triple_dash_scripts/script_one.py, python_modules/dagster/dagster_tests/components_tests/code_locations/python_script_location/defs/triple_dash_scripts/script_two.py, python_modules/dagster/dagster_tests/components_tests/unit_tests/test_pipes_subprocess_script_collection.py, python_modules/libraries/dagster-shared/dagster_shared/yaml_utils/__init__.py
Right now we have "collection" component types which are pretty awkward.
It turns out yaml supports multiple documents in a single file with the `---` delimiter. This ends up being much nicer. Will we be able to compose simpler components in a generic way and it will be expected behavior from users coming from k8s and similar systems.
Thank you @PedramNavid for suggesting! Big advanced.
BK
NOCHANGELOG
=> [dg] Support `---` in component.yaml to allow for multiple instances

python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py, python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster/_core/storage/legacy_storage.py, python_modules/dagster/dagster/_core/storage/runs/base.py, python_modules/dagster/dagster/_core/test_utils.py, python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py, python_modules/libraries/dagster-airlift/dagster_airlift/core/components/airflow_instance/component.py, python_modules/libraries/dagster-airlift/dagster_airlift/core/monitoring_job/event_stream.py, python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_component_defs.py, python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_monitoring_job.py, python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink_tests/integration_tests/test_e2e_components.py
Allow overriding the timestamp set on the event log entry. This allows for backdating events.
Added a new storage test
=> DagsterInstance.report_dagster_event timestamp override

python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py, python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster/_core/execution/context_creation_job.py, python_modules/dagster/dagster/_core/execution/host_mode.py, python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster/_core/storage/legacy_storage.py, python_modules/dagster/dagster/_core/storage/runs/base.py, python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py, python_modules/dagster/dagster/_core/test_utils.py, python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py, python_modules/libraries/dagster-airlift/dagster_airlift/core/components/airflow_instance/component.py, python_modules/libraries/dagster-airlift/dagster_airlift/core/monitoring_job/event_stream.py, python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_component_defs.py, python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_monitoring_job.py, python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink_tests/integration_tests/test_e2e_components.py
=> [historical-runs 3/n] Make runs obey event log entry timestamp

js_modules/dagster-ui/packages/ui-core/src/asset-graph/types/AssetGraphJobSidebar.types.ts, js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, js_modules/dagster-ui/packages/ui-core/src/nav/getLeftNavItemsForOption.tsx, js_modules/dagster-ui/packages/ui-core/src/pipelines/types/GraphExplorer.types.ts, js_modules/dagster-ui/packages/ui-core/src/pipelines/types/PipelineExplorerRoot.oss.types.ts, js_modules/dagster-ui/packages/ui-core/src/pipelines/types/SidebarContainerOverview.types.ts, js_modules/dagster-ui/packages/ui-core/src/runs/RunTimelineTypes.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/types/useRunsForTimeline.types.ts, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/types/WorkspaceQueries.types.ts, python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py, python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster/_core/execution/context_creation_job.py, python_modules/dagster/dagster/_core/execution/host_mode.py, python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster/_core/storage/legacy_storage.py, python_modules/dagster/dagster/_core/storage/runs/base.py, python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py, python_modules/dagster/dagster/_core/test_utils.py, python_modules/dagster/dagster_tests/storage_tests/test_run_storage.py, python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py, python_modules/dagster/dagster_tests/storage_tests/utils/run_storage.py, python_modules/libraries/dagster-airlift/dagster_airlift/core/components/airflow_instance/component.py, python_modules/libraries/dagster-airlift/dagster_airlift/core/monitoring_job/event_stream.py, python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_component_defs.py, python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_monitoring_job.py, python_modules/libraries/dagster-airlift/kitchen-sink/kitchen_sink_tests/integration_tests/test_e2e_components.py
Adds a add_historical_run method to run storage which can be used to alter the create_timestamp of the underlying run. This is necessary to import historical runs and have them represent properly in any views built/filtered on create_timestamp in some way.
Added new storage tests for the method.
=> [historical-runs 2/n] Add history import run method

.buildkite/dagster-buildkite/dagster_buildkite/step_builder.py
Looking at our build data, it was a good decision to raise this limit because we do see a handful of different steps with a max successful runtime of more than 25 minutes:
https://github.com/dagster-io/dagster/pull/28945
But we picked 45 pretty blindly. Since then, we've better instrumented our tests and can now measure our longest successful steps. I'd like to start ratcheting this down because when tests do hang, it really baloons the length of the total build. For example:
https://buildkite.com/dagster/dagster-dagster/builds/121207#019688a0-ab20-403b-946a-29acc089444c
It looks like the only test suites that have exceeded 35 minutes in the last 6 weeks and still passed are dagster-dg - but we've since split that into multiple test suites:
https://github.com/dagster-io/dagster/pull/29353 …
=> Drop max step timeout to 30m

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
This started failing recently in ways that look like resource contention on the instance. The agent itself is getting killed about 2/3 of the way through.
This runs it with more resources. Something we previously did for a similar variant of kitchen-sink tests:
https://github.com/dagster-io/dagster/pull/25487
If this build doesn't pass, I'll instead skip the test suite entirely. Either way, we should carve out time to improve this suite's performance and reliability.
=> [NO_SKIP=true] Run kitchen-sink on Docker queue

python_modules/dagster/dagster/_core/asset_graph_view/serializable_entity_subset.py, python_modules/dagster/dagster_tests/core_tests/asset_graph_view_tests/test_serializable_entity_subset.py
allows adding and removing partition subsets/bools from `SerializableEntitySubset`  and constructing a `SerializableEntitySubset` from the input types we might expect in code (None, partition key, partitions subset) so that we don't need to branch in the calling code
used in https://github.com/dagster-io/internal/pull/15287
=> `compute_union`, `compute_intersection`, `compute_difference`, `from_coercible_value` methods on SerializableEntitySubset

python_modules/automation/automation/graphql/python_client/utils.py
dont depend on test module import
dagster-graphql-client query check
=> fix dagster-graphql-client

python_modules/libraries/dagster-openai/dagster_openai/resources.py, python_modules/libraries/dagster-openai/dagster_openai_tests/test_resources.py
Adds OpenAI models in the output metadata. Nothing prevents users to use multiple OpenAI models per output, so a list of models is added in the metadata.
Although best practice for users would be to use only one model per output, they can use the client to create completions with different models in the same output.
The main downside to supporting a list of models is that users won't know in the insights how many completion/usage tokens were used per model.
2 alternatives if we think using a list of models is not the best:
- We could add only one model in the output metadata and log a warning if users are using another model - using more than one OpenAI model in the same output feels like an anti-pattern.
- We could log usage metadata using the model name in the metadata key, something …
=> [dagster-openai][rfc] Add models to usage metadata

python_modules/dagster/dagster/_core/definitions/multi_dimensional_partitions.py, python_modules/dagster/dagster_tests/definitions_tests/test_multi_partitions.py
If the partition key that's passed into a MultiPartitionsDefinition's has_partition_key is not a multi partition key, it spits out an error. This is bad, and we should instead return false.
Fixed a bug which could cause an error when calling `MultiPartitionsDefinition.has_partition_key()` on invalid keys.
=> [partitions] Fix issue with the `has_partition_key` method on MultiPartitionsDefinition

python_modules/dagster/dagster/_core/execution/context/init.py
`.dagster_run` is currently deprecated in favor of `.run` in `AssetExecutionContext` and `OpExecutionContext`. 
This PR does the same for `InitResourceContext` so that run properties can be access for them uniformly.  
No tests required
> `dagster.InitResourceContext.dagster_run` has been deprecated in favor of `InitResourceContext.run`
cc @cmpadden @smackesey
=> [core] deprecate InitResourceContext.dagster_run in favor of .run

python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py, python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/resources.py, python_modules/libraries/dagster-dbt/dagster_dbt/core/resource.py
Following the thread [here](https://github.com/dagster-io/dagster/pull/28902#discussion_r2021967005), consolidate the logic to get the manifest, translator and selection args for a given context in a single function. The function is the same for dbt core and dbt Cloud.
=> [dagster-dbt] Consolidate cli invocation params logic in dbt core and cloud

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_asset_health.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_health.py, python_modules/dagster/dagster/_streamline/asset_check_health.py, python_modules/dagster/dagster/_streamline/asset_health.py
this is a mainly refactoring PR, no business logic is changing
Simplifies the shared code between the streamline and non-streamline implementations so that an `AssetCheckHealthState` object is created/fetched for both and then converted to the graphene health statuses and metadata
The one new thing this PR introduces is an `AssetHealthStatus` enum so that we can call `asset_check_health_state.asset_health` and get the enum value back, rather than having to compute from the number of checks in each state every time we want to know the state
Internal PR https://github.com/dagster-io/internal/pull/15396
existing tests
=> [gql] asset check health simplification of streamline and non-streamline paths

python_modules/libraries/dagster-tableau/dagster_tableau/asset_utils.py, python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_asset_specs.py
This PR updates the `parse_tableau_external_and_materializable_asset_specs` fn to let users select data sources with extracts as materializable Tableau assets.
New test with BK
=> [2/n][dagster-tableau] Update spec parser to include extracts as materializable assets

js_modules/dagster-ui/packages/ui-core/src/assets/AssetRecentUpdatesTrend.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogActivityChart.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogInsightsLineChart.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogRateCard.module.css, js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogRateCard.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogTopAssetsChart.module.css, js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogTopAssetsChart.tsx, js_modules/dagster-ui/packages/ui-core/src/insights/renderInsightsChartTooltip.tsx
- Add pagination to the charts at the bottom
- Hook up the correct asset labels to the chart at the bottom
- Use theme colors instead of hardcoded colors
- Add tooltips
- Use the users timezone (still a little weird with the activity charts, need to dig into this more, they need to be offset by the users timezone)
- bypass tooltip positioning logic for charts with indexAxis=y (I tried doing something for it similar but realized the existing logic isn't robust because it checks index=0 instead of checking the actual positioning which means index=1 can overflow and be offscreen, also doesn't seem robust enough for bar charts).
- Format all of the numbers
=> Catalog insights polish

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster-graphql/dagster_graphql/schema/external.py, python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py, python_modules/dagster/dagster/_core/workspace/context.py
Right now we pass around this object to the GrapheneAssetNode construction, but not every callsite is covered. Instead, put one on the request context so that it is always available.
Existing coverage
=> Store dynamic partitions loader on the request context instead of passing it around

python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_check_selection.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_checks.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_asset_checks/models/staging/stg_customers_again.sql
When generating asset checks for sources, we encounter the source in the manifest as many times as it is referenced downstream. This meant the existing implementation of `build_dbt_specs` would generate duplicate asset checks.
This PR switches the `asset_checks` list to a dict of `AssetCheckSpec.get_python_identifier()` -> `AssetCheckSpec`
Closes [#29746](https://github.com/dagster-io/dagster/issues/29746)
Added an extra dbt model to existing test project that references the dbt source.
> [dagster-dbt] Fix `DagsterDbtTranslatorSettings.enable_source_tests_as_checks` returning duplicate asset checks
=> [dagster-dbt] Fix `DagsterDbtTranslatorSettings.enable_source_tests_as_checks` returning duplicate asset checks

python_modules/dagster/dagster/_core/executor/multiprocess.py, python_modules/dagster/dagster_tests/execution_tests/misc_execution_tests/test_retries.py
Noticed that multiprocess executor will retry steps on crashes, but will still fail the run (after successfully retrying the step).
BK
> Fixed a bug where the default multiprocess executor would fail runs where the child process for a step crashed, even if a retry policy resulted in a successful retry of that crashed step.
=> prevent crashes from failing multiprocess executor runs

python_modules/dagster/dagster/components/resolved/base.py, python_modules/dagster/dagster/components/resolved/model.py, python_modules/dagster/dagster_tests/components_tests/resolution_tests/test_resolved.py
Using whole parent object resolvers and nested annotations is effectively incompatible so raise an error on it explicitly 
added test
=> [resolvable] error on nested parent object resoler use

python_modules/libraries/dagster-tableau/dagster_tableau/asset_utils.py, python_modules/libraries/dagster-tableau/dagster_tableau/resources.py, python_modules/libraries/dagster-tableau/dagster_tableau/translator.py
Create a clear separation between TableauMetadataSet, TableauViewMetadataSet and TableauDataSourceMetadataSet following this [comment/change](https://github.com/dagster-io/dagster/pull/29679#discussion_r2070809869).
A Tableau data source can't have a workbook ID and a Tableau view (sheets and dashboards) can't have extracts.
BK
=> [dagster-tableau] Add TableauViewMetadataSet

scripts/uv-retry-install.sh
example of failure the current checking did not fire on 
https://buildkite.com/dagster/dagster-dagster/builds/121530/steps?sid=01969289-fea5-40bf-80dc-77b768d81902
since the error text is slightly different
eyes
=> [bk] retry uv on connection reset

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
Companion to https://github.com/dagster-io/dagster/pull/29729
Once I removed the custom PackageSpec, it started falling back to the generic PackageSpec discovery.
https://buildkite.com/organizations/dagster/analytics/suites/dagster/tests/a1ec44fc-cc1c-89a4-ad62-52eca6871d7b
=> Skip starlift-demo for real

js_modules/dagster-ui/packages/ui-core/src/automation/AutomationTargetList.tsx
Fixes: https://github.com/dagster-io/dagster/issues/29708
Previously, the logic for this UI would the following in cases where there were multiple assets defined and a single check:
The previous logic first checked if there was exactly one asset defined, and if that was not the case (and exactly one check was defined), then it would render in the "single check" style. This means that if there were multiple assets and one check, we'd get the "single check" case, which is not what we want.
[ui] Fixed an issue which could cause the "Target" field of AutomationConditionSensorDefinitions to render incorrectly when exactly one asset check was defined in a code location.
=> [ui] Fix bug in automation condition sensor display when only a single asset check exists in a code location

python_modules/dagster-graphql/dagster_graphql/schema/asset_health.py, python_modules/dagster/dagster/_core/definitions/freshness.py
This will be specifically used for cases where an asset does not have a freshness policy, so freshness state cannot be evaluated. Imagine the following scenario:
- asset has freshness policy and has "valid" freshness state (either PASS, FAIL or WARN)
- user removes the freshness policy, code location is reloaded
- we re-evaluate freshness state for the asset - what should this state be?
We could have used UNKNOWN, but that state is also used when an asset does have a freshness policy but has never been materialized. Adding a new NOT_APPLICABLE state lets us be more explicit for cases like this.
tests in `internal`: https://github.com/dagster-io/internal/pull/15277
=> Add `FreshnessState.NOT_APPLICABLE`

js_modules/dagster-ui/packages/ui-core/src/asset-graph/CollapsedGroupNode.tsx
One thing we're losing atm is in the in progress indicator on the group node.... I'll look into fetching that in a follow up in a way that is more performance than querying AssetGraphLiveQuery for it.
=> Show asset health on collapsed group node

examples/docs_snippets/docs_snippets/guides/components/index/19-dg-list-plugins.txt, examples/docs_snippets/docs_snippets/guides/components/index/28-dg-list-plugins.txt, examples/docs_snippets/docs_snippets/guides/components/index/7-dg-list-plugins.txt, examples/docs_snippets/docs_snippets/guides/components/index/9-dg-list-plugins.txt, examples/docs_snippets/docs_snippets/guides/components/shell-script-component/3-dg-list-plugins.txt, examples/docs_snippets/docs_snippets/guides/dg/migrating-project/10-list-plugins.txt, python_modules/dagster/dagster/components/components.py, python_modules/dagster/dagster/components/lib/shim_components/job.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
Super basic job scaffolder which just scaffolds an op-job `@job` decorator without any ops.
Some question if this is particularly useful, or whether we ought to make an asset-job version (which could also probably live in YAML).
New test.
> [components] Added `dagster.job` scaffolder.
=> [dg] Add job scaffolder

python_modules/dagster/dagster/components/core/load_defs.py
Lost a couple minutes trying to use the (falsely) advertised `resources` argument to `load_defs`. When I went to fix the doc string, noticed that `project_root` was missing.
N/A
=> [docs] swap nonexistent argument (`resources`) for missing argument (`project_root`) in docstring for `load_defs`

.buildkite/dagster-buildkite/dagster_buildkite/step_builder.py
https://github.com/dagster-io/internal/pull/15269 added tracking for jest tests, but there was an indication that the message environment variable was missing so adding to see if it resolves. I believe I'll need to wait for the internal pull request to land before testing this change
TODO
=> Add BuildKite Message environment variable

python_modules/dagster/dagster/_core/definitions/freshness.py, python_modules/dagster/dagster/_core/definitions/remote_asset_graph.py, python_modules/dagster/dagster/_core/events/__init__.py, python_modules/dagster/dagster/_streamline/asset_freshness_health.py
Adds a `AssetFreshnessHealthState` state for streamline to update. 
Also adds some helper methods to get info about a freshness event from the event log entry and the freshness policy from an assetnode
corresponding internal pr https://github.com/dagster-io/internal/pull/15433
=> `AssetFreshnessHealthState` for streamline

js_modules/dagster-ui/packages/ui-core/src/asset-data/__tests__/AssetLiveDataProvider.test.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphSupplementaryData.oss.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-selection/useAssetSelectionFiltering.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/AssetCatalogTablev2.test.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetCatalogTableV2.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetCatalogV2VirtualizedTable.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetSelectionSummaryTile.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetsGroupedView.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/catalog/ListGridViews.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/useAllAssets.tsx, js_modules/dagster-ui/packages/ui-core/src/live-data-provider/LiveDataProvider.tsx
1. More memoization
2. Add shimmer rows when health data is still loading to avoid going from showing shimmer rows to no rows / 1 row when we have partial data
3. Add an in memory cache for asset selection resolution similar to what we had in the cloud version of the catalog view tiles.
4. Use a separate live data thread for fetching health data in useAssetGraphSupplementaryData in order to avoid starving the rest of the UI out making the catalog load much faster.
5. Use JSON.stringify on keys in LiveData to avoid unsubscribing/resubscribing to the same set of keys when references change.
6. Process live data updates immediately when cache data is available during subscription to avoid an artificial delay on page load.
App-proxy. Existing tests for LiveDataProvider
=> Catalog v2 perf + loading improvements

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py, python_modules/dagster-graphql/dagster_graphql/implementation/fetch_partition_subsets.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster/dagster/_core/storage/partition_status_cache.py, python_modules/dagster/dagster/_streamline/asset_materialization_health.py
Moves the `AssetMaterializationHealthState` previously defined in internal to OSS. Adds a `compute_for_asset` class method to instantiate an `AssetMaterializationHealthState` for an asset based on the data stored in the DB. The implementation is based off of how materialization health is computed for asset health https://github.com/dagster-io/dagster/blob/2f869684c2e80fe916227f2d0cab04f99571e31a/python_modules/dagster-graphql/dagster_graphql/schema/asset_health.py#L124. A stacked PR will clean up the duplication between these two methods
I needed to move `get_partitions_subsets` out of `dagster_graphql` so i could use it to regenerate the partition status cache when making a new `AssetMaterializationHealthState`
tests in https://github.com/dagster-io/internal/pull/15478
=> AssetMaterializationHealthState

python_modules/dagster/dagster/_streamline/asset_materialization_health.py
In the asset health UIs we want to show the latest failed run id for an asset in a failed state. I figured we might as well just store the id of the latest run to either successfully materialize or fail to materialize the asset. So this adds that metadata. I'm not thrilled with the name `latest_terminal_run_id`, i'm worried it implies that canceled or deleted runs may be included, which is not necessarily the case (unless they successfully materialized an asset before canceling/deleting)
in https://github.com/dagster-io/internal/pull/15480
=> add latest run id to `AssetMaterializationHealthState`

js_modules/dagster-ui/packages/ui-core/src/assets/AssetPageHeader.oss.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx
With the new observe UI we no longer have "folders" and so the folder linking doesn't work. Update the links to instead use the asset selection syntax to scope the catalog to the "folder".
https://github.com/user-attachments/assets/1222cfc9-79a2-42bd-a2f8-e3cad6267bfa
=> Update asset breadcrumb links for new observe UI

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_asset_health.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_health.py, python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster/_streamline/asset_materialization_health.py
Updates the GQL resolver for asset health to use streamline data when available
tests in https://github.com/dagster-io/internal/pull/15492
=> [asset health] use streamline data when available to get materialization health

python_modules/libraries/dagster-dbt/dagster_dbt/components/dbt_project/component.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/test_dbt_project_component.py
`context.resolve_value` currently does not implicitly handle model resolution so do it manually 
added test
[bugfix][components][dbt] `DbtProjectComponent` fields now properly evaluate templates
=> [dbt component] fix project args resolution

.buildkite/dagster-buildkite/dagster_buildkite/step_builder.py
We're seeing intermittent failures with:
https://docs.docker.com/engine/containers/run/#125
For example:
https://buildkite.com/dagster/dagster-dagster/builds/121996#0196b037-f82b-486d-a2dc-047d4315615b/306-312
I think the exit code is sufficiently narrowly scoped that we can retry on it for now.
=> Retry docker daemon exit code 125

python_modules/automation/tox.ini
These unfortunately live outside of pytest so they can't be muted directly in Buildkite.
I'm disabling them for now and we can figure out what caused them to regress:
https://buildkite.com/dagster/dagster-dagster/builds/121995#0196b03d-62f1-4328-bcac-a2e19bdbb2d3/300-1156
=> Temporarily skip make dataproc/spark_docs diff

python_modules/libraries/dagster-sling/dagster_sling/asset_decorator.py, python_modules/libraries/dagster-sling/dagster_sling/components/sling_replication_collection/component.py, python_modules/libraries/dagster-sling/dagster_sling_tests/code_locations/sling_location/defs/ingest/component.yaml, python_modules/libraries/dagster-sling/dagster_sling_tests/test_sling_replication_collection_component.py
Use the translation pattern for the `SlingReplicationCollectionComponent`, modeled after our DBT component.
Updated unit tests.
> [dagster-sling] When using the SlingReplicationCollectionComponent, the `asset_attributes` parameter has been updated to `translation` to match our other integration components.
=> [dagster-sling][components] Use translation pattern for SlingReplicationCollectionComponent

python_modules/libraries/dagster-dbt/dagster_dbt/components/dbt_project/component.py, python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/test_dbt_project_component.py
Enables code references to underlying SQL files, by default, for the DBT component.
Unit test.
=> [components] Automatically enable code references for dbt component

python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py, python_modules/libraries/dagster-fivetran/dagster_fivetran/ops.py, python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
Now that the new Fivetran resource is GA, the legacy resource should be deprecated.
[dagster-fivetran] the `FivetranResource` resource is now deprecated.
=> [dagster-fivetran] mark legacy Fivetran integration as deprecated

js_modules/dagster-ui/packages/ui-core/src/assets/catalog/util.ts, js_modules/dagster-ui/packages/ui-core/src/search/links.tsx
as titled.
Click the link and saw it went to the catalog.
=> [1/2] Update link to code location in asset search to go to catalog with code location asset selection syntax filter

python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py, python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
Wipes asset check evaluations when an asset is wiped in the SQL event log storage.
Update asset checks storage unit test.
> Wiping an asset will now wipe associated asset check evaluations.
=> Wipe asset check evaluations when wiping assets

python_modules/libraries/dagster-dg/dagster_dg/cli/list.py, python_modules/libraries/dagster-dg/dagster_dg/env.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py
This was somewhere in the env demo stack and never got split into its own PR.
Adds a column to the `dg list env` output showing which components consume an env var:
```sh
$ dg list env
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━━━━━━┓
┃ Env Var                                        ┃ Value ┃ Components ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━━┩
│ DESTINATION__SNOWFLAKE__CREDENTIALS__DATABASE  │       │ envvar2    │
│ DESTINATION__SNOWFLAKE__CREDENTIALS__HOST      │       │ envvar2    │
│ DESTINATION__SNOWFLAKE__CREDENTIALS__PASSWORD  │       │ envvar2    │
│ DESTINATION__SNOWFLAKE__CREDENTIALS__ROLE      │       │ envvar2    │
│ DESTINATION__SNOWFLAKE__CREDENTIALS__USERNAME  │       │ envvar2    │
│ …
```
=> [dg] Add consuming components to `dg list env`

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py, python_modules/dagster/dagster_tests/declarative_automation_tests/automation_condition_tests/builtins/test_on_cron_condition.py
Make sure people don't make invalid conditions that will fail when evaluated
=> [da] validate cron string in `cron_tick_passed` condition

js_modules/dagster-ui/packages/ui-core/src/overview/OverviewPageAlerts.oss.tsx, js_modules/dagster-ui/packages/ui-core/src/overview/OverviewPageHeader.tsx
OSS counterpart to https://app.graphite.dev/github/pr/dagster-io/internal/15565, which removes the AMP alert currently shown on Overview. It's the only banner there, so I'm just removing this altogether instead of leaving a couple null-rendering components lying around.
TS, lint.
=> [ui] Remove Overview alerts section

js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/globalAssetGraphPathToString.test.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/globalAssetGraphPathToString.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/AssetTagCollections.tsx
https://dagsterlabs.slack.com/archives/C03CCE471E0/p1746749043149529
Previously, we would include the downstreams of each key on the run when you clicked the "View lineage" button.
I found this unintuitive, as the "view list" button only shows the keys directly on the run. I also added parens to the wider expression to make it easier to add further clauses (e.g. (<big expression>) and status:degraded))
=> [ui] Update the behavior of "view lineage" on the runs view

js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogRateCard.module.css, js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogRateCard.tsx
Instead of displaying infinite loading spinner when there is no data, let's show an empty state
Companion internal PR: https://github.com/dagster-io/internal/pull/15575
Locally viewed:
Loading states:
NOCHANGELOG
=> Add new states to asset catalog rate card

python_modules/dagster/dagster/components/core/defs_module.py, python_modules/dagster/dagster/components/definitions.py, python_modules/dagster/dagster_tests/components_tests/test_definitions.py, python_modules/dagster/dagster_tests/core_tests/test_external_execution_plan.py, python_modules/dagster/dagster_tests/execution_tests/engine_tests/test_step_delegating_executor.py, python_modules/dagster/dagster_tests/execution_tests/execution_plan_tests/test_external_step.py, python_modules/dagster/dagster_tests/general_tests/test_cacheable_assets_defs.py
This adds support for `@definitions` in the `defs` hierarchy. Current we support it at code location entry points, and this mirrors that support in the defs module component. I believe we should default all scaffolding to use this mechanism in order to avoid import-based side effects.
So instead of 
```python
defs = dg.Definitions(resources={'some_resource': 'value'})
```
you can write
```python
from dagster.components import definitions
@definitions
def resources():
return dg.Definitions({'some_resource': 'value'})
```
BK. Also manual tests in standalone projects.
* Support the usage of `@definitions` in the `defs` hierarchy.
=> [dg] Support @definitions in the defs hierarchy

examples/docs_snippets/docs_snippets/guides/components/index/19-dg-list-plugins.txt, examples/docs_snippets/docs_snippets/guides/components/index/22-project-jdbt-incorrect.yaml, examples/docs_snippets/docs_snippets/guides/components/index/24-project-jdbt.yaml, examples/docs_snippets/docs_snippets/guides/components/index/28-dg-list-plugins.txt, examples/docs_snippets/docs_snippets/guides/components/index/7-dg-list-plugins.txt, examples/docs_snippets/docs_snippets/guides/components/index/9-dg-list-plugins.txt, examples/docs_snippets/docs_snippets/guides/components/shell-script-component/3-dg-list-plugins.txt, examples/docs_snippets/docs_snippets/guides/dg/migrating-project/10-list-plugins.txt, python_modules/dagster/dagster/__init__.py, python_modules/dagster/dagster/components/lib/shim_components/resources.py, python_modules/dagster/dagster_tests/component_tests/shim_components/test_resources.py
Enables the command `dg scaffold dagster.resources path/to/resources.py`
This generates a file:
```python
from dagster.components import definitions
@definitions
def resources() -> dg.Definitions:
return dg.Definitions(resources={})
```
If you do require the `ComponentLoadContext` for this invocation, you can add it:
```python
from dagster.components import definitions, ComponentLoadContext
@definitions(has_context_arg=True)
def resources(context: ComponentLoadContext) -> dg.Definitions:
return dg.Definitions(resources={})
```
No matter where you are in the component hierarchy, these resource keys apply globally to the entire location, something we may have to improve at a later date.
Unit tests and manual testing in a standalone project
* Add …
=> [dg] Resource Scaffolding

examples/docs_snippets/docs_snippets/concepts/partitions_schedules_sensors/sensors/run_status_run_requests.py
The type hint for `context` was missing.
=> docs: Add missing type hint

python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/commands/ci/__init__.py
Summary:
This codepath started failing with the click 8.2 upgrade - but it doesn't seem like there was any way to set the underlying loglevel argument before. Source it from an env var instead.
Test Plan:
Run `dagster-cloud ci check` and `DAGSTER_CLOUD_CLI_LOG_LEVEL=DEBUG dagster-cloud-ci check`
=> Fix dagster-cloud-cli log level initialization

python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py, python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/conftest.py, python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_asset_specs.py
Fixes AD-1290.
In some cases, the schema config doesn't exist, even if the connector is connected and the schema status is ready. The Fivetran API request fails with a 404 error in that case.
New tests with BK.
[dagster-fivetran] An issue causing the Fivetran integration to fail when the schema config does not exist for a connector has been fixed.
=> [dagster-fivetran] Handle unavailable schema configs in fetch_fivetran_workspace_data

python_modules/dagster/dagster/components/component_scaffolding.py, python_modules/dagster/dagster/components/lib/shim_components/asset_check.py, python_modules/dagster/dagster/components/lib/shim_components/job.py, python_modules/dagster/dagster/components/lib/shim_components/multi_asset.py, python_modules/dagster/dagster_tests/component_tests/shim_components/shim_test_utils.py, python_modules/dagster/dagster_tests/component_tests/shim_components/test_asset_check.py, python_modules/dagster/dagster_tests/components/test_component_scaffolding.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
This PR proposes changes the pattern of scaffolding our core decorators so that it always creates a valid definition viewable with `dg list defs` after scaffolding. I believe this is important to a smooth DX. However this is a product discussion so worthy of discussion.
BK
* Will write if we decide to do this.
=> [dg] Change asset_check scaffolder to require an asset key so that it always creates a valid asset check

js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationOverviewRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/code-location/css/CodeLocationOverviewRoot.module.css, js_modules/dagster-ui/packages/ui-core/src/workspace/CodeLocationRowSet.tsx
For code locations, display the full image string, and move the copy behavior to an adjacent button.
This should make it easier to search for (and select) image names in the code location history page in Dagster+, and fixes a text alignment issue as well.
View code location list, verify that the entire image name is rendered, wrapping onto a new line as needed. Verify click-to-copy behavior.
View code location change history, verify same.
[ui] Make it easier to select and copy image names for code locations.
=> [ui] Improve image string display for code locations

js_modules/dagster-ui/packages/ui-core/src/assets/AssetHealthSummary.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetMaterializationUpstreamData.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetRecentUpdatesTrend.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/overview/DefinitionSection.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/overview/FreshnessPolicySection.tsx, js_modules/dagster-ui/packages/ui-core/src/ui/TimeFromNow.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedObserveJobRow.tsx
Makes the TimeFromNow component re-render every 5 seconds so that the time updates. Also uses it in more spots since the tooltip functionality is useful generally
=> Make `TimeFromNow` component re-render every 5seconds + use it in more spots

python_modules/dagster/dagster/_core/definitions/asset_check_evaluation.py, python_modules/dagster/dagster/_core/definitions/asset_check_result.py, python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster/_core/snap/execution_plan_snapshot.py, python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance_reexecution.py
This changes the logic for determining which keys to execute to solve two issues:
We did not handle non-subsettable multi assets at all, so this process could have resulted in errors when generating the execution plan
When a blocking asset check fails, we should re-execute it (as this is the source of the run failure, we need to re-execute as part of the process), and we weren't doing that before
Potentially controversially, I have this re-executing both the blocking asset check AND the asset that the check targets, with the logic being that the code of the asset itself is more likely to be the issue than the code of the check. So the workflow you'd want would be to update the code of the asset, then execute "re-execute from asset failure", and have your asset re-executed.
Also moved some …
=> Update mechanism for re-execute from asset failure

python_modules/dagster/dagster/_core/definitions/asset_graph.py, python_modules/dagster/dagster/_core/definitions/partition_mapping.py, python_modules/dagster/dagster/_core/definitions/time_window_partition_mapping.py, python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_asset_partition_mappings.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py, python_modules/dagster/dagster_tests/storage_tests/test_fs_io_manager.py
Seeing some runtime errors querying status for assets with invalid partition mappings
BK
Expanded definition time validation for partition mappings to avoid runtime errors querying asset status.
=> validate partition mappings more comprehensively to avoid runtime errors

python_modules/dagster/dagster/_core/definitions/partition.py, python_modules/dagster/dagster/_core/instance/__init__.py
We should have the flexibility to change the hashing scheme for dynamic partitions definitions to be less volatile.
To do that we need to selectively change the hash when there are mutations to the dynamic partitions definition that affect the partitions cache (e.g. deletions)
This enables us to start tracking partition deletions in the storage layer and invalidate the cache.
The default implementation at the storage layer should match the implementation on the definition.
BK
=> delegate dynamic partitions id caching hash id to dynamic partitions store

python_modules/dagster/dagster/_core/instance/config.py, python_modules/dagster/dagster/_daemon/daemon.py, python_modules/dagster/dagster_tests/daemon_tests/test_dagster_daemon.py
Adds instance config to configure submit threadpool workers for backfill runs
BK
Added a config section to enable submitting backfill runs in a threadpool
=> add config tests, guard against unconfigured threadpool worker

python_modules/dagster/dagster/_core/asset_graph_view/serializable_entity_subset.py, python_modules/dagster/dagster_tests/core_tests/asset_graph_view_tests/test_serializable_entity_subset.py
1. Don't just catch check errors, we might timestamp keys in the wrong format for the partitions definitions, for example
2. Validate partition keys when the subset type is not Default. For now we just allow all keys in the DefaultPartitionSubset, but we may want to add validation eventually. Right now, validating that an asset is in a dynamic partition subset can be expensive, so we won't do it for now
=> catch all errors in SerializableEntitySubset.try_from_coercible

integration_tests/test_suites/daemon-test-suite/auto_run_reexecution_tests/test_auto_run_reexecution.py, python_modules/dagster/dagster/_core/execution/retries.py
Before, we were failing in the run failure events in the WILL_RETRY calculations. Now, we catch that error specficially and indicate that we will not retry.
New test case
=> Handle edge case where the root run has been deleted before a child run fails

js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/EvaluationDetailDialog.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/EvaluationListRow.tsx
In order to avoid cross-push issues, reverting all the frontend DA changes until after the graphql changes go out.
BK
=> Revert "hide evaluations button if shown on evaluations table (#29647)"

python_modules/dagster/dagster_tests/components_tests/utils.py
Summary:
Previous code sporadically returns something like '9409213471622824e-05' instead of the desired random integer, causing the test to flakily fail.
BK
=> Fix components test flake

js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetHealthDataProvider.tsx
Currently even though we don't do the health query when the flag is off we still end up doing a bunch of work that can cause the browser the crash for orgs with large numbers of assets. Pass an empty array to basically turn this into a no-op.
=> Skip health live data machinery completely if flag is off

js_modules/dagster-ui/packages/ui-core/src/app/Util.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx, js_modules/dagster-ui/packages/ui-core/src/graph/asyncGraphLayout.ts, js_modules/dagster-ui/packages/ui-core/src/util/__tests__/hashObject.test.ts, js_modules/dagster-ui/packages/ui-core/src/util/hashObject.ts
Currently for large organizations our existing hash function just JSON.stringifies the arguments to our graph layout algorithm. The issue with this is that the arguments can be over 100MB when stringified which leads to a lot of memory being used that can cause the browser to crash. To get around this use MurmurHash3 to minimize memory usage. 
jest tests
App-proxy - navigate the app of an org with a large workspace and saw that the memory crashing stopped occurring.
spot checked with console.logging that we were getting deterministic hashes.
=> Use MurmurHash3 to hash keys for indexeddb caching

python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py, python_modules/libraries/dagster-fivetran/dagster_fivetran/translator.py, python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/deprecated/test_load_from_instance.py
Right now, the Fivetran multi-asset is still built setting a group name on the `multi_asset` itself. This errors if you try to return an `AssetSpec` from the translator with a group name attached. This PR moves the group name to specs, and tests that a translator can properly alter the group name of an asset.
=> [dagster-fivetran] Support setting group names on per-asset basis thru translator

examples/docs_snippets/docs_snippets/guides/components/index/34-dg-component-check-defs.txt, examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/components/utils.py, python_modules/libraries/dagster-dg/dagster_dg/cli/utils.py
The previous implementation has windows-specific problems. Use the same method that we use without issue for `dagster dev` currently instead. Addresses https://github.com/dagster-io/dagster/issues/28681.
Run dg dev in windows CI, no more file permissions errors
[dg] Fixed an issue where `dg dev` failed with a temporarily file permissions error when running on Windows. Thanks [@polivbr](https://github.com/polivbr)!
=> Make create_temp_workspace_file in dagster-dg match the temporary workspace file creation path that dagster dev uses

python_modules/dagster-test/dagster_test/toys/freshness.py, python_modules/dagster/dagster/_core/definitions/freshness.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_internal_freshness.py
As discussed in https://dagsterlabs.slack.com/archives/C08F6TSCFCJ/p1746226913600029, it does not make sense to have time window freshness policies with fail or warn windows shorter than 1 minute. This PR adds validation to enforce this limit.
Technically a breaking change but should be safe since we don't have any external users creating the new freshness policies yet. We'll advise the freshness design partners of these limits ahead of launch. Will also add to the new freshness docs in a stacked PR.
bk
=> Enforce lower limit of 1 minute for time window freshness parameters

python_modules/dagster/dagster/_grpc/server.py, python_modules/dagster/dagster/_utils/path.py, python_modules/dagster/dagster_tests/utils_tests/test_path.py
Fix an issue where running `dg` in a workspace that depends on executables in the constituent projects wasn't actually referencing those
New test case, run dg dev in a workspace against a project with dbt installed and verify that it is referencing the one in the project now
Fixed an issue where specifying `executable_path` in a workspace.yaml file to run code locations in a different virtual environment would not correctly inherit the PATH of that virtual environment in the code location.
=> Add virtual env folder to PATH when using a venv executable_path in dagster dev

js_modules/dagster-ui/packages/ui-core/src/assets/AutoMaterializePolicyPage/PolicyEvaluationTable.tsx
When the automation condition description is long, the word breaks are ugly:
Viewed page
=> fix word breaking for evaluation links

python_modules/dagster/dagster/_daemon/auto_run_reexecution/auto_run_reexecution.py, python_modules/libraries/dagster-airlift/dagster_airlift/core/monitoring_job/builder.py, python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_monitoring_job.py
We've realized that allowing for "arbitrary history import" is a trickier problem than we initially thought. Dagster currently synonymizes increasing "storage id" in the event log with increasing "event order", but Airlift V2 currently breaks this by potentially inserting runs which occur in the "middle" of history - IE if I run the airflow monitoring job on a time range which is not the most recently processed one, I can insert runs in the middle of the timeline. This can have weird operational affects on downstream event processors which will pick up those runs in the middle of the timeline and kick off side effects, like declarative automation and alerts
Instead of playing a game of "whack-a-mole" to make sure every callsite properly handles "historical runs", we want to try to avoid …
=> [dagster-airlift] Sensor changes for historical runs

python_modules/dagster/dagster/_config/source.py, python_modules/dagster/dagster/_utils/tags.py, python_modules/dagster/dagster_tests/core_tests/config_types_tests/test_source_types.py, python_modules/libraries/dagster-shared/dagster_shared/utils/__init__.py
This seems to be clearly what the user would intend when using this field.
New test case
Fixed an issue where setting an environment variable to the string "false", "0" or "None" for a dagster config field using a BoolSource would evaluate to True.
=> Fix BoolSource env vars evaluating to true when they are set to a false-y string

python_modules/dagster-graphql/dagster_graphql/implementation/events.py, python_modules/dagster-graphql/dagster_graphql/implementation/execution/__init__.py, python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py, python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py, python_modules/dagster/dagster/_core/instance/__init__.py
only shows asset materialization failure events if the `read_asset_materialization_failures` feature is enabled. Does some lite refactoring to make this repeatable  
manually tested, see https://github.com/dagster-io/internal/pull/15561 for before and after in the UI
=> only show failed to materialize events in run logs reading failure events is enabled

python_modules/libraries/dagster-dlt/dagster_dlt/components/dlt_load_collection/component.py, python_modules/libraries/dagster-dlt/dagster_dlt_tests/test_dlt_load_collection_component.py
Fixes the values we yield from dlt component execution. Previously we'd yield the actual pipeline results instead of what the dlt resource emits from its run method.
New test which explicitly runs a component defined asset.
=> [dagster-dlt] Fix component execution

js_modules/dagster-ui/packages/ui-core/src/assets/AssetHealthSummary.tsx
=> [ez][ui] fix space between check s in asset health report card

python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_resource.py
Fixes #29918.
The error was introduced in https://github.com/dagster-io/dagster/pull/29650 when addressing this [comment](https://github.com/dagster-io/dagster/pull/29650#discussion_r2064866321).
Context:
When creating an asset definition, it is allowed to use `OpExecutionContext` as the type hint for the context, like
```python
@dbt_assets(manifest=manifest)
def my_dbt_assets(context: OpExecutionExecution, dbt: DbtCliResource):
...
```
Issue:
We removed the `suppress(DagsterInvalidPropertyError)` statement in `get_updated_cli_invocation_params_for_context`, and used `assets_def = context.assets_def if isinstance(context, AssetExecutionContext) else None` instead. The problem is that the context may be typed as `OpExecutionContext` even though the context is an instance of …
=> [dagster-dbt] Fix dbt cli invocation params for OpExecutionContext

python_modules/libraries/dagster-dg/dagster_dg/context.py
Currently `should_run_dagster_in_process` can return True when `dagster` is not actually installed in the `dg` environment. This can cause real-world isolated tool `dg` installations to fail.
=> [dg] Make should_run_dagster_in_process check for dagster availability (BUILD-1190)

python_modules/dagster/dagster/components/__init__.py
[components] `ResolvedAssetKey` is now exported from `dagster.components`
=> [components] expose ResolvedAssetKey from top

python_modules/libraries/dagster-databricks/dagster_databricks/_test_utils.py, python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_pipes.py
Addresses https://github.com/dagster-io/dagster/issues/29526, by adding a pytest `skipif` condition on the presence of the `DATABRICKS_HOST` environment variable. It appears these tests were built assuming AWS infrastructure, so some basic parsing of the URL was done to set the `node_type_id` to Azure equivalents, with a fallback to the previous default.
Some basic cleaning for typos and unused code was done elsewhere in the module.
Locally targeting the `dagster-databricks` library path.
=> [dagster-databricks] Skip tests reliant on external infrastructure

python_modules/dagster/dagster/components/resolved/model.py, python_modules/dagster/dagster_tests/components_tests/resolution_tests/test_resolved.py
Adds `Resolver.passthrough()`, which does not resolve/process the field value. Useful to prevent a string field from having template variables resolved.
Unit tests.
> [dagster-components] Introduced Resolver.passthrough() to avoid processing fields on a component.
=> [resolved] Add Resolver.passthrough()

python_modules/libraries/dagster-dg/dagster_dg/cli/list.py, python_modules/libraries/dagster-dg/dagster_dg/utils/plus/gql.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/plus_tests/test_list_env_plus.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py
When logged into Dagster Plus, makes `dg list env` output whether an env var is configured for each plus scope.
This segment of the env demo never made it into a standalone PR.
```sh
$ dg list env
┏━━━━━━━━━┳━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━┳━━━━━━━━┳━━━━━━┓
┃ Env Var ┃ Value ┃ Components       ┃ Dev ┃ Branch ┃ Full ┃
┡━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━╇━━━━━━━━╇━━━━━━┩
│ BAZ     │       │ subfolder/mydefs │ ✓   │        │      │
│ FOO     │ ✓     │                  │ ✓   │        │ ✓    │
└─────────┴───────┴──────────────────┴─────┴────────┴──────┘
```
> [components] `dg list env` now displays whether env vars are configured in each Dagster Plus scope.
=> [dg list env] Show plus env var state when running dg list env

python_modules/libraries/dagster-airlift/dagster_airlift/core/components/airflow_instance/component.py, python_modules/libraries/dagster-airlift/dagster_airlift/core/job_builder.py, python_modules/libraries/dagster-airlift/dagster_airlift/core/load_defs.py, python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_component_defs.py
Allows component-based Airlift to use the AirflowFilter API, as well as disable source code retrieval.
New unit tests
=> [dagster-airlift] allow for components-based filtering

python_modules/libraries/dagster-airbyte/dagster_airbyte/asset_decorator.py, python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/beta/test_asset_specs.py
Following changes made in https://github.com/dagster-io/dagster/pull/29968.
~~This PR sets the `group_name` using `replace_attributes(group_name=...)` in the Airbyte asset decorator instead of passing the group name to the multi-asset definitions. This allows users to either set the `group_name` at the spec level in the translator or the asset decorator level without raising an exception.~~
~~Note that if a `group_name` is passed to the asset decorator, it overrides the group name set in the spec.~~
Edit:
After discussion with @benpankow, we will explicitly disallow setting a group name on the asset decorator and in the translator by raising a custom exception.
=> [dagster-airbyte] Raise custom exception on conflicting group_name in Airbyte asset decorator

python_modules/libraries/dagster-airlift/dagster_airlift/core/monitoring_job/builder.py, python_modules/libraries/dagster-airlift/dagster_airlift/core/monitoring_job/event_stream.py, python_modules/libraries/dagster-airlift/dagster_airlift/core/monitoring_job/utils.py
The monitoring job directory is getting excluded from the packaged version of dagster-airlift, this seems like a smoking gun.
I have not been able to reproduce the "directory not included" behavior locally yet.
=> Add init file to monitoring job dir

python_modules/dagster/dagster/_cli/proxy_server_manager.py, python_modules/dagster/dagster/_core/remote_representation/grpc_server_registry.py, python_modules/dagster/dagster/_grpc/proxy_server.py, python_modules/dagster/dagster/_grpc/server.py
In https://github.com/dagster-io/dagster/pull/28991 we moved from one thread per code location making heartbeat pings to a single background thread iterating through each code location making heartbeat pings. This means that if there are many origins or slow origins that its possible for a code server to miss its heartbeat and shut down incorrectly. This resolves that by moving back to one heartbeat thread per code location.
Exiting test coverage for dagster dev, plus:
Create a workspace.yaml with 6 code locations that is slow to start up (e.g. a time.sleep(15) at the start)
Before: `dagster dev` would fail to start up some code locations with an error since they never got an initial heartbeat
Now: starts up correctly
Fixed an issue where `dagster dev` would sometimes raise a gRPC error …
=> make one thread per origin in ProxyServerManager

python_modules/dagster/dagster/_grpc/impl.py
**Version**: 1.10.14
The gRPC server implementation contains a Local File Inclusion (LFI) vulnerability. It exists in the `ExternalNotebookData` endpoint, which is designed to load notebook data for integration with Dagster workflows.
The issue occurs because the `get_notebook_data` function performs insufficient path validation, only checking if the file path ends with `.ipynb`. An attacker with access to the gRPC server can craft requests that include traversal sequences (`../`) to read arbitrary files by appending `.ipynb` to any path. The use of `os.path.abspath()` in the implementation does not prevent directory traversal attacks.
By default, the gRPC server binds to localhost, limiting remote exploitation. However, in custom deployments where the server is bound to external …
=> Fixed local file inclusion vulnerability in gRPC server's `ExternalNotebookData` endpoint

python_modules/automation/tox.ini
This regressed again:
https://github.com/dagster-io/dagster/pull/29903
https://github.com/dagster-io/dagster/pull/29871
I'm just removing for the time being because as far as I can tell, this is just alerting us to a change in docs formatting and hardly seems worth halting the entire build for.
I think when we reintroduce, we should figure out:
- why this has been bouncing back and forth between passing and failing
- whether there's a better home for it than in this tox command. If it were actually captured in pytest, then we'd be able to more easily mute around its failures directly with Buildkite Test Engine. And it doesn't really seem related to to the automation module anyway - it's presumably only relevant to these two integrations.
=> Temporarily remove dataproc/spark docs check

python_modules/dagster/dagster/components/resolved/base.py, python_modules/dagster/dagster/components/resolved/core_models.py, python_modules/dagster/dagster_tests/components_tests/resolution_tests/test_resolved.py
Slight tweaks to resolved error messages, providing suggestions for users to use built-in resolved models for common classes (`AssetKey`, `AssetSpec`, `AssetCheckSpec`):
```python
dagster.components.resolved.errors.ResolutionException: Could not derive resolver for annotation
asset_key: <class 'dagster._core.definitions.asset_key.AssetKey'>
Field types are expected to be:
* serializable types, such as str, float, int, bool, list, etc
* Resolvable subclasses
* pydantic Models
* Annotated with an appropriate dagster.components.Resolver
e.g. Annotated[AssetKey, Resolver(fn=..., model_field_type=...)]
An annotated resolver for AssetKey is available, you may wish to use it instead: ResolvedAssetKey
```
Unit test.
> [components] Added suggestions to component model error messages when built-in …
=> [resolved] provide suggestions in error messages where resolved core models exist

python_modules/dagster/dagster/_core/definitions/external_asset.py, python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_source_asset_decorator.py
Reported by a user -- we were not properly passing this information through. Originally, I fixed this by just forwarding the tags through this call, but then I realized there were a lot of other properties we were dropping at the same time.
Switched to using dagster_internal_init instead, and filled in a bunch of other properties (most of which will probably always be None but still)
Fixed an issue that would cause `op_tags` set on `@observable_source_asset`s to be dropped from the underlying step context object when executed.
=> [bug] Fix issue with op_tags being dropped for observable source assets

js_modules/dagster-ui/packages/ui-core/client.json, js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetHealthDataProvider.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-data/types/AssetHealthDataProvider.types.ts, js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphSupplementaryData.oss.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetRecentUpdatesTrend.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/AssetCatalogTablev2.test.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetCatalogTableV2.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetCatalogV2VirtualizedTable.tsx, python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py, python_modules/dagster-test/dagster_test/toys/asset_health.py
Updates the UI to use the asset health resolver on GrapheneAsset. This allows external assets to display health information since they are returned as GrapheneAssets, but not as GrapheneAssetNodes
After this we could switch the sorting to use the sort key on GrapheneAsset, but will do that in a stacked pr
external asset w health status in the UI 
=> [ui] use asset health resolvers on GrapheneAsset instead of GrapheneAssetNode

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNode.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNode2025.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/layout.ts
Was fixing an issue with the Observe UI and noticed that the new asset nodes are clipped occasionally. This is happening because our hover effect is a `scale(1.03)`, but the "3%" varies based on the height of the nodes, which now changes considerably.
We have been doing the `overflow: clip` for about two years (https://github.com/dagster-io/dagster/commit/e5bfb148b638fd5790d612e19b3b57005b06e1cc#diff-5cd3875eb046b0feb171eb764678d4efc1517fa1853515e2f53b044b4dc5795cL393). I removed it, and also removed the "inset" wrapper we were using to give space for the hover effect, and tested the old + new asset nodes in FF + Chrome + Safari.  They all seem fine, and the node positioning is actually simpler with these wrappers and padding removed.
@hellendag any chance you remember what we originally …
=> [ui] Fix clipping in the asset graph on some faceted nodes

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetNodeHealthRow.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetHealthSummary.tsx
Fixes https://linear.app/dagster-labs/issue/OPER-1860/asset-nodes-for-observed-source-assets-should-be-green-not-grey
This PR updates the observe UI to avoid using the "materialize" term on non-materializable assets. 
I wonder if we change all these to say "executed" to avoid needing to pass the definition information down in, but will defer to @braunjj!  It isn't much work to choose the right verb, just involves a bit more context about the nodes.
Fixed:
Tested manually with observable source assets with the faceted nodes feature flag turned on and off. 
[ui] With the Observe UI feature flag enabled, observable assets no longer reference "materialization" status.
=> [ui] Observe UI mentions “materialized” for non-materializable assets

python_modules/dagster/dagster/components/resolved/base.py, python_modules/dagster/dagster/components/resolved/model.py, python_modules/dagster/dagster_tests/components_tests/resolution_tests/test_resolved_from.py
Natively support `Union` types in `Resolvable` models, ended up being quite straightforward.
Unit tests.
=> [resolved] out-of-the-box support for union types

python_modules/dagster/dagster/_core/storage/upath_io_manager.py, python_modules/dagster/dagster/_utils/log.py, python_modules/dagster/dagster_tests/general_tests/test_import.py
Summary:
This is maybe 40ms of import time that can be defered.
Test Plan:
New test case, compare import microbenchmarks
=> defer structllog imports

python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/config/jinja_template_loader.py, python_modules/libraries/dagster-dg/dagster_dg/check.py, python_modules/libraries/dagster-dg/dagster_dg/cli/check_utils.py, python_modules/libraries/dagster-dg/dagster_dg/utils/__init__.py, python_modules/libraries/dagster-dg/dagster_dg/utils/plus/build.py, python_modules/libraries/dagster-dg/dagster_dg/utils/plus/gql_client.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/import_perf_tests/simple_import.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/import_perf_tests/test_import_perf.py
Building off of alex's execellent past work speeding up import times in dagster core, defer relatively expensive imports until they are actually used in a command rather than at import time, with a test to keep them from sneaking back in. There's some additional juice to squeeze here but these are the easy ones.
New test case, manual trials (lowers import time from ~0.5356 seconds to ~0.317 seconds)
=> Defer expensive dg import time dependencies

python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_decorator.py
As title - add the connector ID to help user find the faulty assets def.
=> [dagster-fivetran] Identify asset in group name error message in fivetran_assets decorator

python_modules/libraries/dagster-dlt/dagster_dlt/asset_decorator.py
As title - add the source and pipeline names to help user find the faulty assets def.
=> [dagster-dlt] Identify asset in group name error message in dlt_assets decorator

python_modules/libraries/dagster-shared/setup.py
LoadableBy[str] requires this version to work.
BK (verified manually that 4.10.10 fails with:
```
File "/Users/dgibson/dagster/python_modules/dagster/dagster/_core/storage/dagster_run.py", line 696, in <module>
LoadableBy[str],
~~~~~~~~~~^^^^^
File "/Users/dgibson/.local/share/uv/python/cpython-3.12.9-macos-aarch64-none/lib/python3.12/typing.py", line 398, in inner
return func(*args, **kwds)
^^^^^^^^^^^^^^^^^^^
File "/Users/dgibson/.local/share/uv/python/cpython-3.12.9-macos-aarch64-none/lib/python3.12/typing.py", line 1110, in _generic_class_getitem
_check_generic(cls, params, len(cls.__parameters__))
File "/Users/dgibson/.local/share/uv/python/cpython-3.12.9-macos-aarch64-none/lib/python3.12/typing.py", line 304, in _check_generic
raise TypeError(f"Too {'many' if alen > elen else 'few'} …
```
=> adjust typing_extensions pin floor

python_modules/dagster/dagster/_cli/api.py, python_modules/dagster/dagster/_cli/code_server.py, python_modules/dagster/dagster/_cli/proxy_server_manager.py, python_modules/dagster/dagster/_core/remote_representation/grpc_server_registry.py, python_modules/dagster/dagster/_core/remote_representation/origin.py, python_modules/dagster/dagster/_core/workspace/context.py, python_modules/dagster/dagster/_daemon/controller.py, python_modules/dagster/dagster/_grpc/__init__.py, python_modules/dagster/dagster/_grpc/constants.py, python_modules/dagster/dagster/_grpc/proxy_server.py, python_modules/dagster/dagster/_grpc/server.py, python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_grpc_server_registry.py, python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_persistent.py, python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_ping.py, python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_watch_server.py, python_modules/dagster/dagster_tests/general_tests/import_cli.py, python_modules/dagster/dagster_tests/general_tests/test_import.py, python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py, python_modules/libraries/dagster-celery/dagster_celery/launcher.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/import_perf_tests/test_import_perf.py
grpc was not in the core dagster import but still popped in if you import an API command. Fix that.
New test case
=> remove grpc dependency from api import flow

python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/conftest.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_asset_decorator.py
As title - add the workspace info to help user find the faulty assets def.
=> [dagster-dbt] Identify asset in group name error message in dbt_cloud_assets decorator

js_modules/dagster-ui/packages/ui-core/src/graph/SVGViewportContext.tsx
Persist zoom level to localStorage so that when you visit a graph it restores your previous zoom level.
https://linear.app/dagster-labs/issue/OPER-2016/persist-users-zoom-level-on-the-asset-graph
https://github.com/user-attachments/assets/4125f58c-b4d5-44e1-afab-fe4a197dde83
The setting is shared across all asset-graphs and the zoom appropriate for one might not be appropriate for another but I think this edge case isn't a big deal and it's a better experience overall to preserve it.
=> [Asset Graph] Persist zoom level to localStorage

python_modules/libraries/dagster-dbt/dagster_dbt/utils.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_dbt_semantic_models/models/semantic_model.yml
Similar to https://github.com/dagster-io/dagster/pull/23232.
~~In dbt core 1.8 and higher,~~ we must represent saved queries using the `SavedQuery` class provided by dbt. Otherwise, using selection args with a dbt project that uses saved queries raises an exception.
Edit: This is also required for dbt core 1.7 and higher
[dagster-dbt] An issue occurring when using dbt selection arguments with a dbt project using saved queries has been fixed.
=> [dagster-dbt] Support dbt assets with select with saved queries

python_modules/dagster/dagster/_core/definitions/metadata/source_code.py, python_modules/libraries/dagster-sling/dagster_sling/components/sling_replication_collection/component.py, python_modules/libraries/dagster-sling/dagster_sling/dagster_sling_translator.py, python_modules/libraries/dagster-sling/dagster_sling_tests/test_sling_replication_collection_component.py
Enables code references to replication file for Sling components.
Unit test.
=> [components][dagster-sling] Add code refs to sling files

examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/dg/test_using_env.py
Fix failing test on master which is due to a latent version mismatch between editable `dagster-sling` and non-editable `dagster` in this test specifically. A forward compat change was introduced and now this test is broken.
Updates to use editable for both.
=> fix dg docs env test

python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py, python_modules/libraries/dagster-fivetran/dagster_fivetran/utils.py, python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/conftest.py, python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/deprecated/test_asset_defs.py, python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_asset_specs.py
Fixes a subtle issue which arises with the legacy Fivetran integration APIs when materializing connections whose asset keys are customized by a user-provided translator.
This codepath was not under test (we never materialized these customized assets, just checked the properties of the specs themselves) - added a new test which tests both legacy and modern APIs with translators which manipulate asset keys in varying ways.
> [dagster-fivetran] Fixed an issue with `load_assets_from_fivetran_instance` legacy apis where assets whose asset keys have been customized using a Fivetran translator would lead to an exception.
=> [dagster-fivetran] Fix asset key translation & customization with legacy Fivetran APIs

js_modules/dagster-ui/packages/ui-core/src/app/App.oss.tsx, js_modules/dagster-ui/packages/ui-core/src/app/AppTopNav/AppTopNav.tsx, js_modules/dagster-ui/packages/ui-core/src/app/AppTopNav/AppTopNavContext.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/AssetCatalogTablev2.test.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetCatalogAssetGraph.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetCatalogTableV2.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetsCatalog.tsx
"Full screen" mode causes the page's navigation to disappear. It is intended for use by the lineage page in the catalog. 
Currently if you turn fullscreen mode on, and navigate away by clicking a link from the asset graph's right sidebar (eg. "View in catalog" link for an asset) then fullscreen mode stays on and there's no way to turn it off to see the page's navigation. To fix this I'm adding a second atom `isFullScreenEnabled` and a hook `useFullScreenEnabledView`
https://github.com/user-attachments/assets/cc2962fd-4ac4-4159-b7d6-20626a8b1937
=> [Catalog] Add `isFullScreenEnabled` atom to control whether a view is full page screenable

js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetsGroupedView.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogRateCard.module.css
Noticed a CSS warning related to this property. Also adding some display names for ease of use in dev tools.
No more CSS warning in console. Display names appear in dev tools.
=> [ui] Fix a CSS warning, add some display names

python_modules/dagster/dagster/_core/definitions/decorators/sensor_decorator.py
Missing docstring for the `required_resource_keys` param
N/A
=> [docs] Add docstring for missing `required_resource_keys` param in @sensor

python_modules/dagster/dagster/_core/definitions/assets.py, python_modules/dagster/dagster_tests/definitions_tests/test_asset_spec.py
silent last write wins seems bad 
added test 
[bugfix] `Definitions` and `AssetDefinition` will now warn if they get different `AssetSpec`s with the same key. This will become an exception in 1.11.
=> [Definitions] detect conflicting AssetSpecs

python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py, python_modules/libraries/dagster-dg/dagster_dg/scaffold.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/plus_tests/test_plus_deploy_command.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py, python_modules/libraries/dagster-dg/dagster_dg_tests/test_cache.py, python_modules/libraries/dagster-dg/dagster_dg_tests/utils.py
Now that populating the cache happens in process rather than over IPC, it is not safe to do this when scaffolding a project - it will populate the cache with the plugins in the global environment rather than the plugins in the venv.
Incidentally the same thing happens if you accidentally run dg list plugins in the wrong venv now while in a project. Do we need to do anything more proactive to detect and prevent that?
BK
=> remote populate-cache argument from scaffold_project

python_modules/dagster/dagster/components/cli/list.py, python_modules/dagster/dagster/components/cli/scaffold.py, python_modules/libraries/dagster-dg/dagster_dg/component.py, python_modules/libraries/dagster-dg/dagster_dg/context.py, python_modules/libraries/dagster-dg/dagster_dg/scaffold.py
After https://app.graphite.dev/github/pr/dagster-io/dagster/30127 these dagster-components invocations happen in-process, but still wrap a CLI invocation using CliRunner.
CliRunner is bad (it's intended for testing, doesn't stream, etc.). Move to direct function invocations instead.
BK
=> Move components CLI invocations to be direct function calls

.buildkite/dagster-buildkite/dagster_buildkite/step_builder.py
In theory we're not supposed to get 128 directly and instead are supposed to get 128 + the actual signal. But one came through here:
https://buildkite.com/dagster/internal/builds/108176#0196f93e-d87a-462c-adb4-7d05a409157e
```
Cloning into '/workspace/build/buildkite/dagster/internal/../dagster'...
fatal: unable to access 'https://github.com/dagster-io/dagster.git/': Could not resolve host: github.com
🚨 Error: The command exited with status 128
```
Which seems totally safe and preferred to just retry our way around.
=> Retry exit code 128

js_modules/dagster-ui/packages/ui-core/src/assets/catalog/util.tsx, js_modules/dagster-ui/packages/ui-core/src/search/links.tsx
Historically groups have been tied to a specific code location but we want to move to making them cross code location. More info on that here: https://github.com/dagster-io/internal/discussions/12935
clicked on a group tile and saw the selection input doesnt include a code locatioin filter
=> Make catalog group link to asset table without cross code location filter.

js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/useAllAssets.tsx
in https://github.com/dagster-io/dagster/pull/30179 I included a change to back `useAssetGraphData` by `useAllAssets` which includes external assets. This was a change in behavior and led to asset graphs including non SDAs. Instead we should go back to relying on the `options.externalAssets` prop so that we only include external assets in the asset selection input (which uses this hook and passes this prop) .
Checked that asset graphs no longer include external assets
=> [Asset Graph] Hide non SDAs again

python_modules/dagster/dagster/_core/definitions/asset_check_spec.py, python_modules/dagster/dagster_tests/definitions_tests/test_asset_check_spec.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_freshness_checks.py
Making `AssetCheckSpec` a `@record_custom` in order to make it play nicer with pydantic.
Note that `ImportFrom` does not play nicely with generics so this loosens type safety by changing the typing from "AutomationCondition[AssetCheckKey]" to "AutomationCondition" on AssetCheckSpec.automation_condition/
BK
NOCHANGELOG
=> Make AssetCheckSpec a @record_custom

python_modules/libraries/dagster-dg/dagster_dg/cli/launch.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_launch_commands.py
Supports the `--config/-c` parameter to pass config files to `dg launch`.
New unit test.
> [dg] `dg launch` now supports passing config files through `--config/-c`.
=> [dg launch] Add --config param to load config from file

python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_launch_commands.py
`dg scaffold defs` merged before this PR did, fixes test
=> [fix] fix dg launch test

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
This commit modifies the order of the overload definitions for the asset decorator to ease the creation of custom wrapper that wrap this decorator. Prior to this commit the overload ordering meant that wrapping the asset decorator would result in type checker errors due to the way in which type checkers select which overload definition to use as described here:
https://typing.python.org/en/latest/spec/overload.html#overload-call-evaluation
It is often useful to modify the `asset` decorator to enforce some sort of local policy. For example, locally I need to ensure that `key_prefix` always contains an environment variable. To do that, I would use the following approach:
```python
import functools
from collections.abc import Callable
from typing import Any, cast
import dagster
def wrap[**P, …
```
=> Adjust asset decorator overload order to ease wrapping

python_modules/libraries/dagster-fivetran/dagster_fivetran/__init__.py, python_modules/libraries/dagster-fivetran/dagster_fivetran/components/workspace_component/component.py, python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/conftest.py, python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_component.py, python_modules/libraries/dagster-fivetran/setup.py, python_modules/libraries/dagster-fivetran/tox.ini
Copied from our DOP impl, introduces a `FivetranWorkspaceComponent`, which loads the connections from a Fivetran workspace (potentially with filter) and transforms them into asset definitions.
Curious in particular on the targeting YAML format (in python it accepts a fn as input)
```yaml
type: dagster_fivetran.FivetranWorkspaceComponent
attributes:
workspace:
workspace_id: "{{ env('FIVETRAN_WORKSPACE_ID') }}"
api_key: "{{ env('FIVETRAN_API_KEY') }}"
api_secret: "{{ env('FIVETRAN_API_SECRET') }}"
translation:
group_name: my_group
connector_selector:
by_name:
- my_connector
```
Unit tests.
> [components][dagster-fivetran] Introduced a FivetranWorkspaceComponent which can be used to pull in Fivetran connections into Dagster
=> [dagster-fivetran] Introduce `FivetranWorkspaceComponent`

python_modules/dagster/dagster/__init__.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/integration_test_defs/definitions/definitions_object_relative_imports/defs.yaml, python_modules/dagster/dagster_tests/components_tests/integration_tests/integration_test_defs/validation/basic_component_extra_value_in_a_subfolder/subfolder/defs.yaml, python_modules/dagster/dagster_tests/components_tests/registry_tests/test_registry.py, python_modules/dagster/setup.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/mcp_tests/test_mcp_serve.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_launch_commands.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_list_commands.py
In advance of release, moves top-level symbols from dagster.components to dagster module
> [components] Exports from dagster.components are now available in the top-level dagster module
=> move dagster.components exports to top level

python_modules/dagster/dagster/components/lib/shim_components/sensor.py, python_modules/dagster/dagster_tests/components_tests/shim_components/test_sensor.py
Make a scaffolded sensor "list-able" by default
BK and manual testing
* In `dg` a scaffolded sensor is now loadable and listable by default.
=> Make @sensor loadable after scaffolding

python_modules/libraries/dagster-dg/dagster_dg/cli/scaffold.py, python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_scaffold_commands.py
This adds class names as command aliases for `dg scaffold defs` subcommands when those class names are unique. For example, if I have a component `some_lib.FooComponent`, and that is the only component named `FooComponent`, then I can just do:
```
$ dg scaffold defs FooComponent ...
```
And it will work as if I typed the fully-qualified name. However, if `some_other_lib.FooComponent` is also in scope, the alias is not added and the other above command will fall back to the substring match menu.
When component classnames are unique, you can now use just the classname as an alias for the fully qualified name when running `dg scaffold defs <component>`.
=> [dg] Add classnames as aliases to scaffold defs subcommands (BUILD-1225)

python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster/components/testing.py, python_modules/dagster/dagster_tests/testing_tests/basic_tests.py
Add `component_defs`, a helper function for creating a `Definitiions` object from a component instance. This enables scenarios of easily utilizing the Pythonic interface for a component and getting a `Definitions` object out of it.
BK
* Added `dagster.components.testing.component_defs` utility to help with testing components.
=> [components] component_defs

python_modules/dagster/dagster/components/component/component.py, python_modules/dagster/dagster_tests/testing_tests/basic_tests.py
For cases when you want to directly test the templating logic using a dictionary rather than a yaml file. This dictionary is what would be passed to `attributes` key of the yaml file.
BK
* Added Component.from_attributes_dict
=> [components] Add Component.from_attributes_dict

python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/commands/job/__init__.py, python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/commands/run/__init__.py, python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/gql.py
Adding the `--wait` flag to `dagster-cloud job launch` is particularly useful in CI pipelines where you're wanting to launch a job to test changes and ensure the dagster run succeeds before merging.
Local manual testing
> [dagster-cloud-cli] Add `--wait` to `job launch` command
=> [dagster-cloud-cli] Add `--wait` to `job launch` command

python_modules/dagster/dagster/components/lib/shim_components/schedule.py, python_modules/dagster/dagster_tests/components_tests/shim_components/test_schedule.py
Make a scaffolded schedule list-able and executable by default
BK and manual test
* Scaffolded schedules in `dg` are now loadable by default.
=> schedule decorator executable

python_modules/libraries/dagster-dg/dagster_dg_tests/cli_tests/test_custom_help_format.py, python_modules/libraries/dagster-dg/setup.py
Summary:
Now that dg is in-environment during development, this pin is more onerous than it should be. Add an upper bound limit instead (since typer does do breaking changes from time to time).
Test Plan: BK
=> Make dagster-dg typer pin less strict

python_modules/dagster-test/dagster_test/components/simple_asset.py, python_modules/dagster/dagster/components/component/component.py, python_modules/dagster/dagster/components/core/defs_module.py, python_modules/dagster/dagster/components/testing.py, python_modules/dagster/dagster_tests/components_tests/cli_tests/test_commands.py, python_modules/dagster/dagster_tests/testing_tests/basic_tests.py, python_modules/dagster/dagster_tests/testing_tests/some_value_simple_asset_component.yaml
Add `Component.from_yaml_path` where you can point directly to a yaml path and load a component instance into memory. Useful for test cases where you have a test per yaml file.
BK
* Added `Component.from_yaml_path` which is useful for testing.
=> [components] Component.from_yaml_path

python_modules/libraries/dagster-fivetran/tox.ini
dagster-dg[test] depends on create-dagster now
=> Fix fivetran BK

python_modules/dagster/dagster/__init__.py, python_modules/dagster/dagster/components/__init__.py, python_modules/dagster/dagster/components/component/component_loader.py, python_modules/dagster/dagster/components/component_scaffolding.py, python_modules/dagster/dagster/components/core/defs_module.py, python_modules/dagster/dagster_tests/components_tests/code_locations/python_script_location/defs/multiple_component_instances/component.py, python_modules/dagster/dagster_tests/components_tests/code_locations/python_script_location/defs/multiple_component_instances_defs_py/component.py, python_modules/dagster/dagster_tests/components_tests/code_locations/python_script_location/defs/script_python_decl/component.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/integration_test_defs/pythonic_components/relative_import/component.py, python_modules/dagster/dagster_tests/components_tests/unit_tests/test_pipes_subprocess_script_collection.py, python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_component_defs.py
Rename `@component` to `@component_instance`. Allow multiple declaration of `component_instance` in the same file.
BK and manual project scaffolding.
* Added `@component_instance` to replace `@component` and allows multiple component instances in a python file.
=> @component -> @component_instance. Allow multiple instances in file

python_modules/dagster/dagster/components/core/defs_module.py, python_modules/dagster/dagster_tests/components_tests/code_locations/python_script_location/defs/multiple_definitions_calls/defs.py, python_modules/dagster/dagster_tests/components_tests/unit_tests/test_pipes_subprocess_script_collection.py
This PR proposes allowing multiple `@definitions` declarations in files in the `defs` hierarchy and automatically merging them together.
This can risk adding duplicative definitions to a project, most likely when importing a `@definitions`-decorated function from one module to another. 
However I do think this is a fairly arbitrary limitation that users would expect to "just work."
Manually tested on a scaffolded project
* Can define multiple `@definitions`-decorated functions in a single module in the `defs` hierarchy and they are automatically merged and incorporated into the project.
=> allow multiple @definitions

python_modules/dagster-test/dagster_test/components/test_utils/test_cases.py, python_modules/dagster/dagster/__init__.py, python_modules/dagster/dagster/components/__init__.py, python_modules/dagster/dagster/components/resolved/base.py, python_modules/dagster/dagster/components/resolved/core_models.py, python_modules/dagster/dagster/components/resolved/model.py, python_modules/dagster/dagster_tests/components_tests/resolution_tests/test_resolvable_model.py, python_modules/dagster/dagster_tests/components_tests/resolution_tests/test_resolved.py, python_modules/libraries/dagster-dbt/dagster_dbt/components/dbt_project/component.py, python_modules/libraries/dagster-dlt/dagster_dlt/components/dlt_load_collection/component.py, python_modules/libraries/dagster-sling/dagster_sling/components/sling_replication_collection/component.py
Flip from having types opt-in to being injectable to allowing it by default.
This base PR just handles it at the level of fields on Resolved objects. 
added test
=> [resolved] default injectable

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/mcp_server.py, python_modules/libraries/dagster-dg-cli/setup.py, python_modules/libraries/dagster-dg-cli/tox.ini, python_modules/libraries/dagster-dg-core/setup.py
As we likely move away from dagster-dg being only installed in an isolated global environment, we have to be a bit stricter about what we bring in. In that light, make mcp a separate extra while it's still an experimental feature.
`dagster mcp serve` with and without the relevant extra installed
=> Add an mcp extra to dagster-dg

python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py
Update how we name fivetran assets in the Fivetran asset factory - we use the connector name instead of the connector ID to ease discoverability when looking at a run.
=> [dagster-fivetran] Use connector name as fivetran_assets name in Fivetran asset factory

python_modules/libraries/dagster-k8s/dagster_k8s/executor.py, python_modules/libraries/dagster-k8s/dagster_k8s/launcher.py, python_modules/libraries/dagster-k8s/dagster_k8s/ops/k8s_job_op.py, python_modules/libraries/dagster-k8s/dagster_k8s/utils.py, python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_executor.py, python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_launcher.py
If the `DAGSTER_CLOUD_DEPLOYMENT_NAME` env var is set on container context, propagate this info into pod labels for the k8s run launcher and k8s executor, since tracking down a run just by ID on a multi-deployment organization can be quite tricky.
> [dagster-k8s] Pods created by the Kubernetes run launcher and executor from Dagster Plus now include the  `dagster/deployment-name` label.
=> [dagster-k8s] include dagster/deployment-id label on pods

js_modules/dagster-ui/packages/ui-core/src/runs/LogsToolbar.tsx
The op selection `Suggest` in the compute logs on the Run page is susceptible to cutting off long step names, which can also make it hard to disambiguate different attempts of the same step. To alleviate this, make the input and menu wider.
There is also an open issue to fix selecting a repeated step from the Gantt chart, which currently just (incorrectly) selects the first attempt of the step. That will require a more substantial fix, so I'm trying to make the workaround a little more palatable in the meantime.
Execute a run that repeats a step attempt. Verify that the menu is wider.
=> [ui] Widen suggest component for compute log op selection

python_modules/libraries/create-dagster/create_dagster/scaffold.py, python_modules/libraries/create-dagster/create_dagster_tests/test_scaffold_commands.py, python_modules/libraries/dagster-dg-cli/setup.py
- Add a `[local] extra to `dagster-dg-cli`, that installs `dagster` as a pinned dependency
- Change scaffolded deps to install `dagster-dg-cli[local]` for the dev dependency group
=> [dg] Add [local] extra to dagster-dg-cli with dagster dependency (BUILD-1241)

js_modules/dagster-ui/packages/ui-core/src/live-data-provider/LiveDataThreadManager.tsx
It appears that as of https://github.com/dagster-io/dagster/pull/29658, asset statuses are not reliably live-updating when materialized.
This appears to be due to the invalidation of the cache in `LiveDataThreadManager`, which removes the key from the list of `lastFetchedOrRequested` keys but does not re-add the keys to the `unfetchedKeys` list. They are then skipped by `determineKeysToFetch`, and not requested for updates.
Fix this by re-adding the keys to `unfetchedKeys` when invalidating the cache, thus allowing them to be fetched again.
Load the app locally, view an asset. Materialize it from the lineage view, verify that the materialization status updates live, including to successful completion of the materialization.
[ui] Fix live updating of asset materialization statuses in asset …
=> [ui] Repair live updating for materializing from asset graph

python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster/components/core/defs_module.py, python_modules/dagster/dagster_tests/components_tests/test_code_references.py
Ignore non `AssetsDefinition`, `AssetSpec` types (cacheable assets, source assets) when mapping over specs to attach code reference info.
=> [fix] fix map_asset_specs call on non-spec types in CompositeYamlComponent

python_modules/libraries/dagster-shared/dagster_shared/record/__init__.py, python_modules/libraries/dagster-shared/dagster_shared_tests/test_record.py
Alternative to #30232. Points users to use BaseModel instead of @record if trying to attach pydantic.Field metadata to a resolved model field.
=> [record] Explicitly error when attaching pydantic.Field to @record

python_modules/dagster-test/dagster_test/dg_defs/composites/python/component.py, python_modules/dagster-test/dagster_test/dg_defs/composites/yaml/component.yaml, python_modules/dagster/dagster/_core/remote_representation/external_data.py, python_modules/dagster/dagster/components/core/defs_module.py, python_modules/dagster/dagster_tests/components_tests/test_definitions.py
Adds leaf components instance information to the repo snapshot containing defs relative key string and full type name. 
Adds `ComponentTreeSnap` as the outer container for component information and to start just adds `leaf_instances` to start as this is the most useful information in the short term. 
added test
=> [components] add Snaps

js_modules/dagster-ui/packages/ui-core/src/runs/RunTimeline.tsx
On the run timeline, when hovering over a run chunk, show the relative time of the runs instead of the sliced run ID. This should hopefully help provide better context about the order of the runs in the list.
Hover on run timeline, verify that relative time is displayed instead of the run ID.
[ui] Show relative start time on runs in run timeline hover lists.
=> [ui] Show relative time for runs in timeline hover list

python_modules/dagster/dagster/_cli/api.py, python_modules/dagster/dagster/_cli/code_server.py, python_modules/dagster/dagster/_cli/utils.py, python_modules/dagster/dagster/_cli/workspace/cli_target.py, python_modules/dagster/dagster/_core/code_pointer.py, python_modules/dagster/dagster/_core/remote_representation/origin.py, python_modules/dagster/dagster/_core/types/loadable_target_origin.py, python_modules/dagster/dagster/_core/workspace/autodiscovery.py, python_modules/dagster/dagster/_core/workspace/config_schema.py, python_modules/dagster/dagster/_core/workspace/load.py, python_modules/dagster/dagster/_core/workspace/load_target.py, python_modules/dagster/dagster/_grpc/server.py, python_modules/dagster/dagster/_grpc/utils.py, python_modules/dagster/dagster_tests/cli_tests/test_workspace_config_schema.py, python_modules/dagster/dagster_tests/cli_tests/workspace_tests/toml_tests/test_toml_loading.py, python_modules/libraries/create-dagster/create_dagster/templates/PROJECT_NAME_PLACEHOLDER/pyproject.toml.jinja, python_modules/libraries/create-dagster/create_dagster/templates/PROJECT_NAME_PLACEHOLDER/src/PROJECT_NAME_PLACEHOLDER/definitions.py.jinja, python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/commands/workspace/__init__.py, python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/config_utils.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/launch.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/list.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/utils.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_check_defs_command.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_dev_command.py, python_modules/libraries/dagster-dg-core/dagster_dg_core/config.py, python_modules/libraries/dagster-dg-core/dagster_dg_core/context.py, python_modules/libraries/dagster-dg-core/dagster_dg_core_tests/test_context.py, python_modules/libraries/dagster-shared/dagster_shared/cli/__init__.py
removes `definitions.py` and adds `autodefs_module` config 
existing scaffolding tests
=> [create-dagster] move scaffold to autodefs

python_modules/dagster-webserver/dagster_webserver_tests/test_app.py, python_modules/dagster/dagster/_core/telemetry.py, python_modules/dagster/dagster_tests/cli_tests/command_tests/test_telemetry.py, python_modules/dagster/dagster_tests/core_tests/test_telemetry_upload.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_telemetry.py, python_modules/libraries/dagster-shared/dagster_shared/telemetry/__init__.py
Without this, if anybody adjusts the log level of the root logger, this logger might also write to stdout.
With dbt installed, dg list defs no longer prints telemetry logger output
Fixed an issue where `dg` commands would sometimes output extra dagster_telemetry_logger ines to stdout at the end of commands.
=> Don't propagate the telemetry logger to the root logger

python_modules/dagster/dagster/components/component/component.py, python_modules/dagster/dagster/components/component/template_vars.py, python_modules/dagster/dagster/components/core/defs_module.py, python_modules/dagster/dagster_tests/components_tests/template_vars_tests/template_vars.py, python_modules/dagster/dagster_tests/components_tests/template_vars_tests/test_basic_template_vars.py, python_modules/dagster/dagster_tests/components_tests/template_vars_tests/test_fn_decorators.py, python_modules/dagster/dagster_tests/components_tests/utils.py, python_modules/libraries/dagster-dg-core/dagster_dg_core/check.py
Right now the only way to inject additional scope in the Component templating engine is create a distinct component subtype and override the class method `get_additional_scope`.
In dogfooding Components DOP –– especially to `ExecutableComponent` –– I found I was making trivial subclasses whose only purpose was to define additional scope for udfs.
Scope is an overloaded, very generic term. So this PR proposes the use of the term "template var" instead of scope.
This PR makes it so that you no need to override `get_additional_scope` to define a template variable. Instead they are defined in two different ways:
1. Annotate a `@staticmethod` on a class. This associates the template variable with the _class_, and this is introspectable when the class is imported. This is known as a _static_ …
=>  @template_var

python_modules/dagster/dagster/components/core/context.py, python_modules/dagster/dagster/components/core/defs_module.py, python_modules/dagster/dagster/components/core/load_defs.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/integration_test_defs/definitions/special_names_at_levels/folder_with_component_py/asset.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/integration_test_defs/definitions/special_names_at_levels/folder_with_component_py/component.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/integration_test_defs/definitions/special_names_at_levels/folder_with_definitions_py/asset.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/integration_test_defs/definitions/special_names_at_levels/folder_with_definitions_py/definitions.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/integration_test_defs/definitions/special_names_at_levels/folder_with_definitions_py/inner/asset.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/integration_test_defs/definitions/special_names_at_levels/top_level.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/test_definitions_autoload.py
Moves us to a world where autoloading behavior is more straightforward by adding a flag that turns off the `definitions.py` and `component.py` special branching behavior. These files are treated as normal Python source files if the flag is set. Defaults to off.
```python
defs = load_defs(
module,
project_root=Path(__file__).parent,
terminate_autoloading_on_keyword_files=False,
)
```
New unit test.
=> [components] Add flag to disable special autoload handling for definitions.py, component.py

python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster/components/core/defs_module.py
In certain code paths (that are constrained in certain ways) we allow SourceAssets and CacheableAssetsDefinitions to be mapped. This refactors the inner function that allows that to not use a boolean argument. To use a fancy term this reduces the cyclomatic complexity of the code path, making it easier to understand. 
BK
=> Refactor map_resolved_asset_specs to eliminate boolean flag

python_modules/dagster/dagster/components/core/context.py, python_modules/dagster/dagster/components/core/defs_module.py, python_modules/dagster/dagster/components/core/load_defs.py, python_modules/dagster/dagster/components/core/tree.py, python_modules/dagster/dagster/components/resolved/context.py, python_modules/dagster/dagster_tests/components_tests/code_locations/component_component_deps/defs/depends_on_my_python_defs/definitions.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/code_locations/dependency_on_dbt_project_location/defs/depends_on_dbt/definitions.py, python_modules/libraries/dagster-dlt/dagster_dlt/components/dlt_load_collection/component.py, python_modules/libraries/dagster-dlt/dagster_dlt_tests/test_dlt_load_collection_component.py, python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_component.py
While writing testing utilities and other code I've noted that we have a global context variable to store a ComponentLoadContext. I think this is easier to screw up and unnecessary. The system will be better, more testable, and more modular if we can get away with not having it.
Two things in order to accomplish this
* If you need access to the context, you have to do in a `@definitions` callback or a `build_defs`. I think the users will thank us for pushing more compute out of the import path
* In another case, I added a stash dictionary to the `ResolutionContext`. I think this is the right thing to do, as it solidfies as ResolutionContext as "lower" in the stack than Components. The component load context is only retrieved from the stash when we know we are dealing with components code. …
=> Eliminate global component load context

python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster_tests/core_tests/definitions_tests/test_definitions_object.py
Reverts #30372 which was causing strange errors that are seemingly non-deterministic. Example BK [run](https://buildkite.com/dagster/dagster-dagster/builds/124463/steps?sid=019731bd-8070-4bc3-b1ed-bbbcbafb76f5).
BK
=> Revert #30372

python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_schedules.py
Like we did in https://github.com/dagster-io/dagster/pull/29554 but for dbt schedules
Update tests with BK
[dagster-dbt] `build_schedule_from_dbt_selection` now supports a `selector` argument, allowing you to use yaml-based selectors.
=> [dagster-dbt] Support --selector for build_schedule_from_dbt_selection

js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx, python_modules/dagster-graphql/dagster_graphql/implementation/fetch_asset_health.py, python_modules/dagster-test/dagster_test/toys/asset_health.py
Some assets have no node on the asset graph (for example, you can report an asset materialization for a key that otherwise has no references in the asset graph, see the new examples added to the toys repo to see an example)
Computing the health for an asset sometimes required getting the node for an asset from the asset graph, this would fail for the kinds of assets described above since there is no node in the asset graph. This PR fixes that by adding a different path for each health component if the asset has no node in the graph. For materialization, we are able to compute some information based on the record in the DB (this falls short if the reported materializations have partitions associated with them, but we don't handle this perfectly in other parts of the UI right now, so i …
=> [asset health] handle computing health data for assets with no definition

python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster_tests/core_tests/definitions_tests/test_definitions_object.py
This is take two at a simpler `get_job_def`, but this one is even simpler. It only gets the job definitions passed directly to the `jobs` parameter. Anything "smarter" than that will be left to `resolve_job_def`.
BK
=> Make Definitions.get_job_def much simpler

python_modules/dagster/dagster/_cli/workspace/cli_target.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/launch.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_launch_commands.py, python_modules/libraries/dagster-shared/dagster_shared/cli/__init__.py
Patterned after #30226, adds `dg launch` options which pattern after those available for `dagster job launch` etc which point to code by its path/module/package.
=> [dg launch] Add support for workspace options

python_modules/libraries/create-dagster/create_dagster/cli/scaffold.py, python_modules/libraries/create-dagster/create_dagster/scaffold.py, python_modules/libraries/create-dagster/create_dagster_tests/test_scaffold_commands.py
The project and workspace scaffold arguments were different in subtle and unneeded ways. Use the same path argument and the same behavior, and drop the 'dagster-workspace' default, which always surprises me during testing.
BK, scaffold a workspace locally
[create-dagster] The `create-dagster workspace` command now accepts the same required path argument as the `create-dagster project` command, instead of defaulting to a `dagster-workspace` subfolder of the current working directory.
=> bring create-dagster workspace args in line with create-dagster project args

python_modules/dagster/dagster/components/testing.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/test_definitions_autoload.py, python_modules/dagster/dagster_tests/components_tests/utils.py, python_modules/libraries/dagster-dlt/dagster_dlt_tests/test_dlt_load_collection_component.py, python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_component.py, python_modules/libraries/dagster-sling/dagster_sling_tests/test_sling_replication_collection_component.py
Testing scaffolding and loading definitions is a pain point, but for our own development as well as our users. We write bespoke, brittle, and slow tests that are no fun to write and debug.
This proposes a new approach based on lightweight sandboxing. Instead of creating entire projects (or entire virtual environments God forbid) we create just a temporary folder and rely on our context and request objects to provide isolation.
You can see them applies to our dlt, fivetran, and sling tests here. I think it provides a nice degree of flexibility that can handle a variety of use cases (e.g. the dlt test harness, which is a beast) while minimizing boilerplate.
Docblock:
```python
@contextmanager
def scaffold_defs_sandbox(
*,
component_cls: type,
component_path: Optional[Union[Path, str]] = …
```
=> scaffold_defs_sandbox utility for testing custom component types

python_modules/dagster/dagster/_daemon/daemon.py, python_modules/dagster/dagster_tests/daemon_tests/test_dagster_daemon.py
https://github.com/dagster-io/dagster/pull/30189#issuecomment-2930805760
```
python -m pytest python_modules/dagster/dagster_tests -k backfill
```
> feat(backfill_daemon): make default use_threads=True, num_workers=4
=> feat(backfill_daemon): make default use_threads=True, num_workers=4

python_modules/dagster/dagster/components/lib/executable_component/component.py, python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_asset_check_only.py
Adding support for `tags` on `ExecutableComponent`, which ends up getting assigned to the underlying `op`. This is fairly critical decision, actually, because we are deciding whether or not to _hide_ ops (which this does) or to be transparent (by having the schema to op: name: foo).
BK
=> Support tags in both the asset and asset check use case

python_modules/dagster/dagster/components/lib/executable_component/component.py, python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_asset_check_only.py
Now that we have some common test cases, easy to add description to ExecutableComponent. Again this becomes the op description.
BK
=> Add description to ExecutableComponent

python_modules/libraries/dagster-airbyte/dagster_airbyte/__init__.py, python_modules/libraries/dagster-airbyte/dagster_airbyte/components/workspace_component/component.py, python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/beta/test_component.py, python_modules/libraries/dagster-airbyte/tox.ini
Pattered after the `FivetranAccountComponent`, introduces a `AirbyteCloudWorkspaceComponent` which loads the connections from an Airbyte Cloud and transforms them into asset definitions.
```yaml
type: dagster_airbyte.AirbyteCloudWorkspaceComponent
attributes:
workspace:
workspace_id: "{{ env('AIRBYTE_WORKSPACE_ID') }}"
client_id: "{{ env('AIRBYTE_CLIENT_ID') }}"
client_secret: "{{ env('AIRBYTE_CLIENT_SECRET') }}"
translation:
group_name: my_group
connection_selector:
by_name:
- my_connection
```
Unit tests.
> [components][dagster-airbyte] Introduced a AirbyteCloudWorkspaceComponent which can be used to pull in Airbyte Cloud connections into Dagster
=> [dagster-airbyte][components] Introduce AirbyteCloudWorkspaceComponent

python_modules/dagster/dagster/components/lib/executable_component/component.py
In the spirit of only having one way of doing things, I'm going to pull partitions definition of the Executable Component, and rely on it in `AssetSpec` only. Worthy of discussion. If we do this we probably want some group assignment primitive as there are a few properties like this.
BK
=> Remove partitions_def from ExecutableComponent

python_modules/dagster/dagster/components/lib/executable_component/component.py, python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_asset_check_only.py, python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_executable_component_in_memory.py, python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_execute_fn_params.py
This PR enforces more strict rules on the parameters of execute_fn of an ExecutableComponent in preparation for supporting parameter passing. Instead of blindly grabbing parameter names we now reuse the logic to handle `ResourceParam`, resource subtypes, and so forth.
BK
=> Require proper resources on the execute_fn

python_modules/dagster/dagster/_cli/definitions.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/check.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/dev.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_check_defs_command.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_dev_command.py, python_modules/libraries/dagster-dg-core/dagster_dg_core_tests/utils.py
Summary:
This regressed a bit when we moved dg to in process - before you could check yaml over the IPC boundary, now you can't. Resolve by temporarily disabling checking yaml in a workspace context. Longer term we can add a gRPC method for checking YAML and use that (which is why check defs still works even after the change, it has always used gRPC).
Test Plan:
dg dev and dg check defs in a workspace using a uv venv now doesn't spew at you
=> Fix logspew in dg dev / dg check defs in a workspace context due to attempting to check yaml

python_modules/dagster/dagster/_utils/schedules.py, python_modules/dagster/dagster_tests/scheduler_tests/test_cron_string_iterator.py
Helper method to get the smallest interval from a given cron string.
Needed to validate a field on cron freshness policy, but likely useful elsewhere so I added it to the schedule utils.
unit tests
=> Smallest interval in cron

python_modules/dagster/dagster/_core/definitions/freshness.py, python_modules/dagster/dagster/_utils/schedules.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_internal_freshness.py
Introduce a new freshness policy type `CronFreshnessPolicy`.
This is very similar in behavior to the cron-based portion of last updated freshness checks.
Evaluation code for this policy will initially be implemented in cloud only (https://github.com/dagster-io/internal/pull/16104), and then ported over to OSS along with `TimeWindowFreshnessPolicy`.
unit tests
=> Introduce `CronFreshnessPolicy`

python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster_tests/core_tests/definitions_tests/test_definitions_object.py
This digs through all the jobs in the `Definitions` object to give higher quality warning (and eventually error) messages.
BK
=> Clearer warning messages in `get_job_def`

python_modules/dagster/dagster/components/lib/executable_component/component.py, python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_asset_check_only.py
Adds a `pool` argument to `ExecutableComponent` which gets passed down to the underlying `multi_asset` and `multi_asset_check`
BK
=> Add pool to executable component

python_modules/dagster/dagster/_grpc/proxy_server.py
The default here should be 180 seconds, but is only set on the real code server, not the proxy server. So repos that take a long time to run this call are more likely to time out when using the proxy server.
add a time.sleep(75) to ExternalRepository on the server. Before it would time out, now it does not.
Fixed an issue where `dagster dev` was sometimes failing to load code locations with a "Deadline Exceeded" error unless the "--use-legacy-code-server-behavior" flag was set.
=> Fix default timeout for ExternalRepository call when using dagster dev

python_modules/dagster/dagster/components/lib/executable_component/python_script_component.py, python_modules/dagster/dagster/components/lib/executable_component/script_utils.py, python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_pipes_subprocess.py, python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_uv_run_component.py
This renames `SubprocessComponent` to `PythonScriptComponent` and moves shared utils to `script_utils.py` for `UvRunComponent` to share as well.
BK
=> SubprocessComponent --> PythonScriptComponent

python_modules/dagster/dagster/_core/events/__init__.py
Noticed this while preparing a demo. Improve the logging for asset check evaluations to actually include if they passed or not.
```
2025-04-06 16:56:11 -0400 - dagster - DEBUG - __ASSET_JOB - 5eddbb3a-1dbc-4b72-b033-53069b2483e5 - 48173 - orders_min_user_id_test - STEP_INPUT - Got input "df" of type "DataFrame". (Type check passed).
2025-04-06 16:56:11 -0400 - dagster - DEBUG - __ASSET_JOB - 5eddbb3a-1dbc-4b72-b033-53069b2483e5 - 48173 - orders_min_user_id_test - ASSET_CHECK_EVALUATION - Asset check 'min_user_id_test' on 'orders' did not pass. Description: 'Minimum value of 1000 not met for column user_id. Found 1'
2025-04-06 16:56:11 -0400 - dagster - DEBUG - __ASSET_JOB - 5eddbb3a-1dbc-4b72-b033-53069b2483e5 - 48173 - orders_min_user_id_test - STEP_OUTPUT - Yielded output "result" of …
```
=> [dg] Better logging message for asset check evals

js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetSelectionSummaryTile.tsx
Make a couple changes to the tile components used in catalog and Dagster+ home.
- Strip down the type required for `AssetSelectionSummaryTileFromSelection` to the minimum, so that I don't need a specific fragment type
- Add a `JobTile` for use in Home. Adding it here since I could see it being useful elsewhere in OSS.
TS, lint, jest. Verify that tiles render correctly in Home.
=> [ui] Tile changes for Home

python_modules/libraries/dagster-shared/dagster_shared/check/functions.py, python_modules/libraries/dagster-shared/dagster_shared_tests/test_check.py
I didnt go dig for the blame, but i have a faint recollection of having to settle for `NoReturn` previously but the proper way to do this is with `Never` https://typing.python.org/en/latest/guides/unreachable.html
added test
=> [check] assert_never -> Never

python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py
Add a utility function for doing bulk metadata updates across all the definitions contained within a `Definitions` object 
updated test
=> add Definitions.with_definition_metadata_update

python_modules/libraries/create-dagster/create_dagster/cli/scaffold.py, python_modules/libraries/dagster-dg-core/dagster_dg_core/utils/__init__.py
Changes the message on project activation using `uv` to have a single copy-pasteable command and ends up with the user in the project folder.
=> Improve activation message when activating a project with uv

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_asset_health.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_health.py
We were always accessing the context to do everything anyway, and this makes it easier to re-use these functions in other places like https://github.com/dagster-io/internal/pull/16144
existing tests
=> functions to get asset health data take a context instead of graphene resolve info

python_modules/libraries/create-dagster/create_dagster/templates/PROJECT_NAME_PLACEHOLDER/pyproject.toml.jinja, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_list_commands.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_scaffold_commands.py, python_modules/libraries/dagster-shared/dagster_shared/seven/__init__.py
Changes the default scaffolded project to include `<root>.components.*` under `project.registry_modules`. This means that when components are scaffolded with either of the below patterns, the pyproject.toml will not be modified because the default pattern will already match the scaffolded module.
- `dg scaffold components Foo`
- `dg scaffold components <root>.components.foo.Foo`
`project.registry_modules` can now accept wildcards (e.g. `foo_bar.components.*`). This will register any module matching the pattern with `dg`.
=> [dg] Add `<root>.components.*` as default registry_modules in new projects

python_modules/dagster/dagster/_core/definitions/job_definition.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_partitioned_assets.py, python_modules/dagster/dagster_tests/core_tests/graph_tests/test_graph.py
This PR fixes [AD-930 - GraphDefinition.to_job() with config blows up if op has custom IO manager](https://linear.app/dagster-labs/issue/AD-930/graphdefinitionto-job-with-config-blows-up-if-op-has-custom-io-manager).
Before the changes made in this PR, this code was raising a `DagsterInvalidDefinitionError` stating that the dummy IO manager was missing:
```python
from dagster import Definitions, Out, graph, op
from dagster._core.storage.fs_io_manager import FilesystemIOManager
@op(out=Out(io_manager_key="dummy"))
def alpha(x: int):
return x
@graph
def my_graph(x):
alpha(x)
my_job = my_graph.to_job(config={"inputs": {"x": 1}})
defs = Definitions(jobs=[my_job], resources={"dummy": FilesystemIOManager(base_dir=".")})
```
The problem: 
When passing a config dictionary to the job, the process …
=> [core] Implement lazy resolution of job configs

js_modules/dagster-ui/packages/ui-core/client.json, js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetSelectionSummaryTile.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/catalog/JobTileQuery.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/catalog/types/JobTileQuery.types.ts
Show the latest run on job tiles for Dagster+ home.
View Home, verify that job tiles have latest run information, and that polling leads to updates.
=> [ui] Show the latest run on job tiles

python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_check_yaml_command.py, python_modules/libraries/dagster-dg-core/dagster_dg_core/check.py, python_modules/libraries/dagster-dg-core/dagster_dg_core/component.py
Allow any valid python symbol component reference to work as a `type` in a `defs.yaml` file when running `dg check yaml`. Prior to this PR only types matching a registered component type or inline components in the defs folder are supported.
New unit test.
Fix a bug with `dg check yaml` where valid component type names were rejected if they were not registered (i.e. visible from `dg check components`).
=> [dg] Allow any python reference to work for yaml check

python_modules/libraries/dagster-dg-core/dagster_dg_core/config.py, python_modules/libraries/dagster-dg-core/dagster_dg_core/context.py, python_modules/libraries/dagster-dg-core/dagster_dg_core_tests/test_context.py
- Per title, emit a warning if `project.autoload_defs` is set but we also find a `<root>/definitions.py` module (which won't be loaded with autoloaded defs).
- Also have config validation error if it detects that `code_location_load_target_module` and `autoload_defs` are both set.
=> [dg] Emit warning when autoload_defs is on and definitions.py found (BUILD-1242)

python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py
If another op has the exact same name, Dagster will be confused when parsing the definitions. We experienced this problem in the dagster-open-platform, where both dlt and Fivetran integration add an op named "hubspot".
Changes were made in [internal](https://github.com/dagster-io/internal/pull/16203), but we should change it here in the asset factory too, to avoid this problem in the future. 
Manual test
=> [dagster-fivetran] Add prefix to op name in build_fivetran_assets_definition

python_modules/dagster/dagster/components/lib/executable_component/component.py
Fixes pyright error from https://github.com/dagster-io/dagster/pull/30578
Given that this PR also introduced the method, I think it's fine to just mark it as a cached_property on the parent. And if we need this to vary depending on implementation, we can fix that later.
=> Mark config_fields as cached_property

python_modules/dagster-graphql/dagster_graphql/implementation/execution/backfill.py, python_modules/dagster-graphql/dagster_graphql/schema/backfill.py, python_modules/dagster/dagster/__init__.py, python_modules/dagster/dagster/_config/pythonic_config/resource.py, python_modules/dagster/dagster/_core/definitions/input.py, python_modules/dagster/dagster/_core/definitions/output.py, python_modules/dagster/dagster/_core/errors.py, python_modules/dagster/dagster/_core/execution/context_creation_job.py, python_modules/dagster/dagster/_core/execution/execution_result.py, python_modules/dagster/dagster/_core/execution/host_mode.py, python_modules/dagster/dagster/_core/execution/plan/execute_plan.py, python_modules/dagster/dagster/_core/execution/plan/utils.py, python_modules/dagster/dagster/_core/remote_representation/external.py, python_modules/dagster/dagster/_core/scheduler/scheduler.py, python_modules/dagster/dagster/_daemon/backfill.py, python_modules/dagster/dagster/_daemon/sensor.py, python_modules/dagster/dagster/components/core/package_entry.py, python_modules/dagster/dagster/components/lib/executable_component/function_component.py, python_modules/dagster/dagster/components/utils.py, python_modules/dagster/dagster_tests/api_tests/api_tests_repo.py, python_modules/dagster/dagster_tests/execution_tests/misc_execution_tests/test_async.py, python_modules/libraries/dagster-airlift/dagster_airlift/core/airflow_instance.py, python_modules/libraries/dagster-airlift/dagster_airlift_tests/integration_tests/test_airflow_instance.py, python_modules/libraries/dagster-shared/dagster_shared/error.py, python_modules/libraries/dagstermill/dagstermill/errors.py
This will allow utilities in dagster-shared, or code in any of our packages, to throw `DagsterError`.
=> Move DagsterError to dagster_shared.error

js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogActivityChart.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogInsightsLineChart.tsx
There's an off-by-one error in the insights details dialog. The previously logic checked for events between the selected hour `X` and `X+1`, when it was supposed to check for events between `X-1` and `X`.
Locally viewed
NOCHANGELOG
=> Fix bucketing in insights details dialog

js_modules/dagster-ui/packages/ui-core/src/assets/auto-materialization/AutomaterializationRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/automation/AutomationTabs.tsx, js_modules/dagster-ui/packages/ui-core/src/automation/MergedAutomationRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/overview/OverviewTabs.tsx
Global AMP does not have many remaining users, so let's move it off the main "Overview" page to the Automations section of the app.
Users who have `global-amp` will see tabs here, with schedules/sensors on one page, and global AMP on the other. Users who are using sensor AMP will not see tabs.
Navigate to Automations. Verify that by default (no global AMP), the tabs do not appear.
Force `global-amp`, verify rendering and behavior of tabs.
[ui] Moved legacy Auto-materialize (global AMP) tab from Overview to Automations.
=> [ui] Move global AMP to Automations section

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/scaffold.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_custom_help_format.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_scaffold_commands.py, python_modules/libraries/dagster-dg-core/dagster_dg_core/utils/__init__.py
Some adjustment to `scaffold defs` parameters for clarity:
- Improve help text of `--json-params` to make clear it is about SCAFFOLDER params, not component params.
- Currently `--json-params` is added to all subcommands. This is confusing when there are no actual scaffolder params. Only add `--json-params` if scaffolder params exist.
- Explicitly mark options that are scaffolder parameters in the help text by preceding with `(scaffolder param)`
Before:
After:
=> [dg] Make scaffold defs scaffolder params more clear

python_modules/dagster/dagster/__init__.py, python_modules/dagster/dagster/components/testing.py, python_modules/dagster/dagster_tests/components_tests/testing_tests/test_defs_sandbox.py, python_modules/dagster/dagster_tests/components_tests/testing_tests/test_get_within_project.py
This PR enhances the component testing utilities by adding functions to load component definitions within a project context. It introduces:
1. `get_module_path` to construct proper module paths from component paths
2. `get_component_defs_within_project` and `get_all_components_defs_within_project` to load component definitions using project configuration from pyproject.toml or dg.toml
3. `copy_code_to_file` utility to help with test scaffolding
The PR also refactors existing functions to use the new module path construction and adds tests for nested components and retrieving components within a project.
One thing to note is that these conditionally include `dagster_dg_core` to get access to `DgContext`.
Added two new test files:
- `test_defs_sandbox.py` to verify nested component loading …
=> Add get_all_components_defs_within_project and get_component_defs_within_project

python_modules/libraries/dagster-dbt/kitchen-sink/Makefile
kitchen sink is occassionally failing builds - I think because it can't do test fixture teardown.
Which is kind of a bummer because we can't use our typical mute tooling to get around it as easily (other than muting the entire build step).
But I just don't think this cleanup is that important. The dash should tell make to suppress any errors during this command.
https://www.gnu.org/software/make/manual/html_node/Errors.html
https://buildkite.com/dagster/dagster-dagster/builds/125669#01975abf-306b-4c80-a35f-ebd50f261f59/525-1428
=> Don't fail the build if `make wipe` fails

examples/docs_snippets/docs_snippets/guides/dg/using-env/9-dg-component-check.txt, python_modules/libraries/dagster-dg-core/dagster_dg_core/component.py
The env var discovery regex is matching strings with trailing whitespace, leading to a snippets test failure.
=> [dg] fix docs snippets env var

python_modules/dagster/dagster/components/testing.py, python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/beta/test_component.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/test_dbt_project_component.py, python_modules/libraries/dagster-dlt/dagster_dlt_tests/test_dlt_load_collection_component.py, python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_component.py, python_modules/libraries/dagster-sling/dagster_sling_tests/test_sling_replication_collection_component.py
We replicate a huge list of test parameters between each of our component tests to validate that customizing assets works as expected.
This PR moves this param list to a shared pytest class which component authors can then subclass.
=> [refactor][tests] Unify asset customization testing into util

python_modules/dagster/dagster/_core/definitions/asset_spec.py, python_modules/dagster/dagster/_core/definitions/freshness.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_internal_freshness.py
To resolve 500s in prod for design partners: https://dagsterlabs.slack.com/archives/C03F99LCHM4/p1749511791789919
Previously user code could pass `None` as the policy to `attach_internal_freshness_policy`, which would serialize to a string literal `"null"`, resulting in 500s when the `AssetNode` attempts to deserialize it to an `InternalFreshnessPolicy`.
Solution is to add explicit runtime type checking to  `attach_internal_freshness_policy`.
Also adds special case handling for asset spec metadata that already has "null" literal for the freshness policy.
unit tests that:
- explicitly try to apply a `None` freshness policy
- cover special handling for metadata with "null" literal freshness policy
=> Don't allow users to apply a null freshness policy to assets

python_modules/dagster/dagster/_core/instance/__init__.py
If you do "re-execute from step failure" before "re-execute from asset failure", this does not subset the actual ExecutionPlanSnapshot object, so all the previous steps will still be in there, even though they weren't executed.
This messed with the logic we were using in this function, that just iterated over all steps without checking if they were actually intended to be executed
Fixed an issue with the new "re-execute from asset failure" functionality that could cause additional steps to be included if the job was previously re-executed from step failure.
=> Fix issue with "Re-execute from asset failure"

js_modules/dagster-ui/packages/ui-components/src/palettes/__stories__/ColorNames.stories.tsx, js_modules/dagster-ui/packages/ui-components/src/palettes/colorNameToVar.tsx
Add a Storybook entry for color names, with the rendered color for the visible theme.
Storybook
=> [ui] Colors in Storybook

js_modules/dagster-ui/packages/ui-core/src/overview/useGroupTimelineRunsBy.tsx
I think this has been broken for a while. Fix persistence of the group-by setting on Timeline.
Set the group-by value on timeline, reload the page without the query param. Verify that the value is persisted.
Delete the LS key, repeat.
[ui] FIx persistence of group-by setting on run timeline.
=> [ui] Fix group-by persistence on timeline view

python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py, python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/pending_repo_snapshot.py, python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/pending_repo_snapshot_with_assets.py, python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_asset_specs.py
This PR adds support to load the snapshot when using `FivetranWorkspace.get_or_fetch_workspace_data`, so that we can load the workspace data from the snapshot whenever we are using the state-backed defs.
New tests with BK
=> [dagster-fivetran] Support snapshot in FivetranWorkspace.get_or_fetch_workspace_data

js_modules/dagster-ui/packages/ui-core/src/workspace/CodeLocationRowSet.tsx, python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/commands/workspace/__init__.py, python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/config/models.py, python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/core/workspace.py, python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli_tests/test_ci_commands.py
Add the argument to the client and data model classes used by the dagster-cloud and dg clis.
New test case, deploy a local autodefs module
Fixed an issue where dg projects using autoload_defs=true could not be deployed to Dagster+.
=> Add autoload module defs property to dagster-cloud-cli

python_modules/libraries/dagster-tableau/dagster_tableau/resources.py, python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_reconstruction.py
This PR implements a materialization function to be used with a multi asset, or the tableau_assets decorator to be implemented in the subsequent PR. 
It is now possible to select a subset of Tableau assets to refresh.
Additional test with BK.
=> [dagster-tableau] Implement refresh_and_poll with AssetExecutionContext

python_modules/libraries/dagster-tableau/dagster_tableau/asset_decorator.py, python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_reconstruction.py
This PR implements the tableau_assets decorator:
- extracted data sources are all included as materializable assets by default,
- can be customized more easily than the asset factory previously provided
- no more parsing the specs for users, unless they need external assets to be included in their definitions.
Updated test with BK.
[dagster-tableau] The `tableau_assets` decorator is now available to create the asset definitions of all materializable assets in a given Tableau workspace. These assets can be subsetted and materialized using the `TableauCloudWorkspace.refresh_and_poll` method.
=> [dagster-tableau] Implement tableau_assets decorator

python_modules/libraries/dagster-dbt/dagster_dbt/dagster_dbt_translator.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py
https://github.com/dagster-io/dagster/pull/29123/files added a new property on the translator and not all child classes will neccesarily call the parent constructor.
Existing dbt translator tests
Fixed an issue where creating a DagsterDbtTranslator that didn't call the parent class's constructor in it's __init__ method raised an Exception during execution.
=> Make custom dbt translators still work if you subclass and don't call the constructor

python_modules/libraries/dagster-tableau/dagster_tableau/translator.py
=> [dagster-tableau] Remove deprecated get_*_key methods in DagsterTableauTranslator

python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_health.py, python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_asset_health.py, python_modules/dagster/dagster/_core/instance/__init__.py
Gates returning asset health data on `ENABLE_ASSET_HEALTH_QUERIES` instead of `ENABLE_OBSERVE`.
See discussion in https://github.com/dagster-io/internal/pull/16300 for reasoning
=> [asset health] gate on different feature flag

python_modules/dagster-graphql/dagster_graphql_tests/cli_test_error_workspace.yaml, python_modules/dagster-graphql/dagster_graphql_tests/cli_test_workspace.yaml, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_misc.py, python_modules/dagster-graphql/dagster_graphql_tests/test_cli.py, python_modules/dagster-graphql/dagster_graphql_tests/test_cli_repo.py
Instead of skipping the fake test, rename the repository
BK
=> Fix pytest skips for repositories that are not tests

python_modules/dagster/dagster/_grpc/server.py, python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_persistent.py
This should not be common, but can happen in certain edge cases (a pod restarting). Include the error stack trace when it does.
New test case
=> better error when a sensor or schedule runs on a code server in an error state

js_modules/dagster-ui/packages/ui-core/src/home/HomeDarkLaunch.oss.tsx, js_modules/dagster-ui/packages/ui-core/src/home/useHomeDarkLaunch.oss.tsx, js_modules/dagster-ui/packages/ui-core/src/overview/OverviewTimelineRoot.tsx
Use a component instead of a hook for the home dark launch. This allows for better gating on the Cloud side.
TS, lint, jest. Load app, verify that the component renders as expected in Cloud.
=> [ui] Use a component for home dark launch

python_modules/dagster/dagster/_core/definitions/freshness.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_internal_freshness.py
fixes an issue when deserializing freshness policies that had been stored in the DB as `"null"`
```
dagster_shared.serdes.errors.deserializationerror: Deserialized object was not expected type <class 'dagster._core.definitions.freshness.InternalFreshnessPolicy'>, got <class 'NoneType'> 
```
Tested by running a shadow script that failed with this error before this change and succeeded after. Fixed a unit test to accurately replicate the backcompat condition
=> fix deserialization of freshness policies

examples/docs_snippets/docs_snippets/guides/components/customizing-existing-component/global/9-defs.yaml, examples/docs_snippets/docs_snippets/guides/components/customizing-existing-component/local/9-component.yaml, examples/docs_snippets/docs_snippets/guides/components/customizing-existing-component/local/9-defs.yaml, examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/components/test_customizing_existing_component.py, python_modules/libraries/dagster-sling/dagster_sling/components/sling_replication_collection/component.py
Use the generic `post_processing` field instead in tests and examples. Commented to follow up and kill in https://linear.app/dagster-labs/issue/BUILD-1307/deprecate-and-delete-asset-post-processors-on-airlift-and-sling
BK
* Removes `asset_post_processors` on `SlingReplicationCollectionComponent` and uses generic `post_processing` key at top-level instead.
=> Use post_processing on Sling Component

python_modules/libraries/dagster-airlift/dagster_airlift/core/components/airflow_instance/component.py, python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_component_defs.py
We're moving to top-level `post_processing` field instead component-specific `asset_post_processors`
https://linear.app/dagster-labs/issue/BUILD-1307/deprecate-and-delete-asset-post-processors-on-airlift-and-sling tracking follow up to deprecate and eliminate the asset_post_processors field.
BK
=> Use post_processing on airlift component

python_modules/libraries/dagster-dg-core/dagster_dg_core/config.py
Introduces a warning displayed to the user if they have autoloading enabled in their `pyproject.toml`, in advance of removal of this feature in a subsequent release.
=> [dg] warn if using autoloading behavior

python_modules/dagster/dagster/components/__init__.py, python_modules/dagster/dagster/components/lib/executable_component/function_component.py, python_modules/dagster/dagster/components/lib/executable_component/python_script_component.py, python_modules/dagster/dagster/components/lib/executable_component/script_utils.py, python_modules/dagster/dagster/components/lib/executable_component/uv_run_component.py, python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_pipes_subprocess.py, python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_uv_run_component.py, python_modules/dagster/dagster_tests/components_tests/testing_tests/test_defs_sandbox.py
https://linear.app/dagster-labs/issue/BUILD-1316/expose-function-python-script-and-uv-run-script-top-level-and-document  
[components] Added `FunctionComponent`, `PythonScriptComponent`, and `UvRunComponent` to make it easier to define arbitrary computations that execute assets or asset checks when invoked.
=> [components] Export FunctionComponent, PythonScriptComponent, UvRunComponent from top level `dagster.components`, add docstrings

python_modules/libraries/dagster-sling/setup.py
remove this pin and handle breaking changes. looks like sling released a 1.4.10.post1 that resolved the breaking changes, so we don't need the pin anymore.
i did end up rebuilding the pyright pins so that we could confirm that pyright is running with the latest version of sling, can remove those changes if desired
[dagster-sling] Removed upper-bound pin on `sling`
=> [dagster-sling] Unpin

js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogTopAssetsChart.tsx
I noticed that the x-axis font on the top assets charts is the default Chart.js gray. Change it to use our palette, and monospace.
View top assets charts, verify x-axis font style.
=> [ui] Fix top assets x axis font

python_modules/libraries/dagster-sling/dagster_sling/resources.py, python_modules/libraries/dagster-sling/dagster_sling_tests/test_resource.py
See changelog
We had the explicitly wrong behavior under test
[dagster-sling] Fixed an issue with the `SlingResource` that could cause values specified with `EnvVar`s to provide the env var name instead of the env var value to the sling replication configuration.
=> [dagster-sling] Fix bug when using `EnvVar` with SlingConnectionResource

js_modules/dagster-ui/packages/ui-components/src/components/Alert.tsx, js_modules/dagster-ui/packages/ui-components/src/components/BaseButton.tsx, js_modules/dagster-ui/packages/ui-components/src/components/Button.tsx, js_modules/dagster-ui/packages/ui-components/src/components/Dialog.tsx, js_modules/dagster-ui/packages/ui-components/src/components/StyledButton.tsx, js_modules/dagster-ui/packages/ui-components/src/components/__stories__/Alert.stories.tsx, js_modules/dagster-ui/packages/ui-components/src/components/__stories__/Button.stories.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetEventMetadataEntriesTable.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/overview/LineageSection.tsx, js_modules/dagster-ui/packages/ui-core/src/launchpad/LaunchpadConfigExpansionButton.tsx, js_modules/dagster-ui/packages/ui-core/src/partitions/DimensionRangeWizard.tsx, js_modules/dagster-ui/packages/ui-core/src/partitions/OpJobPartitionsView.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/StepLogsDialog.tsx
This PR makes a few small changes to the core UI components:
- Our button lists a `fill` prop which we use in billing, but it doesn't do anything. This PR removes the `fill` prop and aligns the button label with `text-align: center` so that it renders properly when it's made wider-than-it's-label via a flexbox.
- Adds an `<Alert intent=“none” />` that renders in gray for a subtle notice (used for “After your trial ends, you will be billed on Jun 16” style messages).
- Adds an `<Alert rightButton={<Button…/>} />`. The alerts currently support displaying an X, but we need to support an actual CTA button placed inside an alert notice.
- Dialog has a `isCloseButtonShown` prop that is used in several places but does not actually do anything since we implement our own header. This is fixed.
The …
=> [ui] UI Component updates to support billing designs

examples/assets_pandas_type_metadata/setup.py, pyright/alt-1/requirements-pinned.txt, pyright/master/requirements-pinned.txt, python_modules/libraries/dagster-pandera/dagster_pandera/__init__.py, python_modules/libraries/dagster-pandera/dagster_pandera_tests/test_dagster_pandera.py, python_modules/libraries/dagster-pandera/setup.py
See https://github.com/dagster-io/dagster/issues/30680
- Installed `pandera==0.24.0` locally and ran `python -m pytest python_modules/libraries/dagster-pandera/dagster_pandera_tests`
- Adds support for version 0.24.0 of the `pandera` library to `dagster-pandera`, dropping support for pandera 0.23.1 and below.
=> Support pandera >= 0.24.0 in dagster-pandera

js_modules/dagster-ui/packages/ui-core/src/nav/useCodeLocationsStatus.tsx
The "View" link on code location status toasts is hardcoded to `accentWhite`. I think this is an oversight on my part from when we changed to the new toast styles, since previously they were always dark solid colors.
Force toasts to appear, verify that links use correct color.
[ui] Fix "View" link color on code location status toasts.
=> [ui] Fix View link on code location status toast

js_modules/dagster-ui/packages/ui-components/src/components/StyledButton.tsx, js_modules/dagster-ui/packages/ui-components/src/components/__stories__/Button.stories.tsx, js_modules/dagster-ui/packages/ui-components/src/components/__stories__/Select.stories.tsx
Additionally added a story that illustrates a select with a minwidth that is implemented the same way the ones in User Settings are - would have helped me see my last change broke something!
=> [ui] Revert change to button alignment, add story showing a select with minWidth

python_modules/dagster/dagster/components/resolved/core_models.py, python_modules/dagster/dagster_tests/components_tests/resolution_tests/test_resolvable_transformer.py, python_modules/libraries/dagster-dg-core/dagster_dg_core/utils/__init__.py
Allows for arbitrary time-window partitions and built-in weekly partitions.
Unit tests.
> [components] Weekly and arbitrary time-window partitions can now be provided to the  `partitions_def` asset customization in YAML.
=> [Resolved] Add weekly, arbitrary time-window partition def

python_modules/dagster/dagster/_core/execution/asset_backfill.py, python_modules/dagster/dagster/_utils/caching_instance_queryer.py
Summary:
This fetches the relevant run records one by one which can be quite slow. Instead, fetch them in a bathc.
Existing backfill test suite covers this case, it should just be faster
Dry run a slow asset backfill tick
=> Batch run record fetch in asset backfill "materialized runs since cursor" logic

python_modules/dagster/dagster/components/definitions.py
I am doing an audit of our preview APIs, removing the `@preview` attribute, improving docs, and making any last minor modifications before we lock the API contract.
In this case we are documenting `@definitions`
Read and claude
* Removing `@preview` from `@definitions`
=> [components] Remove @preview from @definitions and refresh docs

python_modules/dagster/dagster/_core/definitions/asset_job.py, python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_checks.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py
After https://github.com/dagster-io/dagster/pull/30350, dbt tests can be made blocking, which better matches the underlying semantics of dbt tests - as per https://docs.getdbt.com/reference/resource-configs/severity
The only significant behavior change here should be with the new "retry from asset failure" method, which will correctly realize that a test failure should include the connected asset in the retried run. Otherwise there should be no behavior change during execution here.since the dbt cli invocation was already failing on these assets.
We could consider making this change configurable or opt outable in some fashion though.
Modified test cases, verified that they would have short-circuited early and incorrectly without the upstream change
[dagster-dbt] dbt tests with error …
=> make error severity dbt tests blocking asset checks

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py, python_modules/dagster-graphql/dagster_graphql/implementation/loader.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster-graphql/dagster_graphql/schema/external.py, python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_data_versions.py, python_modules/dagster/dagster/_core/workspace/context.py
Similar to https://github.com/dagster-io/dagster/pull/29717/files but for this other field. Makes it easier to construct a new GrapheneAssetNode without having to pass in a bunch of stuff.
BK
=> Source StaleStatusLoader from the workspace context instead of passing it into GrapheneAssetNode

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py, python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_assets.ambr
This id was being used in two places:
- to determine the id (but the asset key already uniquely determines a given GrapheneAsset, unlike GrapheneAssetNode),
- to help with a couple of fields that are not under test and are not currently working
So let's just remove it. I think this would allow us to remove GrapheneAssetRecord as well if we want now that definitions are totally optional on GrapheneAsset.
BK
=> no longer pass a GrapheneAssetNode into GrapheneAsset

python_modules/dagster/dagster/_core/definitions/metadata/__init__.py, python_modules/dagster/dagster/_core/definitions/result.py, python_modules/dagster/dagster/_core/execution/plan/execute_step.py, python_modules/dagster/dagster/_core/types/dagster_type.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py, python_modules/dagster/dagster_tests/definitions_tests/test_materialize_result.py
This is based off of: https://github.com/dagster-io/dagster/pull/30144
An upstack PR will handle the input side of the world, this just tackles `MaterializeResult`.
We do end up needing to differentiate between the case of "explicitly passing the value `None` into the constructor" and "not passing any value at all":
```python
@asset
def my_asset() -> MaterializeResult:
return MaterializeResult()
@asset
def my_asset() -> MaterializeResult:
return MaterializeResult(value=None)
```
One small nice thing to note is that users who opt-in to using the more specific type hint get nice linter support, which is something I was a bit worried about (i thought it might be easy to forget to pass the value):
```python
@asset
def a() -> MaterializeResult[int]:
return MaterializeResult()
``` …
=> Allow `MaterializeResult` to take a `value` argument

python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster-graphql/dagster_graphql/schema/instance.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_internal_freshness.py
adds a resolver to check if freshness policies are getting evaluated to help provide useful tooltips when it is not
also removes the gate for returning a value if freshness is not enabled
NOCHANGELOG
=> [freshness] freshnessEvaluationEnabled resolver

examples/docs_snippets/docs_snippets/guides/components/customizing-existing-component/global/9-defs.yaml, examples/docs_snippets/docs_snippets/guides/components/customizing-existing-component/local/9-defs.yaml, examples/docs_snippets/docs_snippets/guides/components/integrations/dlt-component/4-tree.txt, examples/docs_snippets/docs_snippets/guides/components/integrations/sling-component/11-customized-component.yaml, examples/docs_snippets/docs_snippets/guides/components/integrations/sling-component/9-customized-component.yaml, examples/docs_snippets/docs_snippets/guides/dg/using-env/10-component-with-env-deps.yaml, examples/docs_snippets/docs_snippets/guides/dg/using-env/8-defs.yaml, examples/docs_snippets/docs_snippets/guides/dg/using-env/9-dg-component-check.txt, examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/components/integrations/test_sling_component.py, examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/components/test_customizing_existing_component.py, examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/dg/test_using_env.py, python_modules/libraries/dagster-sling/dagster_sling/asset_decorator.py, python_modules/libraries/dagster-sling/dagster_sling/components/sling_replication_collection/component.py, python_modules/libraries/dagster-sling/dagster_sling_tests/code_locations/sling_location_legacy/defs/ingest/defs.yaml, python_modules/libraries/dagster-sling/dagster_sling_tests/code_locations/sling_location_legacy/defs/ingest/replication.yaml, python_modules/libraries/dagster-sling/dagster_sling_tests/code_locations/sling_location_legacy/input.csv, python_modules/libraries/dagster-sling/dagster_sling_tests/test_sling_replication_collection_component.py
Grabs changes from the following PRs:
- https://github.com/dagster-io/dagster/pull/30561
- https://github.com/dagster-io/dagster/pull/30802
and adds backwards compat (so existing sling usage will continue to function as usual, but will emit a deprecation warning)
In a future release, we can make the sling: config hard-error 
[dagster-sling] The `SlingReplicationCollectionComponent` is now configured by passing `connections` directly. This means that the `sling` yaml field and the `resource` python argument are both deprecated, and will be removed in a future release. The `connections` field in yaml now shares a format with Sling's `env.yaml`.
=> [dagster-sling] Update SlingReplicationComponent configuration + docs

python_modules/dagster/dagster/_grpc/client.py, python_modules/dagster/dagster/_grpc/proxy_server.py, python_modules/dagster/dagster/_grpc/types.py
When making the call to execute a sensor from the grpc client, we need to thread the timeout through the args so that it's respected by the proxy server. Currently that's not happening, and it's manifesting as a timeout in the request that the proxy server makes of 60 seconds, even if the timeout is higher at the client.
- Initially got this to trigger by having a 70 second sleeping sensor, setting the timeout to be 80 seconds on the call to sensor execution, then observing that the sensor execution still times out at 60 seconds. After the fix, the sensor call completes in 70 seconds.
- Fixed a bug with `DAGSTER_GRPC_SENSOR_TIMEOUT_SECONDS` not being propogated through from daemon to code severs, resulting in the sensor still timing out at 60 seconds if the `dagster code-server start` …
=> Fix sensor timeout

examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/components/integrations/test_utils.py
This was muted (hence builds not breaking), but there was a maximum recursion depth exceeded thing going on because the method being invoked just invoked `workspace.build_asset_specs()`.
Getting rid of this override causes the test to pass
NOCHANGELOG
=> Fix broken fivetran docs snippets test

python_modules/dagster/dagster/deprecated/__init__.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_freshness_policy.py
Adds a new top-level module `deprecated` which exports deprecated classes, and exports `LegacyFreshnessPolicy` from it with its old name `FreshnessPolicy`.
This enables users to migrate their existing code with `FreshnessPolicy` to `1.11` by simply changing the import line, without needing to change the name of every reference to `FreshnessPolicy`.
Users will still be able to import `LegacyFreshnessPolicy` from the top-level `dagster` module.
```
from dagster import FreshnessPolicy
<usages>
from dagster.deprecated import FreshnessPolicy
<usages>
from dagster import LegacyFreshnessPolicy
<usages: change to LegacyFreshnessPolicy>
```
a unit test that imports `FreshnessPolicy` from `dagster.deprecated`.
> Allow importing `FreshnessPolicy` from `dagster.deprecated`.
=> [freshness] Allow importing `FreshnessPolicy` from `dagster.deprecated`

examples/docs_snippets/docs_snippets/guides/components/integrations/airbyte-cloud-component/3-scaffold-airbyte-component.txt, examples/docs_snippets/docs_snippets/guides/components/integrations/fivetran-component/3-scaffold-fivetran-component.txt, examples/docs_snippets/docs_snippets/guides/components/integrations/sling-component/3-scaffold-sling-component.txt, examples/docs_snippets/docs_snippets/guides/components/shell-script-component/4-scaffold-instance-of-component.txt, examples/docs_snippets/docs_snippets/guides/dg/dagster-definitions/1-scaffold.txt, examples/docs_snippets/docs_snippets/guides/dg/using-env/5-dg-scaffold-sling.txt, examples/docs_snippets/docs_snippets/integrations/airlift_v2/setup/basic_auth/1-scaffold.txt, python_modules/dagster/dagster/components/component_scaffolding.py, python_modules/dagster/dagster/components/lib/shim_components/base.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/scaffold.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_custom_help_format.py, python_modules/libraries/dagster-dg-core/dagster_dg_core/context.py
We had outdated terminology in the user-facing print statements and help string of `dg scaffold defs`. This updates them to not assume components terminology.
=> [components] Improving verbiage and messages in scaffold defs command

.buildkite/dagster-buildkite/dagster_buildkite/quarantine_utils.py
I think the way we do:
```
dagster-buildkite | buildkite-agent pipeline upload
```
is occassionally having issues when fetching muted tests fails because instead of getting yaml to pipe, we're getting yaml with a random stack trace piped into `buildkite-agent`.
https://buildkite.com/dagster/dagster-dagster/builds/126922#0197a3ab-f669-4425-a276-8acafb9a98ee/210-518
At least that's my best read of what "pipeline parsing" is doing here.
=> Print Buildkite exception to stderr

python_modules/dagster/dagster/components/scaffold/scaffold.py
Removes preview decorator from `@scaffold_with`.
=> [ADOPT-1610] remove preview from scaffold_with

python_modules/dagster/dagster/components/scaffold/scaffold.py
Removes `@preview` from `ScaffoldRequest` and adds a docblock
=> [ADOPT-1611] remove preview from ScaffoldRequest

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/scaffold.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/templates/build-location-fragment.yaml, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/templates/hybrid-github-action.yaml, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/templates/serverless-github-action.yaml, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/plus_tests/test_scaffold_plus_commands.py
Updates the scaffolded github actions to use the published version matching the dg CLI version (or latest, for dev CLI)
New unit test.
=> [dg] dg scaffold github-actions now uses action version matching the CLI

examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/components/test_components_docs.py
don't run certain dagster commands when you're just updating snippets
this saves time!
=> [wip] Make docs snapshot update faster

python_modules/dagster/dagster/preview/freshness/__init__.py, python_modules/dagster/dagster_tests/freshness_tests/test_internal_freshness.py
Allow importing the new freshness classes from `dagster.preview.freshness`. This is a temporary measure while the freshness policy class still has the name `InternalFreshnessPolicy`. We will change the class name to `FreshnessPolicy` in a future release.
```
from dagster.preview.freshness import FreshnessPolicy   # imports InternalFreshnessPolicy
```
Also allows importing the helper method `apply_freshness_policy` from the same `preview` module
new unit test that exercises the import
=> Allow importing new freshness classes from `dagster.preview`

python_modules/dagster/dagster/__init__.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_freshness_policy.py
User code should fail to compile with an `ImportError` when it tries to import `FreshnessPolicy` from top-level Dagster module.
```
from dagster import FreshnessPolicy
```
raises:
```
ImportError: FreshnessPolicy has been renamed to LegacyFreshnessPolicy. Import it as FreshnessPolicy from `dagster.deprecated` or as LegacyFreshnessPolicy from top-level Dagster.
```
Without this PR, user code will still fail with an `ImportError` - it just won't have the nice error message.
We'll remove this `ImportError` once the new freshness policy model (currently named `InternalFreshnessPolicy`) is moved out of preview and assumes the name `FreshnessPolicy`.
a unit test added in this PR
- Adds a custom error message when importing `FreshnessPolicy` from …
=> Raise a bespoke `ImportError` when importing `FreshnessPolicy` from top-level Dagster

examples/docs_snippets/docs_snippets/guides/freshness/cron_policy.py, examples/docs_snippets/docs_snippets/guides/freshness/default_freshness.py, examples/docs_snippets/docs_snippets/guides/freshness/individual_asset_policy.py, examples/docs_snippets/docs_snippets/guides/freshness/map_asset_specs_direct.py, examples/docs_snippets/docs_snippets/guides/freshness/multiple_assets_policy.py, python_modules/dagster/dagster/_core/definitions/asset_spec.py
Update freshness docs code samples to be consistent with our recommended imports and usage for `1.11`.
- `from dagster._core.definitions.freshness import InternalFreshnessPolicy` -> `from dagster.preview.freshness import FreshnessPolicy`
- `from dagster._core.definitions.asset_spec import attach_internal_freshness_policy` -> `from dagster.preview.freshness import apply_freshness_policy`
=> Update freshness docs code samples for `1.11`

python_modules/libraries/dagster-tableau/dagster_tableau/asset_decorator.py, python_modules/libraries/dagster-tableau/dagster_tableau/resources.py, python_modules/libraries/dagster-tableau/dagster_tableau/translator.py, python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_asset_specs.py
Allow users to select specific Tableau workbooks when creating their assets definition and asset spec. Workbooks can be selected by ID, project name and project ID. All assets related to the workbook are selected if the workbook is selected - data sources, sheets and dashboards.
```python
from dagster_tableau import TableauCloudWorkspace, tableau_assets
tableau_workspace = TableauCloudWorkspace(
connected_app_client_id=dg.EnvVar("TABLEAU_CONNECTED_APP_CLIENT_ID"),
connected_app_secret_id=dg.EnvVar("TABLEAU_CONNECTED_APP_SECRET_ID"),
connected_app_secret_value=dg.EnvVar("TABLEAU_CONNECTED_APP_SECRET_VALUE"),
username=dg.EnvVar("TABLEAU_USERNAME"),
site_name=dg.EnvVar("TABLEAU_SITE_NAME"),
pod_name=dg.EnvVar("TABLEAU_POD_NAME"),
)
@tableau_assets( …
```
=> [dagster-tableau] Implement WorkbookSelectorFn

python_modules/libraries/dagster-tableau/dagster_tableau/resources.py, python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_reconstruction.py
Move state-backed defs logic to load the asset specs in the resource and cache the method.
Updated tests with bk
=> [dagster-tableau] Make spec loader a cached method of BaseTableauWorkspace

python_modules/libraries/dagster-powerbi/dagster_powerbi/components/power_bi_workspace/component.py, python_modules/libraries/dagster-powerbi/dagster_powerbi_tests/test_components.py
Power BI is distinct from other translator-enabled component types (dbt, dlt, sling) in that the translated objects are fairly heterogenous; datasets have very different properties from reports which are very different from data sets. This PR introduces the ability to specify per-object-type translators, which are applied after (and merge with, in most cases) the global translation logic:
```yaml
type: dagster_powerbi.PowerBIWorkspaceComponent
attributes:
workspace:
credentials: 
token: {{ env('POWERBI_TOKEN') }}
workspace_id: abcd-1234-abcd-1234
translation:
tags:
- foo: bar
for_datasets:
tags:
- dataset_id: {{ data.properties.id }}
for_reports:
tags:
- report_name: {{ data.properties.name }}
```
=> [dagster-powerbi][components] Per-content-type translation layer

examples/docs_snippets/docs_snippets_tests/snippet_checks/guides/components/integrations/test_dlt_component.py, python_modules/libraries/dagster-dlt/dagster_dlt/components/dlt_load_collection/component.py
Fix an issue where a `None` dataset name would be appended as an invalid asset key prefix.
`dataset_name` is theoretically non-`None`able, but seems in practice this can happen.
e2e test
> [dagster-dlt][components] Fixed an issue where the default scaffolded dlt load lead to an invalid asset key.
=> [dagster-dlt][components] fix asset key for default dlt scaffold

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/templates/serverless-github-action.yaml
This GH action template has fallen behind some of our more recent changes.
Tested against prod with new org/repo.
Fixed an issue where `dg scaffold github-actions` would invoke the `dg` CLI with outdated parameters for serverless orgs.
=> [dg scaffold] fix serverless GH actions template

python_modules/dagster/dagster/components/component_scaffolding.py, python_modules/dagster/dagster/components/core/defs_module.py, python_modules/dagster/dagster/components/core/package_entry.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/scaffold.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/utils.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_integrity.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_scaffold_commands.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_utils_inspect_command.py, python_modules/libraries/dagster-dg-core/dagster_dg_core/utils/__init__.py, python_modules/libraries/dagster-shared/dagster_shared/error.py, python_modules/libraries/dagster-shared/dagster_shared/serdes/objects/package_entry.py, python_modules/libraries/dagster-shared/dagster_shared/seven/__init__.py
Currently `dg scaffold defs <ref>` only works for registered objects (or their aliases, or substring matches). This is part of the legacy of having a registry sourced from out-of-process.
This PR introduces on the fly dynamic subcommand resolution. If the user passes:
```
dg scaffold defs some.component.SomeComponent
```
It will work as long as it is a valid python reference to a scaffoldable object in the environment (though we still rely on the registry when listing available subcommands).
This will allow removal of the `EnvRegistryObjectSnap` layer upstack.
New unit test
=> [dg] Make `dg scaffold defs` work for arbitrary valid refs

python_modules/dagster-test/dagster_test/toys/asset_health.py
Adding this so that random assets can be executed every 15m, to populate some time to resolution metrics.
Locally loaded toys
NOCHANGELOG
=> [toys] Add schedule for random assets

CHANGES.md
Just adding a link to a discussion that was created after the `1.11` release went out.
=> [changelog] Add freshness discussion link to `1.11.0` changelog

python_modules/dagster/dagster/components/component/component.py, python_modules/dagster/dagster/components/core/context.py, python_modules/dagster/dagster/components/core/load_defs.py, python_modules/dagster/dagster/components/core/tree.py, python_modules/dagster/dagster/components/testing.py, python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_asset_check_only.py, python_modules/dagster/dagster_tests/components_tests/executable_component_tests/test_executable_component_in_memory.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/component_loader.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/test_definitions_autoload.py, python_modules/dagster/dagster_tests/components_tests/resolution_tests/test_custom_scope.py, python_modules/dagster/dagster_tests/components_tests/template_vars_tests/test_fn_decorators.py, python_modules/dagster/dagster_tests/components_tests/test_code_references.py, python_modules/dagster/dagster_tests/components_tests/test_definitions.py, python_modules/dagster/dagster_tests/components_tests/unit_tests/test_component_invariant_errors.py, python_modules/dagster/dagster_tests/components_tests/utils.py, python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py, python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/beta/test_component.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/test_dbt_project_component.py, python_modules/libraries/dagster-dlt/dagster_dlt_tests/test_dlt_load_collection_component.py, python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_component.py, python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_pipes.py, python_modules/libraries/dagster-sling/dagster_sling_tests/test_sling_replication_collection_component.py
This PR begins the process of recentering component loading on the `ComponentTree` object, which is now "in charge" of the component loading process, including caching components and their definitions. We'll need a back-reference to the tree available in the context so that components can e.g. load other components.
This means any path which constructs a `ComponentLoadContext` will instead construct a `ComponentTree`, which it now uses to vend the context.
This PR is a pretty dumb drop-in replacement for most callsites, but most could subsequently be cleaned up.
=> [2/n] hoist ComponentTree into ComponentLoadContext

python_modules/dagster/dagster/_core/remote_representation/external_data.py, python_modules/dagster/dagster/components/core/load_defs.py, python_modules/dagster/dagster/components/core/tree.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/test_definitions_autoload.py, python_modules/dagster/dagster_tests/components_tests/unit_tests/test_component_decl.py
Continues the consolidation of manually constructed `ComponentLoadContext`s into `ComponentTree` by handling the `load_defs` case. Currently, this relies on some thorny branching behavior where we try to use `ComponentTree` and fallback to a non-Tree load if the root is not a `DefsFolderComponent`.
This requires some lift so that `ComponentTree` can still be used for e.g. singular components or a single composite YAML file.
=> [3/n] finish consolidating on ComponentTree in load_defs

python_modules/dagster/dagster/components/component/component.py, python_modules/dagster/dagster/components/core/decl.py, python_modules/dagster/dagster/components/core/defs_module.py, python_modules/dagster/dagster/components/core/tree.py, python_modules/dagster/dagster_tests/components_tests/code_locations/component_component_deps/defs/depends_on_my_python_defs/defs.yaml, python_modules/dagster/dagster_tests/components_tests/code_locations/component_component_deps/defs/my_python_defs/defs.yaml, python_modules/dagster/dagster_tests/components_tests/integration_tests/integration_test_defs/definitions/definitions_at_levels_with_config/defs.yaml, python_modules/dagster/dagster_tests/components_tests/integration_tests/integration_test_defs/definitions/definitions_at_levels_with_config/defs_object/defs.yaml, python_modules/dagster/dagster_tests/components_tests/integration_tests/integration_test_defs/definitions/definitions_at_levels_with_config/loose_defs/defs.yaml, python_modules/dagster/dagster_tests/components_tests/integration_tests/integration_test_defs/definitions/definitions_at_levels_with_config/loose_defs/inner/innerer/another_level/defs.yaml, python_modules/dagster/dagster_tests/components_tests/integration_tests/integration_test_defs/definitions/validation_error_file/defs.yaml, python_modules/dagster/dagster_tests/components_tests/integration_tests/test_definitions_autoload.py, python_modules/dagster/dagster_tests/components_tests/unit_tests/test_component_decl.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/code_locations/dependency_on_dbt_project_location/defs/depends_on_dbt/defs.yaml
A rework/edge case pass on previous PRs.
- Makes all `ComponentDecl` objects iterable, so any `ComponentDecl` object can now act as the tree root
- `ComponentPath` replaces `Path` as input for various `ComponentTree` fns to allow loading components at specific indices.
- Properly parses out `DefsFolderDecl` from YAML files, allowing the decl tree to successfully continue past user-specified `DefsFolderDecl`s. This is a bit gnarly as written.
This feels like a natural place to start merging the stack, with the PRs beyond this point more intrusively adjusting the existing loading/defs building logic.
Here's a link to view the changes in aggregate up to this point: https://github.com/dagster-io/dagster/compare/master...benpankow/switch-tree-to-use-componentpath
Update test cases, explicit …
=> [4/n] Cleanup+consolidation pass on Decl layer

js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogActivityChart.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogInsights.module.css, js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogInsightsLineChart.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogLineChart.module.css, js_modules/dagster-ui/packages/ui-core/src/insights/InsightsChartShared.tsx
A few style changes to Insights charts and graphs.
- Asset activity charts
- Add a hover outline to tiles
- `top` placement for hover popover
- Use `cursor: pointer`
- Line chart
- Remove vertical grid lines (super noisy in light mode)
- Remove y-axis line
- Updated style for hover popover
- Larger hover circle on graph line
- Fix blue hover circle color
- Use `cursor: pointer`
- Make large number text use same style as other parts of the UI
Proxy to elementl, verify UI changes described above.
=> [ui] Update styles for Insights v2

python_modules/dagster/dagster/components/core/context.py, python_modules/dagster/dagster/components/core/decl.py, python_modules/dagster/dagster/components/core/defs_module.py, python_modules/dagster/dagster/components/core/tree.py, python_modules/dagster/dagster_tests/components_tests/unit_tests/test_component_decl.py, python_modules/libraries/dagster-sling/dagster_sling/components/sling_replication_collection/component.py, python_modules/libraries/dagster-sling/dagster_sling_tests/test_sling_replication_collection_component.py
The first major cutover to the `Decl` system.
Brokers all component-component interactions exclusively through the tree. In this case, updates all callsites for `ComponentDecl._load_component` to use the tree.
=> [5/n] Broker all component loads through `ComponentTree`

js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/useAllAssets.test.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/useAllAssets.tsx
As titled. We were including duplicate SDAs in the list which led to [this line always being false ](https://github.com/dagster-io/dagster/blob/7bf506bd45531ed0d56aeb448b1f3b11af465664/js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphSupplementaryData.oss.tsx#L22) since the array of nodes included duplicates causing status filtering to forever be in a loading state.
jest. local testing
[ui][plus] Fixed an issue that prevented status filtering from working within the selection syntax.
=> [Observe] Fix status filtering by fixing duplicate SDAs returned by `useAllAssets`

js_modules/dagster-ui/packages/ui-core/client.json, js_modules/dagster-ui/packages/ui-core/src/assets/AssetEvents.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/types/useRecentAssetEvents.types.ts, js_modules/dagster-ui/packages/ui-core/src/assets/useAssetEventsFilters.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/usePaginatedAssetEvents.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/useRecentAssetEvents.tsx
We did a big refactor of the underlying fetch logic for this page, and it looks like the parittions filter was not wired up, but it is an available option on the new GraphQL resolver.
I also changed the name of the filter from “Partitions” to “Partition” to match “Date” and “Type”, and so it says “Partition is any of” instead of “Partitions is any of”
app-proxy with `weekly_support_reminders`
[ui] Filtering by partition on the Asset Events view now works as expected
=> [ui] Fix filtering by partition on asset events page FE-884

js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetSelectionSummaryListItem.tsx
In Catalog list view, fix the horizontal controls on the new list items. The `HorizontalControls` adds the line for us, so we can tidy it up a bit.
Proxy, view Catalog list view. Verify that controls look more correct.
=> [ui] Fix list right-side control spacing on Catalog

js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetCatalogV2VirtualizedTable.tsx
I broke the `Skeleton` rows on the new asset catalog table loading state. Fix them.
Force loading state to be true, verify better rendering.
=> [ui] Fix Catalog list view loading state

python_modules/dagster/dagster/_core/definitions/selector.py, python_modules/dagster/dagster/_core/remote_representation/external.py, python_modules/dagster/dagster/_core/workspace/context.py, python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_execution_plan.py, python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_job.py, python_modules/libraries/dagster-shared/dagster_shared/utils/hash.py
To unblock parallelizing IO/bound grpc/agent calls in DA.
One new thing about these is that I think they are our first loader that depends on something other than the instance.
New unit test cases, used for real in downstream PR
=> Add async loaders for RemoteJob and RemoteExecutionPlan

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_partition_backfill.py, python_modules/dagster/dagster/_core/definitions/automation_condition_sensor_definition.py, python_modules/dagster/dagster/_core/definitions/automation_tick_evaluation_context.py, python_modules/dagster/dagster/_core/execution/asset_backfill.py, python_modules/dagster/dagster/_core/execution/submit_asset_runs.py, python_modules/dagster/dagster/_core/remote_representation/code_location.py, python_modules/dagster/dagster/_core/remote_representation/external.py, python_modules/dagster/dagster/_daemon/asset_daemon.py, python_modules/dagster/dagster/_daemon/backfill.py, python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py, python_modules/dagster/dagster_tests/declarative_automation_tests/daemon_tests/test_e2e.py, python_modules/dagster/dagster_tests/declarative_automation_tests/daemon_tests/test_failure_recovery.py, python_modules/dagster/dagster_tests/declarative_automation_tests/scenario_utils/asset_daemon_scenario.py, python_modules/dagster/dagster_tests/declarative_automation_tests/scenario_utils/base_scenario.py
Add asyncio callsites to the DA daemon when it fetches remote jobs and execution plans. This ended up being much more involved than I had been imagining, particularly when the daemon is already using threadpools.
Test Plan: BK, run DA locally with and without submit threadpool enabled
=> Use asyncio/ loaders to speed up code server access parallelism in DA

python_modules/dagster/dagster/_core/execution/plan/plan.py, python_modules/dagster/dagster_tests/core_tests/graph_tests/test_graph.py
fixes #30581
added test
[bugfix] `@graph` now correctly allows omitting inputs when the destinations of an input mapping have a default value
=> [graph] allow omitting input when destinations have defaults

python_modules/dagster/dagster/_cli/definitions.py, python_modules/dagster/dagster/_core/definitions/asset_graph.py, python_modules/dagster/dagster/_core/definitions/base_asset_graph.py, python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster_tests/cli_tests/command_tests/definitions_command_projects/invalid_partition_mappings_workspace/defs1.py, python_modules/dagster/dagster_tests/cli_tests/command_tests/definitions_command_projects/invalid_partition_mappings_workspace/defs2.py, python_modules/dagster/dagster_tests/cli_tests/command_tests/definitions_command_projects/invalid_partition_mappings_workspace/workspace.yaml, python_modules/dagster/dagster_tests/cli_tests/command_tests/test_definitions_validate_command.py
Gives you a way to detect in CI that you have invalid partition mappings that could cause problems in backfills or DA.
New test case
`dagster definitions validate` will now raise an exception if there are invalid partition mappings between any assets in your asset graph (for example, an upstream and downstream asset with time-based partitions definitions using different timezones)
=> Add validate_partition_mappings support to 'dagster definitions validate'

js_modules/dagster-ui/packages/ui-core/src/app/BaseFallthroughRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/useAllAssets.test.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/useAllAssets.tsx, js_modules/dagster-ui/packages/ui-core/src/automation/MergedAutomationRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationDefinitionsRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationDocsRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationOverviewRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationPageHeader.oss.tsx, js_modules/dagster-ui/packages/ui-core/src/instance/useCodeLocationPageFilters.tsx, js_modules/dagster-ui/packages/ui-core/src/jobs/JobsPageContent.tsx, js_modules/dagster-ui/packages/ui-core/src/nav/LeftNavRepositorySection.tsx, js_modules/dagster-ui/packages/ui-core/src/nav/__tests__/RepoOptionVisibility.test.tsx, js_modules/dagster-ui/packages/ui-core/src/nav/useCodeLocationsStatus.tsx, js_modules/dagster-ui/packages/ui-core/src/overview/OverviewResourcesRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/pipelines/PipelineOrJobDisambiguationRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/LocationBaseDataFetcher.ts, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/WorkspaceContext.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/WorkspaceManager.ts, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/WorkspaceStatusPoller.ts, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/__tests__/WorkspaceContext.test.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/__tests__/WorkspaceManager.test.ts, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceContext/util.ts, js_modules/dagster-ui/packages/ui-core/src/workspace/WorkspaceRoot.tsx
After adding assets to the WorkspaceContext we changed the loading variable to include the loading of assets. This is making non-asset related pages wait for assets and in the case of kraftheinz (over bad internet) their page load time on a fresh load (no indexeddb cache) is like 5 minutes. I added `loadingNonAssets` which is equivalent to the previous loading state and `loadingAssets` so that asset pages only depend on assets loading.
jest. local app proxy
=> Split up loading variable in WorkspaceContext

js_modules/dagster-ui/packages/ui-core/src/assets/asset-checks/AssetChecks.tsx
Right now, asset check executions are displayed in the order they are returned from the db, which uses ids for pagination/sorting. In rare cases it appears that ids may not match with evaluation timestamps. This PR ensures that evaluations rendered on the page will always show the newest evaluation first.
=> [ui] Ensure asset check evaluations are sorted by timestamp

python_modules/dagster/dagster/_core/definitions/asset_selection.py, python_modules/dagster/dagster/_core/selector/subset_selector.py
Small tweak to asset selection evaluation which might marginally improve performance. When finding upstream or downstream assets for certain selections, we iterate over every asset in the selection and find its upstreams. This means we conduct `n` BFSes for `n` assets, duplicating work if they share parents/children. This change simply merges the BFSes for those `n` assets into a single search, which should marginally improve performance for large interconnected graphs.
Deduplicated asset graph traversals when evaluating upstream or downstream asset selections for a large set of assets, substantially speeding up some selection evaluations.
=> Asset selection perf improvements

python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_check_yaml_command.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_list_commands.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_scaffold_commands.py, python_modules/libraries/dagster-dg-core/dagster_dg_core/context.py, python_modules/libraries/dagster-dg-core/dagster_dg_core/env.py
Addresses #30854. Adds a new `has_defs_path` property to the dg context which can be used to alter command behavior if a defs folder is not present. This is used for `dg list env`, which only uses the defs folder to populate the list of components consuming env vars, a secondary piece of functionality.
For cases where a defs folder is expected, `context.defs_path` will now raise a clearer user-facing error about the missing `defs` folder.
```sh
$ dg list env
┏━━━━━━━━━┳━━━━━━━┳━━━━━━━━━━━━┓
┃ Env Var ┃ Value ┃ Components ┃
┡━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━━┩
│ FOO     │ ✓     │            │
└─────────┴───────┴────────────┘
$ dg check yaml
...
dagster_dg_core.error.DgError: Defs folder not found. Ensure folder `src/no_defs_demo/defs` exists in the project root.
```
New unit tests for `dg list …
=> Better error message for missing defs folder, allow list env without one

js_modules/dagster-ui/packages/ui-core/src/assets/AssetEvents.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/useAssetEventsFilters.tsx
Context:
https://dagsterlabs.slack.com/archives/C03CCE471E0/p1751466532317749
This is a bit odd - we present both “Type” (Materialization / Observation) and “Status” (Success / Failure) filters, but under the hood these map to three event types in our system, and Status only exists in the new Observe UI.
This fixes support for the Type filter, which was being ignored, and allows you to use the two filters together. Type=Materialization gives you `FAILED_TO_MATERIALIZE` and `MATERIALIZATION` events, and adding Status=Success filters that to just the latter. There is no “failed observation” event, and filtering to that yields no results.
I also fixed the icons used in the submenus of this filter picker since they were all "job"
I also hid the "Status" filter for non-materializable assets, …
=> [ui] Update the asset event filters to fix type filtering

js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetHealthDataProvider.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetCatalogTableV2.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/catalog/useSelectionHealthData.tsx
We weren't waiting for asset health data to load because the condition `(Object.keys(result.liveDataByNode).length === assetKeys.length` would be immediately true while assets were loading/being filtered (0 assets). To fix this add a loading prop to `useAssetsHealthData` so that we can wait until asset keys are calculated and passed in before checking the condition.
Datadog: https://app.datadoghq.com/rum/sessions?query=%40type%3Aview%20%40view.id%3A56ef928b-2476-40fd-bb76-5440055245d5&fromUser=false&from_ts=1751396498033&to_ts=1751482898033&live=true
=> [Observe][Perf Telemetry] Wait for asset health data to load

python_modules/dagster-test/dagster_test/components/test_utils/test_cases.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/integration_test_defs/validation/defs_folder_no_attributes/defs.yaml, python_modules/libraries/dagster-dg-core/dagster_dg_core/check.py
It is reasonable to want to specify some components without attributes, e.g. a `DefsFolderComponent` with only post-processing steps. Previously, such YAML files would trigger yaml check exceptions, since we explicitly index into the `attributes` key. This PR uses `.get` instead.
New unit test.
[dg] Fixed an issue where `dg dev` and `dg check yaml` would error for YAML components lacking an `attributes` field.
=> [dg][fix] fix check yaml for components which do not have an attributes key specified

js_modules/dagster-ui/packages/ui-core/src/graph/asyncGraphLayout.ts
Currently the asset graph is sometimes ending up in an infinite loading state.
From my repro I was able to see that we were marking asset layout requests as cancelled (which happens in the return of layout effect) yet another layout effect does not fire... this means we end up throwing away the layout without scheduling a new layout. While debugging I saw we were throwing it away even though the layout cache key hasn't changed so add a check of the layout cache key as a further check that the layout should really be cancelled.
local testing
=> [Asset graph] Workaround fix for long loading times

python_modules/libraries/dagster-databricks/dagster_databricks/databricks.py, python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_databricks.py, python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_pyspark.py, python_modules/libraries/dagster-databricks/setup.py
Bumps the `databricks-sdk` version from `v0.17.0` to `v0.47.0`, to go alongside the pin in `dbt-databricks`, and bring the SDK to something more modern. Mimics attempts made in https://github.com/dagster-io/dagster/pull/30920 and https://github.com/dagster-io/dagster/pull/29132. 
Some changes were made when instantiating `Config` objects - `credentials_provider` has been deprecated in favour of `credentials_strategy`. This appears to be a drop-in replacement, but some pyright warnings had to be suppressed.
Some changes to the mocks and types were required to get the tests to pass locally, as pagination in `JobsAPI.get_run` introduced in `v0.38` was causing tests to indefinitely hang via a stuck Python thread. The step launcher has been further tested on my own Databricks instance and …
=> [dagster-databricks] Update dagster-sdk version pin

examples/docs_snippets/docs_snippets/guides/components/shell-script-component/generated/2-shell-command-empty.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/templates/COMPONENT_TYPE/COMPONENT_TYPE_NAME_PLACEHOLDER.py.jinja, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_scaffold_commands.py
Updates the default scaffolded component class to mention that listed fields define *both* the YAML schema and the set of Python params. This makes it a bit more clear in e.g. our docs for Python-centric components that defining params is still useful.
=> [components] adjust hint about yaml schema to mention python params

js_modules/dagster-ui/packages/ui-core/src/app/Flags.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx, js_modules/dagster-ui/packages/ui-core/src/graph/asyncGraphLayout.ts, js_modules/dagster-ui/packages/ui-core/src/hooks/useDebugChanged.tsx, js_modules/dagster-ui/packages/ui-core/src/workers/WorkerThread.oss.ts
When we spawn a webworker it [receives the feature flags from the main thread](https://github.com/dagster-io/dagster/blob/5f69e4093ab41f627b5bd84df179bbec7e07f83a/js_modules/dagster-ui/packages/ui-core/src/workers/WorkerThread.oss.ts#L12) and [calls a function](https://github.com/dagster-io/dagster/blob/5f69e4093ab41f627b5bd84df179bbec7e07f83a/js_modules/dagster-ui/packages/ui-core/src/app/Flags.tsx#L134) to set feature flags that [ends up broadcasting those same flags back the main thread](https://github.com/dagster-io/dagster/blob/5f69e4093ab41f627b5bd84df179bbec7e07f83a/js_modules/dagster-ui/packages/ui-core/src/app/Flags.tsx#L137). Then [useFeatureFlags](https://github.com/dagster-io/dagster/blob/ae5344f8aec26a9205e57dd92d3d7f2e5f2dc34a/js_modules/dagster-ui/packages/ui-core/src/graph/ …
=> Fix AssetGraph -> Webworker infinite loop

python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/commands/ci/__init__.py, python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/commands/workspace/__init__.py, python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/config_utils.py, python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/gql.py, python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli_tests/test_ci_commands.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/plus/deploy_session.py
This fixes the remaining blocker to moving serverless over to use the new github action templates by default, which was the initial deploy failing while it was waiting for the agent to initially heartbeat.
The old github action worked around this by detecting the first github action run and bumping up the timeout for that case, which is fairly hacky. Instead lets just elevate it a bit for all serverless deploys.
This check was intended to quickly error out for users who forgot to set up a hybrid agent before running CI/CD or misconfigured their agent, which should not be as common of an issue for serverless deployments since the agent is automatically spun up for you.
=> Increase agent heartbeat timeout on serverless ci deploy calls

js_modules/dagster-ui/packages/ui-core/src/app/Util.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx, js_modules/dagster-ui/packages/ui-core/src/graph/asyncGraphLayout.ts, js_modules/dagster-ui/packages/ui-core/src/hooks/useQueryAndLocalStoragePersistedState.tsx
This PR resolves an infinite loading state caused by a race condition in the layout calculation system.
The Problem:
When useAssetLayout rapidly switches between different layout requests (e.g., from cache key A to B and back to A), the following sequence occurs:
Layout A starts calculating (state: {loading: true, layout: null, cacheKey: null})
Before A completes, a re-render triggers layout B
The worker for A gets terminated
When the component requests A again, it finds a cached promise that will never resolve (since its worker was terminated)
The Fix:
Added a clearEntry function that removes stale cache entries when their associated workers are terminated. This ensures subsequent requests for the same layout will start fresh rather than waiting on a promise from a dead worker.
BUT WAIT …
=> [Asset Graph] Fix infinite loading asset graph edge case

js_modules/dagster-ui/packages/ui-core/src/assets/AssetValueGraph.tsx
Addresses this issue: https://github.com/dagster-io/dagster/issues/31017
This is the only chart.js I could find that doesn't register the CategoryScale so I'm assuming this is where the issue is coming from but it's hard to tell since the report has a minified stack trace.
=> Add CategoryScale import from chart.js

python_modules/dagster/dagster/_daemon/asset_daemon.py
Summary:
Before, if an asset was removed and the request context chagned, it could lead to an exception while we were evaluating the asset keys targeted by the sensor. Now, we use a single asset graph for the duration of the tick.
BK, run DA locally
=> create a single asset graph per DA tick

js_modules/dagster-ui/packages/ui-core/src/asset-graph/SidebarAssetInfo.tsx
As title. Previously, if you used a condition with no explicit label, it wouldn't show up in the sidebar.
NOCHANGELOG
=> [CORE-280] Fix rendering of automation conditions without explicit labels

js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetCatalogTableV2.tsx
Similar to current catalog -- disable materializing all assets
=> [Observe] Disable materializing all assets in catalog

js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-selection/__tests__/useAssetSelectionFiltering.test.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-selection/useAssetSelectionFiltering.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/catalog/useSelectionHealthData.tsx
I originally added this after seeing some long frames but after adding lots of memoization in different parts we're fast enough without a worker that the worker just slows things down and adds overhead/complexity.
app-proxy
=> Remove worker for `useAssetGraphData`

js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetHealthDataProvider.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphData.tsx
We removed the worker for `useAssetGraphData` so the `graphDataLoading` state is no longer needed since it is synchronously calculated now.
=> Update `useAssetGraphData` loading state

python_modules/libraries/dagster-tableau/dagster_tableau/resources.py
Tableau spec must be of type data_source to be selected for refreshable data source IDs. 
Introducing new metadata keys in https://github.com/dagster-io/dagster/pull/31120 unveiled the issue - we were using `TableauDataSourceMetadataSet.extract(spec.metadata).has_extracts` to select, which was only selecting data sources with extracts, but adding the new metadata keys unveiled that we were not iterating on data sources, but all specs, so we must confirm that the spec is of type data_source before proceeding.
=> [dagster-tableau] Fix refreshable data source IDs in refresh_and_poll

.buildkite/dagster-buildkite/dagster_buildkite/steps/integration.py, integration_tests/python_modules/dagster-k8s-test-infra/dagster_k8s_test_infra/helm.py, integration_tests/test_suites/k8s-test-suite/tests/test_executor.py, python_modules/dagster-test/dagster_test/test_project/build.sh, python_modules/dagster-test/dagster_test/test_project/test_jobs/repo.py, python_modules/libraries/dagster-k8s/dagster_k8s/client.py, python_modules/libraries/dagster-k8s/dagster_k8s/executor.py, python_modules/libraries/dagster-k8s/dagster_k8s/job.py, python_modules/libraries/dagster-k8s/dagster_k8s/pipes.py, python_modules/libraries/dagster-k8s/dagster_k8s/utils.py, python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_executor.py, python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_pipes.py
Adds a new configuration option to the k8s executor which sets a Kubernetes Owner references [\(ref\)](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/object-meta/#System) to step jobs, pointing at the originating run pod. This lets users more easily trace back a step to the run pod which spawned it.
New unit, integration tests.
=> [k8s executor] Option to add `ownerReferences`s to k8s executor step jobs

python_modules/dagster/dagster/_core/storage/cloud_storage_compute_log_manager.py, python_modules/libraries/dagster-aws/dagster_aws/s3/compute_log_manager.py, python_modules/libraries/dagster-azure/dagster_azure/blob/compute_log_manager.py, python_modules/libraries/dagster-gcp/dagster_gcp/gcs/compute_log_manager.py
Summary:
Plenty of compute log managers return None for this field, let the cloud one do it too.
Test Plan: Pyright
=> [ez] Update typehint on download_url_for_type

python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py
dbt syntax supports multiple emails in the "owner" field, so we should too: https://docs.getdbt.com/docs/deploy/model-notifications#configure-groups
[dagster-dbt] The `@dbt_assets` decorator and associated APIs no longer error when parsing dbt projects that contain an owner with multiple emails.
=> [dagster-dbt] Support multiple emails for a dbt owner

examples/docs_snippets/docs_snippets/getting-started/quickstart/dg_check_defs.txt, examples/docs_snippets/docs_snippets/guides/components/index/23-dg-component-check.txt, examples/docs_snippets/docs_snippets/guides/components/index/31-dg-component-check-yaml.txt, examples/docs_snippets/docs_snippets/guides/components/index/32-dg-component-check-defs.txt, examples/docs_snippets/docs_snippets/guides/dg/using-env/11-dg-component-check-fixed.txt, examples/docs_snippets/docs_snippets/guides/tutorials/etl_tutorial/commands/dg-check-defs.txt, python_modules/dagster/dagster/components/core/tree.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/test_definitions_autoload.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/validation_tests/test_component_validation.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_check_yaml_command.py, python_modules/libraries/dagster-dg-core/dagster_dg_core/check.py
Augments any error raised in component load or defs building with the current state of the component load tree, e.g.
Update existing unit tests.
=> [components] Augment component load/build errors with tree

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/since_operator.py, python_modules/dagster/dagster_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_automation_condition.py
This introduces a generic TypeVar to represent the "new" Automation condition in `AutomationCondition.replace()`, and uses that TypeVar in the return type as well to give the caller more information about what class of `AutomationCondition` might be returned. 
This solves the problem where:
```python
dg.AutomationCondition.eager().replace(
"newly_updated", dg.AutomationCondition.data_version_changed()
).with_label("eager_respecting_data_version")
```
fails typechecking. This happens today because `replace` always returns `AutomationCondition`, and hence we don't know that `with_label` will exist on it (that only exists on `BuiltinAutomationCondition`).
But we should be able to know that `with_label` exists; `replace` always returns either `Self` or the type of `new`, both of which are …
=> Use a generic return type in AutomationCondition.replace()

js_modules/dagster-ui/packages/dg-docs-components/src/ComponentScaffolding.tsx
This should be `dg scaffold defs Component {component_name}` instead of `dg scaffold Component {component_name}`
/
=> [ui] wrong `dg scaffold  ...` command in the docs

python_modules/dagster/dagster/_core/definitions/assets/graph/asset_graph.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_deps.py
The comment here claims that we covered the case in the new unit test, but we did not. Now we do.
New test case
Fixed an issue where asset checks referencing asset keys that did not exist in the asset graph did not appear in the Dagster UI.
=> Create a stub asset for upstream keys referenced by asset checks that are not in the graph

python_modules/dagster/dagster/_core/definitions/partitions/context.py, python_modules/dagster/dagster/_core/definitions/partitions/definition/dynamic.py, python_modules/dagster/dagster/_core/definitions/partitions/definition/multi.py, python_modules/dagster/dagster/_core/definitions/partitions/definition/partitions_definition.py, python_modules/dagster/dagster/_core/definitions/partitions/definition/static.py, python_modules/dagster/dagster/_core/definitions/partitions/definition/time_window.py, python_modules/dagster/dagster/_core/definitions/partitions/mapping/identity.py, python_modules/dagster/dagster/_core/definitions/partitions/mapping/last.py, python_modules/dagster/dagster/_core/definitions/partitions/mapping/multi/base.py, python_modules/dagster/dagster/_core/definitions/partitions/mapping/specific_partitions.py, python_modules/dagster/dagster/_core/definitions/partitions/mapping/static.py, python_modules/dagster/dagster/_core/definitions/partitions/mapping/time_window.py, python_modules/dagster/dagster/_core/definitions/partitions/subset/all.py, python_modules/dagster/dagster/_core/definitions/partitions/subset/default.py, python_modules/dagster/dagster/_core/definitions/partitions/subset/partitions_subset.py, python_modules/dagster/dagster/_core/definitions/partitions/subset/time_window.py
Now we (finally) get to the meat of this stack. We have hit a glut of performance and runtime error landmine type issues due to the somewhat silly way all the partition-related methods work.
Basically all of our public methods (and private ones), take two optional parameters: `current_time` and `dynamic_partitions_store`. The curent time argument is only relevant for time-window partitions, and even then most methods function fine without it being set. However, if it is not set, then it becomes very easy to hit perf bottlenecks, specifically around getting the last partition key available. This of course depends on the current time, and so if we're constantly invalidating the cache then this means we have to do a moderately-expensive calculation many times. There are also correctness …
=> [partition-context] partition_loading_context guard

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition_evaluator.py, python_modules/dagster/dagster/_core/execution/asset_backfill.py, python_modules/dagster/dagster/_daemon/backfill.py
Adds the context guard to the two main areas where we do a lot of partition-related computations.
NOCHANGELOG
=> [partition-context] asset backfill and declarative automation use context guard

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/legacy/valid_asset_subset.py, python_modules/dagster/dagster/_core/definitions/partitions/subset/all.py, python_modules/dagster/dagster/_core/definitions/partitions/subset/default.py, python_modules/dagster/dagster/_core/definitions/partitions/subset/partitions_subset.py, python_modules/dagster/dagster/_core/definitions/partitions/subset/time_window.py, python_modules/dagster/dagster/_core/execution/context/input.py, python_modules/dagster/dagster_tests/definitions_tests/test_multi_partitions.py, python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py
This is an internal-only method and now that we're using the context guard behavior we can clean this function up a bit and remove the extraneous parameters.
NOCHANGELOG
=> [partition-context] get_partition_keys_not_in_subset

js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetHealthDataProvider.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphSupplementaryData.oss.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-selection/input/util.ts
Skip querying health data if we don't need it. We only need it if the user explicitly types a `status` filter. 
=> Only query health data if necessary

python_modules/dagster/dagster/_core/execution/context/asset_execution_context.py, python_modules/dagster/dagster/_core/execution/context/op_execution_context.py, python_modules/dagster/dagster/_core/execution/plan/inputs.py, python_modules/dagster/dagster_tests/execution_tests/misc_execution_tests/test_context.py
Implementation of #29898. Adds a new `AssetExecutionContext.load_asset_value` fn which can be used to dynamically load an asset's value in an asset body, rather than loading as part of the input parameters.
```python
@dg.asset(deps=[the_asset])
def the_downstream_asset(context: dg.AssetExecutionContext):
return context.load_asset_value(dg.AssetKey("the_asset"))
```
Unit tests.
- Introduced `AssetExecutionContext.load_asset_value`, which enables loading asset values from the IO manager dynamically rather than requiring asset values be loaded as parameters to the asset function. For example:
```python
@dg.asset(deps=[the_asset])
def the_downstream_asset(context: dg.AssetExecutionContext):
return context.load_asset_value(dg.AssetKey("the_asset"))
```
=> enable loading asset values from AssetExecutionContext

python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py, python_modules/dagster/dagster_tests/declarative_automation_tests/automation_condition_tests/user_defined/test_user_defined_automation_condition.py
Fixes an issue when attempting to serialize snapshot data as shown in the provided test case.
The core issue is that the `is_serializable` property was not properly recursing over the children of the referenced dep conditions.
unit
Fixed a bug that could cause code locations to fail to load when a custom python AutomationCondition was used as the operand of `AutomationCondition.any_deps_match()` or `AutomationCondition.all_deps_match()`
=> [da] Fix bug with serialization of user-defined conditions

python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py, python_modules/dagster/dagster_tests/definitions_tests/test_definitions_load_context.py, python_modules/libraries/dagster-airlift/dagster_airlift/core/components/airflow_instance/component.py, python_modules/libraries/dagster-airlift/dagster_airlift/core/load_defs.py, python_modules/libraries/dagster-snowflake/dagster_snowflake_tests/test_sql_component.py
Allows `Definitions.merge` to merge objects which have previously had the asset graph built, which currently triggers a check error.
The check error is currently blocking cross-component access in #30446. For cross-component accesses, a component triggers the a `Definitions` object to be built for another component, and subsequently accesses properties of that `Definitions` object. If that property requires resolution, such as the list of asset keys, it will cause the subsequent merging of `Definitions` objects at the folder level to fail this check.
Adds a new internal `merge_unbound_defs` which contains the assertion.
=> [definitions] rm assertion for unresolved definitions, add merge_unbound_defs

js_modules/dagster-ui/packages/ui-core/src/asset-graph/useAssetGraphSupplementaryData.oss.tsx, js_modules/dagster-ui/packages/ui-core/src/hooks/__tests__/useStableReferenceByHash.test.tsx, js_modules/dagster-ui/packages/ui-core/src/hooks/useStableReferenceByHash.tsx
Undo an earlier decision that theoretically leads to unbounded memory usage.
existing jest test
=> Rm global cache in `useStableReferenceByHash`

python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster/components/component/component.py, python_modules/dagster/dagster/components/core/context.py, python_modules/dagster/dagster/components/core/tree.py, python_modules/dagster/dagster_tests/components_tests/code_locations/component_component_deps/defs/depends_on_my_python_defs/definitions.py, python_modules/dagster/dagster_tests/components_tests/code_locations/component_component_deps_custom_component/defs/depends_on_my_python_defs/custom_component.py, python_modules/dagster/dagster_tests/components_tests/code_locations/component_component_deps_yaml/defs/depends_on_my_python_defs/custom_component.py, python_modules/dagster/dagster_tests/components_tests/code_locations/component_component_deps_yaml/defs/depends_on_my_python_defs/defs.yaml, python_modules/dagster/dagster_tests/components_tests/code_locations/component_component_deps_yaml/defs/my_python_defs/definitions.py, python_modules/dagster/dagster_tests/components_tests/code_locations/component_component_deps_yaml/defs/my_python_defs/defs.yaml, python_modules/dagster/dagster_tests/components_tests/integration_tests/test_cross_component_deps.py, python_modules/libraries/dagster-dbt/dagster_dbt/components/dbt_project/component.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/code_locations/dependency_on_dbt_project_location/defs/depends_on_dbt/definitions.py
Move x-component loading to use the `component_tree`, now available on the context, instead of brokering access through the context directly. The immediate benefit is that all component loads & defs builds are now cached, and are loaded/built at most once.
```python
deps = context.component_tree.build_defs_at_path("my_python_defs").resolve_all_asset_keys()
```
```yaml
deps: "{{ component_tree.build_defs_at_path('my_python_defs').resolve_all_asset_keys()}}"
```
This is a bit clunky ergonomically, so curious for thoughts on how we might make this more compact.
Existing tests, new test invoking UDF.
=> [7/n] Move x-component access to use ComponentTree, cache defs load

python_modules/dagster/dagster/_core/remote_representation/external_data.py, python_modules/dagster/dagster/components/core/decl.py, python_modules/dagster/dagster/components/core/defs_module.py, python_modules/dagster/dagster/components/core/tree.py, python_modules/dagster/dagster/components/lib/definitions_component/__init__.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/integration_test_defs/definitions/both_python_defs_and_components/dg.toml, python_modules/dagster/dagster_tests/components_tests/integration_tests/integration_test_defs/definitions/both_python_defs_and_components/top_level.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/test_definitions_autoload.py, python_modules/dagster/dagster_tests/components_tests/test_definitions.py, python_modules/dagster/dagster_tests/components_tests/unit_tests/__snapshots__/test_pipes_subprocess_script_collection.ambr, python_modules/dagster/dagster_tests/components_tests/unit_tests/test_component_decl.py, python_modules/dagster/dagster_tests/components_tests/unit_tests/test_pipes_subprocess_script_collection.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/__snapshots__/test_list_commands.ambr, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_list_commands.py
Properly handles loading plain-old-Python definitions and Python component instances from `.py` files in the default, non `terminate_autoloading_on_keyword_files` world.
This actually simplifies our Decl codepaths a bit by combining the composite component with the python defs component to a single component which represents a Python file (and may hold plain defs or other components).
New unit test.
> [components] Python component instances are now properly loaded from ordinary Python files.
=> [component loading] Properly load pythonic components from ordinary defs Python files

python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance_reexecution.py
It's possible for a run to do all of its intended work but still fail (for example, it finishes all its steps and then fails during run cleanup, or completes all its asset materializations but then the step fails). In this case, the retry logic will return an empty list of steps/assets/checks, and then either fail with an inscrutable error related to io managers, or worse, sometimes try to run every step (!) This fixes that by detecting the error and raising an informative exception.
New test cases, simulate manually
Using the "Retry from Asset Failure" option when retrying a run that failed after materializing all of its assets will now correctly indicate that there is no work that needs to be retried.
=> Raise an exception if you try to retry a run with no steps or assets or checks

python_modules/dagster-test/dagster_test/dg_defs/python/component.py, python_modules/dagster-test/dagster_test/dg_defs/yaml/defs.yaml, python_modules/dagster/dagster/components/core/defs_module.py, python_modules/dagster/dagster/components/list/list.py, python_modules/dagster/dagster_tests/components_tests/test_definitions.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/__snapshots__/test_list_commands.ambr
Adds a `dagster/component_origin` metadata entry for all defs coming from yaml or python component instances. 
updated test
=> add component origin metadata to definitions

.claude/coding_conventions.md, .claude/dev_workflow.md, .claude/python_packages.md, CLAUDE.md, MIGRATION.md, Makefile, python_modules/dagster-test/dagster_test_tests/test_package_registry.py, python_modules/libraries/dagster-shared/dagster_shared/record/__init__.py
This commit creates agent-parseable documentation to enable reliable code generation that follows Dagster OSS conventions and norms.
**.claude/coding_conventions.md** (35 lines): Establishes coding standards requiring `@record` decorator instead of `@dataclass`, builtin types instead of typing module equivalents, and proper noqa markers for print statements.
**.claude/dev_workflow.md** (50 lines): Documents mandatory `make ruff` execution after Python edits, manual fix procedures, and pytest standards.
**.claude/python_packages.md** (138 lines): Maps 80+ repository packages to filesystem locations across core, cloud, database, ML, and utility categories.
**CLAUDE.md** (30+ lines): Adds "Quick References" section linking to new documentation files and reinforces mandatory `@record` usage …
=> Add .md files and documentation to make Claude more effective in Dagster monorepo

pyproject.toml, pyright/master/include.txt, scripts/install_dev_python_modules.py
https://github.com/dagster-io/dagster/pull/31126 consolidated some tooling but left a few dangling references that are standing in the way of successfully running `make dev_install`.
=> Remove dangling references to buildkite

python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py
This reverts commit a8a0bc9b0c14d463c65e35cd8c6d74a654348dc0. Test here is insufficient because it tests on an AssetGraph and needs to be testing on a RemoteAssetGraph. Will follow up in the subsequent fix about why pyright didn't catch a glaring type error.
=> Revert "ensure that execution_type is always set on the ExecutionPlanSnapshot for all step outputs that correspond to asset keys (#31248)"

js_modules/dagster-ui/packages/ui-core/src/runs/types/useRunsFeedEntries.types.ts
I think the sequence of lints in tox has drifted from `make lint` over time
=> Fix ui lint

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/ai.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/docs.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_docs_commands.py
Add a cli entry point for getting the details of a specfiic component type 
added test
example non-json output 
```
$ dg docs component dagster.UvRunComponent
Type: dagster.UvRunComponent
Description: Represents a Python script, alongside the set of assets or asset checks that it is responsible for executing.
Accepts a path to a Python script which will be executed in a dagster-pipes subprocess using the `uv run` command.
Example:
```yaml
type: dagster.UvRunComponent
attributes:
execution:
path: update_table.py
assets:
- key: my_table
```
```
=> [dg cli] docs for component by type

js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogActivityChart.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogInsightsLineChart.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogRateCard.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogTopAssetsChart.tsx, js_modules/dagster-ui/packages/ui-core/src/ui/__tests__/formatDuration.test.ts, js_modules/dagster-ui/packages/ui-core/src/ui/formatDuration.ts, js_modules/dagster-ui/packages/ui-core/src/ui/formatters.tsx
We definitely need to make some tweaks here. I think for the rate cards we should probably be more precise?
Before:
After:
=> [Observe][insights] Make units adapt to scale

python_modules/dagster/dagster/_core/execution/asset_backfill.py
This is pretty hard to reproduce in unit tests, but we generally need to be pretty strict about the cases where we launch a child with its parent because our run building machinery is strict about the way in which it builds runs.
The core thing here is that in some cases, we have a target parent subset of: `[a, b]`, and that maps to a target child subset of `[a, b]`. The previous logic would see this, see they had the same partitions definition, all that good stuff, and decide that it was safe for them to get materialized in the same run. However, that target parent subset that we got from the bfs iteration would not actually be all of the target parent partitions that we planned to materialize, and we would end up requesting:
- parent: [a, b, c, d, e]
- child: [a, b]
Then, our run …
=> [backfill] Fix issue that could cause incorrect backfill requests

python_modules/dagster/dagster/_core/definitions/assets/graph/base_asset_graph.py, python_modules/dagster/dagster/_core/definitions/assets/graph/remote_asset_graph.py, python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster_tests/core_tests/instance_tests/execution_plan_snapshot_without_execution_type.json, python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py
Now with better type hinting and better testing.
New test case that was failing before and better matches the actual workflow (changed to a remote asset graph)
=> Bring back "ensure that execution_type is always set on the ExecutionPlanSnapshot for all step outputs that correspond to asset keys (#31248)"

python_modules/libraries/dagster-tableau/dagster_tableau/asset_utils.py, python_modules/libraries/dagster-tableau/dagster_tableau/resources.py, python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_reconstruction.py
This PR changes the behavior of `refresh_and_poll` so that we emit asset observation events for sheets and dashboards.
In Tableau, only data sources with extracts can be materialized (refreshed). Other data sources are live connections, and sheets/dashboards are views of their underlying data sources.
Because of that, sheets and dashboards are not directly materialized via Dagster. We can observe these assets and update the metadata accordingly as a workaround.
Updated tests with BK.
[dagster-tableau] Tableau sheets and dashboards are now being observed and instead of being materialized when using `refresh_and_poll` inside the `@tableau_assets` asset decorator.
=> [dagster-tableau] Yield AssetObservation events for sheets and dashboards

python_modules/libraries/dagster-tableau/dagster_tableau/resources.py, python_modules/libraries/dagster-tableau/dagster_tableau/translator.py, python_modules/libraries/dagster-tableau/dagster_tableau_tests/conftest.py, python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_asset_specs.py, python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_reconstruction.py, python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_resources.py
When fetching workbook details via the Tableau Metadata API (GraphQL), sheets for which the LUID is missing are considered hidden. Previously, we were discarding them, but also discarding their data sources in the process.
In Tableau, dashboards can contain hidden sheets - we want to make sure we represent these dashboards as it should, with their upstream data sources, even if sheets between these dashboards and upstream data sources are hidden. 
This PR updates the code so that we represent upstream data sources as direct deps of these dashboards in the asset lineage.
[dagster-tableau] Dashboards containing hidden sheets are now correctly linked to upstream data sources.
=> [dagster-tableau] Support dashboards and data sources with hidden sheets

python_modules/libraries/dagster-tableau/dagster_tableau/asset_utils.py, python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_asset_specs.py, python_modules/libraries/dagster-tableau/dagster_tableau_tests/test_reconstruction.py
Embedded data sources can't be refreshed using the [Update Data Source Now](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_data_sources.htm#update_data_source_now) endpoint in the Tableau REST API. It's only possible to refresh them using the [Update Workbook Now endpoint](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_workbooks_and_views.htm#update_workbook_now), which refresh all data sources for a given workbook - we want to avoid this solution for now and work with Tableau to figure out if there is an alternative.
This PR makes embedded data sources external data sources for now, since refreshing them with the "Update Data Source Now" endpoint raises an exception.
=> [dagster-tableau] Make embedded data sources external assets

python_modules/libraries/dagster-tableau/dagster_tableau/asset_utils.py, python_modules/libraries/dagster-tableau/dagster_tableau/resources.py, python_modules/libraries/dagster-tableau/dagster_tableau_tests/conftest.py
Similar as #31260 but for data sources too, since using ObserveResults was emiting a materialization event.
=> [dagster-tableau] Use AssetObservation instead of ObserveResult

python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_install_completion.py
When we refactored our divergent buildkite step builders into a single consolidated step builder, this test regressed.
The refactor cut down on implicitly passed env vars and I think that caused this particular test to start failing. I've had trouble running down the exact env var because, well, it wasn't explicitly being set...
But given what this test is doing, I think it's better that we mock our shell and actually test the different conditions here. Instead of having a test whose assertions are tied to the environment in which it's running.
=> Mock SHELL in install completion tests

.claude/commands/validate_changed_docstrings.md, python_modules/automation/automation/docstring_lint/changed_validator.py, python_modules/automation/automation/docstring_lint/file_discovery.py, python_modules/automation/automation/docstring_lint/path_converters.py, python_modules/automation/automation_tests/docstring_lint_tests/test_changed_validator.py, python_modules/automation/automation_tests/docstring_lint_tests/test_path_converters.py, scripts/validate_changed_docstrings.py
This PR adds a new docstring validation tool that checks Python docstrings in uncommitted changed files. The tool helps catch RST syntax errors and other docstring issues early in development, before they reach the documentation build process.
The implementation includes:
- A modular framework for finding changed files using git
- Extraction of Python symbols with docstrings from changed files
- Integration with the existing docstring validation tool
- Path converters for different project structures
- A command-line script to run the validation
- Created comprehensive unit tests for all components
- Tested with various file structures and docstring formats
- Verified error detection and reporting for invalid RST syntax
- Confirmed proper handling of Dagster's specific package structure …
=> Add ability to check all uncommited files and add claude command to invoke it

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/ai.py
works now that they added the flag 
`dg ai` select gemini
[dg] `dg ai` now supports `codex` and `gemini` CLI agents
=> [dg ai] add gemini support

python_modules/libraries/dagster-databricks/setup.py
We need changes in latest versions of Databricks sdk for our new Databricks Serverless pipes. Bumping up the pin so that we support databricks sdk 0.59.
Tests and pyright checks pass. Most changes to support newer versions of the sdk were done in #31023 3 weeks ago.
=> [dagster-databricks] bump databricks sdk version to <0.60

js_modules/dagster-ui/packages/ui-core/src/instance/JobMenu.tsx
Removes the runTimeFragment type from the job action menu to make the component more reusable. This change allows us to add the action menu to the Failed Jobs list on the new Dagster+ Homepage.
=> Remove runTimeFragment type from job action menu

python_modules/dagster/dagster/_core/execution/asset_backfill.py
We have some very confusing behavior at the moment, where in cases where an asset has multiple parents, it's possible for the system to determine that the entirety of a downstream asset may be able to run with one of its parents, and then when another parent is factored in and we determine that we cannot run with part of that parent, we don't accurately remove all assets from the "passed subset".
The core idea here is that we believed we could execute the given subset with its parent because all of the subset would be included in the resulting run. As soon as anything influences this fact, the core assumption breaks down and the partitions get sent to separate runs.
This is a super-targeted fix for this behavior and realistically this entire codepath should be reworked.
NOCHANGELOG
=> [backfill] targeted fix for can run with parent logic

python_modules/dagster/dagster/_annotations.py, python_modules/dagster/dagster_tests/utils_tests/test_annotations.py
Enhanced the `@public` decorator to support class annotations in addition to methods. Previously, the decorator only worked for methods, but now it can be applied to entire classes to mark them as public. The implementation ensures that the public status is only applied to the specific class being decorated, not to its superclasses or subclasses.
This is to setup a system that maintains the invariant that all @public classes and functions are in our public docblocks and that all things in our .rst file are marked public. We are going to programmaticaly enforce this so to make this easier for tools and developers alike.
Added comprehensive tests that verify:
- Classes can be marked as public using the decorator
- Public status is correctly detected with `is_public()`
- Inheritance doesn't …
=> Extend @public annotation to support classes

python_modules/dagster/dagster/components/component/component_loader.py, python_modules/dagster/dagster/components/component_scaffolding.py, python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_component_defs.py
Fixes #30533 by dg-ifying the imports for a component definition scaffolded in python format.
=> Fix component python scaffold import

CLAUDE.md, python_modules/automation/automation/docs_cli/commands/check.py, python_modules/automation/automation/docs_cli/commands/ls.py, python_modules/automation/automation/docs_cli/commands/watch.py, python_modules/automation/automation/docstring_lint/changed_validator.py, python_modules/automation/automation/docstring_lint/cli.py, python_modules/automation/automation/docstring_lint/public_symbol_utils.py, python_modules/automation/automation/docstring_lint/validator.py, python_modules/automation/automation_tests/docs_cli_tests/test_integration.py, python_modules/automation/automation_tests/docs_cli_tests/test_ls_commands.py, python_modules/automation/automation_tests/docstring_lint_tests/test_discover_section_headers.py, python_modules/automation/automation_tests/docstring_lint_tests/test_fixtures/__init__.py, python_modules/automation/automation_tests/docstring_lint_tests/test_fixtures/test_public_class.py, python_modules/automation/automation_tests/docstring_lint_tests/test_known_valid_symbols.py, python_modules/automation/automation_tests/docstring_lint_tests/test_method_docstrings.py, python_modules/automation/automation_tests/docstring_lint_tests/test_public_methods.py, python_modules/automation/automation_tests/docstring_lint_tests/test_public_symbol_utils.py
This PR adds support for validating `@public`-annotated methods on top-level exported classes. The changes include:
1. Improved docstring validation for top-level exported symbols
2. Added support for validating `@public`-annotated methods on classes
3. Enhanced section header detection with a more comprehensive list of allowed section headers
4. Added utilities for working with `@public`-annotated symbols
These improvements will help ensure consistent documentation quality across both top-level symbols and public methods, making the API documentation more complete and reliable.
- Added comprehensive test suite for `@public` method detection and validation
- Created test fixtures with various method types (instance, static, class, property)
- Added tests for section header detection and …
=> Add comprehensive method docstring tests

python_modules/automation/automation/docstring_lint/changed_validator.py, python_modules/automation/automation/docstring_lint/cli.py, python_modules/automation/automation/docstring_lint/watcher.py
Replace `print()` statements with `click.echo()` in the docstring linting tools. This change improves error handling by using Click's built-in functionality for output management, including proper stderr handling for error messages. Eliminates ruff noqa directives.
BK
=> Use click.echo instead of print

python_modules/automation/automation/docstring_lint/exclude_lists.py, python_modules/automation/automation/docstring_lint/public_api_validator.py, python_modules/dagster/dagster/_core/execution/context/asset_check_execution_context.py, python_modules/dagster/dagster/_core/execution/context/system.py
Added @public to a couple decorators in order to debug the process.
1. Adding proper `@public` decorators to `AssetCheckExecutionContext` and `TypeCheckContext` classes
2. Enhancing the public symbol detection to use the exported module path as the canonical path
3. Implementing a more reliable method to check if symbols are exported using dynamic imports instead of regex parsing
4. Adding a cache for package discovery to improve performance
5. Removing `AssetCheckExecutionContext` and `TypeCheckContext` from the exclude list since they're now properly marked as public
These changes make our public API documentation more accurate by correctly identifying where symbols are exported from, which is important for users of our API.
BK
=> Improve @public API validation with dynamic imports and canonical module paths

python_modules/automation/DAGSTER_DOCS_CLI.md, python_modules/automation/automation/docs_cli/commands/watch.py, python_modules/automation/automation_tests/docs_cli_tests/test_watch_commands.py
Renamed the `docstring` command to `docstrings` in the Dagster docs CLI to better reflect that it operates on multiple docstrings. Updated all references to this command in documentation, code, and tests to maintain consistency.
Ran the test suite for the docs CLI to ensure all tests pass with the renamed command. Verified that the command help text and error messages correctly reflect the new command name.
=> Make docstring docstrings for consistency

js_modules/dagster-ui/packages/ui-core/src/launchpad/useLaunchMultipleRunsWithTelemetry.ts, js_modules/dagster-ui/packages/ui-core/src/util/buildExecutionParamsList.ts
If a sensor specifies an asset selection, or if the RunRequest returned by a sensor or schedule evaluation specifies an asset selection, we should pass that asset selection through to the run execution in the dry run sensor/schedule ui flow. 
In fixing this, I noticed that we are not passing through asset check selections either, I'll fix that in a stacked PR (#30998). I also think the UI could use some help to display the selected assets better, so i'll take a stab at that too
fixes #27647 
tested in local dev. I looked at writing a unit test, but it seemed like the mocks for the sensor dry run page hard code the execution parameters when launching a run, so i dont think i would be able to test that the results from evaluating the sensor are correctly transformed into the execution …
=> pass through asset selection when launching a sensor/schedule preview

js_modules/dagster-ui/packages/ui-core/src/launchpad/useLaunchMultipleRunsWithTelemetry.ts, js_modules/dagster-ui/packages/ui-core/src/util/buildExecutionParamsList.ts, python_modules/dagster/dagster/_core/definitions/run_request.py, python_modules/dagster/dagster/_daemon/sensor.py, python_modules/dagster/dagster/_scheduler/scheduler.py, python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py
Turns out if you return a RunRequest that specifies a selection of asset check keys from a schedule, we don't respect that when launching the run 
new unit tests
Schedules now support specifying a subset of asset checks to execute in a `RunRequest`.
=> support asset checks in run requests in schedules

python_modules/dagster/dagster/_config/pythonic_config/config.py, python_modules/dagster/dagster_tests/core_tests/pythonic_config_tests/test_pythonic_config_types.py
Fix issue with PermissiveConfig dot notation by parsing edge cases of extra fields as attributes to the config instantiation.
Co-author: @BoLiuV5
Original issue 22777 dev: @arookieds 
Linked in dev: @alangenfeld
Related Issue: #22777 
Related upstream Pydantic issue (closed without fix): [pydantic#4617](https://github.com/pydantic/pydantic/issues/4617)
This PR addresses an edge case in how PermissiveConfig handles extra fields passed via keyword arguments. Under the current implementation, unrecognized fields are stored in __pydantic_extra__ (or accessible via .model_extra or dict(config).get("key")), but are not accessible via dot notation (e.g., config.foo) unless explicitly declared in the model.
This leads to breakages in downstream use cases where developers expect arbitrary config …
=> Fix issue with PermissiveConfig dot notation #22777 

python_modules/dagster/dagster/components/utils/__init__.py, python_modules/dagster/dagster/components/utils/translation.py, python_modules/dagster/dagster_tests/components_tests/unit_tests/test_spec_processing.py, python_modules/libraries/dagster-airbyte/dagster_airbyte/components/workspace_component/component.py, python_modules/libraries/dagster-dbt/dagster_dbt/components/dbt_project/component.py, python_modules/libraries/dagster-dlt/dagster_dlt/components/dlt_load_collection/component.py, python_modules/libraries/dagster-fivetran/dagster_fivetran/components/workspace_component/component.py, python_modules/libraries/dagster-powerbi/dagster_powerbi/components/power_bi_workspace/component.py, python_modules/libraries/dagster-sling/dagster_sling/components/sling_replication_collection/component.py
Refactored translator logic in our various components by moving shared translation functionality to a new `TranslatorResolver` class to standardize translation function resolution across component types.
Simple translation, which passes along the underlying entity as a template var called `data`, can be accomplished with the following:
```python
class MyComponent(Component, Resolvable):
translation: ResolvedTranslationFn[DataType]
```
For cases where the user wants to customize the mapping of underlying entity -> template vars, they can use `TranslatorResolver`:
```python
class MyComplexDataType(BaseModel):
name: str
id: int
class MyComponent(Component, Resolvable):
translation: Annotated[
TranslationFn[MyComplexDataType],
TranslationFnResolver[MyComplexDataType]( …
```
=> [components] move translation logic to TypeVar-ed resolver

python_modules/dagster/dagster/_core/execution/asset_backfill.py
Summary:
One of the conseuqences of having a bigger candidate subset on each tick now (e.g. anything downstream of any newly materiaized asset or failed asset) is that we are a lot likely to be considering subsets here that are already in one of the materialized/failed/requested subsets. We already list those subsets so it's not particularly useful to indicate that a subset was rejected for being on one of them, so remove it. Now we basically only include this information if we're waiting for a particular parent to materialize first).
(I do think we could consider logging what the full candidate subset is on each tick to help reverse engineer how the BFS went)
BK
=> show fewer failure reasons when candidate subsets aren't considered for obvious reasons

python_modules/dagster/dagster/_core/definitions/definitions_class.py, python_modules/dagster/dagster/_core/definitions/schedule_definition.py, python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py
we were de-syncing nested jobs as part of the update, fix by updating them and ensuring we re-use the same object if the job is additionally passed directly to `Definitions` 
updated test
[bugfix] incorrect duplicate definitions are no longer created when including jobs for schedules & sensors when loading from a `defs` folder
=> handle nested jobs in with_definition_metadata_update

python_modules/automation/automation/docs_cli/commands/check.py, python_modules/automation/automation/docstring_lint/exclude_lists.py, python_modules/automation/automation_tests/docs_cli_tests/test_check_commands.py, python_modules/automation/automation_tests/docs_cli_tests/test_exclude_lists_audit.py
Added a new CLI command `check exclude-lists` to audit the exclude lists used in documentation validation. This command helps identify symbols that no longer need to be in the exclude lists because they now have proper documentation or decorators. The command has three options:
- `--missing-public`: Checks for symbols in `EXCLUDE_MISSING_PUBLIC` that now have `@public` decorators
- `--missing-rst`: Checks for symbols in `EXCLUDE_MISSING_RST` that now have RST documentation
- `--missing-export`: Checks for symbols in `EXCLUDE_MISSING_EXPORT` that are now exported at top-level
Additionally, I removed several symbols from the `EXCLUDE_MISSING_PUBLIC` list that have been fixed, reducing the total count from 309 to 297.
I ran the new command with each option to verify it correctly identifies …
=> Add check exclude-lists so we can audit the exclude lists while we add @public decorators to everything

python_modules/automation/automation/dagster_docs/commands/watch.py, python_modules/automation/automation/dagster_docs/watcher.py, python_modules/automation/automation_tests/dagster_docs_tests/test_watch_commands.py, python_modules/automation/setup.py
Implemented the `--changed` flag functionality for the `watch docstrings` command, which allows monitoring files that have been modified in git. This feature automatically validates docstrings in Python files as they change, making it easier to maintain documentation quality during development.
This will be a nice default dev loop as you don't have to copy and paste symbol names around.
The implementation includes:
- A new `ChangedFilesWatcher` class that monitors git-modified files
- Git integration to detect changed files
- Support for .gitignore patterns to avoid watching irrelevant files
- Automatic refreshing of the watch list when files change status
dagster-docs watch docstrings --changed
=> Support --changed in watch docstrings command

examples/docs_snippets/docs_snippets/concepts/partitions_schedules_sensors/schedules/schedules.py, examples/docs_snippets/docs_snippets/docs_beta/guides/automation/simple-schedule-example.py, examples/docs_snippets/docs_snippets/guides/automation/simple-schedule-example.py
We support a `target` argument to schedules which can make examples much less verbose.
Read.
Example
=> In the scheduling tutorials, use target instead of passing in explicit asset jobs

python_modules/libraries/dagster-pyspark/setup.py
Address #30816. It appears that #30211 was made about a month ago due to some failing tests (described in #30207) in dagster-duckdb-pyspark. I've confirmed that those failing tests do not affect dagster-pyspark or dagster-databricks, so it seems reasonable to remove the constraint on pyspark<4. This would allow users of these libraries who aren't using dagster-duckdb-pyspark to still use spark v4.
If y'all would prefer me putting a minor version bound on 4.something instead of <5 to be more conservative I'm happy to, but it also seems that with the very limited way the dagster-pyspark and dagster-databricks libraries interact with spark that it's relatively unlikely a minor version bump will break them.
I also updated the python classifiers in the setup.py file just because I was in there …
=> Allow pyspark v4 (Rolling back #30211)

python_modules/dagster-pipes/dagster_pipes/__init__.py, python_modules/libraries/dagster-databricks/dagster_databricks/_test_utils.py, python_modules/libraries/dagster-databricks/dagster_databricks/pipes.py, python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_serverless_pipes.py
Fixes #27558.
This PR adds a new `PipesDatabricksServerlessClient` with other required classes to support Databricks Serverless.
How to use in Dagster code:
```python
import os
from dagster_databricks.pipes import PipesDatabricksServerlessClient
from databricks.sdk import WorkspaceClient
from databricks.sdk.service import jobs
pipes_databricks_resource = PipesDatabricksServerlessClient(
client=WorkspaceClient(
host=os.environ["DATABRICKS_HOST"],
token=os.environ["DATABRICKS_TOKEN"],
),
volume_path="/Volumes/catalog/schema/volume",
)
@dg.asset
def databricks_asset(
context: dg.AssetExecutionContext, pipes_databricks: PipesDatabricksServerlessClient
):
task = jobs.SubmitTask.from_dict(
{
"task_key": "serverless_pipes_task",
"notebook_task": {
"notebook_path": …
```
=> [dagster-databricks] Support databricks serverless with pipes client

js_modules/dagster-ui/packages/ui-components/src/components/ListItem.tsx, js_modules/dagster-ui/packages/ui-components/src/components/css/ListItem.module.css
as titled.
changed the estimateSize on the automations table to `10` and saw that we still rendered the rows at the correct height.
=> Fix ListItem to actually dynamic measure rows

python_modules/dagster/dagster/_core/execution/asset_backfill.py, python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py, python_modules/dagster/dagster_tests/declarative_automation_tests/legacy_tests/scenarios/asset_graphs.py, python_modules/dagster/dagster_tests/execution_tests/misc_execution_tests/test_asset_backfill.py
Fix a lineage issue when self-dependant assets are launched in the same run as non-self-dependant assets
Summary:
follow-on fix to https://github.com/dagster-io/dagster/pull/31315, making sure that we still capture the case where there are two parents and one of them is yourself.
Test Plan: New test case that was failing before
=> Fix a lineage issue when self-dependant assets are launched in the same run as non-self-dependant assets

python_modules/dagster/dagster/_core/execution/asset_backfill.py, python_modules/dagster/dagster_tests/declarative_automation_tests/legacy_tests/scenarios/asset_graphs.py, python_modules/dagster/dagster_tests/execution_tests/misc_execution_tests/test_asset_backfill.py
Summary:
Try to make the fix in https://github.com/dagster-io/dagster/pull/31315 even more targeted without affecting throughput as much - if a parent is actively being materialized this tick, be more careful about what child partitions get submitted, to minimize the risk of inadvertently combining them into a single run incorrectly. But if we are just reacting to parent materializations and the parent itself is not being materialized on this tick too, only remove the specific partitions that are
=> only filter out the entire parent subset if it has any partitions being materialized this tick

python_modules/automation/automation_tests/dagster_docs_tests/test_known_valid_symbols.py, python_modules/dagster/dagster/components/lib/executable_component/python_script_component.py, python_modules/dagster/dagster/components/lib/executable_component/uv_run_component.py
Now that we skip code-blocks for section header checks we can remove from exclude list
Updated the YAML code snippets in component documentation to use proper reStructuredText syntax. Changed the format from triple backticks (```yaml) to the proper Sphinx directive (.. code-block:: yaml) in PythonScriptComponent and UvRunComponent classes. Also removed the corresponding entries from the test_known_valid_symbols.py exclusion list since they no longer need to be excluded.
Verified that the documentation renders correctly with the new format and confirmed that the tests pass without the exclusions in the test file.
=> Remove yaml-based erorrs

python_modules/dagster/dagster/components/core/component_tree.py, python_modules/dagster/dagster/components/core/context.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/test_definitions_autoload.py
Adds a new field to `ComponentTree` which tracks component-component dependencies, which we can use down the line to power partial reloading.
```python
assert component_tree.component_tree_dependencies.get_direct_load_dependents_of_component(
component_tree.defs_module_path,
ComponentPath(file_path=Path("single_file/some_file.py"), instance_key=None),
) == {ComponentPath(file_path=Path("single_file"), instance_key=None)}
assert component_tree.component_tree_dependencies.get_direct_load_dependents_of_component(
component_tree.defs_module_path,
ComponentPath(file_path=Path("single_file"), instance_key=None),
) == {ComponentPath(file_path=Path("."), instance_key=None)}
```
Unit test.
=> [3/d][components] Track component-component dependencies in ComponentTree

.claude/commands/diagnose_bk_failure.md, .claude/settings.json, .gitignore, CLAUDE.md
Add a new Claude command to diagnose Buildkite failures in PRs. This command automatically identifies failing Buildkite builds for the current PR, extracts build numbers, and provides links to failing builds for investigation.
See [loom](https://www.loom.com/share/698bb51e778c438d843aa92f4e12f636)
=> Add `/diagnose_bk_failure` Claude command

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/mcp_server.py, python_modules/libraries/dagster-dg-cli/setup.py, python_modules/libraries/dagster-dg-cli/tox.ini
adjust requires and imports accordingly 
[dg] A MCP server is available to expose `dg` CLI capabilities to MCP clients. See the `dg mcp` CLI group for details.
=> [dg] unhide mcp cli group

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/mcp/server.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/mcp_tests/test_mcp_serve.py
Closes ADOPT-1711.
Introduces a new tool endpoint for getting all integrations available in the marketplace. See example usage:
> What integrations can I install?
⏺ I'll help you find the available integrations you can install. Let me check what integrations are available in
the Dagster marketplace.
⎿  [
{
"id": "airlift",
… +1362 lines (ctrl+r to expand)
⏺ Here are the available integrations you can install with Dagster:
ETL & Data Movement
- Sling - YAML configuration for data loading/replication
- dlt - Standardized data pipeline creation
- Embedded ELT - Framework with dlt and sling
- Airbyte - Data sync orchestration
- Fivetran - Connector sync orchestration
- Census - Reverse ETL sync execution
- Hightouch - Data activation workflows
- Meltano - Singer specification ingestion …
=> [mcp] exposes integration marketplace in list_available_integrations tool

python_modules/dagster/dagster/_core/definitions/assets/graph/base_asset_graph.py, python_modules/dagster/dagster/_core/definitions/partitions/subset/partitions_subset.py, python_modules/dagster/dagster/_core/instance/__init__.py, python_modules/dagster/dagster/_core/storage/dagster_run.py, python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py
Store the `PartitionsSubset` on `DagsterRun` if the partitions def for the run is a timewindow partitions def. This allows us to get the partitions materialized by a ranged-run without needing the asset graph
enables https://github.com/dagster-io/internal/pull/17284
=> store partitions subset on the run

python_modules/dagster/dagster/_core/definitions/asset_health/asset_materialization_health.py, python_modules/dagster/dagster/_core/instance/instance.py
Updates the asset materialization health computation function to use the minimal asset materialization health class introduced in the previous pr 
existing test suite in https://github.com/dagster-io/internal/pull/16833 should cover this
=> [asset health] update health calculations to use minimal health state

python_modules/libraries/create-dagster/create_dagster/scaffold.py, python_modules/libraries/create-dagster/create_dagster/templates/PROJECT_NAME_PLACEHOLDER/.gitignore, python_modules/libraries/create-dagster/create_dagster/templates/PROJECT_NAME_PLACEHOLDER/README.md.jinja, python_modules/libraries/create-dagster/create_dagster_tests/test_scaffold_commands.py
When not in a workspace, automatically include the following files in the scaffolded project:
* README.md
* .gitignore
Manually testing:
Verify standalone project:
create-dagster project my-standalone-project --no-uv-sync --use-editable-dagster ~/src/dagster
ls -la my-standalone-project/
head -n 5 my-standalone-project/README.md
wc -l my-standalone-project/.gitignore
Verify workspace project:
create-dagster workspace my-workspace --no-uv-sync --use-editable-dagster ~/src/dagster
cd my-workspace
create-dagster project projects/workspace-project --no-uv-sync
ls -la projects/workspace-project/
Unit testing.
- [create-dagster] Adds .gitignore and README.md to standalone projects
=> Adds .gitignore and README.md to standalone `create-dagster` projects

CLAUDE.md
I used Claude to find PRs and automatically publish them and owen as a reviewer. Added some CLAUDE instructions help out.
Added documentation about PR stack operations to CLAUDE.md, including:
- Techniques for efficiently finding GitHub usernames using `gh search commits`
- Guidelines for using `gt` commands when working with PR stacks
- Explanation of why `gt log` is the preferred command for understanding stack structure
Use while assigned a bunch of PRs for owen to review
=> Add PR stack operations guide to CLAUDE.md

python_modules/dagster/dagster/_core/instance/assets/asset_domain.py, python_modules/dagster/dagster/_core/instance/dagster_instance_refactoring_analysis.md, python_modules/dagster/dagster/_core/instance/instance.py
This PR extracts the Assets domain from DagsterInstance as part of the ongoing refactoring effort. It moves all asset-related methods (25+) from DagsterInstance into a dedicated AssetDomain class, following the domain-based pattern established with the RunDomain extraction.
The implementation creates a new file:
- `assets/asset_domain.py` - Contains the AssetDomain class with all asset-related functionality (287 lines)
All asset methods in DagsterInstance now delegate to the AssetDomain via a cached property, maintaining perfect backward compatibility while significantly reducing the size of the DagsterInstance class.
- Verified all existing tests pass
- Confirmed zero breaking changes - all existing APIs work unchanged
- Validated all ruff and pyright checks pass with no errors
- Updated …
=> Extract asset domain from DagsterInstance

.claude/commands/ai_update_pr.md
This change improves the  command by making its git diff analysis more precise. The updated instructions now specify that the command should analyze only the current branch's changes using `git diff <previous_branch>..HEAD` rather than examining the entire stack history.
The change ensures that PR summaries focus on the specific changes introduced in each branch, avoiding confusion from unrelated changes in the broader stack context.
Ran it on this branch
=> Improve ai_update_pr command to focus on current branch changes only

.claude/commands/diagnose_bk_failure.md, python_modules/dagster/dagster/_core/instance/instance.py, python_modules/dagster/dagster/_core/instance/scheduling/scheduling_domain.py
This PR extracts scheduling-related functionality from the monolithic DagsterInstance class into a dedicated SchedulingDomain class. The refactoring moves all schedule, sensor, and backfill operations from the main instance class into `scheduling/scheduling_domain.py`.
**Key Changes:**
- Created new SchedulingDomain class that encapsulates all scheduling operations
- Moved schedule management methods: start_schedule(), stop_schedule(), reset_schedule()
- Moved sensor management methods: start_sensor(), stop_sensor(), reset_sensor()
- Moved instigator state operations: all_instigator_state(), get_instigator_state(), etc.
- Moved backfill operations: get_backfills(), add_backfill(), update_backfill()
- Moved scheduling utilities: scheduler_debug_info(), get_tick_retention_settings()
The …
=> Refactor DagsterInstance: Extract scheduling domain

python_modules/dagster/dagster/_core/instance/daemon/__init__.py, python_modules/dagster/dagster/_core/instance/daemon/daemon_domain.py, python_modules/dagster/dagster/_core/instance/dagster_instance_refactoring_analysis.md, python_modules/dagster/dagster/_core/instance/instance.py
This PR extracts daemon-related functionality from the monolithic DagsterInstance class into a dedicated DaemonDomain class. This refactoring moves daemon heartbeat management and status operations into `daemon/daemon_domain.py`.
**Key Changes:**
- Created new DaemonDomain class that encapsulates all daemon operations
- Moved daemon heartbeat methods: add_daemon_heartbeat(), get_daemon_heartbeats(), wipe_daemon_heartbeats()
- Moved daemon status methods: get_required_daemon_types(), get_daemon_statuses()
- Moved daemon configuration: daemon_skip_heartbeats_without_errors property
- Added comprehensive refactoring analysis document
The domain pattern uses a cached property _daemon_domain in DagsterInstance for lazy initialization. All existing public APIs remain unchanged, ensuring perfect …
=> Refactor DagsterInstance: Extract daemon operations into DaemonDomain

python_modules/dagster/dagster/_core/instance/CLAUDE.md, python_modules/dagster/dagster/_core/instance/instance.py, python_modules/dagster/dagster/_core/instance/settings_mixin.py
This PR extracts settings-related functionality from the `DagsterInstance` class into a separate `SettingsMixin` class to improve code organization and maintainability. The refactoring moves over 150 lines of settings methods and properties from the main `DagsterInstance` class into the mixin.
The main changes include:
- Created new `SettingsMixin` class containing all settings-related methods and properties
- Updated `DagsterInstance` to inherit from `SettingsMixin` and `DynamicPartitionsStore`
- Moved settings methods like `get_settings()`, `get_backfill_settings()`, run monitoring properties, and logging configuration methods to the mixin
- Added `_initialize_run_monitoring()` method to handle run monitoring setup
- Cleaned up imports by removing unused config imports from instance.py …
=> Extract settings methods from DagsterInstance into SettingsMixin

js_modules/dagster-ui/packages/ui-core/src/assets/LaunchAssetChoosePartitionsDialog.tsx
Summary:
'only 1 partitions failed and missing partitions' =>  'only 1 failed and missing partition'
View dialog locally
=> use adjective correctly in backfill preview dialog

js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogRateCard.tsx, js_modules/dagster-ui/packages/ui-core/src/insights/LineChartWithComparison.tsx
Shortens the sub label to Prev period instead of Previous period to make the chart cards stack better on mobile
=> Shorten previous period to prev period in insights charts

CLAUDE.md, python_modules/dagster/dagster/_core/instance/scheduling/__init__.py
Remove `__all__` declaration from `dagster/_core/instance/scheduling/__init__.py` subpackage. This follows the established coding convention that `__all__` should only be used in top-level package `__init__.py` files to define public APIs, not in subpackages.
The change also updates the development documentation in `CLAUDE.md` to explicitly document this convention for future contributors.
=> Remove __all__ from subpackage init files

python_modules/dagster/dagster/_core/instance/domains_mixin.py, python_modules/dagster/dagster/_core/instance/instance.py
This PR extracts domain properties from DagsterInstance into a reusable DomainsMixin class and converts private domain properties to public ones.
**Key Changes:**
- Created `DomainsMixin` class that defines all domain properties as public `@cached_property` methods
- Updated `DagsterInstance` to inherit from `DomainsMixin` instead of defining domain properties directly
- Converted all domain property access from private (`_run_domain`, `_asset_domain`, etc.) to public (`run_domain`, `asset_domain`, etc.) throughout the DagsterInstance class
- Used `cast("DagsterInstance", self)` pattern in mixin to maintain type safety
This refactoring consolidates the domain architecture pattern and makes domain properties consistently accessible as public APIs.
Existing test suite covers all domain …
=> Extract domain properties into DomainsMixin class

js_modules/dagster-ui/packages/ui-core/src/jobs/JobsPageContent.tsx
The new selection syntax bar on jobs and automations have different heights. Added some extra padding to make them match so they look nice when navigating between them and brings me peace and joy.
=> Make jobs selection bar match height of other pages

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py, .buildkite/dagster-buildkite/dagster_buildkite/utils.py
Because the test hits live snowflake, if multiple parallel BK runs are happening, the tables can get into an incosistent state and cause test failures. Also, we probably don't want to be racking up snowflake bills for random PRs that have nothing to do with dbt Fusion.
This breaks the snowflake tests into their own separate step that only runs if dbt files are modified
NOCHANGELOG
=> [dagster-dbt][buildkite] Move the live snowflake dbt Fusion test into a separate step

python_modules/dagster/dagster/components/list/list.py
dont blow up if the path is not in the dg project, just omit it 
ran in `hooli` where local refs to dbt files that were not in the dg project
=> [dg] guard relative pathing on check

python_modules/libraries/dagster-dbt/kitchen-sink/setup.py
Our dbt-live tests have been failing since we removed our dependency on dbt-core. But they just don't run that frequently so we didn't catch this until I ran a few NO_SKIP builds (frequency is something I'm choosing to ignore for now - defering to the folks working more closely on this stuff on how often they want them to run).
Anyway, I think this should fix them:
https://buildkite.com/organizations/dagster/analytics/suites/dagster-steps/tests/6881a1be-c8be-89aa-9d9d-d9e3272e2055
```
ERROR dagster_dbt_cloud_kitchen_sink_tests/test_dagster_assets.py - dagster_shared.check.functions.CheckError: Expected non-None value: project must be passed if dbt-core is not installed
```
=> Install dbt-core in kitchen-sink tests

.claude/agents/buildkite-error-detective.md, .claude/commands/diagnose_bk_failure.md, CLAUDE.md
This PR introduces a specialized `buildkite-error-detective` agent that dramatically improves CI/CD failure diagnosis efficiency. The agent provides fast, parallel analysis of failing Buildkite builds with pattern-first diagnosis and specific actionable fixes.
The agent leverages the Buildkite MCP server to perform batch operations, analyzing multiple builds simultaneously rather than sequentially. It categorizes failures by type (test failures, infrastructure issues, dependency problems) and provides file paths and line numbers for immediate resolution.
```yaml
tools: mcp__buildkite__get_jobs, mcp__buildkite__get_job_logs, mcp__buildkite__list_builds
target_response_time: 30-45 seconds
efficiency_improvements: 4x faster than manual investigation
```
The existing `diagnose_bk_failure` …
=> Add buildkite-error-detective agent for fast CI/CD failure diagnosis

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py, python_modules/dagster/dagster/_core/instance/assets/asset_domain.py, python_modules/dagster/dagster/_core/instance/instance.py, python_modules/dagster/dagster/_core/instance/mixins/asset_mixin.py, python_modules/dagster/dagster_tests/execution_tests/versioning_tests/test_data_versions.py, python_modules/dagster/dagster_tests/storage_tests/utils/partition_status_cache.py
Extracted all asset-related methods from the `DagsterInstance` class into a new `AssetMixin` class to improve code organization and maintainability. This follows the existing pattern used by other mixins like `SettingsMixin`, `RunsMixin`, and `DomainsMixin`.
The refactoring moves approximately 80 asset-related methods from `instance.py` to the new `asset_mixin.py` file, including:
- Asset key management (`get_asset_keys`, `has_asset_key`, `all_asset_keys`)  
- Asset materialization and observation fetching
- Asset status cache operations
- Asset health state queries
- Asset partition status methods
The `DagsterInstance` class now inherits from `AssetMixin` to maintain full backward compatibility.
Existing test suite covers all moved methods.
**Refactoring**: Extracted asset-related …
=> Extract asset-related methods from DagsterInstance into AssetMixin

.buildkite/dagster-buildkite/dagster_buildkite/pipelines/dagster_oss_nightly_pipeline.py, .buildkite/dagster-buildkite/dagster_buildkite/steps/integration.py, .buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py, .buildkite/dagster-buildkite/dagster_buildkite/steps/tox.py
I want to start threading --split through our PackageSpec so I can
parallelize pytest tests a bit more. And I sometimes want different
splits for different tox factors.
So this introduces a new data class that I can later extend to include
that config. Expectation is that this particular change is a no-op for
the build.
=> Introduce ToxFactor

CLAUDE.md, python_modules/dagster/dagster/_core/instance/instance.py
This change adds the `get_records_for_run` method directly to the `DagsterInstance` class to ensure proper Datadog tracing span attribution. The method was previously only available in `EventMethods`, but Datadog tracing spans specifically expect to find this method on the `DagsterInstance` class itself.
The method is marked as `@traced`, and delegates to the existing implementation in `EventMethods.get_records_for_run`. This duplication is necessary for maintaining proper observability tooling integration while preserving the clean architecture introduced in the recent instance refactoring work.
BK
=> Add get_records_for_run method to DagsterInstance for proper Datadog tracing

python_modules/dagster/dagster/__init__.py, python_modules/dagster/dagster/_core/definitions/metadata/source_code.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_defs_source_metadata.py
Users should be able to use git code references even if their base URL does not include the strings "github" or "gitlab". This change allows users to optionally specify their git platform using a new `platform` parameter in `link_code_references_to_git`.
This is a more robust solution to https://github.com/dagster-io/dagster/issues/23135.
Allow explicit git `platform` selection in `link_code_references_to_git`
=> feat: enable explicit source control platform

python_modules/dagster/dagster/_core/definitions/partitions/context.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_partitions_subset.py
This fixes a few issues with this decorator.
The main one was that it erased all type information of the decorated function. So basically all functions decorated with it became unannotated, which was bad.
The secondary one was that it was possible to annotate a function on a class that did not have a `_partition_loading_context` property on it. Now you will get type errors if you try to do that.
It's a bit cursed but hey it works.
note: added two "new" `# type: ignore`s in the test code, but those actually were removed with the change that added this decorator (because the decorator made the type of the things Any). so this is just restoring the pre-decorator behavior there.
NOCHANGELOG
=> Update type of use_partition_load_context

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetsGraphHeader.oss.tsx
The button was erroneously removed in https://github.com/dagster-io/dagster/pull/31018/. This adds it back. Also hide the breadcrumb in full screen mode to create more space:
=> [catalog] Fix fullscreen button on catalog lineage

python_modules/libraries/dagster-databricks/dagster_databricks/pipes.py
PipesDatabricksClient and PipesDatabricksServerless share the same code for poll and metadata methods - consolidate duplicated methods in one base class
Unit test (manual run)
=> [dagster-databricks] Consolidate poll and metadata methods in BasePipesDatabricksClient

python_modules/dagster/dagster/_core/definitions/partitions/context.py, python_modules/dagster/dagster/_core/definitions/partitions/subset/key_ranges.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_partitions_subset.py
Ensures that you don't get caught by surprise the first time you use this subset with a dynamic partitions definition. Could imagine using this pattern for AllPartitionsSubset as well.
New test case that was failing before
=> require a full partition loading context before loading from a KeyRangesPartitionsSubset

.buildkite/dagster-buildkite/dagster_buildkite/steps/dagster.py, .buildkite/dagster-buildkite/dagster_buildkite/steps/docs.py, .buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
These tests don't fail non-deterministically except getting a node interrupted or something, which in practice don't see too much AFAIK.
BK will fail faster, which in this case is good as it reduces dev feedback loops
Injected ruff error. Pushed [build](https://buildkite.com/dagster/dagster-dagster/builds/130036/steps/canvas?sid=0198656b-4df7-4444-877a-0746e077dd7f). Saw no retries
=> Disable retries for deterministic, reproducable tests

python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py, python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/since_operator.py, python_modules/dagster/dagster_tests/declarative_automation_tests/automation_condition_tests/fundamentals/test_automation_condition.py
Many AutomationConditions don't have labels, since they just define the name in the class. But it's still natural to target those conditions using replace(), for use cases like https://docs.dagster.io/guides/automate/declarative-automation/customizing-automation-conditions/customizing-eager-condition
This allows you to target conditions by name as well as by label.
Unit test
Fixed issue causing `AutomationCondition.replace` to not update built-in sub-conditions that did not have an explicit label.
=> AutomationCondition.replace should target name as well as label

.buildkite/dagster-buildkite/dagster_buildkite/steps/dagster.py
Add `--system` flag to all `uv pip install` commands in buildkite configuration. This flag is required when running in Docker containers to ensure packages are installed in the system Python environment rather than in a virtual environment.
BK
=> Avoid hardcoded use of raw pip

python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_check_yaml_multi_document.py, python_modules/libraries/dagster-dg-core/dagster_dg_core/check.py
- **Adds failing test suite for bug in inline YAML validation failure**
- **Fixes \`dg check yaml\` to check all inline documents**
Previously, typos or schema validation errors were not being caught when multiple documents are provided in a single `defs.yaml` file (delineated with `---`).
This PR introduces a test to catch that scenario, and also implements a fix.
- [dagster-dg-cli] Fixed bug where not all inline definitions were validated by `dg check yaml`
=> [dagster-dg-cli] Fixes issue where not all inline documents are validated with `dg check yaml`

pyright/master/requirements-pinned.txt, python_modules/automation/automation/eval/cli.py, python_modules/automation/automation_tests/test_eval_cli.py, python_modules/automation/setup.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_scaffold_branch_command.py, python_modules/libraries/dagster-dg-cli/tox.ini
Adds a cli utility for running evaluations over a directory of "session" json files. The goal of this tool is to provide a lightweight way to iterate on: 
* An ai flow, where you can accumulate sessions over time and see how evaluation results change. The expected workflow here is running in the same directory as it accumulates new session files. 
* The evaluation definition it self. Only new or modified metric definitions in `eval.yaml` will result in new evaluations performed.
`deepeval` was chosen here as it was the best tool i found from my time searching for doing LLM-as-a-judge evals via `GEval`.
added test
run it on `dg scaffold branch --record` output 
sample:
`eval.yaml`: 
```
metrics:
- name: "Requirement Fulfillment"
criteria: "Assess requirement fulfillment: data …
```
=> [dagster-eval] cli util

python_modules/dagster/setup.py
The python:slim packages seem to have upgraded to a new version of debian in the last 24 hours that doesn't have all the same timezone strings that the previous version did, which means that declaring timezones like US/Central can start failing without having this dependency installed. Add it as an explicit dependency to mitigate that (before, we were only adding it on Wdinows).
BK
Added `tzdata` as a dependency to `dagster`, to ensure that declaring timezones like `US/Central` work in all environments.
=> Always depend on tzdata, not just on Windows

examples/docs_projects/project_ask_ai_dagster/pyproject.toml, examples/docs_projects/project_atproto_dashboard/pyproject.toml, examples/docs_projects/project_dagster_modal_pipes/pyproject.toml, examples/docs_projects/project_llm_fine_tune/pyproject.toml, examples/docs_projects/project_prompt_eng/pyproject.toml, python_modules/dagster/dagster_tests/cli_tests/workspace_tests/toml_tests/test_toml_loading.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/utils.py, python_modules/libraries/dagster-dg-core/dagster_dg_core/config.py, python_modules/libraries/dagster-dg-core/dagster_dg_core/context.py, python_modules/libraries/dagster-dg-core/dagster_dg_core/utils/warnings.py, python_modules/libraries/dagster-dg-core/dagster_dg_core_tests/test_context.py
Remove `autoload_defs` setting from dg project settings-- this was actually deprecated for removal in 1.11.0 but that never happened.
=> [dg] Remove autoload_defs settings from dg project settings (ADOPT-1785)

.claude/commands/ai_update_pr.md, python_modules/automation/automation/dagster_dev/CLAUDE.md, python_modules/automation/automation/dagster_dev/cli.py, python_modules/automation/automation/dagster_dev/commands/__init__.py, python_modules/automation/automation/dagster_dev/commands/greet.py, python_modules/automation/setup.py
Introduces a new `dagster-dev` CLI tool designed for internal developer workflows and optimized for agent invocations. This replaces scattered scripts with a single, introspectable namespace that consolidates development utilities.
In AI-driven world it is very easy and natural to build one-off tools like this for human or agent use, and we should encourage it. The barrier to entry should be low. This makes it so you can vibecode a new script/command in a low-stakes way.
The CLI features automatic command discovery, making it easy for developers to add new utilities without modifying central configuration files.
Key features:
- **Auto-discovery**: Commands are automatically loaded from the `commands/` directory
- **Extensible**: New commands can be added by simply creating Python files …
=> Add dagster-dev CLI for internal developer utilities

python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/databricks_configs.py, python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/configs/databricks.yml, python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/configs/resources/jobs.yml, python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/test_configs.py
Add DatabricksConfigs class, representing the configs required for the DatabricksAssetBundleComponent. Logic inspired from the [demo in hooli](https://github.com/dagster-io/hooli-data-eng-pipelines/tree/add-hooli-ml).
The `databricks.yml` file is the main config file for the asset bundle - it references resources (includes) that define tasks and params. `databricks.yml` and resource files are parsed by `DatabricksConfigs` to extract `tasks` and `job_level_parameters`, which will be used by the component.
Tasks are not handled in this first iteration, causing the extraction process to raise an expected exception. Tasks will be implemented in subsequent PRs.
BK
=> [dagster-databricks] Implement initial DatabricksConfigs class

js_modules/dagster-ui/packages/ui-core/src/asset-graph/SidebarAssetInfo.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/MultipartitioningSupport.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/PartitionHealthSummary.tsx
Improved the navigation flow in the Dagster UI especially in the Asset side panel by making **Materialized/Partition bar** clickable/selectable with options single click and selection range requested by **Daniel**. As a result, this links directly to the specific partitions view depending on user mouse clicks/range. We also introduced additional feature like `isTimeBasedPartition` @ js_modules/dagster-ui/packages/ui-core/src/assets/MultipartitioningSupport.tsx which identity if current task is timebase with dimension type, opening option **range** for only timebase. As a result, the layout was also cleaned up by removing unnecessary steps, resulting in a clearer and more user-friendly interface.
I tested the changes locally by running both the backend and frontend. For the backend, I …
=> feat: Add ability to click on partitions in the Asset side panel

Makefile
Add a new `unsafe_ruff` make target that runs ruff with the `--unsafe-fixes` flag enabled. This allows developers to apply potentially unsafe but helpful ruff fixes when needed.
The new target runs:
- `ruff check --fix --unsafe-fixes .` - Apply all available fixes including unsafe ones
- `ruff format .` - Format code
Verified the make target works correctly and applies unsafe fixes as expected.
=> Add unsafe_ruff make target for applying ruff unsafe fixes

.buildkite/buildkite-shared/buildkite_shared/step_builders/command_step_builder.py, python_modules/dagster/dagster_tests/core_tests/asset_graph_view_tests/test_serializable_entity_subset.py
This change modifies the Buildkite command step builder to disable automatic retries on feature branches while maintaining them on master and release branches. The retry_automatically parameter now defaults to None and uses branch detection logic to determine the appropriate retry behavior.
The reason why is that retries delay the time to failure on feature branches which is not want you want. You want to accelerate the time-to-failure, so that the developer can fix it quickly.
Feature branches will not retry automatically, but master/release branches will continue to retry as before.
Existing test suite covers the command step builder functionality.  
Injected failure [here](https://buildkite.com/dagster/dagster-dagster/builds/131630/steps/canvas) and saw no retry.
Updated Buildkite CI …
=> Disable automatic retries on feature branches

python_modules/dagster/dagster/components/testing/__init__.py, python_modules/dagster/dagster_tests/general_tests/test_import.py, python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/beta/test_component.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/test_dbt_project_component.py, python_modules/libraries/dagster-dlt/dagster_dlt_tests/test_dlt_load_collection_component.py, python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_component.py, python_modules/libraries/dagster-sling/dagster_sling_tests/test_sling_replication_collection_component.py
This is unintentionally causing `pytest` to be imported by the core `dagster` module - this ensures `test_cases` is not imported when importing `dagster`.
Update import tests to catch erroneous `pytest` imports.
=> Prevent test_cases file from being imported by dagster module

python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/conftest.py, python_modules/libraries/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_component_defs.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/import_perf_tests/simple_import.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/plus_tests/test_create_ci_api_token.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/plus_tests/test_plus_deploy_command.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/plus_tests/test_plus_env_command.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/plus_tests/test_plus_login_command.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/plus_tests/utils.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_configure_editor_commands.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_dev_command.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_docs_commands.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_integrity.py
Remove unnecessary `noqa: I001` directives in various test files. In some cases this results in inconsequential import reordering.
=> Remove unnecessary noqa: I001 directives

python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_docs_commands.py
This has been failing for some time now. Since ~July 22.
It's muted in Buildkite and backlogged linear but hasn't been fixed yet.
It does look like it succeeds locally so my suspicion is something Buildkite related. In recent days, I've noticed it falling through our soft mute in Buildkite more frequently (presumably us getting rate limited? Or some weird interaction with its auto-retry https://github.com/dagster-io/dagster/pull/31851)? I'm going to hard skip and see if I can figure out why it's actually failing.
=> Skip test_build_docs_success_in_published_package

python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_all_snapshot_ids.ambr, python_modules/dagster/dagster/_core/snap/node.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_asset_decorator.py
I am not sure why we didn't sort these fields like we did others, I guess its more common to have stable output / input definition order.
updated test
=> [RFC] sort in/out snaps

js_modules/dagster-ui/packages/eslint-config/CHANGES.md, js_modules/dagster-ui/packages/eslint-config/package.json
The internal app is a couple versions behind on our eslint-config. Update the package to get recent changes available to install there.
None, but we've been using this configuration in OSS.
=> [eslint-config] Updates for v1.0.20

python_modules/dagster/setup.py
resolves: https://github.com/dagster-io/dagster/issues/31798
The `dagster` library now supports `protobuf==6.x`
=> protobuf version bump

js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogHorizontalTopAssetsChart.module.css, js_modules/dagster-ui/packages/ui-core/src/assets/insights/AssetCatalogHorizontalTopAssetsChart.tsx, js_modules/dagster-ui/packages/ui-core/src/insights/ActivityChart.tsx, js_modules/dagster-ui/packages/ui-core/src/insights/LineChartWithComparison.tsx
Corresponds to https://github.com/dagster-io/internal/pull/17713.
Add previous window data to line chart dialog, including “change” information, if applicable.
The dialog contents are now virtualized and sortable as well.
Proxy as elementl, verify click behavior, sorting, virtualization.
=> [ui] Insights v2 update line chart dialog

python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/component.py, python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/configs.py, python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/resource.py, python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/conftest.py, python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/test_resource.py
Support existing cluster ID when creating SubmitTask objects in submit_and_poll. Users can pass an existing cluster ID in their custom config file to avoid creating a new cluster when submitting their task via Dagster. 
BK
=> [dagster-databricks] Support existing cluster ID in DatabricksWorkspace.submit_and_poll

python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/component.py, python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/configs.py, python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/resource.py, python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/configs/serverless_custom.yml, python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/test_resource.py
Support whether serverless compute should be used creating SubmitTask objects in submit_and_poll. If yes, cluster config must not be passed to the SubmitTask object.
BK
=> [dagster-databricks] Support serverless in DatabricksWorkspace.submit_and_poll

python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py
I suspect we're deadlocking from time to time. When it happens, it hanges the entire buildkite build and there's no way to recover.
This has been skipped in Buildkite for a while with a backlogged task to dig deeper - I'm just moving the virtual skip to exist in code instead.
=> Hard skip test_threaded_submit_backfill

python_modules/dagster/dagster/components/component/state_backed_component.py, python_modules/dagster/dagster_tests/components_tests/state_backed_component_tests/test_state_backed_component.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/utils.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/utils/ui.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/defs_state_tests/sample_state_backed_component.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/defs_state_tests/test_refresh_state_command.py
Adds a `dg utils refresh-state` CLI that finds all StateBackedComponents in the project and attempts to refresh their state. Does this in nice async-aware fashion so that io-bound operations can execute in parallel
I decided to get a little fancy with the loading state:
[Screen Recording 2025-08-14 at 4.42.24 PM.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/cTPQ7oSxo9qxXgkzpnaK/fc75fd2e-6f34-43b1-aa7a-9e5cfb48d180.mov" />](https://app.graphite.dev/media/video/cTPQ7oSxo9qxXgkzpnaK/fc75fd2e-6f34-43b1-aa7a-9e5cfb48d180.mov)
NOCHANGELOG
=> [4/n] state-backed-component CLI

js_modules/dagster-ui/packages/ui-core/client.json, js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationDefsStateComparison.tsx, js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationDefsStateComparisonSection.tsx, js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationDefsStateQuery.tsx, js_modules/dagster-ui/packages/ui-core/src/code-location/CodeLocationOverviewRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/code-location/types/CodeLocationDefsStateQuery.types.ts, js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/schema/external.py, python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
We want to be able to visualize the state versions that are being used in a given code location alongside the latest available ones
This UI only appears in cases where you're using state-backed components, so this should not impact existing users at all.
Normal:
Out of date:
There are many other places where we might want to thread this information into in the future, but for now this serves as more of a useful diagnostic thing as we start experimenting with this capability.
NOCHANGELOG
=> [5/n] Display version info in the ui

python_modules/dagster/dagster/components/component/state_backed_component.py, python_modules/dagster/dagster/components/core/component_tree.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/test_definitions_autoload.py, python_modules/dagster/dagster_tests/components_tests/state_backed_component_tests/test_state_backed_component.py, python_modules/dagster/dagster_tests/components_tests/unit_tests/test_component_decl.py, python_modules/dagster/dagster_tests/general_tests/grpc_tests/state_versions/test_state_versions_grpc.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/utils.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/defs_state_tests/sample_state_backed_component.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/defs_state_tests/test_refresh_state_command.py, python_modules/libraries/dagster-shared/dagster_shared/serdes/objects/defs_state_info.py
We want this to be based on something more stable than the path to the component. This uses the class name, which feels like a fairly-straightforward option.
This PR adds in error-checking functionality, providing a useful error if/when multiple components are detected with the same defs state key.
Also fixes an issue w/ the ComponentTreeDependencyTracker where a single instance was shared across all ComponentTrees (and renames it to be more general)
NOCHANGELOG
=> [7/n] Update get_defs_state_key functionality

python_modules/dagster/dagster/_core/execution/context/invocation.py, python_modules/libraries/dagster-dbt/dagster_dbt/components/dbt_project/component.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/test_dbt_project_component.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/yaml_template/test_data/dbt_project/expected_example, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/yaml_template/test_data/dbt_project/expected_schema
This updates the DbtProjectCompnent to allow users to pass in custom arguments to the cli invocation.
We could definitely get away with the signature of the `cli_args` field being just `list[str]`, but the way the `--vars` parameter works means that it'd be pretty tough to actually format things in a yaml document (because that param expects json-formatted data). So I added the option to just specify things in dictionary format.
In theory, this is technically a bit overly-specified, in that it's possible that a user's component subclass does not use this configuration at all (i.e. maybe it invokes two completely separate commands or something). However, in the vast majority of cases, it seems likely that people will only invoke one dbt command for the actual execution of their assets …
=> [dagster-dbt] Update DbtProjectComponent with configurable CLI args

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/scaffold/branch/ai.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/scaffold/branch/command.py
`dg scaffold branch "Scaffold a new component that runs a Python script over Dagster pipes representing a single asset." --verbose` 
and continue through to execution instead of canceling
=> [dg scaffold branch] use verbose flag in scaffolding phase

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/scaffold/defs.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_custom_help_format.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_scaffold_commands.py
Before:
After:
`dg scaffold defs --help` now shows descriptions for subcommands.
=> [dg] Add component descriptions to `dg scaffold defs --help` output (ADOPT-1800)

python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/component.py, python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/configs.py
~~Introduce a container class for the translation/get_asset_spec data.~~ Subclass `DatabricksBaseTask` with `DatabricksUnknownTask`. This will ease the process of creating asset keys for dependencies through get_asset_spec in a subsequent PR.
BK with existing tests
=> [dagster-databricks] Implement DatabricksUnknownTask 

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/scaffold/branch/ai.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/scaffold/branch/claude/sdk_client.py
arguments for: 
* user is seeing messages stream through and can ctrl-c if its gone off the rails
* forcing it to stop in the middle of its work does not leave things in a useful state 
I can be convinced theres some limit we should set
`dg scaffold branch "Scaffold a new component that runs a Python script over Dagster pipes representing a single asset." --verbose` actually compleetes everything that is planned
=> [dg scaffold branch] RFC remove max_turns limit

python_modules/dagster/dagster/_core/storage/defs_state/blob_storage_state_storage.py
There's no need to make this directory before we call `upload_state_from_path` (as this also makes sure that the directory is made). So for users not interacting with this set of features, we shouldn't make a directory for them
NOCHANGELOG
=> [state-backed-components] Don't mkdir eagerly

python_modules/dagster/dagster/_core/definitions/asset_health/asset_check_health.py
Summary:
The old logic required a full asset graph fetch in this case, now it does not.
Test Plan:
BK, dry run on a slow asset asset health load
=> Short circuit in asset check health state when the asset key is not in the graph or has no checks

.buildkite/buildkite-shared/buildkite_shared/step_builders/command_step_builder.py, .buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
do not blank out the existing default retry configuration if `with_retry` is called with `None` which happens in tox step building
run
`
BUILDKITE_MESSAGE="foo" BUILDKITE_COMMIT=50419a68e244e199575f20adf54c3abc27d8185c BUILDKITE_BRANCH=master dagster-buildkite
`
and see that `dagster-dbt` has expected automatic retry config
=> [buildkite] fix CommandStepBuilder.with_retry

python_modules/dagster/dagster/components/core/component_tree.py, python_modules/dagster/dagster_tests/components_tests/component_tree_tests/test_component_tree_reloading.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/test_definitions_autoload.py
**NOTE:** this implementation is pretty jank, and mostly a proof of concept / addition of a test case prior to the next PR in the stack, which formalizes this caching concept a bit more. Arguably, I should just merge these prs together, but I do a bunch of other refactoring in the upstack PR as well, so I didn't want the core logical bit to be tied into that. 
this reworks https://github.com/dagster-io/dagster/pull/31482 to have a more explicit concept of a "cache key" that is wired through any cached methods / properties. Each path has an associated cache key, allowing us to update this cache key out of band when certain events happen.
In this pr, the cache key will only ever get invalidated manually, but upstack, we'll add functionality to invalidate the cache key when the state of a …
=> Allow for partial ComponentTreeReloading

python_modules/dagster/dagster/components/core/component_tree.py, python_modules/dagster/dagster/components/core/component_tree_state.py, python_modules/dagster/dagster/components/core/context.py, python_modules/dagster/dagster/components/core/decl.py, python_modules/dagster/dagster/components/core/defs_module.py, python_modules/dagster/dagster_tests/components_tests/component_tree_tests/test_component_tree_reloading.py, python_modules/dagster/dagster_tests/components_tests/integration_tests/test_definitions_autoload.py, python_modules/dagster/dagster_tests/components_tests/unit_tests/test_component_decl.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/components/code_locations/dependency_on_dbt_project_location/defs/depends_on_dbt/definitions.py
This is a refactor and (ideally) simplification of how we manage component tree state. There are a few things going on here:
1. moved ComponentTreeStateTracker into its own file
2. reworked how we manage ComponentPaths. They are now always fully resolved (i.e. they contain absolute paths), meaning they can be used as dictionary keys for caches and other such objects. This removes the need for the _get_canonical_path type functions, as ComponentPaths *are* the canonical paths
3. reworked the caching mechanism from the previous pr to be much more explicit. we now have an explicit cache that routes from a given ComponentPath to a state object with a collection of properties. I use this pattern of having a single dictionary instead of one dictionary per cacheable object type for simplicity -- …
=> Refactor ComponentTree state

python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/core/workspace.py
Summary:
This is no longer needed, the image resolution happens elsewhere now.
BK
=> Remove PexMetadata.resolve_image

js_modules/dagster-ui/packages/ui-components/src/components/SplitPanelContainer.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx
Related: https://dagsterlabs.slack.com/archives/C03CCE471E0/p1755645402070769
Right now, when you close the sidebar on the asset lineage page the component hierarchy changes so the SVGViewport is unmounted and remounted. We use a context to preserve some viewport state within the SVGViewport between layout changes, but this is higher in the tree.
We support passing a null `second` view to the SplitPaneContainer and animates the second panel in when the value changes. This PR just allows us to do the same for the `first` pane so we can hide the sidebar panel without remounting the viewport.
=> [ui] Avoid unmount + remount of viewport when hiding explorer sidebar

js_modules/dagster-ui/packages/ui-core/src/assets/SimpleStakeholderAssetStatus.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/useLatestEvents.tsx, js_modules/dagster-ui/packages/ui-core/src/hooks/usePredicateChangeSignal.tsx
https://linear.app/dagster-labs/issue/FE-926/mismatched-latest-materialization-time-in-the-ui
We have a hook called `usePredicateChangeSignal` that is only used in this location. It's meant to let you filter inputs and trigger a simple number to flip from `0 | 1`, which is then used as a dep in downstream hooks. The problem is that `usePredicateChangeSignal` only updates the "previous inputs" it passes to the predicate IF the predicate returns true, and the predicate we implemented (below) does not return true unless the previous inputs are present, so it never returned true.
```
const refreshHint = usePredicateChangeSignal(
(prevHints, [lastMaterializationTimestamp, assetNodeLoadTimestamp]) => {
const [prevLastMaterializationTimestamp, prevAssetNodeLoadTimestamp] =
prevHints || …
```
=> [ui] Fix asset overview live data not triggering events refresh

python_modules/dagster/dagster/_core/definitions/partitions/definition/time_window.py, python_modules/dagster/dagster/_core/definitions/partitions/definition/time_window_subclasses.py, python_modules/dagster/dagster/_core/definitions/partitions/partitioned_config/time_window.py, python_modules/dagster/dagster/_core/definitions/partitions/partitioned_schedule.py, python_modules/dagster/dagster/_core/definitions/partitions/snap/snap.py, python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_asset_partition_mappings.py, python_modules/dagster/dagster_tests/core_tests/host_representation_tests/test_external_data.py, python_modules/dagster/dagster_tests/core_tests/snap_tests/__snapshots__/test_active_data.ambr, python_modules/dagster/dagster_tests/definitions_tests/test_partitioned_schedule.py, python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py
This PR handles exclusions by omitting them from the set of defined partition keys.
BK
- Adds a param `exclusions` to time window partition definitions to support custom calendars
=> add exclusion support for time window partitions

js_modules/dagster-ui/packages/ui-core/src/insights/ActivityChart.tsx, js_modules/dagster-ui/packages/ui-core/src/insights/LineChartWithComparison.tsx
Fix time range math for opening the dialog from line charts and activity charts. I think this was probably some bad vibing on my part.
The "before" timestamp should be greater than the "after" timestamp. Right now, they're backward.
I think the backend may be swapping them automatically if they're out of order, because the data retrieved seems unchanged. Still, we should try to get this correct in JS.
View Insights, click on line chart and activity charts. The query vars now look correct.
=> [ui] Insights v2: Fix time range

python_modules/dagster/dagster/_utils/cronstring.py, python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py
Summary:
We were handling things like */15 and */30 correctly, but not "* * * * *". Easy fix.
New test case
=> Speed up counting minute-ly partition sets

js_modules/dagster-ui/packages/ui-core/src/runs/LogsToolbar.tsx
On the logs toolbar step selector, add a "title" to allow displaying the entire string on hover. This is useful in cases where step names are super long.
I wasn't able to get `data-tooltip` to work here, possibly because of the DOM nesting involved in the select menu. But since it would require hovering anyway, it works to just show the native title.
Hover on items in the step selector dropdown in the compute log UI, verify that the title appears with the full string.
=> [ui] Run compute log: Add title to step selector items

js_modules/dagster-ui/packages/ui-core/src/selection/SelectionInput.tsx
I fixed https://github.com/dagster-io/dagster/pull/31946 but broke the other case :).
Pasted strings without multiple strings and with multiple strings
[ui]Fix a bug with pasting strings into the selection input
=> Fix pasting strings without multiple spaces

python_modules/libraries/dagster-dg-cli/MANIFEST.in, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/__init__.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/api/API_CONVENTIONS.md, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/api/API_IMPLEMENTATION_PLAN.md, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/api/__init__.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/api/cli_group.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/api/deployment.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/api/formatters.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/api/shared.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/plus/GRAPHQL_SCHEMA.md, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/plus/login.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/plus/schema.graphql, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/dagster_plus_api/README.md, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/dagster_plus_api/__init__.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/dagster_plus_api/api/__init__.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/dagster_plus_api/api/deployments.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/dagster_plus_api/graphql_adapter/__init__.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/dagster_plus_api/graphql_adapter/deployment.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/dagster_plus_api/schemas/CLAUDE.md, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/dagster_plus_api/schemas/__init__.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/dagster_plus_api/schemas/deployment.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/api_classes.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/test_list_commands.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/dagster_plus_api_tests/api_classes.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/dagster_plus_api_tests/rest_compliance_infrastructure.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/dagster_plus_api_tests/test_rest_compliance.py, python_modules/libraries/dagster-dg-cli/setup.cfg
I want to support a new, structured frontend for dg plus. The immediate use case is fetching asset-centric metadata out of plus per customer requests for use in their own metadata store.
GraphQL is a terrible interface for cross-organization public API consumption. It is too complicated and generally requires a client library to make it useful. GraphQL was designed for the develop of rich client-side applications, not simple data transfer.
We want simple CLI access to Dagster, similar in spirit to Github's `gh` cli, which is excellent.
This package implements a three-layer architecture that provides a clean separation between the CLI interface and the Dagster Plus backend. The design follows a CLI → REST-esque Python API → GraphQL pattern, where each layer has distinct responsibilities …
=> New `dg api` structure and first concrete implementation.

python_modules/dagster/dagster/_core/definitions/asset_health/asset_freshness_health.py
rather than fetch the asset record to get the latest materialization timestamp, we can get it from streamline now
Internal PR (for testing) <https://github.com/dagster-io/internal/pull/17085>
=> use asset materialization state for latest materialization timestamp if exists

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/AssetSidebarListView.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/AssetSidebarNode.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/SearchInput.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/Sidebar.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/SidebarHeader.module.css, js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/SidebarHeader.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/TreeViewPanel.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/treeBuilders.ts, js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/useSidebarSelectionState.ts
Currently when you click on an asset there is a chance you get scrolled to another instance of the same asset elsewhere in the tree. This is because the current onClick handlers on record the key of the asset being clicked and not the exact path. To fix this record the exact path of the node that is clicked in the sidebar.
https://github.com/user-attachments/assets/d1207215-aac0-4f4c-bd82-a5bd9be75655
=> [asset graph] Minor sidebar refactor + Fix asset graph sidebar tree view auto-scrolling

python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
Before this would return every asset when an empty list was passed in. Now it returns no assets.
New test cases
Fixed an issue where passing in an empty list in the `assetKeys` argument of the `assetsOrError` field in the GraphQL API would return every asset instead of an empty list of assets.
=> Return an empty list in assetsOrError if an empty list is passed in

python_modules/libraries/dagster-snowflake-polars/setup.py
example error in https://github.com/dagster-io/dagster/issues/32041, many tests are failing so pin until a fix is made in this or dependent library 
bk passes with new pin
=> [dagster-snowflake-polars] pin polars<1.33.0

python_modules/libraries/dagster-dbt/dagster_dbt/__init__.py, python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/__init__.py
To fix API docs [here](https://github.com/dagster-io/dagster/pull/32015/files#r2310631573)
Also, the integration has been around for quite some time now, exposing dbt Cloud v2 even though dbt Cloud v1 is still in the integration seems fine.
=> [dagster-dbt] Expose dbt Cloud v2 APIs in dagster-dbt top level

js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetHealthDataProvider.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-data/__tests__/AssetHealthDataProvider.test.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetHealthSummary.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/AssetHealthSummary.test.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/useAllAssetsNodes.test.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/useAllAssets.tsx, js_modules/dagster-ui/packages/ui-core/src/live-data-provider/LiveDataProvider.tsx
Fetching health for assets without definitions causes expensive stuff to happen on the backend so lets avoid sending health queries for them.
A previous version of this did the filtering in the query function but this pr moves it to the hook itself to avoid batching/chunking the keys that dont have definitions.
loaded a bunch of orgs included ones that previously caused issues.
=> [Asset health] Only fetch health for assets that have definitions

python_modules/libraries/dagster-dbt/dagster_dbt/core/resource.py, python_modules/libraries/dagster-dbt/dagster_dbt/utils.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/core/test_fusion_support.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/fusion_compatible/jaffle_shop/models/schema.yml, python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/fusion_compatible/jaffle_shop/models/staging/schema.yml, python_modules/libraries/dagster-dbt/dagster_dbt_tests/install_dbt_fusion.sh, python_modules/libraries/dagster-dbt/setup.py, python_modules/libraries/dagster-dbt/tox.ini
Adds the `dbt-core` dependency back in to avoid erroring in cases where users are using the dbt Cloud integration (which requires dbt-core in order to parse dbt selection strings against a manifest).
[dagster-dbt] Added the `dbt-core` dependency back to `dagster-dbt` as it is still required for the dbt Cloud integration. If both `dbt-core` and `dbt Fusion` are installed, `dagster-dbt` will still prefer using `dbt Fusion` by default.
=> [dagster-dbt] Add `dbt-core` dependency back in

python_modules/dagster-graphql/dagster_graphql/schema/external.py, python_modules/dagster/dagster/_cli/api.py, python_modules/dagster/dagster/_cli/code_server.py, python_modules/dagster/dagster/_core/definitions/definitions_load_context.py, python_modules/dagster/dagster/_core/definitions/repository_definition/repository_definition.py, python_modules/dagster/dagster/_core/remote_representation/code_location.py, python_modules/dagster/dagster/_core/remote_representation/external_data.py, python_modules/dagster/dagster/_core/remote_representation/grpc_server_registry.py, python_modules/dagster/dagster/_core/storage/defs_state/base.py, python_modules/dagster/dagster/_core/storage/defs_state/blob_storage_state_storage.py, python_modules/dagster/dagster/_grpc/proxy_server.py, python_modules/dagster/dagster/_grpc/server.py, python_modules/dagster/dagster/_grpc/types.py, python_modules/dagster/dagster_tests/storage_tests/utils/defs_state_storage.py, python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/commands/ci/__init__.py, python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/commands/ci/state.py, python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/core/workspace.py, python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli_tests/test_ci_commands.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/defs_state.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/plus/deploy/commands.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/utils.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/utils/plus/build.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/utils/plus/defs_state_storage.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/defs_state_tests/test_refresh_state_command.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/plus_tests/test_plus_deploy_command.py, python_modules/libraries/dagster-shared/dagster_shared/serdes/objects/__init__.py, python_modules/libraries/dagster-shared/dagster_shared/serdes/objects/models/__init__.py, python_modules/libraries/dagster-shared/dagster_shared/serdes/objects/models/defs_state_info.py
This adds a new optional `dg plus deploy refresh-defs-state` command. In order for this to work, we need to bring in the GraphQLDefsStateStorage and create a version of it that can be instantiated with just the available information in the DagsterPlusCliContext object. All this object needs to do is fire off graphql / rest queries, so things work out nicely as this just requires a user token, a url, and a deployment name, all of which we have available.
High level changes:
- factored out common utilities from the existing `dg utils refresh-defs-state` command (which i renamed from `dg utils refresh-component-state` as I think the new things sounds nicer)
- made `DefsStateInfo` and `DefsKeyStateInfo` DagsterModels so that they can be sub-objects in a pydantic schema. While this does have …
=> [2/so] Add `dg plus deploy refresh-defs-state` command

python_modules/dagster-graphql/dagster_graphql/schema/instigation.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_sensors.ambr, python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py, python_modules/dagster/dagster/_cli/sensor.py, python_modules/dagster/dagster/_daemon/sensor.py, python_modules/dagster/dagster_tests/cli_tests/command_tests/test_cli_commands.py, python_modules/dagster/dagster_tests/cli_tests/command_tests/test_sensor_commands.py
This matches the behavior of regular sensors in which we filter out run requests that have a run_key matching an existing run.
These runs do not even show up in the UI, so a similar behavior here seems acceptable
unit, manual
Fixed a bug with the sensor preview behavior that would cause run requests contianing `run_key`s that had already been submitted to show up in the preview result.
=> [sensor-preview] Fix bug where run_keys were not respected

js_modules/dagster-ui/packages/ui-core/src/asset-data/AssetHealthDataProvider.tsx, js_modules/dagster-ui/packages/ui-core/src/asset-data/__tests__/AssetHealthDataProvider.test.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetHealthSummary.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/AssetCatalogTablev2.test.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/AssetHealthSummary.test.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/__tests__/useAllAssetsNodes.test.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/useAllAssets.tsx, js_modules/dagster-ui/packages/ui-core/src/live-data-provider/LiveDataProvider.tsx
Redo of https://github.com/dagster-io/dagster/pull/32044 but with the missing mocks for AssetCatalogTablev2.test.tsx
=> [redo] [Asset health] Only fetch health for assets that have definitions 

python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/cli_invocation.py, python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/client.py, python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/resources.py, python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/run_handler.py, python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/types.py, python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_resources.py
Previously, the `poll_run` command would immediately raise an error when a run failure was detected. This is a bit confusing (in my opinion), and is not actually noted in the docstring. I've updated the code to:
- Not error at all in `poll_run`, instead add a new `wait()` method on the run_handler
- removed `wait_for_success` and instead replaced that call with a `wait()`, followed by a `raise_for_status`.
- Add a `raise_for_status` method on the run object. this is modeled after the `responses` library, where you get a `Response` object and then can decide if/when you want to generate an error based off of that response.
- Removed a check for the test status being PASS when emitting check events -- this brings it in line with the existing implementation for dbt core
With those changes, I …
=> [dbt-cloud] Emit asset events before step failure

js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetSelectionSummaryTile.module.css, js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetSelectionSummaryTile.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetsGroupedView.tsx
Clean up the styles on the asset tiles that show up on the homepage and catalog. In general, made the tiles more compact.
=> update styles for catalog tiles

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_partition_subsets.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py, python_modules/dagster/dagster/_core/definitions/asset_health/asset_materialization_health.py, python_modules/dagster/dagster/_core/storage/event_log/base.py, python_modules/dagster/dagster/_core/storage/partition_status_cache.py
Summary:
Using the loader here more ensures that if this data is fetched more than once in a single graphql request, it will be cached.
Test Plan:
Existing BK
=> Use loaders more when generating asset status cache values

python_modules/dagster/dagster/_config/pythonic_config/resource.py, python_modules/dagster/dagster/_core/definitions/definitions_load_context.py, python_modules/dagster/dagster/_core/execution/context/init.py, python_modules/dagster/dagster/_core/instance/instance.py, python_modules/dagster/dagster/_core/storage/defs_state/base.py, python_modules/dagster/dagster/components/component/state_backed_component.py, python_modules/dagster/dagster_tests/core_tests/instance_tests/test_state_storage_lifecycle.py, python_modules/dagster/dagster_tests/core_tests/resource_tests/test_build_init_resource_context.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/utils/plus/build.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/defs_state_tests/test_refresh_state_command.py
Found a pretty nasty bug when attempting to use a StateBackedComponent in a project that used `FivetranWorkspace.load_asset_specs()` (which uses the old StateBackedDefinitionsLoader functionality). The basic issue is that this ends up using a contextmanager that (among other things), constructs an `UnboundInitResourceContext` object.
This object requires an instance to be made available, so it uses the `ephemeral_instance_if_missing()` context manager in the case that an explicit DagsterInstance is not provided, which it is not in this case. This means that we end up `__enter__`ing a separate DagsterInstance object, which in turn sets the current DefsStateStorage to the defs_state_storage of that new ephemeral instance, which happens to be `None` (although it'd also be bad if it was a …
=> [sbc] Use ExitStack for DefsStateStorage context management

python_modules/dagster/dagster/_core/definitions/asset_selection.py, python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection.py
Allows custom error handling in the graphql layer when an invalid asset selection is input from the frontend.
BK
=> custom DagsterError subclass when an invalid asset selection is parsed

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/defs_state.py
This command requires loading the code location, which can generate a lot of warnings when using preview / beta functionality. We can suppress those warnings in this context to clean things up.
manual
NOCHANGELOG
=> [sbc] suppress dagster warnings in `refresh-defs-state` commands

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/utils.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/defs_state_tests/test_refresh_state_command.py
Ran into this while experimenting -- you get confusing behavior if DAGSTER_HOME is not set, because the command will successfully write state, but it will write it to a temporary directory and instantly be cleared away. so if you have a separate terminal running `dg dev`, that will not actually be impacted by that updated state.
unit
NOCHANGELOG
=> [sbc] ensure DAGSTER_HOME is set for refresh-defs-state

python_modules/dagster/dagster/_core/definitions/asset_selection.py, python_modules/dagster/dagster/_core/definitions/assets/graph/base_asset_graph.py
Summary:
Use this as a filter to asset_keys_for_group rather than doing an intersection of two very large sets
BK
=> GroupsAssetSelection speedup, round 2

python_modules/libraries/dagster-dg-cli/setup.py, python_modules/libraries/dagster-dg-cli/tox.ini
Fixes #31927
Put `anthropic`, `mcp`, and `claude-code-sdk` under a new `ai` extra so that `dg-cli` can be installed without these packages, which are not always installable in sensitive environments.
`anthropic`, `mcp`, and `claude-code-sdk` dependencies of `dagster-dg-cli` are now under a separate `ai` extra, allowing `dagster-dg-cli` to be installed without these dependencies.
=> [dg] Put mcp, anthropic, claude-code-sdk under ai extra (ADOPT-1839)

python_modules/dagster/dagster/_core/instance/instance.py, python_modules/dagster/dagster/_core/instance/types.py, python_modules/dagster/dagster/_utils/caching_instance_queryer.py
Fixes an issue where callsites using DynamicPartitionsStore were using one implementation of get_dynamic_partitions_definition_id and callsites using CachingDynamicParittionsStore were using another implementation.
Dry run scripts that compute asset status cache values in daemon vs. dagit now match
=> Make get_dynamic_partitions_definition_id abstract on DynamicPartitionsStore

python_modules/libraries/dagster-dbt/dagster_dbt/cloud_v2/client.py
This is a required field
[dagster-dbt] Fixed an issue with the DbtCloudWorkspaceClient that would cause errors when calling `trigger_job_run` with no steps_override parameter.
=> [dagster-dbt] Always pass a `cause` when triggering a job run from dagster

python_modules/libraries/dagster-dg-core/dagster_dg_core/component.py, python_modules/libraries/dagster-dg-core/dagster_dg_core_tests/test_context.py
`dg check yaml` was incorrectly matching environment variables in `defs.yaml`.
```python
import re
env_var_regex_dot_notation = re.compile(r"\{\{\s*env\.([^'\"]+)\s*\}\}")
print(env_var_regex_dot_notation.findall("{{ env.FOO }}"))
env_var_regex_dot_notation = re.compile(r"\{\{\s*env\.([^'\"\s]+)\s*\}\}")
print(env_var_regex_dot_notation.findall("{{ env.FOO }}"))
```
- Avoid adding trailing whitespace in env vars that use dot notation in components
=> [components] Avoid adding trailing whitespace to env vars that use dot notation in components

python_modules/dagster/dagster/_core/storage/dagster_run.py, python_modules/dagster/dagster/_core/test_utils.py, python_modules/dagster/dagster_tests/storage_tests/test_run_storage.py, python_modules/dagster/dagster_tests/utils_tests/test_dataloader.py
Applies a limit to the number of runs that the run record loader will fetch in a single storage / sql call, to guard against statement timeouts.
Came up on https://github.com/dagster-io/dagster/pull/32141 where I initially added chunking around RunRecord.gen and owen suggested that it should be part of the default loader implementation instead.
BK
=> Apply a default chunk size to RunRecord loader

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py, python_modules/dagster-graphql/dagster_graphql/implementation/fetch_partition_subsets.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
Summary:
This prevents an issue where in rare circumstances, asset health and asset partition status could show different results for which partitions had failed, by ensuring that the materialized and failed subsets are always sourced from the same place (Specifically, the AssetMaterializationHealthState object). We still have to fetch the in progress subset separately, since that is not currently available on AssetMaterializationHealthState. This should not result in significant additional data fetching since either the AssetMaterializationHealthState will be cached and quick to compute, or it will fall back to computing its data from the asset status partition cache, the potentially expensive part of which is currently cached at the loader level after …
=> Ensure that failed partition subset and materialized subset are sourced from the same data in both asset health and partition statuses

python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/component.py, python_modules/libraries/dagster-databricks/dagster_databricks/components/databricks_asset_bundle/configs.py, python_modules/libraries/dagster-databricks/dagster_databricks_tests/components/databricks_asset_bundle/test_component.py
Databricks tasks don't necessarily map to a single asset - we need a way to pass to what assets a Databricks map.
Currently, we can't add custom fields in required Databricks files (databricks.yml, includes, resources, etc.).
This PR adds a new attribute in the component - asset_specs_by_task_key - that can be customized in defs.yaml. Default asset spec is created for tasks for which asset specs are not defined using this attribute.
```yaml
type: dagster_databricks.components.databricks_asset_bundle.component.DatabricksAssetBundleComponent
attributes:
asset_specs_by_task_key:
my_task:
- key: my_asset_1
deps: [some_asset]
- key: my_asset_2
deps: [some_asset]
```
=> [dagster-databricks] Support task to asset spec mapping in DatabricksAssetBundleComponent

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py, python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
The old code here was very mystifying to me. We fetch the nodes, make a map using info in the nodes, then only use the key in that map, and not the values.
The only benefit I can see is that before it was filering out nodes not in the graph, but it seems perfectly reasonable to fetch the latest info for a node not in the graph.
BK
=> Speed up assetsLatestInfo calculation

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py, python_modules/dagster-graphql/dagster_graphql/schema/asset_selections.py, python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py, python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_assets.ambr, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
Summary:
This makes the method unneccesarily slow. Checking whether an asset has ever existed in the database is not particularly useful, and you can check asset { definition } to see if its in the graph.
Test Plan:
BK, dry runs of slow queries
=> Remove expensive asset graph check from GrapheneAsset constructor

python_modules/libraries/dagster-databricks/dagster_databricks/_test_utils.py, python_modules/libraries/dagster-databricks/dagster_databricks/pipes.py, python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_serverless_pipes.py
This PR updates the `PipesDatabricksServerlessClient` to support Python tasks.
In Databricks Serverless, the following tasks are supported: notebook, Spark Python, Python Wheel and dbt. With this PR, notebook and Python tasks are supported.
Both Spark Python and Python Wheel task requires the `PipesCliArgsParamsLoader`, like when using the `PipesDatabricksClient`:
```python
from dagster_pipes import (
PipesCliArgsParamsLoader,
PipesUnityCatalogVolumesContextLoader,
PipesUnityCatalogVolumesMessageWriter,
open_dagster_pipes,
)
with open_dagster_pipes(
context_loader=PipesUnityCatalogVolumesContextLoader(),
message_writer=PipesUnityCatalogVolumesMessageWriter(),
params_loader=PipesCliArgsParamsLoader(),
) as pipes:
some_parameter_value = pipes.get_extra("some_parameter") …
```
=> [dagster-databricks] Support Spark Python and Python Wheel tasks in PipesDatabricksServerlessClient

python_modules/dagster/dagster/_core/storage/defs_state/base.py, python_modules/dagster/dagster_tests/core_tests/instance_tests/test_state_storage_lifecycle.py
This issue crops up as a side effect of other errors when inside of a webserver that does fancy async things.
The actual error is generally harmless (the process was already in the process of erroring, this just gets added to the stack trace), but we should handle this more gracefully in general and the original behavior here was to set the current storage to None on exit anyway (the contextvar stuff is really just necessary for some pretty niche scenarios) so messing with this isn't the end of the world.
verified the test produced the originally observed error, and now no longer does
NOCHANGELOG
=> [sbc] Fix context var error

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py, .buildkite/dagster-buildkite/dagster_buildkite/utils.py
We missed some failures in `dagster-dg-cli` tests when Component schemas change. This makes it so that buildkite runs this test suite on Component changes.
NOCHANGELOG
=> [buildkite] test dagster-dg-cli when integration with components change

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/api_layer/api/sensor.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/api_layer/graphql_adapter/sensor.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/api_layer/schemas/sensor.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/api/API_IMPLEMENTATION_PLAN.md, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/api/cli_group.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/api/sensor.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/__snapshots__/test_dynamic_command_execution.ambr, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/sensor_tests/Makefile, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/sensor_tests/__snapshots__/test_business_logic.ambr, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/sensor_tests/recordings/empty_filtered_sensors/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/sensor_tests/recordings/empty_sensors/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/sensor_tests/recordings/empty_sensors_text/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/sensor_tests/recordings/error_empty_sensor_name/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/sensor_tests/recordings/error_multiple_sensors_same_name/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/sensor_tests/recordings/error_sensor_not_found/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/sensor_tests/recordings/error_sensor_not_found_text/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/sensor_tests/recordings/success_filtered_sensors_paused/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/sensor_tests/recordings/success_filtered_sensors_paused_text/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/sensor_tests/recordings/success_filtered_sensors_running/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/sensor_tests/recordings/success_filtered_sensors_running_text/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/sensor_tests/recordings/success_filtered_sensors_stopped/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/sensor_tests/recordings/success_filtered_sensors_stopped_text/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/sensor_tests/recordings/success_multiple_sensors/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/sensor_tests/recordings/success_multiple_sensors_text/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/sensor_tests/recordings/success_single_sensor_running/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/sensor_tests/recordings/success_single_sensor_running_text/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/sensor_tests/scenarios.yaml, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/sensor_tests/test_business_logic.py
```
▸ dg api sensor list
Name: dbt_code_version_sensor
Status: STOPPED
Type: STANDARD
Description: None
Name: default_automation_condition_sensor
Status: RUNNING
Type: AUTO_MATERIALIZE
Description: None
Name: orders_sensor
Status: RUNNING
Type: ASSET
Description: None
Name: watch_s3_sensor
Status: RUNNING
Type: STANDARD
Description: None
Name: weekly_freshness_check_sensor
Status: RUNNING
Type: STANDARD
Description:
This sensor launches execution of freshness checks for the provided assets. The sensor will
only launch a new execution of a freshness check if the check previously passed, but enough
time has passed that the check could be overdue again. Once a check has failed, the sensor
will not launch a new execution until the asset has been updated (which should automatically
execute the …
```
=> [dg] adds `dg api sensor list` and `dg api sensor get`

js_modules/dagster-ui/packages/ui-core/client.json, js_modules/dagster-ui/packages/ui-core/src/runs/RunActionsMenuRunFragment.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/externalRuns.tsx, js_modules/dagster-ui/packages/ui-core/src/runs/types/RunActionsMenuRunFragment.types.ts, js_modules/dagster-ui/packages/ui-core/src/runs/types/RunsFeedTableEntryFragment.types.ts, js_modules/dagster-ui/packages/ui-core/src/runs/types/useRunsFeedEntries.types.ts, js_modules/dagster-ui/packages/ui-core/src/workspace/workspacePath.ts
Now that @OwenKephart has added the execution plan `assetKeys` to runs, we can use this to correctly build an href from a run to view asset lineage.
- If there is an asset selection, link to that.
- Else, if there is a list of asset keys in the execution plan, link to that.
View a run that has an `assetSelection`, verify that it links correctly. View a run that only has asset keys on `executionPlan`, verify that it links correctly.
[ui] Fixed the link to "View asset lineage" on runs that don't specify an asset selection.
=> [ui] Use execution plan asset keys to determine asset lineage link on Run page

.claude/commands/dg_troubleshoot_run.md, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/api_layer/api/run_event.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/api_layer/graphql_adapter/run_event.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/api_layer/schemas/run_event.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/api/cli_group.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/api/log.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/__snapshots__/test_dynamic_command_execution.ambr, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/log_tests/Makefile, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/log_tests/__snapshots__/test_business_logic.ambr, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/log_tests/recordings/error_invalid_level_json/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/log_tests/recordings/error_invalid_level_text/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/log_tests/recordings/success_logs_basic_json/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/log_tests/recordings/success_logs_basic_text/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/log_tests/recordings/success_logs_debug_level_json/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/log_tests/recordings/success_logs_debug_level_text/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/log_tests/recordings/success_logs_error_level_only_json/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/log_tests/recordings/success_logs_error_level_only_text/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/log_tests/recordings/success_logs_small_limit_json/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/log_tests/recordings/success_logs_small_limit_text/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/log_tests/recordings/success_logs_step_filter_json/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/log_tests/recordings/success_logs_step_filter_text/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/log_tests/recordings/success_logs_with_errors_json/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/log_tests/recordings/success_logs_with_errors_text/01_response.json, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/log_tests/scenarios.yaml, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/log_tests/test_business_logic.py
Implemented for troubleshooting AI workflows, eg.
```
> /dg_troubleshoot_run is running… 0e7d073a-5fdb-48bd-bb1a-4bb0359c528f
⏺ I'll troubleshoot the failing run by first checking for errors in the logs.
⏺ Bash(dg api log get 0e7d073a-5fdb-48bd-bb1a-4bb0359c528f --json | jq '.logs[] | select(.level == "ERROR")')
⎿  {
"runId": "0e7d073a-5fdb-48bd-bb1a-4bb0359c528f",
"message": "Execution of step \"poll_snowflake_query_history_hour\" failed.",
… +144 lines (ctrl+o to expand)
⏺ Run Failure Summary
Run ID: 0e7d073a-5fdb-48bd-bb1a-4bb0359c528f
Root Cause: Snowflake user account has been temporarily locked
Failed Step: poll_snowflake_query_history_hour
Error Details:
- Primary Issue: snowflake.connector.errors.DatabaseError: 250001 (08001): Failed to connect to DB: …
```
=> [dg] adds `dg api log get`

python_modules/dagster-graphql/dagster_graphql_tests/graphql/graphql_context_test_suite.py
I'd like to subclass the graphql context test suites to add more hooks into the context, while maintaining access to the superclass's graphql context.
The cleanest way I found to do this was to separate out the construction of the context and the fixture function.  Each subclass can add onto the implementation of the context construction, and slightly change the fixture as needed.  The overriding of arguments / usage of fixtures required lots of type ignoring.
BK
=> adjust make_graphql_context_test_suite fixtures

python_modules/dagster-graphql/dagster_graphql/implementation/execution/launch_execution.py, python_modules/dagster-graphql/dagster_graphql/implementation/execution/run_lifecycle.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py, python_modules/dagster/dagster/_cli/job.py, python_modules/dagster/dagster/_core/definitions/assets/graph/remote_asset_graph.py, python_modules/dagster/dagster/_core/execution/job_backfill.py, python_modules/dagster/dagster/_core/instance/methods/run_methods.py, python_modules/dagster/dagster/_core/instance/runs/run_domain.py, python_modules/dagster/dagster/_daemon/auto_run_reexecution/auto_run_reexecution.py, python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py, python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance_reexecution.py, python_modules/dagster/dagster_tests/daemon_tests/conftest.py, python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py
This asset graph sometimes has better caching behavior than the repository scoped asset graph.
Existing test coverage (ensure both types of asset graphs are covered)
=> Prefer passing in a workspace scoped asset graph when creating runs

python_modules/dagster/dagster/_core/instance/runs/run_domain.py, python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py
Summary:
Resolves a very rare issue where the same asset keys being inserted in different orders by different runs simultaneously could cause issues in the storage layer.
Existing test coverage of planned event batching
=> Sort planned events by asset key before they are batch inserted into the database

js_modules/dagster-ui/packages/ui-core/src/graphql/schema.graphql, js_modules/dagster-ui/packages/ui-core/src/graphql/types.ts, python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py, python_modules/dagster/dagster/_core/definitions/freshness.py
We currently compute this in the UI but that requires fetching the freshness policy definition from the asset graph and only works for time window policies. This adds a GQL endpoint that gets the time that the freshness record in the DB updated.
Also updates the `from_db_row`​ method of `FreshnessStateRecord`​ to use dot-access to get the entries we want from the row. There was a bug where the `updated_at`​ attr was sourced from the `created_at`​ column. Also adds timezone info to the datetime object since we store a utc datetime in the DB but read it as a datetime with no timezone. this was causing conversion issues when getting the timestamp to send to the front end
For future perf improvements we can move this to streamline https://linear.app/dagster-labs/issue/OPER-2443/source-timestam …
=> gql to get the time that an asset's freshness state changed

python_modules/libraries/dagster-dg-cli/dagster_dg_cli/cli/api/run.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/__snapshots__/test_dynamic_command_execution.ambr, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/run_tests/__snapshots__/test_business_logic.ambr, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/cli_tests/api_tests/run_tests/test_business_logic.py
Summary:
[test-all] Get the release branch green and also remove the enum from the string, win win
Test plan: BK
=> [test-all] fix dg test snapshots on python 3.9

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
Summary:
This is our slowest test suite (making the test suite faster is of course another option), so add more parallelism.
=> Give dagster-dg-cli more splits

python_modules/libraries/dagster-cloud-cli/dagster_cloud_cli/config_utils.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli/utils/plus/defs_state_storage.py
`gql` automatically pulls out the `result["data"]` field (fun!)
also noticed that we weren't actually pulling this into the code location deploy document
pain
NOCHANGELOG
=> [sbc] Fix refresh-defs-state storage

python_modules/dagster/dagster/components/core/component_tree.py, python_modules/dagster/dagster/components/core/decl.py, python_modules/dagster/dagster/components/resolved/base.py, python_modules/dagster/dagster_tests/components_tests/component_tree_tests/test_get_all_components.py, python_modules/libraries/dagster-shared/dagster_shared/utils/__init__.py
Fixes #32278 
Instead of first loading all components, then inspecting their types, we can instead inspect the type of each component before loading it.
For python-based components, this does mean that we end up ignoring components that do not specify a return type on their function definitions, but I think this is an acceptable sacrifice. If we want to walk this back, we could create an `UnknownComponentTypeSentinel` and load all of those / filter them post-hoc, but I'm biased towards the simple approach for now.
unit
`dagster-dbt project prepare-and-package --components .` will no longer attempt to load components outside of `DbtProjectComponent`, preventing errors when attempting to run this command in environments that do not have the necessary env vars set for other components.
=> [components] load_all_components(of_type=T) should not load components outside of that type

python_modules/dagster/dagster/components/resolved/core_models.py, python_modules/dagster/dagster_tests/components_tests/resolution_tests/test_resolvable_transformer.py, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/yaml_template/test_data/account/expected_example, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/yaml_template/test_data/account/expected_schema, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/yaml_template/test_data/dbt_project/expected_example, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/yaml_template/test_data/dbt_project/expected_schema, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/yaml_template/test_data/python_script/expected_example, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/yaml_template/test_data/python_script/expected_schema, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/yaml_template/test_data/sling_replication_collection/expected_example, python_modules/libraries/dagster-dg-cli/dagster_dg_cli_tests/yaml_template/test_data/sling_replication_collection/expected_schema
This is a field on AssetSpec, you should be able to set it. No yaml schema for this for now, but we can always add that later. For now, you just use template vars.
unit
`ResolvedAssetSpec` and related resolvers now support setting the `freshness_policy` field.
=> [components] Allow `freshness_policy` to be set in `ResolvedAssetSpec`

python_modules/libraries/dagster-airbyte/dagster_airbyte/components/workspace_component/component.py, python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/beta/test_component.py
[dagster-airbyte] The AirbyteWorkspaceComponent now has a `get_asset_spec` method that can be overridden by subclasses.
=> [dagster-airbyte] Add a `get_asset_spec` method to AirbyteWorkspaceComponent

python_modules/dagster-graphql/dagster_graphql/implementation/execution/launch_execution.py, python_modules/dagster-graphql/dagster_graphql/implementation/external.py, python_modules/dagster-graphql/dagster_graphql/implementation/fetch_pipelines.py, python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py, python_modules/dagster-graphql/dagster_graphql/implementation/run_config_schema.py, python_modules/dagster-graphql/dagster_graphql/implementation/utils.py, python_modules/dagster-graphql/dagster_graphql/schema/roots/mutation.py, python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_permissions.py, python_modules/dagster/dagster/_core/remote_representation/code_location.py, python_modules/dagster/dagster/_core/workspace/context.py, python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_job.py
Summary:
Ensures that when we fetch teh run config schema and remote job in teh same graphql query, they go through a shared batching layer (as long as they pass in the same selector).
Test Plan:
Bk
=> Loaderify remote job loading in graphql layer

python_modules/libraries/dagster-sling/dagster_sling/resources.py, python_modules/libraries/dagster-sling/dagster_sling_tests/test_resource.py
Resolves #32208
Stream names containing "INF" (like CUSTOMERINFO) were being corrupted during log parsing, causing DagsterInvariantViolationError.
The _clean_line() method used .replace("INF", "") which stripped ALL "INF" occurrences from log lines, not just the Sling log level prefix. Sling outputs logs as {timestamp} INF {message} where "INF" is the log level indicator.
Updated the regex pattern to only remove the log level prefix at the start of lines:
- Changed from: .replace("INF", "")
- Changed to: re.sub(r"^\d{1,2}:\d{2}[AP]M\s+(INF|WRN|ERR|DBG)\s+", "", line)
Including new test cases for:
- Standard Sling log format with INF in stream names
- Multiple INF occurrences in messages
- Different log levels (WRN, ERR, DBG)
- Edge cases with INF at various positions
- [dagster-sling] …
=> [dagster-sling] resolve issue with log parser and INF

js_modules/dagster-ui/packages/ui-core/client.json, js_modules/dagster-ui/packages/ui-core/src/assets/AssetView.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/types/AssetView.types.ts
Summary:
Bring back the redirect removed in https://app.graphite.dev/github/pr/dagster-io/dagster/32282 by checking for a hasDefinitionOrRecord field
Test Plan:
Load an asset key that does not exist, redirect is retained
Load an asset key that does exist, it works as before
=> Use hasDefinitionOrRecord in asset view permalink

python_modules/dagster-graphql/dagster_graphql/implementation/events.py
Summary:
Noticed some "TypeError: Cannot return null for non-nullable field UrlMetadataEntry.url" in logs - use the property designed to guard against that instead of the guardable one.
BK
=> use non-nullable property for GrapheneUrlMetadataEntry

python_modules/dagster/dagster/_core/definitions/partitions/definition/time_window.py, python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py
Previously, defining a time window partition with a monthly schedule and no provided offset would fail since `TimeWindowPartitionsDefinition` constructor was passing 0 as the default day offset value. In cron format, days of months start at 1, not 0.
```python
partition_def = TimeWindowPartitionsDefinition(
schedule_type=ScheduleType.MONTHLY,
start=datetime.now(),
fmt="%Y-%m-%d",
)
```
This PR simply propagates the constructor default `None` instead of `0` through to `cron_schedule_from_schedule_type_and_offsets` which correctly sets the default day offset to 1.
This lets users define a `TimeWindowPartitionDefinition` with monthly schedule type without manually setting `day_offset=1`.
Added a unit test that tries to define a time window partition this way
Fix a bug where …
=> Use correct default `day_offset` of 1 when defining a `TimeWindowPartition` with monthly schedule

js_modules/dagster-ui/packages/ui-core/src/asset-graph/AssetGraphExplorer.tsx
This is a tiny fix for https://linear.app/dagster-labs/issue/FE-776/lineage-view-materialize-action-not-reflecting-asset-selection-if
If you type a query into the asset graph filter box both the graph data and layout can change. A loading bar appears, but while the UI is loading, clicking the Materialize button does not reflect your new filters.
I tested this manually with some jumping around the asset graph. Most of the time, filters apply ~immediately and the disabled state is not noticeable.
[ui] Lineage view Materialize button is disabled while the view is updating, rather than allowing Materialization of your previous asset query.
=> FE-776: Disable the Materialize button if it’s scope is stale

js_modules/dagster-ui/packages/ui-core/src/app/BaseFallthroughRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/app/__tests__/BaseFallthroughRoot.test.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/AssetActionMenu.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/catalog/AssetCatalogAssetGraph.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/globalAssetGraphPathToString.tsx, js_modules/dagster-ui/packages/ui-core/src/assets/overview/DefinitionSection.tsx, js_modules/dagster-ui/packages/ui-core/src/instigation/TickMaterializationsTable.tsx, js_modules/dagster-ui/packages/ui-core/src/overview/OverviewAssetsRoot.tsx, js_modules/dagster-ui/packages/ui-core/src/workspace/VirtualizedAssetRow.tsx
Related: https://linear.app/dagster-labs/issue/FE-982/make-lineage-ignore-code-locations-in-groupings
We’d like to remove the asset group pages which live at paths scoped to a code location.  We can’t /quite/ get rid of these pages yet, but this PR reduces the number of places in the app that link to them.
Instead of linking to the asset group page, we link to the global graph with a `group: “groupname”` filter.  The impacted callsites are mostly 1) "View in group" (menu option on assets),  2) links to the group name on the definition page, etc., and 3) the root page of the app when assets and no jobs are present.
After this PR, the groups pages are really only accessible via the old Jobs left nav.
I tested these manually and added a new helper.
=> [ui] Prefer the global graph with a group filter over asset group pages

python_modules/dagster/dagster/_core/execution/context/output.py, python_modules/dagster/dagster_tests/execution_tests/context_tests/test_output.py
While working on a PR for dagster-iceberg I found that `build_output_context` doesn't expose the `output_metadata` attribute of `OutputContext` for configuration. 
I tried using `context.add_output_metadata`, but found that it unintuitively does not actually mutate the `output_metadata` value of the `OutputContext` instance, so it can't be used to add `output_metadata` to an existing `OutputContext` instance created by `build_output_context`.
These changes enable a user to pass `output_metadata` to `build_output_context` and have it be set on the resulting `OutputContext` object.
Added a unit test covering the new functionality. Ran the rest of the unit tests
- Enable passing `output_metadata` into `build_output_context`
=> Enable adding output_metadata via build_output_context

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_schedules.py, python_modules/dagster-graphql/dagster_graphql/implementation/utils.py, python_modules/dagster-graphql/dagster_graphql/schema/schedules/__init__.py, python_modules/dagster-graphql/dagster_graphql/schema/sensors.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_sensors.ambr, python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_definition_owner_permissions.py
This changes the sensor / schedule graphql mutations to per-definition permission checks enabled by https://github.com/dagster-io/dagster/pull/32151
BK
=> add sensor/schedule permission checks

python_modules/dagster-graphql/dagster_graphql/implementation/execution/backfill.py, python_modules/dagster-graphql/dagster_graphql/implementation/utils.py, python_modules/dagster-graphql/dagster_graphql/schema/backfill.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_all_snapshot_ids.ambr, python_modules/dagster-graphql/dagster_graphql_tests/graphql/__snapshots__/test_solids.ambr, python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py, python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_definition_owner_permissions.py
Changes the graphql backfill mutations to use the new definition permission checks enabled by https://github.com/dagster-io/dagster/pull/32151.
Asset backfills use the asset definition checks added in https://github.com/dagster-io/dagster/pull/32151.  Job backfills use the job definition checks added in https://github.com/dagster-io/dagster/pull/32285
BK
=> add backfill permission checks

python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud_v2/test_specs.py
Changes made in #32441 modify the number of asset checks in `test_load_check_specs_exclude` because of the updated condition `if child_unique_id not in selected_unique_ids or not child_unique_id.startswith("test")`.
Updated test with BK
=> [dagster-dbt] Fix test_load_check_specs_exclude in dbt Cloud v2 test suite
