dagster-io/dagster

python_modules/libraries/dagster-dbt/dagster_dbt/cli/resources.py

These should show up in the API docs

[dagster-dbt] make dbt cli resource methods public

---

docs/content/concepts/io-management/io-managers.mdx
docs/sphinx/sections/api/apidocs/partitions.rst
examples/docs_snippets/docs_snippets/concepts/io_management/custom_io_manager.py
python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
python_modules/dagster/dagster/_core/storage/fs_io_manager.py

This was initially motivated by https://github.com/dagster-io/dagster/issues/9597, and then I made some additional changes as I read through the docs, to make them more asset-focused.
Local inspection

IO manager concept doc improvements

---

docs/content/dagster-cloud/account/managing-user-agent-tokens.mdx
docs/next/components/mdx/includes/dagster-cloud/GenerateAgentToken.mdx

Renaming the tab since the other tabs don't include verbs

Configure tokens -> Tokens

---

python_modules/libraries/dagster-databricks/dagster_databricks/solids.py

fix code example in create_databricks_job_op

---

.buildkite/dagster-buildkite/dagster_buildkite/package_spec.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/tox.py

So it's clearer why something didn't run.

Skip package steps instead of excluding them

---

python_modules/dagster/dagster_tests/core_tests/storage_tests/utils/event_log_storage.py

allows runs to enter a queued state in tests that update the run status on event change
bk

[event log tests] add origin to run

---

python_modules/dagster-test/dagster_test/toys/big_honkin_asset_graph.py
python_modules/dagster-test/dagster_test/toys/repo.py

move the big honkin asset graph to latest asset APIs

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/helm.py
.buildkite/dagster-buildkite/dagster_buildkite/utils.py
helm/dagster/schema/setup.py
helm/dagster/schema/tox.ini

The thing I'm least sure of is if I've accurately captured this package's dependencies on other dagster packages. I added a few extras based on what was used in the tests and after chatting with @rexledesma.

Conditionally skip helm steps

---

examples/project_fully_featured/setup.py
python_modules/libraries/dagster-snowflake-pandas/setup.py
python_modules/libraries/dagster-snowflake/setup.py

Summary:
Did an exact pin since I would be surprised if they don't fix this in a hotfix of
snowflake-sqlalchemy, see https://github.com/snowflakedb/snowflake-sqlalchemy/issues/350

Workaround for upstream snowflake-sqlalchemy issue

---

python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py

OSS version for making the tag queries more efficient
BK

replace tag joins with subquery over tag intersection queries

---

.buildkite/dagster-buildkite/dagster_buildkite/package_spec.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py
.buildkite/dagster-buildkite/dagster_buildkite/utils.py

I need to figure out why these didn't run on https://github.com/dagster-io/dagster/pull/10037 - it suggests the logic isn't quite right.
This should unbreak main.

Fixup lints

---

docs/content/dagster-cloud/developing-testing/dagster-cloud-cli.mdx

[easy] fix incorrect cli link

---

js_modules/dagit/packages/core/src/assets/LaunchAssetChoosePartitionsDialog.tsx

consistent capitalization in LaunchAssetChoosePartitionsDialog

---

python_modules/dagster/dagster/_core/definitions/graph_definition.py
python_modules/dagster/dagster/_core/types/dagster_type.py
python_modules/dagster/dagster_tests/core_tests/graph_tests/test_graph.py

fix graph type inference with fan-in

---

js_modules/dagit/packages/core/src/app/Permissions.tsx
js_modules/dagit/packages/core/src/testing/TestProvider.tsx

Using this in cloud dagit to figure out when we can decided if a user has permission to do certain things.
cloud

Expose permissions loading state

---

python_modules/dagster-graphql/dagster_graphql/schema/schedules/schedules.py

Custom tick range is generating index error
Inspection

fix future ticks cursor when no ticks are available

---

docs/content/deployment/dagster-instance.mdx
examples/docs_snippets/docs_snippets/deploying/dagster_instance/dagster.yaml
examples/docs_snippets/docs_snippets_tests/deploying_tests/dagster_instance_tests/snapshots/snap_test_dagster_instance.py
helm/dagster/schema/schema/charts/dagster/subschema/daemon.py
helm/dagster/schema/schema_tests/test_dagster_daemon.py
helm/dagster/templates/configmap-instance.yaml
helm/dagster/values.schema.json
helm/dagster/values.yaml

Add helm vals for scheduler threading

---

CHANGES.md

1.0.14 changelog

---

CHANGES.md

Test Plan: Missed the train, chasing it with my luggage trailing behind me as it leaves the station

1.0.14 changelog addendum

---

python_modules/dagster/dagster/_core/storage/alembic/versions/032_rebuild_event_indexes.py
python_modules/dagster/dagster/_core/storage/event_log/schema.py
python_modules/dagster/dagster/_core/storage/migration/utils.py

Our event log queries order by id, so we should include id in our indices.
BK

rebuild event log indices to include id

---

python_modules/libraries/dagster-gcp/dagster_gcp/gcs/io_manager.py

My naive fix for the issue I raised in https://github.com/dagster-io/dagster/issues/10109
Given the intermittent nature of the problem (we haven't had another 503 error of this nature in over a week) it's not an easy problem for me to test but am open to suggestions on how I could test it :)

Retry on Service Unavailable

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/snapshots/snap_test_all_snapshot_ids.py
python_modules/dagster-test/dagster_test_tests/test_toys.py
python_modules/dagster/dagster/_core/definitions/asset_group.py
python_modules/dagster/dagster/_core/definitions/assets_job.py
python_modules/dagster/dagster/_core/definitions/repository_definition.py
python_modules/dagster/dagster_tests/core_tests/asset_defs_tests/test_asset_group.py
python_modules/dagster/dagster_tests/core_tests/asset_defs_tests/test_assets_job.py

because AssetGroup is deprecated and will eventually go away

[refactor] take logic for base asset jobs out of AssetGroup

---

.github/ISSUE_TEMPLATE/config.yml
docs/next/pages/_app.tsx
python_modules/dagster/README.md

docs: update @dagsterio -> @dagster

---

docs/content/concepts/partitions-schedules-sensors/partitions.mdx

switch order of assets and jobs in partitions doc

---

.buildkite/dagster-buildkite/dagster_buildkite/pipelines/dagster_oss_main.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/dagit_ui.py

https://github.com/dagster-io/dagster/pull/10048 ended up not making it into master due to a bad rebase.

Conditionally skip dagit builds

---

python_modules/dagster/dagster/_core/definitions/sensor_definition.py
python_modules/dagster/dagster/_core/event_api.py

Reaching down deep into EventLogRecords creates a lot of boilerplate in our code base.
On the other hand, I marked it as an RFC, because this is a slippery slope, and as soon as we start exposing some stuff on EventLogRecord, what's to stop us from exposing everything??

EventLogRecord.partition_key and EventLogRecord.asset_key

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/asset_defs.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/test_load_from_project.py

@benpankow and I have been discussing making this change potentially, so thought I'd go ahead and put it in a PR so others can see. I'm using a custom version of this currently and it speeds up startup time by approximately 5x (and I only have 25 connections!).
Unit tests

[dagster-airbyte] allow filtering connections by directory names

---

js_modules/dagit/packages/app/package.json
js_modules/dagit/packages/core/package.json
js_modules/dagit/packages/eslint-config/package.json
js_modules/dagit/packages/ui/package.json
js_modules/dagit/yarn.lock

Do a little dependency bumping.
Buildkite

[dagit] Bump TypeScript

---

docs/content/dagster-cloud/deployment/agents/kubernetes/configuration-reference.mdx

From https://dagster.slack.com/archives/C014N0PK37E/p1666716967389189, the previous link was broken.
eyes

docs(dagster-cloud-agent): update IAM role link

---

python_modules/dagster/dagster/_core/storage/event_log/in_memory.py
python_modules/dagster/dagster/_core/storage/runs/in_memory.py
python_modules/dagster/dagster/_core/storage/sqlite.py

Replace custom in-memory logic with in-memory sqlite connection

---

python_modules/libraries/dagster-dbt/dagster_dbt/asset_defs.py

For large dbt projects, these descriptions can result in really large snapshot sizes

[dagster-dbt] add flag to make asset snapshots smaller

---

python_modules/dagster/dagster/_config/snap.py
python_modules/dagster/dagster/_config/traversal_context.py

rm all_types from config_context

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/docs.py

I missed this when skipping other docs steps in https://github.com/dagster-io/dagster/pull/10030

Also skip docs next

---

python_modules/dagster/dagster/_api/snapshot_partition.py
python_modules/dagster/dagster/_core/execution/backfill.py
python_modules/dagster/dagster/_core/host_representation/repository_location.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_daemon/backfill.py
python_modules/dagster/dagster/_daemon/daemon.py
python_modules/dagster/dagster/_grpc/impl.py
python_modules/dagster/dagster/_grpc/types.py

type annotations on backfill-related code paths

---

docs/content/dagster-cloud/deployment/serverless.mdx
docs/node_modules/.yarn-integrity

Add docs for customizing the serverless base image

---

js_modules/dagit/packages/core/src/assets/AssetView.test.tsx
js_modules/dagit/yarn.lock

Repair these warnings by adjusting some of the mocks.
yarn jest AssetView

[dagit] Fix AssetView.test key warnings

---

CHANGES.md

1.0.15 changelog

---

python_modules/dagster/dagster/_core/definitions/reconstruct.py
python_modules/dagster/dagster/_core/events/__init__.py

fix black, mypy

---

CHANGES.md
MIGRATION.md

Was trying to update the hooli_data_eng example and noticed this was incorrect.

Fix stray references to define_assets_job

---

js_modules/dagit/packages/core/src/schedules/humanCronString.test.ts

Not sure why I didn't see this coming, but now that some time zones are starting to switch to standard time because of daylight savings changes, this test is breaking.
Change the test to use time zones that do not use daylight savings.
yarn jest humanCronString

[dagit] Fix daylight savings issue in humanCronString.test

---

python_modules/dagster/dagster/_core/definitions/job_definition.py
python_modules/dagster/dagster_tests/core_tests/asset_defs_tests/test_materialize_to_memory.py

Support overriding run config for partitions with execute_in_process

---

examples/assets_modern_data_stack/assets_modern_data_stack/assets/forecasting.py
python_modules/dagster/dagster/_core/definitions/resolved_asset_deps.py
python_modules/dagster/dagster_tests/core_tests/asset_defs_tests/test_resolved_asset_deps.py

fix some cases in group-based asset dep resolution

---

js_modules/dagit/packages/ui/CHANGES.md
js_modules/dagit/packages/ui/package.json

Summary & Motivation
Update @dagster-io/ui for a release of v1.0.7.
How I Tested These Changes
Buildkite

dagster-io/ui release notes

---

python_modules/dagster/dagster/_core/events/__init__.py

keep storage name for serialized event backcompat

---

js_modules/dagit/packages/core/src/graphql/schema.graphql
python_modules/dagster-graphql/dagster_graphql/implementation/events.py
python_modules/dagster-graphql/dagster_graphql/implementation/execution/__init__.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_logs.py
python_modules/dagster-graphql/dagster_graphql/schema/instance.py
python_modules/dagster-graphql/dagster_graphql/schema/logs/compute_logs.py
python_modules/dagster-graphql/dagster_graphql/schema/logs/events.py
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/subscription.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/snapshots/snap_test_captured_logs.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_captured_logs.py
python_modules/dagster/dagster/_core/events/__init__.py
python_modules/dagster/dagster/_core/execution/plan/execute_plan.py

Creates the new graphql fields / subscriptions to read captured logs.
BK

graphql for captured log subscription

---

helm/dagster/schema/schema/charts/dagster/subschema/daemon.py
helm/dagster/schema/schema/charts/dagster/subschema/dagit.py
helm/dagster/schema/schema_tests/test_dagit.py
helm/dagster/schema/schema_tests/test_dagster_daemon.py
helm/dagster/templates/deployment-daemon.yaml
helm/dagster/templates/helpers/_deployment-dagit.tpl
helm/dagster/values.schema.json
helm/dagster/values.yaml

Add volumes and volumeMounts to dagit and daemon in OSS helm chart

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_execute_pipeline.py

ran black, not sure why my editor didn't format on save.
BK

fix black formatting

---

python_modules/dagster/dagster/_core/definitions/job_definition.py
python_modules/dagster/dagster/_core/definitions/unresolved_asset_job_definition.py
python_modules/dagster/dagster_tests/core_tests/asset_defs_tests/test_unresolved_asset_job.py
python_modules/dagster/dagster_tests/execution_tests/test_job.py

This was recently requested by a user.

run_config argument on run_request_for_partition

---

python_modules/dagster/dagster/__init__.py
python_modules/dagster/dagster/_core/definitions/decorators/source_asset_decorator.py
python_modules/dagster/dagster/_core/definitions/events.py
python_modules/dagster/dagster/_core/definitions/source_asset.py
python_modules/dagster/dagster/_core/errors.py
python_modules/dagster/dagster/_core/execution/context/compute.py
python_modules/dagster/dagster_tests/core_tests/asset_defs_tests/test_asset_group.py
python_modules/dagster/dagster_tests/core_tests/definitions_tests/decorators_tests/test_source_asset.py

New `observable_source_asset` decorator.
Unit tests

Observable source asset decorator

---

python_modules/dagster/dagster/_core/definitions/decorators/source_asset_decorator.py

fix build; isort; black

---

python_modules/dagster/dagster_tests/core_tests/host_representation_tests/test_custom_repository_data.py
python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py
python_modules/dagster/dagster_tests/core_tests/selector_tests/test_execute.py
python_modules/dagster/dagster_tests/core_tests/selector_tests/test_subset_selector.py

Made using https://github.com/dpeng817/codemods

[jog] host_representation_tests, instance_tests, selector_tests

---

CHANGES.md

- make the community contribution acknowledgment mentions consistent in formats
- add `define_dagstermill_asset`
- reorder entries to put changes in libs after core changes

update 1.0.16 changelog

---

python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/test_instance.py

Summary:
We recently moved task_definition from a StringSource to a scalar union, but some users were relying on setting the task definition to an environment variable. In hindsight we probably could have made it an entirely separate field instead of a scalar union, but for now to keep the current behavior without breaking old behavior, set an 'env' key to the dictionaryu that allows it to still be used to source the string from a environment variable.
Test Plan: BK

Back-compat fix for setting the task definition in the EcsRunLauncher to an env var

---

python_modules/dagster/dagster_tests/conftest.py

Summary:
Take 2 on mocking out tqdm - you have to list out each callsite for the patch to stick
Test Plan:
Run test_back_compat.py, no more progress bars

Mock each callsite of tqdm

---

helm/dagster/schema/schema_tests/test_dagit.py
helm/dagster/templates/helpers/_deployment-dagit.tpl

Based on https://github.com/dagster-io/dagster/pull/8900 by @jblawatt with an added test case.
Resolves https://github.com/dagster-io/dagster/issues/10182

add securityContext to dagit init-user-deployment initContainers

---

python_modules/dagster/dagster_tests/conftest.py

Reverts dagster-io/dagster#10368
In favor of #10372

Revert "Mock each callsite of tqdm"

---

python_modules/libraries/dagster-databricks/dagster_databricks/solids.py

Helps with https://github.com/dagster-io/dagster/issues/10281

[apidocs] clarify usage of create_databricks_job_op

---

docs/content/deployment/dagster-instance.mdx

noticed this while reading https://docs.dagster.io/deployment/dagster-instance#dagster-storage
not

fix mysql heading level + typo

---

python_modules/dagster/dagster/_core/definitions/assets_job.py
python_modules/dagster/dagster/_core/definitions/repository_definition.py
python_modules/dagster/dagster_tests/core_tests/definitions_tests/test_repository_definition.py

This will be used by partitioned asset reconciliation sensors
Added a test

Enable accessing base jobs off of repository definitions

---

.gitignore

add pyrightconfig.json to .gitignore

---

python_modules/dagster/dagster/_core/definitions/freshness_policy.py
python_modules/dagster/dagster_tests/core_tests/asset_defs_tests/test_freshness_policy.py

Add a new type of FreshnessPolicy which is relative to the latest available data for the upstream assets.
latest_upstream_materialization_times is going to be relative to the record that we're evaluating this minutes_late value for, so we'll probably end up storing this value in the asset event tags similar to the used_upstream_materialization_times, for efficiency. It corresponds to the newest asset materializations that were available at the time we produced this materialization.

[freshness-policy] add latency freshness policy

---

python_modules/dagster/dagster/_core/definitions/schedule_definition.py
python_modules/dagster/dagster/_scheduler/scheduler.py
python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py

support RunRequest.asset_selection in schedules

---

python_modules/dagster/dagster/_core/definitions/materialize.py
python_modules/dagster/dagster_tests/core_tests/asset_defs_tests/test_materialize.py
python_modules/dagster/dagster_tests/core_tests/asset_defs_tests/test_materialize_to_memory.py

support raise_on_error in materialize and materialize_to_memory

---

python_modules/dagster/dagster/_core/definitions/cacheable_assets.py

As the title.
existing pytest, local

docs(cacheable-assets): mark unimplemented methods as abstract

---

docs/content/dagster-cloud/deployment/agents/docker.mdx

Summary:
These are steps for configuring the whole agent, not just a docker network.

[easy] fix incorrect header in docker guide

---

python_modules/dagster-graphql/dagster_graphql/implementation/events.py

observed an error on this line - defend against it
bk

[graphql] handle null int metadata val

---

python_modules/dagster/dagster_tests/core_tests/snap_tests/snapshots/snap_test_execution_plan.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/snapshots/snap_test_pipeline_snap.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/test_composite_solid_def_snap.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/test_config_schema_snapshot.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/test_dagster_type_namespace_snapshot.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/test_execution_plan.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/test_old_execution_plan_snapshot.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/test_pipeline_snap.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/test_repository_snap.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/test_solid_def_snap.py

Made using https://github.com/dpeng817/codemods

[jog] Convert snap tests

---

python_modules/dagster/dagster/_core/definitions/multi_dimensional_partitions.py
python_modules/dagster/dagster/_core/execution/context/system.py
python_modules/dagster/dagster/_utils/calculate_data_time.py

Fix asset partition key range query

---

docs/content/getting-started/install.mdx

[docs] correct versions in install section

---

CHANGES.md

https://github.com/dagster-io/dagster/blob/yuhan/11-10-changelog_1.0.17/CHANGES.md

changelog 1.0.17

---

python_modules/dagster/dagster/_api/list_repositories.py
python_modules/dagster/dagster/_api/notebook_data.py
python_modules/dagster/dagster/_api/snapshot_schedule.py
python_modules/dagster/dagster/_api/snapshot_sensor.py
python_modules/dagster/dagster/_check/__init__.py
python_modules/dagster/dagster/_config/post_process.py
python_modules/dagster/dagster/_config/validate.py
python_modules/dagster/dagster/_core/execution/plan/external_step.py
python_modules/dagster/dagster/_core/execution/stats.py
python_modules/dagster/dagster/_core/host_representation/repository_location.py
python_modules/dagster/dagster/_core/storage/file_manager.py
python_modules/dagster/dagster/_core/storage/fs_io_manager.py
python_modules/dagster/dagster/_core/storage/memoizable_io_manager.py
python_modules/dagster/dagster/_core/system_config/objects.py
python_modules/dagster/dagster/_daemon/cli/__init__.py
python_modules/dagster/dagster/_grpc/types.py
python_modules/dagster/dagster/_utils/__init__.py
python_modules/dagster/dagster/_utils/calculate_data_time.py
python_modules/dagster/dagster/_utils/log.py
python_modules/dagster/dagster/_utils/yaml_utils.py

more types

---

js_modules/dagit/packages/core/src/nav/useCodeLocationsStatus.tsx

Summary:
The page that explains how it's updating is here.

Updating "Updating XXX.." code location link to go to the right page

---

docs/content/dagster-cloud/getting-started/getting-started-with-hybrid-deployment.mdx

Follow up to #10221 with a clean Git history

[docs ] -  hybrid getting started should clarify CI/CD and docker requirements

---

.buildkite/dagster-buildkite/dagster_buildkite/package_spec.py

docker-compose.yaml, docker-compose.yml, etc.

Also build on yaml changes

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud/resources.py

feat(dbt-cloud): allow account id to be specified as an env var

---

python_modules/dagster/README.md

As the title.
look
https://github.com/dagster-io/dagster/tree/rl/change-slack-link#readme

docs: update Slack link

---

python_modules/dagster/dagster/_core/system_config/composite_descent.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/asset_defs.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/managed/reconciliation.py
python_modules/libraries/dagster-dbt/dagster_dbt/cloud/asset_defs.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py

Summary:
Noticed this on a few assets classes

[easy] Defintion => Definition

---

python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_persistent.py

Summary:
We were sharing a port between two different servers, and terminate() on windows doesn't seem to actually shut down the old server. Use a more blessed cleanup method, and pick a new port before opening the 2nd server.
Test Plan: BK/Azure

windows test fixes for secrets test

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/docs.py
docs/tox.ini

fix(dbt-cloud): add dbt dependency when building API docs

---

js_modules/dagit/packages/core/src/asset-graph/AssetNode.tsx

[dagit] Show “Late” immediately on new assets with freshness policy

---

python_modules/dagster/dagster/_core/definitions/job_definition.py
python_modules/dagster/dagster_tests/core_tests/asset_defs_tests/test_assets_job.py

Fixes logical version bugs:
- "source asset not in job"

fix logical version bugs

---

python_modules/dagster/dagster/_core/storage/captured_log_manager.py
python_modules/dagster/dagster/_core/storage/cloud_storage_compute_log_manager.py
python_modules/dagster/dagster/_core/storage/local_compute_log_manager.py
python_modules/dagster/dagster/_core/storage/noop_compute_log_manager.py
python_modules/dagster/dagster_tests/core_tests/storage_tests/utils/captured_log_manager.py
python_modules/libraries/dagster-aws/dagster_aws/s3/compute_log_manager.py
python_modules/libraries/dagster-azure/dagster_azure/blob/compute_log_manager.py
python_modules/libraries/dagster-azure/dagster_azure/blob/fake_blob_client.py
python_modules/libraries/dagster-gcp/dagster_gcp/gcs/compute_log_manager.py

The log deletion signature was underspecified, since we need to be able to delete based on prefixes in order to do something like run deletion of compute logs
BK

add API for log deletion for both exact match and prefix matches

---

python_modules/dagit/dagit_tests/test_subscriptions.py

skip test_event_log_subscription_chunked on 3.7

---

python_modules/dagster/dagster/_core/storage/cloud_storage_compute_log_manager.py

Also fixes bug where unsubscribing was erroring
BK

stop polling threads that are not actively being subscribed to

---

CHANGES.md

changelog entries for 1.1.0

---

CHANGES.md

updated CHANGES.md to reflect that schema migration is required

---

python_modules/dagster/dagster/_core/definitions/partition.py
python_modules/dagster/dagster_tests/core_tests/partition_tests/test_partition.py

fix serialization of static partitions subsets

---

CHANGES.md

spotted this while i was looking for entries in the changelog

fix lib minor version in changelog

---

examples/tutorial_dbt_dagster/tutorial_template/jaffle_shop/config/profiles.yml

noticed that the content of the profiles.yml is incorrect in the tutorial template. this puts the correct content in

duckdb tutorial - fix profiles.yml

---

CHANGES.md

…ed (#10603)"
This reverts commit f679b3b32e5e63e42a8bf8a065727599fadbc9b4.

1.1 changelog take 3

---

CHANGES.md

1.1.2 changelog

---

python_modules/libraries/dagster-snowflake-pandas/dagster_snowflake_pandas/snowflake_pandas_type_handler.py

Fix typo in docs for snowflake_pandas_io_manager

---

CHANGES.md

fix "changes since" version in changelog

---

python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
python_modules/dagster/dagster_tests/core_tests/definitions_tests/test_asset_reconciliation_sensor.py
python_modules/dagster/dagster_tests/core_tests/definitions_tests/test_time_window_partitions.py

Fixes https://github.com/dagster-io/dagster/issues/9988#issuecomment-1322242611

fix serialization of time window partitions subsets

---

js_modules/dagit/packages/core/src/asset-graph/Utils.tsx
js_modules/dagit/packages/core/src/asset-graph/types/AssetGraphLiveQuery.ts
js_modules/dagit/packages/core/src/asset-graph/types/AssetLatestInfoFragment.ts
js_modules/dagit/packages/core/src/asset-graph/useLiveDataForAssetKeys.tsx
js_modules/dagit/packages/core/src/graphql/schema.graphql
js_modules/dagit/packages/core/src/types/globalTypes.ts
js_modules/dagit/packages/core/src/workspace/types/SingleAssetQuery.ts
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py

This PR doesn't need to ship today, but with the new asset versioning landed, Dagit is no longer using this resolver and I think we can safely remove this code!

Remove remaining references to “upstream changed” calculation + state

---

docs/content/_navigation.json
docs/content/community.mdx
docs/content/getting-started.mdx
docs/content/guides/dagster/enriching-with-software-defined-assets.mdx
docs/content/integrations/airbyte.mdx
docs/content/integrations/dbt-cloud.mdx
docs/content/integrations/fivetran.mdx
docs/next/.versioned_content/_versioned_navigation.json
docs/next/components/JoinSlackButton.tsx
docs/next/yarn.lock

Update docs Slack links to point at dagster.io/slack.
yarn dev, verify that links navigate correctly.

[docs] Update Slack link

---

js_modules/dagit/packages/core/src/assets/AssetPartitions.tsx
js_modules/dagit/packages/core/src/assets/LaunchAssetChoosePartitionsDialog.tsx
js_modules/dagit/packages/core/src/assets/usePartitionDimensionRanges.tsx
js_modules/dagit/packages/core/src/partitions/PartitionRangeWizard.tsx

- Removes Last 50, Last 100 in favor of "Latest" and "All" options
- Pre-select all asset keys not just the last one

[dagit] Minor changes to backfill modal based on user feedback

---

python_modules/dagster/dagster_tests/cli_tests/workspace_tests/autodiscovery_tests/test_autodiscovery.py

Summary & Motivation: While using this file for another reason I noticed typing errors and missing asserts. This fixes that.
Test Plan: BK

Fix typing and missing asserts [fix-typing-in-test-autodiscovery]

---

python_modules/libraries/dagster-duckdb-pandas/dagster_duckdb_pandas_tests/test_type_handler.py
python_modules/libraries/dagster-duckdb-pyspark/dagster_duckdb_pyspark_tests/test_type_handler.py
python_modules/libraries/dagster-duckdb/dagster_duckdb/io_manager.py
python_modules/libraries/dagster-duckdb/dagster_duckdb_tests/test_io_manager.py

[duckdb] don't use BETWEEN for partitions

---

CHANGES.md

changelog for 1.1.3

---

python_modules/dagster/dagster/_core/execution/context/input.py
python_modules/dagster/dagster/_core/execution/context/system.py

We didn't add a job_name oof
Companion pr for internal: https://app.graphite.dev/github/pr/dagster-io/internal/4168

[jog] input_context pipeline_name -> job_name

---

docs/content/integrations.mdx

Add a small bit of color to the integrations page.
read

docs(integrations): fix typo

---

python_modules/dagster/dagster/_core/execution/context/input.py
python_modules/dagster/dagster/_core/execution/context/system.py
python_modules/dagster/dagster/_core/execution/execute_in_process.py
python_modules/dagster/dagster_tests/core_tests/storage_tests/test_memoizable_io_manager.py

We go from creating execution plan twice to once

Add plan to run creation for execute_in_processs

---

python_modules/libraries/dagster-snowflake/dagster_snowflake/snowflake_io_manager.py

[10622](https://github.com/dagster-io/dagster/issues/10622)

add role config to snowflake_io_manager

---

python_modules/automation/automation/docker/images/k8s-example/build_cache/example_project/example_repo/repo.py
python_modules/automation/setup.py

fix automation mypy

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud/asset_defs.py

Basically, just add `TODO:` notes. I know where the integration is going next, but make it explicit for others looking in the source code.
N/A

docs(dbt-cloud): explicitly highlight unimplemented functionality

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud/resources.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud/test_ops.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud/test_resources.py

https://github.com/dagster-io/dagster/pull/7687 and https://github.com/dagster-io/dagster/pull/7888, but for dbt Cloud.
pytest, local

feat(dbt-cloud): cancel dbt cloud run on Dagster job termination

---

python_modules/dagster/dagster_tests/core_tests/system_config_tests/test_system_config.py

Performed using https://github.com/dpeng817/codemods

[jog] convert core_tests/system_config_tests

---

python_modules/dagster-graphql/dagster_graphql/implementation/execution/launch_execution.py
python_modules/dagster-graphql/dagster_graphql/implementation/execution/run_lifecycle.py
python_modules/dagster-graphql/dagster_graphql/implementation/external.py
python_modules/dagster-graphql/dagster_graphql/implementation/utils.py
python_modules/dagster/dagster/_core/definitions/op_definition.py
python_modules/dagster/dagster/_core/errors.py
python_modules/dagster/dagster/_core/execution/api.py
python_modules/dagster/dagster/_core/execution/context/system.py
python_modules/dagster/dagster/_core/execution/plan/active.py
python_modules/dagster/dagster/_core/execution/plan/compute.py
python_modules/dagster/dagster/_core/execution/plan/execute_step.py
python_modules/dagster/dagster/_core/execution/plan/resume_retry.py
python_modules/dagster/dagster/_core/execution/plan/utils.py
python_modules/dagster/dagster/_core/executor/child_process_executor.py
python_modules/dagster/dagster/_core/executor/multiprocess.py
python_modules/dagster/dagster/_core/log_manager.py
python_modules/dagster/dagster/_core/storage/captured_log_manager.py
python_modules/dagster/dagster/_core/workspace/config_schema.py
python_modules/dagster/dagster/_core/workspace/context.py
python_modules/dagster/dagster/_utils/__init__.py
python_modules/dagster/dagster/_utils/interrupts.py

Some type annotation improvements
mypy

typing update in core

---

js_modules/dagit/packages/core/src/app/FallthroughRoot.tsx
js_modules/dagit/packages/core/src/assets/AssetDefinedInMultipleReposNotice.tsx
js_modules/dagit/packages/core/src/assets/AssetView.tsx
js_modules/dagit/packages/core/src/assets/LaunchAssetExecutionButton.tsx
js_modules/dagit/packages/core/src/nav/LeftNavRepositorySection.tsx
js_modules/dagit/packages/core/src/nav/RepoNavItem.tsx
js_modules/dagit/packages/core/src/nav/useCodeLocationsStatus.tsx
js_modules/dagit/packages/core/src/nav/useRepositoryLocationReload.tsx
js_modules/dagit/packages/core/src/overview/OverviewJobsRoot.tsx
js_modules/dagit/packages/core/src/overview/OverviewSchedulesRoot.tsx
js_modules/dagit/packages/core/src/overview/OverviewSensorsRoot.tsx
js_modules/dagit/packages/core/src/pipelines/GraphNotices.tsx
js_modules/dagit/packages/core/src/runs/RunActionButtons.tsx
js_modules/dagit/packages/core/src/workspace/WorkspaceRoot.tsx

Replace more "Workspace" and "Repository" copy throughout Dagit.
Load Dagit, navigate around and verify that strings look correct.

[dagit] Replace more "Workspace" copy in Dagit

---

js_modules/dagit/packages/core/src/configeditor/ConfigEditorDialog.tsx
js_modules/dagit/packages/core/src/overview/OverviewExpansionKey.tsx
js_modules/dagit/packages/core/src/overview/OverviewJobsTable.tsx
js_modules/dagit/packages/core/src/overview/OverviewSchedulesTable.tsx
js_modules/dagit/packages/core/src/overview/OverviewSensorsTable.tsx
js_modules/dagit/packages/core/src/runs/RunTimeline.tsx
js_modules/dagit/packages/core/src/ui/useRepoExpansionState.test.tsx
js_modules/dagit/packages/core/src/ui/useRepoExpansionState.tsx

Clean up some todos I had left for myself over the last couple months.
Buildkite. Verify that expand/collapse stored state works correctly in Overview tabs.

[dagit] Clean up some of my todos

---

python_modules/dagster/dagster/_core/test_utils.py

Fix run launcher lint

---

python_modules/dagster/dagster/_core/host_representation/repository_location.py
python_modules/dagster/dagster/_grpc/__generated__/api_pb2.py
python_modules/dagster/dagster/_grpc/__generated__/api_pb2_grpc.py
python_modules/dagster/dagster/_grpc/client.py
python_modules/dagster/dagster/_grpc/protos/api.proto
python_modules/dagster/dagster/_grpc/server.py
python_modules/dagster/dagster/_grpc/types.py
python_modules/dagster/dagster_tests/api_tests/api_tests_repo.py
python_modules/dagster/dagster_tests/api_tests/test_api_get_current_runs.py
python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_repository.py

Expose the self._executions map over grpc
unit tests

Get current runs on grpc server

---

.github/ISSUE_TEMPLATE/config.yml
python_modules/dagster/README.md
python_modules/dagster/setup.py

Prepare for https://dagster.io/newsletter-signup to be publicized!
eyes

docs: add links to subscribe to newsletter

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_instigators.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py
python_modules/dagster/dagster/_core/host_representation/external.py

observed some performance issues on large repositories with recreating these objects repeatedly 
before & after profiler results:

memoize ExternalRepository getters

---

python_modules/libraries/dagster-msteams/dagster_msteams/resources.py

no more pipelines or solids
code ran locally

fix msteams resource docstring

---

python_modules/dagster-graphql/dagster_graphql/schema/instigation.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_scheduler.py

same as #10632 just in another spot
added test

[graphql] coerce cronSchedule to str 2

---

python_modules/libraries/dagster-managed-elements/dagster_managed_elements/cli.py
python_modules/libraries/dagster-managed-elements/dagster_managed_elements_tests/test_cli.py
python_modules/libraries/dagster-managed-elements/setup.py

Some improvements to the CLI output for managed Airbyte, including removing mention of managed elements from the CLI helptext + adding a loading spinner while a check/apply is happening.

[dagster-airbyte] Improve CLI output for dagster-airbyte check/apply

---

python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud/test_asset_defs.py

test(dbt-cloud): move resources into fixtures

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud/asset_defs.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud/test_asset_defs.py

Resolves https://github.com/dagster-io/dagster/issues/10662.
pytest

feat(dbt-cloud): allow group name to be configurable

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud/asset_defs.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud/test_asset_defs.py

feat(dbt-cloud): allow asset key to be configurable

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud/asset_defs.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud/test_asset_defs.py

The dbt Cloud equivalent of https://github.com/dagster-io/dagster/pull/8725.
pytest
https://user-images.githubusercontent.com/16431325/204921139-c684d87b-f8f3-4dc5-8589-ab154022e353.mov

feat(dbt-cloud): allow partitions on dbt cloud models

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud/asset_defs.py

We should be querying the run artifacts from the build/run step in the dbt Cloud job. 
Otherwise, in the instance that the dbt Cloud job is generating docs, we query the run results from this generate docs step. This erroneously tells us that all the models were materialized successfully, when in fact, this may not be the case since filter options could be passed to the run/build step.
existing pytest?

fix(dbt-cloud): query run artifacts from correct step on materialization

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud/asset_defs.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud/test_asset_defs.py

Rather than attempting to merge the dynamic variables from our partition mapping to potential existing variables in the dbt Cloud job, just disallow them.
If `--vars` exists on the dbt Cloud job, then the variables are static, since they are defined in the UI. And so they can be refactored to `dbt_project.yml` without any loss in functionality. So, raise an error to recommend that refactor.
pytest

feat(dbt-cloud): raise error on jobs with `--vars` argument

---

CHANGES.md

Changelog 1.1.4

---

docs/content/concepts/partitions-schedules-sensors/sensors.mdx
examples/docs_snippets/docs_snippets/concepts/partitions_schedules_sensors/sensors/sensors.py

Need to reference something in the sensor docs about logging.
inspection

add sensor logging docs

---

python_modules/dagster/dagster/_core/execution/context/hook.py
python_modules/dagster/dagster/_core/execution/plan/compute.py
python_modules/dagster/dagster/_core/execution/plan/execute_step.py
python_modules/dagster/dagster/_core/execution/plan/inputs.py
python_modules/dagster/dagster/_core/execution/plan/utils.py
python_modules/dagster/dagster_tests/execution_tests/test_retries.py

resolves https://github.com/dagster-io/dagster/issues/10730
added test

return pre retry policy exception in HookContext.op_exception

---

.buildkite/dagster-buildkite/dagster_buildkite/utils.py

Add johann to BUILD_CREATOR_EMAIL_TO_SLACK_CHANNEL_MAP

---

docs/content/concepts/partitions-schedules-sensors/asset-sensors.mdx
docs/sphinx/sections/api/apidocs/schedules-sensors.rst
examples/docs_snippets/docs_snippets/concepts/partitions_schedules_sensors/sensors/asset_sensors.py
python_modules/dagster/dagster/__init__.py
python_modules/dagster/dagster/_core/definitions/asset_reconciliation_sensor.py
python_modules/dagster/dagster/_core/definitions/freshness_policy_sensor_definition.py

Add some freshness-policy related stuff to API docs, add extra information on the freshness_policy_sensor to the sensors page, explain freshness-based scheduling.

[freshness-policies] Improved docs coverage

---

CHANGES.md

Summary:
Changelog for an OSS release that includes the partitions page fix.

1.1.5 hotfix changelog

---

python_modules/dagster/dagster/_core/execution/execute_in_process.py
python_modules/dagster/dagster/_core/storage/event_log/in_memory.py
python_modules/dagster/dagster/_core/storage/runs/in_memory.py
python_modules/dagster/dagster_tests/cli_tests/test_asset_commands.py
python_modules/dagster/dagster_tests/core_tests/storage_tests/test_local_instance.py

Getting errors for ephemeral instance construction within a threaded context (sensor evaluation).
BK

clean up connections for in-memory storage implementations

---

python_modules/dagster/dagster_tests/core_tests/config_types_tests/evaluator_tests/test_composite_descent.py
python_modules/dagster/dagster_tests/core_tests/config_types_tests/evaluator_tests/test_config_mappings.py
python_modules/dagster/dagster_tests/core_tests/config_types_tests/test_config_default_required.py
python_modules/dagster/dagster_tests/core_tests/config_types_tests/test_config_enums.py
python_modules/dagster/dagster_tests/core_tests/config_types_tests/test_config_schema.py
python_modules/dagster/dagster_tests/core_tests/config_types_tests/test_config_spec.py
python_modules/dagster/dagster_tests/core_tests/config_types_tests/test_config_type_system.py
python_modules/dagster/dagster_tests/core_tests/config_types_tests/test_error_messages.py
python_modules/dagster/dagster_tests/core_tests/config_types_tests/test_type_printer.py

Converted using https://github.com/dpeng817/codemods

[jog] core_tests/config_types_tests

---

python_modules/libraries/dagster-airflow/dagster_airflow/dagster_job_factory.py
python_modules/libraries/dagster-airflow/dagster_airflow/dagster_pipeline_factory.py

[dagster-airflow] use named params and rename use_emphemeral_airflow_db

---

docs/README.md

Adds a troubleshooting section to the docs README to document common errors
Note: my VSCode auto-removes trailing whitespace, so there are a couple line changes in this PR that are just the removal of a space

add troubleshooting section to docs readme

---

python_modules/dagster-graphql/dagster_graphql/implementation/loader.py

should have been caught in #10798 - use better methods for ensuring definitions being fetched exist 
profiling locally with `py-spy`

[graphql] use more efficient defense checks

---

python_modules/libraries/dagstermill/dagstermill/examples/notebooks/yield_3.ipynb

fixes yield 3 test from my very dumb error

[dagstermill] fix failing test

---

docs/content/deployment/guides/docker.mdx

You missed an `in` in the sentence. Quick fix.

minor typo correct in the docs

---

python_modules/dagster-graphql/dagster_graphql/implementation/execution/__init__.py
python_modules/dagster-graphql/dagster_graphql/schema/external.py
python_modules/dagster/dagster/_core/host_representation/grpc_server_state_subscriber.py

typing fixes that would have prevented #10921
mypy

[graphql] misc typing

---

integration_tests/test_suites/daemon-test-suite/auto_run_reexecution_tests/test_auto_run_reexecution.py
integration_tests/test_suites/daemon-test-suite/auto_run_reexecution_tests/utils.py
python_modules/dagster/dagster/_core/host_representation/__init__.py
python_modules/dagster/dagster/_core/host_representation/external.py
python_modules/dagster/dagster/_core/host_representation/handle.py
python_modules/dagster/dagster/_core/host_representation/repository_location.py
python_modules/dagster/dagster/_core/host_representation/selector.py
python_modules/dagster/dagster_tests/api_tests/test_api_get_current_runs.py
python_modules/dagster/dagster_tests/api_tests/test_api_launch_run.py
python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_execution_plan.py
python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_pipeline.py
python_modules/dagster/dagster_tests/api_tests/utils.py
python_modules/dagster/dagster_tests/cli_tests/test_api_commands.py
python_modules/dagster/dagster_tests/daemon_tests/test_queued_run_coordinator_daemon.py

Repo-wide rename PipelineHandle -> JobHandle. Also updated relevant local variables.
Existing BK tests.

rename PipelineHandle -> JobHandle

---

python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/libraries/dagster-postgres/dagster_postgres/event_log/event_log.py
python_modules/libraries/dagster-postgres/dagster_postgres/run_storage/run_storage.py
python_modules/libraries/dagster-postgres/dagster_postgres/schedule_storage/schedule_storage.py
python_modules/libraries/dagster-postgres/dagster_postgres_tests/test_instance.py

resolves https://github.com/dagster-io/dagster/issues/10913
added test

[postgres] preserve existing options when setting connect_args

---

python_modules/dagster/dagster_tests/execution_tests/execution_plan_tests/test_execution_plan.py
python_modules/dagster/dagster_tests/execution_tests/execution_plan_tests/test_execution_plan_composite.py
python_modules/dagster/dagster_tests/execution_tests/execution_plan_tests/test_execution_plan_reexecution.py
python_modules/dagster/dagster_tests/execution_tests/execution_plan_tests/test_execution_plan_subset.py
python_modules/dagster/dagster_tests/execution_tests/execution_plan_tests/test_external_step.py
python_modules/dagster/dagster_tests/execution_tests/execution_plan_tests/test_host_run_worker.py

Converted using https://github.com/dpeng817/codemods

[jog] execution_tests/execution_plan_tests

---

docs/next/.versioned_content/_versioned_navigation.json

files have been successfully uploaded to s3, for example https://docs.dagster.io/getting-started/hello-dagster is live but it's not showing up in the left nav.
this PR is the last step of a manual doc release, so the nav changes can show up in 1.1.5 version
nav changes show up in preview's 1.1.5: https://dagster-git-yuhan-12-06-backfill115versionednav-bc02ba-elementl.vercel.app/getting-started

backfill 1.1.5 versioned_navigation.json

---

python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py

Converted using https://github.com/dpeng817/codemods

[jog] scheduler_tests

---

docs/content/guides/dagster/dagster_type_factories.mdx

Motivated by https://github.com/dagster-io/dagster/discussions/10333

update to dagster_type_factories guide to mention pandera

---

python_modules/dagster/dagster_tests/core_tests/asset_defs_tests/test_decorators.py
python_modules/dagster/dagster_tests/core_tests/test_solid_invocation.py

Motivated by this issue: https://github.com/dagster-io/dagster/issues/10659

add tests for asset and op decorators with kwargs and context

---

js_modules/dagit/packages/core/src/runs/RunMetadataProvider.tsx

This PR fixes a small regression introduced in https://github.com/dagster-io/dagster/commit/483c2765fb8c1c2912a4f1981847b8cb7816b62a#diff-6df197f8e673ed16c9baad8efe0f09170d68654863a10f97e038bec6ad9a07f6L280 
When we see marker log messages that have a stepKey, we want to build the step state object and then apply the marker to the step rather than adding it to the "global" marker list which is used for job-level setup / resource init etc.
This makes the resource init markers appear on the same row as the step box rather than being pinned to the top of the gantt chart:
Before:
After:
I tested these changes visually and also added log messages to our storybook so you can see it there, since not all runs create these messages:

[dagit] Fix Gantt chart rendering of per-step resource init log messages

---

CHANGES.md

1.1.6 Changelog

---

js_modules/dagit/packages/core/src/workspace/CodeLocationMenu.tsx
js_modules/dagit/packages/core/src/workspace/CodeLocationSource.tsx

Got a few components to export for use in Cloud.
Load Dagit, sanity check that Code Locations table looks correct. Load Cloud, verify that I can use the components, pass TS/lint/Jest.

[dagit] Export a few Code Location components for Cloud

---

python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_persistent.py

Summary & Motivation: IS_WINDOWS was not defined
Test Plan: BK

Fix test_persistent

---

.github/dependabot.yml

Ensure that dependabot pull requests are reviewed.
Docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#reviewers
N/A

chore: auto-assign dependabot pull requests

---

js_modules/dagit/packages/core/src/assets/LaunchAssetChoosePartitionsDialog.tsx

This PR is a fix for the issue reported in https://dagster.slack.com/archives/C01U954MEER/p1670433862246309.
When you select multiple assets in the graph and open the backfill modal, there's a third possible state ("partially materialized") for each partition. That state wasn't selectable via the "Completed (100)", "Missing (100)" checkboxes, so you have been unable to re-run partially materialized partitions.
I've fixed this by grouping "partial" partitions into the "missing" category for the checkboxes. I think this matches the user expectation that checking "missing" should "materialize these assets for any partitions where one or more of them are missing". We could alternatively add a "Partially Missing" checkbox and let you toggle inclusion of these separately.
I had missed this …

[dagit] With multiple assets selected, backfill “missing” should include partially materialized partitions

---

examples/quickstart_etl/pyproject.toml
examples/quickstart_etl/quickstart_etl/__init__.py
examples/quickstart_etl/quickstart_etl/repository.py
examples/quickstart_etl/workspace.yaml

- `@repository` -> `Definitions`
- `workspace.yaml` -> `pyproject.toml`
`dagit` loads

convert-examples 7.1/ quickstart_etl workspace->pyproject, repo->defs

---

examples/with_great_expectations/with_great_expectations/__init__.py
examples/with_great_expectations/with_great_expectations/repository.py

`repository.py` -> `__init__.py`
unit + `dagit` loads

convert-examples 8.2/ with_great_expectations file rename

---

docs/sphinx/sections/api/apidocs/execution.rst
examples/assets_pandas_pyspark/assets_pandas_pyspark_tests/test_assets.py
python_modules/dagster/dagster/__init__.py
python_modules/dagster/dagster/_core/test_utils.py

Add instance for test to top level API

---

examples/tutorial_notebook_assets/tutorial_template/assets/__init__.py

accidentally uncommented code blocks that need to be commented in the example

[example] recomment code in dagstermill tutorial

---

python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py
python_modules/libraries/dagster-aws/dagster_aws/ecs/tasks.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/test_launching.py
python_modules/libraries/dagster-celery-k8s/dagster_celery_k8s/executor.py
python_modules/libraries/dagster-celery-k8s/dagster_celery_k8s/launcher.py
python_modules/libraries/dagster-docker/dagster_docker/docker_executor.py
python_modules/libraries/dagster-docker/dagster_docker/docker_run_launcher.py
python_modules/libraries/dagster-k8s/dagster_k8s/executor.py
python_modules/libraries/dagster-k8s/dagster_k8s/job.py
python_modules/libraries/dagster-k8s/dagster_k8s/launcher.py
python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_launcher.py

similar to the labels, add `DAGSTER_RUN_` env vars to environment for containerized executors and launchers 
added test, can add some more

set DAGSTER_RUN_JOB_NAME env var

---

python_modules/dagster/dagster/_daemon/run_coordinator/queued_run_coordinator_daemon.py

slight refactor of run queue daemon
bk

run queue daemon refactor

---

python_modules/dagster/dagster/_core/definitions/asset_reconciliation_sensor.py
python_modules/dagster/dagster_tests/core_tests/definitions_tests/test_asset_reconciliation_sensor.py

If asset1.partition2 depends on asset1.partition1, avoid launching runs for asset1.partition2 until asset1.partition1 is reconciled.

handle self-dependencies in reconciliation sensor

---

python_modules/dagster/dagster/_core/executor/multiprocess.py
python_modules/dagster/dagster_tests/core_tests/definitions_tests/test_executor_definition.py

Allow overriding the default max_concurrent for the default executor via env var

---

docs/content/integrations/snowflake/using-snowflake-with-dagster.mdx
examples/docs_snippets/docs_snippets/integrations/snowflake/configuration.py
examples/docs_snippets/docs_snippets/integrations/snowflake/full_example.py

Converts snowflake guide to use Definitions API
vercel preview https://dagster-git-jamie-definitions-snowflake-elementl.vercel.app/integrations/snowflake/using-snowflake-with-dagster

[docs] [definitions] convert snowflake guide to definitions

---

examples/assets_pandas_type_metadata/assets_pandas_type_metadata/__init__.py
examples/assets_pandas_type_metadata/assets_pandas_type_metadata/repository.py

exactly the same as https://github.com/dagster-io/dagster/pull/11070 which got approved
(i messed up the merging of https://github.com/dagster-io/dagster/pull/11070 which didn't land to master)

convert-examples 4.2/ assets_pandas_type_metadata repository.py -> __init__.py (new)

---

examples/project_fully_featured/project_fully_featured/__init__.py
examples/project_fully_featured/project_fully_featured/repository.py
examples/project_fully_featured/project_fully_featured_tests/test_defs.py
examples/project_fully_featured/pyproject.toml
examples/project_fully_featured/workspace.yaml

- `@repository` -> `Definitions`
- workspace.yaml -> pyproject.toml
- `with_resources` -> `resources` key to `Definitions`
- unit
- `dagit` loads locally

convert-examples 11.1/ project_fully_featured defs, pyproject, no with_resources

---

python_modules/dagster/dagster/_daemon/run_coordinator/queued_run_coordinator_daemon.py

so these can be identified easily
existing tests

add thread name prefix to run dequeue workers

---

helm/dagster/schema/schema/charts/dagster/subschema/run_launcher.py
helm/dagster/schema/schema_tests/test_instance.py
helm/dagster/templates/helpers/instance/_run-launcher.tpl
helm/dagster/values.schema.json
helm/dagster/values.yaml
python_modules/libraries/dagster-k8s/dagster_k8s/container_context.py
python_modules/libraries/dagster-k8s/dagster_k8s/job.py
python_modules/libraries/dagster-k8s/dagster_k8s/launcher.py
python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_launcher.py

to allow recitation of the The Sacred Rites Of Debugging
```
securityContext:
capabilities:
add:
- SYS_PTRACE
```
or other security settings
added tests

[k8s launcher] security context

---

.buildkite/dagster-buildkite/dagster_buildkite/python_packages.py

Trigger builds when .ini files change

---

docs/content/concepts/code-locations/workspace-files.mdx
docs/content/concepts/dagit/dagit.mdx

This PR fixes some racy links that arose as part of the many `Definitions` changes.

[docs] - Fix links

---

CHANGES.md

1.1.7 Changelog

---

docs/content/guides/dagster/scheduling-assets.mdx
examples/docs_snippets/docs_snippets/guides/dagster/scheduling/freshness_1.py
examples/docs_snippets/docs_snippets/guides/dagster/scheduling/freshness_2.py
examples/docs_snippets/docs_snippets/guides/dagster/scheduling/freshness_3.py
examples/docs_snippets/docs_snippets/guides/dagster/scheduling/freshness_4a.py
examples/docs_snippets/docs_snippets/guides/dagster/scheduling/freshness_4b.py
examples/docs_snippets/docs_snippets/guides/dagster/scheduling/freshness_5a.py
examples/docs_snippets/docs_snippets/guides/dagster/scheduling/freshness_5b.py

Summary & Motivation: We are updating all content to refer to Definitions rather than @repository
Test Plan: Read

Update declarative scheduling guide to include Definitions

---

python_modules/dagster/dagster/_grpc/server.py

daemons were all set but found this when searching all thread pools
existing tests

add thread name prefix to grpc server

---

integration_tests/test_suites/backcompat-test-suite/buildkite_deps.txt
integration_tests/test_suites/celery-k8s-test-suite/buildkite_deps.txt
integration_tests/test_suites/daemon-test-suite/buildkite_deps.txt
integration_tests/test_suites/k8s-test-suite/buildkite_deps.txt

This is a follow up to https://github.com/dagster-io/dagster/pull/11025 because I forgot to add the renamed files.

Fixup rename of requirements.txt -> buildkite_deps.txt

---

python_modules/dagster/dagster/_core/definitions/partition.py
python_modules/dagster/dagster/_core/definitions/time_window_partition_mapping.py
python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
python_modules/dagster/dagster/_core/execution/context/input.py
python_modules/dagster/dagster_tests/core_tests/definitions_tests/test_time_window_partitions.py
python_modules/dagster/dagster_tests/core_tests/partition_tests/test_partition.py

This will be used in partition-mapped asset backfills.

support in and len on PartitionsSubsets

---

docs/content/getting-started/releases.mdx

Fix typo in title

---

python_modules/libraries/dagster-snowflake/dagster_snowflake/resources.py

Summary:
https://github.com/dagster-io/dagster/pull/10496/files changed an opt_dict_param to an inst_param
Test Plan: The rare "inspection", although we could add a unit test if we really want to

Fix regression with passing in None to snowflake resource

---

python_modules/libraries/dagster-dbt/setup.py

pin dbt rpc < 0.3.0

---

python_modules/dagster/dagster/_core/run_coordinator/queued_run_coordinator.py
python_modules/dagster/dagster_tests/core_tests/run_coordinator_tests/test_queued_run_coordinator.py

fix dequeue_num_workers setting

---

python_modules/dagster/dagster/_core/definitions/asset_selection.py

add assets example to AssetSelection apidoc

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud/asset_defs.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud/test_asset_defs.py

feat(dbt-cloud): add Dagster run id to dbt Cloud run

---

python_modules/dagster/dagster/_core/definitions/asset_reconciliation_sensor.py
python_modules/dagster/dagster_tests/definitions_tests/test_asset_reconciliation_sensor.py

only reconcile multi-assets if all parents are reconciled

---

js_modules/dagit/packages/core/src/asset-graph/AssetNode.stories.tsx

fix tslint

---

examples/project_fully_featured/project_fully_featured/resources/__init__.py

Minor cleanup of project_fully_featured. No longer need to use hardcoded_resource
BK

Can remove hardcoded_resource from project_fully_featured because of Definitions

---

python_modules/dagster/dagster_tests/cli_tests/snapshots/snap_test_config_scaffolder.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/snapshots/snap_test_active_data.py
python_modules/dagster/dagster_tests/core_tests/snap_tests/snapshots/snap_test_execution_plan.py

I was prototyping in the config system and some changes to snapshot tests turned up. This seemed like an opportune time to rerun the entire dagster test in snapshot update mode.
BK

Rerun dagster_tests with --snapshot-update

---

python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py

I thought I was going to have to change code in order to support this use case (binding an asset to with_resources) before passing into Definitions but I was pleasantly surprised to see that this was already supported. Added test case I assumed would have failed.
BK

Add test case for binding assets before passing to Definitions

---

docs/content/integrations/airflow/from-airflow-to-dagster.mdx

applying changes for erin's review in https://github.com/dagster-io/dagster/pull/10923#issuecomment-1351744322

[dagster-airflow] from airflow to dagster guide updates

---

python_modules/dagster-graphql/dagster_graphql/test/utils.py

recreating this every call showed up in the profiler results of test run
bk

[graphql test] share schema instance

---

examples/project_fully_featured/project_fully_featured/resources/__init__.py
examples/project_fully_featured/project_fully_featured/resources/hn_resource.py
examples/project_fully_featured/project_fully_featured_tests/test_core.py

I'm protoyping a bunch of resource and config API changes on the project fully featured. While doing that I'm discovering some easy wins that we can do now
BK

Use bare objects for the hacker news resources

---

examples/project_fully_featured/project_fully_featured/resources/__init__.py
examples/project_fully_featured/project_fully_featured/resources/hn_resource.py
examples/project_fully_featured/project_fully_featured/resources/snowflake_io_manager.py
examples/project_fully_featured/project_fully_featured_tests/test_core.py
examples/project_fully_featured/project_fully_featured_tests/test_resources/test_snowflake_io_manager.py

Continuing some simplification work. In this case we can use a bare I/O manager instance instead of the factory decorator
BK

Use bare I/O manager in fully featured

---

python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/test_launching.py

Until we've made them less flaky.

Skip race condition tests

---

docs/content/concepts/ops-jobs-graphs/op-retries.mdx

Update op-retries.mdx - no solid

---

docs/content/integrations/airbyte.mdx
examples/docs_snippets/docs_snippets/integrations/airbyte/airbyte.py
examples/docs_snippets/docs_snippets_tests/integrations_tests/test_airbyte.py

https://www.notion.so/dagster/docs-Definitions-Update-Airbyte-guide-857164fe25b4418baddd63f2bc6681bb
unit + 👀

[docs] airbyte guide repository -> definitions

---

docs/content/integrations/airbyte.mdx
docs/content/integrations/fivetran.mdx
examples/docs_snippets/docs_snippets/integrations/airbyte/airbyte.py
examples/docs_snippets/docs_snippets/integrations/fivetran/fivetran.py
examples/docs_snippets/docs_snippets_tests/integrations_tests/test_airbyte.py
examples/docs_snippets/docs_snippets_tests/integrations_tests/test_fivetran.py

https://www.notion.so/dagster/docs-Definitions-Update-Fivetran-guide-962ac9d2ff8746e1b6c13e54bf721e79
unit + 👀

[docs] fivetran guide repository -> definitions

---

docs/content/integrations/dbt/reference.mdx
examples/docs_snippets/docs_snippets/integrations/dbt/dbt.py
examples/docs_snippets/docs_snippets_tests/integrations_tests/test_dbt.py
examples/docs_snippets/setup.py

https://www.notion.so/dagster/docs-Definitions-Update-dbt-reference-bd5070fb335344e4848e4c9294dd1690

[docs] dbt guide repository -> definitions

---

docs/content/integrations/dbt-cloud.mdx
examples/docs_snippets/docs_snippets/integrations/dbt/dbt_cloud.py
examples/docs_snippets/docs_snippets_tests/integrations_tests/test_dbt.py

https://www.notion.so/dagster/docs-Definitions-Update-dbt-Cloud-guide-c496f04c6069407fb445d33b382766fe
unit + eyes

[docs] dbt cloud guide repository -> definitions

---

python_modules/dagster/dagster/_core/definitions/metadata/__init__.py
python_modules/dagster/dagster/_core/execution/context/output.py
python_modules/dagster/dagster_tests/storage_tests/test_io_manager.py

accrete metadata with multiple calls to add_output_metadata

---

docs/content/deployment/executors.mdx
examples/docs_snippets/docs_snippets/deploying/executors/executors.py
examples/docs_snippets/docs_snippets_tests/deploying_tests/test_executor_examples.py

This PR updates the Executor docs for the new `Definitions` world.

[docs] - [definitions] - Update Executors docs

---

python_modules/dagster/dagster/_core/definitions/unresolved_asset_job_definition.py

[apidoc] define_asset_job repository -> Definitions

---

js_modules/dagit/packages/core/src/nav/useCodeLocationsStatus.tsx

Take 2 of https://github.com/dagster-io/dagster/pull/11100.
Rather than recalculate the current set of updates in a useEffect (prone to infinite render chains), this sets state within a query callback, but only if the payload has logically changed (by comparing timestamps).
Randomly cycled through a set of values for location timestamps, and saw that only values higher than the known max triggered toast/refreshes

Ignore stale timestamps from code location updates

---

python_modules/dagster/dagster/_core/definitions/asset_graph.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/host_representation/external_data.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py
python_modules/dagster/dagster_tests/core_tests/host_representation_tests/test_external_data.py

Needed for partition-mapped asset backfills, which execute in a daemon.

AssetGraph.from_external_assets().get_required_multi_asset_keys()

---

python_modules/dagster/dagster/_core/execution/context/input.py
python_modules/dagster/dagster/_core/execution/context/system.py
python_modules/dagster/dagster/_core/storage/asset_value_loader.py
python_modules/dagster/dagster_tests/storage_tests/test_io_manager.py

This is needed to implement certain IOManagers and it not being there was an oversight.
Resolves https://github.com/dagster-io/dagster/issues/11016 
BK

Add instance property to InputContext

---

python_modules/dagster/README.md

https://github.com/dagster-io/dagster/pull/11326#issuecomment-1362305684
View Preview in PR.

Revert "Use dark mode logo on README.md (#11326)"

---

python_modules/dagster/dagster_tests/storage_tests/test_local_instance.py

Disabling another flakey test. Tracking here: https://linear.app/elementl/issue/CORE-86/test-threaded-ephemeral-instance-flakes
BK

skip test_threaded_ephemeral_instance

---

python_modules/dagster/dagster/_config/structured_config.py
python_modules/dagster/dagster_tests/core_tests/resource_tests/test_struct_config_resources.py

Builds upon #11321, adding a utility wrapper which can be used to convert traditional function-style resources into structured config-based resources. This allows us to gradually adopt structured config-based resources.
For example, if we have the following `@resource`-created resource:
```python
WriterFunction = Callable[[str], None]
@resource(config_schema={"prefix": str})
def writer_resource(context):
prefix = context.resource_config["prefix"]
def output(text: str) -> None:
out_txt.append(f"{prefix}{text}")
return output
@op
def hello_world_op(writer: ResourceOutput[WriterFunction]):
writer("hello, world!")
@job(resource_defs={"writer": writer_resource.configured({"prefix": "greeting: "})})
def prefix_job():
hello_world_op()
```
We can wrap and use it:
```python
class …
```

[structured config] Add traditional resource wrapper base class

---

python_modules/dagster/dagster/_core/definitions/external_asset_graph.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_external_asset_graph.py

branch-name: external-asset-graph-bugs

fix some bugs in ExternalAssetGraph

---

js_modules/dagit/packages/eslint-config/CHANGES.md
js_modules/dagit/packages/eslint-config/package.json

Looks like we've already published a 1.0.6. Bumping to 1.0.7.
None.

[dagster-io/eslint-config] v1.0.7

---

js_modules/dagit/packages/core/src/assets/AssetActionMenu.tsx
js_modules/dagit/packages/core/src/assets/LaunchAssetExecutionButton.tsx
js_modules/dagit/packages/core/src/launchpad/LaunchpadHooksContext.tsx

In cloud we want to do some custom things for the button like showing a product tour:

Add Materialize Button hook

---

python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py

branch-name: fix-time-window-partitions-in

fix __contains__ of TimeWindowPartitionsSubset

---

docs/content/concepts/partitions-schedules-sensors/partitions.mdx

fix typo on partitions concepts page

---

js_modules/dagit/packages/ui/src/components/configeditor/codemirror-yaml/mode.tsx

Remove stray console.log

---

python_modules/dagster/dagster/_core/definitions/asset_layer.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/execution/execute_in_process_result.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_materialize_to_memory.py

Inspired by this issue: https://github.com/dagster-io/dagster/issues/11341

ExecuteInProcessResult.asset_value

---

docs/content/dagster-cloud/developing-testing/code-locations.mdx

Summary:
Some missing YAML here

Fix malformed dagster_cloud.yaml in code location docs

---

python_modules/libraries/dagster-databricks/dagster_databricks/databricks_pyspark_step_launcher.py

https://github.com/dagster-io/dagster/issues/11413

[dagster-databricks] handle empty responses

---

python_modules/dagster/dagster/_core/storage/pipeline_run.py
python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py
python_modules/dagster/dagster_tests/storage_tests/utils/run_storage.py

For some internal stat keeping, we want to track runs stuck in a starting state that haven't been updated in the last X seconds.
BK

add run filter for updated before

---

docs/content/integrations/dbt/using-dbt-with-dagster/part-one.mdx

fix(docs): format docs

---

python_modules/dagster/dagster/_core/execution/asset_backfill.py

supply solid_selection to fix submitting runs from pure asset backfills

---

docs/content/integrations/dbt/using-dbt-with-dagster/part-one.mdx

fix(docs): run mdx-format again

---

python_modules/dagster/dagster/_core/instance/__init__.py

This adds typechecks and typehints to solids_to_execute and solid_selection. The most valuable part of this PR is the comment associated with that, as this is the result of a lot of sleuthing:
```
```

Tighten solids_to_execute and solid_selection invariant

---

python_modules/dagster/dagster/_core/instance/__init__.py

This adds typechecks/hints for `asset_selection` parameter and then ensures that `solid_selection` and `solids_to_execute` is None, since that is the current behavior of all callsites.
Relevant comment:
```
#
````
BK

Add invariant for asset_selection

---

python_modules/dagster/dagster/_core/instance/__init__.py

A straightforward set of typechecks that yielded no unexpected invariants or behavior.
BK

Typehint pipeline_name, run_id, and mode

---

python_modules/dagster/dagster/_core/instance/__init__.py

Add typehints and checks for `pipeline_snapshot` and `parent_pipeline_snapshot`. Also ensure that `pipeline_snapshot` is set IF `parent_pipeline_snapshot` is set. 
BK

Add typehints to snapshot arguments to create_run

---

python_modules/dagster/dagster/_core/instance/__init__.py

This adds typechecks, hints, and invariants are the parameter related to re-execution.
A couple of notes. First around `step_keys_to_execute`
```
```
Next around `parent_run_id` and `root_run_id`:
```
if root_run_id or parent_run_id:
check.invariant(
root_run_id and parent_run_id,
"If root_run_id or parent_run_id is passed, this is a re-execution scenario and "
"root_run_id and parent_run_id must both be passed."
)
```
BK

Typehint and do invariants for root_run_id, parent_run_id, step_keys_to_execute and execution_plan_snapshot

---

python_modules/dagster/dagster/_core/instance/__init__.py

Typehint and check the tags and status parameters to create_run.
Tags in callsites comes from sources that are both Mapping[str, str] and Mapping[str, object]. Doing a validation pass to ensure that they are in fact str to str.
Status was relying on the fact that all callsites to create_run_for_pipeline were not respecting the typehint on its status parameter and were passing the enum instead.
BK

Typehint and validate tags and status params to create_run

---

python_modules/dagster/dagster/_core/definitions/asset_layer.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/dependency.py
python_modules/dagster/dagster/_core/execution/context/system.py
python_modules/dagster/dagster/_core/host_representation/external_data.py
python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_asset_partition_mappings.py

Fixes https://github.com/dagster-io/dagster/issues/11420

Fix getting partition mappings when asset dependencies are resolved

---

python_modules/dagster/dagster/_core/definitions/asset_selection.py

Inspired by https://dagster.slack.com/archives/C01U5LFUZJS/p1672760290006609?thread_ts=1671157035.783759&cid=C01U5LFUZJS

docstring examples for AssetSelection.keys

---

CHANGES.md

Preview: https://github.com/dagster-io/dagster/blob/40d758cf45fc82056233d1150c5383db62ca0c1e/CHANGES.md

Changelog 1.1.8

---

docs/content/integrations/airflow/from-airflow-to-dagster.mdx
examples/docs_snippets/docs_snippets/integrations/airflow/tutorial_rewrite_complete.py
examples/docs_snippets/docs_snippets/integrations/airflow/tutorial_rewrite_dagster.py

I was going thru the Airflow guide and noticed it was still on repositories, so I migrated it.
Will review vercel preview

Migrate airflow guide to definitions

---

.github/ISSUE_TEMPLATE/config.yml
python_modules/dagster/README.md

docs: add links to follow LinkedIn page

---

docs/next/public/googlef19442cd2a4784da.html

This PR adds an `.html` verification file to the docs, for Google Search Console.

[docs] - Add GSC site verification file

---

CHANGES.md

Changelog for 1.1.9 hotfix, including #11546 and #11551

[changelog] 1.1.9

---

pyproject.toml
python_modules/automation/automation/docker/dagster_docker.py
python_modules/dagster/dagster/_core/execution/plan/inputs.py
python_modules/dagster/dagster/_utils/__init__.py
python_modules/libraries/dagster-gcp/dagster_gcp/bigquery/types.py

Ruff docstrings D210 (NoSurrondingWhitespace)

---

CHANGES.md

implements suggestions from #11556

[changelog] 1.1.9 round 2

---

js_modules/dagit/packages/core/src/runs/LogsToolbar.tsx

Use localStorage to track the preference between `stdout` and `stderr` for which tab the user will see first when switching to compute logs on a Run page.
- With no localStorage value set, `stdout` will be the default.
- If the user clicks on either `stdout` or `stderr` tab, track that value.
- If the user then navigates to a run and clicks the button to view compute logs, that tab will be the one that shows first.
- If the user changes tabs, update the tracked value.
- If the user navigates to a run with a `logType` query param (e.g. `logType=stderr`), show that compute log tab but do not set the user's preference locally.
Verify the bullet points above when viewing a run. Load a run, switch to compute logs. Verify that `stdout` is the default. Click `stderr`, reload the page with no …

[dagit] Track most recent preference for computed log type view

---

integration_tests/python_modules/dagster-k8s-test-infra/dagster_k8s_test_infra/integration_utils.py
pyproject.toml
python_modules/dagster-test/dagster_test/toys/hammer.py
python_modules/dagster/dagster/_core/selector/subset_selector.py
python_modules/dagster/dagster/_core/storage/event_log/sql_event_log.py
python_modules/dagster/dagster/_serdes/serdes.py
python_modules/dagster/dagster/_serdes/utils.py
python_modules/dagster/dagster_tests/core_tests/resource_tests/test_resource_definition.py
python_modules/libraries/dagster-pagerduty/dagster_pagerduty/resources.py
python_modules/libraries/dagster-pandas/dagster_pandas/constraints.py

Ruff docstrings D403,D405 (FirstLineCapitalized,CapitalizeSectionName)

---

pyproject.toml
python_modules/dagster/dagster_tests/core_tests/test_decorator_utils.py

Ruff docstrings D419 (NonEmpty)

---

docs/content/deployment/guides/docker.mdx

This PR removes some review comments that accidentally made it into this guide.

[docs] - Remove accidental comments

---

python_modules/libraries/dagster-dbt/dagster_dbt/cli/utils.py

We can make a pretty good guess about what log level certain lines should be, so let's do that.

[dagster-dbt] parse log level when json_log_level is not set

---

python_modules/dagit/dagit/cli.py
python_modules/dagit/dagit_tests/test_app.py
python_modules/dagster/dagster/_utils/__init__.py

Fall back to a different port when 3000 is in use instead of failing

---

js_modules/dagit/packages/app/src/NUX/CommunityNux.tsx
js_modules/dagit/packages/ui/src/components/ProductTour.tsx

Make the dialog resize with the iframe + hide scroll bars
I loaded the Nux in OSS dagit, I typed an incorrect email and saw the dialog height increase to accommodate the error message

Update OSS Nux to receive size from iframe via postmessage

---

python_modules/dagster/dagster/_core/execution/api.py
python_modules/dagster/dagster/_legacy/__init__.py

deprecated, no callsites or test coverage
grep, bk

remove reexecute_pipeline_iterator

---

python_modules/libraries/dagster-snowflake-pandas/dagster_snowflake_pandas/snowflake_pandas_type_handler.py

Updates the API doc string to use Definitions

[dagster-snowflake-pandas] update doc string to use Definitions

---

python_modules/dagster/dagster/_core/telemetry.py

telemetry: avoid race condition of dagit and daemon creating same dir

---

python_modules/dagster/dagster/_core/definitions/decorators/job_decorator.py

Fixes https://github.com/dagster-io/dagster/issues/11637

add example and compose_fn argument doc to job decorator

---

js_modules/dagit/packages/app/src/index.tsx

We're going to rethink our strategy here
https://elementl-workspace.slack.com/archives/C03CCE471E0/p1673542741773689?thread_ts=1673495605.296649&cid=C03CCE471E0

Remove community nux for now

---

python_modules/libraries/dagster-dbt/setup.py

chore(dbt): remove unnecessary dependencies

---

docs/content/deployment/overview.mdx

fix an inline link as i was going through this page
https://dagster-git-yuhan-patch-1-elementl.vercel.app/deployment/overview

fix a link on deployment/overview

---

python_modules/dagster/dagster/_core/test_utils.py
python_modules/dagster/dagster/_utils/__init__.py
python_modules/dagster/dagster_tests/general_tests/utils_tests/test_signals.py
python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_failure_recovery.py

Summary:
SIGKILL is not a thing on windows

Unbreak windows tests (and likely the windows multiprocess executor in general)

---

CHANGES.md

changelog for 1.1.10

---

python_modules/dagster/dagster/_core/scheduler/instigation.py

Adds a few basic convenience properties to the `InstigationTick` class that help with filtering.

[tick-alerting] Add properties to InstigationTick

---

docs/content/dagster-cloud/account/setting-up-alerts.mdx

Updates the alerting docs to include tick-based alerting. Uses the UI added here: https://app.graphite.dev/github/pr/dagster-io/internal/4510/tick-alerting-Add-tick-alerting-UI?panel=stack

[tick-alerting] Add docs for tick alerting

---

docs/content/integrations/airflow/reference.mdx

fix broken link to Airflow library page

---

python_modules/dagster/dagster/__init__.py
python_modules/dagster/dagster_tests/definitions_tests/test_definitions_class.py

Test Plan: Bk, import via python shell

Make create_repository_using_definitions_args public

---

python_modules/dagster/dagster_tests/general_tests/utils_tests/test_signals.py

Summary:
Underlying functionality is now working, but a test failure remains - will actually let the windows build finish this time
Test Plan: Azure and BK

one more windows test fix for signals

---

docs/content/concepts/assets/software-defined-assets.mdx
examples/docs_snippets/docs_snippets/concepts/assets/asset_materialization_metadata_none.py
examples/docs_snippets/docs_snippets_tests/concepts_tests/assets_tests/test_asset_materialization_metadata_none.py

Motivated by this Slack question: https://dagster.slack.com/archives/C01U954MEER/p1673534247130169

include docs snippet for how to record metadata for non-output assets

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud/resources.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud/test_resources.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud/utils.py

feat(dbt-cloud): allow jobs to be retrieved from project id

---

integration_tests/test_suites/k8s-test-suite/tests/test_k8s_job_op.py
python_modules/libraries/dagster-k8s/dagster_k8s/ops/k8s_job_op.py

Summary:
You can't add a key to an immutable dict.

fix issue with k8s_job_op when combining command and container_config

---

python_modules/dagster/dagster/_utils/error.py

Fix a type error in `_utils/error.py`, there is an explanatory comment in the changes.
BK

[pyright] [core] _utils/error

---

js_modules/dagit/packages/core/src/instance/CodeLocationsPage.tsx
js_modules/dagit/packages/core/src/instance/InstanceBackfills.tsx
js_modules/dagit/packages/core/src/instance/InstanceConfig.tsx
js_modules/dagit/packages/core/src/instance/InstanceHealthPage.tsx
js_modules/dagit/packages/core/src/overview/OverviewJobsRoot.tsx
js_modules/dagit/packages/core/src/overview/OverviewSchedulesRoot.tsx
js_modules/dagit/packages/core/src/overview/OverviewSensorsRoot.tsx
js_modules/dagit/packages/core/src/overview/OverviewTimelineRoot.tsx
js_modules/dagit/packages/core/src/runs/RunListTabs.tsx
js_modules/dagit/packages/core/src/runs/RunRoot.tsx
js_modules/dagit/packages/core/src/runs/RunsRoot.tsx
js_modules/dagit/packages/core/src/runs/ScheduledRunListRoot.tsx
js_modules/dagit/packages/core/src/workspace/WorkspaceAssetsRoot.tsx
js_modules/dagit/packages/core/src/workspace/WorkspaceGraphsRoot.tsx
js_modules/dagit/packages/core/src/workspace/WorkspaceJobsRoot.tsx
js_modules/dagit/packages/core/src/workspace/WorkspaceOpsRoot.tsx
js_modules/dagit/packages/core/src/workspace/WorkspaceSchedulesRoot.tsx
js_modules/dagit/packages/core/src/workspace/WorkspaceSensorsRoot.tsx

Our document titles are a mess. It looks like we haven't touched them in ages.
Clean them up, especially for Overview, Runs, and code location list views.
Load Dagit, click around and verify that document titles update nicely.

[dagit] Clean up a bunch of document titles

---

python_modules/libraries/dagster-dbt/dagster_dbt/asset_defs.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_defs.py

It's very annoying to try to wire these configurable values through the resource config.

[dagster-dbt] add config schema for dbt asset op

---

python_modules/dagster/dagster/_core/definitions/asset_reconciliation_sensor.py

A followup from the discussion here: https://github.com/dagster-io/dagster/pull/11582. This dramatically improves performance.
A 30-asset multi-asset, downstream of two 15-minute partitioned assets (start-date 2022-01-01). 
I originally tested this before Claire's performance improvements to TimeWindowPartitionsSubset were merged in. In that state, it took 114 seconds (!!) to run my test, the majority of it spent iterating over time windows.
Claire's changes made a big difference, cutting down the total time to 28 seconds, although the performance scaled pretty poorly as the number of source assets increased (i.e. if you had 5 root assets instead of 2, it'd go back to taking over a minute).
After these changes, the original test completes in under 4 seconds, and with 100 source assets, …

[asset-reconciliation] Improve performance for never materialized root partitions

---

python_modules/dagster/dagster/_cli/dev.py
python_modules/dagster/dagster/_serdes/ipc.py

summary:
We were already doing this on windows - lets do it on linux too. Setting this function prevents the grpc servers from being CTRL-Ced whenever the process that opened them got CTRL-c - so we can use our fancier graceful termination logic.
BK, run dagit and CTRL-C it - no more gross "Aborted!" messages for the grpc servers

open grpc servers in their own process group so they don't get interrupted along with whatever process opened them

---

python_modules/dagster/setup.py

See what happens. I want to use the modern API.
bk

test: unpin responses

---

docs/content/integrations/dbt.mdx
docs/content/integrations/dbt/reference.mdx

Add some docs for DBT asset code versions.

DBT code version docs

---

python_modules/dagster/dagster/_core/definitions/partition.py

improve performance of StaticPartitionsDefinition.__eq__

---

docs/content/concepts/io-management/io-managers.mdx

mark PartitionMappings not experimental in IO manager doc

---

examples/project_fully_featured/project_fully_featured_tests/test_resources/test_snowflake_io_manager.py

Update the Snowflake IO manager test for project_fully_featured, since the interfaces for `InputContext`/`OutputContext` have changed.

[fix] Fix Snowflake IO manager tests for project_fully_featured

---

CHANGES.md

Changelog 1.1.11

---

docs/content/deployment/guides/kubernetes/how-to-migrate-your-instance.mdx

I just applied migrations to my dagster deployment for the first time, and got stuck on the `helm template` step for a few minutes. Figured this note might benefit others as well.

docs: add clarification for helm migration guide

---

python_modules/libraries/dagster-dbt/dagster_dbt/cloud/asset_defs.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud/test_asset_defs.py

If the cached compile run is not completed, then we cannot fetch the manifests. Raise an exception instead.
pytest, local

feat(dbt-cloud): raise exception if cached compile has not completed

---

CHANGES.md

1.1.11 changelog: fix link

---

CHANGES.md

Just a few missing items added to Changes.md for 1.1.11

[dagit] Add missing changelog entries for 1.1.11

---

python_modules/dagster/dagster/_core/definitions/decorators/sensor_decorator.py
python_modules/dagster/dagster/_core/definitions/multi_asset_sensor_definition.py
python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py

Fixes https://github.com/dagster-io/dagster/issues/11557

add request_assets param to multi_asset_sensor

---

python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py

[dagit] When viewing an asset that is a root, do not fetch root used data

---

python_modules/dagster/dagster/_core/instance/config.py
python_modules/dagster/dagster/_core/instance/ref.py
python_modules/dagster/dagster_tests/core_tests/instance_tests/test_nux.py

add dagster.yaml tests for nux key

---

integration_tests/test_suites/daemon-test-suite/dagster_dev_command_tests/test_dagster_dev_command.py
python_modules/dagster/dagster/_check/__init__.py
python_modules/dagster/dagster/_cli/dev.py
python_modules/dagster/dagster_tests/general_tests/check_tests/test_check.py

Summary:
This is also a tuple - tested module/file/.toml, but not workspace.yaml. Now rectified.
Test Plan: New BK test

Fix 'dagster dev' command with workspace.yaml passed in

---

python_modules/dagster/dagster/_core/execution/context/compute.py
python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_asset_partition_mappings.py

default argument to asset_partition_keys_for_output

---

js_modules/dagit/packages/core/src/asset-graph/AssetGraphExplorer.tsx

Context:
https://elementl-workspace.slack.com/archives/C03CCE471E0/p1670944563171369
This change makes it possible to click "Materialize All" even if there are too many assets for the graph to render by default. We check for this case (`applyingEmptyDefault`) and set the selection for the purposes of both the Observe and Materialize buttons.
I also cleaned up a few stylistic things in this file because it's getting a bit large -- may try to do more cleanup soon.
I changed `MAX_RENDERED_FOR_EMPTY_QUERY` from 100 to 10 so I could easily test this "applyingEmptyDefault" case.

[dagit] Allow materializing “All” without requiring large graphs are rendered

---

python_modules/libraries/dagster-aws/dagster_aws_tests/ssm_tests/test_parameters.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ssm_tests/test_resources.py

Summary:
Moto added new validation that caught a real problem in our tests - we were missing a required parameter here.
Test Plan: BK

Fix aws ssm tests

---

python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_databricks.py

Summary:
In master these are all dev, but in the RC they are not the same
Test Plan: BK (in release branch)

Fix databricks tests running in release branch

---

CHANGES.md

1.1.14 changelog

---

python_modules/dagster/README.md

[readme] update twitter badge

---

python_modules/dagster/dagster/_core/definitions/asset_reconciliation_sensor.py

Slight adjustment to `asset_reconciliation_sensor` to solve type error.

[pyright] [core] _core/definitions/asset_reconciliation_sensor

---

python_modules/dagster-graphql/dagster_graphql/implementation/events.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_partition_sets.py

Add annotations and fix some type errors with runtime checks in `implementation/fetch_partition_sets`.
BK

[pyright] [gql] implementation/fetch_partition_sets

---

python_modules/dagit/dagit/debug.py
python_modules/dagit/dagit_tests/webserver/test_app.py

[pyright] [dagit] misc

---

python_modules/libraries/dagster-dask/dagster_dask/data_frame.py
python_modules/libraries/dagster-dask/dagster_dask/utils.py
python_modules/libraries/dagster-dask/dagster_dask_tests/hammer_job.py

Fix type errors in `dagster-dask`.
BK

[pyright] [dagster-dask] misc

---

python_modules/dagster-test/dagster_test/toys/input_managers.py

[pyright] [dagster-test] misc

---

python_modules/libraries/dagster-mysql/dagster_mysql/run_storage/run_storage.py
python_modules/libraries/dagster-mysql/dagster_mysql/utils.py
python_modules/libraries/dagster-mysql/dagster_mysql_tests/test_instance.py

[pyright] [dagster-mysql] misc

---

python_modules/libraries/dagster-duckdb-pyspark/dagster_duckdb_pyspark/duckdb_pyspark_type_handler.py

[pyright] [dagster-duckdb-pyspark] misc

---

python_modules/libraries/dagster-pandas/dagster_pandas_tests/test_config_driven_df.py

[pyright] [dagster-pandas] misc

---

python_modules/libraries/dagster-postgres/dagster_postgres/event_log/event_log.py
python_modules/libraries/dagster-postgres/dagster_postgres/run_storage/run_storage.py
python_modules/libraries/dagster-postgres/dagster_postgres_tests/test_instance.py

[pyright] [dagster-postgres] misc

---

python_modules/libraries/dagster-snowflake/dagster_snowflake/resources.py

[pyright] [dagster-snowflake] misc

---

examples/assets_dbt_python/assets_dbt_python/utils/__init__.py

[pyright] [examples/assets-dbt-python] misc

---

python_modules/libraries/dagster-pandera/dagster_pandera_tests/test_dagster_pandera.py

[pyright] [dagster-pandera] misc

---

python_modules/libraries/dagster-aws/dagster_aws/secretsmanager/secrets.py
python_modules/libraries/dagster-aws/dagster_aws/ssm/parameters.py

[pyright] [dagster-aws] misc

---

python_modules/libraries/dagster-airflow/dagster_airflow/dagster_pipeline_factory.py
python_modules/libraries/dagster-airflow/dagster_airflow/hooks/dagster_hook.py
python_modules/libraries/dagster-airflow/dagster_airflow/links/dagster_link.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_airflow_op_to_dagster_op.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_dagster_pipeline_factory/test_solid_execution.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_dagster_pipeline_factory/test_tags.py

Pure typing PR to eliminate pyright type errors in `dagster-airflow`.
BK

[pyright] [dagster-airflow] misc

---

examples/quickstart_gcp/quickstart_gcp/io_managers.py

Fix type error in `quickstart-gcp` example
BK

[pyright] examples/quickstart-gcp

---

python_modules/libraries/dagster-dbt/dagster_dbt/rpc/resources.py

Fix type errors in `dagster-dbt`. No behavior change.
BK

[pyright] [dagster-dbt] misc

---

python_modules/automation/automation/graphql/python_client/utils.py

[pyright] [automation] misc

---

python_modules/libraries/dagster-msteams/dagster_msteams/client.py

Fix type error
BK. Also, I confirmed this works by installing `requests<3` and running:
```
$ python -c 'from requests import codes; print(codes["ok"])'
```

[pyright] [dagster-msteams] misc

---

python_modules/libraries/dagster-snowflake-pandas/dagster_snowflake_pandas/snowflake_pandas_type_handler.py

[pyright] [dagster-snowflake-pandas] misc

---

python_modules/libraries/dagstermill/dagstermill/context.py
python_modules/libraries/dagstermill/dagstermill/engine.py
python_modules/libraries/dagstermill/dagstermill/examples/repository.py
python_modules/libraries/dagstermill/dagstermill/io_managers.py
python_modules/libraries/dagstermill/dagstermill/manager.py
python_modules/libraries/dagstermill/dagstermill/translator.py

Add annotations and fix some type errors in `dagstermill`. Includes a few added runtime type-checks.
BK

[pyright] [dagstermill] misc

---

python_modules/libraries/dagster-docker/dagster_docker/docker_executor.py

[pyright] [dagster-docker] misc

---

python_modules/libraries/dagster-gcp/dagster_gcp/bigquery/ops.py
python_modules/libraries/dagster-gcp/dagster_gcp_tests/bigquery_tests/test_ops.py
python_modules/libraries/dagster-gcp/dagster_gcp_tests/gcs_tests/test_compute_log_manager.py

[pyright] [dagster-gcp] misc

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/asset_defs.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/resources.py

[pyright] [dagster-airbyte] misc

---

python_modules/libraries/dagster-mlflow/dagster_mlflow/hooks.py
python_modules/libraries/dagster-mlflow/dagster_mlflow/resources.py

Remove pylint-ignore comments.

[pyright] [dagster-mlflow] misc

---

python_modules/libraries/dagster-azure/dagster_azure/blob/compute_log_manager.py

[pyright] [dagster-azure] misc

---

python_modules/dagster/dagster/_core/definitions/asset_graph.py
python_modules/dagster/dagster/_core/definitions/external_asset_graph.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_external_asset_graph.py

Add code versions to `AssetGraph`.
Modify exsiting unit test.

Add code versions to AssetGraph

---

python_modules/dagster-graphql/dagster_graphql/schema/solids.py

Fix type error with runtime assertion.
BK

[pyright] [gql] schema/solids#resolve_required_resources

---

python_modules/dagster/dagster/_grpc/server.py

Small refactor of `GrpcServerProcess` to fix some type errors. No behavior change.
Existing BK test.

refactor GrpcServerProcess

---

python_modules/libraries/dagster-aws/dagster_aws/s3/resources.py

Fix s3_resource docstring example

---

python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/storage/legacy_storage.py
python_modules/dagster/dagster/_core/storage/runs/base.py
python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py

Factors out a `RunGroupInfo` `TypedDict` (used upstack in `dagster-graphql`).
BK

[pyright] [core] create RunGroupInfo type

---

examples/assets_smoke_test/setup.py
examples/assets_smoke_test/tox.ini
python_modules/libraries/dagster-snowflake-pandas/setup.py

not sure why this is causing problems, but seems to be the source of our build issues:
https://buildkite.com/dagster/dagster/builds/47070#01860385-662f-47ee-bee5-b9979407ad64
vs
https://buildkite.com/dagster/dagster/builds/47121#018603d2-89f2-4b7e-8927-7b58129b65a8
bk

snowflake connector pin

---

python_modules/dagster-graphql/dagster_graphql/schema/roots/mutation.py

Fix type error with runtime assertion.
BK

[pyright] [gql] schema/roots/mutation

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
python_modules/dagster-graphql/dagster_graphql/implementation/utils.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
python_modules/dagster/dagster/_core/definitions/events.py

Fix some type errors by making it so that `AssetKey.from_graphql_input` always returns an `AssetKey` (previously it could also return `None`) and cleans up associated logic around callsites.
BK

[pyright] [gql] AssetKey cleanup

---

python_modules/dagster/dagster/_core/event_api.py

We want to store these, so this must be whitelisted

whitelist EventLogRecord for serdes

---

python_modules/dagster/dagster/_core/definitions/partition.py
python_modules/dagster/dagster/_core/definitions/time_window_partitions.py

We recently got a question around how to do this, and I didn't see it covered in docs.

document tags_for_partition_fn in _partitioned_config API doc

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_logs.py
python_modules/dagster-graphql/dagster_graphql/implementation/utils.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql/schema/dagster_types.py
python_modules/dagster-graphql/dagster_graphql/schema/external.py
python_modules/dagster-graphql/dagster_graphql/schema/instigation.py
python_modules/dagster-graphql/dagster_graphql/schema/logs/events.py
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
python_modules/dagster-graphql/dagster_graphql/schema/runs.py
python_modules/dagster-graphql/dagster_graphql/schema/schedules/schedules.py
python_modules/dagster-graphql/dagster_graphql/schema/solids.py
python_modules/dagster/dagster/_core/scheduler/instigation.py
python_modules/dagster/dagster/_grpc/utils.py

Assorted typing changes for dagster-graphql. Pure annotation/comment/import changes.
BK

[pyright] [gql] misc

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_sensors.py
python_modules/dagster-graphql/dagster_graphql/implementation/run_config_schema.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql/schema/errors.py
python_modules/dagster-graphql/dagster_graphql/schema/execution.py
python_modules/dagster-graphql/dagster_graphql/schema/external.py
python_modules/dagster-graphql/dagster_graphql/schema/instigation.py
python_modules/dagster-graphql/dagster_graphql/schema/partition_sets.py
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/mutation.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py

Assorted type error fixes, including a few runtime tweaks.
BK

[pyright] [gql] misc type errors 2

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py

Adds type annotations and fixes a few type errors in `implementation/fetch_runs` with runtime checks.
BK

[pyright] [gql] implementation/fetch_runs

---

python_modules/dagster/dagster/_check/__init__.py
python_modules/dagster/dagster_tests/general_tests/check_tests/test_check.py

Adds opt_iterable_param, which was missing
BK

Add opt_iterable_param

---

python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
python_modules/dagster-graphql/dagster_graphql/schema/util.py

Solve a type error related to `ComptueLogManager`-- see inline comment for details. Used upstack.
BK

[pyright] [gql] compute log manager

---

.gitignore

it would also be nice to get a vs-code config example of ruff+black format on save

add .ruff_cache to gitignore

---

docs/content/integrations/airflow.mdx

small tweak to airflow integration page

---

docs/sphinx/sections/api/apidocs/libraries/dagster-docker.rst
python_modules/libraries/dagster-docker/dagster_docker/__init__.py
python_modules/libraries/dagster-docker/dagster_docker/ops/__init__.py
python_modules/libraries/dagster-docker/dagster_docker/ops/docker_container_op.py
python_modules/libraries/dagster-docker/dagster_docker_tests/test_docker_container_op.py
python_modules/libraries/dagster-docker/dagster_docker_tests/test_example_docker_container_op.py
python_modules/libraries/dagster-k8s/dagster_k8s/ops/k8s_job_op.py

Like k8s_job_op but for Docker.

Add docker_container_op and execute_docker_container

---

python_modules/dagster/dagster_tests/general_tests/simple.py
python_modules/dagster/dagster_tests/general_tests/test_import.py

prevent some import time regressions via test
failed on master, passes on top of stacked PRs

[import perf] test to prevent regressions

---

python_modules/libraries/dagstermill/dagstermill_tests/test_logging.py
python_modules/libraries/dagstermill/dagstermill_tests/test_manager.py
python_modules/libraries/dagstermill/dagstermill_tests/test_ops.py

remove legacy APIs from dagstermill tests

---

python_modules/libraries/dagster-shell/dagster_shell_tests/test_terminate.py

remove legacy APIs from dagster_shell_tests

---

examples/docs_snippets/docs_snippets_tests/integrations_tests/test_dagstermill.py
python_modules/dagster/dagster/_core/execution/execution_result.py
python_modules/libraries/dagstermill/dagstermill_tests/test_io.py
python_modules/libraries/dagstermill/dagstermill_tests/test_logging.py
python_modules/libraries/dagstermill/dagstermill_tests/test_ops.py

fix dagstermill tests

---

python_modules/dagster/dagster/_core/host_representation/grpc_server_registry.py
python_modules/dagster/dagster/_core/types/loadable_target_origin.py
python_modules/dagster/dagster/_core/workspace/context.py
python_modules/dagster/dagster/_core/workspace/load_target.py

Type annotations for workspace-related code.
BK

Type annotations for workspace code

---

python_modules/dagster/dagster/_core/host_representation/grpc_server_registry.py

This is a light refactor of `ProcessRegistryEntry` (a class that is used in a very limited scope) with the goal of fixing type errors and enhancing readability. It drops the `check` calls previously used in construction, which I think is OK as discussed for internal objects in this discussion: in this discussion: https://github.com/dagster-io/internal/discussions/4618#discussioncomment-4760254
Existing BK tests.

Refactor ProcessRegistryEntry

---

examples/project_fully_featured/project_fully_featured/resources/parquet_io_manager.py
examples/project_fully_featured/project_fully_featured/resources/snowflake_io_manager.py
examples/project_fully_featured/project_fully_featured/utils/snapshot.py
examples/project_fully_featured/setup.py

Fix some type errors and remove `aiobotocore` pin.
BK

[pyright] examples/project-fully-featured

---

python_modules/libraries/dagster-k8s/dagster_k8s/client.py
python_modules/libraries/dagster-k8s/dagster_k8s/container_context.py
python_modules/libraries/dagster-k8s/dagster_k8s/executor.py
python_modules/libraries/dagster-k8s/dagster_k8s/job.py
python_modules/libraries/dagster-k8s/dagster_k8s/ops/k8s_job_op.py

[pyright] [dagster-k8s] misc

---

python_modules/dagster/dagster_tests/asset_defs_tests/partition_mapping_tests/test_asset_partition_mappings.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_graph.py
python_modules/dagster/dagster_tests/cli_tests/command_tests/file_with_local_import.py
python_modules/dagster/dagster_tests/cli_tests/workspace_tests/autodiscovery_tests/autodiscover_file_in_directory/repository.py
python_modules/dagster/dagster_tests/cli_tests/workspace_tests/hello_world_file_in_directory/hello_world_repository.py
python_modules/dagster/dagster_tests/cli_tests/workspace_tests/multi_file_target_workspace/example_one/pipelines.py
python_modules/dagster/dagster_tests/cli_tests/workspace_tests/multi_file_target_workspace/example_two/pipelines.py
python_modules/dagster/dagster_tests/cli_tests/workspace_tests/multi_file_target_workspace/example_two/solids.py
python_modules/dagster/dagster_tests/core_tests/hook_tests/test_hook_invocation.py
python_modules/dagster/dagster_tests/core_tests/partition_tests/test_partition.py
python_modules/dagster/dagster_tests/core_tests/test_solid_arguments.py
python_modules/dagster/dagster_tests/daemon_sensor_tests/conftest.py
python_modules/dagster/dagster_tests/daemon_sensor_tests/test_run_status_sensors.py
python_modules/dagster/dagster_tests/definitions_tests/test_partitioned_schedule.py
python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py
python_modules/dagster/dagster_tests/execution_tests/dynamic_tests/test_not_allowed.py
python_modules/dagster/dagster_tests/execution_tests/engine_tests/test_step_deletegating_executor_retries.py
python_modules/dagster/dagster_tests/general_tests/py3_tests/test_type_examples_py3.py
python_modules/dagster/dagster_tests/general_tests/test_serdes.py
python_modules/dagster/dagster_tests/scheduler_tests/conftest.py
python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py
python_modules/dagster/dagster_tests/storage_tests/test_upath_io_manager.py

Resolves miscellaneous type errors in `dagster_tests`.
BK

[pyright] [core] tests

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/managed/reconciliation.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/managed/reconciliation.py

[pyright] Type-ignores for various errors related to managed elements

---

python_modules/dagster/dagster/_core/storage/legacy_storage.py

cleam up get_asset_events

---

python_modules/dagster/dagster/_core/definitions/asset_reconciliation_sensor.py
python_modules/dagster/dagster/_utils/caching_instance_queryer.py

[asset-reconciliation] [perf] do not try to fetch materialization records for sources

---

js_modules/dagit/packages/app/src/NUX/CommunityNux.tsx

Add a query parameter for tracking

Add google analytics tracking query param to slack link from OSS

---

integration_tests/test_suites/daemon-test-suite/dagster_dev_command_tests/bar.py
integration_tests/test_suites/daemon-test-suite/dagster_dev_command_tests/repo.py
integration_tests/test_suites/daemon-test-suite/dagster_dev_command_tests/test_dagster_dev_command.py
python_modules/dagster/dagster/_cli/dev.py
python_modules/dagster/dagster/_cli/workspace/cli_target.py

Add --working-directory argument to dagster dev

---

python_modules/libraries/dagster-airflow/dagster_airflow/dagster_pipeline_factory.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/airflow_utils.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_dagster_job_factory/test_load_dag_bag.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_dagster_job_factory/test_load_dag_bag_airflow_2.py

Adds support for converting airflow task level retry config into dagster op retry config
- unit tests

[dagster-airflow] airflow retry support

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/managed/reconciliation.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/resources.py

Change endpoints to the ones that are used by airbyte UI

---

python_modules/dagster/dagster_tests/general_tests/test_import.py

skip import test on windows

---

scripts/check_schemas.py
scripts/get_recent_pypi_changes.py

[pyright] [scripts] misc

---

python_modules/libraries/dagster-airflow/dagster_airflow/dagster_job_factory.py
python_modules/libraries/dagster-airflow/dagster_airflow/dagster_pipeline_factory.py
python_modules/libraries/dagster-airflow/dagster_airflow/utils.py

extracts more utility-type functions into a grab bag util file

[dagster-airflow] move shared functions into utils file

---

python_modules/dagster/dagster/_core/definitions/asset_layer.py

Tiny change to clarify what's going on in this codepath.

in comment, clarify that scraping asset info off of In/Out is legacy

---

python_modules/dagster/dagster/_utils/schedules.py
python_modules/dagster/dagster_tests/scheduler_tests/test_schedule_iterator.py

[schedules] fix nth weekday of month cron handling

---

js_modules/dagit/packages/core/src/assets/usePartitionHealthData.test.tsx
js_modules/dagit/packages/core/src/assets/usePartitionHealthData.tsx

This PR addresses the error surfaced in https://elementl-workspace.slack.com/archives/C03KE7K92TT/p1675447983332539 - retrieving the partition health of an unpartitioned asset would throw an uncaught exception because the health data suggested a one dimensional asset but zero dimensions were present. 
This PR also adds tests for a multi-dimensional asset where both partition ranges are static, since the code path for that is slightly different. This uncovered another small bug in the business logic [!] where the UI would show a "solid green bar" even if a second-dimension key was only materialized for all 1st-dimension keys with any materialization, not all 1st dimension keys total.
I added a failing test case for the datadog case and verified it's fixed by the change.  I /think/ with …

[dagit] Add tests for unpartitioned case, fix for console.error in partition health

---

docs/content/integrations/airflow/migrating-to-dagster.mdx

adds documentation on currently unsupported airflow features

[dagster-airflow] migration limitations

---

python_modules/dagster/dagster/_config/structured_config.py
python_modules/dagster/dagster_tests/core_tests/structured_config_tests/test_structured_config_types.py

Implements support for lists in Pythonic config objects.
Unit tests.

[pythonic config] Correctly handle pydantic List types in config

---

python_modules/dagster/dagster/_core/definitions/run_config.py

I was messing around with this code and it took me a little to get my head straight about what config subtrees were handled by this function, so thought I'd add a docstring to clarity

comment to explain what define_solid_dictionary_cls does

---

CHANGES.md

release 1.1.17 changelog

---

CHANGES.md

Add bugfixes to 1.1.17 changelog

---

docs/content/integrations/airflow/migrating-to-dagster.mdx
docs/content/integrations/airflow/reference.mdx
examples/docs_snippets/docs_snippets/deploying/airflow/mounted.py
examples/docs_snippets/docs_snippets/integrations/airflow/migrate_repo.py
examples/docs_snippets/docs_snippets/integrations/airflow/migrate_repo_connections.py
examples/docs_snippets/docs_snippets/integrations/snowflake/pandas_and_pyspark.py
examples/docs_snippets/docs_snippets/integrations/snowflake/pyspark_configuration.py
python_modules/dagster-test/dagster_test/dagster_airflow/custom_operator.py
python_modules/dagster/dagster/_core/host_representation/external.py

Fixes a few type errors that slipped in between pyright branch and master.
`make pyright`

Fix misc type errors

---

python_modules/dagster/dagster/_core/definitions/composition.py

branch-name: composition-types

type annotations for input_bindings in composition.py

---

python_modules/dagster/dagster/_utils/caching_instance_queryer.py

Fix import

---

python_modules/dagster/dagster/_core/storage/db_io_manager.py
python_modules/dagster/dagster_tests/storage_tests/test_db_io_manager.py
python_modules/libraries/dagster-duckdb-pandas/dagster_duckdb_pandas_tests/test_type_handler.py
python_modules/libraries/dagster-duckdb-pyspark/dagster_duckdb_pyspark_tests/test_type_handler.py
python_modules/libraries/dagster-duckdb/dagster_duckdb/io_manager.py
python_modules/libraries/dagster-duckdb/dagster_duckdb_tests/test_io_manager.py
python_modules/libraries/dagster-snowflake-pandas/dagster_snowflake_pandas_tests/test_snowflake_pandas_type_handler.py
python_modules/libraries/dagster-snowflake-pyspark/dagster_snowflake_pyspark_tests/test_snowflake_pyspark_type_handler.py
python_modules/libraries/dagster-snowflake-pyspark/tox.ini
python_modules/libraries/dagster-snowflake/dagster_snowflake/snowflake_io_manager.py
python_modules/libraries/dagster-snowflake/dagster_snowflake_tests/test_snowflake_io_manager.py
python_modules/libraries/dagster-snowflake/setup.py

Adds static partition support for DBIOManager base class. Updates duckdb and snowflake io managers accordingly
docs plan - i'm going to add multi partition support, then do a pass at updating api docs and the guides to cover partitions
bk - new unit tests

[db io managers] support static partitions

---

docs/content/dagster-cloud/account/setting-up-alerts.mdx

Agent downtime alert docs

---

python_modules/dagster/dagster/_core/execution/plan/inputs.py

fixes formatting issue https://buildkite.com/dagster/dagster/builds/48301

fix pyright 

---

docs/content/deployment/guides/running-locally.mdx
docs/content/integrations/airflow/migrating-to-dagster.mdx
docs/content/integrations/airflow/reference.mdx
examples/docs_snippets/docs_snippets/integrations/airflow/migrate_repo.py
examples/docs_snippets/docs_snippets/integrations/airflow/migrate_repo_connections.py

Attempts to make our migration guide a little more forthright and honest about the complexity and LOE for making a migration
[Preview](https://dagster-git-jvd-migration-considerations-elementl.vercel.app/integrations/airflow/migrating-to-dagster)

[dagster-airflow] [docs] migration guide updates/considerations

---

docs/content/dagster-cloud/account/setting-up-alerts.mdx

Alerts are no longer in cloud settings

Fix alert docs

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/dagster.py

Pending fix to venv build with rust dependency.
BK

Temporarily disable pyright in BK

---

python_modules/dagster/dagster/_core/definitions/decorators/repository_decorator.py
python_modules/dagster/dagster/_core/definitions/definitions_class.py
python_modules/dagster/dagster/_core/definitions/repository_definition.py

This isn't meant for public consumption, so let's make it a private argument.
BK

Make top_level_resources argument _top_level_resources

---

CHANGES.md

1.1.18 Changelog

---

scripts/run-pyright.py

My git workflow does not involve keeping a local copy of `master`.

diff against origin/master in quick_pyright

---

docs/content/dagster-cloud/deployment/serverless.mdx

Update serverless docs with new run isolation default

---

docs/content/integrations/dbt-cloud.mdx
python_modules/libraries/dagster-dbt/dagster_dbt/cloud/cli.py

docs(dbt-cloud): add instructions to cache dbt Cloud compilation

---

docs/content/concepts/ops-jobs-graphs/metadata-tags.mdx

We got feedback on this here: https://dagster.slack.com/archives/C01U954MEER/p1676056189877659?thread_ts=1675883019.174619&cid=C01U954MEER

document system tags on metadata/tags page

---

python_modules/libraries/dagster-airflow/setup.py

fixes https://github.com/dagster-io/dagster/issues/12249

[dagster-airflow] remove ref to cli

---

python_modules/dagster/dagster/_core/definitions/asset_layer.py
python_modules/dagster/dagster/_core/definitions/assets_job.py
python_modules/dagster/dagster/_core/definitions/materialize.py

These are not public APIs, so they shouldn't be marked `@experimental`.
BK

Remove @experimental from build_assets_job and build_source_asset_observation_job

---

python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_executor.py
python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_launcher.py
python_modules/libraries/dagster-k8s/dagster_k8s_tests/unit_tests/test_resource_tags.py

remove legacy APIs from dagster-k8s tests

---

python_modules/dagster/dagster/_core/definitions/asset_graph.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/dependency.py
python_modules/dagster/dagster/_core/definitions/external_asset_graph.py
python_modules/dagster/dagster/_core/definitions/partition_mapping.py
python_modules/dagster/dagster/_core/definitions/pipeline_definition.py
python_modules/dagster/dagster/_core/host_representation/external.py
python_modules/dagster/dagster/_core/selector/subset_selector.py
python_modules/dagster/dagster/_utils/cached_method.py

Pure type annotations diff for `AssetGraph` and friends.
BK

[typing/static] assets

---

python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/graph_definition.py
python_modules/dagster/dagster_tests/core_tests/test_pipeline_execution.py
python_modules/libraries/dagster-airflow/dagster_airflow/dagster_asset_factory.py

Make this method internally public so we are not accessing module-private methods.
BK

[typing/runtime] Make GraphDefinition.create_adjacency_lists internally public

---

python_modules/dagster/dagster/_core/definitions/composition.py

remove some handling for solid in composition.py

---

python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py

Replace resolver `**kwargs` with typed keyword args. Part of a collection of PRs that eliminates resolver `**kwargs` across all resolvers.
BK. Also, correctness of added args was confirmed by manually inspecting the field definition in the parent object.

[typing/runtime] [gql] eliminate resolver **kwargs (5)

---

python_modules/dagster/dagster/_core/definitions/asset_graph.py

Light refactor some asset graph comparisons to fix type errors
BK

[typing/runtime] Asset graph comparisons

---

python_modules/dagster/dagster/_core/storage/db_io_manager.py
python_modules/libraries/dagster-duckdb-pandas/dagster_duckdb_pandas/duckdb_pandas_type_handler.py
python_modules/libraries/dagster-duckdb-pyspark/dagster_duckdb_pyspark/duckdb_pyspark_type_handler.py
python_modules/libraries/dagster-duckdb/dagster_duckdb/io_manager.py
python_modules/libraries/dagster-snowflake-pandas/dagster_snowflake_pandas/snowflake_pandas_type_handler.py
python_modules/libraries/dagster-snowflake/dagster_snowflake/snowflake_io_manager.py

Adds new method to DB IO manager subclasses to create the schema if it doesn't exist. Calls this method within handle_output

[db io managers] create schema if not exist

---

python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py

branch-name: to-source-asset
Useful in conjunction with https://github.com/dagster-io/dagster/pull/12091

AssetsDefinition.to_source_asset

---

docs/content/concepts/ops-jobs-graphs/metadata-tags.mdx

My bad the first time around
Addresses https://github.com/dagster-io/dagster/issues/10297

in tags doc, fix schedule tag and add sensor tag

---

js_modules/dagit/packages/core/src/asset-graph/AssetNode.mocks.ts
js_modules/dagit/packages/core/src/asset-graph/AssetNode.tsx
js_modules/dagit/packages/core/src/asset-graph/types/AssetNode.types.ts
js_modules/dagit/packages/core/src/asset-graph/types/useLiveDataForAssetKeys.types.ts
js_modules/dagit/packages/core/src/assets/AssetsCatalogTable.mocks.ts
js_modules/dagit/packages/core/src/assets/CurrentMinutesLateTag.tsx
js_modules/dagit/packages/core/src/graphql/schema.graphql
js_modules/dagit/packages/core/src/graphql/types.ts
js_modules/dagit/packages/core/src/workspace/types/VirtualizedAssetRow.types.ts
python_modules/dagster-graphql/dagster_graphql/schema/freshness_policy.py
python_modules/dagster/dagster/_core/definitions/freshness_policy.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_freshness_policy.py

Resolves: https://github.com/dagster-io/dagster/issues/12006

[freshness-policies] add a cron_schedule_timezone argument to the FreshnessPolicy class

---

python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/job_definition.py
python_modules/dagster/dagster/_core/selector/subset_selector.py

Light refactor of `convert_dot_separated_string_to_dict` (fix type errors).
BK

[typing/runtime] Refactor subset selection tree

---

python_modules/dagster/dagster/_core/definitions/assets.py

Fix unimported symbol BK

---

examples/assets_dbt_python/setup.py
examples/assets_dbt_python/tox.ini
examples/assets_modern_data_stack/setup.py
examples/assets_modern_data_stack/tox.ini
pyright/master/exclude.txt
pyright/master/requirements.txt

https://github.com/dagster-io/internal/pull/4791#discussion_r1100817139

nux examples in oss 3/: sync dagster-io/quickstart-*/setup.py to example/*

---

python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/selector/subset_selector.py

Flatten sets in a type-checker-legible way
BK

[typing/runtime] Massage set flattening

---

python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/test_asset_reconciliation_sensor_perf.py

bump limit

---

python_modules/dagster/dagster/_core/definitions/solid_invocation.py
python_modules/dagster/dagster_tests/core_tests/test_nothing_dependencies.py

align direct invoke behavior with real behavior
updated test

[direct invoke] yield implicit Nothing Output

---

python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py
python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/test_asset_reconciliation_sensor_perf.py

https://github.com/dagster-io/dagster/issues/11677

[freshness-policies] Allow setting freshness policies when using graph-backed assets

---

python_modules/dagster/dagster/_core/definitions/asset_sensor_definition.py
python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py

https://github.com/dagster-io/dagster/issues/12324

Add skip reason to asset sensor

---

python_modules/dagster/dagster/_core/definitions/repository_definition/repository_data.py
python_modules/dagster/dagster/_core/definitions/repository_definition/repository_data_builder.py

These are nasty functions that need to be refactored. Move them into their own global functions to set that up.
BK

Move CachingRepositoryData.from_list and from_dict into standalone function

---

js_modules/dagit/packages/core/src/sensors/SensorDetails.tsx

This should address an issue where sensors without any targets crash.
:eyes:

 nullsafe array index access

---

js_modules/dagit/packages/core/src/schedules/ScheduleDetails.tsx

Change schedule button text

---

examples/docs_snippets/docs_snippets/concepts/ops_jobs_graphs/op_hooks_context.py
python_modules/dagster/dagster/_core/definitions/events.py
python_modules/dagster/dagster/_core/definitions/executor_definition.py
python_modules/dagster/dagster/_core/definitions/pipeline_base.py
python_modules/dagster/dagster/_core/definitions/pipeline_definition.py
python_modules/dagster/dagster/_core/execution/api.py
python_modules/dagster/dagster/_core/execution/context/compute.py
python_modules/dagster/dagster/_core/execution/context/hook.py
python_modules/dagster/dagster/_core/execution/context/output.py
python_modules/dagster/dagster/_core/execution/context/system.py
python_modules/dagster/dagster/_core/execution/context_creation_pipeline.py
python_modules/dagster/dagster/_core/execution/host_mode.py
python_modules/dagster/dagster/_core/execution/plan/active.py
python_modules/dagster/dagster/_core/execution/plan/compute.py
python_modules/dagster/dagster/_core/execution/plan/execute_plan.py
python_modules/dagster/dagster/_core/execution/plan/inputs.py
python_modules/dagster/dagster/_core/execution/plan/plan.py
python_modules/dagster/dagster/_core/execution/plan/state.py
python_modules/dagster/dagster/_core/execution/plan/step.py
python_modules/dagster/dagster/_core/execution/resolve_versions.py
python_modules/dagster/dagster/_core/execution/resources_init.py
python_modules/dagster/dagster/_core/executor/base.py
python_modules/dagster/dagster/_core/executor/in_process.py
python_modules/dagster/dagster/_core/storage/pipeline_run.py
python_modules/dagster/dagster/_utils/__init__.py

Add type annotations for mostly execution-related modules. Pure typing PR-- no runtime changes.
BK

[typing/static] Execution API types

---

python_modules/dagster/dagster/_core/definitions/asset_group.py
python_modules/dagster/dagster/_core/definitions/graph_definition.py
python_modules/dagster/dagster/_core/definitions/node_definition.py
python_modules/dagster/dagster/_core/definitions/op_definition.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_group.py

Rename NodeDefinition.iterate_solid_defs -> iterate_node_defs
BK

[refactor] NodeDefiniton.iterate_solid_defs -> iterate_op_defs

---

python_modules/dagster/dagster/_core/definitions/asset_layer.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/graph_definition.py
python_modules/dagster/dagster/_core/definitions/input.py
python_modules/dagster/dagster/_core/definitions/job_definition.py
python_modules/dagster/dagster/_core/definitions/output.py
python_modules/dagster/dagster/_core/definitions/pipeline_definition.py
python_modules/dagster/dagster/_core/execution/execute_in_process.py
python_modules/dagster/dagster/_core/execution/execution_result.py
python_modules/dagster/dagster/_core/execution/results.py
python_modules/dagster/dagster/_core/host_representation/external_data.py
python_modules/dagster/dagster/_core/snap/solid.py

- GraphDefinition.get_solid -> get_node
- (FanIn)InputPointer.solid_name -> node_name
- OutputPointer.solid_name -> node_name
One per commit
BK

[refactor] misc core solid -> node renames

---

python_modules/dagster/dagster/_core/definitions/graph_definition.py
python_modules/dagster/dagster/_core/execution/context/output.py
python_modules/dagster/dagster/_core/execution/context/system.py
python_modules/dagster/dagster/_core/execution/plan/plan.py

Misc renames of local variables/functions/args containing "solid" to "node" equivalents.
BK

[refactor] Assorted local var solid -> node

---

CHANGES.md

1.1.19 Changelog

---

python_modules/libraries/dagster-databricks/dagster_databricks/databricks.py
python_modules/libraries/dagster-databricks/dagster_databricks/types.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_databricks.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_ops.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_pyspark.py

Wrangle some of the complexity into types.
pyright

refactor(databricks): add types to databricks.py

---

js_modules/dagit/packages/core/src/graphql/schema.graphql
js_modules/dagit/packages/core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/external.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_workspace.py
python_modules/dagster/dagster/_core/host_representation/repository_location.py
python_modules/dagster/dagster/_grpc/server.py
python_modules/dagster/dagster/_grpc/types.py
python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_persistent.py

expose over graphql the dagster libaries loaded by a code location
added test

[graphql] add RepositoryLocation.dagsterLibraryVersions

---

CHANGES.md

move the code block next to its relevant entry

1.1.19 changelog: reorder code block

---

python_modules/dagster/dagster/_core/events/__init__.py
python_modules/dagster/dagster/_core/execution/context/hook.py
python_modules/dagster/dagster/_core/execution/context/output.py
python_modules/dagster/dagster/_core/execution/context/system.py
python_modules/dagster/dagster/_core/execution/plan/compute.py
python_modules/dagster/dagster/_core/execution/plan/execute_step.py
python_modules/dagster/dagster/_core/execution/plan/plan.py
python_modules/dagster/dagster/_core/execution/plan/step.py
python_modules/dagster/dagster/_core/execution/resolve_versions.py
python_modules/dagster/dagster/_core/execution/resources_init.py
python_modules/dagster/dagster/_core/snap/execution_plan_snapshot.py
python_modules/dagster/dagster_tests/execution_tests/execution_plan_tests/test_external_step.py

- Rename IExecutionStep.solid_handle -> node_handle
BK

[refactor] IExecutionStep.solid_handle -> node_handle

---

python_modules/dagster/dagster/_core/execution/context/hook.py
python_modules/dagster/dagster/_core/execution/context/output.py
python_modules/dagster/dagster/_core/execution/context/system.py
python_modules/dagster/dagster/_core/execution/plan/compute.py
python_modules/dagster/dagster/_core/execution/plan/execute_step.py
python_modules/dagster/dagster/_core/execution/plan/inputs.py
python_modules/dagster/dagster/_core/execution/plan/plan.py
python_modules/dagster/dagster/_core/execution/resolve_versions.py
python_modules/dagster/dagster/_core/system_config/objects.py
python_modules/dagster/dagster_tests/core_tests/system_config_tests/test_system_config.py
python_modules/dagster/dagster_tests/core_tests/test_output_materialization.py
python_modules/libraries/dagstermill/dagstermill/context.py

- Rename ResolvedRunConfig.solids -> ops
BK

[refactor] ResolvedRunConfig.solids -> ops

---

scripts/create_dagster_package.py
scripts/templates_create_dagster_package/__init__.py.tmpl

update to comply with new library registry 
```
python scripts/create_dagster_package.py -n dagster-testing-gen
pip install -e python_modules/libraries/dagster-testing-gen
python> import dagster_testing_gen
```

[library template] add registry call

---

python_modules/dagster/dagster/_core/storage/pipeline_run.py

Delete `PipelineRunsFilter` (update refs to `RunsFilter`)
BK

[refactor] Delete PipelineRunsFilter

---

integration_tests/test_suites/daemon-test-suite/auto_run_reexecution_tests/test_event_log_consumer.py
python_modules/dagster-graphql/dagster_graphql/implementation/execution/__init__.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_partition_sets.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_runs.py
python_modules/dagster-graphql/dagster_graphql/implementation/loader.py
python_modules/dagster-graphql/dagster_graphql/schema/backfill.py
python_modules/dagster-graphql/dagster_graphql/schema/instigation.py
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
python_modules/dagster/dagster/_cli/run.py
python_modules/dagster/dagster/_core/definitions/run_status_sensor_definition.py
python_modules/dagster/dagster/_core/storage/event_log/sqlite/sqlite_event_log.py
python_modules/dagster/dagster/_core/storage/pipeline_run.py
python_modules/dagster/dagster/_core/storage/runs/migration.py
python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py
python_modules/dagster/dagster/_daemon/auto_run_reexecution/auto_run_reexecution.py
python_modules/dagster/dagster/_utils/caching_instance_queryer.py
python_modules/dagster/dagster_tests/storage_tests/utils/run_storage.py

Delete `RunRecord.pipeline_run` (update refs to `RunRecord.dagster_run`)
BK

[refactor] Delete RunRecord.pipeline_run

---

python_modules/dagster/dagster/_core/storage/pipeline_run.py

Rename `pipeline_run_from_storage` -> `dagster_run_from_storage`
BK

[refactor] pipeline_run_from_storage -> dagster_run_from_storage

---

python_modules/dagster/dagster_tests/execution_tests/dynamic_tests/test_dynamic_execution.py
python_modules/dagster/dagster_tests/execution_tests/dynamic_tests/test_dynamic_output.py
python_modules/dagster/dagster_tests/execution_tests/dynamic_tests/test_not_allowed.py
python_modules/dagster/dagster_tests/execution_tests/dynamic_tests/test_reexecute.py

Convert solid/pipeline uses in `execution_tests/dynamic_tests` to op/job
BK

[test-api-update] execution_tests/dynamic_tests

---

CHANGES.md

I should have put this in the first time around

document missing breaking change in 1.1.19 changelog

---

python_modules/libraries/dagster-gcp-pandas/dagster_gcp_pandas/__init__.py

[dagster-gcp-pandas] register library in init

---

python_modules/libraries/dagster-gcp/dagster_gcp/bigquery/io_manager.py

Marks the bigquery io manager as experimental

[bigquery] mark bigquery io manager experimental

---

js_modules/dagit/packages/core/src/graphql/schema.graphql
js_modules/dagit/packages/core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_logical_versions.py

This updates GQL to expose the new StaleStatus and StaleStatusCause data.
Unit tests (in progress)

Update GQL to expose StaleStatus and StaleStatusCause

---

python_modules/dagster/dagster/_core/definitions/logical_version.py
python_modules/dagster/dagster_tests/execution_tests/test_logical_versions.py

Ensure asset keys are sorted when generating list of stale status reasons.
BK

Fix state status logical version test

---

python_modules/dagster/dagster/_config/run_config.py

To pave the way for #11965, removes the existing unused `RunConfig` class

Remove existing RunConfig class

---

docs/content/dagster-cloud/deployment/agents/amazon-ecs/configuration-reference.mdx

Add example of customizing task role and execution role arn to the ECS agent docs

---

CHANGES.md

1.1.20 changelog

---

python_modules/libraries/dagster-databricks/dagster_databricks/databricks.py
python_modules/libraries/dagster-databricks/dagster_databricks/databricks_pyspark_step_launcher.py
python_modules/libraries/dagster-databricks/dagster_databricks/ops.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/conftest.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_databricks.py

Remove the unnecessary duplication.
pytest

refactor(databricks): lift polling methods up to the client

---

CHANGES.md

Fix 1.1.20 changelog codeblock

---

python_modules/dagster/dagster/_core/definitions/reconstruct.py
python_modules/dagster/dagster/_core/execution/plan/external_step.py
python_modules/dagster/dagster/_core/host_representation/origin.py
python_modules/dagster/dagster/_serdes/config_class.py
python_modules/dagster/dagster/_serdes/ipc.py
python_modules/dagster/dagster/_serdes/serdes.py
python_modules/dagster/dagster/_serdes/utils.py
python_modules/dagster/dagster/_utils/error.py
python_modules/libraries/dagstermill/dagstermill/manager.py

Pure static typing diff for `dagster._serdes`
BK

[typing/static] serdes

---

python_modules/libraries/dagster-databricks/dagster_databricks/databricks.py
python_modules/libraries/dagster-databricks/dagster_databricks_tests/test_databricks.py

We need this for certifying the integration with Databricks.
pytest

feat(databricks): override user agent in resource

---

docs/content/integrations/snowflake/reference.mdx

Fixes a couple issues I noticed in the reference page

[docs] Snowflake reference page fixes

---

python_modules/dagster/dagster/_core/execution/backfill.py
python_modules/dagster/dagster/_core/test_utils.py
python_modules/dagster/dagster_tests/daemon_tests/conftest.py
python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py
python_modules/dagster/dagster_tests/daemon_tests/test_backfill_failure_recovery.py
python_modules/dagster/dagster_tests/daemon_tests/test_monitoring_daemon.py
python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py

Adds typing to fixtures used in daemon tests.

[typing] fix typing in daemon tests

---

python_modules/libraries/dagster-dbt/dagster_dbt/asset_selection.py

docs(dagster-dbt): add example to retrieve asset keys from dbt selection

---

scripts/templates_create_dagster_package/setup.cfg.tmpl

error in the setup.cfg that this fixes

fix setup.cfg in create package

---

docs/content/integrations/snowflake/reference.mdx
python_modules/dagster/dagster/_core/storage/db_io_manager.py
python_modules/dagster/dagster_tests/storage_tests/test_db_io_manager.py
python_modules/libraries/dagster-duckdb/dagster_duckdb/io_manager.py
python_modules/libraries/dagster-duckdb/dagster_duckdb_tests/test_io_manager.py
python_modules/libraries/dagster-gcp/dagster_gcp/bigquery/io_manager.py
python_modules/libraries/dagster-gcp/dagster_gcp_tests/bigquery_tests/test_io_manager.py
python_modules/libraries/dagster-snowflake/dagster_snowflake/snowflake_io_manager.py
python_modules/libraries/dagster-snowflake/dagster_snowflake_tests/test_snowflake_io_manager.py

handle multiple non-time-window partitions in db io managers

---

python_modules/libraries/dagster-aws/dagster_aws/ecs/container_context.py
python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py
python_modules/libraries/dagster-aws/dagster_aws/ecs/tasks.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/conftest.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/test_launching.py

Summary:
Gives EcsRunLauncher the tools to launch windows containers
Test Plan: bk

Add runtime_platform to EcsRunLauncher

---

examples/assets_dynamic_partitions/setup.py

remove dagster-cloud dep from dynamic partitions example

---

python_modules/dagster/dagster/_core/definitions/job_definition.py
python_modules/dagster/dagster/_core/definitions/partition.py
python_modules/dagster/dagster/_core/definitions/partitioned_schedule.py
python_modules/dagster/dagster/_core/definitions/unresolved_asset_job_definition.py
python_modules/dagster/dagster_tests/definitions_tests/test_partitioned_schedule.py

Fixes https://github.com/dagster-io/dagster/issues/12532

fix future ticks for partitioned schedules

---

python_modules/dagster/dagster/_core/storage/partition_status_cache.py
python_modules/dagster/dagster_tests/storage_tests/test_asset_status_cache.py

Add failures to partition status cache

---

python_modules/libraries/dagster-gcp-pandas/dagster_gcp_pandas/bigquery/bigquery_pandas_type_handler.py

Missed piping this user config through to the type handler

[bigquery-pandas] pipe gcp location through to type handler

---

python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_decorators.py

make freshness policies work with graph_asset and graph_multi_asset

---

docs/content/integrations/snowflake.mdx
docs/content/integrations/snowflake/reference.mdx
docs/content/integrations/snowflake/using-snowflake-with-dagster.mdx
examples/docs_snippets/docs_snippets/integrations/snowflake/multi_partition.py
examples/docs_snippets/docs_snippets/integrations/snowflake/static_partition.py
examples/docs_snippets/docs_snippets/integrations/snowflake/time_partition.py

a lot of the comments on the bigquery guide apply to this one too! so i'm fixing them here!

[docs, snowflake] fix small things in snowflake docs

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql/schema/pipelines/pipeline.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/snapshots/snap_test_all_snapshot_ids.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/snapshots/snap_test_assets.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/snapshots/snap_test_solids.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
python_modules/dagster/dagster/_core/storage/partition_status_cache.py

gql for counting failed partitions.
Update: to make it so that numMaterialized and numFailed can't total to greater than numPartitions, we now filter out failed partitions from materialized.

asset partitions numFailed

---

js_modules/dagit/packages/core/src/graphql/schema.graphql
js_modules/dagit/packages/core/src/graphql/types.ts

make graphql

---

python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py

This PR provides a helper method that accepts a list of `TimeWindowPartitionsSubset`s and their statuses (failed or materialized). Flattens these subsets into a list of range statuses based on the priority of the statuses.
This helper function:
- calculates the overlap between the two subset's ranges
- removes the overlap from the lower priority subset's ranges
The hope is that this function in the future can be adapted to accept `n` subsets and can flatten based on the priority of each subset.

Flatten overlapping time window subsets in order of priority

---

python_modules/dagster-test/dagster_test/toys/notebooks.py

remove notebook toy off of @pipeline

---

js_modules/dagit/packages/core/src/graphql/schema.graphql
js_modules/dagit/packages/core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql/schema/backfill.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_partition_backfill.py

Will help implement per-code-location permissions on the frontend.
Test plan: New BK tests

More permissions booleans (Assets and backfills)

---

CHANGES.md

update CHANGES.md for 1.1.21

---

CHANGES.md

Update changelog with helm change

---

docs/content/integrations/databricks.mdx
examples/docs_snippets/docs_snippets/integrations/databricks/databricks.py

Update Databricks docs based on feedback from dogfooding.
- Separate out custom op/asset examples
- Remove submit run API call from example so things work out of the box
- Clarify that `DATABRICKS_HOST` should start with `https://`
eyes

docs(databricks): update guide based on feedback

---

python_modules/dagster/dagster/_core/execution/api.py

Fixes dynamic graph execution bug caused in asset usages by not threading `inintial_known_state` through from the execution plan snapshot on the run when we go through the create_run -> execute_run path.
`asset_selection` is always set in asset executions so we were always rebuilding from scratch for assets.
Here we:
* pass along `initial_known_state` when we rebuild
* rebuild from snapshot when subselections match instead of only when they are `None` 
existing coverage. Can add further tests

improve execution plan snapshot use in execute_run

---

.buildkite/dagster-buildkite/dagster_buildkite/package_spec.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/integration.py
.buildkite/dagster-buildkite/dagster_buildkite/utils.py
helm/dagster/charts/dagster-user-deployments/templates/deployment-user.yaml
helm/dagster/schema/schema_tests/test_user_deployments.py

Summary:
Add test that would have caught this, plus atone for my sins by making the e2e tests work on helm schema changes

Fix typo in helm chart

---

CHANGES.md

update automating pipelines guide link

---

python_modules/dagster/dagster/_core/definitions/logical_version.py
python_modules/dagster/dagster_tests/execution_tests/test_logical_versions.py

Fixes bug where a stale cause would appear multiple times if the stale cause is an updated logical version and there are multiple paths to the asset.
New unit test.

[bugfix] Dedup stale root causes for updated data versions

---

docs/content/getting-started/releases.mdx

remove extra paren from releases page

---

python_modules/dagster/dagster/_core/definitions/partition.py
python_modules/dagster/dagster_tests/core_tests/partition_tests/test_partition.py

I found this name a little hard to parse: ![image](https://user-images.githubusercontent.com/654855/223243024-8047570f-8812-4c80-8ddf-0575a75d971e.png)

change DynamicPartitionsDefinition.__repr__

---

docs/content/_navigation.json
docs/content/guides.mdx
docs/content/guides/best-practices.mdx
docs/content/guides/dagster/recommended-project-structure.mdx
docs/content/guides/dagster/recommended_project_structure.mdx

New guide that explores the fully featured project and provides recommendations - https://dagster-git-odette-recommendedprojectguide-elementl.vercel.app/guides/dagster/recommended-project-structure
link to old PR: https://github.com/dagster-io/dagster/pull/11968

Recommended Project Structure Guide

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py
python_modules/dagster/dagster/_core/definitions/metadata/table.py
python_modules/dagster/dagster_tests/execution_tests/test_metadata.py

fix serialization of TableRecord

---

python_modules/dagster-graphql/dagster_graphql/schema/external.py
python_modules/dagster/dagster/_core/workspace/context.py

Summary:
This is needed so that we can use @cached_method on it to speed up performance in certain situations

Make permissions_for_location require keyword args

---

docs/content/concepts/partitions-schedules-sensors/partitions.mdx
examples/docs_snippets/docs_snippets/concepts/partitions_schedules_sensors/partition_mapping.py
examples/docs_snippets/docs_snippets_tests/concepts_tests/partitions_schedules_sensors_tests/test_partition_mapping.py

document PartitionMappings in partitions concepts page

---

python_modules/dagster/dagster/_core/storage/runs/sql_run_storage.py

Got some graphql errors when fetching heartbeats/kvs values on unmigrated dbs.
Loaded unmigrated table, saw no errors, BK

make sure kv/daemon_heartbeat queries explicitly enumerate columns

---

python_modules/dagster/dagster/_core/definitions/asset_selection.py

also update an error message to mention Definitions not repository

[apidoc] asset_selection repository -> Definitions

---

python_modules/dagster/dagster/_core/storage/mem_io_manager.py

Typing on context of mem_io_manager methods is reversed

Fix typing on mem_io_manager

---

docs/content/integrations/bigquery/reference.mdx

adding a quick note about pyspark temporary tables to the docs

[docs] add note about biquery temp tables

---

python_modules/dagster/dagster/_core/execution/plan/inputs.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets_job.py

Reported here: https://dagster.slack.com/archives/C01U954MEER/p1678232859317519?thread_ts=1678127682.574859&cid=C01U954MEER

make context.upstream_output.log work for source assets

---

python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

Test get and set new asset cache fields

---

python_modules/libraries/dagster-duckdb-polars/README.md

couple copy paste errors in the duckdb polars readme

[quick] [duckdb-polars] fix readme

---

js_modules/dagit/packages/ui/src/components/TagSelector.tsx

As titled
addresses https://github.com/dagster-io/dagster/issues/12756
Tested in storybook

Virtualize TagSelector component

---

python_modules/libraries/dagster-snowflake/dagster_snowflake/snowflake_io_manager.py

[dagster-snowflake] fix permissions issue when creating schemas

---

js_modules/dagit/packages/core/src/graphql/schema.graphql
js_modules/dagit/packages/core/src/graphql/types.ts
js_modules/dagit/packages/core/src/resources/ResourceRoot.tsx
js_modules/dagit/packages/core/src/resources/types/ResourceRoot.types.ts
python_modules/dagster-graphql/dagster_graphql/schema/resources.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo_definitions.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/snapshots/snap_test_top_level_resources.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_top_level_resources.py
python_modules/dagster/dagster/_core/host_representation/external.py
python_modules/dagster/dagster/_core/host_representation/external_data.py

Adds a basic special renderer for env vars in the Dagit resources page.
Add unit test, test locally.

[pythonic config] Special rendering for env vars in UI

---

python_modules/dagster-test/dagster_test/toys/nothing_input.py
python_modules/dagster-test/dagster_test/toys/repo.py
python_modules/dagster-test/dagster_test_tests/toys_tests/test_nothing_input.py

nothing input toy

---

js_modules/dagit/packages/core/src/graphql/schema.graphql
js_modules/dagit/packages/core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
python_modules/dagster/dagster/_core/event_api.py

Query to enable showing the run when you click on a failed partition in the catalog

latestRunForPartition gql

---

js_modules/dagit/packages/core/src/partitions/DimensionRangeWizard.tsx
js_modules/dagit/packages/ui/src/components/TagSelector.stories.tsx
js_modules/dagit/packages/ui/src/components/TagSelector.tsx

As titled.
Tested with the partition selector in storybook

[TagSelector] Allow filtering tags in dropdown

---

python_modules/dagster/dagster/_core/execution/context/compute.py
python_modules/dagster/dagster/_core/execution/context/system.py

fix type annotation for partition_time_window

---

python_modules/dagster/dagster/_core/execution/context/compute.py
python_modules/dagster/dagster/_core/execution/context/system.py

Reverts dagster-io/dagster#12850

Revert "fix type annotation for partition_time_window"

---

CHANGES.md

add 1.2.1 changelog

---

python_modules/dagster/dagster/_core/definitions/repository_definition/repository_definition.py
python_modules/dagster/dagster/_core/definitions/source_asset.py
python_modules/dagster/dagster/_core/storage/asset_value_loader.py
python_modules/dagster/dagster_tests/storage_tests/test_asset_value_loader.py

Fixes https://github.com/dagster-io/dagster/issues/12806

Support SourceAssets in load_asset_value

---

python_modules/dagster/dagster/_core/storage/asset_value_loader.py
python_modules/dagster/dagster_tests/storage_tests/test_asset_value_loader.py

Fixes https://github.com/dagster-io/dagster/issues/12854

Fix transitive resource deps for asset value loader

---

docs/content/_navigation.json
docs/content/concepts.mdx
docs/content/concepts/assets/asset-selection-syntax.mdx

add docs page on asset selection syntax

---

js_modules/dagit/packages/core/src/assets/LaunchAssetExecutionButton.tsx

Addresses https://github.com/dagster-io/dagster/issues/12786

Add dropdown for materializing using launchpad

---

docs/content/concepts/io-management/io-managers.mdx

avoid custom PartitionMapping on IO manager concept page

---

docs/content/tutorial/introduction.mdx

A few tweaks to the tutorial intro because I'm very picky about how software-defined assets get talked about.

tutorial intro tweaks

---

python_modules/dagster/dagster/_core/execution/validate_run_config.py
python_modules/dagster/dagster_tests/core_tests/structured_config_tests/test_basic_structured_config.py
python_modules/dagster/dagster_tests/core_tests/test_validate_run_config.py

remove support for legacy APIs from validate_run_config

---

js_modules/dagit/packages/core/src/graphql/schema.graphql
js_modules/dagit/packages/core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
python_modules/dagster/dagster_tests/definitions_tests/test_flatten_time_window_ranges.py

Expand support for adding a materializing status

Make fetch_flattened_time_window_ranges support arbitrary statuses

---

python_modules/dagster/dagster/_core/definitions/multi_dimensional_partitions.py
python_modules/dagster/dagster/_core/definitions/partitioned_schedule.py
python_modules/dagster/dagster/_core/definitions/schedule_definition.py
python_modules/dagster/dagster_tests/definitions_tests/test_multi_partitions.py
python_modules/dagster/dagster_tests/definitions_tests/test_partitioned_schedule.py

Requested by multiple users. Issue here: https://github.com/dagster-io/dagster/issues/10800

Build schedule from multipartitioned job

---

python_modules/dagster/dagster_tests/execution_tests/dynamic_tests/test_reexecute.py

Save some Increased test coverage that was output from trying to reproduce an issue.
its tests

test assets in dynamic re-execution

---

js_modules/dagit/packages/core/src/app/AppError.tsx

Fixes an infinite loop. Check the comment for a description of the issue.
Repro of the issue stopped reproing after this change

Fix error reporter infinite loop

---

scripts/gen_airbyte_classes.py

Convert directives injected into generated airbyte code from pylint-disables to ruff noqas.
---
BK

[ruff] Convert generated directives from pylint to ruff

---

examples/with_wandb/with_wandb/assets/example/train.py
pyproject.toml
python_modules/dagster-graphql/dagster_graphql/implementation/events.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
python_modules/dagster/dagster/_check/__init__.py
python_modules/dagster/dagster/_cli/asset.py
python_modules/dagster/dagster/_core/definitions/asset_layer.py
python_modules/dagster/dagster/_core/definitions/node_container.py
python_modules/dagster/dagster/_core/definitions/partition_mapping.py
python_modules/dagster/dagster/_core/events/utils.py
python_modules/dagster/dagster/_core/execution/plan/execute_step.py
python_modules/dagster/dagster/_core/storage/event_log/migration.py
python_modules/dagster/dagster/_daemon/sensor.py
python_modules/dagster/dagster/_grpc/impl.py
python_modules/dagster/dagster/_scheduler/scheduler.py
python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
python_modules/libraries/dagster-airbyte/dagster_airbyte_tests/test_generated_classes.py
python_modules/libraries/dagster-aws/dagster_aws/utils/mrjob/log4j.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/stubbed_ecs.py
python_modules/libraries/dagster-dbt/dagster_dbt_tests/cloud/utils.py
python_modules/libraries/dagster-snowflake/dagster_snowflake/resources.py
python_modules/libraries/dagstermill/dagstermill_tests/test_ops.py
scripts/check_schemas.py
scripts/gen_airbyte_classes.py

Turns on Ruff `PLW2901` (`redefined-loop-name`) and fixes ~30ish violations in our code. Typically this meant renaming the loop variable.
---
BK

[ruff] enable PLW2901, redefined-loop-name

---

docs/sphinx/_ext/autodoc_dagster.py
docs/sphinx/conf.py
examples/docs_snippets/docs_snippets/guides/dagster/enriching_with_software_defined_assets/mylib.py
examples/experimental/script_to_assets_branching_io_manager/hackernews.py
examples/with_wandb/with_wandb/assets/example/train.py
pyproject.toml
python_modules/automation/automation/docker/cli.py
python_modules/dagster-graphql/dagster_graphql/schema/partition_sets.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/query.py
python_modules/dagster/dagster/_core/definitions/metadata/table.py
python_modules/dagster/dagster/_core/definitions/op_definition.py
python_modules/dagster/dagster/_core/definitions/run_config.py
python_modules/dagster/dagster_tests/scheduler_tests/test_schedule_iterator.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/managed/generated/destinations.py
python_modules/libraries/dagster-airbyte/dagster_airbyte/managed/generated/sources.py
scripts/create_dagster_package.py

Turn on ruff `A001`, `A002` builtin symbol shadowing rules. Replace previously enabled pylint rules.
---
BK

[ruff] enable A001 (builtin-variable-shadowing), A002 (builtin-argument-shadowing)

---

js_modules/dagit/packages/core/src/assets/LaunchAssetChoosePartitionsDialog.tsx

https://elementl-workspace.slack.com/archives/C03CA4TVCAW/p1678833473538839

open backfill options section by default

---

js_modules/dagit/packages/core/src/assets/LaunchAssetChoosePartitionsDialog.tsx
js_modules/dagit/packages/ui/src/components/Radio.tsx

A request from josh to rework the spacing here
Before: 
After:

[Partition Backfill Dialog] Update backfill options spacing

---

CHANGES.md

changelog 1.2.2

---

js_modules/dagit/packages/core/src/assets/LaunchAssetExecutionButton.tsx

[dagit] Fix materialize button awkward half-disabled state

---

js_modules/dagit/packages/core/src/assets/AssetPartitions.tsx

This is a small patch for an issue I noticed today where filtering the asset partitions page can result in partition keys appearing out of order.
There were two errors that caused this:
- The fast-path case was not being matched because the default "all three selected" value was in a different order than expected. (I think this broke when we added FAILED)
- The code that builds the "success + missing" or "failure + missing" set was concatenating the success keys with the missing keys. This is the fastest way to return the right set of keys, but ignores the ordering. I think the best way to do this and preserve ordering is to walk the keys array exactly once. Alternatively we could create ranges for the missing segments and run them through the same logic we already have, but it's not …

[dagit] Preserve key order when filtering on the asset partitions page

---

CHANGES.md

[dagit] A few additional changelog entries

---

python_modules/dagster-test/dagster_test/toys/basic_assets.py
python_modules/dagster-test/dagster_test/toys/repo.py
python_modules/dagster-test/dagster_test_tests/toys_tests/test_basic_assets.py

Add a toy with a basic asset graph and a job

---

docs/content/getting-started/hello-dagster.mdx

Motivated by this slack thread: https://elementl-workspace.slack.com/archives/C03E60FPJCU/p1678726297728869

remove dagit from hello dagster page

---

.buildkite/dagster-buildkite/dagster_buildkite/python_version.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/docs.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/helm.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/test_project.py

Shift the default to align with internal repo 
bk

[buildkite] shift default python verison to 3.10

---

.buildkite/dagster-buildkite/dagster_buildkite/package_spec.py
.buildkite/dagster-buildkite/dagster_buildkite/step_builder.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/dagit_ui.py
.buildkite/dagster-buildkite/dagster_buildkite/steps/test_project.py
js_modules/dagit/tox.ini

some issues that were missed in https://github.com/dagster-io/dagster/pull/12847 
bk

fixup after 3.10 shift

---

python_modules/libraries/dagster-airflow/dagster_airflow/airflow_dag_converter.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_dagster_job_factory/test_load_dag_bag_airflow_2.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_dagster_pipeline_factory/test_load_dag_bag_airflow_2.py
python_modules/libraries/dagster-airflow/dagster_airflow_tests/test_persistent_db/test_persistent_airflow_2_db.py
python_modules/libraries/dagster-airflow/setup.py

[dagster-airflow] remove 2.5.1 constraint

---

python_modules/dagster-graphql/dagster_graphql/implementation/fetch_schedules.py
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_sensors.py
python_modules/dagster-graphql/dagster_graphql/schema/backfill.py
python_modules/dagster-graphql/dagster_graphql/schema/repository_origin.py
python_modules/dagster-graphql/dagster_graphql/schema/solids.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/repo.py
python_modules/dagster/dagster/_cli/job.py
python_modules/dagster/dagster/_cli/workspace/cli_target.py
python_modules/dagster/dagster/_core/definitions/metadata/__init__.py
python_modules/dagster/dagster/_core/origin.py
python_modules/dagster/dagster/_core/workspace/context.py
python_modules/dagster/dagster_tests/api_tests/utils.py
python_modules/dagster/dagster_tests/cli_tests/snapshots/snap_test_config_scaffolder.py
python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py
python_modules/dagster/dagster_tests/daemon_tests/test_queued_run_coordinator_daemon.py
python_modules/dagster/dagster_tests/scheduler_tests/test_scheduler_run.py
python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py

Assorted typing updates for workspace code, CLI, and some graphql. Almost all static changes, but I introduced runtime checks in a few cases where it was clear the immediately following code would fail if the check was not satisfied (e.g. attempting to access an attribute on null).
Internal companion PR: https://github.com/dagster-io/internal/pull/5219

[typing/runtime] workspace

---

python_modules/libraries/dagster-pandas/dagster_pandas/data_frame.py
python_modules/libraries/dagster-pandas/dagster_pandas_tests/test_pandas_dataframe_metadata.py

Closes #6957 
[Test](https://github.com/dagster-io/dagster/blob/de568cb387e61d3f513579fe9ee13670e86c2329/python_modules/libraries/dagster-pandas/dagster_pandas_tests/test_pandas_dataframe_metadata.py)

[dagster-pandas] create a metadata schema table function

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/snapshots/snap_test_assets.py

Accidentally deleted snapshots in https://github.com/dagster-io/dagster/commit/4f0acacc13be1015b20af28ad0fe740203dd1e3e

Add back snapshots

---

python_modules/dagster/dagster/_core/execution/plan/handle.py
python_modules/dagster/dagster/_core/execution/plan/plan.py
python_modules/dagster/dagster/_core/execution/plan/step.py

- Rename `{Unresolved,ResolvedFromDynamic}StepHandle.solid_handle` -> `node_handle`
BK

[refactor] (Unresolved,ResolvedFromDynamic)StepHandle.solid_handle -> node_handle

---

python_modules/dagster/dagster/_utils/caching_instance_queryer.py
python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/test_asset_reconciliation_sensor.py

Test failed before, now it passes

[asset-reconciliation] Fix bug when source assets are present

---

python_modules/dagster/dagster/_core/definitions/assets.py

fix _infer_keys_by_output_names error message

---

docs/content/concepts/assets/multi-assets.mdx
docs/content/concepts/assets/software-defined-assets.mdx
examples/docs_snippets/docs_snippets/concepts/assets/conditional_materialization.py
examples/docs_snippets/docs_snippets/concepts/assets/multi_asset_conditional_materialization.py
examples/docs_snippets/docs_snippets_tests/concepts_tests/assets_tests/test_conditional_materialization.py
examples/docs_snippets/docs_snippets_tests/concepts_tests/assets_tests/test_multi_asset_conditional_materialization.py

Also adds imports and small editorial changes to the single asset conditional materialization section, for consistency.

add docs example for multi-asset conditional materialization

---

python_modules/dagster-test/dagster_test/toys/cross_repo_assets.py
python_modules/dagster-test/dagster_test/toys/repo.py

1. make the names more clear
2. remove usage of AssetGroup API

tweaks to cross-repo-assets toy

---

docs/content/concepts/partitions-schedules-sensors/asset-sensors.mdx
examples/docs_snippets/docs_snippets/concepts/partitions_schedules_sensors/sensors/asset_sensors.py
examples/docs_snippets/docs_snippets_tests/concepts_tests/partitions_schedules_sensors_tests/test_asset_sensors.py

We're missing some docs on how to unit test asset sensors.
BK

asset sensor test docs

---

CHANGES.md

1.2.3 changelog

---

examples/tutorial_dbt_dagster/tutorial_template/jaffle_shop/config/profiles.yml

This PR removes finished code from a file in the dbt tutorial template. Reported in #13079 
👀

[docs] - Remove finished code from dbt tutorial template

---

python_modules/dagster/dagster/_core/definitions/assets.py

Fixes https://github.com/dagster-io/dagster/issues/11808

make AssetsDefinition.to_source_assets public

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/snapshots/snap_test_assets.py

fix missing snapshots

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/snapshots/snap_test_assets.py

fix missing snapshots (again)

---

python_modules/dagster-test/dagster_test/toys/asset_reconciliation/eager_reconciliation.py
python_modules/dagster-test/dagster_test_tests/toys_tests/asset_reconciliation_tests/test_eager_reconciliation.py

add toy for eager asset reconciliation

---

.github/workflows/build-storybook.yml

Deploy storybook to prod when landing UI changes to master.  As is, storybook is a couple days stale.
Inspection, check that UI changes redeploy storybook.

deploy storybook to prod when landing pushes on master

---

python_modules/dagster/dagster/_core/execution/asset_backfill.py
python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py

Summary:
By caching the externalpipeline and externalexecutionplan when they are identical, we can greatly reduce the amount of back and forth that we have to do with the gRPC server. When I run a 2500-run backill of hourly_partitioned_asset, this moves it from 5000 gRPC calls to 2.
Test Plan: Run the above backfill locally

Greatly reduce the number of gRPC calls when doing large asset backfills

---

python_modules/dagster/dagster/_core/run_coordinator/base.py
python_modules/dagster/dagster/_core/run_coordinator/default_run_coordinator.py
python_modules/dagster/dagster/_core/run_coordinator/queued_run_coordinator.py
python_modules/dagster/dagster/_daemon/run_coordinator/queued_run_coordinator_daemon.py
python_modules/dagster/dagster/_utils/tags.py

refactor: add types to run coordinator

---

.github/workflows/build-docs.yml

per https://elementl-workspace.slack.com/archives/C04UBSGDL82/p1680040606700359, it seems like content changes (in https://github.com/dagster-io/dagster/tree/master/docs/content) weren't triggering docs build.

Deploy Docs actions to also trigger on content changes

---

python_modules/dagster/dagster/_serdes/serdes.py
python_modules/dagster/dagster_tests/general_tests/test_serdes.py

Add `field_serializers` functionality to serdes.
This allows custom field serializer logic to be scoped to a single field. The primary motivation for this is to allow serialization of a `metadata` dict as a list of metadata_entries and vice versa-- see upstack: https://github.com/dagster-io/dagster/pull/12770

Add serdes field_serializers

---

docs/content/concepts/partitions-schedules-sensors/partitions.mdx
python_modules/dagster/dagster/_core/definitions/multi_dimensional_partitions.py

no longer mark MultiPartitionsDefinition experimental

---

js_modules/dagit/packages/core/src/graphql/schema.graphql
js_modules/dagit/packages/core/src/graphql/types.ts
js_modules/dagit/packages/core/src/resources/ResourceRoot.tsx
js_modules/dagit/packages/core/src/resources/types/ResourceRoot.types.ts
python_modules/dagster-graphql/dagster_graphql/implementation/fetch_resources.py
python_modules/dagster-graphql/dagster_graphql/schema/external.py
python_modules/dagster-graphql/dagster_graphql/schema/resources.py

Displays nested resources in the Resources UI in a new panel above the config entries.

[2/n][resources ui] Display nested resources in UI

---

CHANGES.md

1.2.4 changelog

---

js_modules/dagit/packages/core/src/resources/ResourceRoot.tsx
js_modules/dagit/packages/core/src/resources/ResourceTabs.tsx
js_modules/dagit/packages/core/src/resources/types/ResourceRoot.types.ts

Lists and links to assets that depend on resources in the resource's page in the Dagster UI.
tested locally

[6/n][resources ui] Highlight assets which use resources in resources UI

---

.github/workflows/build-docs.yml

We weren't pushing production builds of master for the docs site.
Inspection

build prod docs on lands to master

---

CHANGES.md

Test Plan: View preview in github

Fix changes.md markdown

---

js_modules/dagit/packages/core/src/ui/Filters/__tests__/useStaticSetFilter.test.tsx
js_modules/dagit/packages/core/src/ui/Filters/useStaticSetFilter.tsx

The idea is to make the filter state semi-controlled so that callers of the API can act as the source of truth.
jest

[Filtering] useSetFilter: Allow changing initialState arg to force state change.

---

python_modules/dagster/dagster/_core/definitions/time_window_partition_mapping.py

use DagsterError for time window partition mapping offset error

---

python_modules/dagster/dagster/_core/definitions/asset_selection.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_asset_selection.py

Fixes https://github.com/dagster-io/dagster/issues/13249

fix asset selection coercion for multi-assets

---

python_modules/dagster/dagster/_core/definitions/asset_reconciliation_sensor.py

Improving performance for the case that you have a mapping from [lots of partitions] -> [unpartitioned].
Previously, if you were turning on a sensor for the first time, and there was a large set of materialized partitions upstream of an unpartitioned asset, we would call `get_children_partitions` once for each of those materialized partitions. This could be multiple thousands of times, which would time out the sensor.
Now, we group all the newly-materialized partitions into a PartitionsSubset, making it a lot cheaper to compute the downstream partitions subset in the common case (IdentityPartitionMapping), and also skipping the mapping entirely for AllPartitionMapping.

[asset-reconciliation][perf] improve perf on all partition mapping

---

python_modules/dagster/dagster/_core/definitions/partition.py
python_modules/dagster/dagster/_core/definitions/time_window_partitions.py
python_modules/dagster/dagster_tests/definitions_tests/test_time_window_partitions.py

Discovered this through https://github.com/dagster-io/dagster/issues/13216

properly error on exotic cron-schedules with hourly offsets

---

python_modules/dagster/dagster/_core/definitions/asset_graph.py
python_modules/dagster/dagster/_core/definitions/asset_graph_subset.py
python_modules/dagster/dagster/_core/definitions/external_asset_graph.py
python_modules/dagster/dagster/_core/execution/asset_backfill.py
python_modules/dagster/dagster/_scheduler/stale.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_external_asset_graph.py

Fixes https://github.com/dagster-io/dagster/issues/13174
Successfully ran a cross-repo backfill on a test code location with two repos. Before the change, I hit the `StopIteration` error mentioned in the bug report.

fix ExternalAssetGraph.get_job_names

---

js_modules/dagit/packages/eslint-config/CHANGES.md
js_modules/dagit/packages/eslint-config/package.json
js_modules/dagit/yarn.lock

Bumping the package so that we can use it elsewhere that we now have TS 5+.
Buildkite

[eslint-config] Update for v1.0.11

---

python_modules/dagster/dagster/_core/definitions/data_version.py

remove _extract_event_data_from_entry in data_version.py

---

examples/assets_pandas_type_metadata/setup.py

Require pandas<2 for integration libs (followup)

---

docs/content/tutorial/building-an-asset-graph.mdx

Adding link to pipeline scheduling page in tutorial

[DOC] Add link to next tutorial section

---

python_modules/dagster/dagster/_grpc/impl.py

Replace `DagsterInstance` assignments in grpc impl with use as a context manager. This improves performance over relying on garbage collection, per @gibsondan (see https://github.com/dagster-io/dagster/pull/13145/files#r1155100378)
BK

Replace instance assignments with context managers in _grpc.impl

---

docs/sphinx/_ext/autodoc_dagster.py

Adds the other configurable resource base class to sphinx autodoc

[sphinx] autodoc for ConfigurableResourceFactory

---

js_modules/dagit/packages/core/src/search/SearchResults.tsx
js_modules/dagit/packages/core/src/search/types.ts
js_modules/dagit/packages/core/src/search/types/useRepoSearch.types.ts
js_modules/dagit/packages/core/src/search/useRepoSearch.tsx

Adds resources in Dagit's search results, if the flag is enabled:

[pythonic resources][dagit] Display resources in search

---

python_modules/dagster/dagster/_api/snapshot_execution_plan.py
python_modules/dagster/dagster/_core/host_representation/origin.py
python_modules/dagster/dagster/_grpc/types.py
python_modules/dagster/dagster_tests/api_tests/api_tests_repo.py
python_modules/dagster/dagster_tests/api_tests/test_api_launch_run.py
python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_execution_plan.py
python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_partition.py
python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_pipeline.py
python_modules/dagster/dagster_tests/api_tests/test_api_snapshot_repository.py
python_modules/dagster/dagster_tests/api_tests/utils.py

Convert dagster_tests/api_tests fully over to job/op/graph APIs.
BK

[test-api-update] dagster/api_tests

---

python_modules/dagster/dagster/_core/definitions/external_asset_graph.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_external_asset_graph.py

The asset daemon needs this method. The sensor was using the method on the RepositoryDefinition. https://github.com/dagster-io/dagster/blob/johann/03-31-AssetGraph.get_implicit_job_name_for_assets/python_modules/dagster/dagster/_core/definitions/repository_definition/repository_definition.py#L288-L307

ExternalAssetGraph.get_implicit_job_name_for_assets

---

python_modules/dagster/dagster/_utils/schedules.py

summary:
This would have helped debug an issue much sooner earlier today.
Test Plan: BK

Add better invariant when there's an invalid cronstring

---

docs/sphinx/sections/api/apidocs/libraries/dagster-duckdb-polars.rst
python_modules/libraries/dagster-duckdb-polars/dagster_duckdb_polars/__init__.py
python_modules/libraries/dagster-duckdb-polars/dagster_duckdb_polars/duckdb_polars_type_handler.py
python_modules/libraries/dagster-duckdb-polars/dagster_duckdb_polars_tests/test_type_handler.py

Converts the Polars type handler + io manager to the new resource system

[duckdb-polars] DuckDBPolarsIOManager

---

docs/sphinx/sections/api/apidocs/libraries/dagster-duckdb-pyspark.rst
python_modules/libraries/dagster-duckdb-pyspark/dagster_duckdb_pyspark/__init__.py
python_modules/libraries/dagster-duckdb-pyspark/dagster_duckdb_pyspark/duckdb_pyspark_type_handler.py
python_modules/libraries/dagster-duckdb-pyspark/dagster_duckdb_pyspark_tests/test_type_handler.py

converts the pyspark type handler and io manager to the new resource system

[duckdb-pyspark] DuckDBPySparkIOManager

---

docs/sphinx/sections/api/apidocs/libraries/dagster-snowflake.rst
python_modules/libraries/dagster-snowflake/dagster_snowflake/__init__.py
python_modules/libraries/dagster-snowflake/dagster_snowflake/snowflake_io_manager.py

Converts the Snowflake IO manager to the pythonic resource system
unit tests

[snowflake] pythonic resources SnowflakeIOManager 

---

docs/sphinx/sections/api/apidocs/libraries/dagster-snowflake-pyspark.rst
python_modules/libraries/dagster-snowflake-pyspark/dagster_snowflake_pyspark/__init__.py
python_modules/libraries/dagster-snowflake-pyspark/dagster_snowflake_pyspark/snowflake_pyspark_type_handler.py
python_modules/libraries/dagster-snowflake-pyspark/dagster_snowflake_pyspark_tests/test_snowflake_pyspark_type_handler.py

converts the snowflake pyspark io manager to the pythonic resource system

[snowflake-pyspark] SnowflakePySparkIOManager

---

docs/sphinx/sections/api/apidocs/libraries/dagster-snowflake-pandas.rst
python_modules/libraries/dagster-snowflake-pandas/dagster_snowflake_pandas/__init__.py
python_modules/libraries/dagster-snowflake-pandas/dagster_snowflake_pandas/snowflake_pandas_type_handler.py
python_modules/libraries/dagster-snowflake-pandas/dagster_snowflake_pandas_tests/test_snowflake_pandas_type_handler.py
python_modules/libraries/dagster-snowflake/dagster_snowflake/snowflake_io_manager.py

converts the snowflake pandas io manager to the pythonic resource system

[snowflake-pandas] SnowflakePandasIOManager

---

docs/sphinx/sections/api/apidocs/libraries/dagster-gcp.rst
python_modules/libraries/dagster-gcp-pandas/dagster_gcp_pandas/bigquery/bigquery_pandas_type_handler.py
python_modules/libraries/dagster-gcp/dagster_gcp/__init__.py
python_modules/libraries/dagster-gcp/dagster_gcp/bigquery/io_manager.py
python_modules/libraries/dagster-gcp/dagster_gcp/bigquery/resources.py
python_modules/libraries/dagster-gcp/dagster_gcp/bigquery/utils.py

Converts the BigQueryIOManager to the pythonic resource system
unit tests

[dagster-gcp] python resources BigQueryIOManager

---

docs/sphinx/sections/api/apidocs/libraries/dagster-gcp-pandas.rst
python_modules/libraries/dagster-gcp-pandas/dagster_gcp_pandas/__init__.py
python_modules/libraries/dagster-gcp-pandas/dagster_gcp_pandas/bigquery/bigquery_pandas_type_handler.py
python_modules/libraries/dagster-gcp-pandas/dagster_gcp_pandas_tests/bigquery/test_type_handler.py

Converts the bigquery pandas io manager to pythonic resource system

[gcp-pandas] convert BigQueryPandasIOManager

---

CHANGES.md

changelog for 1.2.5

---

python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/storage/legacy_storage.py
python_modules/dagster/dagster/_core/storage/schedules/base.py
python_modules/dagster/dagster/_core/storage/schedules/sql_schedule_storage.py
python_modules/dagster/dagster/_utils/test/schedule_storage.py

We want to be able to quickly filter for the schedules/sensors by status.
BK - test failure is from internal compat

add core storage methods for querying instigators by status

---

CHANGES.md

1.2.6 changelog

---

python_modules/libraries/dagster-github/dagster_github/resources.py
python_modules/libraries/dagster-github/dagster_github_tests/test_resources.py

Updates `dagster-github` resource to use `ConfigurableResource`.

[dagster-github] Migrate to structured resources

---

python_modules/dagster/dagster/_core/definitions/asset_graph.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/external_asset_graph.py
python_modules/dagster/dagster/_core/host_representation/external_data.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_external_asset_graph.py

Thread materialization policies through @asset to ExternalAssetGraph

Add auto_materialize_policy to @asset

---

.buildkite/dagster-buildkite/dagster_buildkite/steps/packages.py

This is resolved as of Feb 2022: https://github.com/dbt-labs/dbt-core/issues/4562.
bk

feat(dbt): add support for python 3.10

---

docs/next/util/redirectUrls.json

Redirecting old links from the Tutorial to their new location in the guides

---

python_modules/libraries/dagster-shell/dagster_shell/solids.py

Migrates the `dagster_shell` internals to use Pythonic config.

[dagster-shell] Migrate to Pythonic config

---

python_modules/dagster/dagster/_core/definitions/asset_reconciliation_sensor.py
python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/scenarios.py
python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/test_auto_materialize_daemon.py

Test calling the existing reconciliation sensor logic on an external asset graph

Auto materialize logic on an external asset graph

---

js_modules/dagit/packages/core/src/instance/BackfillTable.tsx
js_modules/dagit/packages/core/src/instance/DaemonList.tsx
js_modules/dagit/packages/core/src/instance/backfill/BackfillPage.tsx
js_modules/dagit/packages/core/src/instigation/InstigationTick.tsx
js_modules/dagit/packages/core/src/instigation/TickHistory.tsx
js_modules/dagit/packages/core/src/instigation/Unloadable.tsx
js_modules/dagit/packages/core/src/nav/JobMetadata.tsx
js_modules/dagit/packages/core/src/nav/RepoSelector.tsx
js_modules/dagit/packages/core/src/resources/ResourceRoot.tsx
js_modules/dagit/packages/core/src/schedules/SchedulesNextTicks.tsx
js_modules/dagit/packages/core/src/sensors/EditCursorDialog.tsx
js_modules/dagit/packages/core/src/sensors/SensorDetails.tsx
js_modules/dagit/packages/core/src/workspace/RepositoryLocationsList.tsx
js_modules/dagit/packages/ui/src/components/Table.tsx

Use default font for `Table`, instead of monospace font.
Also made a couple of stylistic tweaks in a handful of places that I was testing.
View tables throughout Dagit, verify that they look correct.

[ui] Use default font for Table

---

python_modules/dagster/dagster_tests/daemon_tests/test_backfill.py
python_modules/dagster/dagster_tests/daemon_tests/test_queued_run_coordinator_daemon.py

Convert dagster_tests/daemon_tests fully over to job/op/graph APIs.
BK

[test-api-update] dagster/daemon_tests

---

python_modules/dagster-test/dagster_test/toys/data_versions.py

Adds a toy for working with data versions that should be ideal for UI experimentation.
Played with toy in dagit.

data versions toy

---

python_modules/dagster/dagster/_core/definitions/asset_graph.py

clarify asset key for asset graph errors

---

python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/system_config/objects.py
python_modules/dagster/dagster_tests/launcher_tests/test_default_run_launcher.py
python_modules/dagster/dagster_tests/launcher_tests/test_persistent_grpc_run_launcher.py

Convert dagster_tests/launcher_tests fully over to job/op/graph APIs.
BK

[test-api-update] dagster/launcher-tests

---

python_modules/dagster/dagster_tests/daemon_sensor_tests/conftest.py
python_modules/dagster/dagster_tests/daemon_sensor_tests/test_asset_sensor_run.py
python_modules/dagster/dagster_tests/daemon_sensor_tests/test_run_status_sensors.py
python_modules/dagster/dagster_tests/daemon_sensor_tests/test_sensor_run.py

Convert dagster_tests/daemon_sensor_tests fully over to job/op/graph APIs.
BK

[test-api-update] dagster/daemon_sensor_tests

---

python_modules/dagster/dagster_tests/storage_tests/test_fs_io_manager.py
python_modules/dagster/dagster_tests/storage_tests/test_io_manager.py
python_modules/dagster/dagster_tests/storage_tests/test_io_manager_composites.py
python_modules/dagster/dagster_tests/storage_tests/test_io_managers_with_graphs.py
python_modules/dagster/dagster_tests/storage_tests/test_local_instance.py
python_modules/dagster/dagster_tests/storage_tests/utils/event_log_storage.py

Convert dagster_tests/storage_tests fully over to job/op/graph APIs.
BK

[test-api-update] dagster/storage_tests

---

python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/conftest.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/repo.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/test_launching.py
python_modules/libraries/dagster-aws/dagster_aws_tests/emr_tests/test_pyspark.py
python_modules/libraries/dagster-azure/dagster_azure_tests/adls2_tests/test_adls2_file_manager.py
python_modules/libraries/dagster-celery-k8s/dagster_celery_k8s_tests/test_launcher.py
python_modules/libraries/dagster-celery/dagster_celery_tests/test_execute.py
python_modules/libraries/dagster-celery/dagster_celery_tests/test_priority.py
python_modules/libraries/dagster-celery/dagster_celery_tests/test_queues.py
python_modules/libraries/dagster-docker/dagster_docker_tests/test_docker_executor.py
python_modules/libraries/dagster-mlflow/dagster_mlflow_tests/test_hooks.py
python_modules/libraries/dagster-mlflow/dagster_mlflow_tests/test_resources.py
python_modules/libraries/dagster-msteams/dagster_msteams_tests/test_hooks.py
python_modules/libraries/dagster-pandas/dagster_pandas_tests/pandas_hello_world/test_pandas_hello_world.py
python_modules/libraries/dagster-pandas/dagster_pandas_tests/test_dagstermill_pandas_solids.py
python_modules/libraries/dagster-postgres/dagster_postgres_tests/compat_tests/test_back_compat.py
python_modules/libraries/dagster-pyspark/dagster_pyspark_tests/test_resources.py
python_modules/libraries/dagster-slack/dagster_slack_tests/test_hooks.py
python_modules/libraries/dagster-spark/dagster_spark_tests/test_ops.py
python_modules/libraries/dagstermill/dagstermill_tests/test_assets.py

Convert all integration library tests fully over to job/op/graph APIs.
BK

[test-api-update] libraries

---

integration_tests/test_suites/backcompat-test-suite/dagit_service/legacy_repo.py
integration_tests/test_suites/daemon-test-suite/repo.py
integration_tests/test_suites/daemon-test-suite/test_memory.py
integration_tests/test_suites/daemon-test-suite/test_queued.py

Convert all integration test suites fully over to job/op/graph APIs.
BK

[test-api-update] integration_tests

---

js_modules/dagit/packages/core/src/launchpad/LaunchpadSetupRoot.tsx
js_modules/dagit/packages/core/src/ticks/DryRunRequestTable.tsx

As titled
Tested this with the math sensor from the toys repo

Propagate Sensor Dry Run tags when openning in launchpad

---

python_modules/libraries/dagster-aws/dagster_aws/ecs/container_context.py
python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py
python_modules/libraries/dagster-aws/dagster_aws/ecs/tasks.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/conftest.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/test_container_context.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ecs_tests/launcher_tests/test_launching.py

Summary:
Lets you set EFS volumes and other volumes in your ECS tasks.

Add volumes and mountPoints to EcsRunLauncher and EcsContainerContext

---

python_modules/dagster/dagster/_core/telemetry.py
python_modules/dagster/dagster_tests/cli_tests/command_tests/test_telemetry.py

This adds telemetry to detect the use of the following asset features:
- Partitions
- Freshness policies
- Source assets
- Multi-dimensional partions
- Code versions
- Asset reconciliation sensors
- dbt assets
- Observable source assets

asset feature telemetry

---

python_modules/dagster/dagster/_config/pythonic_config/__init__.py
python_modules/dagster/dagster_tests/core_tests/resource_tests/test_pythonic_config_resources.py
python_modules/libraries/dagster-aws/dagster_aws/athena/__init__.py
python_modules/libraries/dagster-aws/dagster_aws/athena/resources.py
python_modules/libraries/dagster-aws/dagster_aws/ecr/__init__.py
python_modules/libraries/dagster-aws/dagster_aws/ecr/resources.py
python_modules/libraries/dagster-aws/dagster_aws/redshift/__init__.py
python_modules/libraries/dagster-aws/dagster_aws/redshift/resources.py
python_modules/libraries/dagster-aws/dagster_aws_tests/athena_tests/test_resources.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ecr_tests/test_resources.py
python_modules/libraries/dagster-aws/dagster_aws_tests/redshift_tests/test_resources.py

Migrates Athena, ECR, & Redshift resources to Pythonic resource system.
New unit tests

[1/n][dagster-aws] Begin migrating dagster-aws to new resource system

---

python_modules/dagster/dagster_tests/asset_defs_tests/test_source_asset_observation_job.py

Fix bad import of ConfigurableResource

---

python_modules/dagster/dagster_tests/core_tests/pythonic_config_tests/test_errors.py
python_modules/dagster/dagster_tests/core_tests/pythonic_config_tests/test_pythonic_config_types.py
python_modules/libraries/dagster-aws/dagster_aws/secretsmanager/__init__.py
python_modules/libraries/dagster-aws/dagster_aws/secretsmanager/resources.py
python_modules/libraries/dagster-aws/dagster_aws/ssm/__init__.py
python_modules/libraries/dagster-aws/dagster_aws/ssm/resources.py
python_modules/libraries/dagster-aws/dagster_aws/utils/__init__.py
python_modules/libraries/dagster-aws/dagster_aws_tests/secretsmanager_tests/test_secrets.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ssm_tests/test_resources.py

Migrates SecretsManager & SSM resources to Pythonic resource system.
Existing + new unit tests

[2/n][dagster-aws] Migrate SecretsManager, SSM resources to new APIs

---

python_modules/libraries/dagster-github/dagster_github/__init__.py
python_modules/libraries/dagster-github/dagster_github/resources.py
python_modules/libraries/dagster-github/dagster_github_tests/test_resources.py

Per internal discussion we are moving aware from ConfigurableResourceFactory for our integrations. This moves Github.
BK

 Convert github to use non-factory resource

---

python_modules/libraries/dagster-msteams/dagster_msteams/__init__.py
python_modules/libraries/dagster-msteams/dagster_msteams/resources.py
python_modules/libraries/dagster-msteams/dagster_msteams_tests/test_resources.py

Migrate `dagster-msteams` resource to use `ConfigurableResource`.
New unit test.

[dagster-msteams] Migrate to Configurable Resource

---

python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_daemon_health.py
python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/instance/config.py
python_modules/dagster/dagster/_core/instance/ref.py
python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster/_daemon/controller.py
python_modules/dagster/dagster_tests/core_tests/instance_tests/test_instance.py
python_modules/dagster/dagster_tests/daemon_tests/test_dagster_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/asset_reconciliation_scenario.py

Make the asset daemon start up by default in `dagster dev` and `dagster-daemon`

Enable the asset daemon

---

js_modules/dagit/packages/core/src/workspace/VirtualizedAssetRow.tsx

Resolves #13115.
Load app, view Asset catalog.

[ui] Repository -> Code location in Asset table

---

python_modules/libraries/dagster-ge/dagster_ge/factory.py
python_modules/libraries/dagster-ge/dagster_ge_tests/great_expectations_v3/great_expectations.yml
python_modules/libraries/dagster-ge/dagster_ge_tests/snapshots/snap_test_basic_integ.py

the status-quo resource isn't exported. so this would be more of an internal change.

[pythonic resources] dagster-ge GEContextResource

---

python_modules/dagster/dagster/_core/definitions/multi_asset_sensor_definition.py

Get all materializations using `materialization_records_for_key`

Multi asset sensor : optional limit for materialization_records_for_key

---

js_modules/dagit/packages/core/src/graphql/schema.graphql
js_modules/dagit/packages/core/src/graphql/types.ts
python_modules/dagster-graphql/dagster_graphql/schema/instance.py
python_modules/dagster-graphql/dagster_graphql/schema/roots/mutation.py
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_auto_materialize_paused.py
python_modules/dagster/dagster/_daemon/asset_daemon.py

Backend for auto materialize pause button

gql for pausing asset daemon

---

docs/content/concepts/assets/asset-materializations.mdx
docs/content/concepts/assets/asset-observations.mdx
docs/content/concepts/assets/software-defined-assets.mdx
docs/content/concepts/ops-jobs-graphs/op-events.mdx
docs/content/integrations/pandas.mdx

remove MetadataEntry, which is deprecated, from docs content

---

python_modules/dagster/dagster_tests/storage_tests/test_upath_io_manager.py

Fix pyright error. Blames to #13563
BK and watch pyright

Fix pyright error

---

name_conflicts.py
python_modules/dagster/dagster/_core/definitions/assets.py
python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
python_modules/dagster/dagster/_core/definitions/source_asset.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_assets_job.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_decorators.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_source_asset.py

Similar to https://github.com/dagster-io/dagster/pull/13556 for SourceAsset, multi_asset, and AssetsDefinition
BK

SourceAsset, multi_asset, and AssetsDefinition take arbitary dictionary for resource_defs

---

python_modules/libraries/dagster-airbyte/dagster_airbyte/resources.py

Removes the need to rely on private attributes by instead factoring out mutable state in its own object and using @cached_method to cache that state object.
BK

Add AirbyteResourceState to avoid reliance on leading underscore hack in MakeConfigCacheable

---

js_modules/dagit/packages/core/src/asset-graph/SidebarAssetInfo.tsx

[fix] fix ts error in master

---

python_modules/dagster/dagster/_utils/caching_instance_queryer.py

Handle case with no asset observations

---

python_modules/libraries/dagster-aws/dagster_aws/athena/resources.py
python_modules/libraries/dagster-aws/dagster_aws/ecr/resources.py
python_modules/libraries/dagster-aws/dagster_aws/redshift/resources.py
python_modules/libraries/dagster-aws/dagster_aws/s3/io_manager.py
python_modules/libraries/dagster-aws/dagster_aws/s3/resources.py
python_modules/libraries/dagster-aws/dagster_aws/secretsmanager/resources.py
python_modules/libraries/dagster-aws/dagster_aws/ssm/resources.py
python_modules/libraries/dagster-aws/dagster_aws_tests/athena_tests/test_resources.py
python_modules/libraries/dagster-aws/dagster_aws_tests/ecr_tests/test_resources.py
python_modules/libraries/dagster-aws/dagster_aws_tests/redshift_tests/test_resources.py
python_modules/libraries/dagster-aws/dagster_aws_tests/s3_tests/test_io_manager.py
python_modules/libraries/dagster-aws/dagster_aws_tests/s3_tests/test_s3_file_manager.py

some apis predate monday's convo

[pythonic resources] dagster-aws update to get_client + docstring

---

docs/content/guides/dagster/transitioning-data-pipelines-from-development-to-production.mdx
examples/development_to_production/development_to_production/__init__.py
examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/repository/repository_v1.py
examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/repository/repository_v2.py
examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/repository/repository_v3.py

Moves over the resources used in the development-to-production example

[examples] Migrate development-to-production example to use Pythonic IO manager

---

examples/quickstart_gcp/README.md

Missed updating a section in the readme for `quickstart_gcp`

[quickstart_gcp] update readme

---

python_modules/dagster-test/dagster_test/toys/partitioned_assets/__init__.py

add hourly-to-daily partitioned toy to toys code location

---

js_modules/dagit/packages/core/src/app/AppProvider.tsx
js_modules/dagit/packages/core/src/assets/__fixtures__/LaunchAssetExecutionButton.mocks.ts
js_modules/dagit/packages/core/src/graphql/graphql.tsx
js_modules/dagit/packages/core/src/workspace/VirtualizedRepoAssetTable.tsx
js_modules/dagit/packages/core/src/workspace/buildRepoAddress.ts
js_modules/dagit/packages/ui/src/components/Table.tsx

Clean up my todos that I've left behind. Some of them just need to be matched up with an internal branch.
Buildkite

[ui] Clean up my todos

---

python_modules/dagster/dagster/_core/definitions/asset_reconciliation_sensor.py
python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/partition_scenarios.py

Unifies asset reconciliation behavior for multipartitioned and time-partitioned assets, limiting the multipartitions that can be reconciled to the same time window range (1 day).
For multipartitioned assets that do not contain a time dimension, follows existing behavior and reconciles all partitions.
Resolves https://github.com/dagster-io/dagster/issues/13382

[asset-reconciliation] Limit time-dimension multipartitions that can be reconciled with the sensor

---

examples/assets_pandas_pyspark/pyproject.toml

assets_pandas_pyspark: fix module name in pyproject

---

python_modules/dagster/dagster/_core/instance/__init__.py
python_modules/dagster/dagster/_core/instance/config.py
python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/test_asset_daemon.py

```yaml
auto_materialize:
run_tags:
foo: bar
```
Not in love with this api, but we need something. Context: https://elementl-workspace.slack.com/archives/C04UD72HHQX/p1681223846986739

Auto materialize run tags

---

python_modules/dagster/dagster/_core/storage/fs_io_manager.py
python_modules/libraries/dagster-aws/dagster_aws/s3/io_manager.py
python_modules/libraries/dagster-azure/dagster_azure/adls2/io_manager.py
python_modules/libraries/dagster-gcp/dagster_gcp/gcs/io_manager.py

repository -> Definitions in IO manager docstrings

---

docs/content/_navigation.json
docs/content/concepts.mdx
docs/content/concepts/assets/asset-auto-execution.mdx
examples/docs_snippets/docs_snippets/concepts/assets/auto_materialize_eager.py
examples/docs_snippets/docs_snippets/concepts/assets/auto_materialize_lazy.py
examples/docs_snippets/docs_snippets/concepts/assets/auto_materialize_lazy_transitive.py
examples/docs_snippets/docs_snippets/concepts/assets/auto_materialize_multiple.py
examples/docs_snippets/docs_snippets/concepts/assets/auto_materialize_observable_source_asset.py
examples/docs_snippets/docs_snippets/concepts/assets/auto_materialize_time_partitions.py
examples/docs_snippets/docs_snippets_tests/concepts_tests/assets_tests/test_auto_materialize.py
python_modules/dagster/dagster/_core/definitions/auto_materialize_policy.py

There's a lot more we can put in here, but I think this is a good start.

concept page for auto asset-materialization

---

docs/content/concepts/partitions-schedules-sensors/asset-sensors.mdx
examples/docs_snippets/docs_snippets/concepts/partitions_schedules_sensors/sensors/asset_sensors.py
python_modules/dagster/dagster/_core/definitions/data_time.py
python_modules/dagster/dagster/_core/definitions/freshness_policy.py
python_modules/dagster/dagster/_core/definitions/freshness_policy_sensor_definition.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_freshness_policy.py
python_modules/dagster/dagster_tests/definitions_tests/test_freshness_policy_sensor.py
python_modules/dagster/dagster_tests/definitions_tests/test_sensor_invocation.py
python_modules/libraries/dagster-slack/dagster_slack/sensors.py
python_modules/libraries/dagster-slack/dagster_slack_tests/test_sensors.py

This is a breaking change to an experimental API.

late -> overdue on FreshnessPolicy and FreshnessPolicySensorContext

---

docs/content/deployment/run-monitoring.mdx
examples/docs_snippets/docs_snippets/deploying/monitoring_daemon/run_timeouts.py
examples/docs_snippets/docs_snippets_tests/deploying_tests/test_monitoring_daemon_examples.py
python_modules/dagster/dagster/__init__.py

Add docs for run timeouts, add MAX_RUNTIME_SECONDS_TAG to top-level API

---

docs/content/concepts/assets/asset-materializations.mdx
examples/docs_snippets/docs_snippets/concepts/assets/materialization_ops.py

[docs] [resources-config-overhaul] - Update Asset Materializations Concept page

---

docs/content/concepts/assets/asset-observations.mdx
examples/docs_snippets/docs_snippets/concepts/assets/observations.py

[docs] [resources-config-overhaul] - Update Asset Observations Concept page

---

docs/content/concepts/assets/software-defined-assets.mdx
examples/docs_snippets/docs_snippets/concepts/assets/asset_config.py
examples/docs_snippets/docs_snippets/concepts/assets/asset_testing.py
examples/docs_snippets/docs_snippets/concepts/assets/asset_w_context.py
examples/docs_snippets/docs_snippets_tests/concepts_tests/assets_tests/test_asset_config.py
examples/docs_snippets/docs_snippets_tests/concepts_tests/assets_tests/test_asset_testing.py

Some small updates / tweaks to the assets page to take into account Pythonic config + resources.
A few new unit tests.

[docs][pythonic config] Update assets page

---

python_modules/libraries/dagster-ge/dagster_ge/factory.py
python_modules/libraries/dagster-ge/dagster_ge_tests/test_resources.py

hit a bug while migrating the ge example: https://github.com/dagster-io/dagster/pull/13610
this needs to be picked onto the release branch

[pythonic resources] dagster-ge fix

---

docs/content/integrations/airbyte.mdx
examples/docs_snippets/docs_snippets/integrations/airbyte/airbyte.py
examples/docs_snippets/docs_snippets_tests/integrations_tests/test_airbyte.py
examples/docs_snippets/setup.py
examples/docs_snippets/tox.ini

Updates the Airbyte integration tutorial to use the Pythonic airbyte resource

[pythonic resources] Update Airbyte integration docs

---

python_modules/dagster/dagster/_core/definitions/run_config.py
python_modules/dagster/dagster_tests/core_tests/pythonic_config_tests/test_basic_pythonic_config.py

[pythonic config] Allow setting 'execution' config on RunConfig object

---

docs/content/integrations/fivetran.mdx
examples/docs_snippets/docs_snippets/integrations/fivetran/fivetran.py
python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py

Updates the Fivetran integration tutorial to use the Pythonic Fivetran resource

[docs][pythonic config] Update Fivetran integration docs

---

js_modules/dagit/packages/core/src/instance/DeploymentStatusProvider.tsx
js_modules/dagit/packages/core/src/nav/DeploymentStatusIcon.tsx
python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_auto_materialize_paused.py
python_modules/dagster/dagster/_daemon/asset_daemon.py
python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/test_asset_daemon.py

Pause auto materializing by default

---

python_modules/dagster/dagster_tests/core_tests/execution_tests/test_asset_backfill.py

I wrote this test to try to replicate some behavior I observed while testing backfills manually. It ended up passing - i.e. not replicating the behavior I had observed, but it still seemed worthwhile to include.
The backfill test harness didn't have the ability to set a `current_time` or target a particular partition subset, which was needed for this test, so I added it.

add test for hourly-to-daily backfill

---

docs/content/concepts/assets/asset-auto-execution.mdx

update auto-materialize docs with new daemon default

---

docs/content/concepts/assets/asset-auto-execution.mdx
python_modules/dagster/dagster/_core/definitions/auto_materialize_policy.py
python_modules/dagster/dagster_tests/asset_defs_tests/test_external_asset_graph.py
python_modules/dagster/dagster_tests/definitions_tests/asset_reconciliation_tests/auto_materialize_policy_scenarios.py

hide time_window_partition_scope

---

python_modules/dagster/dagster/_core/definitions/run_request.py
python_modules/dagster/dagster_tests/definitions_tests/test_sensor_invocation.py

This callsite doesn't take `RunConfig` yet

[pythonic config] Accept RunConfig in RunRequest constructor

---

docs/content/guides/dagster/branch_deployments.mdx
docs/content/guides/dagster/transitioning-data-pipelines-from-development-to-production.mdx
examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/assets.py
examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/branch_deployments/clone_and_drop_db.py
examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/branch_deployments/repository_v1.py
examples/docs_snippets/docs_snippets/guides/dagster/development_to_production/branch_deployments/repository_v2.py

Updates the branch deployment guide to use the new Snowflake IO manager + Pythonic config system. Does not update the Snowflake resource since that's still pending.

[docs][pythonic resources] Update branch deployment guide

---

docs/content/integrations/bigquery/reference.mdx
docs/content/integrations/bigquery/using-bigquery-with-dagster.mdx
examples/docs_snippets/docs_snippets/integrations/bigquery/basic_example.py
examples/docs_snippets/docs_snippets/integrations/bigquery/config_auth.py
examples/docs_snippets/docs_snippets/integrations/bigquery/configuration.py
examples/docs_snippets/docs_snippets/integrations/bigquery/dataset.py
examples/docs_snippets/docs_snippets/integrations/bigquery/downstream_columns.py
examples/docs_snippets/docs_snippets/integrations/bigquery/full_example.py
examples/docs_snippets/docs_snippets/integrations/bigquery/multi_partition.py
examples/docs_snippets/docs_snippets/integrations/bigquery/multiple_io_managers.py
examples/docs_snippets/docs_snippets/integrations/bigquery/pandas_and_pyspark.py
examples/docs_snippets/docs_snippets/integrations/bigquery/pyspark_configuration.py
examples/docs_snippets/docs_snippets/integrations/bigquery/pyspark_with_spark_resource.py
examples/docs_snippets/docs_snippets/integrations/bigquery/pyspark_with_spark_session.py
examples/docs_snippets/docs_snippets/integrations/bigquery/resource.py
examples/docs_snippets/docs_snippets/integrations/bigquery/static_partition.py

Converts the BigQuery guide to use the pydantic bigquery io managers

[docs] bigqueryy tutorial and guide to new resource system

---

docs/content/integrations/snowflake/reference.mdx
docs/content/integrations/snowflake/using-snowflake-with-dagster.mdx
examples/docs_snippets/docs_snippets/integrations/snowflake/basic_example.py
examples/docs_snippets/docs_snippets/integrations/snowflake/configuration.py
examples/docs_snippets/docs_snippets/integrations/snowflake/downstream_columns.py
examples/docs_snippets/docs_snippets/integrations/snowflake/full_example.py
examples/docs_snippets/docs_snippets/integrations/snowflake/multi_partition.py
examples/docs_snippets/docs_snippets/integrations/snowflake/multiple_io_managers.py
examples/docs_snippets/docs_snippets/integrations/snowflake/pandas_and_pyspark.py
examples/docs_snippets/docs_snippets/integrations/snowflake/private_key_auth.py
examples/docs_snippets/docs_snippets/integrations/snowflake/pyspark_configuration.py
examples/docs_snippets/docs_snippets/integrations/snowflake/pyspark_with_spark_resource.py
examples/docs_snippets/docs_snippets/integrations/snowflake/pyspark_with_spark_session.py
examples/docs_snippets/docs_snippets/integrations/snowflake/resource.py
examples/docs_snippets/docs_snippets/integrations/snowflake/schema.py
examples/docs_snippets/docs_snippets/integrations/snowflake/static_partition.py
examples/docs_snippets/tox.ini

Updates the snowflake guide to use pydantic io managers

[docs] Update snowflake tutorial and guide to use pydantic io managers

---

python_modules/dagster/dagster_tests/daemon_tests/test_monitoring_daemon.py

Run monitoring tests are failing on windows due to an obscure error, disabling until I get the chance to investigate in more detail

Skip monitoring tests on windows

---

docs/content/concepts/partitions-schedules-sensors/asset-sensors.mdx
examples/docs_snippets/docs_snippets/concepts/partitions_schedules_sensors/sensors/asset_sensors.py

Very brief update to asset sensor page to use new config

[pythonic config] Update asset sensor page

---

python_modules/dagster/dagster/_core/definitions/multi_asset_sensor_definition.py

Improves performance for the `latest_materialization_records_by_key` method on the multi asset sensor context.
Now that the asset key table stores the latest materialization event log record, we can just query from the asset key table instead of querying the event logs table for each selected asset. This PR adds this update.

Multi asset sensor `latest_materialization_records_by_key` perf improvement
